# total parametres in each

In [15]:

from pathlib import Path
import subprocess
import sys

base = Path("/home/cse-sdpl/Downloads")

experiments = {
    "E0": base / "CMX_Original",
    "E1": base / "CMX_E1",
    "E2": base / "CMX_E2",
    "E3": base / "CMX_E3",
    "E4": base / "CMX_E4",
    "E5": base / "CMX_E5",
}

count_code = r'''
from config import config as C
from models.builder import EncoderDecoder

model = EncoderDecoder(cfg=C)

total = sum(p.numel() for p in model.parameters())
trainable = sum(
    p.numel() for p in model.parameters()
    if p.requires_grad
)

print(f"Backbone: {C.backbone}")
print(f"Total: {total}")
print(f"Trainable: {trainable}")
'''

results = []

for exp, project in experiments.items():
    print(f"\n{'=' * 45}")
    print(f"Experiment: {exp}")
    print(f"Project: {project}")

    if not project.is_dir():
        print("STATUS: Project directory not found")
        continue

    try:
        run = subprocess.run(
            [sys.executable, "-c", count_code],
            cwd=str(project),
            capture_output=True,
            text=True,
            timeout=180,
        )

        if run.returncode != 0:
            print("STATUS: ERROR")
            print(run.stderr[-2500:])
            continue

        print(run.stdout.strip())

        values = {}
        for line in run.stdout.splitlines():
            if ":" in line:
                key, value = line.split(":", 1)
                values[key.strip()] = value.strip()

        total = int(values["Total"])
        trainable = int(values["Trainable"])

        results.append({
            "Experiment": exp,
            "Backbone": values["Backbone"],
            "Total parameters": f"{total:,}",
            "Total (M)": f"{total / 1e6:.3f}",
            "Trainable parameters": f"{trainable:,}",
            "Status": "OK",
        })

    except Exception as e:
        print(f"STATUS: ERROR - {e}")

import pandas as pd

results_df = pd.DataFrame(results)
display(results_df)

=============================================
Experiment: E0
Project: /home/cse-sdpl/Downloads/CMX_Original
Backbone: mit_b2
Total: 66565521
Trainable: 66565521

=============================================
Experiment: E1
Project: /home/cse-sdpl/Downloads/CMX_E1
Backbone: mit_b2_e1
Total: 66565521
Trainable: 66565521

=============================================
Experiment: E2
Project: /home/cse-sdpl/Downloads/CMX_E2
Backbone: mit_b2_e2
Total: 66565529
Trainable: 66565529

=============================================
Experiment: E3
Project: /home/cse-sdpl/Downloads/CMX_E3
Backbone: mit_b2_e3
Total: 66662169
Trainable: 66662169

=============================================
Experiment: E4
Project: /home/cse-sdpl/Downloads/CMX_E4
Backbone: mit_b2_e4
Total: 66758817
Trainable: 66758817

=============================================
Experiment: E5
Project: /home/cse-sdpl/Downloads/CMX_E5
Backbone: mit_b2_e5
Total: 66758817
Trainable: 66758817

  Experiment   Backbone Total parameters Total (M) Trainable parameters Status
0         E0     mit_b2       66,565,521    66.566           66,565,521     OK
1         E1  mit_b2_e1       66,565,521    66.566           66,565,521     OK
2         E2  mit_b2_e2       66,565,529    66.566           66,565,529     OK
3         E3  mit_b2_e3       66,662,169    66.662           66,662,169     OK
4         E4  mit_b2_e4       66,758,817    66.759           66,758,817     OK
5         E5  mit_b2_e5       66,758,817    66.759           66,758,817     OK

In [1]:

from pathlib import Path

# Update this if your experiments are stored elsewhere
BASE = Path("/home/cse-sdpl/Downloads")

experiments = ["CMX_Original", "CMX_E1", "CMX_E2", "CMX_E3", "CMX_E4"]

for exp in experiments:
    root = BASE / exp
    print(f"\n{'='*50}\n{exp}")
    print("Folder exists:", root.exists())

    if root.exists():
        checkpoints = list(root.rglob("epoch-100.pth"))
        for ckpt in checkpoints:
            print(f"Checkpoint: {ckpt}")
            print(f"Size: {ckpt.stat().st_size / (1024**3):.2f} GB")

        if not checkpoints:
            print("epoch-100.pth not found; checking other checkpoint files...")
            for ckpt in list(root.rglob("*.pth"))[:10]:
                print(ckpt)

==================================================
CMX_Original
Folder exists: True
Checkpoint: /home/cse-sdpl/Downloads/CMX_Original/log_TDD_mit_b2/checkpoint/epoch-100.pth
Size: 0.74 GB

==================================================
CMX_E1
Folder exists: True
Checkpoint: /home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth
Size: 0.67 GB

==================================================
CMX_E2
Folder exists: True
Checkpoint: /home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth
Size: 0.67 GB
Checkpoint: /home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2_e2/checkpoint/epoch-100.pth
Size: 0.74 GB

==================================================
CMX_E3
Folder exists: True
Checkpoint: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth
Size: 0.67 GB
Checkpoint: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e2/checkpoint/epoch-100.pth
Size: 0.74 GB
Checkpoint: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e3/checkpoint/epoch-100.pth
Size: 0.75 GB

==================================================
CMX_E4
Folder exists: True
Checkpoint: /home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2_e4/checkpoint/epoch-100.pth
Size: 0.75 GB

In [2]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_Original")

!python eval.py -e 100 -d 0 --split test -p predictions_E0_test

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:32:59 using devices 0
16 02:32:59 Using backbone: Segformer-B2
16 02:33:00 Using MLP Decoder
16 02:33:00 Load Model: /home/cse-sdpl/Downloads/CMX_Original/log_TDD_mit_b2/checkpoint/epoch-100.pth
16 02:33:04 Load model, Time usage:
	IO: 4.423196315765381, initialize parameters: 0.04419755935668945
16 02:33:04 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@8.862] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:33:06 Save the image 01402D.png
  0%|                                          | 1/393 [00:01<10:50,  1.66s/it]16 02:33:06 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:01<05:07,  1.27it/s]16 02:33:06 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:02<03:18,  1.97it/s]16 02:33:06 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:02<02:27,  2.64it/s]16 02:33:06 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:02<01:59,  3.25it/s]16 02:33:07 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:02<01:42,  3.77it/s]16 02:33:07 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:02<01:31,  4.22it/s]16 02:33:07 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:02<01:23,  4.62it/s]16 02:33:07 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:03<01:19,  4.84it/s]16 02:33:07 Save the image 01411D.png
  3%|█                                        | 10/393 [00:03<01:16,  5.03it/s]16 02:33:07 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:03<01:13,  5.21it/s]16 02:33:08 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:03<01:12,  5.26it/s]16 02:33:08 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:03<01:10,  5.37it/s]16 02:33:08 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:03<01:09,  5.42it/s]16 02:33:08 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:04<01:09,  5.46it/s]16 02:33:08 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:04<01:09,  5.43it/s]16 02:33:09 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:04<01:08,  5.47it/s]16 02:33:09 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:04<01:08,  5.47it/s]16 02:33:09 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:04<01:08,  5.45it/s]16 02:33:09 Save the image 01421D.png
  5%|██                                       | 20/393 [00:05<01:07,  5.51it/s]16 02:33:09 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:05<01:07,  5.50it/s]16 02:33:09 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:05<01:08,  5.44it/s]16 02:33:10 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:05<01:07,  5.47it/s]16 02:33:10 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:05<01:07,  5.47it/s]16 02:33:10 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:06<01:07,  5.45it/s]16 02:33:10 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:06<01:07,  5.44it/s]16 02:33:10 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:06<01:07,  5.44it/s]16 02:33:11 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:06<01:06,  5.45it/s]16 02:33:11 Save the image 01430D.png
  7%|███                                      | 29/393 [00:06<01:06,  5.48it/s]16 02:33:11 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:06<01:01,  5.91it/s]16 02:33:11 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:07<01:03,  5.70it/s]16 02:33:11 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:07<01:03,  5.66it/s]16 02:33:11 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:07<01:05,  5.54it/s]16 02:33:12 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:07<01:04,  5.54it/s]16 02:33:12 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:07<01:05,  5.50it/s]16 02:33:12 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:07<01:04,  5.54it/s]16 02:33:12 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:08<01:03,  5.60it/s]16 02:33:12 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:08<01:04,  5.51it/s]16 02:33:13 Save the image 01440D.png
 10%|████                                     | 39/393 [00:08<01:05,  5.43it/s]16 02:33:13 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:08<01:04,  5.45it/s]16 02:33:13 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:08<01:05,  5.39it/s]16 02:33:13 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:09<01:03,  5.51it/s]16 02:33:13 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:09<01:03,  5.54it/s]16 02:33:13 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:09<01:03,  5.52it/s]16 02:33:14 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:09<01:03,  5.49it/s]16 02:33:14 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:09<01:03,  5.50it/s]16 02:33:14 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:09<01:02,  5.55it/s]16 02:33:14 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:10<01:02,  5.51it/s]16 02:33:14 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:10<01:01,  5.55it/s]16 02:33:15 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:10<01:02,  5.53it/s]16 02:33:15 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:10<01:01,  5.53it/s]16 02:33:15 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:10<01:01,  5.51it/s]16 02:33:15 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:11<01:02,  5.46it/s]16 02:33:15 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:11<01:02,  5.42it/s]16 02:33:15 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:11<01:02,  5.40it/s]16 02:33:16 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:11<01:02,  5.38it/s]16 02:33:16 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:11<01:02,  5.36it/s]16 02:33:16 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:11<01:01,  5.45it/s]16 02:33:16 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:12<00:58,  5.76it/s]16 02:33:16 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:12<00:59,  5.62it/s]16 02:33:17 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:12<00:59,  5.60it/s]16 02:33:17 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:12<00:59,  5.61it/s]16 02:33:17 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:12<00:59,  5.51it/s]16 02:33:17 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:13<00:59,  5.50it/s]16 02:33:17 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:13<00:59,  5.48it/s]16 02:33:17 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:13<00:59,  5.45it/s]16 02:33:18 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:13<00:59,  5.44it/s]16 02:33:18 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:13<00:59,  5.46it/s]16 02:33:18 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:13<00:59,  5.40it/s]16 02:33:18 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:14<00:59,  5.43it/s]16 02:33:18 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:14<00:59,  5.43it/s]16 02:33:19 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:14<00:59,  5.41it/s]16 02:33:19 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:14<00:58,  5.43it/s]16 02:33:19 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:14<00:58,  5.48it/s]16 02:33:19 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:15<00:58,  5.44it/s]16 02:33:19 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:15<00:58,  5.45it/s]16 02:33:19 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:15<00:58,  5.41it/s]16 02:33:20 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:15<00:58,  5.39it/s]16 02:33:20 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:15<00:57,  5.42it/s]16 02:33:20 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:16<00:58,  5.37it/s]16 02:33:20 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:16<00:54,  5.72it/s]16 02:33:20 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:16<00:55,  5.64it/s]16 02:33:21 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:16<00:55,  5.63it/s]16 02:33:21 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:16<00:55,  5.60it/s]16 02:33:21 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:16<00:55,  5.55it/s]16 02:33:21 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:17<00:55,  5.58it/s]16 02:33:21 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:17<00:54,  5.61it/s]16 02:33:21 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:17<00:54,  5.55it/s]16 02:33:22 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:17<00:55,  5.51it/s]16 02:33:22 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:17<00:54,  5.53it/s]16 02:33:22 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:17<00:54,  5.53it/s]16 02:33:22 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:18<00:55,  5.45it/s]16 02:33:22 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:18<00:54,  5.50it/s]16 02:33:23 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:18<00:55,  5.43it/s]16 02:33:23 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:18<00:55,  5.41it/s]16 02:33:23 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:18<00:54,  5.42it/s]16 02:33:23 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:19<00:54,  5.42it/s]16 02:33:23 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:19<00:54,  5.43it/s]16 02:33:23 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:19<00:54,  5.39it/s]16 02:33:24 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:19<00:54,  5.37it/s]16 02:33:24 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:19<00:54,  5.37it/s]16 02:33:24 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:20<00:54,  5.36it/s]16 02:33:24 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:20<00:53,  5.44it/s]16 02:33:24 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:20<00:53,  5.44it/s]16 02:33:25 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:20<00:52,  5.51it/s]16 02:33:25 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:20<00:52,  5.44it/s]16 02:33:25 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:20<00:52,  5.41it/s]16 02:33:25 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:21<00:52,  5.40it/s]16 02:33:25 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:21<00:52,  5.42it/s]16 02:33:25 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:21<00:50,  5.64it/s]16 02:33:26 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:21<00:50,  5.63it/s]16 02:33:26 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:21<00:50,  5.56it/s]16 02:33:26 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:22<00:50,  5.55it/s]16 02:33:26 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:22<00:50,  5.48it/s]16 02:33:26 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:22<00:50,  5.48it/s]16 02:33:27 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:22<00:50,  5.45it/s]16 02:33:27 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:22<00:50,  5.43it/s]16 02:33:27 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:22<00:50,  5.41it/s]16 02:33:27 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:23<00:50,  5.39it/s]16 02:33:27 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:23<00:49,  5.47it/s]16 02:33:28 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:23<00:50,  5.43it/s]16 02:33:28 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:23<00:50,  5.37it/s]16 02:33:28 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:23<00:50,  5.37it/s]16 02:33:28 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:24<00:49,  5.41it/s]16 02:33:28 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:24<00:49,  5.39it/s]16 02:33:28 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:24<00:49,  5.41it/s]16 02:33:29 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:24<00:49,  5.41it/s]16 02:33:29 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:24<00:49,  5.38it/s]16 02:33:29 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:24<00:48,  5.40it/s]16 02:33:29 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:25<00:48,  5.38it/s]16 02:33:29 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:25<00:48,  5.39it/s]16 02:33:30 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:25<00:45,  5.70it/s]16 02:33:30 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:25<00:46,  5.57it/s]16 02:33:30 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:25<00:46,  5.55it/s]16 02:33:30 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:26<00:46,  5.50it/s]16 02:33:30 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:26<00:47,  5.43it/s]16 02:33:30 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:26<00:46,  5.45it/s]16 02:33:31 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:26<00:46,  5.49it/s]16 02:33:31 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:26<00:46,  5.46it/s]16 02:33:31 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:26<00:46,  5.45it/s]16 02:33:31 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:27<00:45,  5.48it/s]16 02:33:31 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:27<00:45,  5.47it/s]16 02:33:32 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:27<00:45,  5.45it/s]16 02:33:32 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:27<00:45,  5.49it/s]16 02:33:32 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:27<00:45,  5.48it/s]16 02:33:32 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:28<00:45,  5.48it/s]16 02:33:32 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:28<00:44,  5.48it/s]16 02:33:32 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:28<00:44,  5.53it/s]16 02:33:33 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:28<00:44,  5.47it/s]16 02:33:33 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:28<00:44,  5.45it/s]16 02:33:33 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:28<00:44,  5.43it/s]16 02:33:33 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:29<00:44,  5.40it/s]16 02:33:33 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:29<00:44,  5.41it/s]16 02:33:34 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:29<00:44,  5.38it/s]16 02:33:34 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:29<00:44,  5.36it/s]16 02:33:34 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:29<00:43,  5.40it/s]16 02:33:34 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:30<00:43,  5.39it/s]16 02:33:34 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:30<00:43,  5.36it/s]16 02:33:34 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:30<00:43,  5.44it/s]16 02:33:35 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:30<00:42,  5.45it/s]16 02:33:35 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:30<00:40,  5.76it/s]16 02:33:35 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:30<00:41,  5.63it/s]16 02:33:35 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:31<00:41,  5.60it/s]16 02:33:35 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:31<00:41,  5.56it/s]16 02:33:36 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:31<00:41,  5.52it/s]16 02:33:36 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:31<00:41,  5.45it/s]16 02:33:36 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:31<00:41,  5.45it/s]16 02:33:36 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:32<00:41,  5.43it/s]16 02:33:36 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:32<00:41,  5.42it/s]16 02:33:36 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:32<00:40,  5.45it/s]16 02:33:37 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:32<00:40,  5.49it/s]16 02:33:37 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:32<00:40,  5.47it/s]16 02:33:37 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:33<00:40,  5.49it/s]16 02:33:37 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:33<00:39,  5.48it/s]16 02:33:37 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:33<00:39,  5.49it/s]16 02:33:38 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:33<00:39,  5.48it/s]16 02:33:38 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:33<00:39,  5.48it/s]16 02:33:38 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:33<00:38,  5.52it/s]16 02:33:38 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:34<00:38,  5.49it/s]16 02:33:38 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:34<00:38,  5.48it/s]16 02:33:38 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:34<00:38,  5.47it/s]16 02:33:39 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:34<00:38,  5.47it/s]16 02:33:39 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:34<00:38,  5.46it/s]16 02:33:39 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:35<00:38,  5.46it/s]16 02:33:39 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:35<00:37,  5.49it/s]16 02:33:39 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:35<00:37,  5.47it/s]16 02:33:40 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:35<00:37,  5.45it/s]16 02:33:40 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:35<00:37,  5.45it/s]16 02:33:40 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:35<00:37,  5.47it/s]16 02:33:40 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:36<00:34,  5.82it/s]16 02:33:40 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:36<00:35,  5.72it/s]16 02:33:40 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:36<00:35,  5.66it/s]16 02:33:41 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:36<00:35,  5.59it/s]16 02:33:41 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:36<00:36,  5.51it/s]16 02:33:41 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:36<00:35,  5.59it/s]16 02:33:41 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:37<00:35,  5.61it/s]16 02:33:41 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:37<00:35,  5.58it/s]16 02:33:42 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:37<00:35,  5.51it/s]16 02:33:42 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:37<00:35,  5.53it/s]16 02:33:42 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:37<00:35,  5.50it/s]16 02:33:42 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:38<00:35,  5.48it/s]16 02:33:42 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:38<00:34,  5.48it/s]16 02:33:42 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:38<00:34,  5.46it/s]16 02:33:43 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:38<00:34,  5.42it/s]16 02:33:43 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:38<00:34,  5.41it/s]16 02:33:43 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:39<00:34,  5.39it/s]16 02:33:43 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:39<00:34,  5.42it/s]16 02:33:43 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:39<00:34,  5.41it/s]16 02:33:44 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:39<00:33,  5.45it/s]16 02:33:44 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:39<00:33,  5.47it/s]16 02:33:44 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:39<00:33,  5.49it/s]16 02:33:44 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:40<00:31,  5.67it/s]16 02:33:44 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:40<00:32,  5.59it/s]16 02:33:44 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:40<00:32,  5.57it/s]16 02:33:45 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:40<00:32,  5.55it/s]16 02:33:45 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:40<00:31,  5.55it/s]16 02:33:45 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:40<00:31,  5.58it/s]16 02:33:45 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:41<00:30,  5.66it/s]16 02:33:45 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:41<00:30,  5.67it/s]16 02:33:46 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:41<00:30,  5.59it/s]16 02:33:46 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:41<00:31,  5.54it/s]16 02:33:46 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:41<00:30,  5.55it/s]16 02:33:46 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:42<00:30,  5.50it/s]16 02:33:46 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:42<00:30,  5.51it/s]16 02:33:46 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:42<00:30,  5.46it/s]16 02:33:47 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:42<00:30,  5.46it/s]16 02:33:47 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:42<00:30,  5.45it/s]16 02:33:47 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:42<00:30,  5.44it/s]16 02:33:47 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:43<00:29,  5.47it/s]16 02:33:47 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:43<00:30,  5.43it/s]16 02:33:48 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:43<00:29,  5.42it/s]16 02:33:48 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:43<00:29,  5.41it/s]16 02:33:48 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:43<00:29,  5.45it/s]16 02:33:48 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:44<00:27,  5.79it/s]16 02:33:48 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:44<00:27,  5.70it/s]16 02:33:48 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:44<00:27,  5.65it/s]16 02:33:49 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:44<00:27,  5.62it/s]16 02:33:49 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:44<00:27,  5.58it/s]16 02:33:49 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:44<00:27,  5.59it/s]16 02:33:49 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:45<00:27,  5.61it/s]16 02:33:49 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:45<00:27,  5.60it/s]16 02:33:50 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:45<00:27,  5.56it/s]16 02:33:50 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:45<00:27,  5.55it/s]16 02:33:50 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:45<00:26,  5.57it/s]16 02:33:50 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:46<00:26,  5.53it/s]16 02:33:50 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:46<00:26,  5.50it/s]16 02:33:50 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:46<00:26,  5.48it/s]16 02:33:51 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:46<00:26,  5.49it/s]16 02:33:51 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:46<00:26,  5.49it/s]16 02:33:51 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:46<00:26,  5.49it/s]16 02:33:51 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:47<00:25,  5.51it/s]16 02:33:51 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:47<00:25,  5.48it/s]16 02:33:52 Save the image 01236N.png

 64%|█████████████████████████▊              | 253/393 [00:47<00:25,  5.46it/s]16 02:33:52 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:47<00:25,  5.45it/s]16 02:33:52 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:47<00:24,  5.55it/s]16 02:33:52 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:47<00:23,  5.89it/s]16 02:33:52 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:48<00:23,  5.79it/s]16 02:33:52 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:48<00:23,  5.76it/s]16 02:33:53 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:48<00:23,  5.69it/s]16 02:33:53 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:48<00:23,  5.58it/s]16 02:33:53 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:48<00:23,  5.67it/s]16 02:33:53 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:49<00:23,  5.66it/s]16 02:33:53 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:49<00:23,  5.59it/s]16 02:33:53 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:49<00:23,  5.55it/s]16 02:33:54 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:49<00:23,  5.54it/s]16 02:33:54 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:49<00:22,  5.55it/s]16 02:33:54 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:49<00:22,  5.50it/s]16 02:33:54 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:50<00:22,  5.46it/s]16 02:33:54 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:50<00:22,  5.49it/s]16 02:33:55 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:50<00:22,  5.52it/s]16 02:33:55 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:50<00:20,  5.88it/s]16 02:33:55 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:50<00:21,  5.73it/s]16 02:33:55 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:51<00:21,  5.65it/s]16 02:33:55 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:51<00:20,  5.70it/s]16 02:33:55 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:51<00:20,  5.65it/s]16 02:33:56 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:51<00:20,  5.71it/s]16 02:33:56 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:51<00:20,  5.73it/s]16 02:33:56 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:51<00:20,  5.65it/s]16 02:33:56 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:52<00:20,  5.59it/s]16 02:33:56 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:52<00:20,  5.51it/s]16 02:33:56 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:52<00:20,  5.56it/s]16 02:33:57 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:52<00:20,  5.50it/s]16 02:33:57 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:52<00:19,  5.56it/s]16 02:33:57 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:53<00:19,  5.59it/s]16 02:33:57 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:53<00:19,  5.57it/s]16 02:33:57 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:53<00:19,  5.54it/s]16 02:33:58 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:53<00:19,  5.55it/s]16 02:33:58 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:53<00:18,  5.57it/s]16 02:33:58 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:53<00:19,  5.45it/s]16 02:33:58 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:54<00:18,  5.46it/s]16 02:33:58 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:54<00:18,  5.49it/s]16 02:33:58 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:54<00:18,  5.48it/s]16 02:33:59 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:54<00:17,  5.74it/s]16 02:33:59 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:54<00:17,  5.62it/s]16 02:33:59 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:54<00:17,  5.56it/s]16 02:33:59 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:55<00:17,  5.45it/s]16 02:33:59 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:55<00:17,  5.48it/s]16 02:34:00 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:55<00:17,  5.48it/s]16 02:34:00 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:55<00:17,  5.52it/s]16 02:34:00 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:55<00:16,  5.61it/s]16 02:34:00 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:56<00:16,  5.51it/s]16 02:34:00 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:56<00:16,  5.51it/s]16 02:34:00 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:56<00:16,  5.48it/s]16 02:34:01 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:56<00:16,  5.46it/s]16 02:34:01 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:56<00:16,  5.48it/s]16 02:34:01 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:56<00:15,  5.46it/s]16 02:34:01 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:57<00:15,  5.44it/s]16 02:34:01 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:57<00:15,  5.42it/s]16 02:34:02 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:57<00:15,  5.44it/s]16 02:34:02 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:57<00:15,  5.42it/s]16 02:34:02 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:57<00:15,  5.42it/s]16 02:34:02 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:58<00:15,  5.39it/s]16 02:34:02 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:58<00:14,  5.42it/s]16 02:34:03 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:58<00:14,  5.35it/s]16 02:34:03 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:58<00:14,  5.42it/s]16 02:34:03 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:58<00:14,  5.41it/s]16 02:34:03 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:59<00:13,  5.45it/s]16 02:34:03 Save the image 01301N.png

 81%|████████████████████████████████▎       | 318/393 [00:59<00:13,  5.41it/s]16 02:34:03 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:59<00:13,  5.42it/s]16 02:34:04 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:59<00:13,  5.40it/s]16 02:34:04 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:59<00:13,  5.42it/s]16 02:34:04 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:59<00:12,  5.75it/s]16 02:34:04 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [01:00<00:12,  5.63it/s]16 02:34:04 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [01:00<00:12,  5.60it/s]16 02:34:04 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [01:00<00:12,  5.57it/s]16 02:34:05 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [01:00<00:12,  5.53it/s]16 02:34:05 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [01:00<00:11,  5.56it/s]16 02:34:05 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [01:01<00:11,  5.50it/s]16 02:34:05 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [01:01<00:11,  5.46it/s]16 02:34:05 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [01:01<00:11,  5.44it/s]16 02:34:06 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [01:01<00:11,  5.46it/s]16 02:34:06 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [01:01<00:11,  5.50it/s]16 02:34:06 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [01:01<00:10,  5.47it/s]16 02:34:06 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [01:02<00:10,  5.50it/s]16 02:34:06 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [01:02<00:10,  5.51it/s]16 02:34:06 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [01:02<00:10,  5.52it/s]16 02:34:07 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [01:02<00:10,  5.52it/s]16 02:34:07 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [01:02<00:09,  5.54it/s]16 02:34:07 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [01:03<00:09,  5.57it/s]16 02:34:07 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [01:03<00:09,  5.52it/s]16 02:34:07 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [01:03<00:09,  5.51it/s]16 02:34:08 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [01:03<00:09,  5.50it/s]16 02:34:08 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [01:03<00:09,  5.52it/s]16 02:34:08 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [01:03<00:08,  5.83it/s]16 02:34:08 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [01:04<00:08,  5.68it/s]16 02:34:08 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [01:04<00:08,  5.70it/s]16 02:34:08 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [01:04<00:08,  5.68it/s]16 02:34:09 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [01:04<00:08,  5.54it/s]16 02:34:09 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [01:04<00:07,  5.57it/s]16 02:34:09 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [01:04<00:07,  5.58it/s]16 02:34:09 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [01:05<00:07,  5.51it/s]16 02:34:09 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [01:05<00:07,  5.47it/s]16 02:34:10 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [01:05<00:07,  5.44it/s]16 02:34:10 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [01:05<00:07,  5.40it/s]16 02:34:10 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [01:05<00:06,  5.43it/s]16 02:34:10 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [01:06<00:06,  5.42it/s]16 02:34:10 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [01:06<00:06,  5.41it/s]16 02:34:10 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [01:06<00:06,  5.42it/s]16 02:34:11 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [01:06<00:06,  5.42it/s]16 02:34:11 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [01:06<00:06,  5.41it/s]16 02:34:11 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [01:07<00:05,  5.46it/s]16 02:34:11 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [01:07<00:05,  5.43it/s]16 02:34:11 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [01:07<00:05,  5.43it/s]16 02:34:12 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [01:07<00:05,  5.42it/s]16 02:34:12 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [01:07<00:05,  5.41it/s]16 02:34:12 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [01:07<00:04,  5.74it/s]16 02:34:12 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [01:08<00:04,  5.60it/s]16 02:34:12 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [01:08<00:04,  5.58it/s]16 02:34:12 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [01:08<00:04,  5.54it/s]16 02:34:13 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [01:08<00:04,  5.51it/s]16 02:34:13 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [01:08<00:03,  5.54it/s]16 02:34:13 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [01:09<00:03,  5.50it/s]16 02:34:13 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [01:09<00:03,  5.52it/s]16 02:34:13 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [01:09<00:03,  5.52it/s]16 02:34:14 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [01:09<00:03,  5.52it/s]16 02:34:14 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [01:09<00:03,  5.53it/s]16 02:34:14 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [01:09<00:02,  5.46it/s]16 02:34:14 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [01:10<00:02,  5.47it/s]16 02:34:14 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [01:10<00:02,  5.48it/s]16 02:34:14 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [01:10<00:02,  5.45it/s]16 02:34:15 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [01:10<00:02,  5.81it/s]16 02:34:15 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [01:10<00:01,  5.60it/s]16 02:34:15 Save the image 01366N.png

 97%|██████████████████████████████████████▉ | 383/393 [01:10<00:01,  5.65it/s]16 02:34:15 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [01:11<00:01,  6.34it/s]16 02:34:15 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [01:11<00:01,  6.93it/s]16 02:34:15 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [01:11<00:01,  6.99it/s]16 02:34:15 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [01:11<00:00,  7.41it/s]16 02:34:16 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [01:11<00:00,  7.81it/s]16 02:34:16 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [01:11<00:00,  8.15it/s]16 02:34:16 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [01:11<00:00,  8.25it/s]16 02:34:16 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [01:11<00:00,  8.36it/s]16 02:34:16 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [01:12<00:00,  8.46it/s]16 02:34:16 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [01:12<00:00,  5.45it/s]
1 unlabeled	98.303%
2 car   	89.098%
3 person	75.033%
4 bike  	64.802%
5 curve 	47.548%
6 car_stop	33.639%
7 guardrail	9.273%
8 color_cone	51.472%
9 bump  	61.139%
----------     mean_IoU	58.923%	freq_IoU	96.777%	mean_pixel_acc	70.841%	pixel_acc	98.227%
16 02:34:16 Evaluation Elapsed Time: 72.15s

In [3]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_Original")

!python eval.py -e 100 -d 0 --split val -p predictions_E0_val

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:34:58 using devices 0
16 02:34:58 Using backbone: Segformer-B2
16 02:34:59 Using MLP Decoder
16 02:35:00 Load Model: /home/cse-sdpl/Downloads/CMX_Original/log_TDD_mit_b2/checkpoint/epoch-100.pth
16 02:35:04 Load model, Time usage:
	IO: 3.993239402770996, initialize parameters: 0.043116092681884766
16 02:35:04 GPU 0 handle 392 data.
  0%|                                                  | 0/392 [00:00<?, ?it/s][ WARN:0@9.322] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:35:05 Save the image 00498D.png
  0%|                                          | 1/392 [00:01<09:47,  1.50s/it]16 02:35:05 Save the image 00499D.png
  1%|▏                                         | 2/392 [00:01<04:42,  1.38it/s]16 02:35:06 Save the image 00500D.png
  1%|▎                                         | 3/392 [00:01<03:00,  2.16it/s]16 02:35:06 Save the image 00501D.png
  1%|▍                                         | 4/392 [00:02<02:17,  2.83it/s]16 02:35:06 Save the image 00502D.png
  1%|▌                                         | 5/392 [00:02<01:52,  3.44it/s]16 02:35:06 Save the image 00503D.png
  2%|▋                                         | 6/392 [00:02<01:38,  3.93it/s]16 02:35:06 Save the image 00504D.png
  2%|▊                                         | 7/392 [00:02<01:28,  4.33it/s]16 02:35:07 Save the image 00505D.png
  2%|▊                                         | 8/392 [00:02<01:22,  4.67it/s]16 02:35:07 Save the image 00506D.png
  2%|▉                                         | 9/392 [00:02<01:18,  4.89it/s]16 02:35:07 Save the image 00507D.png
  3%|█                                        | 10/392 [00:03<01:16,  5.00it/s]16 02:35:07 Save the image 00508D.png
  3%|█▏                                       | 11/392 [00:03<01:13,  5.16it/s]16 02:35:07 Save the image 00509D.png
  3%|█▎                                       | 12/392 [00:03<01:12,  5.27it/s]16 02:35:07 Save the image 00510D.png
  3%|█▎                                       | 13/392 [00:03<01:11,  5.33it/s]16 02:35:08 Save the image 00511D.png
  4%|█▍                                       | 14/392 [00:03<01:10,  5.36it/s]16 02:35:08 Save the image 00512D.png
  4%|█▌                                       | 15/392 [00:04<01:09,  5.43it/s]16 02:35:08 Save the image 00513D.png
  4%|█▋                                       | 16/392 [00:04<01:09,  5.42it/s]16 02:35:08 Save the image 00514D.png
  4%|█▊                                       | 17/392 [00:04<01:08,  5.44it/s]16 02:35:08 Save the image 00515D.png
  5%|█▉                                       | 18/392 [00:04<01:08,  5.45it/s]16 02:35:09 Save the image 00516D.png
  5%|█▉                                       | 19/392 [00:04<01:08,  5.47it/s]16 02:35:09 Save the image 00517D.png
  5%|██                                       | 20/392 [00:04<01:07,  5.52it/s]16 02:35:09 Save the image 00518D.png
  5%|██▏                                      | 21/392 [00:05<01:06,  5.54it/s]16 02:35:09 Save the image 00519D.png
  6%|██▎                                      | 22/392 [00:05<01:07,  5.47it/s]16 02:35:09 Save the image 00520D.png
  6%|██▍                                      | 23/392 [00:05<01:07,  5.43it/s]16 02:35:09 Save the image 00521D.png
  6%|██▌                                      | 24/392 [00:05<01:07,  5.45it/s]16 02:35:10 Save the image 00522D.png
  6%|██▌                                      | 25/392 [00:05<01:03,  5.80it/s]16 02:35:10 Save the image 00523D.png
  7%|██▋                                      | 26/392 [00:05<01:04,  5.68it/s]16 02:35:10 Save the image 00524D.png
  7%|██▊                                      | 27/392 [00:06<01:04,  5.64it/s]16 02:35:10 Save the image 00525D.png
  7%|██▉                                      | 28/392 [00:06<01:04,  5.60it/s]16 02:35:10 Save the image 00526D.png
  7%|███                                      | 29/392 [00:06<01:05,  5.57it/s]16 02:35:11 Save the image 00527D.png
  8%|███▏                                     | 30/392 [00:06<01:04,  5.61it/s]16 02:35:11 Save the image 00528D.png
  8%|███▏                                     | 31/392 [00:06<01:04,  5.61it/s]16 02:35:11 Save the image 00529D.png
  8%|███▎                                     | 32/392 [00:07<01:05,  5.51it/s]16 02:35:11 Save the image 00530D.png
  8%|███▍                                     | 33/392 [00:07<01:05,  5.48it/s]16 02:35:11 Save the image 00531D.png
  9%|███▌                                     | 34/392 [00:07<01:05,  5.50it/s]16 02:35:11 Save the image 00532D.png
  9%|███▋                                     | 35/392 [00:07<01:04,  5.53it/s]16 02:35:12 Save the image 00533D.png
  9%|███▊                                     | 36/392 [00:07<01:04,  5.48it/s]16 02:35:12 Save the image 00534D.png
  9%|███▊                                     | 37/392 [00:07<01:04,  5.50it/s]16 02:35:12 Save the image 00535D.png
 10%|███▉                                     | 38/392 [00:08<01:04,  5.46it/s]16 02:35:12 Save the image 00536D.png
 10%|████                                     | 39/392 [00:08<01:04,  5.49it/s]16 02:35:12 Save the image 00537D.png
 10%|████▏                                    | 40/392 [00:08<01:04,  5.45it/s]16 02:35:13 Save the image 00538D.png
 10%|████▎                                    | 41/392 [00:08<01:04,  5.47it/s]16 02:35:13 Save the image 00539D.png
 11%|████▍                                    | 42/392 [00:08<01:03,  5.53it/s]16 02:35:13 Save the image 00540D.png
 11%|████▍                                    | 43/392 [00:09<01:03,  5.50it/s]16 02:35:13 Save the image 00541D.png
 11%|████▌                                    | 44/392 [00:09<01:03,  5.48it/s]16 02:35:13 Save the image 00542D.png
 11%|████▋                                    | 45/392 [00:09<01:03,  5.46it/s]16 02:35:13 Save the image 00543D.png
 12%|████▊                                    | 46/392 [00:09<01:03,  5.44it/s]16 02:35:14 Save the image 00544D.png
 12%|████▉                                    | 47/392 [00:09<01:03,  5.42it/s]16 02:35:14 Save the image 00545D.png
 12%|█████                                    | 48/392 [00:10<01:02,  5.50it/s]16 02:35:14 Save the image 00546D.png
 12%|█████▏                                   | 49/392 [00:10<01:02,  5.46it/s]16 02:35:14 Save the image 00547D.png
 13%|█████▏                                   | 50/392 [00:10<01:02,  5.44it/s]16 02:35:14 Save the image 00548D.png
 13%|█████▎                                   | 51/392 [00:10<01:02,  5.43it/s]16 02:35:15 Save the image 00549D.png
 13%|█████▍                                   | 52/392 [00:10<01:02,  5.44it/s]16 02:35:15 Save the image 00550D.png
 14%|█████▌                                   | 53/392 [00:10<01:02,  5.40it/s]16 02:35:15 Save the image 00551D.png
 14%|█████▋                                   | 54/392 [00:11<00:58,  5.73it/s]16 02:35:15 Save the image 00552D.png
 14%|█████▊                                   | 55/392 [00:11<01:00,  5.60it/s]16 02:35:15 Save the image 00553D.png
 14%|█████▊                                   | 56/392 [00:11<00:59,  5.60it/s]16 02:35:15 Save the image 00554D.png
 15%|█████▉                                   | 57/392 [00:11<00:59,  5.65it/s]16 02:35:16 Save the image 00555D.png

 15%|██████                                   | 58/392 [00:11<01:00,  5.55it/s]16 02:35:16 Save the image 00556D.png
 15%|██████▏                                  | 59/392 [00:11<01:00,  5.53it/s]16 02:35:16 Save the image 00557D.png
 15%|██████▎                                  | 60/392 [00:12<01:00,  5.51it/s]16 02:35:16 Save the image 00558D.png
 16%|██████▍                                  | 61/392 [00:12<01:00,  5.44it/s]16 02:35:16 Save the image 00559D.png
 16%|██████▍                                  | 62/392 [00:12<01:01,  5.40it/s]16 02:35:17 Save the image 00560D.png
 16%|██████▌                                  | 63/392 [00:12<01:00,  5.41it/s]16 02:35:17 Save the image 00561D.png
 16%|██████▋                                  | 64/392 [00:12<01:00,  5.43it/s]16 02:35:17 Save the image 00562D.png
 17%|██████▊                                  | 65/392 [00:13<01:00,  5.37it/s]16 02:35:17 Save the image 00563D.png
 17%|██████▉                                  | 66/392 [00:13<01:00,  5.37it/s]16 02:35:17 Save the image 00564D.png
 17%|███████                                  | 67/392 [00:13<01:00,  5.41it/s]16 02:35:17 Save the image 00565D.png
 17%|███████                                  | 68/392 [00:13<00:59,  5.44it/s]16 02:35:18 Save the image 00566D.png
 18%|███████▏                                 | 69/392 [00:13<00:59,  5.47it/s]16 02:35:18 Save the image 00567D.png
 18%|███████▎                                 | 70/392 [00:14<00:59,  5.46it/s]16 02:35:18 Save the image 00568D.png
 18%|███████▍                                 | 71/392 [00:14<00:58,  5.49it/s]16 02:35:18 Save the image 00569D.png
 18%|███████▌                                 | 72/392 [00:14<00:59,  5.38it/s]16 02:35:18 Save the image 00570D.png
 19%|███████▋                                 | 73/392 [00:14<00:59,  5.39it/s]16 02:35:19 Save the image 00571D.png
 19%|███████▋                                 | 74/392 [00:14<00:58,  5.41it/s]16 02:35:19 Save the image 00572D.png
 19%|███████▊                                 | 75/392 [00:14<00:58,  5.42it/s]16 02:35:19 Save the image 00573D.png
 19%|███████▉                                 | 76/392 [00:15<00:58,  5.42it/s]16 02:35:19 Save the image 00574D.png
 20%|████████                                 | 77/392 [00:15<00:57,  5.44it/s]16 02:35:19 Save the image 00575D.png
 20%|████████▏                                | 78/392 [00:15<00:57,  5.46it/s]16 02:35:19 Save the image 00576D.png
 20%|████████▎                                | 79/392 [00:15<00:57,  5.44it/s]16 02:35:20 Save the image 00577D.png
 20%|████████▎                                | 80/392 [00:15<00:57,  5.43it/s]16 02:35:20 Save the image 00578D.png
 21%|████████▍                                | 81/392 [00:16<00:57,  5.44it/s]16 02:35:20 Save the image 00579D.png
 21%|████████▌                                | 82/392 [00:16<00:56,  5.46it/s]16 02:35:20 Save the image 00580D.png
 21%|████████▋                                | 83/392 [00:16<00:56,  5.42it/s]16 02:35:20 Save the image 00581D.png
 21%|████████▊                                | 84/392 [00:16<00:56,  5.49it/s]16 02:35:21 Save the image 00582D.png
 22%|████████▉                                | 85/392 [00:16<00:55,  5.51it/s]16 02:35:21 Save the image 00583D.png
 22%|████████▉                                | 86/392 [00:16<00:55,  5.46it/s]16 02:35:21 Save the image 00584D.png
 22%|█████████                                | 87/392 [00:17<00:55,  5.46it/s]16 02:35:21 Save the image 00585D.png
 22%|█████████▏                               | 88/392 [00:17<00:55,  5.48it/s]16 02:35:21 Save the image 00586D.png
 23%|█████████▎                               | 89/392 [00:17<00:55,  5.49it/s]16 02:35:21 Save the image 00587D.png
 23%|█████████▍                               | 90/392 [00:17<00:52,  5.79it/s]16 02:35:22 Save the image 00588D.png
 23%|█████████▌                               | 91/392 [00:17<00:52,  5.69it/s]16 02:35:22 Save the image 00589D.png
 23%|█████████▌                               | 92/392 [00:18<00:53,  5.64it/s]16 02:35:22 Save the image 00590D.png
 24%|█████████▋                               | 93/392 [00:18<00:53,  5.57it/s]16 02:35:22 Save the image 00591D.png
 24%|█████████▊                               | 94/392 [00:18<00:53,  5.52it/s]16 02:35:22 Save the image 00592D.png
 24%|█████████▉                               | 95/392 [00:18<00:53,  5.55it/s]16 02:35:23 Save the image 00593D.png
 24%|██████████                               | 96/392 [00:18<00:52,  5.59it/s]16 02:35:23 Save the image 00594D.png
 25%|██████████▏                              | 97/392 [00:18<00:53,  5.56it/s]16 02:35:23 Save the image 00595D.png
 25%|██████████▎                              | 98/392 [00:19<00:53,  5.51it/s]16 02:35:23 Save the image 00596D.png
 25%|██████████▎                              | 99/392 [00:19<00:53,  5.51it/s]16 02:35:23 Save the image 00597D.png
 26%|██████████▏                             | 100/392 [00:19<00:52,  5.53it/s]16 02:35:23 Save the image 00598D.png
 26%|██████████▎                             | 101/392 [00:19<00:53,  5.49it/s]16 02:35:24 Save the image 00599D.png
 26%|██████████▍                             | 102/392 [00:19<00:52,  5.53it/s]16 02:35:24 Save the image 00600D.png
 26%|██████████▌                             | 103/392 [00:20<00:52,  5.55it/s]16 02:35:24 Save the image 00601D.png
 27%|██████████▌                             | 104/392 [00:20<00:52,  5.50it/s]16 02:35:24 Save the image 00602D.png
 27%|██████████▋                             | 105/392 [00:20<00:52,  5.48it/s]16 02:35:24 Save the image 00603D.png
 27%|██████████▊                             | 106/392 [00:20<00:52,  5.50it/s]16 02:35:25 Save the image 00604D.png
 27%|██████████▉                             | 107/392 [00:20<00:51,  5.52it/s]16 02:35:25 Save the image 00605D.png
 28%|███████████                             | 108/392 [00:20<00:51,  5.48it/s]16 02:35:25 Save the image 00606D.png
 28%|███████████                             | 109/392 [00:21<00:51,  5.53it/s]16 02:35:25 Save the image 00607D.png
 28%|███████████▏                            | 110/392 [00:21<00:50,  5.54it/s]16 02:35:25 Save the image 00608D.png
 28%|███████████▎                            | 111/392 [00:21<00:51,  5.46it/s]16 02:35:25 Save the image 00609D.png
 29%|███████████▍                            | 112/392 [00:21<00:50,  5.50it/s]16 02:35:26 Save the image 00610D.png
 29%|███████████▌                            | 113/392 [00:21<00:50,  5.50it/s]16 02:35:26 Save the image 00611D.png
 29%|███████████▋                            | 114/392 [00:22<00:50,  5.52it/s]16 02:35:26 Save the image 00612D.png
 29%|███████████▋                            | 115/392 [00:22<00:50,  5.49it/s]16 02:35:26 Save the image 00613D.png
 30%|███████████▊                            | 116/392 [00:22<00:50,  5.46it/s]16 02:35:26 Save the image 00614D.png
 30%|███████████▉                            | 117/392 [00:22<00:50,  5.45it/s]16 02:35:27 Save the image 00615D.png
 30%|████████████                            | 118/392 [00:22<00:50,  5.46it/s]16 02:35:27 Save the image 00616D.png
 30%|████████████▏                           | 119/392 [00:22<00:49,  5.47it/s]16 02:35:27 Save the image 00617D.png
 31%|████████████▏                           | 120/392 [00:23<00:49,  5.48it/s]16 02:35:27 Save the image 00618D.png
 31%|████████████▎                           | 121/392 [00:23<00:49,  5.51it/s]16 02:35:27 Save the image 00619D.png
 31%|████████████▍                           | 122/392 [00:23<00:50,  5.38it/s]16 02:35:27 Save the image 00620D.png

 31%|████████████▌                           | 123/392 [00:23<00:49,  5.38it/s]16 02:35:28 Save the image 00621D.png
 32%|████████████▋                           | 124/392 [00:23<00:49,  5.41it/s]16 02:35:28 Save the image 00622D.png
 32%|████████████▊                           | 125/392 [00:24<00:49,  5.44it/s]16 02:35:28 Save the image 00623D.png
 32%|████████████▊                           | 126/392 [00:24<00:48,  5.44it/s]16 02:35:28 Save the image 00624D.png
 32%|████████████▉                           | 127/392 [00:24<00:48,  5.46it/s]16 02:35:28 Save the image 00625D.png
 33%|█████████████                           | 128/392 [00:24<00:48,  5.49it/s]16 02:35:29 Save the image 00626D.png
 33%|█████████████▏                          | 129/392 [00:24<00:48,  5.43it/s]16 02:35:29 Save the image 00627D.png
 33%|█████████████▎                          | 130/392 [00:24<00:48,  5.41it/s]16 02:35:29 Save the image 00628D.png
 33%|█████████████▎                          | 131/392 [00:25<00:47,  5.44it/s]16 02:35:29 Save the image 00629D.png
 34%|█████████████▍                          | 132/392 [00:25<00:47,  5.47it/s]16 02:35:29 Save the image 00630D.png
 34%|█████████████▌                          | 133/392 [00:25<00:48,  5.37it/s]16 02:35:29 Save the image 00631D.png
 34%|█████████████▋                          | 134/392 [00:25<00:48,  5.32it/s]16 02:35:30 Save the image 00632D.png
 34%|█████████████▊                          | 135/392 [00:25<00:48,  5.32it/s]16 02:35:30 Save the image 00633D.png
 35%|█████████████▉                          | 136/392 [00:26<00:48,  5.28it/s]16 02:35:30 Save the image 00634D.png
 35%|█████████████▉                          | 137/392 [00:26<00:47,  5.38it/s]16 02:35:30 Save the image 00635D.png
 35%|██████████████                          | 138/392 [00:26<00:47,  5.40it/s]16 02:35:30 Save the image 00636D.png
 35%|██████████████▏                         | 139/392 [00:26<00:46,  5.42it/s]16 02:35:31 Save the image 00637D.png
 36%|██████████████▎                         | 140/392 [00:26<00:46,  5.44it/s]16 02:35:31 Save the image 00638D.png
 36%|██████████████▍                         | 141/392 [00:27<00:45,  5.46it/s]16 02:35:31 Save the image 00639D.png
 36%|██████████████▍                         | 142/392 [00:27<00:45,  5.48it/s]16 02:35:31 Save the image 00640D.png
 36%|██████████████▌                         | 143/392 [00:27<00:45,  5.48it/s]16 02:35:31 Save the image 00641D.png
 37%|██████████████▋                         | 144/392 [00:27<00:45,  5.51it/s]16 02:35:32 Save the image 00642D.png
 37%|██████████████▊                         | 145/392 [00:27<00:45,  5.49it/s]16 02:35:32 Save the image 00643D.png
 37%|██████████████▉                         | 146/392 [00:27<00:44,  5.54it/s]16 02:35:32 Save the image 00644D.png
 38%|███████████████                         | 147/392 [00:28<00:44,  5.53it/s]16 02:35:32 Save the image 00645D.png
 38%|███████████████                         | 148/392 [00:28<00:44,  5.53it/s]16 02:35:32 Save the image 00646D.png
 38%|███████████████▏                        | 149/392 [00:28<00:43,  5.55it/s]16 02:35:32 Save the image 00647D.png
 38%|███████████████▎                        | 150/392 [00:28<00:44,  5.44it/s]16 02:35:33 Save the image 00648D.png
 39%|███████████████▍                        | 151/392 [00:28<00:44,  5.45it/s]16 02:35:33 Save the image 00649D.png
 39%|███████████████▌                        | 152/392 [00:29<00:43,  5.48it/s]16 02:35:33 Save the image 00650D.png
 39%|███████████████▌                        | 153/392 [00:29<00:43,  5.50it/s]16 02:35:33 Save the image 00651D.png
 39%|███████████████▋                        | 154/392 [00:29<00:42,  5.54it/s]16 02:35:33 Save the image 00652D.png
 40%|███████████████▊                        | 155/392 [00:29<00:42,  5.53it/s]16 02:35:34 Save the image 00653D.png
 40%|███████████████▉                        | 156/392 [00:29<00:42,  5.54it/s]16 02:35:34 Save the image 00654D.png
 40%|████████████████                        | 157/392 [00:29<00:42,  5.47it/s]16 02:35:34 Save the image 00655D.png
 40%|████████████████                        | 158/392 [00:30<00:42,  5.48it/s]16 02:35:34 Save the image 00656D.png
 41%|████████████████▏                       | 159/392 [00:30<00:42,  5.49it/s]16 02:35:34 Save the image 00657D.png
 41%|████████████████▎                       | 160/392 [00:30<00:42,  5.50it/s]16 02:35:34 Save the image 00658D.png
 41%|████████████████▍                       | 161/392 [00:30<00:38,  5.93it/s]16 02:35:35 Save the image 00659D.png
 41%|████████████████▌                       | 162/392 [00:30<00:39,  5.76it/s]16 02:35:35 Save the image 00660D.png
 42%|████████████████▋                       | 163/392 [00:30<00:40,  5.69it/s]16 02:35:35 Save the image 00661D.png
 42%|████████████████▋                       | 164/392 [00:31<00:40,  5.64it/s]16 02:35:35 Save the image 00662D.png
 42%|████████████████▊                       | 165/392 [00:31<00:40,  5.57it/s]16 02:35:35 Save the image 00663D.png
 42%|████████████████▉                       | 166/392 [00:31<00:39,  5.67it/s]16 02:35:35 Save the image 00664D.png
 43%|█████████████████                       | 167/392 [00:31<00:39,  5.65it/s]16 02:35:36 Save the image 00665D.png
 43%|█████████████████▏                      | 168/392 [00:31<00:40,  5.57it/s]16 02:35:36 Save the image 00666D.png
 43%|█████████████████▏                      | 169/392 [00:32<00:40,  5.51it/s]16 02:35:36 Save the image 00667D.png
 43%|█████████████████▎                      | 170/392 [00:32<00:40,  5.52it/s]16 02:35:36 Save the image 00668D.png
 44%|█████████████████▍                      | 171/392 [00:32<00:39,  5.53it/s]16 02:35:36 Save the image 00669D.png
 44%|█████████████████▌                      | 172/392 [00:32<00:40,  5.49it/s]16 02:35:37 Save the image 00670D.png
 44%|█████████████████▋                      | 173/392 [00:32<00:39,  5.52it/s]16 02:35:37 Save the image 00671D.png
 44%|█████████████████▊                      | 174/392 [00:32<00:39,  5.49it/s]16 02:35:37 Save the image 00672D.png
 45%|█████████████████▊                      | 175/392 [00:33<00:39,  5.50it/s]16 02:35:37 Save the image 00673D.png
 45%|█████████████████▉                      | 176/392 [00:33<00:39,  5.47it/s]16 02:35:37 Save the image 00674D.png
 45%|██████████████████                      | 177/392 [00:33<00:39,  5.48it/s]16 02:35:37 Save the image 00675D.png
 45%|██████████████████▏                     | 178/392 [00:33<00:38,  5.51it/s]16 02:35:38 Save the image 00676D.png
 46%|██████████████████▎                     | 179/392 [00:33<00:38,  5.48it/s]16 02:35:38 Save the image 00677D.png
 46%|██████████████████▎                     | 180/392 [00:34<00:38,  5.49it/s]16 02:35:38 Save the image 01377D.png
 46%|██████████████████▍                     | 181/392 [00:34<00:38,  5.51it/s]16 02:35:38 Save the image 01378D.png
 46%|██████████████████▌                     | 182/392 [00:34<00:38,  5.52it/s]16 02:35:38 Save the image 01379D.png
 47%|██████████████████▋                     | 183/392 [00:34<00:38,  5.50it/s]16 02:35:39 Save the image 01380D.png
 47%|██████████████████▊                     | 184/392 [00:34<00:37,  5.50it/s]16 02:35:39 Save the image 01381D.png
 47%|██████████████████▉                     | 185/392 [00:34<00:37,  5.52it/s]16 02:35:39 Save the image 01382D.png
 47%|██████████████████▉                     | 186/392 [00:35<00:37,  5.48it/s]16 02:35:39 Save the image 01383D.png
 48%|███████████████████                     | 187/392 [00:35<00:37,  5.46it/s]16 02:35:39 Save the image 01384D.png

 48%|███████████████████▏                    | 188/392 [00:35<00:37,  5.45it/s]16 02:35:39 Save the image 01385D.png
 48%|███████████████████▎                    | 189/392 [00:35<00:37,  5.47it/s]16 02:35:40 Save the image 01386D.png
 48%|███████████████████▍                    | 190/392 [00:35<00:36,  5.47it/s]16 02:35:40 Save the image 01387D.png
 49%|███████████████████▍                    | 191/392 [00:36<00:36,  5.48it/s]16 02:35:40 Save the image 01388D.png
 49%|███████████████████▌                    | 192/392 [00:36<00:36,  5.50it/s]16 02:35:40 Save the image 01389D.png
 49%|███████████████████▋                    | 193/392 [00:36<00:36,  5.39it/s]16 02:35:40 Save the image 01390D.png
 49%|███████████████████▊                    | 194/392 [00:36<00:36,  5.41it/s]16 02:35:41 Save the image 01391D.png
 50%|███████████████████▉                    | 195/392 [00:36<00:36,  5.42it/s]16 02:35:41 Save the image 01392D.png
 50%|████████████████████                    | 196/392 [00:36<00:35,  5.45it/s]16 02:35:41 Save the image 01393D.png
 50%|████████████████████                    | 197/392 [00:37<00:35,  5.44it/s]16 02:35:41 Save the image 01394D.png
 51%|████████████████████▏                   | 198/392 [00:37<00:35,  5.46it/s]16 02:35:41 Save the image 01395D.png
 51%|████████████████████▎                   | 199/392 [00:37<00:35,  5.51it/s]16 02:35:41 Save the image 01396D.png
 51%|████████████████████▍                   | 200/392 [00:37<00:35,  5.42it/s]16 02:35:42 Save the image 01397D.png
 51%|████████████████████▌                   | 201/392 [00:37<00:35,  5.42it/s]16 02:35:42 Save the image 01398D.png
 52%|████████████████████▌                   | 202/392 [00:38<00:34,  5.45it/s]16 02:35:42 Save the image 01399D.png
 52%|████████████████████▋                   | 203/392 [00:38<00:34,  5.47it/s]16 02:35:42 Save the image 01400D.png
 52%|████████████████████▊                   | 204/392 [00:38<00:34,  5.50it/s]16 02:35:42 Save the image 01401D.png
 52%|████████████████████▉                   | 205/392 [00:38<00:34,  5.50it/s]16 02:35:43 Save the image 01002N.png
 53%|█████████████████████                   | 206/392 [00:38<00:33,  5.52it/s]16 02:35:43 Save the image 01003N.png
 53%|█████████████████████                   | 207/392 [00:38<00:33,  5.49it/s]16 02:35:43 Save the image 01004N.png
 53%|█████████████████████▏                  | 208/392 [00:39<00:33,  5.50it/s]16 02:35:43 Save the image 01005N.png
 53%|█████████████████████▎                  | 209/392 [00:39<00:33,  5.51it/s]16 02:35:43 Save the image 01006N.png
 54%|█████████████████████▍                  | 210/392 [00:39<00:33,  5.50it/s]16 02:35:43 Save the image 01007N.png
 54%|█████████████████████▌                  | 211/392 [00:39<00:30,  5.84it/s]16 02:35:44 Save the image 01008N.png
 54%|█████████████████████▋                  | 212/392 [00:39<00:31,  5.72it/s]16 02:35:44 Save the image 01009N.png
 54%|█████████████████████▋                  | 213/392 [00:40<00:31,  5.69it/s]16 02:35:44 Save the image 01010N.png
 55%|█████████████████████▊                  | 214/392 [00:40<00:31,  5.66it/s]16 02:35:44 Save the image 01011N.png
 55%|█████████████████████▉                  | 215/392 [00:40<00:31,  5.60it/s]16 02:35:44 Save the image 01012N.png
 55%|██████████████████████                  | 216/392 [00:40<00:31,  5.62it/s]16 02:35:45 Save the image 01013N.png
 55%|██████████████████████▏                 | 217/392 [00:40<00:31,  5.64it/s]16 02:35:45 Save the image 01014N.png
 56%|██████████████████████▏                 | 218/392 [00:40<00:31,  5.58it/s]16 02:35:45 Save the image 01015N.png
 56%|██████████████████████▎                 | 219/392 [00:41<00:31,  5.53it/s]16 02:35:45 Save the image 01016N.png
 56%|██████████████████████▍                 | 220/392 [00:41<00:30,  5.61it/s]16 02:35:45 Save the image 01017N.png
 56%|██████████████████████▌                 | 221/392 [00:41<00:30,  5.61it/s]16 02:35:45 Save the image 01018N.png
 57%|██████████████████████▋                 | 222/392 [00:41<00:30,  5.56it/s]16 02:35:46 Save the image 01019N.png
 57%|██████████████████████▊                 | 223/392 [00:41<00:30,  5.58it/s]16 02:35:46 Save the image 01020N.png
 57%|██████████████████████▊                 | 224/392 [00:42<00:30,  5.52it/s]16 02:35:46 Save the image 01021N.png
 57%|██████████████████████▉                 | 225/392 [00:42<00:30,  5.43it/s]16 02:35:46 Save the image 01022N.png
 58%|███████████████████████                 | 226/392 [00:42<00:30,  5.52it/s]16 02:35:46 Save the image 01023N.png
 58%|███████████████████████▏                | 227/392 [00:42<00:29,  5.51it/s]16 02:35:47 Save the image 01024N.png
 58%|███████████████████████▎                | 228/392 [00:42<00:29,  5.52it/s]16 02:35:47 Save the image 01025N.png
 58%|███████████████████████▎                | 229/392 [00:42<00:29,  5.50it/s]16 02:35:47 Save the image 01026N.png
 59%|███████████████████████▍                | 230/392 [00:43<00:29,  5.49it/s]16 02:35:47 Save the image 01027N.png
 59%|███████████████████████▌                | 231/392 [00:43<00:29,  5.48it/s]16 02:35:47 Save the image 01028N.png
 59%|███████████████████████▋                | 232/392 [00:43<00:29,  5.49it/s]16 02:35:47 Save the image 01029N.png
 59%|███████████████████████▊                | 233/392 [00:43<00:29,  5.48it/s]16 02:35:48 Save the image 01030N.png
 60%|███████████████████████▉                | 234/392 [00:43<00:28,  5.53it/s]16 02:35:48 Save the image 01031N.png
 60%|███████████████████████▉                | 235/392 [00:44<00:28,  5.54it/s]16 02:35:48 Save the image 01032N.png
 60%|████████████████████████                | 236/392 [00:44<00:28,  5.41it/s]16 02:35:48 Save the image 01033N.png
 60%|████████████████████████▏               | 237/392 [00:44<00:28,  5.43it/s]16 02:35:48 Save the image 01034N.png
 61%|████████████████████████▎               | 238/392 [00:44<00:28,  5.47it/s]16 02:35:49 Save the image 01035N.png
 61%|████████████████████████▍               | 239/392 [00:44<00:27,  5.48it/s]16 02:35:49 Save the image 01036N.png
 61%|████████████████████████▍               | 240/392 [00:44<00:26,  5.78it/s]16 02:35:49 Save the image 01037N.png
 61%|████████████████████████▌               | 241/392 [00:45<00:26,  5.61it/s]16 02:35:49 Save the image 01038N.png
 62%|████████████████████████▋               | 242/392 [00:45<00:26,  5.62it/s]16 02:35:49 Save the image 01039N.png
 62%|████████████████████████▊               | 243/392 [00:45<00:27,  5.50it/s]16 02:35:49 Save the image 01040N.png
 62%|████████████████████████▉               | 244/392 [00:45<00:26,  5.50it/s]16 02:35:50 Save the image 01041N.png
 62%|█████████████████████████               | 245/392 [00:45<00:26,  5.50it/s]16 02:35:50 Save the image 01042N.png
 63%|█████████████████████████               | 246/392 [00:45<00:26,  5.54it/s]16 02:35:50 Save the image 01043N.png
 63%|█████████████████████████▏              | 247/392 [00:46<00:25,  5.78it/s]16 02:35:50 Save the image 01044N.png
 63%|█████████████████████████▎              | 248/392 [00:46<00:25,  5.58it/s]16 02:35:50 Save the image 01045N.png
 64%|█████████████████████████▍              | 249/392 [00:46<00:25,  5.57it/s]16 02:35:50 Save the image 01046N.png
 64%|█████████████████████████▌              | 250/392 [00:46<00:25,  5.52it/s]16 02:35:51 Save the image 01047N.png
 64%|█████████████████████████▌              | 251/392 [00:46<00:25,  5.55it/s]16 02:35:51 Save the image 01048N.png
 64%|█████████████████████████▋              | 252/392 [00:47<00:25,  5.57it/s]16 02:35:51 Save the image 01049N.png

 65%|█████████████████████████▊              | 253/392 [00:47<00:25,  5.53it/s]16 02:35:51 Save the image 01050N.png
 65%|█████████████████████████▉              | 254/392 [00:47<00:24,  5.55it/s]16 02:35:51 Save the image 01051N.png
 65%|██████████████████████████              | 255/392 [00:47<00:24,  5.49it/s]16 02:35:52 Save the image 01052N.png
 65%|██████████████████████████              | 256/392 [00:47<00:24,  5.50it/s]16 02:35:52 Save the image 01053N.png
 66%|██████████████████████████▏             | 257/392 [00:47<00:24,  5.54it/s]16 02:35:52 Save the image 01054N.png
 66%|██████████████████████████▎             | 258/392 [00:48<00:24,  5.50it/s]16 02:35:52 Save the image 01055N.png
 66%|██████████████████████████▍             | 259/392 [00:48<00:24,  5.52it/s]16 02:35:52 Save the image 01056N.png
 66%|██████████████████████████▌             | 260/392 [00:48<00:24,  5.48it/s]16 02:35:52 Save the image 01057N.png
 67%|██████████████████████████▋             | 261/392 [00:48<00:23,  5.49it/s]16 02:35:53 Save the image 01058N.png
 67%|██████████████████████████▋             | 262/392 [00:48<00:23,  5.47it/s]16 02:35:53 Save the image 01059N.png
 67%|██████████████████████████▊             | 263/392 [00:49<00:23,  5.46it/s]16 02:35:53 Save the image 01060N.png
 67%|██████████████████████████▉             | 264/392 [00:49<00:23,  5.43it/s]16 02:35:53 Save the image 01061N.png
 68%|███████████████████████████             | 265/392 [00:49<00:23,  5.37it/s]16 02:35:53 Save the image 01062N.png
 68%|███████████████████████████▏            | 266/392 [00:49<00:23,  5.36it/s]16 02:35:54 Save the image 01063N.png
 68%|███████████████████████████▏            | 267/392 [00:49<00:23,  5.37it/s]16 02:35:54 Save the image 01064N.png
 68%|███████████████████████████▎            | 268/392 [00:50<00:22,  5.39it/s]16 02:35:54 Save the image 01065N.png
 69%|███████████████████████████▍            | 269/392 [00:50<00:22,  5.39it/s]16 02:35:54 Save the image 01066N.png
 69%|███████████████████████████▌            | 270/392 [00:50<00:22,  5.44it/s]16 02:35:54 Save the image 01067N.png
 69%|███████████████████████████▋            | 271/392 [00:50<00:22,  5.47it/s]16 02:35:55 Save the image 01068N.png
 69%|███████████████████████████▊            | 272/392 [00:50<00:22,  5.45it/s]16 02:35:55 Save the image 01069N.png
 70%|███████████████████████████▊            | 273/392 [00:50<00:22,  5.40it/s]16 02:35:55 Save the image 01070N.png
 70%|███████████████████████████▉            | 274/392 [00:51<00:21,  5.39it/s]16 02:35:55 Save the image 01071N.png
 70%|████████████████████████████            | 275/392 [00:51<00:21,  5.42it/s]16 02:35:55 Save the image 01072N.png
 70%|████████████████████████████▏           | 276/392 [00:51<00:20,  5.76it/s]16 02:35:55 Save the image 01073N.png
 71%|████████████████████████████▎           | 277/392 [00:51<00:20,  5.63it/s]16 02:35:56 Save the image 01074N.png
 71%|████████████████████████████▎           | 278/392 [00:51<00:20,  5.67it/s]16 02:35:56 Save the image 01075N.png
 71%|████████████████████████████▍           | 279/392 [00:51<00:20,  5.65it/s]16 02:35:56 Save the image 01076N.png
 71%|████████████████████████████▌           | 280/392 [00:52<00:20,  5.57it/s]16 02:35:56 Save the image 01077N.png
 72%|████████████████████████████▋           | 281/392 [00:52<00:19,  5.60it/s]16 02:35:56 Save the image 01078N.png
 72%|████████████████████████████▊           | 282/392 [00:52<00:19,  5.63it/s]16 02:35:56 Save the image 01079N.png
 72%|████████████████████████████▉           | 283/392 [00:52<00:19,  5.56it/s]16 02:35:57 Save the image 01080N.png
 72%|████████████████████████████▉           | 284/392 [00:52<00:19,  5.54it/s]16 02:35:57 Save the image 01081N.png
 73%|█████████████████████████████           | 285/392 [00:53<00:19,  5.56it/s]16 02:35:57 Save the image 01082N.png
 73%|█████████████████████████████▏          | 286/392 [00:53<00:19,  5.58it/s]16 02:35:57 Save the image 01083N.png
 73%|█████████████████████████████▎          | 287/392 [00:53<00:18,  5.53it/s]16 02:35:57 Save the image 01084N.png
 73%|█████████████████████████████▍          | 288/392 [00:53<00:18,  5.55it/s]16 02:35:58 Save the image 01085N.png
 74%|█████████████████████████████▍          | 289/392 [00:53<00:18,  5.53it/s]16 02:35:58 Save the image 01086N.png
 74%|█████████████████████████████▌          | 290/392 [00:53<00:18,  5.51it/s]16 02:35:58 Save the image 01087N.png
 74%|█████████████████████████████▋          | 291/392 [00:54<00:18,  5.50it/s]16 02:35:58 Save the image 01088N.png
 74%|█████████████████████████████▊          | 292/392 [00:54<00:18,  5.51it/s]16 02:35:58 Save the image 01089N.png
 75%|█████████████████████████████▉          | 293/392 [00:54<00:17,  5.50it/s]16 02:35:58 Save the image 01090N.png
 75%|██████████████████████████████          | 294/392 [00:54<00:18,  5.42it/s]16 02:35:59 Save the image 01091N.png
 75%|██████████████████████████████          | 295/392 [00:54<00:17,  5.43it/s]16 02:35:59 Save the image 01092N.png
 76%|██████████████████████████████▏         | 296/392 [00:55<00:17,  5.45it/s]16 02:35:59 Save the image 01093N.png
 76%|██████████████████████████████▎         | 297/392 [00:55<00:17,  5.47it/s]16 02:35:59 Save the image 01094N.png
 76%|██████████████████████████████▍         | 298/392 [00:55<00:17,  5.45it/s]16 02:35:59 Save the image 01095N.png
 76%|██████████████████████████████▌         | 299/392 [00:55<00:16,  5.49it/s]16 02:36:00 Save the image 01096N.png
 77%|██████████████████████████████▌         | 300/392 [00:55<00:16,  5.51it/s]16 02:36:00 Save the image 01097N.png
 77%|██████████████████████████████▋         | 301/392 [00:55<00:16,  5.47it/s]16 02:36:00 Save the image 01098N.png
 77%|██████████████████████████████▊         | 302/392 [00:56<00:16,  5.42it/s]16 02:36:00 Save the image 01099N.png
 77%|██████████████████████████████▉         | 303/392 [00:56<00:16,  5.41it/s]16 02:36:00 Save the image 01100N.png
 78%|███████████████████████████████         | 304/392 [00:56<00:16,  5.42it/s]16 02:36:00 Save the image 01101N.png
 78%|███████████████████████████████         | 305/392 [00:56<00:15,  5.74it/s]16 02:36:01 Save the image 01102N.png
 78%|███████████████████████████████▏        | 306/392 [00:56<00:15,  5.63it/s]16 02:36:01 Save the image 01103N.png
 78%|███████████████████████████████▎        | 307/392 [00:57<00:15,  5.60it/s]16 02:36:01 Save the image 01104N.png
 79%|███████████████████████████████▍        | 308/392 [00:57<00:15,  5.59it/s]16 02:36:01 Save the image 01105N.png
 79%|███████████████████████████████▌        | 309/392 [00:57<00:14,  5.54it/s]16 02:36:01 Save the image 01106N.png
 79%|███████████████████████████████▋        | 310/392 [00:57<00:14,  5.57it/s]16 02:36:02 Save the image 01107N.png
 79%|███████████████████████████████▋        | 311/392 [00:57<00:14,  5.60it/s]16 02:36:02 Save the image 01108N.png
 80%|███████████████████████████████▊        | 312/392 [00:57<00:14,  5.55it/s]16 02:36:02 Save the image 01109N.png
 80%|███████████████████████████████▉        | 313/392 [00:58<00:14,  5.53it/s]16 02:36:02 Save the image 01110N.png
 80%|████████████████████████████████        | 314/392 [00:58<00:14,  5.56it/s]16 02:36:02 Save the image 01111N.png
 80%|████████████████████████████████▏       | 315/392 [00:58<00:13,  5.59it/s]16 02:36:02 Save the image 01112N.png
 81%|████████████████████████████████▏       | 316/392 [00:58<00:13,  5.54it/s]16 02:36:03 Save the image 01113N.png
 81%|████████████████████████████████▎       | 317/392 [00:58<00:13,  5.57it/s]16 02:36:03 Save the image 01114N.png

 81%|████████████████████████████████▍       | 318/392 [00:59<00:13,  5.55it/s]16 02:36:03 Save the image 01115N.png
 81%|████████████████████████████████▌       | 319/392 [00:59<00:13,  5.61it/s]16 02:36:03 Save the image 01116N.png
 82%|████████████████████████████████▋       | 320/392 [00:59<00:12,  5.58it/s]16 02:36:03 Save the image 01117N.png
 82%|████████████████████████████████▊       | 321/392 [00:59<00:12,  5.58it/s]16 02:36:04 Save the image 01118N.png
 82%|████████████████████████████████▊       | 322/392 [00:59<00:12,  5.57it/s]16 02:36:04 Save the image 01119N.png
 82%|████████████████████████████████▉       | 323/392 [00:59<00:12,  5.54it/s]16 02:36:04 Save the image 01120N.png
 83%|█████████████████████████████████       | 324/392 [01:00<00:12,  5.52it/s]16 02:36:04 Save the image 01121N.png
 83%|█████████████████████████████████▏      | 325/392 [01:00<00:12,  5.51it/s]16 02:36:04 Save the image 01122N.png
 83%|█████████████████████████████████▎      | 326/392 [01:00<00:11,  5.52it/s]16 02:36:04 Save the image 01123N.png
 83%|█████████████████████████████████▎      | 327/392 [01:00<00:11,  5.50it/s]16 02:36:05 Save the image 01124N.png
 84%|█████████████████████████████████▍      | 328/392 [01:00<00:11,  5.53it/s]16 02:36:05 Save the image 01125N.png
 84%|█████████████████████████████████▌      | 329/392 [01:01<00:11,  5.55it/s]16 02:36:05 Save the image 01126N.png
 84%|█████████████████████████████████▋      | 330/392 [01:01<00:11,  5.51it/s]16 02:36:05 Save the image 01127N.png
 84%|█████████████████████████████████▊      | 331/392 [01:01<00:11,  5.48it/s]16 02:36:05 Save the image 01128N.png
 85%|█████████████████████████████████▉      | 332/392 [01:01<00:10,  5.50it/s]16 02:36:06 Save the image 01129N.png
 85%|█████████████████████████████████▉      | 333/392 [01:01<00:10,  5.51it/s]16 02:36:06 Save the image 01130N.png
 85%|██████████████████████████████████      | 334/392 [01:01<00:10,  5.46it/s]16 02:36:06 Save the image 01131N.png
 85%|██████████████████████████████████▏     | 335/392 [01:02<00:10,  5.54it/s]16 02:36:06 Save the image 01132N.png
 86%|██████████████████████████████████▎     | 336/392 [01:02<00:09,  5.62it/s]16 02:36:06 Save the image 01133N.png
 86%|██████████████████████████████████▍     | 337/392 [01:02<00:10,  5.46it/s]16 02:36:06 Save the image 01134N.png
 86%|██████████████████████████████████▍     | 338/392 [01:02<00:09,  5.45it/s]16 02:36:07 Save the image 01135N.png
 86%|██████████████████████████████████▌     | 339/392 [01:02<00:09,  5.48it/s]16 02:36:07 Save the image 01136N.png
 87%|██████████████████████████████████▋     | 340/392 [01:03<00:09,  5.51it/s]16 02:36:07 Save the image 01137N.png
 87%|██████████████████████████████████▊     | 341/392 [01:03<00:08,  5.87it/s]16 02:36:07 Save the image 01138N.png
 87%|██████████████████████████████████▉     | 342/392 [01:03<00:08,  5.75it/s]16 02:36:07 Save the image 01139N.png
 88%|███████████████████████████████████     | 343/392 [01:03<00:08,  5.70it/s]16 02:36:08 Save the image 01140N.png
 88%|███████████████████████████████████     | 344/392 [01:03<00:08,  5.66it/s]16 02:36:08 Save the image 01141N.png
 88%|███████████████████████████████████▏    | 345/392 [01:03<00:08,  5.62it/s]16 02:36:08 Save the image 01142N.png
 88%|███████████████████████████████████▎    | 346/392 [01:04<00:08,  5.64it/s]16 02:36:08 Save the image 01143N.png
 89%|███████████████████████████████████▍    | 347/392 [01:04<00:07,  5.66it/s]16 02:36:08 Save the image 01144N.png
 89%|███████████████████████████████████▌    | 348/392 [01:04<00:07,  5.61it/s]16 02:36:08 Save the image 01145N.png
 89%|███████████████████████████████████▌    | 349/392 [01:04<00:07,  5.56it/s]16 02:36:09 Save the image 01146N.png
 89%|███████████████████████████████████▋    | 350/392 [01:04<00:07,  5.58it/s]16 02:36:09 Save the image 01147N.png
 90%|███████████████████████████████████▊    | 351/392 [01:04<00:07,  5.58it/s]16 02:36:09 Save the image 01148N.png
 90%|███████████████████████████████████▉    | 352/392 [01:05<00:07,  5.54it/s]16 02:36:09 Save the image 01149N.png
 90%|████████████████████████████████████    | 353/392 [01:05<00:06,  5.58it/s]16 02:36:09 Save the image 01150N.png
 90%|████████████████████████████████████    | 354/392 [01:05<00:06,  5.54it/s]16 02:36:09 Save the image 01151N.png
 91%|████████████████████████████████████▏   | 355/392 [01:05<00:06,  5.50it/s]16 02:36:10 Save the image 01152N.png
 91%|████████████████████████████████████▎   | 356/392 [01:05<00:06,  5.47it/s]16 02:36:10 Save the image 01153N.png
 91%|████████████████████████████████████▍   | 357/392 [01:06<00:06,  5.50it/s]16 02:36:10 Save the image 01154N.png
 91%|████████████████████████████████████▌   | 358/392 [01:06<00:06,  5.53it/s]16 02:36:10 Save the image 01155N.png
 92%|████████████████████████████████████▋   | 359/392 [01:06<00:06,  5.47it/s]16 02:36:10 Save the image 01156N.png
 92%|████████████████████████████████████▋   | 360/392 [01:06<00:05,  5.50it/s]16 02:36:11 Save the image 01157N.png
 92%|████████████████████████████████████▊   | 361/392 [01:06<00:05,  5.49it/s]16 02:36:11 Save the image 01158N.png
 92%|████████████████████████████████████▉   | 362/392 [01:06<00:05,  5.44it/s]16 02:36:11 Save the image 01159N.png
 93%|█████████████████████████████████████   | 363/392 [01:07<00:05,  5.47it/s]16 02:36:11 Save the image 01160N.png
 93%|█████████████████████████████████████▏  | 364/392 [01:07<00:05,  5.44it/s]16 02:36:11 Save the image 01161N.png
 93%|█████████████████████████████████████▏  | 365/392 [01:07<00:04,  5.42it/s]16 02:36:12 Save the image 01162N.png
 93%|█████████████████████████████████████▎  | 366/392 [01:07<00:04,  5.35it/s]16 02:36:12 Save the image 01163N.png
 94%|█████████████████████████████████████▍  | 367/392 [01:07<00:04,  5.28it/s]16 02:36:12 Save the image 01164N.png
 94%|█████████████████████████████████████▌  | 368/392 [01:08<00:04,  5.33it/s]16 02:36:12 Save the image 01165N.png
 94%|█████████████████████████████████████▋  | 369/392 [01:08<00:04,  5.37it/s]16 02:36:12 Save the image 01166N.png
 94%|█████████████████████████████████████▊  | 370/392 [01:08<00:04,  5.39it/s]16 02:36:12 Save the image 01167N.png
 95%|█████████████████████████████████████▊  | 371/392 [01:08<00:03,  5.39it/s]16 02:36:13 Save the image 01168N.png
 95%|█████████████████████████████████████▉  | 372/392 [01:08<00:03,  5.46it/s]16 02:36:13 Save the image 01169N.png
 95%|██████████████████████████████████████  | 373/392 [01:09<00:03,  5.43it/s]16 02:36:13 Save the image 01170N.png
 95%|██████████████████████████████████████▏ | 374/392 [01:09<00:03,  5.47it/s]16 02:36:13 Save the image 01171N.png
 96%|██████████████████████████████████████▎ | 375/392 [01:09<00:03,  5.53it/s]16 02:36:13 Save the image 01172N.png
 96%|██████████████████████████████████████▎ | 376/392 [01:09<00:02,  5.50it/s]16 02:36:13 Save the image 01173N.png
 96%|██████████████████████████████████████▍ | 377/392 [01:09<00:02,  5.83it/s]16 02:36:14 Save the image 01174N.png
 96%|██████████████████████████████████████▌ | 378/392 [01:09<00:02,  5.71it/s]16 02:36:14 Save the image 01175N.png
 97%|██████████████████████████████████████▋ | 379/392 [01:10<00:02,  5.68it/s]16 02:36:14 Save the image 01176N.png
 97%|██████████████████████████████████████▊ | 380/392 [01:10<00:02,  5.66it/s]16 02:36:14 Save the image 01177N.png
 97%|██████████████████████████████████████▉ | 381/392 [01:10<00:01,  5.58it/s]16 02:36:14 Save the image 01178N.png
 97%|██████████████████████████████████████▉ | 382/392 [01:10<00:01,  5.59it/s]16 02:36:15 Save the image 01179N.png

 98%|███████████████████████████████████████ | 383/392 [01:10<00:01,  5.62it/s]16 02:36:15 Save the image 01180N.png
 98%|███████████████████████████████████████▏| 384/392 [01:10<00:01,  5.56it/s]16 02:36:15 Save the image 01181N.png
 98%|███████████████████████████████████████▎| 385/392 [01:11<00:01,  5.53it/s]16 02:36:15 Save the image 01182N.png
 98%|███████████████████████████████████████▍| 386/392 [01:11<00:01,  5.54it/s]16 02:36:15 Save the image 01183N.png
 99%|███████████████████████████████████████▍| 387/392 [01:11<00:00,  5.53it/s]16 02:36:15 Save the image 01184N.png
 99%|███████████████████████████████████████▌| 388/392 [01:11<00:00,  5.50it/s]16 02:36:16 Save the image 01185N.png
 99%|███████████████████████████████████████▋| 389/392 [01:11<00:00,  5.54it/s]16 02:36:16 Save the image 01186N.png
 99%|███████████████████████████████████████▊| 390/392 [01:12<00:00,  5.54it/s]16 02:36:16 Save the image 01187N.png
100%|███████████████████████████████████████▉| 391/392 [01:12<00:00,  5.51it/s]16 02:36:16 Save the image 01188N.png
100%|████████████████████████████████████████| 392/392 [01:12<00:00,  5.41it/s]
1 unlabeled	97.775%
2 car   	87.045%
3 person	71.804%
4 bike  	72.866%
5 curve 	38.150%
6 car_stop	39.068%
7 guardrail	48.623%
8 color_cone	58.333%
9 bump  	50.866%
----------     mean_IoU	62.726%	freq_IoU	95.784%	mean_pixel_acc	72.982%	pixel_acc	97.732%
16 02:36:16 Evaluation Elapsed Time: 72.43s

In [4]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_Original")

!python eval.py -e 100 -d 0 --split train -p predictions_E0_train

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:36:48 using devices 0
16 02:36:48 Using backbone: Segformer-B2
16 02:36:49 Using MLP Decoder
16 02:36:49 Load Model: /home/cse-sdpl/Downloads/CMX_Original/log_TDD_mit_b2/checkpoint/epoch-100.pth
16 02:36:53 Load model, Time usage:
	IO: 4.055520057678223, initialize parameters: 0.04480147361755371
16 02:36:53 GPU 0 handle 1568 data.
  0%|                                                 | 0/1568 [00:00<?, ?it/s][ WARN:0@8.409] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:36:55 Save the image 00001D.png
  0%|                                         | 1/1568 [00:01<42:52,  1.64s/it]16 02:36:55 Save the image 00001D_flip.png
  0%|                                         | 2/1568 [00:01<20:16,  1.29it/s]16 02:36:55 Save the image 00002D.png
  0%|                                         | 3/1568 [00:01<13:03,  2.00it/s]16 02:36:55 Save the image 00002D_flip.png
  0%|                                         | 4/1568 [00:02<09:44,  2.67it/s]16 02:36:56 Save the image 00055D.png
  0%|▏                                        | 5/1568 [00:02<07:54,  3.30it/s]16 02:36:56 Save the image 00055D_flip.png
  0%|▏                                        | 6/1568 [00:02<06:48,  3.82it/s]16 02:36:56 Save the image 00056D.png
  0%|▏                                        | 7/1568 [00:02<06:01,  4.32it/s]16 02:36:56 Save the image 00056D_flip.png
  1%|▏                                        | 8/1568 [00:02<05:30,  4.71it/s]16 02:36:56 Save the image 00057D.png
  1%|▏                                        | 9/1568 [00:03<05:15,  4.95it/s]16 02:36:56 Save the image 00057D_flip.png
  1%|▎                                       | 10/1568 [00:03<05:03,  5.13it/s]16 02:36:57 Save the image 00058D.png
  1%|▎                                       | 11/1568 [00:03<04:52,  5.32it/s]16 02:36:57 Save the image 00058D_flip.png
  1%|▎                                       | 12/1568 [00:03<04:45,  5.44it/s]16 02:36:57 Save the image 00081D.png
  1%|▎                                       | 13/1568 [00:03<04:47,  5.40it/s]16 02:36:57 Save the image 00081D_flip.png
  1%|▎                                       | 14/1568 [00:03<04:44,  5.47it/s]16 02:36:57 Save the image 00082D.png
  1%|▍                                       | 15/1568 [00:04<04:41,  5.52it/s]16 02:36:57 Save the image 00082D_flip.png
  1%|▍                                       | 16/1568 [00:04<04:25,  5.84it/s]16 02:36:58 Save the image 00083D.png
  1%|▍                                       | 17/1568 [00:04<04:28,  5.78it/s]16 02:36:58 Save the image 00083D_flip.png
  1%|▍                                       | 18/1568 [00:04<04:27,  5.79it/s]16 02:36:58 Save the image 00084D.png
  1%|▍                                       | 19/1568 [00:04<04:25,  5.83it/s]16 02:36:58 Save the image 00084D_flip.png
  1%|▌                                       | 20/1568 [00:04<04:27,  5.78it/s]16 02:36:58 Save the image 00085D.png
  1%|▌                                       | 21/1568 [00:05<04:28,  5.76it/s]16 02:36:59 Save the image 00085D_flip.png
  1%|▌                                       | 22/1568 [00:05<04:28,  5.76it/s]16 02:36:59 Save the image 00086D.png
  1%|▌                                       | 23/1568 [00:05<04:28,  5.76it/s]16 02:36:59 Save the image 00086D_flip.png
  2%|▌                                       | 24/1568 [00:05<04:11,  6.14it/s]16 02:36:59 Save the image 00087D.png
  2%|▋                                       | 25/1568 [00:05<04:17,  5.99it/s]16 02:36:59 Save the image 00087D_flip.png
  2%|▋                                       | 26/1568 [00:05<04:19,  5.94it/s]16 02:36:59 Save the image 00088D.png
  2%|▋                                       | 27/1568 [00:06<04:21,  5.90it/s]16 02:37:00 Save the image 00088D_flip.png
  2%|▋                                       | 28/1568 [00:06<04:24,  5.82it/s]16 02:37:00 Save the image 00091D.png
  2%|▋                                       | 29/1568 [00:06<04:21,  5.88it/s]16 02:37:00 Save the image 00091D_flip.png
  2%|▊                                       | 30/1568 [00:06<04:25,  5.80it/s]16 02:37:00 Save the image 00092D.png
  2%|▊                                       | 31/1568 [00:06<04:27,  5.74it/s]16 02:37:00 Save the image 00092D_flip.png
  2%|▊                                       | 32/1568 [00:06<04:12,  6.09it/s]16 02:37:00 Save the image 00093D.png
  2%|▊                                       | 33/1568 [00:07<04:19,  5.91it/s]16 02:37:01 Save the image 00093D_flip.png
  2%|▊                                       | 34/1568 [00:07<04:20,  5.88it/s]16 02:37:01 Save the image 00094D.png
  2%|▉                                       | 35/1568 [00:07<04:22,  5.85it/s]16 02:37:01 Save the image 00094D_flip.png
  2%|▉                                       | 36/1568 [00:07<04:24,  5.79it/s]16 02:37:01 Save the image 00095D.png
  2%|▉                                       | 37/1568 [00:07<04:24,  5.79it/s]16 02:37:01 Save the image 00095D_flip.png
  2%|▉                                       | 38/1568 [00:08<04:26,  5.75it/s]16 02:37:01 Save the image 00096D.png
  2%|▉                                       | 39/1568 [00:08<04:25,  5.75it/s]16 02:37:02 Save the image 00096D_flip.png
  3%|█                                       | 40/1568 [00:08<04:13,  6.03it/s]16 02:37:02 Save the image 00097D.png
  3%|█                                       | 41/1568 [00:08<04:19,  5.89it/s]16 02:37:02 Save the image 00097D_flip.png
  3%|█                                       | 42/1568 [00:08<04:20,  5.85it/s]16 02:37:02 Save the image 00098D.png
  3%|█                                       | 43/1568 [00:08<04:20,  5.85it/s]16 02:37:02 Save the image 00098D_flip.png
  3%|█                                       | 44/1568 [00:09<04:23,  5.77it/s]16 02:37:02 Save the image 00099D.png
  3%|█▏                                      | 45/1568 [00:09<04:23,  5.79it/s]16 02:37:03 Save the image 00099D_flip.png
  3%|█▏                                      | 46/1568 [00:09<04:25,  5.73it/s]16 02:37:03 Save the image 00100D.png
  3%|█▏                                      | 47/1568 [00:09<04:26,  5.70it/s]16 02:37:03 Save the image 00100D_flip.png
  3%|█▏                                      | 48/1568 [00:09<04:27,  5.68it/s]16 02:37:03 Save the image 00101D.png
  3%|█▎                                      | 49/1568 [00:09<04:27,  5.68it/s]16 02:37:03 Save the image 00101D_flip.png
  3%|█▎                                      | 50/1568 [00:10<04:25,  5.72it/s]16 02:37:03 Save the image 00102D.png
  3%|█▎                                      | 51/1568 [00:10<04:25,  5.70it/s]16 02:37:04 Save the image 00102D_flip.png
  3%|█▎                                      | 52/1568 [00:10<04:26,  5.70it/s]16 02:37:04 Save the image 00103D.png
  3%|█▎                                      | 53/1568 [00:10<04:24,  5.72it/s]16 02:37:04 Save the image 00103D_flip.png
  3%|█▍                                      | 54/1568 [00:10<04:23,  5.74it/s]16 02:37:04 Save the image 00104D.png
  4%|█▍                                      | 55/1568 [00:10<04:24,  5.71it/s]16 02:37:04 Save the image 00104D_flip.png
  4%|█▍                                      | 56/1568 [00:11<04:28,  5.63it/s]16 02:37:05 Save the image 00105D.png

  4%|█▍                                      | 57/1568 [00:11<04:27,  5.64it/s]16 02:37:05 Save the image 00105D_flip.png
  4%|█▍                                      | 58/1568 [00:11<04:26,  5.67it/s]16 02:37:05 Save the image 00106D.png
  4%|█▌                                      | 59/1568 [00:11<04:26,  5.66it/s]16 02:37:05 Save the image 00106D_flip.png
  4%|█▌                                      | 60/1568 [00:11<04:26,  5.66it/s]16 02:37:05 Save the image 00107D.png
  4%|█▌                                      | 61/1568 [00:12<04:24,  5.70it/s]16 02:37:05 Save the image 00107D_flip.png
  4%|█▌                                      | 62/1568 [00:12<04:21,  5.75it/s]16 02:37:06 Save the image 00108D.png
  4%|█▌                                      | 63/1568 [00:12<04:12,  5.97it/s]16 02:37:06 Save the image 00108D_flip.png
  4%|█▋                                      | 64/1568 [00:12<04:16,  5.86it/s]16 02:37:06 Save the image 00109D.png
  4%|█▋                                      | 65/1568 [00:12<04:17,  5.84it/s]16 02:37:06 Save the image 00109D_flip.png
  4%|█▋                                      | 66/1568 [00:12<04:17,  5.84it/s]16 02:37:06 Save the image 00110D.png
  4%|█▋                                      | 67/1568 [00:13<04:19,  5.79it/s]16 02:37:06 Save the image 00110D_flip.png
  4%|█▋                                      | 68/1568 [00:13<04:23,  5.70it/s]16 02:37:07 Save the image 00111D.png
  4%|█▊                                      | 69/1568 [00:13<04:22,  5.70it/s]16 02:37:07 Save the image 00111D_flip.png
  4%|█▊                                      | 70/1568 [00:13<04:22,  5.70it/s]16 02:37:07 Save the image 00112D.png
  5%|█▊                                      | 71/1568 [00:13<04:08,  6.02it/s]16 02:37:07 Save the image 00112D_flip.png
  5%|█▊                                      | 72/1568 [00:13<04:13,  5.91it/s]16 02:37:07 Save the image 00113D.png
  5%|█▊                                      | 73/1568 [00:14<04:15,  5.86it/s]16 02:37:07 Save the image 00113D_flip.png
  5%|█▉                                      | 74/1568 [00:14<04:16,  5.81it/s]16 02:37:08 Save the image 00114D.png
  5%|█▉                                      | 75/1568 [00:14<04:22,  5.69it/s]16 02:37:08 Save the image 00114D_flip.png
  5%|█▉                                      | 76/1568 [00:14<04:19,  5.75it/s]16 02:37:08 Save the image 00115D.png
  5%|█▉                                      | 77/1568 [00:14<04:20,  5.72it/s]16 02:37:08 Save the image 00115D_flip.png
  5%|█▉                                      | 78/1568 [00:14<04:20,  5.73it/s]16 02:37:08 Save the image 00116D.png
  5%|██                                      | 79/1568 [00:15<04:20,  5.71it/s]16 02:37:09 Save the image 00116D_flip.png
  5%|██                                      | 80/1568 [00:15<04:19,  5.72it/s]16 02:37:09 Save the image 00117D.png
  5%|██                                      | 81/1568 [00:15<04:19,  5.74it/s]16 02:37:09 Save the image 00117D_flip.png
  5%|██                                      | 82/1568 [00:15<04:20,  5.71it/s]16 02:37:09 Save the image 00118D.png
  5%|██                                      | 83/1568 [00:15<04:19,  5.72it/s]16 02:37:09 Save the image 00118D_flip.png
  5%|██▏                                     | 84/1568 [00:16<04:16,  5.78it/s]16 02:37:09 Save the image 00119D.png
  5%|██▏                                     | 85/1568 [00:16<04:15,  5.81it/s]16 02:37:10 Save the image 00119D_flip.png
  5%|██▏                                     | 86/1568 [00:16<04:16,  5.77it/s]16 02:37:10 Save the image 00120D.png
  6%|██▏                                     | 87/1568 [00:16<04:17,  5.76it/s]16 02:37:10 Save the image 00120D_flip.png
  6%|██▏                                     | 88/1568 [00:16<04:16,  5.77it/s]16 02:37:10 Save the image 00121D.png
  6%|██▎                                     | 89/1568 [00:16<04:15,  5.80it/s]16 02:37:10 Save the image 00121D_flip.png
  6%|██▎                                     | 90/1568 [00:17<04:16,  5.75it/s]16 02:37:10 Save the image 00122D.png
  6%|██▎                                     | 91/1568 [00:17<04:17,  5.73it/s]16 02:37:11 Save the image 00122D_flip.png
  6%|██▎                                     | 92/1568 [00:17<04:17,  5.74it/s]16 02:37:11 Save the image 00123D.png
  6%|██▎                                     | 93/1568 [00:17<04:14,  5.79it/s]16 02:37:11 Save the image 00123D_flip.png
  6%|██▍                                     | 94/1568 [00:17<04:03,  6.05it/s]16 02:37:11 Save the image 00124D.png
  6%|██▍                                     | 95/1568 [00:17<04:08,  5.93it/s]16 02:37:11 Save the image 00124D_flip.png
  6%|██▍                                     | 96/1568 [00:18<04:10,  5.89it/s]16 02:37:11 Save the image 00125D.png
  6%|██▍                                     | 97/1568 [00:18<04:10,  5.87it/s]16 02:37:12 Save the image 00125D_flip.png
  6%|██▌                                     | 98/1568 [00:18<04:13,  5.81it/s]16 02:37:12 Save the image 00126D.png
  6%|██▌                                     | 99/1568 [00:18<04:14,  5.76it/s]16 02:37:12 Save the image 00126D_flip.png
  6%|██▍                                    | 100/1568 [00:18<04:14,  5.77it/s]16 02:37:12 Save the image 00127D.png
  6%|██▌                                    | 101/1568 [00:18<04:14,  5.77it/s]16 02:37:12 Save the image 00127D_flip.png
  7%|██▌                                    | 102/1568 [00:19<04:00,  6.10it/s]16 02:37:12 Save the image 00128D.png
  7%|██▌                                    | 103/1568 [00:19<04:05,  5.96it/s]16 02:37:13 Save the image 00128D_flip.png
  7%|██▌                                    | 104/1568 [00:19<04:07,  5.92it/s]16 02:37:13 Save the image 00129D.png
  7%|██▌                                    | 105/1568 [00:19<04:10,  5.84it/s]16 02:37:13 Save the image 00129D_flip.png
  7%|██▋                                    | 106/1568 [00:19<04:13,  5.76it/s]16 02:37:13 Save the image 00130D.png
  7%|██▋                                    | 107/1568 [00:19<04:11,  5.81it/s]16 02:37:13 Save the image 00130D_flip.png
  7%|██▋                                    | 108/1568 [00:20<04:12,  5.79it/s]16 02:37:14 Save the image 00131D.png
  7%|██▋                                    | 109/1568 [00:20<04:12,  5.78it/s]16 02:37:14 Save the image 00131D_flip.png
  7%|██▋                                    | 110/1568 [00:20<03:57,  6.15it/s]16 02:37:14 Save the image 00132D.png
  7%|██▊                                    | 111/1568 [00:20<04:03,  5.99it/s]16 02:37:14 Save the image 00132D_flip.png
  7%|██▊                                    | 112/1568 [00:20<04:05,  5.94it/s]16 02:37:14 Save the image 00133D.png
  7%|██▊                                    | 113/1568 [00:20<04:05,  5.92it/s]16 02:37:14 Save the image 00133D_flip.png
  7%|██▊                                    | 114/1568 [00:21<04:09,  5.83it/s]16 02:37:15 Save the image 00134D.png
  7%|██▊                                    | 115/1568 [00:21<04:08,  5.85it/s]16 02:37:15 Save the image 00134D_flip.png
  7%|██▉                                    | 116/1568 [00:21<04:10,  5.80it/s]16 02:37:15 Save the image 00135D.png
  7%|██▉                                    | 117/1568 [00:21<04:11,  5.78it/s]16 02:37:15 Save the image 00135D_flip.png
  8%|██▉                                    | 118/1568 [00:21<04:10,  5.79it/s]16 02:37:15 Save the image 00136D.png
  8%|██▉                                    | 119/1568 [00:22<04:10,  5.78it/s]16 02:37:15 Save the image 00136D_flip.png
  8%|██▉                                    | 120/1568 [00:22<04:10,  5.78it/s]16 02:37:16 Save the image 00137D.png

  8%|███                                    | 121/1568 [00:22<04:11,  5.75it/s]16 02:37:16 Save the image 00137D_flip.png
  8%|███                                    | 122/1568 [00:22<04:11,  5.76it/s]16 02:37:16 Save the image 00138D.png
  8%|███                                    | 123/1568 [00:22<04:08,  5.81it/s]16 02:37:16 Save the image 00138D_flip.png
  8%|███                                    | 124/1568 [00:22<04:07,  5.82it/s]16 02:37:16 Save the image 00139D.png
  8%|███                                    | 125/1568 [00:23<04:09,  5.78it/s]16 02:37:16 Save the image 00139D_flip.png
  8%|███▏                                   | 126/1568 [00:23<04:10,  5.75it/s]16 02:37:17 Save the image 00140D.png
  8%|███▏                                   | 127/1568 [00:23<04:10,  5.75it/s]16 02:37:17 Save the image 00140D_flip.png
  8%|███▏                                   | 128/1568 [00:23<04:09,  5.78it/s]16 02:37:17 Save the image 00141D.png
  8%|███▏                                   | 129/1568 [00:23<04:10,  5.74it/s]16 02:37:17 Save the image 00141D_flip.png
  8%|███▏                                   | 130/1568 [00:23<04:10,  5.74it/s]16 02:37:17 Save the image 00142D.png
  8%|███▎                                   | 131/1568 [00:24<04:10,  5.74it/s]16 02:37:17 Save the image 00142D_flip.png
  8%|███▎                                   | 132/1568 [00:24<04:07,  5.79it/s]16 02:37:18 Save the image 00143D.png
  8%|███▎                                   | 133/1568 [00:24<04:00,  5.97it/s]16 02:37:18 Save the image 00143D_flip.png
  9%|███▎                                   | 134/1568 [00:24<04:04,  5.87it/s]16 02:37:18 Save the image 00144D.png
  9%|███▎                                   | 135/1568 [00:24<04:07,  5.78it/s]16 02:37:18 Save the image 00144D_flip.png
  9%|███▍                                   | 136/1568 [00:24<04:07,  5.79it/s]16 02:37:18 Save the image 00145D.png
  9%|███▍                                   | 137/1568 [00:25<04:09,  5.74it/s]16 02:37:18 Save the image 00145D_flip.png
  9%|███▍                                   | 138/1568 [00:25<04:10,  5.71it/s]16 02:37:19 Save the image 00146D.png
  9%|███▍                                   | 139/1568 [00:25<04:09,  5.72it/s]16 02:37:19 Save the image 00146D_flip.png
  9%|███▍                                   | 140/1568 [00:25<04:08,  5.74it/s]16 02:37:19 Save the image 00147D.png
  9%|███▌                                   | 141/1568 [00:25<03:55,  6.07it/s]16 02:37:19 Save the image 00147D_flip.png
  9%|███▌                                   | 142/1568 [00:25<04:00,  5.93it/s]16 02:37:19 Save the image 00148D.png
  9%|███▌                                   | 143/1568 [00:26<04:01,  5.90it/s]16 02:37:20 Save the image 00148D_flip.png
  9%|███▌                                   | 144/1568 [00:26<04:02,  5.88it/s]16 02:37:20 Save the image 00149D.png
  9%|███▌                                   | 145/1568 [00:26<04:04,  5.81it/s]16 02:37:20 Save the image 00149D_flip.png
  9%|███▋                                   | 146/1568 [00:26<04:03,  5.83it/s]16 02:37:20 Save the image 00150D.png
  9%|███▋                                   | 147/1568 [00:26<04:05,  5.79it/s]16 02:37:20 Save the image 00150D_flip.png
  9%|███▋                                   | 148/1568 [00:27<04:06,  5.77it/s]16 02:37:20 Save the image 00151D.png
 10%|███▋                                   | 149/1568 [00:27<04:06,  5.76it/s]16 02:37:21 Save the image 00151D_flip.png
 10%|███▋                                   | 150/1568 [00:27<04:06,  5.76it/s]16 02:37:21 Save the image 00152D.png
 10%|███▊                                   | 151/1568 [00:27<04:05,  5.76it/s]16 02:37:21 Save the image 00152D_flip.png
 10%|███▊                                   | 152/1568 [00:27<04:05,  5.77it/s]16 02:37:21 Save the image 00153D.png
 10%|███▊                                   | 153/1568 [00:27<04:06,  5.74it/s]16 02:37:21 Save the image 00153D_flip.png
 10%|███▊                                   | 154/1568 [00:28<04:04,  5.78it/s]16 02:37:21 Save the image 00154D.png
 10%|███▊                                   | 155/1568 [00:28<04:02,  5.84it/s]16 02:37:22 Save the image 00154D_flip.png
 10%|███▉                                   | 156/1568 [00:28<04:04,  5.78it/s]16 02:37:22 Save the image 00155D.png
 10%|███▉                                   | 157/1568 [00:28<04:06,  5.73it/s]16 02:37:22 Save the image 00155D_flip.png
 10%|███▉                                   | 158/1568 [00:28<04:05,  5.75it/s]16 02:37:22 Save the image 00156D.png
 10%|███▉                                   | 159/1568 [00:28<04:04,  5.76it/s]16 02:37:22 Save the image 00156D_flip.png
 10%|███▉                                   | 160/1568 [00:29<04:06,  5.71it/s]16 02:37:22 Save the image 00157D.png
 10%|████                                   | 161/1568 [00:29<04:06,  5.70it/s]16 02:37:23 Save the image 00157D_flip.png
 10%|████                                   | 162/1568 [00:29<04:05,  5.72it/s]16 02:37:23 Save the image 00158D.png
 10%|████                                   | 163/1568 [00:29<04:03,  5.78it/s]16 02:37:23 Save the image 00158D_flip.png
 10%|████                                   | 164/1568 [00:29<03:52,  6.03it/s]16 02:37:23 Save the image 00159D.png
 11%|████                                   | 165/1568 [00:29<03:56,  5.93it/s]16 02:37:23 Save the image 00159D_flip.png
 11%|████▏                                  | 166/1568 [00:30<03:58,  5.89it/s]16 02:37:23 Save the image 00160D.png
 11%|████▏                                  | 167/1568 [00:30<03:58,  5.88it/s]16 02:37:24 Save the image 00160D_flip.png
 11%|████▏                                  | 168/1568 [00:30<04:00,  5.82it/s]16 02:37:24 Save the image 00161D.png
 11%|████▏                                  | 169/1568 [00:30<04:02,  5.77it/s]16 02:37:24 Save the image 00161D_flip.png
 11%|████▏                                  | 170/1568 [00:30<04:01,  5.79it/s]16 02:37:24 Save the image 00162D.png
 11%|████▎                                  | 171/1568 [00:30<04:01,  5.78it/s]16 02:37:24 Save the image 00162D_flip.png
 11%|████▎                                  | 172/1568 [00:31<03:47,  6.13it/s]16 02:37:24 Save the image 00163D.png
 11%|████▎                                  | 173/1568 [00:31<03:53,  5.97it/s]16 02:37:25 Save the image 00163D_flip.png
 11%|████▎                                  | 174/1568 [00:31<03:55,  5.93it/s]16 02:37:25 Save the image 00164D.png
 11%|████▎                                  | 175/1568 [00:31<03:55,  5.91it/s]16 02:37:25 Save the image 00164D_flip.png
 11%|████▍                                  | 176/1568 [00:31<03:58,  5.84it/s]16 02:37:25 Save the image 00165D.png
 11%|████▍                                  | 177/1568 [00:31<04:00,  5.77it/s]16 02:37:25 Save the image 00165D_flip.png
 11%|████▍                                  | 178/1568 [00:32<04:02,  5.73it/s]16 02:37:26 Save the image 00166D.png
 11%|████▍                                  | 179/1568 [00:32<04:02,  5.74it/s]16 02:37:26 Save the image 00166D_flip.png
 11%|████▍                                  | 180/1568 [00:32<03:46,  6.12it/s]16 02:37:26 Save the image 00167D.png
 12%|████▌                                  | 181/1568 [00:32<03:52,  5.98it/s]16 02:37:26 Save the image 00167D_flip.png
 12%|████▌                                  | 182/1568 [00:32<03:53,  5.92it/s]16 02:37:26 Save the image 00168D.png
 12%|████▌                                  | 183/1568 [00:32<03:54,  5.90it/s]16 02:37:26 Save the image 00168D_flip.png
 12%|████▌                                  | 184/1568 [00:33<03:57,  5.83it/s]16 02:37:27 Save the image 00169D.png

 12%|████▌                                  | 185/1568 [00:33<03:57,  5.82it/s]16 02:37:27 Save the image 00169D_flip.png
 12%|████▋                                  | 186/1568 [00:33<03:59,  5.78it/s]16 02:37:27 Save the image 00170D.png
 12%|████▋                                  | 187/1568 [00:33<03:59,  5.76it/s]16 02:37:27 Save the image 00170D_flip.png
 12%|████▋                                  | 188/1568 [00:33<03:59,  5.77it/s]16 02:37:27 Save the image 00171D.png
 12%|████▋                                  | 189/1568 [00:34<03:59,  5.77it/s]16 02:37:27 Save the image 00171D_flip.png
 12%|████▋                                  | 190/1568 [00:34<03:58,  5.78it/s]16 02:37:28 Save the image 00172D.png
 12%|████▊                                  | 191/1568 [00:34<03:58,  5.77it/s]16 02:37:28 Save the image 00172D_flip.png
 12%|████▊                                  | 192/1568 [00:34<04:00,  5.72it/s]16 02:37:28 Save the image 00173D.png
 12%|████▊                                  | 193/1568 [00:34<03:58,  5.77it/s]16 02:37:28 Save the image 00173D_flip.png
 12%|████▊                                  | 194/1568 [00:34<03:56,  5.80it/s]16 02:37:28 Save the image 00174D.png
 12%|████▊                                  | 195/1568 [00:35<04:01,  5.68it/s]16 02:37:28 Save the image 00174D_flip.png
 12%|████▉                                  | 196/1568 [00:35<04:01,  5.67it/s]16 02:37:29 Save the image 00175D.png
 13%|████▉                                  | 197/1568 [00:35<04:00,  5.70it/s]16 02:37:29 Save the image 00175D_flip.png
 13%|████▉                                  | 198/1568 [00:35<03:58,  5.75it/s]16 02:37:29 Save the image 00176D.png
 13%|████▉                                  | 199/1568 [00:35<03:58,  5.74it/s]16 02:37:29 Save the image 00176D_flip.png
 13%|████▉                                  | 200/1568 [00:35<03:59,  5.71it/s]16 02:37:29 Save the image 00177D.png
 13%|████▉                                  | 201/1568 [00:36<03:58,  5.74it/s]16 02:37:30 Save the image 00177D_flip.png
 13%|█████                                  | 202/1568 [00:36<03:55,  5.80it/s]16 02:37:30 Save the image 00178D.png
 13%|█████                                  | 203/1568 [00:36<03:45,  6.05it/s]16 02:37:30 Save the image 00178D_flip.png
 13%|█████                                  | 204/1568 [00:36<03:50,  5.91it/s]16 02:37:30 Save the image 00179D.png
 13%|█████                                  | 205/1568 [00:36<03:51,  5.88it/s]16 02:37:30 Save the image 00179D_flip.png
 13%|█████                                  | 206/1568 [00:36<03:51,  5.87it/s]16 02:37:30 Save the image 00180D.png
 13%|█████▏                                 | 207/1568 [00:37<03:54,  5.81it/s]16 02:37:31 Save the image 00180D_flip.png
 13%|█████▏                                 | 208/1568 [00:37<03:55,  5.76it/s]16 02:37:31 Save the image 00181D.png
 13%|█████▏                                 | 209/1568 [00:37<03:55,  5.78it/s]16 02:37:31 Save the image 00181D_flip.png
 13%|█████▏                                 | 210/1568 [00:37<03:55,  5.76it/s]16 02:37:31 Save the image 00182D.png
 13%|█████▏                                 | 211/1568 [00:37<03:42,  6.11it/s]16 02:37:31 Save the image 00182D_flip.png
 14%|█████▎                                 | 212/1568 [00:37<03:47,  5.96it/s]16 02:37:31 Save the image 00183D.png
 14%|█████▎                                 | 213/1568 [00:38<03:49,  5.91it/s]16 02:37:32 Save the image 00183D_flip.png
 14%|█████▎                                 | 214/1568 [00:38<03:50,  5.87it/s]16 02:37:32 Save the image 00184D.png
 14%|█████▎                                 | 215/1568 [00:38<03:52,  5.81it/s]16 02:37:32 Save the image 00184D_flip.png
 14%|█████▎                                 | 216/1568 [00:38<03:54,  5.76it/s]16 02:37:32 Save the image 00185D.png
 14%|█████▍                                 | 217/1568 [00:38<03:54,  5.76it/s]16 02:37:32 Save the image 00185D_flip.png
 14%|█████▍                                 | 218/1568 [00:39<03:54,  5.77it/s]16 02:37:32 Save the image 00186D.png
 14%|█████▍                                 | 219/1568 [00:39<03:41,  6.09it/s]16 02:37:33 Save the image 00186D_flip.png
 14%|█████▍                                 | 220/1568 [00:39<03:46,  5.95it/s]16 02:37:33 Save the image 00187D.png
 14%|█████▍                                 | 221/1568 [00:39<03:47,  5.92it/s]16 02:37:33 Save the image 00187D_flip.png
 14%|█████▌                                 | 222/1568 [00:39<03:48,  5.89it/s]16 02:37:33 Save the image 00188D.png
 14%|█████▌                                 | 223/1568 [00:39<03:51,  5.82it/s]16 02:37:33 Save the image 00188D_flip.png
 14%|█████▌                                 | 224/1568 [00:40<03:49,  5.85it/s]16 02:37:33 Save the image 00189D.png
 14%|█████▌                                 | 225/1568 [00:40<03:50,  5.82it/s]16 02:37:34 Save the image 00189D_flip.png
 14%|█████▌                                 | 226/1568 [00:40<03:51,  5.79it/s]16 02:37:34 Save the image 00190D.png
 14%|█████▋                                 | 227/1568 [00:40<03:41,  6.05it/s]16 02:37:34 Save the image 00190D_flip.png
 15%|█████▋                                 | 228/1568 [00:40<03:45,  5.93it/s]16 02:37:34 Save the image 00191D.png
 15%|█████▋                                 | 229/1568 [00:40<03:46,  5.92it/s]16 02:37:34 Save the image 00191D_flip.png
 15%|█████▋                                 | 230/1568 [00:41<03:47,  5.89it/s]16 02:37:34 Save the image 00192D.png
 15%|█████▋                                 | 231/1568 [00:41<03:49,  5.81it/s]16 02:37:35 Save the image 00192D_flip.png
 15%|█████▊                                 | 232/1568 [00:41<03:48,  5.84it/s]16 02:37:35 Save the image 00193D.png
 15%|█████▊                                 | 233/1568 [00:41<03:50,  5.79it/s]16 02:37:35 Save the image 00193D_flip.png
 15%|█████▊                                 | 234/1568 [00:41<03:50,  5.78it/s]16 02:37:35 Save the image 00194D.png
 15%|█████▊                                 | 235/1568 [00:41<03:50,  5.80it/s]16 02:37:35 Save the image 00194D_flip.png
 15%|█████▊                                 | 236/1568 [00:42<03:50,  5.78it/s]16 02:37:35 Save the image 00195D.png
 15%|█████▉                                 | 237/1568 [00:42<03:50,  5.78it/s]16 02:37:36 Save the image 00195D_flip.png
 15%|█████▉                                 | 238/1568 [00:42<03:49,  5.78it/s]16 02:37:36 Save the image 00196D.png
 15%|█████▉                                 | 239/1568 [00:42<03:49,  5.78it/s]16 02:37:36 Save the image 00196D_flip.png
 15%|█████▉                                 | 240/1568 [00:42<03:48,  5.82it/s]16 02:37:36 Save the image 00197D.png
 15%|█████▉                                 | 241/1568 [00:42<03:47,  5.84it/s]16 02:37:36 Save the image 00197D_flip.png
 15%|██████                                 | 242/1568 [00:43<03:49,  5.79it/s]16 02:37:37 Save the image 00198D.png
 15%|██████                                 | 243/1568 [00:43<03:50,  5.75it/s]16 02:37:37 Save the image 00198D_flip.png
 16%|██████                                 | 244/1568 [00:43<03:50,  5.75it/s]16 02:37:37 Save the image 00199D.png
 16%|██████                                 | 245/1568 [00:43<03:49,  5.76it/s]16 02:37:37 Save the image 00199D_flip.png
 16%|██████                                 | 246/1568 [00:43<03:51,  5.71it/s]16 02:37:37 Save the image 00200D.png
 16%|██████▏                                | 247/1568 [00:44<03:49,  5.75it/s]16 02:37:37 Save the image 00200D_flip.png
 16%|██████▏                                | 248/1568 [00:44<03:49,  5.75it/s]16 02:37:38 Save the image 00201D.png

 16%|██████▏                                | 249/1568 [00:44<03:46,  5.83it/s]16 02:37:38 Save the image 00201D_flip.png
 16%|██████▏                                | 250/1568 [00:44<03:39,  6.01it/s]16 02:37:38 Save the image 00202D.png
 16%|██████▏                                | 251/1568 [00:44<03:43,  5.90it/s]16 02:37:38 Save the image 00202D_flip.png
 16%|██████▎                                | 252/1568 [00:44<03:44,  5.87it/s]16 02:37:38 Save the image 00203D.png
 16%|██████▎                                | 253/1568 [00:45<03:44,  5.86it/s]16 02:37:38 Save the image 00203D_flip.png
 16%|██████▎                                | 254/1568 [00:45<03:46,  5.80it/s]16 02:37:39 Save the image 00204D.png
 16%|██████▎                                | 255/1568 [00:45<03:47,  5.76it/s]16 02:37:39 Save the image 00204D_flip.png
 16%|██████▎                                | 256/1568 [00:45<03:47,  5.76it/s]16 02:37:39 Save the image 00205D.png
 16%|██████▍                                | 257/1568 [00:45<03:47,  5.76it/s]16 02:37:39 Save the image 00205D_flip.png
 16%|██████▍                                | 258/1568 [00:45<03:34,  6.11it/s]16 02:37:39 Save the image 00206D.png
 17%|██████▍                                | 259/1568 [00:46<03:39,  5.96it/s]16 02:37:39 Save the image 00206D_flip.png
 17%|██████▍                                | 260/1568 [00:46<03:41,  5.92it/s]16 02:37:40 Save the image 00207D.png
 17%|██████▍                                | 261/1568 [00:46<03:41,  5.90it/s]16 02:37:40 Save the image 00207D_flip.png
 17%|██████▌                                | 262/1568 [00:46<03:44,  5.81it/s]16 02:37:40 Save the image 00208D.png
 17%|██████▌                                | 263/1568 [00:46<03:45,  5.78it/s]16 02:37:40 Save the image 00208D_flip.png
 17%|██████▌                                | 264/1568 [00:46<03:45,  5.77it/s]16 02:37:40 Save the image 00209D.png
 17%|██████▌                                | 265/1568 [00:47<03:46,  5.76it/s]16 02:37:40 Save the image 00209D_flip.png
 17%|██████▌                                | 266/1568 [00:47<03:33,  6.08it/s]16 02:37:41 Save the image 00210D.png
 17%|██████▋                                | 267/1568 [00:47<03:38,  5.95it/s]16 02:37:41 Save the image 00210D_flip.png
 17%|██████▋                                | 268/1568 [00:47<03:40,  5.91it/s]16 02:37:41 Save the image 00211D.png
 17%|██████▋                                | 269/1568 [00:47<03:40,  5.89it/s]16 02:37:41 Save the image 00211D_flip.png
 17%|██████▋                                | 270/1568 [00:47<03:43,  5.82it/s]16 02:37:41 Save the image 00212D.png
 17%|██████▋                                | 271/1568 [00:48<03:42,  5.84it/s]16 02:37:41 Save the image 00212D_flip.png
 17%|██████▊                                | 272/1568 [00:48<03:44,  5.78it/s]16 02:37:42 Save the image 00213D.png
 17%|██████▊                                | 273/1568 [00:48<03:44,  5.77it/s]16 02:37:42 Save the image 00213D_flip.png
 17%|██████▊                                | 274/1568 [00:48<03:44,  5.77it/s]16 02:37:42 Save the image 00214D.png
 18%|██████▊                                | 275/1568 [00:48<03:44,  5.76it/s]16 02:37:42 Save the image 00214D_flip.png
 18%|██████▊                                | 276/1568 [00:48<03:44,  5.77it/s]16 02:37:42 Save the image 00215D.png
 18%|██████▉                                | 277/1568 [00:49<03:44,  5.76it/s]16 02:37:43 Save the image 00215D_flip.png
 18%|██████▉                                | 278/1568 [00:49<03:43,  5.76it/s]16 02:37:43 Save the image 00216D.png
 18%|██████▉                                | 279/1568 [00:49<03:42,  5.79it/s]16 02:37:43 Save the image 00216D_flip.png
 18%|██████▉                                | 280/1568 [00:49<03:41,  5.82it/s]16 02:37:43 Save the image 00217D.png
 18%|██████▉                                | 281/1568 [00:49<03:43,  5.76it/s]16 02:37:43 Save the image 00217D_flip.png
 18%|███████                                | 282/1568 [00:50<03:44,  5.74it/s]16 02:37:43 Save the image 00218D.png
 18%|███████                                | 283/1568 [00:50<03:43,  5.76it/s]16 02:37:44 Save the image 00218D_flip.png
 18%|███████                                | 284/1568 [00:50<03:42,  5.77it/s]16 02:37:44 Save the image 00219D.png
 18%|███████                                | 285/1568 [00:50<03:44,  5.72it/s]16 02:37:44 Save the image 00219D_flip.png
 18%|███████                                | 286/1568 [00:50<03:43,  5.73it/s]16 02:37:44 Save the image 00220D.png
 18%|███████▏                               | 287/1568 [00:50<03:43,  5.73it/s]16 02:37:44 Save the image 00220D_flip.png
 18%|███████▏                               | 288/1568 [00:51<03:41,  5.78it/s]16 02:37:44 Save the image 00221D.png
 18%|███████▏                               | 289/1568 [00:51<03:33,  5.99it/s]16 02:37:45 Save the image 00221D_flip.png
 18%|███████▏                               | 290/1568 [00:51<03:37,  5.88it/s]16 02:37:45 Save the image 00222D.png
 19%|███████▏                               | 291/1568 [00:51<03:37,  5.86it/s]16 02:37:45 Save the image 00222D_flip.png
 19%|███████▎                               | 292/1568 [00:51<03:37,  5.86it/s]16 02:37:45 Save the image 00223D.png
 19%|███████▎                               | 293/1568 [00:51<03:39,  5.80it/s]16 02:37:45 Save the image 00223D_flip.png
 19%|███████▎                               | 294/1568 [00:52<03:41,  5.75it/s]16 02:37:45 Save the image 00224D.png
 19%|███████▎                               | 295/1568 [00:52<03:42,  5.73it/s]16 02:37:46 Save the image 00224D_flip.png
 19%|███████▎                               | 296/1568 [00:52<03:42,  5.72it/s]16 02:37:46 Save the image 00225D.png
 19%|███████▍                               | 297/1568 [00:52<03:28,  6.08it/s]16 02:37:46 Save the image 00225D_flip.png
 19%|███████▍                               | 298/1568 [00:52<03:33,  5.94it/s]16 02:37:46 Save the image 00226D.png
 19%|███████▍                               | 299/1568 [00:52<03:34,  5.91it/s]16 02:37:46 Save the image 00226D_flip.png
 19%|███████▍                               | 300/1568 [00:53<03:35,  5.89it/s]16 02:37:46 Save the image 00227D.png
 19%|███████▍                               | 301/1568 [00:53<03:37,  5.82it/s]16 02:37:47 Save the image 00227D_flip.png
 19%|███████▌                               | 302/1568 [00:53<03:37,  5.81it/s]16 02:37:47 Save the image 00228D.png
 19%|███████▌                               | 303/1568 [00:53<03:38,  5.79it/s]16 02:37:47 Save the image 00228D_flip.png
 19%|███████▌                               | 304/1568 [00:53<03:39,  5.77it/s]16 02:37:47 Save the image 00229D.png
 19%|███████▌                               | 305/1568 [00:53<03:26,  6.11it/s]16 02:37:47 Save the image 00229D_flip.png
 20%|███████▌                               | 306/1568 [00:54<03:31,  5.96it/s]16 02:37:47 Save the image 00230D.png
 20%|███████▋                               | 307/1568 [00:54<03:35,  5.85it/s]16 02:37:48 Save the image 00230D_flip.png
 20%|███████▋                               | 308/1568 [00:54<03:35,  5.85it/s]16 02:37:48 Save the image 00231D.png
 20%|███████▋                               | 309/1568 [00:54<03:37,  5.79it/s]16 02:37:48 Save the image 00231D_flip.png
 20%|███████▋                               | 310/1568 [00:54<03:35,  5.83it/s]16 02:37:48 Save the image 00232D.png
 20%|███████▋                               | 311/1568 [00:54<03:37,  5.78it/s]16 02:37:48 Save the image 00232D_flip.png
 20%|███████▊                               | 312/1568 [00:55<03:38,  5.76it/s]16 02:37:49 Save the image 00233D.png

 20%|███████▊                               | 313/1568 [00:55<03:37,  5.76it/s]16 02:37:49 Save the image 00233D_flip.png
 20%|███████▊                               | 314/1568 [00:55<03:37,  5.77it/s]16 02:37:49 Save the image 00234D.png
 20%|███████▊                               | 315/1568 [00:55<03:36,  5.80it/s]16 02:37:49 Save the image 00234D_flip.png
 20%|███████▊                               | 316/1568 [00:55<03:36,  5.79it/s]16 02:37:49 Save the image 00235D.png
 20%|███████▉                               | 317/1568 [00:56<03:36,  5.79it/s]16 02:37:49 Save the image 00235D_flip.png
 20%|███████▉                               | 318/1568 [00:56<03:35,  5.80it/s]16 02:37:50 Save the image 00236D.png
 20%|███████▉                               | 319/1568 [00:56<03:33,  5.84it/s]16 02:37:50 Save the image 00236D_flip.png
 20%|███████▉                               | 320/1568 [00:56<03:35,  5.79it/s]16 02:37:50 Save the image 00237D.png
 20%|███████▉                               | 321/1568 [00:56<03:37,  5.75it/s]16 02:37:50 Save the image 00237D_flip.png
 21%|████████                               | 322/1568 [00:56<03:36,  5.76it/s]16 02:37:50 Save the image 00238D.png
 21%|████████                               | 323/1568 [00:57<03:35,  5.76it/s]16 02:37:50 Save the image 00238D_flip.png
 21%|████████                               | 324/1568 [00:57<03:37,  5.71it/s]16 02:37:51 Save the image 00239D.png
 21%|████████                               | 325/1568 [00:57<03:37,  5.72it/s]16 02:37:51 Save the image 00239D_flip.png
 21%|████████                               | 326/1568 [00:57<03:36,  5.73it/s]16 02:37:51 Save the image 00240D.png
 21%|████████▏                              | 327/1568 [00:57<03:34,  5.78it/s]16 02:37:51 Save the image 00240D_flip.png
 21%|████████▏                              | 328/1568 [00:57<03:27,  5.97it/s]16 02:37:51 Save the image 00241D.png
 21%|████████▏                              | 329/1568 [00:58<03:31,  5.87it/s]16 02:37:51 Save the image 00241D_flip.png
 21%|████████▏                              | 330/1568 [00:58<03:32,  5.84it/s]16 02:37:52 Save the image 00242D.png
 21%|████████▏                              | 331/1568 [00:58<03:31,  5.84it/s]16 02:37:52 Save the image 00242D_flip.png
 21%|████████▎                              | 332/1568 [00:58<03:33,  5.79it/s]16 02:37:52 Save the image 00243D.png
 21%|████████▎                              | 333/1568 [00:58<03:34,  5.75it/s]16 02:37:52 Save the image 00243D_flip.png
 21%|████████▎                              | 334/1568 [00:58<03:34,  5.75it/s]16 02:37:52 Save the image 00244D.png
 21%|████████▎                              | 335/1568 [00:59<03:35,  5.72it/s]16 02:37:52 Save the image 00244D_flip.png
 21%|████████▎                              | 336/1568 [00:59<03:23,  6.05it/s]16 02:37:53 Save the image 00245D.png
 21%|████████▍                              | 337/1568 [00:59<03:27,  5.92it/s]16 02:37:53 Save the image 00245D_flip.png
 22%|████████▍                              | 338/1568 [00:59<03:28,  5.89it/s]16 02:37:53 Save the image 00246D.png
 22%|████████▍                              | 339/1568 [00:59<03:29,  5.88it/s]16 02:37:53 Save the image 00246D_flip.png
 22%|████████▍                              | 340/1568 [00:59<03:31,  5.80it/s]16 02:37:53 Save the image 00247D.png
 22%|████████▍                              | 341/1568 [01:00<03:30,  5.83it/s]16 02:37:54 Save the image 00247D_flip.png
 22%|████████▌                              | 342/1568 [01:00<03:32,  5.78it/s]16 02:37:54 Save the image 00248D.png
 22%|████████▌                              | 343/1568 [01:00<03:32,  5.78it/s]16 02:37:54 Save the image 00248D_flip.png
 22%|████████▌                              | 344/1568 [01:00<03:19,  6.15it/s]16 02:37:54 Save the image 00249D.png
 22%|████████▌                              | 345/1568 [01:00<03:24,  5.99it/s]16 02:37:54 Save the image 00249D_flip.png
 22%|████████▌                              | 346/1568 [01:00<03:27,  5.90it/s]16 02:37:54 Save the image 00250D.png
 22%|████████▋                              | 347/1568 [01:01<03:27,  5.88it/s]16 02:37:55 Save the image 00250D_flip.png
 22%|████████▋                              | 348/1568 [01:01<03:29,  5.82it/s]16 02:37:55 Save the image 00251D.png
 22%|████████▋                              | 349/1568 [01:01<03:28,  5.85it/s]16 02:37:55 Save the image 00251D_flip.png
 22%|████████▋                              | 350/1568 [01:01<03:30,  5.79it/s]16 02:37:55 Save the image 00252D.png
 22%|████████▋                              | 351/1568 [01:01<03:30,  5.77it/s]16 02:37:55 Save the image 00252D_flip.png
 22%|████████▊                              | 352/1568 [01:01<03:22,  6.01it/s]16 02:37:55 Save the image 00253D.png
 23%|████████▊                              | 353/1568 [01:02<03:25,  5.91it/s]16 02:37:56 Save the image 00253D_flip.png
 23%|████████▊                              | 354/1568 [01:02<03:26,  5.88it/s]16 02:37:56 Save the image 00254D.png
 23%|████████▊                              | 355/1568 [01:02<03:27,  5.85it/s]16 02:37:56 Save the image 00254D_flip.png
 23%|████████▊                              | 356/1568 [01:02<03:29,  5.79it/s]16 02:37:56 Save the image 00255D.png
 23%|████████▉                              | 357/1568 [01:02<03:27,  5.83it/s]16 02:37:56 Save the image 00255D_flip.png
 23%|████████▉                              | 358/1568 [01:03<03:29,  5.77it/s]16 02:37:56 Save the image 00256D.png
 23%|████████▉                              | 359/1568 [01:03<03:29,  5.76it/s]16 02:37:57 Save the image 00256D_flip.png
 23%|████████▉                              | 360/1568 [01:03<03:29,  5.76it/s]16 02:37:57 Save the image 00257D.png
 23%|████████▉                              | 361/1568 [01:03<03:29,  5.76it/s]16 02:37:57 Save the image 00257D_flip.png
 23%|█████████                              | 362/1568 [01:03<03:29,  5.76it/s]16 02:37:57 Save the image 00258D.png
 23%|█████████                              | 363/1568 [01:03<03:29,  5.76it/s]16 02:37:57 Save the image 00258D_flip.png
 23%|█████████                              | 364/1568 [01:04<03:29,  5.76it/s]16 02:37:57 Save the image 00259D.png
 23%|█████████                              | 365/1568 [01:04<03:27,  5.81it/s]16 02:37:58 Save the image 00259D_flip.png
 23%|█████████                              | 366/1568 [01:04<03:28,  5.77it/s]16 02:37:58 Save the image 00260D.png
 23%|█████████▏                             | 367/1568 [01:04<03:28,  5.75it/s]16 02:37:58 Save the image 00260D_flip.png
 23%|█████████▏                             | 368/1568 [01:04<03:29,  5.73it/s]16 02:37:58 Save the image 00261D.png
 24%|█████████▏                             | 369/1568 [01:04<03:28,  5.76it/s]16 02:37:58 Save the image 00261D_flip.png
 24%|█████████▏                             | 370/1568 [01:05<03:27,  5.78it/s]16 02:37:59 Save the image 00262D.png
 24%|█████████▏                             | 371/1568 [01:05<03:28,  5.75it/s]16 02:37:59 Save the image 00262D_flip.png
 24%|█████████▎                             | 372/1568 [01:05<03:28,  5.72it/s]16 02:37:59 Save the image 00263D.png
 24%|█████████▎                             | 373/1568 [01:05<03:28,  5.74it/s]16 02:37:59 Save the image 00263D_flip.png
 24%|█████████▎                             | 374/1568 [01:05<03:27,  5.75it/s]16 02:37:59 Save the image 00264D.png
 24%|█████████▎                             | 375/1568 [01:05<03:16,  6.08it/s]16 02:37:59 Save the image 00264D_flip.png
 24%|█████████▎                             | 376/1568 [01:06<03:20,  5.95it/s]16 02:38:00 Save the image 00265D.png

 24%|█████████▍                             | 377/1568 [01:06<03:21,  5.90it/s]16 02:38:00 Save the image 00265D_flip.png
 24%|█████████▍                             | 378/1568 [01:06<03:21,  5.90it/s]16 02:38:00 Save the image 00266D.png
 24%|█████████▍                             | 379/1568 [01:06<03:23,  5.83it/s]16 02:38:00 Save the image 00266D_flip.png
 24%|█████████▍                             | 380/1568 [01:06<03:25,  5.79it/s]16 02:38:00 Save the image 00267D.png
 24%|█████████▍                             | 381/1568 [01:07<03:25,  5.76it/s]16 02:38:00 Save the image 00267D_flip.png
 24%|█████████▌                             | 382/1568 [01:07<03:25,  5.78it/s]16 02:38:01 Save the image 00268D.png
 24%|█████████▌                             | 383/1568 [01:07<03:12,  6.16it/s]16 02:38:01 Save the image 00268D_flip.png
 24%|█████████▌                             | 384/1568 [01:07<03:17,  6.00it/s]16 02:38:01 Save the image 00269D.png
 25%|█████████▌                             | 385/1568 [01:07<03:18,  5.97it/s]16 02:38:01 Save the image 00269D_flip.png
 25%|█████████▌                             | 386/1568 [01:07<03:18,  5.96it/s]16 02:38:01 Save the image 00270D.png
 25%|█████████▋                             | 387/1568 [01:08<03:21,  5.86it/s]16 02:38:01 Save the image 00270D_flip.png
 25%|█████████▋                             | 388/1568 [01:08<03:23,  5.79it/s]16 02:38:02 Save the image 00271D.png
 25%|█████████▋                             | 389/1568 [01:08<03:24,  5.78it/s]16 02:38:02 Save the image 00271D_flip.png
 25%|█████████▋                             | 390/1568 [01:08<03:23,  5.79it/s]16 02:38:02 Save the image 00272D.png
 25%|█████████▋                             | 391/1568 [01:08<03:11,  6.15it/s]16 02:38:02 Save the image 00272D_flip.png
 25%|█████████▊                             | 392/1568 [01:08<03:16,  5.99it/s]16 02:38:02 Save the image 00273D.png
 25%|█████████▊                             | 393/1568 [01:09<03:17,  5.94it/s]16 02:38:02 Save the image 00273D_flip.png
 25%|█████████▊                             | 394/1568 [01:09<03:19,  5.88it/s]16 02:38:03 Save the image 00274D.png
 25%|█████████▊                             | 395/1568 [01:09<03:22,  5.81it/s]16 02:38:03 Save the image 00274D_flip.png
 25%|█████████▊                             | 396/1568 [01:09<03:23,  5.77it/s]16 02:38:03 Save the image 00275D.png
 25%|█████████▊                             | 397/1568 [01:09<03:24,  5.74it/s]16 02:38:03 Save the image 00275D_flip.png
 25%|█████████▉                             | 398/1568 [01:09<03:23,  5.75it/s]16 02:38:03 Save the image 00276D.png
 25%|█████████▉                             | 399/1568 [01:10<03:22,  5.76it/s]16 02:38:03 Save the image 00276D_flip.png
 26%|█████████▉                             | 400/1568 [01:10<03:22,  5.76it/s]16 02:38:04 Save the image 00277D.png
 26%|█████████▉                             | 401/1568 [01:10<03:21,  5.79it/s]16 02:38:04 Save the image 00277D_flip.png
 26%|█████████▉                             | 402/1568 [01:10<03:21,  5.79it/s]16 02:38:04 Save the image 00278D.png
 26%|██████████                             | 403/1568 [01:10<03:21,  5.78it/s]16 02:38:04 Save the image 00278D_flip.png
 26%|██████████                             | 404/1568 [01:10<03:20,  5.82it/s]16 02:38:04 Save the image 00279D.png
 26%|██████████                             | 405/1568 [01:11<03:19,  5.84it/s]16 02:38:04 Save the image 00279D_flip.png
 26%|██████████                             | 406/1568 [01:11<03:20,  5.78it/s]16 02:38:05 Save the image 00280D.png
 26%|██████████                             | 407/1568 [01:11<03:21,  5.75it/s]16 02:38:05 Save the image 00280D_flip.png
 26%|██████████▏                            | 408/1568 [01:11<03:21,  5.75it/s]16 02:38:05 Save the image 00281D.png
 26%|██████████▏                            | 409/1568 [01:11<03:20,  5.77it/s]16 02:38:05 Save the image 00281D_flip.png
 26%|██████████▏                            | 410/1568 [01:11<03:22,  5.72it/s]16 02:38:05 Save the image 00282D.png
 26%|██████████▏                            | 411/1568 [01:12<03:23,  5.70it/s]16 02:38:06 Save the image 00282D_flip.png
 26%|██████████▏                            | 412/1568 [01:12<03:23,  5.69it/s]16 02:38:06 Save the image 00283D.png
 26%|██████████▎                            | 413/1568 [01:12<03:20,  5.75it/s]16 02:38:06 Save the image 00283D_flip.png
 26%|██████████▎                            | 414/1568 [01:12<03:14,  5.93it/s]16 02:38:06 Save the image 00284D.png
 26%|██████████▎                            | 415/1568 [01:12<03:16,  5.87it/s]16 02:38:06 Save the image 00284D_flip.png
 27%|██████████▎                            | 416/1568 [01:13<03:17,  5.85it/s]16 02:38:06 Save the image 00285D.png
 27%|██████████▎                            | 417/1568 [01:13<03:16,  5.85it/s]16 02:38:07 Save the image 00285D_flip.png
 27%|██████████▍                            | 418/1568 [01:13<03:17,  5.82it/s]16 02:38:07 Save the image 00286D.png
 27%|██████████▍                            | 419/1568 [01:13<03:18,  5.80it/s]16 02:38:07 Save the image 00286D_flip.png
 27%|██████████▍                            | 420/1568 [01:13<03:17,  5.80it/s]16 02:38:07 Save the image 00287D.png
 27%|██████████▍                            | 421/1568 [01:13<03:18,  5.78it/s]16 02:38:07 Save the image 00287D_flip.png
 27%|██████████▍                            | 422/1568 [01:14<03:08,  6.08it/s]16 02:38:07 Save the image 00288D.png
 27%|██████████▌                            | 423/1568 [01:14<03:12,  5.94it/s]16 02:38:08 Save the image 00288D_flip.png
 27%|██████████▌                            | 424/1568 [01:14<03:13,  5.90it/s]16 02:38:08 Save the image 00289D.png
 27%|██████████▌                            | 425/1568 [01:14<03:14,  5.89it/s]16 02:38:08 Save the image 00289D_flip.png
 27%|██████████▌                            | 426/1568 [01:14<03:16,  5.82it/s]16 02:38:08 Save the image 00290D.png
 27%|██████████▌                            | 427/1568 [01:14<03:17,  5.78it/s]16 02:38:08 Save the image 00290D_flip.png
 27%|██████████▋                            | 428/1568 [01:15<03:16,  5.79it/s]16 02:38:08 Save the image 00291D.png
 27%|██████████▋                            | 429/1568 [01:15<03:17,  5.77it/s]16 02:38:09 Save the image 00291D_flip.png
 27%|██████████▋                            | 430/1568 [01:15<03:06,  6.12it/s]16 02:38:09 Save the image 00292D.png
 27%|██████████▋                            | 431/1568 [01:15<03:10,  5.97it/s]16 02:38:09 Save the image 00292D_flip.png
 28%|██████████▋                            | 432/1568 [01:15<03:11,  5.92it/s]16 02:38:09 Save the image 00293D.png
 28%|██████████▊                            | 433/1568 [01:15<03:12,  5.90it/s]16 02:38:09 Save the image 00293D_flip.png
 28%|██████████▊                            | 434/1568 [01:16<03:14,  5.82it/s]16 02:38:09 Save the image 00294D.png
 28%|██████████▊                            | 435/1568 [01:16<03:13,  5.84it/s]16 02:38:10 Save the image 00294D_flip.png
 28%|██████████▊                            | 436/1568 [01:16<03:15,  5.79it/s]16 02:38:10 Save the image 00295D.png
 28%|██████████▊                            | 437/1568 [01:16<03:15,  5.78it/s]16 02:38:10 Save the image 00295D_flip.png
 28%|██████████▉                            | 438/1568 [01:16<03:03,  6.16it/s]16 02:38:10 Save the image 00296D.png
 28%|██████████▉                            | 439/1568 [01:16<03:08,  5.99it/s]16 02:38:10 Save the image 00296D_flip.png
 28%|██████████▉                            | 440/1568 [01:17<03:09,  5.94it/s]16 02:38:10 Save the image 00297D.png

 28%|██████████▉                            | 441/1568 [01:17<03:10,  5.92it/s]16 02:38:11 Save the image 00297D_flip.png
 28%|██████████▉                            | 442/1568 [01:17<03:15,  5.77it/s]16 02:38:11 Save the image 00298D.png
 28%|███████████                            | 443/1568 [01:17<03:14,  5.79it/s]16 02:38:11 Save the image 00298D_flip.png
 28%|███████████                            | 444/1568 [01:17<03:15,  5.75it/s]16 02:38:11 Save the image 00299D.png
 28%|███████████                            | 445/1568 [01:17<03:14,  5.76it/s]16 02:38:11 Save the image 00299D_flip.png
 28%|███████████                            | 446/1568 [01:18<03:14,  5.78it/s]16 02:38:12 Save the image 00300D.png
 29%|███████████                            | 447/1568 [01:18<03:14,  5.77it/s]16 02:38:12 Save the image 00300D_flip.png
 29%|███████████▏                           | 448/1568 [01:18<03:12,  5.80it/s]16 02:38:12 Save the image 00301D.png
 29%|███████████▏                           | 449/1568 [01:18<03:13,  5.77it/s]16 02:38:12 Save the image 00301D_flip.png
 29%|███████████▏                           | 450/1568 [01:18<03:14,  5.74it/s]16 02:38:12 Save the image 00302D.png
 29%|███████████▏                           | 451/1568 [01:18<03:13,  5.78it/s]16 02:38:12 Save the image 00302D_flip.png
 29%|███████████▏                           | 452/1568 [01:19<03:11,  5.83it/s]16 02:38:13 Save the image 00303D.png
 29%|███████████▎                           | 453/1568 [01:19<03:12,  5.78it/s]16 02:38:13 Save the image 00303D_flip.png
 29%|███████████▎                           | 454/1568 [01:19<03:13,  5.77it/s]16 02:38:13 Save the image 00304D.png
 29%|███████████▎                           | 455/1568 [01:19<03:12,  5.77it/s]16 02:38:13 Save the image 00304D_flip.png
 29%|███████████▎                           | 456/1568 [01:19<03:12,  5.77it/s]16 02:38:13 Save the image 00305D.png
 29%|███████████▎                           | 457/1568 [01:20<03:12,  5.76it/s]16 02:38:13 Save the image 00305D_flip.png
 29%|███████████▍                           | 458/1568 [01:20<03:12,  5.76it/s]16 02:38:14 Save the image 00306D.png
 29%|███████████▍                           | 459/1568 [01:20<03:12,  5.76it/s]16 02:38:14 Save the image 00306D_flip.png
 29%|███████████▍                           | 460/1568 [01:20<03:10,  5.80it/s]16 02:38:14 Save the image 00307D.png
 29%|███████████▍                           | 461/1568 [01:20<03:06,  5.95it/s]16 02:38:14 Save the image 00307D_flip.png
 29%|███████████▍                           | 462/1568 [01:20<03:08,  5.87it/s]16 02:38:14 Save the image 00308D.png
 30%|███████████▌                           | 463/1568 [01:21<03:09,  5.84it/s]16 02:38:14 Save the image 00308D_flip.png
 30%|███████████▌                           | 464/1568 [01:21<03:09,  5.83it/s]16 02:38:15 Save the image 00309D.png
 30%|███████████▌                           | 465/1568 [01:21<03:10,  5.79it/s]16 02:38:15 Save the image 00309D_flip.png
 30%|███████████▌                           | 466/1568 [01:21<03:11,  5.75it/s]16 02:38:15 Save the image 00310D.png
 30%|███████████▌                           | 467/1568 [01:21<03:10,  5.78it/s]16 02:38:15 Save the image 00310D_flip.png
 30%|███████████▋                           | 468/1568 [01:21<03:10,  5.78it/s]16 02:38:15 Save the image 00311D.png
 30%|███████████▋                           | 469/1568 [01:22<02:59,  6.13it/s]16 02:38:15 Save the image 00311D_flip.png
 30%|███████████▋                           | 470/1568 [01:22<03:03,  5.97it/s]16 02:38:16 Save the image 00312D.png
 30%|███████████▋                           | 471/1568 [01:22<03:05,  5.93it/s]16 02:38:16 Save the image 00312D_flip.png
 30%|███████████▋                           | 472/1568 [01:22<03:08,  5.82it/s]16 02:38:16 Save the image 00313D.png
 30%|███████████▊                           | 473/1568 [01:22<03:09,  5.76it/s]16 02:38:16 Save the image 00313D_flip.png
 30%|███████████▊                           | 474/1568 [01:22<03:09,  5.77it/s]16 02:38:16 Save the image 00314D.png
 30%|███████████▊                           | 475/1568 [01:23<03:09,  5.76it/s]16 02:38:16 Save the image 00314D_flip.png
 30%|███████████▊                           | 476/1568 [01:23<03:09,  5.76it/s]16 02:38:17 Save the image 00315D.png
 30%|███████████▊                           | 477/1568 [01:23<02:59,  6.08it/s]16 02:38:17 Save the image 00315D_flip.png
 30%|███████████▉                           | 478/1568 [01:23<03:03,  5.94it/s]16 02:38:17 Save the image 00316D.png
 31%|███████████▉                           | 479/1568 [01:23<03:04,  5.90it/s]16 02:38:17 Save the image 00316D_flip.png
 31%|███████████▉                           | 480/1568 [01:23<03:05,  5.87it/s]16 02:38:17 Save the image 00317D.png
 31%|███████████▉                           | 481/1568 [01:24<03:07,  5.80it/s]16 02:38:18 Save the image 00317D_flip.png
 31%|███████████▉                           | 482/1568 [01:24<03:06,  5.83it/s]16 02:38:18 Save the image 00318D.png
 31%|████████████                           | 483/1568 [01:24<03:06,  5.81it/s]16 02:38:18 Save the image 00318D_flip.png
 31%|████████████                           | 484/1568 [01:24<03:07,  5.79it/s]16 02:38:18 Save the image 00319D.png
 31%|████████████                           | 485/1568 [01:24<02:57,  6.09it/s]16 02:38:18 Save the image 00319D_flip.png
 31%|████████████                           | 486/1568 [01:24<03:01,  5.96it/s]16 02:38:18 Save the image 00320D.png
 31%|████████████                           | 487/1568 [01:25<03:02,  5.91it/s]16 02:38:19 Save the image 00320D_flip.png
 31%|████████████▏                          | 488/1568 [01:25<03:03,  5.90it/s]16 02:38:19 Save the image 00321D.png
 31%|████████████▏                          | 489/1568 [01:25<03:05,  5.83it/s]16 02:38:19 Save the image 00321D_flip.png
 31%|████████████▏                          | 490/1568 [01:25<03:04,  5.86it/s]16 02:38:19 Save the image 00322D.png
 31%|████████████▏                          | 491/1568 [01:25<03:05,  5.79it/s]16 02:38:19 Save the image 00322D_flip.png
 31%|████████████▏                          | 492/1568 [01:26<03:06,  5.78it/s]16 02:38:19 Save the image 00323D.png
 31%|████████████▎                          | 493/1568 [01:26<03:06,  5.78it/s]16 02:38:20 Save the image 00323D_flip.png
 32%|████████████▎                          | 494/1568 [01:26<03:06,  5.77it/s]16 02:38:20 Save the image 00324D.png
 32%|████████████▎                          | 495/1568 [01:26<03:04,  5.80it/s]16 02:38:20 Save the image 00324D_flip.png
 32%|████████████▎                          | 496/1568 [01:26<03:05,  5.77it/s]16 02:38:20 Save the image 00325D.png
 32%|████████████▎                          | 497/1568 [01:26<03:05,  5.76it/s]16 02:38:20 Save the image 00325D_flip.png
 32%|████████████▍                          | 498/1568 [01:27<03:04,  5.81it/s]16 02:38:20 Save the image 00326D.png
 32%|████████████▍                          | 499/1568 [01:27<03:02,  5.84it/s]16 02:38:21 Save the image 00326D_flip.png
 32%|████████████▍                          | 500/1568 [01:27<03:04,  5.78it/s]16 02:38:21 Save the image 00327D.png
 32%|████████████▍                          | 501/1568 [01:27<03:05,  5.75it/s]16 02:38:21 Save the image 00327D_flip.png
 32%|████████████▍                          | 502/1568 [01:27<03:05,  5.76it/s]16 02:38:21 Save the image 00328D.png
 32%|████████████▌                          | 503/1568 [01:27<03:04,  5.76it/s]16 02:38:21 Save the image 00328D_flip.png
 32%|████████████▌                          | 504/1568 [01:28<03:06,  5.71it/s]16 02:38:21 Save the image 00329D.png

 32%|████████████▌                          | 505/1568 [01:28<03:07,  5.68it/s]16 02:38:22 Save the image 00329D_flip.png
 32%|████████████▌                          | 506/1568 [01:28<03:06,  5.70it/s]16 02:38:22 Save the image 00330D.png
 32%|████████████▌                          | 507/1568 [01:28<03:05,  5.72it/s]16 02:38:22 Save the image 00330D_flip.png
 32%|████████████▋                          | 508/1568 [01:28<02:54,  6.08it/s]16 02:38:22 Save the image 00331D.png
 32%|████████████▋                          | 509/1568 [01:28<02:58,  5.94it/s]16 02:38:22 Save the image 00331D_flip.png
 33%|████████████▋                          | 510/1568 [01:29<02:59,  5.89it/s]16 02:38:22 Save the image 00332D.png
 33%|████████████▋                          | 511/1568 [01:29<02:59,  5.89it/s]16 02:38:23 Save the image 00332D_flip.png
 33%|████████████▋                          | 512/1568 [01:29<03:01,  5.82it/s]16 02:38:23 Save the image 00333D.png
 33%|████████████▊                          | 513/1568 [01:29<03:02,  5.77it/s]16 02:38:23 Save the image 00333D_flip.png
 33%|████████████▊                          | 514/1568 [01:29<03:02,  5.76it/s]16 02:38:23 Save the image 00334D.png
 33%|████████████▊                          | 515/1568 [01:29<03:02,  5.75it/s]16 02:38:23 Save the image 00334D_flip.png
 33%|████████████▊                          | 516/1568 [01:30<02:52,  6.10it/s]16 02:38:23 Save the image 00335D.png
 33%|████████████▊                          | 517/1568 [01:30<02:56,  5.96it/s]16 02:38:24 Save the image 00335D_flip.png
 33%|████████████▉                          | 518/1568 [01:30<02:57,  5.91it/s]16 02:38:24 Save the image 00336D.png
 33%|████████████▉                          | 519/1568 [01:30<02:58,  5.88it/s]16 02:38:24 Save the image 00336D_flip.png
 33%|████████████▉                          | 520/1568 [01:30<03:00,  5.80it/s]16 02:38:24 Save the image 00337D.png
 33%|████████████▉                          | 521/1568 [01:30<02:59,  5.84it/s]16 02:38:24 Save the image 00337D_flip.png
 33%|████████████▉                          | 522/1568 [01:31<02:59,  5.81it/s]16 02:38:25 Save the image 00338D.png
 33%|█████████████                          | 523/1568 [01:31<03:00,  5.79it/s]16 02:38:25 Save the image 00338D_flip.png
 33%|█████████████                          | 524/1568 [01:31<02:50,  6.12it/s]16 02:38:25 Save the image 00339D.png
 33%|█████████████                          | 525/1568 [01:31<02:54,  5.97it/s]16 02:38:25 Save the image 00339D_flip.png
 34%|█████████████                          | 526/1568 [01:31<02:55,  5.92it/s]16 02:38:25 Save the image 00340D.png
 34%|█████████████                          | 527/1568 [01:31<02:56,  5.91it/s]16 02:38:25 Save the image 00340D_flip.png
 34%|█████████████▏                         | 528/1568 [01:32<02:58,  5.83it/s]16 02:38:26 Save the image 00341D.png
 34%|█████████████▏                         | 529/1568 [01:32<02:57,  5.85it/s]16 02:38:26 Save the image 00341D_flip.png
 34%|█████████████▏                         | 530/1568 [01:32<02:59,  5.79it/s]16 02:38:26 Save the image 00342D.png
 34%|█████████████▏                         | 531/1568 [01:32<02:59,  5.77it/s]16 02:38:26 Save the image 00342D_flip.png
 34%|█████████████▏                         | 532/1568 [01:32<02:57,  5.84it/s]16 02:38:26 Save the image 00343D.png
 34%|█████████████▎                         | 533/1568 [01:33<02:57,  5.82it/s]16 02:38:26 Save the image 00343D_flip.png
 34%|█████████████▎                         | 534/1568 [01:33<03:01,  5.68it/s]16 02:38:27 Save the image 00344D.png
 34%|█████████████▎                         | 535/1568 [01:33<03:02,  5.67it/s]16 02:38:27 Save the image 00344D_flip.png
 34%|█████████████▎                         | 536/1568 [01:33<03:01,  5.69it/s]16 02:38:27 Save the image 00345D.png
 34%|█████████████▎                         | 537/1568 [01:33<02:59,  5.75it/s]16 02:38:27 Save the image 00345D_flip.png
 34%|█████████████▍                         | 538/1568 [01:33<02:57,  5.79it/s]16 02:38:27 Save the image 00346D.png
 34%|█████████████▍                         | 539/1568 [01:34<02:57,  5.78it/s]16 02:38:27 Save the image 00346D_flip.png
 34%|█████████████▍                         | 540/1568 [01:34<02:58,  5.75it/s]16 02:38:28 Save the image 00347D.png
 35%|█████████████▍                         | 541/1568 [01:34<02:57,  5.78it/s]16 02:38:28 Save the image 00347D_flip.png
 35%|█████████████▍                         | 542/1568 [01:34<02:56,  5.80it/s]16 02:38:28 Save the image 00348D.png
 35%|█████████████▌                         | 543/1568 [01:34<02:57,  5.77it/s]16 02:38:28 Save the image 00348D_flip.png
 35%|█████████████▌                         | 544/1568 [01:34<02:57,  5.77it/s]16 02:38:28 Save the image 00349D.png
 35%|█████████████▌                         | 545/1568 [01:35<02:57,  5.75it/s]16 02:38:28 Save the image 00349D_flip.png
 35%|█████████████▌                         | 546/1568 [01:35<02:56,  5.79it/s]16 02:38:29 Save the image 00350D.png
 35%|█████████████▌                         | 547/1568 [01:35<02:51,  5.96it/s]16 02:38:29 Save the image 00350D_flip.png
 35%|█████████████▋                         | 548/1568 [01:35<02:53,  5.89it/s]16 02:38:29 Save the image 00351D.png
 35%|█████████████▋                         | 549/1568 [01:35<02:53,  5.86it/s]16 02:38:29 Save the image 00351D_flip.png
 35%|█████████████▋                         | 550/1568 [01:35<02:53,  5.86it/s]16 02:38:29 Save the image 00352D.png
 35%|█████████████▋                         | 551/1568 [01:36<02:55,  5.80it/s]16 02:38:30 Save the image 00352D_flip.png
 35%|█████████████▋                         | 552/1568 [01:36<02:56,  5.75it/s]16 02:38:30 Save the image 00353D.png
 35%|█████████████▊                         | 553/1568 [01:36<02:56,  5.76it/s]16 02:38:30 Save the image 00353D_flip.png
 35%|█████████████▊                         | 554/1568 [01:36<02:56,  5.76it/s]16 02:38:30 Save the image 00354D.png
 35%|█████████████▊                         | 555/1568 [01:36<02:46,  6.08it/s]16 02:38:30 Save the image 00354D_flip.png
 35%|█████████████▊                         | 556/1568 [01:36<02:50,  5.94it/s]16 02:38:30 Save the image 00355D.png
 36%|█████████████▊                         | 557/1568 [01:37<02:51,  5.90it/s]16 02:38:31 Save the image 00355D_flip.png
 36%|█████████████▉                         | 558/1568 [01:37<02:51,  5.89it/s]16 02:38:31 Save the image 00356D.png
 36%|█████████████▉                         | 559/1568 [01:37<02:53,  5.82it/s]16 02:38:31 Save the image 00356D_flip.png
 36%|█████████████▉                         | 560/1568 [01:37<02:53,  5.79it/s]16 02:38:31 Save the image 00357D.png
 36%|█████████████▉                         | 561/1568 [01:37<02:54,  5.78it/s]16 02:38:31 Save the image 00357D_flip.png
 36%|█████████████▉                         | 562/1568 [01:38<02:54,  5.76it/s]16 02:38:31 Save the image 00358D.png
 36%|██████████████                         | 563/1568 [01:38<02:45,  6.08it/s]16 02:38:32 Save the image 00358D_flip.png
 36%|██████████████                         | 564/1568 [01:38<02:50,  5.88it/s]16 02:38:32 Save the image 00359D.png
 36%|██████████████                         | 565/1568 [01:38<02:51,  5.86it/s]16 02:38:32 Save the image 00359D_flip.png
 36%|██████████████                         | 566/1568 [01:38<02:51,  5.85it/s]16 02:38:32 Save the image 00360D.png
 36%|██████████████                         | 567/1568 [01:38<02:52,  5.79it/s]16 02:38:32 Save the image 00360D_flip.png
 36%|██████████████▏                        | 568/1568 [01:39<02:51,  5.83it/s]16 02:38:32 Save the image 00361D.png

 36%|██████████████▏                        | 569/1568 [01:39<02:52,  5.78it/s]16 02:38:33 Save the image 00361D_flip.png
 36%|██████████████▏                        | 570/1568 [01:39<02:52,  5.77it/s]16 02:38:33 Save the image 00362D.png
 36%|██████████████▏                        | 571/1568 [01:39<02:52,  5.78it/s]16 02:38:33 Save the image 00362D_flip.png
 36%|██████████████▏                        | 572/1568 [01:39<02:52,  5.77it/s]16 02:38:33 Save the image 00363D.png
 37%|██████████████▎                        | 573/1568 [01:39<02:52,  5.78it/s]16 02:38:33 Save the image 00363D_flip.png
 37%|██████████████▎                        | 574/1568 [01:40<02:52,  5.76it/s]16 02:38:33 Save the image 00364D.png
 37%|██████████████▎                        | 575/1568 [01:40<02:52,  5.76it/s]16 02:38:34 Save the image 00364D_flip.png
 37%|██████████████▎                        | 576/1568 [01:40<02:51,  5.79it/s]16 02:38:34 Save the image 00365D.png
 37%|██████████████▎                        | 577/1568 [01:40<02:50,  5.82it/s]16 02:38:34 Save the image 00365D_flip.png
 37%|██████████████▍                        | 578/1568 [01:40<02:51,  5.77it/s]16 02:38:34 Save the image 00366D.png
 37%|██████████████▍                        | 579/1568 [01:40<02:52,  5.75it/s]16 02:38:34 Save the image 00366D_flip.png
 37%|██████████████▍                        | 580/1568 [01:41<02:51,  5.76it/s]16 02:38:35 Save the image 00367D.png
 37%|██████████████▍                        | 581/1568 [01:41<02:50,  5.78it/s]16 02:38:35 Save the image 00367D_flip.png
 37%|██████████████▍                        | 582/1568 [01:41<02:51,  5.74it/s]16 02:38:35 Save the image 00368D.png
 37%|██████████████▌                        | 583/1568 [01:41<02:51,  5.75it/s]16 02:38:35 Save the image 00368D_flip.png
 37%|██████████████▌                        | 584/1568 [01:41<02:50,  5.76it/s]16 02:38:35 Save the image 00369D.png
 37%|██████████████▌                        | 585/1568 [01:41<02:49,  5.80it/s]16 02:38:35 Save the image 00369D_flip.png
 37%|██████████████▌                        | 586/1568 [01:42<02:45,  5.92it/s]16 02:38:36 Save the image 00370D.png
 37%|██████████████▌                        | 587/1568 [01:42<02:48,  5.83it/s]16 02:38:36 Save the image 00370D_flip.png
 38%|██████████████▋                        | 588/1568 [01:42<02:48,  5.82it/s]16 02:38:36 Save the image 00371D.png
 38%|██████████████▋                        | 589/1568 [01:42<02:48,  5.83it/s]16 02:38:36 Save the image 00371D_flip.png
 38%|██████████████▋                        | 590/1568 [01:42<02:49,  5.77it/s]16 02:38:36 Save the image 00372D.png
 38%|██████████████▋                        | 591/1568 [01:43<02:50,  5.74it/s]16 02:38:36 Save the image 00372D_flip.png
 38%|██████████████▋                        | 592/1568 [01:43<02:49,  5.76it/s]16 02:38:37 Save the image 00373D.png
 38%|██████████████▋                        | 593/1568 [01:43<02:51,  5.68it/s]16 02:38:37 Save the image 00373D_flip.png
 38%|██████████████▊                        | 594/1568 [01:43<02:42,  6.01it/s]16 02:38:37 Save the image 00374D.png
 38%|██████████████▊                        | 595/1568 [01:43<02:44,  5.90it/s]16 02:38:37 Save the image 00374D_flip.png
 38%|██████████████▊                        | 596/1568 [01:43<02:45,  5.88it/s]16 02:38:37 Save the image 00375D.png
 38%|██████████████▊                        | 597/1568 [01:44<02:45,  5.87it/s]16 02:38:37 Save the image 00375D_flip.png
 38%|██████████████▊                        | 598/1568 [01:44<02:47,  5.81it/s]16 02:38:38 Save the image 00376D.png
 38%|██████████████▉                        | 599/1568 [01:44<02:45,  5.84it/s]16 02:38:38 Save the image 00376D_flip.png
 38%|██████████████▉                        | 600/1568 [01:44<02:46,  5.82it/s]16 02:38:38 Save the image 00377D.png
 38%|██████████████▉                        | 601/1568 [01:44<02:46,  5.80it/s]16 02:38:38 Save the image 00377D_flip.png
 38%|██████████████▉                        | 602/1568 [01:44<02:38,  6.09it/s]16 02:38:38 Save the image 00378D.png
 38%|██████████████▉                        | 603/1568 [01:45<02:41,  5.96it/s]16 02:38:38 Save the image 00378D_flip.png
 39%|███████████████                        | 604/1568 [01:45<02:43,  5.91it/s]16 02:38:39 Save the image 00379D.png
 39%|███████████████                        | 605/1568 [01:45<02:42,  5.91it/s]16 02:38:39 Save the image 00379D_flip.png
 39%|███████████████                        | 606/1568 [01:45<02:44,  5.86it/s]16 02:38:39 Save the image 00380D.png
 39%|███████████████                        | 607/1568 [01:45<02:42,  5.90it/s]16 02:38:39 Save the image 00380D_flip.png
 39%|███████████████                        | 608/1568 [01:45<02:44,  5.85it/s]16 02:38:39 Save the image 00381D.png
 39%|███████████████▏                       | 609/1568 [01:46<02:44,  5.82it/s]16 02:38:39 Save the image 00381D_flip.png
 39%|███████████████▏                       | 610/1568 [01:46<02:36,  6.12it/s]16 02:38:40 Save the image 00382D.png
 39%|███████████████▏                       | 611/1568 [01:46<02:40,  5.96it/s]16 02:38:40 Save the image 00382D_flip.png
 39%|███████████████▏                       | 612/1568 [01:46<02:41,  5.92it/s]16 02:38:40 Save the image 00383D.png
 39%|███████████████▏                       | 613/1568 [01:46<02:42,  5.88it/s]16 02:38:40 Save the image 00383D_flip.png
 39%|███████████████▎                       | 614/1568 [01:46<02:44,  5.81it/s]16 02:38:40 Save the image 00384D.png
 39%|███████████████▎                       | 615/1568 [01:47<02:42,  5.85it/s]16 02:38:40 Save the image 00384D_flip.png
 39%|███████████████▎                       | 616/1568 [01:47<02:45,  5.75it/s]16 02:38:41 Save the image 00385D.png
 39%|███████████████▎                       | 617/1568 [01:47<02:47,  5.68it/s]16 02:38:41 Save the image 00385D_flip.png
 39%|███████████████▎                       | 618/1568 [01:47<02:47,  5.67it/s]16 02:38:41 Save the image 00386D.png
 39%|███████████████▍                       | 619/1568 [01:47<02:48,  5.63it/s]16 02:38:41 Save the image 00386D_flip.png
 40%|███████████████▍                       | 620/1568 [01:47<02:47,  5.65it/s]16 02:38:41 Save the image 00387D.png
 40%|███████████████▍                       | 621/1568 [01:48<02:46,  5.68it/s]16 02:38:42 Save the image 00387D_flip.png
 40%|███████████████▍                       | 622/1568 [01:48<02:46,  5.70it/s]16 02:38:42 Save the image 00388D.png
 40%|███████████████▍                       | 623/1568 [01:48<02:45,  5.70it/s]16 02:38:42 Save the image 00388D_flip.png
 40%|███████████████▌                       | 624/1568 [01:48<02:44,  5.75it/s]16 02:38:42 Save the image 00389D.png
 40%|███████████████▌                       | 625/1568 [01:48<02:45,  5.71it/s]16 02:38:42 Save the image 00389D_flip.png
 40%|███████████████▌                       | 626/1568 [01:49<02:46,  5.65it/s]16 02:38:42 Save the image 00390D.png
 40%|███████████████▌                       | 627/1568 [01:49<02:47,  5.62it/s]16 02:38:43 Save the image 00390D_flip.png
 40%|███████████████▌                       | 628/1568 [01:49<02:46,  5.63it/s]16 02:38:43 Save the image 00391D.png
 40%|███████████████▋                       | 629/1568 [01:49<02:47,  5.62it/s]16 02:38:43 Save the image 00391D_flip.png
 40%|███████████████▋                       | 630/1568 [01:49<02:46,  5.63it/s]16 02:38:43 Save the image 00392D.png
 40%|███████████████▋                       | 631/1568 [01:49<02:45,  5.67it/s]16 02:38:43 Save the image 00392D_flip.png
 40%|███████████████▋                       | 632/1568 [01:50<02:43,  5.74it/s]16 02:38:43 Save the image 00393D.png

 40%|███████████████▋                       | 633/1568 [01:50<02:38,  5.91it/s]16 02:38:44 Save the image 00393D_flip.png
 40%|███████████████▊                       | 634/1568 [01:50<02:40,  5.83it/s]16 02:38:44 Save the image 00394D.png
 40%|███████████████▊                       | 635/1568 [01:50<02:40,  5.82it/s]16 02:38:44 Save the image 00394D_flip.png
 41%|███████████████▊                       | 636/1568 [01:50<02:41,  5.78it/s]16 02:38:44 Save the image 00395D.png
 41%|███████████████▊                       | 637/1568 [01:50<02:42,  5.74it/s]16 02:38:44 Save the image 00395D_flip.png
 41%|███████████████▊                       | 638/1568 [01:51<02:44,  5.67it/s]16 02:38:45 Save the image 00396D.png
 41%|███████████████▉                       | 639/1568 [01:51<02:44,  5.63it/s]16 02:38:45 Save the image 00396D_flip.png
 41%|███████████████▉                       | 640/1568 [01:51<02:45,  5.61it/s]16 02:38:45 Save the image 00397D.png
 41%|███████████████▉                       | 641/1568 [01:51<02:34,  5.99it/s]16 02:38:45 Save the image 00397D_flip.png
 41%|███████████████▉                       | 642/1568 [01:51<02:39,  5.82it/s]16 02:38:45 Save the image 00398D.png
 41%|███████████████▉                       | 643/1568 [01:52<02:40,  5.75it/s]16 02:38:45 Save the image 00398D_flip.png
 41%|████████████████                       | 644/1568 [01:52<02:41,  5.72it/s]16 02:38:46 Save the image 00399D.png
 41%|████████████████                       | 645/1568 [01:52<02:41,  5.71it/s]16 02:38:46 Save the image 00399D_flip.png
 41%|████████████████                       | 646/1568 [01:52<02:42,  5.68it/s]16 02:38:46 Save the image 00400D.png
 41%|████████████████                       | 647/1568 [01:52<02:43,  5.64it/s]16 02:38:46 Save the image 00400D_flip.png
 41%|████████████████                       | 648/1568 [01:52<02:43,  5.62it/s]16 02:38:46 Save the image 00401D.png
 41%|████████████████▏                      | 649/1568 [01:53<02:34,  5.93it/s]16 02:38:46 Save the image 00401D_flip.png
 41%|████████████████▏                      | 650/1568 [01:53<02:37,  5.83it/s]16 02:38:47 Save the image 00402D.png
 42%|████████████████▏                      | 651/1568 [01:53<02:39,  5.77it/s]16 02:38:47 Save the image 00402D_flip.png
 42%|████████████████▏                      | 652/1568 [01:53<02:40,  5.70it/s]16 02:38:47 Save the image 00403D.png
 42%|████████████████▏                      | 653/1568 [01:53<02:41,  5.67it/s]16 02:38:47 Save the image 00403D_flip.png
 42%|████████████████▎                      | 654/1568 [01:53<02:39,  5.73it/s]16 02:38:47 Save the image 00404D.png
 42%|████████████████▎                      | 655/1568 [01:54<02:39,  5.73it/s]16 02:38:47 Save the image 00404D_flip.png
 42%|████████████████▎                      | 656/1568 [01:54<02:38,  5.74it/s]16 02:38:48 Save the image 00405D.png
 42%|████████████████▎                      | 657/1568 [01:54<02:29,  6.09it/s]16 02:38:48 Save the image 00405D_flip.png
 42%|████████████████▎                      | 658/1568 [01:54<02:33,  5.95it/s]16 02:38:48 Save the image 00406D.png
 42%|████████████████▍                      | 659/1568 [01:54<02:33,  5.91it/s]16 02:38:48 Save the image 00406D_flip.png
 42%|████████████████▍                      | 660/1568 [01:54<02:34,  5.89it/s]16 02:38:48 Save the image 00407D.png
 42%|████████████████▍                      | 661/1568 [01:55<02:35,  5.82it/s]16 02:38:48 Save the image 00407D_flip.png
 42%|████████████████▍                      | 662/1568 [01:55<02:35,  5.84it/s]16 02:38:49 Save the image 00408D.png
 42%|████████████████▍                      | 663/1568 [01:55<02:36,  5.77it/s]16 02:38:49 Save the image 00408D_flip.png
 42%|████████████████▌                      | 664/1568 [01:55<02:38,  5.70it/s]16 02:38:49 Save the image 00409D.png
 42%|████████████████▌                      | 665/1568 [01:55<02:30,  6.01it/s]16 02:38:49 Save the image 00409D_flip.png
 42%|████████████████▌                      | 666/1568 [01:55<02:33,  5.88it/s]16 02:38:49 Save the image 00410D.png
 43%|████████████████▌                      | 667/1568 [01:56<02:33,  5.86it/s]16 02:38:50 Save the image 00410D_flip.png
 43%|████████████████▌                      | 668/1568 [01:56<02:34,  5.83it/s]16 02:38:50 Save the image 00411D.png
 43%|████████████████▋                      | 669/1568 [01:56<02:36,  5.73it/s]16 02:38:50 Save the image 00411D_flip.png
 43%|████████████████▋                      | 670/1568 [01:56<02:37,  5.69it/s]16 02:38:50 Save the image 00412D.png
 43%|████████████████▋                      | 671/1568 [01:56<02:37,  5.71it/s]16 02:38:50 Save the image 00412D_flip.png
 43%|████████████████▋                      | 672/1568 [01:57<02:38,  5.66it/s]16 02:38:50 Save the image 00413D.png
 43%|████████████████▋                      | 673/1568 [01:57<02:29,  5.97it/s]16 02:38:51 Save the image 00413D_flip.png
 43%|████████████████▊                      | 674/1568 [01:57<02:32,  5.87it/s]16 02:38:51 Save the image 00414D.png
 43%|████████████████▊                      | 675/1568 [01:57<02:32,  5.86it/s]16 02:38:51 Save the image 00414D_flip.png
 43%|████████████████▊                      | 676/1568 [01:57<02:31,  5.87it/s]16 02:38:51 Save the image 00415D.png
 43%|████████████████▊                      | 677/1568 [01:57<02:33,  5.80it/s]16 02:38:51 Save the image 00415D_flip.png
 43%|████████████████▊                      | 678/1568 [01:58<02:31,  5.86it/s]16 02:38:51 Save the image 00416D.png
 43%|████████████████▉                      | 679/1568 [01:58<02:32,  5.83it/s]16 02:38:52 Save the image 00416D_flip.png
 43%|████████████████▉                      | 680/1568 [01:58<02:33,  5.80it/s]16 02:38:52 Save the image 00417D.png
 43%|████████████████▉                      | 681/1568 [01:58<02:25,  6.09it/s]16 02:38:52 Save the image 00417D_flip.png
 43%|████████████████▉                      | 682/1568 [01:58<02:28,  5.95it/s]16 02:38:52 Save the image 00418D.png
 44%|████████████████▉                      | 683/1568 [01:58<02:29,  5.91it/s]16 02:38:52 Save the image 00418D_flip.png
 44%|█████████████████                      | 684/1568 [01:59<02:31,  5.83it/s]16 02:38:52 Save the image 00419D.png
 44%|█████████████████                      | 685/1568 [01:59<02:33,  5.76it/s]16 02:38:53 Save the image 00419D_flip.png
 44%|█████████████████                      | 686/1568 [01:59<02:33,  5.75it/s]16 02:38:53 Save the image 00420D.png
 44%|█████████████████                      | 687/1568 [01:59<02:34,  5.70it/s]16 02:38:53 Save the image 00420D_flip.png
 44%|█████████████████                      | 688/1568 [01:59<02:35,  5.65it/s]16 02:38:53 Save the image 00421D.png
 44%|█████████████████▏                     | 689/1568 [01:59<02:27,  5.97it/s]16 02:38:53 Save the image 00421D_flip.png
 44%|█████████████████▏                     | 690/1568 [02:00<02:30,  5.85it/s]16 02:38:53 Save the image 00422D.png
 44%|█████████████████▏                     | 691/1568 [02:00<02:30,  5.84it/s]16 02:38:54 Save the image 00422D_flip.png
 44%|█████████████████▏                     | 692/1568 [02:00<02:30,  5.83it/s]16 02:38:54 Save the image 00423D.png
 44%|█████████████████▏                     | 693/1568 [02:00<02:30,  5.80it/s]16 02:38:54 Save the image 00423D_flip.png
 44%|█████████████████▎                     | 694/1568 [02:00<02:31,  5.76it/s]16 02:38:54 Save the image 00424D.png
 44%|█████████████████▎                     | 695/1568 [02:00<02:32,  5.73it/s]16 02:38:54 Save the image 00424D_flip.png
 44%|█████████████████▎                     | 696/1568 [02:01<02:32,  5.73it/s]16 02:38:54 Save the image 00425D.png

 44%|█████████████████▎                     | 697/1568 [02:01<02:22,  6.12it/s]16 02:38:55 Save the image 00425D_flip.png
 45%|█████████████████▎                     | 698/1568 [02:01<02:25,  5.98it/s]16 02:38:55 Save the image 00426D.png
 45%|█████████████████▍                     | 699/1568 [02:01<02:26,  5.93it/s]16 02:38:55 Save the image 00426D_flip.png
 45%|█████████████████▍                     | 700/1568 [02:01<02:27,  5.90it/s]16 02:38:55 Save the image 00427D.png
 45%|█████████████████▍                     | 701/1568 [02:01<02:28,  5.83it/s]16 02:38:55 Save the image 00427D_flip.png
 45%|█████████████████▍                     | 702/1568 [02:02<02:27,  5.87it/s]16 02:38:56 Save the image 00428D.png
 45%|█████████████████▍                     | 703/1568 [02:02<02:29,  5.80it/s]16 02:38:56 Save the image 00428D_flip.png
 45%|█████████████████▌                     | 704/1568 [02:02<02:29,  5.78it/s]16 02:38:56 Save the image 00429D.png
 45%|█████████████████▌                     | 705/1568 [02:02<02:21,  6.10it/s]16 02:38:56 Save the image 00429D_flip.png
 45%|█████████████████▌                     | 706/1568 [02:02<02:24,  5.96it/s]16 02:38:56 Save the image 00430D.png
 45%|█████████████████▌                     | 707/1568 [02:02<02:25,  5.91it/s]16 02:38:56 Save the image 00430D_flip.png
 45%|█████████████████▌                     | 708/1568 [02:03<02:25,  5.92it/s]16 02:38:57 Save the image 00431D.png
 45%|█████████████████▋                     | 709/1568 [02:03<02:26,  5.85it/s]16 02:38:57 Save the image 00431D_flip.png
 45%|█████████████████▋                     | 710/1568 [02:03<02:26,  5.87it/s]16 02:38:57 Save the image 00432D.png
 45%|█████████████████▋                     | 711/1568 [02:03<02:27,  5.80it/s]16 02:38:57 Save the image 00432D_flip.png
 45%|█████████████████▋                     | 712/1568 [02:03<02:29,  5.74it/s]16 02:38:57 Save the image 00433D.png
 45%|█████████████████▋                     | 713/1568 [02:03<02:20,  6.08it/s]16 02:38:57 Save the image 00433D_flip.png
 46%|█████████████████▊                     | 714/1568 [02:04<02:24,  5.90it/s]16 02:38:58 Save the image 00434D.png
 46%|█████████████████▊                     | 715/1568 [02:04<02:25,  5.86it/s]16 02:38:58 Save the image 00434D_flip.png
 46%|█████████████████▊                     | 716/1568 [02:04<02:26,  5.82it/s]16 02:38:58 Save the image 00435D.png
 46%|█████████████████▊                     | 717/1568 [02:04<02:28,  5.74it/s]16 02:38:58 Save the image 00435D_flip.png
 46%|█████████████████▊                     | 718/1568 [02:04<02:27,  5.76it/s]16 02:38:58 Save the image 00436D.png
 46%|█████████████████▉                     | 719/1568 [02:05<02:27,  5.76it/s]16 02:38:58 Save the image 00436D_flip.png
 46%|█████████████████▉                     | 720/1568 [02:05<02:27,  5.76it/s]16 02:38:59 Save the image 00437D.png
 46%|█████████████████▉                     | 721/1568 [02:05<02:18,  6.13it/s]16 02:38:59 Save the image 00437D_flip.png
 46%|█████████████████▉                     | 722/1568 [02:05<02:21,  5.99it/s]16 02:38:59 Save the image 00438D.png
 46%|█████████████████▉                     | 723/1568 [02:05<02:22,  5.94it/s]16 02:38:59 Save the image 00438D_flip.png
 46%|██████████████████                     | 724/1568 [02:05<02:23,  5.89it/s]16 02:38:59 Save the image 00439D.png
 46%|██████████████████                     | 725/1568 [02:06<02:25,  5.81it/s]16 02:38:59 Save the image 00439D_flip.png
 46%|██████████████████                     | 726/1568 [02:06<02:25,  5.80it/s]16 02:39:00 Save the image 00440D.png
 46%|██████████████████                     | 727/1568 [02:06<02:26,  5.74it/s]16 02:39:00 Save the image 00440D_flip.png
 46%|██████████████████                     | 728/1568 [02:06<02:26,  5.73it/s]16 02:39:00 Save the image 00441D.png
 46%|██████████████████▏                    | 729/1568 [02:06<02:18,  6.04it/s]16 02:39:00 Save the image 00441D_flip.png
 47%|██████████████████▏                    | 730/1568 [02:06<02:21,  5.92it/s]16 02:39:00 Save the image 00442D.png
 47%|██████████████████▏                    | 731/1568 [02:07<02:22,  5.89it/s]16 02:39:00 Save the image 00442D_flip.png
 47%|██████████████████▏                    | 732/1568 [02:07<02:22,  5.88it/s]16 02:39:01 Save the image 00443D.png
 47%|██████████████████▏                    | 733/1568 [02:07<02:23,  5.82it/s]16 02:39:01 Save the image 00443D_flip.png
 47%|██████████████████▎                    | 734/1568 [02:07<02:24,  5.79it/s]16 02:39:01 Save the image 00444D.png
 47%|██████████████████▎                    | 735/1568 [02:07<02:24,  5.75it/s]16 02:39:01 Save the image 00444D_flip.png
 47%|██████████████████▎                    | 736/1568 [02:07<02:26,  5.70it/s]16 02:39:01 Save the image 00445D.png
 47%|██████████████████▎                    | 737/1568 [02:08<02:25,  5.69it/s]16 02:39:02 Save the image 00445D_flip.png
 47%|██████████████████▎                    | 738/1568 [02:08<02:25,  5.72it/s]16 02:39:02 Save the image 00446D.png
 47%|██████████████████▍                    | 739/1568 [02:08<02:24,  5.73it/s]16 02:39:02 Save the image 00446D_flip.png
 47%|██████████████████▍                    | 740/1568 [02:08<02:26,  5.66it/s]16 02:39:02 Save the image 00447D.png
 47%|██████████████████▍                    | 741/1568 [02:08<02:25,  5.67it/s]16 02:39:02 Save the image 00447D_flip.png
 47%|██████████████████▍                    | 742/1568 [02:09<02:25,  5.68it/s]16 02:39:02 Save the image 00448D.png
 47%|██████████████████▍                    | 743/1568 [02:09<02:23,  5.73it/s]16 02:39:03 Save the image 00448D_flip.png
 47%|██████████████████▌                    | 744/1568 [02:09<02:24,  5.71it/s]16 02:39:03 Save the image 00449D.png
 48%|██████████████████▌                    | 745/1568 [02:09<02:24,  5.69it/s]16 02:39:03 Save the image 00449D_flip.png
 48%|██████████████████▌                    | 746/1568 [02:09<02:25,  5.66it/s]16 02:39:03 Save the image 00450D.png
 48%|██████████████████▌                    | 747/1568 [02:09<02:24,  5.70it/s]16 02:39:03 Save the image 00450D_flip.png
 48%|██████████████████▌                    | 748/1568 [02:10<02:23,  5.70it/s]16 02:39:03 Save the image 00451D.png
 48%|██████████████████▋                    | 749/1568 [02:10<02:24,  5.68it/s]16 02:39:04 Save the image 00451D_flip.png
 48%|██████████████████▋                    | 750/1568 [02:10<02:24,  5.65it/s]16 02:39:04 Save the image 00452D.png
 48%|██████████████████▋                    | 751/1568 [02:10<02:23,  5.69it/s]16 02:39:04 Save the image 00452D_flip.png
 48%|██████████████████▋                    | 752/1568 [02:10<02:23,  5.70it/s]16 02:39:04 Save the image 00453D.png
 48%|██████████████████▋                    | 753/1568 [02:10<02:23,  5.69it/s]16 02:39:04 Save the image 00453D_flip.png
 48%|██████████████████▊                    | 754/1568 [02:11<02:22,  5.72it/s]16 02:39:04 Save the image 00454D.png
 48%|██████████████████▊                    | 755/1568 [02:11<02:21,  5.76it/s]16 02:39:05 Save the image 00454D_flip.png
 48%|██████████████████▊                    | 756/1568 [02:11<02:21,  5.73it/s]16 02:39:05 Save the image 00455D.png
 48%|██████████████████▊                    | 757/1568 [02:11<02:22,  5.71it/s]16 02:39:05 Save the image 00455D_flip.png
 48%|██████████████████▊                    | 758/1568 [02:11<02:21,  5.71it/s]16 02:39:05 Save the image 00456D.png
 48%|██████████████████▉                    | 759/1568 [02:11<02:21,  5.71it/s]16 02:39:05 Save the image 00456D_flip.png
 48%|██████████████████▉                    | 760/1568 [02:12<02:13,  6.05it/s]16 02:39:06 Save the image 00457D.png

 49%|██████████████████▉                    | 761/1568 [02:12<02:16,  5.92it/s]16 02:39:06 Save the image 00457D_flip.png
 49%|██████████████████▉                    | 762/1568 [02:12<02:17,  5.88it/s]16 02:39:06 Save the image 00458D.png
 49%|██████████████████▉                    | 763/1568 [02:12<02:18,  5.81it/s]16 02:39:06 Save the image 00458D_flip.png
 49%|███████████████████                    | 764/1568 [02:12<02:19,  5.78it/s]16 02:39:06 Save the image 00459D.png
 49%|███████████████████                    | 765/1568 [02:13<02:18,  5.82it/s]16 02:39:06 Save the image 00459D_flip.png
 49%|███████████████████                    | 766/1568 [02:13<02:18,  5.80it/s]16 02:39:07 Save the image 00460D.png
 49%|███████████████████                    | 767/1568 [02:13<02:18,  5.79it/s]16 02:39:07 Save the image 00460D_flip.png
 49%|███████████████████                    | 768/1568 [02:13<02:11,  6.07it/s]16 02:39:07 Save the image 00461D.png
 49%|███████████████████▏                   | 769/1568 [02:13<02:13,  5.97it/s]16 02:39:07 Save the image 00461D_flip.png
 49%|███████████████████▏                   | 770/1568 [02:13<02:14,  5.92it/s]16 02:39:07 Save the image 00462D.png
 49%|███████████████████▏                   | 771/1568 [02:14<02:15,  5.89it/s]16 02:39:07 Save the image 00462D_flip.png
 49%|███████████████████▏                   | 772/1568 [02:14<02:16,  5.82it/s]16 02:39:08 Save the image 00463D.png
 49%|███████████████████▏                   | 773/1568 [02:14<02:16,  5.84it/s]16 02:39:08 Save the image 00463D_flip.png
 49%|███████████████████▎                   | 774/1568 [02:14<02:17,  5.79it/s]16 02:39:08 Save the image 00464D.png
 49%|███████████████████▎                   | 775/1568 [02:14<02:17,  5.78it/s]16 02:39:08 Save the image 00464D_flip.png
 49%|███████████████████▎                   | 776/1568 [02:14<02:16,  5.79it/s]16 02:39:08 Save the image 00465D.png
 50%|███████████████████▎                   | 777/1568 [02:15<02:16,  5.78it/s]16 02:39:08 Save the image 00465D_flip.png
 50%|███████████████████▎                   | 778/1568 [02:15<02:16,  5.78it/s]16 02:39:09 Save the image 00466D.png
 50%|███████████████████▍                   | 779/1568 [02:15<02:17,  5.74it/s]16 02:39:09 Save the image 00466D_flip.png
 50%|███████████████████▍                   | 780/1568 [02:15<02:17,  5.73it/s]16 02:39:09 Save the image 00478D.png
 50%|███████████████████▍                   | 781/1568 [02:15<02:15,  5.79it/s]16 02:39:09 Save the image 00478D_flip.png
 50%|███████████████████▍                   | 782/1568 [02:15<02:15,  5.80it/s]16 02:39:09 Save the image 00479D.png
 50%|███████████████████▍                   | 783/1568 [02:16<02:16,  5.77it/s]16 02:39:09 Save the image 00479D_flip.png
 50%|███████████████████▌                   | 784/1568 [02:16<02:16,  5.76it/s]16 02:39:10 Save the image 00480D.png
 50%|███████████████████▌                   | 785/1568 [02:16<02:15,  5.77it/s]16 02:39:10 Save the image 00480D_flip.png
 50%|███████████████████▌                   | 786/1568 [02:16<02:15,  5.77it/s]16 02:39:10 Save the image 00481D.png
 50%|███████████████████▌                   | 787/1568 [02:16<02:16,  5.74it/s]16 02:39:10 Save the image 00481D_flip.png
 50%|███████████████████▌                   | 788/1568 [02:16<02:16,  5.71it/s]16 02:39:10 Save the image 00482D.png
 50%|███████████████████▌                   | 789/1568 [02:17<02:16,  5.71it/s]16 02:39:11 Save the image 00482D_flip.png
 50%|███████████████████▋                   | 790/1568 [02:17<02:14,  5.77it/s]16 02:39:11 Save the image 00483D.png
 50%|███████████████████▋                   | 791/1568 [02:17<02:10,  5.95it/s]16 02:39:11 Save the image 00483D_flip.png
 51%|███████████████████▋                   | 792/1568 [02:17<02:12,  5.84it/s]16 02:39:11 Save the image 00484D.png
 51%|███████████████████▋                   | 793/1568 [02:17<02:13,  5.82it/s]16 02:39:11 Save the image 00484D_flip.png
 51%|███████████████████▋                   | 794/1568 [02:18<02:13,  5.79it/s]16 02:39:11 Save the image 00485D.png
 51%|███████████████████▊                   | 795/1568 [02:18<02:14,  5.73it/s]16 02:39:12 Save the image 00485D_flip.png
 51%|███████████████████▊                   | 796/1568 [02:18<02:15,  5.70it/s]16 02:39:12 Save the image 00486D.png
 51%|███████████████████▊                   | 797/1568 [02:18<02:15,  5.68it/s]16 02:39:12 Save the image 00486D_flip.png
 51%|███████████████████▊                   | 798/1568 [02:18<02:15,  5.67it/s]16 02:39:12 Save the image 00487D.png
 51%|███████████████████▊                   | 799/1568 [02:18<02:06,  6.09it/s]16 02:39:12 Save the image 00487D_flip.png
 51%|███████████████████▉                   | 800/1568 [02:19<02:09,  5.95it/s]16 02:39:12 Save the image 00488D.png
 51%|███████████████████▉                   | 801/1568 [02:19<02:09,  5.91it/s]16 02:39:13 Save the image 00488D_flip.png
 51%|███████████████████▉                   | 802/1568 [02:19<02:10,  5.88it/s]16 02:39:13 Save the image 00489D.png
 51%|███████████████████▉                   | 803/1568 [02:19<02:13,  5.75it/s]16 02:39:13 Save the image 00489D_flip.png
 51%|███████████████████▉                   | 804/1568 [02:19<02:13,  5.72it/s]16 02:39:13 Save the image 00490D.png
 51%|████████████████████                   | 805/1568 [02:19<02:13,  5.70it/s]16 02:39:13 Save the image 00490D_flip.png
 51%|████████████████████                   | 806/1568 [02:20<02:13,  5.71it/s]16 02:39:13 Save the image 00491D.png
 51%|████████████████████                   | 807/1568 [02:20<02:05,  6.06it/s]16 02:39:14 Save the image 00491D_flip.png
 52%|████████████████████                   | 808/1568 [02:20<02:08,  5.94it/s]16 02:39:14 Save the image 00492D.png
 52%|████████████████████                   | 809/1568 [02:20<02:08,  5.88it/s]16 02:39:14 Save the image 00492D_flip.png
 52%|████████████████████▏                  | 810/1568 [02:20<02:09,  5.86it/s]16 02:39:14 Save the image 00493D.png
 52%|████████████████████▏                  | 811/1568 [02:20<02:10,  5.79it/s]16 02:39:14 Save the image 00493D_flip.png
 52%|████████████████████▏                  | 812/1568 [02:21<02:11,  5.76it/s]16 02:39:14 Save the image 00494D.png
 52%|████████████████████▏                  | 813/1568 [02:21<02:12,  5.70it/s]16 02:39:15 Save the image 00494D_flip.png
 52%|████████████████████▏                  | 814/1568 [02:21<02:12,  5.68it/s]16 02:39:15 Save the image 00495D.png
 52%|████████████████████▎                  | 815/1568 [02:21<02:04,  6.05it/s]16 02:39:15 Save the image 00495D_flip.png
 52%|████████████████████▎                  | 816/1568 [02:21<02:06,  5.96it/s]16 02:39:15 Save the image 00496D.png
 52%|████████████████████▎                  | 817/1568 [02:21<02:07,  5.91it/s]16 02:39:15 Save the image 00496D_flip.png
 52%|████████████████████▎                  | 818/1568 [02:22<02:07,  5.89it/s]16 02:39:15 Save the image 00497D.png
 52%|████████████████████▎                  | 819/1568 [02:22<02:09,  5.80it/s]16 02:39:16 Save the image 00497D_flip.png
 52%|████████████████████▍                  | 820/1568 [02:22<02:08,  5.82it/s]16 02:39:16 Save the image 00003N.png
 52%|████████████████████▍                  | 821/1568 [02:22<02:09,  5.78it/s]16 02:39:16 Save the image 00003N_flip.png
 52%|████████████████████▍                  | 822/1568 [02:22<02:09,  5.77it/s]16 02:39:16 Save the image 00004N.png
 52%|████████████████████▍                  | 823/1568 [02:22<02:09,  5.76it/s]16 02:39:16 Save the image 00004N_flip.png
 53%|████████████████████▍                  | 824/1568 [02:23<02:10,  5.69it/s]16 02:39:17 Save the image 00005N.png

 53%|████████████████████▌                  | 825/1568 [02:23<02:10,  5.69it/s]16 02:39:17 Save the image 00005N_flip.png
 53%|████████████████████▌                  | 826/1568 [02:23<02:11,  5.62it/s]16 02:39:17 Save the image 00006N.png
 53%|████████████████████▌                  | 827/1568 [02:23<02:12,  5.60it/s]16 02:39:17 Save the image 00006N_flip.png
 53%|████████████████████▌                  | 828/1568 [02:23<02:11,  5.65it/s]16 02:39:17 Save the image 00007N.png
 53%|████████████████████▌                  | 829/1568 [02:24<02:09,  5.70it/s]16 02:39:17 Save the image 00007N_flip.png
 53%|████████████████████▋                  | 830/1568 [02:24<02:10,  5.67it/s]16 02:39:18 Save the image 00008N.png
 53%|████████████████████▋                  | 831/1568 [02:24<02:09,  5.68it/s]16 02:39:18 Save the image 00008N_flip.png
 53%|████████████████████▋                  | 832/1568 [02:24<02:09,  5.70it/s]16 02:39:18 Save the image 00009N.png
 53%|████████████████████▋                  | 833/1568 [02:24<02:08,  5.71it/s]16 02:39:18 Save the image 00009N_flip.png
 53%|████████████████████▋                  | 834/1568 [02:24<02:08,  5.70it/s]16 02:39:18 Save the image 00010N.png
 53%|████████████████████▊                  | 835/1568 [02:25<02:09,  5.68it/s]16 02:39:18 Save the image 00010N_flip.png
 53%|████████████████████▊                  | 836/1568 [02:25<02:07,  5.73it/s]16 02:39:19 Save the image 00011N.png
 53%|████████████████████▊                  | 837/1568 [02:25<02:06,  5.77it/s]16 02:39:19 Save the image 00011N_flip.png
 53%|████████████████████▊                  | 838/1568 [02:25<02:08,  5.68it/s]16 02:39:19 Save the image 00012N.png
 54%|████████████████████▊                  | 839/1568 [02:25<02:08,  5.67it/s]16 02:39:19 Save the image 00012N_flip.png
 54%|████████████████████▉                  | 840/1568 [02:25<02:07,  5.70it/s]16 02:39:19 Save the image 00013N.png
 54%|████████████████████▉                  | 841/1568 [02:26<02:07,  5.72it/s]16 02:39:20 Save the image 00013N_flip.png
 54%|████████████████████▉                  | 842/1568 [02:26<02:07,  5.68it/s]16 02:39:20 Save the image 00014N.png
 54%|████████████████████▉                  | 843/1568 [02:26<02:07,  5.67it/s]16 02:39:20 Save the image 00014N_flip.png
 54%|████████████████████▉                  | 844/1568 [02:26<02:07,  5.68it/s]16 02:39:20 Save the image 00015N.png
 54%|█████████████████████                  | 845/1568 [02:26<02:06,  5.73it/s]16 02:39:20 Save the image 00015N_flip.png
 54%|█████████████████████                  | 846/1568 [02:27<02:05,  5.73it/s]16 02:39:20 Save the image 00016N.png
 54%|█████████████████████                  | 847/1568 [02:27<02:06,  5.71it/s]16 02:39:21 Save the image 00016N_flip.png
 54%|█████████████████████                  | 848/1568 [02:27<02:06,  5.69it/s]16 02:39:21 Save the image 00017N.png
 54%|█████████████████████                  | 849/1568 [02:27<02:05,  5.71it/s]16 02:39:21 Save the image 00017N_flip.png
 54%|█████████████████████▏                 | 850/1568 [02:27<02:06,  5.68it/s]16 02:39:21 Save the image 00018N.png
 54%|█████████████████████▏                 | 851/1568 [02:27<02:06,  5.66it/s]16 02:39:21 Save the image 00018N_flip.png
 54%|█████████████████████▏                 | 852/1568 [02:28<02:06,  5.64it/s]16 02:39:21 Save the image 00019N.png
 54%|█████████████████████▏                 | 853/1568 [02:28<02:06,  5.64it/s]16 02:39:22 Save the image 00019N_flip.png
 54%|█████████████████████▏                 | 854/1568 [02:28<01:59,  6.00it/s]16 02:39:22 Save the image 00020N.png
 55%|█████████████████████▎                 | 855/1568 [02:28<02:02,  5.80it/s]16 02:39:22 Save the image 00020N_flip.png
 55%|█████████████████████▎                 | 856/1568 [02:28<02:03,  5.78it/s]16 02:39:22 Save the image 00021N.png
 55%|█████████████████████▎                 | 857/1568 [02:28<02:02,  5.80it/s]16 02:39:22 Save the image 00021N_flip.png
 55%|█████████████████████▎                 | 858/1568 [02:29<02:04,  5.71it/s]16 02:39:23 Save the image 00022N.png
 55%|█████████████████████▎                 | 859/1568 [02:29<02:04,  5.68it/s]16 02:39:23 Save the image 00022N_flip.png
 55%|█████████████████████▍                 | 860/1568 [02:29<02:05,  5.66it/s]16 02:39:23 Save the image 00023N.png
 55%|█████████████████████▍                 | 861/1568 [02:29<02:03,  5.74it/s]16 02:39:23 Save the image 00023N_flip.png
 55%|█████████████████████▍                 | 862/1568 [02:29<01:58,  5.98it/s]16 02:39:23 Save the image 00024N.png
 55%|█████████████████████▍                 | 863/1568 [02:29<02:00,  5.86it/s]16 02:39:23 Save the image 00024N_flip.png
 55%|█████████████████████▍                 | 864/1568 [02:30<02:00,  5.85it/s]16 02:39:24 Save the image 00025N.png
 55%|█████████████████████▌                 | 865/1568 [02:30<01:59,  5.86it/s]16 02:39:24 Save the image 00025N_flip.png
 55%|█████████████████████▌                 | 866/1568 [02:30<02:01,  5.79it/s]16 02:39:24 Save the image 00026N.png
 55%|█████████████████████▌                 | 867/1568 [02:30<02:01,  5.76it/s]16 02:39:24 Save the image 00026N_flip.png
 55%|█████████████████████▌                 | 868/1568 [02:30<02:01,  5.78it/s]16 02:39:24 Save the image 00027N.png
 55%|█████████████████████▌                 | 869/1568 [02:31<02:01,  5.78it/s]16 02:39:24 Save the image 00027N_flip.png
 55%|█████████████████████▋                 | 870/1568 [02:31<01:54,  6.09it/s]16 02:39:25 Save the image 00028N.png
 56%|█████████████████████▋                 | 871/1568 [02:31<01:57,  5.96it/s]16 02:39:25 Save the image 00028N_flip.png
 56%|█████████████████████▋                 | 872/1568 [02:31<01:57,  5.90it/s]16 02:39:25 Save the image 00029N.png
 56%|█████████████████████▋                 | 873/1568 [02:31<01:58,  5.86it/s]16 02:39:25 Save the image 00029N_flip.png
 56%|█████████████████████▋                 | 874/1568 [02:31<01:59,  5.80it/s]16 02:39:25 Save the image 00030N.png
 56%|█████████████████████▊                 | 875/1568 [02:32<01:59,  5.80it/s]16 02:39:25 Save the image 00030N_flip.png
 56%|█████████████████████▊                 | 876/1568 [02:32<01:59,  5.80it/s]16 02:39:26 Save the image 00031N.png
 56%|█████████████████████▊                 | 877/1568 [02:32<01:58,  5.81it/s]16 02:39:26 Save the image 00031N_flip.png
 56%|█████████████████████▊                 | 878/1568 [02:32<01:52,  6.12it/s]16 02:39:26 Save the image 00032N.png
 56%|█████████████████████▊                 | 879/1568 [02:32<01:55,  5.98it/s]16 02:39:26 Save the image 00032N_flip.png
 56%|█████████████████████▉                 | 880/1568 [02:32<01:56,  5.92it/s]16 02:39:26 Save the image 00033N.png
 56%|█████████████████████▉                 | 881/1568 [02:33<01:57,  5.86it/s]16 02:39:26 Save the image 00033N_flip.png
 56%|█████████████████████▉                 | 882/1568 [02:33<01:59,  5.76it/s]16 02:39:27 Save the image 00034N.png
 56%|█████████████████████▉                 | 883/1568 [02:33<02:00,  5.69it/s]16 02:39:27 Save the image 00034N_flip.png
 56%|█████████████████████▉                 | 884/1568 [02:33<02:00,  5.68it/s]16 02:39:27 Save the image 00035N.png
 56%|██████████████████████                 | 885/1568 [02:33<02:00,  5.67it/s]16 02:39:27 Save the image 00035N_flip.png
 57%|██████████████████████                 | 886/1568 [02:33<01:53,  6.03it/s]16 02:39:27 Save the image 00036N.png
 57%|██████████████████████                 | 887/1568 [02:34<01:55,  5.90it/s]16 02:39:27 Save the image 00036N_flip.png
 57%|██████████████████████                 | 888/1568 [02:34<01:55,  5.89it/s]16 02:39:28 Save the image 00037N.png

 57%|██████████████████████                 | 889/1568 [02:34<01:57,  5.79it/s]16 02:39:28 Save the image 00037N_flip.png
 57%|██████████████████████▏                | 890/1568 [02:34<01:58,  5.70it/s]16 02:39:28 Save the image 00038N.png
 57%|██████████████████████▏                | 891/1568 [02:34<01:59,  5.68it/s]16 02:39:28 Save the image 00038N_flip.png
 57%|██████████████████████▏                | 892/1568 [02:34<01:59,  5.65it/s]16 02:39:28 Save the image 00039N.png
 57%|██████████████████████▏                | 893/1568 [02:35<01:59,  5.65it/s]16 02:39:28 Save the image 00039N_flip.png
 57%|██████████████████████▏                | 894/1568 [02:35<01:51,  6.05it/s]16 02:39:29 Save the image 00040N.png
 57%|██████████████████████▎                | 895/1568 [02:35<01:53,  5.94it/s]16 02:39:29 Save the image 00040N_flip.png
 57%|██████████████████████▎                | 896/1568 [02:35<01:53,  5.90it/s]16 02:39:29 Save the image 00041N.png
 57%|██████████████████████▎                | 897/1568 [02:35<01:54,  5.88it/s]16 02:39:29 Save the image 00041N_flip.png
 57%|██████████████████████▎                | 898/1568 [02:35<01:55,  5.82it/s]16 02:39:29 Save the image 00042N.png
 57%|██████████████████████▎                | 899/1568 [02:36<01:55,  5.79it/s]16 02:39:30 Save the image 00042N_flip.png
 57%|██████████████████████▍                | 900/1568 [02:36<01:55,  5.79it/s]16 02:39:30 Save the image 00043N.png
 57%|██████████████████████▍                | 901/1568 [02:36<01:55,  5.80it/s]16 02:39:30 Save the image 00043N_flip.png
 58%|██████████████████████▍                | 902/1568 [02:36<01:48,  6.16it/s]16 02:39:30 Save the image 00044N.png
 58%|██████████████████████▍                | 903/1568 [02:36<01:51,  5.98it/s]16 02:39:30 Save the image 00044N_flip.png
 58%|██████████████████████▍                | 904/1568 [02:36<01:51,  5.93it/s]16 02:39:30 Save the image 00047N.png
 58%|██████████████████████▌                | 905/1568 [02:37<01:52,  5.91it/s]16 02:39:31 Save the image 00047N_flip.png
 58%|██████████████████████▌                | 906/1568 [02:37<01:53,  5.83it/s]16 02:39:31 Save the image 00048N.png
 58%|██████████████████████▌                | 907/1568 [02:37<01:53,  5.81it/s]16 02:39:31 Save the image 00048N_flip.png
 58%|██████████████████████▌                | 908/1568 [02:37<01:54,  5.76it/s]16 02:39:31 Save the image 00049N.png
 58%|██████████████████████▌                | 909/1568 [02:37<01:54,  5.78it/s]16 02:39:31 Save the image 00049N_flip.png
 58%|██████████████████████▋                | 910/1568 [02:37<01:47,  6.10it/s]16 02:39:31 Save the image 00050N.png
 58%|██████████████████████▋                | 911/1568 [02:38<01:50,  5.96it/s]16 02:39:32 Save the image 00050N_flip.png
 58%|██████████████████████▋                | 912/1568 [02:38<01:50,  5.91it/s]16 02:39:32 Save the image 00051N.png
 58%|██████████████████████▋                | 913/1568 [02:38<01:50,  5.90it/s]16 02:39:32 Save the image 00051N_flip.png
 58%|██████████████████████▋                | 914/1568 [02:38<01:52,  5.83it/s]16 02:39:32 Save the image 00052N.png
 58%|██████████████████████▊                | 915/1568 [02:38<01:52,  5.81it/s]16 02:39:32 Save the image 00052N_flip.png
 58%|██████████████████████▊                | 916/1568 [02:39<01:53,  5.76it/s]16 02:39:32 Save the image 00053N.png
 58%|██████████████████████▊                | 917/1568 [02:39<01:52,  5.77it/s]16 02:39:33 Save the image 00053N_flip.png
 59%|██████████████████████▊                | 918/1568 [02:39<01:52,  5.80it/s]16 02:39:33 Save the image 00054N.png
 59%|██████████████████████▊                | 919/1568 [02:39<01:51,  5.80it/s]16 02:39:33 Save the image 00054N_flip.png
 59%|██████████████████████▉                | 920/1568 [02:39<01:51,  5.80it/s]16 02:39:33 Save the image 00678N.png
 59%|██████████████████████▉                | 921/1568 [02:39<01:51,  5.80it/s]16 02:39:33 Save the image 00678N_flip.png
 59%|██████████████████████▉                | 922/1568 [02:40<01:51,  5.77it/s]16 02:39:33 Save the image 00679N.png
 59%|██████████████████████▉                | 923/1568 [02:40<01:51,  5.80it/s]16 02:39:34 Save the image 00679N_flip.png
 59%|██████████████████████▉                | 924/1568 [02:40<01:50,  5.84it/s]16 02:39:34 Save the image 00680N.png
 59%|███████████████████████                | 925/1568 [02:40<01:51,  5.78it/s]16 02:39:34 Save the image 00680N_flip.png
 59%|███████████████████████                | 926/1568 [02:40<01:51,  5.75it/s]16 02:39:34 Save the image 00681N.png
 59%|███████████████████████                | 927/1568 [02:40<01:51,  5.75it/s]16 02:39:34 Save the image 00681N_flip.png
 59%|███████████████████████                | 928/1568 [02:41<01:50,  5.78it/s]16 02:39:34 Save the image 00682N.png
 59%|███████████████████████                | 929/1568 [02:41<01:51,  5.75it/s]16 02:39:35 Save the image 00682N_flip.png
 59%|███████████████████████▏               | 930/1568 [02:41<01:50,  5.75it/s]16 02:39:35 Save the image 00683N.png
 59%|███████████████████████▏               | 931/1568 [02:41<01:50,  5.75it/s]16 02:39:35 Save the image 00683N_flip.png
 59%|███████████████████████▏               | 932/1568 [02:41<01:49,  5.80it/s]16 02:39:35 Save the image 00684N.png
 60%|███████████████████████▏               | 933/1568 [02:41<01:47,  5.93it/s]16 02:39:35 Save the image 00684N_flip.png
 60%|███████████████████████▏               | 934/1568 [02:42<01:48,  5.86it/s]16 02:39:36 Save the image 00685N.png
 60%|███████████████████████▎               | 935/1568 [02:42<01:49,  5.79it/s]16 02:39:36 Save the image 00685N_flip.png
 60%|███████████████████████▎               | 936/1568 [02:42<01:48,  5.82it/s]16 02:39:36 Save the image 00686N.png
 60%|███████████████████████▎               | 937/1568 [02:42<01:49,  5.77it/s]16 02:39:36 Save the image 00686N_flip.png
 60%|███████████████████████▎               | 938/1568 [02:42<01:49,  5.74it/s]16 02:39:36 Save the image 00687N.png
 60%|███████████████████████▎               | 939/1568 [02:43<01:49,  5.75it/s]16 02:39:36 Save the image 00687N_flip.png
 60%|███████████████████████▍               | 940/1568 [02:43<01:49,  5.72it/s]16 02:39:37 Save the image 00688N.png
 60%|███████████████████████▍               | 941/1568 [02:43<01:44,  6.02it/s]16 02:39:37 Save the image 00688N_flip.png
 60%|███████████████████████▍               | 942/1568 [02:43<01:45,  5.91it/s]16 02:39:37 Save the image 00689N.png
 60%|███████████████████████▍               | 943/1568 [02:43<01:46,  5.87it/s]16 02:39:37 Save the image 00689N_flip.png
 60%|███████████████████████▍               | 944/1568 [02:43<01:45,  5.90it/s]16 02:39:37 Save the image 00690N.png
 60%|███████████████████████▌               | 945/1568 [02:44<01:46,  5.83it/s]16 02:39:37 Save the image 00690N_flip.png
 60%|███████████████████████▌               | 946/1568 [02:44<01:47,  5.77it/s]16 02:39:38 Save the image 00691N.png
 60%|███████████████████████▌               | 947/1568 [02:44<01:47,  5.77it/s]16 02:39:38 Save the image 00691N_flip.png
 60%|███████████████████████▌               | 948/1568 [02:44<01:48,  5.73it/s]16 02:39:38 Save the image 00692N.png
 61%|███████████████████████▌               | 949/1568 [02:44<01:41,  6.10it/s]16 02:39:38 Save the image 00692N_flip.png
 61%|███████████████████████▋               | 950/1568 [02:44<01:43,  5.96it/s]16 02:39:38 Save the image 00693N.png
 61%|███████████████████████▋               | 951/1568 [02:45<01:44,  5.91it/s]16 02:39:38 Save the image 00693N_flip.png
 61%|███████████████████████▋               | 952/1568 [02:45<01:46,  5.81it/s]16 02:39:39 Save the image 00694N.png

 61%|███████████████████████▋               | 953/1568 [02:45<01:47,  5.72it/s]16 02:39:39 Save the image 00694N_flip.png
 61%|███████████████████████▋               | 954/1568 [02:45<01:48,  5.67it/s]16 02:39:39 Save the image 00695N.png
 61%|███████████████████████▊               | 955/1568 [02:45<01:48,  5.66it/s]16 02:39:39 Save the image 00695N_flip.png
 61%|███████████████████████▊               | 956/1568 [02:45<01:47,  5.69it/s]16 02:39:39 Save the image 00696N.png
 61%|███████████████████████▊               | 957/1568 [02:46<01:41,  6.04it/s]16 02:39:39 Save the image 00696N_flip.png
 61%|███████████████████████▊               | 958/1568 [02:46<01:43,  5.91it/s]16 02:39:40 Save the image 00697N.png
 61%|███████████████████████▊               | 959/1568 [02:46<01:43,  5.87it/s]16 02:39:40 Save the image 00697N_flip.png
 61%|███████████████████████▉               | 960/1568 [02:46<01:43,  5.86it/s]16 02:39:40 Save the image 00698N.png
 61%|███████████████████████▉               | 961/1568 [02:46<01:45,  5.76it/s]16 02:39:40 Save the image 00698N_flip.png
 61%|███████████████████████▉               | 962/1568 [02:46<01:46,  5.68it/s]16 02:39:40 Save the image 00699N.png
 61%|███████████████████████▉               | 963/1568 [02:47<01:46,  5.67it/s]16 02:39:41 Save the image 00699N_flip.png
 61%|███████████████████████▉               | 964/1568 [02:47<01:46,  5.65it/s]16 02:39:41 Save the image 00700N.png
 62%|████████████████████████               | 965/1568 [02:47<01:40,  6.01it/s]16 02:39:41 Save the image 00700N_flip.png
 62%|████████████████████████               | 966/1568 [02:47<01:42,  5.88it/s]16 02:39:41 Save the image 00701N.png
 62%|████████████████████████               | 967/1568 [02:47<01:42,  5.85it/s]16 02:39:41 Save the image 00701N_flip.png
 62%|████████████████████████               | 968/1568 [02:47<01:42,  5.85it/s]16 02:39:41 Save the image 00702N.png
 62%|████████████████████████               | 969/1568 [02:48<01:42,  5.83it/s]16 02:39:42 Save the image 00702N_flip.png
 62%|████████████████████████▏              | 970/1568 [02:48<01:43,  5.78it/s]16 02:39:42 Save the image 00703N.png
 62%|████████████████████████▏              | 971/1568 [02:48<01:43,  5.77it/s]16 02:39:42 Save the image 00703N_flip.png
 62%|████████████████████████▏              | 972/1568 [02:48<01:43,  5.76it/s]16 02:39:42 Save the image 00704N.png
 62%|████████████████████████▏              | 973/1568 [02:48<01:37,  6.11it/s]16 02:39:42 Save the image 00704N_flip.png
 62%|████████████████████████▏              | 974/1568 [02:49<01:39,  5.96it/s]16 02:39:42 Save the image 00705N.png
 62%|████████████████████████▎              | 975/1568 [02:49<01:40,  5.92it/s]16 02:39:43 Save the image 00705N_flip.png
 62%|████████████████████████▎              | 976/1568 [02:49<01:41,  5.83it/s]16 02:39:43 Save the image 00706N.png
 62%|████████████████████████▎              | 977/1568 [02:49<01:42,  5.78it/s]16 02:39:43 Save the image 00706N_flip.png
 62%|████████████████████████▎              | 978/1568 [02:49<01:41,  5.83it/s]16 02:39:43 Save the image 00707N.png
 62%|████████████████████████▎              | 979/1568 [02:49<01:41,  5.81it/s]16 02:39:43 Save the image 00707N_flip.png
 62%|████████████████████████▍              | 980/1568 [02:50<01:41,  5.79it/s]16 02:39:43 Save the image 00708N.png
 63%|████████████████████████▍              | 981/1568 [02:50<01:35,  6.14it/s]16 02:39:44 Save the image 00708N_flip.png
 63%|████████████████████████▍              | 982/1568 [02:50<01:37,  5.99it/s]16 02:39:44 Save the image 00709N.png
 63%|████████████████████████▍              | 983/1568 [02:50<01:38,  5.93it/s]16 02:39:44 Save the image 00709N_flip.png
 63%|████████████████████████▍              | 984/1568 [02:50<01:38,  5.91it/s]16 02:39:44 Save the image 00710N.png
 63%|████████████████████████▍              | 985/1568 [02:50<01:40,  5.83it/s]16 02:39:44 Save the image 00710N_flip.png
 63%|████████████████████████▌              | 986/1568 [02:51<01:39,  5.85it/s]16 02:39:44 Save the image 00711N.png
 63%|████████████████████████▌              | 987/1568 [02:51<01:40,  5.79it/s]16 02:39:45 Save the image 00711N_flip.png
 63%|████████████████████████▌              | 988/1568 [02:51<01:40,  5.79it/s]16 02:39:45 Save the image 00712N.png
 63%|████████████████████████▌              | 989/1568 [02:51<01:39,  5.80it/s]16 02:39:45 Save the image 00712N_flip.png
 63%|████████████████████████▌              | 990/1568 [02:51<01:40,  5.77it/s]16 02:39:45 Save the image 00713N.png
 63%|████████████████████████▋              | 991/1568 [02:51<01:39,  5.80it/s]16 02:39:45 Save the image 00713N_flip.png
 63%|████████████████████████▋              | 992/1568 [02:52<01:39,  5.79it/s]16 02:39:45 Save the image 00714N.png
 63%|████████████████████████▋              | 993/1568 [02:52<01:39,  5.78it/s]16 02:39:46 Save the image 00714N_flip.png
 63%|████████████████████████▋              | 994/1568 [02:52<01:38,  5.82it/s]16 02:39:46 Save the image 00715N.png
 63%|████████████████████████▋              | 995/1568 [02:52<01:37,  5.86it/s]16 02:39:46 Save the image 00715N_flip.png
 64%|████████████████████████▊              | 996/1568 [02:52<01:38,  5.82it/s]16 02:39:46 Save the image 00716N.png
 64%|████████████████████████▊              | 997/1568 [02:52<01:38,  5.81it/s]16 02:39:46 Save the image 00716N_flip.png
 64%|████████████████████████▊              | 998/1568 [02:53<01:38,  5.81it/s]16 02:39:46 Save the image 00717N.png
 64%|████████████████████████▊              | 999/1568 [02:53<01:37,  5.82it/s]16 02:39:47 Save the image 00717N_flip.png
 64%|████████████████████████▏             | 1000/1568 [02:53<01:37,  5.80it/s]16 02:39:47 Save the image 00718N.png
 64%|████████████████████████▎             | 1001/1568 [02:53<01:37,  5.79it/s]16 02:39:47 Save the image 00718N_flip.png
 64%|████████████████████████▎             | 1002/1568 [02:53<01:37,  5.79it/s]16 02:39:47 Save the image 00719N.png
 64%|████████████████████████▎             | 1003/1568 [02:53<01:36,  5.85it/s]16 02:39:47 Save the image 00719N_flip.png
 64%|████████████████████████▎             | 1004/1568 [02:54<01:36,  5.84it/s]16 02:39:48 Save the image 00720N.png
 64%|████████████████████████▎             | 1005/1568 [02:54<01:37,  5.78it/s]16 02:39:48 Save the image 00720N_flip.png
 64%|████████████████████████▍             | 1006/1568 [02:54<01:37,  5.74it/s]16 02:39:48 Save the image 00721N.png
 64%|████████████████████████▍             | 1007/1568 [02:54<01:37,  5.77it/s]16 02:39:48 Save the image 00721N_flip.png
 64%|████████████████████████▍             | 1008/1568 [02:54<01:37,  5.73it/s]16 02:39:48 Save the image 00722N.png
 64%|████████████████████████▍             | 1009/1568 [02:55<01:37,  5.71it/s]16 02:39:48 Save the image 00722N_flip.png
 64%|████████████████████████▍             | 1010/1568 [02:55<01:37,  5.73it/s]16 02:39:49 Save the image 00723N.png
 64%|████████████████████████▌             | 1011/1568 [02:55<01:37,  5.73it/s]16 02:39:49 Save the image 00723N_flip.png
 65%|████████████████████████▌             | 1012/1568 [02:55<01:31,  6.10it/s]16 02:39:49 Save the image 00724N.png
 65%|████████████████████████▌             | 1013/1568 [02:55<01:33,  5.96it/s]16 02:39:49 Save the image 00724N_flip.png
 65%|████████████████████████▌             | 1014/1568 [02:55<01:33,  5.91it/s]16 02:39:49 Save the image 00725N.png
 65%|████████████████████████▌             | 1015/1568 [02:56<01:34,  5.87it/s]16 02:39:49 Save the image 00725N_flip.png
 65%|████████████████████████▌             | 1016/1568 [02:56<01:34,  5.81it/s]16 02:39:50 Save the image 00726N.png

 65%|████████████████████████▋             | 1017/1568 [02:56<01:34,  5.81it/s]16 02:39:50 Save the image 00726N_flip.png
 65%|████████████████████████▋             | 1018/1568 [02:56<01:34,  5.80it/s]16 02:39:50 Save the image 00727N.png
 65%|████████████████████████▋             | 1019/1568 [02:56<01:34,  5.81it/s]16 02:39:50 Save the image 00727N_flip.png
 65%|████████████████████████▋             | 1020/1568 [02:56<01:28,  6.20it/s]16 02:39:50 Save the image 00728N.png
 65%|████████████████████████▋             | 1021/1568 [02:57<01:30,  6.04it/s]16 02:39:50 Save the image 00728N_flip.png
 65%|████████████████████████▊             | 1022/1568 [02:57<01:31,  5.97it/s]16 02:39:51 Save the image 00729N.png
 65%|████████████████████████▊             | 1023/1568 [02:57<01:31,  5.94it/s]16 02:39:51 Save the image 00729N_flip.png
 65%|████████████████████████▊             | 1024/1568 [02:57<01:33,  5.84it/s]16 02:39:51 Save the image 00730N.png
 65%|████████████████████████▊             | 1025/1568 [02:57<01:33,  5.83it/s]16 02:39:51 Save the image 00730N_flip.png
 65%|████████████████████████▊             | 1026/1568 [02:57<01:32,  5.83it/s]16 02:39:51 Save the image 00731N.png
 65%|████████████████████████▉             | 1027/1568 [02:58<01:32,  5.82it/s]16 02:39:51 Save the image 00731N_flip.png
 66%|████████████████████████▉             | 1028/1568 [02:58<01:28,  6.13it/s]16 02:39:52 Save the image 00732N.png
 66%|████████████████████████▉             | 1029/1568 [02:58<01:30,  5.98it/s]16 02:39:52 Save the image 00732N_flip.png
 66%|████████████████████████▉             | 1030/1568 [02:58<01:30,  5.92it/s]16 02:39:52 Save the image 00733N.png
 66%|████████████████████████▉             | 1031/1568 [02:58<01:31,  5.89it/s]16 02:39:52 Save the image 00733N_flip.png
 66%|█████████████████████████             | 1032/1568 [02:58<01:32,  5.82it/s]16 02:39:52 Save the image 00734N.png
 66%|█████████████████████████             | 1033/1568 [02:59<01:31,  5.87it/s]16 02:39:52 Save the image 00734N_flip.png
 66%|█████████████████████████             | 1034/1568 [02:59<01:31,  5.81it/s]16 02:39:53 Save the image 00735N.png
 66%|█████████████████████████             | 1035/1568 [02:59<01:31,  5.80it/s]16 02:39:53 Save the image 00735N_flip.png
 66%|█████████████████████████             | 1036/1568 [02:59<01:28,  6.03it/s]16 02:39:53 Save the image 00736N.png
 66%|█████████████████████████▏            | 1037/1568 [02:59<01:29,  5.91it/s]16 02:39:53 Save the image 00736N_flip.png
 66%|█████████████████████████▏            | 1038/1568 [02:59<01:30,  5.88it/s]16 02:39:53 Save the image 00737N.png
 66%|█████████████████████████▏            | 1039/1568 [03:00<01:30,  5.86it/s]16 02:39:53 Save the image 00737N_flip.png
 66%|█████████████████████████▏            | 1040/1568 [03:00<01:31,  5.80it/s]16 02:39:54 Save the image 00738N.png
 66%|█████████████████████████▏            | 1041/1568 [03:00<01:30,  5.84it/s]16 02:39:54 Save the image 00738N_flip.png
 66%|█████████████████████████▎            | 1042/1568 [03:00<01:31,  5.78it/s]16 02:39:54 Save the image 00739N.png
 67%|█████████████████████████▎            | 1043/1568 [03:00<01:30,  5.79it/s]16 02:39:54 Save the image 00739N_flip.png
 67%|█████████████████████████▎            | 1044/1568 [03:00<01:31,  5.75it/s]16 02:39:54 Save the image 00740N.png
 67%|█████████████████████████▎            | 1045/1568 [03:01<01:30,  5.75it/s]16 02:39:55 Save the image 00740N_flip.png
 67%|█████████████████████████▎            | 1046/1568 [03:01<01:30,  5.79it/s]16 02:39:55 Save the image 00741N.png
 67%|█████████████████████████▎            | 1047/1568 [03:01<01:30,  5.77it/s]16 02:39:55 Save the image 00741N_flip.png
 67%|█████████████████████████▍            | 1048/1568 [03:01<01:30,  5.76it/s]16 02:39:55 Save the image 00742N.png
 67%|█████████████████████████▍            | 1049/1568 [03:01<01:29,  5.80it/s]16 02:39:55 Save the image 00742N_flip.png
 67%|█████████████████████████▍            | 1050/1568 [03:02<01:28,  5.84it/s]16 02:39:55 Save the image 00743N.png
 67%|█████████████████████████▍            | 1051/1568 [03:02<01:29,  5.78it/s]16 02:39:56 Save the image 00743N_flip.png
 67%|█████████████████████████▍            | 1052/1568 [03:02<01:29,  5.79it/s]16 02:39:56 Save the image 00744N.png
 67%|█████████████████████████▌            | 1053/1568 [03:02<01:28,  5.81it/s]16 02:39:56 Save the image 00744N_flip.png
 67%|█████████████████████████▌            | 1054/1568 [03:02<01:28,  5.83it/s]16 02:39:56 Save the image 00745N.png
 67%|█████████████████████████▌            | 1055/1568 [03:02<01:28,  5.77it/s]16 02:39:56 Save the image 00745N_flip.png
 67%|█████████████████████████▌            | 1056/1568 [03:03<01:28,  5.78it/s]16 02:39:56 Save the image 00746N.png
 67%|█████████████████████████▌            | 1057/1568 [03:03<01:28,  5.78it/s]16 02:39:57 Save the image 00746N_flip.png
 67%|█████████████████████████▋            | 1058/1568 [03:03<01:27,  5.81it/s]16 02:39:57 Save the image 00747N.png
 68%|█████████████████████████▋            | 1059/1568 [03:03<01:26,  5.90it/s]16 02:39:57 Save the image 00747N_flip.png
 68%|█████████████████████████▋            | 1060/1568 [03:03<01:27,  5.84it/s]16 02:39:57 Save the image 00748N.png
 68%|█████████████████████████▋            | 1061/1568 [03:03<01:27,  5.82it/s]16 02:39:57 Save the image 00748N_flip.png
 68%|█████████████████████████▋            | 1062/1568 [03:04<01:27,  5.80it/s]16 02:39:57 Save the image 00749N.png
 68%|█████████████████████████▊            | 1063/1568 [03:04<01:27,  5.77it/s]16 02:39:58 Save the image 00749N_flip.png
 68%|█████████████████████████▊            | 1064/1568 [03:04<01:28,  5.72it/s]16 02:39:58 Save the image 00750N.png
 68%|█████████████████████████▊            | 1065/1568 [03:04<01:27,  5.73it/s]16 02:39:58 Save the image 00750N_flip.png
 68%|█████████████████████████▊            | 1066/1568 [03:04<01:27,  5.74it/s]16 02:39:58 Save the image 00751N.png
 68%|█████████████████████████▊            | 1067/1568 [03:04<01:22,  6.08it/s]16 02:39:58 Save the image 00751N_flip.png
 68%|█████████████████████████▉            | 1068/1568 [03:05<01:24,  5.94it/s]16 02:39:58 Save the image 00752N.png
 68%|█████████████████████████▉            | 1069/1568 [03:05<01:24,  5.90it/s]16 02:39:59 Save the image 00752N_flip.png
 68%|█████████████████████████▉            | 1070/1568 [03:05<01:24,  5.87it/s]16 02:39:59 Save the image 00753N.png
 68%|█████████████████████████▉            | 1071/1568 [03:05<01:25,  5.80it/s]16 02:39:59 Save the image 00753N_flip.png
 68%|█████████████████████████▉            | 1072/1568 [03:05<01:26,  5.76it/s]16 02:39:59 Save the image 00754N.png
 68%|██████████████████████████            | 1073/1568 [03:05<01:25,  5.77it/s]16 02:39:59 Save the image 00754N_flip.png
 68%|██████████████████████████            | 1074/1568 [03:06<01:25,  5.77it/s]16 02:39:59 Save the image 00755N.png
 69%|██████████████████████████            | 1075/1568 [03:06<01:20,  6.13it/s]16 02:40:00 Save the image 00755N_flip.png
 69%|██████████████████████████            | 1076/1568 [03:06<01:22,  5.97it/s]16 02:40:00 Save the image 00756N.png
 69%|██████████████████████████            | 1077/1568 [03:06<01:22,  5.92it/s]16 02:40:00 Save the image 00756N_flip.png
 69%|██████████████████████████▏           | 1078/1568 [03:06<01:22,  5.90it/s]16 02:40:00 Save the image 00757N.png
 69%|██████████████████████████▏           | 1079/1568 [03:06<01:23,  5.82it/s]16 02:40:00 Save the image 00757N_flip.png
 69%|██████████████████████████▏           | 1080/1568 [03:07<01:23,  5.85it/s]16 02:40:01 Save the image 00758N.png

 69%|██████████████████████████▏           | 1081/1568 [03:07<01:24,  5.76it/s]16 02:40:01 Save the image 00758N_flip.png
 69%|██████████████████████████▏           | 1082/1568 [03:07<01:24,  5.74it/s]16 02:40:01 Save the image 00759N.png
 69%|██████████████████████████▏           | 1083/1568 [03:07<01:24,  5.77it/s]16 02:40:01 Save the image 00759N_flip.png
 69%|██████████████████████████▎           | 1084/1568 [03:07<01:23,  5.76it/s]16 02:40:01 Save the image 00760N.png
 69%|██████████████████████████▎           | 1085/1568 [03:08<01:23,  5.77it/s]16 02:40:01 Save the image 00760N_flip.png
 69%|██████████████████████████▎           | 1086/1568 [03:08<01:23,  5.77it/s]16 02:40:02 Save the image 00761N.png
 69%|██████████████████████████▎           | 1087/1568 [03:08<01:23,  5.78it/s]16 02:40:02 Save the image 00761N_flip.png
 69%|██████████████████████████▎           | 1088/1568 [03:08<01:22,  5.80it/s]16 02:40:02 Save the image 00762N.png
 69%|██████████████████████████▍           | 1089/1568 [03:08<01:23,  5.73it/s]16 02:40:02 Save the image 00762N_flip.png
 70%|██████████████████████████▍           | 1090/1568 [03:08<01:23,  5.71it/s]16 02:40:02 Save the image 00763N.png
 70%|██████████████████████████▍           | 1091/1568 [03:09<01:24,  5.68it/s]16 02:40:02 Save the image 00763N_flip.png
 70%|██████████████████████████▍           | 1092/1568 [03:09<01:23,  5.67it/s]16 02:40:03 Save the image 00764N.png
 70%|██████████████████████████▍           | 1093/1568 [03:09<01:22,  5.74it/s]16 02:40:03 Save the image 00764N_flip.png
 70%|██████████████████████████▌           | 1094/1568 [03:09<01:22,  5.72it/s]16 02:40:03 Save the image 00765N.png
 70%|██████████████████████████▌           | 1095/1568 [03:09<01:23,  5.70it/s]16 02:40:03 Save the image 00765N_flip.png
 70%|██████████████████████████▌           | 1096/1568 [03:09<01:22,  5.72it/s]16 02:40:03 Save the image 00766N.png
 70%|██████████████████████████▌           | 1097/1568 [03:10<01:22,  5.73it/s]16 02:40:03 Save the image 00766N_flip.png
 70%|██████████████████████████▌           | 1098/1568 [03:10<01:17,  6.07it/s]16 02:40:04 Save the image 00767N.png
 70%|██████████████████████████▋           | 1099/1568 [03:10<01:18,  5.95it/s]16 02:40:04 Save the image 00767N_flip.png
 70%|██████████████████████████▋           | 1100/1568 [03:10<01:19,  5.90it/s]16 02:40:04 Save the image 00768N.png
 70%|██████████████████████████▋           | 1101/1568 [03:10<01:19,  5.90it/s]16 02:40:04 Save the image 00768N_flip.png
 70%|██████████████████████████▋           | 1102/1568 [03:10<01:20,  5.80it/s]16 02:40:04 Save the image 00769N.png
 70%|██████████████████████████▋           | 1103/1568 [03:11<01:20,  5.76it/s]16 02:40:05 Save the image 00769N_flip.png
 70%|██████████████████████████▊           | 1104/1568 [03:11<01:20,  5.76it/s]16 02:40:05 Save the image 00770N.png
 70%|██████████████████████████▊           | 1105/1568 [03:11<01:20,  5.78it/s]16 02:40:05 Save the image 00770N_flip.png
 71%|██████████████████████████▊           | 1106/1568 [03:11<01:15,  6.15it/s]16 02:40:05 Save the image 00771N.png
 71%|██████████████████████████▊           | 1107/1568 [03:11<01:16,  6.01it/s]16 02:40:05 Save the image 00771N_flip.png
 71%|██████████████████████████▊           | 1108/1568 [03:11<01:17,  5.97it/s]16 02:40:05 Save the image 00772N.png
 71%|██████████████████████████▉           | 1109/1568 [03:12<01:17,  5.93it/s]16 02:40:06 Save the image 00772N_flip.png
 71%|██████████████████████████▉           | 1110/1568 [03:12<01:18,  5.84it/s]16 02:40:06 Save the image 00773N.png
 71%|██████████████████████████▉           | 1111/1568 [03:12<01:18,  5.80it/s]16 02:40:06 Save the image 00773N_flip.png
 71%|██████████████████████████▉           | 1112/1568 [03:12<01:18,  5.80it/s]16 02:40:06 Save the image 00774N.png
 71%|██████████████████████████▉           | 1113/1568 [03:12<01:18,  5.80it/s]16 02:40:06 Save the image 00774N_flip.png
 71%|██████████████████████████▉           | 1114/1568 [03:12<01:13,  6.17it/s]16 02:40:06 Save the image 00775N.png
 71%|███████████████████████████           | 1115/1568 [03:13<01:15,  6.03it/s]16 02:40:07 Save the image 00775N_flip.png
 71%|███████████████████████████           | 1116/1568 [03:13<01:15,  5.96it/s]16 02:40:07 Save the image 00776N.png
 71%|███████████████████████████           | 1117/1568 [03:13<01:16,  5.93it/s]16 02:40:07 Save the image 00776N_flip.png
 71%|███████████████████████████           | 1118/1568 [03:13<01:16,  5.85it/s]16 02:40:07 Save the image 00777N.png
 71%|███████████████████████████           | 1119/1568 [03:13<01:17,  5.83it/s]16 02:40:07 Save the image 00777N_flip.png
 71%|███████████████████████████▏          | 1120/1568 [03:14<01:16,  5.83it/s]16 02:40:07 Save the image 00778N.png
 71%|███████████████████████████▏          | 1121/1568 [03:14<01:16,  5.82it/s]16 02:40:08 Save the image 00778N_flip.png
 72%|███████████████████████████▏          | 1122/1568 [03:14<01:12,  6.18it/s]16 02:40:08 Save the image 00779N.png
 72%|███████████████████████████▏          | 1123/1568 [03:14<01:13,  6.03it/s]16 02:40:08 Save the image 00779N_flip.png
 72%|███████████████████████████▏          | 1124/1568 [03:14<01:14,  5.96it/s]16 02:40:08 Save the image 00780N.png
 72%|███████████████████████████▎          | 1125/1568 [03:14<01:14,  5.95it/s]16 02:40:08 Save the image 00780N_flip.png
 72%|███████████████████████████▎          | 1126/1568 [03:15<01:15,  5.85it/s]16 02:40:08 Save the image 00781N.png
 72%|███████████████████████████▎          | 1127/1568 [03:15<01:15,  5.82it/s]16 02:40:09 Save the image 00781N_flip.png
 72%|███████████████████████████▎          | 1128/1568 [03:15<01:16,  5.77it/s]16 02:40:09 Save the image 00782N.png
 72%|███████████████████████████▎          | 1129/1568 [03:15<01:15,  5.78it/s]16 02:40:09 Save the image 00782N_flip.png
 72%|███████████████████████████▍          | 1130/1568 [03:15<01:11,  6.09it/s]16 02:40:09 Save the image 00783N.png
 72%|███████████████████████████▍          | 1131/1568 [03:15<01:13,  5.96it/s]16 02:40:09 Save the image 00783N_flip.png
 72%|███████████████████████████▍          | 1132/1568 [03:16<01:13,  5.91it/s]16 02:40:09 Save the image 00784N.png
 72%|███████████████████████████▍          | 1133/1568 [03:16<01:13,  5.90it/s]16 02:40:10 Save the image 00784N_flip.png
 72%|███████████████████████████▍          | 1134/1568 [03:16<01:14,  5.82it/s]16 02:40:10 Save the image 00785N.png
 72%|███████████████████████████▌          | 1135/1568 [03:16<01:14,  5.84it/s]16 02:40:10 Save the image 00785N_flip.png
 72%|███████████████████████████▌          | 1136/1568 [03:16<01:14,  5.79it/s]16 02:40:10 Save the image 00786N.png
 73%|███████████████████████████▌          | 1137/1568 [03:16<01:14,  5.77it/s]16 02:40:10 Save the image 00786N_flip.png
 73%|███████████████████████████▌          | 1138/1568 [03:17<01:12,  5.92it/s]16 02:40:10 Save the image 00787N.png
 73%|███████████████████████████▌          | 1139/1568 [03:17<01:13,  5.85it/s]16 02:40:11 Save the image 00787N_flip.png
 73%|███████████████████████████▋          | 1140/1568 [03:17<01:13,  5.86it/s]16 02:40:11 Save the image 00788N.png
 73%|███████████████████████████▋          | 1141/1568 [03:17<01:13,  5.84it/s]16 02:40:11 Save the image 00788N_flip.png
 73%|███████████████████████████▋          | 1142/1568 [03:17<01:13,  5.79it/s]16 02:40:11 Save the image 00789N.png
 73%|███████████████████████████▋          | 1143/1568 [03:17<01:12,  5.85it/s]16 02:40:11 Save the image 00789N_flip.png
 73%|███████████████████████████▋          | 1144/1568 [03:18<01:13,  5.81it/s]16 02:40:11 Save the image 00790N.png

 73%|███████████████████████████▋          | 1145/1568 [03:18<01:13,  5.79it/s]16 02:40:12 Save the image 00790N_flip.png
 73%|███████████████████████████▊          | 1146/1568 [03:18<01:12,  5.78it/s]16 02:40:12 Save the image 00791N.png
 73%|███████████████████████████▊          | 1147/1568 [03:18<01:12,  5.79it/s]16 02:40:12 Save the image 00791N_flip.png
 73%|███████████████████████████▊          | 1148/1568 [03:18<01:12,  5.82it/s]16 02:40:12 Save the image 00792N.png
 73%|███████████████████████████▊          | 1149/1568 [03:18<01:11,  5.82it/s]16 02:40:12 Save the image 00792N_flip.png
 73%|███████████████████████████▊          | 1150/1568 [03:19<01:12,  5.80it/s]16 02:40:13 Save the image 00793N.png
 73%|███████████████████████████▉          | 1151/1568 [03:19<01:11,  5.83it/s]16 02:40:13 Save the image 00793N_flip.png
 73%|███████████████████████████▉          | 1152/1568 [03:19<01:10,  5.87it/s]16 02:40:13 Save the image 00794N.png
 74%|███████████████████████████▉          | 1153/1568 [03:19<01:11,  5.83it/s]16 02:40:13 Save the image 00794N_flip.png
 74%|███████████████████████████▉          | 1154/1568 [03:19<01:11,  5.78it/s]16 02:40:13 Save the image 00795N.png
 74%|███████████████████████████▉          | 1155/1568 [03:19<01:11,  5.81it/s]16 02:40:13 Save the image 00795N_flip.png
 74%|████████████████████████████          | 1156/1568 [03:20<01:10,  5.82it/s]16 02:40:14 Save the image 00796N.png
 74%|████████████████████████████          | 1157/1568 [03:20<01:11,  5.74it/s]16 02:40:14 Save the image 00796N_flip.png
 74%|████████████████████████████          | 1158/1568 [03:20<01:11,  5.75it/s]16 02:40:14 Save the image 00797N.png
 74%|████████████████████████████          | 1159/1568 [03:20<01:10,  5.76it/s]16 02:40:14 Save the image 00797N_flip.png
 74%|████████████████████████████          | 1160/1568 [03:20<01:10,  5.80it/s]16 02:40:14 Save the image 00798N.png
 74%|████████████████████████████▏         | 1161/1568 [03:21<01:08,  5.90it/s]16 02:40:14 Save the image 00798N_flip.png
 74%|████████████████████████████▏         | 1162/1568 [03:21<01:09,  5.84it/s]16 02:40:15 Save the image 00799N.png
 74%|████████████████████████████▏         | 1163/1568 [03:21<01:09,  5.83it/s]16 02:40:15 Save the image 00799N_flip.png
 74%|████████████████████████████▏         | 1164/1568 [03:21<01:09,  5.84it/s]16 02:40:15 Save the image 00800N.png
 74%|████████████████████████████▏         | 1165/1568 [03:21<01:09,  5.82it/s]16 02:40:15 Save the image 00800N_flip.png
 74%|████████████████████████████▎         | 1166/1568 [03:21<01:09,  5.79it/s]16 02:40:15 Save the image 00801N.png
 74%|████████████████████████████▎         | 1167/1568 [03:22<01:08,  5.81it/s]16 02:40:15 Save the image 00801N_flip.png
 74%|████████████████████████████▎         | 1168/1568 [03:22<01:08,  5.87it/s]16 02:40:16 Save the image 00802N.png
 75%|████████████████████████████▎         | 1169/1568 [03:22<01:05,  6.08it/s]16 02:40:16 Save the image 00802N_flip.png
 75%|████████████████████████████▎         | 1170/1568 [03:22<01:06,  5.97it/s]16 02:40:16 Save the image 00803N.png
 75%|████████████████████████████▍         | 1171/1568 [03:22<01:06,  5.94it/s]16 02:40:16 Save the image 00803N_flip.png
 75%|████████████████████████████▍         | 1172/1568 [03:22<01:06,  5.91it/s]16 02:40:16 Save the image 00804N.png
 75%|████████████████████████████▍         | 1173/1568 [03:23<01:07,  5.86it/s]16 02:40:16 Save the image 00804N_flip.png
 75%|████████████████████████████▍         | 1174/1568 [03:23<01:07,  5.82it/s]16 02:40:17 Save the image 00805N.png
 75%|████████████████████████████▍         | 1175/1568 [03:23<01:07,  5.81it/s]16 02:40:17 Save the image 00805N_flip.png
 75%|████████████████████████████▌         | 1176/1568 [03:23<01:07,  5.78it/s]16 02:40:17 Save the image 00806N.png
 75%|████████████████████████████▌         | 1177/1568 [03:23<01:03,  6.14it/s]16 02:40:17 Save the image 00806N_flip.png
 75%|████████████████████████████▌         | 1178/1568 [03:23<01:04,  6.02it/s]16 02:40:17 Save the image 00807N.png
 75%|████████████████████████████▌         | 1179/1568 [03:24<01:05,  5.97it/s]16 02:40:17 Save the image 00807N_flip.png
 75%|████████████████████████████▌         | 1180/1568 [03:24<01:05,  5.94it/s]16 02:40:18 Save the image 00808N.png
 75%|████████████████████████████▌         | 1181/1568 [03:24<01:06,  5.85it/s]16 02:40:18 Save the image 00808N_flip.png
 75%|████████████████████████████▋         | 1182/1568 [03:24<01:06,  5.79it/s]16 02:40:18 Save the image 00809N.png
 75%|████████████████████████████▋         | 1183/1568 [03:24<01:06,  5.81it/s]16 02:40:18 Save the image 00809N_flip.png
 76%|████████████████████████████▋         | 1184/1568 [03:24<01:06,  5.80it/s]16 02:40:18 Save the image 00810N.png
 76%|████████████████████████████▋         | 1185/1568 [03:25<01:02,  6.15it/s]16 02:40:18 Save the image 00810N_flip.png
 76%|████████████████████████████▋         | 1186/1568 [03:25<01:03,  6.01it/s]16 02:40:19 Save the image 00811N.png
 76%|████████████████████████████▊         | 1187/1568 [03:25<01:04,  5.88it/s]16 02:40:19 Save the image 00811N_flip.png
 76%|████████████████████████████▊         | 1188/1568 [03:25<01:04,  5.88it/s]16 02:40:19 Save the image 00812N.png
 76%|████████████████████████████▊         | 1189/1568 [03:25<01:05,  5.82it/s]16 02:40:19 Save the image 00812N_flip.png
 76%|████████████████████████████▊         | 1190/1568 [03:25<01:05,  5.77it/s]16 02:40:19 Save the image 00813N.png
 76%|████████████████████████████▊         | 1191/1568 [03:26<01:05,  5.76it/s]16 02:40:20 Save the image 00813N_flip.png
 76%|████████████████████████████▉         | 1192/1568 [03:26<01:05,  5.78it/s]16 02:40:20 Save the image 00814N.png
 76%|████████████████████████████▉         | 1193/1568 [03:26<01:01,  6.13it/s]16 02:40:20 Save the image 00814N_flip.png
 76%|████████████████████████████▉         | 1194/1568 [03:26<01:02,  5.98it/s]16 02:40:20 Save the image 00815N.png
 76%|████████████████████████████▉         | 1195/1568 [03:26<01:02,  5.93it/s]16 02:40:20 Save the image 00815N_flip.png
 76%|████████████████████████████▉         | 1196/1568 [03:26<01:03,  5.88it/s]16 02:40:20 Save the image 00816N.png
 76%|█████████████████████████████         | 1197/1568 [03:27<01:03,  5.81it/s]16 02:40:21 Save the image 00816N_flip.png
 76%|█████████████████████████████         | 1198/1568 [03:27<01:03,  5.84it/s]16 02:40:21 Save the image 00817N.png
 76%|█████████████████████████████         | 1199/1568 [03:27<01:03,  5.79it/s]16 02:40:21 Save the image 00817N_flip.png
 77%|█████████████████████████████         | 1200/1568 [03:27<01:03,  5.78it/s]16 02:40:21 Save the image 00818N.png
 77%|█████████████████████████████         | 1201/1568 [03:27<00:59,  6.15it/s]16 02:40:21 Save the image 00818N_flip.png
 77%|█████████████████████████████▏        | 1202/1568 [03:27<01:01,  6.00it/s]16 02:40:21 Save the image 00819N.png
 77%|█████████████████████████████▏        | 1203/1568 [03:28<01:01,  5.94it/s]16 02:40:22 Save the image 00819N_flip.png
 77%|█████████████████████████████▏        | 1204/1568 [03:28<01:01,  5.89it/s]16 02:40:22 Save the image 00820N.png
 77%|█████████████████████████████▏        | 1205/1568 [03:28<01:02,  5.83it/s]16 02:40:22 Save the image 00820N_flip.png
 77%|█████████████████████████████▏        | 1206/1568 [03:28<01:01,  5.86it/s]16 02:40:22 Save the image 00821N.png
 77%|█████████████████████████████▎        | 1207/1568 [03:28<01:02,  5.82it/s]16 02:40:22 Save the image 00821N_flip.png
 77%|█████████████████████████████▎        | 1208/1568 [03:29<01:02,  5.80it/s]16 02:40:22 Save the image 00822N.png

 77%|█████████████████████████████▎        | 1209/1568 [03:29<01:01,  5.81it/s]16 02:40:23 Save the image 00822N_flip.png
 77%|█████████████████████████████▎        | 1210/1568 [03:29<01:01,  5.78it/s]16 02:40:23 Save the image 00823N.png
 77%|█████████████████████████████▎        | 1211/1568 [03:29<01:01,  5.79it/s]16 02:40:23 Save the image 00823N_flip.png
 77%|█████████████████████████████▎        | 1212/1568 [03:29<01:01,  5.76it/s]16 02:40:23 Save the image 00824N.png
 77%|█████████████████████████████▍        | 1213/1568 [03:29<01:01,  5.76it/s]16 02:40:23 Save the image 00824N_flip.png
 77%|█████████████████████████████▍        | 1214/1568 [03:30<01:01,  5.79it/s]16 02:40:23 Save the image 00825N.png
 77%|█████████████████████████████▍        | 1215/1568 [03:30<01:00,  5.84it/s]16 02:40:24 Save the image 00825N_flip.png
 78%|█████████████████████████████▍        | 1216/1568 [03:30<01:00,  5.78it/s]16 02:40:24 Save the image 00826N.png
 78%|█████████████████████████████▍        | 1217/1568 [03:30<01:01,  5.74it/s]16 02:40:24 Save the image 00826N_flip.png
 78%|█████████████████████████████▌        | 1218/1568 [03:30<01:00,  5.76it/s]16 02:40:24 Save the image 00827N.png
 78%|█████████████████████████████▌        | 1219/1568 [03:30<01:00,  5.75it/s]16 02:40:24 Save the image 00827N_flip.png
 78%|█████████████████████████████▌        | 1220/1568 [03:31<01:00,  5.71it/s]16 02:40:24 Save the image 00828N.png
 78%|█████████████████████████████▌        | 1221/1568 [03:31<01:00,  5.72it/s]16 02:40:25 Save the image 00828N_flip.png
 78%|█████████████████████████████▌        | 1222/1568 [03:31<01:00,  5.72it/s]16 02:40:25 Save the image 00829N.png
 78%|█████████████████████████████▋        | 1223/1568 [03:31<00:59,  5.77it/s]16 02:40:25 Save the image 00829N_flip.png
 78%|█████████████████████████████▋        | 1224/1568 [03:31<00:57,  6.00it/s]16 02:40:25 Save the image 00830N.png
 78%|█████████████████████████████▋        | 1225/1568 [03:31<00:58,  5.88it/s]16 02:40:25 Save the image 00830N_flip.png
 78%|█████████████████████████████▋        | 1226/1568 [03:32<00:58,  5.86it/s]16 02:40:25 Save the image 00831N.png
 78%|█████████████████████████████▋        | 1227/1568 [03:32<00:58,  5.86it/s]16 02:40:26 Save the image 00831N_flip.png
 78%|█████████████████████████████▊        | 1228/1568 [03:32<00:58,  5.80it/s]16 02:40:26 Save the image 00832N.png
 78%|█████████████████████████████▊        | 1229/1568 [03:32<00:58,  5.75it/s]16 02:40:26 Save the image 00832N_flip.png
 78%|█████████████████████████████▊        | 1230/1568 [03:32<00:58,  5.77it/s]16 02:40:26 Save the image 00833N.png
 79%|█████████████████████████████▊        | 1231/1568 [03:32<00:58,  5.75it/s]16 02:40:26 Save the image 00833N_flip.png
 79%|█████████████████████████████▊        | 1232/1568 [03:33<00:55,  6.09it/s]16 02:40:27 Save the image 00834N.png
 79%|█████████████████████████████▉        | 1233/1568 [03:33<00:56,  5.88it/s]16 02:40:27 Save the image 00834N_flip.png
 79%|█████████████████████████████▉        | 1234/1568 [03:33<00:57,  5.84it/s]16 02:40:27 Save the image 00835N.png
 79%|█████████████████████████████▉        | 1235/1568 [03:33<00:56,  5.85it/s]16 02:40:27 Save the image 00835N_flip.png
 79%|█████████████████████████████▉        | 1236/1568 [03:33<00:57,  5.79it/s]16 02:40:27 Save the image 00836N.png
 79%|█████████████████████████████▉        | 1237/1568 [03:34<00:56,  5.82it/s]16 02:40:27 Save the image 00836N_flip.png
 79%|██████████████████████████████        | 1238/1568 [03:34<00:56,  5.79it/s]16 02:40:28 Save the image 00837N.png
 79%|██████████████████████████████        | 1239/1568 [03:34<00:56,  5.79it/s]16 02:40:28 Save the image 00837N_flip.png
 79%|██████████████████████████████        | 1240/1568 [03:34<00:53,  6.10it/s]16 02:40:28 Save the image 00838N.png
 79%|██████████████████████████████        | 1241/1568 [03:34<00:54,  5.96it/s]16 02:40:28 Save the image 00838N_flip.png
 79%|██████████████████████████████        | 1242/1568 [03:34<00:55,  5.92it/s]16 02:40:28 Save the image 00839N.png
 79%|██████████████████████████████        | 1243/1568 [03:35<00:55,  5.90it/s]16 02:40:28 Save the image 00839N_flip.png
 79%|██████████████████████████████▏       | 1244/1568 [03:35<00:55,  5.83it/s]16 02:40:29 Save the image 00840N.png
 79%|██████████████████████████████▏       | 1245/1568 [03:35<00:55,  5.87it/s]16 02:40:29 Save the image 00840N_flip.png
 79%|██████████████████████████████▏       | 1246/1568 [03:35<00:55,  5.83it/s]16 02:40:29 Save the image 00841N.png
 80%|██████████████████████████████▏       | 1247/1568 [03:35<00:55,  5.81it/s]16 02:40:29 Save the image 00841N_flip.png
 80%|██████████████████████████████▏       | 1248/1568 [03:35<00:52,  6.14it/s]16 02:40:29 Save the image 00842N.png
 80%|██████████████████████████████▎       | 1249/1568 [03:36<00:53,  6.01it/s]16 02:40:29 Save the image 00842N_flip.png
 80%|██████████████████████████████▎       | 1250/1568 [03:36<00:53,  5.97it/s]16 02:40:30 Save the image 00843N.png
 80%|██████████████████████████████▎       | 1251/1568 [03:36<00:53,  5.96it/s]16 02:40:30 Save the image 00843N_flip.png
 80%|██████████████████████████████▎       | 1252/1568 [03:36<00:53,  5.89it/s]16 02:40:30 Save the image 00844N.png
 80%|██████████████████████████████▎       | 1253/1568 [03:36<00:53,  5.87it/s]16 02:40:30 Save the image 00844N_flip.png
 80%|██████████████████████████████▍       | 1254/1568 [03:36<00:53,  5.86it/s]16 02:40:30 Save the image 00845N.png
 80%|██████████████████████████████▍       | 1255/1568 [03:37<00:53,  5.81it/s]16 02:40:30 Save the image 00845N_flip.png
 80%|██████████████████████████████▍       | 1256/1568 [03:37<00:50,  6.13it/s]16 02:40:31 Save the image 00846N.png
 80%|██████████████████████████████▍       | 1257/1568 [03:37<00:51,  5.99it/s]16 02:40:31 Save the image 00846N_flip.png
 80%|██████████████████████████████▍       | 1258/1568 [03:37<00:52,  5.94it/s]16 02:40:31 Save the image 00847N.png
 80%|██████████████████████████████▌       | 1259/1568 [03:37<00:52,  5.90it/s]16 02:40:31 Save the image 00847N_flip.png
 80%|██████████████████████████████▌       | 1260/1568 [03:37<00:52,  5.83it/s]16 02:40:31 Save the image 00848N.png
 80%|██████████████████████████████▌       | 1261/1568 [03:38<00:52,  5.85it/s]16 02:40:31 Save the image 00848N_flip.png
 80%|██████████████████████████████▌       | 1262/1568 [03:38<00:52,  5.81it/s]16 02:40:32 Save the image 00849N.png
 81%|██████████████████████████████▌       | 1263/1568 [03:38<00:52,  5.81it/s]16 02:40:32 Save the image 00849N_flip.png
 81%|██████████████████████████████▋       | 1264/1568 [03:38<00:49,  6.10it/s]16 02:40:32 Save the image 00850N.png
 81%|██████████████████████████████▋       | 1265/1568 [03:38<00:50,  5.97it/s]16 02:40:32 Save the image 00850N_flip.png
 81%|██████████████████████████████▋       | 1266/1568 [03:38<00:50,  5.93it/s]16 02:40:32 Save the image 00851N.png
 81%|██████████████████████████████▋       | 1267/1568 [03:39<00:50,  5.92it/s]16 02:40:32 Save the image 00851N_flip.png
 81%|██████████████████████████████▋       | 1268/1568 [03:39<00:51,  5.84it/s]16 02:40:33 Save the image 00852N.png
 81%|██████████████████████████████▊       | 1269/1568 [03:39<00:50,  5.88it/s]16 02:40:33 Save the image 00852N_flip.png
 81%|██████████████████████████████▊       | 1270/1568 [03:39<00:51,  5.82it/s]16 02:40:33 Save the image 00853N.png
 81%|██████████████████████████████▊       | 1271/1568 [03:39<00:51,  5.80it/s]16 02:40:33 Save the image 00853N_flip.png
 81%|██████████████████████████████▊       | 1272/1568 [03:39<00:47,  6.18it/s]16 02:40:33 Save the image 00854N.png

 81%|██████████████████████████████▊       | 1273/1568 [03:40<00:48,  6.03it/s]16 02:40:33 Save the image 00854N_flip.png
 81%|██████████████████████████████▉       | 1274/1568 [03:40<00:49,  5.97it/s]16 02:40:34 Save the image 00855N.png
 81%|██████████████████████████████▉       | 1275/1568 [03:40<00:49,  5.91it/s]16 02:40:34 Save the image 00855N_flip.png
 81%|██████████████████████████████▉       | 1276/1568 [03:40<00:50,  5.84it/s]16 02:40:34 Save the image 00856N.png
 81%|██████████████████████████████▉       | 1277/1568 [03:40<00:49,  5.87it/s]16 02:40:34 Save the image 00856N_flip.png
 82%|██████████████████████████████▉       | 1278/1568 [03:40<00:49,  5.85it/s]16 02:40:34 Save the image 00857N.png
 82%|██████████████████████████████▉       | 1279/1568 [03:41<00:49,  5.84it/s]16 02:40:34 Save the image 00857N_flip.png
 82%|███████████████████████████████       | 1280/1568 [03:41<00:46,  6.17it/s]16 02:40:35 Save the image 00858N.png
 82%|███████████████████████████████       | 1281/1568 [03:41<00:47,  6.01it/s]16 02:40:35 Save the image 00858N_flip.png
 82%|███████████████████████████████       | 1282/1568 [03:41<00:48,  5.95it/s]16 02:40:35 Save the image 00859N.png
 82%|███████████████████████████████       | 1283/1568 [03:41<00:48,  5.91it/s]16 02:40:35 Save the image 00859N_flip.png
 82%|███████████████████████████████       | 1284/1568 [03:41<00:48,  5.83it/s]16 02:40:35 Save the image 00860N.png
 82%|███████████████████████████████▏      | 1285/1568 [03:42<00:48,  5.79it/s]16 02:40:35 Save the image 00860N_flip.png
 82%|███████████████████████████████▏      | 1286/1568 [03:42<00:48,  5.76it/s]16 02:40:36 Save the image 00861N.png
 82%|███████████████████████████████▏      | 1287/1568 [03:42<00:48,  5.76it/s]16 02:40:36 Save the image 00861N_flip.png
 82%|███████████████████████████████▏      | 1288/1568 [03:42<00:48,  5.79it/s]16 02:40:36 Save the image 00862N.png
 82%|███████████████████████████████▏      | 1289/1568 [03:42<00:48,  5.80it/s]16 02:40:36 Save the image 00862N_flip.png
 82%|███████████████████████████████▎      | 1290/1568 [03:42<00:47,  5.85it/s]16 02:40:36 Save the image 00863N.png
 82%|███████████████████████████████▎      | 1291/1568 [03:43<00:47,  5.82it/s]16 02:40:37 Save the image 00863N_flip.png
 82%|███████████████████████████████▎      | 1292/1568 [03:43<00:47,  5.80it/s]16 02:40:37 Save the image 00864N.png
 82%|███████████████████████████████▎      | 1293/1568 [03:43<00:46,  5.86it/s]16 02:40:37 Save the image 00864N_flip.png
 83%|███████████████████████████████▎      | 1294/1568 [03:43<00:46,  5.91it/s]16 02:40:37 Save the image 00865N.png
 83%|███████████████████████████████▍      | 1295/1568 [03:43<00:46,  5.86it/s]16 02:40:37 Save the image 00865N_flip.png
 83%|███████████████████████████████▍      | 1296/1568 [03:44<00:46,  5.85it/s]16 02:40:37 Save the image 00866N.png
 83%|███████████████████████████████▍      | 1297/1568 [03:44<00:46,  5.83it/s]16 02:40:38 Save the image 00866N_flip.png
 83%|███████████████████████████████▍      | 1298/1568 [03:44<00:46,  5.87it/s]16 02:40:38 Save the image 00867N.png
 83%|███████████████████████████████▍      | 1299/1568 [03:44<00:45,  5.85it/s]16 02:40:38 Save the image 00867N_flip.png
 83%|███████████████████████████████▌      | 1300/1568 [03:44<00:45,  5.83it/s]16 02:40:38 Save the image 00868N.png
 83%|███████████████████████████████▌      | 1301/1568 [03:44<00:45,  5.85it/s]16 02:40:38 Save the image 00868N_flip.png
 83%|███████████████████████████████▌      | 1302/1568 [03:45<00:45,  5.87it/s]16 02:40:38 Save the image 00869N.png
 83%|███████████████████████████████▌      | 1303/1568 [03:45<00:45,  5.80it/s]16 02:40:39 Save the image 00869N_flip.png
 83%|███████████████████████████████▌      | 1304/1568 [03:45<00:45,  5.77it/s]16 02:40:39 Save the image 00870N.png
 83%|███████████████████████████████▋      | 1305/1568 [03:45<00:45,  5.80it/s]16 02:40:39 Save the image 00870N_flip.png
 83%|███████████████████████████████▋      | 1306/1568 [03:45<00:45,  5.82it/s]16 02:40:39 Save the image 00871N.png
 83%|███████████████████████████████▋      | 1307/1568 [03:45<00:45,  5.78it/s]16 02:40:39 Save the image 00871N_flip.png
 83%|███████████████████████████████▋      | 1308/1568 [03:46<00:44,  5.79it/s]16 02:40:39 Save the image 00872N.png
 83%|███████████████████████████████▋      | 1309/1568 [03:46<00:44,  5.79it/s]16 02:40:40 Save the image 00872N_flip.png
 84%|███████████████████████████████▋      | 1310/1568 [03:46<00:43,  5.88it/s]16 02:40:40 Save the image 00873N.png
 84%|███████████████████████████████▊      | 1311/1568 [03:46<00:42,  5.98it/s]16 02:40:40 Save the image 00873N_flip.png
 84%|███████████████████████████████▊      | 1312/1568 [03:46<00:43,  5.89it/s]16 02:40:40 Save the image 00874N.png
 84%|███████████████████████████████▊      | 1313/1568 [03:46<00:43,  5.89it/s]16 02:40:40 Save the image 00874N_flip.png
 84%|███████████████████████████████▊      | 1314/1568 [03:47<00:43,  5.90it/s]16 02:40:40 Save the image 00875N.png
 84%|███████████████████████████████▊      | 1315/1568 [03:47<00:43,  5.83it/s]16 02:40:41 Save the image 00875N_flip.png
 84%|███████████████████████████████▉      | 1316/1568 [03:47<00:43,  5.78it/s]16 02:40:41 Save the image 00876N.png
 84%|███████████████████████████████▉      | 1317/1568 [03:47<00:43,  5.78it/s]16 02:40:41 Save the image 00876N_flip.png
 84%|███████████████████████████████▉      | 1318/1568 [03:47<00:43,  5.78it/s]16 02:40:41 Save the image 00877N.png
 84%|███████████████████████████████▉      | 1319/1568 [03:47<00:40,  6.13it/s]16 02:40:41 Save the image 00877N_flip.png
 84%|███████████████████████████████▉      | 1320/1568 [03:48<00:41,  6.00it/s]16 02:40:41 Save the image 00878N.png
 84%|████████████████████████████████      | 1321/1568 [03:48<00:41,  5.94it/s]16 02:40:42 Save the image 00878N_flip.png
 84%|████████████████████████████████      | 1322/1568 [03:48<00:41,  5.93it/s]16 02:40:42 Save the image 00879N.png
 84%|████████████████████████████████      | 1323/1568 [03:48<00:41,  5.85it/s]16 02:40:42 Save the image 00879N_flip.png
 84%|████████████████████████████████      | 1324/1568 [03:48<00:42,  5.79it/s]16 02:40:42 Save the image 00880N.png
 85%|████████████████████████████████      | 1325/1568 [03:48<00:42,  5.78it/s]16 02:40:42 Save the image 00880N_flip.png
 85%|████████████████████████████████▏     | 1326/1568 [03:49<00:41,  5.79it/s]16 02:40:42 Save the image 00881N.png
 85%|████████████████████████████████▏     | 1327/1568 [03:49<00:39,  6.07it/s]16 02:40:43 Save the image 00881N_flip.png
 85%|████████████████████████████████▏     | 1328/1568 [03:49<00:40,  5.94it/s]16 02:40:43 Save the image 00882N.png
 85%|████████████████████████████████▏     | 1329/1568 [03:49<00:40,  5.90it/s]16 02:40:43 Save the image 00882N_flip.png
 85%|████████████████████████████████▏     | 1330/1568 [03:49<00:40,  5.87it/s]16 02:40:43 Save the image 00883N.png
 85%|████████████████████████████████▎     | 1331/1568 [03:49<00:40,  5.80it/s]16 02:40:43 Save the image 00883N_flip.png
 85%|████████████████████████████████▎     | 1332/1568 [03:50<00:40,  5.83it/s]16 02:40:44 Save the image 00884N.png
 85%|████████████████████████████████▎     | 1333/1568 [03:50<00:40,  5.81it/s]16 02:40:44 Save the image 00884N_flip.png
 85%|████████████████████████████████▎     | 1334/1568 [03:50<00:40,  5.79it/s]16 02:40:44 Save the image 00885N.png
 85%|████████████████████████████████▎     | 1335/1568 [03:50<00:37,  6.13it/s]16 02:40:44 Save the image 00885N_flip.png
 85%|████████████████████████████████▍     | 1336/1568 [03:50<00:38,  5.98it/s]16 02:40:44 Save the image 00886N.png

 85%|████████████████████████████████▍     | 1337/1568 [03:50<00:38,  5.93it/s]16 02:40:44 Save the image 00886N_flip.png
 85%|████████████████████████████████▍     | 1338/1568 [03:51<00:38,  5.90it/s]16 02:40:45 Save the image 00887N.png
 85%|████████████████████████████████▍     | 1339/1568 [03:51<00:39,  5.82it/s]16 02:40:45 Save the image 00887N_flip.png
 85%|████████████████████████████████▍     | 1340/1568 [03:51<00:39,  5.84it/s]16 02:40:45 Save the image 00888N.png
 86%|████████████████████████████████▍     | 1341/1568 [03:51<00:39,  5.79it/s]16 02:40:45 Save the image 00888N_flip.png
 86%|████████████████████████████████▌     | 1342/1568 [03:51<00:39,  5.78it/s]16 02:40:45 Save the image 00889N.png
 86%|████████████████████████████████▌     | 1343/1568 [03:52<00:38,  5.79it/s]16 02:40:45 Save the image 00889N_flip.png
 86%|████████████████████████████████▌     | 1344/1568 [03:52<00:38,  5.78it/s]16 02:40:46 Save the image 00890N.png
 86%|████████████████████████████████▌     | 1345/1568 [03:52<00:38,  5.73it/s]16 02:40:46 Save the image 00890N_flip.png
 86%|████████████████████████████████▌     | 1346/1568 [03:52<00:38,  5.73it/s]16 02:40:46 Save the image 00891N.png
 86%|████████████████████████████████▋     | 1347/1568 [03:52<00:38,  5.74it/s]16 02:40:46 Save the image 00891N_flip.png
 86%|████████████████████████████████▋     | 1348/1568 [03:52<00:38,  5.78it/s]16 02:40:46 Save the image 00892N.png
 86%|████████████████████████████████▋     | 1349/1568 [03:53<00:37,  5.82it/s]16 02:40:46 Save the image 00892N_flip.png
 86%|████████████████████████████████▋     | 1350/1568 [03:53<00:37,  5.78it/s]16 02:40:47 Save the image 00893N.png
 86%|████████████████████████████████▋     | 1351/1568 [03:53<00:37,  5.76it/s]16 02:40:47 Save the image 00893N_flip.png
 86%|████████████████████████████████▊     | 1352/1568 [03:53<00:37,  5.76it/s]16 02:40:47 Save the image 00894N.png
 86%|████████████████████████████████▊     | 1353/1568 [03:53<00:37,  5.79it/s]16 02:40:47 Save the image 00894N_flip.png
 86%|████████████████████████████████▊     | 1354/1568 [03:53<00:37,  5.73it/s]16 02:40:47 Save the image 00895N.png
 86%|████████████████████████████████▊     | 1355/1568 [03:54<00:37,  5.73it/s]16 02:40:47 Save the image 00895N_flip.png
 86%|████████████████████████████████▊     | 1356/1568 [03:54<00:36,  5.74it/s]16 02:40:48 Save the image 00896N.png
 87%|████████████████████████████████▉     | 1357/1568 [03:54<00:36,  5.80it/s]16 02:40:48 Save the image 00896N_flip.png
 87%|████████████████████████████████▉     | 1358/1568 [03:54<00:35,  5.98it/s]16 02:40:48 Save the image 00897N.png
 87%|████████████████████████████████▉     | 1359/1568 [03:54<00:35,  5.89it/s]16 02:40:48 Save the image 00897N_flip.png
 87%|████████████████████████████████▉     | 1360/1568 [03:54<00:35,  5.86it/s]16 02:40:48 Save the image 00898N.png
 87%|████████████████████████████████▉     | 1361/1568 [03:55<00:35,  5.87it/s]16 02:40:49 Save the image 00898N_flip.png
 87%|█████████████████████████████████     | 1362/1568 [03:55<00:35,  5.80it/s]16 02:40:49 Save the image 00899N.png
 87%|█████████████████████████████████     | 1363/1568 [03:55<00:35,  5.77it/s]16 02:40:49 Save the image 00899N_flip.png
 87%|█████████████████████████████████     | 1364/1568 [03:55<00:35,  5.78it/s]16 02:40:49 Save the image 00900N.png
 87%|█████████████████████████████████     | 1365/1568 [03:55<00:35,  5.79it/s]16 02:40:49 Save the image 00900N_flip.png
 87%|█████████████████████████████████     | 1366/1568 [03:55<00:32,  6.13it/s]16 02:40:49 Save the image 00901N.png
 87%|█████████████████████████████████▏    | 1367/1568 [03:56<00:33,  5.97it/s]16 02:40:50 Save the image 00901N_flip.png
 87%|█████████████████████████████████▏    | 1368/1568 [03:56<00:33,  5.92it/s]16 02:40:50 Save the image 00902N.png
 87%|█████████████████████████████████▏    | 1369/1568 [03:56<00:33,  5.91it/s]16 02:40:50 Save the image 00902N_flip.png
 87%|█████████████████████████████████▏    | 1370/1568 [03:56<00:33,  5.84it/s]16 02:40:50 Save the image 00903N.png
 87%|█████████████████████████████████▏    | 1371/1568 [03:56<00:34,  5.78it/s]16 02:40:50 Save the image 00903N_flip.png
 88%|█████████████████████████████████▎    | 1372/1568 [03:57<00:33,  5.77it/s]16 02:40:50 Save the image 00904N.png
 88%|█████████████████████████████████▎    | 1373/1568 [03:57<00:33,  5.76it/s]16 02:40:51 Save the image 00904N_flip.png
 88%|█████████████████████████████████▎    | 1374/1568 [03:57<00:31,  6.10it/s]16 02:40:51 Save the image 00905N.png
 88%|█████████████████████████████████▎    | 1375/1568 [03:57<00:32,  5.96it/s]16 02:40:51 Save the image 00905N_flip.png
 88%|█████████████████████████████████▎    | 1376/1568 [03:57<00:32,  5.90it/s]16 02:40:51 Save the image 00906N.png
 88%|█████████████████████████████████▎    | 1377/1568 [03:57<00:32,  5.88it/s]16 02:40:51 Save the image 00906N_flip.png
 88%|█████████████████████████████████▍    | 1378/1568 [03:58<00:32,  5.82it/s]16 02:40:51 Save the image 00907N.png
 88%|█████████████████████████████████▍    | 1379/1568 [03:58<00:32,  5.88it/s]16 02:40:52 Save the image 00907N_flip.png
 88%|█████████████████████████████████▍    | 1380/1568 [03:58<00:32,  5.81it/s]16 02:40:52 Save the image 00908N.png
 88%|█████████████████████████████████▍    | 1381/1568 [03:58<00:32,  5.76it/s]16 02:40:52 Save the image 00908N_flip.png
 88%|█████████████████████████████████▍    | 1382/1568 [03:58<00:30,  6.11it/s]16 02:40:52 Save the image 00909N.png
 88%|█████████████████████████████████▌    | 1383/1568 [03:58<00:30,  5.97it/s]16 02:40:52 Save the image 00909N_flip.png
 88%|█████████████████████████████████▌    | 1384/1568 [03:59<00:31,  5.86it/s]16 02:40:52 Save the image 00910N.png
 88%|█████████████████████████████████▌    | 1385/1568 [03:59<00:31,  5.85it/s]16 02:40:53 Save the image 00910N_flip.png
 88%|█████████████████████████████████▌    | 1386/1568 [03:59<00:31,  5.79it/s]16 02:40:53 Save the image 00911N.png
 88%|█████████████████████████████████▌    | 1387/1568 [03:59<00:31,  5.82it/s]16 02:40:53 Save the image 00911N_flip.png
 89%|█████████████████████████████████▋    | 1388/1568 [03:59<00:31,  5.77it/s]16 02:40:53 Save the image 00912N.png
 89%|█████████████████████████████████▋    | 1389/1568 [03:59<00:31,  5.76it/s]16 02:40:53 Save the image 00912N_flip.png
 89%|█████████████████████████████████▋    | 1390/1568 [04:00<00:29,  6.09it/s]16 02:40:53 Save the image 00913N.png
 89%|█████████████████████████████████▋    | 1391/1568 [04:00<00:29,  5.95it/s]16 02:40:54 Save the image 00913N_flip.png
 89%|█████████████████████████████████▋    | 1392/1568 [04:00<00:29,  5.92it/s]16 02:40:54 Save the image 00914N.png
 89%|█████████████████████████████████▊    | 1393/1568 [04:00<00:29,  5.88it/s]16 02:40:54 Save the image 00914N_flip.png
 89%|█████████████████████████████████▊    | 1394/1568 [04:00<00:29,  5.80it/s]16 02:40:54 Save the image 00915N.png
 89%|█████████████████████████████████▊    | 1395/1568 [04:00<00:29,  5.80it/s]16 02:40:54 Save the image 00915N_flip.png
 89%|█████████████████████████████████▊    | 1396/1568 [04:01<00:29,  5.74it/s]16 02:40:54 Save the image 00916N.png
 89%|█████████████████████████████████▊    | 1397/1568 [04:01<00:29,  5.73it/s]16 02:40:55 Save the image 00916N_flip.png
 89%|█████████████████████████████████▉    | 1398/1568 [04:01<00:28,  6.05it/s]16 02:40:55 Save the image 00917N.png
 89%|█████████████████████████████████▉    | 1399/1568 [04:01<00:28,  5.92it/s]16 02:40:55 Save the image 00917N_flip.png
 89%|█████████████████████████████████▉    | 1400/1568 [04:01<00:28,  5.88it/s]16 02:40:55 Save the image 00918N.png

 89%|█████████████████████████████████▉    | 1401/1568 [04:01<00:28,  5.85it/s]16 02:40:55 Save the image 00918N_flip.png
 89%|█████████████████████████████████▉    | 1402/1568 [04:02<00:28,  5.79it/s]16 02:40:55 Save the image 00919N.png
 89%|██████████████████████████████████    | 1403/1568 [04:02<00:28,  5.80it/s]16 02:40:56 Save the image 00919N_flip.png
 90%|██████████████████████████████████    | 1404/1568 [04:02<00:28,  5.71it/s]16 02:40:56 Save the image 00920N.png
 90%|██████████████████████████████████    | 1405/1568 [04:02<00:28,  5.65it/s]16 02:40:56 Save the image 00920N_flip.png
 90%|██████████████████████████████████    | 1406/1568 [04:02<00:27,  5.98it/s]16 02:40:56 Save the image 00921N.png
 90%|██████████████████████████████████    | 1407/1568 [04:02<00:27,  5.84it/s]16 02:40:56 Save the image 00921N_flip.png
 90%|██████████████████████████████████    | 1408/1568 [04:03<00:27,  5.80it/s]16 02:40:57 Save the image 00922N.png
 90%|██████████████████████████████████▏   | 1409/1568 [04:03<00:27,  5.70it/s]16 02:40:57 Save the image 00922N_flip.png
 90%|██████████████████████████████████▏   | 1410/1568 [04:03<00:28,  5.64it/s]16 02:40:57 Save the image 00923N.png
 90%|██████████████████████████████████▏   | 1411/1568 [04:03<00:27,  5.68it/s]16 02:40:57 Save the image 00923N_flip.png
 90%|██████████████████████████████████▏   | 1412/1568 [04:03<00:27,  5.67it/s]16 02:40:57 Save the image 00924N.png
 90%|██████████████████████████████████▏   | 1413/1568 [04:04<00:27,  5.65it/s]16 02:40:57 Save the image 00924N_flip.png
 90%|██████████████████████████████████▎   | 1414/1568 [04:04<00:26,  5.92it/s]16 02:40:58 Save the image 00925N.png
 90%|██████████████████████████████████▎   | 1415/1568 [04:04<00:26,  5.78it/s]16 02:40:58 Save the image 00925N_flip.png
 90%|██████████████████████████████████▎   | 1416/1568 [04:04<00:26,  5.77it/s]16 02:40:58 Save the image 00926N.png
 90%|██████████████████████████████████▎   | 1417/1568 [04:04<00:26,  5.76it/s]16 02:40:58 Save the image 00926N_flip.png
 90%|██████████████████████████████████▎   | 1418/1568 [04:04<00:26,  5.69it/s]16 02:40:58 Save the image 00927N.png
 90%|██████████████████████████████████▍   | 1419/1568 [04:05<00:26,  5.72it/s]16 02:40:58 Save the image 00927N_flip.png
 91%|██████████████████████████████████▍   | 1420/1568 [04:05<00:26,  5.65it/s]16 02:40:59 Save the image 00928N.png
 91%|██████████████████████████████████▍   | 1421/1568 [04:05<00:26,  5.63it/s]16 02:40:59 Save the image 00928N_flip.png
 91%|██████████████████████████████████▍   | 1422/1568 [04:05<00:26,  5.61it/s]16 02:40:59 Save the image 00929N.png
 91%|██████████████████████████████████▍   | 1423/1568 [04:05<00:25,  5.61it/s]16 02:40:59 Save the image 00929N_flip.png
 91%|██████████████████████████████████▌   | 1424/1568 [04:05<00:25,  5.65it/s]16 02:40:59 Save the image 00930N.png
 91%|██████████████████████████████████▌   | 1425/1568 [04:06<00:25,  5.60it/s]16 02:41:00 Save the image 00930N_flip.png
 91%|██████████████████████████████████▌   | 1426/1568 [04:06<00:25,  5.61it/s]16 02:41:00 Save the image 00931N.png
 91%|██████████████████████████████████▌   | 1427/1568 [04:06<00:25,  5.63it/s]16 02:41:00 Save the image 00931N_flip.png
 91%|██████████████████████████████████▌   | 1428/1568 [04:06<00:24,  5.67it/s]16 02:41:00 Save the image 00932N.png
 91%|██████████████████████████████████▋   | 1429/1568 [04:06<00:24,  5.65it/s]16 02:41:00 Save the image 00932N_flip.png
 91%|██████████████████████████████████▋   | 1430/1568 [04:07<00:24,  5.64it/s]16 02:41:00 Save the image 00933N.png
 91%|██████████████████████████████████▋   | 1431/1568 [04:07<00:24,  5.67it/s]16 02:41:01 Save the image 00933N_flip.png
 91%|██████████████████████████████████▋   | 1432/1568 [04:07<00:24,  5.66it/s]16 02:41:01 Save the image 00934N.png
 91%|██████████████████████████████████▋   | 1433/1568 [04:07<00:23,  5.65it/s]16 02:41:01 Save the image 00934N_flip.png
 91%|██████████████████████████████████▊   | 1434/1568 [04:07<00:23,  5.64it/s]16 02:41:01 Save the image 00935N.png
 92%|██████████████████████████████████▊   | 1435/1568 [04:07<00:23,  5.62it/s]16 02:41:01 Save the image 00935N_flip.png
 92%|██████████████████████████████████▊   | 1436/1568 [04:08<00:23,  5.66it/s]16 02:41:01 Save the image 00936N.png
 92%|██████████████████████████████████▊   | 1437/1568 [04:08<00:23,  5.69it/s]16 02:41:02 Save the image 00936N_flip.png
 92%|██████████████████████████████████▊   | 1438/1568 [04:08<00:23,  5.62it/s]16 02:41:02 Save the image 00937N.png
 92%|██████████████████████████████████▊   | 1439/1568 [04:08<00:22,  5.66it/s]16 02:41:02 Save the image 00937N_flip.png
 92%|██████████████████████████████████▉   | 1440/1568 [04:08<00:22,  5.68it/s]16 02:41:02 Save the image 00938N.png
 92%|██████████████████████████████████▉   | 1441/1568 [04:08<00:22,  5.66it/s]16 02:41:02 Save the image 00938N_flip.png
 92%|██████████████████████████████████▉   | 1442/1568 [04:09<00:22,  5.66it/s]16 02:41:03 Save the image 00939N.png
 92%|██████████████████████████████████▉   | 1443/1568 [04:09<00:21,  5.69it/s]16 02:41:03 Save the image 00939N_flip.png
 92%|██████████████████████████████████▉   | 1444/1568 [04:09<00:21,  5.69it/s]16 02:41:03 Save the image 00940N.png
 92%|███████████████████████████████████   | 1445/1568 [04:09<00:20,  6.03it/s]16 02:41:03 Save the image 00940N_flip.png
 92%|███████████████████████████████████   | 1446/1568 [04:09<00:20,  5.92it/s]16 02:41:03 Save the image 00941N.png
 92%|███████████████████████████████████   | 1447/1568 [04:10<00:20,  5.88it/s]16 02:41:03 Save the image 00941N_flip.png
 92%|███████████████████████████████████   | 1448/1568 [04:10<00:20,  5.88it/s]16 02:41:04 Save the image 00942N.png
 92%|███████████████████████████████████   | 1449/1568 [04:10<00:20,  5.81it/s]16 02:41:04 Save the image 00942N_flip.png
 92%|███████████████████████████████████▏  | 1450/1568 [04:10<00:20,  5.85it/s]16 02:41:04 Save the image 00943N.png
 93%|███████████████████████████████████▏  | 1451/1568 [04:10<00:20,  5.79it/s]16 02:41:04 Save the image 00943N_flip.png
 93%|███████████████████████████████████▏  | 1452/1568 [04:10<00:20,  5.79it/s]16 02:41:04 Save the image 00944N.png
 93%|███████████████████████████████████▏  | 1453/1568 [04:11<00:18,  6.13it/s]16 02:41:04 Save the image 00944N_flip.png
 93%|███████████████████████████████████▏  | 1454/1568 [04:11<00:19,  5.98it/s]16 02:41:05 Save the image 00945N.png
 93%|███████████████████████████████████▎  | 1455/1568 [04:11<00:19,  5.93it/s]16 02:41:05 Save the image 00945N_flip.png
 93%|███████████████████████████████████▎  | 1456/1568 [04:11<00:18,  5.91it/s]16 02:41:05 Save the image 00946N.png
 93%|███████████████████████████████████▎  | 1457/1568 [04:11<00:19,  5.84it/s]16 02:41:05 Save the image 00946N_flip.png
 93%|███████████████████████████████████▎  | 1458/1568 [04:11<00:18,  5.85it/s]16 02:41:05 Save the image 00947N.png
 93%|███████████████████████████████████▎  | 1459/1568 [04:12<00:18,  5.79it/s]16 02:41:05 Save the image 00947N_flip.png
 93%|███████████████████████████████████▍  | 1460/1568 [04:12<00:18,  5.78it/s]16 02:41:06 Save the image 00948N.png
 93%|███████████████████████████████████▍  | 1461/1568 [04:12<00:18,  5.79it/s]16 02:41:06 Save the image 00948N_flip.png
 93%|███████████████████████████████████▍  | 1462/1568 [04:12<00:18,  5.78it/s]16 02:41:06 Save the image 00949N.png
 93%|███████████████████████████████████▍  | 1463/1568 [04:12<00:18,  5.78it/s]16 02:41:06 Save the image 00949N_flip.png
 93%|███████████████████████████████████▍  | 1464/1568 [04:12<00:17,  5.78it/s]16 02:41:06 Save the image 00950N.png

 93%|███████████████████████████████████▌  | 1465/1568 [04:13<00:17,  5.75it/s]16 02:41:06 Save the image 00950N_flip.png
 93%|███████████████████████████████████▌  | 1466/1568 [04:13<00:17,  5.80it/s]16 02:41:07 Save the image 00951N.png
 94%|███████████████████████████████████▌  | 1467/1568 [04:13<00:17,  5.82it/s]16 02:41:07 Save the image 00951N_flip.png
 94%|███████████████████████████████████▌  | 1468/1568 [04:13<00:17,  5.77it/s]16 02:41:07 Save the image 00952N.png
 94%|███████████████████████████████████▌  | 1469/1568 [04:13<00:17,  5.74it/s]16 02:41:07 Save the image 00952N_flip.png
 94%|███████████████████████████████████▋  | 1470/1568 [04:13<00:17,  5.75it/s]16 02:41:07 Save the image 00953N.png
 94%|███████████████████████████████████▋  | 1471/1568 [04:14<00:16,  5.78it/s]16 02:41:08 Save the image 00953N_flip.png
 94%|███████████████████████████████████▋  | 1472/1568 [04:14<00:16,  5.75it/s]16 02:41:08 Save the image 00954N.png
 94%|███████████████████████████████████▋  | 1473/1568 [04:14<00:16,  5.76it/s]16 02:41:08 Save the image 00954N_flip.png
 94%|███████████████████████████████████▋  | 1474/1568 [04:14<00:16,  5.76it/s]16 02:41:08 Save the image 00955N.png
 94%|███████████████████████████████████▋  | 1475/1568 [04:14<00:15,  5.83it/s]16 02:41:08 Save the image 00955N_flip.png
 94%|███████████████████████████████████▊  | 1476/1568 [04:14<00:15,  5.93it/s]16 02:41:08 Save the image 00956N.png
 94%|███████████████████████████████████▊  | 1477/1568 [04:15<00:15,  5.85it/s]16 02:41:09 Save the image 00956N_flip.png
 94%|███████████████████████████████████▊  | 1478/1568 [04:15<00:15,  5.86it/s]16 02:41:09 Save the image 00957N.png
 94%|███████████████████████████████████▊  | 1479/1568 [04:15<00:15,  5.83it/s]16 02:41:09 Save the image 00957N_flip.png
 94%|███████████████████████████████████▊  | 1480/1568 [04:15<00:15,  5.78it/s]16 02:41:09 Save the image 00958N.png
 94%|███████████████████████████████████▉  | 1481/1568 [04:15<00:15,  5.79it/s]16 02:41:09 Save the image 00958N_flip.png
 95%|███████████████████████████████████▉  | 1482/1568 [04:16<00:14,  5.81it/s]16 02:41:09 Save the image 00959N.png
 95%|███████████████████████████████████▉  | 1483/1568 [04:16<00:14,  5.88it/s]16 02:41:10 Save the image 00959N_flip.png
 95%|███████████████████████████████████▉  | 1484/1568 [04:16<00:13,  6.09it/s]16 02:41:10 Save the image 00960N.png
 95%|███████████████████████████████████▉  | 1485/1568 [04:16<00:13,  5.95it/s]16 02:41:10 Save the image 00960N_flip.png
 95%|████████████████████████████████████  | 1486/1568 [04:16<00:13,  5.91it/s]16 02:41:10 Save the image 00961N.png
 95%|████████████████████████████████████  | 1487/1568 [04:16<00:13,  5.91it/s]16 02:41:10 Save the image 00961N_flip.png
 95%|████████████████████████████████████  | 1488/1568 [04:17<00:13,  5.84it/s]16 02:41:10 Save the image 00962N.png
 95%|████████████████████████████████████  | 1489/1568 [04:17<00:13,  5.78it/s]16 02:41:11 Save the image 00962N_flip.png
 95%|████████████████████████████████████  | 1490/1568 [04:17<00:13,  5.79it/s]16 02:41:11 Save the image 00963N.png
 95%|████████████████████████████████████▏ | 1491/1568 [04:17<00:13,  5.79it/s]16 02:41:11 Save the image 00963N_flip.png
 95%|████████████████████████████████████▏ | 1492/1568 [04:17<00:12,  6.15it/s]16 02:41:11 Save the image 00964N.png
 95%|████████████████████████████████████▏ | 1493/1568 [04:17<00:12,  6.04it/s]16 02:41:11 Save the image 00964N_flip.png
 95%|████████████████████████████████████▏ | 1494/1568 [04:18<00:12,  5.98it/s]16 02:41:11 Save the image 00965N.png
 95%|████████████████████████████████████▏ | 1495/1568 [04:18<00:12,  5.96it/s]16 02:41:12 Save the image 00965N_flip.png
 95%|████████████████████████████████████▎ | 1496/1568 [04:18<00:12,  5.87it/s]16 02:41:12 Save the image 00966N.png
 95%|████████████████████████████████████▎ | 1497/1568 [04:18<00:12,  5.77it/s]16 02:41:12 Save the image 00966N_flip.png
 96%|████████████████████████████████████▎ | 1498/1568 [04:18<00:12,  5.77it/s]16 02:41:12 Save the image 00967N.png
 96%|████████████████████████████████████▎ | 1499/1568 [04:18<00:11,  5.78it/s]16 02:41:12 Save the image 00967N_flip.png
 96%|████████████████████████████████████▎ | 1500/1568 [04:19<00:11,  6.11it/s]16 02:41:12 Save the image 00968N.png
 96%|████████████████████████████████████▍ | 1501/1568 [04:19<00:11,  5.97it/s]16 02:41:13 Save the image 00968N_flip.png
 96%|████████████████████████████████████▍ | 1502/1568 [04:19<00:11,  5.93it/s]16 02:41:13 Save the image 00969N.png
 96%|████████████████████████████████████▍ | 1503/1568 [04:19<00:10,  5.92it/s]16 02:41:13 Save the image 00969N_flip.png
 96%|████████████████████████████████████▍ | 1504/1568 [04:19<00:10,  5.84it/s]16 02:41:13 Save the image 00970N.png
 96%|████████████████████████████████████▍ | 1505/1568 [04:19<00:10,  5.79it/s]16 02:41:13 Save the image 00970N_flip.png
 96%|████████████████████████████████████▍ | 1506/1568 [04:20<00:10,  5.77it/s]16 02:41:13 Save the image 00971N.png
 96%|████████████████████████████████████▌ | 1507/1568 [04:20<00:10,  5.78it/s]16 02:41:14 Save the image 00971N_flip.png
 96%|████████████████████████████████████▌ | 1508/1568 [04:20<00:09,  6.09it/s]16 02:41:14 Save the image 00972N.png
 96%|████████████████████████████████████▌ | 1509/1568 [04:20<00:09,  5.96it/s]16 02:41:14 Save the image 00972N_flip.png
 96%|████████████████████████████████████▌ | 1510/1568 [04:20<00:09,  5.92it/s]16 02:41:14 Save the image 00973N.png
 96%|████████████████████████████████████▌ | 1511/1568 [04:20<00:09,  5.90it/s]16 02:41:14 Save the image 00973N_flip.png
 96%|████████████████████████████████████▋ | 1512/1568 [04:21<00:09,  5.82it/s]16 02:41:14 Save the image 00974N.png
 96%|████████████████████████████████████▋ | 1513/1568 [04:21<00:09,  5.84it/s]16 02:41:15 Save the image 00974N_flip.png
 97%|████████████████████████████████████▋ | 1514/1568 [04:21<00:09,  5.82it/s]16 02:41:15 Save the image 00975N.png
 97%|████████████████████████████████████▋ | 1515/1568 [04:21<00:09,  5.80it/s]16 02:41:15 Save the image 00975N_flip.png
 97%|████████████████████████████████████▋ | 1516/1568 [04:21<00:08,  6.17it/s]16 02:41:15 Save the image 00976N.png
 97%|████████████████████████████████████▊ | 1517/1568 [04:21<00:08,  6.01it/s]16 02:41:15 Save the image 00976N_flip.png
 97%|████████████████████████████████████▊ | 1518/1568 [04:22<00:08,  5.95it/s]16 02:41:15 Save the image 00977N.png
 97%|████████████████████████████████████▊ | 1519/1568 [04:22<00:08,  5.88it/s]16 02:41:16 Save the image 00977N_flip.png
 97%|████████████████████████████████████▊ | 1520/1568 [04:22<00:08,  5.81it/s]16 02:41:16 Save the image 00978N.png
 97%|████████████████████████████████████▊ | 1521/1568 [04:22<00:08,  5.83it/s]16 02:41:16 Save the image 00978N_flip.png
 97%|████████████████████████████████████▉ | 1522/1568 [04:22<00:07,  5.78it/s]16 02:41:16 Save the image 00979N.png
 97%|████████████████████████████████████▉ | 1523/1568 [04:22<00:07,  5.78it/s]16 02:41:16 Save the image 00979N_flip.png
 97%|████████████████████████████████████▉ | 1524/1568 [04:23<00:07,  5.79it/s]16 02:41:17 Save the image 00980N.png
 97%|████████████████████████████████████▉ | 1525/1568 [04:23<00:07,  5.78it/s]16 02:41:17 Save the image 00980N_flip.png
 97%|████████████████████████████████████▉ | 1526/1568 [04:23<00:07,  5.81it/s]16 02:41:17 Save the image 00981N.png
 97%|█████████████████████████████████████ | 1527/1568 [04:23<00:07,  5.80it/s]16 02:41:17 Save the image 00981N_flip.png
 97%|█████████████████████████████████████ | 1528/1568 [04:23<00:06,  5.76it/s]16 02:41:17 Save the image 00982N.png

 98%|█████████████████████████████████████ | 1529/1568 [04:24<00:06,  5.79it/s]16 02:41:17 Save the image 00982N_flip.png
 98%|█████████████████████████████████████ | 1530/1568 [04:24<00:06,  5.83it/s]16 02:41:18 Save the image 00983N.png
 98%|█████████████████████████████████████ | 1531/1568 [04:24<00:06,  5.79it/s]16 02:41:18 Save the image 00983N_flip.png
 98%|█████████████████████████████████████▏| 1532/1568 [04:24<00:06,  5.79it/s]16 02:41:18 Save the image 00984N.png
 98%|█████████████████████████████████████▏| 1533/1568 [04:24<00:06,  5.81it/s]16 02:41:18 Save the image 00984N_flip.png
 98%|█████████████████████████████████████▏| 1534/1568 [04:24<00:05,  5.79it/s]16 02:41:18 Save the image 00985N.png
 98%|█████████████████████████████████████▏| 1535/1568 [04:25<00:05,  5.72it/s]16 02:41:18 Save the image 00985N_flip.png
 98%|█████████████████████████████████████▏| 1536/1568 [04:25<00:05,  5.73it/s]16 02:41:19 Save the image 00986N.png
 98%|█████████████████████████████████████▏| 1537/1568 [04:25<00:05,  5.74it/s]16 02:41:19 Save the image 00986N_flip.png
 98%|█████████████████████████████████████▎| 1538/1568 [04:25<00:05,  5.79it/s]16 02:41:19 Save the image 00987N.png
 98%|█████████████████████████████████████▎| 1539/1568 [04:25<00:04,  5.97it/s]16 02:41:19 Save the image 00987N_flip.png
 98%|█████████████████████████████████████▎| 1540/1568 [04:25<00:04,  5.88it/s]16 02:41:19 Save the image 00988N.png
 98%|█████████████████████████████████████▎| 1541/1568 [04:26<00:04,  5.85it/s]16 02:41:19 Save the image 00988N_flip.png
 98%|█████████████████████████████████████▎| 1542/1568 [04:26<00:04,  5.85it/s]16 02:41:20 Save the image 00989N.png
 98%|█████████████████████████████████████▍| 1543/1568 [04:26<00:04,  5.80it/s]16 02:41:20 Save the image 00989N_flip.png
 98%|█████████████████████████████████████▍| 1544/1568 [04:26<00:04,  5.81it/s]16 02:41:20 Save the image 00990N.png
 99%|█████████████████████████████████████▍| 1545/1568 [04:26<00:03,  5.80it/s]16 02:41:20 Save the image 00990N_flip.png
 99%|█████████████████████████████████████▍| 1546/1568 [04:26<00:03,  5.77it/s]16 02:41:20 Save the image 00991N.png
 99%|█████████████████████████████████████▍| 1547/1568 [04:27<00:03,  6.14it/s]16 02:41:20 Save the image 00991N_flip.png
 99%|█████████████████████████████████████▌| 1548/1568 [04:27<00:03,  6.01it/s]16 02:41:21 Save the image 00992N.png
 99%|█████████████████████████████████████▌| 1549/1568 [04:27<00:03,  5.97it/s]16 02:41:21 Save the image 00992N_flip.png
 99%|█████████████████████████████████████▌| 1550/1568 [04:27<00:03,  5.94it/s]16 02:41:21 Save the image 00993N.png
 99%|█████████████████████████████████████▌| 1551/1568 [04:27<00:02,  5.87it/s]16 02:41:21 Save the image 00993N_flip.png
 99%|█████████████████████████████████████▌| 1552/1568 [04:27<00:02,  5.81it/s]16 02:41:21 Save the image 00994N.png
 99%|█████████████████████████████████████▋| 1553/1568 [04:28<00:02,  5.80it/s]16 02:41:21 Save the image 00994N_flip.png
 99%|█████████████████████████████████████▋| 1554/1568 [04:28<00:02,  5.80it/s]16 02:41:22 Save the image 00995N.png
 99%|█████████████████████████████████████▋| 1555/1568 [04:28<00:02,  6.14it/s]16 02:41:22 Save the image 00995N_flip.png
 99%|█████████████████████████████████████▋| 1556/1568 [04:28<00:02,  5.98it/s]16 02:41:22 Save the image 00996N.png
 99%|█████████████████████████████████████▋| 1557/1568 [04:28<00:01,  5.93it/s]16 02:41:22 Save the image 00996N_flip.png
 99%|█████████████████████████████████████▊| 1558/1568 [04:28<00:01,  5.91it/s]16 02:41:22 Save the image 00997N.png
 99%|█████████████████████████████████████▊| 1559/1568 [04:29<00:01,  5.84it/s]16 02:41:23 Save the image 00997N_flip.png
 99%|█████████████████████████████████████▊| 1560/1568 [04:29<00:01,  5.79it/s]16 02:41:23 Save the image 00998N.png
100%|█████████████████████████████████████▊| 1561/1568 [04:29<00:01,  5.77it/s]16 02:41:23 Save the image 00998N_flip.png
100%|█████████████████████████████████████▊| 1562/1568 [04:29<00:01,  5.77it/s]16 02:41:23 Save the image 00999N.png
100%|█████████████████████████████████████▉| 1563/1568 [04:29<00:00,  6.15it/s]16 02:41:23 Save the image 00999N_flip.png
100%|█████████████████████████████████████▉| 1564/1568 [04:29<00:00,  6.00it/s]16 02:41:23 Save the image 01000N.png
100%|█████████████████████████████████████▉| 1565/1568 [04:30<00:00,  5.94it/s]16 02:41:24 Save the image 01000N_flip.png
100%|█████████████████████████████████████▉| 1566/1568 [04:30<00:00,  5.91it/s]16 02:41:24 Save the image 01001N.png
100%|█████████████████████████████████████▉| 1567/1568 [04:30<00:00,  5.83it/s]16 02:41:24 Save the image 01001N_flip.png
100%|██████████████████████████████████████| 1568/1568 [04:30<00:00,  5.79it/s]
1 unlabeled	99.520%
2 car   	97.232%
3 person	89.233%
4 bike  	90.006%
5 curve 	90.455%
6 car_stop	92.457%
7 guardrail	95.618%
8 color_cone	85.688%
9 bump  	94.267%
----------     mean_IoU	92.720%	freq_IoU	99.092%	mean_pixel_acc	96.772%	pixel_acc	99.535%
16 02:41:24 Evaluation Elapsed Time: 270.66s

# e1

In [9]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E1")

!python eval.py -e 100 -d 0 --split test -p predictions_E1_test

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:44:41 using devices 0
16 02:44:41 Using E1: SegFormer-B2 without FRM
16 02:44:42 Using MLP Decoder
16 02:44:42 Load Model: /home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth
16 02:44:46 Load model, Time usage:
	IO: 3.9483625888824463, initialize parameters: 0.043245553970336914
16 02:44:46 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@8.194] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:44:47 Save the image 01402D.png
  0%|                                          | 1/393 [00:01<09:43,  1.49s/it]16 02:44:47 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:01<04:39,  1.40it/s]16 02:44:47 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:01<02:55,  2.22it/s]16 02:44:48 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:01<02:12,  2.94it/s]16 02:44:48 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:02<01:47,  3.61it/s]16 02:44:48 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:02<01:33,  4.14it/s]16 02:44:48 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:02<01:24,  4.56it/s]16 02:44:48 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:02<01:18,  4.90it/s]16 02:44:48 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:02<01:14,  5.16it/s]16 02:44:49 Save the image 01411D.png
  3%|█                                        | 10/393 [00:02<01:11,  5.32it/s]16 02:44:49 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:03<01:06,  5.72it/s]16 02:44:49 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:03<01:06,  5.72it/s]16 02:44:49 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:03<01:05,  5.79it/s]16 02:44:49 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:03<01:05,  5.78it/s]16 02:44:49 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:03<01:05,  5.76it/s]16 02:44:50 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:04<01:05,  5.77it/s]16 02:44:50 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:04<01:05,  5.78it/s]16 02:44:50 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:04<01:04,  5.86it/s]16 02:44:50 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:04<01:02,  6.00it/s]16 02:44:50 Save the image 01421D.png
  5%|██                                       | 20/393 [00:04<01:03,  5.89it/s]16 02:44:50 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:04<01:03,  5.90it/s]16 02:44:51 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:05<01:03,  5.87it/s]16 02:44:51 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:05<01:03,  5.86it/s]16 02:44:51 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:05<01:03,  5.84it/s]16 02:44:51 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:05<01:03,  5.83it/s]16 02:44:51 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:05<01:02,  5.88it/s]16 02:44:51 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:05<01:00,  6.00it/s]16 02:44:52 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:06<01:01,  5.90it/s]16 02:44:52 Save the image 01430D.png
  7%|███                                      | 29/393 [00:06<01:02,  5.86it/s]16 02:44:52 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:06<01:01,  5.91it/s]16 02:44:52 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:06<01:01,  5.87it/s]16 02:44:52 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:06<01:01,  5.88it/s]16 02:44:52 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:06<01:01,  5.86it/s]16 02:44:53 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:07<01:01,  5.88it/s]16 02:44:53 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:07<01:00,  5.92it/s]16 02:44:53 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:07<01:01,  5.84it/s]16 02:44:53 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:07<01:00,  5.86it/s]16 02:44:53 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:07<01:00,  5.89it/s]16 02:44:53 Save the image 01440D.png
 10%|████                                     | 39/393 [00:07<01:00,  5.85it/s]16 02:44:54 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:08<01:00,  5.87it/s]16 02:44:54 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:08<01:00,  5.86it/s]16 02:44:54 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:08<00:59,  5.91it/s]16 02:44:54 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:08<00:58,  6.00it/s]16 02:44:54 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:08<00:58,  5.95it/s]16 02:44:54 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:08<00:58,  5.97it/s]16 02:44:55 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:09<00:57,  6.00it/s]16 02:44:55 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:09<00:58,  5.93it/s]16 02:44:55 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:09<00:58,  5.91it/s]16 02:44:55 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:09<00:58,  5.89it/s]16 02:44:55 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:09<00:57,  5.94it/s]16 02:44:56 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:09<00:57,  5.99it/s]16 02:44:56 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:10<00:57,  5.93it/s]16 02:44:56 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:10<00:57,  5.91it/s]16 02:44:56 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:10<00:57,  5.87it/s]16 02:44:56 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:10<00:57,  5.84it/s]16 02:44:56 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:10<00:57,  5.81it/s]16 02:44:57 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:10<00:57,  5.80it/s]16 02:44:57 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:11<00:57,  5.86it/s]16 02:44:57 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:11<00:57,  5.85it/s]16 02:44:57 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:11<00:57,  5.83it/s]16 02:44:57 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:11<00:57,  5.82it/s]16 02:44:57 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:11<00:56,  5.82it/s]16 02:44:58 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:11<00:56,  5.79it/s]16 02:44:58 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:12<00:56,  5.78it/s]16 02:44:58 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:12<00:56,  5.77it/s]16 02:44:58 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:12<00:56,  5.79it/s]16 02:44:58 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:12<00:56,  5.81it/s]16 02:44:58 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:12<00:56,  5.78it/s]16 02:44:59 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:13<00:56,  5.76it/s]16 02:44:59 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:13<00:55,  5.78it/s]16 02:44:59 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:13<00:55,  5.78it/s]16 02:44:59 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:13<00:55,  5.76it/s]16 02:44:59 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:13<00:55,  5.73it/s]16 02:44:59 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:13<00:54,  5.83it/s]16 02:45:00 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:14<00:54,  5.87it/s]16 02:45:00 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:14<00:54,  5.78it/s]16 02:45:00 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:14<00:54,  5.80it/s]16 02:45:00 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:14<00:54,  5.83it/s]16 02:45:00 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:14<00:54,  5.77it/s]16 02:45:01 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:14<00:54,  5.79it/s]16 02:45:01 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:15<00:54,  5.73it/s]16 02:45:01 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:15<00:53,  5.80it/s]16 02:45:01 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:15<00:52,  5.96it/s]16 02:45:01 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:15<00:52,  5.86it/s]16 02:45:01 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:15<00:52,  5.84it/s]16 02:45:02 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:15<00:52,  5.88it/s]16 02:45:02 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:16<00:52,  5.81it/s]16 02:45:02 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:16<00:52,  5.76it/s]16 02:45:02 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:16<00:52,  5.78it/s]16 02:45:02 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:16<00:51,  5.86it/s]16 02:45:02 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:16<00:51,  5.90it/s]16 02:45:03 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:16<00:51,  5.80it/s]16 02:45:03 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:17<00:51,  5.82it/s]16 02:45:03 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:17<00:50,  5.87it/s]16 02:45:03 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:17<00:50,  5.86it/s]16 02:45:03 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:17<00:50,  5.84it/s]16 02:45:03 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:17<00:50,  5.84it/s]16 02:45:04 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:18<00:49,  5.91it/s]16 02:45:04 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:18<00:49,  6.00it/s]16 02:45:04 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:18<00:49,  5.95it/s]16 02:45:04 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:18<00:49,  5.93it/s]16 02:45:04 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:18<00:48,  5.94it/s]16 02:45:04 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:18<00:49,  5.91it/s]16 02:45:05 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:19<00:48,  5.90it/s]16 02:45:05 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:19<00:48,  5.91it/s]16 02:45:05 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:19<00:48,  5.95it/s]16 02:45:05 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:19<00:46,  6.12it/s]16 02:45:05 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:19<00:47,  6.03it/s]16 02:45:05 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:19<00:47,  6.01it/s]16 02:45:06 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:20<00:47,  5.99it/s]16 02:45:06 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:20<00:47,  5.92it/s]16 02:45:06 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:20<00:47,  5.88it/s]16 02:45:06 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:20<00:47,  5.87it/s]16 02:45:06 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:20<00:47,  5.93it/s]16 02:45:06 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:20<00:45,  6.13it/s]16 02:45:07 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:21<00:45,  6.03it/s]16 02:45:07 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:21<00:46,  5.94it/s]16 02:45:07 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:21<00:46,  5.93it/s]16 02:45:07 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:21<00:46,  5.89it/s]16 02:45:07 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:21<00:46,  5.87it/s]16 02:45:07 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:21<00:46,  5.85it/s]16 02:45:08 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:22<00:46,  5.83it/s]16 02:45:08 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:22<00:43,  6.15it/s]16 02:45:08 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:22<00:44,  6.06it/s]16 02:45:08 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:22<00:44,  6.02it/s]16 02:45:08 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:22<00:44,  6.02it/s]16 02:45:08 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:22<00:44,  5.96it/s]16 02:45:09 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:23<00:44,  5.92it/s]16 02:45:09 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:23<00:44,  5.87it/s]16 02:45:09 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:23<00:44,  5.92it/s]16 02:45:09 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:23<00:42,  6.12it/s]16 02:45:09 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:23<00:43,  6.03it/s]16 02:45:09 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:23<00:43,  6.00it/s]16 02:45:10 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:24<00:43,  5.97it/s]16 02:45:10 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:24<00:43,  5.90it/s]16 02:45:10 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:24<00:43,  5.90it/s]16 02:45:10 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:24<00:43,  5.87it/s]16 02:45:10 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:24<00:43,  5.84it/s]16 02:45:10 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:24<00:41,  6.17it/s]16 02:45:11 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:25<00:41,  6.06it/s]16 02:45:11 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:25<00:41,  6.02it/s]16 02:45:11 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:25<00:41,  5.99it/s]16 02:45:11 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:25<00:42,  5.92it/s]16 02:45:11 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:25<00:42,  5.89it/s]16 02:45:11 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:25<00:42,  5.86it/s]16 02:45:12 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:26<00:42,  5.77it/s]16 02:45:12 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:26<00:39,  6.15it/s]16 02:45:12 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:26<00:40,  6.04it/s]16 02:45:12 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:26<00:40,  6.01it/s]16 02:45:12 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:26<00:40,  5.98it/s]16 02:45:12 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:26<00:40,  5.93it/s]16 02:45:13 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:27<00:40,  5.89it/s]16 02:45:13 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:27<00:40,  5.85it/s]16 02:45:13 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:27<00:40,  5.85it/s]16 02:45:13 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:27<00:38,  6.21it/s]16 02:45:13 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:27<00:38,  6.08it/s]16 02:45:13 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:27<00:39,  6.04it/s]16 02:45:14 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:28<00:39,  5.99it/s]16 02:45:14 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:28<00:39,  5.94it/s]16 02:45:14 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:28<00:39,  5.90it/s]16 02:45:14 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:28<00:39,  5.91it/s]16 02:45:14 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:28<00:39,  5.89it/s]16 02:45:14 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:28<00:36,  6.25it/s]16 02:45:15 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:29<00:37,  6.11it/s]16 02:45:15 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:29<00:37,  6.05it/s]16 02:45:15 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:29<00:37,  6.01it/s]16 02:45:15 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:29<00:37,  5.95it/s]16 02:45:15 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:29<00:38,  5.91it/s]16 02:45:15 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:29<00:37,  5.92it/s]16 02:45:16 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:30<00:37,  5.87it/s]16 02:45:16 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:30<00:35,  6.21it/s]16 02:45:16 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:30<00:36,  6.09it/s]16 02:45:16 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:30<00:36,  6.06it/s]16 02:45:16 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:30<00:36,  6.03it/s]16 02:45:16 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:30<00:36,  5.96it/s]16 02:45:17 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:31<00:36,  5.91it/s]16 02:45:17 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:31<00:36,  5.89it/s]16 02:45:17 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:31<00:36,  5.94it/s]16 02:45:17 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:31<00:34,  6.12it/s]16 02:45:17 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:31<00:35,  6.01it/s]16 02:45:17 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:31<00:35,  5.99it/s]16 02:45:18 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:32<00:35,  5.93it/s]16 02:45:18 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:32<00:35,  5.89it/s]16 02:45:18 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:32<00:35,  5.86it/s]16 02:45:18 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:32<00:35,  5.84it/s]16 02:45:18 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:32<00:35,  5.84it/s]16 02:45:18 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:32<00:33,  6.17it/s]16 02:45:19 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:33<00:33,  6.05it/s]16 02:45:19 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:33<00:33,  6.02it/s]16 02:45:19 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:33<00:34,  5.95it/s]16 02:45:19 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:33<00:34,  5.90it/s]16 02:45:19 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:33<00:34,  5.87it/s]16 02:45:20 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:33<00:33,  5.88it/s]16 02:45:20 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:34<00:33,  5.87it/s]16 02:45:20 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:34<00:31,  6.20it/s]16 02:45:20 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:34<00:32,  6.07it/s]16 02:45:20 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:34<00:32,  6.03it/s]16 02:45:20 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:34<00:32,  5.96it/s]16 02:45:21 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:34<00:32,  5.90it/s]16 02:45:21 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:35<00:32,  5.87it/s]16 02:45:21 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:35<00:32,  5.85it/s]16 02:45:21 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:35<00:32,  5.85it/s]16 02:45:21 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:35<00:30,  6.21it/s]16 02:45:21 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:35<00:31,  6.08it/s]16 02:45:21 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:35<00:31,  6.04it/s]16 02:45:22 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:36<00:31,  6.02it/s]16 02:45:22 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:36<00:31,  5.95it/s]16 02:45:22 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:36<00:31,  5.93it/s]16 02:45:22 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:36<00:30,  5.94it/s]16 02:45:22 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:36<00:30,  5.92it/s]16 02:45:22 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:36<00:29,  6.23it/s]16 02:45:23 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:37<00:29,  6.10it/s]16 02:45:23 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:37<00:29,  6.05it/s]16 02:45:23 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:37<00:29,  6.01it/s]16 02:45:23 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:37<00:29,  5.96it/s]16 02:45:23 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:37<00:29,  5.96it/s]16 02:45:24 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:37<00:29,  5.94it/s]16 02:45:24 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:38<00:29,  6.00it/s]16 02:45:24 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:38<00:28,  6.08it/s]16 02:45:24 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:38<00:28,  6.00it/s]16 02:45:24 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:38<00:28,  6.00it/s]16 02:45:24 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:38<00:28,  5.98it/s]16 02:45:25 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:38<00:28,  5.92it/s]16 02:45:25 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:39<00:28,  5.91it/s]16 02:45:25 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:39<00:28,  5.90it/s]16 02:45:25 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:39<00:28,  5.96it/s]16 02:45:25 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:39<00:27,  6.06it/s]16 02:45:25 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:39<00:27,  6.00it/s]16 02:45:26 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:39<00:27,  5.98it/s]16 02:45:26 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:40<00:27,  5.97it/s]16 02:45:26 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:40<00:27,  5.90it/s]16 02:45:26 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:40<00:27,  5.90it/s]16 02:45:26 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:40<00:27,  5.90it/s]16 02:45:26 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:40<00:26,  5.97it/s]16 02:45:27 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:40<00:26,  6.06it/s]16 02:45:27 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:41<00:26,  6.00it/s]16 02:45:27 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:41<00:26,  6.00it/s]16 02:45:27 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:41<00:25,  5.99it/s]16 02:45:27 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:41<00:25,  5.95it/s]16 02:45:27 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:41<00:25,  5.94it/s]16 02:45:28 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:41<00:25,  5.90it/s]16 02:45:28 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:42<00:25,  5.95it/s]16 02:45:28 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:42<00:24,  6.05it/s]16 02:45:28 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:42<00:24,  5.98it/s]16 02:45:28 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:42<00:24,  5.96it/s]16 02:45:28 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:42<00:24,  5.97it/s]16 02:45:29 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:42<00:24,  5.91it/s]16 02:45:29 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:43<00:24,  5.93it/s]16 02:45:29 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:43<00:24,  5.91it/s]16 02:45:29 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:43<00:24,  5.95it/s]16 02:45:29 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:43<00:23,  6.06it/s]16 02:45:29 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:43<00:23,  5.99it/s]16 02:45:30 Save the image 01236N.png

 64%|█████████████████████████▊              | 253/393 [00:43<00:23,  5.98it/s]16 02:45:30 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:44<00:23,  5.92it/s]16 02:45:30 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:44<00:23,  5.89it/s]16 02:45:30 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:44<00:23,  5.89it/s]16 02:45:30 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:44<00:23,  5.90it/s]16 02:45:30 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:44<00:22,  5.96it/s]16 02:45:31 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:44<00:21,  6.11it/s]16 02:45:31 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:45<00:22,  6.04it/s]16 02:45:31 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:45<00:21,  6.03it/s]16 02:45:31 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:45<00:21,  6.03it/s]16 02:45:31 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:45<00:21,  5.96it/s]16 02:45:31 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:45<00:21,  5.97it/s]16 02:45:32 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:45<00:21,  5.94it/s]16 02:45:32 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:46<00:21,  5.99it/s]16 02:45:32 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:46<00:20,  6.01it/s]16 02:45:32 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:46<00:20,  5.97it/s]16 02:45:32 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:46<00:20,  5.96it/s]16 02:45:32 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:46<00:20,  5.98it/s]16 02:45:33 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:46<00:20,  5.96it/s]16 02:45:33 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:47<00:20,  5.96it/s]16 02:45:33 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:47<00:20,  5.98it/s]16 02:45:33 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:47<00:19,  6.01it/s]16 02:45:33 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:47<00:19,  6.03it/s]16 02:45:33 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:47<00:19,  5.96it/s]16 02:45:34 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:47<00:19,  5.97it/s]16 02:45:34 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:48<00:19,  5.95it/s]16 02:45:34 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:48<00:19,  5.90it/s]16 02:45:34 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:48<00:19,  5.88it/s]16 02:45:34 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:48<00:19,  5.86it/s]16 02:45:34 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:48<00:18,  5.94it/s]16 02:45:35 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:48<00:18,  6.06it/s]16 02:45:35 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:49<00:18,  5.99it/s]16 02:45:35 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:49<00:18,  6.00it/s]16 02:45:35 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:49<00:17,  5.99it/s]16 02:45:35 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:49<00:17,  5.95it/s]16 02:45:35 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:49<00:17,  5.93it/s]16 02:45:36 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:50<00:17,  5.84it/s]16 02:45:36 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:50<00:17,  5.92it/s]16 02:45:36 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:50<00:16,  6.07it/s]16 02:45:36 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:50<00:16,  6.00it/s]16 02:45:36 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:50<00:16,  6.00it/s]16 02:45:36 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:50<00:16,  5.95it/s]16 02:45:37 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:50<00:16,  5.91it/s]16 02:45:37 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:51<00:16,  5.89it/s]16 02:45:37 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:51<00:16,  5.86it/s]16 02:45:37 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:51<00:16,  5.92it/s]16 02:45:37 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:51<00:15,  6.10it/s]16 02:45:37 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:51<00:15,  6.02it/s]16 02:45:38 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:52<00:15,  5.99it/s]16 02:45:38 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:52<00:15,  5.93it/s]16 02:45:38 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:52<00:15,  5.90it/s]16 02:45:38 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:52<00:15,  5.87it/s]16 02:45:38 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:52<00:15,  5.86it/s]16 02:45:38 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:52<00:14,  5.84it/s]16 02:45:39 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:53<00:13,  6.17it/s]16 02:45:39 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:53<00:14,  6.05it/s]16 02:45:39 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:53<00:13,  6.02it/s]16 02:45:39 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:53<00:13,  5.99it/s]16 02:45:39 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:53<00:13,  5.93it/s]16 02:45:39 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:53<00:13,  5.90it/s]16 02:45:40 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:54<00:13,  5.88it/s]16 02:45:40 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:54<00:13,  5.88it/s]16 02:45:40 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:54<00:12,  6.22it/s]16 02:45:40 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:54<00:12,  6.10it/s]16 02:45:40 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:54<00:12,  6.07it/s]16 02:45:40 Save the image 01301N.png

 81%|████████████████████████████████▎       | 318/393 [00:54<00:12,  6.05it/s]16 02:45:41 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:55<00:12,  5.96it/s]16 02:45:41 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:55<00:12,  5.94it/s]16 02:45:41 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:55<00:12,  5.92it/s]16 02:45:41 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:55<00:11,  5.98it/s]16 02:45:41 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [00:55<00:11,  6.07it/s]16 02:45:41 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:55<00:11,  5.98it/s]16 02:45:42 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:56<00:11,  5.99it/s]16 02:45:42 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:56<00:11,  5.98it/s]16 02:45:42 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:56<00:11,  5.93it/s]16 02:45:42 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:56<00:10,  5.94it/s]16 02:45:42 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:56<00:10,  5.92it/s]16 02:45:42 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:56<00:10,  5.96it/s]16 02:45:43 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:57<00:10,  6.06it/s]16 02:45:43 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [00:57<00:10,  5.98it/s]16 02:45:43 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:57<00:10,  5.99it/s]16 02:45:43 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [00:57<00:09,  5.98it/s]16 02:45:43 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [00:57<00:09,  5.95it/s]16 02:45:43 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [00:57<00:09,  5.96it/s]16 02:45:44 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [00:58<00:09,  5.93it/s]16 02:45:44 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [00:58<00:09,  5.96it/s]16 02:45:44 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [00:58<00:08,  6.03it/s]16 02:45:44 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [00:58<00:08,  5.98it/s]16 02:45:44 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [00:58<00:08,  5.96it/s]16 02:45:44 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [00:58<00:08,  5.97it/s]16 02:45:45 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [00:59<00:08,  5.92it/s]16 02:45:45 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [00:59<00:08,  5.89it/s]16 02:45:45 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [00:59<00:08,  5.89it/s]16 02:45:45 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [00:59<00:07,  5.93it/s]16 02:45:45 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [00:59<00:07,  6.08it/s]16 02:45:45 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [00:59<00:07,  6.00it/s]16 02:45:46 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [01:00<00:07,  5.93it/s]16 02:45:46 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [01:00<00:07,  5.93it/s]16 02:45:46 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [01:00<00:07,  5.89it/s]16 02:45:46 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [01:00<00:06,  5.86it/s]16 02:45:46 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [01:00<00:06,  5.89it/s]16 02:45:46 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [01:00<00:06,  5.92it/s]16 02:45:47 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [01:01<00:06,  6.16it/s]16 02:45:47 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [01:01<00:06,  6.05it/s]16 02:45:47 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [01:01<00:05,  6.01it/s]16 02:45:47 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [01:01<00:05,  5.98it/s]16 02:45:47 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [01:01<00:05,  5.92it/s]16 02:45:47 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [01:01<00:05,  5.89it/s]16 02:45:48 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [01:02<00:05,  5.88it/s]16 02:45:48 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [01:02<00:05,  5.93it/s]16 02:45:48 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [01:02<00:04,  6.13it/s]16 02:45:48 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [01:02<00:04,  6.02it/s]16 02:45:48 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [01:02<00:04,  5.99it/s]16 02:45:48 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [01:02<00:04,  5.93it/s]16 02:45:49 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [01:03<00:04,  5.84it/s]16 02:45:49 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [01:03<00:04,  5.81it/s]16 02:45:49 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [01:03<00:04,  5.81it/s]16 02:45:49 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [01:03<00:03,  5.90it/s]16 02:45:49 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [01:03<00:03,  5.86it/s]16 02:45:50 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [01:03<00:03,  5.84it/s]16 02:45:50 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [01:04<00:03,  5.86it/s]16 02:45:50 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [01:04<00:03,  5.88it/s]16 02:45:50 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [01:04<00:03,  5.86it/s]16 02:45:50 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [01:04<00:02,  5.84it/s]16 02:45:50 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [01:04<00:02,  5.80it/s]16 02:45:51 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [01:04<00:02,  5.83it/s]16 02:45:51 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [01:05<00:02,  5.82it/s]16 02:45:51 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [01:05<00:02,  5.84it/s]16 02:45:51 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [01:05<00:02,  5.83it/s]16 02:45:51 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [01:05<00:01,  5.81it/s]16 02:45:51 Save the image 01366N.png

 97%|██████████████████████████████████████▉ | 383/393 [01:05<00:01,  5.81it/s]16 02:45:52 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [01:05<00:01,  5.79it/s]16 02:45:52 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [01:06<00:01,  5.80it/s]16 02:45:52 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [01:06<00:01,  5.88it/s]16 02:45:52 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [01:06<00:01,  5.81it/s]16 02:45:52 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [01:06<00:00,  5.75it/s]16 02:45:52 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [01:06<00:00,  5.78it/s]16 02:45:53 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [01:07<00:00,  5.84it/s]16 02:45:53 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [01:07<00:00,  5.80it/s]16 02:45:53 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [01:07<00:00,  5.83it/s]16 02:45:53 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [01:07<00:00,  5.82it/s]
1 unlabeled	98.237%
2 car   	88.676%
3 person	74.412%
4 bike  	64.871%
5 curve 	46.047%
6 car_stop	29.591%
7 guardrail	6.372%
8 color_cone	44.308%
9 bump  	58.564%
----------     mean_IoU	56.786%	freq_IoU	96.664%	mean_pixel_acc	65.979%	pixel_acc	98.176%
16 02:45:53 Evaluation Elapsed Time: 67.54s

In [10]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E1")

!python eval.py -e 100 -d 0 --split val -p predictions_E1_val

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:46:17 using devices 0
16 02:46:17 Using E1: SegFormer-B2 without FRM
16 02:46:18 Using MLP Decoder
16 02:46:20 Load Model: /home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth
16 02:46:24 Load model, Time usage:
	IO: 4.102044343948364, initialize parameters: 0.042738914489746094
16 02:46:24 GPU 0 handle 392 data.
  0%|                                                  | 0/392 [00:00<?, ?it/s][ WARN:0@10.188] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:46:25 Save the image 00498D.png
  0%|                                          | 1/392 [00:01<09:26,  1.45s/it]16 02:46:26 Save the image 00499D.png
  1%|▏                                         | 2/392 [00:01<04:30,  1.44it/s]16 02:46:26 Save the image 00500D.png
  1%|▎                                         | 3/392 [00:01<02:57,  2.19it/s]16 02:46:26 Save the image 00501D.png
  1%|▍                                         | 4/392 [00:01<02:13,  2.91it/s]16 02:46:26 Save the image 00502D.png
  1%|▌                                         | 5/392 [00:02<01:48,  3.56it/s]16 02:46:26 Save the image 00503D.png
  2%|▋                                         | 6/392 [00:02<01:33,  4.14it/s]16 02:46:26 Save the image 00504D.png
  2%|▊                                         | 7/392 [00:02<01:23,  4.62it/s]16 02:46:27 Save the image 00505D.png
  2%|▊                                         | 8/392 [00:02<01:17,  4.94it/s]16 02:46:27 Save the image 00506D.png
  2%|▉                                         | 9/392 [00:02<01:13,  5.21it/s]16 02:46:27 Save the image 00507D.png
  3%|█                                        | 10/392 [00:02<01:10,  5.40it/s]16 02:46:27 Save the image 00508D.png
  3%|█▏                                       | 11/392 [00:03<01:09,  5.52it/s]16 02:46:27 Save the image 00509D.png
  3%|█▎                                       | 12/392 [00:03<01:07,  5.60it/s]16 02:46:27 Save the image 00510D.png
  3%|█▎                                       | 13/392 [00:03<01:07,  5.65it/s]16 02:46:28 Save the image 00511D.png
  4%|█▍                                       | 14/392 [00:03<01:05,  5.77it/s]16 02:46:28 Save the image 00512D.png
  4%|█▌                                       | 15/392 [00:03<01:02,  6.01it/s]16 02:46:28 Save the image 00513D.png
  4%|█▋                                       | 16/392 [00:03<01:03,  5.95it/s]16 02:46:28 Save the image 00514D.png
  4%|█▊                                       | 17/392 [00:04<01:03,  5.95it/s]16 02:46:28 Save the image 00515D.png
  5%|█▉                                       | 18/392 [00:04<01:03,  5.93it/s]16 02:46:28 Save the image 00516D.png
  5%|█▉                                       | 19/392 [00:04<01:03,  5.86it/s]16 02:46:29 Save the image 00517D.png
  5%|██                                       | 20/392 [00:04<01:03,  5.84it/s]16 02:46:29 Save the image 00518D.png
  5%|██▏                                      | 21/392 [00:04<01:03,  5.83it/s]16 02:46:29 Save the image 00519D.png
  6%|██▎                                      | 22/392 [00:05<01:03,  5.83it/s]16 02:46:29 Save the image 00520D.png
  6%|██▍                                      | 23/392 [00:05<00:59,  6.16it/s]16 02:46:29 Save the image 00521D.png
  6%|██▌                                      | 24/392 [00:05<01:00,  6.05it/s]16 02:46:29 Save the image 00522D.png
  6%|██▌                                      | 25/392 [00:05<01:00,  6.03it/s]16 02:46:30 Save the image 00523D.png
  7%|██▋                                      | 26/392 [00:05<01:01,  5.98it/s]16 02:46:30 Save the image 00524D.png
  7%|██▊                                      | 27/392 [00:05<01:01,  5.92it/s]16 02:46:30 Save the image 00525D.png
  7%|██▉                                      | 28/392 [00:05<01:01,  5.93it/s]16 02:46:30 Save the image 00526D.png
  7%|███                                      | 29/392 [00:06<01:01,  5.93it/s]16 02:46:30 Save the image 00527D.png
  8%|███▏                                     | 30/392 [00:06<01:00,  6.00it/s]16 02:46:30 Save the image 00528D.png
  8%|███▏                                     | 31/392 [00:06<00:59,  6.10it/s]16 02:46:31 Save the image 00529D.png
  8%|███▎                                     | 32/392 [00:06<00:59,  6.01it/s]16 02:46:31 Save the image 00530D.png
  8%|███▍                                     | 33/392 [00:06<00:59,  5.98it/s]16 02:46:31 Save the image 00531D.png
  9%|███▌                                     | 34/392 [00:06<00:59,  5.98it/s]16 02:46:31 Save the image 00532D.png
  9%|███▋                                     | 35/392 [00:07<01:00,  5.93it/s]16 02:46:31 Save the image 00533D.png
  9%|███▊                                     | 36/392 [00:07<00:59,  5.94it/s]16 02:46:31 Save the image 00534D.png
  9%|███▊                                     | 37/392 [00:07<01:00,  5.90it/s]16 02:46:32 Save the image 00535D.png
 10%|███▉                                     | 38/392 [00:07<00:59,  5.95it/s]16 02:46:32 Save the image 00536D.png
 10%|████                                     | 39/392 [00:07<00:57,  6.09it/s]16 02:46:32 Save the image 00537D.png
 10%|████▏                                    | 40/392 [00:07<00:58,  6.01it/s]16 02:46:32 Save the image 00538D.png
 10%|████▎                                    | 41/392 [00:08<00:58,  5.98it/s]16 02:46:32 Save the image 00539D.png
 11%|████▍                                    | 42/392 [00:08<00:58,  5.96it/s]16 02:46:32 Save the image 00540D.png
 11%|████▍                                    | 43/392 [00:08<00:59,  5.90it/s]16 02:46:33 Save the image 00541D.png
 11%|████▌                                    | 44/392 [00:08<00:59,  5.88it/s]16 02:46:33 Save the image 00542D.png
 11%|████▋                                    | 45/392 [00:08<00:59,  5.88it/s]16 02:46:33 Save the image 00543D.png
 12%|████▊                                    | 46/392 [00:09<00:58,  5.95it/s]16 02:46:33 Save the image 00544D.png
 12%|████▉                                    | 47/392 [00:09<00:57,  6.04it/s]16 02:46:33 Save the image 00545D.png
 12%|█████                                    | 48/392 [00:09<00:57,  5.95it/s]16 02:46:33 Save the image 00546D.png
 12%|█████▏                                   | 49/392 [00:09<00:57,  5.95it/s]16 02:46:34 Save the image 00547D.png
 13%|█████▏                                   | 50/392 [00:09<00:57,  5.95it/s]16 02:46:34 Save the image 00548D.png
 13%|█████▎                                   | 51/392 [00:09<00:57,  5.91it/s]16 02:46:34 Save the image 00549D.png
 13%|█████▍                                   | 52/392 [00:10<00:57,  5.87it/s]16 02:46:34 Save the image 00550D.png
 14%|█████▌                                   | 53/392 [00:10<00:57,  5.90it/s]16 02:46:34 Save the image 00551D.png
 14%|█████▋                                   | 54/392 [00:10<00:57,  5.88it/s]16 02:46:34 Save the image 00552D.png
 14%|█████▊                                   | 55/392 [00:10<00:54,  6.21it/s]16 02:46:35 Save the image 00553D.png
 14%|█████▊                                   | 56/392 [00:10<00:55,  6.05it/s]16 02:46:35 Save the image 00554D.png
 15%|█████▉                                   | 57/392 [00:10<00:56,  5.98it/s]16 02:46:35 Save the image 00555D.png

 15%|██████                                   | 58/392 [00:11<00:56,  5.96it/s]16 02:46:35 Save the image 00556D.png
 15%|██████▏                                  | 59/392 [00:11<00:56,  5.89it/s]16 02:46:35 Save the image 00557D.png
 15%|██████▎                                  | 60/392 [00:11<00:56,  5.84it/s]16 02:46:36 Save the image 00558D.png
 16%|██████▍                                  | 61/392 [00:11<00:56,  5.83it/s]16 02:46:36 Save the image 00559D.png
 16%|██████▍                                  | 62/392 [00:11<00:56,  5.89it/s]16 02:46:36 Save the image 00560D.png
 16%|██████▌                                  | 63/392 [00:11<00:55,  5.93it/s]16 02:46:36 Save the image 00561D.png
 16%|██████▋                                  | 64/392 [00:12<00:55,  5.86it/s]16 02:46:36 Save the image 00562D.png
 17%|██████▊                                  | 65/392 [00:12<00:55,  5.85it/s]16 02:46:36 Save the image 00563D.png
 17%|██████▉                                  | 66/392 [00:12<00:55,  5.83it/s]16 02:46:37 Save the image 00564D.png
 17%|███████                                  | 67/392 [00:12<00:56,  5.78it/s]16 02:46:37 Save the image 00565D.png
 17%|███████                                  | 68/392 [00:12<00:55,  5.81it/s]16 02:46:37 Save the image 00566D.png
 18%|███████▏                                 | 69/392 [00:12<00:56,  5.77it/s]16 02:46:37 Save the image 00567D.png
 18%|███████▎                                 | 70/392 [00:13<00:55,  5.82it/s]16 02:46:37 Save the image 00568D.png
 18%|███████▍                                 | 71/392 [00:13<00:55,  5.83it/s]16 02:46:37 Save the image 00569D.png
 18%|███████▌                                 | 72/392 [00:13<00:55,  5.81it/s]16 02:46:38 Save the image 00570D.png
 19%|███████▋                                 | 73/392 [00:13<00:54,  5.84it/s]16 02:46:38 Save the image 00571D.png
 19%|███████▋                                 | 74/392 [00:13<00:54,  5.87it/s]16 02:46:38 Save the image 00572D.png
 19%|███████▊                                 | 75/392 [00:13<00:54,  5.85it/s]16 02:46:38 Save the image 00573D.png
 19%|███████▉                                 | 76/392 [00:14<00:53,  5.86it/s]16 02:46:38 Save the image 00574D.png
 20%|████████                                 | 77/392 [00:14<00:53,  5.85it/s]16 02:46:38 Save the image 00575D.png
 20%|████████▏                                | 78/392 [00:14<00:53,  5.90it/s]16 02:46:39 Save the image 00576D.png
 20%|████████▎                                | 79/392 [00:14<00:51,  6.07it/s]16 02:46:39 Save the image 00577D.png
 20%|████████▎                                | 80/392 [00:14<00:52,  6.00it/s]16 02:46:39 Save the image 00578D.png
 21%|████████▍                                | 81/392 [00:14<00:51,  5.98it/s]16 02:46:39 Save the image 00579D.png
 21%|████████▌                                | 82/392 [00:15<00:52,  5.96it/s]16 02:46:39 Save the image 00580D.png
 21%|████████▋                                | 83/392 [00:15<00:52,  5.91it/s]16 02:46:39 Save the image 00581D.png
 21%|████████▊                                | 84/392 [00:15<00:52,  5.87it/s]16 02:46:40 Save the image 00582D.png
 22%|████████▉                                | 85/392 [00:15<00:52,  5.86it/s]16 02:46:40 Save the image 00583D.png
 22%|████████▉                                | 86/392 [00:15<00:51,  5.92it/s]16 02:46:40 Save the image 00584D.png
 22%|█████████                                | 87/392 [00:15<00:50,  6.08it/s]16 02:46:40 Save the image 00585D.png
 22%|█████████▏                               | 88/392 [00:16<00:50,  6.00it/s]16 02:46:40 Save the image 00586D.png
 23%|█████████▎                               | 89/392 [00:16<00:50,  6.00it/s]16 02:46:40 Save the image 00587D.png
 23%|█████████▍                               | 90/392 [00:16<00:50,  5.99it/s]16 02:46:41 Save the image 00588D.png
 23%|█████████▌                               | 91/392 [00:16<00:50,  5.92it/s]16 02:46:41 Save the image 00589D.png
 23%|█████████▌                               | 92/392 [00:16<00:50,  5.91it/s]16 02:46:41 Save the image 00590D.png
 24%|█████████▋                               | 93/392 [00:16<00:50,  5.88it/s]16 02:46:41 Save the image 00591D.png
 24%|█████████▊                               | 94/392 [00:17<00:50,  5.93it/s]16 02:46:41 Save the image 00592D.png
 24%|█████████▉                               | 95/392 [00:17<00:48,  6.06it/s]16 02:46:41 Save the image 00593D.png
 24%|██████████                               | 96/392 [00:17<00:49,  5.99it/s]16 02:46:42 Save the image 00594D.png
 25%|██████████▏                              | 97/392 [00:17<00:49,  5.96it/s]16 02:46:42 Save the image 00595D.png
 25%|██████████▎                              | 98/392 [00:17<00:49,  5.95it/s]16 02:46:42 Save the image 00596D.png
 25%|██████████▎                              | 99/392 [00:17<00:49,  5.90it/s]16 02:46:42 Save the image 00597D.png
 26%|██████████▏                             | 100/392 [00:18<00:49,  5.87it/s]16 02:46:42 Save the image 00598D.png
 26%|██████████▎                             | 101/392 [00:18<00:49,  5.87it/s]16 02:46:42 Save the image 00599D.png
 26%|██████████▍                             | 102/392 [00:18<00:48,  5.93it/s]16 02:46:43 Save the image 00600D.png
 26%|██████████▌                             | 103/392 [00:18<00:47,  6.10it/s]16 02:46:43 Save the image 00601D.png
 27%|██████████▌                             | 104/392 [00:18<00:47,  6.01it/s]16 02:46:43 Save the image 00602D.png
 27%|██████████▋                             | 105/392 [00:18<00:47,  5.98it/s]16 02:46:43 Save the image 00603D.png
 27%|██████████▊                             | 106/392 [00:19<00:48,  5.94it/s]16 02:46:43 Save the image 00604D.png
 27%|██████████▉                             | 107/392 [00:19<00:48,  5.89it/s]16 02:46:43 Save the image 00605D.png
 28%|███████████                             | 108/392 [00:19<00:48,  5.87it/s]16 02:46:44 Save the image 00606D.png
 28%|███████████                             | 109/392 [00:19<00:48,  5.88it/s]16 02:46:44 Save the image 00607D.png
 28%|███████████▏                            | 110/392 [00:19<00:48,  5.84it/s]16 02:46:44 Save the image 00608D.png
 28%|███████████▎                            | 111/392 [00:19<00:46,  6.09it/s]16 02:46:44 Save the image 00609D.png
 29%|███████████▍                            | 112/392 [00:20<00:46,  5.98it/s]16 02:46:44 Save the image 00610D.png
 29%|███████████▌                            | 113/392 [00:20<00:46,  5.96it/s]16 02:46:44 Save the image 00611D.png
 29%|███████████▋                            | 114/392 [00:20<00:46,  5.96it/s]16 02:46:45 Save the image 00612D.png
 29%|███████████▋                            | 115/392 [00:20<00:46,  5.91it/s]16 02:46:45 Save the image 00613D.png
 30%|███████████▊                            | 116/392 [00:20<00:46,  5.87it/s]16 02:46:45 Save the image 00614D.png
 30%|███████████▉                            | 117/392 [00:21<00:46,  5.88it/s]16 02:46:45 Save the image 00615D.png
 30%|████████████                            | 118/392 [00:21<00:46,  5.84it/s]16 02:46:45 Save the image 00616D.png
 30%|████████████▏                           | 119/392 [00:21<00:43,  6.21it/s]16 02:46:45 Save the image 00617D.png
 31%|████████████▏                           | 120/392 [00:21<00:44,  6.07it/s]16 02:46:46 Save the image 00618D.png
 31%|████████████▎                           | 121/392 [00:21<00:44,  6.03it/s]16 02:46:46 Save the image 00619D.png
 31%|████████████▍                           | 122/392 [00:21<00:45,  5.96it/s]16 02:46:46 Save the image 00620D.png

 31%|████████████▌                           | 123/392 [00:22<00:45,  5.89it/s]16 02:46:46 Save the image 00621D.png
 32%|████████████▋                           | 124/392 [00:22<00:45,  5.86it/s]16 02:46:46 Save the image 00622D.png
 32%|████████████▊                           | 125/392 [00:22<00:45,  5.85it/s]16 02:46:46 Save the image 00623D.png
 32%|████████████▊                           | 126/392 [00:22<00:45,  5.84it/s]16 02:46:47 Save the image 00624D.png
 32%|████████████▉                           | 127/392 [00:22<00:43,  6.14it/s]16 02:46:47 Save the image 00625D.png
 33%|█████████████                           | 128/392 [00:22<00:43,  6.03it/s]16 02:46:47 Save the image 00626D.png
 33%|█████████████▏                          | 129/392 [00:23<00:43,  6.00it/s]16 02:46:47 Save the image 00627D.png
 33%|█████████████▎                          | 130/392 [00:23<00:43,  5.99it/s]16 02:46:47 Save the image 00628D.png
 33%|█████████████▎                          | 131/392 [00:23<00:43,  5.93it/s]16 02:46:47 Save the image 00629D.png
 34%|█████████████▍                          | 132/392 [00:23<00:44,  5.88it/s]16 02:46:48 Save the image 00630D.png
 34%|█████████████▌                          | 133/392 [00:23<00:44,  5.88it/s]16 02:46:48 Save the image 00631D.png
 34%|█████████████▋                          | 134/392 [00:23<00:43,  5.87it/s]16 02:46:48 Save the image 00632D.png
 34%|█████████████▊                          | 135/392 [00:23<00:41,  6.21it/s]16 02:46:48 Save the image 00633D.png
 35%|█████████████▉                          | 136/392 [00:24<00:42,  6.09it/s]16 02:46:48 Save the image 00634D.png
 35%|█████████████▉                          | 137/392 [00:24<00:42,  6.04it/s]16 02:46:48 Save the image 00635D.png
 35%|██████████████                          | 138/392 [00:24<00:42,  5.99it/s]16 02:46:49 Save the image 00636D.png
 35%|██████████████▏                         | 139/392 [00:24<00:42,  5.93it/s]16 02:46:49 Save the image 00637D.png
 36%|██████████████▎                         | 140/392 [00:24<00:42,  5.91it/s]16 02:46:49 Save the image 00638D.png
 36%|██████████████▍                         | 141/392 [00:25<00:42,  5.86it/s]16 02:46:49 Save the image 00639D.png
 36%|██████████████▍                         | 142/392 [00:25<00:42,  5.84it/s]16 02:46:49 Save the image 00640D.png
 36%|██████████████▌                         | 143/392 [00:25<00:40,  6.17it/s]16 02:46:49 Save the image 00641D.png
 37%|██████████████▋                         | 144/392 [00:25<00:41,  6.04it/s]16 02:46:50 Save the image 00642D.png
 37%|██████████████▊                         | 145/392 [00:25<00:41,  6.01it/s]16 02:46:50 Save the image 00643D.png
 37%|██████████████▉                         | 146/392 [00:25<00:41,  5.98it/s]16 02:46:50 Save the image 00644D.png
 38%|███████████████                         | 147/392 [00:26<00:41,  5.92it/s]16 02:46:50 Save the image 00645D.png
 38%|███████████████                         | 148/392 [00:26<00:41,  5.88it/s]16 02:46:50 Save the image 00646D.png
 38%|███████████████▏                        | 149/392 [00:26<00:41,  5.86it/s]16 02:46:51 Save the image 00647D.png
 38%|███████████████▎                        | 150/392 [00:26<00:41,  5.84it/s]16 02:46:51 Save the image 00648D.png
 39%|███████████████▍                        | 151/392 [00:26<00:38,  6.19it/s]16 02:46:51 Save the image 00649D.png
 39%|███████████████▌                        | 152/392 [00:26<00:39,  6.08it/s]16 02:46:51 Save the image 00650D.png
 39%|███████████████▌                        | 153/392 [00:27<00:39,  6.04it/s]16 02:46:51 Save the image 00651D.png
 39%|███████████████▋                        | 154/392 [00:27<00:39,  6.00it/s]16 02:46:51 Save the image 00652D.png
 40%|███████████████▊                        | 155/392 [00:27<00:39,  5.93it/s]16 02:46:51 Save the image 00653D.png
 40%|███████████████▉                        | 156/392 [00:27<00:39,  5.90it/s]16 02:46:52 Save the image 00654D.png
 40%|████████████████                        | 157/392 [00:27<00:39,  5.90it/s]16 02:46:52 Save the image 00655D.png
 40%|████████████████                        | 158/392 [00:27<00:39,  5.87it/s]16 02:46:52 Save the image 00656D.png
 41%|████████████████▏                       | 159/392 [00:28<00:37,  6.23it/s]16 02:46:52 Save the image 00657D.png
 41%|████████████████▎                       | 160/392 [00:28<00:38,  6.09it/s]16 02:46:52 Save the image 00658D.png
 41%|████████████████▍                       | 161/392 [00:28<00:38,  6.04it/s]16 02:46:52 Save the image 00659D.png
 41%|████████████████▌                       | 162/392 [00:28<00:38,  6.02it/s]16 02:46:53 Save the image 00660D.png
 42%|████████████████▋                       | 163/392 [00:28<00:38,  5.96it/s]16 02:46:53 Save the image 00661D.png
 42%|████████████████▋                       | 164/392 [00:28<00:38,  5.90it/s]16 02:46:53 Save the image 00662D.png
 42%|████████████████▊                       | 165/392 [00:29<00:38,  5.87it/s]16 02:46:53 Save the image 00663D.png
 42%|████████████████▉                       | 166/392 [00:29<00:38,  5.84it/s]16 02:46:53 Save the image 00664D.png
 43%|█████████████████                       | 167/392 [00:29<00:36,  6.16it/s]16 02:46:53 Save the image 00665D.png
 43%|█████████████████▏                      | 168/392 [00:29<00:37,  6.04it/s]16 02:46:54 Save the image 00666D.png
 43%|█████████████████▏                      | 169/392 [00:29<00:37,  6.02it/s]16 02:46:54 Save the image 00667D.png
 43%|█████████████████▎                      | 170/392 [00:29<00:37,  5.98it/s]16 02:46:54 Save the image 00668D.png
 44%|█████████████████▍                      | 171/392 [00:30<00:37,  5.85it/s]16 02:46:54 Save the image 00669D.png
 44%|█████████████████▌                      | 172/392 [00:30<00:37,  5.91it/s]16 02:46:54 Save the image 00670D.png
 44%|█████████████████▋                      | 173/392 [00:30<00:37,  5.88it/s]16 02:46:55 Save the image 00671D.png
 44%|█████████████████▊                      | 174/392 [00:30<00:37,  5.85it/s]16 02:46:55 Save the image 00672D.png
 45%|█████████████████▊                      | 175/392 [00:30<00:34,  6.21it/s]16 02:46:55 Save the image 00673D.png
 45%|█████████████████▉                      | 176/392 [00:30<00:35,  6.08it/s]16 02:46:55 Save the image 00674D.png
 45%|██████████████████                      | 177/392 [00:31<00:35,  6.03it/s]16 02:46:55 Save the image 00675D.png
 45%|██████████████████▏                     | 178/392 [00:31<00:35,  6.01it/s]16 02:46:55 Save the image 00676D.png
 46%|██████████████████▎                     | 179/392 [00:31<00:35,  5.94it/s]16 02:46:56 Save the image 00677D.png
 46%|██████████████████▎                     | 180/392 [00:31<00:35,  5.89it/s]16 02:46:56 Save the image 01377D.png
 46%|██████████████████▍                     | 181/392 [00:31<00:35,  5.91it/s]16 02:46:56 Save the image 01378D.png
 46%|██████████████████▌                     | 182/392 [00:31<00:35,  5.89it/s]16 02:46:56 Save the image 01379D.png
 47%|██████████████████▋                     | 183/392 [00:32<00:33,  6.25it/s]16 02:46:56 Save the image 01380D.png
 47%|██████████████████▊                     | 184/392 [00:32<00:34,  6.10it/s]16 02:46:56 Save the image 01381D.png
 47%|██████████████████▉                     | 185/392 [00:32<00:34,  6.05it/s]16 02:46:56 Save the image 01382D.png
 47%|██████████████████▉                     | 186/392 [00:32<00:34,  6.00it/s]16 02:46:57 Save the image 01383D.png
 48%|███████████████████                     | 187/392 [00:32<00:34,  5.94it/s]16 02:46:57 Save the image 01384D.png

 48%|███████████████████▏                    | 188/392 [00:32<00:34,  5.90it/s]16 02:46:57 Save the image 01385D.png
 48%|███████████████████▎                    | 189/392 [00:33<00:34,  5.89it/s]16 02:46:57 Save the image 01386D.png
 48%|███████████████████▍                    | 190/392 [00:33<00:34,  5.85it/s]16 02:46:57 Save the image 01387D.png
 49%|███████████████████▍                    | 191/392 [00:33<00:32,  6.18it/s]16 02:46:58 Save the image 01388D.png
 49%|███████████████████▌                    | 192/392 [00:33<00:33,  6.06it/s]16 02:46:58 Save the image 01389D.png
 49%|███████████████████▋                    | 193/392 [00:33<00:33,  6.02it/s]16 02:46:58 Save the image 01390D.png
 49%|███████████████████▊                    | 194/392 [00:33<00:33,  5.98it/s]16 02:46:58 Save the image 01391D.png
 50%|███████████████████▉                    | 195/392 [00:34<00:33,  5.93it/s]16 02:46:58 Save the image 01392D.png
 50%|████████████████████                    | 196/392 [00:34<00:33,  5.88it/s]16 02:46:58 Save the image 01393D.png
 50%|████████████████████                    | 197/392 [00:34<00:33,  5.90it/s]16 02:46:59 Save the image 01394D.png
 51%|████████████████████▏                   | 198/392 [00:34<00:33,  5.87it/s]16 02:46:59 Save the image 01395D.png
 51%|████████████████████▎                   | 199/392 [00:34<00:30,  6.23it/s]16 02:46:59 Save the image 01396D.png
 51%|████████████████████▍                   | 200/392 [00:34<00:31,  6.09it/s]16 02:46:59 Save the image 01397D.png
 51%|████████████████████▌                   | 201/392 [00:35<00:31,  5.97it/s]16 02:46:59 Save the image 01398D.png
 52%|████████████████████▌                   | 202/392 [00:35<00:31,  5.94it/s]16 02:46:59 Save the image 01399D.png
 52%|████████████████████▋                   | 203/392 [00:35<00:32,  5.89it/s]16 02:47:00 Save the image 01400D.png
 52%|████████████████████▊                   | 204/392 [00:35<00:31,  5.91it/s]16 02:47:00 Save the image 01401D.png
 52%|████████████████████▉                   | 205/392 [00:35<00:31,  5.88it/s]16 02:47:00 Save the image 01002N.png
 53%|█████████████████████                   | 206/392 [00:35<00:31,  5.87it/s]16 02:47:00 Save the image 01003N.png
 53%|█████████████████████                   | 207/392 [00:36<00:29,  6.20it/s]16 02:47:00 Save the image 01004N.png
 53%|█████████████████████▏                  | 208/392 [00:36<00:30,  6.07it/s]16 02:47:00 Save the image 01005N.png
 53%|█████████████████████▎                  | 209/392 [00:36<00:30,  6.05it/s]16 02:47:01 Save the image 01006N.png
 54%|█████████████████████▍                  | 210/392 [00:36<00:30,  6.03it/s]16 02:47:01 Save the image 01007N.png
 54%|█████████████████████▌                  | 211/392 [00:36<00:30,  5.96it/s]16 02:47:01 Save the image 01008N.png
 54%|█████████████████████▋                  | 212/392 [00:36<00:30,  5.92it/s]16 02:47:01 Save the image 01009N.png
 54%|█████████████████████▋                  | 213/392 [00:37<00:30,  5.94it/s]16 02:47:01 Save the image 01010N.png
 55%|█████████████████████▊                  | 214/392 [00:37<00:30,  5.92it/s]16 02:47:01 Save the image 01011N.png
 55%|█████████████████████▉                  | 215/392 [00:37<00:28,  6.28it/s]16 02:47:01 Save the image 01012N.png
 55%|██████████████████████                  | 216/392 [00:37<00:28,  6.15it/s]16 02:47:02 Save the image 01013N.png
 55%|██████████████████████▏                 | 217/392 [00:37<00:28,  6.11it/s]16 02:47:02 Save the image 01014N.png
 56%|██████████████████████▏                 | 218/392 [00:37<00:28,  6.04it/s]16 02:47:02 Save the image 01015N.png
 56%|██████████████████████▎                 | 219/392 [00:38<00:28,  5.98it/s]16 02:47:02 Save the image 01016N.png
 56%|██████████████████████▍                 | 220/392 [00:38<00:29,  5.93it/s]16 02:47:02 Save the image 01017N.png
 56%|██████████████████████▌                 | 221/392 [00:38<00:28,  5.92it/s]16 02:47:03 Save the image 01018N.png
 57%|██████████████████████▋                 | 222/392 [00:38<00:28,  5.89it/s]16 02:47:03 Save the image 01019N.png
 57%|██████████████████████▊                 | 223/392 [00:38<00:27,  6.24it/s]16 02:47:03 Save the image 01020N.png
 57%|██████████████████████▊                 | 224/392 [00:38<00:27,  6.10it/s]16 02:47:03 Save the image 01021N.png
 57%|██████████████████████▉                 | 225/392 [00:39<00:27,  6.04it/s]16 02:47:03 Save the image 01022N.png
 58%|███████████████████████                 | 226/392 [00:39<00:27,  5.98it/s]16 02:47:03 Save the image 01023N.png
 58%|███████████████████████▏                | 227/392 [00:39<00:27,  5.93it/s]16 02:47:04 Save the image 01024N.png
 58%|███████████████████████▎                | 228/392 [00:39<00:27,  5.91it/s]16 02:47:04 Save the image 01025N.png
 58%|███████████████████████▎                | 229/392 [00:39<00:27,  5.90it/s]16 02:47:04 Save the image 01026N.png
 59%|███████████████████████▍                | 230/392 [00:39<00:27,  5.98it/s]16 02:47:04 Save the image 01027N.png
 59%|███████████████████████▌                | 231/392 [00:40<00:26,  6.17it/s]16 02:47:04 Save the image 01028N.png
 59%|███████████████████████▋                | 232/392 [00:40<00:26,  5.99it/s]16 02:47:04 Save the image 01029N.png
 59%|███████████████████████▊                | 233/392 [00:40<00:26,  5.98it/s]16 02:47:05 Save the image 01030N.png
 60%|███████████████████████▉                | 234/392 [00:40<00:26,  5.97it/s]16 02:47:05 Save the image 01031N.png
 60%|███████████████████████▉                | 235/392 [00:40<00:26,  5.92it/s]16 02:47:05 Save the image 01032N.png
 60%|████████████████████████                | 236/392 [00:40<00:26,  5.86it/s]16 02:47:05 Save the image 01033N.png
 60%|████████████████████████▏               | 237/392 [00:41<00:26,  5.90it/s]16 02:47:05 Save the image 01034N.png
 61%|████████████████████████▎               | 238/392 [00:41<00:26,  5.90it/s]16 02:47:05 Save the image 01035N.png
 61%|████████████████████████▍               | 239/392 [00:41<00:24,  6.19it/s]16 02:47:06 Save the image 01036N.png
 61%|████████████████████████▍               | 240/392 [00:41<00:25,  6.06it/s]16 02:47:06 Save the image 01037N.png
 61%|████████████████████████▌               | 241/392 [00:41<00:25,  6.02it/s]16 02:47:06 Save the image 01038N.png
 62%|████████████████████████▋               | 242/392 [00:41<00:25,  5.98it/s]16 02:47:06 Save the image 01039N.png
 62%|████████████████████████▊               | 243/392 [00:42<00:25,  5.92it/s]16 02:47:06 Save the image 01040N.png
 62%|████████████████████████▉               | 244/392 [00:42<00:25,  5.91it/s]16 02:47:06 Save the image 01041N.png
 62%|█████████████████████████               | 245/392 [00:42<00:24,  5.89it/s]16 02:47:07 Save the image 01042N.png
 63%|█████████████████████████               | 246/392 [00:42<00:24,  5.94it/s]16 02:47:07 Save the image 01043N.png
 63%|█████████████████████████▏              | 247/392 [00:42<00:23,  6.05it/s]16 02:47:07 Save the image 01044N.png
 63%|█████████████████████████▎              | 248/392 [00:42<00:24,  5.97it/s]16 02:47:07 Save the image 01045N.png
 64%|█████████████████████████▍              | 249/392 [00:43<00:23,  5.96it/s]16 02:47:07 Save the image 01046N.png
 64%|█████████████████████████▌              | 250/392 [00:43<00:23,  5.94it/s]16 02:47:07 Save the image 01047N.png
 64%|█████████████████████████▌              | 251/392 [00:43<00:23,  5.90it/s]16 02:47:08 Save the image 01048N.png
 64%|█████████████████████████▋              | 252/392 [00:43<00:23,  5.88it/s]16 02:47:08 Save the image 01049N.png

 65%|█████████████████████████▊              | 253/392 [00:43<00:23,  5.90it/s]16 02:47:08 Save the image 01050N.png
 65%|█████████████████████████▉              | 254/392 [00:43<00:23,  5.95it/s]16 02:47:08 Save the image 01051N.png
 65%|██████████████████████████              | 255/392 [00:44<00:22,  6.09it/s]16 02:47:08 Save the image 01052N.png
 65%|██████████████████████████              | 256/392 [00:44<00:22,  6.00it/s]16 02:47:08 Save the image 01053N.png
 66%|██████████████████████████▏             | 257/392 [00:44<00:22,  5.98it/s]16 02:47:09 Save the image 01054N.png
 66%|██████████████████████████▎             | 258/392 [00:44<00:22,  5.99it/s]16 02:47:09 Save the image 01055N.png
 66%|██████████████████████████▍             | 259/392 [00:44<00:22,  5.92it/s]16 02:47:09 Save the image 01056N.png
 66%|██████████████████████████▌             | 260/392 [00:44<00:22,  5.90it/s]16 02:47:09 Save the image 01057N.png
 67%|██████████████████████████▋             | 261/392 [00:45<00:22,  5.88it/s]16 02:47:09 Save the image 01058N.png
 67%|██████████████████████████▋             | 262/392 [00:45<00:21,  5.94it/s]16 02:47:09 Save the image 01059N.png
 67%|██████████████████████████▊             | 263/392 [00:45<00:21,  6.04it/s]16 02:47:10 Save the image 01060N.png
 67%|██████████████████████████▉             | 264/392 [00:45<00:21,  5.97it/s]16 02:47:10 Save the image 01061N.png
 68%|███████████████████████████             | 265/392 [00:45<00:21,  5.96it/s]16 02:47:10 Save the image 01062N.png
 68%|███████████████████████████▏            | 266/392 [00:45<00:21,  5.92it/s]16 02:47:10 Save the image 01063N.png
 68%|███████████████████████████▏            | 267/392 [00:46<00:21,  5.87it/s]16 02:47:10 Save the image 01064N.png
 68%|███████████████████████████▎            | 268/392 [00:46<00:21,  5.85it/s]16 02:47:10 Save the image 01065N.png
 69%|███████████████████████████▍            | 269/392 [00:46<00:21,  5.84it/s]16 02:47:11 Save the image 01066N.png
 69%|███████████████████████████▌            | 270/392 [00:46<00:20,  5.91it/s]16 02:47:11 Save the image 01067N.png
 69%|███████████████████████████▋            | 271/392 [00:46<00:19,  6.13it/s]16 02:47:11 Save the image 01068N.png
 69%|███████████████████████████▊            | 272/392 [00:46<00:19,  6.03it/s]16 02:47:11 Save the image 01069N.png
 70%|███████████████████████████▊            | 273/392 [00:47<00:19,  6.00it/s]16 02:47:11 Save the image 01070N.png
 70%|███████████████████████████▉            | 274/392 [00:47<00:19,  5.96it/s]16 02:47:11 Save the image 01071N.png
 70%|████████████████████████████            | 275/392 [00:47<00:19,  5.91it/s]16 02:47:12 Save the image 01072N.png
 70%|████████████████████████████▏           | 276/392 [00:47<00:19,  5.88it/s]16 02:47:12 Save the image 01073N.png
 71%|████████████████████████████▎           | 277/392 [00:47<00:19,  5.88it/s]16 02:47:12 Save the image 01074N.png
 71%|████████████████████████████▎           | 278/392 [00:47<00:19,  5.92it/s]16 02:47:12 Save the image 01075N.png
 71%|████████████████████████████▍           | 279/392 [00:48<00:18,  6.11it/s]16 02:47:12 Save the image 01076N.png
 71%|████████████████████████████▌           | 280/392 [00:48<00:18,  6.03it/s]16 02:47:12 Save the image 01077N.png
 72%|████████████████████████████▋           | 281/392 [00:48<00:18,  6.01it/s]16 02:47:13 Save the image 01078N.png
 72%|████████████████████████████▊           | 282/392 [00:48<00:18,  6.01it/s]16 02:47:13 Save the image 01079N.png
 72%|████████████████████████████▉           | 283/392 [00:48<00:18,  5.96it/s]16 02:47:13 Save the image 01080N.png
 72%|████████████████████████████▉           | 284/392 [00:48<00:18,  5.93it/s]16 02:47:13 Save the image 01081N.png
 73%|█████████████████████████████           | 285/392 [00:49<00:18,  5.92it/s]16 02:47:13 Save the image 01082N.png
 73%|█████████████████████████████▏          | 286/392 [00:49<00:17,  5.97it/s]16 02:47:13 Save the image 01083N.png
 73%|█████████████████████████████▎          | 287/392 [00:49<00:17,  6.01it/s]16 02:47:14 Save the image 01084N.png
 73%|█████████████████████████████▍          | 288/392 [00:49<00:17,  5.96it/s]16 02:47:14 Save the image 01085N.png
 74%|█████████████████████████████▍          | 289/392 [00:49<00:17,  5.95it/s]16 02:47:14 Save the image 01086N.png
 74%|█████████████████████████████▌          | 290/392 [00:49<00:17,  5.92it/s]16 02:47:14 Save the image 01087N.png
 74%|█████████████████████████████▋          | 291/392 [00:50<00:17,  5.88it/s]16 02:47:14 Save the image 01088N.png
 74%|█████████████████████████████▊          | 292/392 [00:50<00:17,  5.86it/s]16 02:47:14 Save the image 01089N.png
 75%|█████████████████████████████▉          | 293/392 [00:50<00:16,  5.86it/s]16 02:47:15 Save the image 01090N.png
 75%|██████████████████████████████          | 294/392 [00:50<00:16,  5.93it/s]16 02:47:15 Save the image 01091N.png
 75%|██████████████████████████████          | 295/392 [00:50<00:15,  6.07it/s]16 02:47:15 Save the image 01092N.png
 76%|██████████████████████████████▏         | 296/392 [00:50<00:16,  5.99it/s]16 02:47:15 Save the image 01093N.png
 76%|██████████████████████████████▎         | 297/392 [00:51<00:15,  5.97it/s]16 02:47:15 Save the image 01094N.png
 76%|██████████████████████████████▍         | 298/392 [00:51<00:16,  5.84it/s]16 02:47:15 Save the image 01095N.png
 76%|██████████████████████████████▌         | 299/392 [00:51<00:16,  5.79it/s]16 02:47:16 Save the image 01096N.png
 77%|██████████████████████████████▌         | 300/392 [00:51<00:15,  5.79it/s]16 02:47:16 Save the image 01097N.png
 77%|██████████████████████████████▋         | 301/392 [00:51<00:15,  5.79it/s]16 02:47:16 Save the image 01098N.png
 77%|██████████████████████████████▊         | 302/392 [00:52<00:15,  5.79it/s]16 02:47:16 Save the image 01099N.png
 77%|██████████████████████████████▉         | 303/392 [00:52<00:14,  6.09it/s]16 02:47:16 Save the image 01100N.png
 78%|███████████████████████████████         | 304/392 [00:52<00:14,  5.99it/s]16 02:47:16 Save the image 01101N.png
 78%|███████████████████████████████         | 305/392 [00:52<00:14,  5.94it/s]16 02:47:17 Save the image 01102N.png
 78%|███████████████████████████████▏        | 306/392 [00:52<00:14,  5.92it/s]16 02:47:17 Save the image 01103N.png
 78%|███████████████████████████████▎        | 307/392 [00:52<00:14,  5.91it/s]16 02:47:17 Save the image 01104N.png
 79%|███████████████████████████████▍        | 308/392 [00:53<00:14,  5.90it/s]16 02:47:17 Save the image 01105N.png
 79%|███████████████████████████████▌        | 309/392 [00:53<00:14,  5.92it/s]16 02:47:17 Save the image 01106N.png
 79%|███████████████████████████████▋        | 310/392 [00:53<00:13,  5.89it/s]16 02:47:17 Save the image 01107N.png
 79%|███████████████████████████████▋        | 311/392 [00:53<00:12,  6.25it/s]16 02:47:18 Save the image 01108N.png
 80%|███████████████████████████████▊        | 312/392 [00:53<00:13,  6.11it/s]16 02:47:18 Save the image 01109N.png
 80%|███████████████████████████████▉        | 313/392 [00:53<00:12,  6.08it/s]16 02:47:18 Save the image 01110N.png
 80%|████████████████████████████████        | 314/392 [00:53<00:12,  6.06it/s]16 02:47:18 Save the image 01111N.png
 80%|████████████████████████████████▏       | 315/392 [00:54<00:12,  6.00it/s]16 02:47:18 Save the image 01112N.png
 81%|████████████████████████████████▏       | 316/392 [00:54<00:12,  5.96it/s]16 02:47:18 Save the image 01113N.png
 81%|████████████████████████████████▎       | 317/392 [00:54<00:12,  5.94it/s]16 02:47:19 Save the image 01114N.png

 81%|████████████████████████████████▍       | 318/392 [00:54<00:12,  5.92it/s]16 02:47:19 Save the image 01115N.png
 81%|████████████████████████████████▌       | 319/392 [00:54<00:11,  6.27it/s]16 02:47:19 Save the image 01116N.png
 82%|████████████████████████████████▋       | 320/392 [00:54<00:11,  6.13it/s]16 02:47:19 Save the image 01117N.png
 82%|████████████████████████████████▊       | 321/392 [00:55<00:11,  6.09it/s]16 02:47:19 Save the image 01118N.png
 82%|████████████████████████████████▊       | 322/392 [00:55<00:11,  6.05it/s]16 02:47:19 Save the image 01119N.png
 82%|████████████████████████████████▉       | 323/392 [00:55<00:11,  5.99it/s]16 02:47:20 Save the image 01120N.png
 83%|█████████████████████████████████       | 324/392 [00:55<00:11,  5.96it/s]16 02:47:20 Save the image 01121N.png
 83%|█████████████████████████████████▏      | 325/392 [00:55<00:11,  5.93it/s]16 02:47:20 Save the image 01122N.png
 83%|█████████████████████████████████▎      | 326/392 [00:55<00:11,  5.92it/s]16 02:47:20 Save the image 01123N.png
 83%|█████████████████████████████████▎      | 327/392 [00:56<00:10,  6.00it/s]16 02:47:20 Save the image 01124N.png
 84%|█████████████████████████████████▍      | 328/392 [00:56<00:10,  5.95it/s]16 02:47:20 Save the image 01125N.png
 84%|█████████████████████████████████▌      | 329/392 [00:56<00:10,  5.94it/s]16 02:47:21 Save the image 01126N.png
 84%|█████████████████████████████████▋      | 330/392 [00:56<00:10,  5.93it/s]16 02:47:21 Save the image 01127N.png
 84%|█████████████████████████████████▊      | 331/392 [00:56<00:10,  5.83it/s]16 02:47:21 Save the image 01128N.png
 85%|█████████████████████████████████▉      | 332/392 [00:57<00:10,  5.81it/s]16 02:47:21 Save the image 01129N.png
 85%|█████████████████████████████████▉      | 333/392 [00:57<00:10,  5.74it/s]16 02:47:21 Save the image 01130N.png
 85%|██████████████████████████████████      | 334/392 [00:57<00:10,  5.80it/s]16 02:47:21 Save the image 01131N.png
 85%|██████████████████████████████████▏     | 335/392 [00:57<00:09,  5.76it/s]16 02:47:22 Save the image 01132N.png
 86%|██████████████████████████████████▎     | 336/392 [00:57<00:09,  5.75it/s]16 02:47:22 Save the image 01133N.png
 86%|██████████████████████████████████▍     | 337/392 [00:57<00:09,  5.81it/s]16 02:47:22 Save the image 01134N.png
 86%|██████████████████████████████████▍     | 338/392 [00:58<00:09,  5.83it/s]16 02:47:22 Save the image 01135N.png
 86%|██████████████████████████████████▌     | 339/392 [00:58<00:09,  5.77it/s]16 02:47:22 Save the image 01136N.png
 87%|██████████████████████████████████▋     | 340/392 [00:58<00:09,  5.76it/s]16 02:47:23 Save the image 01137N.png
 87%|██████████████████████████████████▊     | 341/392 [00:58<00:08,  5.78it/s]16 02:47:23 Save the image 01138N.png
 87%|██████████████████████████████████▉     | 342/392 [00:58<00:08,  5.84it/s]16 02:47:23 Save the image 01139N.png
 88%|███████████████████████████████████     | 343/392 [00:58<00:08,  5.90it/s]16 02:47:23 Save the image 01140N.png
 88%|███████████████████████████████████     | 344/392 [00:59<00:08,  5.83it/s]16 02:47:23 Save the image 01141N.png
 88%|███████████████████████████████████▏    | 345/392 [00:59<00:08,  5.87it/s]16 02:47:23 Save the image 01142N.png
 88%|███████████████████████████████████▎    | 346/392 [00:59<00:07,  5.87it/s]16 02:47:24 Save the image 01143N.png
 89%|███████████████████████████████████▍    | 347/392 [00:59<00:07,  5.85it/s]16 02:47:24 Save the image 01144N.png
 89%|███████████████████████████████████▌    | 348/392 [00:59<00:07,  5.86it/s]16 02:47:24 Save the image 01145N.png
 89%|███████████████████████████████████▌    | 349/392 [00:59<00:07,  5.79it/s]16 02:47:24 Save the image 01146N.png
 89%|███████████████████████████████████▋    | 350/392 [01:00<00:07,  5.84it/s]16 02:47:24 Save the image 01147N.png
 90%|███████████████████████████████████▊    | 351/392 [01:00<00:07,  5.85it/s]16 02:47:24 Save the image 01148N.png
 90%|███████████████████████████████████▉    | 352/392 [01:00<00:06,  5.82it/s]16 02:47:25 Save the image 01149N.png
 90%|████████████████████████████████████    | 353/392 [01:00<00:06,  5.79it/s]16 02:47:25 Save the image 01150N.png
 90%|████████████████████████████████████    | 354/392 [01:00<00:06,  5.79it/s]16 02:47:25 Save the image 01151N.png
 91%|████████████████████████████████████▏   | 355/392 [01:00<00:06,  5.78it/s]16 02:47:25 Save the image 01152N.png
 91%|████████████████████████████████████▎   | 356/392 [01:01<00:06,  5.77it/s]16 02:47:25 Save the image 01153N.png
 91%|████████████████████████████████████▍   | 357/392 [01:01<00:06,  5.76it/s]16 02:47:25 Save the image 01154N.png
 91%|████████████████████████████████████▌   | 358/392 [01:01<00:05,  5.78it/s]16 02:47:26 Save the image 01155N.png
 92%|████████████████████████████████████▋   | 359/392 [01:01<00:05,  5.74it/s]16 02:47:26 Save the image 01156N.png
 92%|████████████████████████████████████▋   | 360/392 [01:01<00:05,  5.73it/s]16 02:47:26 Save the image 01157N.png
 92%|████████████████████████████████████▊   | 361/392 [01:02<00:05,  5.74it/s]16 02:47:26 Save the image 01158N.png
 92%|████████████████████████████████████▉   | 362/392 [01:02<00:05,  5.75it/s]16 02:47:26 Save the image 01159N.png
 93%|█████████████████████████████████████   | 363/392 [01:02<00:05,  5.75it/s]16 02:47:27 Save the image 01160N.png
 93%|█████████████████████████████████████▏  | 364/392 [01:02<00:04,  5.66it/s]16 02:47:27 Save the image 01161N.png
 93%|█████████████████████████████████████▏  | 365/392 [01:02<00:04,  5.67it/s]16 02:47:27 Save the image 01162N.png
 93%|█████████████████████████████████████▎  | 366/392 [01:02<00:04,  5.74it/s]16 02:47:27 Save the image 01163N.png
 94%|█████████████████████████████████████▍  | 367/392 [01:03<00:04,  5.85it/s]16 02:47:27 Save the image 01164N.png
 94%|█████████████████████████████████████▌  | 368/392 [01:03<00:04,  5.83it/s]16 02:47:27 Save the image 01165N.png
 94%|█████████████████████████████████████▋  | 369/392 [01:03<00:03,  5.80it/s]16 02:47:28 Save the image 01166N.png
 94%|█████████████████████████████████████▊  | 370/392 [01:03<00:03,  5.80it/s]16 02:47:28 Save the image 01167N.png
 95%|█████████████████████████████████████▊  | 371/392 [01:03<00:03,  5.78it/s]16 02:47:28 Save the image 01168N.png
 95%|█████████████████████████████████████▉  | 372/392 [01:03<00:03,  5.78it/s]16 02:47:28 Save the image 01169N.png
 95%|██████████████████████████████████████  | 373/392 [01:04<00:03,  5.76it/s]16 02:47:28 Save the image 01170N.png
 95%|██████████████████████████████████████▏ | 374/392 [01:04<00:03,  5.80it/s]16 02:47:28 Save the image 01171N.png
 96%|██████████████████████████████████████▎ | 375/392 [01:04<00:02,  5.76it/s]16 02:47:29 Save the image 01172N.png
 96%|██████████████████████████████████████▎ | 376/392 [01:04<00:02,  5.72it/s]16 02:47:29 Save the image 01173N.png
 96%|██████████████████████████████████████▍ | 377/392 [01:04<00:02,  5.75it/s]16 02:47:29 Save the image 01174N.png
 96%|██████████████████████████████████████▌ | 378/392 [01:04<00:02,  5.79it/s]16 02:47:29 Save the image 01175N.png
 97%|██████████████████████████████████████▋ | 379/392 [01:05<00:02,  5.74it/s]16 02:47:29 Save the image 01176N.png
 97%|██████████████████████████████████████▊ | 380/392 [01:05<00:02,  5.77it/s]16 02:47:29 Save the image 01177N.png
 97%|██████████████████████████████████████▉ | 381/392 [01:05<00:01,  5.72it/s]16 02:47:30 Save the image 01178N.png
 97%|██████████████████████████████████████▉ | 382/392 [01:05<00:01,  5.79it/s]16 02:47:30 Save the image 01179N.png

 98%|███████████████████████████████████████ | 383/392 [01:05<00:01,  5.83it/s]16 02:47:30 Save the image 01180N.png
 98%|███████████████████████████████████████▏| 384/392 [01:06<00:01,  5.77it/s]16 02:47:30 Save the image 01181N.png
 98%|███████████████████████████████████████▎| 385/392 [01:06<00:01,  5.79it/s]16 02:47:30 Save the image 01182N.png
 98%|███████████████████████████████████████▍| 386/392 [01:06<00:01,  5.85it/s]16 02:47:30 Save the image 01183N.png
 99%|███████████████████████████████████████▍| 387/392 [01:06<00:00,  5.78it/s]16 02:47:31 Save the image 01184N.png
 99%|███████████████████████████████████████▌| 388/392 [01:06<00:00,  5.78it/s]16 02:47:31 Save the image 01185N.png
 99%|███████████████████████████████████████▋| 389/392 [01:06<00:00,  5.79it/s]16 02:47:31 Save the image 01186N.png
 99%|███████████████████████████████████████▊| 390/392 [01:07<00:00,  5.86it/s]16 02:47:31 Save the image 01187N.png
100%|███████████████████████████████████████▉| 391/392 [01:07<00:00,  5.87it/s]16 02:47:31 Save the image 01188N.png
100%|████████████████████████████████████████| 392/392 [01:07<00:00,  5.82it/s]
1 unlabeled	97.726%
2 car   	87.001%
3 person	71.608%
4 bike  	72.682%
5 curve 	36.603%
6 car_stop	32.581%
7 guardrail	45.387%
8 color_cone	56.540%
9 bump  	48.367%
----------     mean_IoU	60.944%	freq_IoU	95.678%	mean_pixel_acc	70.880%	pixel_acc	97.684%
16 02:47:31 Evaluation Elapsed Time: 67.38s

In [11]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E1")

!python eval.py -e 100 -d 0 --split train -p predictions_E1_train

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:49:04 using devices 0
16 02:49:04 Using E1: SegFormer-B2 without FRM
16 02:49:05 Using MLP Decoder
16 02:49:05 Load Model: /home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth
16 02:49:09 Load model, Time usage:
	IO: 4.073198080062866, initialize parameters: 0.04323744773864746
16 02:49:09 GPU 0 handle 1568 data.
  0%|                                                 | 0/1568 [00:00<?, ?it/s][ WARN:0@8.131] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:49:11 Save the image 00001D.png
  0%|                                         | 1/1568 [00:01<35:06,  1.34s/it]16 02:49:11 Save the image 00001D_flip.png
  0%|                                         | 2/1568 [00:01<17:01,  1.53it/s]16 02:49:11 Save the image 00002D.png
  0%|                                         | 3/1568 [00:01<11:16,  2.31it/s]16 02:49:11 Save the image 00002D_flip.png
  0%|                                         | 4/1568 [00:01<08:35,  3.03it/s]16 02:49:11 Save the image 00055D.png
  0%|▏                                        | 5/1568 [00:02<07:05,  3.67it/s]16 02:49:11 Save the image 00055D_flip.png
  0%|▏                                        | 6/1568 [00:02<06:08,  4.24it/s]16 02:49:12 Save the image 00056D.png
  0%|▏                                        | 7/1568 [00:02<05:28,  4.76it/s]16 02:49:12 Save the image 00056D_flip.png
  1%|▏                                        | 8/1568 [00:02<05:09,  5.05it/s]16 02:49:12 Save the image 00057D.png
  1%|▏                                        | 9/1568 [00:02<04:54,  5.30it/s]16 02:49:12 Save the image 00057D_flip.png
  1%|▎                                       | 10/1568 [00:02<04:44,  5.48it/s]16 02:49:12 Save the image 00058D.png
  1%|▎                                       | 11/1568 [00:03<04:40,  5.56it/s]16 02:49:12 Save the image 00058D_flip.png
  1%|▎                                       | 12/1568 [00:03<04:35,  5.64it/s]16 02:49:13 Save the image 00081D.png
  1%|▎                                       | 13/1568 [00:03<04:32,  5.70it/s]16 02:49:13 Save the image 00081D_flip.png
  1%|▎                                       | 14/1568 [00:03<04:30,  5.74it/s]16 02:49:13 Save the image 00082D.png
  1%|▍                                       | 15/1568 [00:03<04:11,  6.16it/s]16 02:49:13 Save the image 00082D_flip.png
  1%|▍                                       | 16/1568 [00:03<04:15,  6.08it/s]16 02:49:13 Save the image 00083D.png
  1%|▍                                       | 17/1568 [00:04<04:16,  6.04it/s]16 02:49:13 Save the image 00083D_flip.png
  1%|▍                                       | 18/1568 [00:04<04:16,  6.04it/s]16 02:49:14 Save the image 00084D.png
  1%|▍                                       | 19/1568 [00:04<04:19,  5.97it/s]16 02:49:14 Save the image 00084D_flip.png
  1%|▌                                       | 20/1568 [00:04<04:20,  5.95it/s]16 02:49:14 Save the image 00085D.png
  1%|▌                                       | 21/1568 [00:04<04:21,  5.91it/s]16 02:49:14 Save the image 00085D_flip.png
  1%|▌                                       | 22/1568 [00:04<04:22,  5.89it/s]16 02:49:14 Save the image 00086D.png
  1%|▌                                       | 23/1568 [00:05<04:08,  6.21it/s]16 02:49:14 Save the image 00086D_flip.png
  2%|▌                                       | 24/1568 [00:05<04:13,  6.10it/s]16 02:49:15 Save the image 00087D.png
  2%|▋                                       | 25/1568 [00:05<04:15,  6.05it/s]16 02:49:15 Save the image 00087D_flip.png
  2%|▋                                       | 26/1568 [00:05<04:16,  6.01it/s]16 02:49:15 Save the image 00088D.png
  2%|▋                                       | 27/1568 [00:05<04:20,  5.91it/s]16 02:49:15 Save the image 00088D_flip.png
  2%|▋                                       | 28/1568 [00:05<04:21,  5.90it/s]16 02:49:15 Save the image 00091D.png
  2%|▋                                       | 29/1568 [00:06<04:20,  5.90it/s]16 02:49:15 Save the image 00091D_flip.png
  2%|▊                                       | 30/1568 [00:06<04:19,  5.94it/s]16 02:49:16 Save the image 00092D.png
  2%|▊                                       | 31/1568 [00:06<04:18,  5.95it/s]16 02:49:16 Save the image 00092D_flip.png
  2%|▊                                       | 32/1568 [00:06<04:20,  5.91it/s]16 02:49:16 Save the image 00093D.png
  2%|▊                                       | 33/1568 [00:06<04:18,  5.93it/s]16 02:49:16 Save the image 00093D_flip.png
  2%|▊                                       | 34/1568 [00:06<04:17,  5.95it/s]16 02:49:16 Save the image 00094D.png
  2%|▉                                       | 35/1568 [00:07<04:20,  5.89it/s]16 02:49:16 Save the image 00094D_flip.png
  2%|▉                                       | 36/1568 [00:07<04:20,  5.87it/s]16 02:49:17 Save the image 00095D.png
  2%|▉                                       | 37/1568 [00:07<04:21,  5.86it/s]16 02:49:17 Save the image 00095D_flip.png
  2%|▉                                       | 38/1568 [00:07<04:17,  5.93it/s]16 02:49:17 Save the image 00096D.png
  2%|▉                                       | 39/1568 [00:07<04:09,  6.14it/s]16 02:49:17 Save the image 00096D_flip.png
  3%|█                                       | 40/1568 [00:07<04:12,  6.05it/s]16 02:49:17 Save the image 00097D.png
  3%|█                                       | 41/1568 [00:08<04:13,  6.01it/s]16 02:49:17 Save the image 00097D_flip.png
  3%|█                                       | 42/1568 [00:08<04:14,  6.00it/s]16 02:49:18 Save the image 00098D.png
  3%|█                                       | 43/1568 [00:08<04:18,  5.91it/s]16 02:49:18 Save the image 00098D_flip.png
  3%|█                                       | 44/1568 [00:08<04:20,  5.86it/s]16 02:49:18 Save the image 00099D.png
  3%|█▏                                      | 45/1568 [00:08<04:22,  5.80it/s]16 02:49:18 Save the image 00099D_flip.png
  3%|█▏                                      | 46/1568 [00:08<04:19,  5.86it/s]16 02:49:18 Save the image 00100D.png
  3%|█▏                                      | 47/1568 [00:09<04:14,  5.99it/s]16 02:49:19 Save the image 00100D_flip.png
  3%|█▏                                      | 48/1568 [00:09<04:17,  5.90it/s]16 02:49:19 Save the image 00101D.png
  3%|█▎                                      | 49/1568 [00:09<04:17,  5.90it/s]16 02:49:19 Save the image 00101D_flip.png
  3%|█▎                                      | 50/1568 [00:09<04:17,  5.89it/s]16 02:49:19 Save the image 00102D.png
  3%|█▎                                      | 51/1568 [00:09<04:19,  5.84it/s]16 02:49:19 Save the image 00102D_flip.png
  3%|█▎                                      | 52/1568 [00:09<04:22,  5.78it/s]16 02:49:19 Save the image 00103D.png
  3%|█▎                                      | 53/1568 [00:10<04:20,  5.81it/s]16 02:49:20 Save the image 00103D_flip.png
  3%|█▍                                      | 54/1568 [00:10<04:19,  5.84it/s]16 02:49:20 Save the image 00104D.png
  4%|█▍                                      | 55/1568 [00:10<04:17,  5.88it/s]16 02:49:20 Save the image 00104D_flip.png
  4%|█▍                                      | 56/1568 [00:10<04:21,  5.79it/s]16 02:49:20 Save the image 00105D.png

  4%|█▍                                      | 57/1568 [00:10<04:20,  5.81it/s]16 02:49:20 Save the image 00105D_flip.png
  4%|█▍                                      | 58/1568 [00:10<04:18,  5.84it/s]16 02:49:20 Save the image 00106D.png
  4%|█▌                                      | 59/1568 [00:11<04:21,  5.77it/s]16 02:49:21 Save the image 00106D_flip.png
  4%|█▌                                      | 60/1568 [00:11<04:21,  5.76it/s]16 02:49:21 Save the image 00107D.png
  4%|█▌                                      | 61/1568 [00:11<04:20,  5.80it/s]16 02:49:21 Save the image 00107D_flip.png
  4%|█▌                                      | 62/1568 [00:11<04:16,  5.88it/s]16 02:49:21 Save the image 00108D.png
  4%|█▌                                      | 63/1568 [00:11<04:11,  5.98it/s]16 02:49:21 Save the image 00108D_flip.png
  4%|█▋                                      | 64/1568 [00:11<04:13,  5.93it/s]16 02:49:21 Save the image 00109D.png
  4%|█▋                                      | 65/1568 [00:12<04:13,  5.93it/s]16 02:49:22 Save the image 00109D_flip.png
  4%|█▋                                      | 66/1568 [00:12<04:16,  5.86it/s]16 02:49:22 Save the image 00110D.png
  4%|█▋                                      | 67/1568 [00:12<04:22,  5.71it/s]16 02:49:22 Save the image 00110D_flip.png
  4%|█▋                                      | 68/1568 [00:12<04:21,  5.73it/s]16 02:49:22 Save the image 00111D.png
  4%|█▊                                      | 69/1568 [00:12<04:20,  5.75it/s]16 02:49:22 Save the image 00111D_flip.png
  4%|█▊                                      | 70/1568 [00:13<04:19,  5.76it/s]16 02:49:22 Save the image 00112D.png
  5%|█▊                                      | 71/1568 [00:13<04:03,  6.15it/s]16 02:49:23 Save the image 00112D_flip.png
  5%|█▊                                      | 72/1568 [00:13<04:10,  5.98it/s]16 02:49:23 Save the image 00113D.png
  5%|█▊                                      | 73/1568 [00:13<04:11,  5.95it/s]16 02:49:23 Save the image 00113D_flip.png
  5%|█▉                                      | 74/1568 [00:13<04:12,  5.93it/s]16 02:49:23 Save the image 00114D.png
  5%|█▉                                      | 75/1568 [00:13<04:16,  5.82it/s]16 02:49:23 Save the image 00114D_flip.png
  5%|█▉                                      | 76/1568 [00:14<04:16,  5.81it/s]16 02:49:23 Save the image 00115D.png
  5%|█▉                                      | 77/1568 [00:14<04:14,  5.86it/s]16 02:49:24 Save the image 00115D_flip.png
  5%|█▉                                      | 78/1568 [00:14<04:15,  5.84it/s]16 02:49:24 Save the image 00116D.png
  5%|██                                      | 79/1568 [00:14<04:00,  6.19it/s]16 02:49:24 Save the image 00116D_flip.png
  5%|██                                      | 80/1568 [00:14<04:05,  6.07it/s]16 02:49:24 Save the image 00117D.png
  5%|██                                      | 81/1568 [00:14<04:06,  6.04it/s]16 02:49:24 Save the image 00117D_flip.png
  5%|██                                      | 82/1568 [00:15<04:07,  6.01it/s]16 02:49:24 Save the image 00118D.png
  5%|██                                      | 83/1568 [00:15<04:09,  5.95it/s]16 02:49:25 Save the image 00118D_flip.png
  5%|██▏                                     | 84/1568 [00:15<04:11,  5.91it/s]16 02:49:25 Save the image 00119D.png
  5%|██▏                                     | 85/1568 [00:15<04:11,  5.90it/s]16 02:49:25 Save the image 00119D_flip.png
  5%|██▏                                     | 86/1568 [00:15<04:12,  5.88it/s]16 02:49:25 Save the image 00120D.png
  6%|██▏                                     | 87/1568 [00:15<03:57,  6.25it/s]16 02:49:25 Save the image 00120D_flip.png
  6%|██▏                                     | 88/1568 [00:16<04:03,  6.08it/s]16 02:49:25 Save the image 00121D.png
  6%|██▎                                     | 89/1568 [00:16<04:05,  6.03it/s]16 02:49:26 Save the image 00121D_flip.png
  6%|██▎                                     | 90/1568 [00:16<04:07,  5.98it/s]16 02:49:26 Save the image 00122D.png
  6%|██▎                                     | 91/1568 [00:16<04:11,  5.88it/s]16 02:49:26 Save the image 00122D_flip.png
  6%|██▎                                     | 92/1568 [00:16<04:16,  5.76it/s]16 02:49:26 Save the image 00123D.png
  6%|██▎                                     | 93/1568 [00:16<04:19,  5.68it/s]16 02:49:26 Save the image 00123D_flip.png
  6%|██▍                                     | 94/1568 [00:17<04:18,  5.70it/s]16 02:49:26 Save the image 00124D.png
  6%|██▍                                     | 95/1568 [00:17<04:10,  5.87it/s]16 02:49:27 Save the image 00124D_flip.png
  6%|██▍                                     | 96/1568 [00:17<04:12,  5.82it/s]16 02:49:27 Save the image 00125D.png
  6%|██▍                                     | 97/1568 [00:17<04:10,  5.86it/s]16 02:49:27 Save the image 00125D_flip.png
  6%|██▌                                     | 98/1568 [00:17<04:11,  5.85it/s]16 02:49:27 Save the image 00126D.png
  6%|██▌                                     | 99/1568 [00:17<04:13,  5.81it/s]16 02:49:27 Save the image 00126D_flip.png
  6%|██▍                                    | 100/1568 [00:18<04:11,  5.84it/s]16 02:49:28 Save the image 00127D.png
  6%|██▌                                    | 101/1568 [00:18<04:12,  5.80it/s]16 02:49:28 Save the image 00127D_flip.png
  7%|██▌                                    | 102/1568 [00:18<04:13,  5.78it/s]16 02:49:28 Save the image 00128D.png
  7%|██▌                                    | 103/1568 [00:18<03:58,  6.14it/s]16 02:49:28 Save the image 00128D_flip.png
  7%|██▌                                    | 104/1568 [00:18<04:04,  5.99it/s]16 02:49:28 Save the image 00129D.png
  7%|██▌                                    | 105/1568 [00:18<04:05,  5.97it/s]16 02:49:28 Save the image 00129D_flip.png
  7%|██▋                                    | 106/1568 [00:19<04:07,  5.92it/s]16 02:49:29 Save the image 00130D.png
  7%|██▋                                    | 107/1568 [00:19<04:09,  5.85it/s]16 02:49:29 Save the image 00130D_flip.png
  7%|██▋                                    | 108/1568 [00:19<04:09,  5.84it/s]16 02:49:29 Save the image 00131D.png
  7%|██▋                                    | 109/1568 [00:19<04:11,  5.80it/s]16 02:49:29 Save the image 00131D_flip.png
  7%|██▋                                    | 110/1568 [00:19<04:12,  5.78it/s]16 02:49:29 Save the image 00132D.png
  7%|██▊                                    | 111/1568 [00:19<03:56,  6.15it/s]16 02:49:29 Save the image 00132D_flip.png
  7%|██▊                                    | 112/1568 [00:20<04:00,  6.04it/s]16 02:49:30 Save the image 00133D.png
  7%|██▊                                    | 113/1568 [00:20<04:01,  6.02it/s]16 02:49:30 Save the image 00133D_flip.png
  7%|██▊                                    | 114/1568 [00:20<04:04,  5.95it/s]16 02:49:30 Save the image 00134D.png
  7%|██▊                                    | 115/1568 [00:20<04:05,  5.92it/s]16 02:49:30 Save the image 00134D_flip.png
  7%|██▉                                    | 116/1568 [00:20<04:06,  5.89it/s]16 02:49:30 Save the image 00135D.png
  7%|██▉                                    | 117/1568 [00:20<04:06,  5.90it/s]16 02:49:30 Save the image 00135D_flip.png
  8%|██▉                                    | 118/1568 [00:21<04:06,  5.87it/s]16 02:49:31 Save the image 00136D.png
  8%|██▉                                    | 119/1568 [00:21<03:52,  6.22it/s]16 02:49:31 Save the image 00136D_flip.png
  8%|██▉                                    | 120/1568 [00:21<03:57,  6.09it/s]16 02:49:31 Save the image 00137D.png

  8%|███                                    | 121/1568 [00:21<03:59,  6.05it/s]16 02:49:31 Save the image 00137D_flip.png
  8%|███                                    | 122/1568 [00:21<04:00,  6.01it/s]16 02:49:31 Save the image 00138D.png
  8%|███                                    | 123/1568 [00:21<04:04,  5.91it/s]16 02:49:31 Save the image 00138D_flip.png
  8%|███                                    | 124/1568 [00:22<04:06,  5.86it/s]16 02:49:32 Save the image 00139D.png
  8%|███                                    | 125/1568 [00:22<04:05,  5.88it/s]16 02:49:32 Save the image 00139D_flip.png
  8%|███▏                                   | 126/1568 [00:22<04:06,  5.86it/s]16 02:49:32 Save the image 00140D.png
  8%|███▏                                   | 127/1568 [00:22<03:52,  6.20it/s]16 02:49:32 Save the image 00140D_flip.png
  8%|███▏                                   | 128/1568 [00:22<03:57,  6.07it/s]16 02:49:32 Save the image 00141D.png
  8%|███▏                                   | 129/1568 [00:22<03:58,  6.03it/s]16 02:49:32 Save the image 00141D_flip.png
  8%|███▏                                   | 130/1568 [00:23<03:59,  5.99it/s]16 02:49:33 Save the image 00142D.png
  8%|███▎                                   | 131/1568 [00:23<04:03,  5.91it/s]16 02:49:33 Save the image 00142D_flip.png
  8%|███▎                                   | 132/1568 [00:23<04:04,  5.88it/s]16 02:49:33 Save the image 00143D.png
  8%|███▎                                   | 133/1568 [00:23<04:04,  5.88it/s]16 02:49:33 Save the image 00143D_flip.png
  9%|███▎                                   | 134/1568 [00:23<04:05,  5.85it/s]16 02:49:33 Save the image 00144D.png
  9%|███▎                                   | 135/1568 [00:23<03:50,  6.21it/s]16 02:49:33 Save the image 00144D_flip.png
  9%|███▍                                   | 136/1568 [00:24<03:56,  6.06it/s]16 02:49:34 Save the image 00145D.png
  9%|███▍                                   | 137/1568 [00:24<03:57,  6.03it/s]16 02:49:34 Save the image 00145D_flip.png
  9%|███▍                                   | 138/1568 [00:24<03:59,  5.98it/s]16 02:49:34 Save the image 00146D.png
  9%|███▍                                   | 139/1568 [00:24<04:00,  5.93it/s]16 02:49:34 Save the image 00146D_flip.png
  9%|███▍                                   | 140/1568 [00:24<04:02,  5.88it/s]16 02:49:34 Save the image 00147D.png
  9%|███▌                                   | 141/1568 [00:24<04:04,  5.84it/s]16 02:49:34 Save the image 00147D_flip.png
  9%|███▌                                   | 142/1568 [00:25<04:05,  5.81it/s]16 02:49:35 Save the image 00148D.png
  9%|███▌                                   | 143/1568 [00:25<03:49,  6.20it/s]16 02:49:35 Save the image 00148D_flip.png
  9%|███▌                                   | 144/1568 [00:25<03:54,  6.08it/s]16 02:49:35 Save the image 00149D.png
  9%|███▌                                   | 145/1568 [00:25<03:55,  6.04it/s]16 02:49:35 Save the image 00149D_flip.png
  9%|███▋                                   | 146/1568 [00:25<03:56,  6.00it/s]16 02:49:35 Save the image 00150D.png
  9%|███▋                                   | 147/1568 [00:25<03:59,  5.95it/s]16 02:49:35 Save the image 00150D_flip.png
  9%|███▋                                   | 148/1568 [00:26<04:00,  5.90it/s]16 02:49:36 Save the image 00151D.png
 10%|███▋                                   | 149/1568 [00:26<04:01,  5.87it/s]16 02:49:36 Save the image 00151D_flip.png
 10%|███▋                                   | 150/1568 [00:26<04:02,  5.85it/s]16 02:49:36 Save the image 00152D.png
 10%|███▊                                   | 151/1568 [00:26<03:47,  6.22it/s]16 02:49:36 Save the image 00152D_flip.png
 10%|███▊                                   | 152/1568 [00:26<03:52,  6.09it/s]16 02:49:36 Save the image 00153D.png
 10%|███▊                                   | 153/1568 [00:26<03:53,  6.05it/s]16 02:49:36 Save the image 00153D_flip.png
 10%|███▊                                   | 154/1568 [00:27<03:56,  5.99it/s]16 02:49:37 Save the image 00154D.png
 10%|███▊                                   | 155/1568 [00:27<03:59,  5.91it/s]16 02:49:37 Save the image 00154D_flip.png
 10%|███▉                                   | 156/1568 [00:27<04:00,  5.88it/s]16 02:49:37 Save the image 00155D.png
 10%|███▉                                   | 157/1568 [00:27<04:00,  5.87it/s]16 02:49:37 Save the image 00155D_flip.png
 10%|███▉                                   | 158/1568 [00:27<04:03,  5.80it/s]16 02:49:37 Save the image 00156D.png
 10%|███▉                                   | 159/1568 [00:27<03:49,  6.13it/s]16 02:49:37 Save the image 00156D_flip.png
 10%|███▉                                   | 160/1568 [00:28<03:53,  6.04it/s]16 02:49:38 Save the image 00157D.png
 10%|████                                   | 161/1568 [00:28<03:55,  5.98it/s]16 02:49:38 Save the image 00157D_flip.png
 10%|████                                   | 162/1568 [00:28<03:56,  5.95it/s]16 02:49:38 Save the image 00158D.png
 10%|████                                   | 163/1568 [00:28<03:57,  5.91it/s]16 02:49:38 Save the image 00158D_flip.png
 10%|████                                   | 164/1568 [00:28<03:55,  5.96it/s]16 02:49:38 Save the image 00159D.png
 11%|████                                   | 165/1568 [00:28<03:55,  5.95it/s]16 02:49:38 Save the image 00159D_flip.png
 11%|████▏                                  | 166/1568 [00:29<03:57,  5.91it/s]16 02:49:39 Save the image 00160D.png
 11%|████▏                                  | 167/1568 [00:29<03:43,  6.26it/s]16 02:49:39 Save the image 00160D_flip.png
 11%|████▏                                  | 168/1568 [00:29<03:48,  6.11it/s]16 02:49:39 Save the image 00161D.png
 11%|████▏                                  | 169/1568 [00:29<03:50,  6.07it/s]16 02:49:39 Save the image 00161D_flip.png
 11%|████▏                                  | 170/1568 [00:29<03:51,  6.03it/s]16 02:49:39 Save the image 00162D.png
 11%|████▎                                  | 171/1568 [00:29<03:54,  5.96it/s]16 02:49:39 Save the image 00162D_flip.png
 11%|████▎                                  | 172/1568 [00:30<03:54,  5.96it/s]16 02:49:40 Save the image 00163D.png
 11%|████▎                                  | 173/1568 [00:30<03:55,  5.93it/s]16 02:49:40 Save the image 00163D_flip.png
 11%|████▎                                  | 174/1568 [00:30<03:55,  5.92it/s]16 02:49:40 Save the image 00164D.png
 11%|████▎                                  | 175/1568 [00:30<03:41,  6.29it/s]16 02:49:40 Save the image 00164D_flip.png
 11%|████▍                                  | 176/1568 [00:30<03:46,  6.14it/s]16 02:49:40 Save the image 00165D.png
 11%|████▍                                  | 177/1568 [00:30<03:48,  6.08it/s]16 02:49:40 Save the image 00165D_flip.png
 11%|████▍                                  | 178/1568 [00:31<03:50,  6.04it/s]16 02:49:41 Save the image 00166D.png
 11%|████▍                                  | 179/1568 [00:31<03:52,  5.97it/s]16 02:49:41 Save the image 00166D_flip.png
 11%|████▍                                  | 180/1568 [00:31<03:54,  5.91it/s]16 02:49:41 Save the image 00167D.png
 12%|████▌                                  | 181/1568 [00:31<03:54,  5.92it/s]16 02:49:41 Save the image 00167D_flip.png
 12%|████▌                                  | 182/1568 [00:31<03:55,  5.89it/s]16 02:49:41 Save the image 00168D.png
 12%|████▌                                  | 183/1568 [00:31<03:42,  6.24it/s]16 02:49:41 Save the image 00168D_flip.png
 12%|████▌                                  | 184/1568 [00:32<03:47,  6.10it/s]16 02:49:42 Save the image 00169D.png

 12%|████▌                                  | 185/1568 [00:32<03:48,  6.06it/s]16 02:49:42 Save the image 00169D_flip.png
 12%|████▋                                  | 186/1568 [00:32<03:49,  6.03it/s]16 02:49:42 Save the image 00170D.png
 12%|████▋                                  | 187/1568 [00:32<03:51,  5.96it/s]16 02:49:42 Save the image 00170D_flip.png
 12%|████▋                                  | 188/1568 [00:32<03:52,  5.94it/s]16 02:49:42 Save the image 00171D.png
 12%|████▋                                  | 189/1568 [00:32<03:53,  5.91it/s]16 02:49:42 Save the image 00171D_flip.png
 12%|████▋                                  | 190/1568 [00:33<03:54,  5.87it/s]16 02:49:43 Save the image 00172D.png
 12%|████▊                                  | 191/1568 [00:33<03:42,  6.20it/s]16 02:49:43 Save the image 00172D_flip.png
 12%|████▊                                  | 192/1568 [00:33<03:46,  6.08it/s]16 02:49:43 Save the image 00173D.png
 12%|████▊                                  | 193/1568 [00:33<03:47,  6.04it/s]16 02:49:43 Save the image 00173D_flip.png
 12%|████▊                                  | 194/1568 [00:33<03:48,  6.02it/s]16 02:49:43 Save the image 00174D.png
 12%|████▊                                  | 195/1568 [00:33<03:50,  5.95it/s]16 02:49:43 Save the image 00174D_flip.png
 12%|████▉                                  | 196/1568 [00:34<03:50,  5.95it/s]16 02:49:44 Save the image 00175D.png
 13%|████▉                                  | 197/1568 [00:34<03:50,  5.95it/s]16 02:49:44 Save the image 00175D_flip.png
 13%|████▉                                  | 198/1568 [00:34<03:51,  5.92it/s]16 02:49:44 Save the image 00176D.png
 13%|████▉                                  | 199/1568 [00:34<03:39,  6.25it/s]16 02:49:44 Save the image 00176D_flip.png
 13%|████▉                                  | 200/1568 [00:34<03:44,  6.11it/s]16 02:49:44 Save the image 00177D.png
 13%|████▉                                  | 201/1568 [00:34<03:45,  6.06it/s]16 02:49:44 Save the image 00177D_flip.png
 13%|█████                                  | 202/1568 [00:35<03:46,  6.03it/s]16 02:49:45 Save the image 00178D.png
 13%|█████                                  | 203/1568 [00:35<03:49,  5.95it/s]16 02:49:45 Save the image 00178D_flip.png
 13%|█████                                  | 204/1568 [00:35<03:49,  5.93it/s]16 02:49:45 Save the image 00179D.png
 13%|█████                                  | 205/1568 [00:35<03:51,  5.90it/s]16 02:49:45 Save the image 00179D_flip.png
 13%|█████                                  | 206/1568 [00:35<03:51,  5.89it/s]16 02:49:45 Save the image 00180D.png
 13%|█████▏                                 | 207/1568 [00:35<03:37,  6.27it/s]16 02:49:45 Save the image 00180D_flip.png
 13%|█████▏                                 | 208/1568 [00:36<03:42,  6.12it/s]16 02:49:46 Save the image 00181D.png
 13%|█████▏                                 | 209/1568 [00:36<03:43,  6.07it/s]16 02:49:46 Save the image 00181D_flip.png
 13%|█████▏                                 | 210/1568 [00:36<03:45,  6.03it/s]16 02:49:46 Save the image 00182D.png
 13%|█████▏                                 | 211/1568 [00:36<03:47,  5.97it/s]16 02:49:46 Save the image 00182D_flip.png
 14%|█████▎                                 | 212/1568 [00:36<03:49,  5.91it/s]16 02:49:46 Save the image 00183D.png
 14%|█████▎                                 | 213/1568 [00:36<03:50,  5.88it/s]16 02:49:46 Save the image 00183D_flip.png
 14%|█████▎                                 | 214/1568 [00:37<03:51,  5.86it/s]16 02:49:47 Save the image 00184D.png
 14%|█████▎                                 | 215/1568 [00:37<03:36,  6.24it/s]16 02:49:47 Save the image 00184D_flip.png
 14%|█████▎                                 | 216/1568 [00:37<03:41,  6.10it/s]16 02:49:47 Save the image 00185D.png
 14%|█████▍                                 | 217/1568 [00:37<03:42,  6.06it/s]16 02:49:47 Save the image 00185D_flip.png
 14%|█████▍                                 | 218/1568 [00:37<03:44,  6.02it/s]16 02:49:47 Save the image 00186D.png
 14%|█████▍                                 | 219/1568 [00:37<03:46,  5.95it/s]16 02:49:47 Save the image 00186D_flip.png
 14%|█████▍                                 | 220/1568 [00:38<03:47,  5.92it/s]16 02:49:48 Save the image 00187D.png
 14%|█████▍                                 | 221/1568 [00:38<03:47,  5.92it/s]16 02:49:48 Save the image 00187D_flip.png
 14%|█████▌                                 | 222/1568 [00:38<03:48,  5.88it/s]16 02:49:48 Save the image 00188D.png
 14%|█████▌                                 | 223/1568 [00:38<03:35,  6.24it/s]16 02:49:48 Save the image 00188D_flip.png
 14%|█████▌                                 | 224/1568 [00:38<03:41,  6.07it/s]16 02:49:48 Save the image 00189D.png
 14%|█████▌                                 | 225/1568 [00:38<03:42,  6.04it/s]16 02:49:48 Save the image 00189D_flip.png
 14%|█████▌                                 | 226/1568 [00:39<03:44,  5.98it/s]16 02:49:49 Save the image 00190D.png
 14%|█████▋                                 | 227/1568 [00:39<03:48,  5.88it/s]16 02:49:49 Save the image 00190D_flip.png
 15%|█████▋                                 | 228/1568 [00:39<03:49,  5.85it/s]16 02:49:49 Save the image 00191D.png
 15%|█████▋                                 | 229/1568 [00:39<03:48,  5.87it/s]16 02:49:49 Save the image 00191D_flip.png
 15%|█████▋                                 | 230/1568 [00:39<03:48,  5.85it/s]16 02:49:49 Save the image 00192D.png
 15%|█████▋                                 | 231/1568 [00:39<03:36,  6.18it/s]16 02:49:49 Save the image 00192D_flip.png
 15%|█████▊                                 | 232/1568 [00:40<03:40,  6.06it/s]16 02:49:50 Save the image 00193D.png
 15%|█████▊                                 | 233/1568 [00:40<03:41,  6.04it/s]16 02:49:50 Save the image 00193D_flip.png
 15%|█████▊                                 | 234/1568 [00:40<03:43,  5.97it/s]16 02:49:50 Save the image 00194D.png
 15%|█████▊                                 | 235/1568 [00:40<03:47,  5.87it/s]16 02:49:50 Save the image 00194D_flip.png
 15%|█████▊                                 | 236/1568 [00:40<03:49,  5.80it/s]16 02:49:50 Save the image 00195D.png
 15%|█████▉                                 | 237/1568 [00:40<03:48,  5.83it/s]16 02:49:50 Save the image 00195D_flip.png
 15%|█████▉                                 | 238/1568 [00:41<03:49,  5.81it/s]16 02:49:51 Save the image 00196D.png
 15%|█████▉                                 | 239/1568 [00:41<03:37,  6.10it/s]16 02:49:51 Save the image 00196D_flip.png
 15%|█████▉                                 | 240/1568 [00:41<03:44,  5.92it/s]16 02:49:51 Save the image 00197D.png
 15%|█████▉                                 | 241/1568 [00:41<03:45,  5.89it/s]16 02:49:51 Save the image 00197D_flip.png
 15%|██████                                 | 242/1568 [00:41<03:46,  5.85it/s]16 02:49:51 Save the image 00198D.png
 15%|██████                                 | 243/1568 [00:41<03:48,  5.80it/s]16 02:49:51 Save the image 00198D_flip.png
 16%|██████                                 | 244/1568 [00:42<03:52,  5.70it/s]16 02:49:52 Save the image 00199D.png
 16%|██████                                 | 245/1568 [00:42<03:50,  5.75it/s]16 02:49:52 Save the image 00199D_flip.png
 16%|██████                                 | 246/1568 [00:42<03:49,  5.76it/s]16 02:49:52 Save the image 00200D.png
 16%|██████▏                                | 247/1568 [00:42<03:36,  6.10it/s]16 02:49:52 Save the image 00200D_flip.png
 16%|██████▏                                | 248/1568 [00:42<03:39,  6.00it/s]16 02:49:52 Save the image 00201D.png

 16%|██████▏                                | 249/1568 [00:43<03:40,  5.99it/s]16 02:49:52 Save the image 00201D_flip.png
 16%|██████▏                                | 250/1568 [00:43<03:41,  5.95it/s]16 02:49:53 Save the image 00202D.png
 16%|██████▏                                | 251/1568 [00:43<03:44,  5.87it/s]16 02:49:53 Save the image 00202D_flip.png
 16%|██████▎                                | 252/1568 [00:43<03:46,  5.81it/s]16 02:49:53 Save the image 00203D.png
 16%|██████▎                                | 253/1568 [00:43<03:47,  5.79it/s]16 02:49:53 Save the image 00203D_flip.png
 16%|██████▎                                | 254/1568 [00:43<03:43,  5.87it/s]16 02:49:53 Save the image 00204D.png
 16%|██████▎                                | 255/1568 [00:44<03:39,  5.99it/s]16 02:49:53 Save the image 00204D_flip.png
 16%|██████▎                                | 256/1568 [00:44<03:41,  5.92it/s]16 02:49:54 Save the image 00205D.png
 16%|██████▍                                | 257/1568 [00:44<03:42,  5.90it/s]16 02:49:54 Save the image 00205D_flip.png
 16%|██████▍                                | 258/1568 [00:44<03:44,  5.85it/s]16 02:49:54 Save the image 00206D.png
 17%|██████▍                                | 259/1568 [00:44<03:46,  5.79it/s]16 02:49:54 Save the image 00206D_flip.png
 17%|██████▍                                | 260/1568 [00:44<03:45,  5.79it/s]16 02:49:54 Save the image 00207D.png
 17%|██████▍                                | 261/1568 [00:45<03:45,  5.79it/s]16 02:49:55 Save the image 00207D_flip.png
 17%|██████▌                                | 262/1568 [00:45<03:42,  5.86it/s]16 02:49:55 Save the image 00208D.png
 17%|██████▌                                | 263/1568 [00:45<03:35,  6.04it/s]16 02:49:55 Save the image 00208D_flip.png
 17%|██████▌                                | 264/1568 [00:45<03:38,  5.96it/s]16 02:49:55 Save the image 00209D.png
 17%|██████▌                                | 265/1568 [00:45<03:38,  5.96it/s]16 02:49:55 Save the image 00209D_flip.png
 17%|██████▌                                | 266/1568 [00:45<03:39,  5.92it/s]16 02:49:55 Save the image 00210D.png
 17%|██████▋                                | 267/1568 [00:46<03:41,  5.89it/s]16 02:49:56 Save the image 00210D_flip.png
 17%|██████▋                                | 268/1568 [00:46<03:42,  5.85it/s]16 02:49:56 Save the image 00211D.png
 17%|██████▋                                | 269/1568 [00:46<03:43,  5.81it/s]16 02:49:56 Save the image 00211D_flip.png
 17%|██████▋                                | 270/1568 [00:46<03:43,  5.81it/s]16 02:49:56 Save the image 00212D.png
 17%|██████▋                                | 271/1568 [00:46<03:37,  5.96it/s]16 02:49:56 Save the image 00212D_flip.png
 17%|██████▊                                | 272/1568 [00:46<03:39,  5.90it/s]16 02:49:56 Save the image 00213D.png
 17%|██████▊                                | 273/1568 [00:47<03:41,  5.86it/s]16 02:49:57 Save the image 00213D_flip.png
 17%|██████▊                                | 274/1568 [00:47<03:40,  5.86it/s]16 02:49:57 Save the image 00214D.png
 18%|██████▊                                | 275/1568 [00:47<03:44,  5.76it/s]16 02:49:57 Save the image 00214D_flip.png
 18%|██████▊                                | 276/1568 [00:47<03:44,  5.76it/s]16 02:49:57 Save the image 00215D.png
 18%|██████▉                                | 277/1568 [00:47<03:43,  5.77it/s]16 02:49:57 Save the image 00215D_flip.png
 18%|██████▉                                | 278/1568 [00:47<03:41,  5.83it/s]16 02:49:57 Save the image 00216D.png
 18%|██████▉                                | 279/1568 [00:48<03:40,  5.85it/s]16 02:49:58 Save the image 00216D_flip.png
 18%|██████▉                                | 280/1568 [00:48<03:41,  5.82it/s]16 02:49:58 Save the image 00217D.png
 18%|██████▉                                | 281/1568 [00:48<03:39,  5.86it/s]16 02:49:58 Save the image 00217D_flip.png
 18%|███████                                | 282/1568 [00:48<03:38,  5.89it/s]16 02:49:58 Save the image 00218D.png
 18%|███████                                | 283/1568 [00:48<03:39,  5.86it/s]16 02:49:58 Save the image 00218D_flip.png
 18%|███████                                | 284/1568 [00:48<03:39,  5.85it/s]16 02:49:58 Save the image 00219D.png
 18%|███████                                | 285/1568 [00:49<03:39,  5.84it/s]16 02:49:59 Save the image 00219D_flip.png
 18%|███████                                | 286/1568 [00:49<03:40,  5.82it/s]16 02:49:59 Save the image 00220D.png
 18%|███████▏                               | 287/1568 [00:49<03:32,  6.02it/s]16 02:49:59 Save the image 00220D_flip.png
 18%|███████▏                               | 288/1568 [00:49<03:36,  5.92it/s]16 02:49:59 Save the image 00221D.png
 18%|███████▏                               | 289/1568 [00:49<03:37,  5.87it/s]16 02:49:59 Save the image 00221D_flip.png
 18%|███████▏                               | 290/1568 [00:49<03:37,  5.89it/s]16 02:49:59 Save the image 00222D.png
 19%|███████▏                               | 291/1568 [00:50<03:38,  5.85it/s]16 02:50:00 Save the image 00222D_flip.png
 19%|███████▎                               | 292/1568 [00:50<03:37,  5.86it/s]16 02:50:00 Save the image 00223D.png
 19%|███████▎                               | 293/1568 [00:50<03:38,  5.82it/s]16 02:50:00 Save the image 00223D_flip.png
 19%|███████▎                               | 294/1568 [00:50<03:36,  5.90it/s]16 02:50:00 Save the image 00224D.png
 19%|███████▎                               | 295/1568 [00:50<03:29,  6.09it/s]16 02:50:00 Save the image 00224D_flip.png
 19%|███████▎                               | 296/1568 [00:51<03:32,  5.99it/s]16 02:50:00 Save the image 00225D.png
 19%|███████▍                               | 297/1568 [00:51<03:34,  5.92it/s]16 02:50:01 Save the image 00225D_flip.png
 19%|███████▍                               | 298/1568 [00:51<03:36,  5.85it/s]16 02:50:01 Save the image 00226D.png
 19%|███████▍                               | 299/1568 [00:51<03:42,  5.70it/s]16 02:50:01 Save the image 00226D_flip.png
 19%|███████▍                               | 300/1568 [00:51<03:42,  5.69it/s]16 02:50:01 Save the image 00227D.png
 19%|███████▍                               | 301/1568 [00:51<03:41,  5.71it/s]16 02:50:01 Save the image 00227D_flip.png
 19%|███████▌                               | 302/1568 [00:52<03:42,  5.70it/s]16 02:50:01 Save the image 00228D.png
 19%|███████▌                               | 303/1568 [00:52<03:28,  6.06it/s]16 02:50:02 Save the image 00228D_flip.png
 19%|███████▌                               | 304/1568 [00:52<03:32,  5.95it/s]16 02:50:02 Save the image 00229D.png
 19%|███████▌                               | 305/1568 [00:52<03:32,  5.96it/s]16 02:50:02 Save the image 00229D_flip.png
 20%|███████▌                               | 306/1568 [00:52<03:32,  5.93it/s]16 02:50:02 Save the image 00230D.png
 20%|███████▋                               | 307/1568 [00:52<03:34,  5.88it/s]16 02:50:02 Save the image 00230D_flip.png
 20%|███████▋                               | 308/1568 [00:53<03:34,  5.86it/s]16 02:50:03 Save the image 00231D.png
 20%|███████▋                               | 309/1568 [00:53<03:35,  5.85it/s]16 02:50:03 Save the image 00231D_flip.png
 20%|███████▋                               | 310/1568 [00:53<03:35,  5.83it/s]16 02:50:03 Save the image 00232D.png
 20%|███████▋                               | 311/1568 [00:53<03:22,  6.21it/s]16 02:50:03 Save the image 00232D_flip.png
 20%|███████▊                               | 312/1568 [00:53<03:26,  6.08it/s]16 02:50:03 Save the image 00233D.png

 20%|███████▊                               | 313/1568 [00:53<03:27,  6.05it/s]16 02:50:03 Save the image 00233D_flip.png
 20%|███████▊                               | 314/1568 [00:54<03:28,  6.01it/s]16 02:50:04 Save the image 00234D.png
 20%|███████▊                               | 315/1568 [00:54<03:30,  5.94it/s]16 02:50:04 Save the image 00234D_flip.png
 20%|███████▊                               | 316/1568 [00:54<03:32,  5.90it/s]16 02:50:04 Save the image 00235D.png
 20%|███████▉                               | 317/1568 [00:54<03:32,  5.87it/s]16 02:50:04 Save the image 00235D_flip.png
 20%|███████▉                               | 318/1568 [00:54<03:32,  5.87it/s]16 02:50:04 Save the image 00236D.png
 20%|███████▉                               | 319/1568 [00:54<03:20,  6.24it/s]16 02:50:04 Save the image 00236D_flip.png
 20%|███████▉                               | 320/1568 [00:55<03:24,  6.11it/s]16 02:50:04 Save the image 00237D.png
 20%|███████▉                               | 321/1568 [00:55<03:25,  6.07it/s]16 02:50:05 Save the image 00237D_flip.png
 21%|████████                               | 322/1568 [00:55<03:26,  6.03it/s]16 02:50:05 Save the image 00238D.png
 21%|████████                               | 323/1568 [00:55<03:28,  5.96it/s]16 02:50:05 Save the image 00238D_flip.png
 21%|████████                               | 324/1568 [00:55<03:30,  5.92it/s]16 02:50:05 Save the image 00239D.png
 21%|████████                               | 325/1568 [00:55<03:30,  5.89it/s]16 02:50:05 Save the image 00239D_flip.png
 21%|████████                               | 326/1568 [00:56<03:31,  5.87it/s]16 02:50:05 Save the image 00240D.png
 21%|████████▏                              | 327/1568 [00:56<03:19,  6.21it/s]16 02:50:06 Save the image 00240D_flip.png
 21%|████████▏                              | 328/1568 [00:56<03:23,  6.08it/s]16 02:50:06 Save the image 00241D.png
 21%|████████▏                              | 329/1568 [00:56<03:24,  6.05it/s]16 02:50:06 Save the image 00241D_flip.png
 21%|████████▏                              | 330/1568 [00:56<03:25,  6.01it/s]16 02:50:06 Save the image 00242D.png
 21%|████████▏                              | 331/1568 [00:56<03:28,  5.94it/s]16 02:50:06 Save the image 00242D_flip.png
 21%|████████▎                              | 332/1568 [00:57<03:29,  5.91it/s]16 02:50:07 Save the image 00243D.png
 21%|████████▎                              | 333/1568 [00:57<03:30,  5.87it/s]16 02:50:07 Save the image 00243D_flip.png
 21%|████████▎                              | 334/1568 [00:57<03:30,  5.85it/s]16 02:50:07 Save the image 00244D.png
 21%|████████▎                              | 335/1568 [00:57<03:18,  6.23it/s]16 02:50:07 Save the image 00244D_flip.png
 21%|████████▎                              | 336/1568 [00:57<03:22,  6.10it/s]16 02:50:07 Save the image 00245D.png
 21%|████████▍                              | 337/1568 [00:57<03:23,  6.06it/s]16 02:50:07 Save the image 00245D_flip.png
 22%|████████▍                              | 338/1568 [00:58<03:24,  6.02it/s]16 02:50:08 Save the image 00246D.png
 22%|████████▍                              | 339/1568 [00:58<03:26,  5.95it/s]16 02:50:08 Save the image 00246D_flip.png
 22%|████████▍                              | 340/1568 [00:58<03:30,  5.84it/s]16 02:50:08 Save the image 00247D.png
 22%|████████▍                              | 341/1568 [00:58<03:30,  5.83it/s]16 02:50:08 Save the image 00247D_flip.png
 22%|████████▌                              | 342/1568 [00:58<03:30,  5.83it/s]16 02:50:08 Save the image 00248D.png
 22%|████████▌                              | 343/1568 [00:58<03:17,  6.21it/s]16 02:50:08 Save the image 00248D_flip.png
 22%|████████▌                              | 344/1568 [00:59<03:21,  6.09it/s]16 02:50:09 Save the image 00249D.png
 22%|████████▌                              | 345/1568 [00:59<03:21,  6.06it/s]16 02:50:09 Save the image 00249D_flip.png
 22%|████████▌                              | 346/1568 [00:59<03:24,  5.99it/s]16 02:50:09 Save the image 00250D.png
 22%|████████▋                              | 347/1568 [00:59<03:27,  5.88it/s]16 02:50:09 Save the image 00250D_flip.png
 22%|████████▋                              | 348/1568 [00:59<03:30,  5.81it/s]16 02:50:09 Save the image 00251D.png
 22%|████████▋                              | 349/1568 [00:59<03:29,  5.82it/s]16 02:50:09 Save the image 00251D_flip.png
 22%|████████▋                              | 350/1568 [01:00<03:29,  5.81it/s]16 02:50:10 Save the image 00252D.png
 22%|████████▋                              | 351/1568 [01:00<03:17,  6.15it/s]16 02:50:10 Save the image 00252D_flip.png
 22%|████████▊                              | 352/1568 [01:00<03:22,  6.00it/s]16 02:50:10 Save the image 00253D.png
 23%|████████▊                              | 353/1568 [01:00<03:22,  5.99it/s]16 02:50:10 Save the image 00253D_flip.png
 23%|████████▊                              | 354/1568 [01:00<03:22,  5.99it/s]16 02:50:10 Save the image 00254D.png
 23%|████████▊                              | 355/1568 [01:00<03:24,  5.92it/s]16 02:50:10 Save the image 00254D_flip.png
 23%|████████▊                              | 356/1568 [01:01<03:25,  5.89it/s]16 02:50:11 Save the image 00255D.png
 23%|████████▉                              | 357/1568 [01:01<03:26,  5.87it/s]16 02:50:11 Save the image 00255D_flip.png
 23%|████████▉                              | 358/1568 [01:01<03:26,  5.85it/s]16 02:50:11 Save the image 00256D.png
 23%|████████▉                              | 359/1568 [01:01<03:14,  6.21it/s]16 02:50:11 Save the image 00256D_flip.png
 23%|████████▉                              | 360/1568 [01:01<03:18,  6.08it/s]16 02:50:11 Save the image 00257D.png
 23%|████████▉                              | 361/1568 [01:01<03:19,  6.05it/s]16 02:50:11 Save the image 00257D_flip.png
 23%|█████████                              | 362/1568 [01:02<03:20,  6.02it/s]16 02:50:12 Save the image 00258D.png
 23%|█████████                              | 363/1568 [01:02<03:22,  5.95it/s]16 02:50:12 Save the image 00258D_flip.png
 23%|█████████                              | 364/1568 [01:02<03:24,  5.90it/s]16 02:50:12 Save the image 00259D.png
 23%|█████████                              | 365/1568 [01:02<03:26,  5.83it/s]16 02:50:12 Save the image 00259D_flip.png
 23%|█████████                              | 366/1568 [01:02<03:26,  5.82it/s]16 02:50:12 Save the image 00260D.png
 23%|█████████▏                             | 367/1568 [01:02<03:14,  6.18it/s]16 02:50:12 Save the image 00260D_flip.png
 23%|█████████▏                             | 368/1568 [01:03<03:18,  6.05it/s]16 02:50:13 Save the image 00261D.png
 24%|█████████▏                             | 369/1568 [01:03<03:20,  5.97it/s]16 02:50:13 Save the image 00261D_flip.png
 24%|█████████▏                             | 370/1568 [01:03<03:24,  5.86it/s]16 02:50:13 Save the image 00262D.png
 24%|█████████▏                             | 371/1568 [01:03<03:26,  5.81it/s]16 02:50:13 Save the image 00262D_flip.png
 24%|█████████▎                             | 372/1568 [01:03<03:27,  5.75it/s]16 02:50:13 Save the image 00263D.png
 24%|█████████▎                             | 373/1568 [01:03<03:27,  5.77it/s]16 02:50:13 Save the image 00263D_flip.png
 24%|█████████▎                             | 374/1568 [01:04<03:27,  5.76it/s]16 02:50:14 Save the image 00264D.png
 24%|█████████▎                             | 375/1568 [01:04<03:17,  6.05it/s]16 02:50:14 Save the image 00264D_flip.png
 24%|█████████▎                             | 376/1568 [01:04<03:20,  5.95it/s]16 02:50:14 Save the image 00265D.png

 24%|█████████▍                             | 377/1568 [01:04<03:22,  5.89it/s]16 02:50:14 Save the image 00265D_flip.png
 24%|█████████▍                             | 378/1568 [01:04<03:22,  5.87it/s]16 02:50:14 Save the image 00266D.png
 24%|█████████▍                             | 379/1568 [01:04<03:24,  5.81it/s]16 02:50:14 Save the image 00266D_flip.png
 24%|█████████▍                             | 380/1568 [01:05<03:24,  5.81it/s]16 02:50:15 Save the image 00267D.png
 24%|█████████▍                             | 381/1568 [01:05<03:23,  5.82it/s]16 02:50:15 Save the image 00267D_flip.png
 24%|█████████▌                             | 382/1568 [01:05<03:22,  5.85it/s]16 02:50:15 Save the image 00268D.png
 24%|█████████▌                             | 383/1568 [01:05<03:21,  5.89it/s]16 02:50:15 Save the image 00268D_flip.png
 24%|█████████▌                             | 384/1568 [01:05<03:21,  5.87it/s]16 02:50:15 Save the image 00269D.png
 25%|█████████▌                             | 385/1568 [01:05<03:20,  5.89it/s]16 02:50:15 Save the image 00269D_flip.png
 25%|█████████▌                             | 386/1568 [01:06<03:18,  5.94it/s]16 02:50:16 Save the image 00270D.png
 25%|█████████▋                             | 387/1568 [01:06<03:19,  5.92it/s]16 02:50:16 Save the image 00270D_flip.png
 25%|█████████▋                             | 388/1568 [01:06<03:19,  5.91it/s]16 02:50:16 Save the image 00271D.png
 25%|█████████▋                             | 389/1568 [01:06<03:19,  5.91it/s]16 02:50:16 Save the image 00271D_flip.png
 25%|█████████▋                             | 390/1568 [01:06<03:17,  5.97it/s]16 02:50:16 Save the image 00272D.png
 25%|█████████▋                             | 391/1568 [01:06<03:15,  6.04it/s]16 02:50:16 Save the image 00272D_flip.png
 25%|█████████▊                             | 392/1568 [01:07<03:16,  5.98it/s]16 02:50:17 Save the image 00273D.png
 25%|█████████▊                             | 393/1568 [01:07<03:17,  5.96it/s]16 02:50:17 Save the image 00273D_flip.png
 25%|█████████▊                             | 394/1568 [01:07<03:17,  5.95it/s]16 02:50:17 Save the image 00274D.png
 25%|█████████▊                             | 395/1568 [01:07<03:18,  5.91it/s]16 02:50:17 Save the image 00274D_flip.png
 25%|█████████▊                             | 396/1568 [01:07<03:19,  5.88it/s]16 02:50:17 Save the image 00275D.png
 25%|█████████▊                             | 397/1568 [01:08<03:19,  5.86it/s]16 02:50:17 Save the image 00275D_flip.png
 25%|█████████▉                             | 398/1568 [01:08<03:17,  5.92it/s]16 02:50:18 Save the image 00276D.png
 25%|█████████▉                             | 399/1568 [01:08<03:11,  6.11it/s]16 02:50:18 Save the image 00276D_flip.png
 26%|█████████▉                             | 400/1568 [01:08<03:14,  6.00it/s]16 02:50:18 Save the image 00277D.png
 26%|█████████▉                             | 401/1568 [01:08<03:15,  5.98it/s]16 02:50:18 Save the image 00277D_flip.png
 26%|█████████▉                             | 402/1568 [01:08<03:15,  5.97it/s]16 02:50:18 Save the image 00278D.png
 26%|██████████                             | 403/1568 [01:09<03:16,  5.93it/s]16 02:50:18 Save the image 00278D_flip.png
 26%|██████████                             | 404/1568 [01:09<03:17,  5.89it/s]16 02:50:19 Save the image 00279D.png
 26%|██████████                             | 405/1568 [01:09<03:18,  5.87it/s]16 02:50:19 Save the image 00279D_flip.png
 26%|██████████                             | 406/1568 [01:09<03:19,  5.83it/s]16 02:50:19 Save the image 00280D.png
 26%|██████████                             | 407/1568 [01:09<03:08,  6.16it/s]16 02:50:19 Save the image 00280D_flip.png
 26%|██████████▏                            | 408/1568 [01:09<03:11,  6.05it/s]16 02:50:19 Save the image 00281D.png
 26%|██████████▏                            | 409/1568 [01:10<03:12,  6.01it/s]16 02:50:19 Save the image 00281D_flip.png
 26%|██████████▏                            | 410/1568 [01:10<03:12,  6.00it/s]16 02:50:20 Save the image 00282D.png
 26%|██████████▏                            | 411/1568 [01:10<03:15,  5.93it/s]16 02:50:20 Save the image 00282D_flip.png
 26%|██████████▏                            | 412/1568 [01:10<03:18,  5.83it/s]16 02:50:20 Save the image 00283D.png
 26%|██████████▎                            | 413/1568 [01:10<03:18,  5.82it/s]16 02:50:20 Save the image 00283D_flip.png
 26%|██████████▎                            | 414/1568 [01:10<03:18,  5.83it/s]16 02:50:20 Save the image 00284D.png
 26%|██████████▎                            | 415/1568 [01:11<03:06,  6.17it/s]16 02:50:20 Save the image 00284D_flip.png
 27%|██████████▎                            | 416/1568 [01:11<03:10,  6.05it/s]16 02:50:21 Save the image 00285D.png
 27%|██████████▎                            | 417/1568 [01:11<03:11,  6.02it/s]16 02:50:21 Save the image 00285D_flip.png
 27%|██████████▍                            | 418/1568 [01:11<03:12,  5.99it/s]16 02:50:21 Save the image 00286D.png
 27%|██████████▍                            | 419/1568 [01:11<03:13,  5.93it/s]16 02:50:21 Save the image 00286D_flip.png
 27%|██████████▍                            | 420/1568 [01:11<03:14,  5.90it/s]16 02:50:21 Save the image 00287D.png
 27%|██████████▍                            | 421/1568 [01:12<03:14,  5.91it/s]16 02:50:21 Save the image 00287D_flip.png
 27%|██████████▍                            | 422/1568 [01:12<03:15,  5.86it/s]16 02:50:22 Save the image 00288D.png
 27%|██████████▌                            | 423/1568 [01:12<03:04,  6.20it/s]16 02:50:22 Save the image 00288D_flip.png
 27%|██████████▌                            | 424/1568 [01:12<03:08,  6.08it/s]16 02:50:22 Save the image 00289D.png
 27%|██████████▌                            | 425/1568 [01:12<03:09,  6.03it/s]16 02:50:22 Save the image 00289D_flip.png
 27%|██████████▌                            | 426/1568 [01:12<03:10,  5.98it/s]16 02:50:22 Save the image 00290D.png
 27%|██████████▌                            | 427/1568 [01:13<03:12,  5.92it/s]16 02:50:22 Save the image 00290D_flip.png
 27%|██████████▋                            | 428/1568 [01:13<03:13,  5.89it/s]16 02:50:23 Save the image 00291D.png
 27%|██████████▋                            | 429/1568 [01:13<03:13,  5.90it/s]16 02:50:23 Save the image 00291D_flip.png
 27%|██████████▋                            | 430/1568 [01:13<03:14,  5.86it/s]16 02:50:23 Save the image 00292D.png
 27%|██████████▋                            | 431/1568 [01:13<03:03,  6.20it/s]16 02:50:23 Save the image 00292D_flip.png
 28%|██████████▋                            | 432/1568 [01:13<03:07,  6.07it/s]16 02:50:23 Save the image 00293D.png
 28%|██████████▊                            | 433/1568 [01:14<03:08,  6.03it/s]16 02:50:23 Save the image 00293D_flip.png
 28%|██████████▊                            | 434/1568 [01:14<03:09,  5.99it/s]16 02:50:24 Save the image 00294D.png
 28%|██████████▊                            | 435/1568 [01:14<03:11,  5.92it/s]16 02:50:24 Save the image 00294D_flip.png
 28%|██████████▊                            | 436/1568 [01:14<03:12,  5.88it/s]16 02:50:24 Save the image 00295D.png
 28%|██████████▊                            | 437/1568 [01:14<03:12,  5.89it/s]16 02:50:24 Save the image 00295D_flip.png
 28%|██████████▉                            | 438/1568 [01:14<03:12,  5.86it/s]16 02:50:24 Save the image 00296D.png
 28%|██████████▉                            | 439/1568 [01:15<03:01,  6.23it/s]16 02:50:24 Save the image 00296D_flip.png
 28%|██████████▉                            | 440/1568 [01:15<03:05,  6.09it/s]16 02:50:25 Save the image 00297D.png

 28%|██████████▉                            | 441/1568 [01:15<03:07,  6.02it/s]16 02:50:25 Save the image 00297D_flip.png
 28%|██████████▉                            | 442/1568 [01:15<03:08,  5.98it/s]16 02:50:25 Save the image 00298D.png
 28%|███████████                            | 443/1568 [01:15<03:09,  5.93it/s]16 02:50:25 Save the image 00298D_flip.png
 28%|███████████                            | 444/1568 [01:15<03:10,  5.89it/s]16 02:50:25 Save the image 00299D.png
 28%|███████████                            | 445/1568 [01:16<03:10,  5.89it/s]16 02:50:26 Save the image 00299D_flip.png
 28%|███████████                            | 446/1568 [01:16<03:11,  5.86it/s]16 02:50:26 Save the image 00300D.png
 29%|███████████                            | 447/1568 [01:16<03:00,  6.23it/s]16 02:50:26 Save the image 00300D_flip.png
 29%|███████████▏                           | 448/1568 [01:16<03:04,  6.08it/s]16 02:50:26 Save the image 00301D.png
 29%|███████████▏                           | 449/1568 [01:16<03:06,  6.02it/s]16 02:50:26 Save the image 00301D_flip.png
 29%|███████████▏                           | 450/1568 [01:16<03:06,  5.98it/s]16 02:50:26 Save the image 00302D.png
 29%|███████████▏                           | 451/1568 [01:17<03:08,  5.92it/s]16 02:50:27 Save the image 00302D_flip.png
 29%|███████████▏                           | 452/1568 [01:17<03:09,  5.88it/s]16 02:50:27 Save the image 00303D.png
 29%|███████████▎                           | 453/1568 [01:17<03:12,  5.81it/s]16 02:50:27 Save the image 00303D_flip.png
 29%|███████████▎                           | 454/1568 [01:17<03:13,  5.75it/s]16 02:50:27 Save the image 00304D.png
 29%|███████████▎                           | 455/1568 [01:17<03:03,  6.05it/s]16 02:50:27 Save the image 00304D_flip.png
 29%|███████████▎                           | 456/1568 [01:17<03:08,  5.89it/s]16 02:50:27 Save the image 00305D.png
 29%|███████████▎                           | 457/1568 [01:18<03:11,  5.79it/s]16 02:50:28 Save the image 00305D_flip.png
 29%|███████████▍                           | 458/1568 [01:18<03:10,  5.84it/s]16 02:50:28 Save the image 00306D.png
 29%|███████████▍                           | 459/1568 [01:18<03:14,  5.71it/s]16 02:50:28 Save the image 00306D_flip.png
 29%|███████████▍                           | 460/1568 [01:18<03:14,  5.70it/s]16 02:50:28 Save the image 00307D.png
 29%|███████████▍                           | 461/1568 [01:18<03:13,  5.73it/s]16 02:50:28 Save the image 00307D_flip.png
 29%|███████████▍                           | 462/1568 [01:18<03:13,  5.73it/s]16 02:50:28 Save the image 00308D.png
 30%|███████████▌                           | 463/1568 [01:19<03:01,  6.08it/s]16 02:50:29 Save the image 00308D_flip.png
 30%|███████████▌                           | 464/1568 [01:19<03:08,  5.86it/s]16 02:50:29 Save the image 00309D.png
 30%|███████████▌                           | 465/1568 [01:19<03:07,  5.88it/s]16 02:50:29 Save the image 00309D_flip.png
 30%|███████████▌                           | 466/1568 [01:19<03:09,  5.81it/s]16 02:50:29 Save the image 00310D.png
 30%|███████████▌                           | 467/1568 [01:19<03:11,  5.75it/s]16 02:50:29 Save the image 00310D_flip.png
 30%|███████████▋                           | 468/1568 [01:19<03:10,  5.76it/s]16 02:50:29 Save the image 00311D.png
 30%|███████████▋                           | 469/1568 [01:20<03:09,  5.78it/s]16 02:50:30 Save the image 00311D_flip.png
 30%|███████████▋                           | 470/1568 [01:20<03:09,  5.80it/s]16 02:50:30 Save the image 00312D.png
 30%|███████████▋                           | 471/1568 [01:20<02:57,  6.18it/s]16 02:50:30 Save the image 00312D_flip.png
 30%|███████████▋                           | 472/1568 [01:20<03:01,  6.05it/s]16 02:50:30 Save the image 00313D.png
 30%|███████████▊                           | 473/1568 [01:20<03:02,  6.01it/s]16 02:50:30 Save the image 00313D_flip.png
 30%|███████████▊                           | 474/1568 [01:20<03:03,  5.97it/s]16 02:50:30 Save the image 00314D.png
 30%|███████████▊                           | 475/1568 [01:21<03:05,  5.90it/s]16 02:50:31 Save the image 00314D_flip.png
 30%|███████████▊                           | 476/1568 [01:21<03:06,  5.86it/s]16 02:50:31 Save the image 00315D.png
 30%|███████████▊                           | 477/1568 [01:21<03:07,  5.82it/s]16 02:50:31 Save the image 00315D_flip.png
 30%|███████████▉                           | 478/1568 [01:21<03:10,  5.74it/s]16 02:50:31 Save the image 00316D.png
 31%|███████████▉                           | 479/1568 [01:21<03:01,  5.98it/s]16 02:50:31 Save the image 00316D_flip.png
 31%|███████████▉                           | 480/1568 [01:22<03:04,  5.90it/s]16 02:50:31 Save the image 00317D.png
 31%|███████████▉                           | 481/1568 [01:22<03:05,  5.88it/s]16 02:50:32 Save the image 00317D_flip.png
 31%|███████████▉                           | 482/1568 [01:22<03:06,  5.84it/s]16 02:50:32 Save the image 00318D.png
 31%|████████████                           | 483/1568 [01:22<03:08,  5.75it/s]16 02:50:32 Save the image 00318D_flip.png
 31%|████████████                           | 484/1568 [01:22<03:09,  5.72it/s]16 02:50:32 Save the image 00319D.png
 31%|████████████                           | 485/1568 [01:22<03:07,  5.78it/s]16 02:50:32 Save the image 00319D_flip.png
 31%|████████████                           | 486/1568 [01:23<03:06,  5.80it/s]16 02:50:32 Save the image 00320D.png
 31%|████████████                           | 487/1568 [01:23<02:55,  6.15it/s]16 02:50:33 Save the image 00320D_flip.png
 31%|████████████▏                          | 488/1568 [01:23<02:58,  6.04it/s]16 02:50:33 Save the image 00321D.png
 31%|████████████▏                          | 489/1568 [01:23<02:59,  6.02it/s]16 02:50:33 Save the image 00321D_flip.png
 31%|████████████▏                          | 490/1568 [01:23<02:59,  6.00it/s]16 02:50:33 Save the image 00322D.png
 31%|████████████▏                          | 491/1568 [01:23<03:01,  5.95it/s]16 02:50:33 Save the image 00322D_flip.png
 31%|████████████▏                          | 492/1568 [01:24<03:02,  5.90it/s]16 02:50:33 Save the image 00323D.png
 31%|████████████▎                          | 493/1568 [01:24<03:02,  5.88it/s]16 02:50:34 Save the image 00323D_flip.png
 32%|████████████▎                          | 494/1568 [01:24<03:02,  5.87it/s]16 02:50:34 Save the image 00324D.png
 32%|████████████▎                          | 495/1568 [01:24<02:52,  6.21it/s]16 02:50:34 Save the image 00324D_flip.png
 32%|████████████▎                          | 496/1568 [01:24<02:57,  6.03it/s]16 02:50:34 Save the image 00325D.png
 32%|████████████▎                          | 497/1568 [01:24<02:58,  6.01it/s]16 02:50:34 Save the image 00325D_flip.png
 32%|████████████▍                          | 498/1568 [01:25<02:58,  5.99it/s]16 02:50:34 Save the image 00326D.png
 32%|████████████▍                          | 499/1568 [01:25<03:02,  5.85it/s]16 02:50:35 Save the image 00326D_flip.png
 32%|████████████▍                          | 500/1568 [01:25<03:03,  5.82it/s]16 02:50:35 Save the image 00327D.png
 32%|████████████▍                          | 501/1568 [01:25<03:03,  5.81it/s]16 02:50:35 Save the image 00327D_flip.png
 32%|████████████▍                          | 502/1568 [01:25<03:02,  5.83it/s]16 02:50:35 Save the image 00328D.png
 32%|████████████▌                          | 503/1568 [01:25<02:51,  6.21it/s]16 02:50:35 Save the image 00328D_flip.png
 32%|████████████▌                          | 504/1568 [01:26<02:55,  6.08it/s]16 02:50:35 Save the image 00329D.png

 32%|████████████▌                          | 505/1568 [01:26<02:55,  6.05it/s]16 02:50:36 Save the image 00329D_flip.png
 32%|████████████▌                          | 506/1568 [01:26<02:56,  6.01it/s]16 02:50:36 Save the image 00330D.png
 32%|████████████▌                          | 507/1568 [01:26<02:58,  5.94it/s]16 02:50:36 Save the image 00330D_flip.png
 32%|████████████▋                          | 508/1568 [01:26<03:00,  5.88it/s]16 02:50:36 Save the image 00331D.png
 32%|████████████▋                          | 509/1568 [01:26<03:01,  5.84it/s]16 02:50:36 Save the image 00331D_flip.png
 33%|████████████▋                          | 510/1568 [01:27<03:01,  5.83it/s]16 02:50:36 Save the image 00332D.png
 33%|████████████▋                          | 511/1568 [01:27<02:51,  6.16it/s]16 02:50:37 Save the image 00332D_flip.png
 33%|████████████▋                          | 512/1568 [01:27<02:54,  6.06it/s]16 02:50:37 Save the image 00333D.png
 33%|████████████▊                          | 513/1568 [01:27<02:55,  6.00it/s]16 02:50:37 Save the image 00333D_flip.png
 33%|████████████▊                          | 514/1568 [01:27<02:57,  5.95it/s]16 02:50:37 Save the image 00334D.png
 33%|████████████▊                          | 515/1568 [01:27<02:59,  5.86it/s]16 02:50:37 Save the image 00334D_flip.png
 33%|████████████▊                          | 516/1568 [01:28<02:59,  5.85it/s]16 02:50:38 Save the image 00335D.png
 33%|████████████▊                          | 517/1568 [01:28<03:00,  5.83it/s]16 02:50:38 Save the image 00335D_flip.png
 33%|████████████▉                          | 518/1568 [01:28<02:59,  5.86it/s]16 02:50:38 Save the image 00336D.png
 33%|████████████▉                          | 519/1568 [01:28<02:56,  5.95it/s]16 02:50:38 Save the image 00336D_flip.png
 33%|████████████▉                          | 520/1568 [01:28<02:58,  5.87it/s]16 02:50:38 Save the image 00337D.png
 33%|████████████▉                          | 521/1568 [01:28<02:57,  5.89it/s]16 02:50:38 Save the image 00337D_flip.png
 33%|████████████▉                          | 522/1568 [01:29<02:59,  5.84it/s]16 02:50:39 Save the image 00338D.png
 33%|█████████████                          | 523/1568 [01:29<03:01,  5.77it/s]16 02:50:39 Save the image 00338D_flip.png
 33%|█████████████                          | 524/1568 [01:29<03:00,  5.78it/s]16 02:50:39 Save the image 00339D.png
 33%|█████████████                          | 525/1568 [01:29<03:00,  5.77it/s]16 02:50:39 Save the image 00339D_flip.png
 34%|█████████████                          | 526/1568 [01:29<03:00,  5.78it/s]16 02:50:39 Save the image 00340D.png
 34%|█████████████                          | 527/1568 [01:29<02:56,  5.90it/s]16 02:50:39 Save the image 00340D_flip.png
 34%|█████████████▏                         | 528/1568 [01:30<02:56,  5.88it/s]16 02:50:40 Save the image 00341D.png
 34%|█████████████▏                         | 529/1568 [01:30<02:57,  5.85it/s]16 02:50:40 Save the image 00341D_flip.png
 34%|█████████████▏                         | 530/1568 [01:30<02:58,  5.81it/s]16 02:50:40 Save the image 00342D.png
 34%|█████████████▏                         | 531/1568 [01:30<02:58,  5.81it/s]16 02:50:40 Save the image 00342D_flip.png
 34%|█████████████▏                         | 532/1568 [01:30<02:58,  5.81it/s]16 02:50:40 Save the image 00343D.png
 34%|█████████████▎                         | 533/1568 [01:30<02:58,  5.80it/s]16 02:50:40 Save the image 00343D_flip.png
 34%|█████████████▎                         | 534/1568 [01:31<02:55,  5.88it/s]16 02:50:41 Save the image 00344D.png
 34%|█████████████▎                         | 535/1568 [01:31<02:51,  6.01it/s]16 02:50:41 Save the image 00344D_flip.png
 34%|█████████████▎                         | 536/1568 [01:31<02:53,  5.93it/s]16 02:50:41 Save the image 00345D.png
 34%|█████████████▎                         | 537/1568 [01:31<02:53,  5.94it/s]16 02:50:41 Save the image 00345D_flip.png
 34%|█████████████▍                         | 538/1568 [01:31<02:53,  5.92it/s]16 02:50:41 Save the image 00346D.png
 34%|█████████████▍                         | 539/1568 [01:31<02:55,  5.88it/s]16 02:50:41 Save the image 00346D_flip.png
 34%|█████████████▍                         | 540/1568 [01:32<02:55,  5.86it/s]16 02:50:42 Save the image 00347D.png
 35%|█████████████▍                         | 541/1568 [01:32<02:56,  5.82it/s]16 02:50:42 Save the image 00347D_flip.png
 35%|█████████████▍                         | 542/1568 [01:32<02:55,  5.85it/s]16 02:50:42 Save the image 00348D.png
 35%|█████████████▌                         | 543/1568 [01:32<02:50,  6.00it/s]16 02:50:42 Save the image 00348D_flip.png
 35%|█████████████▌                         | 544/1568 [01:32<02:52,  5.94it/s]16 02:50:42 Save the image 00349D.png
 35%|█████████████▌                         | 545/1568 [01:33<02:52,  5.93it/s]16 02:50:42 Save the image 00349D_flip.png
 35%|█████████████▌                         | 546/1568 [01:33<02:53,  5.90it/s]16 02:50:43 Save the image 00350D.png
 35%|█████████████▌                         | 547/1568 [01:33<02:55,  5.83it/s]16 02:50:43 Save the image 00350D_flip.png
 35%|█████████████▋                         | 548/1568 [01:33<02:55,  5.82it/s]16 02:50:43 Save the image 00351D.png
 35%|█████████████▋                         | 549/1568 [01:33<02:55,  5.82it/s]16 02:50:43 Save the image 00351D_flip.png
 35%|█████████████▋                         | 550/1568 [01:33<02:53,  5.87it/s]16 02:50:43 Save the image 00352D.png
 35%|█████████████▋                         | 551/1568 [01:34<02:49,  5.99it/s]16 02:50:43 Save the image 00352D_flip.png
 35%|█████████████▋                         | 552/1568 [01:34<02:53,  5.84it/s]16 02:50:44 Save the image 00353D.png
 35%|█████████████▊                         | 553/1568 [01:34<02:53,  5.85it/s]16 02:50:44 Save the image 00353D_flip.png
 35%|█████████████▊                         | 554/1568 [01:34<02:52,  5.88it/s]16 02:50:44 Save the image 00354D.png
 35%|█████████████▊                         | 555/1568 [01:34<02:53,  5.85it/s]16 02:50:44 Save the image 00354D_flip.png
 35%|█████████████▊                         | 556/1568 [01:34<02:54,  5.79it/s]16 02:50:44 Save the image 00355D.png
 36%|█████████████▊                         | 557/1568 [01:35<02:55,  5.77it/s]16 02:50:45 Save the image 00355D_flip.png
 36%|█████████████▉                         | 558/1568 [01:35<02:53,  5.83it/s]16 02:50:45 Save the image 00356D.png
 36%|█████████████▉                         | 559/1568 [01:35<02:46,  6.07it/s]16 02:50:45 Save the image 00356D_flip.png
 36%|█████████████▉                         | 560/1568 [01:35<02:48,  5.98it/s]16 02:50:45 Save the image 00357D.png
 36%|█████████████▉                         | 561/1568 [01:35<02:48,  5.96it/s]16 02:50:45 Save the image 00357D_flip.png
 36%|█████████████▉                         | 562/1568 [01:35<02:49,  5.94it/s]16 02:50:45 Save the image 00358D.png
 36%|██████████████                         | 563/1568 [01:36<02:50,  5.89it/s]16 02:50:46 Save the image 00358D_flip.png
 36%|██████████████                         | 564/1568 [01:36<02:51,  5.86it/s]16 02:50:46 Save the image 00359D.png
 36%|██████████████                         | 565/1568 [01:36<02:50,  5.87it/s]16 02:50:46 Save the image 00359D_flip.png
 36%|██████████████                         | 566/1568 [01:36<02:51,  5.83it/s]16 02:50:46 Save the image 00360D.png
 36%|██████████████                         | 567/1568 [01:36<02:44,  6.08it/s]16 02:50:46 Save the image 00360D_flip.png
 36%|██████████████▏                        | 568/1568 [01:36<02:48,  5.94it/s]16 02:50:46 Save the image 00361D.png

 36%|██████████████▏                        | 569/1568 [01:37<02:48,  5.92it/s]16 02:50:47 Save the image 00361D_flip.png
 36%|██████████████▏                        | 570/1568 [01:37<02:48,  5.92it/s]16 02:50:47 Save the image 00362D.png
 36%|██████████████▏                        | 571/1568 [01:37<02:50,  5.84it/s]16 02:50:47 Save the image 00362D_flip.png
 36%|██████████████▏                        | 572/1568 [01:37<02:51,  5.82it/s]16 02:50:47 Save the image 00363D.png
 37%|██████████████▎                        | 573/1568 [01:37<02:50,  5.83it/s]16 02:50:47 Save the image 00363D_flip.png
 37%|██████████████▎                        | 574/1568 [01:37<02:48,  5.89it/s]16 02:50:47 Save the image 00364D.png
 37%|██████████████▎                        | 575/1568 [01:38<02:45,  5.98it/s]16 02:50:48 Save the image 00364D_flip.png
 37%|██████████████▎                        | 576/1568 [01:38<02:48,  5.88it/s]16 02:50:48 Save the image 00365D.png
 37%|██████████████▎                        | 577/1568 [01:38<02:49,  5.85it/s]16 02:50:48 Save the image 00365D_flip.png
 37%|██████████████▍                        | 578/1568 [01:38<02:48,  5.89it/s]16 02:50:48 Save the image 00366D.png
 37%|██████████████▍                        | 579/1568 [01:38<02:49,  5.84it/s]16 02:50:48 Save the image 00366D_flip.png
 37%|██████████████▍                        | 580/1568 [01:38<02:50,  5.81it/s]16 02:50:48 Save the image 00367D.png
 37%|██████████████▍                        | 581/1568 [01:39<02:50,  5.80it/s]16 02:50:49 Save the image 00367D_flip.png
 37%|██████████████▍                        | 582/1568 [01:39<02:49,  5.82it/s]16 02:50:49 Save the image 00368D.png
 37%|██████████████▌                        | 583/1568 [01:39<02:43,  6.04it/s]16 02:50:49 Save the image 00368D_flip.png
 37%|██████████████▌                        | 584/1568 [01:39<02:44,  5.97it/s]16 02:50:49 Save the image 00369D.png
 37%|██████████████▌                        | 585/1568 [01:39<02:44,  5.96it/s]16 02:50:49 Save the image 00369D_flip.png
 37%|██████████████▌                        | 586/1568 [01:39<02:45,  5.94it/s]16 02:50:49 Save the image 00370D.png
 37%|██████████████▌                        | 587/1568 [01:40<02:47,  5.87it/s]16 02:50:50 Save the image 00370D_flip.png
 38%|██████████████▋                        | 588/1568 [01:40<02:47,  5.87it/s]16 02:50:50 Save the image 00371D.png
 38%|██████████████▋                        | 589/1568 [01:40<02:47,  5.85it/s]16 02:50:50 Save the image 00371D_flip.png
 38%|██████████████▋                        | 590/1568 [01:40<02:46,  5.86it/s]16 02:50:50 Save the image 00372D.png
 38%|██████████████▋                        | 591/1568 [01:40<02:37,  6.19it/s]16 02:50:50 Save the image 00372D_flip.png
 38%|██████████████▋                        | 592/1568 [01:40<02:40,  6.07it/s]16 02:50:50 Save the image 00373D.png
 38%|██████████████▋                        | 593/1568 [01:41<02:41,  6.03it/s]16 02:50:51 Save the image 00373D_flip.png
 38%|██████████████▊                        | 594/1568 [01:41<02:42,  6.00it/s]16 02:50:51 Save the image 00374D.png
 38%|██████████████▊                        | 595/1568 [01:41<02:43,  5.94it/s]16 02:50:51 Save the image 00374D_flip.png
 38%|██████████████▊                        | 596/1568 [01:41<02:44,  5.91it/s]16 02:50:51 Save the image 00375D.png
 38%|██████████████▊                        | 597/1568 [01:41<02:45,  5.88it/s]16 02:50:51 Save the image 00375D_flip.png
 38%|██████████████▊                        | 598/1568 [01:41<02:45,  5.85it/s]16 02:50:51 Save the image 00376D.png
 38%|██████████████▉                        | 599/1568 [01:42<02:35,  6.23it/s]16 02:50:52 Save the image 00376D_flip.png
 38%|██████████████▉                        | 600/1568 [01:42<02:38,  6.09it/s]16 02:50:52 Save the image 00377D.png
 38%|██████████████▉                        | 601/1568 [01:42<02:39,  6.06it/s]16 02:50:52 Save the image 00377D_flip.png
 38%|██████████████▉                        | 602/1568 [01:42<02:40,  6.02it/s]16 02:50:52 Save the image 00378D.png
 38%|██████████████▉                        | 603/1568 [01:42<02:42,  5.95it/s]16 02:50:52 Save the image 00378D_flip.png
 39%|███████████████                        | 604/1568 [01:42<02:43,  5.90it/s]16 02:50:52 Save the image 00379D.png
 39%|███████████████                        | 605/1568 [01:43<02:42,  5.93it/s]16 02:50:53 Save the image 00379D_flip.png
 39%|███████████████                        | 606/1568 [01:43<02:43,  5.90it/s]16 02:50:53 Save the image 00380D.png
 39%|███████████████                        | 607/1568 [01:43<02:34,  6.21it/s]16 02:50:53 Save the image 00380D_flip.png
 39%|███████████████                        | 608/1568 [01:43<02:38,  6.08it/s]16 02:50:53 Save the image 00381D.png
 39%|███████████████▏                       | 609/1568 [01:43<02:38,  6.04it/s]16 02:50:53 Save the image 00381D_flip.png
 39%|███████████████▏                       | 610/1568 [01:43<02:39,  6.01it/s]16 02:50:53 Save the image 00382D.png
 39%|███████████████▏                       | 611/1568 [01:44<02:41,  5.94it/s]16 02:50:54 Save the image 00382D_flip.png
 39%|███████████████▏                       | 612/1568 [01:44<02:43,  5.84it/s]16 02:50:54 Save the image 00383D.png
 39%|███████████████▏                       | 613/1568 [01:44<02:43,  5.85it/s]16 02:50:54 Save the image 00383D_flip.png
 39%|███████████████▎                       | 614/1568 [01:44<02:43,  5.84it/s]16 02:50:54 Save the image 00384D.png
 39%|███████████████▎                       | 615/1568 [01:44<02:33,  6.22it/s]16 02:50:54 Save the image 00384D_flip.png
 39%|███████████████▎                       | 616/1568 [01:44<02:36,  6.10it/s]16 02:50:54 Save the image 00385D.png
 39%|███████████████▎                       | 617/1568 [01:45<02:36,  6.06it/s]16 02:50:55 Save the image 00385D_flip.png
 39%|███████████████▎                       | 618/1568 [01:45<02:37,  6.02it/s]16 02:50:55 Save the image 00386D.png
 39%|███████████████▍                       | 619/1568 [01:45<02:40,  5.93it/s]16 02:50:55 Save the image 00386D_flip.png
 40%|███████████████▍                       | 620/1568 [01:45<02:40,  5.90it/s]16 02:50:55 Save the image 00387D.png
 40%|███████████████▍                       | 621/1568 [01:45<02:41,  5.87it/s]16 02:50:55 Save the image 00387D_flip.png
 40%|███████████████▍                       | 622/1568 [01:46<02:41,  5.85it/s]16 02:50:55 Save the image 00388D.png
 40%|███████████████▍                       | 623/1568 [01:46<02:32,  6.20it/s]16 02:50:56 Save the image 00388D_flip.png
 40%|███████████████▌                       | 624/1568 [01:46<02:35,  6.08it/s]16 02:50:56 Save the image 00389D.png
 40%|███████████████▌                       | 625/1568 [01:46<02:35,  6.05it/s]16 02:50:56 Save the image 00389D_flip.png
 40%|███████████████▌                       | 626/1568 [01:46<02:36,  6.02it/s]16 02:50:56 Save the image 00390D.png
 40%|███████████████▌                       | 627/1568 [01:46<02:38,  5.95it/s]16 02:50:56 Save the image 00390D_flip.png
 40%|███████████████▌                       | 628/1568 [01:46<02:39,  5.91it/s]16 02:50:56 Save the image 00391D.png
 40%|███████████████▋                       | 629/1568 [01:47<02:39,  5.87it/s]16 02:50:57 Save the image 00391D_flip.png
 40%|███████████████▋                       | 630/1568 [01:47<02:40,  5.85it/s]16 02:50:57 Save the image 00392D.png
 40%|███████████████▋                       | 631/1568 [01:47<02:30,  6.22it/s]16 02:50:57 Save the image 00392D_flip.png
 40%|███████████████▋                       | 632/1568 [01:47<02:33,  6.09it/s]16 02:50:57 Save the image 00393D.png

 40%|███████████████▋                       | 633/1568 [01:47<02:34,  6.05it/s]16 02:50:57 Save the image 00393D_flip.png
 40%|███████████████▊                       | 634/1568 [01:47<02:35,  6.02it/s]16 02:50:57 Save the image 00394D.png
 40%|███████████████▊                       | 635/1568 [01:48<02:36,  5.95it/s]16 02:50:58 Save the image 00394D_flip.png
 41%|███████████████▊                       | 636/1568 [01:48<02:37,  5.91it/s]16 02:50:58 Save the image 00395D.png
 41%|███████████████▊                       | 637/1568 [01:48<02:38,  5.88it/s]16 02:50:58 Save the image 00395D_flip.png
 41%|███████████████▊                       | 638/1568 [01:48<02:38,  5.86it/s]16 02:50:58 Save the image 00396D.png
 41%|███████████████▉                       | 639/1568 [01:48<02:28,  6.24it/s]16 02:50:58 Save the image 00396D_flip.png
 41%|███████████████▉                       | 640/1568 [01:48<02:32,  6.10it/s]16 02:50:58 Save the image 00397D.png
 41%|███████████████▉                       | 641/1568 [01:49<02:32,  6.06it/s]16 02:50:59 Save the image 00397D_flip.png
 41%|███████████████▉                       | 642/1568 [01:49<02:33,  6.02it/s]16 02:50:59 Save the image 00398D.png
 41%|███████████████▉                       | 643/1568 [01:49<02:35,  5.95it/s]16 02:50:59 Save the image 00398D_flip.png
 41%|████████████████                       | 644/1568 [01:49<02:36,  5.91it/s]16 02:50:59 Save the image 00399D.png
 41%|████████████████                       | 645/1568 [01:49<02:36,  5.88it/s]16 02:50:59 Save the image 00399D_flip.png
 41%|████████████████                       | 646/1568 [01:50<02:36,  5.87it/s]16 02:50:59 Save the image 00400D.png
 41%|████████████████                       | 647/1568 [01:50<02:28,  6.20it/s]16 02:51:00 Save the image 00400D_flip.png
 41%|████████████████                       | 648/1568 [01:50<02:31,  6.07it/s]16 02:51:00 Save the image 00401D.png
 41%|████████████████▏                      | 649/1568 [01:50<02:32,  6.04it/s]16 02:51:00 Save the image 00401D_flip.png
 41%|████████████████▏                      | 650/1568 [01:50<02:32,  6.01it/s]16 02:51:00 Save the image 00402D.png
 42%|████████████████▏                      | 651/1568 [01:50<02:34,  5.94it/s]16 02:51:00 Save the image 00402D_flip.png
 42%|████████████████▏                      | 652/1568 [01:50<02:34,  5.91it/s]16 02:51:00 Save the image 00403D.png
 42%|████████████████▏                      | 653/1568 [01:51<02:35,  5.88it/s]16 02:51:01 Save the image 00403D_flip.png
 42%|████████████████▎                      | 654/1568 [01:51<02:36,  5.85it/s]16 02:51:01 Save the image 00404D.png
 42%|████████████████▎                      | 655/1568 [01:51<02:26,  6.23it/s]16 02:51:01 Save the image 00404D_flip.png
 42%|████████████████▎                      | 656/1568 [01:51<02:29,  6.10it/s]16 02:51:01 Save the image 00405D.png
 42%|████████████████▎                      | 657/1568 [01:51<02:30,  6.06it/s]16 02:51:01 Save the image 00405D_flip.png
 42%|████████████████▎                      | 658/1568 [01:51<02:31,  6.01it/s]16 02:51:01 Save the image 00406D.png
 42%|████████████████▍                      | 659/1568 [01:52<02:32,  5.95it/s]16 02:51:02 Save the image 00406D_flip.png
 42%|████████████████▍                      | 660/1568 [01:52<02:32,  5.94it/s]16 02:51:02 Save the image 00407D.png
 42%|████████████████▍                      | 661/1568 [01:52<02:33,  5.91it/s]16 02:51:02 Save the image 00407D_flip.png
 42%|████████████████▍                      | 662/1568 [01:52<02:34,  5.88it/s]16 02:51:02 Save the image 00408D.png
 42%|████████████████▍                      | 663/1568 [01:52<02:25,  6.23it/s]16 02:51:02 Save the image 00408D_flip.png
 42%|████████████████▌                      | 664/1568 [01:52<02:28,  6.10it/s]16 02:51:02 Save the image 00409D.png
 42%|████████████████▌                      | 665/1568 [01:53<02:29,  6.06it/s]16 02:51:03 Save the image 00409D_flip.png
 42%|████████████████▌                      | 666/1568 [01:53<02:29,  6.01it/s]16 02:51:03 Save the image 00410D.png
 43%|████████████████▌                      | 667/1568 [01:53<02:31,  5.95it/s]16 02:51:03 Save the image 00410D_flip.png
 43%|████████████████▌                      | 668/1568 [01:53<02:31,  5.96it/s]16 02:51:03 Save the image 00411D.png
 43%|████████████████▋                      | 669/1568 [01:53<02:31,  5.92it/s]16 02:51:03 Save the image 00411D_flip.png
 43%|████████████████▋                      | 670/1568 [01:54<02:32,  5.91it/s]16 02:51:03 Save the image 00412D.png
 43%|████████████████▋                      | 671/1568 [01:54<02:23,  6.25it/s]16 02:51:04 Save the image 00412D_flip.png
 43%|████████████████▋                      | 672/1568 [01:54<02:26,  6.11it/s]16 02:51:04 Save the image 00413D.png
 43%|████████████████▋                      | 673/1568 [01:54<02:27,  6.07it/s]16 02:51:04 Save the image 00413D_flip.png
 43%|████████████████▊                      | 674/1568 [01:54<02:28,  6.03it/s]16 02:51:04 Save the image 00414D.png
 43%|████████████████▊                      | 675/1568 [01:54<02:29,  5.95it/s]16 02:51:04 Save the image 00414D_flip.png
 43%|████████████████▊                      | 676/1568 [01:54<02:30,  5.93it/s]16 02:51:04 Save the image 00415D.png
 43%|████████████████▊                      | 677/1568 [01:55<02:30,  5.90it/s]16 02:51:05 Save the image 00415D_flip.png
 43%|████████████████▊                      | 678/1568 [01:55<02:31,  5.87it/s]16 02:51:05 Save the image 00416D.png
 43%|████████████████▉                      | 679/1568 [01:55<02:22,  6.24it/s]16 02:51:05 Save the image 00416D_flip.png
 43%|████████████████▉                      | 680/1568 [01:55<02:25,  6.10it/s]16 02:51:05 Save the image 00417D.png
 43%|████████████████▉                      | 681/1568 [01:55<02:26,  6.07it/s]16 02:51:05 Save the image 00417D_flip.png
 43%|████████████████▉                      | 682/1568 [01:55<02:26,  6.03it/s]16 02:51:05 Save the image 00418D.png
 44%|████████████████▉                      | 683/1568 [01:56<02:29,  5.93it/s]16 02:51:06 Save the image 00418D_flip.png
 44%|█████████████████                      | 684/1568 [01:56<02:29,  5.93it/s]16 02:51:06 Save the image 00419D.png
 44%|█████████████████                      | 685/1568 [01:56<02:29,  5.90it/s]16 02:51:06 Save the image 00419D_flip.png
 44%|█████████████████                      | 686/1568 [01:56<02:29,  5.91it/s]16 02:51:06 Save the image 00420D.png
 44%|█████████████████                      | 687/1568 [01:56<02:20,  6.28it/s]16 02:51:06 Save the image 00420D_flip.png
 44%|█████████████████                      | 688/1568 [01:56<02:23,  6.13it/s]16 02:51:06 Save the image 00421D.png
 44%|█████████████████▏                     | 689/1568 [01:57<02:24,  6.08it/s]16 02:51:07 Save the image 00421D_flip.png
 44%|█████████████████▏                     | 690/1568 [01:57<02:25,  6.03it/s]16 02:51:07 Save the image 00422D.png
 44%|█████████████████▏                     | 691/1568 [01:57<02:27,  5.96it/s]16 02:51:07 Save the image 00422D_flip.png
 44%|█████████████████▏                     | 692/1568 [01:57<02:28,  5.92it/s]16 02:51:07 Save the image 00423D.png
 44%|█████████████████▏                     | 693/1568 [01:57<02:28,  5.89it/s]16 02:51:07 Save the image 00423D_flip.png
 44%|█████████████████▎                     | 694/1568 [01:58<02:30,  5.80it/s]16 02:51:07 Save the image 00424D.png
 44%|█████████████████▎                     | 695/1568 [01:58<02:24,  6.03it/s]16 02:51:08 Save the image 00424D_flip.png
 44%|█████████████████▎                     | 696/1568 [01:58<02:26,  5.97it/s]16 02:51:08 Save the image 00425D.png

 44%|█████████████████▎                     | 697/1568 [01:58<02:25,  5.98it/s]16 02:51:08 Save the image 00425D_flip.png
 45%|█████████████████▎                     | 698/1568 [01:58<02:25,  5.98it/s]16 02:51:08 Save the image 00426D.png
 45%|█████████████████▍                     | 699/1568 [01:58<02:26,  5.92it/s]16 02:51:08 Save the image 00426D_flip.png
 45%|█████████████████▍                     | 700/1568 [01:58<02:25,  5.97it/s]16 02:51:08 Save the image 00427D.png
 45%|█████████████████▍                     | 701/1568 [01:59<02:26,  5.93it/s]16 02:51:09 Save the image 00427D_flip.png
 45%|█████████████████▍                     | 702/1568 [01:59<02:26,  5.90it/s]16 02:51:09 Save the image 00428D.png
 45%|█████████████████▍                     | 703/1568 [01:59<02:19,  6.20it/s]16 02:51:09 Save the image 00428D_flip.png
 45%|█████████████████▌                     | 704/1568 [01:59<02:22,  6.08it/s]16 02:51:09 Save the image 00429D.png
 45%|█████████████████▌                     | 705/1568 [01:59<02:23,  6.00it/s]16 02:51:09 Save the image 00429D_flip.png
 45%|█████████████████▌                     | 706/1568 [01:59<02:24,  5.97it/s]16 02:51:09 Save the image 00430D.png
 45%|█████████████████▌                     | 707/1568 [02:00<02:25,  5.91it/s]16 02:51:10 Save the image 00430D_flip.png
 45%|█████████████████▌                     | 708/1568 [02:00<02:24,  5.94it/s]16 02:51:10 Save the image 00431D.png
 45%|█████████████████▋                     | 709/1568 [02:00<02:25,  5.88it/s]16 02:51:10 Save the image 00431D_flip.png
 45%|█████████████████▋                     | 710/1568 [02:00<02:27,  5.83it/s]16 02:51:10 Save the image 00432D.png
 45%|█████████████████▋                     | 711/1568 [02:00<02:18,  6.18it/s]16 02:51:10 Save the image 00432D_flip.png
 45%|█████████████████▋                     | 712/1568 [02:00<02:22,  6.01it/s]16 02:51:10 Save the image 00433D.png
 45%|█████████████████▋                     | 713/1568 [02:01<02:22,  6.00it/s]16 02:51:11 Save the image 00433D_flip.png
 46%|█████████████████▊                     | 714/1568 [02:01<02:23,  5.93it/s]16 02:51:11 Save the image 00434D.png
 46%|█████████████████▊                     | 715/1568 [02:01<02:26,  5.81it/s]16 02:51:11 Save the image 00434D_flip.png
 46%|█████████████████▊                     | 716/1568 [02:01<02:25,  5.84it/s]16 02:51:11 Save the image 00435D.png
 46%|█████████████████▊                     | 717/1568 [02:01<02:27,  5.78it/s]16 02:51:11 Save the image 00435D_flip.png
 46%|█████████████████▊                     | 718/1568 [02:02<02:26,  5.80it/s]16 02:51:11 Save the image 00436D.png
 46%|█████████████████▉                     | 719/1568 [02:02<02:21,  5.98it/s]16 02:51:12 Save the image 00436D_flip.png
 46%|█████████████████▉                     | 720/1568 [02:02<02:25,  5.84it/s]16 02:51:12 Save the image 00437D.png
 46%|█████████████████▉                     | 721/1568 [02:02<02:25,  5.83it/s]16 02:51:12 Save the image 00437D_flip.png
 46%|█████████████████▉                     | 722/1568 [02:02<02:25,  5.83it/s]16 02:51:12 Save the image 00438D.png
 46%|█████████████████▉                     | 723/1568 [02:02<02:25,  5.80it/s]16 02:51:12 Save the image 00438D_flip.png
 46%|██████████████████                     | 724/1568 [02:03<02:24,  5.84it/s]16 02:51:13 Save the image 00439D.png
 46%|██████████████████                     | 725/1568 [02:03<02:25,  5.79it/s]16 02:51:13 Save the image 00439D_flip.png
 46%|██████████████████                     | 726/1568 [02:03<02:25,  5.81it/s]16 02:51:13 Save the image 00440D.png
 46%|██████████████████                     | 727/1568 [02:03<02:23,  5.86it/s]16 02:51:13 Save the image 00440D_flip.png
 46%|██████████████████                     | 728/1568 [02:03<02:24,  5.82it/s]16 02:51:13 Save the image 00441D.png
 46%|██████████████████▏                    | 729/1568 [02:03<02:23,  5.85it/s]16 02:51:13 Save the image 00441D_flip.png
 47%|██████████████████▏                    | 730/1568 [02:04<02:23,  5.82it/s]16 02:51:14 Save the image 00442D.png
 47%|██████████████████▏                    | 731/1568 [02:04<02:23,  5.82it/s]16 02:51:14 Save the image 00442D_flip.png
 47%|██████████████████▏                    | 732/1568 [02:04<02:24,  5.79it/s]16 02:51:14 Save the image 00443D.png
 47%|██████████████████▏                    | 733/1568 [02:04<02:24,  5.80it/s]16 02:51:14 Save the image 00443D_flip.png
 47%|██████████████████▎                    | 734/1568 [02:04<02:21,  5.87it/s]16 02:51:14 Save the image 00444D.png
 47%|██████████████████▎                    | 735/1568 [02:04<02:21,  5.90it/s]16 02:51:14 Save the image 00444D_flip.png
 47%|██████████████████▎                    | 736/1568 [02:05<02:21,  5.87it/s]16 02:51:15 Save the image 00445D.png
 47%|██████████████████▎                    | 737/1568 [02:05<02:21,  5.89it/s]16 02:51:15 Save the image 00445D_flip.png
 47%|██████████████████▎                    | 738/1568 [02:05<02:20,  5.92it/s]16 02:51:15 Save the image 00446D.png
 47%|██████████████████▍                    | 739/1568 [02:05<02:20,  5.89it/s]16 02:51:15 Save the image 00446D_flip.png
 47%|██████████████████▍                    | 740/1568 [02:05<02:21,  5.86it/s]16 02:51:15 Save the image 00447D.png
 47%|██████████████████▍                    | 741/1568 [02:05<02:21,  5.86it/s]16 02:51:15 Save the image 00447D_flip.png
 47%|██████████████████▍                    | 742/1568 [02:06<02:19,  5.91it/s]16 02:51:16 Save the image 00448D.png
 47%|██████████████████▍                    | 743/1568 [02:06<02:16,  6.06it/s]16 02:51:16 Save the image 00448D_flip.png
 47%|██████████████████▌                    | 744/1568 [02:06<02:17,  5.99it/s]16 02:51:16 Save the image 00449D.png
 48%|██████████████████▌                    | 745/1568 [02:06<02:18,  5.96it/s]16 02:51:16 Save the image 00449D_flip.png
 48%|██████████████████▌                    | 746/1568 [02:06<02:18,  5.95it/s]16 02:51:16 Save the image 00450D.png
 48%|██████████████████▌                    | 747/1568 [02:06<02:19,  5.90it/s]16 02:51:16 Save the image 00450D_flip.png
 48%|██████████████████▌                    | 748/1568 [02:07<02:19,  5.89it/s]16 02:51:17 Save the image 00451D.png
 48%|██████████████████▋                    | 749/1568 [02:07<02:19,  5.85it/s]16 02:51:17 Save the image 00451D_flip.png
 48%|██████████████████▋                    | 750/1568 [02:07<02:18,  5.91it/s]16 02:51:17 Save the image 00452D.png
 48%|██████████████████▋                    | 751/1568 [02:07<02:13,  6.12it/s]16 02:51:17 Save the image 00452D_flip.png
 48%|██████████████████▋                    | 752/1568 [02:07<02:15,  6.03it/s]16 02:51:17 Save the image 00453D.png
 48%|██████████████████▋                    | 753/1568 [02:07<02:15,  5.99it/s]16 02:51:17 Save the image 00453D_flip.png
 48%|██████████████████▊                    | 754/1568 [02:08<02:16,  5.98it/s]16 02:51:18 Save the image 00454D.png
 48%|██████████████████▊                    | 755/1568 [02:08<02:17,  5.92it/s]16 02:51:18 Save the image 00454D_flip.png
 48%|██████████████████▊                    | 756/1568 [02:08<02:17,  5.92it/s]16 02:51:18 Save the image 00455D.png
 48%|██████████████████▊                    | 757/1568 [02:08<02:17,  5.89it/s]16 02:51:18 Save the image 00455D_flip.png
 48%|██████████████████▊                    | 758/1568 [02:08<02:16,  5.94it/s]16 02:51:18 Save the image 00456D.png
 48%|██████████████████▉                    | 759/1568 [02:08<02:12,  6.11it/s]16 02:51:18 Save the image 00456D_flip.png
 48%|██████████████████▉                    | 760/1568 [02:09<02:14,  6.01it/s]16 02:51:19 Save the image 00457D.png

 49%|██████████████████▉                    | 761/1568 [02:09<02:15,  5.98it/s]16 02:51:19 Save the image 00457D_flip.png
 49%|██████████████████▉                    | 762/1568 [02:09<02:15,  5.96it/s]16 02:51:19 Save the image 00458D.png
 49%|██████████████████▉                    | 763/1568 [02:09<02:16,  5.90it/s]16 02:51:19 Save the image 00458D_flip.png
 49%|███████████████████                    | 764/1568 [02:09<02:16,  5.87it/s]16 02:51:19 Save the image 00459D.png
 49%|███████████████████                    | 765/1568 [02:09<02:16,  5.88it/s]16 02:51:19 Save the image 00459D_flip.png
 49%|███████████████████                    | 766/1568 [02:10<02:16,  5.86it/s]16 02:51:20 Save the image 00460D.png
 49%|███████████████████                    | 767/1568 [02:10<02:09,  6.19it/s]16 02:51:20 Save the image 00460D_flip.png
 49%|███████████████████                    | 768/1568 [02:10<02:11,  6.07it/s]16 02:51:20 Save the image 00461D.png
 49%|███████████████████▏                   | 769/1568 [02:10<02:12,  6.03it/s]16 02:51:20 Save the image 00461D_flip.png
 49%|███████████████████▏                   | 770/1568 [02:10<02:12,  6.00it/s]16 02:51:20 Save the image 00462D.png
 49%|███████████████████▏                   | 771/1568 [02:10<02:14,  5.94it/s]16 02:51:20 Save the image 00462D_flip.png
 49%|███████████████████▏                   | 772/1568 [02:11<02:14,  5.90it/s]16 02:51:21 Save the image 00463D.png
 49%|███████████████████▏                   | 773/1568 [02:11<02:15,  5.87it/s]16 02:51:21 Save the image 00463D_flip.png
 49%|███████████████████▎                   | 774/1568 [02:11<02:16,  5.84it/s]16 02:51:21 Save the image 00464D.png
 49%|███████████████████▎                   | 775/1568 [02:11<02:08,  6.16it/s]16 02:51:21 Save the image 00464D_flip.png
 49%|███████████████████▎                   | 776/1568 [02:11<02:10,  6.06it/s]16 02:51:21 Save the image 00465D.png
 50%|███████████████████▎                   | 777/1568 [02:11<02:11,  6.02it/s]16 02:51:21 Save the image 00465D_flip.png
 50%|███████████████████▎                   | 778/1568 [02:12<02:12,  5.98it/s]16 02:51:22 Save the image 00466D.png
 50%|███████████████████▍                   | 779/1568 [02:12<02:13,  5.90it/s]16 02:51:22 Save the image 00466D_flip.png
 50%|███████████████████▍                   | 780/1568 [02:12<02:14,  5.87it/s]16 02:51:22 Save the image 00478D.png
 50%|███████████████████▍                   | 781/1568 [02:12<02:13,  5.89it/s]16 02:51:22 Save the image 00478D_flip.png
 50%|███████████████████▍                   | 782/1568 [02:12<02:14,  5.85it/s]16 02:51:22 Save the image 00479D.png
 50%|███████████████████▍                   | 783/1568 [02:12<02:06,  6.20it/s]16 02:51:22 Save the image 00479D_flip.png
 50%|███████████████████▌                   | 784/1568 [02:13<02:10,  6.00it/s]16 02:51:23 Save the image 00480D.png
 50%|███████████████████▌                   | 785/1568 [02:13<02:10,  5.98it/s]16 02:51:23 Save the image 00480D_flip.png
 50%|███████████████████▌                   | 786/1568 [02:13<02:11,  5.96it/s]16 02:51:23 Save the image 00481D.png
 50%|███████████████████▌                   | 787/1568 [02:13<02:12,  5.91it/s]16 02:51:23 Save the image 00481D_flip.png
 50%|███████████████████▌                   | 788/1568 [02:13<02:12,  5.88it/s]16 02:51:23 Save the image 00482D.png
 50%|███████████████████▌                   | 789/1568 [02:14<02:12,  5.88it/s]16 02:51:23 Save the image 00482D_flip.png
 50%|███████████████████▋                   | 790/1568 [02:14<02:13,  5.85it/s]16 02:51:24 Save the image 00483D.png
 50%|███████████████████▋                   | 791/1568 [02:14<02:05,  6.19it/s]16 02:51:24 Save the image 00483D_flip.png
 51%|███████████████████▋                   | 792/1568 [02:14<02:08,  6.06it/s]16 02:51:24 Save the image 00484D.png
 51%|███████████████████▋                   | 793/1568 [02:14<02:08,  6.01it/s]16 02:51:24 Save the image 00484D_flip.png
 51%|███████████████████▋                   | 794/1568 [02:14<02:09,  5.98it/s]16 02:51:24 Save the image 00485D.png
 51%|███████████████████▊                   | 795/1568 [02:15<02:10,  5.92it/s]16 02:51:24 Save the image 00485D_flip.png
 51%|███████████████████▊                   | 796/1568 [02:15<02:11,  5.89it/s]16 02:51:25 Save the image 00486D.png
 51%|███████████████████▊                   | 797/1568 [02:15<02:10,  5.89it/s]16 02:51:25 Save the image 00486D_flip.png
 51%|███████████████████▊                   | 798/1568 [02:15<02:11,  5.86it/s]16 02:51:25 Save the image 00487D.png
 51%|███████████████████▊                   | 799/1568 [02:15<02:04,  6.20it/s]16 02:51:25 Save the image 00487D_flip.png
 51%|███████████████████▉                   | 800/1568 [02:15<02:06,  6.07it/s]16 02:51:25 Save the image 00488D.png
 51%|███████████████████▉                   | 801/1568 [02:16<02:07,  6.04it/s]16 02:51:25 Save the image 00488D_flip.png
 51%|███████████████████▉                   | 802/1568 [02:16<02:07,  5.99it/s]16 02:51:26 Save the image 00489D.png
 51%|███████████████████▉                   | 803/1568 [02:16<02:09,  5.91it/s]16 02:51:26 Save the image 00489D_flip.png
 51%|███████████████████▉                   | 804/1568 [02:16<02:09,  5.88it/s]16 02:51:26 Save the image 00490D.png
 51%|████████████████████                   | 805/1568 [02:16<02:10,  5.85it/s]16 02:51:26 Save the image 00490D_flip.png
 51%|████████████████████                   | 806/1568 [02:16<02:10,  5.84it/s]16 02:51:26 Save the image 00491D.png
 51%|████████████████████                   | 807/1568 [02:17<02:03,  6.17it/s]16 02:51:26 Save the image 00491D_flip.png
 52%|████████████████████                   | 808/1568 [02:17<02:06,  5.99it/s]16 02:51:27 Save the image 00492D.png
 52%|████████████████████                   | 809/1568 [02:17<02:08,  5.92it/s]16 02:51:27 Save the image 00492D_flip.png
 52%|████████████████████▏                  | 810/1568 [02:17<02:08,  5.88it/s]16 02:51:27 Save the image 00493D.png
 52%|████████████████████▏                  | 811/1568 [02:17<02:09,  5.85it/s]16 02:51:27 Save the image 00493D_flip.png
 52%|████████████████████▏                  | 812/1568 [02:17<02:11,  5.76it/s]16 02:51:27 Save the image 00494D.png
 52%|████████████████████▏                  | 813/1568 [02:18<02:09,  5.81it/s]16 02:51:28 Save the image 00494D_flip.png
 52%|████████████████████▏                  | 814/1568 [02:18<02:10,  5.78it/s]16 02:51:28 Save the image 00495D.png
 52%|████████████████████▎                  | 815/1568 [02:18<02:04,  6.07it/s]16 02:51:28 Save the image 00495D_flip.png
 52%|████████████████████▎                  | 816/1568 [02:18<02:05,  5.98it/s]16 02:51:28 Save the image 00496D.png
 52%|████████████████████▎                  | 817/1568 [02:18<02:07,  5.89it/s]16 02:51:28 Save the image 00496D_flip.png
 52%|████████████████████▎                  | 818/1568 [02:18<02:07,  5.90it/s]16 02:51:28 Save the image 00497D.png
 52%|████████████████████▎                  | 819/1568 [02:19<02:09,  5.78it/s]16 02:51:29 Save the image 00497D_flip.png
 52%|████████████████████▍                  | 820/1568 [02:19<02:09,  5.77it/s]16 02:51:29 Save the image 00003N.png
 52%|████████████████████▍                  | 821/1568 [02:19<02:10,  5.74it/s]16 02:51:29 Save the image 00003N_flip.png
 52%|████████████████████▍                  | 822/1568 [02:19<02:08,  5.79it/s]16 02:51:29 Save the image 00004N.png
 52%|████████████████████▍                  | 823/1568 [02:19<02:05,  5.96it/s]16 02:51:29 Save the image 00004N_flip.png
 53%|████████████████████▍                  | 824/1568 [02:19<02:06,  5.89it/s]16 02:51:29 Save the image 00005N.png

 53%|████████████████████▌                  | 825/1568 [02:20<02:05,  5.90it/s]16 02:51:30 Save the image 00005N_flip.png
 53%|████████████████████▌                  | 826/1568 [02:20<02:05,  5.90it/s]16 02:51:30 Save the image 00006N.png
 53%|████████████████████▌                  | 827/1568 [02:20<02:06,  5.86it/s]16 02:51:30 Save the image 00006N_flip.png
 53%|████████████████████▌                  | 828/1568 [02:20<02:06,  5.85it/s]16 02:51:30 Save the image 00007N.png
 53%|████████████████████▌                  | 829/1568 [02:20<02:06,  5.84it/s]16 02:51:30 Save the image 00007N_flip.png
 53%|████████████████████▋                  | 830/1568 [02:20<02:06,  5.83it/s]16 02:51:30 Save the image 00008N.png
 53%|████████████████████▋                  | 831/1568 [02:21<01:59,  6.15it/s]16 02:51:31 Save the image 00008N_flip.png
 53%|████████████████████▋                  | 832/1568 [02:21<02:01,  6.04it/s]16 02:51:31 Save the image 00009N.png
 53%|████████████████████▋                  | 833/1568 [02:21<02:02,  6.01it/s]16 02:51:31 Save the image 00009N_flip.png
 53%|████████████████████▋                  | 834/1568 [02:21<02:03,  5.95it/s]16 02:51:31 Save the image 00010N.png
 53%|████████████████████▊                  | 835/1568 [02:21<02:03,  5.91it/s]16 02:51:31 Save the image 00010N_flip.png
 53%|████████████████████▊                  | 836/1568 [02:21<02:04,  5.88it/s]16 02:51:31 Save the image 00011N.png
 53%|████████████████████▊                  | 837/1568 [02:22<02:04,  5.87it/s]16 02:51:32 Save the image 00011N_flip.png
 53%|████████████████████▊                  | 838/1568 [02:22<02:04,  5.85it/s]16 02:51:32 Save the image 00012N.png
 54%|████████████████████▊                  | 839/1568 [02:22<01:57,  6.18it/s]16 02:51:32 Save the image 00012N_flip.png
 54%|████████████████████▉                  | 840/1568 [02:22<02:00,  6.06it/s]16 02:51:32 Save the image 00013N.png
 54%|████████████████████▉                  | 841/1568 [02:22<02:00,  6.03it/s]16 02:51:32 Save the image 00013N_flip.png
 54%|████████████████████▉                  | 842/1568 [02:22<02:02,  5.91it/s]16 02:51:32 Save the image 00014N.png
 54%|████████████████████▉                  | 843/1568 [02:23<02:03,  5.86it/s]16 02:51:33 Save the image 00014N_flip.png
 54%|████████████████████▉                  | 844/1568 [02:23<02:04,  5.84it/s]16 02:51:33 Save the image 00015N.png
 54%|█████████████████████                  | 845/1568 [02:23<02:03,  5.84it/s]16 02:51:33 Save the image 00015N_flip.png
 54%|█████████████████████                  | 846/1568 [02:23<02:03,  5.85it/s]16 02:51:33 Save the image 00016N.png
 54%|█████████████████████                  | 847/1568 [02:23<01:56,  6.20it/s]16 02:51:33 Save the image 00016N_flip.png
 54%|█████████████████████                  | 848/1568 [02:23<01:58,  6.07it/s]16 02:51:33 Save the image 00017N.png
 54%|█████████████████████                  | 849/1568 [02:24<01:59,  6.03it/s]16 02:51:34 Save the image 00017N_flip.png
 54%|█████████████████████▏                 | 850/1568 [02:24<01:59,  6.00it/s]16 02:51:34 Save the image 00018N.png
 54%|█████████████████████▏                 | 851/1568 [02:24<02:00,  5.94it/s]16 02:51:34 Save the image 00018N_flip.png
 54%|█████████████████████▏                 | 852/1568 [02:24<02:01,  5.89it/s]16 02:51:34 Save the image 00019N.png
 54%|█████████████████████▏                 | 853/1568 [02:24<02:01,  5.89it/s]16 02:51:34 Save the image 00019N_flip.png
 54%|█████████████████████▏                 | 854/1568 [02:24<02:01,  5.88it/s]16 02:51:34 Save the image 00020N.png
 55%|█████████████████████▎                 | 855/1568 [02:25<01:54,  6.25it/s]16 02:51:35 Save the image 00020N_flip.png
 55%|█████████████████████▎                 | 856/1568 [02:25<01:56,  6.13it/s]16 02:51:35 Save the image 00021N.png
 55%|█████████████████████▎                 | 857/1568 [02:25<01:57,  6.06it/s]16 02:51:35 Save the image 00021N_flip.png
 55%|█████████████████████▎                 | 858/1568 [02:25<01:57,  6.02it/s]16 02:51:35 Save the image 00022N.png
 55%|█████████████████████▎                 | 859/1568 [02:25<01:58,  5.98it/s]16 02:51:35 Save the image 00022N_flip.png
 55%|█████████████████████▍                 | 860/1568 [02:25<01:59,  5.95it/s]16 02:51:35 Save the image 00023N.png
 55%|█████████████████████▍                 | 861/1568 [02:26<01:58,  5.95it/s]16 02:51:36 Save the image 00023N_flip.png
 55%|█████████████████████▍                 | 862/1568 [02:26<01:59,  5.90it/s]16 02:51:36 Save the image 00024N.png
 55%|█████████████████████▍                 | 863/1568 [02:26<01:52,  6.26it/s]16 02:51:36 Save the image 00024N_flip.png
 55%|█████████████████████▍                 | 864/1568 [02:26<01:55,  6.11it/s]16 02:51:36 Save the image 00025N.png
 55%|█████████████████████▌                 | 865/1568 [02:26<01:55,  6.06it/s]16 02:51:36 Save the image 00025N_flip.png
 55%|█████████████████████▌                 | 866/1568 [02:26<01:56,  6.02it/s]16 02:51:36 Save the image 00026N.png
 55%|█████████████████████▌                 | 867/1568 [02:27<01:57,  5.95it/s]16 02:51:37 Save the image 00026N_flip.png
 55%|█████████████████████▌                 | 868/1568 [02:27<01:58,  5.91it/s]16 02:51:37 Save the image 00027N.png
 55%|█████████████████████▌                 | 869/1568 [02:27<01:58,  5.91it/s]16 02:51:37 Save the image 00027N_flip.png
 55%|█████████████████████▋                 | 870/1568 [02:27<01:58,  5.89it/s]16 02:51:37 Save the image 00028N.png
 56%|█████████████████████▋                 | 871/1568 [02:27<01:51,  6.27it/s]16 02:51:37 Save the image 00028N_flip.png
 56%|█████████████████████▋                 | 872/1568 [02:27<01:53,  6.12it/s]16 02:51:37 Save the image 00029N.png
 56%|█████████████████████▋                 | 873/1568 [02:28<01:54,  6.07it/s]16 02:51:38 Save the image 00029N_flip.png
 56%|█████████████████████▋                 | 874/1568 [02:28<01:55,  6.02it/s]16 02:51:38 Save the image 00030N.png
 56%|█████████████████████▊                 | 875/1568 [02:28<01:56,  5.97it/s]16 02:51:38 Save the image 00030N_flip.png
 56%|█████████████████████▊                 | 876/1568 [02:28<01:56,  5.94it/s]16 02:51:38 Save the image 00031N.png
 56%|█████████████████████▊                 | 877/1568 [02:28<01:56,  5.91it/s]16 02:51:38 Save the image 00031N_flip.png
 56%|█████████████████████▊                 | 878/1568 [02:28<01:55,  5.98it/s]16 02:51:38 Save the image 00032N.png
 56%|█████████████████████▊                 | 879/1568 [02:29<01:51,  6.16it/s]16 02:51:39 Save the image 00032N_flip.png
 56%|█████████████████████▉                 | 880/1568 [02:29<01:53,  6.06it/s]16 02:51:39 Save the image 00033N.png
 56%|█████████████████████▉                 | 881/1568 [02:29<01:54,  6.02it/s]16 02:51:39 Save the image 00033N_flip.png
 56%|█████████████████████▉                 | 882/1568 [02:29<01:54,  5.99it/s]16 02:51:39 Save the image 00034N.png
 56%|█████████████████████▉                 | 883/1568 [02:29<01:55,  5.92it/s]16 02:51:39 Save the image 00034N_flip.png
 56%|█████████████████████▉                 | 884/1568 [02:29<01:56,  5.89it/s]16 02:51:39 Save the image 00035N.png
 56%|██████████████████████                 | 885/1568 [02:30<01:56,  5.87it/s]16 02:51:40 Save the image 00035N_flip.png
 57%|██████████████████████                 | 886/1568 [02:30<01:54,  5.93it/s]16 02:51:40 Save the image 00036N.png
 57%|██████████████████████                 | 887/1568 [02:30<01:50,  6.15it/s]16 02:51:40 Save the image 00036N_flip.png
 57%|██████████████████████                 | 888/1568 [02:30<01:52,  6.06it/s]16 02:51:40 Save the image 00037N.png

 57%|██████████████████████                 | 889/1568 [02:30<01:52,  6.01it/s]16 02:51:40 Save the image 00037N_flip.png
 57%|██████████████████████▏                | 890/1568 [02:30<01:54,  5.95it/s]16 02:51:40 Save the image 00038N.png
 57%|██████████████████████▏                | 891/1568 [02:31<01:54,  5.89it/s]16 02:51:41 Save the image 00038N_flip.png
 57%|██████████████████████▏                | 892/1568 [02:31<01:55,  5.84it/s]16 02:51:41 Save the image 00039N.png
 57%|██████████████████████▏                | 893/1568 [02:31<01:55,  5.85it/s]16 02:51:41 Save the image 00039N_flip.png
 57%|██████████████████████▏                | 894/1568 [02:31<01:55,  5.85it/s]16 02:51:41 Save the image 00040N.png
 57%|██████████████████████▎                | 895/1568 [02:31<01:48,  6.20it/s]16 02:51:41 Save the image 00040N_flip.png
 57%|██████████████████████▎                | 896/1568 [02:31<01:50,  6.08it/s]16 02:51:41 Save the image 00041N.png
 57%|██████████████████████▎                | 897/1568 [02:32<01:51,  6.03it/s]16 02:51:42 Save the image 00041N_flip.png
 57%|██████████████████████▎                | 898/1568 [02:32<01:52,  5.98it/s]16 02:51:42 Save the image 00042N.png
 57%|██████████████████████▎                | 899/1568 [02:32<01:53,  5.91it/s]16 02:51:42 Save the image 00042N_flip.png
 57%|██████████████████████▍                | 900/1568 [02:32<01:53,  5.87it/s]16 02:51:42 Save the image 00043N.png
 57%|██████████████████████▍                | 901/1568 [02:32<01:53,  5.85it/s]16 02:51:42 Save the image 00043N_flip.png
 58%|██████████████████████▍                | 902/1568 [02:32<01:52,  5.90it/s]16 02:51:42 Save the image 00044N.png
 58%|██████████████████████▍                | 903/1568 [02:33<01:51,  5.94it/s]16 02:51:43 Save the image 00044N_flip.png
 58%|██████████████████████▍                | 904/1568 [02:33<01:53,  5.83it/s]16 02:51:43 Save the image 00047N.png
 58%|██████████████████████▌                | 905/1568 [02:33<01:53,  5.84it/s]16 02:51:43 Save the image 00047N_flip.png
 58%|██████████████████████▌                | 906/1568 [02:33<01:53,  5.83it/s]16 02:51:43 Save the image 00048N.png
 58%|██████████████████████▌                | 907/1568 [02:33<01:54,  5.79it/s]16 02:51:43 Save the image 00048N_flip.png
 58%|██████████████████████▌                | 908/1568 [02:34<01:54,  5.77it/s]16 02:51:43 Save the image 00049N.png
 58%|██████████████████████▌                | 909/1568 [02:34<01:54,  5.74it/s]16 02:51:44 Save the image 00049N_flip.png
 58%|██████████████████████▋                | 910/1568 [02:34<01:53,  5.81it/s]16 02:51:44 Save the image 00050N.png
 58%|██████████████████████▋                | 911/1568 [02:34<01:49,  6.01it/s]16 02:51:44 Save the image 00050N_flip.png
 58%|██████████████████████▋                | 912/1568 [02:34<01:51,  5.87it/s]16 02:51:44 Save the image 00051N.png
 58%|██████████████████████▋                | 913/1568 [02:34<01:51,  5.87it/s]16 02:51:44 Save the image 00051N_flip.png
 58%|██████████████████████▋                | 914/1568 [02:35<01:50,  5.90it/s]16 02:51:44 Save the image 00052N.png
 58%|██████████████████████▊                | 915/1568 [02:35<01:51,  5.87it/s]16 02:51:45 Save the image 00052N_flip.png
 58%|██████████████████████▊                | 916/1568 [02:35<01:50,  5.88it/s]16 02:51:45 Save the image 00053N.png
 58%|██████████████████████▊                | 917/1568 [02:35<01:51,  5.82it/s]16 02:51:45 Save the image 00053N_flip.png
 59%|██████████████████████▊                | 918/1568 [02:35<01:50,  5.87it/s]16 02:51:45 Save the image 00054N.png
 59%|██████████████████████▊                | 919/1568 [02:35<01:49,  5.93it/s]16 02:51:45 Save the image 00054N_flip.png
 59%|██████████████████████▉                | 920/1568 [02:36<01:49,  5.90it/s]16 02:51:45 Save the image 00678N.png
 59%|██████████████████████▉                | 921/1568 [02:36<01:49,  5.91it/s]16 02:51:46 Save the image 00678N_flip.png
 59%|██████████████████████▉                | 922/1568 [02:36<01:50,  5.87it/s]16 02:51:46 Save the image 00679N.png
 59%|██████████████████████▉                | 923/1568 [02:36<01:50,  5.84it/s]16 02:51:46 Save the image 00679N_flip.png
 59%|██████████████████████▉                | 924/1568 [02:36<01:49,  5.86it/s]16 02:51:46 Save the image 00680N.png
 59%|███████████████████████                | 925/1568 [02:36<01:50,  5.83it/s]16 02:51:46 Save the image 00680N_flip.png
 59%|███████████████████████                | 926/1568 [02:37<01:48,  5.90it/s]16 02:51:47 Save the image 00681N.png
 59%|███████████████████████                | 927/1568 [02:37<01:47,  5.98it/s]16 02:51:47 Save the image 00681N_flip.png
 59%|███████████████████████                | 928/1568 [02:37<01:47,  5.93it/s]16 02:51:47 Save the image 00682N.png
 59%|███████████████████████                | 929/1568 [02:37<01:47,  5.93it/s]16 02:51:47 Save the image 00682N_flip.png
 59%|███████████████████████▏               | 930/1568 [02:37<01:48,  5.89it/s]16 02:51:47 Save the image 00683N.png
 59%|███████████████████████▏               | 931/1568 [02:37<01:48,  5.85it/s]16 02:51:47 Save the image 00683N_flip.png
 59%|███████████████████████▏               | 932/1568 [02:38<01:48,  5.84it/s]16 02:51:48 Save the image 00684N.png
 60%|███████████████████████▏               | 933/1568 [02:38<01:50,  5.76it/s]16 02:51:48 Save the image 00684N_flip.png
 60%|███████████████████████▏               | 934/1568 [02:38<01:50,  5.76it/s]16 02:51:48 Save the image 00685N.png
 60%|███████████████████████▎               | 935/1568 [02:38<01:43,  6.13it/s]16 02:51:48 Save the image 00685N_flip.png
 60%|███████████████████████▎               | 936/1568 [02:38<01:45,  6.02it/s]16 02:51:48 Save the image 00686N.png
 60%|███████████████████████▎               | 937/1568 [02:38<01:45,  6.01it/s]16 02:51:48 Save the image 00686N_flip.png
 60%|███████████████████████▎               | 938/1568 [02:39<01:45,  5.97it/s]16 02:51:49 Save the image 00687N.png
 60%|███████████████████████▎               | 939/1568 [02:39<01:46,  5.91it/s]16 02:51:49 Save the image 00687N_flip.png
 60%|███████████████████████▍               | 940/1568 [02:39<01:46,  5.88it/s]16 02:51:49 Save the image 00688N.png
 60%|███████████████████████▍               | 941/1568 [02:39<01:47,  5.86it/s]16 02:51:49 Save the image 00688N_flip.png
 60%|███████████████████████▍               | 942/1568 [02:39<01:46,  5.85it/s]16 02:51:49 Save the image 00689N.png
 60%|███████████████████████▍               | 943/1568 [02:39<01:40,  6.20it/s]16 02:51:49 Save the image 00689N_flip.png
 60%|███████████████████████▍               | 944/1568 [02:40<01:42,  6.07it/s]16 02:51:50 Save the image 00690N.png
 60%|███████████████████████▌               | 945/1568 [02:40<01:43,  6.03it/s]16 02:51:50 Save the image 00690N_flip.png
 60%|███████████████████████▌               | 946/1568 [02:40<01:43,  5.99it/s]16 02:51:50 Save the image 00691N.png
 60%|███████████████████████▌               | 947/1568 [02:40<01:44,  5.93it/s]16 02:51:50 Save the image 00691N_flip.png
 60%|███████████████████████▌               | 948/1568 [02:40<01:45,  5.89it/s]16 02:51:50 Save the image 00692N.png
 61%|███████████████████████▌               | 949/1568 [02:40<01:45,  5.89it/s]16 02:51:50 Save the image 00692N_flip.png
 61%|███████████████████████▋               | 950/1568 [02:41<01:44,  5.89it/s]16 02:51:51 Save the image 00693N.png
 61%|███████████████████████▋               | 951/1568 [02:41<01:39,  6.22it/s]16 02:51:51 Save the image 00693N_flip.png
 61%|███████████████████████▋               | 952/1568 [02:41<01:41,  6.09it/s]16 02:51:51 Save the image 00694N.png

 61%|███████████████████████▋               | 953/1568 [02:41<01:41,  6.04it/s]16 02:51:51 Save the image 00694N_flip.png
 61%|███████████████████████▋               | 954/1568 [02:41<01:42,  6.00it/s]16 02:51:51 Save the image 00695N.png
 61%|███████████████████████▊               | 955/1568 [02:41<01:43,  5.93it/s]16 02:51:51 Save the image 00695N_flip.png
 61%|███████████████████████▊               | 956/1568 [02:42<01:43,  5.89it/s]16 02:51:52 Save the image 00696N.png
 61%|███████████████████████▊               | 957/1568 [02:42<01:43,  5.89it/s]16 02:51:52 Save the image 00696N_flip.png
 61%|███████████████████████▊               | 958/1568 [02:42<01:43,  5.87it/s]16 02:51:52 Save the image 00697N.png
 61%|███████████████████████▊               | 959/1568 [02:42<01:37,  6.24it/s]16 02:51:52 Save the image 00697N_flip.png
 61%|███████████████████████▉               | 960/1568 [02:42<01:39,  6.09it/s]16 02:51:52 Save the image 00698N.png
 61%|███████████████████████▉               | 961/1568 [02:42<01:40,  6.05it/s]16 02:51:52 Save the image 00698N_flip.png
 61%|███████████████████████▉               | 962/1568 [02:43<01:40,  6.02it/s]16 02:51:53 Save the image 00699N.png
 61%|███████████████████████▉               | 963/1568 [02:43<01:42,  5.88it/s]16 02:51:53 Save the image 00699N_flip.png
 61%|███████████████████████▉               | 964/1568 [02:43<01:43,  5.85it/s]16 02:51:53 Save the image 00700N.png
 62%|████████████████████████               | 965/1568 [02:43<01:42,  5.86it/s]16 02:51:53 Save the image 00700N_flip.png
 62%|████████████████████████               | 966/1568 [02:43<01:42,  5.85it/s]16 02:51:53 Save the image 00701N.png
 62%|████████████████████████               | 967/1568 [02:43<01:36,  6.20it/s]16 02:51:53 Save the image 00701N_flip.png
 62%|████████████████████████               | 968/1568 [02:44<01:38,  6.07it/s]16 02:51:54 Save the image 00702N.png
 62%|████████████████████████               | 969/1568 [02:44<01:39,  6.03it/s]16 02:51:54 Save the image 00702N_flip.png
 62%|████████████████████████▏              | 970/1568 [02:44<01:40,  5.95it/s]16 02:51:54 Save the image 00703N.png
 62%|████████████████████████▏              | 971/1568 [02:44<01:41,  5.91it/s]16 02:51:54 Save the image 00703N_flip.png
 62%|████████████████████████▏              | 972/1568 [02:44<01:40,  5.92it/s]16 02:51:54 Save the image 00704N.png
 62%|████████████████████████▏              | 973/1568 [02:44<01:40,  5.91it/s]16 02:51:54 Save the image 00704N_flip.png
 62%|████████████████████████▏              | 974/1568 [02:45<01:40,  5.88it/s]16 02:51:55 Save the image 00705N.png
 62%|████████████████████████▎              | 975/1568 [02:45<01:35,  6.24it/s]16 02:51:55 Save the image 00705N_flip.png
 62%|████████████████████████▎              | 976/1568 [02:45<01:37,  6.10it/s]16 02:51:55 Save the image 00706N.png
 62%|████████████████████████▎              | 977/1568 [02:45<01:37,  6.06it/s]16 02:51:55 Save the image 00706N_flip.png
 62%|████████████████████████▎              | 978/1568 [02:45<01:38,  6.00it/s]16 02:51:55 Save the image 00707N.png
 62%|████████████████████████▎              | 979/1568 [02:45<01:39,  5.93it/s]16 02:51:55 Save the image 00707N_flip.png
 62%|████████████████████████▍              | 980/1568 [02:46<01:39,  5.89it/s]16 02:51:56 Save the image 00708N.png
 63%|████████████████████████▍              | 981/1568 [02:46<01:39,  5.88it/s]16 02:51:56 Save the image 00708N_flip.png
 63%|████████████████████████▍              | 982/1568 [02:46<01:39,  5.87it/s]16 02:51:56 Save the image 00709N.png
 63%|████████████████████████▍              | 983/1568 [02:46<01:34,  6.22it/s]16 02:51:56 Save the image 00709N_flip.png
 63%|████████████████████████▍              | 984/1568 [02:46<01:36,  6.08it/s]16 02:51:56 Save the image 00710N.png
 63%|████████████████████████▍              | 985/1568 [02:46<01:36,  6.04it/s]16 02:51:56 Save the image 00710N_flip.png
 63%|████████████████████████▌              | 986/1568 [02:47<01:36,  6.01it/s]16 02:51:57 Save the image 00711N.png
 63%|████████████████████████▌              | 987/1568 [02:47<01:37,  5.94it/s]16 02:51:57 Save the image 00711N_flip.png
 63%|████████████████████████▌              | 988/1568 [02:47<01:38,  5.89it/s]16 02:51:57 Save the image 00712N.png
 63%|████████████████████████▌              | 989/1568 [02:47<01:38,  5.87it/s]16 02:51:57 Save the image 00712N_flip.png
 63%|████████████████████████▌              | 990/1568 [02:47<01:38,  5.85it/s]16 02:51:57 Save the image 00713N.png
 63%|████████████████████████▋              | 991/1568 [02:47<01:33,  6.20it/s]16 02:51:57 Save the image 00713N_flip.png
 63%|████████████████████████▋              | 992/1568 [02:48<01:34,  6.07it/s]16 02:51:58 Save the image 00714N.png
 63%|████████████████████████▋              | 993/1568 [02:48<01:36,  5.97it/s]16 02:51:58 Save the image 00714N_flip.png
 63%|████████████████████████▋              | 994/1568 [02:48<01:36,  5.95it/s]16 02:51:58 Save the image 00715N.png
 63%|████████████████████████▋              | 995/1568 [02:48<01:37,  5.90it/s]16 02:51:58 Save the image 00715N_flip.png
 64%|████████████████████████▊              | 996/1568 [02:48<01:36,  5.90it/s]16 02:51:58 Save the image 00716N.png
 64%|████████████████████████▊              | 997/1568 [02:48<01:36,  5.90it/s]16 02:51:58 Save the image 00716N_flip.png
 64%|████████████████████████▊              | 998/1568 [02:49<01:36,  5.88it/s]16 02:51:59 Save the image 00717N.png
 64%|████████████████████████▊              | 999/1568 [02:49<01:31,  6.25it/s]16 02:51:59 Save the image 00717N_flip.png
 64%|████████████████████████▏             | 1000/1568 [02:49<01:32,  6.12it/s]16 02:51:59 Save the image 00718N.png
 64%|████████████████████████▎             | 1001/1568 [02:49<01:33,  6.07it/s]16 02:51:59 Save the image 00718N_flip.png
 64%|████████████████████████▎             | 1002/1568 [02:49<01:33,  6.02it/s]16 02:51:59 Save the image 00719N.png
 64%|████████████████████████▎             | 1003/1568 [02:49<01:34,  5.96it/s]16 02:51:59 Save the image 00719N_flip.png
 64%|████████████████████████▎             | 1004/1568 [02:50<01:35,  5.93it/s]16 02:52:00 Save the image 00720N.png
 64%|████████████████████████▎             | 1005/1568 [02:50<01:35,  5.91it/s]16 02:52:00 Save the image 00720N_flip.png
 64%|████████████████████████▍             | 1006/1568 [02:50<01:35,  5.88it/s]16 02:52:00 Save the image 00721N.png
 64%|████████████████████████▍             | 1007/1568 [02:50<01:30,  6.22it/s]16 02:52:00 Save the image 00721N_flip.png
 64%|████████████████████████▍             | 1008/1568 [02:50<01:31,  6.10it/s]16 02:52:00 Save the image 00722N.png
 64%|████████████████████████▍             | 1009/1568 [02:50<01:32,  6.06it/s]16 02:52:00 Save the image 00722N_flip.png
 64%|████████████████████████▍             | 1010/1568 [02:51<01:32,  6.02it/s]16 02:52:01 Save the image 00723N.png
 64%|████████████████████████▌             | 1011/1568 [02:51<01:33,  5.95it/s]16 02:52:01 Save the image 00723N_flip.png
 65%|████████████████████████▌             | 1012/1568 [02:51<01:34,  5.91it/s]16 02:52:01 Save the image 00724N.png
 65%|████████████████████████▌             | 1013/1568 [02:51<01:34,  5.90it/s]16 02:52:01 Save the image 00724N_flip.png
 65%|████████████████████████▌             | 1014/1568 [02:51<01:33,  5.90it/s]16 02:52:01 Save the image 00725N.png
 65%|████████████████████████▌             | 1015/1568 [02:51<01:28,  6.26it/s]16 02:52:01 Save the image 00725N_flip.png
 65%|████████████████████████▌             | 1016/1568 [02:52<01:30,  6.11it/s]16 02:52:02 Save the image 00726N.png

 65%|████████████████████████▋             | 1017/1568 [02:52<01:30,  6.06it/s]16 02:52:02 Save the image 00726N_flip.png
 65%|████████████████████████▋             | 1018/1568 [02:52<01:31,  6.02it/s]16 02:52:02 Save the image 00727N.png
 65%|████████████████████████▋             | 1019/1568 [02:52<01:32,  5.95it/s]16 02:52:02 Save the image 00727N_flip.png
 65%|████████████████████████▋             | 1020/1568 [02:52<01:32,  5.91it/s]16 02:52:02 Save the image 00728N.png
 65%|████████████████████████▋             | 1021/1568 [02:52<01:33,  5.88it/s]16 02:52:02 Save the image 00728N_flip.png
 65%|████████████████████████▊             | 1022/1568 [02:53<01:33,  5.87it/s]16 02:52:03 Save the image 00729N.png
 65%|████████████████████████▊             | 1023/1568 [02:53<01:27,  6.25it/s]16 02:52:03 Save the image 00729N_flip.png
 65%|████████████████████████▊             | 1024/1568 [02:53<01:30,  6.04it/s]16 02:52:03 Save the image 00730N.png
 65%|████████████████████████▊             | 1025/1568 [02:53<01:30,  6.01it/s]16 02:52:03 Save the image 00730N_flip.png
 65%|████████████████████████▊             | 1026/1568 [02:53<01:30,  5.98it/s]16 02:52:03 Save the image 00731N.png
 65%|████████████████████████▉             | 1027/1568 [02:53<01:31,  5.92it/s]16 02:52:03 Save the image 00731N_flip.png
 66%|████████████████████████▉             | 1028/1568 [02:54<01:31,  5.88it/s]16 02:52:04 Save the image 00732N.png
 66%|████████████████████████▉             | 1029/1568 [02:54<01:31,  5.86it/s]16 02:52:04 Save the image 00732N_flip.png
 66%|████████████████████████▉             | 1030/1568 [02:54<01:31,  5.86it/s]16 02:52:04 Save the image 00733N.png
 66%|████████████████████████▉             | 1031/1568 [02:54<01:26,  6.22it/s]16 02:52:04 Save the image 00733N_flip.png
 66%|█████████████████████████             | 1032/1568 [02:54<01:28,  6.08it/s]16 02:52:04 Save the image 00734N.png
 66%|█████████████████████████             | 1033/1568 [02:54<01:28,  6.04it/s]16 02:52:04 Save the image 00734N_flip.png
 66%|█████████████████████████             | 1034/1568 [02:55<01:28,  6.04it/s]16 02:52:05 Save the image 00735N.png
 66%|█████████████████████████             | 1035/1568 [02:55<01:29,  5.97it/s]16 02:52:05 Save the image 00735N_flip.png
 66%|█████████████████████████             | 1036/1568 [02:55<01:29,  5.93it/s]16 02:52:05 Save the image 00736N.png
 66%|█████████████████████████▏            | 1037/1568 [02:55<01:29,  5.93it/s]16 02:52:05 Save the image 00736N_flip.png
 66%|█████████████████████████▏            | 1038/1568 [02:55<01:29,  5.92it/s]16 02:52:05 Save the image 00737N.png
 66%|█████████████████████████▏            | 1039/1568 [02:55<01:24,  6.27it/s]16 02:52:05 Save the image 00737N_flip.png
 66%|█████████████████████████▏            | 1040/1568 [02:56<01:26,  6.12it/s]16 02:52:06 Save the image 00738N.png
 66%|█████████████████████████▏            | 1041/1568 [02:56<01:26,  6.06it/s]16 02:52:06 Save the image 00738N_flip.png
 66%|█████████████████████████▎            | 1042/1568 [02:56<01:27,  6.02it/s]16 02:52:06 Save the image 00739N.png
 67%|█████████████████████████▎            | 1043/1568 [02:56<01:28,  5.95it/s]16 02:52:06 Save the image 00739N_flip.png
 67%|█████████████████████████▎            | 1044/1568 [02:56<01:28,  5.90it/s]16 02:52:06 Save the image 00740N.png
 67%|█████████████████████████▎            | 1045/1568 [02:56<01:28,  5.89it/s]16 02:52:06 Save the image 00740N_flip.png
 67%|█████████████████████████▎            | 1046/1568 [02:57<01:29,  5.86it/s]16 02:52:07 Save the image 00741N.png
 67%|█████████████████████████▎            | 1047/1568 [02:57<01:23,  6.21it/s]16 02:52:07 Save the image 00741N_flip.png
 67%|█████████████████████████▍            | 1048/1568 [02:57<01:25,  6.08it/s]16 02:52:07 Save the image 00742N.png
 67%|█████████████████████████▍            | 1049/1568 [02:57<01:25,  6.04it/s]16 02:52:07 Save the image 00742N_flip.png
 67%|█████████████████████████▍            | 1050/1568 [02:57<01:26,  6.01it/s]16 02:52:07 Save the image 00743N.png
 67%|█████████████████████████▍            | 1051/1568 [02:57<01:27,  5.94it/s]16 02:52:07 Save the image 00743N_flip.png
 67%|█████████████████████████▍            | 1052/1568 [02:58<01:27,  5.90it/s]16 02:52:08 Save the image 00744N.png
 67%|█████████████████████████▌            | 1053/1568 [02:58<01:27,  5.91it/s]16 02:52:08 Save the image 00744N_flip.png
 67%|█████████████████████████▌            | 1054/1568 [02:58<01:27,  5.89it/s]16 02:52:08 Save the image 00745N.png
 67%|█████████████████████████▌            | 1055/1568 [02:58<01:22,  6.24it/s]16 02:52:08 Save the image 00745N_flip.png
 67%|█████████████████████████▌            | 1056/1568 [02:58<01:23,  6.12it/s]16 02:52:08 Save the image 00746N.png
 67%|█████████████████████████▌            | 1057/1568 [02:58<01:24,  6.06it/s]16 02:52:08 Save the image 00746N_flip.png
 67%|█████████████████████████▋            | 1058/1568 [02:59<01:24,  6.01it/s]16 02:52:09 Save the image 00747N.png
 68%|█████████████████████████▋            | 1059/1568 [02:59<01:25,  5.95it/s]16 02:52:09 Save the image 00747N_flip.png
 68%|█████████████████████████▋            | 1060/1568 [02:59<01:26,  5.90it/s]16 02:52:09 Save the image 00748N.png
 68%|█████████████████████████▋            | 1061/1568 [02:59<01:25,  5.90it/s]16 02:52:09 Save the image 00748N_flip.png
 68%|█████████████████████████▋            | 1062/1568 [02:59<01:26,  5.87it/s]16 02:52:09 Save the image 00749N.png
 68%|█████████████████████████▊            | 1063/1568 [02:59<01:20,  6.24it/s]16 02:52:09 Save the image 00749N_flip.png
 68%|█████████████████████████▊            | 1064/1568 [03:00<01:22,  6.10it/s]16 02:52:10 Save the image 00750N.png
 68%|█████████████████████████▊            | 1065/1568 [03:00<01:23,  6.06it/s]16 02:52:10 Save the image 00750N_flip.png
 68%|█████████████████████████▊            | 1066/1568 [03:00<01:23,  6.02it/s]16 02:52:10 Save the image 00751N.png
 68%|█████████████████████████▊            | 1067/1568 [03:00<01:24,  5.95it/s]16 02:52:10 Save the image 00751N_flip.png
 68%|█████████████████████████▉            | 1068/1568 [03:00<01:24,  5.91it/s]16 02:52:10 Save the image 00752N.png
 68%|█████████████████████████▉            | 1069/1568 [03:00<01:25,  5.87it/s]16 02:52:10 Save the image 00752N_flip.png
 68%|█████████████████████████▉            | 1070/1568 [03:01<01:25,  5.85it/s]16 02:52:11 Save the image 00753N.png
 68%|█████████████████████████▉            | 1071/1568 [03:01<01:19,  6.22it/s]16 02:52:11 Save the image 00753N_flip.png
 68%|█████████████████████████▉            | 1072/1568 [03:01<01:21,  6.08it/s]16 02:52:11 Save the image 00754N.png
 68%|██████████████████████████            | 1073/1568 [03:01<01:21,  6.04it/s]16 02:52:11 Save the image 00754N_flip.png
 68%|██████████████████████████            | 1074/1568 [03:01<01:22,  6.00it/s]16 02:52:11 Save the image 00755N.png
 69%|██████████████████████████            | 1075/1568 [03:01<01:22,  5.94it/s]16 02:52:11 Save the image 00755N_flip.png
 69%|██████████████████████████            | 1076/1568 [03:02<01:23,  5.90it/s]16 02:52:12 Save the image 00756N.png
 69%|██████████████████████████            | 1077/1568 [03:02<01:23,  5.90it/s]16 02:52:12 Save the image 00756N_flip.png
 69%|██████████████████████████▏           | 1078/1568 [03:02<01:23,  5.88it/s]16 02:52:12 Save the image 00757N.png
 69%|██████████████████████████▏           | 1079/1568 [03:02<01:18,  6.25it/s]16 02:52:12 Save the image 00757N_flip.png
 69%|██████████████████████████▏           | 1080/1568 [03:02<01:20,  6.10it/s]16 02:52:12 Save the image 00758N.png

 69%|██████████████████████████▏           | 1081/1568 [03:02<01:20,  6.03it/s]16 02:52:12 Save the image 00758N_flip.png
 69%|██████████████████████████▏           | 1082/1568 [03:03<01:21,  6.00it/s]16 02:52:13 Save the image 00759N.png
 69%|██████████████████████████▏           | 1083/1568 [03:03<01:21,  5.94it/s]16 02:52:13 Save the image 00759N_flip.png
 69%|██████████████████████████▎           | 1084/1568 [03:03<01:22,  5.90it/s]16 02:52:13 Save the image 00760N.png
 69%|██████████████████████████▎           | 1085/1568 [03:03<01:21,  5.92it/s]16 02:52:13 Save the image 00760N_flip.png
 69%|██████████████████████████▎           | 1086/1568 [03:03<01:22,  5.88it/s]16 02:52:13 Save the image 00761N.png
 69%|██████████████████████████▎           | 1087/1568 [03:03<01:17,  6.23it/s]16 02:52:13 Save the image 00761N_flip.png
 69%|██████████████████████████▎           | 1088/1568 [03:04<01:18,  6.09it/s]16 02:52:14 Save the image 00762N.png
 69%|██████████████████████████▍           | 1089/1568 [03:04<01:19,  6.04it/s]16 02:52:14 Save the image 00762N_flip.png
 70%|██████████████████████████▍           | 1090/1568 [03:04<01:19,  6.00it/s]16 02:52:14 Save the image 00763N.png
 70%|██████████████████████████▍           | 1091/1568 [03:04<01:20,  5.95it/s]16 02:52:14 Save the image 00763N_flip.png
 70%|██████████████████████████▍           | 1092/1568 [03:04<01:20,  5.92it/s]16 02:52:14 Save the image 00764N.png
 70%|██████████████████████████▍           | 1093/1568 [03:04<01:20,  5.89it/s]16 02:52:14 Save the image 00764N_flip.png
 70%|██████████████████████████▌           | 1094/1568 [03:05<01:20,  5.88it/s]16 02:52:15 Save the image 00765N.png
 70%|██████████████████████████▌           | 1095/1568 [03:05<01:17,  6.11it/s]16 02:52:15 Save the image 00765N_flip.png
 70%|██████████████████████████▌           | 1096/1568 [03:05<01:18,  6.00it/s]16 02:52:15 Save the image 00766N.png
 70%|██████████████████████████▌           | 1097/1568 [03:05<01:18,  5.99it/s]16 02:52:15 Save the image 00766N_flip.png
 70%|██████████████████████████▌           | 1098/1568 [03:05<01:18,  5.97it/s]16 02:52:15 Save the image 00767N.png
 70%|██████████████████████████▋           | 1099/1568 [03:05<01:19,  5.92it/s]16 02:52:15 Save the image 00767N_flip.png
 70%|██████████████████████████▋           | 1100/1568 [03:06<01:19,  5.88it/s]16 02:52:16 Save the image 00768N.png
 70%|██████████████████████████▋           | 1101/1568 [03:06<01:19,  5.89it/s]16 02:52:16 Save the image 00768N_flip.png
 70%|██████████████████████████▋           | 1102/1568 [03:06<01:19,  5.86it/s]16 02:52:16 Save the image 00769N.png
 70%|██████████████████████████▋           | 1103/1568 [03:06<01:14,  6.23it/s]16 02:52:16 Save the image 00769N_flip.png
 70%|██████████████████████████▊           | 1104/1568 [03:06<01:16,  6.09it/s]16 02:52:16 Save the image 00770N.png
 70%|██████████████████████████▊           | 1105/1568 [03:06<01:16,  6.04it/s]16 02:52:16 Save the image 00770N_flip.png
 71%|██████████████████████████▊           | 1106/1568 [03:07<01:17,  6.00it/s]16 02:52:17 Save the image 00771N.png
 71%|██████████████████████████▊           | 1107/1568 [03:07<01:17,  5.95it/s]16 02:52:17 Save the image 00771N_flip.png
 71%|██████████████████████████▊           | 1108/1568 [03:07<01:17,  5.90it/s]16 02:52:17 Save the image 00772N.png
 71%|██████████████████████████▉           | 1109/1568 [03:07<01:18,  5.88it/s]16 02:52:17 Save the image 00772N_flip.png
 71%|██████████████████████████▉           | 1110/1568 [03:07<01:18,  5.87it/s]16 02:52:17 Save the image 00773N.png
 71%|██████████████████████████▉           | 1111/1568 [03:07<01:13,  6.18it/s]16 02:52:17 Save the image 00773N_flip.png
 71%|██████████████████████████▉           | 1112/1568 [03:08<01:15,  6.06it/s]16 02:52:18 Save the image 00774N.png
 71%|██████████████████████████▉           | 1113/1568 [03:08<01:15,  6.02it/s]16 02:52:18 Save the image 00774N_flip.png
 71%|██████████████████████████▉           | 1114/1568 [03:08<01:15,  5.99it/s]16 02:52:18 Save the image 00775N.png
 71%|███████████████████████████           | 1115/1568 [03:08<01:16,  5.93it/s]16 02:52:18 Save the image 00775N_flip.png
 71%|███████████████████████████           | 1116/1568 [03:08<01:16,  5.89it/s]16 02:52:18 Save the image 00776N.png
 71%|███████████████████████████           | 1117/1568 [03:08<01:16,  5.87it/s]16 02:52:18 Save the image 00776N_flip.png
 71%|███████████████████████████           | 1118/1568 [03:09<01:16,  5.87it/s]16 02:52:19 Save the image 00777N.png
 71%|███████████████████████████           | 1119/1568 [03:09<01:11,  6.24it/s]16 02:52:19 Save the image 00777N_flip.png
 71%|███████████████████████████▏          | 1120/1568 [03:09<01:13,  6.12it/s]16 02:52:19 Save the image 00778N.png
 71%|███████████████████████████▏          | 1121/1568 [03:09<01:13,  6.09it/s]16 02:52:19 Save the image 00778N_flip.png
 72%|███████████████████████████▏          | 1122/1568 [03:09<01:13,  6.06it/s]16 02:52:19 Save the image 00779N.png
 72%|███████████████████████████▏          | 1123/1568 [03:09<01:14,  5.98it/s]16 02:52:19 Save the image 00779N_flip.png
 72%|███████████████████████████▏          | 1124/1568 [03:10<01:14,  5.92it/s]16 02:52:20 Save the image 00780N.png
 72%|███████████████████████████▎          | 1125/1568 [03:10<01:16,  5.82it/s]16 02:52:20 Save the image 00780N_flip.png
 72%|███████████████████████████▎          | 1126/1568 [03:10<01:16,  5.78it/s]16 02:52:20 Save the image 00781N.png
 72%|███████████████████████████▎          | 1127/1568 [03:10<01:11,  6.13it/s]16 02:52:20 Save the image 00781N_flip.png
 72%|███████████████████████████▎          | 1128/1568 [03:10<01:13,  6.02it/s]16 02:52:20 Save the image 00782N.png
 72%|███████████████████████████▎          | 1129/1568 [03:10<01:13,  5.94it/s]16 02:52:20 Save the image 00782N_flip.png
 72%|███████████████████████████▍          | 1130/1568 [03:11<01:13,  5.93it/s]16 02:52:21 Save the image 00783N.png
 72%|███████████████████████████▍          | 1131/1568 [03:11<01:15,  5.83it/s]16 02:52:21 Save the image 00783N_flip.png
 72%|███████████████████████████▍          | 1132/1568 [03:11<01:14,  5.85it/s]16 02:52:21 Save the image 00784N.png
 72%|███████████████████████████▍          | 1133/1568 [03:11<01:15,  5.80it/s]16 02:52:21 Save the image 00784N_flip.png
 72%|███████████████████████████▍          | 1134/1568 [03:11<01:14,  5.85it/s]16 02:52:21 Save the image 00785N.png
 72%|███████████████████████████▌          | 1135/1568 [03:12<01:13,  5.89it/s]16 02:52:21 Save the image 00785N_flip.png
 72%|███████████████████████████▌          | 1136/1568 [03:12<01:13,  5.85it/s]16 02:52:22 Save the image 00786N.png
 73%|███████████████████████████▌          | 1137/1568 [03:12<01:13,  5.88it/s]16 02:52:22 Save the image 00786N_flip.png
 73%|███████████████████████████▌          | 1138/1568 [03:12<01:13,  5.87it/s]16 02:52:22 Save the image 00787N.png
 73%|███████████████████████████▌          | 1139/1568 [03:12<01:13,  5.82it/s]16 02:52:22 Save the image 00787N_flip.png
 73%|███████████████████████████▋          | 1140/1568 [03:12<01:13,  5.81it/s]16 02:52:22 Save the image 00788N.png
 73%|███████████████████████████▋          | 1141/1568 [03:13<01:13,  5.82it/s]16 02:52:22 Save the image 00788N_flip.png
 73%|███████████████████████████▋          | 1142/1568 [03:13<01:12,  5.91it/s]16 02:52:23 Save the image 00789N.png
 73%|███████████████████████████▋          | 1143/1568 [03:13<01:11,  5.96it/s]16 02:52:23 Save the image 00789N_flip.png
 73%|███████████████████████████▋          | 1144/1568 [03:13<01:11,  5.91it/s]16 02:52:23 Save the image 00790N.png

 73%|███████████████████████████▋          | 1145/1568 [03:13<01:11,  5.93it/s]16 02:52:23 Save the image 00790N_flip.png
 73%|███████████████████████████▊          | 1146/1568 [03:13<01:11,  5.92it/s]16 02:52:23 Save the image 00791N.png
 73%|███████████████████████████▊          | 1147/1568 [03:14<01:12,  5.82it/s]16 02:52:24 Save the image 00791N_flip.png
 73%|███████████████████████████▊          | 1148/1568 [03:14<01:12,  5.80it/s]16 02:52:24 Save the image 00792N.png
 73%|███████████████████████████▊          | 1149/1568 [03:14<01:12,  5.82it/s]16 02:52:24 Save the image 00792N_flip.png
 73%|███████████████████████████▊          | 1150/1568 [03:14<01:11,  5.83it/s]16 02:52:24 Save the image 00793N.png
 73%|███████████████████████████▉          | 1151/1568 [03:14<01:10,  5.90it/s]16 02:52:24 Save the image 00793N_flip.png
 73%|███████████████████████████▉          | 1152/1568 [03:14<01:11,  5.82it/s]16 02:52:24 Save the image 00794N.png
 74%|███████████████████████████▉          | 1153/1568 [03:15<01:11,  5.84it/s]16 02:52:25 Save the image 00794N_flip.png
 74%|███████████████████████████▉          | 1154/1568 [03:15<01:10,  5.84it/s]16 02:52:25 Save the image 00795N.png
 74%|███████████████████████████▉          | 1155/1568 [03:15<01:10,  5.82it/s]16 02:52:25 Save the image 00795N_flip.png
 74%|████████████████████████████          | 1156/1568 [03:15<01:10,  5.81it/s]16 02:52:25 Save the image 00796N.png
 74%|████████████████████████████          | 1157/1568 [03:15<01:10,  5.83it/s]16 02:52:25 Save the image 00796N_flip.png
 74%|████████████████████████████          | 1158/1568 [03:15<01:10,  5.84it/s]16 02:52:25 Save the image 00797N.png
 74%|████████████████████████████          | 1159/1568 [03:16<01:10,  5.81it/s]16 02:52:26 Save the image 00797N_flip.png
 74%|████████████████████████████          | 1160/1568 [03:16<01:10,  5.81it/s]16 02:52:26 Save the image 00798N.png
 74%|████████████████████████████▏         | 1161/1568 [03:16<01:09,  5.85it/s]16 02:52:26 Save the image 00798N_flip.png
 74%|████████████████████████████▏         | 1162/1568 [03:16<01:08,  5.91it/s]16 02:52:26 Save the image 00799N.png
 74%|████████████████████████████▏         | 1163/1568 [03:16<01:09,  5.85it/s]16 02:52:26 Save the image 00799N_flip.png
 74%|████████████████████████████▏         | 1164/1568 [03:16<01:09,  5.84it/s]16 02:52:26 Save the image 00800N.png
 74%|████████████████████████████▏         | 1165/1568 [03:17<01:09,  5.78it/s]16 02:52:27 Save the image 00800N_flip.png
 74%|████████████████████████████▎         | 1166/1568 [03:17<01:08,  5.84it/s]16 02:52:27 Save the image 00801N.png
 74%|████████████████████████████▎         | 1167/1568 [03:17<01:08,  5.84it/s]16 02:52:27 Save the image 00801N_flip.png
 74%|████████████████████████████▎         | 1168/1568 [03:17<01:08,  5.82it/s]16 02:52:27 Save the image 00802N.png
 75%|████████████████████████████▎         | 1169/1568 [03:17<01:08,  5.85it/s]16 02:52:27 Save the image 00802N_flip.png
 75%|████████████████████████████▎         | 1170/1568 [03:18<01:08,  5.84it/s]16 02:52:27 Save the image 00803N.png
 75%|████████████████████████████▍         | 1171/1568 [03:18<01:08,  5.82it/s]16 02:52:28 Save the image 00803N_flip.png
 75%|████████████████████████████▍         | 1172/1568 [03:18<01:07,  5.84it/s]16 02:52:28 Save the image 00804N.png
 75%|████████████████████████████▍         | 1173/1568 [03:18<01:07,  5.82it/s]16 02:52:28 Save the image 00804N_flip.png
 75%|████████████████████████████▍         | 1174/1568 [03:18<01:06,  5.92it/s]16 02:52:28 Save the image 00805N.png
 75%|████████████████████████████▍         | 1175/1568 [03:18<01:07,  5.83it/s]16 02:52:28 Save the image 00805N_flip.png
 75%|████████████████████████████▌         | 1176/1568 [03:19<01:07,  5.83it/s]16 02:52:28 Save the image 00806N.png
 75%|████████████████████████████▌         | 1177/1568 [03:19<01:06,  5.84it/s]16 02:52:29 Save the image 00806N_flip.png
 75%|████████████████████████████▌         | 1178/1568 [03:19<01:06,  5.86it/s]16 02:52:29 Save the image 00807N.png
 75%|████████████████████████████▌         | 1179/1568 [03:19<01:06,  5.84it/s]16 02:52:29 Save the image 00807N_flip.png
 75%|████████████████████████████▌         | 1180/1568 [03:19<01:06,  5.86it/s]16 02:52:29 Save the image 00808N.png
 75%|████████████████████████████▌         | 1181/1568 [03:19<01:06,  5.86it/s]16 02:52:29 Save the image 00808N_flip.png
 75%|████████████████████████████▋         | 1182/1568 [03:20<01:05,  5.94it/s]16 02:52:29 Save the image 00809N.png
 75%|████████████████████████████▋         | 1183/1568 [03:20<01:05,  5.90it/s]16 02:52:30 Save the image 00809N_flip.png
 76%|████████████████████████████▋         | 1184/1568 [03:20<01:05,  5.90it/s]16 02:52:30 Save the image 00810N.png
 76%|████████████████████████████▋         | 1185/1568 [03:20<01:04,  5.90it/s]16 02:52:30 Save the image 00810N_flip.png
 76%|████████████████████████████▋         | 1186/1568 [03:20<01:04,  5.88it/s]16 02:52:30 Save the image 00811N.png
 76%|████████████████████████████▊         | 1187/1568 [03:20<01:04,  5.86it/s]16 02:52:30 Save the image 00811N_flip.png
 76%|████████████████████████████▊         | 1188/1568 [03:21<01:04,  5.87it/s]16 02:52:31 Save the image 00812N.png
 76%|████████████████████████████▊         | 1189/1568 [03:21<01:04,  5.86it/s]16 02:52:31 Save the image 00812N_flip.png
 76%|████████████████████████████▊         | 1190/1568 [03:21<01:03,  5.92it/s]16 02:52:31 Save the image 00813N.png
 76%|████████████████████████████▊         | 1191/1568 [03:21<01:02,  6.02it/s]16 02:52:31 Save the image 00813N_flip.png
 76%|████████████████████████████▉         | 1192/1568 [03:21<01:03,  5.95it/s]16 02:52:31 Save the image 00814N.png
 76%|████████████████████████████▉         | 1193/1568 [03:21<01:03,  5.94it/s]16 02:52:31 Save the image 00814N_flip.png
 76%|████████████████████████████▉         | 1194/1568 [03:22<01:03,  5.93it/s]16 02:52:32 Save the image 00815N.png
 76%|████████████████████████████▉         | 1195/1568 [03:22<01:04,  5.81it/s]16 02:52:32 Save the image 00815N_flip.png
 76%|████████████████████████████▉         | 1196/1568 [03:22<01:03,  5.82it/s]16 02:52:32 Save the image 00816N.png
 76%|█████████████████████████████         | 1197/1568 [03:22<01:04,  5.77it/s]16 02:52:32 Save the image 00816N_flip.png
 76%|█████████████████████████████         | 1198/1568 [03:22<01:04,  5.75it/s]16 02:52:32 Save the image 00817N.png
 76%|█████████████████████████████         | 1199/1568 [03:22<01:01,  6.01it/s]16 02:52:32 Save the image 00817N_flip.png
 77%|█████████████████████████████         | 1200/1568 [03:23<01:01,  5.94it/s]16 02:52:33 Save the image 00818N.png
 77%|█████████████████████████████         | 1201/1568 [03:23<01:01,  5.94it/s]16 02:52:33 Save the image 00818N_flip.png
 77%|█████████████████████████████▏        | 1202/1568 [03:23<01:01,  5.92it/s]16 02:52:33 Save the image 00819N.png
 77%|█████████████████████████████▏        | 1203/1568 [03:23<01:02,  5.86it/s]16 02:52:33 Save the image 00819N_flip.png
 77%|█████████████████████████████▏        | 1204/1568 [03:23<01:02,  5.85it/s]16 02:52:33 Save the image 00820N.png
 77%|█████████████████████████████▏        | 1205/1568 [03:23<01:02,  5.80it/s]16 02:52:33 Save the image 00820N_flip.png
 77%|█████████████████████████████▏        | 1206/1568 [03:24<01:01,  5.86it/s]16 02:52:34 Save the image 00821N.png
 77%|█████████████████████████████▎        | 1207/1568 [03:24<01:00,  5.93it/s]16 02:52:34 Save the image 00821N_flip.png
 77%|█████████████████████████████▎        | 1208/1568 [03:24<01:01,  5.85it/s]16 02:52:34 Save the image 00822N.png

 77%|█████████████████████████████▎        | 1209/1568 [03:24<01:01,  5.82it/s]16 02:52:34 Save the image 00822N_flip.png
 77%|█████████████████████████████▎        | 1210/1568 [03:24<01:01,  5.81it/s]16 02:52:34 Save the image 00823N.png
 77%|█████████████████████████████▎        | 1211/1568 [03:24<01:01,  5.77it/s]16 02:52:34 Save the image 00823N_flip.png
 77%|█████████████████████████████▎        | 1212/1568 [03:25<01:01,  5.79it/s]16 02:52:35 Save the image 00824N.png
 77%|█████████████████████████████▍        | 1213/1568 [03:25<01:01,  5.79it/s]16 02:52:35 Save the image 00824N_flip.png
 77%|█████████████████████████████▍        | 1214/1568 [03:25<01:00,  5.87it/s]16 02:52:35 Save the image 00825N.png
 77%|█████████████████████████████▍        | 1215/1568 [03:25<00:58,  6.08it/s]16 02:52:35 Save the image 00825N_flip.png
 78%|█████████████████████████████▍        | 1216/1568 [03:25<00:58,  5.98it/s]16 02:52:35 Save the image 00826N.png
 78%|█████████████████████████████▍        | 1217/1568 [03:25<00:58,  5.96it/s]16 02:52:35 Save the image 00826N_flip.png
 78%|█████████████████████████████▌        | 1218/1568 [03:26<00:58,  5.95it/s]16 02:52:36 Save the image 00827N.png
 78%|█████████████████████████████▌        | 1219/1568 [03:26<00:59,  5.91it/s]16 02:52:36 Save the image 00827N_flip.png
 78%|█████████████████████████████▌        | 1220/1568 [03:26<00:59,  5.88it/s]16 02:52:36 Save the image 00828N.png
 78%|█████████████████████████████▌        | 1221/1568 [03:26<00:59,  5.87it/s]16 02:52:36 Save the image 00828N_flip.png
 78%|█████████████████████████████▌        | 1222/1568 [03:26<00:58,  5.93it/s]16 02:52:36 Save the image 00829N.png
 78%|█████████████████████████████▋        | 1223/1568 [03:26<00:56,  6.12it/s]16 02:52:36 Save the image 00829N_flip.png
 78%|█████████████████████████████▋        | 1224/1568 [03:27<00:57,  6.02it/s]16 02:52:37 Save the image 00830N.png
 78%|█████████████████████████████▋        | 1225/1568 [03:27<00:57,  5.93it/s]16 02:52:37 Save the image 00830N_flip.png
 78%|█████████████████████████████▋        | 1226/1568 [03:27<00:57,  5.92it/s]16 02:52:37 Save the image 00831N.png
 78%|█████████████████████████████▋        | 1227/1568 [03:27<00:57,  5.89it/s]16 02:52:37 Save the image 00831N_flip.png
 78%|█████████████████████████████▊        | 1228/1568 [03:27<00:58,  5.86it/s]16 02:52:37 Save the image 00832N.png
 78%|█████████████████████████████▊        | 1229/1568 [03:28<00:57,  5.88it/s]16 02:52:37 Save the image 00832N_flip.png
 78%|█████████████████████████████▊        | 1230/1568 [03:28<00:57,  5.86it/s]16 02:52:38 Save the image 00833N.png
 79%|█████████████████████████████▊        | 1231/1568 [03:28<00:54,  6.20it/s]16 02:52:38 Save the image 00833N_flip.png
 79%|█████████████████████████████▊        | 1232/1568 [03:28<00:55,  6.08it/s]16 02:52:38 Save the image 00834N.png
 79%|█████████████████████████████▉        | 1233/1568 [03:28<00:55,  6.03it/s]16 02:52:38 Save the image 00834N_flip.png
 79%|█████████████████████████████▉        | 1234/1568 [03:28<00:55,  6.00it/s]16 02:52:38 Save the image 00835N.png
 79%|█████████████████████████████▉        | 1235/1568 [03:29<00:56,  5.94it/s]16 02:52:38 Save the image 00835N_flip.png
 79%|█████████████████████████████▉        | 1236/1568 [03:29<00:56,  5.90it/s]16 02:52:39 Save the image 00836N.png
 79%|█████████████████████████████▉        | 1237/1568 [03:29<00:56,  5.91it/s]16 02:52:39 Save the image 00836N_flip.png
 79%|██████████████████████████████        | 1238/1568 [03:29<00:56,  5.89it/s]16 02:52:39 Save the image 00837N.png
 79%|██████████████████████████████        | 1239/1568 [03:29<00:53,  6.20it/s]16 02:52:39 Save the image 00837N_flip.png
 79%|██████████████████████████████        | 1240/1568 [03:29<00:53,  6.08it/s]16 02:52:39 Save the image 00838N.png
 79%|██████████████████████████████        | 1241/1568 [03:30<00:54,  6.03it/s]16 02:52:39 Save the image 00838N_flip.png
 79%|██████████████████████████████        | 1242/1568 [03:30<00:54,  5.99it/s]16 02:52:40 Save the image 00839N.png
 79%|██████████████████████████████        | 1243/1568 [03:30<00:54,  5.92it/s]16 02:52:40 Save the image 00839N_flip.png
 79%|██████████████████████████████▏       | 1244/1568 [03:30<00:55,  5.87it/s]16 02:52:40 Save the image 00840N.png
 79%|██████████████████████████████▏       | 1245/1568 [03:30<00:54,  5.88it/s]16 02:52:40 Save the image 00840N_flip.png
 79%|██████████████████████████████▏       | 1246/1568 [03:30<00:54,  5.86it/s]16 02:52:40 Save the image 00841N.png
 80%|██████████████████████████████▏       | 1247/1568 [03:31<00:51,  6.21it/s]16 02:52:40 Save the image 00841N_flip.png
 80%|██████████████████████████████▏       | 1248/1568 [03:31<00:52,  6.10it/s]16 02:52:41 Save the image 00842N.png
 80%|██████████████████████████████▎       | 1249/1568 [03:31<00:52,  6.05it/s]16 02:52:41 Save the image 00842N_flip.png
 80%|██████████████████████████████▎       | 1250/1568 [03:31<00:53,  5.97it/s]16 02:52:41 Save the image 00843N.png
 80%|██████████████████████████████▎       | 1251/1568 [03:31<00:53,  5.93it/s]16 02:52:41 Save the image 00843N_flip.png
 80%|██████████████████████████████▎       | 1252/1568 [03:31<00:53,  5.91it/s]16 02:52:41 Save the image 00844N.png
 80%|██████████████████████████████▎       | 1253/1568 [03:32<00:53,  5.89it/s]16 02:52:41 Save the image 00844N_flip.png
 80%|██████████████████████████████▍       | 1254/1568 [03:32<00:53,  5.88it/s]16 02:52:42 Save the image 00845N.png
 80%|██████████████████████████████▍       | 1255/1568 [03:32<00:50,  6.20it/s]16 02:52:42 Save the image 00845N_flip.png
 80%|██████████████████████████████▍       | 1256/1568 [03:32<00:51,  6.08it/s]16 02:52:42 Save the image 00846N.png
 80%|██████████████████████████████▍       | 1257/1568 [03:32<00:51,  6.03it/s]16 02:52:42 Save the image 00846N_flip.png
 80%|██████████████████████████████▍       | 1258/1568 [03:32<00:51,  5.99it/s]16 02:52:42 Save the image 00847N.png
 80%|██████████████████████████████▌       | 1259/1568 [03:33<00:52,  5.93it/s]16 02:52:42 Save the image 00847N_flip.png
 80%|██████████████████████████████▌       | 1260/1568 [03:33<00:52,  5.90it/s]16 02:52:43 Save the image 00848N.png
 80%|██████████████████████████████▌       | 1261/1568 [03:33<00:52,  5.83it/s]16 02:52:43 Save the image 00848N_flip.png
 80%|██████████████████████████████▌       | 1262/1568 [03:33<00:52,  5.84it/s]16 02:52:43 Save the image 00849N.png
 81%|██████████████████████████████▌       | 1263/1568 [03:33<00:51,  5.95it/s]16 02:52:43 Save the image 00849N_flip.png
 81%|██████████████████████████████▋       | 1264/1568 [03:33<00:51,  5.88it/s]16 02:52:43 Save the image 00850N.png
 81%|██████████████████████████████▋       | 1265/1568 [03:34<00:51,  5.87it/s]16 02:52:43 Save the image 00850N_flip.png
 81%|██████████████████████████████▋       | 1266/1568 [03:34<00:51,  5.86it/s]16 02:52:44 Save the image 00851N.png
 81%|██████████████████████████████▋       | 1267/1568 [03:34<00:51,  5.80it/s]16 02:52:44 Save the image 00851N_flip.png
 81%|██████████████████████████████▋       | 1268/1568 [03:34<00:51,  5.83it/s]16 02:52:44 Save the image 00852N.png
 81%|██████████████████████████████▊       | 1269/1568 [03:34<00:51,  5.82it/s]16 02:52:44 Save the image 00852N_flip.png
 81%|██████████████████████████████▊       | 1270/1568 [03:34<00:51,  5.84it/s]16 02:52:44 Save the image 00853N.png
 81%|██████████████████████████████▊       | 1271/1568 [03:35<00:51,  5.78it/s]16 02:52:45 Save the image 00853N_flip.png
 81%|██████████████████████████████▊       | 1272/1568 [03:35<00:51,  5.76it/s]16 02:52:45 Save the image 00854N.png

 81%|██████████████████████████████▊       | 1273/1568 [03:35<00:50,  5.81it/s]16 02:52:45 Save the image 00854N_flip.png
 81%|██████████████████████████████▉       | 1274/1568 [03:35<00:50,  5.86it/s]16 02:52:45 Save the image 00855N.png
 81%|██████████████████████████████▉       | 1275/1568 [03:35<00:50,  5.84it/s]16 02:52:45 Save the image 00855N_flip.png
 81%|██████████████████████████████▉       | 1276/1568 [03:35<00:49,  5.86it/s]16 02:52:45 Save the image 00856N.png
 81%|██████████████████████████████▉       | 1277/1568 [03:36<00:49,  5.85it/s]16 02:52:46 Save the image 00856N_flip.png
 82%|██████████████████████████████▉       | 1278/1568 [03:36<00:49,  5.86it/s]16 02:52:46 Save the image 00857N.png
 82%|██████████████████████████████▉       | 1279/1568 [03:36<00:47,  6.05it/s]16 02:52:46 Save the image 00857N_flip.png
 82%|███████████████████████████████       | 1280/1568 [03:36<00:48,  5.99it/s]16 02:52:46 Save the image 00858N.png
 82%|███████████████████████████████       | 1281/1568 [03:36<00:48,  5.96it/s]16 02:52:46 Save the image 00858N_flip.png
 82%|███████████████████████████████       | 1282/1568 [03:36<00:48,  5.94it/s]16 02:52:46 Save the image 00859N.png
 82%|███████████████████████████████       | 1283/1568 [03:37<00:48,  5.90it/s]16 02:52:47 Save the image 00859N_flip.png
 82%|███████████████████████████████       | 1284/1568 [03:37<00:48,  5.90it/s]16 02:52:47 Save the image 00860N.png
 82%|███████████████████████████████▏      | 1285/1568 [03:37<00:48,  5.88it/s]16 02:52:47 Save the image 00860N_flip.png
 82%|███████████████████████████████▏      | 1286/1568 [03:37<00:47,  5.96it/s]16 02:52:47 Save the image 00861N.png
 82%|███████████████████████████████▏      | 1287/1568 [03:37<00:45,  6.12it/s]16 02:52:47 Save the image 00861N_flip.png
 82%|███████████████████████████████▏      | 1288/1568 [03:37<00:46,  6.04it/s]16 02:52:47 Save the image 00862N.png
 82%|███████████████████████████████▏      | 1289/1568 [03:38<00:46,  6.00it/s]16 02:52:48 Save the image 00862N_flip.png
 82%|███████████████████████████████▎      | 1290/1568 [03:38<00:46,  6.02it/s]16 02:52:48 Save the image 00863N.png
 82%|███████████████████████████████▎      | 1291/1568 [03:38<00:46,  5.97it/s]16 02:52:48 Save the image 00863N_flip.png
 82%|███████████████████████████████▎      | 1292/1568 [03:38<00:46,  5.97it/s]16 02:52:48 Save the image 00864N.png
 82%|███████████████████████████████▎      | 1293/1568 [03:38<00:46,  5.93it/s]16 02:52:48 Save the image 00864N_flip.png
 83%|███████████████████████████████▎      | 1294/1568 [03:38<00:45,  5.99it/s]16 02:52:48 Save the image 00865N.png
 83%|███████████████████████████████▍      | 1295/1568 [03:39<00:45,  6.06it/s]16 02:52:49 Save the image 00865N_flip.png
 83%|███████████████████████████████▍      | 1296/1568 [03:39<00:45,  5.99it/s]16 02:52:49 Save the image 00866N.png
 83%|███████████████████████████████▍      | 1297/1568 [03:39<00:45,  5.97it/s]16 02:52:49 Save the image 00866N_flip.png
 83%|███████████████████████████████▍      | 1298/1568 [03:39<00:45,  5.98it/s]16 02:52:49 Save the image 00867N.png
 83%|███████████████████████████████▍      | 1299/1568 [03:39<00:45,  5.93it/s]16 02:52:49 Save the image 00867N_flip.png
 83%|███████████████████████████████▌      | 1300/1568 [03:39<00:45,  5.90it/s]16 02:52:49 Save the image 00868N.png
 83%|███████████████████████████████▌      | 1301/1568 [03:40<00:45,  5.87it/s]16 02:52:50 Save the image 00868N_flip.png
 83%|███████████████████████████████▌      | 1302/1568 [03:40<00:44,  5.93it/s]16 02:52:50 Save the image 00869N.png
 83%|███████████████████████████████▌      | 1303/1568 [03:40<00:43,  6.07it/s]16 02:52:50 Save the image 00869N_flip.png
 83%|███████████████████████████████▌      | 1304/1568 [03:40<00:44,  6.00it/s]16 02:52:50 Save the image 00870N.png
 83%|███████████████████████████████▋      | 1305/1568 [03:40<00:43,  5.99it/s]16 02:52:50 Save the image 00870N_flip.png
 83%|███████████████████████████████▋      | 1306/1568 [03:40<00:43,  5.97it/s]16 02:52:50 Save the image 00871N.png
 83%|███████████████████████████████▋      | 1307/1568 [03:41<00:44,  5.91it/s]16 02:52:51 Save the image 00871N_flip.png
 83%|███████████████████████████████▋      | 1308/1568 [03:41<00:44,  5.81it/s]16 02:52:51 Save the image 00872N.png
 83%|███████████████████████████████▋      | 1309/1568 [03:41<00:44,  5.80it/s]16 02:52:51 Save the image 00872N_flip.png
 84%|███████████████████████████████▋      | 1310/1568 [03:41<00:44,  5.82it/s]16 02:52:51 Save the image 00873N.png
 84%|███████████████████████████████▊      | 1311/1568 [03:41<00:41,  6.13it/s]16 02:52:51 Save the image 00873N_flip.png
 84%|███████████████████████████████▊      | 1312/1568 [03:41<00:42,  6.05it/s]16 02:52:51 Save the image 00874N.png
 84%|███████████████████████████████▊      | 1313/1568 [03:42<00:42,  6.04it/s]16 02:52:52 Save the image 00874N_flip.png
 84%|███████████████████████████████▊      | 1314/1568 [03:42<00:42,  6.02it/s]16 02:52:52 Save the image 00875N.png
 84%|███████████████████████████████▊      | 1315/1568 [03:42<00:42,  5.96it/s]16 02:52:52 Save the image 00875N_flip.png
 84%|███████████████████████████████▉      | 1316/1568 [03:42<00:42,  5.94it/s]16 02:52:52 Save the image 00876N.png
 84%|███████████████████████████████▉      | 1317/1568 [03:42<00:42,  5.90it/s]16 02:52:52 Save the image 00876N_flip.png
 84%|███████████████████████████████▉      | 1318/1568 [03:42<00:42,  5.95it/s]16 02:52:52 Save the image 00877N.png
 84%|███████████████████████████████▉      | 1319/1568 [03:43<00:41,  6.06it/s]16 02:52:53 Save the image 00877N_flip.png
 84%|███████████████████████████████▉      | 1320/1568 [03:43<00:41,  5.99it/s]16 02:52:53 Save the image 00878N.png
 84%|████████████████████████████████      | 1321/1568 [03:43<00:41,  5.97it/s]16 02:52:53 Save the image 00878N_flip.png
 84%|████████████████████████████████      | 1322/1568 [03:43<00:41,  5.98it/s]16 02:52:53 Save the image 00879N.png
 84%|████████████████████████████████      | 1323/1568 [03:43<00:41,  5.94it/s]16 02:52:53 Save the image 00879N_flip.png
 84%|████████████████████████████████      | 1324/1568 [03:43<00:41,  5.92it/s]16 02:52:53 Save the image 00880N.png
 85%|████████████████████████████████      | 1325/1568 [03:44<00:41,  5.89it/s]16 02:52:54 Save the image 00880N_flip.png
 85%|████████████████████████████████▏     | 1326/1568 [03:44<00:40,  5.95it/s]16 02:52:54 Save the image 00881N.png
 85%|████████████████████████████████▏     | 1327/1568 [03:44<00:39,  6.10it/s]16 02:52:54 Save the image 00881N_flip.png
 85%|████████████████████████████████▏     | 1328/1568 [03:44<00:40,  6.00it/s]16 02:52:54 Save the image 00882N.png
 85%|████████████████████████████████▏     | 1329/1568 [03:44<00:39,  5.98it/s]16 02:52:54 Save the image 00882N_flip.png
 85%|████████████████████████████████▏     | 1330/1568 [03:44<00:39,  5.96it/s]16 02:52:54 Save the image 00883N.png
 85%|████████████████████████████████▎     | 1331/1568 [03:45<00:40,  5.91it/s]16 02:52:55 Save the image 00883N_flip.png
 85%|████████████████████████████████▎     | 1332/1568 [03:45<00:40,  5.88it/s]16 02:52:55 Save the image 00884N.png
 85%|████████████████████████████████▎     | 1333/1568 [03:45<00:40,  5.85it/s]16 02:52:55 Save the image 00884N_flip.png
 85%|████████████████████████████████▎     | 1334/1568 [03:45<00:39,  5.92it/s]16 02:52:55 Save the image 00885N.png
 85%|████████████████████████████████▎     | 1335/1568 [03:45<00:38,  6.09it/s]16 02:52:55 Save the image 00885N_flip.png
 85%|████████████████████████████████▍     | 1336/1568 [03:46<00:38,  5.95it/s]16 02:52:55 Save the image 00886N.png

 85%|████████████████████████████████▍     | 1337/1568 [03:46<00:39,  5.89it/s]16 02:52:56 Save the image 00886N_flip.png
 85%|████████████████████████████████▍     | 1338/1568 [03:46<00:39,  5.86it/s]16 02:52:56 Save the image 00887N.png
 85%|████████████████████████████████▍     | 1339/1568 [03:46<00:40,  5.69it/s]16 02:52:56 Save the image 00887N_flip.png
 85%|████████████████████████████████▍     | 1340/1568 [03:46<00:39,  5.72it/s]16 02:52:56 Save the image 00888N.png
 86%|████████████████████████████████▍     | 1341/1568 [03:46<00:39,  5.71it/s]16 02:52:56 Save the image 00888N_flip.png
 86%|████████████████████████████████▌     | 1342/1568 [03:47<00:38,  5.80it/s]16 02:52:56 Save the image 00889N.png
 86%|████████████████████████████████▌     | 1343/1568 [03:47<00:37,  5.93it/s]16 02:52:57 Save the image 00889N_flip.png
 86%|████████████████████████████████▌     | 1344/1568 [03:47<00:38,  5.84it/s]16 02:52:57 Save the image 00890N.png
 86%|████████████████████████████████▌     | 1345/1568 [03:47<00:38,  5.81it/s]16 02:52:57 Save the image 00890N_flip.png
 86%|████████████████████████████████▌     | 1346/1568 [03:47<00:38,  5.81it/s]16 02:52:57 Save the image 00891N.png
 86%|████████████████████████████████▋     | 1347/1568 [03:47<00:38,  5.74it/s]16 02:52:57 Save the image 00891N_flip.png
 86%|████████████████████████████████▋     | 1348/1568 [03:48<00:38,  5.76it/s]16 02:52:58 Save the image 00892N.png
 86%|████████████████████████████████▋     | 1349/1568 [03:48<00:37,  5.77it/s]16 02:52:58 Save the image 00892N_flip.png
 86%|████████████████████████████████▋     | 1350/1568 [03:48<00:37,  5.85it/s]16 02:52:58 Save the image 00893N.png
 86%|████████████████████████████████▋     | 1351/1568 [03:48<00:36,  6.01it/s]16 02:52:58 Save the image 00893N_flip.png
 86%|████████████████████████████████▊     | 1352/1568 [03:48<00:36,  5.94it/s]16 02:52:58 Save the image 00894N.png
 86%|████████████████████████████████▊     | 1353/1568 [03:48<00:36,  5.94it/s]16 02:52:58 Save the image 00894N_flip.png
 86%|████████████████████████████████▊     | 1354/1568 [03:49<00:36,  5.92it/s]16 02:52:59 Save the image 00895N.png
 86%|████████████████████████████████▊     | 1355/1568 [03:49<00:36,  5.88it/s]16 02:52:59 Save the image 00895N_flip.png
 86%|████████████████████████████████▊     | 1356/1568 [03:49<00:36,  5.87it/s]16 02:52:59 Save the image 00896N.png
 87%|████████████████████████████████▉     | 1357/1568 [03:49<00:35,  5.88it/s]16 02:52:59 Save the image 00896N_flip.png
 87%|████████████████████████████████▉     | 1358/1568 [03:49<00:35,  5.94it/s]16 02:52:59 Save the image 00897N.png
 87%|████████████████████████████████▉     | 1359/1568 [03:49<00:34,  6.13it/s]16 02:52:59 Save the image 00897N_flip.png
 87%|████████████████████████████████▉     | 1360/1568 [03:50<00:34,  6.04it/s]16 02:53:00 Save the image 00898N.png
 87%|████████████████████████████████▉     | 1361/1568 [03:50<00:34,  6.00it/s]16 02:53:00 Save the image 00898N_flip.png
 87%|█████████████████████████████████     | 1362/1568 [03:50<00:34,  5.96it/s]16 02:53:00 Save the image 00899N.png
 87%|█████████████████████████████████     | 1363/1568 [03:50<00:34,  5.91it/s]16 02:53:00 Save the image 00899N_flip.png
 87%|█████████████████████████████████     | 1364/1568 [03:50<00:34,  5.91it/s]16 02:53:00 Save the image 00900N.png
 87%|█████████████████████████████████     | 1365/1568 [03:50<00:34,  5.89it/s]16 02:53:00 Save the image 00900N_flip.png
 87%|█████████████████████████████████     | 1366/1568 [03:51<00:34,  5.88it/s]16 02:53:01 Save the image 00901N.png
 87%|█████████████████████████████████▏    | 1367/1568 [03:51<00:33,  5.96it/s]16 02:53:01 Save the image 00901N_flip.png
 87%|█████████████████████████████████▏    | 1368/1568 [03:51<00:34,  5.84it/s]16 02:53:01 Save the image 00902N.png
 87%|█████████████████████████████████▏    | 1369/1568 [03:51<00:34,  5.84it/s]16 02:53:01 Save the image 00902N_flip.png
 87%|█████████████████████████████████▏    | 1370/1568 [03:51<00:33,  5.86it/s]16 02:53:01 Save the image 00903N.png
 87%|█████████████████████████████████▏    | 1371/1568 [03:51<00:34,  5.78it/s]16 02:53:01 Save the image 00903N_flip.png
 88%|█████████████████████████████████▎    | 1372/1568 [03:52<00:33,  5.79it/s]16 02:53:02 Save the image 00904N.png
 88%|█████████████████████████████████▎    | 1373/1568 [03:52<00:33,  5.82it/s]16 02:53:02 Save the image 00904N_flip.png
 88%|█████████████████████████████████▎    | 1374/1568 [03:52<00:33,  5.79it/s]16 02:53:02 Save the image 00905N.png
 88%|█████████████████████████████████▎    | 1375/1568 [03:52<00:31,  6.09it/s]16 02:53:02 Save the image 00905N_flip.png
 88%|█████████████████████████████████▎    | 1376/1568 [03:52<00:32,  5.98it/s]16 02:53:02 Save the image 00906N.png
 88%|█████████████████████████████████▎    | 1377/1568 [03:52<00:31,  5.97it/s]16 02:53:02 Save the image 00906N_flip.png
 88%|█████████████████████████████████▍    | 1378/1568 [03:53<00:32,  5.90it/s]16 02:53:03 Save the image 00907N.png
 88%|█████████████████████████████████▍    | 1379/1568 [03:53<00:32,  5.84it/s]16 02:53:03 Save the image 00907N_flip.png
 88%|█████████████████████████████████▍    | 1380/1568 [03:53<00:32,  5.84it/s]16 02:53:03 Save the image 00908N.png
 88%|█████████████████████████████████▍    | 1381/1568 [03:53<00:32,  5.82it/s]16 02:53:03 Save the image 00908N_flip.png
 88%|█████████████████████████████████▍    | 1382/1568 [03:53<00:31,  5.81it/s]16 02:53:03 Save the image 00909N.png
 88%|█████████████████████████████████▌    | 1383/1568 [03:53<00:29,  6.17it/s]16 02:53:03 Save the image 00909N_flip.png
 88%|█████████████████████████████████▌    | 1384/1568 [03:54<00:30,  6.06it/s]16 02:53:04 Save the image 00910N.png
 88%|█████████████████████████████████▌    | 1385/1568 [03:54<00:30,  6.02it/s]16 02:53:04 Save the image 00910N_flip.png
 88%|█████████████████████████████████▌    | 1386/1568 [03:54<00:30,  6.00it/s]16 02:53:04 Save the image 00911N.png
 88%|█████████████████████████████████▌    | 1387/1568 [03:54<00:30,  5.94it/s]16 02:53:04 Save the image 00911N_flip.png
 89%|█████████████████████████████████▋    | 1388/1568 [03:54<00:30,  5.91it/s]16 02:53:04 Save the image 00912N.png
 89%|█████████████████████████████████▋    | 1389/1568 [03:55<00:30,  5.92it/s]16 02:53:04 Save the image 00912N_flip.png
 89%|█████████████████████████████████▋    | 1390/1568 [03:55<00:30,  5.89it/s]16 02:53:05 Save the image 00913N.png
 89%|█████████████████████████████████▋    | 1391/1568 [03:55<00:28,  6.24it/s]16 02:53:05 Save the image 00913N_flip.png
 89%|█████████████████████████████████▋    | 1392/1568 [03:55<00:28,  6.11it/s]16 02:53:05 Save the image 00914N.png
 89%|█████████████████████████████████▊    | 1393/1568 [03:55<00:28,  6.06it/s]16 02:53:05 Save the image 00914N_flip.png
 89%|█████████████████████████████████▊    | 1394/1568 [03:55<00:28,  6.02it/s]16 02:53:05 Save the image 00915N.png
 89%|█████████████████████████████████▊    | 1395/1568 [03:55<00:29,  5.94it/s]16 02:53:05 Save the image 00915N_flip.png
 89%|█████████████████████████████████▊    | 1396/1568 [03:56<00:29,  5.91it/s]16 02:53:06 Save the image 00916N.png
 89%|█████████████████████████████████▊    | 1397/1568 [03:56<00:29,  5.87it/s]16 02:53:06 Save the image 00916N_flip.png
 89%|█████████████████████████████████▉    | 1398/1568 [03:56<00:29,  5.79it/s]16 02:53:06 Save the image 00917N.png
 89%|█████████████████████████████████▉    | 1399/1568 [03:56<00:27,  6.15it/s]16 02:53:06 Save the image 00917N_flip.png
 89%|█████████████████████████████████▉    | 1400/1568 [03:56<00:28,  5.99it/s]16 02:53:06 Save the image 00918N.png

 89%|█████████████████████████████████▉    | 1401/1568 [03:57<00:27,  5.98it/s]16 02:53:06 Save the image 00918N_flip.png
 89%|█████████████████████████████████▉    | 1402/1568 [03:57<00:27,  5.96it/s]16 02:53:07 Save the image 00919N.png
 89%|██████████████████████████████████    | 1403/1568 [03:57<00:28,  5.86it/s]16 02:53:07 Save the image 00919N_flip.png
 90%|██████████████████████████████████    | 1404/1568 [03:57<00:28,  5.78it/s]16 02:53:07 Save the image 00920N.png
 90%|██████████████████████████████████    | 1405/1568 [03:57<00:28,  5.78it/s]16 02:53:07 Save the image 00920N_flip.png
 90%|██████████████████████████████████    | 1406/1568 [03:57<00:28,  5.76it/s]16 02:53:07 Save the image 00921N.png
 90%|██████████████████████████████████    | 1407/1568 [03:58<00:26,  6.08it/s]16 02:53:07 Save the image 00921N_flip.png
 90%|██████████████████████████████████    | 1408/1568 [03:58<00:26,  5.97it/s]16 02:53:08 Save the image 00922N.png
 90%|██████████████████████████████████▏   | 1409/1568 [03:58<00:26,  5.95it/s]16 02:53:08 Save the image 00922N_flip.png
 90%|██████████████████████████████████▏   | 1410/1568 [03:58<00:26,  5.93it/s]16 02:53:08 Save the image 00923N.png
 90%|██████████████████████████████████▏   | 1411/1568 [03:58<00:26,  5.84it/s]16 02:53:08 Save the image 00923N_flip.png
 90%|██████████████████████████████████▏   | 1412/1568 [03:58<00:26,  5.81it/s]16 02:53:08 Save the image 00924N.png
 90%|██████████████████████████████████▏   | 1413/1568 [03:59<00:26,  5.81it/s]16 02:53:09 Save the image 00924N_flip.png
 90%|██████████████████████████████████▎   | 1414/1568 [03:59<00:26,  5.81it/s]16 02:53:09 Save the image 00925N.png
 90%|██████████████████████████████████▎   | 1415/1568 [03:59<00:25,  6.03it/s]16 02:53:09 Save the image 00925N_flip.png
 90%|██████████████████████████████████▎   | 1416/1568 [03:59<00:25,  5.90it/s]16 02:53:09 Save the image 00926N.png
 90%|██████████████████████████████████▎   | 1417/1568 [03:59<00:25,  5.88it/s]16 02:53:09 Save the image 00926N_flip.png
 90%|██████████████████████████████████▎   | 1418/1568 [03:59<00:25,  5.89it/s]16 02:53:09 Save the image 00927N.png
 90%|██████████████████████████████████▍   | 1419/1568 [04:00<00:25,  5.80it/s]16 02:53:10 Save the image 00927N_flip.png
 91%|██████████████████████████████████▍   | 1420/1568 [04:00<00:25,  5.79it/s]16 02:53:10 Save the image 00928N.png
 91%|██████████████████████████████████▍   | 1421/1568 [04:00<00:25,  5.76it/s]16 02:53:10 Save the image 00928N_flip.png
 91%|██████████████████████████████████▍   | 1422/1568 [04:00<00:25,  5.80it/s]16 02:53:10 Save the image 00929N.png
 91%|██████████████████████████████████▍   | 1423/1568 [04:00<00:24,  5.93it/s]16 02:53:10 Save the image 00929N_flip.png
 91%|██████████████████████████████████▌   | 1424/1568 [04:00<00:24,  5.86it/s]16 02:53:10 Save the image 00930N.png
 91%|██████████████████████████████████▌   | 1425/1568 [04:01<00:24,  5.81it/s]16 02:53:11 Save the image 00930N_flip.png
 91%|██████████████████████████████████▌   | 1426/1568 [04:01<00:24,  5.80it/s]16 02:53:11 Save the image 00931N.png
 91%|██████████████████████████████████▌   | 1427/1568 [04:01<00:24,  5.73it/s]16 02:53:11 Save the image 00931N_flip.png
 91%|██████████████████████████████████▌   | 1428/1568 [04:01<00:24,  5.73it/s]16 02:53:11 Save the image 00932N.png
 91%|██████████████████████████████████▋   | 1429/1568 [04:01<00:24,  5.73it/s]16 02:53:11 Save the image 00932N_flip.png
 91%|██████████████████████████████████▋   | 1430/1568 [04:01<00:23,  5.82it/s]16 02:53:11 Save the image 00933N.png
 91%|██████████████████████████████████▋   | 1431/1568 [04:02<00:23,  5.95it/s]16 02:53:12 Save the image 00933N_flip.png
 91%|██████████████████████████████████▋   | 1432/1568 [04:02<00:23,  5.87it/s]16 02:53:12 Save the image 00934N.png
 91%|██████████████████████████████████▋   | 1433/1568 [04:02<00:23,  5.81it/s]16 02:53:12 Save the image 00934N_flip.png
 91%|██████████████████████████████████▊   | 1434/1568 [04:02<00:23,  5.81it/s]16 02:53:12 Save the image 00935N.png
 92%|██████████████████████████████████▊   | 1435/1568 [04:02<00:23,  5.75it/s]16 02:53:12 Save the image 00935N_flip.png
 92%|██████████████████████████████████▊   | 1436/1568 [04:03<00:23,  5.72it/s]16 02:53:12 Save the image 00936N.png
 92%|██████████████████████████████████▊   | 1437/1568 [04:03<00:22,  5.73it/s]16 02:53:13 Save the image 00936N_flip.png
 92%|██████████████████████████████████▊   | 1438/1568 [04:03<00:22,  5.83it/s]16 02:53:13 Save the image 00937N.png
 92%|██████████████████████████████████▊   | 1439/1568 [04:03<00:21,  5.97it/s]16 02:53:13 Save the image 00937N_flip.png
 92%|██████████████████████████████████▉   | 1440/1568 [04:03<00:21,  5.90it/s]16 02:53:13 Save the image 00938N.png
 92%|██████████████████████████████████▉   | 1441/1568 [04:03<00:21,  5.91it/s]16 02:53:13 Save the image 00938N_flip.png
 92%|██████████████████████████████████▉   | 1442/1568 [04:04<00:21,  5.89it/s]16 02:53:13 Save the image 00939N.png
 92%|██████████████████████████████████▉   | 1443/1568 [04:04<00:21,  5.86it/s]16 02:53:14 Save the image 00939N_flip.png
 92%|██████████████████████████████████▉   | 1444/1568 [04:04<00:21,  5.84it/s]16 02:53:14 Save the image 00940N.png
 92%|███████████████████████████████████   | 1445/1568 [04:04<00:21,  5.81it/s]16 02:53:14 Save the image 00940N_flip.png
 92%|███████████████████████████████████   | 1446/1568 [04:04<00:21,  5.80it/s]16 02:53:14 Save the image 00941N.png
 92%|███████████████████████████████████   | 1447/1568 [04:04<00:19,  6.13it/s]16 02:53:14 Save the image 00941N_flip.png
 92%|███████████████████████████████████   | 1448/1568 [04:05<00:19,  6.00it/s]16 02:53:14 Save the image 00942N.png
 92%|███████████████████████████████████   | 1449/1568 [04:05<00:19,  5.96it/s]16 02:53:15 Save the image 00942N_flip.png
 92%|███████████████████████████████████▏  | 1450/1568 [04:05<00:19,  5.92it/s]16 02:53:15 Save the image 00943N.png
 93%|███████████████████████████████████▏  | 1451/1568 [04:05<00:19,  5.87it/s]16 02:53:15 Save the image 00943N_flip.png
 93%|███████████████████████████████████▏  | 1452/1568 [04:05<00:19,  5.85it/s]16 02:53:15 Save the image 00944N.png
 93%|███████████████████████████████████▏  | 1453/1568 [04:05<00:19,  5.79it/s]16 02:53:15 Save the image 00944N_flip.png
 93%|███████████████████████████████████▏  | 1454/1568 [04:06<00:19,  5.76it/s]16 02:53:15 Save the image 00945N.png
 93%|███████████████████████████████████▎  | 1455/1568 [04:06<00:18,  6.04it/s]16 02:53:16 Save the image 00945N_flip.png
 93%|███████████████████████████████████▎  | 1456/1568 [04:06<00:18,  5.93it/s]16 02:53:16 Save the image 00946N.png
 93%|███████████████████████████████████▎  | 1457/1568 [04:06<00:18,  5.91it/s]16 02:53:16 Save the image 00946N_flip.png
 93%|███████████████████████████████████▎  | 1458/1568 [04:06<00:18,  5.90it/s]16 02:53:16 Save the image 00947N.png
 93%|███████████████████████████████████▎  | 1459/1568 [04:06<00:18,  5.83it/s]16 02:53:16 Save the image 00947N_flip.png
 93%|███████████████████████████████████▍  | 1460/1568 [04:07<00:18,  5.80it/s]16 02:53:17 Save the image 00948N.png
 93%|███████████████████████████████████▍  | 1461/1568 [04:07<00:18,  5.79it/s]16 02:53:17 Save the image 00948N_flip.png
 93%|███████████████████████████████████▍  | 1462/1568 [04:07<00:18,  5.82it/s]16 02:53:17 Save the image 00949N.png
 93%|███████████████████████████████████▍  | 1463/1568 [04:07<00:17,  5.85it/s]16 02:53:17 Save the image 00949N_flip.png
 93%|███████████████████████████████████▍  | 1464/1568 [04:07<00:17,  5.82it/s]16 02:53:17 Save the image 00950N.png

 93%|███████████████████████████████████▌  | 1465/1568 [04:07<00:17,  5.83it/s]16 02:53:17 Save the image 00950N_flip.png
 93%|███████████████████████████████████▌  | 1466/1568 [04:08<00:17,  5.87it/s]16 02:53:18 Save the image 00951N.png
 94%|███████████████████████████████████▌  | 1467/1568 [04:08<00:17,  5.85it/s]16 02:53:18 Save the image 00951N_flip.png
 94%|███████████████████████████████████▌  | 1468/1568 [04:08<00:17,  5.85it/s]16 02:53:18 Save the image 00952N.png
 94%|███████████████████████████████████▌  | 1469/1568 [04:08<00:17,  5.79it/s]16 02:53:18 Save the image 00952N_flip.png
 94%|███████████████████████████████████▋  | 1470/1568 [04:08<00:16,  5.84it/s]16 02:53:18 Save the image 00953N.png
 94%|███████████████████████████████████▋  | 1471/1568 [04:08<00:16,  5.96it/s]16 02:53:18 Save the image 00953N_flip.png
 94%|███████████████████████████████████▋  | 1472/1568 [04:09<00:16,  5.87it/s]16 02:53:19 Save the image 00954N.png
 94%|███████████████████████████████████▋  | 1473/1568 [04:09<00:16,  5.85it/s]16 02:53:19 Save the image 00954N_flip.png
 94%|███████████████████████████████████▋  | 1474/1568 [04:09<00:16,  5.87it/s]16 02:53:19 Save the image 00955N.png
 94%|███████████████████████████████████▋  | 1475/1568 [04:09<00:16,  5.77it/s]16 02:53:19 Save the image 00955N_flip.png
 94%|███████████████████████████████████▊  | 1476/1568 [04:09<00:15,  5.78it/s]16 02:53:19 Save the image 00956N.png
 94%|███████████████████████████████████▊  | 1477/1568 [04:10<00:15,  5.79it/s]16 02:53:19 Save the image 00956N_flip.png
 94%|███████████████████████████████████▊  | 1478/1568 [04:10<00:15,  5.82it/s]16 02:53:20 Save the image 00957N.png
 94%|███████████████████████████████████▊  | 1479/1568 [04:10<00:15,  5.85it/s]16 02:53:20 Save the image 00957N_flip.png
 94%|███████████████████████████████████▊  | 1480/1568 [04:10<00:15,  5.81it/s]16 02:53:20 Save the image 00958N.png
 94%|███████████████████████████████████▉  | 1481/1568 [04:10<00:14,  5.81it/s]16 02:53:20 Save the image 00958N_flip.png
 95%|███████████████████████████████████▉  | 1482/1568 [04:10<00:14,  5.86it/s]16 02:53:20 Save the image 00959N.png
 95%|███████████████████████████████████▉  | 1483/1568 [04:11<00:14,  5.79it/s]16 02:53:20 Save the image 00959N_flip.png
 95%|███████████████████████████████████▉  | 1484/1568 [04:11<00:14,  5.81it/s]16 02:53:21 Save the image 00960N.png
 95%|███████████████████████████████████▉  | 1485/1568 [04:11<00:14,  5.83it/s]16 02:53:21 Save the image 00960N_flip.png
 95%|████████████████████████████████████  | 1486/1568 [04:11<00:14,  5.85it/s]16 02:53:21 Save the image 00961N.png
 95%|████████████████████████████████████  | 1487/1568 [04:11<00:13,  5.81it/s]16 02:53:21 Save the image 00961N_flip.png
 95%|████████████████████████████████████  | 1488/1568 [04:11<00:13,  5.79it/s]16 02:53:21 Save the image 00962N.png
 95%|████████████████████████████████████  | 1489/1568 [04:12<00:13,  5.77it/s]16 02:53:22 Save the image 00962N_flip.png
 95%|████████████████████████████████████  | 1490/1568 [04:12<00:13,  5.82it/s]16 02:53:22 Save the image 00963N.png
 95%|████████████████████████████████████▏ | 1491/1568 [04:12<00:13,  5.76it/s]16 02:53:22 Save the image 00963N_flip.png
 95%|████████████████████████████████████▏ | 1492/1568 [04:12<00:13,  5.76it/s]16 02:53:22 Save the image 00964N.png
 95%|████████████████████████████████████▏ | 1493/1568 [04:12<00:13,  5.74it/s]16 02:53:22 Save the image 00964N_flip.png
 95%|████████████████████████████████████▏ | 1494/1568 [04:12<00:12,  5.79it/s]16 02:53:22 Save the image 00965N.png
 95%|████████████████████████████████████▏ | 1495/1568 [04:13<00:12,  5.91it/s]16 02:53:23 Save the image 00965N_flip.png
 95%|████████████████████████████████████▎ | 1496/1568 [04:13<00:12,  5.89it/s]16 02:53:23 Save the image 00966N.png
 95%|████████████████████████████████████▎ | 1497/1568 [04:13<00:12,  5.88it/s]16 02:53:23 Save the image 00966N_flip.png
 96%|████████████████████████████████████▎ | 1498/1568 [04:13<00:11,  5.88it/s]16 02:53:23 Save the image 00967N.png
 96%|████████████████████████████████████▎ | 1499/1568 [04:13<00:11,  5.85it/s]16 02:53:23 Save the image 00967N_flip.png
 96%|████████████████████████████████████▎ | 1500/1568 [04:13<00:11,  5.85it/s]16 02:53:23 Save the image 00968N.png
 96%|████████████████████████████████████▍ | 1501/1568 [04:14<00:11,  5.81it/s]16 02:53:24 Save the image 00968N_flip.png
 96%|████████████████████████████████████▍ | 1502/1568 [04:14<00:11,  5.85it/s]16 02:53:24 Save the image 00969N.png
 96%|████████████████████████████████████▍ | 1503/1568 [04:14<00:11,  5.86it/s]16 02:53:24 Save the image 00969N_flip.png
 96%|████████████████████████████████████▍ | 1504/1568 [04:14<00:11,  5.79it/s]16 02:53:24 Save the image 00970N.png
 96%|████████████████████████████████████▍ | 1505/1568 [04:14<00:10,  5.79it/s]16 02:53:24 Save the image 00970N_flip.png
 96%|████████████████████████████████████▍ | 1506/1568 [04:14<00:10,  5.82it/s]16 02:53:24 Save the image 00971N.png
 96%|████████████████████████████████████▌ | 1507/1568 [04:15<00:10,  5.78it/s]16 02:53:25 Save the image 00971N_flip.png
 96%|████████████████████████████████████▌ | 1508/1568 [04:15<00:10,  5.79it/s]16 02:53:25 Save the image 00972N.png
 96%|████████████████████████████████████▌ | 1509/1568 [04:15<00:10,  5.82it/s]16 02:53:25 Save the image 00972N_flip.png
 96%|████████████████████████████████████▌ | 1510/1568 [04:15<00:09,  5.89it/s]16 02:53:25 Save the image 00973N.png
 96%|████████████████████████████████████▌ | 1511/1568 [04:15<00:09,  5.94it/s]16 02:53:25 Save the image 00973N_flip.png
 96%|████████████████████████████████████▋ | 1512/1568 [04:15<00:09,  5.90it/s]16 02:53:25 Save the image 00974N.png
 96%|████████████████████████████████████▋ | 1513/1568 [04:16<00:09,  5.90it/s]16 02:53:26 Save the image 00974N_flip.png
 97%|████████████████████████████████████▋ | 1514/1568 [04:16<00:09,  5.91it/s]16 02:53:26 Save the image 00975N.png
 97%|████████████████████████████████████▋ | 1515/1568 [04:16<00:09,  5.87it/s]16 02:53:26 Save the image 00975N_flip.png
 97%|████████████████████████████████████▋ | 1516/1568 [04:16<00:08,  5.88it/s]16 02:53:26 Save the image 00976N.png
 97%|████████████████████████████████████▊ | 1517/1568 [04:16<00:08,  5.85it/s]16 02:53:26 Save the image 00976N_flip.png
 97%|████████████████████████████████████▊ | 1518/1568 [04:17<00:08,  5.92it/s]16 02:53:26 Save the image 00977N.png
 97%|████████████████████████████████████▊ | 1519/1568 [04:17<00:08,  6.11it/s]16 02:53:27 Save the image 00977N_flip.png
 97%|████████████████████████████████████▊ | 1520/1568 [04:17<00:07,  6.00it/s]16 02:53:27 Save the image 00978N.png
 97%|████████████████████████████████████▊ | 1521/1568 [04:17<00:07,  5.98it/s]16 02:53:27 Save the image 00978N_flip.png
 97%|████████████████████████████████████▉ | 1522/1568 [04:17<00:07,  5.93it/s]16 02:53:27 Save the image 00979N.png
 97%|████████████████████████████████████▉ | 1523/1568 [04:17<00:07,  5.81it/s]16 02:53:27 Save the image 00979N_flip.png
 97%|████████████████████████████████████▉ | 1524/1568 [04:18<00:07,  5.82it/s]16 02:53:27 Save the image 00980N.png
 97%|████████████████████████████████████▉ | 1525/1568 [04:18<00:07,  5.81it/s]16 02:53:28 Save the image 00980N_flip.png
 97%|████████████████████████████████████▉ | 1526/1568 [04:18<00:07,  5.87it/s]16 02:53:28 Save the image 00981N.png
 97%|█████████████████████████████████████ | 1527/1568 [04:18<00:06,  5.97it/s]16 02:53:28 Save the image 00981N_flip.png
 97%|█████████████████████████████████████ | 1528/1568 [04:18<00:06,  5.91it/s]16 02:53:28 Save the image 00982N.png

 98%|█████████████████████████████████████ | 1529/1568 [04:18<00:06,  5.93it/s]16 02:53:28 Save the image 00982N_flip.png
 98%|█████████████████████████████████████ | 1530/1568 [04:19<00:06,  5.94it/s]16 02:53:28 Save the image 00983N.png
 98%|█████████████████████████████████████ | 1531/1568 [04:19<00:06,  5.89it/s]16 02:53:29 Save the image 00983N_flip.png
 98%|█████████████████████████████████████▏| 1532/1568 [04:19<00:06,  5.87it/s]16 02:53:29 Save the image 00984N.png
 98%|█████████████████████████████████████▏| 1533/1568 [04:19<00:05,  5.89it/s]16 02:53:29 Save the image 00984N_flip.png
 98%|█████████████████████████████████████▏| 1534/1568 [04:19<00:05,  5.94it/s]16 02:53:29 Save the image 00985N.png
 98%|█████████████████████████████████████▏| 1535/1568 [04:19<00:05,  6.12it/s]16 02:53:29 Save the image 00985N_flip.png
 98%|█████████████████████████████████████▏| 1536/1568 [04:20<00:05,  6.01it/s]16 02:53:29 Save the image 00986N.png
 98%|█████████████████████████████████████▏| 1537/1568 [04:20<00:05,  5.99it/s]16 02:53:30 Save the image 00986N_flip.png
 98%|█████████████████████████████████████▎| 1538/1568 [04:20<00:05,  5.96it/s]16 02:53:30 Save the image 00987N.png
 98%|█████████████████████████████████████▎| 1539/1568 [04:20<00:04,  5.93it/s]16 02:53:30 Save the image 00987N_flip.png
 98%|█████████████████████████████████████▎| 1540/1568 [04:20<00:04,  5.92it/s]16 02:53:30 Save the image 00988N.png
 98%|█████████████████████████████████████▎| 1541/1568 [04:20<00:04,  5.91it/s]16 02:53:30 Save the image 00988N_flip.png
 98%|█████████████████████████████████████▎| 1542/1568 [04:21<00:04,  5.96it/s]16 02:53:30 Save the image 00989N.png
 98%|█████████████████████████████████████▍| 1543/1568 [04:21<00:04,  6.11it/s]16 02:53:31 Save the image 00989N_flip.png
 98%|█████████████████████████████████████▍| 1544/1568 [04:21<00:03,  6.03it/s]16 02:53:31 Save the image 00990N.png
 99%|█████████████████████████████████████▍| 1545/1568 [04:21<00:03,  6.00it/s]16 02:53:31 Save the image 00990N_flip.png
 99%|█████████████████████████████████████▍| 1546/1568 [04:21<00:03,  5.99it/s]16 02:53:31 Save the image 00991N.png
 99%|█████████████████████████████████████▍| 1547/1568 [04:21<00:03,  5.94it/s]16 02:53:31 Save the image 00991N_flip.png
 99%|█████████████████████████████████████▌| 1548/1568 [04:22<00:03,  5.91it/s]16 02:53:32 Save the image 00992N.png
 99%|█████████████████████████████████████▌| 1549/1568 [04:22<00:03,  5.89it/s]16 02:53:32 Save the image 00992N_flip.png
 99%|█████████████████████████████████████▌| 1550/1568 [04:22<00:03,  5.98it/s]16 02:53:32 Save the image 00993N.png
 99%|█████████████████████████████████████▌| 1551/1568 [04:22<00:02,  6.15it/s]16 02:53:32 Save the image 00993N_flip.png
 99%|█████████████████████████████████████▌| 1552/1568 [04:22<00:02,  6.06it/s]16 02:53:32 Save the image 00994N.png
 99%|█████████████████████████████████████▋| 1553/1568 [04:22<00:02,  6.03it/s]16 02:53:32 Save the image 00994N_flip.png
 99%|█████████████████████████████████████▋| 1554/1568 [04:23<00:02,  6.00it/s]16 02:53:32 Save the image 00995N.png
 99%|█████████████████████████████████████▋| 1555/1568 [04:23<00:02,  5.94it/s]16 02:53:33 Save the image 00995N_flip.png
 99%|█████████████████████████████████████▋| 1556/1568 [04:23<00:02,  5.91it/s]16 02:53:33 Save the image 00996N.png
 99%|█████████████████████████████████████▋| 1557/1568 [04:23<00:01,  5.88it/s]16 02:53:33 Save the image 00996N_flip.png
 99%|█████████████████████████████████████▊| 1558/1568 [04:23<00:01,  5.95it/s]16 02:53:33 Save the image 00997N.png
 99%|█████████████████████████████████████▊| 1559/1568 [04:23<00:01,  6.14it/s]16 02:53:33 Save the image 00997N_flip.png
 99%|█████████████████████████████████████▊| 1560/1568 [04:24<00:01,  6.02it/s]16 02:53:33 Save the image 00998N.png
100%|█████████████████████████████████████▊| 1561/1568 [04:24<00:01,  6.00it/s]16 02:53:34 Save the image 00998N_flip.png
100%|█████████████████████████████████████▊| 1562/1568 [04:24<00:01,  5.99it/s]16 02:53:34 Save the image 00999N.png
100%|█████████████████████████████████████▉| 1563/1568 [04:24<00:00,  5.93it/s]16 02:53:34 Save the image 00999N_flip.png
100%|█████████████████████████████████████▉| 1564/1568 [04:24<00:00,  5.91it/s]16 02:53:34 Save the image 01000N.png
100%|█████████████████████████████████████▉| 1565/1568 [04:24<00:00,  5.89it/s]16 02:53:34 Save the image 01000N_flip.png
100%|█████████████████████████████████████▉| 1566/1568 [04:25<00:00,  5.94it/s]16 02:53:35 Save the image 01001N.png
100%|█████████████████████████████████████▉| 1567/1568 [04:25<00:00,  6.06it/s]16 02:53:35 Save the image 01001N_flip.png
100%|██████████████████████████████████████| 1568/1568 [04:25<00:00,  5.91it/s]
1 unlabeled	99.543%
2 car   	97.360%
3 person	89.765%
4 bike  	90.399%
5 curve 	90.996%
6 car_stop	92.626%
7 guardrail	95.882%
8 color_cone	86.249%
9 bump  	94.563%
----------     mean_IoU	93.043%	freq_IoU	99.134%	mean_pixel_acc	96.913%	pixel_acc	99.557%
16 02:53:35 Evaluation Elapsed Time: 265.40s

# e2

In [12]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E2")

!python eval.py -e 100 -d 0 --split test -p predictions_E2_test

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:54:58 using devices 0
16 02:54:58 Using E2: SegFormer-B2 with FRM and weighted cross-attention fusion
16 02:54:59 Using MLP Decoder
16 02:54:59 Load Model: /home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2_e2/checkpoint/epoch-100.pth
16 02:55:04 Load model, Time usage:
	IO: 4.514350414276123, initialize parameters: 0.04472064971923828
16 02:55:04 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@8.795] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:55:05 Save the image 01402D.png
  0%|                                          | 1/393 [00:01<10:33,  1.62s/it]16 02:55:06 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:01<05:01,  1.30it/s]16 02:55:06 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:01<03:13,  2.01it/s]16 02:55:06 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:02<02:23,  2.71it/s]16 02:55:06 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:02<01:56,  3.33it/s]16 02:55:06 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:02<01:39,  3.90it/s]16 02:55:06 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:02<01:29,  4.33it/s]16 02:55:07 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:02<01:22,  4.69it/s]16 02:55:07 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:02<01:13,  5.24it/s]16 02:55:07 Save the image 01411D.png
  3%|█                                        | 10/393 [00:03<01:11,  5.36it/s]16 02:55:07 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:03<01:09,  5.49it/s]16 02:55:07 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:03<01:08,  5.58it/s]16 02:55:07 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:03<01:08,  5.56it/s]16 02:55:08 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:03<01:06,  5.68it/s]16 02:55:08 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:04<01:06,  5.71it/s]16 02:55:08 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:04<01:05,  5.72it/s]16 02:55:08 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:04<01:01,  6.12it/s]16 02:55:08 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:04<01:03,  5.90it/s]16 02:55:08 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:04<01:03,  5.85it/s]16 02:55:09 Save the image 01421D.png
  5%|██                                       | 20/393 [00:04<01:04,  5.81it/s]16 02:55:09 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:05<01:04,  5.74it/s]16 02:55:09 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:05<01:04,  5.77it/s]16 02:55:09 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:05<01:04,  5.74it/s]16 02:55:09 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:05<01:04,  5.74it/s]16 02:55:09 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:05<01:03,  5.76it/s]16 02:55:10 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:05<01:03,  5.76it/s]16 02:55:10 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:06<01:03,  5.77it/s]16 02:55:10 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:06<01:03,  5.75it/s]16 02:55:10 Save the image 01430D.png
  7%|███                                      | 29/393 [00:06<01:03,  5.76it/s]16 02:55:10 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:06<01:02,  5.80it/s]16 02:55:11 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:06<01:01,  5.85it/s]16 02:55:11 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:06<01:02,  5.79it/s]16 02:55:11 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:07<01:02,  5.79it/s]16 02:55:11 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:07<01:01,  5.80it/s]16 02:55:11 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:07<01:01,  5.79it/s]16 02:55:11 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:07<01:02,  5.74it/s]16 02:55:12 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:07<01:01,  5.76it/s]16 02:55:12 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:07<01:01,  5.77it/s]16 02:55:12 Save the image 01440D.png
 10%|████                                     | 39/393 [00:08<01:00,  5.81it/s]16 02:55:12 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:08<00:58,  6.04it/s]16 02:55:12 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:08<00:59,  5.91it/s]16 02:55:12 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:08<00:59,  5.89it/s]16 02:55:13 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:08<00:59,  5.90it/s]16 02:55:13 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:09<00:59,  5.83it/s]16 02:55:13 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:09<01:00,  5.72it/s]16 02:55:13 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:09<01:00,  5.73it/s]16 02:55:13 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:09<01:00,  5.74it/s]16 02:55:13 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:09<00:56,  6.09it/s]16 02:55:14 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:09<00:57,  5.96it/s]16 02:55:14 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:10<00:58,  5.91it/s]16 02:55:14 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:10<00:58,  5.86it/s]16 02:55:14 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:10<00:59,  5.74it/s]16 02:55:14 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:10<00:59,  5.71it/s]16 02:55:14 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:10<00:59,  5.68it/s]16 02:55:15 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:10<00:59,  5.66it/s]16 02:55:15 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:11<00:56,  5.94it/s]16 02:55:15 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:11<00:57,  5.84it/s]16 02:55:15 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:11<00:57,  5.82it/s]16 02:55:15 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:11<00:57,  5.80it/s]16 02:55:16 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:11<00:57,  5.74it/s]16 02:55:16 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:11<00:58,  5.71it/s]16 02:55:16 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:12<00:57,  5.72it/s]16 02:55:16 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:12<00:57,  5.75it/s]16 02:55:16 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:12<00:53,  6.14it/s]16 02:55:16 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:12<00:54,  5.99it/s]16 02:55:17 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:12<00:55,  5.93it/s]16 02:55:17 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:12<00:55,  5.88it/s]16 02:55:17 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:13<00:55,  5.82it/s]16 02:55:17 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:13<00:55,  5.83it/s]16 02:55:17 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:13<00:55,  5.79it/s]16 02:55:17 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:13<00:55,  5.78it/s]16 02:55:18 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:13<00:52,  6.12it/s]16 02:55:18 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:13<00:53,  5.99it/s]16 02:55:18 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:14<00:53,  5.94it/s]16 02:55:18 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:14<00:54,  5.88it/s]16 02:55:18 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:14<00:54,  5.82it/s]16 02:55:18 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:14<00:54,  5.84it/s]16 02:55:19 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:14<00:54,  5.79it/s]16 02:55:19 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:15<00:54,  5.79it/s]16 02:55:19 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:15<00:54,  5.76it/s]16 02:55:19 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:15<00:54,  5.77it/s]16 02:55:19 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:15<00:53,  5.81it/s]16 02:55:19 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:15<00:53,  5.78it/s]16 02:55:20 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:15<00:53,  5.78it/s]16 02:55:20 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:16<00:52,  5.82it/s]16 02:55:20 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:16<00:52,  5.86it/s]16 02:55:20 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:16<00:52,  5.81it/s]16 02:55:20 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:16<00:52,  5.76it/s]16 02:55:20 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:16<00:52,  5.77it/s]16 02:55:21 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:16<00:52,  5.79it/s]16 02:55:21 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:17<00:52,  5.74it/s]16 02:55:21 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:17<00:52,  5.73it/s]16 02:55:21 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:17<00:52,  5.74it/s]16 02:55:21 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:17<00:52,  5.75it/s]16 02:55:21 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:17<00:48,  6.08it/s]16 02:55:22 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:17<00:49,  5.96it/s]16 02:55:22 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:18<00:49,  5.93it/s]16 02:55:22 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:18<00:49,  5.92it/s]16 02:55:22 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:18<00:50,  5.85it/s]16 02:55:22 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:18<00:50,  5.80it/s]16 02:55:23 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:18<00:50,  5.73it/s]16 02:55:23 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:18<00:50,  5.71it/s]16 02:55:23 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:19<00:47,  6.08it/s]16 02:55:23 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:19<00:48,  5.95it/s]16 02:55:23 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:19<00:48,  5.91it/s]16 02:55:23 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:19<00:49,  5.85it/s]16 02:55:24 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:19<00:49,  5.81it/s]16 02:55:24 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:19<00:48,  5.82it/s]16 02:55:24 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:20<00:49,  5.77it/s]16 02:55:24 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:20<00:48,  5.78it/s]16 02:55:24 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:20<00:46,  6.12it/s]16 02:55:24 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:20<00:47,  5.95it/s]16 02:55:25 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:20<00:47,  5.91it/s]16 02:55:25 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:20<00:47,  5.89it/s]16 02:55:25 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:21<00:47,  5.82it/s]16 02:55:25 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:21<00:47,  5.84it/s]16 02:55:25 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:21<00:47,  5.78it/s]16 02:55:25 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:21<00:47,  5.77it/s]16 02:55:26 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:21<00:47,  5.75it/s]16 02:55:26 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:22<00:47,  5.73it/s]16 02:55:26 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:22<00:47,  5.74it/s]16 02:55:26 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:22<00:47,  5.73it/s]16 02:55:26 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:22<00:47,  5.71it/s]16 02:55:26 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:22<00:46,  5.76it/s]16 02:55:27 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:22<00:46,  5.82it/s]16 02:55:27 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:23<00:46,  5.77it/s]16 02:55:27 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:23<00:46,  5.75it/s]16 02:55:27 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:23<00:46,  5.75it/s]16 02:55:27 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:23<00:45,  5.78it/s]16 02:55:28 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:23<00:45,  5.75it/s]16 02:55:28 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:23<00:45,  5.72it/s]16 02:55:28 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:24<00:45,  5.72it/s]16 02:55:28 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:24<00:45,  5.74it/s]16 02:55:28 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:24<00:42,  6.10it/s]16 02:55:28 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:24<00:43,  5.96it/s]16 02:55:29 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:24<00:43,  5.91it/s]16 02:55:29 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:24<00:43,  5.89it/s]16 02:55:29 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:25<00:43,  5.80it/s]16 02:55:29 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:25<00:44,  5.76it/s]16 02:55:29 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:25<00:44,  5.72it/s]16 02:55:29 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:25<00:44,  5.69it/s]16 02:55:30 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:25<00:41,  6.03it/s]16 02:55:30 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:25<00:42,  5.92it/s]16 02:55:30 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:26<00:42,  5.89it/s]16 02:55:30 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:26<00:42,  5.86it/s]16 02:55:30 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:26<00:42,  5.80it/s]16 02:55:30 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:26<00:42,  5.83it/s]16 02:55:31 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:26<00:42,  5.78it/s]16 02:55:31 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:27<00:42,  5.76it/s]16 02:55:31 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:27<00:42,  5.75it/s]16 02:55:31 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:27<00:42,  5.75it/s]16 02:55:31 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:27<00:42,  5.74it/s]16 02:55:31 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:27<00:41,  5.74it/s]16 02:55:32 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:27<00:41,  5.75it/s]16 02:55:32 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:28<00:41,  5.79it/s]16 02:55:32 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:28<00:40,  5.84it/s]16 02:55:32 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:28<00:41,  5.72it/s]16 02:55:32 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:28<00:41,  5.69it/s]16 02:55:33 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:28<00:40,  5.72it/s]16 02:55:33 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:28<00:41,  5.67it/s]16 02:55:33 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:29<00:41,  5.64it/s]16 02:55:33 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:29<00:41,  5.62it/s]16 02:55:33 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:29<00:40,  5.64it/s]16 02:55:33 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:29<00:40,  5.68it/s]16 02:55:34 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:29<00:39,  5.80it/s]16 02:55:34 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:30<00:39,  5.75it/s]16 02:55:34 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:30<00:39,  5.72it/s]16 02:55:34 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:30<00:39,  5.71it/s]16 02:55:34 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:30<00:39,  5.62it/s]16 02:55:34 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:30<00:41,  5.43it/s]16 02:55:35 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:30<00:40,  5.47it/s]16 02:55:35 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:31<00:40,  5.52it/s]16 02:55:35 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:31<00:37,  5.89it/s]16 02:55:35 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:31<00:37,  5.83it/s]16 02:55:35 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:31<00:37,  5.79it/s]16 02:55:36 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:31<00:37,  5.76it/s]16 02:55:36 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:31<00:37,  5.70it/s]16 02:55:36 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:32<00:37,  5.70it/s]16 02:55:36 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:32<00:37,  5.73it/s]16 02:55:36 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:32<00:37,  5.75it/s]16 02:55:36 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:32<00:34,  6.12it/s]16 02:55:37 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:32<00:35,  5.98it/s]16 02:55:37 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:32<00:35,  5.93it/s]16 02:55:37 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:33<00:35,  5.91it/s]16 02:55:37 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:33<00:35,  5.84it/s]16 02:55:37 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:33<00:35,  5.84it/s]16 02:55:37 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:33<00:35,  5.82it/s]16 02:55:38 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:33<00:35,  5.81it/s]16 02:55:38 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:33<00:33,  6.13it/s]16 02:55:38 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:34<00:34,  5.94it/s]16 02:55:38 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:34<00:34,  5.86it/s]16 02:55:38 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:34<00:34,  5.81it/s]16 02:55:38 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:34<00:34,  5.78it/s]16 02:55:39 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:34<00:34,  5.83it/s]16 02:55:39 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:35<00:34,  5.78it/s]16 02:55:39 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:35<00:34,  5.78it/s]16 02:55:39 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:35<00:32,  6.11it/s]16 02:55:39 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:35<00:32,  5.92it/s]16 02:55:39 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:35<00:33,  5.78it/s]16 02:55:40 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:35<00:33,  5.75it/s]16 02:55:40 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:36<00:33,  5.69it/s]16 02:55:40 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:36<00:33,  5.75it/s]16 02:55:40 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:36<00:33,  5.73it/s]16 02:55:40 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:36<00:32,  5.73it/s]16 02:55:40 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:36<00:32,  5.72it/s]16 02:55:41 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:36<00:32,  5.76it/s]16 02:55:41 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:37<00:32,  5.79it/s]16 02:55:41 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:37<00:32,  5.78it/s]16 02:55:41 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:37<00:31,  5.77it/s]16 02:55:41 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:37<00:31,  5.82it/s]16 02:55:42 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:37<00:31,  5.82it/s]16 02:55:42 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:37<00:31,  5.78it/s]16 02:55:42 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:38<00:31,  5.74it/s]16 02:55:42 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:38<00:31,  5.71it/s]16 02:55:42 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:38<00:30,  5.75it/s]16 02:55:42 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:38<00:30,  5.75it/s]16 02:55:43 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:38<00:30,  5.78it/s]16 02:55:43 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:38<00:30,  5.80it/s]16 02:55:43 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:39<00:29,  5.85it/s]16 02:55:43 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:39<00:29,  5.77it/s]16 02:55:43 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:39<00:29,  5.76it/s]16 02:55:43 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:39<00:29,  5.77it/s]16 02:55:44 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:39<00:29,  5.81it/s]16 02:55:44 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:40<00:29,  5.76it/s]16 02:55:44 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:40<00:29,  5.78it/s]16 02:55:44 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:40<00:29,  5.75it/s]16 02:55:44 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:40<00:28,  5.80it/s]16 02:55:44 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:40<00:28,  5.85it/s]16 02:55:45 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:40<00:28,  5.80it/s]16 02:55:45 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:41<00:27,  5.83it/s]16 02:55:45 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:41<00:27,  5.85it/s]16 02:55:45 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:41<00:27,  5.82it/s]16 02:55:45 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:41<00:27,  5.84it/s]16 02:55:45 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:41<00:27,  5.83it/s]16 02:55:46 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:41<00:26,  5.88it/s]16 02:55:46 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:42<00:26,  6.01it/s]16 02:55:46 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:42<00:26,  5.92it/s]16 02:55:46 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:42<00:26,  5.90it/s]16 02:55:46 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:42<00:26,  5.91it/s]16 02:55:46 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:42<00:26,  5.84it/s]16 02:55:47 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:42<00:26,  5.82it/s]16 02:55:47 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:43<00:26,  5.78it/s]16 02:55:47 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:43<00:26,  5.76it/s]16 02:55:47 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:43<00:24,  6.08it/s]16 02:55:47 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:43<00:25,  5.91it/s]16 02:55:48 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:43<00:25,  5.87it/s]16 02:55:48 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:43<00:24,  5.86it/s]16 02:55:48 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:44<00:24,  5.81it/s]16 02:55:48 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:44<00:25,  5.75it/s]16 02:55:48 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:44<00:24,  5.74it/s]16 02:55:48 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:44<00:24,  5.75it/s]16 02:55:49 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:44<00:23,  6.08it/s]16 02:55:49 Save the image 01236N.png

 64%|█████████████████████████▊              | 253/393 [00:44<00:23,  5.96it/s]16 02:55:49 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:45<00:23,  5.93it/s]16 02:55:49 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:45<00:23,  5.90it/s]16 02:55:49 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:45<00:23,  5.84it/s]16 02:55:49 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:45<00:23,  5.84it/s]16 02:55:50 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:45<00:23,  5.85it/s]16 02:55:50 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:45<00:23,  5.81it/s]16 02:55:50 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:46<00:21,  6.22it/s]16 02:55:50 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:46<00:21,  6.06it/s]16 02:55:50 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:46<00:21,  6.01it/s]16 02:55:50 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:46<00:21,  5.99it/s]16 02:55:51 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:46<00:21,  5.88it/s]16 02:55:51 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:46<00:21,  5.85it/s]16 02:55:51 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:47<00:21,  5.77it/s]16 02:55:51 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:47<00:21,  5.73it/s]16 02:55:51 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:47<00:20,  6.07it/s]16 02:55:51 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:47<00:20,  5.94it/s]16 02:55:52 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:47<00:20,  5.87it/s]16 02:55:52 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:48<00:20,  5.86it/s]16 02:55:52 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:48<00:20,  5.80it/s]16 02:55:52 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:48<00:20,  5.78it/s]16 02:55:52 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:48<00:20,  5.77it/s]16 02:55:52 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:48<00:20,  5.67it/s]16 02:55:53 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:48<00:19,  6.01it/s]16 02:55:53 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:49<00:19,  5.90it/s]16 02:55:53 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:49<00:19,  5.88it/s]16 02:55:53 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:49<00:19,  5.87it/s]16 02:55:53 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:49<00:19,  5.78it/s]16 02:55:53 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:49<00:19,  5.76it/s]16 02:55:54 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:49<00:19,  5.76it/s]16 02:55:54 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:50<00:19,  5.78it/s]16 02:55:54 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:50<00:17,  6.17it/s]16 02:55:54 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:50<00:17,  6.02it/s]16 02:55:54 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:50<00:18,  5.91it/s]16 02:55:54 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:50<00:18,  5.83it/s]16 02:55:55 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:50<00:18,  5.77it/s]16 02:55:55 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:51<00:18,  5.76it/s]16 02:55:55 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:51<00:17,  5.79it/s]16 02:55:55 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:51<00:17,  5.79it/s]16 02:55:55 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:51<00:16,  6.07it/s]16 02:55:56 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:51<00:16,  5.93it/s]16 02:55:56 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:51<00:16,  5.86it/s]16 02:55:56 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:52<00:16,  5.82it/s]16 02:55:56 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:52<00:16,  5.77it/s]16 02:55:56 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:52<00:16,  5.69it/s]16 02:55:56 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:52<00:16,  5.67it/s]16 02:55:57 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:52<00:16,  5.66it/s]16 02:55:57 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:52<00:15,  6.02it/s]16 02:55:57 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:53<00:15,  5.89it/s]16 02:55:57 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:53<00:15,  5.80it/s]16 02:55:57 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:53<00:15,  5.78it/s]16 02:55:57 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:53<00:15,  5.73it/s]16 02:55:58 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:53<00:15,  5.70it/s]16 02:55:58 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:54<00:15,  5.72it/s]16 02:55:58 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:54<00:14,  5.74it/s]16 02:55:58 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:54<00:13,  6.10it/s]16 02:55:58 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:54<00:14,  5.89it/s]16 02:55:58 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:54<00:14,  5.86it/s]16 02:55:59 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:54<00:14,  5.82it/s]16 02:55:59 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:55<00:14,  5.77it/s]16 02:55:59 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:55<00:14,  5.71it/s]16 02:55:59 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:55<00:13,  5.71it/s]16 02:55:59 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:55<00:13,  5.69it/s]16 02:55:59 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:55<00:12,  6.05it/s]16 02:56:00 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:55<00:12,  5.94it/s]16 02:56:00 Save the image 01301N.png

 81%|████████████████████████████████▎       | 318/393 [00:56<00:12,  5.88it/s]16 02:56:00 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:56<00:12,  5.87it/s]16 02:56:00 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:56<00:12,  5.78it/s]16 02:56:00 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:56<00:12,  5.70it/s]16 02:56:01 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:56<00:12,  5.68it/s]16 02:56:01 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [00:56<00:12,  5.69it/s]16 02:56:01 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:57<00:11,  6.00it/s]16 02:56:01 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:57<00:11,  5.89it/s]16 02:56:01 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:57<00:11,  5.89it/s]16 02:56:01 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:57<00:11,  5.86it/s]16 02:56:02 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:57<00:11,  5.78it/s]16 02:56:02 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:57<00:11,  5.70it/s]16 02:56:02 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:58<00:11,  5.70it/s]16 02:56:02 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:58<00:11,  5.62it/s]16 02:56:02 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [00:58<00:10,  5.76it/s]16 02:56:02 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:58<00:10,  5.73it/s]16 02:56:03 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [00:58<00:10,  5.76it/s]16 02:56:03 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [00:59<00:10,  5.73it/s]16 02:56:03 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [00:59<00:10,  5.66it/s]16 02:56:03 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [00:59<00:09,  5.73it/s]16 02:56:03 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [00:59<00:09,  5.70it/s]16 02:56:03 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [00:59<00:09,  5.69it/s]16 02:56:04 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [00:59<00:09,  5.72it/s]16 02:56:04 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [01:00<00:09,  5.73it/s]16 02:56:04 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [01:00<00:08,  5.76it/s]16 02:56:04 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [01:00<00:08,  5.75it/s]16 02:56:04 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [01:00<00:08,  5.73it/s]16 02:56:05 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [01:00<00:08,  5.76it/s]16 02:56:05 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [01:00<00:08,  5.79it/s]16 02:56:05 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [01:01<00:07,  5.78it/s]16 02:56:05 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [01:01<00:07,  5.76it/s]16 02:56:05 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [01:01<00:07,  5.75it/s]16 02:56:05 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [01:01<00:07,  5.72it/s]16 02:56:06 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [01:01<00:07,  5.69it/s]16 02:56:06 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [01:02<00:07,  5.71it/s]16 02:56:06 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [01:02<00:07,  5.61it/s]16 02:56:06 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [01:02<00:06,  5.64it/s]16 02:56:06 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [01:02<00:06,  5.85it/s]16 02:56:06 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [01:02<00:06,  5.80it/s]16 02:56:07 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [01:02<00:06,  5.79it/s]16 02:56:07 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [01:03<00:06,  5.81it/s]16 02:56:07 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [01:03<00:05,  5.72it/s]16 02:56:07 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [01:03<00:05,  5.72it/s]16 02:56:07 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [01:03<00:05,  5.70it/s]16 02:56:07 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [01:03<00:05,  5.68it/s]16 02:56:08 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [01:03<00:04,  6.04it/s]16 02:56:08 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [01:04<00:04,  5.91it/s]16 02:56:08 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [01:04<00:04,  5.88it/s]16 02:56:08 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [01:04<00:04,  5.88it/s]16 02:56:08 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [01:04<00:04,  5.81it/s]16 02:56:09 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [01:04<00:04,  5.78it/s]16 02:56:09 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [01:04<00:04,  5.80it/s]16 02:56:09 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [01:05<00:04,  5.74it/s]16 02:56:09 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [01:05<00:03,  6.05it/s]16 02:56:09 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [01:05<00:03,  5.95it/s]16 02:56:09 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [01:05<00:03,  5.88it/s]16 02:56:10 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [01:05<00:03,  5.79it/s]16 02:56:10 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [01:05<00:03,  5.66it/s]16 02:56:10 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [01:06<00:03,  5.66it/s]16 02:56:10 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [01:06<00:02,  5.69it/s]16 02:56:10 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [01:06<00:02,  5.72it/s]16 02:56:10 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [01:06<00:02,  6.10it/s]16 02:56:11 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [01:06<00:02,  5.98it/s]16 02:56:11 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [01:06<00:02,  5.91it/s]16 02:56:11 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [01:07<00:01,  5.89it/s]16 02:56:11 Save the image 01366N.png

 97%|██████████████████████████████████████▉ | 383/393 [01:07<00:01,  5.78it/s]16 02:56:11 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [01:07<00:01,  5.72it/s]16 02:56:11 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [01:07<00:01,  5.68it/s]16 02:56:12 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [01:07<00:01,  5.72it/s]16 02:56:12 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [01:08<00:00,  6.10it/s]16 02:56:12 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [01:08<00:00,  5.95it/s]16 02:56:12 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [01:08<00:00,  5.87it/s]16 02:56:12 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [01:08<00:00,  5.87it/s]16 02:56:12 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [01:08<00:00,  5.78it/s]16 02:56:13 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [01:08<00:00,  5.73it/s]16 02:56:13 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [01:09<00:00,  5.69it/s]
1 unlabeled	98.296%
2 car   	89.336%
3 person	75.209%
4 bike  	64.498%
5 curve 	49.209%
6 car_stop	29.546%
7 guardrail	6.311%
8 color_cone	52.058%
9 bump  	56.012%
----------     mean_IoU	57.830%	freq_IoU	96.768%	mean_pixel_acc	67.892%	pixel_acc	98.224%
16 02:56:13 Evaluation Elapsed Time: 69.06s

In [13]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E2")

!python eval.py -e 100 -d 0 --split val -p predictions_E2_val

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:57:23 using devices 0
16 02:57:23 Using E2: SegFormer-B2 with FRM and weighted cross-attention fusion
16 02:57:24 Using MLP Decoder
16 02:57:24 Load Model: /home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2_e2/checkpoint/epoch-100.pth
16 02:57:28 Load model, Time usage:
	IO: 4.229828357696533, initialize parameters: 0.04425406455993652
16 02:57:28 GPU 0 handle 392 data.
  0%|                                                  | 0/392 [00:00<?, ?it/s][ WARN:0@10.499] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:57:32 Save the image 00498D.png
  0%|                                          | 1/392 [00:03<23:00,  3.53s/it]16 02:57:32 Save the image 00499D.png
  1%|▏                                         | 2/392 [00:03<10:08,  1.56s/it]16 02:57:32 Save the image 00500D.png
  1%|▎                                         | 3/392 [00:03<05:59,  1.08it/s]16 02:57:32 Save the image 00501D.png
  1%|▍                                         | 4/392 [00:04<04:01,  1.61it/s]16 02:57:33 Save the image 00502D.png
  1%|▌                                         | 5/392 [00:04<02:58,  2.17it/s]16 02:57:33 Save the image 00503D.png
  2%|▋                                         | 6/392 [00:04<02:20,  2.75it/s]16 02:57:33 Save the image 00504D.png
  2%|▊                                         | 7/392 [00:04<01:56,  3.30it/s]16 02:57:33 Save the image 00505D.png
  2%|▊                                         | 8/392 [00:04<01:42,  3.75it/s]16 02:57:33 Save the image 00506D.png
  2%|▉                                         | 9/392 [00:04<01:31,  4.18it/s]16 02:57:33 Save the image 00507D.png
  3%|█                                        | 10/392 [00:05<01:24,  4.54it/s]16 02:57:34 Save the image 00508D.png
  3%|█▏                                       | 11/392 [00:05<01:18,  4.85it/s]16 02:57:34 Save the image 00509D.png
  3%|█▎                                       | 12/392 [00:05<01:10,  5.36it/s]16 02:57:34 Save the image 00510D.png
  3%|█▎                                       | 13/392 [00:05<01:09,  5.45it/s]16 02:57:34 Save the image 00511D.png
  4%|█▍                                       | 14/392 [00:05<01:08,  5.54it/s]16 02:57:34 Save the image 00512D.png
  4%|█▌                                       | 15/392 [00:05<01:07,  5.61it/s]16 02:57:34 Save the image 00513D.png
  4%|█▋                                       | 16/392 [00:06<01:07,  5.61it/s]16 02:57:35 Save the image 00514D.png
  4%|█▊                                       | 17/392 [00:06<01:05,  5.70it/s]16 02:57:35 Save the image 00515D.png
  5%|█▉                                       | 18/392 [00:06<01:05,  5.67it/s]16 02:57:35 Save the image 00516D.png
  5%|█▉                                       | 19/392 [00:06<01:05,  5.70it/s]16 02:57:35 Save the image 00517D.png
  5%|██                                       | 20/392 [00:06<01:05,  5.72it/s]16 02:57:35 Save the image 00518D.png
  5%|██▏                                      | 21/392 [00:06<01:04,  5.74it/s]16 02:57:36 Save the image 00519D.png
  6%|██▎                                      | 22/392 [00:07<01:04,  5.75it/s]16 02:57:36 Save the image 00520D.png
  6%|██▍                                      | 23/392 [00:07<01:04,  5.73it/s]16 02:57:36 Save the image 00521D.png
  6%|██▌                                      | 24/392 [00:07<01:04,  5.74it/s]16 02:57:36 Save the image 00522D.png
  6%|██▌                                      | 25/392 [00:07<01:03,  5.80it/s]16 02:57:36 Save the image 00523D.png
  7%|██▋                                      | 26/392 [00:07<01:02,  5.83it/s]16 02:57:36 Save the image 00524D.png
  7%|██▊                                      | 27/392 [00:08<01:03,  5.76it/s]16 02:57:37 Save the image 00525D.png
  7%|██▉                                      | 28/392 [00:08<01:03,  5.72it/s]16 02:57:37 Save the image 00526D.png
  7%|███                                      | 29/392 [00:08<01:03,  5.70it/s]16 02:57:37 Save the image 00527D.png
  8%|███▏                                     | 30/392 [00:08<01:03,  5.68it/s]16 02:57:37 Save the image 00528D.png
  8%|███▏                                     | 31/392 [00:08<01:03,  5.65it/s]16 02:57:37 Save the image 00529D.png
  8%|███▎                                     | 32/392 [00:08<01:03,  5.68it/s]16 02:57:37 Save the image 00530D.png
  8%|███▍                                     | 33/392 [00:09<01:03,  5.67it/s]16 02:57:38 Save the image 00531D.png
  9%|███▌                                     | 34/392 [00:09<01:02,  5.74it/s]16 02:57:38 Save the image 00532D.png
  9%|███▋                                     | 35/392 [00:09<01:01,  5.76it/s]16 02:57:38 Save the image 00533D.png
  9%|███▊                                     | 36/392 [00:09<01:01,  5.74it/s]16 02:57:38 Save the image 00534D.png
  9%|███▊                                     | 37/392 [00:09<01:01,  5.77it/s]16 02:57:38 Save the image 00535D.png
 10%|███▉                                     | 38/392 [00:09<01:01,  5.77it/s]16 02:57:38 Save the image 00536D.png
 10%|████                                     | 39/392 [00:10<01:01,  5.78it/s]16 02:57:39 Save the image 00537D.png
 10%|████▏                                    | 40/392 [00:10<01:01,  5.75it/s]16 02:57:39 Save the image 00538D.png
 10%|████▎                                    | 41/392 [00:10<01:01,  5.75it/s]16 02:57:39 Save the image 00539D.png
 11%|████▍                                    | 42/392 [00:10<01:00,  5.75it/s]16 02:57:39 Save the image 00540D.png
 11%|████▍                                    | 43/392 [00:10<00:57,  6.10it/s]16 02:57:39 Save the image 00541D.png
 11%|████▌                                    | 44/392 [00:10<00:58,  5.97it/s]16 02:57:39 Save the image 00542D.png
 11%|████▋                                    | 45/392 [00:11<00:58,  5.92it/s]16 02:57:40 Save the image 00543D.png
 12%|████▊                                    | 46/392 [00:11<00:58,  5.91it/s]16 02:57:40 Save the image 00544D.png
 12%|████▉                                    | 47/392 [00:11<00:59,  5.84it/s]16 02:57:40 Save the image 00545D.png
 12%|█████                                    | 48/392 [00:11<00:59,  5.79it/s]16 02:57:40 Save the image 00546D.png
 12%|█████▏                                   | 49/392 [00:11<00:59,  5.78it/s]16 02:57:40 Save the image 00547D.png
 13%|█████▏                                   | 50/392 [00:12<00:59,  5.77it/s]16 02:57:40 Save the image 00548D.png
 13%|█████▎                                   | 51/392 [00:12<00:56,  6.09it/s]16 02:57:41 Save the image 00549D.png
 13%|█████▍                                   | 52/392 [00:12<00:57,  5.90it/s]16 02:57:41 Save the image 00550D.png
 14%|█████▌                                   | 53/392 [00:12<00:57,  5.87it/s]16 02:57:41 Save the image 00551D.png
 14%|█████▋                                   | 54/392 [00:12<00:57,  5.83it/s]16 02:57:41 Save the image 00552D.png
 14%|█████▊                                   | 55/392 [00:12<00:58,  5.77it/s]16 02:57:41 Save the image 00553D.png
 14%|█████▊                                   | 56/392 [00:13<00:58,  5.77it/s]16 02:57:42 Save the image 00554D.png
 15%|█████▉                                   | 57/392 [00:13<00:58,  5.72it/s]16 02:57:42 Save the image 00555D.png

 15%|██████                                   | 58/392 [00:13<00:58,  5.73it/s]16 02:57:42 Save the image 00556D.png
 15%|██████▏                                  | 59/392 [00:13<00:54,  6.07it/s]16 02:57:42 Save the image 00557D.png
 15%|██████▎                                  | 60/392 [00:13<00:55,  5.94it/s]16 02:57:42 Save the image 00558D.png
 16%|██████▍                                  | 61/392 [00:13<00:56,  5.85it/s]16 02:57:42 Save the image 00559D.png
 16%|██████▍                                  | 62/392 [00:14<00:56,  5.84it/s]16 02:57:43 Save the image 00560D.png
 16%|██████▌                                  | 63/392 [00:14<00:57,  5.76it/s]16 02:57:43 Save the image 00561D.png
 16%|██████▋                                  | 64/392 [00:14<00:56,  5.81it/s]16 02:57:43 Save the image 00562D.png
 17%|██████▊                                  | 65/392 [00:14<00:56,  5.80it/s]16 02:57:43 Save the image 00563D.png
 17%|██████▉                                  | 66/392 [00:14<00:56,  5.79it/s]16 02:57:43 Save the image 00564D.png
 17%|███████                                  | 67/392 [00:14<00:53,  6.13it/s]16 02:57:43 Save the image 00565D.png
 17%|███████                                  | 68/392 [00:15<00:54,  5.93it/s]16 02:57:44 Save the image 00566D.png
 18%|███████▏                                 | 69/392 [00:15<00:55,  5.86it/s]16 02:57:44 Save the image 00567D.png
 18%|███████▎                                 | 70/392 [00:15<00:55,  5.80it/s]16 02:57:44 Save the image 00568D.png
 18%|███████▍                                 | 71/392 [00:15<00:55,  5.77it/s]16 02:57:44 Save the image 00569D.png
 18%|███████▌                                 | 72/392 [00:15<00:54,  5.82it/s]16 02:57:44 Save the image 00570D.png
 19%|███████▋                                 | 73/392 [00:15<00:55,  5.78it/s]16 02:57:44 Save the image 00571D.png
 19%|███████▋                                 | 74/392 [00:16<00:55,  5.74it/s]16 02:57:45 Save the image 00572D.png
 19%|███████▊                                 | 75/392 [00:16<00:52,  6.05it/s]16 02:57:45 Save the image 00573D.png
 19%|███████▉                                 | 76/392 [00:16<00:53,  5.90it/s]16 02:57:45 Save the image 00574D.png
 20%|████████                                 | 77/392 [00:16<00:53,  5.86it/s]16 02:57:45 Save the image 00575D.png
 20%|████████▏                                | 78/392 [00:16<00:53,  5.83it/s]16 02:57:45 Save the image 00576D.png
 20%|████████▎                                | 79/392 [00:16<00:54,  5.77it/s]16 02:57:45 Save the image 00577D.png
 20%|████████▎                                | 80/392 [00:17<00:53,  5.81it/s]16 02:57:46 Save the image 00578D.png
 21%|████████▍                                | 81/392 [00:17<00:53,  5.77it/s]16 02:57:46 Save the image 00579D.png
 21%|████████▌                                | 82/392 [00:17<00:53,  5.77it/s]16 02:57:46 Save the image 00580D.png
 21%|████████▋                                | 83/392 [00:17<00:53,  5.77it/s]16 02:57:46 Save the image 00581D.png
 21%|████████▊                                | 84/392 [00:17<00:53,  5.76it/s]16 02:57:46 Save the image 00582D.png
 22%|████████▉                                | 85/392 [00:18<00:53,  5.79it/s]16 02:57:47 Save the image 00583D.png
 22%|████████▉                                | 86/392 [00:18<00:52,  5.78it/s]16 02:57:47 Save the image 00584D.png
 22%|█████████                                | 87/392 [00:18<00:53,  5.72it/s]16 02:57:47 Save the image 00585D.png
 22%|█████████▏                               | 88/392 [00:18<00:53,  5.72it/s]16 02:57:47 Save the image 00586D.png
 23%|█████████▎                               | 89/392 [00:18<00:52,  5.73it/s]16 02:57:47 Save the image 00587D.png
 23%|█████████▍                               | 90/392 [00:18<00:53,  5.68it/s]16 02:57:47 Save the image 00588D.png
 23%|█████████▌                               | 91/392 [00:19<00:52,  5.69it/s]16 02:57:48 Save the image 00589D.png
 23%|█████████▌                               | 92/392 [00:19<00:52,  5.69it/s]16 02:57:48 Save the image 00590D.png
 24%|█████████▋                               | 93/392 [00:19<00:52,  5.69it/s]16 02:57:48 Save the image 00591D.png
 24%|█████████▊                               | 94/392 [00:19<00:52,  5.69it/s]16 02:57:48 Save the image 00592D.png
 24%|█████████▉                               | 95/392 [00:19<00:51,  5.71it/s]16 02:57:48 Save the image 00593D.png
 24%|██████████                               | 96/392 [00:19<00:51,  5.70it/s]16 02:57:48 Save the image 00594D.png
 25%|██████████▏                              | 97/392 [00:20<00:51,  5.76it/s]16 02:57:49 Save the image 00595D.png
 25%|██████████▎                              | 98/392 [00:20<00:49,  5.89it/s]16 02:57:49 Save the image 00596D.png
 25%|██████████▎                              | 99/392 [00:20<00:50,  5.82it/s]16 02:57:49 Save the image 00597D.png
 26%|██████████▏                             | 100/392 [00:20<00:50,  5.76it/s]16 02:57:49 Save the image 00598D.png
 26%|██████████▎                             | 101/392 [00:20<00:50,  5.76it/s]16 02:57:49 Save the image 00599D.png
 26%|██████████▍                             | 102/392 [00:20<00:50,  5.74it/s]16 02:57:49 Save the image 00600D.png
 26%|██████████▌                             | 103/392 [00:21<00:50,  5.71it/s]16 02:57:50 Save the image 00601D.png
 27%|██████████▌                             | 104/392 [00:21<00:50,  5.72it/s]16 02:57:50 Save the image 00602D.png
 27%|██████████▋                             | 105/392 [00:21<00:50,  5.73it/s]16 02:57:50 Save the image 00603D.png
 27%|██████████▊                             | 106/392 [00:21<00:47,  6.03it/s]16 02:57:50 Save the image 00604D.png
 27%|██████████▉                             | 107/392 [00:21<00:48,  5.92it/s]16 02:57:50 Save the image 00605D.png
 28%|███████████                             | 108/392 [00:21<00:48,  5.87it/s]16 02:57:51 Save the image 00606D.png
 28%|███████████                             | 109/392 [00:22<00:48,  5.84it/s]16 02:57:51 Save the image 00607D.png
 28%|███████████▏                            | 110/392 [00:22<00:48,  5.78it/s]16 02:57:51 Save the image 00608D.png
 28%|███████████▎                            | 111/392 [00:22<00:48,  5.81it/s]16 02:57:51 Save the image 00609D.png
 29%|███████████▍                            | 112/392 [00:22<00:48,  5.77it/s]16 02:57:51 Save the image 00610D.png
 29%|███████████▌                            | 113/392 [00:22<00:48,  5.77it/s]16 02:57:51 Save the image 00611D.png
 29%|███████████▋                            | 114/392 [00:23<00:48,  5.78it/s]16 02:57:52 Save the image 00612D.png
 29%|███████████▋                            | 115/392 [00:23<00:48,  5.76it/s]16 02:57:52 Save the image 00613D.png
 30%|███████████▊                            | 116/392 [00:23<00:47,  5.75it/s]16 02:57:52 Save the image 00614D.png
 30%|███████████▉                            | 117/392 [00:23<00:48,  5.73it/s]16 02:57:52 Save the image 00615D.png
 30%|████████████                            | 118/392 [00:23<00:47,  5.72it/s]16 02:57:52 Save the image 00616D.png
 30%|████████████▏                           | 119/392 [00:23<00:47,  5.75it/s]16 02:57:52 Save the image 00617D.png
 31%|████████████▏                           | 120/392 [00:24<00:46,  5.79it/s]16 02:57:53 Save the image 00618D.png
 31%|████████████▎                           | 121/392 [00:24<00:47,  5.72it/s]16 02:57:53 Save the image 00619D.png
 31%|████████████▍                           | 122/392 [00:24<00:47,  5.72it/s]16 02:57:53 Save the image 00620D.png

 31%|████████████▌                           | 123/392 [00:24<00:47,  5.71it/s]16 02:57:53 Save the image 00621D.png
 32%|████████████▋                           | 124/392 [00:24<00:46,  5.75it/s]16 02:57:53 Save the image 00622D.png
 32%|████████████▊                           | 125/392 [00:24<00:46,  5.73it/s]16 02:57:53 Save the image 00623D.png
 32%|████████████▊                           | 126/392 [00:25<00:46,  5.71it/s]16 02:57:54 Save the image 00624D.png
 32%|████████████▉                           | 127/392 [00:25<00:46,  5.72it/s]16 02:57:54 Save the image 00625D.png
 33%|█████████████                           | 128/392 [00:25<00:45,  5.79it/s]16 02:57:54 Save the image 00626D.png
 33%|█████████████▏                          | 129/392 [00:25<00:43,  5.98it/s]16 02:57:54 Save the image 00627D.png
 33%|█████████████▎                          | 130/392 [00:25<00:44,  5.83it/s]16 02:57:54 Save the image 00628D.png
 33%|█████████████▎                          | 131/392 [00:25<00:44,  5.81it/s]16 02:57:54 Save the image 00629D.png
 34%|█████████████▍                          | 132/392 [00:26<00:44,  5.78it/s]16 02:57:55 Save the image 00630D.png
 34%|█████████████▌                          | 133/392 [00:26<00:45,  5.74it/s]16 02:57:55 Save the image 00631D.png
 34%|█████████████▋                          | 134/392 [00:26<00:45,  5.73it/s]16 02:57:55 Save the image 00632D.png
 34%|█████████████▊                          | 135/392 [00:26<00:44,  5.72it/s]16 02:57:55 Save the image 00633D.png
 35%|█████████████▉                          | 136/392 [00:26<00:44,  5.72it/s]16 02:57:55 Save the image 00634D.png
 35%|█████████████▉                          | 137/392 [00:26<00:41,  6.10it/s]16 02:57:56 Save the image 00635D.png
 35%|██████████████                          | 138/392 [00:27<00:43,  5.87it/s]16 02:57:56 Save the image 00636D.png
 35%|██████████████▏                         | 139/392 [00:27<00:43,  5.86it/s]16 02:57:56 Save the image 00637D.png
 36%|██████████████▎                         | 140/392 [00:27<00:43,  5.82it/s]16 02:57:56 Save the image 00638D.png
 36%|██████████████▍                         | 141/392 [00:27<00:43,  5.76it/s]16 02:57:56 Save the image 00639D.png
 36%|██████████████▍                         | 142/392 [00:27<00:43,  5.78it/s]16 02:57:56 Save the image 00640D.png
 36%|██████████████▌                         | 143/392 [00:28<00:43,  5.73it/s]16 02:57:57 Save the image 00641D.png
 37%|██████████████▋                         | 144/392 [00:28<00:43,  5.71it/s]16 02:57:57 Save the image 00642D.png
 37%|██████████████▊                         | 145/392 [00:28<00:43,  5.66it/s]16 02:57:57 Save the image 00643D.png
 37%|██████████████▉                         | 146/392 [00:28<00:43,  5.66it/s]16 02:57:57 Save the image 00644D.png
 38%|███████████████                         | 147/392 [00:28<00:43,  5.69it/s]16 02:57:57 Save the image 00645D.png
 38%|███████████████                         | 148/392 [00:28<00:43,  5.64it/s]16 02:57:57 Save the image 00646D.png
 38%|███████████████▏                        | 149/392 [00:29<00:42,  5.66it/s]16 02:57:58 Save the image 00647D.png
 38%|███████████████▎                        | 150/392 [00:29<00:42,  5.68it/s]16 02:57:58 Save the image 00648D.png
 39%|███████████████▍                        | 151/392 [00:29<00:42,  5.69it/s]16 02:57:58 Save the image 00649D.png
 39%|███████████████▌                        | 152/392 [00:29<00:42,  5.67it/s]16 02:57:58 Save the image 00650D.png
 39%|███████████████▌                        | 153/392 [00:29<00:42,  5.66it/s]16 02:57:58 Save the image 00651D.png
 39%|███████████████▋                        | 154/392 [00:29<00:41,  5.69it/s]16 02:57:59 Save the image 00652D.png
 40%|███████████████▊                        | 155/392 [00:30<00:41,  5.73it/s]16 02:57:59 Save the image 00653D.png
 40%|███████████████▉                        | 156/392 [00:30<00:41,  5.66it/s]16 02:57:59 Save the image 00654D.png
 40%|████████████████                        | 157/392 [00:30<00:41,  5.63it/s]16 02:57:59 Save the image 00655D.png
 40%|████████████████                        | 158/392 [00:30<00:41,  5.66it/s]16 02:57:59 Save the image 00656D.png
 41%|████████████████▏                       | 159/392 [00:30<00:40,  5.72it/s]16 02:57:59 Save the image 00657D.png
 41%|████████████████▎                       | 160/392 [00:31<00:38,  5.99it/s]16 02:58:00 Save the image 00658D.png
 41%|████████████████▍                       | 161/392 [00:31<00:39,  5.78it/s]16 02:58:00 Save the image 00659D.png
 41%|████████████████▌                       | 162/392 [00:31<00:40,  5.63it/s]16 02:58:00 Save the image 00660D.png
 42%|████████████████▋                       | 163/392 [00:31<00:41,  5.56it/s]16 02:58:00 Save the image 00661D.png
 42%|████████████████▋                       | 164/392 [00:31<00:41,  5.49it/s]16 02:58:00 Save the image 00662D.png
 42%|████████████████▊                       | 165/392 [00:31<00:40,  5.54it/s]16 02:58:00 Save the image 00663D.png
 42%|████████████████▉                       | 166/392 [00:32<00:40,  5.58it/s]16 02:58:01 Save the image 00664D.png
 43%|█████████████████                       | 167/392 [00:32<00:40,  5.62it/s]16 02:58:01 Save the image 00665D.png
 43%|█████████████████▏                      | 168/392 [00:32<00:39,  5.62it/s]16 02:58:01 Save the image 00666D.png
 43%|█████████████████▏                      | 169/392 [00:32<00:39,  5.64it/s]16 02:58:01 Save the image 00667D.png
 43%|█████████████████▎                      | 170/392 [00:32<00:39,  5.67it/s]16 02:58:01 Save the image 00668D.png
 44%|█████████████████▍                      | 171/392 [00:33<00:39,  5.65it/s]16 02:58:02 Save the image 00669D.png
 44%|█████████████████▌                      | 172/392 [00:33<00:39,  5.60it/s]16 02:58:02 Save the image 00670D.png
 44%|█████████████████▋                      | 173/392 [00:33<00:38,  5.65it/s]16 02:58:02 Save the image 00671D.png
 44%|█████████████████▊                      | 174/392 [00:33<00:38,  5.68it/s]16 02:58:02 Save the image 00672D.png
 45%|█████████████████▊                      | 175/392 [00:33<00:38,  5.63it/s]16 02:58:02 Save the image 00673D.png
 45%|█████████████████▉                      | 176/392 [00:33<00:39,  5.51it/s]16 02:58:02 Save the image 00674D.png
 45%|██████████████████                      | 177/392 [00:34<00:38,  5.59it/s]16 02:58:03 Save the image 00675D.png
 45%|██████████████████▏                     | 178/392 [00:34<00:37,  5.66it/s]16 02:58:03 Save the image 00676D.png
 46%|██████████████████▎                     | 179/392 [00:34<00:37,  5.64it/s]16 02:58:03 Save the image 00677D.png
 46%|██████████████████▎                     | 180/392 [00:34<00:37,  5.64it/s]16 02:58:03 Save the image 01377D.png
 46%|██████████████████▍                     | 181/392 [00:34<00:37,  5.64it/s]16 02:58:03 Save the image 01378D.png
 46%|██████████████████▌                     | 182/392 [00:34<00:37,  5.66it/s]16 02:58:03 Save the image 01379D.png
 47%|██████████████████▋                     | 183/392 [00:35<00:34,  6.02it/s]16 02:58:04 Save the image 01380D.png
 47%|██████████████████▊                     | 184/392 [00:35<00:35,  5.88it/s]16 02:58:04 Save the image 01381D.png
 47%|██████████████████▉                     | 185/392 [00:35<00:35,  5.81it/s]16 02:58:04 Save the image 01382D.png
 47%|██████████████████▉                     | 186/392 [00:35<00:35,  5.78it/s]16 02:58:04 Save the image 01383D.png
 48%|███████████████████                     | 187/392 [00:35<00:36,  5.68it/s]16 02:58:04 Save the image 01384D.png

 48%|███████████████████▏                    | 188/392 [00:35<00:35,  5.71it/s]16 02:58:05 Save the image 01385D.png
 48%|███████████████████▎                    | 189/392 [00:36<00:35,  5.68it/s]16 02:58:05 Save the image 01386D.png
 48%|███████████████████▍                    | 190/392 [00:36<00:35,  5.71it/s]16 02:58:05 Save the image 01387D.png
 49%|███████████████████▍                    | 191/392 [00:36<00:33,  6.06it/s]16 02:58:05 Save the image 01388D.png
 49%|███████████████████▌                    | 192/392 [00:36<00:33,  5.92it/s]16 02:58:05 Save the image 01389D.png
 49%|███████████████████▋                    | 193/392 [00:36<00:33,  5.86it/s]16 02:58:05 Save the image 01390D.png
 49%|███████████████████▊                    | 194/392 [00:37<00:33,  5.84it/s]16 02:58:06 Save the image 01391D.png
 50%|███████████████████▉                    | 195/392 [00:37<00:34,  5.76it/s]16 02:58:06 Save the image 01392D.png
 50%|████████████████████                    | 196/392 [00:37<00:33,  5.81it/s]16 02:58:06 Save the image 01393D.png
 50%|████████████████████                    | 197/392 [00:37<00:33,  5.74it/s]16 02:58:06 Save the image 01394D.png
 51%|████████████████████▏                   | 198/392 [00:37<00:33,  5.74it/s]16 02:58:06 Save the image 01395D.png
 51%|████████████████████▎                   | 199/392 [00:37<00:33,  5.72it/s]16 02:58:06 Save the image 01396D.png
 51%|████████████████████▍                   | 200/392 [00:38<00:33,  5.70it/s]16 02:58:07 Save the image 01397D.png
 51%|████████████████████▌                   | 201/392 [00:38<00:33,  5.71it/s]16 02:58:07 Save the image 01398D.png
 52%|████████████████████▌                   | 202/392 [00:38<00:33,  5.70it/s]16 02:58:07 Save the image 01399D.png
 52%|████████████████████▋                   | 203/392 [00:38<00:33,  5.71it/s]16 02:58:07 Save the image 01400D.png
 52%|████████████████████▊                   | 204/392 [00:38<00:32,  5.71it/s]16 02:58:07 Save the image 01401D.png
 52%|████████████████████▉                   | 205/392 [00:38<00:32,  5.76it/s]16 02:58:07 Save the image 01002N.png
 53%|█████████████████████                   | 206/392 [00:39<00:32,  5.73it/s]16 02:58:08 Save the image 01003N.png
 53%|█████████████████████                   | 207/392 [00:39<00:32,  5.71it/s]16 02:58:08 Save the image 01004N.png
 53%|█████████████████████▏                  | 208/392 [00:39<00:32,  5.73it/s]16 02:58:08 Save the image 01005N.png
 53%|█████████████████████▎                  | 209/392 [00:39<00:31,  5.76it/s]16 02:58:08 Save the image 01006N.png
 54%|█████████████████████▍                  | 210/392 [00:39<00:31,  5.74it/s]16 02:58:08 Save the image 01007N.png
 54%|█████████████████████▌                  | 211/392 [00:39<00:31,  5.72it/s]16 02:58:08 Save the image 01008N.png
 54%|█████████████████████▋                  | 212/392 [00:40<00:31,  5.75it/s]16 02:58:09 Save the image 01009N.png
 54%|█████████████████████▋                  | 213/392 [00:40<00:31,  5.75it/s]16 02:58:09 Save the image 01010N.png
 55%|█████████████████████▊                  | 214/392 [00:40<00:29,  6.10it/s]16 02:58:09 Save the image 01011N.png
 55%|█████████████████████▉                  | 215/392 [00:40<00:29,  5.96it/s]16 02:58:09 Save the image 01012N.png
 55%|██████████████████████                  | 216/392 [00:40<00:29,  5.92it/s]16 02:58:09 Save the image 01013N.png
 55%|██████████████████████▏                 | 217/392 [00:40<00:29,  5.88it/s]16 02:58:10 Save the image 01014N.png
 56%|██████████████████████▏                 | 218/392 [00:41<00:29,  5.82it/s]16 02:58:10 Save the image 01015N.png
 56%|██████████████████████▎                 | 219/392 [00:41<00:29,  5.77it/s]16 02:58:10 Save the image 01016N.png
 56%|██████████████████████▍                 | 220/392 [00:41<00:30,  5.73it/s]16 02:58:10 Save the image 01017N.png
 56%|██████████████████████▌                 | 221/392 [00:41<00:29,  5.71it/s]16 02:58:10 Save the image 01018N.png
 57%|██████████████████████▋                 | 222/392 [00:41<00:28,  6.06it/s]16 02:58:10 Save the image 01019N.png
 57%|██████████████████████▊                 | 223/392 [00:42<00:28,  5.90it/s]16 02:58:11 Save the image 01020N.png
 57%|██████████████████████▊                 | 224/392 [00:42<00:28,  5.86it/s]16 02:58:11 Save the image 01021N.png
 57%|██████████████████████▉                 | 225/392 [00:42<00:28,  5.81it/s]16 02:58:11 Save the image 01022N.png
 58%|███████████████████████                 | 226/392 [00:42<00:28,  5.76it/s]16 02:58:11 Save the image 01023N.png
 58%|███████████████████████▏                | 227/392 [00:42<00:28,  5.81it/s]16 02:58:11 Save the image 01024N.png
 58%|███████████████████████▎                | 228/392 [00:42<00:28,  5.80it/s]16 02:58:11 Save the image 01025N.png
 58%|███████████████████████▎                | 229/392 [00:43<00:28,  5.78it/s]16 02:58:12 Save the image 01026N.png
 59%|███████████████████████▍                | 230/392 [00:43<00:26,  6.15it/s]16 02:58:12 Save the image 01027N.png
 59%|███████████████████████▌                | 231/392 [00:43<00:26,  6.02it/s]16 02:58:12 Save the image 01028N.png
 59%|███████████████████████▋                | 232/392 [00:43<00:26,  5.96it/s]16 02:58:12 Save the image 01029N.png
 59%|███████████████████████▊                | 233/392 [00:43<00:26,  5.91it/s]16 02:58:12 Save the image 01030N.png
 60%|███████████████████████▉                | 234/392 [00:43<00:27,  5.79it/s]16 02:58:12 Save the image 01031N.png
 60%|███████████████████████▉                | 235/392 [00:44<00:26,  5.83it/s]16 02:58:13 Save the image 01032N.png
 60%|████████████████████████                | 236/392 [00:44<00:26,  5.78it/s]16 02:58:13 Save the image 01033N.png
 60%|████████████████████████▏               | 237/392 [00:44<00:26,  5.77it/s]16 02:58:13 Save the image 01034N.png
 61%|████████████████████████▎               | 238/392 [00:44<00:25,  6.15it/s]16 02:58:13 Save the image 01035N.png
 61%|████████████████████████▍               | 239/392 [00:44<00:25,  5.99it/s]16 02:58:13 Save the image 01036N.png
 61%|████████████████████████▍               | 240/392 [00:44<00:25,  5.88it/s]16 02:58:13 Save the image 01037N.png
 61%|████████████████████████▌               | 241/392 [00:45<00:25,  5.87it/s]16 02:58:14 Save the image 01038N.png
 62%|████████████████████████▋               | 242/392 [00:45<00:26,  5.77it/s]16 02:58:14 Save the image 01039N.png
 62%|████████████████████████▊               | 243/392 [00:45<00:25,  5.74it/s]16 02:58:14 Save the image 01040N.png
 62%|████████████████████████▉               | 244/392 [00:45<00:25,  5.70it/s]16 02:58:14 Save the image 01041N.png
 62%|█████████████████████████               | 245/392 [00:45<00:25,  5.71it/s]16 02:58:14 Save the image 01042N.png
 63%|█████████████████████████               | 246/392 [00:45<00:23,  6.09it/s]16 02:58:14 Save the image 01043N.png
 63%|█████████████████████████▏              | 247/392 [00:46<00:24,  5.96it/s]16 02:58:15 Save the image 01044N.png
 63%|█████████████████████████▎              | 248/392 [00:46<00:24,  5.91it/s]16 02:58:15 Save the image 01045N.png
 64%|█████████████████████████▍              | 249/392 [00:46<00:24,  5.84it/s]16 02:58:15 Save the image 01046N.png
 64%|█████████████████████████▌              | 250/392 [00:46<00:24,  5.76it/s]16 02:58:15 Save the image 01047N.png
 64%|█████████████████████████▌              | 251/392 [00:46<00:24,  5.81it/s]16 02:58:15 Save the image 01048N.png
 64%|█████████████████████████▋              | 252/392 [00:46<00:24,  5.76it/s]16 02:58:15 Save the image 01049N.png

 65%|█████████████████████████▊              | 253/392 [00:47<00:24,  5.75it/s]16 02:58:16 Save the image 01050N.png
 65%|█████████████████████████▉              | 254/392 [00:47<00:23,  5.75it/s]16 02:58:16 Save the image 01051N.png
 65%|██████████████████████████              | 255/392 [00:47<00:23,  5.71it/s]16 02:58:16 Save the image 01052N.png
 65%|██████████████████████████              | 256/392 [00:47<00:23,  5.72it/s]16 02:58:16 Save the image 01053N.png
 66%|██████████████████████████▏             | 257/392 [00:47<00:23,  5.71it/s]16 02:58:16 Save the image 01054N.png
 66%|██████████████████████████▎             | 258/392 [00:48<00:23,  5.68it/s]16 02:58:17 Save the image 01055N.png
 66%|██████████████████████████▍             | 259/392 [00:48<00:23,  5.71it/s]16 02:58:17 Save the image 01056N.png
 66%|██████████████████████████▌             | 260/392 [00:48<00:22,  5.74it/s]16 02:58:17 Save the image 01057N.png
 67%|██████████████████████████▋             | 261/392 [00:48<00:22,  5.71it/s]16 02:58:17 Save the image 01058N.png
 67%|██████████████████████████▋             | 262/392 [00:48<00:22,  5.69it/s]16 02:58:17 Save the image 01059N.png
 67%|██████████████████████████▊             | 263/392 [00:48<00:22,  5.73it/s]16 02:58:17 Save the image 01060N.png
 67%|██████████████████████████▉             | 264/392 [00:49<00:22,  5.75it/s]16 02:58:18 Save the image 01061N.png
 68%|███████████████████████████             | 265/392 [00:49<00:22,  5.71it/s]16 02:58:18 Save the image 01062N.png
 68%|███████████████████████████▏            | 266/392 [00:49<00:22,  5.67it/s]16 02:58:18 Save the image 01063N.png
 68%|███████████████████████████▏            | 267/392 [00:49<00:21,  5.70it/s]16 02:58:18 Save the image 01064N.png
 68%|███████████████████████████▎            | 268/392 [00:49<00:21,  5.72it/s]16 02:58:18 Save the image 01065N.png
 69%|███████████████████████████▍            | 269/392 [00:49<00:20,  6.03it/s]16 02:58:18 Save the image 01066N.png
 69%|███████████████████████████▌            | 270/392 [00:50<00:20,  5.92it/s]16 02:58:19 Save the image 01067N.png
 69%|███████████████████████████▋            | 271/392 [00:50<00:20,  5.89it/s]16 02:58:19 Save the image 01068N.png
 69%|███████████████████████████▊            | 272/392 [00:50<00:20,  5.86it/s]16 02:58:19 Save the image 01069N.png
 70%|███████████████████████████▊            | 273/392 [00:50<00:20,  5.80it/s]16 02:58:19 Save the image 01070N.png
 70%|███████████████████████████▉            | 274/392 [00:50<00:20,  5.81it/s]16 02:58:19 Save the image 01071N.png
 70%|████████████████████████████            | 275/392 [00:50<00:20,  5.80it/s]16 02:58:19 Save the image 01072N.png
 70%|████████████████████████████▏           | 276/392 [00:51<00:20,  5.72it/s]16 02:58:20 Save the image 01073N.png
 71%|████████████████████████████▎           | 277/392 [00:51<00:19,  6.01it/s]16 02:58:20 Save the image 01074N.png
 71%|████████████████████████████▎           | 278/392 [00:51<00:19,  5.89it/s]16 02:58:20 Save the image 01075N.png
 71%|████████████████████████████▍           | 279/392 [00:51<00:19,  5.86it/s]16 02:58:20 Save the image 01076N.png
 71%|████████████████████████████▌           | 280/392 [00:51<00:19,  5.87it/s]16 02:58:20 Save the image 01077N.png
 72%|████████████████████████████▋           | 281/392 [00:51<00:19,  5.81it/s]16 02:58:20 Save the image 01078N.png
 72%|████████████████████████████▊           | 282/392 [00:52<00:19,  5.79it/s]16 02:58:21 Save the image 01079N.png
 72%|████████████████████████████▉           | 283/392 [00:52<00:19,  5.73it/s]16 02:58:21 Save the image 01080N.png
 72%|████████████████████████████▉           | 284/392 [00:52<00:18,  5.75it/s]16 02:58:21 Save the image 01081N.png
 73%|█████████████████████████████           | 285/392 [00:52<00:17,  6.04it/s]16 02:58:21 Save the image 01082N.png
 73%|█████████████████████████████▏          | 286/392 [00:52<00:17,  5.92it/s]16 02:58:21 Save the image 01083N.png
 73%|█████████████████████████████▎          | 287/392 [00:53<00:17,  5.85it/s]16 02:58:22 Save the image 01084N.png
 73%|█████████████████████████████▍          | 288/392 [00:53<00:17,  5.82it/s]16 02:58:22 Save the image 01085N.png
 74%|█████████████████████████████▍          | 289/392 [00:53<00:17,  5.73it/s]16 02:58:22 Save the image 01086N.png
 74%|█████████████████████████████▌          | 290/392 [00:53<00:17,  5.74it/s]16 02:58:22 Save the image 01087N.png
 74%|█████████████████████████████▋          | 291/392 [00:53<00:17,  5.70it/s]16 02:58:22 Save the image 01088N.png
 74%|█████████████████████████████▊          | 292/392 [00:53<00:17,  5.70it/s]16 02:58:22 Save the image 01089N.png
 75%|█████████████████████████████▉          | 293/392 [00:54<00:17,  5.76it/s]16 02:58:23 Save the image 01090N.png
 75%|██████████████████████████████          | 294/392 [00:54<00:16,  5.77it/s]16 02:58:23 Save the image 01091N.png
 75%|██████████████████████████████          | 295/392 [00:54<00:16,  5.78it/s]16 02:58:23 Save the image 01092N.png
 76%|██████████████████████████████▏         | 296/392 [00:54<00:16,  5.78it/s]16 02:58:23 Save the image 01093N.png
 76%|██████████████████████████████▎         | 297/392 [00:54<00:16,  5.76it/s]16 02:58:23 Save the image 01094N.png
 76%|██████████████████████████████▍         | 298/392 [00:54<00:16,  5.81it/s]16 02:58:23 Save the image 01095N.png
 76%|██████████████████████████████▌         | 299/392 [00:55<00:15,  5.86it/s]16 02:58:24 Save the image 01096N.png
 77%|██████████████████████████████▌         | 300/392 [00:55<00:15,  5.81it/s]16 02:58:24 Save the image 01097N.png
 77%|██████████████████████████████▋         | 301/392 [00:55<00:15,  5.73it/s]16 02:58:24 Save the image 01098N.png
 77%|██████████████████████████████▊         | 302/392 [00:55<00:15,  5.71it/s]16 02:58:24 Save the image 01099N.png
 77%|██████████████████████████████▉         | 303/392 [00:55<00:15,  5.72it/s]16 02:58:24 Save the image 01100N.png
 78%|███████████████████████████████         | 304/392 [00:55<00:15,  5.68it/s]16 02:58:24 Save the image 01101N.png
 78%|███████████████████████████████         | 305/392 [00:56<00:15,  5.71it/s]16 02:58:25 Save the image 01102N.png
 78%|███████████████████████████████▏        | 306/392 [00:56<00:15,  5.71it/s]16 02:58:25 Save the image 01103N.png
 78%|███████████████████████████████▎        | 307/392 [00:56<00:14,  5.73it/s]16 02:58:25 Save the image 01104N.png
 79%|███████████████████████████████▍        | 308/392 [00:56<00:14,  5.80it/s]16 02:58:25 Save the image 01105N.png
 79%|███████████████████████████████▌        | 309/392 [00:56<00:14,  5.76it/s]16 02:58:25 Save the image 01106N.png
 79%|███████████████████████████████▋        | 310/392 [00:57<00:14,  5.78it/s]16 02:58:26 Save the image 01107N.png
 79%|███████████████████████████████▋        | 311/392 [00:57<00:14,  5.77it/s]16 02:58:26 Save the image 01108N.png
 80%|███████████████████████████████▊        | 312/392 [00:57<00:13,  5.75it/s]16 02:58:26 Save the image 01109N.png
 80%|███████████████████████████████▉        | 313/392 [00:57<00:13,  5.69it/s]16 02:58:26 Save the image 01110N.png
 80%|████████████████████████████████        | 314/392 [00:57<00:13,  5.70it/s]16 02:58:26 Save the image 01111N.png
 80%|████████████████████████████████▏       | 315/392 [00:57<00:13,  5.71it/s]16 02:58:26 Save the image 01112N.png
 81%|████████████████████████████████▏       | 316/392 [00:58<00:12,  6.05it/s]16 02:58:27 Save the image 01113N.png
 81%|████████████████████████████████▎       | 317/392 [00:58<00:12,  5.92it/s]16 02:58:27 Save the image 01114N.png

 81%|████████████████████████████████▍       | 318/392 [00:58<00:12,  5.87it/s]16 02:58:27 Save the image 01115N.png
 81%|████████████████████████████████▌       | 319/392 [00:58<00:12,  5.84it/s]16 02:58:27 Save the image 01116N.png
 82%|████████████████████████████████▋       | 320/392 [00:58<00:12,  5.79it/s]16 02:58:27 Save the image 01117N.png
 82%|████████████████████████████████▊       | 321/392 [00:58<00:12,  5.72it/s]16 02:58:27 Save the image 01118N.png
 82%|████████████████████████████████▊       | 322/392 [00:59<00:12,  5.70it/s]16 02:58:28 Save the image 01119N.png
 82%|████████████████████████████████▉       | 323/392 [00:59<00:12,  5.70it/s]16 02:58:28 Save the image 01120N.png
 83%|█████████████████████████████████       | 324/392 [00:59<00:11,  5.74it/s]16 02:58:28 Save the image 01121N.png
 83%|█████████████████████████████████▏      | 325/392 [00:59<00:11,  5.73it/s]16 02:58:28 Save the image 01122N.png
 83%|█████████████████████████████████▎      | 326/392 [00:59<00:11,  5.75it/s]16 02:58:28 Save the image 01123N.png
 83%|█████████████████████████████████▎      | 327/392 [00:59<00:11,  5.72it/s]16 02:58:28 Save the image 01124N.png
 84%|█████████████████████████████████▍      | 328/392 [01:00<00:11,  5.69it/s]16 02:58:29 Save the image 01125N.png
 84%|█████████████████████████████████▌      | 329/392 [01:00<00:11,  5.72it/s]16 02:58:29 Save the image 01126N.png
 84%|█████████████████████████████████▋      | 330/392 [01:00<00:10,  5.78it/s]16 02:58:29 Save the image 01127N.png
 84%|█████████████████████████████████▊      | 331/392 [01:00<00:10,  5.75it/s]16 02:58:29 Save the image 01128N.png
 85%|█████████████████████████████████▉      | 332/392 [01:00<00:10,  5.72it/s]16 02:58:29 Save the image 01129N.png
 85%|█████████████████████████████████▉      | 333/392 [01:01<00:10,  5.75it/s]16 02:58:30 Save the image 01130N.png
 85%|██████████████████████████████████      | 334/392 [01:01<00:10,  5.77it/s]16 02:58:30 Save the image 01131N.png
 85%|██████████████████████████████████▏     | 335/392 [01:01<00:09,  5.74it/s]16 02:58:30 Save the image 01132N.png
 86%|██████████████████████████████████▎     | 336/392 [01:01<00:09,  5.75it/s]16 02:58:30 Save the image 01133N.png
 86%|██████████████████████████████████▍     | 337/392 [01:01<00:09,  5.76it/s]16 02:58:30 Save the image 01134N.png
 86%|██████████████████████████████████▍     | 338/392 [01:01<00:09,  5.81it/s]16 02:58:30 Save the image 01135N.png
 86%|██████████████████████████████████▌     | 339/392 [01:02<00:08,  5.96it/s]16 02:58:31 Save the image 01136N.png
 87%|██████████████████████████████████▋     | 340/392 [01:02<00:08,  5.89it/s]16 02:58:31 Save the image 01137N.png
 87%|██████████████████████████████████▊     | 341/392 [01:02<00:08,  5.87it/s]16 02:58:31 Save the image 01138N.png
 87%|██████████████████████████████████▉     | 342/392 [01:02<00:08,  5.86it/s]16 02:58:31 Save the image 01139N.png
 88%|███████████████████████████████████     | 343/392 [01:02<00:08,  5.81it/s]16 02:58:31 Save the image 01140N.png
 88%|███████████████████████████████████     | 344/392 [01:02<00:08,  5.77it/s]16 02:58:31 Save the image 01141N.png
 88%|███████████████████████████████████▏    | 345/392 [01:03<00:08,  5.79it/s]16 02:58:32 Save the image 01142N.png
 88%|███████████████████████████████████▎    | 346/392 [01:03<00:07,  5.77it/s]16 02:58:32 Save the image 01143N.png
 89%|███████████████████████████████████▍    | 347/392 [01:03<00:07,  6.08it/s]16 02:58:32 Save the image 01144N.png
 89%|███████████████████████████████████▌    | 348/392 [01:03<00:07,  5.96it/s]16 02:58:32 Save the image 01145N.png
 89%|███████████████████████████████████▌    | 349/392 [01:03<00:07,  5.92it/s]16 02:58:32 Save the image 01146N.png
 89%|███████████████████████████████████▋    | 350/392 [01:03<00:07,  5.91it/s]16 02:58:32 Save the image 01147N.png
 90%|███████████████████████████████████▊    | 351/392 [01:04<00:07,  5.81it/s]16 02:58:33 Save the image 01148N.png
 90%|███████████████████████████████████▉    | 352/392 [01:04<00:06,  5.74it/s]16 02:58:33 Save the image 01149N.png
 90%|████████████████████████████████████    | 353/392 [01:04<00:06,  5.72it/s]16 02:58:33 Save the image 01150N.png
 90%|████████████████████████████████████    | 354/392 [01:04<00:06,  5.73it/s]16 02:58:33 Save the image 01151N.png
 91%|████████████████████████████████████▏   | 355/392 [01:04<00:06,  5.74it/s]16 02:58:33 Save the image 01152N.png
 91%|████████████████████████████████████▎   | 356/392 [01:04<00:06,  5.74it/s]16 02:58:33 Save the image 01153N.png
 91%|████████████████████████████████████▍   | 357/392 [01:05<00:06,  5.77it/s]16 02:58:34 Save the image 01154N.png
 91%|████████████████████████████████████▌   | 358/392 [01:05<00:05,  5.73it/s]16 02:58:34 Save the image 01155N.png
 92%|████████████████████████████████████▋   | 359/392 [01:05<00:05,  5.72it/s]16 02:58:34 Save the image 01156N.png
 92%|████████████████████████████████████▋   | 360/392 [01:05<00:05,  5.76it/s]16 02:58:34 Save the image 01157N.png
 92%|████████████████████████████████████▊   | 361/392 [01:05<00:05,  5.79it/s]16 02:58:34 Save the image 01158N.png
 92%|████████████████████████████████████▉   | 362/392 [01:06<00:05,  5.74it/s]16 02:58:35 Save the image 01159N.png
 93%|█████████████████████████████████████   | 363/392 [01:06<00:05,  5.70it/s]16 02:58:35 Save the image 01160N.png
 93%|█████████████████████████████████████▏  | 364/392 [01:06<00:04,  5.71it/s]16 02:58:35 Save the image 01161N.png
 93%|█████████████████████████████████████▏  | 365/392 [01:06<00:04,  5.72it/s]16 02:58:35 Save the image 01162N.png
 93%|█████████████████████████████████████▎  | 366/392 [01:06<00:04,  5.69it/s]16 02:58:35 Save the image 01163N.png
 94%|█████████████████████████████████████▍  | 367/392 [01:06<00:04,  5.68it/s]16 02:58:35 Save the image 01164N.png
 94%|█████████████████████████████████████▌  | 368/392 [01:07<00:04,  5.71it/s]16 02:58:36 Save the image 01165N.png
 94%|█████████████████████████████████████▋  | 369/392 [01:07<00:04,  5.68it/s]16 02:58:36 Save the image 01166N.png
 94%|█████████████████████████████████████▊  | 370/392 [01:07<00:03,  5.95it/s]16 02:58:36 Save the image 01167N.png
 95%|█████████████████████████████████████▊  | 371/392 [01:07<00:03,  5.81it/s]16 02:58:36 Save the image 01168N.png
 95%|█████████████████████████████████████▉  | 372/392 [01:07<00:03,  5.79it/s]16 02:58:36 Save the image 01169N.png
 95%|██████████████████████████████████████  | 373/392 [01:07<00:03,  5.80it/s]16 02:58:36 Save the image 01170N.png
 95%|██████████████████████████████████████▏ | 374/392 [01:08<00:03,  5.75it/s]16 02:58:37 Save the image 01171N.png
 96%|██████████████████████████████████████▎ | 375/392 [01:08<00:02,  5.71it/s]16 02:58:37 Save the image 01172N.png
 96%|██████████████████████████████████████▎ | 376/392 [01:08<00:02,  5.72it/s]16 02:58:37 Save the image 01173N.png
 96%|██████████████████████████████████████▍ | 377/392 [01:08<00:02,  5.73it/s]16 02:58:37 Save the image 01174N.png
 96%|██████████████████████████████████████▌ | 378/392 [01:08<00:02,  6.07it/s]16 02:58:37 Save the image 01175N.png
 97%|██████████████████████████████████████▋ | 379/392 [01:08<00:02,  5.92it/s]16 02:58:37 Save the image 01176N.png
 97%|██████████████████████████████████████▊ | 380/392 [01:09<00:02,  5.87it/s]16 02:58:38 Save the image 01177N.png
 97%|██████████████████████████████████████▉ | 381/392 [01:09<00:01,  5.83it/s]16 02:58:38 Save the image 01178N.png
 97%|██████████████████████████████████████▉ | 382/392 [01:09<00:01,  5.77it/s]16 02:58:38 Save the image 01179N.png

 98%|███████████████████████████████████████ | 383/392 [01:09<00:01,  5.82it/s]16 02:58:38 Save the image 01180N.png
 98%|███████████████████████████████████████▏| 384/392 [01:09<00:01,  5.81it/s]16 02:58:38 Save the image 01181N.png
 98%|███████████████████████████████████████▎| 385/392 [01:09<00:01,  5.80it/s]16 02:58:38 Save the image 01182N.png
 98%|███████████████████████████████████████▍| 386/392 [01:10<00:00,  6.17it/s]16 02:58:39 Save the image 01183N.png
 99%|███████████████████████████████████████▍| 387/392 [01:10<00:00,  5.97it/s]16 02:58:39 Save the image 01184N.png
 99%|███████████████████████████████████████▌| 388/392 [01:10<00:00,  5.91it/s]16 02:58:39 Save the image 01185N.png
 99%|███████████████████████████████████████▋| 389/392 [01:10<00:00,  5.86it/s]16 02:58:39 Save the image 01186N.png
 99%|███████████████████████████████████████▊| 390/392 [01:10<00:00,  5.81it/s]16 02:58:39 Save the image 01187N.png
100%|███████████████████████████████████████▉| 391/392 [01:10<00:00,  5.82it/s]16 02:58:39 Save the image 01188N.png
100%|████████████████████████████████████████| 392/392 [01:11<00:00,  5.51it/s]
1 unlabeled	97.783%
2 car   	86.555%
3 person	71.449%
4 bike  	73.042%
5 curve 	38.948%
6 car_stop	41.058%
7 guardrail	45.470%
8 color_cone	58.579%
9 bump  	48.038%
----------     mean_IoU	62.325%	freq_IoU	95.773%	mean_pixel_acc	72.627%	pixel_acc	97.731%
16 02:58:39 Evaluation Elapsed Time: 71.16s

In [14]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E2")

!python eval.py -e 100 -d 0 --split train -p predictions_E2_train

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 02:59:31 using devices 0
16 02:59:31 Using E2: SegFormer-B2 with FRM and weighted cross-attention fusion
16 02:59:32 Using MLP Decoder
16 02:59:32 Load Model: /home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2_e2/checkpoint/epoch-100.pth
16 02:59:36 Load model, Time usage:
	IO: 4.218412637710571, initialize parameters: 0.0432584285736084
16 02:59:36 GPU 0 handle 1568 data.
  0%|                                                 | 0/1568 [00:00<?, ?it/s][ WARN:0@8.359] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 02:59:38 Save the image 00001D.png
  0%|                                         | 1/1568 [00:01<35:58,  1.38s/it]16 02:59:38 Save the image 00001D_flip.png
  0%|                                         | 2/1568 [00:01<17:25,  1.50it/s]16 02:59:38 Save the image 00002D.png
  0%|                                         | 3/1568 [00:01<11:33,  2.26it/s]16 02:59:38 Save the image 00002D_flip.png
  0%|                                         | 4/1568 [00:01<08:44,  2.98it/s]16 02:59:38 Save the image 00055D.png
  0%|▏                                        | 5/1568 [00:02<07:16,  3.58it/s]16 02:59:39 Save the image 00055D_flip.png
  0%|▏                                        | 6/1568 [00:02<06:19,  4.11it/s]16 02:59:39 Save the image 00056D.png
  0%|▏                                        | 7/1568 [00:02<05:27,  4.76it/s]16 02:59:39 Save the image 00056D_flip.png
  1%|▏                                        | 8/1568 [00:02<05:10,  5.02it/s]16 02:59:39 Save the image 00057D.png
  1%|▏                                        | 9/1568 [00:02<04:57,  5.25it/s]16 02:59:39 Save the image 00057D_flip.png
  1%|▎                                       | 10/1568 [00:02<04:47,  5.43it/s]16 02:59:39 Save the image 00058D.png
  1%|▎                                       | 11/1568 [00:03<04:42,  5.50it/s]16 02:59:40 Save the image 00058D_flip.png
  1%|▎                                       | 12/1568 [00:03<04:36,  5.62it/s]16 02:59:40 Save the image 00081D.png
  1%|▎                                       | 13/1568 [00:03<04:35,  5.64it/s]16 02:59:40 Save the image 00081D_flip.png
  1%|▎                                       | 14/1568 [00:03<04:35,  5.64it/s]16 02:59:40 Save the image 00082D.png
  1%|▍                                       | 15/1568 [00:03<04:19,  5.97it/s]16 02:59:40 Save the image 00082D_flip.png
  1%|▍                                       | 16/1568 [00:03<04:24,  5.87it/s]16 02:59:40 Save the image 00083D.png
  1%|▍                                       | 17/1568 [00:04<04:26,  5.81it/s]16 02:59:41 Save the image 00083D_flip.png
  1%|▍                                       | 18/1568 [00:04<04:28,  5.78it/s]16 02:59:41 Save the image 00084D.png
  1%|▍                                       | 19/1568 [00:04<04:32,  5.69it/s]16 02:59:41 Save the image 00084D_flip.png
  1%|▌                                       | 20/1568 [00:04<04:29,  5.75it/s]16 02:59:41 Save the image 00085D.png
  1%|▌                                       | 21/1568 [00:04<04:28,  5.76it/s]16 02:59:41 Save the image 00085D_flip.png
  1%|▌                                       | 22/1568 [00:04<04:28,  5.77it/s]16 02:59:41 Save the image 00086D.png
  1%|▌                                       | 23/1568 [00:05<04:16,  6.02it/s]16 02:59:42 Save the image 00086D_flip.png
  2%|▌                                       | 24/1568 [00:05<04:21,  5.90it/s]16 02:59:42 Save the image 00087D.png
  2%|▋                                       | 25/1568 [00:05<04:23,  5.87it/s]16 02:59:42 Save the image 00087D_flip.png
  2%|▋                                       | 26/1568 [00:05<04:24,  5.84it/s]16 02:59:42 Save the image 00088D.png
  2%|▋                                       | 27/1568 [00:05<04:26,  5.79it/s]16 02:59:42 Save the image 00088D_flip.png
  2%|▋                                       | 28/1568 [00:05<04:24,  5.83it/s]16 02:59:43 Save the image 00091D.png
  2%|▋                                       | 29/1568 [00:06<04:25,  5.79it/s]16 02:59:43 Save the image 00091D_flip.png
  2%|▊                                       | 30/1568 [00:06<04:25,  5.79it/s]16 02:59:43 Save the image 00092D.png
  2%|▊                                       | 31/1568 [00:06<04:25,  5.79it/s]16 02:59:43 Save the image 00092D_flip.png
  2%|▊                                       | 32/1568 [00:06<04:27,  5.75it/s]16 02:59:43 Save the image 00093D.png
  2%|▊                                       | 33/1568 [00:06<04:26,  5.76it/s]16 02:59:43 Save the image 00093D_flip.png
  2%|▊                                       | 34/1568 [00:07<04:26,  5.76it/s]16 02:59:44 Save the image 00094D.png
  2%|▉                                       | 35/1568 [00:07<04:25,  5.77it/s]16 02:59:44 Save the image 00094D_flip.png
  2%|▉                                       | 36/1568 [00:07<04:23,  5.81it/s]16 02:59:44 Save the image 00095D.png
  2%|▉                                       | 37/1568 [00:07<04:22,  5.82it/s]16 02:59:44 Save the image 00095D_flip.png
  2%|▉                                       | 38/1568 [00:07<04:25,  5.77it/s]16 02:59:44 Save the image 00096D.png
  2%|▉                                       | 39/1568 [00:07<04:25,  5.75it/s]16 02:59:44 Save the image 00096D_flip.png
  3%|█                                       | 40/1568 [00:08<04:25,  5.76it/s]16 02:59:45 Save the image 00097D.png
  3%|█                                       | 41/1568 [00:08<04:24,  5.76it/s]16 02:59:45 Save the image 00097D_flip.png
  3%|█                                       | 42/1568 [00:08<04:26,  5.72it/s]16 02:59:45 Save the image 00098D.png
  3%|█                                       | 43/1568 [00:08<04:27,  5.69it/s]16 02:59:45 Save the image 00098D_flip.png
  3%|█                                       | 44/1568 [00:08<04:27,  5.70it/s]16 02:59:45 Save the image 00099D.png
  3%|█▏                                      | 45/1568 [00:08<04:27,  5.69it/s]16 02:59:45 Save the image 00099D_flip.png
  3%|█▏                                      | 46/1568 [00:09<04:12,  6.02it/s]16 02:59:46 Save the image 00100D.png
  3%|█▏                                      | 47/1568 [00:09<04:18,  5.89it/s]16 02:59:46 Save the image 00100D_flip.png
  3%|█▏                                      | 48/1568 [00:09<04:19,  5.85it/s]16 02:59:46 Save the image 00101D.png
  3%|█▎                                      | 49/1568 [00:09<04:21,  5.80it/s]16 02:59:46 Save the image 00101D_flip.png
  3%|█▎                                      | 50/1568 [00:09<04:24,  5.73it/s]16 02:59:46 Save the image 00102D.png
  3%|█▎                                      | 51/1568 [00:09<04:23,  5.75it/s]16 02:59:46 Save the image 00102D_flip.png
  3%|█▎                                      | 52/1568 [00:10<04:24,  5.73it/s]16 02:59:47 Save the image 00103D.png
  3%|█▎                                      | 53/1568 [00:10<04:23,  5.76it/s]16 02:59:47 Save the image 00103D_flip.png
  3%|█▍                                      | 54/1568 [00:10<04:10,  6.04it/s]16 02:59:47 Save the image 00104D.png
  4%|█▍                                      | 55/1568 [00:10<04:17,  5.87it/s]16 02:59:47 Save the image 00104D_flip.png
  4%|█▍                                      | 56/1568 [00:10<04:17,  5.86it/s]16 02:59:47 Save the image 00105D.png

  4%|█▍                                      | 57/1568 [00:10<04:18,  5.84it/s]16 02:59:48 Save the image 00105D_flip.png
  4%|█▍                                      | 58/1568 [00:11<04:20,  5.80it/s]16 02:59:48 Save the image 00106D.png
  4%|█▌                                      | 59/1568 [00:11<04:18,  5.83it/s]16 02:59:48 Save the image 00106D_flip.png
  4%|█▌                                      | 60/1568 [00:11<04:21,  5.78it/s]16 02:59:48 Save the image 00107D.png
  4%|█▌                                      | 61/1568 [00:11<04:20,  5.78it/s]16 02:59:48 Save the image 00107D_flip.png
  4%|█▌                                      | 62/1568 [00:11<04:21,  5.76it/s]16 02:59:48 Save the image 00108D.png
  4%|█▌                                      | 63/1568 [00:12<04:22,  5.74it/s]16 02:59:49 Save the image 00108D_flip.png
  4%|█▋                                      | 64/1568 [00:12<04:21,  5.76it/s]16 02:59:49 Save the image 00109D.png
  4%|█▋                                      | 65/1568 [00:12<04:20,  5.77it/s]16 02:59:49 Save the image 00109D_flip.png
  4%|█▋                                      | 66/1568 [00:12<04:21,  5.74it/s]16 02:59:49 Save the image 00110D.png
  4%|█▋                                      | 67/1568 [00:12<04:19,  5.79it/s]16 02:59:49 Save the image 00110D_flip.png
  4%|█▋                                      | 68/1568 [00:12<04:17,  5.83it/s]16 02:59:49 Save the image 00111D.png
  4%|█▊                                      | 69/1568 [00:13<04:19,  5.79it/s]16 02:59:50 Save the image 00111D_flip.png
  4%|█▊                                      | 70/1568 [00:13<04:19,  5.77it/s]16 02:59:50 Save the image 00112D.png
  5%|█▊                                      | 71/1568 [00:13<04:18,  5.78it/s]16 02:59:50 Save the image 00112D_flip.png
  5%|█▊                                      | 72/1568 [00:13<04:18,  5.79it/s]16 02:59:50 Save the image 00113D.png
  5%|█▊                                      | 73/1568 [00:13<04:19,  5.75it/s]16 02:59:50 Save the image 00113D_flip.png
  5%|█▉                                      | 74/1568 [00:13<04:19,  5.76it/s]16 02:59:50 Save the image 00114D.png
  5%|█▉                                      | 75/1568 [00:14<04:20,  5.74it/s]16 02:59:51 Save the image 00114D_flip.png
  5%|█▉                                      | 76/1568 [00:14<04:17,  5.79it/s]16 02:59:51 Save the image 00115D.png
  5%|█▉                                      | 77/1568 [00:14<04:06,  6.06it/s]16 02:59:51 Save the image 00115D_flip.png
  5%|█▉                                      | 78/1568 [00:14<04:10,  5.94it/s]16 02:59:51 Save the image 00116D.png
  5%|██                                      | 79/1568 [00:14<04:13,  5.88it/s]16 02:59:51 Save the image 00116D_flip.png
  5%|██                                      | 80/1568 [00:14<04:14,  5.85it/s]16 02:59:51 Save the image 00117D.png
  5%|██                                      | 81/1568 [00:15<04:16,  5.79it/s]16 02:59:52 Save the image 00117D_flip.png
  5%|██                                      | 82/1568 [00:15<04:18,  5.75it/s]16 02:59:52 Save the image 00118D.png
  5%|██                                      | 83/1568 [00:15<04:17,  5.77it/s]16 02:59:52 Save the image 00118D_flip.png
  5%|██▏                                     | 84/1568 [00:15<04:16,  5.79it/s]16 02:59:52 Save the image 00119D.png
  5%|██▏                                     | 85/1568 [00:15<04:01,  6.15it/s]16 02:59:52 Save the image 00119D_flip.png
  5%|██▏                                     | 86/1568 [00:15<04:06,  6.00it/s]16 02:59:52 Save the image 00120D.png
  6%|██▏                                     | 87/1568 [00:16<04:09,  5.94it/s]16 02:59:53 Save the image 00120D_flip.png
  6%|██▏                                     | 88/1568 [00:16<04:11,  5.89it/s]16 02:59:53 Save the image 00121D.png
  6%|██▎                                     | 89/1568 [00:16<04:13,  5.82it/s]16 02:59:53 Save the image 00121D_flip.png
  6%|██▎                                     | 90/1568 [00:16<04:15,  5.79it/s]16 02:59:53 Save the image 00122D.png
  6%|██▎                                     | 91/1568 [00:16<04:16,  5.75it/s]16 02:59:53 Save the image 00122D_flip.png
  6%|██▎                                     | 92/1568 [00:17<04:17,  5.73it/s]16 02:59:54 Save the image 00123D.png
  6%|██▎                                     | 93/1568 [00:17<04:03,  6.07it/s]16 02:59:54 Save the image 00123D_flip.png
  6%|██▍                                     | 94/1568 [00:17<04:07,  5.95it/s]16 02:59:54 Save the image 00124D.png
  6%|██▍                                     | 95/1568 [00:17<04:09,  5.91it/s]16 02:59:54 Save the image 00124D_flip.png
  6%|██▍                                     | 96/1568 [00:17<04:08,  5.93it/s]16 02:59:54 Save the image 00125D.png
  6%|██▍                                     | 97/1568 [00:17<04:11,  5.85it/s]16 02:59:54 Save the image 00125D_flip.png
  6%|██▌                                     | 98/1568 [00:18<04:09,  5.89it/s]16 02:59:55 Save the image 00126D.png
  6%|██▌                                     | 99/1568 [00:18<04:11,  5.84it/s]16 02:59:55 Save the image 00126D_flip.png
  6%|██▍                                    | 100/1568 [00:18<04:11,  5.84it/s]16 02:59:55 Save the image 00127D.png
  6%|██▌                                    | 101/1568 [00:18<03:56,  6.21it/s]16 02:59:55 Save the image 00127D_flip.png
  7%|██▌                                    | 102/1568 [00:18<04:02,  6.04it/s]16 02:59:55 Save the image 00128D.png
  7%|██▌                                    | 103/1568 [00:18<04:05,  5.98it/s]16 02:59:55 Save the image 00128D_flip.png
  7%|██▌                                    | 104/1568 [00:19<04:06,  5.94it/s]16 02:59:56 Save the image 00129D.png
  7%|██▌                                    | 105/1568 [00:19<04:09,  5.86it/s]16 02:59:56 Save the image 00129D_flip.png
  7%|██▋                                    | 106/1568 [00:19<04:09,  5.87it/s]16 02:59:56 Save the image 00130D.png
  7%|██▋                                    | 107/1568 [00:19<04:11,  5.81it/s]16 02:59:56 Save the image 00130D_flip.png
  7%|██▋                                    | 108/1568 [00:19<04:11,  5.82it/s]16 02:59:56 Save the image 00131D.png
  7%|██▋                                    | 109/1568 [00:19<04:10,  5.83it/s]16 02:59:56 Save the image 00131D_flip.png
  7%|██▋                                    | 110/1568 [00:20<04:11,  5.79it/s]16 02:59:57 Save the image 00132D.png
  7%|██▊                                    | 111/1568 [00:20<04:11,  5.79it/s]16 02:59:57 Save the image 00132D_flip.png
  7%|██▊                                    | 112/1568 [00:20<04:11,  5.78it/s]16 02:59:57 Save the image 00133D.png
  7%|██▊                                    | 113/1568 [00:20<04:11,  5.78it/s]16 02:59:57 Save the image 00133D_flip.png
  7%|██▊                                    | 114/1568 [00:20<04:09,  5.82it/s]16 02:59:57 Save the image 00134D.png
  7%|██▊                                    | 115/1568 [00:20<04:08,  5.85it/s]16 02:59:57 Save the image 00134D_flip.png
  7%|██▉                                    | 116/1568 [00:21<04:10,  5.80it/s]16 02:59:58 Save the image 00135D.png
  7%|██▉                                    | 117/1568 [00:21<04:11,  5.76it/s]16 02:59:58 Save the image 00135D_flip.png
  8%|██▉                                    | 118/1568 [00:21<04:11,  5.77it/s]16 02:59:58 Save the image 00136D.png
  8%|██▉                                    | 119/1568 [00:21<04:09,  5.80it/s]16 02:59:58 Save the image 00136D_flip.png
  8%|██▉                                    | 120/1568 [00:21<04:10,  5.78it/s]16 02:59:58 Save the image 00137D.png

  8%|███                                    | 121/1568 [00:21<04:10,  5.78it/s]16 02:59:58 Save the image 00137D_flip.png
  8%|███                                    | 122/1568 [00:22<04:10,  5.78it/s]16 02:59:59 Save the image 00138D.png
  8%|███                                    | 123/1568 [00:22<04:07,  5.83it/s]16 02:59:59 Save the image 00138D_flip.png
  8%|███                                    | 124/1568 [00:22<04:01,  5.97it/s]16 02:59:59 Save the image 00139D.png
  8%|███                                    | 125/1568 [00:22<04:04,  5.89it/s]16 02:59:59 Save the image 00139D_flip.png
  8%|███▏                                   | 126/1568 [00:22<04:05,  5.87it/s]16 02:59:59 Save the image 00140D.png
  8%|███▏                                   | 127/1568 [00:22<04:08,  5.81it/s]16 02:59:59 Save the image 00140D_flip.png
  8%|███▏                                   | 128/1568 [00:23<04:09,  5.77it/s]16 03:00:00 Save the image 00141D.png
  8%|███▏                                   | 129/1568 [00:23<04:10,  5.74it/s]16 03:00:00 Save the image 00141D_flip.png
  8%|███▏                                   | 130/1568 [00:23<04:10,  5.75it/s]16 03:00:00 Save the image 00142D.png
  8%|███▎                                   | 131/1568 [00:23<04:10,  5.74it/s]16 03:00:00 Save the image 00142D_flip.png
  8%|███▎                                   | 132/1568 [00:23<03:55,  6.09it/s]16 03:00:00 Save the image 00143D.png
  8%|███▎                                   | 133/1568 [00:24<04:00,  5.96it/s]16 03:00:01 Save the image 00143D_flip.png
  9%|███▎                                   | 134/1568 [00:24<04:05,  5.84it/s]16 03:00:01 Save the image 00144D.png
  9%|███▎                                   | 135/1568 [00:24<04:04,  5.85it/s]16 03:00:01 Save the image 00144D_flip.png
  9%|███▍                                   | 136/1568 [00:24<04:06,  5.80it/s]16 03:00:01 Save the image 00145D.png
  9%|███▍                                   | 137/1568 [00:24<04:05,  5.84it/s]16 03:00:01 Save the image 00145D_flip.png
  9%|███▍                                   | 138/1568 [00:24<04:07,  5.78it/s]16 03:00:01 Save the image 00146D.png
  9%|███▍                                   | 139/1568 [00:25<04:06,  5.80it/s]16 03:00:02 Save the image 00146D_flip.png
  9%|███▍                                   | 140/1568 [00:25<03:50,  6.18it/s]16 03:00:02 Save the image 00147D.png
  9%|███▌                                   | 141/1568 [00:25<03:57,  6.01it/s]16 03:00:02 Save the image 00147D_flip.png
  9%|███▌                                   | 142/1568 [00:25<03:59,  5.96it/s]16 03:00:02 Save the image 00148D.png
  9%|███▌                                   | 143/1568 [00:25<04:01,  5.91it/s]16 03:00:02 Save the image 00148D_flip.png
  9%|███▌                                   | 144/1568 [00:25<04:04,  5.83it/s]16 03:00:02 Save the image 00149D.png
  9%|███▌                                   | 145/1568 [00:26<04:02,  5.87it/s]16 03:00:03 Save the image 00149D_flip.png
  9%|███▋                                   | 146/1568 [00:26<04:04,  5.81it/s]16 03:00:03 Save the image 00150D.png
  9%|███▋                                   | 147/1568 [00:26<04:06,  5.76it/s]16 03:00:03 Save the image 00150D_flip.png
  9%|███▋                                   | 148/1568 [00:26<04:05,  5.78it/s]16 03:00:03 Save the image 00151D.png
 10%|███▋                                   | 149/1568 [00:26<04:06,  5.76it/s]16 03:00:03 Save the image 00151D_flip.png
 10%|███▋                                   | 150/1568 [00:26<04:04,  5.79it/s]16 03:00:03 Save the image 00152D.png
 10%|███▊                                   | 151/1568 [00:27<04:04,  5.80it/s]16 03:00:04 Save the image 00152D_flip.png
 10%|███▊                                   | 152/1568 [00:27<04:05,  5.77it/s]16 03:00:04 Save the image 00153D.png
 10%|███▊                                   | 153/1568 [00:27<04:03,  5.81it/s]16 03:00:04 Save the image 00153D_flip.png
 10%|███▊                                   | 154/1568 [00:27<04:01,  5.85it/s]16 03:00:04 Save the image 00154D.png
 10%|███▊                                   | 155/1568 [00:27<04:03,  5.80it/s]16 03:00:04 Save the image 00154D_flip.png
 10%|███▉                                   | 156/1568 [00:27<04:05,  5.76it/s]16 03:00:04 Save the image 00155D.png
 10%|███▉                                   | 157/1568 [00:28<04:04,  5.77it/s]16 03:00:05 Save the image 00155D_flip.png
 10%|███▉                                   | 158/1568 [00:28<04:03,  5.80it/s]16 03:00:05 Save the image 00156D.png
 10%|███▉                                   | 159/1568 [00:28<04:04,  5.75it/s]16 03:00:05 Save the image 00156D_flip.png
 10%|███▉                                   | 160/1568 [00:28<04:04,  5.76it/s]16 03:00:05 Save the image 00157D.png
 10%|████                                   | 161/1568 [00:28<04:03,  5.78it/s]16 03:00:05 Save the image 00157D_flip.png
 10%|████                                   | 162/1568 [00:28<04:01,  5.82it/s]16 03:00:05 Save the image 00158D.png
 10%|████                                   | 163/1568 [00:29<03:56,  5.95it/s]16 03:00:06 Save the image 00158D_flip.png
 10%|████                                   | 164/1568 [00:29<04:01,  5.81it/s]16 03:00:06 Save the image 00159D.png
 11%|████                                   | 165/1568 [00:29<04:01,  5.81it/s]16 03:00:06 Save the image 00159D_flip.png
 11%|████▏                                  | 166/1568 [00:29<04:01,  5.80it/s]16 03:00:06 Save the image 00160D.png
 11%|████▏                                  | 167/1568 [00:29<04:02,  5.77it/s]16 03:00:06 Save the image 00160D_flip.png
 11%|████▏                                  | 168/1568 [00:30<04:03,  5.76it/s]16 03:00:07 Save the image 00161D.png
 11%|████▏                                  | 169/1568 [00:30<04:01,  5.79it/s]16 03:00:07 Save the image 00161D_flip.png
 11%|████▏                                  | 170/1568 [00:30<04:00,  5.81it/s]16 03:00:07 Save the image 00162D.png
 11%|████▎                                  | 171/1568 [00:30<03:48,  6.11it/s]16 03:00:07 Save the image 00162D_flip.png
 11%|████▎                                  | 172/1568 [00:30<03:54,  5.96it/s]16 03:00:07 Save the image 00163D.png
 11%|████▎                                  | 173/1568 [00:30<03:55,  5.93it/s]16 03:00:07 Save the image 00163D_flip.png
 11%|████▎                                  | 174/1568 [00:31<03:56,  5.89it/s]16 03:00:08 Save the image 00164D.png
 11%|████▎                                  | 175/1568 [00:31<03:59,  5.82it/s]16 03:00:08 Save the image 00164D_flip.png
 11%|████▍                                  | 176/1568 [00:31<03:58,  5.85it/s]16 03:00:08 Save the image 00165D.png
 11%|████▍                                  | 177/1568 [00:31<03:58,  5.82it/s]16 03:00:08 Save the image 00165D_flip.png
 11%|████▍                                  | 178/1568 [00:31<04:00,  5.78it/s]16 03:00:08 Save the image 00166D.png
 11%|████▍                                  | 179/1568 [00:31<03:46,  6.13it/s]16 03:00:08 Save the image 00166D_flip.png
 11%|████▍                                  | 180/1568 [00:32<03:51,  5.99it/s]16 03:00:09 Save the image 00167D.png
 12%|████▌                                  | 181/1568 [00:32<03:53,  5.94it/s]16 03:00:09 Save the image 00167D_flip.png
 12%|████▌                                  | 182/1568 [00:32<03:55,  5.89it/s]16 03:00:09 Save the image 00168D.png
 12%|████▌                                  | 183/1568 [00:32<03:57,  5.83it/s]16 03:00:09 Save the image 00168D_flip.png
 12%|████▌                                  | 184/1568 [00:32<03:56,  5.85it/s]16 03:00:09 Save the image 00169D.png

 12%|████▌                                  | 185/1568 [00:32<03:57,  5.82it/s]16 03:00:09 Save the image 00169D_flip.png
 12%|████▋                                  | 186/1568 [00:33<03:58,  5.79it/s]16 03:00:10 Save the image 00170D.png
 12%|████▋                                  | 187/1568 [00:33<03:56,  5.84it/s]16 03:00:10 Save the image 00170D_flip.png
 12%|████▋                                  | 188/1568 [00:33<03:58,  5.80it/s]16 03:00:10 Save the image 00171D.png
 12%|████▋                                  | 189/1568 [00:33<03:57,  5.80it/s]16 03:00:10 Save the image 00171D_flip.png
 12%|████▋                                  | 190/1568 [00:33<03:58,  5.79it/s]16 03:00:10 Save the image 00172D.png
 12%|████▊                                  | 191/1568 [00:33<03:58,  5.76it/s]16 03:00:10 Save the image 00172D_flip.png
 12%|████▊                                  | 192/1568 [00:34<03:57,  5.80it/s]16 03:00:11 Save the image 00173D.png
 12%|████▊                                  | 193/1568 [00:34<03:55,  5.83it/s]16 03:00:11 Save the image 00173D_flip.png
 12%|████▊                                  | 194/1568 [00:34<03:57,  5.79it/s]16 03:00:11 Save the image 00174D.png
 12%|████▊                                  | 195/1568 [00:34<03:57,  5.78it/s]16 03:00:11 Save the image 00174D_flip.png
 12%|████▉                                  | 196/1568 [00:34<03:57,  5.78it/s]16 03:00:11 Save the image 00175D.png
 13%|████▉                                  | 197/1568 [00:34<03:56,  5.79it/s]16 03:00:11 Save the image 00175D_flip.png
 13%|████▉                                  | 198/1568 [00:35<03:57,  5.76it/s]16 03:00:12 Save the image 00176D.png
 13%|████▉                                  | 199/1568 [00:35<03:57,  5.77it/s]16 03:00:12 Save the image 00176D_flip.png
 13%|████▉                                  | 200/1568 [00:35<03:57,  5.77it/s]16 03:00:12 Save the image 00177D.png
 13%|████▉                                  | 201/1568 [00:35<03:54,  5.82it/s]16 03:00:12 Save the image 00177D_flip.png
 13%|█████                                  | 202/1568 [00:35<03:50,  5.94it/s]16 03:00:12 Save the image 00178D.png
 13%|█████                                  | 203/1568 [00:36<03:52,  5.87it/s]16 03:00:13 Save the image 00178D_flip.png
 13%|█████                                  | 204/1568 [00:36<03:53,  5.85it/s]16 03:00:13 Save the image 00179D.png
 13%|█████                                  | 205/1568 [00:36<03:51,  5.89it/s]16 03:00:13 Save the image 00179D_flip.png
 13%|█████                                  | 206/1568 [00:36<03:54,  5.82it/s]16 03:00:13 Save the image 00180D.png
 13%|█████▏                                 | 207/1568 [00:36<03:54,  5.81it/s]16 03:00:13 Save the image 00180D_flip.png
 13%|█████▏                                 | 208/1568 [00:36<03:55,  5.77it/s]16 03:00:13 Save the image 00181D.png
 13%|█████▏                                 | 209/1568 [00:37<03:56,  5.75it/s]16 03:00:14 Save the image 00181D_flip.png
 13%|█████▏                                 | 210/1568 [00:37<03:44,  6.05it/s]16 03:00:14 Save the image 00182D.png
 13%|█████▏                                 | 211/1568 [00:37<03:48,  5.93it/s]16 03:00:14 Save the image 00182D_flip.png
 14%|█████▎                                 | 212/1568 [00:37<03:50,  5.89it/s]16 03:00:14 Save the image 00183D.png
 14%|█████▎                                 | 213/1568 [00:37<03:49,  5.90it/s]16 03:00:14 Save the image 00183D_flip.png
 14%|█████▎                                 | 214/1568 [00:37<03:51,  5.84it/s]16 03:00:14 Save the image 00184D.png
 14%|█████▎                                 | 215/1568 [00:38<03:53,  5.80it/s]16 03:00:15 Save the image 00184D_flip.png
 14%|█████▎                                 | 216/1568 [00:38<03:52,  5.81it/s]16 03:00:15 Save the image 00185D.png
 14%|█████▍                                 | 217/1568 [00:38<03:53,  5.79it/s]16 03:00:15 Save the image 00185D_flip.png
 14%|█████▍                                 | 218/1568 [00:38<03:40,  6.11it/s]16 03:00:15 Save the image 00186D.png
 14%|█████▍                                 | 219/1568 [00:38<03:45,  5.98it/s]16 03:00:15 Save the image 00186D_flip.png
 14%|█████▍                                 | 220/1568 [00:38<03:47,  5.93it/s]16 03:00:15 Save the image 00187D.png
 14%|█████▍                                 | 221/1568 [00:39<03:49,  5.87it/s]16 03:00:16 Save the image 00187D_flip.png
 14%|█████▌                                 | 222/1568 [00:39<03:51,  5.81it/s]16 03:00:16 Save the image 00188D.png
 14%|█████▌                                 | 223/1568 [00:39<03:50,  5.84it/s]16 03:00:16 Save the image 00188D_flip.png
 14%|█████▌                                 | 224/1568 [00:39<03:52,  5.78it/s]16 03:00:16 Save the image 00189D.png
 14%|█████▌                                 | 225/1568 [00:39<03:52,  5.78it/s]16 03:00:16 Save the image 00189D_flip.png
 14%|█████▌                                 | 226/1568 [00:39<03:51,  5.79it/s]16 03:00:16 Save the image 00190D.png
 14%|█████▋                                 | 227/1568 [00:40<03:53,  5.75it/s]16 03:00:17 Save the image 00190D_flip.png
 15%|█████▋                                 | 228/1568 [00:40<03:52,  5.77it/s]16 03:00:17 Save the image 00191D.png
 15%|█████▋                                 | 229/1568 [00:40<03:53,  5.74it/s]16 03:00:17 Save the image 00191D_flip.png
 15%|█████▋                                 | 230/1568 [00:40<03:53,  5.73it/s]16 03:00:17 Save the image 00192D.png
 15%|█████▋                                 | 231/1568 [00:40<03:50,  5.81it/s]16 03:00:17 Save the image 00192D_flip.png
 15%|█████▊                                 | 232/1568 [00:40<03:48,  5.85it/s]16 03:00:17 Save the image 00193D.png
 15%|█████▊                                 | 233/1568 [00:41<03:49,  5.82it/s]16 03:00:18 Save the image 00193D_flip.png
 15%|█████▊                                 | 234/1568 [00:41<03:50,  5.79it/s]16 03:00:18 Save the image 00194D.png
 15%|█████▊                                 | 235/1568 [00:41<03:50,  5.80it/s]16 03:00:18 Save the image 00194D_flip.png
 15%|█████▊                                 | 236/1568 [00:41<03:48,  5.82it/s]16 03:00:18 Save the image 00195D.png
 15%|█████▉                                 | 237/1568 [00:41<03:49,  5.79it/s]16 03:00:18 Save the image 00195D_flip.png
 15%|█████▉                                 | 238/1568 [00:42<03:49,  5.79it/s]16 03:00:19 Save the image 00196D.png
 15%|█████▉                                 | 239/1568 [00:42<03:49,  5.80it/s]16 03:00:19 Save the image 00196D_flip.png
 15%|█████▉                                 | 240/1568 [00:42<03:47,  5.84it/s]16 03:00:19 Save the image 00197D.png
 15%|█████▉                                 | 241/1568 [00:42<03:42,  5.96it/s]16 03:00:19 Save the image 00197D_flip.png
 15%|██████                                 | 242/1568 [00:42<03:45,  5.88it/s]16 03:00:19 Save the image 00198D.png
 15%|██████                                 | 243/1568 [00:42<03:46,  5.85it/s]16 03:00:19 Save the image 00198D_flip.png
 16%|██████                                 | 244/1568 [00:43<03:46,  5.86it/s]16 03:00:20 Save the image 00199D.png
 16%|██████                                 | 245/1568 [00:43<03:47,  5.81it/s]16 03:00:20 Save the image 00199D_flip.png
 16%|██████                                 | 246/1568 [00:43<03:49,  5.77it/s]16 03:00:20 Save the image 00200D.png
 16%|██████▏                                | 247/1568 [00:43<03:48,  5.79it/s]16 03:00:20 Save the image 00200D_flip.png
 16%|██████▏                                | 248/1568 [00:43<03:47,  5.81it/s]16 03:00:20 Save the image 00201D.png

 16%|██████▏                                | 249/1568 [00:43<03:34,  6.15it/s]16 03:00:20 Save the image 00201D_flip.png
 16%|██████▏                                | 250/1568 [00:44<03:39,  6.00it/s]16 03:00:21 Save the image 00202D.png
 16%|██████▏                                | 251/1568 [00:44<03:41,  5.95it/s]16 03:00:21 Save the image 00202D_flip.png
 16%|██████▎                                | 252/1568 [00:44<03:41,  5.93it/s]16 03:00:21 Save the image 00203D.png
 16%|██████▎                                | 253/1568 [00:44<03:44,  5.86it/s]16 03:00:21 Save the image 00203D_flip.png
 16%|██████▎                                | 254/1568 [00:44<03:45,  5.82it/s]16 03:00:21 Save the image 00204D.png
 16%|██████▎                                | 255/1568 [00:44<03:45,  5.82it/s]16 03:00:21 Save the image 00204D_flip.png
 16%|██████▎                                | 256/1568 [00:45<03:46,  5.78it/s]16 03:00:22 Save the image 00205D.png
 16%|██████▍                                | 257/1568 [00:45<03:33,  6.13it/s]16 03:00:22 Save the image 00205D_flip.png
 16%|██████▍                                | 258/1568 [00:45<03:38,  5.99it/s]16 03:00:22 Save the image 00206D.png
 17%|██████▍                                | 259/1568 [00:45<03:39,  5.96it/s]16 03:00:22 Save the image 00206D_flip.png
 17%|██████▍                                | 260/1568 [00:45<03:39,  5.96it/s]16 03:00:22 Save the image 00207D.png
 17%|██████▍                                | 261/1568 [00:45<03:42,  5.87it/s]16 03:00:22 Save the image 00207D_flip.png
 17%|██████▌                                | 262/1568 [00:46<03:43,  5.85it/s]16 03:00:23 Save the image 00208D.png
 17%|██████▌                                | 263/1568 [00:46<03:44,  5.83it/s]16 03:00:23 Save the image 00208D_flip.png
 17%|██████▌                                | 264/1568 [00:46<03:43,  5.83it/s]16 03:00:23 Save the image 00209D.png
 17%|██████▌                                | 265/1568 [00:46<03:30,  6.18it/s]16 03:00:23 Save the image 00209D_flip.png
 17%|██████▌                                | 266/1568 [00:46<03:36,  6.02it/s]16 03:00:23 Save the image 00210D.png
 17%|██████▋                                | 267/1568 [00:46<03:38,  5.97it/s]16 03:00:23 Save the image 00210D_flip.png
 17%|██████▋                                | 268/1568 [00:47<03:39,  5.92it/s]16 03:00:24 Save the image 00211D.png
 17%|██████▋                                | 269/1568 [00:47<03:42,  5.84it/s]16 03:00:24 Save the image 00211D_flip.png
 17%|██████▋                                | 270/1568 [00:47<03:40,  5.87it/s]16 03:00:24 Save the image 00212D.png
 17%|██████▋                                | 271/1568 [00:47<03:41,  5.86it/s]16 03:00:24 Save the image 00212D_flip.png
 17%|██████▊                                | 272/1568 [00:47<03:41,  5.86it/s]16 03:00:24 Save the image 00213D.png
 17%|██████▊                                | 273/1568 [00:47<03:29,  6.19it/s]16 03:00:24 Save the image 00213D_flip.png
 17%|██████▊                                | 274/1568 [00:48<03:34,  6.02it/s]16 03:00:25 Save the image 00214D.png
 18%|██████▊                                | 275/1568 [00:48<03:36,  5.96it/s]16 03:00:25 Save the image 00214D_flip.png
 18%|██████▊                                | 276/1568 [00:48<03:37,  5.94it/s]16 03:00:25 Save the image 00215D.png
 18%|██████▉                                | 277/1568 [00:48<03:40,  5.85it/s]16 03:00:25 Save the image 00215D_flip.png
 18%|██████▉                                | 278/1568 [00:48<03:39,  5.87it/s]16 03:00:25 Save the image 00216D.png
 18%|██████▉                                | 279/1568 [00:48<03:40,  5.85it/s]16 03:00:25 Save the image 00216D_flip.png
 18%|██████▉                                | 280/1568 [00:49<03:40,  5.84it/s]16 03:00:26 Save the image 00217D.png
 18%|██████▉                                | 281/1568 [00:49<03:26,  6.22it/s]16 03:00:26 Save the image 00217D_flip.png
 18%|███████                                | 282/1568 [00:49<03:32,  6.05it/s]16 03:00:26 Save the image 00218D.png
 18%|███████                                | 283/1568 [00:49<03:34,  5.99it/s]16 03:00:26 Save the image 00218D_flip.png
 18%|███████                                | 284/1568 [00:49<03:36,  5.93it/s]16 03:00:26 Save the image 00219D.png
 18%|███████                                | 285/1568 [00:49<03:39,  5.85it/s]16 03:00:26 Save the image 00219D_flip.png
 18%|███████                                | 286/1568 [00:50<03:38,  5.87it/s]16 03:00:27 Save the image 00220D.png
 18%|███████▏                               | 287/1568 [00:50<03:39,  5.83it/s]16 03:00:27 Save the image 00220D_flip.png
 18%|███████▏                               | 288/1568 [00:50<03:41,  5.78it/s]16 03:00:27 Save the image 00221D.png
 18%|███████▏                               | 289/1568 [00:50<03:28,  6.13it/s]16 03:00:27 Save the image 00221D_flip.png
 18%|███████▏                               | 290/1568 [00:50<03:33,  5.98it/s]16 03:00:27 Save the image 00222D.png
 19%|███████▏                               | 291/1568 [00:50<03:35,  5.94it/s]16 03:00:27 Save the image 00222D_flip.png
 19%|███████▎                               | 292/1568 [00:51<03:36,  5.90it/s]16 03:00:28 Save the image 00223D.png
 19%|███████▎                               | 293/1568 [00:51<03:38,  5.82it/s]16 03:00:28 Save the image 00223D_flip.png
 19%|███████▎                               | 294/1568 [00:51<03:37,  5.85it/s]16 03:00:28 Save the image 00224D.png
 19%|███████▎                               | 295/1568 [00:51<03:39,  5.80it/s]16 03:00:28 Save the image 00224D_flip.png
 19%|███████▎                               | 296/1568 [00:51<03:40,  5.76it/s]16 03:00:28 Save the image 00225D.png
 19%|███████▍                               | 297/1568 [00:52<03:42,  5.71it/s]16 03:00:29 Save the image 00225D_flip.png
 19%|███████▍                               | 298/1568 [00:52<03:45,  5.64it/s]16 03:00:29 Save the image 00226D.png
 19%|███████▍                               | 299/1568 [00:52<03:42,  5.71it/s]16 03:00:29 Save the image 00226D_flip.png
 19%|███████▍                               | 300/1568 [00:52<03:41,  5.73it/s]16 03:00:29 Save the image 00227D.png
 19%|███████▍                               | 301/1568 [00:52<03:40,  5.75it/s]16 03:00:29 Save the image 00227D_flip.png
 19%|███████▌                               | 302/1568 [00:52<03:38,  5.80it/s]16 03:00:29 Save the image 00228D.png
 19%|███████▌                               | 303/1568 [00:53<03:36,  5.85it/s]16 03:00:30 Save the image 00228D_flip.png
 19%|███████▌                               | 304/1568 [00:53<03:37,  5.80it/s]16 03:00:30 Save the image 00229D.png
 19%|███████▌                               | 305/1568 [00:53<03:38,  5.78it/s]16 03:00:30 Save the image 00229D_flip.png
 20%|███████▌                               | 306/1568 [00:53<03:38,  5.79it/s]16 03:00:30 Save the image 00230D.png
 20%|███████▋                               | 307/1568 [00:53<03:37,  5.79it/s]16 03:00:30 Save the image 00230D_flip.png
 20%|███████▋                               | 308/1568 [00:53<03:38,  5.76it/s]16 03:00:30 Save the image 00231D.png
 20%|███████▋                               | 309/1568 [00:54<03:38,  5.77it/s]16 03:00:31 Save the image 00231D_flip.png
 20%|███████▋                               | 310/1568 [00:54<03:38,  5.76it/s]16 03:00:31 Save the image 00232D.png
 20%|███████▋                               | 311/1568 [00:54<03:36,  5.81it/s]16 03:00:31 Save the image 00232D_flip.png
 20%|███████▊                               | 312/1568 [00:54<03:29,  5.99it/s]16 03:00:31 Save the image 00233D.png

 20%|███████▊                               | 313/1568 [00:54<03:32,  5.89it/s]16 03:00:31 Save the image 00233D_flip.png
 20%|███████▊                               | 314/1568 [00:54<03:33,  5.87it/s]16 03:00:31 Save the image 00234D.png
 20%|███████▊                               | 315/1568 [00:55<03:33,  5.86it/s]16 03:00:32 Save the image 00234D_flip.png
 20%|███████▊                               | 316/1568 [00:55<03:35,  5.81it/s]16 03:00:32 Save the image 00235D.png
 20%|███████▉                               | 317/1568 [00:55<03:36,  5.77it/s]16 03:00:32 Save the image 00235D_flip.png
 20%|███████▉                               | 318/1568 [00:55<03:36,  5.78it/s]16 03:00:32 Save the image 00236D.png
 20%|███████▉                               | 319/1568 [00:55<03:35,  5.79it/s]16 03:00:32 Save the image 00236D_flip.png
 20%|███████▉                               | 320/1568 [00:55<03:25,  6.07it/s]16 03:00:32 Save the image 00237D.png
 20%|███████▉                               | 321/1568 [00:56<03:29,  5.94it/s]16 03:00:33 Save the image 00237D_flip.png
 21%|████████                               | 322/1568 [00:56<03:32,  5.87it/s]16 03:00:33 Save the image 00238D.png
 21%|████████                               | 323/1568 [00:56<03:33,  5.84it/s]16 03:00:33 Save the image 00238D_flip.png
 21%|████████                               | 324/1568 [00:56<03:34,  5.79it/s]16 03:00:33 Save the image 00239D.png
 21%|████████                               | 325/1568 [00:56<03:36,  5.74it/s]16 03:00:33 Save the image 00239D_flip.png
 21%|████████                               | 326/1568 [00:56<03:37,  5.72it/s]16 03:00:34 Save the image 00240D.png
 21%|████████▏                              | 327/1568 [00:57<03:37,  5.72it/s]16 03:00:34 Save the image 00240D_flip.png
 21%|████████▏                              | 328/1568 [00:57<03:26,  6.00it/s]16 03:00:34 Save the image 00241D.png
 21%|████████▏                              | 329/1568 [00:57<03:29,  5.91it/s]16 03:00:34 Save the image 00241D_flip.png
 21%|████████▏                              | 330/1568 [00:57<03:30,  5.89it/s]16 03:00:34 Save the image 00242D.png
 21%|████████▏                              | 331/1568 [00:57<03:31,  5.84it/s]16 03:00:34 Save the image 00242D_flip.png
 21%|████████▎                              | 332/1568 [00:58<03:33,  5.79it/s]16 03:00:35 Save the image 00243D.png
 21%|████████▎                              | 333/1568 [00:58<03:32,  5.81it/s]16 03:00:35 Save the image 00243D_flip.png
 21%|████████▎                              | 334/1568 [00:58<03:33,  5.77it/s]16 03:00:35 Save the image 00244D.png
 21%|████████▎                              | 335/1568 [00:58<03:34,  5.76it/s]16 03:00:35 Save the image 00244D_flip.png
 21%|████████▎                              | 336/1568 [00:58<03:35,  5.72it/s]16 03:00:35 Save the image 00245D.png
 21%|████████▍                              | 337/1568 [00:58<03:35,  5.71it/s]16 03:00:35 Save the image 00245D_flip.png
 22%|████████▍                              | 338/1568 [00:59<03:34,  5.74it/s]16 03:00:36 Save the image 00246D.png
 22%|████████▍                              | 339/1568 [00:59<03:32,  5.77it/s]16 03:00:36 Save the image 00246D_flip.png
 22%|████████▍                              | 340/1568 [00:59<03:32,  5.78it/s]16 03:00:36 Save the image 00247D.png
 22%|████████▍                              | 341/1568 [00:59<03:30,  5.82it/s]16 03:00:36 Save the image 00247D_flip.png
 22%|████████▌                              | 342/1568 [00:59<03:29,  5.85it/s]16 03:00:36 Save the image 00248D.png
 22%|████████▌                              | 343/1568 [00:59<03:31,  5.79it/s]16 03:00:36 Save the image 00248D_flip.png
 22%|████████▌                              | 344/1568 [01:00<03:32,  5.77it/s]16 03:00:37 Save the image 00249D.png
 22%|████████▌                              | 345/1568 [01:00<03:33,  5.73it/s]16 03:00:37 Save the image 00249D_flip.png
 22%|████████▌                              | 346/1568 [01:00<03:33,  5.72it/s]16 03:00:37 Save the image 00250D.png
 22%|████████▋                              | 347/1568 [01:00<03:33,  5.71it/s]16 03:00:37 Save the image 00250D_flip.png
 22%|████████▋                              | 348/1568 [01:00<03:33,  5.73it/s]16 03:00:37 Save the image 00251D.png
 22%|████████▋                              | 349/1568 [01:00<03:32,  5.73it/s]16 03:00:37 Save the image 00251D_flip.png
 22%|████████▋                              | 350/1568 [01:01<03:31,  5.75it/s]16 03:00:38 Save the image 00252D.png
 22%|████████▋                              | 351/1568 [01:01<03:29,  5.81it/s]16 03:00:38 Save the image 00252D_flip.png
 22%|████████▊                              | 352/1568 [01:01<03:31,  5.76it/s]16 03:00:38 Save the image 00253D.png
 23%|████████▊                              | 353/1568 [01:01<03:31,  5.75it/s]16 03:00:38 Save the image 00253D_flip.png
 23%|████████▊                              | 354/1568 [01:01<03:31,  5.74it/s]16 03:00:38 Save the image 00254D.png
 23%|████████▊                              | 355/1568 [01:02<03:33,  5.69it/s]16 03:00:39 Save the image 00254D_flip.png
 23%|████████▊                              | 356/1568 [01:02<03:35,  5.63it/s]16 03:00:39 Save the image 00255D.png
 23%|████████▉                              | 357/1568 [01:02<03:33,  5.68it/s]16 03:00:39 Save the image 00255D_flip.png
 23%|████████▉                              | 358/1568 [01:02<03:34,  5.64it/s]16 03:00:39 Save the image 00256D.png
 23%|████████▉                              | 359/1568 [01:02<03:20,  6.02it/s]16 03:00:39 Save the image 00256D_flip.png
 23%|████████▉                              | 360/1568 [01:02<03:24,  5.90it/s]16 03:00:39 Save the image 00257D.png
 23%|████████▉                              | 361/1568 [01:03<03:25,  5.87it/s]16 03:00:40 Save the image 00257D_flip.png
 23%|█████████                              | 362/1568 [01:03<03:26,  5.85it/s]16 03:00:40 Save the image 00258D.png
 23%|█████████                              | 363/1568 [01:03<03:27,  5.80it/s]16 03:00:40 Save the image 00258D_flip.png
 23%|█████████                              | 364/1568 [01:03<03:28,  5.77it/s]16 03:00:40 Save the image 00259D.png
 23%|█████████                              | 365/1568 [01:03<03:27,  5.79it/s]16 03:00:40 Save the image 00259D_flip.png
 23%|█████████                              | 366/1568 [01:03<03:26,  5.81it/s]16 03:00:40 Save the image 00260D.png
 23%|█████████▏                             | 367/1568 [01:04<03:14,  6.18it/s]16 03:00:41 Save the image 00260D_flip.png
 23%|█████████▏                             | 368/1568 [01:04<03:19,  6.03it/s]16 03:00:41 Save the image 00261D.png
 24%|█████████▏                             | 369/1568 [01:04<03:20,  5.97it/s]16 03:00:41 Save the image 00261D_flip.png
 24%|█████████▏                             | 370/1568 [01:04<03:20,  5.97it/s]16 03:00:41 Save the image 00262D.png
 24%|█████████▏                             | 371/1568 [01:04<03:23,  5.87it/s]16 03:00:41 Save the image 00262D_flip.png
 24%|█████████▎                             | 372/1568 [01:04<03:24,  5.86it/s]16 03:00:41 Save the image 00263D.png
 24%|█████████▎                             | 373/1568 [01:05<03:25,  5.83it/s]16 03:00:42 Save the image 00263D_flip.png
 24%|█████████▎                             | 374/1568 [01:05<03:25,  5.80it/s]16 03:00:42 Save the image 00264D.png
 24%|█████████▎                             | 375/1568 [01:05<03:15,  6.11it/s]16 03:00:42 Save the image 00264D_flip.png
 24%|█████████▎                             | 376/1568 [01:05<03:19,  5.98it/s]16 03:00:42 Save the image 00265D.png

 24%|█████████▍                             | 377/1568 [01:05<03:21,  5.92it/s]16 03:00:42 Save the image 00265D_flip.png
 24%|█████████▍                             | 378/1568 [01:05<03:24,  5.83it/s]16 03:00:42 Save the image 00266D.png
 24%|█████████▍                             | 379/1568 [01:06<03:27,  5.74it/s]16 03:00:43 Save the image 00266D_flip.png
 24%|█████████▍                             | 380/1568 [01:06<03:24,  5.81it/s]16 03:00:43 Save the image 00267D.png
 24%|█████████▍                             | 381/1568 [01:06<03:24,  5.81it/s]16 03:00:43 Save the image 00267D_flip.png
 24%|█████████▌                             | 382/1568 [01:06<03:24,  5.81it/s]16 03:00:43 Save the image 00268D.png
 24%|█████████▌                             | 383/1568 [01:06<03:11,  6.20it/s]16 03:00:43 Save the image 00268D_flip.png
 24%|█████████▌                             | 384/1568 [01:06<03:16,  6.03it/s]16 03:00:43 Save the image 00269D.png
 25%|█████████▌                             | 385/1568 [01:07<03:19,  5.94it/s]16 03:00:44 Save the image 00269D_flip.png
 25%|█████████▌                             | 386/1568 [01:07<03:21,  5.87it/s]16 03:00:44 Save the image 00270D.png
 25%|█████████▋                             | 387/1568 [01:07<03:22,  5.82it/s]16 03:00:44 Save the image 00270D_flip.png
 25%|█████████▋                             | 388/1568 [01:07<03:21,  5.87it/s]16 03:00:44 Save the image 00271D.png
 25%|█████████▋                             | 389/1568 [01:07<03:22,  5.83it/s]16 03:00:44 Save the image 00271D_flip.png
 25%|█████████▋                             | 390/1568 [01:07<03:22,  5.83it/s]16 03:00:44 Save the image 00272D.png
 25%|█████████▋                             | 391/1568 [01:08<03:09,  6.21it/s]16 03:00:45 Save the image 00272D_flip.png
 25%|█████████▊                             | 392/1568 [01:08<03:14,  6.06it/s]16 03:00:45 Save the image 00273D.png
 25%|█████████▊                             | 393/1568 [01:08<03:15,  6.01it/s]16 03:00:45 Save the image 00273D_flip.png
 25%|█████████▊                             | 394/1568 [01:08<03:16,  5.97it/s]16 03:00:45 Save the image 00274D.png
 25%|█████████▊                             | 395/1568 [01:08<03:19,  5.87it/s]16 03:00:45 Save the image 00274D_flip.png
 25%|█████████▊                             | 396/1568 [01:08<03:19,  5.86it/s]16 03:00:45 Save the image 00275D.png
 25%|█████████▊                             | 397/1568 [01:09<03:21,  5.81it/s]16 03:00:46 Save the image 00275D_flip.png
 25%|█████████▉                             | 398/1568 [01:09<03:22,  5.79it/s]16 03:00:46 Save the image 00276D.png
 25%|█████████▉                             | 399/1568 [01:09<03:09,  6.16it/s]16 03:00:46 Save the image 00276D_flip.png
 26%|█████████▉                             | 400/1568 [01:09<03:14,  6.00it/s]16 03:00:46 Save the image 00277D.png
 26%|█████████▉                             | 401/1568 [01:09<03:16,  5.94it/s]16 03:00:46 Save the image 00277D_flip.png
 26%|█████████▉                             | 402/1568 [01:09<03:18,  5.87it/s]16 03:00:46 Save the image 00278D.png
 26%|██████████                             | 403/1568 [01:10<03:20,  5.80it/s]16 03:00:47 Save the image 00278D_flip.png
 26%|██████████                             | 404/1568 [01:10<03:18,  5.86it/s]16 03:00:47 Save the image 00279D.png
 26%|██████████                             | 405/1568 [01:10<03:19,  5.82it/s]16 03:00:47 Save the image 00279D_flip.png
 26%|██████████                             | 406/1568 [01:10<03:20,  5.81it/s]16 03:00:47 Save the image 00280D.png
 26%|██████████                             | 407/1568 [01:10<03:09,  6.14it/s]16 03:00:47 Save the image 00280D_flip.png
 26%|██████████▏                            | 408/1568 [01:10<03:13,  5.98it/s]16 03:00:47 Save the image 00281D.png
 26%|██████████▏                            | 409/1568 [01:11<03:15,  5.94it/s]16 03:00:48 Save the image 00281D_flip.png
 26%|██████████▏                            | 410/1568 [01:11<03:15,  5.92it/s]16 03:00:48 Save the image 00282D.png
 26%|██████████▏                            | 411/1568 [01:11<03:18,  5.84it/s]16 03:00:48 Save the image 00282D_flip.png
 26%|██████████▏                            | 412/1568 [01:11<03:17,  5.87it/s]16 03:00:48 Save the image 00283D.png
 26%|██████████▎                            | 413/1568 [01:11<03:18,  5.81it/s]16 03:00:48 Save the image 00283D_flip.png
 26%|██████████▎                            | 414/1568 [01:12<03:19,  5.80it/s]16 03:00:49 Save the image 00284D.png
 26%|██████████▎                            | 415/1568 [01:12<03:18,  5.81it/s]16 03:00:49 Save the image 00284D_flip.png
 27%|██████████▎                            | 416/1568 [01:12<03:18,  5.79it/s]16 03:00:49 Save the image 00285D.png
 27%|██████████▎                            | 417/1568 [01:12<03:16,  5.84it/s]16 03:00:49 Save the image 00285D_flip.png
 27%|██████████▍                            | 418/1568 [01:12<03:17,  5.83it/s]16 03:00:49 Save the image 00286D.png
 27%|██████████▍                            | 419/1568 [01:12<03:18,  5.79it/s]16 03:00:49 Save the image 00286D_flip.png
 27%|██████████▍                            | 420/1568 [01:13<03:17,  5.81it/s]16 03:00:50 Save the image 00287D.png
 27%|██████████▍                            | 421/1568 [01:13<03:17,  5.80it/s]16 03:00:50 Save the image 00287D_flip.png
 27%|██████████▍                            | 422/1568 [01:13<03:22,  5.67it/s]16 03:00:50 Save the image 00288D.png
 27%|██████████▌                            | 423/1568 [01:13<03:24,  5.61it/s]16 03:00:50 Save the image 00288D_flip.png
 27%|██████████▌                            | 424/1568 [01:13<03:23,  5.63it/s]16 03:00:50 Save the image 00289D.png
 27%|██████████▌                            | 425/1568 [01:13<03:22,  5.64it/s]16 03:00:50 Save the image 00289D_flip.png
 27%|██████████▌                            | 426/1568 [01:14<03:23,  5.62it/s]16 03:00:51 Save the image 00290D.png
 27%|██████████▌                            | 427/1568 [01:14<03:22,  5.64it/s]16 03:00:51 Save the image 00290D_flip.png
 27%|██████████▋                            | 428/1568 [01:14<03:22,  5.64it/s]16 03:00:51 Save the image 00291D.png
 27%|██████████▋                            | 429/1568 [01:14<03:20,  5.69it/s]16 03:00:51 Save the image 00291D_flip.png
 27%|██████████▋                            | 430/1568 [01:14<03:20,  5.67it/s]16 03:00:51 Save the image 00292D.png
 27%|██████████▋                            | 431/1568 [01:15<03:21,  5.66it/s]16 03:00:52 Save the image 00292D_flip.png
 28%|██████████▋                            | 432/1568 [01:15<03:20,  5.67it/s]16 03:00:52 Save the image 00293D.png
 28%|██████████▊                            | 433/1568 [01:15<03:18,  5.71it/s]16 03:00:52 Save the image 00293D_flip.png
 28%|██████████▊                            | 434/1568 [01:15<03:21,  5.64it/s]16 03:00:52 Save the image 00294D.png
 28%|██████████▊                            | 435/1568 [01:15<03:21,  5.62it/s]16 03:00:52 Save the image 00294D_flip.png
 28%|██████████▊                            | 436/1568 [01:15<03:21,  5.61it/s]16 03:00:52 Save the image 00295D.png
 28%|██████████▊                            | 437/1568 [01:16<03:18,  5.70it/s]16 03:00:53 Save the image 00295D_flip.png
 28%|██████████▉                            | 438/1568 [01:16<03:12,  5.87it/s]16 03:00:53 Save the image 00296D.png
 28%|██████████▉                            | 439/1568 [01:16<03:13,  5.83it/s]16 03:00:53 Save the image 00296D_flip.png
 28%|██████████▉                            | 440/1568 [01:16<03:13,  5.82it/s]16 03:00:53 Save the image 00297D.png

 28%|██████████▉                            | 441/1568 [01:16<03:13,  5.81it/s]16 03:00:53 Save the image 00297D_flip.png
 28%|██████████▉                            | 442/1568 [01:16<03:18,  5.67it/s]16 03:00:53 Save the image 00298D.png
 28%|███████████                            | 443/1568 [01:17<03:20,  5.62it/s]16 03:00:54 Save the image 00298D_flip.png
 28%|███████████                            | 444/1568 [01:17<03:22,  5.56it/s]16 03:00:54 Save the image 00299D.png
 28%|███████████                            | 445/1568 [01:17<03:21,  5.57it/s]16 03:00:54 Save the image 00299D_flip.png
 28%|███████████                            | 446/1568 [01:17<03:09,  5.93it/s]16 03:00:54 Save the image 00300D.png
 29%|███████████                            | 447/1568 [01:17<03:12,  5.81it/s]16 03:00:54 Save the image 00300D_flip.png
 29%|███████████▏                           | 448/1568 [01:17<03:14,  5.77it/s]16 03:00:54 Save the image 00301D.png
 29%|███████████▏                           | 449/1568 [01:18<03:14,  5.75it/s]16 03:00:55 Save the image 00301D_flip.png
 29%|███████████▏                           | 450/1568 [01:18<03:16,  5.68it/s]16 03:00:55 Save the image 00302D.png
 29%|███████████▏                           | 451/1568 [01:18<03:18,  5.63it/s]16 03:00:55 Save the image 00302D_flip.png
 29%|███████████▏                           | 452/1568 [01:18<03:19,  5.60it/s]16 03:00:55 Save the image 00303D.png
 29%|███████████▎                           | 453/1568 [01:18<03:18,  5.63it/s]16 03:00:55 Save the image 00303D_flip.png
 29%|███████████▎                           | 454/1568 [01:19<03:08,  5.91it/s]16 03:00:56 Save the image 00304D.png
 29%|███████████▎                           | 455/1568 [01:19<03:11,  5.82it/s]16 03:00:56 Save the image 00304D_flip.png
 29%|███████████▎                           | 456/1568 [01:19<03:12,  5.78it/s]16 03:00:56 Save the image 00305D.png
 29%|███████████▎                           | 457/1568 [01:19<03:12,  5.78it/s]16 03:00:56 Save the image 00305D_flip.png
 29%|███████████▍                           | 458/1568 [01:19<03:13,  5.73it/s]16 03:00:56 Save the image 00306D.png
 29%|███████████▍                           | 459/1568 [01:19<03:14,  5.69it/s]16 03:00:56 Save the image 00306D_flip.png
 29%|███████████▍                           | 460/1568 [01:20<03:15,  5.68it/s]16 03:00:57 Save the image 00307D.png
 29%|███████████▍                           | 461/1568 [01:20<03:15,  5.65it/s]16 03:00:57 Save the image 00307D_flip.png
 29%|███████████▍                           | 462/1568 [01:20<03:04,  6.00it/s]16 03:00:57 Save the image 00308D.png
 30%|███████████▌                           | 463/1568 [01:20<03:08,  5.85it/s]16 03:00:57 Save the image 00308D_flip.png
 30%|███████████▌                           | 464/1568 [01:20<03:10,  5.79it/s]16 03:00:57 Save the image 00309D.png
 30%|███████████▌                           | 465/1568 [01:20<03:09,  5.81it/s]16 03:00:57 Save the image 00309D_flip.png
 30%|███████████▌                           | 466/1568 [01:21<03:12,  5.74it/s]16 03:00:58 Save the image 00310D.png
 30%|███████████▌                           | 467/1568 [01:21<03:12,  5.73it/s]16 03:00:58 Save the image 00310D_flip.png
 30%|███████████▋                           | 468/1568 [01:21<03:12,  5.72it/s]16 03:00:58 Save the image 00311D.png
 30%|███████████▋                           | 469/1568 [01:21<03:12,  5.71it/s]16 03:00:58 Save the image 00311D_flip.png
 30%|███████████▋                           | 470/1568 [01:21<03:01,  6.03it/s]16 03:00:58 Save the image 00312D.png
 30%|███████████▋                           | 471/1568 [01:21<03:07,  5.86it/s]16 03:00:58 Save the image 00312D_flip.png
 30%|███████████▋                           | 472/1568 [01:22<03:09,  5.78it/s]16 03:00:59 Save the image 00313D.png
 30%|███████████▊                           | 473/1568 [01:22<03:12,  5.69it/s]16 03:00:59 Save the image 00313D_flip.png
 30%|███████████▊                           | 474/1568 [01:22<03:14,  5.63it/s]16 03:00:59 Save the image 00314D.png
 30%|███████████▊                           | 475/1568 [01:22<03:15,  5.60it/s]16 03:00:59 Save the image 00314D_flip.png
 30%|███████████▊                           | 476/1568 [01:22<03:15,  5.58it/s]16 03:00:59 Save the image 00315D.png
 30%|███████████▊                           | 477/1568 [01:23<03:15,  5.58it/s]16 03:01:00 Save the image 00315D_flip.png
 30%|███████████▉                           | 478/1568 [01:23<03:04,  5.90it/s]16 03:01:00 Save the image 00316D.png
 31%|███████████▉                           | 479/1568 [01:23<03:08,  5.78it/s]16 03:01:00 Save the image 00316D_flip.png
 31%|███████████▉                           | 480/1568 [01:23<03:08,  5.78it/s]16 03:01:00 Save the image 00317D.png
 31%|███████████▉                           | 481/1568 [01:23<03:09,  5.75it/s]16 03:01:00 Save the image 00317D_flip.png
 31%|███████████▉                           | 482/1568 [01:23<03:11,  5.68it/s]16 03:01:00 Save the image 00318D.png
 31%|████████████                           | 483/1568 [01:24<03:13,  5.62it/s]16 03:01:01 Save the image 00318D_flip.png
 31%|████████████                           | 484/1568 [01:24<03:14,  5.57it/s]16 03:01:01 Save the image 00319D.png
 31%|████████████                           | 485/1568 [01:24<03:14,  5.57it/s]16 03:01:01 Save the image 00319D_flip.png
 31%|████████████                           | 486/1568 [01:24<03:03,  5.91it/s]16 03:01:01 Save the image 00320D.png
 31%|████████████                           | 487/1568 [01:24<03:06,  5.80it/s]16 03:01:01 Save the image 00320D_flip.png
 31%|████████████▏                          | 488/1568 [01:24<03:07,  5.77it/s]16 03:01:01 Save the image 00321D.png
 31%|████████████▏                          | 489/1568 [01:25<03:07,  5.77it/s]16 03:01:02 Save the image 00321D_flip.png
 31%|████████████▏                          | 490/1568 [01:25<03:10,  5.66it/s]16 03:01:02 Save the image 00322D.png
 31%|████████████▏                          | 491/1568 [01:25<03:11,  5.63it/s]16 03:01:02 Save the image 00322D_flip.png
 31%|████████████▏                          | 492/1568 [01:25<03:12,  5.60it/s]16 03:01:02 Save the image 00323D.png
 31%|████████████▎                          | 493/1568 [01:25<03:12,  5.59it/s]16 03:01:02 Save the image 00323D_flip.png
 32%|████████████▎                          | 494/1568 [01:25<03:00,  5.94it/s]16 03:01:03 Save the image 00324D.png
 32%|████████████▎                          | 495/1568 [01:26<03:04,  5.80it/s]16 03:01:03 Save the image 00324D_flip.png
 32%|████████████▎                          | 496/1568 [01:26<03:04,  5.81it/s]16 03:01:03 Save the image 00325D.png
 32%|████████████▎                          | 497/1568 [01:26<03:03,  5.85it/s]16 03:01:03 Save the image 00325D_flip.png
 32%|████████████▍                          | 498/1568 [01:26<03:04,  5.79it/s]16 03:01:03 Save the image 00326D.png
 32%|████████████▍                          | 499/1568 [01:26<03:04,  5.79it/s]16 03:01:03 Save the image 00326D_flip.png
 32%|████████████▍                          | 500/1568 [01:27<03:04,  5.78it/s]16 03:01:04 Save the image 00327D.png
 32%|████████████▍                          | 501/1568 [01:27<03:04,  5.78it/s]16 03:01:04 Save the image 00327D_flip.png
 32%|████████████▍                          | 502/1568 [01:27<02:53,  6.13it/s]16 03:01:04 Save the image 00328D.png
 32%|████████████▌                          | 503/1568 [01:27<02:58,  5.98it/s]16 03:01:04 Save the image 00328D_flip.png
 32%|████████████▌                          | 504/1568 [01:27<02:59,  5.92it/s]16 03:01:04 Save the image 00329D.png

 32%|████████████▌                          | 505/1568 [01:27<03:00,  5.89it/s]16 03:01:04 Save the image 00329D_flip.png
 32%|████████████▌                          | 506/1568 [01:28<03:03,  5.79it/s]16 03:01:05 Save the image 00330D.png
 32%|████████████▌                          | 507/1568 [01:28<03:01,  5.83it/s]16 03:01:05 Save the image 00330D_flip.png
 32%|████████████▋                          | 508/1568 [01:28<03:03,  5.79it/s]16 03:01:05 Save the image 00331D.png
 32%|████████████▋                          | 509/1568 [01:28<03:03,  5.78it/s]16 03:01:05 Save the image 00331D_flip.png
 33%|████████████▋                          | 510/1568 [01:28<03:02,  5.80it/s]16 03:01:05 Save the image 00332D.png
 33%|████████████▋                          | 511/1568 [01:28<03:02,  5.79it/s]16 03:01:05 Save the image 00332D_flip.png
 33%|████████████▋                          | 512/1568 [01:29<03:04,  5.74it/s]16 03:01:06 Save the image 00333D.png
 33%|████████████▊                          | 513/1568 [01:29<03:03,  5.73it/s]16 03:01:06 Save the image 00333D_flip.png
 33%|████████████▊                          | 514/1568 [01:29<03:04,  5.71it/s]16 03:01:06 Save the image 00334D.png
 33%|████████████▊                          | 515/1568 [01:29<03:02,  5.78it/s]16 03:01:06 Save the image 00334D_flip.png
 33%|████████████▊                          | 516/1568 [01:29<03:01,  5.80it/s]16 03:01:06 Save the image 00335D.png
 33%|████████████▊                          | 517/1568 [01:29<03:03,  5.74it/s]16 03:01:06 Save the image 00335D_flip.png
 33%|████████████▉                          | 518/1568 [01:30<03:02,  5.75it/s]16 03:01:07 Save the image 00336D.png
 33%|████████████▉                          | 519/1568 [01:30<03:03,  5.72it/s]16 03:01:07 Save the image 00336D_flip.png
 33%|████████████▉                          | 520/1568 [01:30<03:01,  5.77it/s]16 03:01:07 Save the image 00337D.png
 33%|████████████▉                          | 521/1568 [01:30<03:02,  5.72it/s]16 03:01:07 Save the image 00337D_flip.png
 33%|████████████▉                          | 522/1568 [01:30<03:03,  5.69it/s]16 03:01:07 Save the image 00338D.png
 33%|█████████████                          | 523/1568 [01:31<03:04,  5.67it/s]16 03:01:08 Save the image 00338D_flip.png
 33%|█████████████                          | 524/1568 [01:31<03:05,  5.63it/s]16 03:01:08 Save the image 00339D.png
 33%|█████████████                          | 525/1568 [01:31<03:08,  5.55it/s]16 03:01:08 Save the image 00339D_flip.png
 34%|█████████████                          | 526/1568 [01:31<03:06,  5.60it/s]16 03:01:08 Save the image 00340D.png
 34%|█████████████                          | 527/1568 [01:31<03:03,  5.66it/s]16 03:01:08 Save the image 00340D_flip.png
 34%|█████████████▏                         | 528/1568 [01:31<03:03,  5.68it/s]16 03:01:08 Save the image 00341D.png
 34%|█████████████▏                         | 529/1568 [01:32<03:05,  5.60it/s]16 03:01:09 Save the image 00341D_flip.png
 34%|█████████████▏                         | 530/1568 [01:32<03:03,  5.64it/s]16 03:01:09 Save the image 00342D.png
 34%|█████████████▏                         | 531/1568 [01:32<03:02,  5.68it/s]16 03:01:09 Save the image 00342D_flip.png
 34%|█████████████▏                         | 532/1568 [01:32<03:00,  5.75it/s]16 03:01:09 Save the image 00343D.png
 34%|█████████████▎                         | 533/1568 [01:32<02:53,  5.98it/s]16 03:01:09 Save the image 00343D_flip.png
 34%|█████████████▎                         | 534/1568 [01:32<02:55,  5.90it/s]16 03:01:09 Save the image 00344D.png
 34%|█████████████▎                         | 535/1568 [01:33<02:55,  5.87it/s]16 03:01:10 Save the image 00344D_flip.png
 34%|█████████████▎                         | 536/1568 [01:33<02:55,  5.87it/s]16 03:01:10 Save the image 00345D.png
 34%|█████████████▎                         | 537/1568 [01:33<02:57,  5.82it/s]16 03:01:10 Save the image 00345D_flip.png
 34%|█████████████▍                         | 538/1568 [01:33<02:58,  5.78it/s]16 03:01:10 Save the image 00346D.png
 34%|█████████████▍                         | 539/1568 [01:33<02:58,  5.75it/s]16 03:01:10 Save the image 00346D_flip.png
 34%|█████████████▍                         | 540/1568 [01:33<02:59,  5.72it/s]16 03:01:10 Save the image 00347D.png
 35%|█████████████▍                         | 541/1568 [01:34<02:49,  6.05it/s]16 03:01:11 Save the image 00347D_flip.png
 35%|█████████████▍                         | 542/1568 [01:34<02:53,  5.93it/s]16 03:01:11 Save the image 00348D.png
 35%|█████████████▌                         | 543/1568 [01:34<02:54,  5.87it/s]16 03:01:11 Save the image 00348D_flip.png
 35%|█████████████▌                         | 544/1568 [01:34<02:55,  5.83it/s]16 03:01:11 Save the image 00349D.png
 35%|█████████████▌                         | 545/1568 [01:34<02:56,  5.79it/s]16 03:01:11 Save the image 00349D_flip.png
 35%|█████████████▌                         | 546/1568 [01:34<02:57,  5.75it/s]16 03:01:12 Save the image 00350D.png
 35%|█████████████▌                         | 547/1568 [01:35<02:56,  5.77it/s]16 03:01:12 Save the image 00350D_flip.png
 35%|█████████████▋                         | 548/1568 [01:35<02:56,  5.79it/s]16 03:01:12 Save the image 00351D.png
 35%|█████████████▋                         | 549/1568 [01:35<02:45,  6.14it/s]16 03:01:12 Save the image 00351D_flip.png
 35%|█████████████▋                         | 550/1568 [01:35<02:49,  6.00it/s]16 03:01:12 Save the image 00352D.png
 35%|█████████████▋                         | 551/1568 [01:35<02:51,  5.94it/s]16 03:01:12 Save the image 00352D_flip.png
 35%|█████████████▋                         | 552/1568 [01:36<02:53,  5.87it/s]16 03:01:13 Save the image 00353D.png
 35%|█████████████▊                         | 553/1568 [01:36<02:54,  5.80it/s]16 03:01:13 Save the image 00353D_flip.png
 35%|█████████████▊                         | 554/1568 [01:36<02:57,  5.71it/s]16 03:01:13 Save the image 00354D.png
 35%|█████████████▊                         | 555/1568 [01:36<02:57,  5.70it/s]16 03:01:13 Save the image 00354D_flip.png
 35%|█████████████▊                         | 556/1568 [01:36<02:56,  5.72it/s]16 03:01:13 Save the image 00355D.png
 36%|█████████████▊                         | 557/1568 [01:36<02:46,  6.08it/s]16 03:01:13 Save the image 00355D_flip.png
 36%|█████████████▉                         | 558/1568 [01:37<02:50,  5.92it/s]16 03:01:14 Save the image 00356D.png
 36%|█████████████▉                         | 559/1568 [01:37<02:51,  5.90it/s]16 03:01:14 Save the image 00356D_flip.png
 36%|█████████████▉                         | 560/1568 [01:37<02:52,  5.86it/s]16 03:01:14 Save the image 00357D.png
 36%|█████████████▉                         | 561/1568 [01:37<02:54,  5.76it/s]16 03:01:14 Save the image 00357D_flip.png
 36%|█████████████▉                         | 562/1568 [01:37<02:57,  5.68it/s]16 03:01:14 Save the image 00358D.png
 36%|██████████████                         | 563/1568 [01:37<02:57,  5.67it/s]16 03:01:14 Save the image 00358D_flip.png
 36%|██████████████                         | 564/1568 [01:38<02:57,  5.65it/s]16 03:01:15 Save the image 00359D.png
 36%|██████████████                         | 565/1568 [01:38<02:48,  5.97it/s]16 03:01:15 Save the image 00359D_flip.png
 36%|██████████████                         | 566/1568 [01:38<02:50,  5.89it/s]16 03:01:15 Save the image 00360D.png
 36%|██████████████                         | 567/1568 [01:38<02:50,  5.87it/s]16 03:01:15 Save the image 00360D_flip.png
 36%|██████████████▏                        | 568/1568 [01:38<02:51,  5.85it/s]16 03:01:15 Save the image 00361D.png

 36%|██████████████▏                        | 569/1568 [01:38<02:53,  5.75it/s]16 03:01:15 Save the image 00361D_flip.png
 36%|██████████████▏                        | 570/1568 [01:39<02:54,  5.73it/s]16 03:01:16 Save the image 00362D.png
 36%|██████████████▏                        | 571/1568 [01:39<02:55,  5.69it/s]16 03:01:16 Save the image 00362D_flip.png
 36%|██████████████▏                        | 572/1568 [01:39<02:55,  5.66it/s]16 03:01:16 Save the image 00363D.png
 37%|██████████████▎                        | 573/1568 [01:39<02:45,  6.01it/s]16 03:01:16 Save the image 00363D_flip.png
 37%|██████████████▎                        | 574/1568 [01:39<02:48,  5.89it/s]16 03:01:16 Save the image 00364D.png
 37%|██████████████▎                        | 575/1568 [01:39<02:49,  5.86it/s]16 03:01:16 Save the image 00364D_flip.png
 37%|██████████████▎                        | 576/1568 [01:40<02:49,  5.87it/s]16 03:01:17 Save the image 00365D.png
 37%|██████████████▎                        | 577/1568 [01:40<02:50,  5.80it/s]16 03:01:17 Save the image 00365D_flip.png
 37%|██████████████▍                        | 578/1568 [01:40<02:52,  5.73it/s]16 03:01:17 Save the image 00366D.png
 37%|██████████████▍                        | 579/1568 [01:40<02:52,  5.72it/s]16 03:01:17 Save the image 00366D_flip.png
 37%|██████████████▍                        | 580/1568 [01:40<02:52,  5.73it/s]16 03:01:17 Save the image 00367D.png
 37%|██████████████▍                        | 581/1568 [01:40<02:43,  6.04it/s]16 03:01:18 Save the image 00367D_flip.png
 37%|██████████████▍                        | 582/1568 [01:41<02:48,  5.84it/s]16 03:01:18 Save the image 00368D.png
 37%|██████████████▌                        | 583/1568 [01:41<02:48,  5.83it/s]16 03:01:18 Save the image 00368D_flip.png
 37%|██████████████▌                        | 584/1568 [01:41<02:50,  5.78it/s]16 03:01:18 Save the image 00369D.png
 37%|██████████████▌                        | 585/1568 [01:41<02:52,  5.69it/s]16 03:01:18 Save the image 00369D_flip.png
 37%|██████████████▌                        | 586/1568 [01:41<02:52,  5.70it/s]16 03:01:18 Save the image 00370D.png
 37%|██████████████▌                        | 587/1568 [01:42<02:52,  5.69it/s]16 03:01:19 Save the image 00370D_flip.png
 38%|██████████████▋                        | 588/1568 [01:42<02:51,  5.73it/s]16 03:01:19 Save the image 00371D.png
 38%|██████████████▋                        | 589/1568 [01:42<02:41,  6.05it/s]16 03:01:19 Save the image 00371D_flip.png
 38%|██████████████▋                        | 590/1568 [01:42<02:45,  5.93it/s]16 03:01:19 Save the image 00372D.png
 38%|██████████████▋                        | 591/1568 [01:42<02:45,  5.89it/s]16 03:01:19 Save the image 00372D_flip.png
 38%|██████████████▋                        | 592/1568 [01:42<02:46,  5.85it/s]16 03:01:19 Save the image 00373D.png
 38%|██████████████▋                        | 593/1568 [01:43<02:48,  5.79it/s]16 03:01:20 Save the image 00373D_flip.png
 38%|██████████████▊                        | 594/1568 [01:43<02:47,  5.82it/s]16 03:01:20 Save the image 00374D.png
 38%|██████████████▊                        | 595/1568 [01:43<02:48,  5.77it/s]16 03:01:20 Save the image 00374D_flip.png
 38%|██████████████▊                        | 596/1568 [01:43<02:48,  5.77it/s]16 03:01:20 Save the image 00375D.png
 38%|██████████████▊                        | 597/1568 [01:43<02:48,  5.78it/s]16 03:01:20 Save the image 00375D_flip.png
 38%|██████████████▊                        | 598/1568 [01:43<02:48,  5.77it/s]16 03:01:20 Save the image 00376D.png
 38%|██████████████▉                        | 599/1568 [01:44<02:47,  5.77it/s]16 03:01:21 Save the image 00376D_flip.png
 38%|██████████████▉                        | 600/1568 [01:44<02:48,  5.75it/s]16 03:01:21 Save the image 00377D.png
 38%|██████████████▉                        | 601/1568 [01:44<02:48,  5.75it/s]16 03:01:21 Save the image 00377D_flip.png
 38%|██████████████▉                        | 602/1568 [01:44<02:46,  5.80it/s]16 03:01:21 Save the image 00378D.png
 38%|██████████████▉                        | 603/1568 [01:44<02:45,  5.82it/s]16 03:01:21 Save the image 00378D_flip.png
 39%|███████████████                        | 604/1568 [01:44<02:47,  5.75it/s]16 03:01:21 Save the image 00379D.png
 39%|███████████████                        | 605/1568 [01:45<02:49,  5.68it/s]16 03:01:22 Save the image 00379D_flip.png
 39%|███████████████                        | 606/1568 [01:45<02:49,  5.68it/s]16 03:01:22 Save the image 00380D.png
 39%|███████████████                        | 607/1568 [01:45<02:47,  5.72it/s]16 03:01:22 Save the image 00380D_flip.png
 39%|███████████████                        | 608/1568 [01:45<02:50,  5.64it/s]16 03:01:22 Save the image 00381D.png
 39%|███████████████▏                       | 609/1568 [01:45<02:50,  5.63it/s]16 03:01:22 Save the image 00381D_flip.png
 39%|███████████████▏                       | 610/1568 [01:46<02:49,  5.65it/s]16 03:01:23 Save the image 00382D.png
 39%|███████████████▏                       | 611/1568 [01:46<02:49,  5.64it/s]16 03:01:23 Save the image 00382D_flip.png
 39%|███████████████▏                       | 612/1568 [01:46<02:43,  5.85it/s]16 03:01:23 Save the image 00383D.png
 39%|███████████████▏                       | 613/1568 [01:46<02:45,  5.77it/s]16 03:01:23 Save the image 00383D_flip.png
 39%|███████████████▎                       | 614/1568 [01:46<02:46,  5.74it/s]16 03:01:23 Save the image 00384D.png
 39%|███████████████▎                       | 615/1568 [01:46<02:47,  5.70it/s]16 03:01:23 Save the image 00384D_flip.png
 39%|███████████████▎                       | 616/1568 [01:47<02:48,  5.66it/s]16 03:01:24 Save the image 00385D.png
 39%|███████████████▎                       | 617/1568 [01:47<02:47,  5.67it/s]16 03:01:24 Save the image 00385D_flip.png
 39%|███████████████▎                       | 618/1568 [01:47<02:47,  5.67it/s]16 03:01:24 Save the image 00386D.png
 39%|███████████████▍                       | 619/1568 [01:47<02:47,  5.65it/s]16 03:01:24 Save the image 00386D_flip.png
 40%|███████████████▍                       | 620/1568 [01:47<02:38,  5.96it/s]16 03:01:24 Save the image 00387D.png
 40%|███████████████▍                       | 621/1568 [01:47<02:41,  5.87it/s]16 03:01:24 Save the image 00387D_flip.png
 40%|███████████████▍                       | 622/1568 [01:48<02:41,  5.86it/s]16 03:01:25 Save the image 00388D.png
 40%|███████████████▍                       | 623/1568 [01:48<02:42,  5.82it/s]16 03:01:25 Save the image 00388D_flip.png
 40%|███████████████▌                       | 624/1568 [01:48<02:45,  5.72it/s]16 03:01:25 Save the image 00389D.png
 40%|███████████████▌                       | 625/1568 [01:48<02:46,  5.67it/s]16 03:01:25 Save the image 00389D_flip.png
 40%|███████████████▌                       | 626/1568 [01:48<02:46,  5.67it/s]16 03:01:25 Save the image 00390D.png
 40%|███████████████▌                       | 627/1568 [01:49<02:45,  5.68it/s]16 03:01:25 Save the image 00390D_flip.png
 40%|███████████████▌                       | 628/1568 [01:49<02:35,  6.04it/s]16 03:01:26 Save the image 00391D.png
 40%|███████████████▋                       | 629/1568 [01:49<02:38,  5.92it/s]16 03:01:26 Save the image 00391D_flip.png
 40%|███████████████▋                       | 630/1568 [01:49<02:39,  5.89it/s]16 03:01:26 Save the image 00392D.png
 40%|███████████████▋                       | 631/1568 [01:49<02:39,  5.86it/s]16 03:01:26 Save the image 00392D_flip.png
 40%|███████████████▋                       | 632/1568 [01:49<02:41,  5.81it/s]16 03:01:26 Save the image 00393D.png

 40%|███████████████▋                       | 633/1568 [01:50<02:41,  5.78it/s]16 03:01:27 Save the image 00393D_flip.png
 40%|███████████████▊                       | 634/1568 [01:50<02:42,  5.75it/s]16 03:01:27 Save the image 00394D.png
 40%|███████████████▊                       | 635/1568 [01:50<02:42,  5.73it/s]16 03:01:27 Save the image 00394D_flip.png
 41%|███████████████▊                       | 636/1568 [01:50<02:33,  6.08it/s]16 03:01:27 Save the image 00395D.png
 41%|███████████████▊                       | 637/1568 [01:50<02:36,  5.95it/s]16 03:01:27 Save the image 00395D_flip.png
 41%|███████████████▊                       | 638/1568 [01:50<02:37,  5.91it/s]16 03:01:27 Save the image 00396D.png
 41%|███████████████▉                       | 639/1568 [01:51<02:38,  5.85it/s]16 03:01:28 Save the image 00396D_flip.png
 41%|███████████████▉                       | 640/1568 [01:51<02:39,  5.80it/s]16 03:01:28 Save the image 00397D.png
 41%|███████████████▉                       | 641/1568 [01:51<02:38,  5.83it/s]16 03:01:28 Save the image 00397D_flip.png
 41%|███████████████▉                       | 642/1568 [01:51<02:40,  5.79it/s]16 03:01:28 Save the image 00398D.png
 41%|███████████████▉                       | 643/1568 [01:51<02:40,  5.78it/s]16 03:01:28 Save the image 00398D_flip.png
 41%|████████████████                       | 644/1568 [01:51<02:40,  5.77it/s]16 03:01:28 Save the image 00399D.png
 41%|████████████████                       | 645/1568 [01:52<02:40,  5.73it/s]16 03:01:29 Save the image 00399D_flip.png
 41%|████████████████                       | 646/1568 [01:52<02:40,  5.75it/s]16 03:01:29 Save the image 00400D.png
 41%|████████████████                       | 647/1568 [01:52<02:40,  5.74it/s]16 03:01:29 Save the image 00400D_flip.png
 41%|████████████████                       | 648/1568 [01:52<02:39,  5.76it/s]16 03:01:29 Save the image 00401D.png
 41%|████████████████▏                      | 649/1568 [01:52<02:38,  5.79it/s]16 03:01:29 Save the image 00401D_flip.png
 41%|████████████████▏                      | 650/1568 [01:52<02:37,  5.81it/s]16 03:01:29 Save the image 00402D.png
 42%|████████████████▏                      | 651/1568 [01:53<02:39,  5.76it/s]16 03:01:30 Save the image 00402D_flip.png
 42%|████████████████▏                      | 652/1568 [01:53<02:39,  5.74it/s]16 03:01:30 Save the image 00403D.png
 42%|████████████████▏                      | 653/1568 [01:53<02:39,  5.75it/s]16 03:01:30 Save the image 00403D_flip.png
 42%|████████████████▎                      | 654/1568 [01:53<02:38,  5.77it/s]16 03:01:30 Save the image 00404D.png
 42%|████████████████▎                      | 655/1568 [01:53<02:39,  5.74it/s]16 03:01:30 Save the image 00404D_flip.png
 42%|████████████████▎                      | 656/1568 [01:53<02:39,  5.71it/s]16 03:01:30 Save the image 00405D.png
 42%|████████████████▎                      | 657/1568 [01:54<02:38,  5.73it/s]16 03:01:31 Save the image 00405D_flip.png
 42%|████████████████▎                      | 658/1568 [01:54<02:39,  5.72it/s]16 03:01:31 Save the image 00406D.png
 42%|████████████████▍                      | 659/1568 [01:54<02:29,  6.07it/s]16 03:01:31 Save the image 00406D_flip.png
 42%|████████████████▍                      | 660/1568 [01:54<02:32,  5.94it/s]16 03:01:31 Save the image 00407D.png
 42%|████████████████▍                      | 661/1568 [01:54<02:33,  5.89it/s]16 03:01:31 Save the image 00407D_flip.png
 42%|████████████████▍                      | 662/1568 [01:54<02:34,  5.86it/s]16 03:01:32 Save the image 00408D.png
 42%|████████████████▍                      | 663/1568 [01:55<02:36,  5.80it/s]16 03:01:32 Save the image 00408D_flip.png
 42%|████████████████▌                      | 664/1568 [01:55<02:37,  5.76it/s]16 03:01:32 Save the image 00409D.png
 42%|████████████████▌                      | 665/1568 [01:55<02:36,  5.76it/s]16 03:01:32 Save the image 00409D_flip.png
 42%|████████████████▌                      | 666/1568 [01:55<02:36,  5.75it/s]16 03:01:32 Save the image 00410D.png
 43%|████████████████▌                      | 667/1568 [01:55<02:27,  6.09it/s]16 03:01:32 Save the image 00410D_flip.png
 43%|████████████████▌                      | 668/1568 [01:56<02:31,  5.96it/s]16 03:01:33 Save the image 00411D.png
 43%|████████████████▋                      | 669/1568 [01:56<02:32,  5.91it/s]16 03:01:33 Save the image 00411D_flip.png
 43%|████████████████▋                      | 670/1568 [01:56<02:33,  5.86it/s]16 03:01:33 Save the image 00412D.png
 43%|████████████████▋                      | 671/1568 [01:56<02:34,  5.79it/s]16 03:01:33 Save the image 00412D_flip.png
 43%|████████████████▋                      | 672/1568 [01:56<02:34,  5.79it/s]16 03:01:33 Save the image 00413D.png
 43%|████████████████▋                      | 673/1568 [01:56<02:36,  5.72it/s]16 03:01:33 Save the image 00413D_flip.png
 43%|████████████████▊                      | 674/1568 [01:57<02:35,  5.76it/s]16 03:01:34 Save the image 00414D.png
 43%|████████████████▊                      | 675/1568 [01:57<02:34,  5.76it/s]16 03:01:34 Save the image 00414D_flip.png
 43%|████████████████▊                      | 676/1568 [01:57<02:35,  5.74it/s]16 03:01:34 Save the image 00415D.png
 43%|████████████████▊                      | 677/1568 [01:57<02:34,  5.76it/s]16 03:01:34 Save the image 00415D_flip.png
 43%|████████████████▊                      | 678/1568 [01:57<02:34,  5.77it/s]16 03:01:34 Save the image 00416D.png
 43%|████████████████▉                      | 679/1568 [01:57<02:34,  5.74it/s]16 03:01:34 Save the image 00416D_flip.png
 43%|████████████████▉                      | 680/1568 [01:58<02:33,  5.80it/s]16 03:01:35 Save the image 00417D.png
 43%|████████████████▉                      | 681/1568 [01:58<02:32,  5.80it/s]16 03:01:35 Save the image 00417D_flip.png
 43%|████████████████▉                      | 682/1568 [01:58<02:35,  5.70it/s]16 03:01:35 Save the image 00418D.png
 44%|████████████████▉                      | 683/1568 [01:58<02:35,  5.68it/s]16 03:01:35 Save the image 00418D_flip.png
 44%|█████████████████                      | 684/1568 [01:58<02:35,  5.67it/s]16 03:01:35 Save the image 00419D.png
 44%|█████████████████                      | 685/1568 [01:58<02:35,  5.66it/s]16 03:01:36 Save the image 00419D_flip.png
 44%|█████████████████                      | 686/1568 [01:59<02:37,  5.59it/s]16 03:01:36 Save the image 00420D.png
 44%|█████████████████                      | 687/1568 [01:59<02:37,  5.61it/s]16 03:01:36 Save the image 00420D_flip.png
 44%|█████████████████                      | 688/1568 [01:59<02:37,  5.60it/s]16 03:01:36 Save the image 00421D.png
 44%|█████████████████▏                     | 689/1568 [01:59<02:35,  5.65it/s]16 03:01:36 Save the image 00421D_flip.png
 44%|█████████████████▏                     | 690/1568 [01:59<02:32,  5.75it/s]16 03:01:36 Save the image 00422D.png
 44%|█████████████████▏                     | 691/1568 [02:00<02:34,  5.69it/s]16 03:01:37 Save the image 00422D_flip.png
 44%|█████████████████▏                     | 692/1568 [02:00<02:34,  5.68it/s]16 03:01:37 Save the image 00423D.png
 44%|█████████████████▏                     | 693/1568 [02:00<02:34,  5.65it/s]16 03:01:37 Save the image 00423D_flip.png
 44%|█████████████████▎                     | 694/1568 [02:00<02:35,  5.63it/s]16 03:01:37 Save the image 00424D.png
 44%|█████████████████▎                     | 695/1568 [02:00<02:34,  5.64it/s]16 03:01:37 Save the image 00424D_flip.png
 44%|█████████████████▎                     | 696/1568 [02:00<02:34,  5.65it/s]16 03:01:37 Save the image 00425D.png

 44%|█████████████████▎                     | 697/1568 [02:01<02:32,  5.72it/s]16 03:01:38 Save the image 00425D_flip.png
 45%|█████████████████▎                     | 698/1568 [02:01<02:28,  5.84it/s]16 03:01:38 Save the image 00426D.png
 45%|█████████████████▍                     | 699/1568 [02:01<02:30,  5.76it/s]16 03:01:38 Save the image 00426D_flip.png
 45%|█████████████████▍                     | 700/1568 [02:01<02:31,  5.73it/s]16 03:01:38 Save the image 00427D.png
 45%|█████████████████▍                     | 701/1568 [02:01<02:31,  5.73it/s]16 03:01:38 Save the image 00427D_flip.png
 45%|█████████████████▍                     | 702/1568 [02:01<02:32,  5.70it/s]16 03:01:38 Save the image 00428D.png
 45%|█████████████████▍                     | 703/1568 [02:02<02:32,  5.67it/s]16 03:01:39 Save the image 00428D_flip.png
 45%|█████████████████▌                     | 704/1568 [02:02<02:32,  5.68it/s]16 03:01:39 Save the image 00429D.png
 45%|█████████████████▌                     | 705/1568 [02:02<02:29,  5.76it/s]16 03:01:39 Save the image 00429D_flip.png
 45%|█████████████████▌                     | 706/1568 [02:02<02:26,  5.88it/s]16 03:01:39 Save the image 00430D.png
 45%|█████████████████▌                     | 707/1568 [02:02<02:27,  5.83it/s]16 03:01:39 Save the image 00430D_flip.png
 45%|█████████████████▌                     | 708/1568 [02:03<02:27,  5.83it/s]16 03:01:40 Save the image 00431D.png
 45%|█████████████████▋                     | 709/1568 [02:03<02:28,  5.79it/s]16 03:01:40 Save the image 00431D_flip.png
 45%|█████████████████▋                     | 710/1568 [02:03<02:29,  5.75it/s]16 03:01:40 Save the image 00432D.png
 45%|█████████████████▋                     | 711/1568 [02:03<02:29,  5.73it/s]16 03:01:40 Save the image 00432D_flip.png
 45%|█████████████████▋                     | 712/1568 [02:03<02:28,  5.76it/s]16 03:01:40 Save the image 00433D.png
 45%|█████████████████▋                     | 713/1568 [02:03<02:29,  5.74it/s]16 03:01:40 Save the image 00433D_flip.png
 46%|█████████████████▊                     | 714/1568 [02:04<02:20,  6.09it/s]16 03:01:41 Save the image 00434D.png
 46%|█████████████████▊                     | 715/1568 [02:04<02:23,  5.96it/s]16 03:01:41 Save the image 00434D_flip.png
 46%|█████████████████▊                     | 716/1568 [02:04<02:23,  5.93it/s]16 03:01:41 Save the image 00435D.png
 46%|█████████████████▊                     | 717/1568 [02:04<02:24,  5.89it/s]16 03:01:41 Save the image 00435D_flip.png
 46%|█████████████████▊                     | 718/1568 [02:04<02:25,  5.83it/s]16 03:01:41 Save the image 00436D.png
 46%|█████████████████▉                     | 719/1568 [02:04<02:25,  5.82it/s]16 03:01:41 Save the image 00436D_flip.png
 46%|█████████████████▉                     | 720/1568 [02:05<02:26,  5.81it/s]16 03:01:42 Save the image 00437D.png
 46%|█████████████████▉                     | 721/1568 [02:05<02:26,  5.77it/s]16 03:01:42 Save the image 00437D_flip.png
 46%|█████████████████▉                     | 722/1568 [02:05<02:18,  6.11it/s]16 03:01:42 Save the image 00438D.png
 46%|█████████████████▉                     | 723/1568 [02:05<02:21,  5.97it/s]16 03:01:42 Save the image 00438D_flip.png
 46%|██████████████████                     | 724/1568 [02:05<02:22,  5.93it/s]16 03:01:42 Save the image 00439D.png
 46%|██████████████████                     | 725/1568 [02:05<02:22,  5.92it/s]16 03:01:42 Save the image 00439D_flip.png
 46%|██████████████████                     | 726/1568 [02:06<02:24,  5.84it/s]16 03:01:43 Save the image 00440D.png
 46%|██████████████████                     | 727/1568 [02:06<02:23,  5.86it/s]16 03:01:43 Save the image 00440D_flip.png
 46%|██████████████████                     | 728/1568 [02:06<02:24,  5.81it/s]16 03:01:43 Save the image 00441D.png
 46%|██████████████████▏                    | 729/1568 [02:06<02:24,  5.79it/s]16 03:01:43 Save the image 00441D_flip.png
 47%|██████████████████▏                    | 730/1568 [02:06<02:24,  5.81it/s]16 03:01:43 Save the image 00442D.png
 47%|██████████████████▏                    | 731/1568 [02:06<02:24,  5.78it/s]16 03:01:43 Save the image 00442D_flip.png
 47%|██████████████████▏                    | 732/1568 [02:07<02:24,  5.78it/s]16 03:01:44 Save the image 00443D.png
 47%|██████████████████▏                    | 733/1568 [02:07<02:24,  5.78it/s]16 03:01:44 Save the image 00443D_flip.png
 47%|██████████████████▎                    | 734/1568 [02:07<02:24,  5.76it/s]16 03:01:44 Save the image 00444D.png
 47%|██████████████████▎                    | 735/1568 [02:07<02:23,  5.81it/s]16 03:01:44 Save the image 00444D_flip.png
 47%|██████████████████▎                    | 736/1568 [02:07<02:22,  5.85it/s]16 03:01:44 Save the image 00445D.png
 47%|██████████████████▎                    | 737/1568 [02:07<02:23,  5.81it/s]16 03:01:44 Save the image 00445D_flip.png
 47%|██████████████████▎                    | 738/1568 [02:08<02:23,  5.78it/s]16 03:01:45 Save the image 00446D.png
 47%|██████████████████▍                    | 739/1568 [02:08<02:23,  5.79it/s]16 03:01:45 Save the image 00446D_flip.png
 47%|██████████████████▍                    | 740/1568 [02:08<02:23,  5.79it/s]16 03:01:45 Save the image 00447D.png
 47%|██████████████████▍                    | 741/1568 [02:08<02:24,  5.73it/s]16 03:01:45 Save the image 00447D_flip.png
 47%|██████████████████▍                    | 742/1568 [02:08<02:23,  5.75it/s]16 03:01:45 Save the image 00448D.png
 47%|██████████████████▍                    | 743/1568 [02:09<02:23,  5.73it/s]16 03:01:46 Save the image 00448D_flip.png
 47%|██████████████████▌                    | 744/1568 [02:09<02:21,  5.80it/s]16 03:01:46 Save the image 00449D.png
 48%|██████████████████▌                    | 745/1568 [02:09<02:17,  5.99it/s]16 03:01:46 Save the image 00449D_flip.png
 48%|██████████████████▌                    | 746/1568 [02:09<02:19,  5.91it/s]16 03:01:46 Save the image 00450D.png
 48%|██████████████████▌                    | 747/1568 [02:09<02:19,  5.87it/s]16 03:01:46 Save the image 00450D_flip.png
 48%|██████████████████▌                    | 748/1568 [02:09<02:20,  5.86it/s]16 03:01:46 Save the image 00451D.png
 48%|██████████████████▋                    | 749/1568 [02:10<02:21,  5.81it/s]16 03:01:47 Save the image 00451D_flip.png
 48%|██████████████████▋                    | 750/1568 [02:10<02:21,  5.77it/s]16 03:01:47 Save the image 00452D.png
 48%|██████████████████▋                    | 751/1568 [02:10<02:21,  5.77it/s]16 03:01:47 Save the image 00452D_flip.png
 48%|██████████████████▋                    | 752/1568 [02:10<02:22,  5.72it/s]16 03:01:47 Save the image 00453D.png
 48%|██████████████████▋                    | 753/1568 [02:10<02:14,  6.07it/s]16 03:01:47 Save the image 00453D_flip.png
 48%|██████████████████▊                    | 754/1568 [02:10<02:17,  5.91it/s]16 03:01:47 Save the image 00454D.png
 48%|██████████████████▊                    | 755/1568 [02:11<02:20,  5.80it/s]16 03:01:48 Save the image 00454D_flip.png
 48%|██████████████████▊                    | 756/1568 [02:11<02:20,  5.78it/s]16 03:01:48 Save the image 00455D.png
 48%|██████████████████▊                    | 757/1568 [02:11<02:21,  5.75it/s]16 03:01:48 Save the image 00455D_flip.png
 48%|██████████████████▊                    | 758/1568 [02:11<02:20,  5.77it/s]16 03:01:48 Save the image 00456D.png
 48%|██████████████████▉                    | 759/1568 [02:11<02:19,  5.79it/s]16 03:01:48 Save the image 00456D_flip.png
 48%|██████████████████▉                    | 760/1568 [02:11<02:20,  5.76it/s]16 03:01:48 Save the image 00457D.png

 49%|██████████████████▉                    | 761/1568 [02:12<02:12,  6.08it/s]16 03:01:49 Save the image 00457D_flip.png
 49%|██████████████████▉                    | 762/1568 [02:12<02:15,  5.95it/s]16 03:01:49 Save the image 00458D.png
 49%|██████████████████▉                    | 763/1568 [02:12<02:16,  5.92it/s]16 03:01:49 Save the image 00458D_flip.png
 49%|███████████████████                    | 764/1568 [02:12<02:17,  5.86it/s]16 03:01:49 Save the image 00459D.png
 49%|███████████████████                    | 765/1568 [02:12<02:18,  5.80it/s]16 03:01:49 Save the image 00459D_flip.png
 49%|███████████████████                    | 766/1568 [02:12<02:17,  5.83it/s]16 03:01:49 Save the image 00460D.png
 49%|███████████████████                    | 767/1568 [02:13<02:18,  5.78it/s]16 03:01:50 Save the image 00460D_flip.png
 49%|███████████████████                    | 768/1568 [02:13<02:19,  5.75it/s]16 03:01:50 Save the image 00461D.png
 49%|███████████████████▏                   | 769/1568 [02:13<02:19,  5.73it/s]16 03:01:50 Save the image 00461D_flip.png
 49%|███████████████████▏                   | 770/1568 [02:13<02:18,  5.75it/s]16 03:01:50 Save the image 00462D.png
 49%|███████████████████▏                   | 771/1568 [02:13<02:17,  5.80it/s]16 03:01:50 Save the image 00462D_flip.png
 49%|███████████████████▏                   | 772/1568 [02:13<02:17,  5.79it/s]16 03:01:51 Save the image 00463D.png
 49%|███████████████████▏                   | 773/1568 [02:14<02:17,  5.79it/s]16 03:01:51 Save the image 00463D_flip.png
 49%|███████████████████▎                   | 774/1568 [02:14<02:16,  5.84it/s]16 03:01:51 Save the image 00464D.png
 49%|███████████████████▎                   | 775/1568 [02:14<02:15,  5.86it/s]16 03:01:51 Save the image 00464D_flip.png
 49%|███████████████████▎                   | 776/1568 [02:14<02:16,  5.81it/s]16 03:01:51 Save the image 00465D.png
 50%|███████████████████▎                   | 777/1568 [02:14<02:17,  5.77it/s]16 03:01:51 Save the image 00465D_flip.png
 50%|███████████████████▎                   | 778/1568 [02:15<02:16,  5.78it/s]16 03:01:52 Save the image 00466D.png
 50%|███████████████████▍                   | 779/1568 [02:15<02:15,  5.81it/s]16 03:01:52 Save the image 00466D_flip.png
 50%|███████████████████▍                   | 780/1568 [02:15<02:17,  5.72it/s]16 03:01:52 Save the image 00478D.png
 50%|███████████████████▍                   | 781/1568 [02:15<02:17,  5.71it/s]16 03:01:52 Save the image 00478D_flip.png
 50%|███████████████████▍                   | 782/1568 [02:15<02:19,  5.62it/s]16 03:01:52 Save the image 00479D.png
 50%|███████████████████▍                   | 783/1568 [02:15<02:17,  5.70it/s]16 03:01:52 Save the image 00479D_flip.png
 50%|███████████████████▌                   | 784/1568 [02:16<02:12,  5.92it/s]16 03:01:53 Save the image 00480D.png
 50%|███████████████████▌                   | 785/1568 [02:16<02:14,  5.84it/s]16 03:01:53 Save the image 00480D_flip.png
 50%|███████████████████▌                   | 786/1568 [02:16<02:14,  5.83it/s]16 03:01:53 Save the image 00481D.png
 50%|███████████████████▌                   | 787/1568 [02:16<02:14,  5.81it/s]16 03:01:53 Save the image 00481D_flip.png
 50%|███████████████████▌                   | 788/1568 [02:16<02:15,  5.77it/s]16 03:01:53 Save the image 00482D.png
 50%|███████████████████▌                   | 789/1568 [02:16<02:15,  5.74it/s]16 03:01:53 Save the image 00482D_flip.png
 50%|███████████████████▋                   | 790/1568 [02:17<02:15,  5.76it/s]16 03:01:54 Save the image 00483D.png
 50%|███████████████████▋                   | 791/1568 [02:17<02:15,  5.73it/s]16 03:01:54 Save the image 00483D_flip.png
 51%|███████████████████▋                   | 792/1568 [02:17<02:07,  6.08it/s]16 03:01:54 Save the image 00484D.png
 51%|███████████████████▋                   | 793/1568 [02:17<02:10,  5.95it/s]16 03:01:54 Save the image 00484D_flip.png
 51%|███████████████████▋                   | 794/1568 [02:17<02:10,  5.91it/s]16 03:01:54 Save the image 00485D.png
 51%|███████████████████▊                   | 795/1568 [02:17<02:11,  5.88it/s]16 03:01:54 Save the image 00485D_flip.png
 51%|███████████████████▊                   | 796/1568 [02:18<02:12,  5.81it/s]16 03:01:55 Save the image 00486D.png
 51%|███████████████████▊                   | 797/1568 [02:18<02:12,  5.83it/s]16 03:01:55 Save the image 00486D_flip.png
 51%|███████████████████▊                   | 798/1568 [02:18<02:13,  5.78it/s]16 03:01:55 Save the image 00487D.png
 51%|███████████████████▊                   | 799/1568 [02:18<02:13,  5.78it/s]16 03:01:55 Save the image 00487D_flip.png
 51%|███████████████████▉                   | 800/1568 [02:18<02:04,  6.16it/s]16 03:01:55 Save the image 00488D.png
 51%|███████████████████▉                   | 801/1568 [02:18<02:07,  6.00it/s]16 03:01:55 Save the image 00488D_flip.png
 51%|███████████████████▉                   | 802/1568 [02:19<02:08,  5.95it/s]16 03:01:56 Save the image 00489D.png
 51%|███████████████████▉                   | 803/1568 [02:19<02:10,  5.88it/s]16 03:01:56 Save the image 00489D_flip.png
 51%|███████████████████▉                   | 804/1568 [02:19<02:11,  5.82it/s]16 03:01:56 Save the image 00490D.png
 51%|████████████████████                   | 805/1568 [02:19<02:10,  5.84it/s]16 03:01:56 Save the image 00490D_flip.png
 51%|████████████████████                   | 806/1568 [02:19<02:11,  5.79it/s]16 03:01:56 Save the image 00491D.png
 51%|████████████████████                   | 807/1568 [02:19<02:11,  5.80it/s]16 03:01:57 Save the image 00491D_flip.png
 52%|████████████████████                   | 808/1568 [02:20<02:11,  5.79it/s]16 03:01:57 Save the image 00492D.png
 52%|████████████████████                   | 809/1568 [02:20<02:11,  5.76it/s]16 03:01:57 Save the image 00492D_flip.png
 52%|████████████████████▏                  | 810/1568 [02:20<02:11,  5.77it/s]16 03:01:57 Save the image 00493D.png
 52%|████████████████████▏                  | 811/1568 [02:20<02:11,  5.75it/s]16 03:01:57 Save the image 00493D_flip.png
 52%|████████████████████▏                  | 812/1568 [02:20<02:11,  5.76it/s]16 03:01:57 Save the image 00494D.png
 52%|████████████████████▏                  | 813/1568 [02:21<02:09,  5.82it/s]16 03:01:58 Save the image 00494D_flip.png
 52%|████████████████████▏                  | 814/1568 [02:21<02:08,  5.86it/s]16 03:01:58 Save the image 00495D.png
 52%|████████████████████▎                  | 815/1568 [02:21<02:09,  5.81it/s]16 03:01:58 Save the image 00495D_flip.png
 52%|████████████████████▎                  | 816/1568 [02:21<02:10,  5.78it/s]16 03:01:58 Save the image 00496D.png
 52%|████████████████████▎                  | 817/1568 [02:21<02:09,  5.79it/s]16 03:01:58 Save the image 00496D_flip.png
 52%|████████████████████▎                  | 818/1568 [02:21<02:09,  5.81it/s]16 03:01:58 Save the image 00497D.png
 52%|████████████████████▎                  | 819/1568 [02:22<02:09,  5.78it/s]16 03:01:59 Save the image 00497D_flip.png
 52%|████████████████████▍                  | 820/1568 [02:22<02:10,  5.74it/s]16 03:01:59 Save the image 00003N.png
 52%|████████████████████▍                  | 821/1568 [02:22<02:10,  5.73it/s]16 03:01:59 Save the image 00003N_flip.png
 52%|████████████████████▍                  | 822/1568 [02:22<02:08,  5.79it/s]16 03:01:59 Save the image 00004N.png
 52%|████████████████████▍                  | 823/1568 [02:22<02:03,  6.05it/s]16 03:01:59 Save the image 00004N_flip.png
 53%|████████████████████▍                  | 824/1568 [02:22<02:05,  5.93it/s]16 03:01:59 Save the image 00005N.png

 53%|████████████████████▌                  | 825/1568 [02:23<02:06,  5.89it/s]16 03:02:00 Save the image 00005N_flip.png
 53%|████████████████████▌                  | 826/1568 [02:23<02:06,  5.85it/s]16 03:02:00 Save the image 00006N.png
 53%|████████████████████▌                  | 827/1568 [02:23<02:07,  5.80it/s]16 03:02:00 Save the image 00006N_flip.png
 53%|████████████████████▌                  | 828/1568 [02:23<02:08,  5.76it/s]16 03:02:00 Save the image 00007N.png
 53%|████████████████████▌                  | 829/1568 [02:23<02:07,  5.78it/s]16 03:02:00 Save the image 00007N_flip.png
 53%|████████████████████▋                  | 830/1568 [02:23<02:07,  5.77it/s]16 03:02:00 Save the image 00008N.png
 53%|████████████████████▋                  | 831/1568 [02:24<02:00,  6.11it/s]16 03:02:01 Save the image 00008N_flip.png
 53%|████████████████████▋                  | 832/1568 [02:24<02:03,  5.97it/s]16 03:02:01 Save the image 00009N.png
 53%|████████████████████▋                  | 833/1568 [02:24<02:03,  5.93it/s]16 03:02:01 Save the image 00009N_flip.png
 53%|████████████████████▋                  | 834/1568 [02:24<02:03,  5.92it/s]16 03:02:01 Save the image 00010N.png
 53%|████████████████████▊                  | 835/1568 [02:24<02:05,  5.84it/s]16 03:02:01 Save the image 00010N_flip.png
 53%|████████████████████▊                  | 836/1568 [02:24<02:05,  5.81it/s]16 03:02:01 Save the image 00011N.png
 53%|████████████████████▊                  | 837/1568 [02:25<02:05,  5.80it/s]16 03:02:02 Save the image 00011N_flip.png
 53%|████████████████████▊                  | 838/1568 [02:25<02:05,  5.80it/s]16 03:02:02 Save the image 00012N.png
 54%|████████████████████▊                  | 839/1568 [02:25<01:58,  6.13it/s]16 03:02:02 Save the image 00012N_flip.png
 54%|████████████████████▉                  | 840/1568 [02:25<02:01,  5.99it/s]16 03:02:02 Save the image 00013N.png
 54%|████████████████████▉                  | 841/1568 [02:25<02:02,  5.95it/s]16 03:02:02 Save the image 00013N_flip.png
 54%|████████████████████▉                  | 842/1568 [02:25<02:03,  5.88it/s]16 03:02:02 Save the image 00014N.png
 54%|████████████████████▉                  | 843/1568 [02:26<02:04,  5.82it/s]16 03:02:03 Save the image 00014N_flip.png
 54%|████████████████████▉                  | 844/1568 [02:26<02:04,  5.84it/s]16 03:02:03 Save the image 00015N.png
 54%|█████████████████████                  | 845/1568 [02:26<02:04,  5.79it/s]16 03:02:03 Save the image 00015N_flip.png
 54%|█████████████████████                  | 846/1568 [02:26<02:04,  5.78it/s]16 03:02:03 Save the image 00016N.png
 54%|█████████████████████                  | 847/1568 [02:26<02:04,  5.79it/s]16 03:02:03 Save the image 00016N_flip.png
 54%|█████████████████████                  | 848/1568 [02:27<02:05,  5.76it/s]16 03:02:04 Save the image 00017N.png
 54%|█████████████████████                  | 849/1568 [02:27<02:04,  5.76it/s]16 03:02:04 Save the image 00017N_flip.png
 54%|█████████████████████▏                 | 850/1568 [02:27<02:05,  5.70it/s]16 03:02:04 Save the image 00018N.png
 54%|█████████████████████▏                 | 851/1568 [02:27<02:05,  5.71it/s]16 03:02:04 Save the image 00018N_flip.png
 54%|█████████████████████▏                 | 852/1568 [02:27<02:03,  5.81it/s]16 03:02:04 Save the image 00019N.png
 54%|█████████████████████▏                 | 853/1568 [02:27<02:02,  5.83it/s]16 03:02:04 Save the image 00019N_flip.png
 54%|█████████████████████▏                 | 854/1568 [02:28<02:03,  5.79it/s]16 03:02:05 Save the image 00020N.png
 55%|█████████████████████▎                 | 855/1568 [02:28<02:03,  5.79it/s]16 03:02:05 Save the image 00020N_flip.png
 55%|█████████████████████▎                 | 856/1568 [02:28<02:02,  5.81it/s]16 03:02:05 Save the image 00021N.png
 55%|█████████████████████▎                 | 857/1568 [02:28<02:02,  5.82it/s]16 03:02:05 Save the image 00021N_flip.png
 55%|█████████████████████▎                 | 858/1568 [02:28<02:02,  5.78it/s]16 03:02:05 Save the image 00022N.png
 55%|█████████████████████▎                 | 859/1568 [02:28<02:02,  5.79it/s]16 03:02:05 Save the image 00022N_flip.png
 55%|█████████████████████▍                 | 860/1568 [02:29<02:02,  5.78it/s]16 03:02:06 Save the image 00023N.png
 55%|█████████████████████▍                 | 861/1568 [02:29<02:02,  5.77it/s]16 03:02:06 Save the image 00023N_flip.png
 55%|█████████████████████▍                 | 862/1568 [02:29<01:59,  5.90it/s]16 03:02:06 Save the image 00024N.png
 55%|█████████████████████▍                 | 863/1568 [02:29<02:00,  5.84it/s]16 03:02:06 Save the image 00024N_flip.png
 55%|█████████████████████▍                 | 864/1568 [02:29<02:01,  5.82it/s]16 03:02:06 Save the image 00025N.png
 55%|█████████████████████▌                 | 865/1568 [02:29<02:01,  5.80it/s]16 03:02:06 Save the image 00025N_flip.png
 55%|█████████████████████▌                 | 866/1568 [02:30<02:01,  5.77it/s]16 03:02:07 Save the image 00026N.png
 55%|█████████████████████▌                 | 867/1568 [02:30<02:01,  5.75it/s]16 03:02:07 Save the image 00026N_flip.png
 55%|█████████████████████▌                 | 868/1568 [02:30<02:02,  5.73it/s]16 03:02:07 Save the image 00027N.png
 55%|█████████████████████▌                 | 869/1568 [02:30<02:02,  5.70it/s]16 03:02:07 Save the image 00027N_flip.png
 55%|█████████████████████▋                 | 870/1568 [02:30<01:56,  5.98it/s]16 03:02:07 Save the image 00028N.png
 56%|█████████████████████▋                 | 871/1568 [02:30<01:58,  5.88it/s]16 03:02:07 Save the image 00028N_flip.png
 56%|█████████████████████▋                 | 872/1568 [02:31<01:58,  5.85it/s]16 03:02:08 Save the image 00029N.png
 56%|█████████████████████▋                 | 873/1568 [02:31<01:59,  5.81it/s]16 03:02:08 Save the image 00029N_flip.png
 56%|█████████████████████▋                 | 874/1568 [02:31<02:01,  5.71it/s]16 03:02:08 Save the image 00030N.png
 56%|█████████████████████▊                 | 875/1568 [02:31<02:00,  5.73it/s]16 03:02:08 Save the image 00030N_flip.png
 56%|█████████████████████▊                 | 876/1568 [02:31<02:00,  5.76it/s]16 03:02:08 Save the image 00031N.png
 56%|█████████████████████▊                 | 877/1568 [02:32<01:58,  5.82it/s]16 03:02:09 Save the image 00031N_flip.png
 56%|█████████████████████▊                 | 878/1568 [02:32<01:55,  5.96it/s]16 03:02:09 Save the image 00032N.png
 56%|█████████████████████▊                 | 879/1568 [02:32<01:57,  5.88it/s]16 03:02:09 Save the image 00032N_flip.png
 56%|█████████████████████▉                 | 880/1568 [02:32<01:57,  5.87it/s]16 03:02:09 Save the image 00033N.png
 56%|█████████████████████▉                 | 881/1568 [02:32<01:58,  5.80it/s]16 03:02:09 Save the image 00033N_flip.png
 56%|█████████████████████▉                 | 882/1568 [02:32<01:59,  5.72it/s]16 03:02:09 Save the image 00034N.png
 56%|█████████████████████▉                 | 883/1568 [02:33<01:59,  5.73it/s]16 03:02:10 Save the image 00034N_flip.png
 56%|█████████████████████▉                 | 884/1568 [02:33<01:59,  5.75it/s]16 03:02:10 Save the image 00035N.png
 56%|██████████████████████                 | 885/1568 [02:33<01:58,  5.74it/s]16 03:02:10 Save the image 00035N_flip.png
 57%|██████████████████████                 | 886/1568 [02:33<01:52,  6.08it/s]16 03:02:10 Save the image 00036N.png
 57%|██████████████████████                 | 887/1568 [02:33<01:54,  5.95it/s]16 03:02:10 Save the image 00036N_flip.png
 57%|██████████████████████                 | 888/1568 [02:33<01:55,  5.87it/s]16 03:02:10 Save the image 00037N.png

 57%|██████████████████████                 | 889/1568 [02:34<01:56,  5.81it/s]16 03:02:11 Save the image 00037N_flip.png
 57%|██████████████████████▏                | 890/1568 [02:34<01:57,  5.76it/s]16 03:02:11 Save the image 00038N.png
 57%|██████████████████████▏                | 891/1568 [02:34<01:59,  5.69it/s]16 03:02:11 Save the image 00038N_flip.png
 57%|██████████████████████▏                | 892/1568 [02:34<01:59,  5.67it/s]16 03:02:11 Save the image 00039N.png
 57%|██████████████████████▏                | 893/1568 [02:34<01:59,  5.67it/s]16 03:02:11 Save the image 00039N_flip.png
 57%|██████████████████████▏                | 894/1568 [02:34<01:52,  6.01it/s]16 03:02:11 Save the image 00040N.png
 57%|██████████████████████▎                | 895/1568 [02:35<01:55,  5.85it/s]16 03:02:12 Save the image 00040N_flip.png
 57%|██████████████████████▎                | 896/1568 [02:35<01:55,  5.81it/s]16 03:02:12 Save the image 00041N.png
 57%|██████████████████████▎                | 897/1568 [02:35<01:56,  5.77it/s]16 03:02:12 Save the image 00041N_flip.png
 57%|██████████████████████▎                | 898/1568 [02:35<01:57,  5.72it/s]16 03:02:12 Save the image 00042N.png
 57%|██████████████████████▎                | 899/1568 [02:35<01:57,  5.70it/s]16 03:02:12 Save the image 00042N_flip.png
 57%|██████████████████████▍                | 900/1568 [02:35<01:57,  5.71it/s]16 03:02:13 Save the image 00043N.png
 57%|██████████████████████▍                | 901/1568 [02:36<01:56,  5.73it/s]16 03:02:13 Save the image 00043N_flip.png
 58%|██████████████████████▍                | 902/1568 [02:36<01:48,  6.11it/s]16 03:02:13 Save the image 00044N.png
 58%|██████████████████████▍                | 903/1568 [02:36<01:51,  5.97it/s]16 03:02:13 Save the image 00044N_flip.png
 58%|██████████████████████▍                | 904/1568 [02:36<01:52,  5.91it/s]16 03:02:13 Save the image 00047N.png
 58%|██████████████████████▌                | 905/1568 [02:36<01:52,  5.87it/s]16 03:02:13 Save the image 00047N_flip.png
 58%|██████████████████████▌                | 906/1568 [02:37<01:54,  5.80it/s]16 03:02:14 Save the image 00048N.png
 58%|██████████████████████▌                | 907/1568 [02:37<01:53,  5.81it/s]16 03:02:14 Save the image 00048N_flip.png
 58%|██████████████████████▌                | 908/1568 [02:37<01:54,  5.74it/s]16 03:02:14 Save the image 00049N.png
 58%|██████████████████████▌                | 909/1568 [02:37<01:55,  5.70it/s]16 03:02:14 Save the image 00049N_flip.png
 58%|██████████████████████▋                | 910/1568 [02:37<01:49,  6.00it/s]16 03:02:14 Save the image 00050N.png
 58%|██████████████████████▋                | 911/1568 [02:37<01:51,  5.89it/s]16 03:02:14 Save the image 00050N_flip.png
 58%|██████████████████████▋                | 912/1568 [02:38<01:52,  5.86it/s]16 03:02:15 Save the image 00051N.png
 58%|██████████████████████▋                | 913/1568 [02:38<01:52,  5.83it/s]16 03:02:15 Save the image 00051N_flip.png
 58%|██████████████████████▋                | 914/1568 [02:38<01:53,  5.77it/s]16 03:02:15 Save the image 00052N.png
 58%|██████████████████████▊                | 915/1568 [02:38<01:52,  5.81it/s]16 03:02:15 Save the image 00052N_flip.png
 58%|██████████████████████▊                | 916/1568 [02:38<01:52,  5.80it/s]16 03:02:15 Save the image 00053N.png
 58%|██████████████████████▊                | 917/1568 [02:38<01:52,  5.80it/s]16 03:02:15 Save the image 00053N_flip.png
 59%|██████████████████████▊                | 918/1568 [02:39<01:45,  6.17it/s]16 03:02:16 Save the image 00054N.png
 59%|██████████████████████▊                | 919/1568 [02:39<01:47,  6.03it/s]16 03:02:16 Save the image 00054N_flip.png
 59%|██████████████████████▉                | 920/1568 [02:39<01:48,  5.98it/s]16 03:02:16 Save the image 00678N.png
 59%|██████████████████████▉                | 921/1568 [02:39<01:49,  5.92it/s]16 03:02:16 Save the image 00678N_flip.png
 59%|██████████████████████▉                | 922/1568 [02:39<01:50,  5.87it/s]16 03:02:16 Save the image 00679N.png
 59%|██████████████████████▉                | 923/1568 [02:39<01:49,  5.88it/s]16 03:02:16 Save the image 00679N_flip.png
 59%|██████████████████████▉                | 924/1568 [02:40<01:49,  5.87it/s]16 03:02:17 Save the image 00680N.png
 59%|███████████████████████                | 925/1568 [02:40<01:50,  5.83it/s]16 03:02:17 Save the image 00680N_flip.png
 59%|███████████████████████                | 926/1568 [02:40<01:44,  6.16it/s]16 03:02:17 Save the image 00681N.png
 59%|███████████████████████                | 927/1568 [02:40<01:46,  6.02it/s]16 03:02:17 Save the image 00681N_flip.png
 59%|███████████████████████                | 928/1568 [02:40<01:47,  5.97it/s]16 03:02:17 Save the image 00682N.png
 59%|███████████████████████                | 929/1568 [02:40<01:48,  5.91it/s]16 03:02:17 Save the image 00682N_flip.png
 59%|███████████████████████▏               | 930/1568 [02:41<01:49,  5.84it/s]16 03:02:18 Save the image 00683N.png
 59%|███████████████████████▏               | 931/1568 [02:41<01:48,  5.86it/s]16 03:02:18 Save the image 00683N_flip.png
 59%|███████████████████████▏               | 932/1568 [02:41<01:49,  5.81it/s]16 03:02:18 Save the image 00684N.png
 60%|███████████████████████▏               | 933/1568 [02:41<01:49,  5.82it/s]16 03:02:18 Save the image 00684N_flip.png
 60%|███████████████████████▏               | 934/1568 [02:41<01:42,  6.20it/s]16 03:02:18 Save the image 00685N.png
 60%|███████████████████████▎               | 935/1568 [02:41<01:44,  6.04it/s]16 03:02:18 Save the image 00685N_flip.png
 60%|███████████████████████▎               | 936/1568 [02:42<01:45,  5.97it/s]16 03:02:19 Save the image 00686N.png
 60%|███████████████████████▎               | 937/1568 [02:42<01:46,  5.93it/s]16 03:02:19 Save the image 00686N_flip.png
 60%|███████████████████████▎               | 938/1568 [02:42<01:47,  5.86it/s]16 03:02:19 Save the image 00687N.png
 60%|███████████████████████▎               | 939/1568 [02:42<01:46,  5.89it/s]16 03:02:19 Save the image 00687N_flip.png
 60%|███████████████████████▍               | 940/1568 [02:42<01:47,  5.86it/s]16 03:02:19 Save the image 00688N.png
 60%|███████████████████████▍               | 941/1568 [02:42<01:47,  5.85it/s]16 03:02:19 Save the image 00688N_flip.png
 60%|███████████████████████▍               | 942/1568 [02:43<01:41,  6.19it/s]16 03:02:20 Save the image 00689N.png
 60%|███████████████████████▍               | 943/1568 [02:43<01:44,  5.96it/s]16 03:02:20 Save the image 00689N_flip.png
 60%|███████████████████████▍               | 944/1568 [02:43<01:45,  5.93it/s]16 03:02:20 Save the image 00690N.png
 60%|███████████████████████▌               | 945/1568 [02:43<01:44,  5.94it/s]16 03:02:20 Save the image 00690N_flip.png
 60%|███████████████████████▌               | 946/1568 [02:43<01:45,  5.88it/s]16 03:02:20 Save the image 00691N.png
 60%|███████████████████████▌               | 947/1568 [02:43<01:45,  5.91it/s]16 03:02:20 Save the image 00691N_flip.png
 60%|███████████████████████▌               | 948/1568 [02:44<01:46,  5.84it/s]16 03:02:21 Save the image 00692N.png
 61%|███████████████████████▌               | 949/1568 [02:44<01:46,  5.82it/s]16 03:02:21 Save the image 00692N_flip.png
 61%|███████████████████████▋               | 950/1568 [02:44<01:40,  6.18it/s]16 03:02:21 Save the image 00693N.png
 61%|███████████████████████▋               | 951/1568 [02:44<01:42,  6.02it/s]16 03:02:21 Save the image 00693N_flip.png
 61%|███████████████████████▋               | 952/1568 [02:44<01:43,  5.97it/s]16 03:02:21 Save the image 00694N.png

 61%|███████████████████████▋               | 953/1568 [02:44<01:44,  5.90it/s]16 03:02:21 Save the image 00694N_flip.png
 61%|███████████████████████▋               | 954/1568 [02:45<01:45,  5.81it/s]16 03:02:22 Save the image 00695N.png
 61%|███████████████████████▊               | 955/1568 [02:45<01:44,  5.86it/s]16 03:02:22 Save the image 00695N_flip.png
 61%|███████████████████████▊               | 956/1568 [02:45<01:44,  5.83it/s]16 03:02:22 Save the image 00696N.png
 61%|███████████████████████▊               | 957/1568 [02:45<01:44,  5.83it/s]16 03:02:22 Save the image 00696N_flip.png
 61%|███████████████████████▊               | 958/1568 [02:45<01:38,  6.22it/s]16 03:02:22 Save the image 00697N.png
 61%|███████████████████████▊               | 959/1568 [02:45<01:40,  6.06it/s]16 03:02:22 Save the image 00697N_flip.png
 61%|███████████████████████▉               | 960/1568 [02:46<01:41,  5.99it/s]16 03:02:23 Save the image 00698N.png
 61%|███████████████████████▉               | 961/1568 [02:46<01:42,  5.95it/s]16 03:02:23 Save the image 00698N_flip.png
 61%|███████████████████████▉               | 962/1568 [02:46<01:43,  5.87it/s]16 03:02:23 Save the image 00699N.png
 61%|███████████████████████▉               | 963/1568 [02:46<01:42,  5.88it/s]16 03:02:23 Save the image 00699N_flip.png
 61%|███████████████████████▉               | 964/1568 [02:46<01:43,  5.82it/s]16 03:02:23 Save the image 00700N.png
 62%|████████████████████████               | 965/1568 [02:46<01:43,  5.81it/s]16 03:02:23 Save the image 00700N_flip.png
 62%|████████████████████████               | 966/1568 [02:47<01:38,  6.11it/s]16 03:02:24 Save the image 00701N.png
 62%|████████████████████████               | 967/1568 [02:47<01:40,  5.97it/s]16 03:02:24 Save the image 00701N_flip.png
 62%|████████████████████████               | 968/1568 [02:47<01:41,  5.93it/s]16 03:02:24 Save the image 00702N.png
 62%|████████████████████████               | 969/1568 [02:47<01:41,  5.90it/s]16 03:02:24 Save the image 00702N_flip.png
 62%|████████████████████████▏              | 970/1568 [02:47<01:42,  5.83it/s]16 03:02:24 Save the image 00703N.png
 62%|████████████████████████▏              | 971/1568 [02:47<01:41,  5.85it/s]16 03:02:25 Save the image 00703N_flip.png
 62%|████████████████████████▏              | 972/1568 [02:48<01:42,  5.80it/s]16 03:02:25 Save the image 00704N.png
 62%|████████████████████████▏              | 973/1568 [02:48<01:42,  5.79it/s]16 03:02:25 Save the image 00704N_flip.png
 62%|████████████████████████▏              | 974/1568 [02:48<01:42,  5.79it/s]16 03:02:25 Save the image 00705N.png
 62%|████████████████████████▎              | 975/1568 [02:48<01:42,  5.76it/s]16 03:02:25 Save the image 00705N_flip.png
 62%|████████████████████████▎              | 976/1568 [02:48<01:41,  5.82it/s]16 03:02:25 Save the image 00706N.png
 62%|████████████████████████▎              | 977/1568 [02:49<01:41,  5.81it/s]16 03:02:26 Save the image 00706N_flip.png
 62%|████████████████████████▎              | 978/1568 [02:49<01:41,  5.80it/s]16 03:02:26 Save the image 00707N.png
 62%|████████████████████████▎              | 979/1568 [02:49<01:41,  5.83it/s]16 03:02:26 Save the image 00707N_flip.png
 62%|████████████████████████▍              | 980/1568 [02:49<01:40,  5.87it/s]16 03:02:26 Save the image 00708N.png
 63%|████████████████████████▍              | 981/1568 [02:49<01:41,  5.80it/s]16 03:02:26 Save the image 00708N_flip.png
 63%|████████████████████████▍              | 982/1568 [02:49<01:41,  5.76it/s]16 03:02:26 Save the image 00709N.png
 63%|████████████████████████▍              | 983/1568 [02:50<01:42,  5.70it/s]16 03:02:27 Save the image 00709N_flip.png
 63%|████████████████████████▍              | 984/1568 [02:50<01:42,  5.71it/s]16 03:02:27 Save the image 00710N.png
 63%|████████████████████████▍              | 985/1568 [02:50<01:43,  5.66it/s]16 03:02:27 Save the image 00710N_flip.png
 63%|████████████████████████▌              | 986/1568 [02:50<01:42,  5.67it/s]16 03:02:27 Save the image 00711N.png
 63%|████████████████████████▌              | 987/1568 [02:50<01:42,  5.66it/s]16 03:02:27 Save the image 00711N_flip.png
 63%|████████████████████████▌              | 988/1568 [02:50<01:40,  5.75it/s]16 03:02:27 Save the image 00712N.png
 63%|████████████████████████▌              | 989/1568 [02:51<01:39,  5.84it/s]16 03:02:28 Save the image 00712N_flip.png
 63%|████████████████████████▌              | 990/1568 [02:51<01:39,  5.82it/s]16 03:02:28 Save the image 00713N.png
 63%|████████████████████████▋              | 991/1568 [02:51<01:39,  5.82it/s]16 03:02:28 Save the image 00713N_flip.png
 63%|████████████████████████▋              | 992/1568 [02:51<01:38,  5.82it/s]16 03:02:28 Save the image 00714N.png
 63%|████████████████████████▋              | 993/1568 [02:51<01:39,  5.77it/s]16 03:02:28 Save the image 00714N_flip.png
 63%|████████████████████████▋              | 994/1568 [02:51<01:39,  5.74it/s]16 03:02:28 Save the image 00715N.png
 63%|████████████████████████▋              | 995/1568 [02:52<01:39,  5.76it/s]16 03:02:29 Save the image 00715N_flip.png
 64%|████████████████████████▊              | 996/1568 [02:52<01:38,  5.78it/s]16 03:02:29 Save the image 00716N.png
 64%|████████████████████████▊              | 997/1568 [02:52<01:32,  6.16it/s]16 03:02:29 Save the image 00716N_flip.png
 64%|████████████████████████▊              | 998/1568 [02:52<01:34,  6.02it/s]16 03:02:29 Save the image 00717N.png
 64%|████████████████████████▊              | 999/1568 [02:52<01:35,  5.98it/s]16 03:02:29 Save the image 00717N_flip.png
 64%|████████████████████████▏             | 1000/1568 [02:52<01:35,  5.95it/s]16 03:02:29 Save the image 00718N.png
 64%|████████████████████████▎             | 1001/1568 [02:53<01:36,  5.89it/s]16 03:02:30 Save the image 00718N_flip.png
 64%|████████████████████████▎             | 1002/1568 [02:53<01:36,  5.85it/s]16 03:02:30 Save the image 00719N.png
 64%|████████████████████████▎             | 1003/1568 [02:53<01:36,  5.84it/s]16 03:02:30 Save the image 00719N_flip.png
 64%|████████████████████████▎             | 1004/1568 [02:53<01:36,  5.81it/s]16 03:02:30 Save the image 00720N.png
 64%|████████████████████████▎             | 1005/1568 [02:53<01:30,  6.19it/s]16 03:02:30 Save the image 00720N_flip.png
 64%|████████████████████████▍             | 1006/1568 [02:53<01:32,  6.05it/s]16 03:02:30 Save the image 00721N.png
 64%|████████████████████████▍             | 1007/1568 [02:54<01:33,  5.98it/s]16 03:02:31 Save the image 00721N_flip.png
 64%|████████████████████████▍             | 1008/1568 [02:54<01:34,  5.92it/s]16 03:02:31 Save the image 00722N.png
 64%|████████████████████████▍             | 1009/1568 [02:54<01:36,  5.80it/s]16 03:02:31 Save the image 00722N_flip.png
 64%|████████████████████████▍             | 1010/1568 [02:54<01:36,  5.76it/s]16 03:02:31 Save the image 00723N.png
 64%|████████████████████████▌             | 1011/1568 [02:54<01:36,  5.78it/s]16 03:02:31 Save the image 00723N_flip.png
 65%|████████████████████████▌             | 1012/1568 [02:55<01:36,  5.74it/s]16 03:02:32 Save the image 00724N.png
 65%|████████████████████████▌             | 1013/1568 [02:55<01:31,  6.07it/s]16 03:02:32 Save the image 00724N_flip.png
 65%|████████████████████████▌             | 1014/1568 [02:55<01:32,  5.96it/s]16 03:02:32 Save the image 00725N.png
 65%|████████████████████████▌             | 1015/1568 [02:55<01:33,  5.92it/s]16 03:02:32 Save the image 00725N_flip.png
 65%|████████████████████████▌             | 1016/1568 [02:55<01:33,  5.87it/s]16 03:02:32 Save the image 00726N.png

 65%|████████████████████████▋             | 1017/1568 [02:55<01:34,  5.80it/s]16 03:02:32 Save the image 00726N_flip.png
 65%|████████████████████████▋             | 1018/1568 [02:56<01:35,  5.77it/s]16 03:02:33 Save the image 00727N.png
 65%|████████████████████████▋             | 1019/1568 [02:56<01:35,  5.74it/s]16 03:02:33 Save the image 00727N_flip.png
 65%|████████████████████████▋             | 1020/1568 [02:56<01:35,  5.72it/s]16 03:02:33 Save the image 00728N.png
 65%|████████████████████████▋             | 1021/1568 [02:56<01:30,  6.07it/s]16 03:02:33 Save the image 00728N_flip.png
 65%|████████████████████████▊             | 1022/1568 [02:56<01:31,  5.94it/s]16 03:02:33 Save the image 00729N.png
 65%|████████████████████████▊             | 1023/1568 [02:56<01:32,  5.87it/s]16 03:02:33 Save the image 00729N_flip.png
 65%|████████████████████████▊             | 1024/1568 [02:57<01:33,  5.82it/s]16 03:02:34 Save the image 00730N.png
 65%|████████████████████████▊             | 1025/1568 [02:57<01:33,  5.78it/s]16 03:02:34 Save the image 00730N_flip.png
 65%|████████████████████████▊             | 1026/1568 [02:57<01:34,  5.71it/s]16 03:02:34 Save the image 00731N.png
 65%|████████████████████████▉             | 1027/1568 [02:57<01:34,  5.73it/s]16 03:02:34 Save the image 00731N_flip.png
 66%|████████████████████████▉             | 1028/1568 [02:57<01:33,  5.77it/s]16 03:02:34 Save the image 00732N.png
 66%|████████████████████████▉             | 1029/1568 [02:57<01:30,  5.98it/s]16 03:02:34 Save the image 00732N_flip.png
 66%|████████████████████████▉             | 1030/1568 [02:58<01:31,  5.86it/s]16 03:02:35 Save the image 00733N.png
 66%|████████████████████████▉             | 1031/1568 [02:58<01:32,  5.82it/s]16 03:02:35 Save the image 00733N_flip.png
 66%|█████████████████████████             | 1032/1568 [02:58<01:31,  5.83it/s]16 03:02:35 Save the image 00734N.png
 66%|█████████████████████████             | 1033/1568 [02:58<01:32,  5.75it/s]16 03:02:35 Save the image 00734N_flip.png
 66%|█████████████████████████             | 1034/1568 [02:58<01:33,  5.73it/s]16 03:02:35 Save the image 00735N.png
 66%|█████████████████████████             | 1035/1568 [02:58<01:33,  5.72it/s]16 03:02:35 Save the image 00735N_flip.png
 66%|█████████████████████████             | 1036/1568 [02:59<01:32,  5.78it/s]16 03:02:36 Save the image 00736N.png
 66%|█████████████████████████▏            | 1037/1568 [02:59<01:29,  5.91it/s]16 03:02:36 Save the image 00736N_flip.png
 66%|█████████████████████████▏            | 1038/1568 [02:59<01:30,  5.83it/s]16 03:02:36 Save the image 00737N.png
 66%|█████████████████████████▏            | 1039/1568 [02:59<01:30,  5.82it/s]16 03:02:36 Save the image 00737N_flip.png
 66%|█████████████████████████▏            | 1040/1568 [02:59<01:31,  5.77it/s]16 03:02:36 Save the image 00738N.png
 66%|█████████████████████████▏            | 1041/1568 [03:00<01:32,  5.70it/s]16 03:02:37 Save the image 00738N_flip.png
 66%|█████████████████████████▎            | 1042/1568 [03:00<01:32,  5.70it/s]16 03:02:37 Save the image 00739N.png
 67%|█████████████████████████▎            | 1043/1568 [03:00<01:32,  5.66it/s]16 03:02:37 Save the image 00739N_flip.png
 67%|█████████████████████████▎            | 1044/1568 [03:00<01:32,  5.65it/s]16 03:02:37 Save the image 00740N.png
 67%|█████████████████████████▎            | 1045/1568 [03:00<01:28,  5.88it/s]16 03:02:37 Save the image 00740N_flip.png
 67%|█████████████████████████▎            | 1046/1568 [03:00<01:30,  5.78it/s]16 03:02:37 Save the image 00741N.png
 67%|█████████████████████████▎            | 1047/1568 [03:01<01:30,  5.77it/s]16 03:02:38 Save the image 00741N_flip.png
 67%|█████████████████████████▍            | 1048/1568 [03:01<01:30,  5.76it/s]16 03:02:38 Save the image 00742N.png
 67%|█████████████████████████▍            | 1049/1568 [03:01<01:30,  5.73it/s]16 03:02:38 Save the image 00742N_flip.png
 67%|█████████████████████████▍            | 1050/1568 [03:01<01:30,  5.71it/s]16 03:02:38 Save the image 00743N.png
 67%|█████████████████████████▍            | 1051/1568 [03:01<01:29,  5.75it/s]16 03:02:38 Save the image 00743N_flip.png
 67%|█████████████████████████▍            | 1052/1568 [03:01<01:29,  5.76it/s]16 03:02:38 Save the image 00744N.png
 67%|█████████████████████████▌            | 1053/1568 [03:02<01:24,  6.11it/s]16 03:02:39 Save the image 00744N_flip.png
 67%|█████████████████████████▌            | 1054/1568 [03:02<01:26,  5.97it/s]16 03:02:39 Save the image 00745N.png
 67%|█████████████████████████▌            | 1055/1568 [03:02<01:26,  5.92it/s]16 03:02:39 Save the image 00745N_flip.png
 67%|█████████████████████████▌            | 1056/1568 [03:02<01:27,  5.88it/s]16 03:02:39 Save the image 00746N.png
 67%|█████████████████████████▌            | 1057/1568 [03:02<01:28,  5.81it/s]16 03:02:39 Save the image 00746N_flip.png
 67%|█████████████████████████▋            | 1058/1568 [03:02<01:28,  5.76it/s]16 03:02:39 Save the image 00747N.png
 68%|█████████████████████████▋            | 1059/1568 [03:03<01:28,  5.76it/s]16 03:02:40 Save the image 00747N_flip.png
 68%|█████████████████████████▋            | 1060/1568 [03:03<01:28,  5.74it/s]16 03:02:40 Save the image 00748N.png
 68%|█████████████████████████▋            | 1061/1568 [03:03<01:23,  6.06it/s]16 03:02:40 Save the image 00748N_flip.png
 68%|█████████████████████████▋            | 1062/1568 [03:03<01:25,  5.93it/s]16 03:02:40 Save the image 00749N.png
 68%|█████████████████████████▊            | 1063/1568 [03:03<01:25,  5.87it/s]16 03:02:40 Save the image 00749N_flip.png
 68%|█████████████████████████▊            | 1064/1568 [03:03<01:25,  5.87it/s]16 03:02:40 Save the image 00750N.png
 68%|█████████████████████████▊            | 1065/1568 [03:04<01:26,  5.81it/s]16 03:02:41 Save the image 00750N_flip.png
 68%|█████████████████████████▊            | 1066/1568 [03:04<01:26,  5.84it/s]16 03:02:41 Save the image 00751N.png
 68%|█████████████████████████▊            | 1067/1568 [03:04<01:26,  5.80it/s]16 03:02:41 Save the image 00751N_flip.png
 68%|█████████████████████████▉            | 1068/1568 [03:04<01:26,  5.79it/s]16 03:02:41 Save the image 00752N.png
 68%|█████████████████████████▉            | 1069/1568 [03:04<01:21,  6.13it/s]16 03:02:41 Save the image 00752N_flip.png
 68%|█████████████████████████▉            | 1070/1568 [03:04<01:23,  5.97it/s]16 03:02:41 Save the image 00753N.png
 68%|█████████████████████████▉            | 1071/1568 [03:05<01:23,  5.92it/s]16 03:02:42 Save the image 00753N_flip.png
 68%|█████████████████████████▉            | 1072/1568 [03:05<01:24,  5.87it/s]16 03:02:42 Save the image 00754N.png
 68%|██████████████████████████            | 1073/1568 [03:05<01:25,  5.80it/s]16 03:02:42 Save the image 00754N_flip.png
 68%|██████████████████████████            | 1074/1568 [03:05<01:24,  5.84it/s]16 03:02:42 Save the image 00755N.png
 69%|██████████████████████████            | 1075/1568 [03:05<01:25,  5.79it/s]16 03:02:42 Save the image 00755N_flip.png
 69%|██████████████████████████            | 1076/1568 [03:06<01:25,  5.77it/s]16 03:02:43 Save the image 00756N.png
 69%|██████████████████████████            | 1077/1568 [03:06<01:24,  5.79it/s]16 03:02:43 Save the image 00756N_flip.png
 69%|██████████████████████████▏           | 1078/1568 [03:06<01:24,  5.77it/s]16 03:02:43 Save the image 00757N.png
 69%|██████████████████████████▏           | 1079/1568 [03:06<01:24,  5.78it/s]16 03:02:43 Save the image 00757N_flip.png
 69%|██████████████████████████▏           | 1080/1568 [03:06<01:24,  5.75it/s]16 03:02:43 Save the image 00758N.png

 69%|██████████████████████████▏           | 1081/1568 [03:06<01:24,  5.74it/s]16 03:02:43 Save the image 00758N_flip.png
 69%|██████████████████████████▏           | 1082/1568 [03:07<01:24,  5.78it/s]16 03:02:44 Save the image 00759N.png
 69%|██████████████████████████▏           | 1083/1568 [03:07<01:23,  5.82it/s]16 03:02:44 Save the image 00759N_flip.png
 69%|██████████████████████████▎           | 1084/1568 [03:07<01:23,  5.77it/s]16 03:02:44 Save the image 00760N.png
 69%|██████████████████████████▎           | 1085/1568 [03:07<01:24,  5.74it/s]16 03:02:44 Save the image 00760N_flip.png
 69%|██████████████████████████▎           | 1086/1568 [03:07<01:23,  5.75it/s]16 03:02:44 Save the image 00761N.png
 69%|██████████████████████████▎           | 1087/1568 [03:07<01:23,  5.73it/s]16 03:02:44 Save the image 00761N_flip.png
 69%|██████████████████████████▎           | 1088/1568 [03:08<01:24,  5.69it/s]16 03:02:45 Save the image 00762N.png
 69%|██████████████████████████▍           | 1089/1568 [03:08<01:24,  5.68it/s]16 03:02:45 Save the image 00762N_flip.png
 70%|██████████████████████████▍           | 1090/1568 [03:08<01:23,  5.72it/s]16 03:02:45 Save the image 00763N.png
 70%|██████████████████████████▍           | 1091/1568 [03:08<01:23,  5.72it/s]16 03:02:45 Save the image 00763N_flip.png
 70%|██████████████████████████▍           | 1092/1568 [03:08<01:18,  6.04it/s]16 03:02:45 Save the image 00764N.png
 70%|██████████████████████████▍           | 1093/1568 [03:08<01:20,  5.91it/s]16 03:02:45 Save the image 00764N_flip.png
 70%|██████████████████████████▌           | 1094/1568 [03:09<01:20,  5.86it/s]16 03:02:46 Save the image 00765N.png
 70%|██████████████████████████▌           | 1095/1568 [03:09<01:20,  5.88it/s]16 03:02:46 Save the image 00765N_flip.png
 70%|██████████████████████████▌           | 1096/1568 [03:09<01:21,  5.80it/s]16 03:02:46 Save the image 00766N.png
 70%|██████████████████████████▌           | 1097/1568 [03:09<01:21,  5.76it/s]16 03:02:46 Save the image 00766N_flip.png
 70%|██████████████████████████▌           | 1098/1568 [03:09<01:22,  5.73it/s]16 03:02:46 Save the image 00767N.png
 70%|██████████████████████████▋           | 1099/1568 [03:09<01:21,  5.72it/s]16 03:02:46 Save the image 00767N_flip.png
 70%|██████████████████████████▋           | 1100/1568 [03:10<01:17,  6.06it/s]16 03:02:47 Save the image 00768N.png
 70%|██████████████████████████▋           | 1101/1568 [03:10<01:18,  5.93it/s]16 03:02:47 Save the image 00768N_flip.png
 70%|██████████████████████████▋           | 1102/1568 [03:10<01:19,  5.89it/s]16 03:02:47 Save the image 00769N.png
 70%|██████████████████████████▋           | 1103/1568 [03:10<01:18,  5.89it/s]16 03:02:47 Save the image 00769N_flip.png
 70%|██████████████████████████▊           | 1104/1568 [03:10<01:19,  5.82it/s]16 03:02:47 Save the image 00770N.png
 70%|██████████████████████████▊           | 1105/1568 [03:11<01:19,  5.83it/s]16 03:02:48 Save the image 00770N_flip.png
 71%|██████████████████████████▊           | 1106/1568 [03:11<01:19,  5.78it/s]16 03:02:48 Save the image 00771N.png
 71%|██████████████████████████▊           | 1107/1568 [03:11<01:19,  5.79it/s]16 03:02:48 Save the image 00771N_flip.png
 71%|██████████████████████████▊           | 1108/1568 [03:11<01:14,  6.15it/s]16 03:02:48 Save the image 00772N.png
 71%|██████████████████████████▉           | 1109/1568 [03:11<01:16,  6.02it/s]16 03:02:48 Save the image 00772N_flip.png
 71%|██████████████████████████▉           | 1110/1568 [03:11<01:16,  5.95it/s]16 03:02:48 Save the image 00773N.png
 71%|██████████████████████████▉           | 1111/1568 [03:12<01:16,  5.95it/s]16 03:02:49 Save the image 00773N_flip.png
 71%|██████████████████████████▉           | 1112/1568 [03:12<01:17,  5.86it/s]16 03:02:49 Save the image 00774N.png
 71%|██████████████████████████▉           | 1113/1568 [03:12<01:17,  5.85it/s]16 03:02:49 Save the image 00774N_flip.png
 71%|██████████████████████████▉           | 1114/1568 [03:12<01:17,  5.84it/s]16 03:02:49 Save the image 00775N.png
 71%|███████████████████████████           | 1115/1568 [03:12<01:17,  5.83it/s]16 03:02:49 Save the image 00775N_flip.png
 71%|███████████████████████████           | 1116/1568 [03:12<01:13,  6.19it/s]16 03:02:49 Save the image 00776N.png
 71%|███████████████████████████           | 1117/1568 [03:13<01:14,  6.02it/s]16 03:02:50 Save the image 00776N_flip.png
 71%|███████████████████████████           | 1118/1568 [03:13<01:15,  5.97it/s]16 03:02:50 Save the image 00777N.png
 71%|███████████████████████████           | 1119/1568 [03:13<01:15,  5.93it/s]16 03:02:50 Save the image 00777N_flip.png
 71%|███████████████████████████▏          | 1120/1568 [03:13<01:16,  5.87it/s]16 03:02:50 Save the image 00778N.png
 71%|███████████████████████████▏          | 1121/1568 [03:13<01:17,  5.75it/s]16 03:02:50 Save the image 00778N_flip.png
 72%|███████████████████████████▏          | 1122/1568 [03:13<01:17,  5.73it/s]16 03:02:50 Save the image 00779N.png
 72%|███████████████████████████▏          | 1123/1568 [03:14<01:17,  5.76it/s]16 03:02:51 Save the image 00779N_flip.png
 72%|███████████████████████████▏          | 1124/1568 [03:14<01:13,  6.08it/s]16 03:02:51 Save the image 00780N.png
 72%|███████████████████████████▎          | 1125/1568 [03:14<01:14,  5.95it/s]16 03:02:51 Save the image 00780N_flip.png
 72%|███████████████████████████▎          | 1126/1568 [03:14<01:14,  5.91it/s]16 03:02:51 Save the image 00781N.png
 72%|███████████████████████████▎          | 1127/1568 [03:14<01:14,  5.88it/s]16 03:02:51 Save the image 00781N_flip.png
 72%|███████████████████████████▎          | 1128/1568 [03:14<01:15,  5.82it/s]16 03:02:51 Save the image 00782N.png
 72%|███████████████████████████▎          | 1129/1568 [03:15<01:15,  5.84it/s]16 03:02:52 Save the image 00782N_flip.png
 72%|███████████████████████████▍          | 1130/1568 [03:15<01:15,  5.78it/s]16 03:02:52 Save the image 00783N.png
 72%|███████████████████████████▍          | 1131/1568 [03:15<01:15,  5.79it/s]16 03:02:52 Save the image 00783N_flip.png
 72%|███████████████████████████▍          | 1132/1568 [03:15<01:15,  5.79it/s]16 03:02:52 Save the image 00784N.png
 72%|███████████████████████████▍          | 1133/1568 [03:15<01:15,  5.78it/s]16 03:02:52 Save the image 00784N_flip.png
 72%|███████████████████████████▍          | 1134/1568 [03:15<01:15,  5.78it/s]16 03:02:52 Save the image 00785N.png
 72%|███████████████████████████▌          | 1135/1568 [03:16<01:14,  5.79it/s]16 03:02:53 Save the image 00785N_flip.png
 72%|███████████████████████████▌          | 1136/1568 [03:16<01:14,  5.80it/s]16 03:02:53 Save the image 00786N.png
 73%|███████████████████████████▌          | 1137/1568 [03:16<01:13,  5.86it/s]16 03:02:53 Save the image 00786N_flip.png
 73%|███████████████████████████▌          | 1138/1568 [03:16<01:13,  5.88it/s]16 03:02:53 Save the image 00787N.png
 73%|███████████████████████████▌          | 1139/1568 [03:16<01:13,  5.83it/s]16 03:02:53 Save the image 00787N_flip.png
 73%|███████████████████████████▋          | 1140/1568 [03:16<01:13,  5.79it/s]16 03:02:53 Save the image 00788N.png
 73%|███████████████████████████▋          | 1141/1568 [03:17<01:13,  5.80it/s]16 03:02:54 Save the image 00788N_flip.png
 73%|███████████████████████████▋          | 1142/1568 [03:17<01:13,  5.81it/s]16 03:02:54 Save the image 00789N.png
 73%|███████████████████████████▋          | 1143/1568 [03:17<01:13,  5.80it/s]16 03:02:54 Save the image 00789N_flip.png
 73%|███████████████████████████▋          | 1144/1568 [03:17<01:13,  5.80it/s]16 03:02:54 Save the image 00790N.png

 73%|███████████████████████████▋          | 1145/1568 [03:17<01:12,  5.87it/s]16 03:02:54 Save the image 00790N_flip.png
 73%|███████████████████████████▊          | 1146/1568 [03:17<01:11,  5.91it/s]16 03:02:54 Save the image 00791N.png
 73%|███████████████████████████▊          | 1147/1568 [03:18<01:11,  5.85it/s]16 03:02:55 Save the image 00791N_flip.png
 73%|███████████████████████████▊          | 1148/1568 [03:18<01:12,  5.82it/s]16 03:02:55 Save the image 00792N.png
 73%|███████████████████████████▊          | 1149/1568 [03:18<01:11,  5.82it/s]16 03:02:55 Save the image 00792N_flip.png
 73%|███████████████████████████▊          | 1150/1568 [03:18<01:11,  5.83it/s]16 03:02:55 Save the image 00793N.png
 73%|███████████████████████████▉          | 1151/1568 [03:18<01:12,  5.78it/s]16 03:02:55 Save the image 00793N_flip.png
 73%|███████████████████████████▉          | 1152/1568 [03:19<01:11,  5.79it/s]16 03:02:56 Save the image 00794N.png
 74%|███████████████████████████▉          | 1153/1568 [03:19<01:12,  5.76it/s]16 03:02:56 Save the image 00794N_flip.png
 74%|███████████████████████████▉          | 1154/1568 [03:19<01:11,  5.83it/s]16 03:02:56 Save the image 00795N.png
 74%|███████████████████████████▉          | 1155/1568 [03:19<01:09,  5.94it/s]16 03:02:56 Save the image 00795N_flip.png
 74%|████████████████████████████          | 1156/1568 [03:19<01:10,  5.87it/s]16 03:02:56 Save the image 00796N.png
 74%|████████████████████████████          | 1157/1568 [03:19<01:09,  5.87it/s]16 03:02:56 Save the image 00796N_flip.png
 74%|████████████████████████████          | 1158/1568 [03:20<01:10,  5.85it/s]16 03:02:57 Save the image 00797N.png
 74%|████████████████████████████          | 1159/1568 [03:20<01:10,  5.83it/s]16 03:02:57 Save the image 00797N_flip.png
 74%|████████████████████████████          | 1160/1568 [03:20<01:10,  5.80it/s]16 03:02:57 Save the image 00798N.png
 74%|████████████████████████████▏         | 1161/1568 [03:20<01:10,  5.79it/s]16 03:02:57 Save the image 00798N_flip.png
 74%|████████████████████████████▏         | 1162/1568 [03:20<01:10,  5.76it/s]16 03:02:57 Save the image 00799N.png
 74%|████████████████████████████▏         | 1163/1568 [03:20<01:07,  6.04it/s]16 03:02:57 Save the image 00799N_flip.png
 74%|████████████████████████████▏         | 1164/1568 [03:21<01:08,  5.88it/s]16 03:02:58 Save the image 00800N.png
 74%|████████████████████████████▏         | 1165/1568 [03:21<01:08,  5.88it/s]16 03:02:58 Save the image 00800N_flip.png
 74%|████████████████████████████▎         | 1166/1568 [03:21<01:08,  5.89it/s]16 03:02:58 Save the image 00801N.png
 74%|████████████████████████████▎         | 1167/1568 [03:21<01:08,  5.82it/s]16 03:02:58 Save the image 00801N_flip.png
 74%|████████████████████████████▎         | 1168/1568 [03:21<01:09,  5.79it/s]16 03:02:58 Save the image 00802N.png
 75%|████████████████████████████▎         | 1169/1568 [03:21<01:08,  5.79it/s]16 03:02:58 Save the image 00802N_flip.png
 75%|████████████████████████████▎         | 1170/1568 [03:22<01:08,  5.80it/s]16 03:02:59 Save the image 00803N.png
 75%|████████████████████████████▍         | 1171/1568 [03:22<01:04,  6.14it/s]16 03:02:59 Save the image 00803N_flip.png
 75%|████████████████████████████▍         | 1172/1568 [03:22<01:05,  6.01it/s]16 03:02:59 Save the image 00804N.png
 75%|████████████████████████████▍         | 1173/1568 [03:22<01:06,  5.96it/s]16 03:02:59 Save the image 00804N_flip.png
 75%|████████████████████████████▍         | 1174/1568 [03:22<01:06,  5.92it/s]16 03:02:59 Save the image 00805N.png
 75%|████████████████████████████▍         | 1175/1568 [03:22<01:07,  5.85it/s]16 03:02:59 Save the image 00805N_flip.png
 75%|████████████████████████████▌         | 1176/1568 [03:23<01:07,  5.81it/s]16 03:03:00 Save the image 00806N.png
 75%|████████████████████████████▌         | 1177/1568 [03:23<01:07,  5.80it/s]16 03:03:00 Save the image 00806N_flip.png
 75%|████████████████████████████▌         | 1178/1568 [03:23<01:07,  5.78it/s]16 03:03:00 Save the image 00807N.png
 75%|████████████████████████████▌         | 1179/1568 [03:23<01:03,  6.13it/s]16 03:03:00 Save the image 00807N_flip.png
 75%|████████████████████████████▌         | 1180/1568 [03:23<01:04,  5.99it/s]16 03:03:00 Save the image 00808N.png
 75%|████████████████████████████▌         | 1181/1568 [03:23<01:05,  5.95it/s]16 03:03:00 Save the image 00808N_flip.png
 75%|████████████████████████████▋         | 1182/1568 [03:24<01:04,  5.95it/s]16 03:03:01 Save the image 00809N.png
 75%|████████████████████████████▋         | 1183/1568 [03:24<01:05,  5.87it/s]16 03:03:01 Save the image 00809N_flip.png
 76%|████████████████████████████▋         | 1184/1568 [03:24<01:05,  5.83it/s]16 03:03:01 Save the image 00810N.png
 76%|████████████████████████████▋         | 1185/1568 [03:24<01:05,  5.83it/s]16 03:03:01 Save the image 00810N_flip.png
 76%|████████████████████████████▋         | 1186/1568 [03:24<01:05,  5.82it/s]16 03:03:01 Save the image 00811N.png
 76%|████████████████████████████▊         | 1187/1568 [03:24<01:02,  6.13it/s]16 03:03:01 Save the image 00811N_flip.png
 76%|████████████████████████████▊         | 1188/1568 [03:25<01:03,  5.97it/s]16 03:03:02 Save the image 00812N.png
 76%|████████████████████████████▊         | 1189/1568 [03:25<01:04,  5.91it/s]16 03:03:02 Save the image 00812N_flip.png
 76%|████████████████████████████▊         | 1190/1568 [03:25<01:03,  5.92it/s]16 03:03:02 Save the image 00813N.png
 76%|████████████████████████████▊         | 1191/1568 [03:25<01:04,  5.85it/s]16 03:03:02 Save the image 00813N_flip.png
 76%|████████████████████████████▉         | 1192/1568 [03:25<01:04,  5.80it/s]16 03:03:02 Save the image 00814N.png
 76%|████████████████████████████▉         | 1193/1568 [03:26<01:05,  5.74it/s]16 03:03:03 Save the image 00814N_flip.png
 76%|████████████████████████████▉         | 1194/1568 [03:26<01:05,  5.73it/s]16 03:03:03 Save the image 00815N.png
 76%|████████████████████████████▉         | 1195/1568 [03:26<01:01,  6.10it/s]16 03:03:03 Save the image 00815N_flip.png
 76%|████████████████████████████▉         | 1196/1568 [03:26<01:02,  5.98it/s]16 03:03:03 Save the image 00816N.png
 76%|█████████████████████████████         | 1197/1568 [03:26<01:02,  5.92it/s]16 03:03:03 Save the image 00816N_flip.png
 76%|█████████████████████████████         | 1198/1568 [03:26<01:02,  5.89it/s]16 03:03:03 Save the image 00817N.png
 76%|█████████████████████████████         | 1199/1568 [03:27<01:03,  5.82it/s]16 03:03:04 Save the image 00817N_flip.png
 77%|█████████████████████████████         | 1200/1568 [03:27<01:03,  5.84it/s]16 03:03:04 Save the image 00818N.png
 77%|█████████████████████████████         | 1201/1568 [03:27<01:02,  5.83it/s]16 03:03:04 Save the image 00818N_flip.png
 77%|█████████████████████████████▏        | 1202/1568 [03:27<01:02,  5.82it/s]16 03:03:04 Save the image 00819N.png
 77%|█████████████████████████████▏        | 1203/1568 [03:27<00:59,  6.15it/s]16 03:03:04 Save the image 00819N_flip.png
 77%|█████████████████████████████▏        | 1204/1568 [03:27<01:00,  5.99it/s]16 03:03:04 Save the image 00820N.png
 77%|█████████████████████████████▏        | 1205/1568 [03:28<01:01,  5.93it/s]16 03:03:05 Save the image 00820N_flip.png
 77%|█████████████████████████████▏        | 1206/1568 [03:28<01:01,  5.89it/s]16 03:03:05 Save the image 00821N.png
 77%|█████████████████████████████▎        | 1207/1568 [03:28<01:02,  5.81it/s]16 03:03:05 Save the image 00821N_flip.png
 77%|█████████████████████████████▎        | 1208/1568 [03:28<01:01,  5.85it/s]16 03:03:05 Save the image 00822N.png

 77%|█████████████████████████████▎        | 1209/1568 [03:28<01:02,  5.79it/s]16 03:03:05 Save the image 00822N_flip.png
 77%|█████████████████████████████▎        | 1210/1568 [03:28<01:01,  5.78it/s]16 03:03:05 Save the image 00823N.png
 77%|█████████████████████████████▎        | 1211/1568 [03:29<00:59,  5.97it/s]16 03:03:06 Save the image 00823N_flip.png
 77%|█████████████████████████████▎        | 1212/1568 [03:29<01:00,  5.87it/s]16 03:03:06 Save the image 00824N.png
 77%|█████████████████████████████▍        | 1213/1568 [03:29<01:00,  5.83it/s]16 03:03:06 Save the image 00824N_flip.png
 77%|█████████████████████████████▍        | 1214/1568 [03:29<01:01,  5.78it/s]16 03:03:06 Save the image 00825N.png
 77%|█████████████████████████████▍        | 1215/1568 [03:29<01:01,  5.75it/s]16 03:03:06 Save the image 00825N_flip.png
 78%|█████████████████████████████▍        | 1216/1568 [03:29<01:00,  5.79it/s]16 03:03:06 Save the image 00826N.png
 78%|█████████████████████████████▍        | 1217/1568 [03:30<01:01,  5.75it/s]16 03:03:07 Save the image 00826N_flip.png
 78%|█████████████████████████████▌        | 1218/1568 [03:30<01:00,  5.76it/s]16 03:03:07 Save the image 00827N.png
 78%|█████████████████████████████▌        | 1219/1568 [03:30<01:01,  5.72it/s]16 03:03:07 Save the image 00827N_flip.png
 78%|█████████████████████████████▌        | 1220/1568 [03:30<01:00,  5.73it/s]16 03:03:07 Save the image 00828N.png
 78%|█████████████████████████████▌        | 1221/1568 [03:30<01:01,  5.67it/s]16 03:03:07 Save the image 00828N_flip.png
 78%|█████████████████████████████▌        | 1222/1568 [03:30<01:01,  5.62it/s]16 03:03:07 Save the image 00829N.png
 78%|█████████████████████████████▋        | 1223/1568 [03:31<01:01,  5.59it/s]16 03:03:08 Save the image 00829N_flip.png
 78%|█████████████████████████████▋        | 1224/1568 [03:31<01:01,  5.63it/s]16 03:03:08 Save the image 00830N.png
 78%|█████████████████████████████▋        | 1225/1568 [03:31<01:00,  5.71it/s]16 03:03:08 Save the image 00830N_flip.png
 78%|█████████████████████████████▋        | 1226/1568 [03:31<00:58,  5.85it/s]16 03:03:08 Save the image 00831N.png
 78%|█████████████████████████████▋        | 1227/1568 [03:31<00:58,  5.80it/s]16 03:03:08 Save the image 00831N_flip.png
 78%|█████████████████████████████▊        | 1228/1568 [03:32<00:58,  5.79it/s]16 03:03:09 Save the image 00832N.png
 78%|█████████████████████████████▊        | 1229/1568 [03:32<00:58,  5.78it/s]16 03:03:09 Save the image 00832N_flip.png
 78%|█████████████████████████████▊        | 1230/1568 [03:32<00:59,  5.72it/s]16 03:03:09 Save the image 00833N.png
 79%|█████████████████████████████▊        | 1231/1568 [03:32<00:59,  5.69it/s]16 03:03:09 Save the image 00833N_flip.png
 79%|█████████████████████████████▊        | 1232/1568 [03:32<00:58,  5.72it/s]16 03:03:09 Save the image 00834N.png
 79%|█████████████████████████████▉        | 1233/1568 [03:32<00:58,  5.69it/s]16 03:03:09 Save the image 00834N_flip.png
 79%|█████████████████████████████▉        | 1234/1568 [03:33<00:55,  6.04it/s]16 03:03:10 Save the image 00835N.png
 79%|█████████████████████████████▉        | 1235/1568 [03:33<00:56,  5.92it/s]16 03:03:10 Save the image 00835N_flip.png
 79%|█████████████████████████████▉        | 1236/1568 [03:33<00:56,  5.88it/s]16 03:03:10 Save the image 00836N.png
 79%|█████████████████████████████▉        | 1237/1568 [03:33<00:56,  5.88it/s]16 03:03:10 Save the image 00836N_flip.png
 79%|██████████████████████████████        | 1238/1568 [03:33<00:56,  5.81it/s]16 03:03:10 Save the image 00837N.png
 79%|██████████████████████████████        | 1239/1568 [03:33<00:56,  5.83it/s]16 03:03:10 Save the image 00837N_flip.png
 79%|██████████████████████████████        | 1240/1568 [03:34<00:56,  5.78it/s]16 03:03:11 Save the image 00838N.png
 79%|██████████████████████████████        | 1241/1568 [03:34<00:56,  5.78it/s]16 03:03:11 Save the image 00838N_flip.png
 79%|██████████████████████████████        | 1242/1568 [03:34<00:53,  6.09it/s]16 03:03:11 Save the image 00839N.png
 79%|██████████████████████████████        | 1243/1568 [03:34<00:54,  5.96it/s]16 03:03:11 Save the image 00839N_flip.png
 79%|██████████████████████████████▏       | 1244/1568 [03:34<00:54,  5.91it/s]16 03:03:11 Save the image 00840N.png
 79%|██████████████████████████████▏       | 1245/1568 [03:34<00:55,  5.86it/s]16 03:03:11 Save the image 00840N_flip.png
 79%|██████████████████████████████▏       | 1246/1568 [03:35<00:55,  5.78it/s]16 03:03:12 Save the image 00841N.png
 80%|██████████████████████████████▏       | 1247/1568 [03:35<00:55,  5.78it/s]16 03:03:12 Save the image 00841N_flip.png
 80%|██████████████████████████████▏       | 1248/1568 [03:35<00:56,  5.70it/s]16 03:03:12 Save the image 00842N.png
 80%|██████████████████████████████▎       | 1249/1568 [03:35<00:55,  5.72it/s]16 03:03:12 Save the image 00842N_flip.png
 80%|██████████████████████████████▎       | 1250/1568 [03:35<00:52,  6.10it/s]16 03:03:12 Save the image 00843N.png
 80%|██████████████████████████████▎       | 1251/1568 [03:35<00:52,  5.99it/s]16 03:03:12 Save the image 00843N_flip.png
 80%|██████████████████████████████▎       | 1252/1568 [03:36<00:53,  5.91it/s]16 03:03:13 Save the image 00844N.png
 80%|██████████████████████████████▎       | 1253/1568 [03:36<00:53,  5.88it/s]16 03:03:13 Save the image 00844N_flip.png
 80%|██████████████████████████████▍       | 1254/1568 [03:36<00:53,  5.84it/s]16 03:03:13 Save the image 00845N.png
 80%|██████████████████████████████▍       | 1255/1568 [03:36<00:54,  5.79it/s]16 03:03:13 Save the image 00845N_flip.png
 80%|██████████████████████████████▍       | 1256/1568 [03:36<00:53,  5.79it/s]16 03:03:13 Save the image 00846N.png
 80%|██████████████████████████████▍       | 1257/1568 [03:36<00:54,  5.75it/s]16 03:03:13 Save the image 00846N_flip.png
 80%|██████████████████████████████▍       | 1258/1568 [03:37<00:50,  6.11it/s]16 03:03:14 Save the image 00847N.png
 80%|██████████████████████████████▌       | 1259/1568 [03:37<00:51,  5.96it/s]16 03:03:14 Save the image 00847N_flip.png
 80%|██████████████████████████████▌       | 1260/1568 [03:37<00:52,  5.90it/s]16 03:03:14 Save the image 00848N.png
 80%|██████████████████████████████▌       | 1261/1568 [03:37<00:52,  5.88it/s]16 03:03:14 Save the image 00848N_flip.png
 80%|██████████████████████████████▌       | 1262/1568 [03:37<00:52,  5.77it/s]16 03:03:14 Save the image 00849N.png
 81%|██████████████████████████████▌       | 1263/1568 [03:38<00:52,  5.76it/s]16 03:03:15 Save the image 00849N_flip.png
 81%|██████████████████████████████▋       | 1264/1568 [03:38<00:52,  5.76it/s]16 03:03:15 Save the image 00850N.png
 81%|██████████████████████████████▋       | 1265/1568 [03:38<00:52,  5.73it/s]16 03:03:15 Save the image 00850N_flip.png
 81%|██████████████████████████████▋       | 1266/1568 [03:38<00:49,  6.05it/s]16 03:03:15 Save the image 00851N.png
 81%|██████████████████████████████▋       | 1267/1568 [03:38<00:50,  5.91it/s]16 03:03:15 Save the image 00851N_flip.png
 81%|██████████████████████████████▋       | 1268/1568 [03:38<00:50,  5.90it/s]16 03:03:15 Save the image 00852N.png
 81%|██████████████████████████████▊       | 1269/1568 [03:39<00:50,  5.87it/s]16 03:03:16 Save the image 00852N_flip.png
 81%|██████████████████████████████▊       | 1270/1568 [03:39<00:51,  5.80it/s]16 03:03:16 Save the image 00853N.png
 81%|██████████████████████████████▊       | 1271/1568 [03:39<00:51,  5.82it/s]16 03:03:16 Save the image 00853N_flip.png
 81%|██████████████████████████████▊       | 1272/1568 [03:39<00:51,  5.80it/s]16 03:03:16 Save the image 00854N.png

 81%|██████████████████████████████▊       | 1273/1568 [03:39<00:51,  5.77it/s]16 03:03:16 Save the image 00854N_flip.png
 81%|██████████████████████████████▉       | 1274/1568 [03:39<00:47,  6.18it/s]16 03:03:16 Save the image 00855N.png
 81%|██████████████████████████████▉       | 1275/1568 [03:40<00:49,  5.98it/s]16 03:03:17 Save the image 00855N_flip.png
 81%|██████████████████████████████▉       | 1276/1568 [03:40<00:49,  5.95it/s]16 03:03:17 Save the image 00856N.png
 81%|██████████████████████████████▉       | 1277/1568 [03:40<00:49,  5.88it/s]16 03:03:17 Save the image 00856N_flip.png
 82%|██████████████████████████████▉       | 1278/1568 [03:40<00:50,  5.78it/s]16 03:03:17 Save the image 00857N.png
 82%|██████████████████████████████▉       | 1279/1568 [03:40<00:49,  5.78it/s]16 03:03:17 Save the image 00857N_flip.png
 82%|███████████████████████████████       | 1280/1568 [03:40<00:50,  5.74it/s]16 03:03:17 Save the image 00858N.png
 82%|███████████████████████████████       | 1281/1568 [03:41<00:50,  5.70it/s]16 03:03:18 Save the image 00858N_flip.png
 82%|███████████████████████████████       | 1282/1568 [03:41<00:47,  6.08it/s]16 03:03:18 Save the image 00859N.png
 82%|███████████████████████████████       | 1283/1568 [03:41<00:47,  5.94it/s]16 03:03:18 Save the image 00859N_flip.png
 82%|███████████████████████████████       | 1284/1568 [03:41<00:48,  5.90it/s]16 03:03:18 Save the image 00860N.png
 82%|███████████████████████████████▏      | 1285/1568 [03:41<00:48,  5.85it/s]16 03:03:18 Save the image 00860N_flip.png
 82%|███████████████████████████████▏      | 1286/1568 [03:41<00:48,  5.77it/s]16 03:03:18 Save the image 00861N.png
 82%|███████████████████████████████▏      | 1287/1568 [03:42<00:49,  5.70it/s]16 03:03:19 Save the image 00861N_flip.png
 82%|███████████████████████████████▏      | 1288/1568 [03:42<00:48,  5.72it/s]16 03:03:19 Save the image 00862N.png
 82%|███████████████████████████████▏      | 1289/1568 [03:42<00:48,  5.74it/s]16 03:03:19 Save the image 00862N_flip.png
 82%|███████████████████████████████▎      | 1290/1568 [03:42<00:45,  6.12it/s]16 03:03:19 Save the image 00863N.png
 82%|███████████████████████████████▎      | 1291/1568 [03:42<00:46,  5.99it/s]16 03:03:19 Save the image 00863N_flip.png
 82%|███████████████████████████████▎      | 1292/1568 [03:42<00:46,  5.96it/s]16 03:03:19 Save the image 00864N.png
 82%|███████████████████████████████▎      | 1293/1568 [03:43<00:46,  5.91it/s]16 03:03:20 Save the image 00864N_flip.png
 83%|███████████████████████████████▎      | 1294/1568 [03:43<00:47,  5.83it/s]16 03:03:20 Save the image 00865N.png
 83%|███████████████████████████████▍      | 1295/1568 [03:43<00:47,  5.76it/s]16 03:03:20 Save the image 00865N_flip.png
 83%|███████████████████████████████▍      | 1296/1568 [03:43<00:47,  5.72it/s]16 03:03:20 Save the image 00866N.png
 83%|███████████████████████████████▍      | 1297/1568 [03:43<00:47,  5.76it/s]16 03:03:20 Save the image 00866N_flip.png
 83%|███████████████████████████████▍      | 1298/1568 [03:43<00:44,  6.10it/s]16 03:03:20 Save the image 00867N.png
 83%|███████████████████████████████▍      | 1299/1568 [03:44<00:45,  5.91it/s]16 03:03:21 Save the image 00867N_flip.png
 83%|███████████████████████████████▌      | 1300/1568 [03:44<00:45,  5.89it/s]16 03:03:21 Save the image 00868N.png
 83%|███████████████████████████████▌      | 1301/1568 [03:44<00:45,  5.87it/s]16 03:03:21 Save the image 00868N_flip.png
 83%|███████████████████████████████▌      | 1302/1568 [03:44<00:45,  5.80it/s]16 03:03:21 Save the image 00869N.png
 83%|███████████████████████████████▌      | 1303/1568 [03:44<00:46,  5.73it/s]16 03:03:21 Save the image 00869N_flip.png
 83%|███████████████████████████████▌      | 1304/1568 [03:45<00:46,  5.71it/s]16 03:03:22 Save the image 00870N.png
 83%|███████████████████████████████▋      | 1305/1568 [03:45<00:45,  5.73it/s]16 03:03:22 Save the image 00870N_flip.png
 83%|███████████████████████████████▋      | 1306/1568 [03:45<00:42,  6.13it/s]16 03:03:22 Save the image 00871N.png
 83%|███████████████████████████████▋      | 1307/1568 [03:45<00:43,  6.00it/s]16 03:03:22 Save the image 00871N_flip.png
 83%|███████████████████████████████▋      | 1308/1568 [03:45<00:43,  5.93it/s]16 03:03:22 Save the image 00872N.png
 83%|███████████████████████████████▋      | 1309/1568 [03:45<00:43,  5.89it/s]16 03:03:22 Save the image 00872N_flip.png
 84%|███████████████████████████████▋      | 1310/1568 [03:46<00:44,  5.82it/s]16 03:03:23 Save the image 00873N.png
 84%|███████████████████████████████▊      | 1311/1568 [03:46<00:44,  5.82it/s]16 03:03:23 Save the image 00873N_flip.png
 84%|███████████████████████████████▊      | 1312/1568 [03:46<00:43,  5.82it/s]16 03:03:23 Save the image 00874N.png
 84%|███████████████████████████████▊      | 1313/1568 [03:46<00:44,  5.78it/s]16 03:03:23 Save the image 00874N_flip.png
 84%|███████████████████████████████▊      | 1314/1568 [03:46<00:41,  6.12it/s]16 03:03:23 Save the image 00875N.png
 84%|███████████████████████████████▊      | 1315/1568 [03:46<00:42,  5.99it/s]16 03:03:23 Save the image 00875N_flip.png
 84%|███████████████████████████████▉      | 1316/1568 [03:47<00:42,  5.96it/s]16 03:03:24 Save the image 00876N.png
 84%|███████████████████████████████▉      | 1317/1568 [03:47<00:42,  5.93it/s]16 03:03:24 Save the image 00876N_flip.png
 84%|███████████████████████████████▉      | 1318/1568 [03:47<00:42,  5.86it/s]16 03:03:24 Save the image 00877N.png
 84%|███████████████████████████████▉      | 1319/1568 [03:47<00:43,  5.78it/s]16 03:03:24 Save the image 00877N_flip.png
 84%|███████████████████████████████▉      | 1320/1568 [03:47<00:42,  5.77it/s]16 03:03:24 Save the image 00878N.png
 84%|████████████████████████████████      | 1321/1568 [03:47<00:42,  5.77it/s]16 03:03:24 Save the image 00878N_flip.png
 84%|████████████████████████████████      | 1322/1568 [03:48<00:40,  6.08it/s]16 03:03:25 Save the image 00879N.png
 84%|████████████████████████████████      | 1323/1568 [03:48<00:41,  5.89it/s]16 03:03:25 Save the image 00879N_flip.png
 84%|████████████████████████████████      | 1324/1568 [03:48<00:41,  5.84it/s]16 03:03:25 Save the image 00880N.png
 85%|████████████████████████████████      | 1325/1568 [03:48<00:41,  5.86it/s]16 03:03:25 Save the image 00880N_flip.png
 85%|████████████████████████████████▏     | 1326/1568 [03:48<00:41,  5.81it/s]16 03:03:25 Save the image 00881N.png
 85%|████████████████████████████████▏     | 1327/1568 [03:48<00:41,  5.77it/s]16 03:03:25 Save the image 00881N_flip.png
 85%|████████████████████████████████▏     | 1328/1568 [03:49<00:41,  5.77it/s]16 03:03:26 Save the image 00882N.png
 85%|████████████████████████████████▏     | 1329/1568 [03:49<00:41,  5.75it/s]16 03:03:26 Save the image 00882N_flip.png
 85%|████████████████████████████████▏     | 1330/1568 [03:49<00:39,  6.04it/s]16 03:03:26 Save the image 00883N.png
 85%|████████████████████████████████▎     | 1331/1568 [03:49<00:40,  5.90it/s]16 03:03:26 Save the image 00883N_flip.png
 85%|████████████████████████████████▎     | 1332/1568 [03:49<00:40,  5.88it/s]16 03:03:26 Save the image 00884N.png
 85%|████████████████████████████████▎     | 1333/1568 [03:49<00:40,  5.85it/s]16 03:03:26 Save the image 00884N_flip.png
 85%|████████████████████████████████▎     | 1334/1568 [03:50<00:40,  5.76it/s]16 03:03:27 Save the image 00885N.png
 85%|████████████████████████████████▎     | 1335/1568 [03:50<00:40,  5.73it/s]16 03:03:27 Save the image 00885N_flip.png
 85%|████████████████████████████████▍     | 1336/1568 [03:50<00:40,  5.70it/s]16 03:03:27 Save the image 00886N.png

 85%|████████████████████████████████▍     | 1337/1568 [03:50<00:40,  5.73it/s]16 03:03:27 Save the image 00886N_flip.png
 85%|████████████████████████████████▍     | 1338/1568 [03:50<00:37,  6.13it/s]16 03:03:27 Save the image 00887N.png
 85%|████████████████████████████████▍     | 1339/1568 [03:50<00:38,  5.95it/s]16 03:03:27 Save the image 00887N_flip.png
 85%|████████████████████████████████▍     | 1340/1568 [03:51<00:38,  5.87it/s]16 03:03:28 Save the image 00888N.png
 86%|████████████████████████████████▍     | 1341/1568 [03:51<00:38,  5.85it/s]16 03:03:28 Save the image 00888N_flip.png
 86%|████████████████████████████████▌     | 1342/1568 [03:51<00:39,  5.75it/s]16 03:03:28 Save the image 00889N.png
 86%|████████████████████████████████▌     | 1343/1568 [03:51<00:39,  5.73it/s]16 03:03:28 Save the image 00889N_flip.png
 86%|████████████████████████████████▌     | 1344/1568 [03:51<00:38,  5.75it/s]16 03:03:28 Save the image 00890N.png
 86%|████████████████████████████████▌     | 1345/1568 [03:52<00:38,  5.74it/s]16 03:03:28 Save the image 00890N_flip.png
 86%|████████████████████████████████▌     | 1346/1568 [03:52<00:36,  6.07it/s]16 03:03:29 Save the image 00891N.png
 86%|████████████████████████████████▋     | 1347/1568 [03:52<00:37,  5.93it/s]16 03:03:29 Save the image 00891N_flip.png
 86%|████████████████████████████████▋     | 1348/1568 [03:52<00:37,  5.86it/s]16 03:03:29 Save the image 00892N.png
 86%|████████████████████████████████▋     | 1349/1568 [03:52<00:37,  5.88it/s]16 03:03:29 Save the image 00892N_flip.png
 86%|████████████████████████████████▋     | 1350/1568 [03:52<00:37,  5.82it/s]16 03:03:29 Save the image 00893N.png
 86%|████████████████████████████████▋     | 1351/1568 [03:53<00:37,  5.77it/s]16 03:03:30 Save the image 00893N_flip.png
 86%|████████████████████████████████▊     | 1352/1568 [03:53<00:37,  5.72it/s]16 03:03:30 Save the image 00894N.png
 86%|████████████████████████████████▊     | 1353/1568 [03:53<00:37,  5.71it/s]16 03:03:30 Save the image 00894N_flip.png
 86%|████████████████████████████████▊     | 1354/1568 [03:53<00:35,  6.07it/s]16 03:03:30 Save the image 00895N.png
 86%|████████████████████████████████▊     | 1355/1568 [03:53<00:35,  5.95it/s]16 03:03:30 Save the image 00895N_flip.png
 86%|████████████████████████████████▊     | 1356/1568 [03:53<00:35,  5.94it/s]16 03:03:30 Save the image 00896N.png
 87%|████████████████████████████████▉     | 1357/1568 [03:54<00:35,  5.88it/s]16 03:03:31 Save the image 00896N_flip.png
 87%|████████████████████████████████▉     | 1358/1568 [03:54<00:36,  5.76it/s]16 03:03:31 Save the image 00897N.png
 87%|████████████████████████████████▉     | 1359/1568 [03:54<00:36,  5.77it/s]16 03:03:31 Save the image 00897N_flip.png
 87%|████████████████████████████████▉     | 1360/1568 [03:54<00:36,  5.77it/s]16 03:03:31 Save the image 00898N.png
 87%|████████████████████████████████▉     | 1361/1568 [03:54<00:35,  5.77it/s]16 03:03:31 Save the image 00898N_flip.png
 87%|█████████████████████████████████     | 1362/1568 [03:54<00:33,  6.12it/s]16 03:03:31 Save the image 00899N.png
 87%|█████████████████████████████████     | 1363/1568 [03:55<00:34,  5.96it/s]16 03:03:32 Save the image 00899N_flip.png
 87%|█████████████████████████████████     | 1364/1568 [03:55<00:34,  5.92it/s]16 03:03:32 Save the image 00900N.png
 87%|█████████████████████████████████     | 1365/1568 [03:55<00:34,  5.88it/s]16 03:03:32 Save the image 00900N_flip.png
 87%|█████████████████████████████████     | 1366/1568 [03:55<00:35,  5.76it/s]16 03:03:32 Save the image 00901N.png
 87%|█████████████████████████████████▏    | 1367/1568 [03:55<00:34,  5.75it/s]16 03:03:32 Save the image 00901N_flip.png
 87%|█████████████████████████████████▏    | 1368/1568 [03:55<00:35,  5.71it/s]16 03:03:32 Save the image 00902N.png
 87%|█████████████████████████████████▏    | 1369/1568 [03:56<00:34,  5.69it/s]16 03:03:33 Save the image 00902N_flip.png
 87%|█████████████████████████████████▏    | 1370/1568 [03:56<00:32,  6.04it/s]16 03:03:33 Save the image 00903N.png
 87%|█████████████████████████████████▏    | 1371/1568 [03:56<00:33,  5.92it/s]16 03:03:33 Save the image 00903N_flip.png
 88%|█████████████████████████████████▎    | 1372/1568 [03:56<00:33,  5.90it/s]16 03:03:33 Save the image 00904N.png
 88%|█████████████████████████████████▎    | 1373/1568 [03:56<00:33,  5.83it/s]16 03:03:33 Save the image 00904N_flip.png
 88%|█████████████████████████████████▎    | 1374/1568 [03:56<00:33,  5.72it/s]16 03:03:33 Save the image 00905N.png
 88%|█████████████████████████████████▎    | 1375/1568 [03:57<00:33,  5.77it/s]16 03:03:34 Save the image 00905N_flip.png
 88%|█████████████████████████████████▎    | 1376/1568 [03:57<00:33,  5.77it/s]16 03:03:34 Save the image 00906N.png
 88%|█████████████████████████████████▎    | 1377/1568 [03:57<00:33,  5.74it/s]16 03:03:34 Save the image 00906N_flip.png
 88%|█████████████████████████████████▍    | 1378/1568 [03:57<00:31,  6.09it/s]16 03:03:34 Save the image 00907N.png
 88%|█████████████████████████████████▍    | 1379/1568 [03:57<00:31,  5.96it/s]16 03:03:34 Save the image 00907N_flip.png
 88%|█████████████████████████████████▍    | 1380/1568 [03:57<00:31,  5.94it/s]16 03:03:34 Save the image 00908N.png
 88%|█████████████████████████████████▍    | 1381/1568 [03:58<00:28,  6.65it/s]16 03:03:35 Save the image 00908N_flip.png
 88%|█████████████████████████████████▍    | 1382/1568 [03:58<00:25,  7.31it/s]16 03:03:35 Save the image 00909N.png
 88%|█████████████████████████████████▌    | 1383/1568 [03:58<00:25,  7.28it/s]16 03:03:35 Save the image 00909N_flip.png
 88%|█████████████████████████████████▌    | 1384/1568 [03:58<00:25,  7.33it/s]16 03:03:35 Save the image 00910N.png
 88%|█████████████████████████████████▌    | 1385/1568 [03:58<00:23,  7.75it/s]16 03:03:35 Save the image 00910N_flip.png
 88%|█████████████████████████████████▌    | 1386/1568 [03:58<00:22,  8.14it/s]16 03:03:35 Save the image 00911N.png
 88%|█████████████████████████████████▌    | 1387/1568 [03:58<00:21,  8.51it/s]16 03:03:35 Save the image 00911N_flip.png
 89%|█████████████████████████████████▋    | 1388/1568 [03:58<00:20,  8.67it/s]16 03:03:35 Save the image 00912N.png
 89%|█████████████████████████████████▋    | 1389/1568 [03:58<00:20,  8.83it/s]16 03:03:35 Save the image 00912N_flip.png
 89%|█████████████████████████████████▋    | 1390/1568 [03:59<00:19,  8.92it/s]16 03:03:36 Save the image 00913N.png
 89%|█████████████████████████████████▋    | 1391/1568 [03:59<00:19,  8.99it/s]16 03:03:36 Save the image 00913N_flip.png
 89%|█████████████████████████████████▋    | 1392/1568 [03:59<00:19,  9.08it/s]16 03:03:36 Save the image 00914N.png
 89%|█████████████████████████████████▊    | 1393/1568 [03:59<00:19,  9.14it/s]16 03:03:36 Save the image 00914N_flip.png
 89%|█████████████████████████████████▊    | 1394/1568 [03:59<00:18,  9.20it/s]16 03:03:36 Save the image 00915N.png
 89%|█████████████████████████████████▊    | 1395/1568 [03:59<00:18,  9.22it/s]16 03:03:36 Save the image 00915N_flip.png
 89%|█████████████████████████████████▊    | 1396/1568 [03:59<00:18,  9.26it/s]16 03:03:36 Save the image 00916N.png
 89%|█████████████████████████████████▊    | 1397/1568 [03:59<00:20,  8.16it/s]16 03:03:36 Save the image 00916N_flip.png
 89%|█████████████████████████████████▉    | 1398/1568 [04:00<00:23,  7.13it/s]16 03:03:37 Save the image 00917N.png
 89%|█████████████████████████████████▉    | 1399/1568 [04:00<00:25,  6.62it/s]16 03:03:37 Save the image 00917N_flip.png
 89%|█████████████████████████████████▉    | 1400/1568 [04:00<00:26,  6.30it/s]16 03:03:37 Save the image 00918N.png

 89%|█████████████████████████████████▉    | 1401/1568 [04:00<00:27,  6.07it/s]16 03:03:37 Save the image 00918N_flip.png
 89%|█████████████████████████████████▉    | 1402/1568 [04:00<00:26,  6.32it/s]16 03:03:37 Save the image 00919N.png
 89%|██████████████████████████████████    | 1403/1568 [04:00<00:27,  6.07it/s]16 03:03:37 Save the image 00919N_flip.png
 90%|██████████████████████████████████    | 1404/1568 [04:01<00:27,  5.97it/s]16 03:03:38 Save the image 00920N.png
 90%|██████████████████████████████████    | 1405/1568 [04:01<00:27,  5.88it/s]16 03:03:38 Save the image 00920N_flip.png
 90%|██████████████████████████████████    | 1406/1568 [04:01<00:27,  5.80it/s]16 03:03:38 Save the image 00921N.png
 90%|██████████████████████████████████    | 1407/1568 [04:01<00:27,  5.76it/s]16 03:03:38 Save the image 00921N_flip.png
 90%|██████████████████████████████████    | 1408/1568 [04:01<00:27,  5.77it/s]16 03:03:38 Save the image 00922N.png
 90%|██████████████████████████████████▏   | 1409/1568 [04:02<00:27,  5.69it/s]16 03:03:38 Save the image 00922N_flip.png
 90%|██████████████████████████████████▏   | 1410/1568 [04:02<00:26,  6.07it/s]16 03:03:39 Save the image 00923N.png
 90%|██████████████████████████████████▏   | 1411/1568 [04:02<00:26,  5.94it/s]16 03:03:39 Save the image 00923N_flip.png
 90%|██████████████████████████████████▏   | 1412/1568 [04:02<00:26,  5.89it/s]16 03:03:39 Save the image 00924N.png
 90%|██████████████████████████████████▏   | 1413/1568 [04:02<00:26,  5.83it/s]16 03:03:39 Save the image 00924N_flip.png
 90%|██████████████████████████████████▎   | 1414/1568 [04:02<00:26,  5.76it/s]16 03:03:39 Save the image 00925N.png
 90%|██████████████████████████████████▎   | 1415/1568 [04:03<00:26,  5.69it/s]16 03:03:40 Save the image 00925N_flip.png
 90%|██████████████████████████████████▎   | 1416/1568 [04:03<00:26,  5.71it/s]16 03:03:40 Save the image 00926N.png
 90%|██████████████████████████████████▎   | 1417/1568 [04:03<00:26,  5.72it/s]16 03:03:40 Save the image 00926N_flip.png
 90%|██████████████████████████████████▎   | 1418/1568 [04:03<00:24,  6.08it/s]16 03:03:40 Save the image 00927N.png
 90%|██████████████████████████████████▍   | 1419/1568 [04:03<00:25,  5.93it/s]16 03:03:40 Save the image 00927N_flip.png
 91%|██████████████████████████████████▍   | 1420/1568 [04:03<00:25,  5.83it/s]16 03:03:40 Save the image 00928N.png
 91%|██████████████████████████████████▍   | 1421/1568 [04:04<00:25,  5.84it/s]16 03:03:41 Save the image 00928N_flip.png
 91%|██████████████████████████████████▍   | 1422/1568 [04:04<00:25,  5.74it/s]16 03:03:41 Save the image 00929N.png
 91%|██████████████████████████████████▍   | 1423/1568 [04:04<00:25,  5.74it/s]16 03:03:41 Save the image 00929N_flip.png
 91%|██████████████████████████████████▌   | 1424/1568 [04:04<00:25,  5.69it/s]16 03:03:41 Save the image 00930N.png
 91%|██████████████████████████████████▌   | 1425/1568 [04:04<00:25,  5.70it/s]16 03:03:41 Save the image 00930N_flip.png
 91%|██████████████████████████████████▌   | 1426/1568 [04:04<00:23,  6.05it/s]16 03:03:41 Save the image 00931N.png
 91%|██████████████████████████████████▌   | 1427/1568 [04:05<00:23,  5.90it/s]16 03:03:42 Save the image 00931N_flip.png
 91%|██████████████████████████████████▌   | 1428/1568 [04:05<00:24,  5.81it/s]16 03:03:42 Save the image 00932N.png
 91%|██████████████████████████████████▋   | 1429/1568 [04:05<00:24,  5.76it/s]16 03:03:42 Save the image 00932N_flip.png
 91%|██████████████████████████████████▋   | 1430/1568 [04:05<00:24,  5.71it/s]16 03:03:42 Save the image 00933N.png
 91%|██████████████████████████████████▋   | 1431/1568 [04:05<00:24,  5.67it/s]16 03:03:42 Save the image 00933N_flip.png
 91%|██████████████████████████████████▋   | 1432/1568 [04:05<00:23,  5.68it/s]16 03:03:42 Save the image 00934N.png
 91%|██████████████████████████████████▋   | 1433/1568 [04:06<00:23,  5.64it/s]16 03:03:43 Save the image 00934N_flip.png
 91%|██████████████████████████████████▊   | 1434/1568 [04:06<00:22,  6.02it/s]16 03:03:43 Save the image 00935N.png
 92%|██████████████████████████████████▊   | 1435/1568 [04:06<00:22,  5.85it/s]16 03:03:43 Save the image 00935N_flip.png
 92%|██████████████████████████████████▊   | 1436/1568 [04:06<00:22,  5.79it/s]16 03:03:43 Save the image 00936N.png
 92%|██████████████████████████████████▊   | 1437/1568 [04:06<00:22,  5.77it/s]16 03:03:43 Save the image 00936N_flip.png
 92%|██████████████████████████████████▊   | 1438/1568 [04:06<00:22,  5.69it/s]16 03:03:44 Save the image 00937N.png
 92%|██████████████████████████████████▊   | 1439/1568 [04:07<00:22,  5.69it/s]16 03:03:44 Save the image 00937N_flip.png
 92%|██████████████████████████████████▉   | 1440/1568 [04:07<00:22,  5.65it/s]16 03:03:44 Save the image 00938N.png
 92%|██████████████████████████████████▉   | 1441/1568 [04:07<00:22,  5.67it/s]16 03:03:44 Save the image 00938N_flip.png
 92%|██████████████████████████████████▉   | 1442/1568 [04:07<00:20,  6.03it/s]16 03:03:44 Save the image 00939N.png
 92%|██████████████████████████████████▉   | 1443/1568 [04:07<00:21,  5.89it/s]16 03:03:44 Save the image 00939N_flip.png
 92%|██████████████████████████████████▉   | 1444/1568 [04:08<00:21,  5.80it/s]16 03:03:45 Save the image 00940N.png
 92%|███████████████████████████████████   | 1445/1568 [04:08<00:21,  5.78it/s]16 03:03:45 Save the image 00940N_flip.png
 92%|███████████████████████████████████   | 1446/1568 [04:08<00:21,  5.72it/s]16 03:03:45 Save the image 00941N.png
 92%|███████████████████████████████████   | 1447/1568 [04:08<00:21,  5.70it/s]16 03:03:45 Save the image 00941N_flip.png
 92%|███████████████████████████████████   | 1448/1568 [04:08<00:21,  5.71it/s]16 03:03:45 Save the image 00942N.png
 92%|███████████████████████████████████   | 1449/1568 [04:08<00:20,  5.72it/s]16 03:03:45 Save the image 00942N_flip.png
 92%|███████████████████████████████████▏  | 1450/1568 [04:09<00:19,  6.10it/s]16 03:03:46 Save the image 00943N.png
 93%|███████████████████████████████████▏  | 1451/1568 [04:09<00:19,  5.96it/s]16 03:03:46 Save the image 00943N_flip.png
 93%|███████████████████████████████████▏  | 1452/1568 [04:09<00:19,  5.91it/s]16 03:03:46 Save the image 00944N.png
 93%|███████████████████████████████████▏  | 1453/1568 [04:09<00:19,  5.86it/s]16 03:03:46 Save the image 00944N_flip.png
 93%|███████████████████████████████████▏  | 1454/1568 [04:09<00:19,  5.80it/s]16 03:03:46 Save the image 00945N.png
 93%|███████████████████████████████████▎  | 1455/1568 [04:09<00:19,  5.82it/s]16 03:03:46 Save the image 00945N_flip.png
 93%|███████████████████████████████████▎  | 1456/1568 [04:10<00:19,  5.77it/s]16 03:03:47 Save the image 00946N.png
 93%|███████████████████████████████████▎  | 1457/1568 [04:10<00:19,  5.78it/s]16 03:03:47 Save the image 00946N_flip.png
 93%|███████████████████████████████████▎  | 1458/1568 [04:10<00:18,  6.07it/s]16 03:03:47 Save the image 00947N.png
 93%|███████████████████████████████████▎  | 1459/1568 [04:10<00:18,  5.90it/s]16 03:03:47 Save the image 00947N_flip.png
 93%|███████████████████████████████████▍  | 1460/1568 [04:10<00:18,  5.87it/s]16 03:03:47 Save the image 00948N.png
 93%|███████████████████████████████████▍  | 1461/1568 [04:10<00:18,  5.77it/s]16 03:03:47 Save the image 00948N_flip.png
 93%|███████████████████████████████████▍  | 1462/1568 [04:11<00:18,  5.71it/s]16 03:03:48 Save the image 00949N.png
 93%|███████████████████████████████████▍  | 1463/1568 [04:11<00:18,  5.73it/s]16 03:03:48 Save the image 00949N_flip.png
 93%|███████████████████████████████████▍  | 1464/1568 [04:11<00:18,  5.72it/s]16 03:03:48 Save the image 00950N.png

 93%|███████████████████████████████████▌  | 1465/1568 [04:11<00:18,  5.69it/s]16 03:03:48 Save the image 00950N_flip.png
 93%|███████████████████████████████████▌  | 1466/1568 [04:11<00:17,  5.73it/s]16 03:03:48 Save the image 00951N.png
 94%|███████████████████████████████████▌  | 1467/1568 [04:11<00:17,  5.74it/s]16 03:03:49 Save the image 00951N_flip.png
 94%|███████████████████████████████████▌  | 1468/1568 [04:12<00:17,  5.78it/s]16 03:03:49 Save the image 00952N.png
 94%|███████████████████████████████████▌  | 1469/1568 [04:12<00:17,  5.79it/s]16 03:03:49 Save the image 00952N_flip.png
 94%|███████████████████████████████████▋  | 1470/1568 [04:12<00:16,  5.78it/s]16 03:03:49 Save the image 00953N.png
 94%|███████████████████████████████████▋  | 1471/1568 [04:12<00:16,  5.83it/s]16 03:03:49 Save the image 00953N_flip.png
 94%|███████████████████████████████████▋  | 1472/1568 [04:12<00:16,  5.87it/s]16 03:03:49 Save the image 00954N.png
 94%|███████████████████████████████████▋  | 1473/1568 [04:13<00:16,  5.85it/s]16 03:03:50 Save the image 00954N_flip.png
 94%|███████████████████████████████████▋  | 1474/1568 [04:13<00:16,  5.80it/s]16 03:03:50 Save the image 00955N.png
 94%|███████████████████████████████████▋  | 1475/1568 [04:13<00:16,  5.81it/s]16 03:03:50 Save the image 00955N_flip.png
 94%|███████████████████████████████████▊  | 1476/1568 [04:13<00:15,  5.83it/s]16 03:03:50 Save the image 00956N.png
 94%|███████████████████████████████████▊  | 1477/1568 [04:13<00:15,  5.81it/s]16 03:03:50 Save the image 00956N_flip.png
 94%|███████████████████████████████████▊  | 1478/1568 [04:13<00:15,  5.82it/s]16 03:03:50 Save the image 00957N.png
 94%|███████████████████████████████████▊  | 1479/1568 [04:14<00:15,  5.79it/s]16 03:03:51 Save the image 00957N_flip.png
 94%|███████████████████████████████████▊  | 1480/1568 [04:14<00:15,  5.84it/s]16 03:03:51 Save the image 00958N.png
 94%|███████████████████████████████████▉  | 1481/1568 [04:14<00:14,  5.80it/s]16 03:03:51 Save the image 00958N_flip.png
 95%|███████████████████████████████████▉  | 1482/1568 [04:14<00:14,  5.75it/s]16 03:03:51 Save the image 00959N.png
 95%|███████████████████████████████████▉  | 1483/1568 [04:14<00:14,  5.78it/s]16 03:03:51 Save the image 00959N_flip.png
 95%|███████████████████████████████████▉  | 1484/1568 [04:14<00:14,  5.78it/s]16 03:03:51 Save the image 00960N.png
 95%|███████████████████████████████████▉  | 1485/1568 [04:15<00:14,  5.74it/s]16 03:03:52 Save the image 00960N_flip.png
 95%|████████████████████████████████████  | 1486/1568 [04:15<00:14,  5.73it/s]16 03:03:52 Save the image 00961N.png
 95%|████████████████████████████████████  | 1487/1568 [04:15<00:14,  5.75it/s]16 03:03:52 Save the image 00961N_flip.png
 95%|████████████████████████████████████  | 1488/1568 [04:15<00:14,  5.70it/s]16 03:03:52 Save the image 00962N.png
 95%|████████████████████████████████████  | 1489/1568 [04:15<00:14,  5.64it/s]16 03:03:52 Save the image 00962N_flip.png
 95%|████████████████████████████████████  | 1490/1568 [04:15<00:13,  5.66it/s]16 03:03:52 Save the image 00963N.png
 95%|████████████████████████████████████▏ | 1491/1568 [04:16<00:13,  5.67it/s]16 03:03:53 Save the image 00963N_flip.png
 95%|████████████████████████████████████▏ | 1492/1568 [04:16<00:13,  5.68it/s]16 03:03:53 Save the image 00964N.png
 95%|████████████████████████████████████▏ | 1493/1568 [04:16<00:13,  5.63it/s]16 03:03:53 Save the image 00964N_flip.png
 95%|████████████████████████████████████▏ | 1494/1568 [04:16<00:13,  5.66it/s]16 03:03:53 Save the image 00965N.png
 95%|████████████████████████████████████▏ | 1495/1568 [04:16<00:12,  5.64it/s]16 03:03:53 Save the image 00965N_flip.png
 95%|████████████████████████████████████▎ | 1496/1568 [04:17<00:12,  5.71it/s]16 03:03:54 Save the image 00966N.png
 95%|████████████████████████████████████▎ | 1497/1568 [04:17<00:12,  5.81it/s]16 03:03:54 Save the image 00966N_flip.png
 96%|████████████████████████████████████▎ | 1498/1568 [04:17<00:12,  5.71it/s]16 03:03:54 Save the image 00967N.png
 96%|████████████████████████████████████▎ | 1499/1568 [04:17<00:12,  5.72it/s]16 03:03:54 Save the image 00967N_flip.png
 96%|████████████████████████████████████▎ | 1500/1568 [04:17<00:11,  5.70it/s]16 03:03:54 Save the image 00968N.png
 96%|████████████████████████████████████▍ | 1501/1568 [04:17<00:11,  5.67it/s]16 03:03:54 Save the image 00968N_flip.png
 96%|████████████████████████████████████▍ | 1502/1568 [04:18<00:11,  5.68it/s]16 03:03:55 Save the image 00969N.png
 96%|████████████████████████████████████▍ | 1503/1568 [04:18<00:11,  5.69it/s]16 03:03:55 Save the image 00969N_flip.png
 96%|████████████████████████████████████▍ | 1504/1568 [04:18<00:11,  5.71it/s]16 03:03:55 Save the image 00970N.png
 96%|████████████████████████████████████▍ | 1505/1568 [04:18<00:10,  5.82it/s]16 03:03:55 Save the image 00970N_flip.png
 96%|████████████████████████████████████▍ | 1506/1568 [04:18<00:10,  5.77it/s]16 03:03:55 Save the image 00971N.png
 96%|████████████████████████████████████▌ | 1507/1568 [04:18<00:10,  5.74it/s]16 03:03:55 Save the image 00971N_flip.png
 96%|████████████████████████████████████▌ | 1508/1568 [04:19<00:10,  5.75it/s]16 03:03:56 Save the image 00972N.png
 96%|████████████████████████████████████▌ | 1509/1568 [04:19<00:10,  5.69it/s]16 03:03:56 Save the image 00972N_flip.png
 96%|████████████████████████████████████▌ | 1510/1568 [04:19<00:10,  5.68it/s]16 03:03:56 Save the image 00973N.png
 96%|████████████████████████████████████▌ | 1511/1568 [04:19<00:10,  5.68it/s]16 03:03:56 Save the image 00973N_flip.png
 96%|████████████████████████████████████▋ | 1512/1568 [04:19<00:09,  5.73it/s]16 03:03:56 Save the image 00974N.png
 96%|████████████████████████████████████▋ | 1513/1568 [04:19<00:09,  5.85it/s]16 03:03:57 Save the image 00974N_flip.png
 97%|████████████████████████████████████▋ | 1514/1568 [04:20<00:09,  5.79it/s]16 03:03:57 Save the image 00975N.png
 97%|████████████████████████████████████▋ | 1515/1568 [04:20<00:09,  5.75it/s]16 03:03:57 Save the image 00975N_flip.png
 97%|████████████████████████████████████▋ | 1516/1568 [04:20<00:09,  5.74it/s]16 03:03:57 Save the image 00976N.png
 97%|████████████████████████████████████▊ | 1517/1568 [04:20<00:08,  5.69it/s]16 03:03:57 Save the image 00976N_flip.png
 97%|████████████████████████████████████▊ | 1518/1568 [04:20<00:08,  5.63it/s]16 03:03:57 Save the image 00977N.png
 97%|████████████████████████████████████▊ | 1519/1568 [04:21<00:08,  5.64it/s]16 03:03:58 Save the image 00977N_flip.png
 97%|████████████████████████████████████▊ | 1520/1568 [04:21<00:08,  5.67it/s]16 03:03:58 Save the image 00978N.png
 97%|████████████████████████████████████▊ | 1521/1568 [04:21<00:08,  5.85it/s]16 03:03:58 Save the image 00978N_flip.png
 97%|████████████████████████████████████▉ | 1522/1568 [04:21<00:07,  5.79it/s]16 03:03:58 Save the image 00979N.png
 97%|████████████████████████████████████▉ | 1523/1568 [04:21<00:07,  5.74it/s]16 03:03:58 Save the image 00979N_flip.png
 97%|████████████████████████████████████▉ | 1524/1568 [04:21<00:07,  5.75it/s]16 03:03:58 Save the image 00980N.png
 97%|████████████████████████████████████▉ | 1525/1568 [04:22<00:07,  5.75it/s]16 03:03:59 Save the image 00980N_flip.png
 97%|████████████████████████████████████▉ | 1526/1568 [04:22<00:07,  5.77it/s]16 03:03:59 Save the image 00981N.png
 97%|█████████████████████████████████████ | 1527/1568 [04:22<00:07,  5.78it/s]16 03:03:59 Save the image 00981N_flip.png
 97%|█████████████████████████████████████ | 1528/1568 [04:22<00:06,  5.83it/s]16 03:03:59 Save the image 00982N.png

 98%|█████████████████████████████████████ | 1529/1568 [04:22<00:06,  6.02it/s]16 03:03:59 Save the image 00982N_flip.png
 98%|█████████████████████████████████████ | 1530/1568 [04:22<00:06,  5.91it/s]16 03:03:59 Save the image 00983N.png
 98%|█████████████████████████████████████ | 1531/1568 [04:23<00:06,  5.90it/s]16 03:04:00 Save the image 00983N_flip.png
 98%|█████████████████████████████████████▏| 1532/1568 [04:23<00:06,  5.85it/s]16 03:04:00 Save the image 00984N.png
 98%|█████████████████████████████████████▏| 1533/1568 [04:23<00:06,  5.80it/s]16 03:04:00 Save the image 00984N_flip.png
 98%|█████████████████████████████████████▏| 1534/1568 [04:23<00:05,  5.76it/s]16 03:04:00 Save the image 00985N.png
 98%|█████████████████████████████████████▏| 1535/1568 [04:23<00:05,  5.71it/s]16 03:04:00 Save the image 00985N_flip.png
 98%|█████████████████████████████████████▏| 1536/1568 [04:23<00:05,  5.71it/s]16 03:04:00 Save the image 00986N.png
 98%|█████████████████████████████████████▏| 1537/1568 [04:24<00:05,  6.08it/s]16 03:04:01 Save the image 00986N_flip.png
 98%|█████████████████████████████████████▎| 1538/1568 [04:24<00:05,  5.97it/s]16 03:04:01 Save the image 00987N.png
 98%|█████████████████████████████████████▎| 1539/1568 [04:24<00:04,  5.87it/s]16 03:04:01 Save the image 00987N_flip.png
 98%|█████████████████████████████████████▎| 1540/1568 [04:24<00:04,  5.81it/s]16 03:04:01 Save the image 00988N.png
 98%|█████████████████████████████████████▎| 1541/1568 [04:24<00:04,  5.76it/s]16 03:04:01 Save the image 00988N_flip.png
 98%|█████████████████████████████████████▎| 1542/1568 [04:25<00:04,  5.75it/s]16 03:04:02 Save the image 00989N.png
 98%|█████████████████████████████████████▍| 1543/1568 [04:25<00:04,  5.71it/s]16 03:04:02 Save the image 00989N_flip.png
 98%|█████████████████████████████████████▍| 1544/1568 [04:25<00:04,  5.70it/s]16 03:04:02 Save the image 00990N.png
 99%|█████████████████████████████████████▍| 1545/1568 [04:25<00:03,  5.93it/s]16 03:04:02 Save the image 00990N_flip.png
 99%|█████████████████████████████████████▍| 1546/1568 [04:25<00:03,  5.83it/s]16 03:04:02 Save the image 00991N.png
 99%|█████████████████████████████████████▍| 1547/1568 [04:25<00:03,  5.79it/s]16 03:04:02 Save the image 00991N_flip.png
 99%|█████████████████████████████████████▌| 1548/1568 [04:26<00:03,  5.81it/s]16 03:04:03 Save the image 00992N.png
 99%|█████████████████████████████████████▌| 1549/1568 [04:26<00:03,  5.76it/s]16 03:04:03 Save the image 00992N_flip.png
 99%|█████████████████████████████████████▌| 1550/1568 [04:26<00:03,  5.67it/s]16 03:04:03 Save the image 00993N.png
 99%|█████████████████████████████████████▌| 1551/1568 [04:26<00:02,  5.71it/s]16 03:04:03 Save the image 00993N_flip.png
 99%|█████████████████████████████████████▌| 1552/1568 [04:26<00:02,  5.72it/s]16 03:04:03 Save the image 00994N.png
 99%|█████████████████████████████████████▋| 1553/1568 [04:26<00:02,  5.97it/s]16 03:04:03 Save the image 00994N_flip.png
 99%|█████████████████████████████████████▋| 1554/1568 [04:27<00:02,  5.84it/s]16 03:04:04 Save the image 00995N.png
 99%|█████████████████████████████████████▋| 1555/1568 [04:27<00:02,  5.82it/s]16 03:04:04 Save the image 00995N_flip.png
 99%|█████████████████████████████████████▋| 1556/1568 [04:27<00:02,  5.78it/s]16 03:04:04 Save the image 00996N.png
 99%|█████████████████████████████████████▋| 1557/1568 [04:27<00:01,  5.74it/s]16 03:04:04 Save the image 00996N_flip.png
 99%|█████████████████████████████████████▊| 1558/1568 [04:27<00:01,  5.77it/s]16 03:04:04 Save the image 00997N.png
 99%|█████████████████████████████████████▊| 1559/1568 [04:27<00:01,  5.76it/s]16 03:04:04 Save the image 00997N_flip.png
 99%|█████████████████████████████████████▊| 1560/1568 [04:28<00:01,  5.80it/s]16 03:04:05 Save the image 00998N.png
100%|█████████████████████████████████████▊| 1561/1568 [04:28<00:01,  6.01it/s]16 03:04:05 Save the image 00998N_flip.png
100%|█████████████████████████████████████▊| 1562/1568 [04:28<00:01,  5.90it/s]16 03:04:05 Save the image 00999N.png
100%|█████████████████████████████████████▉| 1563/1568 [04:28<00:00,  5.89it/s]16 03:04:05 Save the image 00999N_flip.png
100%|█████████████████████████████████████▉| 1564/1568 [04:28<00:00,  5.85it/s]16 03:04:05 Save the image 01000N.png
100%|█████████████████████████████████████▉| 1565/1568 [04:28<00:00,  5.79it/s]16 03:04:05 Save the image 01000N_flip.png
100%|█████████████████████████████████████▉| 1566/1568 [04:29<00:00,  5.77it/s]16 03:04:06 Save the image 01001N.png
100%|█████████████████████████████████████▉| 1567/1568 [04:29<00:00,  5.79it/s]16 03:04:06 Save the image 01001N_flip.png
100%|██████████████████████████████████████| 1568/1568 [04:29<00:00,  5.82it/s]
1 unlabeled	99.514%
2 car   	97.196%
3 person	89.110%
4 bike  	89.782%
5 curve 	90.328%
6 car_stop	92.313%
7 guardrail	95.834%
8 color_cone	85.626%
9 bump  	94.115%
----------     mean_IoU	92.646%	freq_IoU	99.080%	mean_pixel_acc	96.752%	pixel_acc	99.528%
16 03:04:06 Evaluation Elapsed Time: 269.48s

# E3

In [16]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E3")

!python eval.py -e 100 -d 0 --split test -p predictions_E3_test

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 03:05:26 using devices 0
16 03:05:26 Using E3: SegFormer-B2 with reliability-guided fusion
16 03:05:27 Using MLP Decoder
16 03:05:27 Load Model: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e3/checkpoint/epoch-100.pth
16 03:05:32 Load model, Time usage:
	IO: 4.592591047286987, initialize parameters: 0.0491793155670166
16 03:05:32 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@8.862] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 03:05:33 Save the image 01402D.png
  0%|                                          | 1/393 [00:01<09:42,  1.49s/it]16 03:05:34 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:01<04:41,  1.39it/s]16 03:05:34 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:01<03:04,  2.12it/s]16 03:05:34 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:02<02:18,  2.80it/s]16 03:05:34 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:02<01:54,  3.38it/s]16 03:05:34 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:02<01:41,  3.82it/s]16 03:05:35 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:02<01:31,  4.23it/s]16 03:05:35 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:02<01:24,  4.57it/s]16 03:05:35 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:02<01:19,  4.81it/s]16 03:05:35 Save the image 01411D.png
  3%|█                                        | 10/393 [00:03<01:17,  4.94it/s]16 03:05:35 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:03<01:14,  5.13it/s]16 03:05:36 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:03<01:13,  5.20it/s]16 03:05:36 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:03<01:12,  5.25it/s]16 03:05:36 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:03<01:12,  5.23it/s]16 03:05:36 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:04<01:11,  5.31it/s]16 03:05:36 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:04<01:10,  5.37it/s]16 03:05:36 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:04<01:10,  5.37it/s]16 03:05:37 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:04<01:08,  5.44it/s]16 03:05:37 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:04<01:09,  5.42it/s]16 03:05:37 Save the image 01421D.png
  5%|██                                       | 20/393 [00:04<01:08,  5.43it/s]16 03:05:37 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:05<01:08,  5.43it/s]16 03:05:37 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:05<01:08,  5.45it/s]16 03:05:38 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:05<01:06,  5.53it/s]16 03:05:38 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:05<01:07,  5.48it/s]16 03:05:38 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:05<01:07,  5.46it/s]16 03:05:38 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:06<01:07,  5.44it/s]16 03:05:38 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:06<01:07,  5.42it/s]16 03:05:38 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:06<01:07,  5.39it/s]16 03:05:39 Save the image 01430D.png
  7%|███                                      | 29/393 [00:06<01:07,  5.39it/s]16 03:05:39 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:06<01:07,  5.39it/s]16 03:05:39 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:07<01:07,  5.37it/s]16 03:05:39 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:07<01:07,  5.36it/s]16 03:05:39 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:07<01:07,  5.32it/s]16 03:05:40 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:07<01:06,  5.38it/s]16 03:05:40 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:07<01:03,  5.66it/s]16 03:05:40 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:07<01:03,  5.60it/s]16 03:05:40 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:08<01:03,  5.58it/s]16 03:05:40 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:08<01:03,  5.56it/s]16 03:05:40 Save the image 01440D.png
 10%|████                                     | 39/393 [00:08<01:04,  5.52it/s]16 03:05:41 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:08<01:04,  5.48it/s]16 03:05:41 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:08<01:03,  5.53it/s]16 03:05:41 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:08<01:01,  5.70it/s]16 03:05:41 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:09<01:02,  5.61it/s]16 03:05:41 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:09<01:02,  5.58it/s]16 03:05:42 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:09<01:02,  5.57it/s]16 03:05:42 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:09<01:02,  5.52it/s]16 03:05:42 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:09<01:02,  5.57it/s]16 03:05:42 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:10<01:02,  5.56it/s]16 03:05:42 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:10<01:02,  5.51it/s]16 03:05:42 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:10<01:02,  5.49it/s]16 03:05:43 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:10<01:02,  5.50it/s]16 03:05:43 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:10<01:02,  5.50it/s]16 03:05:43 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:11<01:02,  5.41it/s]16 03:05:43 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:11<01:01,  5.47it/s]16 03:05:43 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:11<01:02,  5.45it/s]16 03:05:44 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:11<01:02,  5.39it/s]16 03:05:44 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:11<01:02,  5.35it/s]16 03:05:44 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:11<01:01,  5.41it/s]16 03:05:44 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:12<01:01,  5.43it/s]16 03:05:44 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:12<01:01,  5.41it/s]16 03:05:44 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:12<01:01,  5.41it/s]16 03:05:45 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:12<01:00,  5.46it/s]16 03:05:45 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:12<01:00,  5.44it/s]16 03:05:45 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:13<01:00,  5.44it/s]16 03:05:45 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:13<01:00,  5.46it/s]16 03:05:45 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:13<00:59,  5.47it/s]16 03:05:46 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:13<00:59,  5.45it/s]16 03:05:46 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:13<00:59,  5.46it/s]16 03:05:46 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:13<00:59,  5.44it/s]16 03:05:46 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:14<00:59,  5.43it/s]16 03:05:46 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:14<00:59,  5.42it/s]16 03:05:47 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:14<00:59,  5.42it/s]16 03:05:47 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:14<00:58,  5.46it/s]16 03:05:47 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:14<00:58,  5.44it/s]16 03:05:47 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:15<00:58,  5.43it/s]16 03:05:47 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:15<00:58,  5.42it/s]16 03:05:47 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:15<00:58,  5.41it/s]16 03:05:48 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:15<00:58,  5.37it/s]16 03:05:48 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:15<00:58,  5.39it/s]16 03:05:48 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:15<00:57,  5.40it/s]16 03:05:48 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:16<00:58,  5.30it/s]16 03:05:48 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:16<00:58,  5.35it/s]16 03:05:49 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:16<00:58,  5.34it/s]16 03:05:49 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:16<00:57,  5.34it/s]16 03:05:49 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:16<00:57,  5.39it/s]16 03:05:49 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:17<00:57,  5.37it/s]16 03:05:49 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:17<00:57,  5.33it/s]16 03:05:49 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:17<00:57,  5.34it/s]16 03:05:50 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:17<00:56,  5.36it/s]16 03:05:50 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:17<00:56,  5.38it/s]16 03:05:50 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:18<00:55,  5.41it/s]16 03:05:50 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:18<00:52,  5.72it/s]16 03:05:50 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:18<00:53,  5.62it/s]16 03:05:51 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:18<00:53,  5.59it/s]16 03:05:51 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:18<00:53,  5.55it/s]16 03:05:51 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:18<00:53,  5.56it/s]16 03:05:51 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:19<00:53,  5.57it/s]16 03:05:51 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:19<00:52,  5.58it/s]16 03:05:51 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:19<00:52,  5.55it/s]16 03:05:52 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:19<00:53,  5.50it/s]16 03:05:52 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:19<00:52,  5.52it/s]16 03:05:52 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:20<00:52,  5.50it/s]16 03:05:52 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:20<00:53,  5.46it/s]16 03:05:52 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:20<00:52,  5.50it/s]16 03:05:53 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:20<00:52,  5.53it/s]16 03:05:53 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:20<00:52,  5.45it/s]16 03:05:53 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:20<00:52,  5.44it/s]16 03:05:53 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:21<00:51,  5.48it/s]16 03:05:53 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:21<00:52,  5.44it/s]16 03:05:53 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:21<00:52,  5.43it/s]16 03:05:54 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:21<00:52,  5.42it/s]16 03:05:54 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:21<00:51,  5.42it/s]16 03:05:54 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:22<00:52,  5.35it/s]16 03:05:54 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:22<00:52,  5.33it/s]16 03:05:54 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:22<00:52,  5.33it/s]16 03:05:55 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:22<00:52,  5.32it/s]16 03:05:55 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:22<00:52,  5.28it/s]16 03:05:55 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:22<00:51,  5.32it/s]16 03:05:55 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:23<00:51,  5.36it/s]16 03:05:55 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:23<00:51,  5.33it/s]16 03:05:56 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:23<00:47,  5.67it/s]16 03:05:56 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:23<00:49,  5.52it/s]16 03:05:56 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:23<00:48,  5.57it/s]16 03:05:56 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:24<00:49,  5.49it/s]16 03:05:56 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:24<00:49,  5.41it/s]16 03:05:56 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:24<00:49,  5.45it/s]16 03:05:57 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:24<00:48,  5.44it/s]16 03:05:57 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:24<00:48,  5.41it/s]16 03:05:57 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:24<00:48,  5.39it/s]16 03:05:57 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:25<00:48,  5.43it/s]16 03:05:57 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:25<00:48,  5.41it/s]16 03:05:58 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:25<00:48,  5.34it/s]16 03:05:58 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:25<00:48,  5.38it/s]16 03:05:58 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:25<00:48,  5.36it/s]16 03:05:58 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:26<00:48,  5.37it/s]16 03:05:58 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:26<00:47,  5.38it/s]16 03:05:58 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:26<00:47,  5.38it/s]16 03:05:59 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:26<00:47,  5.42it/s]16 03:05:59 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:26<00:46,  5.41it/s]16 03:05:59 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:27<00:46,  5.47it/s]16 03:05:59 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:27<00:46,  5.45it/s]16 03:05:59 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:27<00:46,  5.43it/s]16 03:06:00 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:27<00:45,  5.49it/s]16 03:06:00 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:27<00:45,  5.46it/s]16 03:06:00 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:27<00:45,  5.46it/s]16 03:06:00 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:28<00:45,  5.44it/s]16 03:06:00 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:28<00:45,  5.45it/s]16 03:06:01 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:28<00:45,  5.43it/s]16 03:06:01 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:28<00:44,  5.43it/s]16 03:06:01 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:28<00:44,  5.42it/s]16 03:06:01 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:29<00:44,  5.44it/s]16 03:06:01 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:29<00:44,  5.43it/s]16 03:06:01 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:29<00:44,  5.42it/s]16 03:06:02 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:29<00:44,  5.41it/s]16 03:06:02 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:29<00:44,  5.40it/s]16 03:06:02 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:29<00:43,  5.40it/s]16 03:06:02 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:30<00:43,  5.39it/s]16 03:06:02 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:30<00:43,  5.42it/s]16 03:06:03 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:30<00:43,  5.43it/s]16 03:06:03 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:30<00:43,  5.36it/s]16 03:06:03 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:30<00:42,  5.43it/s]16 03:06:03 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:31<00:42,  5.41it/s]16 03:06:03 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:31<00:42,  5.40it/s]16 03:06:03 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:31<00:42,  5.39it/s]16 03:06:04 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:31<00:42,  5.39it/s]16 03:06:04 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:31<00:41,  5.42it/s]16 03:06:04 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:32<00:42,  5.33it/s]16 03:06:04 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:32<00:41,  5.42it/s]16 03:06:04 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:32<00:41,  5.41it/s]16 03:06:05 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:32<00:41,  5.41it/s]16 03:06:05 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:32<00:40,  5.46it/s]16 03:06:05 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:32<00:40,  5.42it/s]16 03:06:05 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:33<00:40,  5.40it/s]16 03:06:05 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:33<00:41,  5.32it/s]16 03:06:06 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:33<00:40,  5.33it/s]16 03:06:06 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:33<00:40,  5.35it/s]16 03:06:06 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:33<00:40,  5.36it/s]16 03:06:06 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:34<00:40,  5.36it/s]16 03:06:06 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:34<00:39,  5.38it/s]16 03:06:06 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:34<00:39,  5.41it/s]16 03:06:07 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:34<00:39,  5.40it/s]16 03:06:07 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:34<00:39,  5.40it/s]16 03:06:07 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:34<00:38,  5.39it/s]16 03:06:07 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:35<00:38,  5.38it/s]16 03:06:07 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:35<00:38,  5.40it/s]16 03:06:08 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:35<00:38,  5.40it/s]16 03:06:08 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:35<00:38,  5.38it/s]16 03:06:08 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:35<00:37,  5.40it/s]16 03:06:08 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:36<00:38,  5.34it/s]16 03:06:08 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:36<00:38,  5.30it/s]16 03:06:08 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:36<00:37,  5.33it/s]16 03:06:09 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:36<00:37,  5.34it/s]16 03:06:09 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:36<00:37,  5.36it/s]16 03:06:09 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:37<00:36,  5.39it/s]16 03:06:09 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:37<00:36,  5.36it/s]16 03:06:09 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:37<00:37,  5.31it/s]16 03:06:10 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:37<00:36,  5.35it/s]16 03:06:10 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:37<00:36,  5.40it/s]16 03:06:10 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:37<00:33,  5.72it/s]16 03:06:10 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:38<00:34,  5.62it/s]16 03:06:10 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:38<00:33,  5.67it/s]16 03:06:10 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:38<00:34,  5.53it/s]16 03:06:11 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:38<00:34,  5.49it/s]16 03:06:11 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:38<00:34,  5.52it/s]16 03:06:11 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:39<00:34,  5.52it/s]16 03:06:11 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:39<00:33,  5.62it/s]16 03:06:11 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:39<00:33,  5.53it/s]16 03:06:12 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:39<00:33,  5.49it/s]16 03:06:12 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:39<00:33,  5.49it/s]16 03:06:12 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:39<00:33,  5.47it/s]16 03:06:12 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:40<00:32,  5.52it/s]16 03:06:12 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:40<00:32,  5.50it/s]16 03:06:12 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:40<00:33,  5.45it/s]16 03:06:13 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:40<00:32,  5.45it/s]16 03:06:13 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:40<00:32,  5.49it/s]16 03:06:13 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:41<00:32,  5.47it/s]16 03:06:13 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:41<00:32,  5.40it/s]16 03:06:13 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:41<00:32,  5.47it/s]16 03:06:14 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:41<00:31,  5.47it/s]16 03:06:14 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:41<00:31,  5.47it/s]16 03:06:14 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:41<00:31,  5.53it/s]16 03:06:14 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:42<00:30,  5.52it/s]16 03:06:14 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:42<00:30,  5.52it/s]16 03:06:15 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:42<00:31,  5.42it/s]16 03:06:15 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:42<00:30,  5.49it/s]16 03:06:15 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:42<00:30,  5.47it/s]16 03:06:15 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:43<00:30,  5.46it/s]16 03:06:15 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:43<00:28,  5.78it/s]16 03:06:15 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:43<00:28,  5.66it/s]16 03:06:16 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:43<00:28,  5.64it/s]16 03:06:16 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:43<00:28,  5.62it/s]16 03:06:16 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:43<00:28,  5.57it/s]16 03:06:16 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:44<00:28,  5.60it/s]16 03:06:16 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:44<00:28,  5.61it/s]16 03:06:16 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:44<00:28,  5.45it/s]16 03:06:17 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:44<00:29,  5.33it/s]16 03:06:17 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:44<00:28,  5.40it/s]16 03:06:17 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:45<00:28,  5.44it/s]16 03:06:17 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:45<00:28,  5.44it/s]16 03:06:17 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:45<00:27,  5.50it/s]16 03:06:18 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:45<00:27,  5.49it/s]16 03:06:18 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:45<00:27,  5.47it/s]16 03:06:18 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:45<00:27,  5.46it/s]16 03:06:18 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:46<00:27,  5.46it/s]16 03:06:18 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:46<00:27,  5.45it/s]16 03:06:18 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:46<00:27,  5.42it/s]16 03:06:19 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:46<00:26,  5.43it/s]16 03:06:19 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:46<00:26,  5.42it/s]16 03:06:19 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:47<00:26,  5.51it/s]16 03:06:19 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:47<00:26,  5.49it/s]16 03:06:19 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:47<00:26,  5.44it/s]16 03:06:20 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:47<00:25,  5.50it/s]16 03:06:20 Save the image 01236N.png

 64%|█████████████████████████▊              | 253/393 [00:47<00:26,  5.38it/s]16 03:06:20 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:47<00:25,  5.40it/s]16 03:06:20 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:48<00:25,  5.42it/s]16 03:06:20 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:48<00:25,  5.42it/s]16 03:06:21 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:48<00:24,  5.47it/s]16 03:06:21 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:48<00:24,  5.48it/s]16 03:06:21 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:48<00:24,  5.48it/s]16 03:06:21 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:49<00:24,  5.38it/s]16 03:06:21 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:49<00:24,  5.41it/s]16 03:06:21 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:49<00:24,  5.40it/s]16 03:06:22 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:49<00:23,  5.48it/s]16 03:06:22 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:49<00:22,  5.82it/s]16 03:06:22 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:49<00:22,  5.69it/s]16 03:06:22 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:50<00:22,  5.66it/s]16 03:06:22 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:50<00:22,  5.50it/s]16 03:06:23 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:50<00:22,  5.47it/s]16 03:06:23 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:50<00:22,  5.52it/s]16 03:06:23 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:50<00:22,  5.57it/s]16 03:06:23 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:51<00:21,  5.58it/s]16 03:06:23 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:51<00:21,  5.55it/s]16 03:06:23 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:51<00:21,  5.55it/s]16 03:06:24 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:51<00:21,  5.54it/s]16 03:06:24 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:51<00:21,  5.51it/s]16 03:06:24 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:51<00:21,  5.55it/s]16 03:06:24 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:52<00:20,  5.57it/s]16 03:06:24 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:52<00:20,  5.53it/s]16 03:06:24 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:52<00:20,  5.50it/s]16 03:06:25 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:52<00:20,  5.48it/s]16 03:06:25 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:52<00:20,  5.49it/s]16 03:06:25 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:53<00:20,  5.48it/s]16 03:06:25 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:53<00:20,  5.46it/s]16 03:06:25 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:53<00:19,  5.46it/s]16 03:06:26 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:53<00:19,  5.45it/s]16 03:06:26 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:53<00:19,  5.44it/s]16 03:06:26 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:53<00:19,  5.43it/s]16 03:06:26 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:54<00:19,  5.45it/s]16 03:06:26 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:54<00:19,  5.44it/s]16 03:06:27 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:54<00:19,  5.38it/s]16 03:06:27 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:54<00:18,  5.43it/s]16 03:06:27 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:54<00:19,  5.30it/s]16 03:06:27 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:55<00:18,  5.30it/s]16 03:06:27 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:55<00:18,  5.35it/s]16 03:06:27 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:55<00:18,  5.38it/s]16 03:06:28 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:55<00:18,  5.39it/s]16 03:06:28 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:55<00:17,  5.40it/s]16 03:06:28 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:55<00:17,  5.40it/s]16 03:06:28 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:56<00:17,  5.34it/s]16 03:06:28 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:56<00:17,  5.36it/s]16 03:06:29 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:56<00:17,  5.39it/s]16 03:06:29 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:56<00:16,  5.42it/s]16 03:06:29 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:56<00:16,  5.39it/s]16 03:06:29 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:57<00:16,  5.39it/s]16 03:06:29 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:57<00:16,  5.40it/s]16 03:06:29 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:57<00:16,  5.40it/s]16 03:06:30 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:57<00:15,  5.73it/s]16 03:06:30 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:57<00:15,  5.62it/s]16 03:06:30 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:57<00:14,  5.62it/s]16 03:06:30 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:58<00:14,  5.60it/s]16 03:06:30 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:58<00:14,  5.56it/s]16 03:06:31 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:58<00:14,  5.57it/s]16 03:06:31 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:58<00:14,  5.55it/s]16 03:06:31 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:58<00:14,  5.45it/s]16 03:06:31 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:59<00:14,  5.43it/s]16 03:06:31 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:59<00:14,  5.47it/s]16 03:06:31 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:59<00:13,  5.49it/s]16 03:06:32 Save the image 01301N.png

 81%|████████████████████████████████▎       | 318/393 [00:59<00:13,  5.47it/s]16 03:06:32 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:59<00:13,  5.52it/s]16 03:06:32 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [01:00<00:13,  5.39it/s]16 03:06:32 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [01:00<00:13,  5.29it/s]16 03:06:32 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [01:00<00:13,  5.37it/s]16 03:06:33 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [01:00<00:12,  5.42it/s]16 03:06:33 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [01:00<00:12,  5.40it/s]16 03:06:33 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [01:00<00:12,  5.42it/s]16 03:06:33 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [01:01<00:12,  5.50it/s]16 03:06:33 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [01:01<00:12,  5.43it/s]16 03:06:34 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [01:01<00:12,  5.37it/s]16 03:06:34 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [01:01<00:11,  5.36it/s]16 03:06:34 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [01:01<00:11,  5.37it/s]16 03:06:34 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [01:02<00:11,  5.38it/s]16 03:06:34 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [01:02<00:11,  5.31it/s]16 03:06:34 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [01:02<00:11,  5.33it/s]16 03:06:35 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [01:02<00:11,  5.35it/s]16 03:06:35 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [01:02<00:10,  5.37it/s]16 03:06:35 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [01:02<00:10,  5.39it/s]16 03:06:35 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [01:03<00:10,  5.41it/s]16 03:06:35 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [01:03<00:10,  5.39it/s]16 03:06:36 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [01:03<00:10,  5.33it/s]16 03:06:36 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [01:03<00:09,  5.35it/s]16 03:06:36 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [01:03<00:09,  5.34it/s]16 03:06:36 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [01:04<00:09,  5.32it/s]16 03:06:36 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [01:04<00:09,  5.35it/s]16 03:06:36 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [01:04<00:09,  5.35it/s]16 03:06:37 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [01:04<00:08,  5.35it/s]16 03:06:37 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [01:04<00:08,  5.32it/s]16 03:06:37 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [01:05<00:08,  5.31it/s]16 03:06:37 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [01:05<00:08,  5.27it/s]16 03:06:37 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [01:05<00:08,  5.33it/s]16 03:06:38 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [01:05<00:07,  5.70it/s]16 03:06:38 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [01:05<00:07,  5.55it/s]16 03:06:38 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [01:05<00:07,  5.53it/s]16 03:06:38 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [01:06<00:07,  5.49it/s]16 03:06:38 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [01:06<00:07,  5.44it/s]16 03:06:39 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [01:06<00:06,  5.49it/s]16 03:06:39 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [01:06<00:06,  5.48it/s]16 03:06:39 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [01:06<00:06,  5.43it/s]16 03:06:39 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [01:07<00:06,  5.33it/s]16 03:06:39 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [01:07<00:06,  5.37it/s]16 03:06:39 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [01:07<00:06,  5.36it/s]16 03:06:40 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [01:07<00:05,  5.35it/s]16 03:06:40 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [01:07<00:05,  5.39it/s]16 03:06:40 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [01:07<00:05,  5.37it/s]16 03:06:40 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [01:08<00:05,  5.39it/s]16 03:06:40 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [01:08<00:05,  5.38it/s]16 03:06:41 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [01:08<00:05,  5.37it/s]16 03:06:41 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [01:08<00:04,  5.41it/s]16 03:06:41 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [01:08<00:04,  5.36it/s]16 03:06:41 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [01:09<00:04,  5.36it/s]16 03:06:41 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [01:09<00:04,  5.34it/s]16 03:06:41 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [01:09<00:04,  5.35it/s]16 03:06:42 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [01:09<00:03,  5.69it/s]16 03:06:42 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [01:09<00:03,  5.58it/s]16 03:06:42 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [01:10<00:03,  5.55it/s]16 03:06:42 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [01:10<00:03,  5.47it/s]16 03:06:42 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [01:10<00:03,  5.46it/s]16 03:06:43 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [01:10<00:02,  5.47it/s]16 03:06:43 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [01:10<00:02,  5.51it/s]16 03:06:43 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [01:10<00:02,  5.49it/s]16 03:06:43 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [01:11<00:02,  5.43it/s]16 03:06:43 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [01:11<00:02,  5.41it/s]16 03:06:43 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [01:11<00:02,  5.43it/s]16 03:06:44 Save the image 01366N.png

 97%|██████████████████████████████████████▉ | 383/393 [01:11<00:01,  5.39it/s]16 03:06:44 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [01:11<00:01,  5.45it/s]16 03:06:44 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [01:12<00:01,  5.41it/s]16 03:06:44 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [01:12<00:01,  5.40it/s]16 03:06:44 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [01:12<00:01,  5.39it/s]16 03:06:45 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [01:12<00:00,  5.48it/s]16 03:06:45 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [01:12<00:00,  5.41it/s]16 03:06:45 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [01:12<00:00,  5.38it/s]16 03:06:45 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [01:13<00:00,  5.35it/s]16 03:06:45 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [01:13<00:00,  5.36it/s]16 03:06:46 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [01:13<00:00,  5.35it/s]
1 unlabeled	98.314%
2 car   	89.556%
3 person	75.183%
4 bike  	64.706%
5 curve 	47.586%
6 car_stop	30.836%
7 guardrail	6.209%
8 color_cone	51.353%
9 bump  	57.304%
----------     mean_IoU	57.894%	freq_IoU	96.792%	mean_pixel_acc	67.030%	pixel_acc	98.247%
16 03:06:46 Evaluation Elapsed Time: 73.52s

In [17]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E3")

!python eval.py -e 100 -d 0 --split val -p predictions_E3_val

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 03:07:12 using devices 0
16 03:07:12 Using E3: SegFormer-B2 with reliability-guided fusion
16 03:07:13 Using MLP Decoder
16 03:07:15 Load Model: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e3/checkpoint/epoch-100.pth
16 03:07:19 Load model, Time usage:
	IO: 4.246111869812012, initialize parameters: 0.04618048667907715
16 03:07:19 GPU 0 handle 392 data.
  0%|                                                  | 0/392 [00:00<?, ?it/s][ WARN:0@10.523] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 03:07:21 Save the image 00498D.png
  0%|                                          | 1/392 [00:01<10:37,  1.63s/it]16 03:07:21 Save the image 00499D.png
  1%|▏                                         | 2/392 [00:01<05:03,  1.28it/s]16 03:07:21 Save the image 00500D.png
  1%|▎                                         | 3/392 [00:01<03:17,  1.97it/s]16 03:07:22 Save the image 00501D.png
  1%|▍                                         | 4/392 [00:02<02:27,  2.62it/s]16 03:07:22 Save the image 00502D.png
  1%|▌                                         | 5/392 [00:02<01:59,  3.24it/s]16 03:07:22 Save the image 00503D.png
  2%|▋                                         | 6/392 [00:02<01:42,  3.78it/s]16 03:07:22 Save the image 00504D.png
  2%|▊                                         | 7/392 [00:02<01:31,  4.23it/s]16 03:07:22 Save the image 00505D.png
  2%|▊                                         | 8/392 [00:02<01:24,  4.53it/s]16 03:07:22 Save the image 00506D.png
  2%|▉                                         | 9/392 [00:03<01:19,  4.80it/s]16 03:07:23 Save the image 00507D.png
  3%|█                                        | 10/392 [00:03<01:16,  4.98it/s]16 03:07:23 Save the image 00508D.png
  3%|█▏                                       | 11/392 [00:03<01:15,  5.07it/s]16 03:07:23 Save the image 00509D.png
  3%|█▎                                       | 12/392 [00:03<01:13,  5.18it/s]16 03:07:23 Save the image 00510D.png
  3%|█▎                                       | 13/392 [00:03<01:12,  5.26it/s]16 03:07:23 Save the image 00511D.png
  4%|█▍                                       | 14/392 [00:04<01:11,  5.26it/s]16 03:07:24 Save the image 00512D.png
  4%|█▌                                       | 15/392 [00:04<01:11,  5.30it/s]16 03:07:24 Save the image 00513D.png
  4%|█▋                                       | 16/392 [00:04<01:10,  5.32it/s]16 03:07:24 Save the image 00514D.png
  4%|█▊                                       | 17/392 [00:04<01:09,  5.37it/s]16 03:07:24 Save the image 00515D.png
  5%|█▉                                       | 18/392 [00:04<01:09,  5.37it/s]16 03:07:24 Save the image 00516D.png
  5%|█▉                                       | 19/392 [00:04<01:08,  5.43it/s]16 03:07:25 Save the image 00517D.png
  5%|██                                       | 20/392 [00:05<01:08,  5.41it/s]16 03:07:25 Save the image 00518D.png
  5%|██▏                                      | 21/392 [00:05<01:08,  5.42it/s]16 03:07:25 Save the image 00519D.png
  6%|██▎                                      | 22/392 [00:05<01:08,  5.41it/s]16 03:07:25 Save the image 00520D.png
  6%|██▍                                      | 23/392 [00:05<01:08,  5.41it/s]16 03:07:25 Save the image 00521D.png
  6%|██▌                                      | 24/392 [00:05<01:07,  5.44it/s]16 03:07:25 Save the image 00522D.png
  6%|██▌                                      | 25/392 [00:06<01:07,  5.42it/s]16 03:07:26 Save the image 00523D.png
  7%|██▋                                      | 26/392 [00:06<01:06,  5.48it/s]16 03:07:26 Save the image 00524D.png
  7%|██▊                                      | 27/392 [00:06<01:06,  5.45it/s]16 03:07:26 Save the image 00525D.png
  7%|██▉                                      | 28/392 [00:06<01:06,  5.45it/s]16 03:07:26 Save the image 00526D.png
  7%|███                                      | 29/392 [00:06<01:06,  5.43it/s]16 03:07:26 Save the image 00527D.png
  8%|███▏                                     | 30/392 [00:06<01:06,  5.41it/s]16 03:07:27 Save the image 00528D.png
  8%|███▏                                     | 31/392 [00:07<01:07,  5.37it/s]16 03:07:27 Save the image 00529D.png
  8%|███▎                                     | 32/392 [00:07<01:06,  5.42it/s]16 03:07:27 Save the image 00530D.png
  8%|███▍                                     | 33/392 [00:07<01:06,  5.41it/s]16 03:07:27 Save the image 00531D.png
  9%|███▌                                     | 34/392 [00:07<01:06,  5.41it/s]16 03:07:27 Save the image 00532D.png
  9%|███▋                                     | 35/392 [00:07<01:05,  5.42it/s]16 03:07:27 Save the image 00533D.png
  9%|███▊                                     | 36/392 [00:08<01:05,  5.41it/s]16 03:07:28 Save the image 00534D.png
  9%|███▊                                     | 37/392 [00:08<01:05,  5.41it/s]16 03:07:28 Save the image 00535D.png
 10%|███▉                                     | 38/392 [00:08<01:05,  5.43it/s]16 03:07:28 Save the image 00536D.png
 10%|████                                     | 39/392 [00:08<01:06,  5.34it/s]16 03:07:28 Save the image 00537D.png
 10%|████▏                                    | 40/392 [00:08<01:05,  5.36it/s]16 03:07:28 Save the image 00538D.png
 10%|████▎                                    | 41/392 [00:09<01:05,  5.37it/s]16 03:07:29 Save the image 00539D.png
 11%|████▍                                    | 42/392 [00:09<01:04,  5.39it/s]16 03:07:29 Save the image 00540D.png
 11%|████▍                                    | 43/392 [00:09<01:05,  5.37it/s]16 03:07:29 Save the image 00541D.png
 11%|████▌                                    | 44/392 [00:09<01:04,  5.40it/s]16 03:07:29 Save the image 00542D.png
 11%|████▋                                    | 45/392 [00:09<01:04,  5.42it/s]16 03:07:29 Save the image 00543D.png
 12%|████▊                                    | 46/392 [00:09<01:04,  5.33it/s]16 03:07:30 Save the image 00544D.png
 12%|████▉                                    | 47/392 [00:10<01:03,  5.42it/s]16 03:07:30 Save the image 00545D.png
 12%|█████                                    | 48/392 [00:10<01:03,  5.38it/s]16 03:07:30 Save the image 00546D.png
 12%|█████▏                                   | 49/392 [00:10<01:04,  5.34it/s]16 03:07:30 Save the image 00547D.png
 13%|█████▏                                   | 50/392 [00:10<01:04,  5.34it/s]16 03:07:30 Save the image 00548D.png
 13%|█████▎                                   | 51/392 [00:10<01:03,  5.36it/s]16 03:07:30 Save the image 00549D.png
 13%|█████▍                                   | 52/392 [00:11<01:03,  5.37it/s]16 03:07:31 Save the image 00550D.png
 14%|█████▌                                   | 53/392 [00:11<01:03,  5.32it/s]16 03:07:31 Save the image 00551D.png
 14%|█████▋                                   | 54/392 [00:11<01:03,  5.30it/s]16 03:07:31 Save the image 00552D.png
 14%|█████▊                                   | 55/392 [00:11<01:03,  5.32it/s]16 03:07:31 Save the image 00553D.png
 14%|█████▊                                   | 56/392 [00:11<01:03,  5.31it/s]16 03:07:31 Save the image 00554D.png
 15%|█████▉                                   | 57/392 [00:12<01:03,  5.29it/s]16 03:07:32 Save the image 00555D.png

 15%|██████                                   | 58/392 [00:12<01:02,  5.34it/s]16 03:07:32 Save the image 00556D.png
 15%|██████▏                                  | 59/392 [00:12<01:01,  5.45it/s]16 03:07:32 Save the image 00557D.png
 15%|██████▎                                  | 60/392 [00:12<01:01,  5.43it/s]16 03:07:32 Save the image 00558D.png
 16%|██████▍                                  | 61/392 [00:12<01:01,  5.42it/s]16 03:07:32 Save the image 00559D.png
 16%|██████▍                                  | 62/392 [00:12<01:00,  5.41it/s]16 03:07:33 Save the image 00560D.png
 16%|██████▌                                  | 63/392 [00:13<01:00,  5.42it/s]16 03:07:33 Save the image 00561D.png
 16%|██████▋                                  | 64/392 [00:13<01:00,  5.42it/s]16 03:07:33 Save the image 00562D.png
 17%|██████▊                                  | 65/392 [00:13<01:00,  5.42it/s]16 03:07:33 Save the image 00563D.png
 17%|██████▉                                  | 66/392 [00:13<01:00,  5.42it/s]16 03:07:33 Save the image 00564D.png
 17%|███████                                  | 67/392 [00:13<01:00,  5.39it/s]16 03:07:33 Save the image 00565D.png
 17%|███████                                  | 68/392 [00:14<00:59,  5.41it/s]16 03:07:34 Save the image 00566D.png
 18%|███████▏                                 | 69/392 [00:14<00:59,  5.40it/s]16 03:07:34 Save the image 00567D.png
 18%|███████▎                                 | 70/392 [00:14<00:59,  5.40it/s]16 03:07:34 Save the image 00568D.png
 18%|███████▍                                 | 71/392 [00:14<00:59,  5.43it/s]16 03:07:34 Save the image 00569D.png
 18%|███████▌                                 | 72/392 [00:14<00:59,  5.42it/s]16 03:07:34 Save the image 00570D.png
 19%|███████▋                                 | 73/392 [00:14<00:58,  5.42it/s]16 03:07:35 Save the image 00571D.png
 19%|███████▋                                 | 74/392 [00:15<00:59,  5.33it/s]16 03:07:35 Save the image 00572D.png
 19%|███████▊                                 | 75/392 [00:15<00:59,  5.35it/s]16 03:07:35 Save the image 00573D.png
 19%|███████▉                                 | 76/392 [00:15<00:58,  5.37it/s]16 03:07:35 Save the image 00574D.png
 20%|████████                                 | 77/392 [00:15<00:58,  5.37it/s]16 03:07:35 Save the image 00575D.png
 20%|████████▏                                | 78/392 [00:15<00:58,  5.38it/s]16 03:07:35 Save the image 00576D.png
 20%|████████▎                                | 79/392 [00:16<00:58,  5.39it/s]16 03:07:36 Save the image 00577D.png
 20%|████████▎                                | 80/392 [00:16<00:57,  5.41it/s]16 03:07:36 Save the image 00578D.png
 21%|████████▍                                | 81/392 [00:16<00:57,  5.44it/s]16 03:07:36 Save the image 00579D.png
 21%|████████▌                                | 82/392 [00:16<00:57,  5.41it/s]16 03:07:36 Save the image 00580D.png
 21%|████████▋                                | 83/392 [00:16<00:57,  5.42it/s]16 03:07:36 Save the image 00581D.png
 21%|████████▊                                | 84/392 [00:16<00:57,  5.37it/s]16 03:07:37 Save the image 00582D.png
 22%|████████▉                                | 85/392 [00:17<00:55,  5.53it/s]16 03:07:37 Save the image 00583D.png
 22%|████████▉                                | 86/392 [00:17<00:55,  5.48it/s]16 03:07:37 Save the image 00584D.png
 22%|█████████                                | 87/392 [00:17<00:55,  5.48it/s]16 03:07:37 Save the image 00585D.png
 22%|█████████▏                               | 88/392 [00:17<00:56,  5.37it/s]16 03:07:37 Save the image 00586D.png
 23%|█████████▎                               | 89/392 [00:17<00:56,  5.36it/s]16 03:07:38 Save the image 00587D.png
 23%|█████████▍                               | 90/392 [00:18<00:56,  5.38it/s]16 03:07:38 Save the image 00588D.png
 23%|█████████▌                               | 91/392 [00:18<00:56,  5.32it/s]16 03:07:38 Save the image 00589D.png
 23%|█████████▌                               | 92/392 [00:18<00:52,  5.73it/s]16 03:07:38 Save the image 00590D.png
 24%|█████████▋                               | 93/392 [00:18<00:53,  5.60it/s]16 03:07:38 Save the image 00591D.png
 24%|█████████▊                               | 94/392 [00:18<00:53,  5.56it/s]16 03:07:38 Save the image 00592D.png
 24%|█████████▉                               | 95/392 [00:18<00:53,  5.53it/s]16 03:07:39 Save the image 00593D.png
 24%|██████████                               | 96/392 [00:19<00:53,  5.48it/s]16 03:07:39 Save the image 00594D.png
 25%|██████████▏                              | 97/392 [00:19<00:53,  5.52it/s]16 03:07:39 Save the image 00595D.png
 25%|██████████▎                              | 98/392 [00:19<00:52,  5.55it/s]16 03:07:39 Save the image 00596D.png
 25%|██████████▎                              | 99/392 [00:19<00:53,  5.51it/s]16 03:07:39 Save the image 00597D.png
 26%|██████████▏                             | 100/392 [00:19<00:53,  5.47it/s]16 03:07:39 Save the image 00598D.png
 26%|██████████▎                             | 101/392 [00:20<00:52,  5.50it/s]16 03:07:40 Save the image 00599D.png
 26%|██████████▍                             | 102/392 [00:20<00:52,  5.50it/s]16 03:07:40 Save the image 00600D.png
 26%|██████████▌                             | 103/392 [00:20<00:52,  5.47it/s]16 03:07:40 Save the image 00601D.png
 27%|██████████▌                             | 104/392 [00:20<00:52,  5.52it/s]16 03:07:40 Save the image 00602D.png
 27%|██████████▋                             | 105/392 [00:20<00:52,  5.52it/s]16 03:07:40 Save the image 00603D.png
 27%|██████████▊                             | 106/392 [00:20<00:52,  5.48it/s]16 03:07:41 Save the image 00604D.png
 27%|██████████▉                             | 107/392 [00:21<00:52,  5.46it/s]16 03:07:41 Save the image 00605D.png
 28%|███████████                             | 108/392 [00:21<00:52,  5.45it/s]16 03:07:41 Save the image 00606D.png
 28%|███████████                             | 109/392 [00:21<00:51,  5.54it/s]16 03:07:41 Save the image 00607D.png
 28%|███████████▏                            | 110/392 [00:21<00:51,  5.48it/s]16 03:07:41 Save the image 00608D.png
 28%|███████████▎                            | 111/392 [00:21<00:51,  5.50it/s]16 03:07:41 Save the image 00609D.png
 29%|███████████▍                            | 112/392 [00:22<00:51,  5.47it/s]16 03:07:42 Save the image 00610D.png
 29%|███████████▌                            | 113/392 [00:22<00:51,  5.45it/s]16 03:07:42 Save the image 00611D.png
 29%|███████████▋                            | 114/392 [00:22<00:51,  5.42it/s]16 03:07:42 Save the image 00612D.png
 29%|███████████▋                            | 115/392 [00:22<00:51,  5.38it/s]16 03:07:42 Save the image 00613D.png
 30%|███████████▊                            | 116/392 [00:22<00:51,  5.40it/s]16 03:07:42 Save the image 00614D.png
 30%|███████████▉                            | 117/392 [00:23<00:50,  5.40it/s]16 03:07:43 Save the image 00615D.png
 30%|████████████                            | 118/392 [00:23<00:50,  5.45it/s]16 03:07:43 Save the image 00616D.png
 30%|████████████▏                           | 119/392 [00:23<00:50,  5.37it/s]16 03:07:43 Save the image 00617D.png
 31%|████████████▏                           | 120/392 [00:23<00:50,  5.44it/s]16 03:07:43 Save the image 00618D.png
 31%|████████████▎                           | 121/392 [00:23<00:50,  5.42it/s]16 03:07:43 Save the image 00619D.png
 31%|████████████▍                           | 122/392 [00:23<00:49,  5.42it/s]16 03:07:44 Save the image 00620D.png

 31%|████████████▌                           | 123/392 [00:24<00:49,  5.43it/s]16 03:07:44 Save the image 00621D.png
 32%|████████████▋                           | 124/392 [00:24<00:49,  5.41it/s]16 03:07:44 Save the image 00622D.png
 32%|████████████▊                           | 125/392 [00:24<00:49,  5.44it/s]16 03:07:44 Save the image 00623D.png
 32%|████████████▊                           | 126/392 [00:24<00:49,  5.42it/s]16 03:07:44 Save the image 00624D.png
 32%|████████████▉                           | 127/392 [00:24<00:48,  5.43it/s]16 03:07:44 Save the image 00625D.png
 33%|█████████████                           | 128/392 [00:25<00:48,  5.42it/s]16 03:07:45 Save the image 00626D.png
 33%|█████████████▏                          | 129/392 [00:25<00:48,  5.42it/s]16 03:07:45 Save the image 00627D.png
 33%|█████████████▎                          | 130/392 [00:25<00:48,  5.42it/s]16 03:07:45 Save the image 00628D.png
 33%|█████████████▎                          | 131/392 [00:25<00:48,  5.42it/s]16 03:07:45 Save the image 00629D.png
 34%|█████████████▍                          | 132/392 [00:25<00:48,  5.42it/s]16 03:07:45 Save the image 00630D.png
 34%|█████████████▌                          | 133/392 [00:25<00:47,  5.41it/s]16 03:07:46 Save the image 00631D.png
 34%|█████████████▋                          | 134/392 [00:26<00:47,  5.42it/s]16 03:07:46 Save the image 00632D.png
 34%|█████████████▊                          | 135/392 [00:26<00:47,  5.40it/s]16 03:07:46 Save the image 00633D.png
 35%|█████████████▉                          | 136/392 [00:26<00:47,  5.41it/s]16 03:07:46 Save the image 00634D.png
 35%|█████████████▉                          | 137/392 [00:26<00:46,  5.44it/s]16 03:07:46 Save the image 00635D.png
 35%|██████████████                          | 138/392 [00:26<00:46,  5.42it/s]16 03:07:46 Save the image 00636D.png
 35%|██████████████▏                         | 139/392 [00:27<00:46,  5.40it/s]16 03:07:47 Save the image 00637D.png
 36%|██████████████▎                         | 140/392 [00:27<00:46,  5.40it/s]16 03:07:47 Save the image 00638D.png
 36%|██████████████▍                         | 141/392 [00:27<00:46,  5.41it/s]16 03:07:47 Save the image 00639D.png
 36%|██████████████▍                         | 142/392 [00:27<00:46,  5.40it/s]16 03:07:47 Save the image 00640D.png
 36%|██████████████▌                         | 143/392 [00:27<00:46,  5.40it/s]16 03:07:47 Save the image 00641D.png
 37%|██████████████▋                         | 144/392 [00:28<00:45,  5.43it/s]16 03:07:48 Save the image 00642D.png
 37%|██████████████▊                         | 145/392 [00:28<00:45,  5.42it/s]16 03:07:48 Save the image 00643D.png
 37%|██████████████▉                         | 146/392 [00:28<00:45,  5.41it/s]16 03:07:48 Save the image 00644D.png
 38%|███████████████                         | 147/392 [00:28<00:45,  5.40it/s]16 03:07:48 Save the image 00645D.png
 38%|███████████████                         | 148/392 [00:28<00:45,  5.40it/s]16 03:07:48 Save the image 00646D.png
 38%|███████████████▏                        | 149/392 [00:28<00:44,  5.40it/s]16 03:07:49 Save the image 00647D.png
 38%|███████████████▎                        | 150/392 [00:29<00:44,  5.40it/s]16 03:07:49 Save the image 00648D.png
 39%|███████████████▍                        | 151/392 [00:29<00:44,  5.43it/s]16 03:07:49 Save the image 00649D.png
 39%|███████████████▌                        | 152/392 [00:29<00:44,  5.42it/s]16 03:07:49 Save the image 00650D.png
 39%|███████████████▌                        | 153/392 [00:29<00:44,  5.41it/s]16 03:07:49 Save the image 00651D.png
 39%|███████████████▋                        | 154/392 [00:29<00:44,  5.40it/s]16 03:07:49 Save the image 00652D.png
 40%|███████████████▊                        | 155/392 [00:30<00:43,  5.40it/s]16 03:07:50 Save the image 00653D.png
 40%|███████████████▉                        | 156/392 [00:30<00:43,  5.39it/s]16 03:07:50 Save the image 00654D.png
 40%|████████████████                        | 157/392 [00:30<00:43,  5.40it/s]16 03:07:50 Save the image 00655D.png
 40%|████████████████                        | 158/392 [00:30<00:43,  5.42it/s]16 03:07:50 Save the image 00656D.png
 41%|████████████████▏                       | 159/392 [00:30<00:43,  5.40it/s]16 03:07:50 Save the image 00657D.png
 41%|████████████████▎                       | 160/392 [00:30<00:42,  5.42it/s]16 03:07:51 Save the image 00658D.png
 41%|████████████████▍                       | 161/392 [00:31<00:42,  5.43it/s]16 03:07:51 Save the image 00659D.png
 41%|████████████████▌                       | 162/392 [00:31<00:42,  5.42it/s]16 03:07:51 Save the image 00660D.png
 42%|████████████████▋                       | 163/392 [00:31<00:42,  5.40it/s]16 03:07:51 Save the image 00661D.png
 42%|████████████████▋                       | 164/392 [00:31<00:41,  5.43it/s]16 03:07:51 Save the image 00662D.png
 42%|████████████████▊                       | 165/392 [00:31<00:41,  5.41it/s]16 03:07:51 Save the image 00663D.png
 42%|████████████████▉                       | 166/392 [00:32<00:42,  5.38it/s]16 03:07:52 Save the image 00664D.png
 43%|█████████████████                       | 167/392 [00:32<00:41,  5.42it/s]16 03:07:52 Save the image 00665D.png
 43%|█████████████████▏                      | 168/392 [00:32<00:41,  5.41it/s]16 03:07:52 Save the image 00666D.png
 43%|█████████████████▏                      | 169/392 [00:32<00:41,  5.42it/s]16 03:07:52 Save the image 00667D.png
 43%|█████████████████▎                      | 170/392 [00:32<00:40,  5.46it/s]16 03:07:52 Save the image 00668D.png
 44%|█████████████████▍                      | 171/392 [00:32<00:40,  5.43it/s]16 03:07:53 Save the image 00669D.png
 44%|█████████████████▌                      | 172/392 [00:33<00:40,  5.49it/s]16 03:07:53 Save the image 00670D.png
 44%|█████████████████▋                      | 173/392 [00:33<00:40,  5.44it/s]16 03:07:53 Save the image 00671D.png
 44%|█████████████████▊                      | 174/392 [00:33<00:40,  5.42it/s]16 03:07:53 Save the image 00672D.png
 45%|█████████████████▊                      | 175/392 [00:33<00:40,  5.40it/s]16 03:07:53 Save the image 00673D.png
 45%|█████████████████▉                      | 176/392 [00:33<00:40,  5.40it/s]16 03:07:54 Save the image 00674D.png
 45%|██████████████████                      | 177/392 [00:34<00:39,  5.38it/s]16 03:07:54 Save the image 00675D.png
 45%|██████████████████▏                     | 178/392 [00:34<00:39,  5.39it/s]16 03:07:54 Save the image 00676D.png
 46%|██████████████████▎                     | 179/392 [00:34<00:39,  5.41it/s]16 03:07:54 Save the image 00677D.png
 46%|██████████████████▎                     | 180/392 [00:34<00:39,  5.38it/s]16 03:07:54 Save the image 01377D.png
 46%|██████████████████▍                     | 181/392 [00:34<00:39,  5.40it/s]16 03:07:54 Save the image 01378D.png
 46%|██████████████████▌                     | 182/392 [00:35<00:38,  5.41it/s]16 03:07:55 Save the image 01379D.png
 47%|██████████████████▋                     | 183/392 [00:35<00:38,  5.40it/s]16 03:07:55 Save the image 01380D.png
 47%|██████████████████▊                     | 184/392 [00:35<00:38,  5.41it/s]16 03:07:55 Save the image 01381D.png
 47%|██████████████████▉                     | 185/392 [00:35<00:38,  5.41it/s]16 03:07:55 Save the image 01382D.png
 47%|██████████████████▉                     | 186/392 [00:35<00:38,  5.42it/s]16 03:07:55 Save the image 01383D.png
 48%|███████████████████                     | 187/392 [00:35<00:38,  5.39it/s]16 03:07:56 Save the image 01384D.png

 48%|███████████████████▏                    | 188/392 [00:36<00:37,  5.38it/s]16 03:07:56 Save the image 01385D.png
 48%|███████████████████▎                    | 189/392 [00:36<00:37,  5.37it/s]16 03:07:56 Save the image 01386D.png
 48%|███████████████████▍                    | 190/392 [00:36<00:37,  5.37it/s]16 03:07:56 Save the image 01387D.png
 49%|███████████████████▍                    | 191/392 [00:36<00:37,  5.34it/s]16 03:07:56 Save the image 01388D.png
 49%|███████████████████▌                    | 192/392 [00:36<00:37,  5.36it/s]16 03:07:56 Save the image 01389D.png
 49%|███████████████████▋                    | 193/392 [00:37<00:36,  5.39it/s]16 03:07:57 Save the image 01390D.png
 49%|███████████████████▊                    | 194/392 [00:37<00:36,  5.39it/s]16 03:07:57 Save the image 01391D.png
 50%|███████████████████▉                    | 195/392 [00:37<00:36,  5.42it/s]16 03:07:57 Save the image 01392D.png
 50%|████████████████████                    | 196/392 [00:37<00:36,  5.43it/s]16 03:07:57 Save the image 01393D.png
 50%|████████████████████                    | 197/392 [00:37<00:35,  5.44it/s]16 03:07:57 Save the image 01394D.png
 51%|████████████████████▏                   | 198/392 [00:37<00:35,  5.49it/s]16 03:07:58 Save the image 01395D.png
 51%|████████████████████▎                   | 199/392 [00:38<00:35,  5.47it/s]16 03:07:58 Save the image 01396D.png
 51%|████████████████████▍                   | 200/392 [00:38<00:35,  5.47it/s]16 03:07:58 Save the image 01397D.png
 51%|████████████████████▌                   | 201/392 [00:38<00:35,  5.43it/s]16 03:07:58 Save the image 01398D.png
 52%|████████████████████▌                   | 202/392 [00:38<00:35,  5.41it/s]16 03:07:58 Save the image 01399D.png
 52%|████████████████████▋                   | 203/392 [00:38<00:34,  5.41it/s]16 03:07:58 Save the image 01400D.png
 52%|████████████████████▊                   | 204/392 [00:39<00:34,  5.41it/s]16 03:07:59 Save the image 01401D.png
 52%|████████████████████▉                   | 205/392 [00:39<00:34,  5.41it/s]16 03:07:59 Save the image 01002N.png
 53%|█████████████████████                   | 206/392 [00:39<00:34,  5.43it/s]16 03:07:59 Save the image 01003N.png
 53%|█████████████████████                   | 207/392 [00:39<00:33,  5.46it/s]16 03:07:59 Save the image 01004N.png
 53%|█████████████████████▏                  | 208/392 [00:39<00:33,  5.45it/s]16 03:07:59 Save the image 01005N.png
 53%|█████████████████████▎                  | 209/392 [00:40<00:33,  5.44it/s]16 03:08:00 Save the image 01006N.png
 54%|█████████████████████▍                  | 210/392 [00:40<00:33,  5.44it/s]16 03:08:00 Save the image 01007N.png
 54%|█████████████████████▌                  | 211/392 [00:40<00:33,  5.44it/s]16 03:08:00 Save the image 01008N.png
 54%|█████████████████████▋                  | 212/392 [00:40<00:31,  5.74it/s]16 03:08:00 Save the image 01009N.png
 54%|█████████████████████▋                  | 213/392 [00:40<00:31,  5.64it/s]16 03:08:00 Save the image 01010N.png
 55%|█████████████████████▊                  | 214/392 [00:40<00:31,  5.63it/s]16 03:08:00 Save the image 01011N.png
 55%|█████████████████████▉                  | 215/392 [00:41<00:32,  5.52it/s]16 03:08:01 Save the image 01012N.png
 55%|██████████████████████                  | 216/392 [00:41<00:31,  5.51it/s]16 03:08:01 Save the image 01013N.png
 55%|██████████████████████▏                 | 217/392 [00:41<00:31,  5.48it/s]16 03:08:01 Save the image 01014N.png
 56%|██████████████████████▏                 | 218/392 [00:41<00:31,  5.52it/s]16 03:08:01 Save the image 01015N.png
 56%|██████████████████████▎                 | 219/392 [00:41<00:30,  5.70it/s]16 03:08:01 Save the image 01016N.png
 56%|██████████████████████▍                 | 220/392 [00:41<00:30,  5.61it/s]16 03:08:02 Save the image 01017N.png
 56%|██████████████████████▌                 | 221/392 [00:42<00:30,  5.58it/s]16 03:08:02 Save the image 01018N.png
 57%|██████████████████████▋                 | 222/392 [00:42<00:30,  5.55it/s]16 03:08:02 Save the image 01019N.png
 57%|██████████████████████▊                 | 223/392 [00:42<00:30,  5.50it/s]16 03:08:02 Save the image 01020N.png
 57%|██████████████████████▊                 | 224/392 [00:42<00:30,  5.52it/s]16 03:08:02 Save the image 01021N.png
 57%|██████████████████████▉                 | 225/392 [00:42<00:30,  5.55it/s]16 03:08:02 Save the image 01022N.png
 58%|███████████████████████                 | 226/392 [00:43<00:29,  5.58it/s]16 03:08:03 Save the image 01023N.png
 58%|███████████████████████▏                | 227/392 [00:43<00:29,  5.53it/s]16 03:08:03 Save the image 01024N.png
 58%|███████████████████████▎                | 228/392 [00:43<00:29,  5.49it/s]16 03:08:03 Save the image 01025N.png
 58%|███████████████████████▎                | 229/392 [00:43<00:29,  5.52it/s]16 03:08:03 Save the image 01026N.png
 59%|███████████████████████▍                | 230/392 [00:43<00:29,  5.47it/s]16 03:08:03 Save the image 01027N.png
 59%|███████████████████████▌                | 231/392 [00:43<00:29,  5.47it/s]16 03:08:04 Save the image 01028N.png
 59%|███████████████████████▋                | 232/392 [00:44<00:29,  5.46it/s]16 03:08:04 Save the image 01029N.png
 59%|███████████████████████▊                | 233/392 [00:44<00:29,  5.46it/s]16 03:08:04 Save the image 01030N.png
 60%|███████████████████████▉                | 234/392 [00:44<00:28,  5.47it/s]16 03:08:04 Save the image 01031N.png
 60%|███████████████████████▉                | 235/392 [00:44<00:28,  5.47it/s]16 03:08:04 Save the image 01032N.png
 60%|████████████████████████                | 236/392 [00:44<00:28,  5.44it/s]16 03:08:04 Save the image 01033N.png
 60%|████████████████████████▏               | 237/392 [00:45<00:28,  5.43it/s]16 03:08:05 Save the image 01034N.png
 61%|████████████████████████▎               | 238/392 [00:45<00:28,  5.43it/s]16 03:08:05 Save the image 01035N.png
 61%|████████████████████████▍               | 239/392 [00:45<00:28,  5.41it/s]16 03:08:05 Save the image 01036N.png
 61%|████████████████████████▍               | 240/392 [00:45<00:28,  5.43it/s]16 03:08:05 Save the image 01037N.png
 61%|████████████████████████▌               | 241/392 [00:45<00:27,  5.43it/s]16 03:08:05 Save the image 01038N.png
 62%|████████████████████████▋               | 242/392 [00:46<00:27,  5.42it/s]16 03:08:06 Save the image 01039N.png
 62%|████████████████████████▊               | 243/392 [00:46<00:27,  5.36it/s]16 03:08:06 Save the image 01040N.png
 62%|████████████████████████▉               | 244/392 [00:46<00:27,  5.40it/s]16 03:08:06 Save the image 01041N.png
 62%|█████████████████████████               | 245/392 [00:46<00:27,  5.40it/s]16 03:08:06 Save the image 01042N.png
 63%|█████████████████████████               | 246/392 [00:46<00:27,  5.40it/s]16 03:08:06 Save the image 01043N.png
 63%|█████████████████████████▏              | 247/392 [00:46<00:26,  5.40it/s]16 03:08:07 Save the image 01044N.png
 63%|█████████████████████████▎              | 248/392 [00:47<00:26,  5.40it/s]16 03:08:07 Save the image 01045N.png
 64%|█████████████████████████▍              | 249/392 [00:47<00:26,  5.40it/s]16 03:08:07 Save the image 01046N.png
 64%|█████████████████████████▌              | 250/392 [00:47<00:26,  5.43it/s]16 03:08:07 Save the image 01047N.png
 64%|█████████████████████████▌              | 251/392 [00:47<00:26,  5.42it/s]16 03:08:07 Save the image 01048N.png
 64%|█████████████████████████▋              | 252/392 [00:47<00:25,  5.40it/s]16 03:08:07 Save the image 01049N.png

 65%|█████████████████████████▊              | 253/392 [00:48<00:25,  5.40it/s]16 03:08:08 Save the image 01050N.png
 65%|█████████████████████████▉              | 254/392 [00:48<00:25,  5.41it/s]16 03:08:08 Save the image 01051N.png
 65%|██████████████████████████              | 255/392 [00:48<00:25,  5.40it/s]16 03:08:08 Save the image 01052N.png
 65%|██████████████████████████              | 256/392 [00:48<00:25,  5.40it/s]16 03:08:08 Save the image 01053N.png
 66%|██████████████████████████▏             | 257/392 [00:48<00:24,  5.42it/s]16 03:08:08 Save the image 01054N.png
 66%|██████████████████████████▎             | 258/392 [00:48<00:24,  5.41it/s]16 03:08:09 Save the image 01055N.png
 66%|██████████████████████████▍             | 259/392 [00:49<00:24,  5.40it/s]16 03:08:09 Save the image 01056N.png
 66%|██████████████████████████▌             | 260/392 [00:49<00:24,  5.41it/s]16 03:08:09 Save the image 01057N.png
 67%|██████████████████████████▋             | 261/392 [00:49<00:24,  5.42it/s]16 03:08:09 Save the image 01058N.png
 67%|██████████████████████████▋             | 262/392 [00:49<00:23,  5.42it/s]16 03:08:09 Save the image 01059N.png
 67%|██████████████████████████▊             | 263/392 [00:49<00:23,  5.42it/s]16 03:08:09 Save the image 01060N.png
 67%|██████████████████████████▉             | 264/392 [00:50<00:23,  5.43it/s]16 03:08:10 Save the image 01061N.png
 68%|███████████████████████████             | 265/392 [00:50<00:23,  5.42it/s]16 03:08:10 Save the image 01062N.png
 68%|███████████████████████████▏            | 266/392 [00:50<00:23,  5.41it/s]16 03:08:10 Save the image 01063N.png
 68%|███████████████████████████▏            | 267/392 [00:50<00:23,  5.42it/s]16 03:08:10 Save the image 01064N.png
 68%|███████████████████████████▎            | 268/392 [00:50<00:22,  5.42it/s]16 03:08:10 Save the image 01065N.png
 69%|███████████████████████████▍            | 269/392 [00:50<00:22,  5.43it/s]16 03:08:11 Save the image 01066N.png
 69%|███████████████████████████▌            | 270/392 [00:51<00:22,  5.44it/s]16 03:08:11 Save the image 01067N.png
 69%|███████████████████████████▋            | 271/392 [00:51<00:22,  5.44it/s]16 03:08:11 Save the image 01068N.png
 69%|███████████████████████████▊            | 272/392 [00:51<00:22,  5.36it/s]16 03:08:11 Save the image 01069N.png
 70%|███████████████████████████▊            | 273/392 [00:51<00:21,  5.44it/s]16 03:08:11 Save the image 01070N.png
 70%|███████████████████████████▉            | 274/392 [00:51<00:21,  5.44it/s]16 03:08:11 Save the image 01071N.png
 70%|████████████████████████████            | 275/392 [00:52<00:21,  5.44it/s]16 03:08:12 Save the image 01072N.png
 70%|████████████████████████████▏           | 276/392 [00:52<00:21,  5.42it/s]16 03:08:12 Save the image 01073N.png
 71%|████████████████████████████▎           | 277/392 [00:52<00:21,  5.43it/s]16 03:08:12 Save the image 01074N.png
 71%|████████████████████████████▎           | 278/392 [00:52<00:20,  5.43it/s]16 03:08:12 Save the image 01075N.png
 71%|████████████████████████████▍           | 279/392 [00:52<00:20,  5.42it/s]16 03:08:12 Save the image 01076N.png
 71%|████████████████████████████▌           | 280/392 [00:53<00:20,  5.41it/s]16 03:08:13 Save the image 01077N.png
 72%|████████████████████████████▋           | 281/392 [00:53<00:20,  5.41it/s]16 03:08:13 Save the image 01078N.png
 72%|████████████████████████████▊           | 282/392 [00:53<00:20,  5.42it/s]16 03:08:13 Save the image 01079N.png
 72%|████████████████████████████▉           | 283/392 [00:53<00:20,  5.45it/s]16 03:08:13 Save the image 01080N.png
 72%|████████████████████████████▉           | 284/392 [00:53<00:19,  5.45it/s]16 03:08:13 Save the image 01081N.png
 73%|█████████████████████████████           | 285/392 [00:53<00:19,  5.45it/s]16 03:08:14 Save the image 01082N.png
 73%|█████████████████████████████▏          | 286/392 [00:54<00:19,  5.44it/s]16 03:08:14 Save the image 01083N.png
 73%|█████████████████████████████▎          | 287/392 [00:54<00:19,  5.44it/s]16 03:08:14 Save the image 01084N.png
 73%|█████████████████████████████▍          | 288/392 [00:54<00:19,  5.44it/s]16 03:08:14 Save the image 01085N.png
 74%|█████████████████████████████▍          | 289/392 [00:54<00:18,  5.44it/s]16 03:08:14 Save the image 01086N.png
 74%|█████████████████████████████▌          | 290/392 [00:54<00:17,  5.74it/s]16 03:08:14 Save the image 01087N.png
 74%|█████████████████████████████▋          | 291/392 [00:55<00:17,  5.62it/s]16 03:08:15 Save the image 01088N.png
 74%|█████████████████████████████▊          | 292/392 [00:55<00:17,  5.57it/s]16 03:08:15 Save the image 01089N.png
 75%|█████████████████████████████▉          | 293/392 [00:55<00:17,  5.54it/s]16 03:08:15 Save the image 01090N.png
 75%|██████████████████████████████          | 294/392 [00:55<00:17,  5.50it/s]16 03:08:15 Save the image 01091N.png
 75%|██████████████████████████████          | 295/392 [00:55<00:17,  5.48it/s]16 03:08:15 Save the image 01092N.png
 76%|██████████████████████████████▏         | 296/392 [00:55<00:17,  5.54it/s]16 03:08:15 Save the image 01093N.png
 76%|██████████████████████████████▎         | 297/392 [00:56<00:16,  5.64it/s]16 03:08:16 Save the image 01094N.png
 76%|██████████████████████████████▍         | 298/392 [00:56<00:17,  5.50it/s]16 03:08:16 Save the image 01095N.png
 76%|██████████████████████████████▌         | 299/392 [00:56<00:16,  5.56it/s]16 03:08:16 Save the image 01096N.png
 77%|██████████████████████████████▌         | 300/392 [00:56<00:16,  5.53it/s]16 03:08:16 Save the image 01097N.png
 77%|██████████████████████████████▋         | 301/392 [00:56<00:16,  5.48it/s]16 03:08:16 Save the image 01098N.png
 77%|██████████████████████████████▊         | 302/392 [00:57<00:16,  5.51it/s]16 03:08:17 Save the image 01099N.png
 77%|██████████████████████████████▉         | 303/392 [00:57<00:16,  5.54it/s]16 03:08:17 Save the image 01100N.png
 78%|███████████████████████████████         | 304/392 [00:57<00:16,  5.49it/s]16 03:08:17 Save the image 01101N.png
 78%|███████████████████████████████         | 305/392 [00:57<00:15,  5.46it/s]16 03:08:17 Save the image 01102N.png
 78%|███████████████████████████████▏        | 306/392 [00:57<00:15,  5.48it/s]16 03:08:17 Save the image 01103N.png
 78%|███████████████████████████████▎        | 307/392 [00:57<00:15,  5.49it/s]16 03:08:18 Save the image 01104N.png
 79%|███████████████████████████████▍        | 308/392 [00:58<00:15,  5.45it/s]16 03:08:18 Save the image 01105N.png
 79%|███████████████████████████████▌        | 309/392 [00:58<00:15,  5.52it/s]16 03:08:18 Save the image 01106N.png
 79%|███████████████████████████████▋        | 310/392 [00:58<00:14,  5.50it/s]16 03:08:18 Save the image 01107N.png
 79%|███████████████████████████████▋        | 311/392 [00:58<00:14,  5.49it/s]16 03:08:18 Save the image 01108N.png
 80%|███████████████████████████████▊        | 312/392 [00:58<00:14,  5.48it/s]16 03:08:18 Save the image 01109N.png
 80%|███████████████████████████████▉        | 313/392 [00:59<00:14,  5.50it/s]16 03:08:19 Save the image 01110N.png
 80%|████████████████████████████████        | 314/392 [00:59<00:14,  5.49it/s]16 03:08:19 Save the image 01111N.png
 80%|████████████████████████████████▏       | 315/392 [00:59<00:14,  5.46it/s]16 03:08:19 Save the image 01112N.png
 81%|████████████████████████████████▏       | 316/392 [00:59<00:13,  5.45it/s]16 03:08:19 Save the image 01113N.png
 81%|████████████████████████████████▎       | 317/392 [00:59<00:13,  5.45it/s]16 03:08:19 Save the image 01114N.png

 81%|████████████████████████████████▍       | 318/392 [00:59<00:13,  5.45it/s]16 03:08:20 Save the image 01115N.png
 81%|████████████████████████████████▌       | 319/392 [01:00<00:13,  5.45it/s]16 03:08:20 Save the image 01116N.png
 82%|████████████████████████████████▋       | 320/392 [01:00<00:13,  5.46it/s]16 03:08:20 Save the image 01117N.png
 82%|████████████████████████████████▊       | 321/392 [01:00<00:12,  5.48it/s]16 03:08:20 Save the image 01118N.png
 82%|████████████████████████████████▊       | 322/392 [01:00<00:12,  5.47it/s]16 03:08:20 Save the image 01119N.png
 82%|████████████████████████████████▉       | 323/392 [01:00<00:12,  5.46it/s]16 03:08:20 Save the image 01120N.png
 83%|█████████████████████████████████       | 324/392 [01:01<00:12,  5.47it/s]16 03:08:21 Save the image 01121N.png
 83%|█████████████████████████████████▏      | 325/392 [01:01<00:12,  5.45it/s]16 03:08:21 Save the image 01122N.png
 83%|█████████████████████████████████▎      | 326/392 [01:01<00:12,  5.49it/s]16 03:08:21 Save the image 01123N.png
 83%|█████████████████████████████████▎      | 327/392 [01:01<00:11,  5.49it/s]16 03:08:21 Save the image 01124N.png
 84%|█████████████████████████████████▍      | 328/392 [01:01<00:11,  5.50it/s]16 03:08:21 Save the image 01125N.png
 84%|█████████████████████████████████▌      | 329/392 [01:01<00:11,  5.45it/s]16 03:08:22 Save the image 01126N.png
 84%|█████████████████████████████████▋      | 330/392 [01:02<00:11,  5.51it/s]16 03:08:22 Save the image 01127N.png
 84%|█████████████████████████████████▊      | 331/392 [01:02<00:11,  5.49it/s]16 03:08:22 Save the image 01128N.png
 85%|█████████████████████████████████▉      | 332/392 [01:02<00:10,  5.61it/s]16 03:08:22 Save the image 01129N.png
 85%|█████████████████████████████████▉      | 333/392 [01:02<00:10,  5.88it/s]16 03:08:22 Save the image 01130N.png
 85%|██████████████████████████████████      | 334/392 [01:02<00:10,  5.72it/s]16 03:08:22 Save the image 01131N.png
 85%|██████████████████████████████████▏     | 335/392 [01:02<00:10,  5.67it/s]16 03:08:23 Save the image 01132N.png
 86%|██████████████████████████████████▎     | 336/392 [01:03<00:09,  5.63it/s]16 03:08:23 Save the image 01133N.png
 86%|██████████████████████████████████▍     | 337/392 [01:03<00:09,  5.54it/s]16 03:08:23 Save the image 01134N.png
 86%|██████████████████████████████████▍     | 338/392 [01:03<00:09,  5.48it/s]16 03:08:23 Save the image 01135N.png
 86%|██████████████████████████████████▌     | 339/392 [01:03<00:09,  5.52it/s]16 03:08:23 Save the image 01136N.png
 87%|██████████████████████████████████▋     | 340/392 [01:03<00:09,  5.49it/s]16 03:08:23 Save the image 01137N.png
 87%|██████████████████████████████████▊     | 341/392 [01:04<00:09,  5.47it/s]16 03:08:24 Save the image 01138N.png
 87%|██████████████████████████████████▉     | 342/392 [01:04<00:09,  5.49it/s]16 03:08:24 Save the image 01139N.png
 88%|███████████████████████████████████     | 343/392 [01:04<00:08,  5.51it/s]16 03:08:24 Save the image 01140N.png
 88%|███████████████████████████████████     | 344/392 [01:04<00:08,  5.47it/s]16 03:08:24 Save the image 01141N.png
 88%|███████████████████████████████████▏    | 345/392 [01:04<00:08,  5.52it/s]16 03:08:24 Save the image 01142N.png
 88%|███████████████████████████████████▎    | 346/392 [01:05<00:08,  5.48it/s]16 03:08:25 Save the image 01143N.png
 89%|███████████████████████████████████▍    | 347/392 [01:05<00:08,  5.47it/s]16 03:08:25 Save the image 01144N.png
 89%|███████████████████████████████████▌    | 348/392 [01:05<00:08,  5.46it/s]16 03:08:25 Save the image 01145N.png
 89%|███████████████████████████████████▌    | 349/392 [01:05<00:07,  5.48it/s]16 03:08:25 Save the image 01146N.png
 89%|███████████████████████████████████▋    | 350/392 [01:05<00:07,  5.47it/s]16 03:08:25 Save the image 01147N.png
 90%|███████████████████████████████████▊    | 351/392 [01:05<00:07,  5.43it/s]16 03:08:26 Save the image 01148N.png
 90%|███████████████████████████████████▉    | 352/392 [01:06<00:07,  5.49it/s]16 03:08:26 Save the image 01149N.png
 90%|████████████████████████████████████    | 353/392 [01:06<00:07,  5.46it/s]16 03:08:26 Save the image 01150N.png
 90%|████████████████████████████████████    | 354/392 [01:06<00:06,  5.45it/s]16 03:08:26 Save the image 01151N.png
 91%|████████████████████████████████████▏   | 355/392 [01:06<00:06,  5.43it/s]16 03:08:26 Save the image 01152N.png
 91%|████████████████████████████████████▎   | 356/392 [01:06<00:06,  5.42it/s]16 03:08:26 Save the image 01153N.png
 91%|████████████████████████████████████▍   | 357/392 [01:07<00:06,  5.38it/s]16 03:08:27 Save the image 01154N.png
 91%|████████████████████████████████████▌   | 358/392 [01:07<00:06,  5.38it/s]16 03:08:27 Save the image 01155N.png
 92%|████████████████████████████████████▋   | 359/392 [01:07<00:06,  5.34it/s]16 03:08:27 Save the image 01156N.png
 92%|████████████████████████████████████▋   | 360/392 [01:07<00:05,  5.33it/s]16 03:08:27 Save the image 01157N.png
 92%|████████████████████████████████████▊   | 361/392 [01:07<00:05,  5.35it/s]16 03:08:27 Save the image 01158N.png
 92%|████████████████████████████████████▉   | 362/392 [01:07<00:05,  5.36it/s]16 03:08:28 Save the image 01159N.png
 93%|█████████████████████████████████████   | 363/392 [01:08<00:05,  5.38it/s]16 03:08:28 Save the image 01160N.png
 93%|█████████████████████████████████████▏  | 364/392 [01:08<00:05,  5.41it/s]16 03:08:28 Save the image 01161N.png
 93%|█████████████████████████████████████▏  | 365/392 [01:08<00:05,  5.33it/s]16 03:08:28 Save the image 01162N.png
 93%|█████████████████████████████████████▎  | 366/392 [01:08<00:04,  5.33it/s]16 03:08:28 Save the image 01163N.png
 94%|█████████████████████████████████████▍  | 367/392 [01:08<00:04,  5.37it/s]16 03:08:28 Save the image 01164N.png
 94%|█████████████████████████████████████▌  | 368/392 [01:09<00:04,  5.36it/s]16 03:08:29 Save the image 01165N.png
 94%|█████████████████████████████████████▋  | 369/392 [01:09<00:04,  5.39it/s]16 03:08:29 Save the image 01166N.png
 94%|█████████████████████████████████████▊  | 370/392 [01:09<00:04,  5.39it/s]16 03:08:29 Save the image 01167N.png
 95%|█████████████████████████████████████▊  | 371/392 [01:09<00:03,  5.39it/s]16 03:08:29 Save the image 01168N.png
 95%|█████████████████████████████████████▉  | 372/392 [01:09<00:03,  5.74it/s]16 03:08:29 Save the image 01169N.png
 95%|██████████████████████████████████████  | 373/392 [01:09<00:03,  5.64it/s]16 03:08:30 Save the image 01170N.png
 95%|██████████████████████████████████████▏ | 374/392 [01:10<00:03,  5.56it/s]16 03:08:30 Save the image 01171N.png
 96%|██████████████████████████████████████▎ | 375/392 [01:10<00:03,  5.59it/s]16 03:08:30 Save the image 01172N.png
 96%|██████████████████████████████████████▎ | 376/392 [01:10<00:02,  5.79it/s]16 03:08:30 Save the image 01173N.png
 96%|██████████████████████████████████████▍ | 377/392 [01:10<00:02,  5.68it/s]16 03:08:30 Save the image 01174N.png
 96%|██████████████████████████████████████▌ | 378/392 [01:10<00:02,  5.64it/s]16 03:08:30 Save the image 01175N.png
 97%|██████████████████████████████████████▋ | 379/392 [01:11<00:02,  5.58it/s]16 03:08:31 Save the image 01176N.png
 97%|██████████████████████████████████████▊ | 380/392 [01:11<00:02,  5.53it/s]16 03:08:31 Save the image 01177N.png
 97%|██████████████████████████████████████▉ | 381/392 [01:11<00:01,  5.56it/s]16 03:08:31 Save the image 01178N.png
 97%|██████████████████████████████████████▉ | 382/392 [01:11<00:01,  5.57it/s]16 03:08:31 Save the image 01179N.png

 98%|███████████████████████████████████████ | 383/392 [01:11<00:01,  5.51it/s]16 03:08:31 Save the image 01180N.png
 98%|███████████████████████████████████████▏| 384/392 [01:11<00:01,  5.49it/s]16 03:08:32 Save the image 01181N.png
 98%|███████████████████████████████████████▎| 385/392 [01:12<00:01,  5.44it/s]16 03:08:32 Save the image 01182N.png
 98%|███████████████████████████████████████▍| 386/392 [01:12<00:01,  5.52it/s]16 03:08:32 Save the image 01183N.png
 99%|███████████████████████████████████████▍| 387/392 [01:12<00:00,  5.48it/s]16 03:08:32 Save the image 01184N.png
 99%|███████████████████████████████████████▌| 388/392 [01:12<00:00,  5.52it/s]16 03:08:32 Save the image 01185N.png
 99%|███████████████████████████████████████▋| 389/392 [01:12<00:00,  5.48it/s]16 03:08:32 Save the image 01186N.png
 99%|███████████████████████████████████████▊| 390/392 [01:13<00:00,  5.47it/s]16 03:08:33 Save the image 01187N.png
100%|███████████████████████████████████████▉| 391/392 [01:13<00:00,  5.44it/s]16 03:08:33 Save the image 01188N.png
100%|████████████████████████████████████████| 392/392 [01:13<00:00,  5.34it/s]
1 unlabeled	97.769%
2 car   	86.617%
3 person	71.802%
4 bike  	72.749%
5 curve 	38.595%
6 car_stop	35.661%
7 guardrail	48.186%
8 color_cone	56.572%
9 bump  	49.702%
----------     mean_IoU	61.961%	freq_IoU	95.739%	mean_pixel_acc	71.182%	pixel_acc	97.723%
16 03:08:33 Evaluation Elapsed Time: 73.42s

In [18]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E3")

!python eval.py -e 100 -d 0 --split train -p predictions_E3_train

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 03:11:14 using devices 0
16 03:11:14 Using E3: SegFormer-B2 with reliability-guided fusion
16 03:11:15 Using MLP Decoder
16 03:11:15 Load Model: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e3/checkpoint/epoch-100.pth
16 03:11:19 Load model, Time usage:
	IO: 4.348769187927246, initialize parameters: 0.044000864028930664
16 03:11:19 GPU 0 handle 1568 data.
  0%|                                                 | 0/1568 [00:00<?, ?it/s][ WARN:0@8.676] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 03:11:21 Save the image 00001D.png
  0%|                                         | 1/1568 [00:01<42:31,  1.63s/it]16 03:11:21 Save the image 00001D_flip.png
  0%|                                         | 2/1568 [00:01<20:14,  1.29it/s]16 03:11:21 Save the image 00002D.png
  0%|                                         | 3/1568 [00:01<13:11,  1.98it/s]16 03:11:21 Save the image 00002D_flip.png
  0%|                                         | 4/1568 [00:02<09:52,  2.64it/s]16 03:11:22 Save the image 00055D.png
  0%|▏                                        | 5/1568 [00:02<07:59,  3.26it/s]16 03:11:22 Save the image 00055D_flip.png
  0%|▏                                        | 6/1568 [00:02<06:52,  3.78it/s]16 03:11:22 Save the image 00056D.png
  0%|▏                                        | 7/1568 [00:02<06:12,  4.19it/s]16 03:11:22 Save the image 00056D_flip.png
  1%|▏                                        | 8/1568 [00:02<05:42,  4.55it/s]16 03:11:22 Save the image 00057D.png
  1%|▏                                        | 9/1568 [00:03<05:29,  4.74it/s]16 03:11:23 Save the image 00057D_flip.png
  1%|▎                                       | 10/1568 [00:03<05:16,  4.92it/s]16 03:11:23 Save the image 00058D.png
  1%|▎                                       | 11/1568 [00:03<05:11,  5.00it/s]16 03:11:23 Save the image 00058D_flip.png
  1%|▎                                       | 12/1568 [00:03<05:03,  5.12it/s]16 03:11:23 Save the image 00081D.png
  1%|▎                                       | 13/1568 [00:03<04:59,  5.20it/s]16 03:11:23 Save the image 00081D_flip.png
  1%|▎                                       | 14/1568 [00:04<04:58,  5.21it/s]16 03:11:23 Save the image 00082D.png
  1%|▍                                       | 15/1568 [00:04<04:54,  5.27it/s]16 03:11:24 Save the image 00082D_flip.png
  1%|▍                                       | 16/1568 [00:04<04:51,  5.33it/s]16 03:11:24 Save the image 00083D.png
  1%|▍                                       | 17/1568 [00:04<04:50,  5.35it/s]16 03:11:24 Save the image 00083D_flip.png
  1%|▍                                       | 18/1568 [00:04<04:49,  5.35it/s]16 03:11:24 Save the image 00084D.png
  1%|▍                                       | 19/1568 [00:04<04:48,  5.36it/s]16 03:11:24 Save the image 00084D_flip.png
  1%|▌                                       | 20/1568 [00:05<04:46,  5.40it/s]16 03:11:25 Save the image 00085D.png
  1%|▌                                       | 21/1568 [00:05<04:46,  5.40it/s]16 03:11:25 Save the image 00085D_flip.png
  1%|▌                                       | 22/1568 [00:05<04:46,  5.40it/s]16 03:11:25 Save the image 00086D.png
  1%|▌                                       | 23/1568 [00:05<04:45,  5.41it/s]16 03:11:25 Save the image 00086D_flip.png
  2%|▌                                       | 24/1568 [00:05<04:45,  5.41it/s]16 03:11:25 Save the image 00087D.png
  2%|▋                                       | 25/1568 [00:06<04:30,  5.70it/s]16 03:11:25 Save the image 00087D_flip.png
  2%|▋                                       | 26/1568 [00:06<04:35,  5.60it/s]16 03:11:26 Save the image 00088D.png
  2%|▋                                       | 27/1568 [00:06<04:35,  5.59it/s]16 03:11:26 Save the image 00088D_flip.png
  2%|▋                                       | 28/1568 [00:06<04:38,  5.53it/s]16 03:11:26 Save the image 00091D.png
  2%|▋                                       | 29/1568 [00:06<04:40,  5.49it/s]16 03:11:26 Save the image 00091D_flip.png
  2%|▊                                       | 30/1568 [00:06<04:34,  5.60it/s]16 03:11:26 Save the image 00092D.png
  2%|▊                                       | 31/1568 [00:07<04:33,  5.63it/s]16 03:11:27 Save the image 00092D_flip.png
  2%|▊                                       | 32/1568 [00:07<04:32,  5.64it/s]16 03:11:27 Save the image 00093D.png
  2%|▊                                       | 33/1568 [00:07<04:35,  5.57it/s]16 03:11:27 Save the image 00093D_flip.png
  2%|▊                                       | 34/1568 [00:07<04:35,  5.56it/s]16 03:11:27 Save the image 00094D.png
  2%|▉                                       | 35/1568 [00:07<04:36,  5.54it/s]16 03:11:27 Save the image 00094D_flip.png
  2%|▉                                       | 36/1568 [00:08<04:36,  5.54it/s]16 03:11:27 Save the image 00095D.png
  2%|▉                                       | 37/1568 [00:08<04:32,  5.62it/s]16 03:11:28 Save the image 00095D_flip.png
  2%|▉                                       | 38/1568 [00:08<04:35,  5.55it/s]16 03:11:28 Save the image 00096D.png
  2%|▉                                       | 39/1568 [00:08<04:36,  5.52it/s]16 03:11:28 Save the image 00096D_flip.png
  3%|█                                       | 40/1568 [00:08<04:37,  5.50it/s]16 03:11:28 Save the image 00097D.png
  3%|█                                       | 41/1568 [00:08<04:37,  5.50it/s]16 03:11:28 Save the image 00097D_flip.png
  3%|█                                       | 42/1568 [00:09<04:37,  5.49it/s]16 03:11:29 Save the image 00098D.png
  3%|█                                       | 43/1568 [00:09<04:40,  5.44it/s]16 03:11:29 Save the image 00098D_flip.png
  3%|█                                       | 44/1568 [00:09<04:37,  5.50it/s]16 03:11:29 Save the image 00099D.png
  3%|█▏                                      | 45/1568 [00:09<04:38,  5.47it/s]16 03:11:29 Save the image 00099D_flip.png
  3%|█▏                                      | 46/1568 [00:09<04:39,  5.44it/s]16 03:11:29 Save the image 00100D.png
  3%|█▏                                      | 47/1568 [00:10<04:40,  5.43it/s]16 03:11:29 Save the image 00100D_flip.png
  3%|█▏                                      | 48/1568 [00:10<04:39,  5.43it/s]16 03:11:30 Save the image 00101D.png
  3%|█▎                                      | 49/1568 [00:10<04:38,  5.44it/s]16 03:11:30 Save the image 00101D_flip.png
  3%|█▎                                      | 50/1568 [00:10<04:39,  5.43it/s]16 03:11:30 Save the image 00102D.png
  3%|█▎                                      | 51/1568 [00:10<04:38,  5.45it/s]16 03:11:30 Save the image 00102D_flip.png
  3%|█▎                                      | 52/1568 [00:10<04:40,  5.41it/s]16 03:11:30 Save the image 00103D.png
  3%|█▎                                      | 53/1568 [00:11<04:39,  5.42it/s]16 03:11:31 Save the image 00103D_flip.png
  3%|█▍                                      | 54/1568 [00:11<04:40,  5.41it/s]16 03:11:31 Save the image 00104D.png
  4%|█▍                                      | 55/1568 [00:11<04:39,  5.42it/s]16 03:11:31 Save the image 00104D_flip.png
  4%|█▍                                      | 56/1568 [00:11<04:38,  5.44it/s]16 03:11:31 Save the image 00105D.png

  4%|█▍                                      | 57/1568 [00:11<04:38,  5.43it/s]16 03:11:31 Save the image 00105D_flip.png
  4%|█▍                                      | 58/1568 [00:12<04:37,  5.43it/s]16 03:11:31 Save the image 00106D.png
  4%|█▌                                      | 59/1568 [00:12<04:38,  5.41it/s]16 03:11:32 Save the image 00106D_flip.png
  4%|█▌                                      | 60/1568 [00:12<04:38,  5.41it/s]16 03:11:32 Save the image 00107D.png
  4%|█▌                                      | 61/1568 [00:12<04:37,  5.42it/s]16 03:11:32 Save the image 00107D_flip.png
  4%|█▌                                      | 62/1568 [00:12<04:37,  5.42it/s]16 03:11:32 Save the image 00108D.png
  4%|█▌                                      | 63/1568 [00:12<04:39,  5.38it/s]16 03:11:32 Save the image 00108D_flip.png
  4%|█▋                                      | 64/1568 [00:13<04:38,  5.39it/s]16 03:11:33 Save the image 00109D.png
  4%|█▋                                      | 65/1568 [00:13<04:35,  5.47it/s]16 03:11:33 Save the image 00109D_flip.png
  4%|█▋                                      | 66/1568 [00:13<04:36,  5.44it/s]16 03:11:33 Save the image 00110D.png
  4%|█▋                                      | 67/1568 [00:13<04:35,  5.45it/s]16 03:11:33 Save the image 00110D_flip.png
  4%|█▋                                      | 68/1568 [00:13<04:36,  5.43it/s]16 03:11:33 Save the image 00111D.png
  4%|█▊                                      | 69/1568 [00:14<04:37,  5.41it/s]16 03:11:34 Save the image 00111D_flip.png
  4%|█▊                                      | 70/1568 [00:14<04:35,  5.45it/s]16 03:11:34 Save the image 00112D.png
  5%|█▊                                      | 71/1568 [00:14<04:35,  5.43it/s]16 03:11:34 Save the image 00112D_flip.png
  5%|█▊                                      | 72/1568 [00:14<04:35,  5.43it/s]16 03:11:34 Save the image 00113D.png
  5%|█▊                                      | 73/1568 [00:14<04:35,  5.42it/s]16 03:11:34 Save the image 00113D_flip.png
  5%|█▉                                      | 74/1568 [00:15<04:35,  5.42it/s]16 03:11:34 Save the image 00114D.png
  5%|█▉                                      | 75/1568 [00:15<04:39,  5.35it/s]16 03:11:35 Save the image 00114D_flip.png
  5%|█▉                                      | 76/1568 [00:15<04:36,  5.40it/s]16 03:11:35 Save the image 00115D.png
  5%|█▉                                      | 77/1568 [00:15<04:34,  5.43it/s]16 03:11:35 Save the image 00115D_flip.png
  5%|█▉                                      | 78/1568 [00:15<04:34,  5.42it/s]16 03:11:35 Save the image 00116D.png
  5%|██                                      | 79/1568 [00:15<04:32,  5.47it/s]16 03:11:35 Save the image 00116D_flip.png
  5%|██                                      | 80/1568 [00:16<04:31,  5.47it/s]16 03:11:36 Save the image 00117D.png
  5%|██                                      | 81/1568 [00:16<04:32,  5.47it/s]16 03:11:36 Save the image 00117D_flip.png
  5%|██                                      | 82/1568 [00:16<04:33,  5.44it/s]16 03:11:36 Save the image 00118D.png
  5%|██                                      | 83/1568 [00:16<04:32,  5.44it/s]16 03:11:36 Save the image 00118D_flip.png
  5%|██▏                                     | 84/1568 [00:16<04:31,  5.47it/s]16 03:11:36 Save the image 00119D.png
  5%|██▏                                     | 85/1568 [00:17<04:31,  5.47it/s]16 03:11:36 Save the image 00119D_flip.png
  5%|██▏                                     | 86/1568 [00:17<04:31,  5.46it/s]16 03:11:37 Save the image 00120D.png
  6%|██▏                                     | 87/1568 [00:17<04:31,  5.45it/s]16 03:11:37 Save the image 00120D_flip.png
  6%|██▏                                     | 88/1568 [00:17<04:31,  5.45it/s]16 03:11:37 Save the image 00121D.png
  6%|██▎                                     | 89/1568 [00:17<04:31,  5.44it/s]16 03:11:37 Save the image 00121D_flip.png
  6%|██▎                                     | 90/1568 [00:17<04:31,  5.44it/s]16 03:11:37 Save the image 00122D.png
  6%|██▎                                     | 91/1568 [00:18<04:31,  5.44it/s]16 03:11:38 Save the image 00122D_flip.png
  6%|██▎                                     | 92/1568 [00:18<04:32,  5.42it/s]16 03:11:38 Save the image 00123D.png
  6%|██▎                                     | 93/1568 [00:18<04:32,  5.42it/s]16 03:11:38 Save the image 00123D_flip.png
  6%|██▍                                     | 94/1568 [00:18<04:31,  5.42it/s]16 03:11:38 Save the image 00124D.png
  6%|██▍                                     | 95/1568 [00:18<04:31,  5.43it/s]16 03:11:38 Save the image 00124D_flip.png
  6%|██▍                                     | 96/1568 [00:19<04:30,  5.44it/s]16 03:11:38 Save the image 00125D.png
  6%|██▍                                     | 97/1568 [00:19<04:30,  5.44it/s]16 03:11:39 Save the image 00125D_flip.png
  6%|██▌                                     | 98/1568 [00:19<04:30,  5.44it/s]16 03:11:39 Save the image 00126D.png
  6%|██▌                                     | 99/1568 [00:19<04:31,  5.42it/s]16 03:11:39 Save the image 00126D_flip.png
  6%|██▍                                    | 100/1568 [00:19<04:31,  5.41it/s]16 03:11:39 Save the image 00127D.png
  6%|██▌                                    | 101/1568 [00:19<04:30,  5.43it/s]16 03:11:39 Save the image 00127D_flip.png
  7%|██▌                                    | 102/1568 [00:20<04:29,  5.44it/s]16 03:11:40 Save the image 00128D.png
  7%|██▌                                    | 103/1568 [00:20<04:27,  5.48it/s]16 03:11:40 Save the image 00128D_flip.png
  7%|██▌                                    | 104/1568 [00:20<04:27,  5.47it/s]16 03:11:40 Save the image 00129D.png
  7%|██▌                                    | 105/1568 [00:20<04:29,  5.43it/s]16 03:11:40 Save the image 00129D_flip.png
  7%|██▋                                    | 106/1568 [00:20<04:27,  5.47it/s]16 03:11:40 Save the image 00130D.png
  7%|██▋                                    | 107/1568 [00:21<04:28,  5.45it/s]16 03:11:41 Save the image 00130D_flip.png
  7%|██▋                                    | 108/1568 [00:21<04:28,  5.44it/s]16 03:11:41 Save the image 00131D.png
  7%|██▋                                    | 109/1568 [00:21<04:27,  5.45it/s]16 03:11:41 Save the image 00131D_flip.png
  7%|██▋                                    | 110/1568 [00:21<04:12,  5.78it/s]16 03:11:41 Save the image 00132D.png
  7%|██▊                                    | 111/1568 [00:21<04:16,  5.68it/s]16 03:11:41 Save the image 00132D_flip.png
  7%|██▊                                    | 112/1568 [00:21<04:17,  5.65it/s]16 03:11:41 Save the image 00133D.png
  7%|██▊                                    | 113/1568 [00:22<04:19,  5.60it/s]16 03:11:42 Save the image 00133D_flip.png
  7%|██▊                                    | 114/1568 [00:22<04:21,  5.55it/s]16 03:11:42 Save the image 00134D.png
  7%|██▊                                    | 115/1568 [00:22<04:20,  5.57it/s]16 03:11:42 Save the image 00134D_flip.png
  7%|██▉                                    | 116/1568 [00:22<04:19,  5.60it/s]16 03:11:42 Save the image 00135D.png
  7%|██▉                                    | 117/1568 [00:22<04:17,  5.64it/s]16 03:11:42 Save the image 00135D_flip.png
  8%|██▉                                    | 118/1568 [00:23<04:20,  5.57it/s]16 03:11:42 Save the image 00136D.png
  8%|██▉                                    | 119/1568 [00:23<04:20,  5.56it/s]16 03:11:43 Save the image 00136D_flip.png
  8%|██▉                                    | 120/1568 [00:23<04:17,  5.63it/s]16 03:11:43 Save the image 00137D.png

  8%|███                                    | 121/1568 [00:23<04:20,  5.56it/s]16 03:11:43 Save the image 00137D_flip.png
  8%|███                                    | 122/1568 [00:23<04:18,  5.59it/s]16 03:11:43 Save the image 00138D.png
  8%|███                                    | 123/1568 [00:23<04:21,  5.52it/s]16 03:11:43 Save the image 00138D_flip.png
  8%|███                                    | 124/1568 [00:24<04:23,  5.49it/s]16 03:11:44 Save the image 00139D.png
  8%|███                                    | 125/1568 [00:24<04:24,  5.46it/s]16 03:11:44 Save the image 00139D_flip.png
  8%|███▏                                   | 126/1568 [00:24<04:22,  5.49it/s]16 03:11:44 Save the image 00140D.png
  8%|███▏                                   | 127/1568 [00:24<04:22,  5.49it/s]16 03:11:44 Save the image 00140D_flip.png
  8%|███▏                                   | 128/1568 [00:24<04:23,  5.46it/s]16 03:11:44 Save the image 00141D.png
  8%|███▏                                   | 129/1568 [00:25<04:21,  5.49it/s]16 03:11:44 Save the image 00141D_flip.png
  8%|███▏                                   | 130/1568 [00:25<04:23,  5.46it/s]16 03:11:45 Save the image 00142D.png
  8%|███▎                                   | 131/1568 [00:25<04:24,  5.44it/s]16 03:11:45 Save the image 00142D_flip.png
  8%|███▎                                   | 132/1568 [00:25<04:24,  5.43it/s]16 03:11:45 Save the image 00143D.png
  8%|███▎                                   | 133/1568 [00:25<04:24,  5.44it/s]16 03:11:45 Save the image 00143D_flip.png
  9%|███▎                                   | 134/1568 [00:25<04:22,  5.46it/s]16 03:11:45 Save the image 00144D.png
  9%|███▎                                   | 135/1568 [00:26<04:23,  5.43it/s]16 03:11:46 Save the image 00144D_flip.png
  9%|███▍                                   | 136/1568 [00:26<04:20,  5.49it/s]16 03:11:46 Save the image 00145D.png
  9%|███▍                                   | 137/1568 [00:26<04:22,  5.46it/s]16 03:11:46 Save the image 00145D_flip.png
  9%|███▍                                   | 138/1568 [00:26<04:22,  5.44it/s]16 03:11:46 Save the image 00146D.png
  9%|███▍                                   | 139/1568 [00:26<04:22,  5.45it/s]16 03:11:46 Save the image 00146D_flip.png
  9%|███▍                                   | 140/1568 [00:27<04:22,  5.45it/s]16 03:11:46 Save the image 00147D.png
  9%|███▌                                   | 141/1568 [00:27<04:22,  5.44it/s]16 03:11:47 Save the image 00147D_flip.png
  9%|███▌                                   | 142/1568 [00:27<04:21,  5.46it/s]16 03:11:47 Save the image 00148D.png
  9%|███▌                                   | 143/1568 [00:27<04:21,  5.44it/s]16 03:11:47 Save the image 00148D_flip.png
  9%|███▌                                   | 144/1568 [00:27<04:22,  5.43it/s]16 03:11:47 Save the image 00149D.png
  9%|███▌                                   | 145/1568 [00:27<04:21,  5.44it/s]16 03:11:47 Save the image 00149D_flip.png
  9%|███▋                                   | 146/1568 [00:28<04:22,  5.43it/s]16 03:11:48 Save the image 00150D.png
  9%|███▋                                   | 147/1568 [00:28<04:21,  5.43it/s]16 03:11:48 Save the image 00150D_flip.png
  9%|███▋                                   | 148/1568 [00:28<04:17,  5.51it/s]16 03:11:48 Save the image 00151D.png
 10%|███▋                                   | 149/1568 [00:28<04:22,  5.40it/s]16 03:11:48 Save the image 00151D_flip.png
 10%|███▋                                   | 150/1568 [00:28<04:22,  5.41it/s]16 03:11:48 Save the image 00152D.png
 10%|███▊                                   | 151/1568 [00:29<04:21,  5.42it/s]16 03:11:49 Save the image 00152D_flip.png
 10%|███▊                                   | 152/1568 [00:29<04:20,  5.43it/s]16 03:11:49 Save the image 00153D.png
 10%|███▊                                   | 153/1568 [00:29<04:20,  5.43it/s]16 03:11:49 Save the image 00153D_flip.png
 10%|███▊                                   | 154/1568 [00:29<04:20,  5.42it/s]16 03:11:49 Save the image 00154D.png
 10%|███▊                                   | 155/1568 [00:29<04:20,  5.43it/s]16 03:11:49 Save the image 00154D_flip.png
 10%|███▉                                   | 156/1568 [00:29<04:20,  5.41it/s]16 03:11:49 Save the image 00155D.png
 10%|███▉                                   | 157/1568 [00:30<04:21,  5.40it/s]16 03:11:50 Save the image 00155D_flip.png
 10%|███▉                                   | 158/1568 [00:30<04:20,  5.41it/s]16 03:11:50 Save the image 00156D.png
 10%|███▉                                   | 159/1568 [00:30<04:16,  5.48it/s]16 03:11:50 Save the image 00156D_flip.png
 10%|███▉                                   | 160/1568 [00:30<04:17,  5.47it/s]16 03:11:50 Save the image 00157D.png
 10%|████                                   | 161/1568 [00:30<04:17,  5.47it/s]16 03:11:50 Save the image 00157D_flip.png
 10%|████                                   | 162/1568 [00:31<04:19,  5.42it/s]16 03:11:51 Save the image 00158D.png
 10%|████                                   | 163/1568 [00:31<04:21,  5.38it/s]16 03:11:51 Save the image 00158D_flip.png
 10%|████                                   | 164/1568 [00:31<04:20,  5.38it/s]16 03:11:51 Save the image 00159D.png
 11%|████                                   | 165/1568 [00:31<04:16,  5.46it/s]16 03:11:51 Save the image 00159D_flip.png
 11%|████▏                                  | 166/1568 [00:31<04:16,  5.47it/s]16 03:11:51 Save the image 00160D.png
 11%|████▏                                  | 167/1568 [00:32<04:16,  5.46it/s]16 03:11:51 Save the image 00160D_flip.png
 11%|████▏                                  | 168/1568 [00:32<04:16,  5.47it/s]16 03:11:52 Save the image 00161D.png
 11%|████▏                                  | 169/1568 [00:32<04:15,  5.48it/s]16 03:11:52 Save the image 00161D_flip.png
 11%|████▏                                  | 170/1568 [00:32<04:13,  5.52it/s]16 03:11:52 Save the image 00162D.png
 11%|████▎                                  | 171/1568 [00:32<04:13,  5.50it/s]16 03:11:52 Save the image 00162D_flip.png
 11%|████▎                                  | 172/1568 [00:32<04:14,  5.49it/s]16 03:11:52 Save the image 00163D.png
 11%|████▎                                  | 173/1568 [00:33<04:15,  5.47it/s]16 03:11:53 Save the image 00163D_flip.png
 11%|████▎                                  | 174/1568 [00:33<04:02,  5.75it/s]16 03:11:53 Save the image 00164D.png
 11%|████▎                                  | 175/1568 [00:33<04:05,  5.67it/s]16 03:11:53 Save the image 00164D_flip.png
 11%|████▍                                  | 176/1568 [00:33<04:03,  5.71it/s]16 03:11:53 Save the image 00165D.png
 11%|████▍                                  | 177/1568 [00:33<04:05,  5.66it/s]16 03:11:53 Save the image 00165D_flip.png
 11%|████▍                                  | 178/1568 [00:33<04:08,  5.60it/s]16 03:11:53 Save the image 00166D.png
 11%|████▍                                  | 179/1568 [00:34<04:04,  5.69it/s]16 03:11:54 Save the image 00166D_flip.png
 11%|████▍                                  | 180/1568 [00:34<04:04,  5.67it/s]16 03:11:54 Save the image 00167D.png
 12%|████▌                                  | 181/1568 [00:34<04:07,  5.60it/s]16 03:11:54 Save the image 00167D_flip.png
 12%|████▌                                  | 182/1568 [00:34<04:09,  5.57it/s]16 03:11:54 Save the image 00168D.png
 12%|████▌                                  | 183/1568 [00:34<04:08,  5.57it/s]16 03:11:54 Save the image 00168D_flip.png
 12%|████▌                                  | 184/1568 [00:35<04:11,  5.50it/s]16 03:11:54 Save the image 00169D.png

 12%|████▌                                  | 185/1568 [00:35<04:12,  5.48it/s]16 03:11:55 Save the image 00169D_flip.png
 12%|████▋                                  | 186/1568 [00:35<04:10,  5.53it/s]16 03:11:55 Save the image 00170D.png
 12%|████▋                                  | 187/1568 [00:35<04:10,  5.50it/s]16 03:11:55 Save the image 00170D_flip.png
 12%|████▋                                  | 188/1568 [00:35<04:11,  5.48it/s]16 03:11:55 Save the image 00171D.png
 12%|████▋                                  | 189/1568 [00:35<04:12,  5.46it/s]16 03:11:55 Save the image 00171D_flip.png
 12%|████▋                                  | 190/1568 [00:36<04:12,  5.45it/s]16 03:11:56 Save the image 00172D.png
 12%|████▊                                  | 191/1568 [00:36<04:11,  5.48it/s]16 03:11:56 Save the image 00172D_flip.png
 12%|████▊                                  | 192/1568 [00:36<04:11,  5.46it/s]16 03:11:56 Save the image 00173D.png
 12%|████▊                                  | 193/1568 [00:36<04:11,  5.46it/s]16 03:11:56 Save the image 00173D_flip.png
 12%|████▊                                  | 194/1568 [00:36<04:12,  5.44it/s]16 03:11:56 Save the image 00174D.png
 12%|████▊                                  | 195/1568 [00:37<04:12,  5.44it/s]16 03:11:57 Save the image 00174D_flip.png
 12%|████▉                                  | 196/1568 [00:37<04:12,  5.44it/s]16 03:11:57 Save the image 00175D.png
 13%|████▉                                  | 197/1568 [00:37<04:11,  5.45it/s]16 03:11:57 Save the image 00175D_flip.png
 13%|████▉                                  | 198/1568 [00:37<04:11,  5.46it/s]16 03:11:57 Save the image 00176D.png
 13%|████▉                                  | 199/1568 [00:37<04:11,  5.45it/s]16 03:11:57 Save the image 00176D_flip.png
 13%|████▉                                  | 200/1568 [00:37<04:11,  5.44it/s]16 03:11:57 Save the image 00177D.png
 13%|████▉                                  | 201/1568 [00:38<04:11,  5.44it/s]16 03:11:58 Save the image 00177D_flip.png
 13%|█████                                  | 202/1568 [00:38<04:10,  5.46it/s]16 03:11:58 Save the image 00178D.png
 13%|█████                                  | 203/1568 [00:38<04:09,  5.48it/s]16 03:11:58 Save the image 00178D_flip.png
 13%|█████                                  | 204/1568 [00:38<04:09,  5.46it/s]16 03:11:58 Save the image 00179D.png
 13%|█████                                  | 205/1568 [00:38<04:08,  5.47it/s]16 03:11:58 Save the image 00179D_flip.png
 13%|█████                                  | 206/1568 [00:39<04:16,  5.32it/s]16 03:11:59 Save the image 00180D.png
 13%|█████▏                                 | 207/1568 [00:39<04:11,  5.41it/s]16 03:11:59 Save the image 00180D_flip.png
 13%|█████▏                                 | 208/1568 [00:39<04:11,  5.42it/s]16 03:11:59 Save the image 00181D.png
 13%|█████▏                                 | 209/1568 [00:39<04:10,  5.43it/s]16 03:11:59 Save the image 00181D_flip.png
 13%|█████▏                                 | 210/1568 [00:39<04:09,  5.44it/s]16 03:11:59 Save the image 00182D.png
 13%|█████▏                                 | 211/1568 [00:40<04:08,  5.45it/s]16 03:11:59 Save the image 00182D_flip.png
 14%|█████▎                                 | 212/1568 [00:40<04:08,  5.46it/s]16 03:12:00 Save the image 00183D.png
 14%|█████▎                                 | 213/1568 [00:40<04:09,  5.43it/s]16 03:12:00 Save the image 00183D_flip.png
 14%|█████▎                                 | 214/1568 [00:40<04:08,  5.44it/s]16 03:12:00 Save the image 00184D.png
 14%|█████▎                                 | 215/1568 [00:40<04:07,  5.46it/s]16 03:12:00 Save the image 00184D_flip.png
 14%|█████▎                                 | 216/1568 [00:40<04:06,  5.47it/s]16 03:12:00 Save the image 00185D.png
 14%|█████▍                                 | 217/1568 [00:41<03:55,  5.73it/s]16 03:12:01 Save the image 00185D_flip.png
 14%|█████▍                                 | 218/1568 [00:41<03:58,  5.65it/s]16 03:12:01 Save the image 00186D.png
 14%|█████▍                                 | 219/1568 [00:41<03:59,  5.64it/s]16 03:12:01 Save the image 00186D_flip.png
 14%|█████▍                                 | 220/1568 [00:41<04:00,  5.60it/s]16 03:12:01 Save the image 00187D.png
 14%|█████▍                                 | 221/1568 [00:41<04:02,  5.55it/s]16 03:12:01 Save the image 00187D_flip.png
 14%|█████▌                                 | 222/1568 [00:41<04:00,  5.59it/s]16 03:12:01 Save the image 00188D.png
 14%|█████▌                                 | 223/1568 [00:42<03:59,  5.61it/s]16 03:12:02 Save the image 00188D_flip.png
 14%|█████▌                                 | 224/1568 [00:42<04:00,  5.59it/s]16 03:12:02 Save the image 00189D.png
 14%|█████▌                                 | 225/1568 [00:42<04:02,  5.54it/s]16 03:12:02 Save the image 00189D_flip.png
 14%|█████▌                                 | 226/1568 [00:42<04:01,  5.56it/s]16 03:12:02 Save the image 00190D.png
 14%|█████▋                                 | 227/1568 [00:42<04:01,  5.55it/s]16 03:12:02 Save the image 00190D_flip.png
 15%|█████▋                                 | 228/1568 [00:43<04:02,  5.52it/s]16 03:12:03 Save the image 00191D.png
 15%|█████▋                                 | 229/1568 [00:43<04:01,  5.54it/s]16 03:12:03 Save the image 00191D_flip.png
 15%|█████▋                                 | 230/1568 [00:43<04:02,  5.52it/s]16 03:12:03 Save the image 00192D.png
 15%|█████▋                                 | 231/1568 [00:43<04:02,  5.51it/s]16 03:12:03 Save the image 00192D_flip.png
 15%|█████▊                                 | 232/1568 [00:43<04:02,  5.50it/s]16 03:12:03 Save the image 00193D.png
 15%|█████▊                                 | 233/1568 [00:43<04:02,  5.50it/s]16 03:12:03 Save the image 00193D_flip.png
 15%|█████▊                                 | 234/1568 [00:44<04:04,  5.46it/s]16 03:12:04 Save the image 00194D.png
 15%|█████▊                                 | 235/1568 [00:44<04:01,  5.52it/s]16 03:12:04 Save the image 00194D_flip.png
 15%|█████▊                                 | 236/1568 [00:44<04:01,  5.51it/s]16 03:12:04 Save the image 00195D.png
 15%|█████▉                                 | 237/1568 [00:44<04:02,  5.49it/s]16 03:12:04 Save the image 00195D_flip.png
 15%|█████▉                                 | 238/1568 [00:44<04:02,  5.49it/s]16 03:12:04 Save the image 00196D.png
 15%|█████▉                                 | 239/1568 [00:45<04:03,  5.46it/s]16 03:12:05 Save the image 00196D_flip.png
 15%|█████▉                                 | 240/1568 [00:45<04:02,  5.47it/s]16 03:12:05 Save the image 00197D.png
 15%|█████▉                                 | 241/1568 [00:45<04:01,  5.48it/s]16 03:12:05 Save the image 00197D_flip.png
 15%|██████                                 | 242/1568 [00:45<04:02,  5.46it/s]16 03:12:05 Save the image 00198D.png
 15%|██████                                 | 243/1568 [00:45<04:03,  5.44it/s]16 03:12:05 Save the image 00198D_flip.png
 16%|██████                                 | 244/1568 [00:45<04:04,  5.42it/s]16 03:12:05 Save the image 00199D.png
 16%|██████                                 | 245/1568 [00:46<04:04,  5.42it/s]16 03:12:06 Save the image 00199D_flip.png
 16%|██████                                 | 246/1568 [00:46<04:03,  5.43it/s]16 03:12:06 Save the image 00200D.png
 16%|██████▏                                | 247/1568 [00:46<04:02,  5.44it/s]16 03:12:06 Save the image 00200D_flip.png
 16%|██████▏                                | 248/1568 [00:46<04:01,  5.47it/s]16 03:12:06 Save the image 00201D.png

 16%|██████▏                                | 249/1568 [00:46<04:05,  5.38it/s]16 03:12:06 Save the image 00201D_flip.png
 16%|██████▏                                | 250/1568 [00:47<04:04,  5.39it/s]16 03:12:07 Save the image 00202D.png
 16%|██████▏                                | 251/1568 [00:47<04:03,  5.41it/s]16 03:12:07 Save the image 00202D_flip.png
 16%|██████▎                                | 252/1568 [00:47<04:02,  5.42it/s]16 03:12:07 Save the image 00203D.png
 16%|██████▎                                | 253/1568 [00:47<04:02,  5.43it/s]16 03:12:07 Save the image 00203D_flip.png
 16%|██████▎                                | 254/1568 [00:47<04:01,  5.44it/s]16 03:12:07 Save the image 00204D.png
 16%|██████▎                                | 255/1568 [00:48<04:01,  5.44it/s]16 03:12:07 Save the image 00204D_flip.png
 16%|██████▎                                | 256/1568 [00:48<04:01,  5.43it/s]16 03:12:08 Save the image 00205D.png
 16%|██████▍                                | 257/1568 [00:48<04:01,  5.44it/s]16 03:12:08 Save the image 00205D_flip.png
 16%|██████▍                                | 258/1568 [00:48<04:00,  5.45it/s]16 03:12:08 Save the image 00206D.png
 17%|██████▍                                | 259/1568 [00:48<03:59,  5.46it/s]16 03:12:08 Save the image 00206D_flip.png
 17%|██████▍                                | 260/1568 [00:48<03:59,  5.46it/s]16 03:12:08 Save the image 00207D.png
 17%|██████▍                                | 261/1568 [00:49<03:59,  5.45it/s]16 03:12:09 Save the image 00207D_flip.png
 17%|██████▌                                | 262/1568 [00:49<03:59,  5.46it/s]16 03:12:09 Save the image 00208D.png
 17%|██████▌                                | 263/1568 [00:49<03:57,  5.50it/s]16 03:12:09 Save the image 00208D_flip.png
 17%|██████▌                                | 264/1568 [00:49<03:57,  5.50it/s]16 03:12:09 Save the image 00209D.png
 17%|██████▌                                | 265/1568 [00:49<03:57,  5.48it/s]16 03:12:09 Save the image 00209D_flip.png
 17%|██████▌                                | 266/1568 [00:50<03:58,  5.46it/s]16 03:12:09 Save the image 00210D.png
 17%|██████▋                                | 267/1568 [00:50<03:45,  5.78it/s]16 03:12:10 Save the image 00210D_flip.png
 17%|██████▋                                | 268/1568 [00:50<03:49,  5.68it/s]16 03:12:10 Save the image 00211D.png
 17%|██████▋                                | 269/1568 [00:50<03:50,  5.64it/s]16 03:12:10 Save the image 00211D_flip.png
 17%|██████▋                                | 270/1568 [00:50<03:50,  5.62it/s]16 03:12:10 Save the image 00212D.png
 17%|██████▋                                | 271/1568 [00:50<03:53,  5.56it/s]16 03:12:10 Save the image 00212D_flip.png
 17%|██████▊                                | 272/1568 [00:51<03:52,  5.58it/s]16 03:12:11 Save the image 00213D.png
 17%|██████▊                                | 273/1568 [00:51<03:52,  5.57it/s]16 03:12:11 Save the image 00213D_flip.png
 17%|██████▊                                | 274/1568 [00:51<03:54,  5.52it/s]16 03:12:11 Save the image 00214D.png
 18%|██████▊                                | 275/1568 [00:51<03:57,  5.46it/s]16 03:12:11 Save the image 00214D_flip.png
 18%|██████▊                                | 276/1568 [00:51<03:56,  5.47it/s]16 03:12:11 Save the image 00215D.png
 18%|██████▉                                | 277/1568 [00:52<03:57,  5.43it/s]16 03:12:11 Save the image 00215D_flip.png
 18%|██████▉                                | 278/1568 [00:52<03:56,  5.45it/s]16 03:12:12 Save the image 00216D.png
 18%|██████▉                                | 279/1568 [00:52<03:54,  5.51it/s]16 03:12:12 Save the image 00216D_flip.png
 18%|██████▉                                | 280/1568 [00:52<03:56,  5.45it/s]16 03:12:12 Save the image 00217D.png
 18%|██████▉                                | 281/1568 [00:52<03:58,  5.39it/s]16 03:12:12 Save the image 00217D_flip.png
 18%|███████                                | 282/1568 [00:52<03:58,  5.39it/s]16 03:12:12 Save the image 00218D.png
 18%|███████                                | 283/1568 [00:53<03:57,  5.40it/s]16 03:12:13 Save the image 00218D_flip.png
 18%|███████                                | 284/1568 [00:53<03:57,  5.42it/s]16 03:12:13 Save the image 00219D.png
 18%|███████                                | 285/1568 [00:53<03:57,  5.40it/s]16 03:12:13 Save the image 00219D_flip.png
 18%|███████                                | 286/1568 [00:53<03:57,  5.41it/s]16 03:12:13 Save the image 00220D.png
 18%|███████▏                               | 287/1568 [00:53<03:57,  5.40it/s]16 03:12:13 Save the image 00220D_flip.png
 18%|███████▏                               | 288/1568 [00:54<03:58,  5.36it/s]16 03:12:13 Save the image 00221D.png
 18%|███████▏                               | 289/1568 [00:54<04:00,  5.32it/s]16 03:12:14 Save the image 00221D_flip.png
 18%|███████▏                               | 290/1568 [00:54<03:59,  5.33it/s]16 03:12:14 Save the image 00222D.png
 19%|███████▏                               | 291/1568 [00:54<03:57,  5.37it/s]16 03:12:14 Save the image 00222D_flip.png
 19%|███████▎                               | 292/1568 [00:54<03:57,  5.38it/s]16 03:12:14 Save the image 00223D.png
 19%|███████▎                               | 293/1568 [00:54<03:57,  5.38it/s]16 03:12:14 Save the image 00223D_flip.png
 19%|███████▎                               | 294/1568 [00:55<03:56,  5.39it/s]16 03:12:15 Save the image 00224D.png
 19%|███████▎                               | 295/1568 [00:55<03:56,  5.39it/s]16 03:12:15 Save the image 00224D_flip.png
 19%|███████▎                               | 296/1568 [00:55<03:55,  5.40it/s]16 03:12:15 Save the image 00225D.png
 19%|███████▍                               | 297/1568 [00:55<03:58,  5.34it/s]16 03:12:15 Save the image 00225D_flip.png
 19%|███████▍                               | 298/1568 [00:55<03:57,  5.35it/s]16 03:12:15 Save the image 00226D.png
 19%|███████▍                               | 299/1568 [00:56<04:01,  5.25it/s]16 03:12:16 Save the image 00226D_flip.png
 19%|███████▍                               | 300/1568 [00:56<04:00,  5.27it/s]16 03:12:16 Save the image 00227D.png
 19%|███████▍                               | 301/1568 [00:56<03:58,  5.32it/s]16 03:12:16 Save the image 00227D_flip.png
 19%|███████▌                               | 302/1568 [00:56<03:56,  5.36it/s]16 03:12:16 Save the image 00228D.png
 19%|███████▌                               | 303/1568 [00:56<03:55,  5.36it/s]16 03:12:16 Save the image 00228D_flip.png
 19%|███████▌                               | 304/1568 [00:57<03:55,  5.36it/s]16 03:12:16 Save the image 00229D.png
 19%|███████▌                               | 305/1568 [00:57<03:56,  5.34it/s]16 03:12:17 Save the image 00229D_flip.png
 20%|███████▌                               | 306/1568 [00:57<04:00,  5.24it/s]16 03:12:17 Save the image 00230D.png
 20%|███████▋                               | 307/1568 [00:57<03:58,  5.30it/s]16 03:12:17 Save the image 00230D_flip.png
 20%|███████▋                               | 308/1568 [00:57<03:56,  5.34it/s]16 03:12:17 Save the image 00231D.png
 20%|███████▋                               | 309/1568 [00:57<03:54,  5.36it/s]16 03:12:17 Save the image 00231D_flip.png
 20%|███████▋                               | 310/1568 [00:58<03:54,  5.38it/s]16 03:12:18 Save the image 00232D.png
 20%|███████▋                               | 311/1568 [00:58<03:53,  5.38it/s]16 03:12:18 Save the image 00232D_flip.png
 20%|███████▊                               | 312/1568 [00:58<03:48,  5.49it/s]16 03:12:18 Save the image 00233D.png

 20%|███████▊                               | 313/1568 [00:58<03:55,  5.33it/s]16 03:12:18 Save the image 00233D_flip.png
 20%|███████▊                               | 314/1568 [00:58<03:54,  5.34it/s]16 03:12:18 Save the image 00234D.png
 20%|███████▊                               | 315/1568 [00:59<03:54,  5.35it/s]16 03:12:19 Save the image 00234D_flip.png
 20%|███████▊                               | 316/1568 [00:59<03:53,  5.36it/s]16 03:12:19 Save the image 00235D.png
 20%|███████▉                               | 317/1568 [00:59<03:52,  5.38it/s]16 03:12:19 Save the image 00235D_flip.png
 20%|███████▉                               | 318/1568 [00:59<03:51,  5.39it/s]16 03:12:19 Save the image 00236D.png
 20%|███████▉                               | 319/1568 [00:59<03:50,  5.41it/s]16 03:12:19 Save the image 00236D_flip.png
 20%|███████▉                               | 320/1568 [01:00<03:54,  5.33it/s]16 03:12:19 Save the image 00237D.png
 20%|███████▉                               | 321/1568 [01:00<03:55,  5.29it/s]16 03:12:20 Save the image 00237D_flip.png
 21%|████████                               | 322/1568 [01:00<03:52,  5.35it/s]16 03:12:20 Save the image 00238D.png
 21%|████████                               | 323/1568 [01:00<03:53,  5.33it/s]16 03:12:20 Save the image 00238D_flip.png
 21%|████████                               | 324/1568 [01:00<03:39,  5.67it/s]16 03:12:20 Save the image 00239D.png
 21%|████████                               | 325/1568 [01:00<03:42,  5.58it/s]16 03:12:20 Save the image 00239D_flip.png
 21%|████████                               | 326/1568 [01:01<03:44,  5.53it/s]16 03:12:21 Save the image 00240D.png
 21%|████████▏                              | 327/1568 [01:01<03:49,  5.41it/s]16 03:12:21 Save the image 00240D_flip.png
 21%|████████▏                              | 328/1568 [01:01<03:58,  5.21it/s]16 03:12:21 Save the image 00241D.png
 21%|████████▏                              | 329/1568 [01:01<03:57,  5.22it/s]16 03:12:21 Save the image 00241D_flip.png
 21%|████████▏                              | 330/1568 [01:01<03:55,  5.26it/s]16 03:12:21 Save the image 00242D.png
 21%|████████▏                              | 331/1568 [01:02<03:40,  5.62it/s]16 03:12:21 Save the image 00242D_flip.png
 21%|████████▎                              | 332/1568 [01:02<03:43,  5.53it/s]16 03:12:22 Save the image 00243D.png
 21%|████████▎                              | 333/1568 [01:02<03:43,  5.52it/s]16 03:12:22 Save the image 00243D_flip.png
 21%|████████▎                              | 334/1568 [01:02<03:45,  5.46it/s]16 03:12:22 Save the image 00244D.png
 21%|████████▎                              | 335/1568 [01:02<03:46,  5.43it/s]16 03:12:22 Save the image 00244D_flip.png
 21%|████████▎                              | 336/1568 [01:02<03:44,  5.48it/s]16 03:12:22 Save the image 00245D.png
 21%|████████▍                              | 337/1568 [01:03<03:42,  5.54it/s]16 03:12:23 Save the image 00245D_flip.png
 22%|████████▍                              | 338/1568 [01:03<03:42,  5.52it/s]16 03:12:23 Save the image 00246D.png
 22%|████████▍                              | 339/1568 [01:03<03:43,  5.49it/s]16 03:12:23 Save the image 00246D_flip.png
 22%|████████▍                              | 340/1568 [01:03<03:45,  5.44it/s]16 03:12:23 Save the image 00247D.png
 22%|████████▍                              | 341/1568 [01:03<03:44,  5.47it/s]16 03:12:23 Save the image 00247D_flip.png
 22%|████████▌                              | 342/1568 [01:04<03:45,  5.44it/s]16 03:12:23 Save the image 00248D.png
 22%|████████▌                              | 343/1568 [01:04<03:43,  5.49it/s]16 03:12:24 Save the image 00248D_flip.png
 22%|████████▌                              | 344/1568 [01:04<03:44,  5.46it/s]16 03:12:24 Save the image 00249D.png
 22%|████████▌                              | 345/1568 [01:04<03:44,  5.45it/s]16 03:12:24 Save the image 00249D_flip.png
 22%|████████▌                              | 346/1568 [01:04<03:48,  5.35it/s]16 03:12:24 Save the image 00250D.png
 22%|████████▋                              | 347/1568 [01:04<03:48,  5.34it/s]16 03:12:24 Save the image 00250D_flip.png
 22%|████████▋                              | 348/1568 [01:05<03:46,  5.39it/s]16 03:12:25 Save the image 00251D.png
 22%|████████▋                              | 349/1568 [01:05<03:46,  5.39it/s]16 03:12:25 Save the image 00251D_flip.png
 22%|████████▋                              | 350/1568 [01:05<03:42,  5.46it/s]16 03:12:25 Save the image 00252D.png
 22%|████████▋                              | 351/1568 [01:05<03:43,  5.44it/s]16 03:12:25 Save the image 00252D_flip.png
 22%|████████▊                              | 352/1568 [01:05<03:43,  5.44it/s]16 03:12:25 Save the image 00253D.png
 23%|████████▊                              | 353/1568 [01:06<03:47,  5.34it/s]16 03:12:26 Save the image 00253D_flip.png
 23%|████████▊                              | 354/1568 [01:06<03:50,  5.27it/s]16 03:12:26 Save the image 00254D.png
 23%|████████▊                              | 355/1568 [01:06<03:47,  5.33it/s]16 03:12:26 Save the image 00254D_flip.png
 23%|████████▊                              | 356/1568 [01:06<03:45,  5.36it/s]16 03:12:26 Save the image 00255D.png
 23%|████████▉                              | 357/1568 [01:06<03:42,  5.43it/s]16 03:12:26 Save the image 00255D_flip.png
 23%|████████▉                              | 358/1568 [01:07<03:40,  5.48it/s]16 03:12:26 Save the image 00256D.png
 23%|████████▉                              | 359/1568 [01:07<03:41,  5.46it/s]16 03:12:27 Save the image 00256D_flip.png
 23%|████████▉                              | 360/1568 [01:07<03:44,  5.38it/s]16 03:12:27 Save the image 00257D.png
 23%|████████▉                              | 361/1568 [01:07<03:44,  5.38it/s]16 03:12:27 Save the image 00257D_flip.png
 23%|█████████                              | 362/1568 [01:07<03:42,  5.43it/s]16 03:12:27 Save the image 00258D.png
 23%|█████████                              | 363/1568 [01:07<03:42,  5.41it/s]16 03:12:27 Save the image 00258D_flip.png
 23%|█████████                              | 364/1568 [01:08<03:39,  5.49it/s]16 03:12:28 Save the image 00259D.png
 23%|█████████                              | 365/1568 [01:08<03:40,  5.46it/s]16 03:12:28 Save the image 00259D_flip.png
 23%|█████████                              | 366/1568 [01:08<03:40,  5.45it/s]16 03:12:28 Save the image 00260D.png
 23%|█████████▏                             | 367/1568 [01:08<03:43,  5.37it/s]16 03:12:28 Save the image 00260D_flip.png
 23%|█████████▏                             | 368/1568 [01:08<03:40,  5.43it/s]16 03:12:28 Save the image 00261D.png
 24%|█████████▏                             | 369/1568 [01:09<03:40,  5.44it/s]16 03:12:28 Save the image 00261D_flip.png
 24%|█████████▏                             | 370/1568 [01:09<03:41,  5.42it/s]16 03:12:29 Save the image 00262D.png
 24%|█████████▏                             | 371/1568 [01:09<03:39,  5.46it/s]16 03:12:29 Save the image 00262D_flip.png
 24%|█████████▎                             | 372/1568 [01:09<03:39,  5.46it/s]16 03:12:29 Save the image 00263D.png
 24%|█████████▎                             | 373/1568 [01:09<03:39,  5.45it/s]16 03:12:29 Save the image 00263D_flip.png
 24%|█████████▎                             | 374/1568 [01:09<03:39,  5.45it/s]16 03:12:29 Save the image 00264D.png
 24%|█████████▎                             | 375/1568 [01:10<03:39,  5.44it/s]16 03:12:30 Save the image 00264D_flip.png
 24%|█████████▎                             | 376/1568 [01:10<03:37,  5.47it/s]16 03:12:30 Save the image 00265D.png

 24%|█████████▍                             | 377/1568 [01:10<03:38,  5.45it/s]16 03:12:30 Save the image 00265D_flip.png
 24%|█████████▍                             | 378/1568 [01:10<03:38,  5.45it/s]16 03:12:30 Save the image 00266D.png
 24%|█████████▍                             | 379/1568 [01:10<03:38,  5.44it/s]16 03:12:30 Save the image 00266D_flip.png
 24%|█████████▍                             | 380/1568 [01:11<03:38,  5.44it/s]16 03:12:31 Save the image 00267D.png
 24%|█████████▍                             | 381/1568 [01:11<03:38,  5.44it/s]16 03:12:31 Save the image 00267D_flip.png
 24%|█████████▌                             | 382/1568 [01:11<03:37,  5.45it/s]16 03:12:31 Save the image 00268D.png
 24%|█████████▌                             | 383/1568 [01:11<03:36,  5.48it/s]16 03:12:31 Save the image 00268D_flip.png
 24%|█████████▌                             | 384/1568 [01:11<03:38,  5.43it/s]16 03:12:31 Save the image 00269D.png
 25%|█████████▌                             | 385/1568 [01:11<03:37,  5.44it/s]16 03:12:31 Save the image 00269D_flip.png
 25%|█████████▌                             | 386/1568 [01:12<03:36,  5.45it/s]16 03:12:32 Save the image 00270D.png
 25%|█████████▋                             | 387/1568 [01:12<03:36,  5.45it/s]16 03:12:32 Save the image 00270D_flip.png
 25%|█████████▋                             | 388/1568 [01:12<03:36,  5.46it/s]16 03:12:32 Save the image 00271D.png
 25%|█████████▋                             | 389/1568 [01:12<03:36,  5.46it/s]16 03:12:32 Save the image 00271D_flip.png
 25%|█████████▋                             | 390/1568 [01:12<03:35,  5.47it/s]16 03:12:32 Save the image 00272D.png
 25%|█████████▋                             | 391/1568 [01:13<03:37,  5.40it/s]16 03:12:33 Save the image 00272D_flip.png
 25%|█████████▊                             | 392/1568 [01:13<03:36,  5.42it/s]16 03:12:33 Save the image 00273D.png
 25%|█████████▊                             | 393/1568 [01:13<03:39,  5.35it/s]16 03:12:33 Save the image 00273D_flip.png
 25%|█████████▊                             | 394/1568 [01:13<03:35,  5.44it/s]16 03:12:33 Save the image 00274D.png
 25%|█████████▊                             | 395/1568 [01:13<03:35,  5.44it/s]16 03:12:33 Save the image 00274D_flip.png
 25%|█████████▊                             | 396/1568 [01:14<03:35,  5.45it/s]16 03:12:33 Save the image 00275D.png
 25%|█████████▊                             | 397/1568 [01:14<03:34,  5.45it/s]16 03:12:34 Save the image 00275D_flip.png
 25%|█████████▉                             | 398/1568 [01:14<03:36,  5.41it/s]16 03:12:34 Save the image 00276D.png
 25%|█████████▉                             | 399/1568 [01:14<03:36,  5.40it/s]16 03:12:34 Save the image 00276D_flip.png
 26%|█████████▉                             | 400/1568 [01:14<03:36,  5.40it/s]16 03:12:34 Save the image 00277D.png
 26%|█████████▉                             | 401/1568 [01:14<03:35,  5.41it/s]16 03:12:34 Save the image 00277D_flip.png
 26%|█████████▉                             | 402/1568 [01:15<03:34,  5.45it/s]16 03:12:35 Save the image 00278D.png
 26%|██████████                             | 403/1568 [01:15<03:33,  5.44it/s]16 03:12:35 Save the image 00278D_flip.png
 26%|██████████                             | 404/1568 [01:15<03:33,  5.46it/s]16 03:12:35 Save the image 00279D.png
 26%|██████████                             | 405/1568 [01:15<03:36,  5.37it/s]16 03:12:35 Save the image 00279D_flip.png
 26%|██████████                             | 406/1568 [01:15<03:35,  5.39it/s]16 03:12:35 Save the image 00280D.png
 26%|██████████                             | 407/1568 [01:16<03:34,  5.40it/s]16 03:12:35 Save the image 00280D_flip.png
 26%|██████████▏                            | 408/1568 [01:16<03:34,  5.41it/s]16 03:12:36 Save the image 00281D.png
 26%|██████████▏                            | 409/1568 [01:16<03:33,  5.44it/s]16 03:12:36 Save the image 00281D_flip.png
 26%|██████████▏                            | 410/1568 [01:16<03:33,  5.43it/s]16 03:12:36 Save the image 00282D.png
 26%|██████████▏                            | 411/1568 [01:16<03:32,  5.44it/s]16 03:12:36 Save the image 00282D_flip.png
 26%|██████████▏                            | 412/1568 [01:16<03:35,  5.36it/s]16 03:12:36 Save the image 00283D.png
 26%|██████████▎                            | 413/1568 [01:17<03:32,  5.44it/s]16 03:12:37 Save the image 00283D_flip.png
 26%|██████████▎                            | 414/1568 [01:17<03:31,  5.45it/s]16 03:12:37 Save the image 00284D.png
 26%|██████████▎                            | 415/1568 [01:17<03:31,  5.44it/s]16 03:12:37 Save the image 00284D_flip.png
 27%|██████████▎                            | 416/1568 [01:17<03:21,  5.73it/s]16 03:12:37 Save the image 00285D.png
 27%|██████████▎                            | 417/1568 [01:17<03:24,  5.64it/s]16 03:12:37 Save the image 00285D_flip.png
 27%|██████████▍                            | 418/1568 [01:18<03:24,  5.62it/s]16 03:12:37 Save the image 00286D.png
 27%|██████████▍                            | 419/1568 [01:18<03:26,  5.57it/s]16 03:12:38 Save the image 00286D_flip.png
 27%|██████████▍                            | 420/1568 [01:18<03:28,  5.51it/s]16 03:12:38 Save the image 00287D.png
 27%|██████████▍                            | 421/1568 [01:18<03:26,  5.55it/s]16 03:12:38 Save the image 00287D_flip.png
 27%|██████████▍                            | 422/1568 [01:18<03:24,  5.59it/s]16 03:12:38 Save the image 00288D.png
 27%|██████████▌                            | 423/1568 [01:18<03:24,  5.61it/s]16 03:12:38 Save the image 00288D_flip.png
 27%|██████████▌                            | 424/1568 [01:19<03:25,  5.56it/s]16 03:12:39 Save the image 00289D.png
 27%|██████████▌                            | 425/1568 [01:19<03:25,  5.56it/s]16 03:12:39 Save the image 00289D_flip.png
 27%|██████████▌                            | 426/1568 [01:19<03:25,  5.56it/s]16 03:12:39 Save the image 00290D.png
 27%|██████████▌                            | 427/1568 [01:19<03:27,  5.51it/s]16 03:12:39 Save the image 00290D_flip.png
 27%|██████████▋                            | 428/1568 [01:19<03:25,  5.55it/s]16 03:12:39 Save the image 00291D.png
 27%|██████████▋                            | 429/1568 [01:20<03:26,  5.52it/s]16 03:12:39 Save the image 00291D_flip.png
 27%|██████████▋                            | 430/1568 [01:20<03:27,  5.50it/s]16 03:12:40 Save the image 00292D.png
 27%|██████████▋                            | 431/1568 [01:20<03:27,  5.47it/s]16 03:12:40 Save the image 00292D_flip.png
 28%|██████████▋                            | 432/1568 [01:20<03:26,  5.50it/s]16 03:12:40 Save the image 00293D.png
 28%|██████████▊                            | 433/1568 [01:20<03:26,  5.51it/s]16 03:12:40 Save the image 00293D_flip.png
 28%|██████████▊                            | 434/1568 [01:20<03:26,  5.49it/s]16 03:12:40 Save the image 00294D.png
 28%|██████████▊                            | 435/1568 [01:21<03:26,  5.49it/s]16 03:12:41 Save the image 00294D_flip.png
 28%|██████████▊                            | 436/1568 [01:21<03:27,  5.45it/s]16 03:12:41 Save the image 00295D.png
 28%|██████████▊                            | 437/1568 [01:21<03:28,  5.42it/s]16 03:12:41 Save the image 00295D_flip.png
 28%|██████████▉                            | 438/1568 [01:21<03:28,  5.43it/s]16 03:12:41 Save the image 00296D.png
 28%|██████████▉                            | 439/1568 [01:21<03:27,  5.44it/s]16 03:12:41 Save the image 00296D_flip.png
 28%|██████████▉                            | 440/1568 [01:22<03:26,  5.46it/s]16 03:12:41 Save the image 00297D.png

 28%|██████████▉                            | 441/1568 [01:22<03:27,  5.43it/s]16 03:12:42 Save the image 00297D_flip.png
 28%|██████████▉                            | 442/1568 [01:22<03:27,  5.42it/s]16 03:12:42 Save the image 00298D.png
 28%|███████████                            | 443/1568 [01:22<03:27,  5.42it/s]16 03:12:42 Save the image 00298D_flip.png
 28%|███████████                            | 444/1568 [01:22<03:27,  5.43it/s]16 03:12:42 Save the image 00299D.png
 28%|███████████                            | 445/1568 [01:22<03:26,  5.43it/s]16 03:12:42 Save the image 00299D_flip.png
 28%|███████████                            | 446/1568 [01:23<03:26,  5.44it/s]16 03:12:43 Save the image 00300D.png
 29%|███████████                            | 447/1568 [01:23<03:25,  5.44it/s]16 03:12:43 Save the image 00300D_flip.png
 29%|███████████▏                           | 448/1568 [01:23<03:28,  5.38it/s]16 03:12:43 Save the image 00301D.png
 29%|███████████▏                           | 449/1568 [01:23<03:30,  5.33it/s]16 03:12:43 Save the image 00301D_flip.png
 29%|███████████▏                           | 450/1568 [01:23<03:28,  5.37it/s]16 03:12:43 Save the image 00302D.png
 29%|███████████▏                           | 451/1568 [01:24<03:27,  5.39it/s]16 03:12:44 Save the image 00302D_flip.png
 29%|███████████▏                           | 452/1568 [01:24<03:25,  5.44it/s]16 03:12:44 Save the image 00303D.png
 29%|███████████▎                           | 453/1568 [01:24<03:24,  5.45it/s]16 03:12:44 Save the image 00303D_flip.png
 29%|███████████▎                           | 454/1568 [01:24<03:24,  5.44it/s]16 03:12:44 Save the image 00304D.png
 29%|███████████▎                           | 455/1568 [01:24<03:25,  5.41it/s]16 03:12:44 Save the image 00304D_flip.png
 29%|███████████▎                           | 456/1568 [01:24<03:24,  5.43it/s]16 03:12:44 Save the image 00305D.png
 29%|███████████▎                           | 457/1568 [01:25<03:24,  5.44it/s]16 03:12:45 Save the image 00305D_flip.png
 29%|███████████▍                           | 458/1568 [01:25<03:24,  5.44it/s]16 03:12:45 Save the image 00306D.png
 29%|███████████▍                           | 459/1568 [01:25<03:11,  5.78it/s]16 03:12:45 Save the image 00306D_flip.png
 29%|███████████▍                           | 460/1568 [01:25<03:15,  5.67it/s]16 03:12:45 Save the image 00307D.png
 29%|███████████▍                           | 461/1568 [01:25<03:17,  5.59it/s]16 03:12:45 Save the image 00307D_flip.png
 29%|███████████▍                           | 462/1568 [01:26<03:19,  5.56it/s]16 03:12:46 Save the image 00308D.png
 30%|███████████▌                           | 463/1568 [01:26<03:20,  5.51it/s]16 03:12:46 Save the image 00308D_flip.png
 30%|███████████▌                           | 464/1568 [01:26<03:19,  5.52it/s]16 03:12:46 Save the image 00309D.png
 30%|███████████▌                           | 465/1568 [01:26<03:19,  5.52it/s]16 03:12:46 Save the image 00309D_flip.png
 30%|███████████▌                           | 466/1568 [01:26<03:21,  5.48it/s]16 03:12:46 Save the image 00310D.png
 30%|███████████▌                           | 467/1568 [01:26<03:25,  5.36it/s]16 03:12:46 Save the image 00310D_flip.png
 30%|███████████▋                           | 468/1568 [01:27<03:21,  5.45it/s]16 03:12:47 Save the image 00311D.png
 30%|███████████▋                           | 469/1568 [01:27<03:20,  5.49it/s]16 03:12:47 Save the image 00311D_flip.png
 30%|███████████▋                           | 470/1568 [01:27<03:22,  5.43it/s]16 03:12:47 Save the image 00312D.png
 30%|███████████▋                           | 471/1568 [01:27<03:20,  5.47it/s]16 03:12:47 Save the image 00312D_flip.png
 30%|███████████▋                           | 472/1568 [01:27<03:21,  5.43it/s]16 03:12:47 Save the image 00313D.png
 30%|███████████▊                           | 473/1568 [01:28<03:22,  5.41it/s]16 03:12:48 Save the image 00313D_flip.png
 30%|███████████▊                           | 474/1568 [01:28<03:24,  5.36it/s]16 03:12:48 Save the image 00314D.png
 30%|███████████▊                           | 475/1568 [01:28<03:22,  5.39it/s]16 03:12:48 Save the image 00314D_flip.png
 30%|███████████▊                           | 476/1568 [01:28<03:20,  5.43it/s]16 03:12:48 Save the image 00315D.png
 30%|███████████▊                           | 477/1568 [01:28<03:20,  5.44it/s]16 03:12:48 Save the image 00315D_flip.png
 30%|███████████▉                           | 478/1568 [01:29<03:19,  5.46it/s]16 03:12:48 Save the image 00316D.png
 31%|███████████▉                           | 479/1568 [01:29<03:19,  5.45it/s]16 03:12:49 Save the image 00316D_flip.png
 31%|███████████▉                           | 480/1568 [01:29<03:19,  5.45it/s]16 03:12:49 Save the image 00317D.png
 31%|███████████▉                           | 481/1568 [01:29<03:19,  5.44it/s]16 03:12:49 Save the image 00317D_flip.png
 31%|███████████▉                           | 482/1568 [01:29<03:19,  5.46it/s]16 03:12:49 Save the image 00318D.png
 31%|████████████                           | 483/1568 [01:29<03:16,  5.52it/s]16 03:12:49 Save the image 00318D_flip.png
 31%|████████████                           | 484/1568 [01:30<03:17,  5.48it/s]16 03:12:50 Save the image 00319D.png
 31%|████████████                           | 485/1568 [01:30<03:18,  5.47it/s]16 03:12:50 Save the image 00319D_flip.png
 31%|████████████                           | 486/1568 [01:30<03:18,  5.46it/s]16 03:12:50 Save the image 00320D.png
 31%|████████████                           | 487/1568 [01:30<03:18,  5.46it/s]16 03:12:50 Save the image 00320D_flip.png
 31%|████████████▏                          | 488/1568 [01:30<03:16,  5.50it/s]16 03:12:50 Save the image 00321D.png
 31%|████████████▏                          | 489/1568 [01:31<03:16,  5.48it/s]16 03:12:50 Save the image 00321D_flip.png
 31%|████████████▏                          | 490/1568 [01:31<03:16,  5.49it/s]16 03:12:51 Save the image 00322D.png
 31%|████████████▏                          | 491/1568 [01:31<03:17,  5.44it/s]16 03:12:51 Save the image 00322D_flip.png
 31%|████████████▏                          | 492/1568 [01:31<03:17,  5.45it/s]16 03:12:51 Save the image 00323D.png
 31%|████████████▎                          | 493/1568 [01:31<03:17,  5.45it/s]16 03:12:51 Save the image 00323D_flip.png
 32%|████████████▎                          | 494/1568 [01:31<03:17,  5.44it/s]16 03:12:51 Save the image 00324D.png
 32%|████████████▎                          | 495/1568 [01:32<03:05,  5.78it/s]16 03:12:52 Save the image 00324D_flip.png
 32%|████████████▎                          | 496/1568 [01:32<03:08,  5.68it/s]16 03:12:52 Save the image 00325D.png
 32%|████████████▎                          | 497/1568 [01:32<03:09,  5.65it/s]16 03:12:52 Save the image 00325D_flip.png
 32%|████████████▍                          | 498/1568 [01:32<03:12,  5.55it/s]16 03:12:52 Save the image 00326D.png
 32%|████████████▍                          | 499/1568 [01:32<03:14,  5.50it/s]16 03:12:52 Save the image 00326D_flip.png
 32%|████████████▍                          | 500/1568 [01:32<03:12,  5.54it/s]16 03:12:52 Save the image 00327D.png
 32%|████████████▍                          | 501/1568 [01:33<03:11,  5.57it/s]16 03:12:53 Save the image 00327D_flip.png
 32%|████████████▍                          | 502/1568 [01:33<03:11,  5.55it/s]16 03:12:53 Save the image 00328D.png
 32%|████████████▌                          | 503/1568 [01:33<03:13,  5.52it/s]16 03:12:53 Save the image 00328D_flip.png
 32%|████████████▌                          | 504/1568 [01:33<03:12,  5.53it/s]16 03:12:53 Save the image 00329D.png

 32%|████████████▌                          | 505/1568 [01:33<03:12,  5.53it/s]16 03:12:53 Save the image 00329D_flip.png
 32%|████████████▌                          | 506/1568 [01:34<03:13,  5.49it/s]16 03:12:54 Save the image 00330D.png
 32%|████████████▌                          | 507/1568 [01:34<03:11,  5.54it/s]16 03:12:54 Save the image 00330D_flip.png
 32%|████████████▋                          | 508/1568 [01:34<03:12,  5.51it/s]16 03:12:54 Save the image 00331D.png
 32%|████████████▋                          | 509/1568 [01:34<03:13,  5.47it/s]16 03:12:54 Save the image 00331D_flip.png
 33%|████████████▋                          | 510/1568 [01:34<03:14,  5.45it/s]16 03:12:54 Save the image 00332D.png
 33%|████████████▋                          | 511/1568 [01:34<03:12,  5.50it/s]16 03:12:54 Save the image 00332D_flip.png
 33%|████████████▋                          | 512/1568 [01:35<03:11,  5.52it/s]16 03:12:55 Save the image 00333D.png
 33%|████████████▊                          | 513/1568 [01:35<03:11,  5.50it/s]16 03:12:55 Save the image 00333D_flip.png
 33%|████████████▊                          | 514/1568 [01:35<03:12,  5.48it/s]16 03:12:55 Save the image 00334D.png
 33%|████████████▊                          | 515/1568 [01:35<03:12,  5.47it/s]16 03:12:55 Save the image 00334D_flip.png
 33%|████████████▊                          | 516/1568 [01:35<03:12,  5.46it/s]16 03:12:55 Save the image 00335D.png
 33%|████████████▊                          | 517/1568 [01:36<03:13,  5.44it/s]16 03:12:56 Save the image 00335D_flip.png
 33%|████████████▉                          | 518/1568 [01:36<03:10,  5.51it/s]16 03:12:56 Save the image 00336D.png
 33%|████████████▉                          | 519/1568 [01:36<03:11,  5.49it/s]16 03:12:56 Save the image 00336D_flip.png
 33%|████████████▉                          | 520/1568 [01:36<03:11,  5.46it/s]16 03:12:56 Save the image 00337D.png
 33%|████████████▉                          | 521/1568 [01:36<03:11,  5.46it/s]16 03:12:56 Save the image 00337D_flip.png
 33%|████████████▉                          | 522/1568 [01:37<03:12,  5.45it/s]16 03:12:56 Save the image 00338D.png
 33%|█████████████                          | 523/1568 [01:37<03:12,  5.44it/s]16 03:12:57 Save the image 00338D_flip.png
 33%|█████████████                          | 524/1568 [01:37<03:11,  5.46it/s]16 03:12:57 Save the image 00339D.png
 33%|█████████████                          | 525/1568 [01:37<03:11,  5.46it/s]16 03:12:57 Save the image 00339D_flip.png
 34%|█████████████                          | 526/1568 [01:37<03:10,  5.48it/s]16 03:12:57 Save the image 00340D.png
 34%|█████████████                          | 527/1568 [01:37<03:11,  5.44it/s]16 03:12:57 Save the image 00340D_flip.png
 34%|█████████████▏                         | 528/1568 [01:38<03:11,  5.42it/s]16 03:12:58 Save the image 00341D.png
 34%|█████████████▏                         | 529/1568 [01:38<03:11,  5.42it/s]16 03:12:58 Save the image 00341D_flip.png
 34%|█████████████▏                         | 530/1568 [01:38<03:11,  5.43it/s]16 03:12:58 Save the image 00342D.png
 34%|█████████████▏                         | 531/1568 [01:38<03:00,  5.75it/s]16 03:12:58 Save the image 00342D_flip.png
 34%|█████████████▏                         | 532/1568 [01:38<03:03,  5.65it/s]16 03:12:58 Save the image 00343D.png
 34%|█████████████▎                         | 533/1568 [01:38<03:04,  5.61it/s]16 03:12:58 Save the image 00343D_flip.png
 34%|█████████████▎                         | 534/1568 [01:39<03:03,  5.65it/s]16 03:12:59 Save the image 00344D.png
 34%|█████████████▎                         | 535/1568 [01:39<03:05,  5.57it/s]16 03:12:59 Save the image 00344D_flip.png
 34%|█████████████▎                         | 536/1568 [01:39<03:04,  5.61it/s]16 03:12:59 Save the image 00345D.png
 34%|█████████████▎                         | 537/1568 [01:39<03:04,  5.60it/s]16 03:12:59 Save the image 00345D_flip.png
 34%|█████████████▍                         | 538/1568 [01:39<03:06,  5.53it/s]16 03:12:59 Save the image 00346D.png
 34%|█████████████▍                         | 539/1568 [01:40<03:07,  5.48it/s]16 03:13:00 Save the image 00346D_flip.png
 34%|█████████████▍                         | 540/1568 [01:40<03:07,  5.49it/s]16 03:13:00 Save the image 00347D.png
 35%|█████████████▍                         | 541/1568 [01:40<03:06,  5.50it/s]16 03:13:00 Save the image 00347D_flip.png
 35%|█████████████▍                         | 542/1568 [01:40<03:07,  5.48it/s]16 03:13:00 Save the image 00348D.png
 35%|█████████████▌                         | 543/1568 [01:40<03:05,  5.53it/s]16 03:13:00 Save the image 00348D_flip.png
 35%|█████████████▌                         | 544/1568 [01:40<03:06,  5.50it/s]16 03:13:00 Save the image 00349D.png
 35%|█████████████▌                         | 545/1568 [01:41<03:08,  5.42it/s]16 03:13:01 Save the image 00349D_flip.png
 35%|█████████████▌                         | 546/1568 [01:41<03:06,  5.47it/s]16 03:13:01 Save the image 00350D.png
 35%|█████████████▌                         | 547/1568 [01:41<03:05,  5.50it/s]16 03:13:01 Save the image 00350D_flip.png
 35%|█████████████▋                         | 548/1568 [01:41<03:04,  5.52it/s]16 03:13:01 Save the image 00351D.png
 35%|█████████████▋                         | 549/1568 [01:41<03:05,  5.48it/s]16 03:13:01 Save the image 00351D_flip.png
 35%|█████████████▋                         | 550/1568 [01:42<03:04,  5.51it/s]16 03:13:02 Save the image 00352D.png
 35%|█████████████▋                         | 551/1568 [01:42<03:03,  5.55it/s]16 03:13:02 Save the image 00352D_flip.png
 35%|█████████████▋                         | 552/1568 [01:42<03:04,  5.51it/s]16 03:13:02 Save the image 00353D.png
 35%|█████████████▊                         | 553/1568 [01:42<03:06,  5.46it/s]16 03:13:02 Save the image 00353D_flip.png
 35%|█████████████▊                         | 554/1568 [01:42<03:06,  5.44it/s]16 03:13:02 Save the image 00354D.png
 35%|█████████████▊                         | 555/1568 [01:43<03:07,  5.41it/s]16 03:13:02 Save the image 00354D_flip.png
 35%|█████████████▊                         | 556/1568 [01:43<03:06,  5.41it/s]16 03:13:03 Save the image 00355D.png
 36%|█████████████▊                         | 557/1568 [01:43<03:07,  5.39it/s]16 03:13:03 Save the image 00355D_flip.png
 36%|█████████████▉                         | 558/1568 [01:43<03:06,  5.41it/s]16 03:13:03 Save the image 00356D.png
 36%|█████████████▉                         | 559/1568 [01:43<03:07,  5.38it/s]16 03:13:03 Save the image 00356D_flip.png
 36%|█████████████▉                         | 560/1568 [01:43<02:57,  5.69it/s]16 03:13:03 Save the image 00357D.png
 36%|█████████████▉                         | 561/1568 [01:44<02:59,  5.60it/s]16 03:13:04 Save the image 00357D_flip.png
 36%|█████████████▉                         | 562/1568 [01:44<03:00,  5.58it/s]16 03:13:04 Save the image 00358D.png
 36%|██████████████                         | 563/1568 [01:44<03:01,  5.55it/s]16 03:13:04 Save the image 00358D_flip.png
 36%|██████████████                         | 564/1568 [01:44<03:02,  5.50it/s]16 03:13:04 Save the image 00359D.png
 36%|██████████████                         | 565/1568 [01:44<03:01,  5.54it/s]16 03:13:04 Save the image 00359D_flip.png
 36%|██████████████                         | 566/1568 [01:44<02:59,  5.59it/s]16 03:13:04 Save the image 00360D.png
 36%|██████████████                         | 567/1568 [01:45<02:58,  5.60it/s]16 03:13:05 Save the image 00360D_flip.png
 36%|██████████████▏                        | 568/1568 [01:45<02:59,  5.57it/s]16 03:13:05 Save the image 00361D.png

 36%|██████████████▏                        | 569/1568 [01:45<02:59,  5.57it/s]16 03:13:05 Save the image 00361D_flip.png
 36%|██████████████▏                        | 570/1568 [01:45<02:59,  5.57it/s]16 03:13:05 Save the image 00362D.png
 36%|██████████████▏                        | 571/1568 [01:45<03:00,  5.51it/s]16 03:13:05 Save the image 00362D_flip.png
 36%|██████████████▏                        | 572/1568 [01:46<02:59,  5.54it/s]16 03:13:06 Save the image 00363D.png
 37%|██████████████▎                        | 573/1568 [01:46<03:01,  5.48it/s]16 03:13:06 Save the image 00363D_flip.png
 37%|██████████████▎                        | 574/1568 [01:46<03:00,  5.52it/s]16 03:13:06 Save the image 00364D.png
 37%|██████████████▎                        | 575/1568 [01:46<03:00,  5.49it/s]16 03:13:06 Save the image 00364D_flip.png
 37%|██████████████▎                        | 576/1568 [01:46<03:00,  5.50it/s]16 03:13:06 Save the image 00365D.png
 37%|██████████████▎                        | 577/1568 [01:46<03:00,  5.50it/s]16 03:13:06 Save the image 00365D_flip.png
 37%|██████████████▍                        | 578/1568 [01:47<03:00,  5.48it/s]16 03:13:07 Save the image 00366D.png
 37%|██████████████▍                        | 579/1568 [01:47<02:58,  5.53it/s]16 03:13:07 Save the image 00366D_flip.png
 37%|██████████████▍                        | 580/1568 [01:47<02:59,  5.50it/s]16 03:13:07 Save the image 00367D.png
 37%|██████████████▍                        | 581/1568 [01:47<02:59,  5.49it/s]16 03:13:07 Save the image 00367D_flip.png
 37%|██████████████▍                        | 582/1568 [01:47<03:00,  5.46it/s]16 03:13:07 Save the image 00368D.png
 37%|██████████████▌                        | 583/1568 [01:48<02:59,  5.47it/s]16 03:13:08 Save the image 00368D_flip.png
 37%|██████████████▌                        | 584/1568 [01:48<02:59,  5.48it/s]16 03:13:08 Save the image 00369D.png
 37%|██████████████▌                        | 585/1568 [01:48<03:00,  5.45it/s]16 03:13:08 Save the image 00369D_flip.png
 37%|██████████████▌                        | 586/1568 [01:48<03:00,  5.45it/s]16 03:13:08 Save the image 00370D.png
 37%|██████████████▌                        | 587/1568 [01:48<03:00,  5.43it/s]16 03:13:08 Save the image 00370D_flip.png
 38%|██████████████▋                        | 588/1568 [01:49<03:03,  5.35it/s]16 03:13:08 Save the image 00371D.png
 38%|██████████████▋                        | 589/1568 [01:49<03:02,  5.37it/s]16 03:13:09 Save the image 00371D_flip.png
 38%|██████████████▋                        | 590/1568 [01:49<03:00,  5.41it/s]16 03:13:09 Save the image 00372D.png
 38%|██████████████▋                        | 591/1568 [01:49<02:59,  5.45it/s]16 03:13:09 Save the image 00372D_flip.png
 38%|██████████████▋                        | 592/1568 [01:49<02:59,  5.43it/s]16 03:13:09 Save the image 00373D.png
 38%|██████████████▋                        | 593/1568 [01:49<02:57,  5.48it/s]16 03:13:09 Save the image 00373D_flip.png
 38%|██████████████▊                        | 594/1568 [01:50<02:57,  5.47it/s]16 03:13:10 Save the image 00374D.png
 38%|██████████████▊                        | 595/1568 [01:50<02:59,  5.43it/s]16 03:13:10 Save the image 00374D_flip.png
 38%|██████████████▊                        | 596/1568 [01:50<03:00,  5.40it/s]16 03:13:10 Save the image 00375D.png
 38%|██████████████▊                        | 597/1568 [01:50<03:02,  5.32it/s]16 03:13:10 Save the image 00375D_flip.png
 38%|██████████████▊                        | 598/1568 [01:50<03:00,  5.37it/s]16 03:13:10 Save the image 00376D.png
 38%|██████████████▉                        | 599/1568 [01:51<03:02,  5.32it/s]16 03:13:10 Save the image 00376D_flip.png
 38%|██████████████▉                        | 600/1568 [01:51<03:02,  5.29it/s]16 03:13:11 Save the image 00377D.png
 38%|██████████████▉                        | 601/1568 [01:51<03:01,  5.32it/s]16 03:13:11 Save the image 00377D_flip.png
 38%|██████████████▉                        | 602/1568 [01:51<03:02,  5.31it/s]16 03:13:11 Save the image 00378D.png
 38%|██████████████▉                        | 603/1568 [01:51<03:02,  5.29it/s]16 03:13:11 Save the image 00378D_flip.png
 39%|███████████████                        | 604/1568 [01:51<03:00,  5.34it/s]16 03:13:11 Save the image 00379D.png
 39%|███████████████                        | 605/1568 [01:52<03:00,  5.34it/s]16 03:13:12 Save the image 00379D_flip.png
 39%|███████████████                        | 606/1568 [01:52<03:00,  5.33it/s]16 03:13:12 Save the image 00380D.png
 39%|███████████████                        | 607/1568 [01:52<03:01,  5.30it/s]16 03:13:12 Save the image 00380D_flip.png
 39%|███████████████                        | 608/1568 [01:52<03:00,  5.33it/s]16 03:13:12 Save the image 00381D.png
 39%|███████████████▏                       | 609/1568 [01:52<03:00,  5.30it/s]16 03:13:12 Save the image 00381D_flip.png
 39%|███████████████▏                       | 610/1568 [01:53<02:48,  5.68it/s]16 03:13:13 Save the image 00382D.png
 39%|███████████████▏                       | 611/1568 [01:53<02:54,  5.48it/s]16 03:13:13 Save the image 00382D_flip.png
 39%|███████████████▏                       | 612/1568 [01:53<02:52,  5.55it/s]16 03:13:13 Save the image 00383D.png
 39%|███████████████▏                       | 613/1568 [01:53<02:53,  5.50it/s]16 03:13:13 Save the image 00383D_flip.png
 39%|███████████████▎                       | 614/1568 [01:53<02:56,  5.41it/s]16 03:13:13 Save the image 00384D.png
 39%|███████████████▎                       | 615/1568 [01:54<02:54,  5.45it/s]16 03:13:13 Save the image 00384D_flip.png
 39%|███████████████▎                       | 616/1568 [01:54<02:54,  5.47it/s]16 03:13:14 Save the image 00385D.png
 39%|███████████████▎                       | 617/1568 [01:54<02:56,  5.40it/s]16 03:13:14 Save the image 00385D_flip.png
 39%|███████████████▎                       | 618/1568 [01:54<02:57,  5.34it/s]16 03:13:14 Save the image 00386D.png
 39%|███████████████▍                       | 619/1568 [01:54<02:57,  5.36it/s]16 03:13:14 Save the image 00386D_flip.png
 40%|███████████████▍                       | 620/1568 [01:54<02:57,  5.34it/s]16 03:13:14 Save the image 00387D.png
 40%|███████████████▍                       | 621/1568 [01:55<02:58,  5.30it/s]16 03:13:15 Save the image 00387D_flip.png
 40%|███████████████▍                       | 622/1568 [01:55<02:58,  5.30it/s]16 03:13:15 Save the image 00388D.png
 40%|███████████████▍                       | 623/1568 [01:55<02:58,  5.30it/s]16 03:13:15 Save the image 00388D_flip.png
 40%|███████████████▌                       | 624/1568 [01:55<02:58,  5.29it/s]16 03:13:15 Save the image 00389D.png
 40%|███████████████▌                       | 625/1568 [01:55<02:57,  5.31it/s]16 03:13:15 Save the image 00389D_flip.png
 40%|███████████████▌                       | 626/1568 [01:56<02:56,  5.34it/s]16 03:13:16 Save the image 00390D.png
 40%|███████████████▌                       | 627/1568 [01:56<02:55,  5.36it/s]16 03:13:16 Save the image 00390D_flip.png
 40%|███████████████▌                       | 628/1568 [01:56<02:58,  5.27it/s]16 03:13:16 Save the image 00391D.png
 40%|███████████████▋                       | 629/1568 [01:56<02:56,  5.31it/s]16 03:13:16 Save the image 00391D_flip.png
 40%|███████████████▋                       | 630/1568 [01:56<02:56,  5.31it/s]16 03:13:16 Save the image 00392D.png
 40%|███████████████▋                       | 631/1568 [01:57<02:56,  5.31it/s]16 03:13:16 Save the image 00392D_flip.png
 40%|███████████████▋                       | 632/1568 [01:57<02:57,  5.27it/s]16 03:13:17 Save the image 00393D.png

 40%|███████████████▋                       | 633/1568 [01:57<02:56,  5.29it/s]16 03:13:17 Save the image 00393D_flip.png
 40%|███████████████▊                       | 634/1568 [01:57<02:55,  5.33it/s]16 03:13:17 Save the image 00394D.png
 40%|███████████████▊                       | 635/1568 [01:57<02:53,  5.37it/s]16 03:13:17 Save the image 00394D_flip.png
 41%|███████████████▊                       | 636/1568 [01:57<02:53,  5.39it/s]16 03:13:17 Save the image 00395D.png
 41%|███████████████▊                       | 637/1568 [01:58<02:52,  5.39it/s]16 03:13:18 Save the image 00395D_flip.png
 41%|███████████████▊                       | 638/1568 [01:58<02:54,  5.34it/s]16 03:13:18 Save the image 00396D.png
 41%|███████████████▉                       | 639/1568 [01:58<02:51,  5.42it/s]16 03:13:18 Save the image 00396D_flip.png
 41%|███████████████▉                       | 640/1568 [01:58<02:51,  5.42it/s]16 03:13:18 Save the image 00397D.png
 41%|███████████████▉                       | 641/1568 [01:58<02:50,  5.43it/s]16 03:13:18 Save the image 00397D_flip.png
 41%|███████████████▉                       | 642/1568 [01:59<02:51,  5.40it/s]16 03:13:19 Save the image 00398D.png
 41%|███████████████▉                       | 643/1568 [01:59<02:51,  5.39it/s]16 03:13:19 Save the image 00398D_flip.png
 41%|████████████████                       | 644/1568 [01:59<02:50,  5.41it/s]16 03:13:19 Save the image 00399D.png
 41%|████████████████                       | 645/1568 [01:59<02:50,  5.42it/s]16 03:13:19 Save the image 00399D_flip.png
 41%|████████████████                       | 646/1568 [01:59<02:49,  5.44it/s]16 03:13:19 Save the image 00400D.png
 41%|████████████████                       | 647/1568 [01:59<02:49,  5.42it/s]16 03:13:19 Save the image 00400D_flip.png
 41%|████████████████                       | 648/1568 [02:00<02:49,  5.43it/s]16 03:13:20 Save the image 00401D.png
 41%|████████████████▏                      | 649/1568 [02:00<02:49,  5.42it/s]16 03:13:20 Save the image 00401D_flip.png
 41%|████████████████▏                      | 650/1568 [02:00<02:50,  5.37it/s]16 03:13:20 Save the image 00402D.png
 42%|████████████████▏                      | 651/1568 [02:00<02:51,  5.34it/s]16 03:13:20 Save the image 00402D_flip.png
 42%|████████████████▏                      | 652/1568 [02:00<02:51,  5.36it/s]16 03:13:20 Save the image 00403D.png
 42%|████████████████▏                      | 653/1568 [02:01<02:49,  5.39it/s]16 03:13:21 Save the image 00403D_flip.png
 42%|████████████████▎                      | 654/1568 [02:01<02:52,  5.29it/s]16 03:13:21 Save the image 00404D.png
 42%|████████████████▎                      | 655/1568 [02:01<02:49,  5.38it/s]16 03:13:21 Save the image 00404D_flip.png
 42%|████████████████▎                      | 656/1568 [02:01<02:51,  5.32it/s]16 03:13:21 Save the image 00405D.png
 42%|████████████████▎                      | 657/1568 [02:01<02:50,  5.34it/s]16 03:13:21 Save the image 00405D_flip.png
 42%|████████████████▎                      | 658/1568 [02:02<02:49,  5.36it/s]16 03:13:21 Save the image 00406D.png
 42%|████████████████▍                      | 659/1568 [02:02<02:48,  5.39it/s]16 03:13:22 Save the image 00406D_flip.png
 42%|████████████████▍                      | 660/1568 [02:02<02:47,  5.42it/s]16 03:13:22 Save the image 00407D.png
 42%|████████████████▍                      | 661/1568 [02:02<02:47,  5.43it/s]16 03:13:22 Save the image 00407D_flip.png
 42%|████████████████▍                      | 662/1568 [02:02<02:46,  5.44it/s]16 03:13:22 Save the image 00408D.png
 42%|████████████████▍                      | 663/1568 [02:02<02:47,  5.39it/s]16 03:13:22 Save the image 00408D_flip.png
 42%|████████████████▌                      | 664/1568 [02:03<02:47,  5.40it/s]16 03:13:23 Save the image 00409D.png
 42%|████████████████▌                      | 665/1568 [02:03<02:46,  5.41it/s]16 03:13:23 Save the image 00409D_flip.png
 42%|████████████████▌                      | 666/1568 [02:03<02:46,  5.43it/s]16 03:13:23 Save the image 00410D.png
 43%|████████████████▌                      | 667/1568 [02:03<02:45,  5.45it/s]16 03:13:23 Save the image 00410D_flip.png
 43%|████████████████▌                      | 668/1568 [02:03<02:44,  5.46it/s]16 03:13:23 Save the image 00411D.png
 43%|████████████████▋                      | 669/1568 [02:04<02:44,  5.47it/s]16 03:13:24 Save the image 00411D_flip.png
 43%|████████████████▋                      | 670/1568 [02:04<02:46,  5.39it/s]16 03:13:24 Save the image 00412D.png
 43%|████████████████▋                      | 671/1568 [02:04<02:45,  5.41it/s]16 03:13:24 Save the image 00412D_flip.png
 43%|████████████████▋                      | 672/1568 [02:04<02:45,  5.43it/s]16 03:13:24 Save the image 00413D.png
 43%|████████████████▋                      | 673/1568 [02:04<02:44,  5.44it/s]16 03:13:24 Save the image 00413D_flip.png
 43%|████████████████▊                      | 674/1568 [02:04<02:44,  5.44it/s]16 03:13:24 Save the image 00414D.png
 43%|████████████████▊                      | 675/1568 [02:05<02:43,  5.45it/s]16 03:13:25 Save the image 00414D_flip.png
 43%|████████████████▊                      | 676/1568 [02:05<02:42,  5.48it/s]16 03:13:25 Save the image 00415D.png
 43%|████████████████▊                      | 677/1568 [02:05<02:43,  5.44it/s]16 03:13:25 Save the image 00415D_flip.png
 43%|████████████████▊                      | 678/1568 [02:05<02:43,  5.43it/s]16 03:13:25 Save the image 00416D.png
 43%|████████████████▉                      | 679/1568 [02:05<02:43,  5.44it/s]16 03:13:25 Save the image 00416D_flip.png
 43%|████████████████▉                      | 680/1568 [02:06<02:43,  5.42it/s]16 03:13:25 Save the image 00417D.png
 43%|████████████████▉                      | 681/1568 [02:06<02:33,  5.79it/s]16 03:13:26 Save the image 00417D_flip.png
 43%|████████████████▉                      | 682/1568 [02:06<02:36,  5.67it/s]16 03:13:26 Save the image 00418D.png
 44%|████████████████▉                      | 683/1568 [02:06<02:37,  5.63it/s]16 03:13:26 Save the image 00418D_flip.png
 44%|█████████████████                      | 684/1568 [02:06<02:38,  5.58it/s]16 03:13:26 Save the image 00419D.png
 44%|█████████████████                      | 685/1568 [02:06<02:39,  5.52it/s]16 03:13:26 Save the image 00419D_flip.png
 44%|█████████████████                      | 686/1568 [02:07<02:39,  5.54it/s]16 03:13:27 Save the image 00420D.png
 44%|█████████████████                      | 687/1568 [02:07<02:38,  5.57it/s]16 03:13:27 Save the image 00420D_flip.png
 44%|█████████████████                      | 688/1568 [02:07<02:36,  5.62it/s]16 03:13:27 Save the image 00421D.png
 44%|█████████████████▏                     | 689/1568 [02:07<02:38,  5.56it/s]16 03:13:27 Save the image 00421D_flip.png
 44%|█████████████████▏                     | 690/1568 [02:07<02:37,  5.57it/s]16 03:13:27 Save the image 00422D.png
 44%|█████████████████▏                     | 691/1568 [02:08<02:37,  5.56it/s]16 03:13:27 Save the image 00422D_flip.png
 44%|█████████████████▏                     | 692/1568 [02:08<02:38,  5.52it/s]16 03:13:28 Save the image 00423D.png
 44%|█████████████████▏                     | 693/1568 [02:08<02:37,  5.54it/s]16 03:13:28 Save the image 00423D_flip.png
 44%|█████████████████▎                     | 694/1568 [02:08<02:37,  5.55it/s]16 03:13:28 Save the image 00424D.png
 44%|█████████████████▎                     | 695/1568 [02:08<02:36,  5.59it/s]16 03:13:28 Save the image 00424D_flip.png
 44%|█████████████████▎                     | 696/1568 [02:08<02:37,  5.55it/s]16 03:13:28 Save the image 00425D.png

 44%|█████████████████▎                     | 697/1568 [02:09<02:37,  5.53it/s]16 03:13:29 Save the image 00425D_flip.png
 45%|█████████████████▎                     | 698/1568 [02:09<02:37,  5.52it/s]16 03:13:29 Save the image 00426D.png
 45%|█████████████████▍                     | 699/1568 [02:09<02:37,  5.50it/s]16 03:13:29 Save the image 00426D_flip.png
 45%|█████████████████▍                     | 700/1568 [02:09<02:38,  5.48it/s]16 03:13:29 Save the image 00427D.png
 45%|█████████████████▍                     | 701/1568 [02:09<02:36,  5.55it/s]16 03:13:29 Save the image 00427D_flip.png
 45%|█████████████████▍                     | 702/1568 [02:10<02:36,  5.52it/s]16 03:13:29 Save the image 00428D.png
 45%|█████████████████▍                     | 703/1568 [02:10<02:37,  5.50it/s]16 03:13:30 Save the image 00428D_flip.png
 45%|█████████████████▌                     | 704/1568 [02:10<02:37,  5.49it/s]16 03:13:30 Save the image 00429D.png
 45%|█████████████████▌                     | 705/1568 [02:10<02:36,  5.51it/s]16 03:13:30 Save the image 00429D_flip.png
 45%|█████████████████▌                     | 706/1568 [02:10<02:37,  5.47it/s]16 03:13:30 Save the image 00430D.png
 45%|█████████████████▌                     | 707/1568 [02:10<02:37,  5.46it/s]16 03:13:30 Save the image 00430D_flip.png
 45%|█████████████████▌                     | 708/1568 [02:11<02:37,  5.46it/s]16 03:13:31 Save the image 00431D.png
 45%|█████████████████▋                     | 709/1568 [02:11<02:37,  5.47it/s]16 03:13:31 Save the image 00431D_flip.png
 45%|█████████████████▋                     | 710/1568 [02:11<02:31,  5.65it/s]16 03:13:31 Save the image 00432D.png
 45%|█████████████████▋                     | 711/1568 [02:11<02:33,  5.59it/s]16 03:13:31 Save the image 00432D_flip.png
 45%|█████████████████▋                     | 712/1568 [02:11<02:33,  5.57it/s]16 03:13:31 Save the image 00433D.png
 45%|█████████████████▋                     | 713/1568 [02:12<02:37,  5.41it/s]16 03:13:31 Save the image 00433D_flip.png
 46%|█████████████████▊                     | 714/1568 [02:12<02:37,  5.44it/s]16 03:13:32 Save the image 00434D.png
 46%|█████████████████▊                     | 715/1568 [02:12<02:36,  5.44it/s]16 03:13:32 Save the image 00434D_flip.png
 46%|█████████████████▊                     | 716/1568 [02:12<02:36,  5.44it/s]16 03:13:32 Save the image 00435D.png
 46%|█████████████████▊                     | 717/1568 [02:12<02:27,  5.77it/s]16 03:13:32 Save the image 00435D_flip.png
 46%|█████████████████▊                     | 718/1568 [02:12<02:30,  5.65it/s]16 03:13:32 Save the image 00436D.png
 46%|█████████████████▉                     | 719/1568 [02:13<02:30,  5.64it/s]16 03:13:33 Save the image 00436D_flip.png
 46%|█████████████████▉                     | 720/1568 [02:13<02:31,  5.60it/s]16 03:13:33 Save the image 00437D.png
 46%|█████████████████▉                     | 721/1568 [02:13<02:32,  5.54it/s]16 03:13:33 Save the image 00437D_flip.png
 46%|█████████████████▉                     | 722/1568 [02:13<02:32,  5.56it/s]16 03:13:33 Save the image 00438D.png
 46%|█████████████████▉                     | 723/1568 [02:13<02:29,  5.66it/s]16 03:13:33 Save the image 00438D_flip.png
 46%|██████████████████                     | 724/1568 [02:13<02:30,  5.59it/s]16 03:13:33 Save the image 00439D.png
 46%|██████████████████                     | 725/1568 [02:14<02:32,  5.53it/s]16 03:13:34 Save the image 00439D_flip.png
 46%|██████████████████                     | 726/1568 [02:14<02:32,  5.53it/s]16 03:13:34 Save the image 00440D.png
 46%|██████████████████                     | 727/1568 [02:14<02:32,  5.52it/s]16 03:13:34 Save the image 00440D_flip.png
 46%|██████████████████                     | 728/1568 [02:14<02:33,  5.48it/s]16 03:13:34 Save the image 00441D.png
 46%|██████████████████▏                    | 729/1568 [02:14<02:31,  5.54it/s]16 03:13:34 Save the image 00441D_flip.png
 47%|██████████████████▏                    | 730/1568 [02:15<02:32,  5.51it/s]16 03:13:35 Save the image 00442D.png
 47%|██████████████████▏                    | 731/1568 [02:15<02:32,  5.48it/s]16 03:13:35 Save the image 00442D_flip.png
 47%|██████████████████▏                    | 732/1568 [02:15<02:32,  5.48it/s]16 03:13:35 Save the image 00443D.png
 47%|██████████████████▏                    | 733/1568 [02:15<02:32,  5.49it/s]16 03:13:35 Save the image 00443D_flip.png
 47%|██████████████████▎                    | 734/1568 [02:15<02:31,  5.50it/s]16 03:13:35 Save the image 00444D.png
 47%|██████████████████▎                    | 735/1568 [02:16<02:33,  5.43it/s]16 03:13:35 Save the image 00444D_flip.png
 47%|██████████████████▎                    | 736/1568 [02:16<02:31,  5.48it/s]16 03:13:36 Save the image 00445D.png
 47%|██████████████████▎                    | 737/1568 [02:16<02:32,  5.47it/s]16 03:13:36 Save the image 00445D_flip.png
 47%|██████████████████▎                    | 738/1568 [02:16<02:31,  5.47it/s]16 03:13:36 Save the image 00446D.png
 47%|██████████████████▍                    | 739/1568 [02:16<02:32,  5.45it/s]16 03:13:36 Save the image 00446D_flip.png
 47%|██████████████████▍                    | 740/1568 [02:16<02:32,  5.41it/s]16 03:13:36 Save the image 00447D.png
 47%|██████████████████▍                    | 741/1568 [02:17<02:33,  5.40it/s]16 03:13:37 Save the image 00447D_flip.png
 47%|██████████████████▍                    | 742/1568 [02:17<02:35,  5.31it/s]16 03:13:37 Save the image 00448D.png
 47%|██████████████████▍                    | 743/1568 [02:17<02:34,  5.34it/s]16 03:13:37 Save the image 00448D_flip.png
 47%|██████████████████▌                    | 744/1568 [02:17<02:33,  5.39it/s]16 03:13:37 Save the image 00449D.png
 48%|██████████████████▌                    | 745/1568 [02:17<02:32,  5.41it/s]16 03:13:37 Save the image 00449D_flip.png
 48%|██████████████████▌                    | 746/1568 [02:18<02:29,  5.51it/s]16 03:13:37 Save the image 00450D.png
 48%|██████████████████▌                    | 747/1568 [02:18<02:29,  5.50it/s]16 03:13:38 Save the image 00450D_flip.png
 48%|██████████████████▌                    | 748/1568 [02:18<02:28,  5.50it/s]16 03:13:38 Save the image 00451D.png
 48%|██████████████████▋                    | 749/1568 [02:18<02:31,  5.41it/s]16 03:13:38 Save the image 00451D_flip.png
 48%|██████████████████▋                    | 750/1568 [02:18<02:30,  5.45it/s]16 03:13:38 Save the image 00452D.png
 48%|██████████████████▋                    | 751/1568 [02:18<02:30,  5.45it/s]16 03:13:38 Save the image 00452D_flip.png
 48%|██████████████████▋                    | 752/1568 [02:19<02:30,  5.44it/s]16 03:13:39 Save the image 00453D.png
 48%|██████████████████▋                    | 753/1568 [02:19<02:21,  5.75it/s]16 03:13:39 Save the image 00453D_flip.png
 48%|██████████████████▊                    | 754/1568 [02:19<02:23,  5.66it/s]16 03:13:39 Save the image 00454D.png
 48%|██████████████████▊                    | 755/1568 [02:19<02:24,  5.64it/s]16 03:13:39 Save the image 00454D_flip.png
 48%|██████████████████▊                    | 756/1568 [02:19<02:25,  5.59it/s]16 03:13:39 Save the image 00455D.png
 48%|██████████████████▊                    | 757/1568 [02:20<02:26,  5.54it/s]16 03:13:39 Save the image 00455D_flip.png
 48%|██████████████████▊                    | 758/1568 [02:20<02:25,  5.56it/s]16 03:13:40 Save the image 00456D.png
 48%|██████████████████▉                    | 759/1568 [02:20<02:24,  5.58it/s]16 03:13:40 Save the image 00456D_flip.png
 48%|██████████████████▉                    | 760/1568 [02:20<02:24,  5.60it/s]16 03:13:40 Save the image 00457D.png

 49%|██████████████████▉                    | 761/1568 [02:20<02:25,  5.54it/s]16 03:13:40 Save the image 00457D_flip.png
 49%|██████████████████▉                    | 762/1568 [02:20<02:25,  5.54it/s]16 03:13:40 Save the image 00458D.png
 49%|██████████████████▉                    | 763/1568 [02:21<02:23,  5.61it/s]16 03:13:41 Save the image 00458D_flip.png
 49%|███████████████████                    | 764/1568 [02:21<02:24,  5.55it/s]16 03:13:41 Save the image 00459D.png
 49%|███████████████████                    | 765/1568 [02:21<02:26,  5.48it/s]16 03:13:41 Save the image 00459D_flip.png
 49%|███████████████████                    | 766/1568 [02:21<02:25,  5.52it/s]16 03:13:41 Save the image 00460D.png
 49%|███████████████████                    | 767/1568 [02:21<02:25,  5.49it/s]16 03:13:41 Save the image 00460D_flip.png
 49%|███████████████████                    | 768/1568 [02:22<02:26,  5.46it/s]16 03:13:41 Save the image 00461D.png
 49%|███████████████████▏                   | 769/1568 [02:22<02:25,  5.48it/s]16 03:13:42 Save the image 00461D_flip.png
 49%|███████████████████▏                   | 770/1568 [02:22<02:25,  5.49it/s]16 03:13:42 Save the image 00462D.png
 49%|███████████████████▏                   | 771/1568 [02:22<02:25,  5.46it/s]16 03:13:42 Save the image 00462D_flip.png
 49%|███████████████████▏                   | 772/1568 [02:22<02:24,  5.53it/s]16 03:13:42 Save the image 00463D.png
 49%|███████████████████▏                   | 773/1568 [02:22<02:25,  5.48it/s]16 03:13:42 Save the image 00463D_flip.png
 49%|███████████████████▎                   | 774/1568 [02:23<02:24,  5.48it/s]16 03:13:43 Save the image 00464D.png
 49%|███████████████████▎                   | 775/1568 [02:23<02:25,  5.45it/s]16 03:13:43 Save the image 00464D_flip.png
 49%|███████████████████▎                   | 776/1568 [02:23<02:25,  5.46it/s]16 03:13:43 Save the image 00465D.png
 50%|███████████████████▎                   | 777/1568 [02:23<02:25,  5.42it/s]16 03:13:43 Save the image 00465D_flip.png
 50%|███████████████████▎                   | 778/1568 [02:23<02:26,  5.40it/s]16 03:13:43 Save the image 00466D.png
 50%|███████████████████▍                   | 779/1568 [02:24<02:24,  5.46it/s]16 03:13:43 Save the image 00466D_flip.png
 50%|███████████████████▍                   | 780/1568 [02:24<02:24,  5.46it/s]16 03:13:44 Save the image 00478D.png
 50%|███████████████████▍                   | 781/1568 [02:24<02:24,  5.46it/s]16 03:13:44 Save the image 00478D_flip.png
 50%|███████████████████▍                   | 782/1568 [02:24<02:24,  5.44it/s]16 03:13:44 Save the image 00479D.png
 50%|███████████████████▍                   | 783/1568 [02:24<02:24,  5.43it/s]16 03:13:44 Save the image 00479D_flip.png
 50%|███████████████████▌                   | 784/1568 [02:24<02:23,  5.45it/s]16 03:13:44 Save the image 00480D.png
 50%|███████████████████▌                   | 785/1568 [02:25<02:23,  5.44it/s]16 03:13:45 Save the image 00480D_flip.png
 50%|███████████████████▌                   | 786/1568 [02:25<02:23,  5.44it/s]16 03:13:45 Save the image 00481D.png
 50%|███████████████████▌                   | 787/1568 [02:25<02:23,  5.43it/s]16 03:13:45 Save the image 00481D_flip.png
 50%|███████████████████▌                   | 788/1568 [02:25<02:23,  5.44it/s]16 03:13:45 Save the image 00482D.png
 50%|███████████████████▌                   | 789/1568 [02:25<02:23,  5.43it/s]16 03:13:45 Save the image 00482D_flip.png
 50%|███████████████████▋                   | 790/1568 [02:26<02:22,  5.45it/s]16 03:13:45 Save the image 00483D.png
 50%|███████████████████▋                   | 791/1568 [02:26<02:22,  5.46it/s]16 03:13:46 Save the image 00483D_flip.png
 51%|███████████████████▋                   | 792/1568 [02:26<02:22,  5.45it/s]16 03:13:46 Save the image 00484D.png
 51%|███████████████████▋                   | 793/1568 [02:26<02:22,  5.44it/s]16 03:13:46 Save the image 00484D_flip.png
 51%|███████████████████▋                   | 794/1568 [02:26<02:22,  5.44it/s]16 03:13:46 Save the image 00485D.png
 51%|███████████████████▊                   | 795/1568 [02:26<02:21,  5.44it/s]16 03:13:46 Save the image 00485D_flip.png
 51%|███████████████████▊                   | 796/1568 [02:27<02:22,  5.44it/s]16 03:13:47 Save the image 00486D.png
 51%|███████████████████▊                   | 797/1568 [02:27<02:21,  5.44it/s]16 03:13:47 Save the image 00486D_flip.png
 51%|███████████████████▊                   | 798/1568 [02:27<02:21,  5.44it/s]16 03:13:47 Save the image 00487D.png
 51%|███████████████████▊                   | 799/1568 [02:27<02:21,  5.42it/s]16 03:13:47 Save the image 00487D_flip.png
 51%|███████████████████▉                   | 800/1568 [02:27<02:21,  5.41it/s]16 03:13:47 Save the image 00488D.png
 51%|███████████████████▉                   | 801/1568 [02:28<02:21,  5.40it/s]16 03:13:48 Save the image 00488D_flip.png
 51%|███████████████████▉                   | 802/1568 [02:28<02:21,  5.41it/s]16 03:13:48 Save the image 00489D.png
 51%|███████████████████▉                   | 803/1568 [02:28<02:21,  5.41it/s]16 03:13:48 Save the image 00489D_flip.png
 51%|███████████████████▉                   | 804/1568 [02:28<02:21,  5.42it/s]16 03:13:48 Save the image 00490D.png
 51%|████████████████████                   | 805/1568 [02:28<02:20,  5.45it/s]16 03:13:48 Save the image 00490D_flip.png
 51%|████████████████████                   | 806/1568 [02:28<02:20,  5.43it/s]16 03:13:48 Save the image 00491D.png
 51%|████████████████████                   | 807/1568 [02:29<02:20,  5.41it/s]16 03:13:49 Save the image 00491D_flip.png
 52%|████████████████████                   | 808/1568 [02:29<02:20,  5.42it/s]16 03:13:49 Save the image 00492D.png
 52%|████████████████████                   | 809/1568 [02:29<02:19,  5.42it/s]16 03:13:49 Save the image 00492D_flip.png
 52%|████████████████████▏                  | 810/1568 [02:29<02:19,  5.41it/s]16 03:13:49 Save the image 00493D.png
 52%|████████████████████▏                  | 811/1568 [02:29<02:19,  5.42it/s]16 03:13:49 Save the image 00493D_flip.png
 52%|████████████████████▏                  | 812/1568 [02:30<02:19,  5.43it/s]16 03:13:50 Save the image 00494D.png
 52%|████████████████████▏                  | 813/1568 [02:30<02:20,  5.37it/s]16 03:13:50 Save the image 00494D_flip.png
 52%|████████████████████▏                  | 814/1568 [02:30<02:19,  5.42it/s]16 03:13:50 Save the image 00495D.png
 52%|████████████████████▎                  | 815/1568 [02:30<02:19,  5.41it/s]16 03:13:50 Save the image 00495D_flip.png
 52%|████████████████████▎                  | 816/1568 [02:30<02:18,  5.43it/s]16 03:13:50 Save the image 00496D.png
 52%|████████████████████▎                  | 817/1568 [02:31<02:18,  5.43it/s]16 03:13:50 Save the image 00496D_flip.png
 52%|████████████████████▎                  | 818/1568 [02:31<02:18,  5.43it/s]16 03:13:51 Save the image 00497D.png
 52%|████████████████████▎                  | 819/1568 [02:31<02:16,  5.48it/s]16 03:13:51 Save the image 00497D_flip.png
 52%|████████████████████▍                  | 820/1568 [02:31<02:19,  5.37it/s]16 03:13:51 Save the image 00003N.png
 52%|████████████████████▍                  | 821/1568 [02:31<02:17,  5.45it/s]16 03:13:51 Save the image 00003N_flip.png
 52%|████████████████████▍                  | 822/1568 [02:31<02:17,  5.44it/s]16 03:13:51 Save the image 00004N.png
 52%|████████████████████▍                  | 823/1568 [02:32<02:16,  5.44it/s]16 03:13:52 Save the image 00004N_flip.png
 53%|████████████████████▍                  | 824/1568 [02:32<02:17,  5.43it/s]16 03:13:52 Save the image 00005N.png

 53%|████████████████████▌                  | 825/1568 [02:32<02:16,  5.43it/s]16 03:13:52 Save the image 00005N_flip.png
 53%|████████████████████▌                  | 826/1568 [02:32<02:16,  5.44it/s]16 03:13:52 Save the image 00006N.png
 53%|████████████████████▌                  | 827/1568 [02:32<02:16,  5.41it/s]16 03:13:52 Save the image 00006N_flip.png
 53%|████████████████████▌                  | 828/1568 [02:33<02:16,  5.40it/s]16 03:13:52 Save the image 00007N.png
 53%|████████████████████▌                  | 829/1568 [02:33<02:16,  5.41it/s]16 03:13:53 Save the image 00007N_flip.png
 53%|████████████████████▋                  | 830/1568 [02:33<02:16,  5.42it/s]16 03:13:53 Save the image 00008N.png
 53%|████████████████████▋                  | 831/1568 [02:33<02:16,  5.41it/s]16 03:13:53 Save the image 00008N_flip.png
 53%|████████████████████▋                  | 832/1568 [02:33<02:15,  5.43it/s]16 03:13:53 Save the image 00009N.png
 53%|████████████████████▋                  | 833/1568 [02:33<02:15,  5.44it/s]16 03:13:53 Save the image 00009N_flip.png
 53%|████████████████████▋                  | 834/1568 [02:34<02:15,  5.43it/s]16 03:13:54 Save the image 00010N.png
 53%|████████████████████▊                  | 835/1568 [02:34<02:15,  5.41it/s]16 03:13:54 Save the image 00010N_flip.png
 53%|████████████████████▊                  | 836/1568 [02:34<02:15,  5.41it/s]16 03:13:54 Save the image 00011N.png
 53%|████████████████████▊                  | 837/1568 [02:34<02:14,  5.43it/s]16 03:13:54 Save the image 00011N_flip.png
 53%|████████████████████▊                  | 838/1568 [02:34<02:14,  5.43it/s]16 03:13:54 Save the image 00012N.png
 54%|████████████████████▊                  | 839/1568 [02:35<02:14,  5.42it/s]16 03:13:55 Save the image 00012N_flip.png
 54%|████████████████████▉                  | 840/1568 [02:35<02:13,  5.45it/s]16 03:13:55 Save the image 00013N.png
 54%|████████████████████▉                  | 841/1568 [02:35<02:12,  5.50it/s]16 03:13:55 Save the image 00013N_flip.png
 54%|████████████████████▉                  | 842/1568 [02:35<02:12,  5.47it/s]16 03:13:55 Save the image 00014N.png
 54%|████████████████████▉                  | 843/1568 [02:35<02:12,  5.46it/s]16 03:13:55 Save the image 00014N_flip.png
 54%|████████████████████▉                  | 844/1568 [02:35<02:12,  5.47it/s]16 03:13:55 Save the image 00015N.png
 54%|█████████████████████                  | 845/1568 [02:36<02:12,  5.46it/s]16 03:13:56 Save the image 00015N_flip.png
 54%|█████████████████████                  | 846/1568 [02:36<02:12,  5.47it/s]16 03:13:56 Save the image 00016N.png
 54%|█████████████████████                  | 847/1568 [02:36<02:11,  5.47it/s]16 03:13:56 Save the image 00016N_flip.png
 54%|█████████████████████                  | 848/1568 [02:36<02:14,  5.36it/s]16 03:13:56 Save the image 00017N.png
 54%|█████████████████████                  | 849/1568 [02:36<02:12,  5.43it/s]16 03:13:56 Save the image 00017N_flip.png
 54%|█████████████████████▏                 | 850/1568 [02:37<02:12,  5.42it/s]16 03:13:57 Save the image 00018N.png
 54%|█████████████████████▏                 | 851/1568 [02:37<02:12,  5.41it/s]16 03:13:57 Save the image 00018N_flip.png
 54%|█████████████████████▏                 | 852/1568 [02:37<02:12,  5.41it/s]16 03:13:57 Save the image 00019N.png
 54%|█████████████████████▏                 | 853/1568 [02:37<02:11,  5.42it/s]16 03:13:57 Save the image 00019N_flip.png
 54%|█████████████████████▏                 | 854/1568 [02:37<02:11,  5.44it/s]16 03:13:57 Save the image 00020N.png
 55%|█████████████████████▎                 | 855/1568 [02:38<02:11,  5.43it/s]16 03:13:57 Save the image 00020N_flip.png
 55%|█████████████████████▎                 | 856/1568 [02:38<02:10,  5.44it/s]16 03:13:58 Save the image 00021N.png
 55%|█████████████████████▎                 | 857/1568 [02:38<02:10,  5.45it/s]16 03:13:58 Save the image 00021N_flip.png
 55%|█████████████████████▎                 | 858/1568 [02:38<02:10,  5.45it/s]16 03:13:58 Save the image 00022N.png
 55%|█████████████████████▎                 | 859/1568 [02:38<02:09,  5.48it/s]16 03:13:58 Save the image 00022N_flip.png
 55%|█████████████████████▍                 | 860/1568 [02:38<02:09,  5.48it/s]16 03:13:58 Save the image 00023N.png
 55%|█████████████████████▍                 | 861/1568 [02:39<02:08,  5.49it/s]16 03:13:59 Save the image 00023N_flip.png
 55%|█████████████████████▍                 | 862/1568 [02:39<02:10,  5.40it/s]16 03:13:59 Save the image 00024N.png
 55%|█████████████████████▍                 | 863/1568 [02:39<02:10,  5.40it/s]16 03:13:59 Save the image 00024N_flip.png
 55%|█████████████████████▍                 | 864/1568 [02:39<02:10,  5.41it/s]16 03:13:59 Save the image 00025N.png
 55%|█████████████████████▌                 | 865/1568 [02:39<02:09,  5.43it/s]16 03:13:59 Save the image 00025N_flip.png
 55%|█████████████████████▌                 | 866/1568 [02:40<02:08,  5.46it/s]16 03:13:59 Save the image 00026N.png
 55%|█████████████████████▌                 | 867/1568 [02:40<02:08,  5.44it/s]16 03:14:00 Save the image 00026N_flip.png
 55%|█████████████████████▌                 | 868/1568 [02:40<02:07,  5.48it/s]16 03:14:00 Save the image 00027N.png
 55%|█████████████████████▌                 | 869/1568 [02:40<02:08,  5.43it/s]16 03:14:00 Save the image 00027N_flip.png
 55%|█████████████████████▋                 | 870/1568 [02:40<02:08,  5.43it/s]16 03:14:00 Save the image 00028N.png
 56%|█████████████████████▋                 | 871/1568 [02:40<02:08,  5.43it/s]16 03:14:00 Save the image 00028N_flip.png
 56%|█████████████████████▋                 | 872/1568 [02:41<02:07,  5.44it/s]16 03:14:01 Save the image 00029N.png
 56%|█████████████████████▋                 | 873/1568 [02:41<02:07,  5.47it/s]16 03:14:01 Save the image 00029N_flip.png
 56%|█████████████████████▋                 | 874/1568 [02:41<02:06,  5.47it/s]16 03:14:01 Save the image 00030N.png
 56%|█████████████████████▊                 | 875/1568 [02:41<02:06,  5.49it/s]16 03:14:01 Save the image 00030N_flip.png
 56%|█████████████████████▊                 | 876/1568 [02:41<02:09,  5.35it/s]16 03:14:01 Save the image 00031N.png
 56%|█████████████████████▊                 | 877/1568 [02:42<02:07,  5.44it/s]16 03:14:01 Save the image 00031N_flip.png
 56%|█████████████████████▊                 | 878/1568 [02:42<02:06,  5.46it/s]16 03:14:02 Save the image 00032N.png
 56%|█████████████████████▊                 | 879/1568 [02:42<02:06,  5.46it/s]16 03:14:02 Save the image 00032N_flip.png
 56%|█████████████████████▉                 | 880/1568 [02:42<02:00,  5.73it/s]16 03:14:02 Save the image 00033N.png
 56%|█████████████████████▉                 | 881/1568 [02:42<02:01,  5.64it/s]16 03:14:02 Save the image 00033N_flip.png
 56%|█████████████████████▉                 | 882/1568 [02:42<02:01,  5.63it/s]16 03:14:02 Save the image 00034N.png
 56%|█████████████████████▉                 | 883/1568 [02:43<02:02,  5.57it/s]16 03:14:03 Save the image 00034N_flip.png
 56%|█████████████████████▉                 | 884/1568 [02:43<02:05,  5.46it/s]16 03:14:03 Save the image 00035N.png
 56%|██████████████████████                 | 885/1568 [02:43<02:04,  5.47it/s]16 03:14:03 Save the image 00035N_flip.png
 57%|██████████████████████                 | 886/1568 [02:43<02:03,  5.52it/s]16 03:14:03 Save the image 00036N.png
 57%|██████████████████████                 | 887/1568 [02:43<01:58,  5.77it/s]16 03:14:03 Save the image 00036N_flip.png
 57%|██████████████████████                 | 888/1568 [02:44<02:01,  5.58it/s]16 03:14:03 Save the image 00037N.png

 57%|██████████████████████                 | 889/1568 [02:44<02:01,  5.57it/s]16 03:14:04 Save the image 00037N_flip.png
 57%|██████████████████████▏                | 890/1568 [02:44<02:01,  5.58it/s]16 03:14:04 Save the image 00038N.png
 57%|██████████████████████▏                | 891/1568 [02:44<02:02,  5.53it/s]16 03:14:04 Save the image 00038N_flip.png
 57%|██████████████████████▏                | 892/1568 [02:44<02:01,  5.58it/s]16 03:14:04 Save the image 00039N.png
 57%|██████████████████████▏                | 893/1568 [02:44<02:00,  5.60it/s]16 03:14:04 Save the image 00039N_flip.png
 57%|██████████████████████▏                | 894/1568 [02:45<02:01,  5.56it/s]16 03:14:05 Save the image 00040N.png
 57%|██████████████████████▎                | 895/1568 [02:45<02:01,  5.53it/s]16 03:14:05 Save the image 00040N_flip.png
 57%|██████████████████████▎                | 896/1568 [02:45<02:01,  5.55it/s]16 03:14:05 Save the image 00041N.png
 57%|██████████████████████▎                | 897/1568 [02:45<02:00,  5.55it/s]16 03:14:05 Save the image 00041N_flip.png
 57%|██████████████████████▎                | 898/1568 [02:45<02:01,  5.51it/s]16 03:14:05 Save the image 00042N.png
 57%|██████████████████████▎                | 899/1568 [02:46<02:01,  5.51it/s]16 03:14:05 Save the image 00042N_flip.png
 57%|██████████████████████▍                | 900/1568 [02:46<02:01,  5.50it/s]16 03:14:06 Save the image 00043N.png
 57%|██████████████████████▍                | 901/1568 [02:46<02:01,  5.50it/s]16 03:14:06 Save the image 00043N_flip.png
 58%|██████████████████████▍                | 902/1568 [02:46<02:00,  5.51it/s]16 03:14:06 Save the image 00044N.png
 58%|██████████████████████▍                | 903/1568 [02:46<02:01,  5.48it/s]16 03:14:06 Save the image 00044N_flip.png
 58%|██████████████████████▍                | 904/1568 [02:46<02:02,  5.41it/s]16 03:14:06 Save the image 00047N.png
 58%|██████████████████████▌                | 905/1568 [02:47<02:01,  5.48it/s]16 03:14:07 Save the image 00047N_flip.png
 58%|██████████████████████▌                | 906/1568 [02:47<02:01,  5.45it/s]16 03:14:07 Save the image 00048N.png
 58%|██████████████████████▌                | 907/1568 [02:47<02:01,  5.44it/s]16 03:14:07 Save the image 00048N_flip.png
 58%|██████████████████████▌                | 908/1568 [02:47<02:01,  5.45it/s]16 03:14:07 Save the image 00049N.png
 58%|██████████████████████▌                | 909/1568 [02:47<02:01,  5.44it/s]16 03:14:07 Save the image 00049N_flip.png
 58%|██████████████████████▋                | 910/1568 [02:48<02:00,  5.45it/s]16 03:14:07 Save the image 00050N.png
 58%|██████████████████████▋                | 911/1568 [02:48<02:00,  5.47it/s]16 03:14:08 Save the image 00050N_flip.png
 58%|██████████████████████▋                | 912/1568 [02:48<02:00,  5.44it/s]16 03:14:08 Save the image 00051N.png
 58%|██████████████████████▋                | 913/1568 [02:48<02:00,  5.45it/s]16 03:14:08 Save the image 00051N_flip.png
 58%|██████████████████████▋                | 914/1568 [02:48<01:59,  5.46it/s]16 03:14:08 Save the image 00052N.png
 58%|██████████████████████▊                | 915/1568 [02:48<01:59,  5.46it/s]16 03:14:08 Save the image 00052N_flip.png
 58%|██████████████████████▊                | 916/1568 [02:49<01:59,  5.47it/s]16 03:14:09 Save the image 00053N.png
 58%|██████████████████████▊                | 917/1568 [02:49<01:58,  5.48it/s]16 03:14:09 Save the image 00053N_flip.png
 59%|██████████████████████▊                | 918/1568 [02:49<01:58,  5.48it/s]16 03:14:09 Save the image 00054N.png
 59%|██████████████████████▊                | 919/1568 [02:49<02:01,  5.36it/s]16 03:14:09 Save the image 00054N_flip.png
 59%|██████████████████████▉                | 920/1568 [02:49<02:00,  5.38it/s]16 03:14:09 Save the image 00678N.png
 59%|██████████████████████▉                | 921/1568 [02:50<01:59,  5.40it/s]16 03:14:09 Save the image 00678N_flip.png
 59%|██████████████████████▉                | 922/1568 [02:50<01:59,  5.42it/s]16 03:14:10 Save the image 00679N.png
 59%|██████████████████████▉                | 923/1568 [02:50<01:58,  5.43it/s]16 03:14:10 Save the image 00679N_flip.png
 59%|██████████████████████▉                | 924/1568 [02:50<01:58,  5.44it/s]16 03:14:10 Save the image 00680N.png
 59%|███████████████████████                | 925/1568 [02:50<01:57,  5.46it/s]16 03:14:10 Save the image 00680N_flip.png
 59%|███████████████████████                | 926/1568 [02:50<01:57,  5.45it/s]16 03:14:10 Save the image 00681N.png
 59%|███████████████████████                | 927/1568 [02:51<01:57,  5.44it/s]16 03:14:11 Save the image 00681N_flip.png
 59%|███████████████████████                | 928/1568 [02:51<01:57,  5.45it/s]16 03:14:11 Save the image 00682N.png
 59%|███████████████████████                | 929/1568 [02:51<01:57,  5.46it/s]16 03:14:11 Save the image 00682N_flip.png
 59%|███████████████████████▏               | 930/1568 [02:51<01:53,  5.65it/s]16 03:14:11 Save the image 00683N.png
 59%|███████████████████████▏               | 931/1568 [02:51<01:52,  5.64it/s]16 03:14:11 Save the image 00683N_flip.png
 59%|███████████████████████▏               | 932/1568 [02:52<01:54,  5.58it/s]16 03:14:11 Save the image 00684N.png
 60%|███████████████████████▏               | 933/1568 [02:52<01:53,  5.61it/s]16 03:14:12 Save the image 00684N_flip.png
 60%|███████████████████████▏               | 934/1568 [02:52<01:53,  5.57it/s]16 03:14:12 Save the image 00685N.png
 60%|███████████████████████▎               | 935/1568 [02:52<01:54,  5.52it/s]16 03:14:12 Save the image 00685N_flip.png
 60%|███████████████████████▎               | 936/1568 [02:52<01:53,  5.57it/s]16 03:14:12 Save the image 00686N.png
 60%|███████████████████████▎               | 937/1568 [02:52<01:50,  5.69it/s]16 03:14:12 Save the image 00686N_flip.png
 60%|███████████████████████▎               | 938/1568 [02:53<01:52,  5.60it/s]16 03:14:13 Save the image 00687N.png
 60%|███████████████████████▎               | 939/1568 [02:53<01:53,  5.55it/s]16 03:14:13 Save the image 00687N_flip.png
 60%|███████████████████████▍               | 940/1568 [02:53<01:54,  5.49it/s]16 03:14:13 Save the image 00688N.png
 60%|███████████████████████▍               | 941/1568 [02:53<01:55,  5.43it/s]16 03:14:13 Save the image 00688N_flip.png
 60%|███████████████████████▍               | 942/1568 [02:53<01:52,  5.57it/s]16 03:14:13 Save the image 00689N.png
 60%|███████████████████████▍               | 943/1568 [02:54<01:53,  5.53it/s]16 03:14:13 Save the image 00689N_flip.png
 60%|███████████████████████▍               | 944/1568 [02:54<01:55,  5.40it/s]16 03:14:14 Save the image 00690N.png
 60%|███████████████████████▌               | 945/1568 [02:54<01:55,  5.41it/s]16 03:14:14 Save the image 00690N_flip.png
 60%|███████████████████████▌               | 946/1568 [02:54<01:54,  5.41it/s]16 03:14:14 Save the image 00691N.png
 60%|███████████████████████▌               | 947/1568 [02:54<01:53,  5.47it/s]16 03:14:14 Save the image 00691N_flip.png
 60%|███████████████████████▌               | 948/1568 [02:54<01:54,  5.44it/s]16 03:14:14 Save the image 00692N.png
 61%|███████████████████████▌               | 949/1568 [02:55<01:54,  5.42it/s]16 03:14:15 Save the image 00692N_flip.png
 61%|███████████████████████▋               | 950/1568 [02:55<01:54,  5.38it/s]16 03:14:15 Save the image 00693N.png
 61%|███████████████████████▋               | 951/1568 [02:55<01:54,  5.38it/s]16 03:14:15 Save the image 00693N_flip.png
 61%|███████████████████████▋               | 952/1568 [02:55<01:47,  5.72it/s]16 03:14:15 Save the image 00694N.png

 61%|███████████████████████▋               | 953/1568 [02:55<01:49,  5.61it/s]16 03:14:15 Save the image 00694N_flip.png
 61%|███████████████████████▋               | 954/1568 [02:56<01:49,  5.61it/s]16 03:14:15 Save the image 00695N.png
 61%|███████████████████████▊               | 955/1568 [02:56<01:50,  5.56it/s]16 03:14:16 Save the image 00695N_flip.png
 61%|███████████████████████▊               | 956/1568 [02:56<01:51,  5.51it/s]16 03:14:16 Save the image 00696N.png
 61%|███████████████████████▊               | 957/1568 [02:56<01:49,  5.57it/s]16 03:14:16 Save the image 00696N_flip.png
 61%|███████████████████████▊               | 958/1568 [02:56<01:49,  5.59it/s]16 03:14:16 Save the image 00697N.png
 61%|███████████████████████▊               | 959/1568 [02:56<01:48,  5.59it/s]16 03:14:16 Save the image 00697N_flip.png
 61%|███████████████████████▉               | 960/1568 [02:57<01:49,  5.53it/s]16 03:14:17 Save the image 00698N.png
 61%|███████████████████████▉               | 961/1568 [02:57<01:49,  5.53it/s]16 03:14:17 Save the image 00698N_flip.png
 61%|███████████████████████▉               | 962/1568 [02:57<01:49,  5.52it/s]16 03:14:17 Save the image 00699N.png
 61%|███████████████████████▉               | 963/1568 [02:57<01:50,  5.48it/s]16 03:14:17 Save the image 00699N_flip.png
 61%|███████████████████████▉               | 964/1568 [02:57<01:49,  5.50it/s]16 03:14:17 Save the image 00700N.png
 62%|████████████████████████               | 965/1568 [02:58<01:49,  5.53it/s]16 03:14:17 Save the image 00700N_flip.png
 62%|████████████████████████               | 966/1568 [02:58<01:49,  5.50it/s]16 03:14:18 Save the image 00701N.png
 62%|████████████████████████               | 967/1568 [02:58<01:50,  5.46it/s]16 03:14:18 Save the image 00701N_flip.png
 62%|████████████████████████               | 968/1568 [02:58<01:49,  5.48it/s]16 03:14:18 Save the image 00702N.png
 62%|████████████████████████               | 969/1568 [02:58<01:49,  5.47it/s]16 03:14:18 Save the image 00702N_flip.png
 62%|████████████████████████▏              | 970/1568 [02:58<01:50,  5.40it/s]16 03:14:18 Save the image 00703N.png
 62%|████████████████████████▏              | 971/1568 [02:59<01:50,  5.43it/s]16 03:14:19 Save the image 00703N_flip.png
 62%|████████████████████████▏              | 972/1568 [02:59<01:50,  5.39it/s]16 03:14:19 Save the image 00704N.png
 62%|████████████████████████▏              | 973/1568 [02:59<01:50,  5.38it/s]16 03:14:19 Save the image 00704N_flip.png
 62%|████████████████████████▏              | 974/1568 [02:59<01:51,  5.34it/s]16 03:14:19 Save the image 00705N.png
 62%|████████████████████████▎              | 975/1568 [02:59<01:49,  5.41it/s]16 03:14:19 Save the image 00705N_flip.png
 62%|████████████████████████▎              | 976/1568 [03:00<01:49,  5.42it/s]16 03:14:19 Save the image 00706N.png
 62%|████████████████████████▎              | 977/1568 [03:00<01:49,  5.38it/s]16 03:14:20 Save the image 00706N_flip.png
 62%|████████████████████████▎              | 978/1568 [03:00<01:50,  5.33it/s]16 03:14:20 Save the image 00707N.png
 62%|████████████████████████▎              | 979/1568 [03:00<01:49,  5.36it/s]16 03:14:20 Save the image 00707N_flip.png
 62%|████████████████████████▍              | 980/1568 [03:00<01:49,  5.36it/s]16 03:14:20 Save the image 00708N.png
 63%|████████████████████████▍              | 981/1568 [03:00<01:48,  5.40it/s]16 03:14:20 Save the image 00708N_flip.png
 63%|████████████████████████▍              | 982/1568 [03:01<01:49,  5.35it/s]16 03:14:21 Save the image 00709N.png
 63%|████████████████████████▍              | 983/1568 [03:01<01:47,  5.45it/s]16 03:14:21 Save the image 00709N_flip.png
 63%|████████████████████████▍              | 984/1568 [03:01<01:47,  5.42it/s]16 03:14:21 Save the image 00710N.png
 63%|████████████████████████▍              | 985/1568 [03:01<01:47,  5.43it/s]16 03:14:21 Save the image 00710N_flip.png
 63%|████████████████████████▌              | 986/1568 [03:01<01:47,  5.42it/s]16 03:14:21 Save the image 00711N.png
 63%|████████████████████████▌              | 987/1568 [03:02<01:45,  5.48it/s]16 03:14:21 Save the image 00711N_flip.png
 63%|████████████████████████▌              | 988/1568 [03:02<01:40,  5.75it/s]16 03:14:22 Save the image 00712N.png
 63%|████████████████████████▌              | 989/1568 [03:02<01:42,  5.65it/s]16 03:14:22 Save the image 00712N_flip.png
 63%|████████████████████████▌              | 990/1568 [03:02<01:43,  5.60it/s]16 03:14:22 Save the image 00713N.png
 63%|████████████████████████▋              | 991/1568 [03:02<01:43,  5.57it/s]16 03:14:22 Save the image 00713N_flip.png
 63%|████████████████████████▋              | 992/1568 [03:02<01:44,  5.53it/s]16 03:14:22 Save the image 00714N.png
 63%|████████████████████████▋              | 993/1568 [03:03<01:43,  5.57it/s]16 03:14:23 Save the image 00714N_flip.png
 63%|████████████████████████▋              | 994/1568 [03:03<01:43,  5.53it/s]16 03:14:23 Save the image 00715N.png
 63%|████████████████████████▋              | 995/1568 [03:03<01:44,  5.50it/s]16 03:14:23 Save the image 00715N_flip.png
 64%|████████████████████████▊              | 996/1568 [03:03<01:44,  5.48it/s]16 03:14:23 Save the image 00716N.png
 64%|████████████████████████▊              | 997/1568 [03:03<01:43,  5.50it/s]16 03:14:23 Save the image 00716N_flip.png
 64%|████████████████████████▊              | 998/1568 [03:04<01:43,  5.51it/s]16 03:14:24 Save the image 00717N.png
 64%|████████████████████████▊              | 999/1568 [03:04<01:43,  5.50it/s]16 03:14:24 Save the image 00717N_flip.png
 64%|████████████████████████▏             | 1000/1568 [03:04<01:43,  5.49it/s]16 03:14:24 Save the image 00718N.png
 64%|████████████████████████▎             | 1001/1568 [03:04<01:43,  5.47it/s]16 03:14:24 Save the image 00718N_flip.png
 64%|████████████████████████▎             | 1002/1568 [03:04<01:43,  5.47it/s]16 03:14:24 Save the image 00719N.png
 64%|████████████████████████▎             | 1003/1568 [03:04<01:44,  5.41it/s]16 03:14:24 Save the image 00719N_flip.png
 64%|████████████████████████▎             | 1004/1568 [03:05<01:44,  5.40it/s]16 03:14:25 Save the image 00720N.png
 64%|████████████████████████▎             | 1005/1568 [03:05<01:42,  5.50it/s]16 03:14:25 Save the image 00720N_flip.png
 64%|████████████████████████▍             | 1006/1568 [03:05<01:43,  5.41it/s]16 03:14:25 Save the image 00721N.png
 64%|████████████████████████▍             | 1007/1568 [03:05<01:44,  5.36it/s]16 03:14:25 Save the image 00721N_flip.png
 64%|████████████████████████▍             | 1008/1568 [03:05<01:44,  5.38it/s]16 03:14:25 Save the image 00722N.png
 64%|████████████████████████▍             | 1009/1568 [03:06<01:43,  5.38it/s]16 03:14:26 Save the image 00722N_flip.png
 64%|████████████████████████▍             | 1010/1568 [03:06<01:38,  5.65it/s]16 03:14:26 Save the image 00723N.png
 64%|████████████████████████▌             | 1011/1568 [03:06<01:40,  5.53it/s]16 03:14:26 Save the image 00723N_flip.png
 65%|████████████████████████▌             | 1012/1568 [03:06<01:40,  5.53it/s]16 03:14:26 Save the image 00724N.png
 65%|████████████████████████▌             | 1013/1568 [03:06<01:40,  5.53it/s]16 03:14:26 Save the image 00724N_flip.png
 65%|████████████████████████▌             | 1014/1568 [03:06<01:40,  5.51it/s]16 03:14:26 Save the image 00725N.png
 65%|████████████████████████▌             | 1015/1568 [03:07<01:39,  5.56it/s]16 03:14:27 Save the image 00725N_flip.png
 65%|████████████████████████▌             | 1016/1568 [03:07<01:39,  5.56it/s]16 03:14:27 Save the image 00726N.png

 65%|████████████████████████▋             | 1017/1568 [03:07<01:41,  5.44it/s]16 03:14:27 Save the image 00726N_flip.png
 65%|████████████████████████▋             | 1018/1568 [03:07<01:41,  5.42it/s]16 03:14:27 Save the image 00727N.png
 65%|████████████████████████▋             | 1019/1568 [03:07<01:40,  5.47it/s]16 03:14:27 Save the image 00727N_flip.png
 65%|████████████████████████▋             | 1020/1568 [03:08<01:39,  5.49it/s]16 03:14:28 Save the image 00728N.png
 65%|████████████████████████▋             | 1021/1568 [03:08<01:41,  5.40it/s]16 03:14:28 Save the image 00728N_flip.png
 65%|████████████████████████▊             | 1022/1568 [03:08<01:40,  5.41it/s]16 03:14:28 Save the image 00729N.png
 65%|████████████████████████▊             | 1023/1568 [03:08<01:40,  5.41it/s]16 03:14:28 Save the image 00729N_flip.png
 65%|████████████████████████▊             | 1024/1568 [03:08<01:41,  5.38it/s]16 03:14:28 Save the image 00730N.png
 65%|████████████████████████▊             | 1025/1568 [03:09<01:40,  5.39it/s]16 03:14:28 Save the image 00730N_flip.png
 65%|████████████████████████▊             | 1026/1568 [03:09<01:40,  5.42it/s]16 03:14:29 Save the image 00731N.png
 65%|████████████████████████▉             | 1027/1568 [03:09<01:39,  5.44it/s]16 03:14:29 Save the image 00731N_flip.png
 66%|████████████████████████▉             | 1028/1568 [03:09<01:39,  5.41it/s]16 03:14:29 Save the image 00732N.png
 66%|████████████████████████▉             | 1029/1568 [03:09<01:39,  5.42it/s]16 03:14:29 Save the image 00732N_flip.png
 66%|████████████████████████▉             | 1030/1568 [03:09<01:39,  5.41it/s]16 03:14:29 Save the image 00733N.png
 66%|████████████████████████▉             | 1031/1568 [03:10<01:39,  5.42it/s]16 03:14:30 Save the image 00733N_flip.png
 66%|█████████████████████████             | 1032/1568 [03:10<01:39,  5.39it/s]16 03:14:30 Save the image 00734N.png
 66%|█████████████████████████             | 1033/1568 [03:10<01:38,  5.45it/s]16 03:14:30 Save the image 00734N_flip.png
 66%|█████████████████████████             | 1034/1568 [03:10<01:37,  5.48it/s]16 03:14:30 Save the image 00735N.png
 66%|█████████████████████████             | 1035/1568 [03:10<01:38,  5.40it/s]16 03:14:30 Save the image 00735N_flip.png
 66%|█████████████████████████             | 1036/1568 [03:11<01:38,  5.39it/s]16 03:14:30 Save the image 00736N.png
 66%|█████████████████████████▏            | 1037/1568 [03:11<01:38,  5.39it/s]16 03:14:31 Save the image 00736N_flip.png
 66%|█████████████████████████▏            | 1038/1568 [03:11<01:38,  5.36it/s]16 03:14:31 Save the image 00737N.png
 66%|█████████████████████████▏            | 1039/1568 [03:11<01:36,  5.47it/s]16 03:14:31 Save the image 00737N_flip.png
 66%|█████████████████████████▏            | 1040/1568 [03:11<01:36,  5.45it/s]16 03:14:31 Save the image 00738N.png
 66%|█████████████████████████▏            | 1041/1568 [03:11<01:36,  5.46it/s]16 03:14:31 Save the image 00738N_flip.png
 66%|█████████████████████████▎            | 1042/1568 [03:12<01:37,  5.38it/s]16 03:14:32 Save the image 00739N.png
 67%|█████████████████████████▎            | 1043/1568 [03:12<01:37,  5.38it/s]16 03:14:32 Save the image 00739N_flip.png
 67%|█████████████████████████▎            | 1044/1568 [03:12<01:37,  5.39it/s]16 03:14:32 Save the image 00740N.png
 67%|█████████████████████████▎            | 1045/1568 [03:12<01:36,  5.40it/s]16 03:14:32 Save the image 00740N_flip.png
 67%|█████████████████████████▎            | 1046/1568 [03:12<01:30,  5.75it/s]16 03:14:32 Save the image 00741N.png
 67%|█████████████████████████▎            | 1047/1568 [03:13<01:32,  5.65it/s]16 03:14:32 Save the image 00741N_flip.png
 67%|█████████████████████████▍            | 1048/1568 [03:13<01:32,  5.63it/s]16 03:14:33 Save the image 00742N.png
 67%|█████████████████████████▍            | 1049/1568 [03:13<01:32,  5.61it/s]16 03:14:33 Save the image 00742N_flip.png
 67%|█████████████████████████▍            | 1050/1568 [03:13<01:33,  5.55it/s]16 03:14:33 Save the image 00743N.png
 67%|█████████████████████████▍            | 1051/1568 [03:13<01:32,  5.57it/s]16 03:14:33 Save the image 00743N_flip.png
 67%|█████████████████████████▍            | 1052/1568 [03:13<01:32,  5.60it/s]16 03:14:33 Save the image 00744N.png
 67%|█████████████████████████▌            | 1053/1568 [03:14<01:32,  5.55it/s]16 03:14:34 Save the image 00744N_flip.png
 67%|█████████████████████████▌            | 1054/1568 [03:14<01:33,  5.52it/s]16 03:14:34 Save the image 00745N.png
 67%|█████████████████████████▌            | 1055/1568 [03:14<01:32,  5.52it/s]16 03:14:34 Save the image 00745N_flip.png
 67%|█████████████████████████▌            | 1056/1568 [03:14<01:32,  5.52it/s]16 03:14:34 Save the image 00746N.png
 67%|█████████████████████████▌            | 1057/1568 [03:14<01:33,  5.49it/s]16 03:14:34 Save the image 00746N_flip.png
 67%|█████████████████████████▋            | 1058/1568 [03:15<01:32,  5.54it/s]16 03:14:34 Save the image 00747N.png
 68%|█████████████████████████▋            | 1059/1568 [03:15<01:33,  5.45it/s]16 03:14:35 Save the image 00747N_flip.png
 68%|█████████████████████████▋            | 1060/1568 [03:15<01:34,  5.40it/s]16 03:14:35 Save the image 00748N.png
 68%|█████████████████████████▋            | 1061/1568 [03:15<01:33,  5.42it/s]16 03:14:35 Save the image 00748N_flip.png
 68%|█████████████████████████▋            | 1062/1568 [03:15<01:33,  5.41it/s]16 03:14:35 Save the image 00749N.png
 68%|█████████████████████████▊            | 1063/1568 [03:15<01:33,  5.38it/s]16 03:14:35 Save the image 00749N_flip.png
 68%|█████████████████████████▊            | 1064/1568 [03:16<01:33,  5.36it/s]16 03:14:36 Save the image 00750N.png
 68%|█████████████████████████▊            | 1065/1568 [03:16<01:34,  5.30it/s]16 03:14:36 Save the image 00750N_flip.png
 68%|█████████████████████████▊            | 1066/1568 [03:16<01:34,  5.34it/s]16 03:14:36 Save the image 00751N.png
 68%|█████████████████████████▊            | 1067/1568 [03:16<01:33,  5.37it/s]16 03:14:36 Save the image 00751N_flip.png
 68%|█████████████████████████▉            | 1068/1568 [03:16<01:32,  5.42it/s]16 03:14:36 Save the image 00752N.png
 68%|█████████████████████████▉            | 1069/1568 [03:17<01:32,  5.41it/s]16 03:14:37 Save the image 00752N_flip.png
 68%|█████████████████████████▉            | 1070/1568 [03:17<01:31,  5.42it/s]16 03:14:37 Save the image 00753N.png
 68%|█████████████████████████▉            | 1071/1568 [03:17<01:32,  5.39it/s]16 03:14:37 Save the image 00753N_flip.png
 68%|█████████████████████████▉            | 1072/1568 [03:17<01:31,  5.41it/s]16 03:14:37 Save the image 00754N.png
 68%|██████████████████████████            | 1073/1568 [03:17<01:31,  5.42it/s]16 03:14:37 Save the image 00754N_flip.png
 68%|██████████████████████████            | 1074/1568 [03:18<01:31,  5.41it/s]16 03:14:37 Save the image 00755N.png
 69%|██████████████████████████            | 1075/1568 [03:18<01:30,  5.46it/s]16 03:14:38 Save the image 00755N_flip.png
 69%|██████████████████████████            | 1076/1568 [03:18<01:30,  5.45it/s]16 03:14:38 Save the image 00756N.png
 69%|██████████████████████████            | 1077/1568 [03:18<01:29,  5.46it/s]16 03:14:38 Save the image 00756N_flip.png
 69%|██████████████████████████▏           | 1078/1568 [03:18<01:30,  5.42it/s]16 03:14:38 Save the image 00757N.png
 69%|██████████████████████████▏           | 1079/1568 [03:18<01:30,  5.43it/s]16 03:14:38 Save the image 00757N_flip.png
 69%|██████████████████████████▏           | 1080/1568 [03:19<01:29,  5.43it/s]16 03:14:39 Save the image 00758N.png

 69%|██████████████████████████▏           | 1081/1568 [03:19<01:29,  5.43it/s]16 03:14:39 Save the image 00758N_flip.png
 69%|██████████████████████████▏           | 1082/1568 [03:19<01:24,  5.76it/s]16 03:14:39 Save the image 00759N.png
 69%|██████████████████████████▏           | 1083/1568 [03:19<01:26,  5.64it/s]16 03:14:39 Save the image 00759N_flip.png
 69%|██████████████████████████▎           | 1084/1568 [03:19<01:26,  5.63it/s]16 03:14:39 Save the image 00760N.png
 69%|██████████████████████████▎           | 1085/1568 [03:19<01:26,  5.58it/s]16 03:14:39 Save the image 00760N_flip.png
 69%|██████████████████████████▎           | 1086/1568 [03:20<01:27,  5.54it/s]16 03:14:40 Save the image 00761N.png
 69%|██████████████████████████▎           | 1087/1568 [03:20<01:26,  5.56it/s]16 03:14:40 Save the image 00761N_flip.png
 69%|██████████████████████████▎           | 1088/1568 [03:20<01:25,  5.60it/s]16 03:14:40 Save the image 00762N.png
 69%|██████████████████████████▍           | 1089/1568 [03:20<01:26,  5.57it/s]16 03:14:40 Save the image 00762N_flip.png
 70%|██████████████████████████▍           | 1090/1568 [03:20<01:26,  5.53it/s]16 03:14:40 Save the image 00763N.png
 70%|██████████████████████████▍           | 1091/1568 [03:21<01:26,  5.54it/s]16 03:14:41 Save the image 00763N_flip.png
 70%|██████████████████████████▍           | 1092/1568 [03:21<01:25,  5.56it/s]16 03:14:41 Save the image 00764N.png
 70%|██████████████████████████▍           | 1093/1568 [03:21<01:26,  5.52it/s]16 03:14:41 Save the image 00764N_flip.png
 70%|██████████████████████████▌           | 1094/1568 [03:21<01:25,  5.56it/s]16 03:14:41 Save the image 00765N.png
 70%|██████████████████████████▌           | 1095/1568 [03:21<01:25,  5.52it/s]16 03:14:41 Save the image 00765N_flip.png
 70%|██████████████████████████▌           | 1096/1568 [03:21<01:25,  5.50it/s]16 03:14:41 Save the image 00766N.png
 70%|██████████████████████████▌           | 1097/1568 [03:22<01:25,  5.48it/s]16 03:14:42 Save the image 00766N_flip.png
 70%|██████████████████████████▌           | 1098/1568 [03:22<01:25,  5.48it/s]16 03:14:42 Save the image 00767N.png
 70%|██████████████████████████▋           | 1099/1568 [03:22<01:26,  5.44it/s]16 03:14:42 Save the image 00767N_flip.png
 70%|██████████████████████████▋           | 1100/1568 [03:22<01:27,  5.37it/s]16 03:14:42 Save the image 00768N.png
 70%|██████████████████████████▋           | 1101/1568 [03:22<01:27,  5.35it/s]16 03:14:42 Save the image 00768N_flip.png
 70%|██████████████████████████▋           | 1102/1568 [03:23<01:26,  5.37it/s]16 03:14:43 Save the image 00769N.png
 70%|██████████████████████████▋           | 1103/1568 [03:23<01:26,  5.36it/s]16 03:14:43 Save the image 00769N_flip.png
 70%|██████████████████████████▊           | 1104/1568 [03:23<01:26,  5.35it/s]16 03:14:43 Save the image 00770N.png
 70%|██████████████████████████▊           | 1105/1568 [03:23<01:26,  5.37it/s]16 03:14:43 Save the image 00770N_flip.png
 71%|██████████████████████████▊           | 1106/1568 [03:23<01:26,  5.36it/s]16 03:14:43 Save the image 00771N.png
 71%|██████████████████████████▊           | 1107/1568 [03:24<01:27,  5.29it/s]16 03:14:43 Save the image 00771N_flip.png
 71%|██████████████████████████▊           | 1108/1568 [03:24<01:26,  5.34it/s]16 03:14:44 Save the image 00772N.png
 71%|██████████████████████████▉           | 1109/1568 [03:24<01:25,  5.36it/s]16 03:14:44 Save the image 00772N_flip.png
 71%|██████████████████████████▉           | 1110/1568 [03:24<01:26,  5.27it/s]16 03:14:44 Save the image 00773N.png
 71%|██████████████████████████▉           | 1111/1568 [03:24<01:20,  5.71it/s]16 03:14:44 Save the image 00773N_flip.png
 71%|██████████████████████████▉           | 1112/1568 [03:24<01:21,  5.62it/s]16 03:14:44 Save the image 00774N.png
 71%|██████████████████████████▉           | 1113/1568 [03:25<01:21,  5.58it/s]16 03:14:45 Save the image 00774N_flip.png
 71%|██████████████████████████▉           | 1114/1568 [03:25<01:22,  5.52it/s]16 03:14:45 Save the image 00775N.png
 71%|███████████████████████████           | 1115/1568 [03:25<01:22,  5.49it/s]16 03:14:45 Save the image 00775N_flip.png
 71%|███████████████████████████           | 1116/1568 [03:25<01:21,  5.54it/s]16 03:14:45 Save the image 00776N.png
 71%|███████████████████████████           | 1117/1568 [03:25<01:21,  5.51it/s]16 03:14:45 Save the image 00776N_flip.png
 71%|███████████████████████████           | 1118/1568 [03:26<01:22,  5.45it/s]16 03:14:45 Save the image 00777N.png
 71%|███████████████████████████           | 1119/1568 [03:26<01:22,  5.43it/s]16 03:14:46 Save the image 00777N_flip.png
 71%|███████████████████████████▏          | 1120/1568 [03:26<01:22,  5.42it/s]16 03:14:46 Save the image 00778N.png
 71%|███████████████████████████▏          | 1121/1568 [03:26<01:22,  5.42it/s]16 03:14:46 Save the image 00778N_flip.png
 72%|███████████████████████████▏          | 1122/1568 [03:26<01:22,  5.43it/s]16 03:14:46 Save the image 00779N.png
 72%|███████████████████████████▏          | 1123/1568 [03:26<01:22,  5.38it/s]16 03:14:46 Save the image 00779N_flip.png
 72%|███████████████████████████▏          | 1124/1568 [03:27<01:22,  5.40it/s]16 03:14:47 Save the image 00780N.png
 72%|███████████████████████████▎          | 1125/1568 [03:27<01:21,  5.41it/s]16 03:14:47 Save the image 00780N_flip.png
 72%|███████████████████████████▎          | 1126/1568 [03:27<01:21,  5.41it/s]16 03:14:47 Save the image 00781N.png
 72%|███████████████████████████▎          | 1127/1568 [03:27<01:21,  5.44it/s]16 03:14:47 Save the image 00781N_flip.png
 72%|███████████████████████████▎          | 1128/1568 [03:27<01:20,  5.47it/s]16 03:14:47 Save the image 00782N.png
 72%|███████████████████████████▎          | 1129/1568 [03:28<01:20,  5.44it/s]16 03:14:48 Save the image 00782N_flip.png
 72%|███████████████████████████▍          | 1130/1568 [03:28<01:20,  5.44it/s]16 03:14:48 Save the image 00783N.png
 72%|███████████████████████████▍          | 1131/1568 [03:28<01:20,  5.43it/s]16 03:14:48 Save the image 00783N_flip.png
 72%|███████████████████████████▍          | 1132/1568 [03:28<01:20,  5.43it/s]16 03:14:48 Save the image 00784N.png
 72%|███████████████████████████▍          | 1133/1568 [03:28<01:16,  5.72it/s]16 03:14:48 Save the image 00784N_flip.png
 72%|███████████████████████████▍          | 1134/1568 [03:28<01:16,  5.64it/s]16 03:14:48 Save the image 00785N.png
 72%|███████████████████████████▌          | 1135/1568 [03:29<01:17,  5.62it/s]16 03:14:49 Save the image 00785N_flip.png
 72%|███████████████████████████▌          | 1136/1568 [03:29<01:17,  5.59it/s]16 03:14:49 Save the image 00786N.png
 73%|███████████████████████████▌          | 1137/1568 [03:29<01:17,  5.55it/s]16 03:14:49 Save the image 00786N_flip.png
 73%|███████████████████████████▌          | 1138/1568 [03:29<01:18,  5.51it/s]16 03:14:49 Save the image 00787N.png
 73%|███████████████████████████▌          | 1139/1568 [03:29<01:16,  5.62it/s]16 03:14:49 Save the image 00787N_flip.png
 73%|███████████████████████████▋          | 1140/1568 [03:30<01:16,  5.59it/s]16 03:14:49 Save the image 00788N.png
 73%|███████████████████████████▋          | 1141/1568 [03:30<01:16,  5.55it/s]16 03:14:50 Save the image 00788N_flip.png
 73%|███████████████████████████▋          | 1142/1568 [03:30<01:16,  5.55it/s]16 03:14:50 Save the image 00789N.png
 73%|███████████████████████████▋          | 1143/1568 [03:30<01:16,  5.54it/s]16 03:14:50 Save the image 00789N_flip.png
 73%|███████████████████████████▋          | 1144/1568 [03:30<01:16,  5.53it/s]16 03:14:50 Save the image 00790N.png

 73%|███████████████████████████▋          | 1145/1568 [03:30<01:16,  5.56it/s]16 03:14:50 Save the image 00790N_flip.png
 73%|███████████████████████████▊          | 1146/1568 [03:31<01:16,  5.52it/s]16 03:14:51 Save the image 00791N.png
 73%|███████████████████████████▊          | 1147/1568 [03:31<01:16,  5.50it/s]16 03:14:51 Save the image 00791N_flip.png
 73%|███████████████████████████▊          | 1148/1568 [03:31<01:16,  5.49it/s]16 03:14:51 Save the image 00792N.png
 73%|███████████████████████████▊          | 1149/1568 [03:31<01:16,  5.48it/s]16 03:14:51 Save the image 00792N_flip.png
 73%|███████████████████████████▊          | 1150/1568 [03:31<01:16,  5.49it/s]16 03:14:51 Save the image 00793N.png
 73%|███████████████████████████▉          | 1151/1568 [03:32<01:15,  5.49it/s]16 03:14:51 Save the image 00793N_flip.png
 73%|███████████████████████████▉          | 1152/1568 [03:32<01:15,  5.48it/s]16 03:14:52 Save the image 00794N.png
 74%|███████████████████████████▉          | 1153/1568 [03:32<01:15,  5.49it/s]16 03:14:52 Save the image 00794N_flip.png
 74%|███████████████████████████▉          | 1154/1568 [03:32<01:15,  5.49it/s]16 03:14:52 Save the image 00795N.png
 74%|███████████████████████████▉          | 1155/1568 [03:32<01:14,  5.51it/s]16 03:14:52 Save the image 00795N_flip.png
 74%|████████████████████████████          | 1156/1568 [03:32<01:15,  5.49it/s]16 03:14:52 Save the image 00796N.png
 74%|████████████████████████████          | 1157/1568 [03:33<01:14,  5.50it/s]16 03:14:53 Save the image 00796N_flip.png
 74%|████████████████████████████          | 1158/1568 [03:33<01:14,  5.47it/s]16 03:14:53 Save the image 00797N.png
 74%|████████████████████████████          | 1159/1568 [03:33<01:14,  5.47it/s]16 03:14:53 Save the image 00797N_flip.png
 74%|████████████████████████████          | 1160/1568 [03:33<01:14,  5.48it/s]16 03:14:53 Save the image 00798N.png
 74%|████████████████████████████▏         | 1161/1568 [03:33<01:14,  5.47it/s]16 03:14:53 Save the image 00798N_flip.png
 74%|████████████████████████████▏         | 1162/1568 [03:34<01:10,  5.79it/s]16 03:14:53 Save the image 00799N.png
 74%|████████████████████████████▏         | 1163/1568 [03:34<01:11,  5.68it/s]16 03:14:54 Save the image 00799N_flip.png
 74%|████████████████████████████▏         | 1164/1568 [03:34<01:11,  5.61it/s]16 03:14:54 Save the image 00800N.png
 74%|████████████████████████████▏         | 1165/1568 [03:34<01:12,  5.57it/s]16 03:14:54 Save the image 00800N_flip.png
 74%|████████████████████████████▎         | 1166/1568 [03:34<01:13,  5.48it/s]16 03:14:54 Save the image 00801N.png
 74%|████████████████████████████▎         | 1167/1568 [03:34<01:11,  5.59it/s]16 03:14:54 Save the image 00801N_flip.png
 74%|████████████████████████████▎         | 1168/1568 [03:35<01:11,  5.62it/s]16 03:14:55 Save the image 00802N.png
 75%|████████████████████████████▎         | 1169/1568 [03:35<01:11,  5.59it/s]16 03:14:55 Save the image 00802N_flip.png
 75%|████████████████████████████▎         | 1170/1568 [03:35<01:11,  5.56it/s]16 03:14:55 Save the image 00803N.png
 75%|████████████████████████████▍         | 1171/1568 [03:35<01:11,  5.56it/s]16 03:14:55 Save the image 00803N_flip.png
 75%|████████████████████████████▍         | 1172/1568 [03:35<01:11,  5.56it/s]16 03:14:55 Save the image 00804N.png
 75%|████████████████████████████▍         | 1173/1568 [03:35<01:11,  5.52it/s]16 03:14:55 Save the image 00804N_flip.png
 75%|████████████████████████████▍         | 1174/1568 [03:36<01:10,  5.57it/s]16 03:14:56 Save the image 00805N.png
 75%|████████████████████████████▍         | 1175/1568 [03:36<01:11,  5.53it/s]16 03:14:56 Save the image 00805N_flip.png
 75%|████████████████████████████▌         | 1176/1568 [03:36<01:11,  5.50it/s]16 03:14:56 Save the image 00806N.png
 75%|████████████████████████████▌         | 1177/1568 [03:36<01:11,  5.50it/s]16 03:14:56 Save the image 00806N_flip.png
 75%|████████████████████████████▌         | 1178/1568 [03:36<01:10,  5.51it/s]16 03:14:56 Save the image 00807N.png
 75%|████████████████████████████▌         | 1179/1568 [03:37<01:10,  5.51it/s]16 03:14:57 Save the image 00807N_flip.png
 75%|████████████████████████████▌         | 1180/1568 [03:37<01:11,  5.46it/s]16 03:14:57 Save the image 00808N.png
 75%|████████████████████████████▌         | 1181/1568 [03:37<01:10,  5.45it/s]16 03:14:57 Save the image 00808N_flip.png
 75%|████████████████████████████▋         | 1182/1568 [03:37<01:10,  5.46it/s]16 03:14:57 Save the image 00809N.png
 75%|████████████████████████████▋         | 1183/1568 [03:37<01:10,  5.47it/s]16 03:14:57 Save the image 00809N_flip.png
 76%|████████████████████████████▋         | 1184/1568 [03:38<01:10,  5.48it/s]16 03:14:57 Save the image 00810N.png
 76%|████████████████████████████▋         | 1185/1568 [03:38<01:09,  5.47it/s]16 03:14:58 Save the image 00810N_flip.png
 76%|████████████████████████████▋         | 1186/1568 [03:38<01:10,  5.45it/s]16 03:14:58 Save the image 00811N.png
 76%|████████████████████████████▊         | 1187/1568 [03:38<01:10,  5.41it/s]16 03:14:58 Save the image 00811N_flip.png
 76%|████████████████████████████▊         | 1188/1568 [03:38<01:10,  5.36it/s]16 03:14:58 Save the image 00812N.png
 76%|████████████████████████████▊         | 1189/1568 [03:38<01:10,  5.35it/s]16 03:14:58 Save the image 00812N_flip.png
 76%|████████████████████████████▊         | 1190/1568 [03:39<01:10,  5.38it/s]16 03:14:59 Save the image 00813N.png
 76%|████████████████████████████▊         | 1191/1568 [03:39<01:06,  5.65it/s]16 03:14:59 Save the image 00813N_flip.png
 76%|████████████████████████████▉         | 1192/1568 [03:39<01:07,  5.60it/s]16 03:14:59 Save the image 00814N.png
 76%|████████████████████████████▉         | 1193/1568 [03:39<01:07,  5.55it/s]16 03:14:59 Save the image 00814N_flip.png
 76%|████████████████████████████▉         | 1194/1568 [03:39<01:08,  5.43it/s]16 03:14:59 Save the image 00815N.png
 76%|████████████████████████████▉         | 1195/1568 [03:40<01:08,  5.47it/s]16 03:14:59 Save the image 00815N_flip.png
 76%|████████████████████████████▉         | 1196/1568 [03:40<01:07,  5.48it/s]16 03:15:00 Save the image 00816N.png
 76%|█████████████████████████████         | 1197/1568 [03:40<01:07,  5.50it/s]16 03:15:00 Save the image 00816N_flip.png
 76%|█████████████████████████████         | 1198/1568 [03:40<01:07,  5.49it/s]16 03:15:00 Save the image 00817N.png
 76%|█████████████████████████████         | 1199/1568 [03:40<01:07,  5.47it/s]16 03:15:00 Save the image 00817N_flip.png
 77%|█████████████████████████████         | 1200/1568 [03:40<01:07,  5.49it/s]16 03:15:00 Save the image 00818N.png
 77%|█████████████████████████████         | 1201/1568 [03:41<01:06,  5.50it/s]16 03:15:01 Save the image 00818N_flip.png
 77%|█████████████████████████████▏        | 1202/1568 [03:41<01:06,  5.47it/s]16 03:15:01 Save the image 00819N.png
 77%|█████████████████████████████▏        | 1203/1568 [03:41<01:06,  5.46it/s]16 03:15:01 Save the image 00819N_flip.png
 77%|█████████████████████████████▏        | 1204/1568 [03:41<01:06,  5.44it/s]16 03:15:01 Save the image 00820N.png
 77%|█████████████████████████████▏        | 1205/1568 [03:41<01:06,  5.44it/s]16 03:15:01 Save the image 00820N_flip.png
 77%|█████████████████████████████▏        | 1206/1568 [03:42<01:05,  5.50it/s]16 03:15:01 Save the image 00821N.png
 77%|█████████████████████████████▎        | 1207/1568 [03:42<01:05,  5.49it/s]16 03:15:02 Save the image 00821N_flip.png
 77%|█████████████████████████████▎        | 1208/1568 [03:42<01:05,  5.50it/s]16 03:15:02 Save the image 00822N.png

 77%|█████████████████████████████▎        | 1209/1568 [03:42<01:05,  5.46it/s]16 03:15:02 Save the image 00822N_flip.png
 77%|█████████████████████████████▎        | 1210/1568 [03:42<01:05,  5.44it/s]16 03:15:02 Save the image 00823N.png
 77%|█████████████████████████████▎        | 1211/1568 [03:42<01:06,  5.35it/s]16 03:15:02 Save the image 00823N_flip.png
 77%|█████████████████████████████▎        | 1212/1568 [03:43<01:06,  5.35it/s]16 03:15:03 Save the image 00824N.png
 77%|█████████████████████████████▍        | 1213/1568 [03:43<01:06,  5.32it/s]16 03:15:03 Save the image 00824N_flip.png
 77%|█████████████████████████████▍        | 1214/1568 [03:43<01:06,  5.33it/s]16 03:15:03 Save the image 00825N.png
 77%|█████████████████████████████▍        | 1215/1568 [03:43<01:05,  5.39it/s]16 03:15:03 Save the image 00825N_flip.png
 78%|█████████████████████████████▍        | 1216/1568 [03:43<01:06,  5.32it/s]16 03:15:03 Save the image 00826N.png
 78%|█████████████████████████████▍        | 1217/1568 [03:44<01:05,  5.33it/s]16 03:15:04 Save the image 00826N_flip.png
 78%|█████████████████████████████▌        | 1218/1568 [03:44<01:05,  5.37it/s]16 03:15:04 Save the image 00827N.png
 78%|█████████████████████████████▌        | 1219/1568 [03:44<01:05,  5.35it/s]16 03:15:04 Save the image 00827N_flip.png
 78%|█████████████████████████████▌        | 1220/1568 [03:44<01:01,  5.65it/s]16 03:15:04 Save the image 00828N.png
 78%|█████████████████████████████▌        | 1221/1568 [03:44<01:02,  5.58it/s]16 03:15:04 Save the image 00828N_flip.png
 78%|█████████████████████████████▌        | 1222/1568 [03:44<01:02,  5.52it/s]16 03:15:04 Save the image 00829N.png
 78%|█████████████████████████████▋        | 1223/1568 [03:45<01:03,  5.46it/s]16 03:15:05 Save the image 00829N_flip.png
 78%|█████████████████████████████▋        | 1224/1568 [03:45<01:04,  5.36it/s]16 03:15:05 Save the image 00830N.png
 78%|█████████████████████████████▋        | 1225/1568 [03:45<01:02,  5.48it/s]16 03:15:05 Save the image 00830N_flip.png
 78%|█████████████████████████████▋        | 1226/1568 [03:45<01:02,  5.46it/s]16 03:15:05 Save the image 00831N.png
 78%|█████████████████████████████▋        | 1227/1568 [03:45<01:02,  5.42it/s]16 03:15:05 Save the image 00831N_flip.png
 78%|█████████████████████████████▊        | 1228/1568 [03:46<01:02,  5.41it/s]16 03:15:06 Save the image 00832N.png
 78%|█████████████████████████████▊        | 1229/1568 [03:46<01:02,  5.42it/s]16 03:15:06 Save the image 00832N_flip.png
 78%|█████████████████████████████▊        | 1230/1568 [03:46<01:02,  5.38it/s]16 03:15:06 Save the image 00833N.png
 79%|█████████████████████████████▊        | 1231/1568 [03:46<01:02,  5.36it/s]16 03:15:06 Save the image 00833N_flip.png
 79%|█████████████████████████████▊        | 1232/1568 [03:46<01:01,  5.43it/s]16 03:15:06 Save the image 00834N.png
 79%|█████████████████████████████▉        | 1233/1568 [03:47<01:01,  5.41it/s]16 03:15:06 Save the image 00834N_flip.png
 79%|█████████████████████████████▉        | 1234/1568 [03:47<01:01,  5.41it/s]16 03:15:07 Save the image 00835N.png
 79%|█████████████████████████████▉        | 1235/1568 [03:47<01:01,  5.40it/s]16 03:15:07 Save the image 00835N_flip.png
 79%|█████████████████████████████▉        | 1236/1568 [03:47<01:01,  5.40it/s]16 03:15:07 Save the image 00836N.png
 79%|█████████████████████████████▉        | 1237/1568 [03:47<01:00,  5.44it/s]16 03:15:07 Save the image 00836N_flip.png
 79%|██████████████████████████████        | 1238/1568 [03:47<01:00,  5.44it/s]16 03:15:07 Save the image 00837N.png
 79%|██████████████████████████████        | 1239/1568 [03:48<01:00,  5.45it/s]16 03:15:08 Save the image 00837N_flip.png
 79%|██████████████████████████████        | 1240/1568 [03:48<01:00,  5.39it/s]16 03:15:08 Save the image 00838N.png
 79%|██████████████████████████████        | 1241/1568 [03:48<01:01,  5.36it/s]16 03:15:08 Save the image 00838N_flip.png
 79%|██████████████████████████████        | 1242/1568 [03:48<01:01,  5.33it/s]16 03:15:08 Save the image 00839N.png
 79%|██████████████████████████████        | 1243/1568 [03:48<01:00,  5.37it/s]16 03:15:08 Save the image 00839N_flip.png
 79%|██████████████████████████████▏       | 1244/1568 [03:49<01:00,  5.38it/s]16 03:15:09 Save the image 00840N.png
 79%|██████████████████████████████▏       | 1245/1568 [03:49<01:01,  5.28it/s]16 03:15:09 Save the image 00840N_flip.png
 79%|██████████████████████████████▏       | 1246/1568 [03:49<01:00,  5.33it/s]16 03:15:09 Save the image 00841N.png
 80%|██████████████████████████████▏       | 1247/1568 [03:49<01:00,  5.31it/s]16 03:15:09 Save the image 00841N_flip.png
 80%|██████████████████████████████▏       | 1248/1568 [03:49<01:00,  5.33it/s]16 03:15:09 Save the image 00842N.png
 80%|██████████████████████████████▎       | 1249/1568 [03:49<00:55,  5.70it/s]16 03:15:09 Save the image 00842N_flip.png
 80%|██████████████████████████████▎       | 1250/1568 [03:50<00:57,  5.56it/s]16 03:15:10 Save the image 00843N.png
 80%|██████████████████████████████▎       | 1251/1568 [03:50<00:57,  5.55it/s]16 03:15:10 Save the image 00843N_flip.png
 80%|██████████████████████████████▎       | 1252/1568 [03:50<00:56,  5.56it/s]16 03:15:10 Save the image 00844N.png
 80%|██████████████████████████████▎       | 1253/1568 [03:50<00:57,  5.46it/s]16 03:15:10 Save the image 00844N_flip.png
 80%|██████████████████████████████▍       | 1254/1568 [03:50<00:57,  5.50it/s]16 03:15:10 Save the image 00845N.png
 80%|██████████████████████████████▍       | 1255/1568 [03:51<00:56,  5.53it/s]16 03:15:10 Save the image 00845N_flip.png
 80%|██████████████████████████████▍       | 1256/1568 [03:51<00:57,  5.44it/s]16 03:15:11 Save the image 00846N.png
 80%|██████████████████████████████▍       | 1257/1568 [03:51<00:58,  5.35it/s]16 03:15:11 Save the image 00846N_flip.png
 80%|██████████████████████████████▍       | 1258/1568 [03:51<00:57,  5.37it/s]16 03:15:11 Save the image 00847N.png
 80%|██████████████████████████████▌       | 1259/1568 [03:51<00:57,  5.41it/s]16 03:15:11 Save the image 00847N_flip.png
 80%|██████████████████████████████▌       | 1260/1568 [03:51<00:57,  5.37it/s]16 03:15:11 Save the image 00848N.png
 80%|██████████████████████████████▌       | 1261/1568 [03:52<00:56,  5.43it/s]16 03:15:12 Save the image 00848N_flip.png
 80%|██████████████████████████████▌       | 1262/1568 [03:52<00:56,  5.42it/s]16 03:15:12 Save the image 00849N.png
 81%|██████████████████████████████▌       | 1263/1568 [03:52<00:56,  5.42it/s]16 03:15:12 Save the image 00849N_flip.png
 81%|██████████████████████████████▋       | 1264/1568 [03:52<00:56,  5.38it/s]16 03:15:12 Save the image 00850N.png
 81%|██████████████████████████████▋       | 1265/1568 [03:52<00:55,  5.43it/s]16 03:15:12 Save the image 00850N_flip.png
 81%|██████████████████████████████▋       | 1266/1568 [03:53<00:55,  5.41it/s]16 03:15:13 Save the image 00851N.png
 81%|██████████████████████████████▋       | 1267/1568 [03:53<00:55,  5.39it/s]16 03:15:13 Save the image 00851N_flip.png
 81%|██████████████████████████████▋       | 1268/1568 [03:53<00:55,  5.39it/s]16 03:15:13 Save the image 00852N.png
 81%|██████████████████████████████▊       | 1269/1568 [03:53<00:55,  5.39it/s]16 03:15:13 Save the image 00852N_flip.png
 81%|██████████████████████████████▊       | 1270/1568 [03:53<00:55,  5.36it/s]16 03:15:13 Save the image 00853N.png
 81%|██████████████████████████████▊       | 1271/1568 [03:54<00:55,  5.39it/s]16 03:15:13 Save the image 00853N_flip.png
 81%|██████████████████████████████▊       | 1272/1568 [03:54<00:54,  5.42it/s]16 03:15:14 Save the image 00854N.png

 81%|██████████████████████████████▊       | 1273/1568 [03:54<00:54,  5.45it/s]16 03:15:14 Save the image 00854N_flip.png
 81%|██████████████████████████████▉       | 1274/1568 [03:54<00:54,  5.43it/s]16 03:15:14 Save the image 00855N.png
 81%|██████████████████████████████▉       | 1275/1568 [03:54<00:54,  5.39it/s]16 03:15:14 Save the image 00855N_flip.png
 81%|██████████████████████████████▉       | 1276/1568 [03:54<00:54,  5.38it/s]16 03:15:14 Save the image 00856N.png
 81%|██████████████████████████████▉       | 1277/1568 [03:55<00:53,  5.43it/s]16 03:15:15 Save the image 00856N_flip.png
 82%|██████████████████████████████▉       | 1278/1568 [03:55<00:51,  5.67it/s]16 03:15:15 Save the image 00857N.png
 82%|██████████████████████████████▉       | 1279/1568 [03:55<00:51,  5.60it/s]16 03:15:15 Save the image 00857N_flip.png
 82%|███████████████████████████████       | 1280/1568 [03:55<00:51,  5.60it/s]16 03:15:15 Save the image 00858N.png
 82%|███████████████████████████████       | 1281/1568 [03:55<00:51,  5.53it/s]16 03:15:15 Save the image 00858N_flip.png
 82%|███████████████████████████████       | 1282/1568 [03:56<00:52,  5.43it/s]16 03:15:15 Save the image 00859N.png
 82%|███████████████████████████████       | 1283/1568 [03:56<00:51,  5.49it/s]16 03:15:16 Save the image 00859N_flip.png
 82%|███████████████████████████████       | 1284/1568 [03:56<00:51,  5.48it/s]16 03:15:16 Save the image 00860N.png
 82%|███████████████████████████████▏      | 1285/1568 [03:56<00:51,  5.47it/s]16 03:15:16 Save the image 00860N_flip.png
 82%|███████████████████████████████▏      | 1286/1568 [03:56<00:51,  5.44it/s]16 03:15:16 Save the image 00861N.png
 82%|███████████████████████████████▏      | 1287/1568 [03:56<00:51,  5.42it/s]16 03:15:16 Save the image 00861N_flip.png
 82%|███████████████████████████████▏      | 1288/1568 [03:57<00:51,  5.47it/s]16 03:15:17 Save the image 00862N.png
 82%|███████████████████████████████▏      | 1289/1568 [03:57<00:51,  5.42it/s]16 03:15:17 Save the image 00862N_flip.png
 82%|███████████████████████████████▎      | 1290/1568 [03:57<00:51,  5.40it/s]16 03:15:17 Save the image 00863N.png
 82%|███████████████████████████████▎      | 1291/1568 [03:57<00:51,  5.42it/s]16 03:15:17 Save the image 00863N_flip.png
 82%|███████████████████████████████▎      | 1292/1568 [03:57<00:51,  5.38it/s]16 03:15:17 Save the image 00864N.png
 82%|███████████████████████████████▎      | 1293/1568 [03:58<00:50,  5.41it/s]16 03:15:17 Save the image 00864N_flip.png
 83%|███████████████████████████████▎      | 1294/1568 [03:58<00:50,  5.43it/s]16 03:15:18 Save the image 00865N.png
 83%|███████████████████████████████▍      | 1295/1568 [03:58<00:50,  5.46it/s]16 03:15:18 Save the image 00865N_flip.png
 83%|███████████████████████████████▍      | 1296/1568 [03:58<00:50,  5.42it/s]16 03:15:18 Save the image 00866N.png
 83%|███████████████████████████████▍      | 1297/1568 [03:58<00:50,  5.41it/s]16 03:15:18 Save the image 00866N_flip.png
 83%|███████████████████████████████▍      | 1298/1568 [03:58<00:49,  5.42it/s]16 03:15:18 Save the image 00867N.png
 83%|███████████████████████████████▍      | 1299/1568 [03:59<00:49,  5.48it/s]16 03:15:19 Save the image 00867N_flip.png
 83%|███████████████████████████████▌      | 1300/1568 [03:59<00:47,  5.69it/s]16 03:15:19 Save the image 00868N.png
 83%|███████████████████████████████▌      | 1301/1568 [03:59<00:47,  5.56it/s]16 03:15:19 Save the image 00868N_flip.png
 83%|███████████████████████████████▌      | 1302/1568 [03:59<00:48,  5.54it/s]16 03:15:19 Save the image 00869N.png
 83%|███████████████████████████████▌      | 1303/1568 [03:59<00:47,  5.55it/s]16 03:15:19 Save the image 00869N_flip.png
 83%|███████████████████████████████▌      | 1304/1568 [04:00<00:47,  5.52it/s]16 03:15:19 Save the image 00870N.png
 83%|███████████████████████████████▋      | 1305/1568 [04:00<00:47,  5.49it/s]16 03:15:20 Save the image 00870N_flip.png
 83%|███████████████████████████████▋      | 1306/1568 [04:00<00:48,  5.44it/s]16 03:15:20 Save the image 00871N.png
 83%|███████████████████████████████▋      | 1307/1568 [04:00<00:47,  5.45it/s]16 03:15:20 Save the image 00871N_flip.png
 83%|███████████████████████████████▋      | 1308/1568 [04:00<00:47,  5.42it/s]16 03:15:20 Save the image 00872N.png
 83%|███████████████████████████████▋      | 1309/1568 [04:00<00:48,  5.39it/s]16 03:15:20 Save the image 00872N_flip.png
 84%|███████████████████████████████▋      | 1310/1568 [04:01<00:47,  5.38it/s]16 03:15:21 Save the image 00873N.png
 84%|███████████████████████████████▊      | 1311/1568 [04:01<00:47,  5.39it/s]16 03:15:21 Save the image 00873N_flip.png
 84%|███████████████████████████████▊      | 1312/1568 [04:01<00:48,  5.33it/s]16 03:15:21 Save the image 00874N.png
 84%|███████████████████████████████▊      | 1313/1568 [04:01<00:47,  5.37it/s]16 03:15:21 Save the image 00874N_flip.png
 84%|███████████████████████████████▊      | 1314/1568 [04:01<00:47,  5.40it/s]16 03:15:21 Save the image 00875N.png
 84%|███████████████████████████████▊      | 1315/1568 [04:02<00:43,  5.76it/s]16 03:15:22 Save the image 00875N_flip.png
 84%|███████████████████████████████▉      | 1316/1568 [04:02<00:45,  5.53it/s]16 03:15:22 Save the image 00876N.png
 84%|███████████████████████████████▉      | 1317/1568 [04:02<00:45,  5.51it/s]16 03:15:22 Save the image 00876N_flip.png
 84%|███████████████████████████████▉      | 1318/1568 [04:02<00:45,  5.52it/s]16 03:15:22 Save the image 00877N.png
 84%|███████████████████████████████▉      | 1319/1568 [04:02<00:46,  5.39it/s]16 03:15:22 Save the image 00877N_flip.png
 84%|███████████████████████████████▉      | 1320/1568 [04:02<00:45,  5.51it/s]16 03:15:22 Save the image 00878N.png
 84%|████████████████████████████████      | 1321/1568 [04:03<00:44,  5.52it/s]16 03:15:23 Save the image 00878N_flip.png
 84%|████████████████████████████████      | 1322/1568 [04:03<00:44,  5.48it/s]16 03:15:23 Save the image 00879N.png
 84%|████████████████████████████████      | 1323/1568 [04:03<00:45,  5.43it/s]16 03:15:23 Save the image 00879N_flip.png
 84%|████████████████████████████████      | 1324/1568 [04:03<00:44,  5.45it/s]16 03:15:23 Save the image 00880N.png
 85%|████████████████████████████████      | 1325/1568 [04:03<00:44,  5.42it/s]16 03:15:23 Save the image 00880N_flip.png
 85%|████████████████████████████████▏     | 1326/1568 [04:04<00:45,  5.38it/s]16 03:15:24 Save the image 00881N.png
 85%|████████████████████████████████▏     | 1327/1568 [04:04<00:44,  5.43it/s]16 03:15:24 Save the image 00881N_flip.png
 85%|████████████████████████████████▏     | 1328/1568 [04:04<00:44,  5.38it/s]16 03:15:24 Save the image 00882N.png
 85%|████████████████████████████████▏     | 1329/1568 [04:04<00:44,  5.36it/s]16 03:15:24 Save the image 00882N_flip.png
 85%|████████████████████████████████▏     | 1330/1568 [04:04<00:44,  5.31it/s]16 03:15:24 Save the image 00883N.png
 85%|████████████████████████████████▎     | 1331/1568 [04:05<00:44,  5.34it/s]16 03:15:24 Save the image 00883N_flip.png
 85%|████████████████████████████████▎     | 1332/1568 [04:05<00:44,  5.33it/s]16 03:15:25 Save the image 00884N.png
 85%|████████████████████████████████▎     | 1333/1568 [04:05<00:44,  5.33it/s]16 03:15:25 Save the image 00884N_flip.png
 85%|████████████████████████████████▎     | 1334/1568 [04:05<00:43,  5.32it/s]16 03:15:25 Save the image 00885N.png
 85%|████████████████████████████████▎     | 1335/1568 [04:05<00:43,  5.31it/s]16 03:15:25 Save the image 00885N_flip.png
 85%|████████████████████████████████▍     | 1336/1568 [04:05<00:43,  5.33it/s]16 03:15:25 Save the image 00886N.png

 85%|████████████████████████████████▍     | 1337/1568 [04:06<00:43,  5.27it/s]16 03:15:26 Save the image 00886N_flip.png
 85%|████████████████████████████████▍     | 1338/1568 [04:06<00:43,  5.31it/s]16 03:15:26 Save the image 00887N.png
 85%|████████████████████████████████▍     | 1339/1568 [04:06<00:43,  5.30it/s]16 03:15:26 Save the image 00887N_flip.png
 85%|████████████████████████████████▍     | 1340/1568 [04:06<00:42,  5.31it/s]16 03:15:26 Save the image 00888N.png
 86%|████████████████████████████████▍     | 1341/1568 [04:06<00:43,  5.28it/s]16 03:15:26 Save the image 00888N_flip.png
 86%|████████████████████████████████▌     | 1342/1568 [04:07<00:42,  5.29it/s]16 03:15:27 Save the image 00889N.png
 86%|████████████████████████████████▌     | 1343/1568 [04:07<00:42,  5.31it/s]16 03:15:27 Save the image 00889N_flip.png
 86%|████████████████████████████████▌     | 1344/1568 [04:07<00:39,  5.62it/s]16 03:15:27 Save the image 00890N.png
 86%|████████████████████████████████▌     | 1345/1568 [04:07<00:40,  5.52it/s]16 03:15:27 Save the image 00890N_flip.png
 86%|████████████████████████████████▌     | 1346/1568 [04:07<00:40,  5.43it/s]16 03:15:27 Save the image 00891N.png
 86%|████████████████████████████████▋     | 1347/1568 [04:08<00:40,  5.49it/s]16 03:15:27 Save the image 00891N_flip.png
 86%|████████████████████████████████▋     | 1348/1568 [04:08<00:40,  5.44it/s]16 03:15:28 Save the image 00892N.png
 86%|████████████████████████████████▋     | 1349/1568 [04:08<00:39,  5.48it/s]16 03:15:28 Save the image 00892N_flip.png
 86%|████████████████████████████████▋     | 1350/1568 [04:08<00:39,  5.48it/s]16 03:15:28 Save the image 00893N.png
 86%|████████████████████████████████▋     | 1351/1568 [04:08<00:39,  5.45it/s]16 03:15:28 Save the image 00893N_flip.png
 86%|████████████████████████████████▊     | 1352/1568 [04:08<00:39,  5.41it/s]16 03:15:28 Save the image 00894N.png
 86%|████████████████████████████████▊     | 1353/1568 [04:09<00:39,  5.40it/s]16 03:15:29 Save the image 00894N_flip.png
 86%|████████████████████████████████▊     | 1354/1568 [04:09<00:39,  5.40it/s]16 03:15:29 Save the image 00895N.png
 86%|████████████████████████████████▊     | 1355/1568 [04:09<00:39,  5.36it/s]16 03:15:29 Save the image 00895N_flip.png
 86%|████████████████████████████████▊     | 1356/1568 [04:09<00:39,  5.42it/s]16 03:15:29 Save the image 00896N.png
 87%|████████████████████████████████▉     | 1357/1568 [04:09<00:39,  5.38it/s]16 03:15:29 Save the image 00896N_flip.png
 87%|████████████████████████████████▉     | 1358/1568 [04:10<00:38,  5.40it/s]16 03:15:29 Save the image 00897N.png
 87%|████████████████████████████████▉     | 1359/1568 [04:10<00:38,  5.37it/s]16 03:15:30 Save the image 00897N_flip.png
 87%|████████████████████████████████▉     | 1360/1568 [04:10<00:38,  5.38it/s]16 03:15:30 Save the image 00898N.png
 87%|████████████████████████████████▉     | 1361/1568 [04:10<00:38,  5.43it/s]16 03:15:30 Save the image 00898N_flip.png
 87%|█████████████████████████████████     | 1362/1568 [04:10<00:38,  5.36it/s]16 03:15:30 Save the image 00899N.png
 87%|█████████████████████████████████     | 1363/1568 [04:10<00:38,  5.35it/s]16 03:15:30 Save the image 00899N_flip.png
 87%|█████████████████████████████████     | 1364/1568 [04:11<00:38,  5.34it/s]16 03:15:31 Save the image 00900N.png
 87%|█████████████████████████████████     | 1365/1568 [04:11<00:38,  5.32it/s]16 03:15:31 Save the image 00900N_flip.png
 87%|█████████████████████████████████     | 1366/1568 [04:11<00:35,  5.64it/s]16 03:15:31 Save the image 00901N.png
 87%|█████████████████████████████████▏    | 1367/1568 [04:11<00:36,  5.49it/s]16 03:15:31 Save the image 00901N_flip.png
 87%|█████████████████████████████████▏    | 1368/1568 [04:11<00:36,  5.48it/s]16 03:15:31 Save the image 00902N.png
 87%|█████████████████████████████████▏    | 1369/1568 [04:12<00:36,  5.50it/s]16 03:15:31 Save the image 00902N_flip.png
 87%|█████████████████████████████████▏    | 1370/1568 [04:12<00:35,  5.55it/s]16 03:15:32 Save the image 00903N.png
 87%|█████████████████████████████████▏    | 1371/1568 [04:12<00:35,  5.57it/s]16 03:15:32 Save the image 00903N_flip.png
 88%|█████████████████████████████████▎    | 1372/1568 [04:12<00:35,  5.56it/s]16 03:15:32 Save the image 00904N.png
 88%|█████████████████████████████████▎    | 1373/1568 [04:12<00:35,  5.54it/s]16 03:15:32 Save the image 00904N_flip.png
 88%|█████████████████████████████████▎    | 1374/1568 [04:12<00:35,  5.46it/s]16 03:15:32 Save the image 00905N.png
 88%|█████████████████████████████████▎    | 1375/1568 [04:13<00:35,  5.48it/s]16 03:15:33 Save the image 00905N_flip.png
 88%|█████████████████████████████████▎    | 1376/1568 [04:13<00:35,  5.41it/s]16 03:15:33 Save the image 00906N.png
 88%|█████████████████████████████████▎    | 1377/1568 [04:13<00:35,  5.37it/s]16 03:15:33 Save the image 00906N_flip.png
 88%|█████████████████████████████████▍    | 1378/1568 [04:13<00:35,  5.37it/s]16 03:15:33 Save the image 00907N.png
 88%|█████████████████████████████████▍    | 1379/1568 [04:13<00:35,  5.37it/s]16 03:15:33 Save the image 00907N_flip.png
 88%|█████████████████████████████████▍    | 1380/1568 [04:14<00:35,  5.35it/s]16 03:15:34 Save the image 00908N.png
 88%|█████████████████████████████████▍    | 1381/1568 [04:14<00:35,  5.32it/s]16 03:15:34 Save the image 00908N_flip.png
 88%|█████████████████████████████████▍    | 1382/1568 [04:14<00:34,  5.34it/s]16 03:15:34 Save the image 00909N.png
 88%|█████████████████████████████████▌    | 1383/1568 [04:14<00:34,  5.36it/s]16 03:15:34 Save the image 00909N_flip.png
 88%|█████████████████████████████████▌    | 1384/1568 [04:14<00:34,  5.32it/s]16 03:15:34 Save the image 00910N.png
 88%|█████████████████████████████████▌    | 1385/1568 [04:15<00:34,  5.28it/s]16 03:15:34 Save the image 00910N_flip.png
 88%|█████████████████████████████████▌    | 1386/1568 [04:15<00:34,  5.30it/s]16 03:15:35 Save the image 00911N.png
 88%|█████████████████████████████████▌    | 1387/1568 [04:15<00:34,  5.31it/s]16 03:15:35 Save the image 00911N_flip.png
 89%|█████████████████████████████████▋    | 1388/1568 [04:15<00:33,  5.31it/s]16 03:15:35 Save the image 00912N.png
 89%|█████████████████████████████████▋    | 1389/1568 [04:15<00:33,  5.33it/s]16 03:15:35 Save the image 00912N_flip.png
 89%|█████████████████████████████████▋    | 1390/1568 [04:15<00:33,  5.31it/s]16 03:15:35 Save the image 00913N.png
 89%|█████████████████████████████████▋    | 1391/1568 [04:16<00:33,  5.33it/s]16 03:15:36 Save the image 00913N_flip.png
 89%|█████████████████████████████████▋    | 1392/1568 [04:16<00:33,  5.29it/s]16 03:15:36 Save the image 00914N.png
 89%|█████████████████████████████████▊    | 1393/1568 [04:16<00:33,  5.29it/s]16 03:15:36 Save the image 00914N_flip.png
 89%|█████████████████████████████████▊    | 1394/1568 [04:16<00:32,  5.31it/s]16 03:15:36 Save the image 00915N.png
 89%|█████████████████████████████████▊    | 1395/1568 [04:16<00:30,  5.60it/s]16 03:15:36 Save the image 00915N_flip.png
 89%|█████████████████████████████████▊    | 1396/1568 [04:17<00:31,  5.49it/s]16 03:15:37 Save the image 00916N.png
 89%|█████████████████████████████████▊    | 1397/1568 [04:17<00:31,  5.51it/s]16 03:15:37 Save the image 00916N_flip.png
 89%|█████████████████████████████████▉    | 1398/1568 [04:17<00:30,  5.49it/s]16 03:15:37 Save the image 00917N.png
 89%|█████████████████████████████████▉    | 1399/1568 [04:17<00:30,  5.47it/s]16 03:15:37 Save the image 00917N_flip.png
 89%|█████████████████████████████████▉    | 1400/1568 [04:17<00:30,  5.50it/s]16 03:15:37 Save the image 00918N.png

 89%|█████████████████████████████████▉    | 1401/1568 [04:17<00:30,  5.53it/s]16 03:15:37 Save the image 00918N_flip.png
 89%|█████████████████████████████████▉    | 1402/1568 [04:18<00:29,  5.58it/s]16 03:15:38 Save the image 00919N.png
 89%|██████████████████████████████████    | 1403/1568 [04:18<00:29,  5.58it/s]16 03:15:38 Save the image 00919N_flip.png
 90%|██████████████████████████████████    | 1404/1568 [04:18<00:29,  5.56it/s]16 03:15:38 Save the image 00920N.png
 90%|██████████████████████████████████    | 1405/1568 [04:18<00:29,  5.54it/s]16 03:15:38 Save the image 00920N_flip.png
 90%|██████████████████████████████████    | 1406/1568 [04:18<00:29,  5.55it/s]16 03:15:38 Save the image 00921N.png
 90%|██████████████████████████████████    | 1407/1568 [04:19<00:28,  5.56it/s]16 03:15:38 Save the image 00921N_flip.png
 90%|██████████████████████████████████    | 1408/1568 [04:19<00:29,  5.51it/s]16 03:15:39 Save the image 00922N.png
 90%|██████████████████████████████████▏   | 1409/1568 [04:19<00:29,  5.47it/s]16 03:15:39 Save the image 00922N_flip.png
 90%|██████████████████████████████████▏   | 1410/1568 [04:19<00:28,  5.45it/s]16 03:15:39 Save the image 00923N.png
 90%|██████████████████████████████████▏   | 1411/1568 [04:19<00:28,  5.47it/s]16 03:15:39 Save the image 00923N_flip.png
 90%|██████████████████████████████████▏   | 1412/1568 [04:19<00:28,  5.45it/s]16 03:15:39 Save the image 00924N.png
 90%|██████████████████████████████████▏   | 1413/1568 [04:20<00:28,  5.43it/s]16 03:15:40 Save the image 00924N_flip.png
 90%|██████████████████████████████████▎   | 1414/1568 [04:20<00:28,  5.41it/s]16 03:15:40 Save the image 00925N.png
 90%|██████████████████████████████████▎   | 1415/1568 [04:20<00:28,  5.39it/s]16 03:15:40 Save the image 00925N_flip.png
 90%|██████████████████████████████████▎   | 1416/1568 [04:20<00:28,  5.40it/s]16 03:15:40 Save the image 00926N.png
 90%|██████████████████████████████████▎   | 1417/1568 [04:20<00:28,  5.39it/s]16 03:15:40 Save the image 00926N_flip.png
 90%|██████████████████████████████████▎   | 1418/1568 [04:21<00:27,  5.42it/s]16 03:15:41 Save the image 00927N.png
 90%|██████████████████████████████████▍   | 1419/1568 [04:21<00:27,  5.37it/s]16 03:15:41 Save the image 00927N_flip.png
 91%|██████████████████████████████████▍   | 1420/1568 [04:21<00:27,  5.36it/s]16 03:15:41 Save the image 00928N.png
 91%|██████████████████████████████████▍   | 1421/1568 [04:21<00:27,  5.37it/s]16 03:15:41 Save the image 00928N_flip.png
 91%|██████████████████████████████████▍   | 1422/1568 [04:21<00:27,  5.37it/s]16 03:15:41 Save the image 00929N.png
 91%|██████████████████████████████████▍   | 1423/1568 [04:22<00:27,  5.31it/s]16 03:15:41 Save the image 00929N_flip.png
 91%|██████████████████████████████████▌   | 1424/1568 [04:22<00:27,  5.31it/s]16 03:15:42 Save the image 00930N.png
 91%|██████████████████████████████████▌   | 1425/1568 [04:22<00:26,  5.34it/s]16 03:15:42 Save the image 00930N_flip.png
 91%|██████████████████████████████████▌   | 1426/1568 [04:22<00:26,  5.36it/s]16 03:15:42 Save the image 00931N.png
 91%|██████████████████████████████████▌   | 1427/1568 [04:22<00:26,  5.36it/s]16 03:15:42 Save the image 00931N_flip.png
 91%|██████████████████████████████████▌   | 1428/1568 [04:22<00:25,  5.39it/s]16 03:15:42 Save the image 00932N.png
 91%|██████████████████████████████████▋   | 1429/1568 [04:23<00:26,  5.33it/s]16 03:15:43 Save the image 00932N_flip.png
 91%|██████████████████████████████████▋   | 1430/1568 [04:23<00:25,  5.43it/s]16 03:15:43 Save the image 00933N.png
 91%|██████████████████████████████████▋   | 1431/1568 [04:23<00:25,  5.44it/s]16 03:15:43 Save the image 00933N_flip.png
 91%|██████████████████████████████████▋   | 1432/1568 [04:23<00:25,  5.43it/s]16 03:15:43 Save the image 00934N.png
 91%|██████████████████████████████████▋   | 1433/1568 [04:23<00:24,  5.45it/s]16 03:15:43 Save the image 00934N_flip.png
 91%|██████████████████████████████████▊   | 1434/1568 [04:24<00:24,  5.43it/s]16 03:15:44 Save the image 00935N.png
 92%|██████████████████████████████████▊   | 1435/1568 [04:24<00:24,  5.42it/s]16 03:15:44 Save the image 00935N_flip.png
 92%|██████████████████████████████████▊   | 1436/1568 [04:24<00:24,  5.42it/s]16 03:15:44 Save the image 00936N.png
 92%|██████████████████████████████████▊   | 1437/1568 [04:24<00:24,  5.41it/s]16 03:15:44 Save the image 00936N_flip.png
 92%|██████████████████████████████████▊   | 1438/1568 [04:24<00:24,  5.40it/s]16 03:15:44 Save the image 00937N.png
 92%|██████████████████████████████████▊   | 1439/1568 [04:24<00:23,  5.40it/s]16 03:15:44 Save the image 00937N_flip.png
 92%|██████████████████████████████████▉   | 1440/1568 [04:25<00:23,  5.42it/s]16 03:15:45 Save the image 00938N.png
 92%|██████████████████████████████████▉   | 1441/1568 [04:25<00:23,  5.40it/s]16 03:15:45 Save the image 00938N_flip.png
 92%|██████████████████████████████████▉   | 1442/1568 [04:25<00:23,  5.34it/s]16 03:15:45 Save the image 00939N.png
 92%|██████████████████████████████████▉   | 1443/1568 [04:25<00:23,  5.33it/s]16 03:15:45 Save the image 00939N_flip.png
 92%|██████████████████████████████████▉   | 1444/1568 [04:25<00:23,  5.36it/s]16 03:15:45 Save the image 00940N.png
 92%|███████████████████████████████████   | 1445/1568 [04:26<00:22,  5.35it/s]16 03:15:46 Save the image 00940N_flip.png
 92%|███████████████████████████████████   | 1446/1568 [04:26<00:22,  5.34it/s]16 03:15:46 Save the image 00941N.png
 92%|███████████████████████████████████   | 1447/1568 [04:26<00:22,  5.36it/s]16 03:15:46 Save the image 00941N_flip.png
 92%|███████████████████████████████████   | 1448/1568 [04:26<00:22,  5.32it/s]16 03:15:46 Save the image 00942N.png
 92%|███████████████████████████████████   | 1449/1568 [04:26<00:22,  5.29it/s]16 03:15:46 Save the image 00942N_flip.png
 92%|███████████████████████████████████▏  | 1450/1568 [04:27<00:22,  5.30it/s]16 03:15:47 Save the image 00943N.png
 93%|███████████████████████████████████▏  | 1451/1568 [04:27<00:22,  5.31it/s]16 03:15:47 Save the image 00943N_flip.png
 93%|███████████████████████████████████▏  | 1452/1568 [04:27<00:20,  5.63it/s]16 03:15:47 Save the image 00944N.png
 93%|███████████████████████████████████▏  | 1453/1568 [04:27<00:20,  5.52it/s]16 03:15:47 Save the image 00944N_flip.png
 93%|███████████████████████████████████▏  | 1454/1568 [04:27<00:20,  5.50it/s]16 03:15:47 Save the image 00945N.png
 93%|███████████████████████████████████▎  | 1455/1568 [04:27<00:20,  5.47it/s]16 03:15:47 Save the image 00945N_flip.png
 93%|███████████████████████████████████▎  | 1456/1568 [04:28<00:20,  5.44it/s]16 03:15:48 Save the image 00946N.png
 93%|███████████████████████████████████▎  | 1457/1568 [04:28<00:20,  5.47it/s]16 03:15:48 Save the image 00946N_flip.png
 93%|███████████████████████████████████▎  | 1458/1568 [04:28<00:20,  5.46it/s]16 03:15:48 Save the image 00947N.png
 93%|███████████████████████████████████▎  | 1459/1568 [04:28<00:20,  5.42it/s]16 03:15:48 Save the image 00947N_flip.png
 93%|███████████████████████████████████▍  | 1460/1568 [04:28<00:19,  5.41it/s]16 03:15:48 Save the image 00948N.png
 93%|███████████████████████████████████▍  | 1461/1568 [04:29<00:19,  5.40it/s]16 03:15:49 Save the image 00948N_flip.png
 93%|███████████████████████████████████▍  | 1462/1568 [04:29<00:19,  5.41it/s]16 03:15:49 Save the image 00949N.png
 93%|███████████████████████████████████▍  | 1463/1568 [04:29<00:19,  5.40it/s]16 03:15:49 Save the image 00949N_flip.png
 93%|███████████████████████████████████▍  | 1464/1568 [04:29<00:19,  5.43it/s]16 03:15:49 Save the image 00950N.png

 93%|███████████████████████████████████▌  | 1465/1568 [04:29<00:19,  5.37it/s]16 03:15:49 Save the image 00950N_flip.png
 93%|███████████████████████████████████▌  | 1466/1568 [04:29<00:19,  5.36it/s]16 03:15:49 Save the image 00951N.png
 94%|███████████████████████████████████▌  | 1467/1568 [04:30<00:18,  5.37it/s]16 03:15:50 Save the image 00951N_flip.png
 94%|███████████████████████████████████▌  | 1468/1568 [04:30<00:18,  5.42it/s]16 03:15:50 Save the image 00952N.png
 94%|███████████████████████████████████▌  | 1469/1568 [04:30<00:18,  5.43it/s]16 03:15:50 Save the image 00952N_flip.png
 94%|███████████████████████████████████▋  | 1470/1568 [04:30<00:18,  5.39it/s]16 03:15:50 Save the image 00953N.png
 94%|███████████████████████████████████▋  | 1471/1568 [04:30<00:17,  5.40it/s]16 03:15:50 Save the image 00953N_flip.png
 94%|███████████████████████████████████▋  | 1472/1568 [04:31<00:17,  5.35it/s]16 03:15:51 Save the image 00954N.png
 94%|███████████████████████████████████▋  | 1473/1568 [04:31<00:17,  5.38it/s]16 03:15:51 Save the image 00954N_flip.png
 94%|███████████████████████████████████▋  | 1474/1568 [04:31<00:16,  5.70it/s]16 03:15:51 Save the image 00955N.png
 94%|███████████████████████████████████▋  | 1475/1568 [04:31<00:16,  5.56it/s]16 03:15:51 Save the image 00955N_flip.png
 94%|███████████████████████████████████▊  | 1476/1568 [04:31<00:16,  5.54it/s]16 03:15:51 Save the image 00956N.png
 94%|███████████████████████████████████▊  | 1477/1568 [04:32<00:16,  5.53it/s]16 03:15:51 Save the image 00956N_flip.png
 94%|███████████████████████████████████▊  | 1478/1568 [04:32<00:16,  5.43it/s]16 03:15:52 Save the image 00957N.png
 94%|███████████████████████████████████▊  | 1479/1568 [04:32<00:16,  5.45it/s]16 03:15:52 Save the image 00957N_flip.png
 94%|███████████████████████████████████▊  | 1480/1568 [04:32<00:16,  5.50it/s]16 03:15:52 Save the image 00958N.png
 94%|███████████████████████████████████▉  | 1481/1568 [04:32<00:16,  5.42it/s]16 03:15:52 Save the image 00958N_flip.png
 95%|███████████████████████████████████▉  | 1482/1568 [04:32<00:16,  5.36it/s]16 03:15:52 Save the image 00959N.png
 95%|███████████████████████████████████▉  | 1483/1568 [04:33<00:15,  5.38it/s]16 03:15:53 Save the image 00959N_flip.png
 95%|███████████████████████████████████▉  | 1484/1568 [04:33<00:15,  5.35it/s]16 03:15:53 Save the image 00960N.png
 95%|███████████████████████████████████▉  | 1485/1568 [04:33<00:15,  5.40it/s]16 03:15:53 Save the image 00960N_flip.png
 95%|████████████████████████████████████  | 1486/1568 [04:33<00:15,  5.41it/s]16 03:15:53 Save the image 00961N.png
 95%|████████████████████████████████████  | 1487/1568 [04:33<00:14,  5.41it/s]16 03:15:53 Save the image 00961N_flip.png
 95%|████████████████████████████████████  | 1488/1568 [04:34<00:14,  5.36it/s]16 03:15:53 Save the image 00962N.png
 95%|████████████████████████████████████  | 1489/1568 [04:34<00:14,  5.36it/s]16 03:15:54 Save the image 00962N_flip.png
 95%|████████████████████████████████████  | 1490/1568 [04:34<00:14,  5.36it/s]16 03:15:54 Save the image 00963N.png
 95%|████████████████████████████████████▏ | 1491/1568 [04:34<00:14,  5.40it/s]16 03:15:54 Save the image 00963N_flip.png
 95%|████████████████████████████████████▏ | 1492/1568 [04:34<00:14,  5.41it/s]16 03:15:54 Save the image 00964N.png
 95%|████████████████████████████████████▏ | 1493/1568 [04:34<00:13,  5.38it/s]16 03:15:54 Save the image 00964N_flip.png
 95%|████████████████████████████████████▏ | 1494/1568 [04:35<00:13,  5.39it/s]16 03:15:55 Save the image 00965N.png
 95%|████████████████████████████████████▏ | 1495/1568 [04:35<00:13,  5.39it/s]16 03:15:55 Save the image 00965N_flip.png
 95%|████████████████████████████████████▎ | 1496/1568 [04:35<00:12,  5.73it/s]16 03:15:55 Save the image 00966N.png
 95%|████████████████████████████████████▎ | 1497/1568 [04:35<00:12,  5.63it/s]16 03:15:55 Save the image 00966N_flip.png
 96%|████████████████████████████████████▎ | 1498/1568 [04:35<00:12,  5.56it/s]16 03:15:55 Save the image 00967N.png
 96%|████████████████████████████████████▎ | 1499/1568 [04:36<00:12,  5.54it/s]16 03:15:55 Save the image 00967N_flip.png
 96%|████████████████████████████████████▎ | 1500/1568 [04:36<00:12,  5.48it/s]16 03:15:56 Save the image 00968N.png
 96%|████████████████████████████████████▍ | 1501/1568 [04:36<00:12,  5.48it/s]16 03:15:56 Save the image 00968N_flip.png
 96%|████████████████████████████████████▍ | 1502/1568 [04:36<00:12,  5.46it/s]16 03:15:56 Save the image 00969N.png
 96%|████████████████████████████████████▍ | 1503/1568 [04:36<00:12,  5.41it/s]16 03:15:56 Save the image 00969N_flip.png
 96%|████████████████████████████████████▍ | 1504/1568 [04:36<00:11,  5.40it/s]16 03:15:56 Save the image 00970N.png
 96%|████████████████████████████████████▍ | 1505/1568 [04:37<00:11,  5.45it/s]16 03:15:57 Save the image 00970N_flip.png
 96%|████████████████████████████████████▍ | 1506/1568 [04:37<00:11,  5.44it/s]16 03:15:57 Save the image 00971N.png
 96%|████████████████████████████████████▌ | 1507/1568 [04:37<00:11,  5.37it/s]16 03:15:57 Save the image 00971N_flip.png
 96%|████████████████████████████████████▌ | 1508/1568 [04:37<00:11,  5.38it/s]16 03:15:57 Save the image 00972N.png
 96%|████████████████████████████████████▌ | 1509/1568 [04:37<00:11,  5.36it/s]16 03:15:57 Save the image 00972N_flip.png
 96%|████████████████████████████████████▌ | 1510/1568 [04:38<00:10,  5.32it/s]16 03:15:58 Save the image 00973N.png
 96%|████████████████████████████████████▌ | 1511/1568 [04:38<00:10,  5.33it/s]16 03:15:58 Save the image 00973N_flip.png
 96%|████████████████████████████████████▋ | 1512/1568 [04:38<00:10,  5.34it/s]16 03:15:58 Save the image 00974N.png
 96%|████████████████████████████████████▋ | 1513/1568 [04:38<00:10,  5.36it/s]16 03:15:58 Save the image 00974N_flip.png
 97%|████████████████████████████████████▋ | 1514/1568 [04:38<00:10,  5.38it/s]16 03:15:58 Save the image 00975N.png
 97%|████████████████████████████████████▋ | 1515/1568 [04:39<00:09,  5.38it/s]16 03:15:58 Save the image 00975N_flip.png
 97%|████████████████████████████████████▋ | 1516/1568 [04:39<00:09,  5.36it/s]16 03:15:59 Save the image 00976N.png
 97%|████████████████████████████████████▊ | 1517/1568 [04:39<00:09,  5.38it/s]16 03:15:59 Save the image 00976N_flip.png
 97%|████████████████████████████████████▊ | 1518/1568 [04:39<00:08,  5.72it/s]16 03:15:59 Save the image 00977N.png
 97%|████████████████████████████████████▊ | 1519/1568 [04:39<00:08,  5.56it/s]16 03:15:59 Save the image 00977N_flip.png
 97%|████████████████████████████████████▊ | 1520/1568 [04:39<00:08,  5.54it/s]16 03:15:59 Save the image 00978N.png
 97%|████████████████████████████████████▊ | 1521/1568 [04:40<00:08,  5.55it/s]16 03:16:00 Save the image 00978N_flip.png
 97%|████████████████████████████████████▉ | 1522/1568 [04:40<00:08,  5.45it/s]16 03:16:00 Save the image 00979N.png
 97%|████████████████████████████████████▉ | 1523/1568 [04:40<00:08,  5.49it/s]16 03:16:00 Save the image 00979N_flip.png
 97%|████████████████████████████████████▉ | 1524/1568 [04:40<00:07,  5.51it/s]16 03:16:00 Save the image 00980N.png
 97%|████████████████████████████████████▉ | 1525/1568 [04:40<00:07,  5.42it/s]16 03:16:00 Save the image 00980N_flip.png
 97%|████████████████████████████████████▉ | 1526/1568 [04:41<00:07,  5.41it/s]16 03:16:00 Save the image 00981N.png
 97%|█████████████████████████████████████ | 1527/1568 [04:41<00:07,  5.46it/s]16 03:16:01 Save the image 00981N_flip.png
 97%|█████████████████████████████████████ | 1528/1568 [04:41<00:07,  5.35it/s]16 03:16:01 Save the image 00982N.png

 98%|█████████████████████████████████████ | 1529/1568 [04:41<00:07,  5.40it/s]16 03:16:01 Save the image 00982N_flip.png
 98%|█████████████████████████████████████ | 1530/1568 [04:41<00:07,  5.41it/s]16 03:16:01 Save the image 00983N.png
 98%|█████████████████████████████████████ | 1531/1568 [04:41<00:06,  5.35it/s]16 03:16:01 Save the image 00983N_flip.png
 98%|█████████████████████████████████████▏| 1532/1568 [04:42<00:06,  5.35it/s]16 03:16:02 Save the image 00984N.png
 98%|█████████████████████████████████████▏| 1533/1568 [04:42<00:06,  5.36it/s]16 03:16:02 Save the image 00984N_flip.png
 98%|█████████████████████████████████████▏| 1534/1568 [04:42<00:06,  5.35it/s]16 03:16:02 Save the image 00985N.png
 98%|█████████████████████████████████████▏| 1535/1568 [04:42<00:06,  5.38it/s]16 03:16:02 Save the image 00985N_flip.png
 98%|█████████████████████████████████████▏| 1536/1568 [04:42<00:06,  5.27it/s]16 03:16:02 Save the image 00986N.png
 98%|█████████████████████████████████████▏| 1537/1568 [04:43<00:05,  5.30it/s]16 03:16:03 Save the image 00986N_flip.png
 98%|█████████████████████████████████████▎| 1538/1568 [04:43<00:05,  5.35it/s]16 03:16:03 Save the image 00987N.png
 98%|█████████████████████████████████████▎| 1539/1568 [04:43<00:05,  5.42it/s]16 03:16:03 Save the image 00987N_flip.png
 98%|█████████████████████████████████████▎| 1540/1568 [04:43<00:04,  5.73it/s]16 03:16:03 Save the image 00988N.png
 98%|█████████████████████████████████████▎| 1541/1568 [04:43<00:04,  5.63it/s]16 03:16:03 Save the image 00988N_flip.png
 98%|█████████████████████████████████████▎| 1542/1568 [04:43<00:04,  5.60it/s]16 03:16:03 Save the image 00989N.png
 98%|█████████████████████████████████████▍| 1543/1568 [04:44<00:04,  5.55it/s]16 03:16:04 Save the image 00989N_flip.png
 98%|█████████████████████████████████████▍| 1544/1568 [04:44<00:04,  5.50it/s]16 03:16:04 Save the image 00990N.png
 99%|█████████████████████████████████████▍| 1545/1568 [04:44<00:04,  5.51it/s]16 03:16:04 Save the image 00990N_flip.png
 99%|█████████████████████████████████████▍| 1546/1568 [04:44<00:03,  5.51it/s]16 03:16:04 Save the image 00991N.png
 99%|█████████████████████████████████████▍| 1547/1568 [04:44<00:03,  5.48it/s]16 03:16:04 Save the image 00991N_flip.png
 99%|█████████████████████████████████████▌| 1548/1568 [04:45<00:03,  5.44it/s]16 03:16:05 Save the image 00992N.png
 99%|█████████████████████████████████████▌| 1549/1568 [04:45<00:03,  5.43it/s]16 03:16:05 Save the image 00992N_flip.png
 99%|█████████████████████████████████████▌| 1550/1568 [04:45<00:03,  5.44it/s]16 03:16:05 Save the image 00993N.png
 99%|█████████████████████████████████████▌| 1551/1568 [04:45<00:03,  5.44it/s]16 03:16:05 Save the image 00993N_flip.png
 99%|█████████████████████████████████████▌| 1552/1568 [04:45<00:02,  5.38it/s]16 03:16:05 Save the image 00994N.png
 99%|█████████████████████████████████████▋| 1553/1568 [04:45<00:02,  5.37it/s]16 03:16:05 Save the image 00994N_flip.png
 99%|█████████████████████████████████████▋| 1554/1568 [04:46<00:02,  5.38it/s]16 03:16:06 Save the image 00995N.png
 99%|█████████████████████████████████████▋| 1555/1568 [04:46<00:02,  5.37it/s]16 03:16:06 Save the image 00995N_flip.png
 99%|█████████████████████████████████████▋| 1556/1568 [04:46<00:02,  5.29it/s]16 03:16:06 Save the image 00996N.png
 99%|█████████████████████████████████████▋| 1557/1568 [04:46<00:02,  5.33it/s]16 03:16:06 Save the image 00996N_flip.png
 99%|█████████████████████████████████████▊| 1558/1568 [04:46<00:01,  5.29it/s]16 03:16:06 Save the image 00997N.png
 99%|█████████████████████████████████████▊| 1559/1568 [04:47<00:01,  5.27it/s]16 03:16:07 Save the image 00997N_flip.png
 99%|█████████████████████████████████████▊| 1560/1568 [04:47<00:01,  5.31it/s]16 03:16:07 Save the image 00998N.png
100%|█████████████████████████████████████▊| 1561/1568 [04:47<00:01,  5.36it/s]16 03:16:07 Save the image 00998N_flip.png
100%|█████████████████████████████████████▊| 1562/1568 [04:47<00:01,  5.38it/s]16 03:16:07 Save the image 00999N.png
100%|█████████████████████████████████████▉| 1563/1568 [04:47<00:00,  5.41it/s]16 03:16:07 Save the image 00999N_flip.png
100%|█████████████████████████████████████▉| 1564/1568 [04:48<00:00,  5.45it/s]16 03:16:07 Save the image 01000N.png
100%|█████████████████████████████████████▉| 1565/1568 [04:48<00:00,  5.36it/s]16 03:16:08 Save the image 01000N_flip.png
100%|█████████████████████████████████████▉| 1566/1568 [04:48<00:00,  5.39it/s]16 03:16:08 Save the image 01001N.png
100%|█████████████████████████████████████▉| 1567/1568 [04:48<00:00,  5.40it/s]16 03:16:08 Save the image 01001N_flip.png
100%|██████████████████████████████████████| 1568/1568 [04:48<00:00,  5.43it/s]
1 unlabeled	99.659%
2 car   	97.970%
3 person	91.854%
4 bike  	92.752%
5 curve 	93.865%
6 car_stop	94.882%
7 guardrail	97.351%
8 color_cone	89.706%
9 bump  	96.198%
----------     mean_IoU	94.915%	freq_IoU	99.351%	mean_pixel_acc	97.607%	pixel_acc	99.670%
16 03:16:08 Evaluation Elapsed Time: 288.80s

# e4

In [20]:
import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E4")

!python eval.py -e 100 -d 0 --split test -p predictions_E4_test

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 03:17:58 using devices 0
16 03:17:58 Using E4: SegFormer-B2 with reliability-gated rectification
16 03:17:58 Using MLP Decoder
16 03:18:01 Load Model: /home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2_e4/checkpoint/epoch-100.pth
16 03:18:06 Load model, Time usage:
	IO: 4.23034930229187, initialize parameters: 0.04506731033325195
16 03:18:06 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@12.651] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 03:18:08 Save the image 01402D.png
  0%|                                          | 1/393 [00:02<16:59,  2.60s/it]16 03:18:09 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:02<07:39,  1.17s/it]16 03:18:09 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:02<04:39,  1.39it/s]16 03:18:09 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:03<03:16,  1.98it/s]16 03:18:09 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:03<02:28,  2.60it/s]16 03:18:09 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:03<02:01,  3.20it/s]16 03:18:09 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:03<01:43,  3.74it/s]16 03:18:10 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:03<01:31,  4.22it/s]16 03:18:10 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:03<01:23,  4.61it/s]16 03:18:10 Save the image 01411D.png
  3%|█                                        | 10/393 [00:04<01:17,  4.94it/s]16 03:18:10 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:04<01:14,  5.15it/s]16 03:18:10 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:04<01:11,  5.30it/s]16 03:18:10 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:04<01:09,  5.44it/s]16 03:18:11 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:04<01:09,  5.48it/s]16 03:18:11 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:05<01:08,  5.49it/s]16 03:18:11 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:05<01:07,  5.55it/s]16 03:18:11 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:05<01:07,  5.60it/s]16 03:18:11 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:05<01:07,  5.58it/s]16 03:18:12 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:05<01:06,  5.60it/s]16 03:18:12 Save the image 01421D.png
  5%|██                                       | 20/393 [00:05<01:07,  5.57it/s]16 03:18:12 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:06<01:06,  5.62it/s]16 03:18:12 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:06<01:04,  5.71it/s]16 03:18:12 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:06<01:02,  5.90it/s]16 03:18:12 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:06<01:03,  5.81it/s]16 03:18:13 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:06<01:03,  5.78it/s]16 03:18:13 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:06<01:03,  5.77it/s]16 03:18:13 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:07<01:03,  5.75it/s]16 03:18:13 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:07<01:03,  5.73it/s]16 03:18:13 Save the image 01430D.png
  7%|███                                      | 29/393 [00:07<01:03,  5.72it/s]16 03:18:13 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:07<01:03,  5.72it/s]16 03:18:14 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:07<00:59,  6.03it/s]16 03:18:14 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:07<01:01,  5.89it/s]16 03:18:14 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:08<01:02,  5.80it/s]16 03:18:14 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:08<01:01,  5.83it/s]16 03:18:14 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:08<01:01,  5.78it/s]16 03:18:14 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:08<01:02,  5.76it/s]16 03:18:15 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:08<01:02,  5.73it/s]16 03:18:15 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:09<01:02,  5.72it/s]16 03:18:15 Save the image 01440D.png
 10%|████                                     | 39/393 [00:09<00:59,  5.99it/s]16 03:18:15 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:09<01:00,  5.86it/s]16 03:18:15 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:09<01:00,  5.83it/s]16 03:18:15 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:09<01:00,  5.81it/s]16 03:18:16 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:09<01:00,  5.75it/s]16 03:18:16 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:10<01:00,  5.73it/s]16 03:18:16 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:10<01:00,  5.73it/s]16 03:18:16 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:10<01:01,  5.68it/s]16 03:18:16 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:10<00:57,  5.99it/s]16 03:18:17 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:10<00:58,  5.88it/s]16 03:18:17 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:10<00:58,  5.83it/s]16 03:18:17 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:11<00:59,  5.81it/s]16 03:18:17 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:11<00:59,  5.77it/s]16 03:18:17 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:11<00:59,  5.75it/s]16 03:18:17 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:11<00:59,  5.73it/s]16 03:18:18 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:11<00:59,  5.71it/s]16 03:18:18 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:11<00:55,  6.08it/s]16 03:18:18 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:12<00:56,  5.92it/s]16 03:18:18 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:12<00:57,  5.89it/s]16 03:18:18 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:12<00:57,  5.87it/s]16 03:18:18 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:12<00:57,  5.78it/s]16 03:18:19 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:12<00:58,  5.73it/s]16 03:18:19 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:12<00:58,  5.71it/s]16 03:18:19 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:13<00:58,  5.70it/s]16 03:18:19 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:13<00:54,  6.09it/s]16 03:18:19 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:13<00:55,  5.95it/s]16 03:18:19 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:13<00:55,  5.88it/s]16 03:18:20 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:13<00:55,  5.85it/s]16 03:18:20 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:14<00:56,  5.77it/s]16 03:18:20 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:14<00:56,  5.75it/s]16 03:18:20 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:14<00:56,  5.73it/s]16 03:18:20 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:14<00:56,  5.73it/s]16 03:18:20 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:14<00:53,  6.07it/s]16 03:18:21 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:14<00:54,  5.84it/s]16 03:18:21 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:15<00:54,  5.82it/s]16 03:18:21 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:15<00:54,  5.82it/s]16 03:18:21 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:15<00:55,  5.74it/s]16 03:18:21 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:15<00:55,  5.76it/s]16 03:18:22 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:15<00:55,  5.74it/s]16 03:18:22 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:15<00:55,  5.72it/s]16 03:18:22 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:16<00:51,  6.06it/s]16 03:18:22 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:16<00:52,  5.93it/s]16 03:18:22 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:16<00:52,  5.90it/s]16 03:18:22 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:16<00:53,  5.86it/s]16 03:18:23 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:16<00:53,  5.79it/s]16 03:18:23 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:16<00:53,  5.79it/s]16 03:18:23 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:17<00:53,  5.76it/s]16 03:18:23 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:17<00:53,  5.75it/s]16 03:18:23 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:17<00:50,  6.10it/s]16 03:18:23 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:17<00:51,  5.94it/s]16 03:18:24 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:17<00:51,  5.88it/s]16 03:18:24 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:17<00:51,  5.86it/s]16 03:18:24 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:18<00:52,  5.77it/s]16 03:18:24 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:18<00:51,  5.81it/s]16 03:18:24 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:18<00:51,  5.78it/s]16 03:18:24 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:18<00:51,  5.76it/s]16 03:18:25 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:18<00:48,  6.12it/s]16 03:18:25 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:18<00:49,  5.95it/s]16 03:18:25 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:19<00:50,  5.89it/s]16 03:18:25 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:19<00:50,  5.85it/s]16 03:18:25 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:19<00:50,  5.78it/s]16 03:18:25 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:19<00:50,  5.80it/s]16 03:18:26 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:19<00:50,  5.77it/s]16 03:18:26 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:20<00:50,  5.75it/s]16 03:18:26 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:20<00:47,  6.07it/s]16 03:18:26 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:20<00:48,  5.93it/s]16 03:18:26 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:20<00:49,  5.87it/s]16 03:18:26 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:20<00:49,  5.86it/s]16 03:18:27 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:20<00:49,  5.78it/s]16 03:18:27 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:21<00:49,  5.76it/s]16 03:18:27 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:21<00:49,  5.73it/s]16 03:18:27 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:21<00:49,  5.74it/s]16 03:18:27 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:21<00:46,  6.08it/s]16 03:18:27 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:21<00:47,  5.92it/s]16 03:18:28 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:21<00:47,  5.87it/s]16 03:18:28 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:22<00:47,  5.85it/s]16 03:18:28 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:22<00:48,  5.76it/s]16 03:18:28 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:22<00:47,  5.78it/s]16 03:18:28 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:22<00:48,  5.75it/s]16 03:18:29 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:22<00:47,  5.73it/s]16 03:18:29 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:22<00:47,  5.77it/s]16 03:18:29 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:23<00:47,  5.74it/s]16 03:18:29 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:23<00:47,  5.76it/s]16 03:18:29 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:23<00:47,  5.74it/s]16 03:18:29 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:23<00:47,  5.73it/s]16 03:18:30 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:23<00:46,  5.75it/s]16 03:18:30 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:23<00:46,  5.79it/s]16 03:18:30 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:24<00:46,  5.76it/s]16 03:18:30 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:24<00:46,  5.73it/s]16 03:18:30 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:24<00:46,  5.71it/s]16 03:18:30 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:24<00:46,  5.74it/s]16 03:18:31 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:24<00:45,  5.72it/s]16 03:18:31 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:25<00:45,  5.72it/s]16 03:18:31 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:25<00:45,  5.78it/s]16 03:18:31 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:25<00:44,  5.80it/s]16 03:18:31 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:25<00:44,  5.76it/s]16 03:18:31 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:25<00:45,  5.71it/s]16 03:18:32 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:25<00:45,  5.71it/s]16 03:18:32 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:26<00:45,  5.64it/s]16 03:18:32 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:26<00:45,  5.55it/s]16 03:18:32 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:26<00:45,  5.57it/s]16 03:18:32 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:26<00:45,  5.60it/s]16 03:18:33 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:26<00:44,  5.63it/s]16 03:18:33 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:26<00:41,  5.99it/s]16 03:18:33 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:27<00:42,  5.86it/s]16 03:18:33 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:27<00:42,  5.83it/s]16 03:18:33 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:27<00:42,  5.80it/s]16 03:18:33 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:27<00:43,  5.73it/s]16 03:18:34 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:27<00:42,  5.78it/s]16 03:18:34 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:27<00:42,  5.75it/s]16 03:18:34 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:28<00:42,  5.75it/s]16 03:18:34 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:28<00:39,  6.11it/s]16 03:18:34 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:28<00:40,  5.91it/s]16 03:18:34 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:28<00:41,  5.86it/s]16 03:18:35 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:28<00:41,  5.85it/s]16 03:18:35 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:29<00:41,  5.75it/s]16 03:18:35 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:29<00:42,  5.66it/s]16 03:18:35 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:29<00:41,  5.65it/s]16 03:18:35 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:29<00:41,  5.66it/s]16 03:18:35 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:29<00:39,  5.99it/s]16 03:18:36 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:29<00:39,  5.87it/s]16 03:18:36 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:30<00:39,  5.84it/s]16 03:18:36 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:30<00:39,  5.83it/s]16 03:18:36 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:30<00:40,  5.75it/s]16 03:18:36 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:30<00:40,  5.73it/s]16 03:18:37 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:30<00:39,  5.73it/s]16 03:18:37 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:30<00:39,  5.72it/s]16 03:18:37 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:31<00:37,  6.05it/s]16 03:18:37 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:31<00:38,  5.90it/s]16 03:18:37 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:31<00:38,  5.88it/s]16 03:18:37 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:31<00:38,  5.85it/s]16 03:18:38 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:31<00:38,  5.80it/s]16 03:18:38 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:31<00:38,  5.79it/s]16 03:18:38 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:32<00:38,  5.78it/s]16 03:18:38 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:32<00:38,  5.77it/s]16 03:18:38 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:32<00:35,  6.14it/s]16 03:18:38 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:32<00:36,  5.97it/s]16 03:18:39 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:32<00:36,  5.89it/s]16 03:18:39 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:32<00:36,  5.87it/s]16 03:18:39 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:33<00:37,  5.76it/s]16 03:18:39 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:33<00:37,  5.71it/s]16 03:18:39 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:33<00:37,  5.72it/s]16 03:18:39 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:33<00:37,  5.71it/s]16 03:18:40 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:33<00:34,  6.04it/s]16 03:18:40 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:33<00:35,  5.90it/s]16 03:18:40 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:34<00:35,  5.85it/s]16 03:18:40 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:34<00:35,  5.83it/s]16 03:18:40 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:34<00:35,  5.76it/s]16 03:18:40 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:34<00:35,  5.77it/s]16 03:18:41 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:34<00:35,  5.76it/s]16 03:18:41 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:35<00:35,  5.73it/s]16 03:18:41 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:35<00:33,  6.09it/s]16 03:18:41 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:35<00:34,  5.93it/s]16 03:18:41 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:35<00:34,  5.88it/s]16 03:18:41 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:35<00:34,  5.83it/s]16 03:18:42 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:35<00:34,  5.75it/s]16 03:18:42 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:36<00:34,  5.76it/s]16 03:18:42 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:36<00:34,  5.74it/s]16 03:18:42 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:36<00:34,  5.73it/s]16 03:18:42 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:36<00:32,  6.06it/s]16 03:18:42 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:36<00:32,  5.94it/s]16 03:18:43 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:36<00:32,  5.86it/s]16 03:18:43 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:37<00:33,  5.81it/s]16 03:18:43 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:37<00:33,  5.75it/s]16 03:18:43 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:37<00:32,  5.79it/s]16 03:18:43 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:37<00:32,  5.76it/s]16 03:18:44 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:37<00:32,  5.74it/s]16 03:18:44 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:37<00:30,  6.12it/s]16 03:18:44 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:38<00:31,  5.98it/s]16 03:18:44 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:38<00:31,  5.93it/s]16 03:18:44 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:38<00:31,  5.87it/s]16 03:18:44 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:38<00:31,  5.81it/s]16 03:18:45 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:38<00:31,  5.78it/s]16 03:18:45 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:38<00:31,  5.75it/s]16 03:18:45 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:39<00:31,  5.73it/s]16 03:18:45 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:39<00:29,  6.05it/s]16 03:18:45 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:39<00:30,  5.93it/s]16 03:18:45 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:39<00:30,  5.90it/s]16 03:18:46 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:39<00:29,  5.88it/s]16 03:18:46 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:39<00:30,  5.75it/s]16 03:18:46 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:40<00:30,  5.75it/s]16 03:18:46 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:40<00:30,  5.74it/s]16 03:18:46 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:40<00:29,  5.74it/s]16 03:18:46 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:40<00:27,  6.12it/s]16 03:18:47 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:40<00:28,  5.97it/s]16 03:18:47 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:40<00:28,  5.92it/s]16 03:18:47 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:41<00:28,  5.90it/s]16 03:18:47 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:41<00:28,  5.82it/s]16 03:18:47 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:41<00:28,  5.79it/s]16 03:18:47 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:41<00:28,  5.79it/s]16 03:18:48 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:41<00:28,  5.78it/s]16 03:18:48 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:41<00:26,  6.14it/s]16 03:18:48 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:42<00:26,  6.02it/s]16 03:18:48 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:42<00:27,  5.96it/s]16 03:18:48 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:42<00:26,  5.93it/s]16 03:18:48 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:42<00:27,  5.88it/s]16 03:18:49 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:42<00:27,  5.84it/s]16 03:18:49 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:43<00:26,  5.82it/s]16 03:18:49 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:43<00:26,  5.82it/s]16 03:18:49 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:43<00:26,  5.92it/s]16 03:18:49 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:43<00:26,  5.87it/s]16 03:18:49 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:43<00:26,  5.85it/s]16 03:18:50 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:43<00:25,  5.85it/s]16 03:18:50 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:44<00:26,  5.78it/s]16 03:18:50 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:44<00:25,  5.78it/s]16 03:18:50 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:44<00:25,  5.77it/s]16 03:18:50 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:44<00:25,  5.81it/s]16 03:18:50 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:44<00:24,  5.95it/s]16 03:18:51 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:44<00:24,  5.88it/s]16 03:18:51 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:45<00:24,  5.85it/s]16 03:18:51 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:45<00:24,  5.84it/s]16 03:18:51 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:45<00:24,  5.79it/s]16 03:18:51 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:45<00:24,  5.77it/s]16 03:18:52 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:45<00:24,  5.76it/s]16 03:18:52 Save the image 01236N.png

 64%|█████████████████████████▊              | 253/393 [00:45<00:24,  5.80it/s]16 03:18:52 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:46<00:23,  5.92it/s]16 03:18:52 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:46<00:23,  5.88it/s]16 03:18:52 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:46<00:23,  5.86it/s]16 03:18:52 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:46<00:23,  5.85it/s]16 03:18:53 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:46<00:23,  5.83it/s]16 03:18:53 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:46<00:23,  5.81it/s]16 03:18:53 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:47<00:22,  5.80it/s]16 03:18:53 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:47<00:22,  5.82it/s]16 03:18:53 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:47<00:22,  5.92it/s]16 03:18:53 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:47<00:22,  5.83it/s]16 03:18:54 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:47<00:22,  5.82it/s]16 03:18:54 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:47<00:21,  5.84it/s]16 03:18:54 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:48<00:21,  5.80it/s]16 03:18:54 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:48<00:22,  5.72it/s]16 03:18:54 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:48<00:21,  5.71it/s]16 03:18:54 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:48<00:21,  5.76it/s]16 03:18:55 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:48<00:21,  5.81it/s]16 03:18:55 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:49<00:21,  5.80it/s]16 03:18:55 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:49<00:20,  5.81it/s]16 03:18:55 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:49<00:20,  5.78it/s]16 03:18:55 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:49<00:20,  5.78it/s]16 03:18:56 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:49<00:20,  5.75it/s]16 03:18:56 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:49<00:20,  5.71it/s]16 03:18:56 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:50<00:20,  5.73it/s]16 03:18:56 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:50<00:19,  5.76it/s]16 03:18:56 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:50<00:19,  5.72it/s]16 03:18:56 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:50<00:19,  5.73it/s]16 03:18:57 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:50<00:19,  5.75it/s]16 03:18:57 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:50<00:19,  5.73it/s]16 03:18:57 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:51<00:19,  5.73it/s]16 03:18:57 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:51<00:19,  5.67it/s]16 03:18:57 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:51<00:18,  5.73it/s]16 03:18:57 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:51<00:18,  5.75it/s]16 03:18:58 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:51<00:18,  5.71it/s]16 03:18:58 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:52<00:18,  5.70it/s]16 03:18:58 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:52<00:18,  5.71it/s]16 03:18:58 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:52<00:18,  5.68it/s]16 03:18:58 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:52<00:18,  5.66it/s]16 03:18:58 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:52<00:17,  5.63it/s]16 03:18:59 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:52<00:17,  5.68it/s]16 03:18:59 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:53<00:16,  5.85it/s]16 03:18:59 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:53<00:16,  5.78it/s]16 03:18:59 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:53<00:16,  5.76it/s]16 03:18:59 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:53<00:16,  5.78it/s]16 03:19:00 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:53<00:16,  5.73it/s]16 03:19:00 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:53<00:16,  5.73it/s]16 03:19:00 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:54<00:16,  5.74it/s]16 03:19:00 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:54<00:15,  5.79it/s]16 03:19:00 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:54<00:15,  6.01it/s]16 03:19:00 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:54<00:15,  5.90it/s]16 03:19:01 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:54<00:15,  5.88it/s]16 03:19:01 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:54<00:15,  5.82it/s]16 03:19:01 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:55<00:15,  5.73it/s]16 03:19:01 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:55<00:15,  5.68it/s]16 03:19:01 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:55<00:14,  5.69it/s]16 03:19:01 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:55<00:14,  5.72it/s]16 03:19:02 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:55<00:14,  5.83it/s]16 03:19:02 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:55<00:14,  5.77it/s]16 03:19:02 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:56<00:14,  5.71it/s]16 03:19:02 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:56<00:13,  5.73it/s]16 03:19:02 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:56<00:13,  5.68it/s]16 03:19:02 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:56<00:13,  5.60it/s]16 03:19:03 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:56<00:13,  5.61it/s]16 03:19:03 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:57<00:13,  5.69it/s]16 03:19:03 Save the image 01301N.png

 81%|████████████████████████████████▎       | 318/393 [00:57<00:12,  5.80it/s]16 03:19:03 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:57<00:12,  5.70it/s]16 03:19:03 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:57<00:12,  5.72it/s]16 03:19:04 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:57<00:12,  5.68it/s]16 03:19:04 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:57<00:12,  5.69it/s]16 03:19:04 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [00:58<00:12,  5.66it/s]16 03:19:04 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:58<00:12,  5.66it/s]16 03:19:04 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:58<00:11,  5.70it/s]16 03:19:04 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:58<00:11,  5.74it/s]16 03:19:05 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:58<00:11,  5.70it/s]16 03:19:05 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:58<00:11,  5.69it/s]16 03:19:05 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:59<00:11,  5.66it/s]16 03:19:05 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:59<00:11,  5.65it/s]16 03:19:05 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:59<00:11,  5.62it/s]16 03:19:05 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [00:59<00:10,  5.61it/s]16 03:19:06 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:59<00:10,  5.66it/s]16 03:19:06 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [01:00<00:10,  5.69it/s]16 03:19:06 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [01:00<00:10,  5.66it/s]16 03:19:06 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [01:00<00:10,  5.66it/s]16 03:19:06 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [01:00<00:09,  5.69it/s]16 03:19:07 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [01:00<00:09,  5.70it/s]16 03:19:07 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [01:00<00:09,  5.67it/s]16 03:19:07 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [01:01<00:09,  5.63it/s]16 03:19:07 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [01:01<00:09,  5.67it/s]16 03:19:07 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [01:01<00:08,  5.81it/s]16 03:19:07 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [01:01<00:08,  5.75it/s]16 03:19:08 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [01:01<00:08,  5.74it/s]16 03:19:08 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [01:01<00:08,  5.69it/s]16 03:19:08 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [01:02<00:08,  5.66it/s]16 03:19:08 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [01:02<00:08,  5.69it/s]16 03:19:08 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [01:02<00:07,  5.70it/s]16 03:19:08 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [01:02<00:07,  5.76it/s]16 03:19:09 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [01:02<00:07,  5.86it/s]16 03:19:09 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [01:03<00:07,  5.75it/s]16 03:19:09 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [01:03<00:07,  5.73it/s]16 03:19:09 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [01:03<00:06,  5.74it/s]16 03:19:09 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [01:03<00:06,  5.68it/s]16 03:19:09 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [01:03<00:06,  5.65it/s]16 03:19:10 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [01:03<00:06,  5.67it/s]16 03:19:10 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [01:04<00:06,  5.68it/s]16 03:19:10 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [01:04<00:06,  5.78it/s]16 03:19:10 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [01:04<00:05,  5.74it/s]16 03:19:10 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [01:04<00:05,  5.76it/s]16 03:19:11 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [01:04<00:05,  5.76it/s]16 03:19:11 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [01:04<00:05,  5.76it/s]16 03:19:11 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [01:05<00:05,  5.76it/s]16 03:19:11 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [01:05<00:05,  5.70it/s]16 03:19:11 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [01:05<00:04,  5.72it/s]16 03:19:11 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [01:05<00:04,  5.83it/s]16 03:19:12 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [01:05<00:04,  5.76it/s]16 03:19:12 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [01:05<00:04,  5.78it/s]16 03:19:12 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [01:06<00:04,  5.81it/s]16 03:19:12 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [01:06<00:04,  5.73it/s]16 03:19:12 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [01:06<00:03,  5.68it/s]16 03:19:12 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [01:06<00:03,  5.68it/s]16 03:19:13 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [01:06<00:03,  5.75it/s]16 03:19:13 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [01:07<00:03,  5.88it/s]16 03:19:13 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [01:07<00:03,  5.83it/s]16 03:19:13 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [01:07<00:02,  5.82it/s]16 03:19:13 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [01:07<00:02,  5.81it/s]16 03:19:13 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [01:07<00:02,  5.80it/s]16 03:19:14 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [01:07<00:02,  5.74it/s]16 03:19:14 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [01:08<00:02,  5.71it/s]16 03:19:14 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [01:08<00:02,  5.73it/s]16 03:19:14 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [01:08<00:01,  5.82it/s]16 03:19:14 Save the image 01366N.png

 97%|██████████████████████████████████████▉ | 383/393 [01:08<00:01,  5.78it/s]16 03:19:15 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [01:08<00:01,  5.76it/s]16 03:19:15 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [01:08<00:01,  5.76it/s]16 03:19:15 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [01:09<00:01,  5.75it/s]16 03:19:15 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [01:09<00:01,  5.72it/s]16 03:19:15 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [01:09<00:00,  5.70it/s]16 03:19:15 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [01:09<00:00,  5.77it/s]16 03:19:16 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [01:09<00:00,  5.80it/s]16 03:19:16 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [01:09<00:00,  5.79it/s]16 03:19:16 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [01:10<00:00,  5.79it/s]16 03:19:16 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [01:10<00:00,  5.59it/s]
1 unlabeled	98.335%
2 car   	89.669%
3 person	75.300%
4 bike  	64.247%
5 curve 	46.909%
6 car_stop	32.645%
7 guardrail	4.883%
8 color_cone	52.549%
9 bump  	58.233%
----------     mean_IoU	58.086%	freq_IoU	96.816%	mean_pixel_acc	66.617%	pixel_acc	98.258%
16 03:19:16 Evaluation Elapsed Time: 70.32s

In [21]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E4")

!python eval.py -e 100 -d 0 --split val -p predictions_E4_val

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 03:19:45 using devices 0
16 03:19:45 Using E4: SegFormer-B2 with reliability-gated rectification
16 03:19:46 Using MLP Decoder
16 03:19:46 Load Model: /home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2_e4/checkpoint/epoch-100.pth
16 03:19:51 Load model, Time usage:
	IO: 4.325042486190796, initialize parameters: 0.044379472732543945
16 03:19:51 GPU 0 handle 392 data.
  0%|                                                  | 0/392 [00:00<?, ?it/s][ WARN:0@8.458] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 03:19:52 Save the image 00498D.png
  0%|                                          | 1/392 [00:01<09:52,  1.52s/it]16 03:19:52 Save the image 00499D.png
  1%|▏                                         | 2/392 [00:01<04:43,  1.38it/s]16 03:19:52 Save the image 00500D.png
  1%|▎                                         | 3/392 [00:01<03:04,  2.10it/s]16 03:19:53 Save the image 00501D.png
  1%|▍                                         | 4/392 [00:02<02:18,  2.80it/s]16 03:19:53 Save the image 00502D.png
  1%|▌                                         | 5/392 [00:02<01:52,  3.44it/s]16 03:19:53 Save the image 00503D.png
  2%|▋                                         | 6/392 [00:02<01:36,  3.98it/s]16 03:19:53 Save the image 00504D.png
  2%|▊                                         | 7/392 [00:02<01:22,  4.66it/s]16 03:19:53 Save the image 00505D.png
  2%|▊                                         | 8/392 [00:02<01:17,  4.94it/s]16 03:19:53 Save the image 00506D.png
  2%|▉                                         | 9/392 [00:02<01:13,  5.18it/s]16 03:19:54 Save the image 00507D.png
  3%|█                                        | 10/392 [00:03<01:11,  5.36it/s]16 03:19:54 Save the image 00508D.png
  3%|█▏                                       | 11/392 [00:03<01:09,  5.45it/s]16 03:19:54 Save the image 00509D.png
  3%|█▎                                       | 12/392 [00:03<01:08,  5.51it/s]16 03:19:54 Save the image 00510D.png
  3%|█▎                                       | 13/392 [00:03<01:07,  5.57it/s]16 03:19:54 Save the image 00511D.png
  4%|█▍                                       | 14/392 [00:03<01:07,  5.62it/s]16 03:19:54 Save the image 00512D.png
  4%|█▌                                       | 15/392 [00:03<01:02,  6.02it/s]16 03:19:55 Save the image 00513D.png
  4%|█▋                                       | 16/392 [00:04<01:03,  5.91it/s]16 03:19:55 Save the image 00514D.png
  4%|█▊                                       | 17/392 [00:04<01:03,  5.88it/s]16 03:19:55 Save the image 00515D.png
  5%|█▉                                       | 18/392 [00:04<01:03,  5.88it/s]16 03:19:55 Save the image 00516D.png
  5%|█▉                                       | 19/392 [00:04<01:04,  5.82it/s]16 03:19:55 Save the image 00517D.png
  5%|██                                       | 20/392 [00:04<01:04,  5.77it/s]16 03:19:55 Save the image 00518D.png
  5%|██▏                                      | 21/392 [00:04<01:04,  5.75it/s]16 03:19:56 Save the image 00519D.png
  6%|██▎                                      | 22/392 [00:05<01:04,  5.70it/s]16 03:19:56 Save the image 00520D.png
  6%|██▍                                      | 23/392 [00:05<01:00,  6.05it/s]16 03:19:56 Save the image 00521D.png
  6%|██▌                                      | 24/392 [00:05<01:02,  5.89it/s]16 03:19:56 Save the image 00522D.png
  6%|██▌                                      | 25/392 [00:05<01:02,  5.86it/s]16 03:19:56 Save the image 00523D.png
  7%|██▋                                      | 26/392 [00:05<01:03,  5.78it/s]16 03:19:57 Save the image 00524D.png
  7%|██▊                                      | 27/392 [00:05<01:03,  5.76it/s]16 03:19:57 Save the image 00525D.png
  7%|██▉                                      | 28/392 [00:06<01:03,  5.75it/s]16 03:19:57 Save the image 00526D.png
  7%|███                                      | 29/392 [00:06<01:03,  5.76it/s]16 03:19:57 Save the image 00527D.png
  8%|███▏                                     | 30/392 [00:06<01:02,  5.80it/s]16 03:19:57 Save the image 00528D.png
  8%|███▏                                     | 31/392 [00:06<01:00,  5.97it/s]16 03:19:57 Save the image 00529D.png
  8%|███▎                                     | 32/392 [00:06<01:01,  5.89it/s]16 03:19:58 Save the image 00530D.png
  8%|███▍                                     | 33/392 [00:06<01:01,  5.87it/s]16 03:19:58 Save the image 00531D.png
  9%|███▌                                     | 34/392 [00:07<01:01,  5.83it/s]16 03:19:58 Save the image 00532D.png
  9%|███▋                                     | 35/392 [00:07<01:01,  5.80it/s]16 03:19:58 Save the image 00533D.png
  9%|███▊                                     | 36/392 [00:07<01:01,  5.79it/s]16 03:19:58 Save the image 00534D.png
  9%|███▊                                     | 37/392 [00:07<01:01,  5.79it/s]16 03:19:58 Save the image 00535D.png
 10%|███▉                                     | 38/392 [00:07<01:00,  5.82it/s]16 03:19:59 Save the image 00536D.png
 10%|████                                     | 39/392 [00:08<00:58,  5.99it/s]16 03:19:59 Save the image 00537D.png
 10%|████▏                                    | 40/392 [00:08<00:59,  5.92it/s]16 03:19:59 Save the image 00538D.png
 10%|████▎                                    | 41/392 [00:08<00:59,  5.89it/s]16 03:19:59 Save the image 00539D.png
 11%|████▍                                    | 42/392 [00:08<00:59,  5.85it/s]16 03:19:59 Save the image 00540D.png
 11%|████▍                                    | 43/392 [00:08<00:59,  5.83it/s]16 03:19:59 Save the image 00541D.png
 11%|████▌                                    | 44/392 [00:08<00:59,  5.81it/s]16 03:20:00 Save the image 00542D.png
 11%|████▋                                    | 45/392 [00:09<00:59,  5.80it/s]16 03:20:00 Save the image 00543D.png
 12%|████▊                                    | 46/392 [00:09<00:59,  5.79it/s]16 03:20:00 Save the image 00544D.png
 12%|████▉                                    | 47/392 [00:09<00:57,  5.96it/s]16 03:20:00 Save the image 00545D.png
 12%|█████                                    | 48/392 [00:09<00:58,  5.86it/s]16 03:20:00 Save the image 00546D.png
 12%|█████▏                                   | 49/392 [00:09<00:59,  5.81it/s]16 03:20:00 Save the image 00547D.png
 13%|█████▏                                   | 50/392 [00:09<00:59,  5.79it/s]16 03:20:01 Save the image 00548D.png
 13%|█████▎                                   | 51/392 [00:10<00:58,  5.78it/s]16 03:20:01 Save the image 00549D.png
 13%|█████▍                                   | 52/392 [00:10<00:58,  5.77it/s]16 03:20:01 Save the image 00550D.png
 14%|█████▌                                   | 53/392 [00:10<00:59,  5.72it/s]16 03:20:01 Save the image 00551D.png
 14%|█████▋                                   | 54/392 [00:10<00:58,  5.75it/s]16 03:20:01 Save the image 00552D.png
 14%|█████▊                                   | 55/392 [00:10<00:57,  5.84it/s]16 03:20:01 Save the image 00553D.png
 14%|█████▊                                   | 56/392 [00:10<00:57,  5.80it/s]16 03:20:02 Save the image 00554D.png
 15%|█████▉                                   | 57/392 [00:11<00:58,  5.75it/s]16 03:20:02 Save the image 00555D.png

 15%|██████                                   | 58/392 [00:11<00:58,  5.73it/s]16 03:20:02 Save the image 00556D.png
 15%|██████▏                                  | 59/392 [00:11<00:58,  5.74it/s]16 03:20:02 Save the image 00557D.png
 15%|██████▎                                  | 60/392 [00:11<00:57,  5.73it/s]16 03:20:02 Save the image 00558D.png
 16%|██████▍                                  | 61/392 [00:11<00:58,  5.70it/s]16 03:20:03 Save the image 00559D.png
 16%|██████▍                                  | 62/392 [00:11<00:57,  5.75it/s]16 03:20:03 Save the image 00560D.png
 16%|██████▌                                  | 63/392 [00:12<00:57,  5.77it/s]16 03:20:03 Save the image 00561D.png
 16%|██████▋                                  | 64/392 [00:12<00:57,  5.72it/s]16 03:20:03 Save the image 00562D.png
 17%|██████▊                                  | 65/392 [00:12<00:57,  5.73it/s]16 03:20:03 Save the image 00563D.png
 17%|██████▉                                  | 66/392 [00:12<00:56,  5.73it/s]16 03:20:03 Save the image 00564D.png
 17%|███████                                  | 67/392 [00:12<00:56,  5.73it/s]16 03:20:04 Save the image 00565D.png
 17%|███████                                  | 68/392 [00:13<00:56,  5.74it/s]16 03:20:04 Save the image 00566D.png
 18%|███████▏                                 | 69/392 [00:13<00:56,  5.69it/s]16 03:20:04 Save the image 00567D.png
 18%|███████▎                                 | 70/392 [00:13<00:56,  5.74it/s]16 03:20:04 Save the image 00568D.png
 18%|███████▍                                 | 71/392 [00:13<00:55,  5.77it/s]16 03:20:04 Save the image 00569D.png
 18%|███████▌                                 | 72/392 [00:13<00:55,  5.78it/s]16 03:20:04 Save the image 00570D.png
 19%|███████▋                                 | 73/392 [00:13<00:55,  5.77it/s]16 03:20:05 Save the image 00571D.png
 19%|███████▋                                 | 74/392 [00:14<00:55,  5.78it/s]16 03:20:05 Save the image 00572D.png
 19%|███████▊                                 | 75/392 [00:14<00:55,  5.69it/s]16 03:20:05 Save the image 00573D.png
 19%|███████▉                                 | 76/392 [00:14<00:55,  5.70it/s]16 03:20:05 Save the image 00574D.png
 20%|████████                                 | 77/392 [00:14<00:55,  5.71it/s]16 03:20:05 Save the image 00575D.png
 20%|████████▏                                | 78/392 [00:14<00:55,  5.71it/s]16 03:20:05 Save the image 00576D.png
 20%|████████▎                                | 79/392 [00:14<00:51,  6.07it/s]16 03:20:06 Save the image 00577D.png
 20%|████████▎                                | 80/392 [00:15<00:52,  5.98it/s]16 03:20:06 Save the image 00578D.png
 21%|████████▍                                | 81/392 [00:15<00:52,  5.93it/s]16 03:20:06 Save the image 00579D.png
 21%|████████▌                                | 82/392 [00:15<00:52,  5.93it/s]16 03:20:06 Save the image 00580D.png
 21%|████████▋                                | 83/392 [00:15<00:52,  5.86it/s]16 03:20:06 Save the image 00581D.png
 21%|████████▊                                | 84/392 [00:15<00:52,  5.83it/s]16 03:20:07 Save the image 00582D.png
 22%|████████▉                                | 85/392 [00:15<00:52,  5.81it/s]16 03:20:07 Save the image 00583D.png
 22%|████████▉                                | 86/392 [00:16<00:52,  5.85it/s]16 03:20:07 Save the image 00584D.png
 22%|█████████                                | 87/392 [00:16<00:50,  6.02it/s]16 03:20:07 Save the image 00585D.png
 22%|█████████▏                               | 88/392 [00:16<00:51,  5.93it/s]16 03:20:07 Save the image 00586D.png
 23%|█████████▎                               | 89/392 [00:16<00:51,  5.91it/s]16 03:20:07 Save the image 00587D.png
 23%|█████████▍                               | 90/392 [00:16<00:51,  5.87it/s]16 03:20:08 Save the image 00588D.png
 23%|█████████▌                               | 91/392 [00:16<00:51,  5.84it/s]16 03:20:08 Save the image 00589D.png
 23%|█████████▌                               | 92/392 [00:17<00:51,  5.83it/s]16 03:20:08 Save the image 00590D.png
 24%|█████████▋                               | 93/392 [00:17<00:51,  5.81it/s]16 03:20:08 Save the image 00591D.png
 24%|█████████▊                               | 94/392 [00:17<00:51,  5.83it/s]16 03:20:08 Save the image 00592D.png
 24%|█████████▉                               | 95/392 [00:17<00:49,  5.99it/s]16 03:20:08 Save the image 00593D.png
 24%|██████████                               | 96/392 [00:17<00:50,  5.88it/s]16 03:20:09 Save the image 00594D.png
 25%|██████████▏                              | 97/392 [00:17<00:50,  5.87it/s]16 03:20:09 Save the image 00595D.png
 25%|██████████▎                              | 98/392 [00:18<00:50,  5.82it/s]16 03:20:09 Save the image 00596D.png
 25%|██████████▎                              | 99/392 [00:18<00:50,  5.78it/s]16 03:20:09 Save the image 00597D.png
 26%|██████████▏                             | 100/392 [00:18<00:50,  5.76it/s]16 03:20:09 Save the image 00598D.png
 26%|██████████▎                             | 101/392 [00:18<00:50,  5.76it/s]16 03:20:09 Save the image 00599D.png
 26%|██████████▍                             | 102/392 [00:18<00:49,  5.81it/s]16 03:20:10 Save the image 00600D.png
 26%|██████████▌                             | 103/392 [00:19<00:48,  5.99it/s]16 03:20:10 Save the image 00601D.png
 27%|██████████▌                             | 104/392 [00:19<00:49,  5.87it/s]16 03:20:10 Save the image 00602D.png
 27%|██████████▋                             | 105/392 [00:19<00:49,  5.83it/s]16 03:20:10 Save the image 00603D.png
 27%|██████████▊                             | 106/392 [00:19<00:49,  5.82it/s]16 03:20:10 Save the image 00604D.png
 27%|██████████▉                             | 107/392 [00:19<00:49,  5.80it/s]16 03:20:10 Save the image 00605D.png
 28%|███████████                             | 108/392 [00:19<00:49,  5.77it/s]16 03:20:11 Save the image 00606D.png
 28%|███████████                             | 109/392 [00:20<00:49,  5.75it/s]16 03:20:11 Save the image 00607D.png
 28%|███████████▏                            | 110/392 [00:20<00:48,  5.78it/s]16 03:20:11 Save the image 00608D.png
 28%|███████████▎                            | 111/392 [00:20<00:46,  6.00it/s]16 03:20:11 Save the image 00609D.png
 29%|███████████▍                            | 112/392 [00:20<00:47,  5.92it/s]16 03:20:11 Save the image 00610D.png
 29%|███████████▌                            | 113/392 [00:20<00:47,  5.86it/s]16 03:20:11 Save the image 00611D.png
 29%|███████████▋                            | 114/392 [00:20<00:47,  5.85it/s]16 03:20:12 Save the image 00612D.png
 29%|███████████▋                            | 115/392 [00:21<00:48,  5.73it/s]16 03:20:12 Save the image 00613D.png
 30%|███████████▊                            | 116/392 [00:21<00:48,  5.69it/s]16 03:20:12 Save the image 00614D.png
 30%|███████████▉                            | 117/392 [00:21<00:48,  5.70it/s]16 03:20:12 Save the image 00615D.png
 30%|████████████                            | 118/392 [00:21<00:48,  5.70it/s]16 03:20:12 Save the image 00616D.png
 30%|████████████▏                           | 119/392 [00:21<00:45,  6.04it/s]16 03:20:12 Save the image 00617D.png
 31%|████████████▏                           | 120/392 [00:21<00:45,  5.92it/s]16 03:20:13 Save the image 00618D.png
 31%|████████████▎                           | 121/392 [00:22<00:46,  5.87it/s]16 03:20:13 Save the image 00619D.png
 31%|████████████▍                           | 122/392 [00:22<00:46,  5.84it/s]16 03:20:13 Save the image 00620D.png

 31%|████████████▌                           | 123/392 [00:22<00:46,  5.77it/s]16 03:20:13 Save the image 00621D.png
 32%|████████████▋                           | 124/392 [00:22<00:46,  5.76it/s]16 03:20:13 Save the image 00622D.png
 32%|████████████▊                           | 125/392 [00:22<00:46,  5.76it/s]16 03:20:14 Save the image 00623D.png
 32%|████████████▊                           | 126/392 [00:22<00:46,  5.76it/s]16 03:20:14 Save the image 00624D.png
 32%|████████████▉                           | 127/392 [00:23<00:43,  6.13it/s]16 03:20:14 Save the image 00625D.png
 33%|█████████████                           | 128/392 [00:23<00:44,  5.98it/s]16 03:20:14 Save the image 00626D.png
 33%|█████████████▏                          | 129/392 [00:23<00:44,  5.91it/s]16 03:20:14 Save the image 00627D.png
 33%|█████████████▎                          | 130/392 [00:23<00:44,  5.90it/s]16 03:20:14 Save the image 00628D.png
 33%|█████████████▎                          | 131/392 [00:23<00:44,  5.83it/s]16 03:20:15 Save the image 00629D.png
 34%|█████████████▍                          | 132/392 [00:23<00:44,  5.80it/s]16 03:20:15 Save the image 00630D.png
 34%|█████████████▌                          | 133/392 [00:24<00:44,  5.79it/s]16 03:20:15 Save the image 00631D.png
 34%|█████████████▋                          | 134/392 [00:24<00:44,  5.78it/s]16 03:20:15 Save the image 00632D.png
 34%|█████████████▊                          | 135/392 [00:24<00:42,  6.10it/s]16 03:20:15 Save the image 00633D.png
 35%|█████████████▉                          | 136/392 [00:24<00:42,  5.97it/s]16 03:20:15 Save the image 00634D.png
 35%|█████████████▉                          | 137/392 [00:24<00:43,  5.92it/s]16 03:20:16 Save the image 00635D.png
 35%|██████████████                          | 138/392 [00:25<00:43,  5.88it/s]16 03:20:16 Save the image 00636D.png
 35%|██████████████▏                         | 139/392 [00:25<00:43,  5.78it/s]16 03:20:16 Save the image 00637D.png
 36%|██████████████▎                         | 140/392 [00:25<00:43,  5.76it/s]16 03:20:16 Save the image 00638D.png
 36%|██████████████▍                         | 141/392 [00:25<00:43,  5.76it/s]16 03:20:16 Save the image 00639D.png
 36%|██████████████▍                         | 142/392 [00:25<00:43,  5.78it/s]16 03:20:16 Save the image 00640D.png
 36%|██████████████▌                         | 143/392 [00:25<00:42,  5.87it/s]16 03:20:17 Save the image 00641D.png
 37%|██████████████▋                         | 144/392 [00:26<00:42,  5.82it/s]16 03:20:17 Save the image 00642D.png
 37%|██████████████▊                         | 145/392 [00:26<00:42,  5.81it/s]16 03:20:17 Save the image 00643D.png
 37%|██████████████▉                         | 146/392 [00:26<00:42,  5.80it/s]16 03:20:17 Save the image 00644D.png
 38%|███████████████                         | 147/392 [00:26<00:42,  5.77it/s]16 03:20:17 Save the image 00645D.png
 38%|███████████████                         | 148/392 [00:26<00:42,  5.77it/s]16 03:20:17 Save the image 00646D.png
 38%|███████████████▏                        | 149/392 [00:26<00:42,  5.76it/s]16 03:20:18 Save the image 00647D.png
 38%|███████████████▎                        | 150/392 [00:27<00:41,  5.79it/s]16 03:20:18 Save the image 00648D.png
 39%|███████████████▍                        | 151/392 [00:27<00:40,  6.00it/s]16 03:20:18 Save the image 00649D.png
 39%|███████████████▌                        | 152/392 [00:27<00:40,  5.88it/s]16 03:20:18 Save the image 00650D.png
 39%|███████████████▌                        | 153/392 [00:27<00:41,  5.78it/s]16 03:20:18 Save the image 00651D.png
 39%|███████████████▋                        | 154/392 [00:27<00:41,  5.78it/s]16 03:20:18 Save the image 00652D.png
 40%|███████████████▊                        | 155/392 [00:27<00:41,  5.76it/s]16 03:20:19 Save the image 00653D.png
 40%|███████████████▉                        | 156/392 [00:28<00:40,  5.76it/s]16 03:20:19 Save the image 00654D.png
 40%|████████████████                        | 157/392 [00:28<00:40,  5.76it/s]16 03:20:19 Save the image 00655D.png
 40%|████████████████                        | 158/392 [00:28<00:40,  5.79it/s]16 03:20:19 Save the image 00656D.png
 41%|████████████████▏                       | 159/392 [00:28<00:39,  5.90it/s]16 03:20:19 Save the image 00657D.png
 41%|████████████████▎                       | 160/392 [00:28<00:39,  5.85it/s]16 03:20:20 Save the image 00658D.png
 41%|████████████████▍                       | 161/392 [00:28<00:39,  5.84it/s]16 03:20:20 Save the image 00659D.png
 41%|████████████████▌                       | 162/392 [00:29<00:39,  5.85it/s]16 03:20:20 Save the image 00660D.png
 42%|████████████████▋                       | 163/392 [00:29<00:39,  5.74it/s]16 03:20:20 Save the image 00661D.png
 42%|████████████████▋                       | 164/392 [00:29<00:40,  5.69it/s]16 03:20:20 Save the image 00662D.png
 42%|████████████████▊                       | 165/392 [00:29<00:40,  5.66it/s]16 03:20:20 Save the image 00663D.png
 42%|████████████████▉                       | 166/392 [00:29<00:40,  5.63it/s]16 03:20:21 Save the image 00664D.png
 43%|█████████████████                       | 167/392 [00:30<00:38,  5.88it/s]16 03:20:21 Save the image 00665D.png
 43%|█████████████████▏                      | 168/392 [00:30<00:38,  5.84it/s]16 03:20:21 Save the image 00666D.png
 43%|█████████████████▏                      | 169/392 [00:30<00:38,  5.81it/s]16 03:20:21 Save the image 00667D.png
 43%|█████████████████▎                      | 170/392 [00:30<00:38,  5.74it/s]16 03:20:21 Save the image 00668D.png
 44%|█████████████████▍                      | 171/392 [00:30<00:38,  5.69it/s]16 03:20:21 Save the image 00669D.png
 44%|█████████████████▌                      | 172/392 [00:30<00:38,  5.67it/s]16 03:20:22 Save the image 00670D.png
 44%|█████████████████▋                      | 173/392 [00:31<00:38,  5.63it/s]16 03:20:22 Save the image 00671D.png
 44%|█████████████████▊                      | 174/392 [00:31<00:38,  5.64it/s]16 03:20:22 Save the image 00672D.png
 45%|█████████████████▊                      | 175/392 [00:31<00:37,  5.86it/s]16 03:20:22 Save the image 00673D.png
 45%|█████████████████▉                      | 176/392 [00:31<00:37,  5.79it/s]16 03:20:22 Save the image 00674D.png
 45%|██████████████████                      | 177/392 [00:31<00:37,  5.73it/s]16 03:20:22 Save the image 00675D.png
 45%|██████████████████▏                     | 178/392 [00:31<00:37,  5.69it/s]16 03:20:23 Save the image 00676D.png
 46%|██████████████████▎                     | 179/392 [00:32<00:37,  5.69it/s]16 03:20:23 Save the image 00677D.png
 46%|██████████████████▎                     | 180/392 [00:32<00:37,  5.64it/s]16 03:20:23 Save the image 01377D.png
 46%|██████████████████▍                     | 181/392 [00:32<00:37,  5.63it/s]16 03:20:23 Save the image 01378D.png
 46%|██████████████████▌                     | 182/392 [00:32<00:36,  5.70it/s]16 03:20:23 Save the image 01379D.png
 47%|██████████████████▋                     | 183/392 [00:32<00:36,  5.80it/s]16 03:20:24 Save the image 01380D.png
 47%|██████████████████▊                     | 184/392 [00:32<00:36,  5.77it/s]16 03:20:24 Save the image 01381D.png
 47%|██████████████████▉                     | 185/392 [00:33<00:36,  5.72it/s]16 03:20:24 Save the image 01382D.png
 47%|██████████████████▉                     | 186/392 [00:33<00:36,  5.69it/s]16 03:20:24 Save the image 01383D.png
 48%|███████████████████                     | 187/392 [00:33<00:36,  5.64it/s]16 03:20:24 Save the image 01384D.png

 48%|███████████████████▏                    | 188/392 [00:33<00:36,  5.64it/s]16 03:20:24 Save the image 01385D.png
 48%|███████████████████▎                    | 189/392 [00:33<00:36,  5.63it/s]16 03:20:25 Save the image 01386D.png
 48%|███████████████████▍                    | 190/392 [00:34<00:35,  5.70it/s]16 03:20:25 Save the image 01387D.png
 49%|███████████████████▍                    | 191/392 [00:34<00:34,  5.81it/s]16 03:20:25 Save the image 01388D.png
 49%|███████████████████▌                    | 192/392 [00:34<00:35,  5.71it/s]16 03:20:25 Save the image 01389D.png
 49%|███████████████████▋                    | 193/392 [00:34<00:34,  5.70it/s]16 03:20:25 Save the image 01390D.png
 49%|███████████████████▊                    | 194/392 [00:34<00:34,  5.67it/s]16 03:20:25 Save the image 01391D.png
 50%|███████████████████▉                    | 195/392 [00:34<00:34,  5.65it/s]16 03:20:26 Save the image 01392D.png
 50%|████████████████████                    | 196/392 [00:35<00:34,  5.64it/s]16 03:20:26 Save the image 01393D.png
 50%|████████████████████                    | 197/392 [00:35<00:34,  5.63it/s]16 03:20:26 Save the image 01394D.png
 51%|████████████████████▏                   | 198/392 [00:35<00:34,  5.69it/s]16 03:20:26 Save the image 01395D.png
 51%|████████████████████▎                   | 199/392 [00:35<00:33,  5.81it/s]16 03:20:26 Save the image 01396D.png
 51%|████████████████████▍                   | 200/392 [00:35<00:33,  5.78it/s]16 03:20:27 Save the image 01397D.png
 51%|████████████████████▌                   | 201/392 [00:35<00:33,  5.77it/s]16 03:20:27 Save the image 01398D.png
 52%|████████████████████▌                   | 202/392 [00:36<00:32,  5.80it/s]16 03:20:27 Save the image 01399D.png
 52%|████████████████████▋                   | 203/392 [00:36<00:32,  5.77it/s]16 03:20:27 Save the image 01400D.png
 52%|████████████████████▊                   | 204/392 [00:36<00:32,  5.71it/s]16 03:20:27 Save the image 01401D.png
 52%|████████████████████▉                   | 205/392 [00:36<00:32,  5.69it/s]16 03:20:27 Save the image 01002N.png
 53%|█████████████████████                   | 206/392 [00:36<00:32,  5.73it/s]16 03:20:28 Save the image 01003N.png
 53%|█████████████████████                   | 207/392 [00:37<00:31,  5.79it/s]16 03:20:28 Save the image 01004N.png
 53%|█████████████████████▏                  | 208/392 [00:37<00:31,  5.75it/s]16 03:20:28 Save the image 01005N.png
 53%|█████████████████████▎                  | 209/392 [00:37<00:31,  5.72it/s]16 03:20:28 Save the image 01006N.png
 54%|█████████████████████▍                  | 210/392 [00:37<00:31,  5.74it/s]16 03:20:28 Save the image 01007N.png
 54%|█████████████████████▌                  | 211/392 [00:37<00:31,  5.71it/s]16 03:20:28 Save the image 01008N.png
 54%|█████████████████████▋                  | 212/392 [00:37<00:31,  5.69it/s]16 03:20:29 Save the image 01009N.png
 54%|█████████████████████▋                  | 213/392 [00:38<00:31,  5.63it/s]16 03:20:29 Save the image 01010N.png
 55%|█████████████████████▊                  | 214/392 [00:38<00:31,  5.69it/s]16 03:20:29 Save the image 01011N.png
 55%|█████████████████████▉                  | 215/392 [00:38<00:30,  5.76it/s]16 03:20:29 Save the image 01012N.png
 55%|██████████████████████                  | 216/392 [00:38<00:30,  5.73it/s]16 03:20:29 Save the image 01013N.png
 55%|██████████████████████▏                 | 217/392 [00:38<00:30,  5.72it/s]16 03:20:30 Save the image 01014N.png
 56%|██████████████████████▏                 | 218/392 [00:38<00:30,  5.71it/s]16 03:20:30 Save the image 01015N.png
 56%|██████████████████████▎                 | 219/392 [00:39<00:30,  5.70it/s]16 03:20:30 Save the image 01016N.png
 56%|██████████████████████▍                 | 220/392 [00:39<00:30,  5.72it/s]16 03:20:30 Save the image 01017N.png
 56%|██████████████████████▌                 | 221/392 [00:39<00:29,  5.71it/s]16 03:20:30 Save the image 01018N.png
 57%|██████████████████████▋                 | 222/392 [00:39<00:29,  5.75it/s]16 03:20:30 Save the image 01019N.png
 57%|██████████████████████▊                 | 223/392 [00:39<00:29,  5.80it/s]16 03:20:31 Save the image 01020N.png
 57%|██████████████████████▊                 | 224/392 [00:39<00:29,  5.75it/s]16 03:20:31 Save the image 01021N.png
 57%|██████████████████████▉                 | 225/392 [00:40<00:29,  5.74it/s]16 03:20:31 Save the image 01022N.png
 58%|███████████████████████                 | 226/392 [00:40<00:29,  5.70it/s]16 03:20:31 Save the image 01023N.png
 58%|███████████████████████▏                | 227/392 [00:40<00:29,  5.65it/s]16 03:20:31 Save the image 01024N.png
 58%|███████████████████████▎                | 228/392 [00:40<00:28,  5.69it/s]16 03:20:31 Save the image 01025N.png
 58%|███████████████████████▎                | 229/392 [00:40<00:28,  5.71it/s]16 03:20:32 Save the image 01026N.png
 59%|███████████████████████▍                | 230/392 [00:41<00:27,  5.79it/s]16 03:20:32 Save the image 01027N.png
 59%|███████████████████████▌                | 231/392 [00:41<00:26,  5.98it/s]16 03:20:32 Save the image 01028N.png
 59%|███████████████████████▋                | 232/392 [00:41<00:27,  5.91it/s]16 03:20:32 Save the image 01029N.png
 59%|███████████████████████▊                | 233/392 [00:41<00:27,  5.88it/s]16 03:20:32 Save the image 01030N.png
 60%|███████████████████████▉                | 234/392 [00:41<00:26,  5.88it/s]16 03:20:32 Save the image 01031N.png
 60%|███████████████████████▉                | 235/392 [00:41<00:27,  5.80it/s]16 03:20:33 Save the image 01032N.png
 60%|████████████████████████                | 236/392 [00:42<00:27,  5.74it/s]16 03:20:33 Save the image 01033N.png
 60%|████████████████████████▏               | 237/392 [00:42<00:27,  5.71it/s]16 03:20:33 Save the image 01034N.png
 61%|████████████████████████▎               | 238/392 [00:42<00:26,  5.81it/s]16 03:20:33 Save the image 01035N.png
 61%|████████████████████████▍               | 239/392 [00:42<00:26,  5.85it/s]16 03:20:33 Save the image 01036N.png
 61%|████████████████████████▍               | 240/392 [00:42<00:26,  5.79it/s]16 03:20:33 Save the image 01037N.png
 61%|████████████████████████▌               | 241/392 [00:42<00:26,  5.74it/s]16 03:20:34 Save the image 01038N.png
 62%|████████████████████████▋               | 242/392 [00:43<00:26,  5.72it/s]16 03:20:34 Save the image 01039N.png
 62%|████████████████████████▊               | 243/392 [00:43<00:26,  5.66it/s]16 03:20:34 Save the image 01040N.png
 62%|████████████████████████▉               | 244/392 [00:43<00:26,  5.66it/s]16 03:20:34 Save the image 01041N.png
 62%|█████████████████████████               | 245/392 [00:43<00:26,  5.65it/s]16 03:20:34 Save the image 01042N.png
 63%|█████████████████████████               | 246/392 [00:43<00:25,  5.70it/s]16 03:20:35 Save the image 01043N.png
 63%|█████████████████████████▏              | 247/392 [00:43<00:24,  5.86it/s]16 03:20:35 Save the image 01044N.png
 63%|█████████████████████████▎              | 248/392 [00:44<00:24,  5.80it/s]16 03:20:35 Save the image 01045N.png
 64%|█████████████████████████▍              | 249/392 [00:44<00:24,  5.79it/s]16 03:20:35 Save the image 01046N.png
 64%|█████████████████████████▌              | 250/392 [00:44<00:24,  5.77it/s]16 03:20:35 Save the image 01047N.png
 64%|█████████████████████████▌              | 251/392 [00:44<00:24,  5.72it/s]16 03:20:35 Save the image 01048N.png
 64%|█████████████████████████▋              | 252/392 [00:44<00:24,  5.72it/s]16 03:20:36 Save the image 01049N.png

 65%|█████████████████████████▊              | 253/392 [00:45<00:24,  5.73it/s]16 03:20:36 Save the image 01050N.png
 65%|█████████████████████████▉              | 254/392 [00:45<00:23,  5.81it/s]16 03:20:36 Save the image 01051N.png
 65%|██████████████████████████              | 255/392 [00:45<00:23,  5.95it/s]16 03:20:36 Save the image 01052N.png
 65%|██████████████████████████              | 256/392 [00:45<00:23,  5.86it/s]16 03:20:36 Save the image 01053N.png
 66%|██████████████████████████▏             | 257/392 [00:45<00:23,  5.83it/s]16 03:20:36 Save the image 01054N.png
 66%|██████████████████████████▎             | 258/392 [00:45<00:22,  5.83it/s]16 03:20:37 Save the image 01055N.png
 66%|██████████████████████████▍             | 259/392 [00:46<00:23,  5.76it/s]16 03:20:37 Save the image 01056N.png
 66%|██████████████████████████▌             | 260/392 [00:46<00:22,  5.75it/s]16 03:20:37 Save the image 01057N.png
 67%|██████████████████████████▋             | 261/392 [00:46<00:22,  5.75it/s]16 03:20:37 Save the image 01058N.png
 67%|██████████████████████████▋             | 262/392 [00:46<00:22,  5.79it/s]16 03:20:37 Save the image 01059N.png
 67%|██████████████████████████▊             | 263/392 [00:46<00:21,  6.05it/s]16 03:20:37 Save the image 01060N.png
 67%|██████████████████████████▉             | 264/392 [00:46<00:21,  5.92it/s]16 03:20:38 Save the image 01061N.png
 68%|███████████████████████████             | 265/392 [00:47<00:21,  5.89it/s]16 03:20:38 Save the image 01062N.png
 68%|███████████████████████████▏            | 266/392 [00:47<00:21,  5.86it/s]16 03:20:38 Save the image 01063N.png
 68%|███████████████████████████▏            | 267/392 [00:47<00:21,  5.82it/s]16 03:20:38 Save the image 01064N.png
 68%|███████████████████████████▎            | 268/392 [00:47<00:21,  5.74it/s]16 03:20:38 Save the image 01065N.png
 69%|███████████████████████████▍            | 269/392 [00:47<00:21,  5.74it/s]16 03:20:38 Save the image 01066N.png
 69%|███████████████████████████▌            | 270/392 [00:47<00:21,  5.81it/s]16 03:20:39 Save the image 01067N.png
 69%|███████████████████████████▋            | 271/392 [00:48<00:20,  5.96it/s]16 03:20:39 Save the image 01068N.png
 69%|███████████████████████████▊            | 272/392 [00:48<00:20,  5.86it/s]16 03:20:39 Save the image 01069N.png
 70%|███████████████████████████▊            | 273/392 [00:48<00:20,  5.85it/s]16 03:20:39 Save the image 01070N.png
 70%|███████████████████████████▉            | 274/392 [00:48<00:20,  5.88it/s]16 03:20:39 Save the image 01071N.png
 70%|████████████████████████████            | 275/392 [00:48<00:20,  5.84it/s]16 03:20:40 Save the image 01072N.png
 70%|████████████████████████████▏           | 276/392 [00:48<00:19,  5.82it/s]16 03:20:40 Save the image 01073N.png
 71%|████████████████████████████▎           | 277/392 [00:49<00:19,  5.80it/s]16 03:20:40 Save the image 01074N.png
 71%|████████████████████████████▎           | 278/392 [00:49<00:19,  5.83it/s]16 03:20:40 Save the image 01075N.png
 71%|████████████████████████████▍           | 279/392 [00:49<00:19,  5.89it/s]16 03:20:40 Save the image 01076N.png
 71%|████████████████████████████▌           | 280/392 [00:49<00:19,  5.82it/s]16 03:20:40 Save the image 01077N.png
 72%|████████████████████████████▋           | 281/392 [00:49<00:19,  5.82it/s]16 03:20:41 Save the image 01078N.png
 72%|████████████████████████████▊           | 282/392 [00:49<00:18,  5.84it/s]16 03:20:41 Save the image 01079N.png
 72%|████████████████████████████▉           | 283/392 [00:50<00:18,  5.82it/s]16 03:20:41 Save the image 01080N.png
 72%|████████████████████████████▉           | 284/392 [00:50<00:18,  5.81it/s]16 03:20:41 Save the image 01081N.png
 73%|█████████████████████████████           | 285/392 [00:50<00:18,  5.77it/s]16 03:20:41 Save the image 01082N.png
 73%|█████████████████████████████▏          | 286/392 [00:50<00:18,  5.81it/s]16 03:20:41 Save the image 01083N.png
 73%|█████████████████████████████▎          | 287/392 [00:50<00:17,  5.86it/s]16 03:20:42 Save the image 01084N.png
 73%|█████████████████████████████▍          | 288/392 [00:51<00:17,  5.78it/s]16 03:20:42 Save the image 01085N.png
 74%|█████████████████████████████▍          | 289/392 [00:51<00:17,  5.79it/s]16 03:20:42 Save the image 01086N.png
 74%|█████████████████████████████▌          | 290/392 [00:51<00:17,  5.80it/s]16 03:20:42 Save the image 01087N.png
 74%|█████████████████████████████▋          | 291/392 [00:51<00:17,  5.74it/s]16 03:20:42 Save the image 01088N.png
 74%|█████████████████████████████▊          | 292/392 [00:51<00:17,  5.74it/s]16 03:20:42 Save the image 01089N.png
 75%|█████████████████████████████▉          | 293/392 [00:51<00:17,  5.75it/s]16 03:20:43 Save the image 01090N.png
 75%|██████████████████████████████          | 294/392 [00:52<00:16,  5.81it/s]16 03:20:43 Save the image 01091N.png
 75%|██████████████████████████████          | 295/392 [00:52<00:16,  5.89it/s]16 03:20:43 Save the image 01092N.png
 76%|██████████████████████████████▏         | 296/392 [00:52<00:16,  5.80it/s]16 03:20:43 Save the image 01093N.png
 76%|██████████████████████████████▎         | 297/392 [00:52<00:16,  5.77it/s]16 03:20:43 Save the image 01094N.png
 76%|██████████████████████████████▍         | 298/392 [00:52<00:16,  5.77it/s]16 03:20:43 Save the image 01095N.png
 76%|██████████████████████████████▌         | 299/392 [00:52<00:16,  5.74it/s]16 03:20:44 Save the image 01096N.png
 77%|██████████████████████████████▌         | 300/392 [00:53<00:16,  5.71it/s]16 03:20:44 Save the image 01097N.png
 77%|██████████████████████████████▋         | 301/392 [00:53<00:15,  5.71it/s]16 03:20:44 Save the image 01098N.png
 77%|██████████████████████████████▊         | 302/392 [00:53<00:15,  5.77it/s]16 03:20:44 Save the image 01099N.png
 77%|██████████████████████████████▉         | 303/392 [00:53<00:15,  5.88it/s]16 03:20:44 Save the image 01100N.png
 78%|███████████████████████████████         | 304/392 [00:53<00:15,  5.79it/s]16 03:20:45 Save the image 01101N.png
 78%|███████████████████████████████         | 305/392 [00:53<00:14,  5.80it/s]16 03:20:45 Save the image 01102N.png
 78%|███████████████████████████████▏        | 306/392 [00:54<00:14,  5.81it/s]16 03:20:45 Save the image 01103N.png
 78%|███████████████████████████████▎        | 307/392 [00:54<00:14,  5.78it/s]16 03:20:45 Save the image 01104N.png
 79%|███████████████████████████████▍        | 308/392 [00:54<00:14,  5.73it/s]16 03:20:45 Save the image 01105N.png
 79%|███████████████████████████████▌        | 309/392 [00:54<00:14,  5.72it/s]16 03:20:45 Save the image 01106N.png
 79%|███████████████████████████████▋        | 310/392 [00:54<00:14,  5.78it/s]16 03:20:46 Save the image 01107N.png
 79%|███████████████████████████████▋        | 311/392 [00:55<00:14,  5.78it/s]16 03:20:46 Save the image 01108N.png
 80%|███████████████████████████████▊        | 312/392 [00:55<00:13,  5.76it/s]16 03:20:46 Save the image 01109N.png
 80%|███████████████████████████████▉        | 313/392 [00:55<00:13,  5.77it/s]16 03:20:46 Save the image 01110N.png
 80%|████████████████████████████████        | 314/392 [00:55<00:13,  5.77it/s]16 03:20:46 Save the image 01111N.png
 80%|████████████████████████████████▏       | 315/392 [00:55<00:13,  5.78it/s]16 03:20:46 Save the image 01112N.png
 81%|████████████████████████████████▏       | 316/392 [00:55<00:13,  5.77it/s]16 03:20:47 Save the image 01113N.png
 81%|████████████████████████████████▎       | 317/392 [00:56<00:12,  5.77it/s]16 03:20:47 Save the image 01114N.png

 81%|████████████████████████████████▍       | 318/392 [00:56<00:12,  5.75it/s]16 03:20:47 Save the image 01115N.png
 81%|████████████████████████████████▌       | 319/392 [00:56<00:12,  5.80it/s]16 03:20:47 Save the image 01116N.png
 82%|████████████████████████████████▋       | 320/392 [00:56<00:12,  5.75it/s]16 03:20:47 Save the image 01117N.png
 82%|████████████████████████████████▊       | 321/392 [00:56<00:12,  5.71it/s]16 03:20:47 Save the image 01118N.png
 82%|████████████████████████████████▊       | 322/392 [00:56<00:12,  5.71it/s]16 03:20:48 Save the image 01119N.png
 82%|████████████████████████████████▉       | 323/392 [00:57<00:12,  5.71it/s]16 03:20:48 Save the image 01120N.png
 83%|█████████████████████████████████       | 324/392 [00:57<00:12,  5.61it/s]16 03:20:48 Save the image 01121N.png
 83%|█████████████████████████████████▏      | 325/392 [00:57<00:11,  5.62it/s]16 03:20:48 Save the image 01122N.png
 83%|█████████████████████████████████▎      | 326/392 [00:57<00:11,  5.70it/s]16 03:20:48 Save the image 01123N.png
 83%|█████████████████████████████████▎      | 327/392 [00:57<00:11,  5.87it/s]16 03:20:49 Save the image 01124N.png
 84%|█████████████████████████████████▍      | 328/392 [00:57<00:11,  5.81it/s]16 03:20:49 Save the image 01125N.png
 84%|█████████████████████████████████▌      | 329/392 [00:58<00:10,  5.78it/s]16 03:20:49 Save the image 01126N.png
 84%|█████████████████████████████████▋      | 330/392 [00:58<00:10,  5.77it/s]16 03:20:49 Save the image 01127N.png
 84%|█████████████████████████████████▊      | 331/392 [00:58<00:10,  5.71it/s]16 03:20:49 Save the image 01128N.png
 85%|█████████████████████████████████▉      | 332/392 [00:58<00:10,  5.71it/s]16 03:20:49 Save the image 01129N.png
 85%|█████████████████████████████████▉      | 333/392 [00:58<00:10,  5.68it/s]16 03:20:50 Save the image 01130N.png
 85%|██████████████████████████████████      | 334/392 [00:59<00:10,  5.71it/s]16 03:20:50 Save the image 01131N.png
 85%|██████████████████████████████████▏     | 335/392 [00:59<00:09,  5.75it/s]16 03:20:50 Save the image 01132N.png
 86%|██████████████████████████████████▎     | 336/392 [00:59<00:09,  5.71it/s]16 03:20:50 Save the image 01133N.png
 86%|██████████████████████████████████▍     | 337/392 [00:59<00:09,  5.72it/s]16 03:20:50 Save the image 01134N.png
 86%|██████████████████████████████████▍     | 338/392 [00:59<00:09,  5.70it/s]16 03:20:50 Save the image 01135N.png
 86%|██████████████████████████████████▌     | 339/392 [00:59<00:09,  5.71it/s]16 03:20:51 Save the image 01136N.png
 87%|██████████████████████████████████▋     | 340/392 [01:00<00:09,  5.68it/s]16 03:20:51 Save the image 01137N.png
 87%|██████████████████████████████████▊     | 341/392 [01:00<00:08,  5.69it/s]16 03:20:51 Save the image 01138N.png
 87%|██████████████████████████████████▉     | 342/392 [01:00<00:08,  5.72it/s]16 03:20:51 Save the image 01139N.png
 88%|███████████████████████████████████     | 343/392 [01:00<00:08,  5.70it/s]16 03:20:51 Save the image 01140N.png
 88%|███████████████████████████████████     | 344/392 [01:00<00:08,  5.69it/s]16 03:20:51 Save the image 01141N.png
 88%|███████████████████████████████████▏    | 345/392 [01:00<00:08,  5.70it/s]16 03:20:52 Save the image 01142N.png
 88%|███████████████████████████████████▎    | 346/392 [01:01<00:08,  5.72it/s]16 03:20:52 Save the image 01143N.png
 89%|███████████████████████████████████▍    | 347/392 [01:01<00:07,  5.68it/s]16 03:20:52 Save the image 01144N.png
 89%|███████████████████████████████████▌    | 348/392 [01:01<00:07,  5.67it/s]16 03:20:52 Save the image 01145N.png
 89%|███████████████████████████████████▌    | 349/392 [01:01<00:07,  5.65it/s]16 03:20:52 Save the image 01146N.png
 89%|███████████████████████████████████▋    | 350/392 [01:01<00:07,  5.70it/s]16 03:20:53 Save the image 01147N.png
 90%|███████████████████████████████████▊    | 351/392 [01:01<00:07,  5.72it/s]16 03:20:53 Save the image 01148N.png
 90%|███████████████████████████████████▉    | 352/392 [01:02<00:07,  5.66it/s]16 03:20:53 Save the image 01149N.png
 90%|████████████████████████████████████    | 353/392 [01:02<00:06,  5.68it/s]16 03:20:53 Save the image 01150N.png
 90%|████████████████████████████████████    | 354/392 [01:02<00:06,  5.66it/s]16 03:20:53 Save the image 01151N.png
 91%|████████████████████████████████████▏   | 355/392 [01:02<00:06,  5.67it/s]16 03:20:53 Save the image 01152N.png
 91%|████████████████████████████████████▎   | 356/392 [01:02<00:06,  5.64it/s]16 03:20:54 Save the image 01153N.png
 91%|████████████████████████████████████▍   | 357/392 [01:03<00:06,  5.63it/s]16 03:20:54 Save the image 01154N.png
 91%|████████████████████████████████████▌   | 358/392 [01:03<00:05,  5.69it/s]16 03:20:54 Save the image 01155N.png
 92%|████████████████████████████████████▋   | 359/392 [01:03<00:05,  5.76it/s]16 03:20:54 Save the image 01156N.png
 92%|████████████████████████████████████▋   | 360/392 [01:03<00:05,  5.69it/s]16 03:20:54 Save the image 01157N.png
 92%|████████████████████████████████████▊   | 361/392 [01:03<00:05,  5.68it/s]16 03:20:54 Save the image 01158N.png
 92%|████████████████████████████████████▉   | 362/392 [01:03<00:05,  5.69it/s]16 03:20:55 Save the image 01159N.png
 93%|█████████████████████████████████████   | 363/392 [01:04<00:05,  5.65it/s]16 03:20:55 Save the image 01160N.png
 93%|█████████████████████████████████████▏  | 364/392 [01:04<00:04,  5.64it/s]16 03:20:55 Save the image 01161N.png
 93%|█████████████████████████████████████▏  | 365/392 [01:04<00:04,  5.63it/s]16 03:20:55 Save the image 01162N.png
 93%|█████████████████████████████████████▎  | 366/392 [01:04<00:04,  5.69it/s]16 03:20:55 Save the image 01163N.png
 94%|█████████████████████████████████████▍  | 367/392 [01:04<00:04,  5.76it/s]16 03:20:56 Save the image 01164N.png
 94%|█████████████████████████████████████▌  | 368/392 [01:04<00:04,  5.72it/s]16 03:20:56 Save the image 01165N.png
 94%|█████████████████████████████████████▋  | 369/392 [01:05<00:04,  5.69it/s]16 03:20:56 Save the image 01166N.png
 94%|█████████████████████████████████████▊  | 370/392 [01:05<00:03,  5.70it/s]16 03:20:56 Save the image 01167N.png
 95%|█████████████████████████████████████▊  | 371/392 [01:05<00:03,  5.65it/s]16 03:20:56 Save the image 01168N.png
 95%|█████████████████████████████████████▉  | 372/392 [01:05<00:03,  5.66it/s]16 03:20:56 Save the image 01169N.png
 95%|██████████████████████████████████████  | 373/392 [01:05<00:03,  5.63it/s]16 03:20:57 Save the image 01170N.png
 95%|██████████████████████████████████████▏ | 374/392 [01:06<00:03,  5.70it/s]16 03:20:57 Save the image 01171N.png
 96%|██████████████████████████████████████▎ | 375/392 [01:06<00:02,  5.67it/s]16 03:20:57 Save the image 01172N.png
 96%|██████████████████████████████████████▎ | 376/392 [01:06<00:02,  5.67it/s]16 03:20:57 Save the image 01173N.png
 96%|██████████████████████████████████████▍ | 377/392 [01:06<00:02,  5.66it/s]16 03:20:57 Save the image 01174N.png
 96%|██████████████████████████████████████▌ | 378/392 [01:06<00:02,  5.67it/s]16 03:20:57 Save the image 01175N.png
 97%|██████████████████████████████████████▋ | 379/392 [01:06<00:02,  5.66it/s]16 03:20:58 Save the image 01176N.png
 97%|██████████████████████████████████████▊ | 380/392 [01:07<00:02,  5.64it/s]16 03:20:58 Save the image 01177N.png
 97%|██████████████████████████████████████▉ | 381/392 [01:07<00:01,  5.63it/s]16 03:20:58 Save the image 01178N.png
 97%|██████████████████████████████████████▉ | 382/392 [01:07<00:01,  5.66it/s]16 03:20:58 Save the image 01179N.png

 98%|███████████████████████████████████████ | 383/392 [01:07<00:01,  5.73it/s]16 03:20:58 Save the image 01180N.png
 98%|███████████████████████████████████████▏| 384/392 [01:07<00:01,  5.66it/s]16 03:20:59 Save the image 01181N.png
 98%|███████████████████████████████████████▎| 385/392 [01:07<00:01,  5.72it/s]16 03:20:59 Save the image 01182N.png
 98%|███████████████████████████████████████▍| 386/392 [01:08<00:01,  5.69it/s]16 03:20:59 Save the image 01183N.png
 99%|███████████████████████████████████████▍| 387/392 [01:08<00:00,  5.66it/s]16 03:20:59 Save the image 01184N.png
 99%|███████████████████████████████████████▌| 388/392 [01:08<00:00,  5.63it/s]16 03:20:59 Save the image 01185N.png
 99%|███████████████████████████████████████▋| 389/392 [01:08<00:00,  5.64it/s]16 03:20:59 Save the image 01186N.png
 99%|███████████████████████████████████████▊| 390/392 [01:08<00:00,  5.69it/s]16 03:21:00 Save the image 01187N.png
100%|███████████████████████████████████████▉| 391/392 [01:09<00:00,  5.66it/s]16 03:21:00 Save the image 01188N.png
100%|████████████████████████████████████████| 392/392 [01:09<00:00,  5.66it/s]
1 unlabeled	97.821%
2 car   	87.388%
3 person	72.118%
4 bike  	72.445%
5 curve 	38.937%
6 car_stop	34.894%
7 guardrail	49.828%
8 color_cone	59.796%
9 bump  	46.668%
----------     mean_IoU	62.211%	freq_IoU	95.808%	mean_pixel_acc	71.387%	pixel_acc	97.758%
16 03:21:00 Evaluation Elapsed Time: 69.23s

In [22]:

import os

os.chdir("/home/cse-sdpl/Downloads/CMX_E4")

!python eval.py -e 100 -d 0 --split train -p predictions_E4_train

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 03:21:23 using devices 0
16 03:21:23 Using E4: SegFormer-B2 with reliability-gated rectification
16 03:21:24 Using MLP Decoder
16 03:21:24 Load Model: /home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2_e4/checkpoint/epoch-100.pth
16 03:21:29 Load model, Time usage:
	IO: 4.333745002746582, initialize parameters: 0.04397153854370117
16 03:21:29 GPU 0 handle 1568 data.
  0%|                                                 | 0/1568 [00:00<?, ?it/s][ WARN:0@11.610] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 03:21:33 Save the image 00001D.png
  0%|                                       | 1/1568 [00:04<1:58:31,  4.54s/it]16 03:21:33 Save the image 00001D_flip.png
  0%|                                         | 2/1568 [00:04<51:04,  1.96s/it]16 03:21:33 Save the image 00002D.png
  0%|                                         | 3/1568 [00:04<29:53,  1.15s/it]16 03:21:34 Save the image 00002D_flip.png
  0%|                                         | 4/1568 [00:05<19:49,  1.31it/s]16 03:21:34 Save the image 00055D.png
  0%|▏                                        | 5/1568 [00:05<14:16,  1.82it/s]16 03:21:34 Save the image 00055D_flip.png
  0%|▏                                        | 6/1568 [00:05<10:58,  2.37it/s]16 03:21:34 Save the image 00056D.png
  0%|▏                                        | 7/1568 [00:05<08:48,  2.96it/s]16 03:21:34 Save the image 00056D_flip.png
  1%|▏                                        | 8/1568 [00:05<07:25,  3.50it/s]16 03:21:35 Save the image 00057D.png
  1%|▏                                        | 9/1568 [00:05<06:33,  3.96it/s]16 03:21:35 Save the image 00057D_flip.png
  1%|▎                                       | 10/1568 [00:06<05:40,  4.57it/s]16 03:21:35 Save the image 00058D.png
  1%|▎                                       | 11/1568 [00:06<05:23,  4.82it/s]16 03:21:35 Save the image 00058D_flip.png
  1%|▎                                       | 12/1568 [00:06<05:05,  5.09it/s]16 03:21:35 Save the image 00081D.png
  1%|▎                                       | 13/1568 [00:06<04:53,  5.30it/s]16 03:21:35 Save the image 00081D_flip.png
  1%|▎                                       | 14/1568 [00:06<04:46,  5.42it/s]16 03:21:36 Save the image 00082D.png
  1%|▍                                       | 15/1568 [00:06<04:41,  5.52it/s]16 03:21:36 Save the image 00082D_flip.png
  1%|▍                                       | 16/1568 [00:07<04:37,  5.60it/s]16 03:21:36 Save the image 00083D.png
  1%|▍                                       | 17/1568 [00:07<04:34,  5.66it/s]16 03:21:36 Save the image 00083D_flip.png
  1%|▍                                       | 18/1568 [00:07<04:18,  5.99it/s]16 03:21:36 Save the image 00084D.png
  1%|▍                                       | 19/1568 [00:07<04:22,  5.89it/s]16 03:21:36 Save the image 00084D_flip.png
  1%|▌                                       | 20/1568 [00:07<04:24,  5.84it/s]16 03:21:37 Save the image 00085D.png
  1%|▌                                       | 21/1568 [00:07<04:27,  5.78it/s]16 03:21:37 Save the image 00085D_flip.png
  1%|▌                                       | 22/1568 [00:08<04:28,  5.77it/s]16 03:21:37 Save the image 00086D.png
  1%|▌                                       | 23/1568 [00:08<04:27,  5.77it/s]16 03:21:37 Save the image 00086D_flip.png
  2%|▌                                       | 24/1568 [00:08<04:27,  5.76it/s]16 03:21:37 Save the image 00087D.png
  2%|▋                                       | 25/1568 [00:08<04:25,  5.80it/s]16 03:21:37 Save the image 00087D_flip.png
  2%|▋                                       | 26/1568 [00:08<04:20,  5.92it/s]16 03:21:38 Save the image 00088D.png
  2%|▋                                       | 27/1568 [00:08<04:24,  5.83it/s]16 03:21:38 Save the image 00088D_flip.png
  2%|▋                                       | 28/1568 [00:09<04:25,  5.80it/s]16 03:21:38 Save the image 00091D.png
  2%|▋                                       | 29/1568 [00:09<04:26,  5.78it/s]16 03:21:38 Save the image 00091D_flip.png
  2%|▊                                       | 30/1568 [00:09<04:28,  5.73it/s]16 03:21:38 Save the image 00092D.png
  2%|▊                                       | 31/1568 [00:09<04:28,  5.73it/s]16 03:21:38 Save the image 00092D_flip.png
  2%|▊                                       | 32/1568 [00:09<04:30,  5.68it/s]16 03:21:39 Save the image 00093D.png
  2%|▊                                       | 33/1568 [00:10<04:26,  5.76it/s]16 03:21:39 Save the image 00093D_flip.png
  2%|▊                                       | 34/1568 [00:10<04:19,  5.90it/s]16 03:21:39 Save the image 00094D.png
  2%|▉                                       | 35/1568 [00:10<04:22,  5.84it/s]16 03:21:39 Save the image 00094D_flip.png
  2%|▉                                       | 36/1568 [00:10<04:22,  5.83it/s]16 03:21:39 Save the image 00095D.png
  2%|▉                                       | 37/1568 [00:10<04:22,  5.83it/s]16 03:21:39 Save the image 00095D_flip.png
  2%|▉                                       | 38/1568 [00:10<04:24,  5.79it/s]16 03:21:40 Save the image 00096D.png
  2%|▉                                       | 39/1568 [00:11<04:24,  5.79it/s]16 03:21:40 Save the image 00096D_flip.png
  3%|█                                       | 40/1568 [00:11<04:24,  5.77it/s]16 03:21:40 Save the image 00097D.png
  3%|█                                       | 41/1568 [00:11<04:21,  5.84it/s]16 03:21:40 Save the image 00097D_flip.png
  3%|█                                       | 42/1568 [00:11<04:15,  5.97it/s]16 03:21:40 Save the image 00098D.png
  3%|█                                       | 43/1568 [00:11<04:18,  5.89it/s]16 03:21:41 Save the image 00098D_flip.png
  3%|█                                       | 44/1568 [00:11<04:19,  5.87it/s]16 03:21:41 Save the image 00099D.png
  3%|█▏                                      | 45/1568 [00:12<04:22,  5.80it/s]16 03:21:41 Save the image 00099D_flip.png
  3%|█▏                                      | 46/1568 [00:12<04:27,  5.69it/s]16 03:21:41 Save the image 00100D.png
  3%|█▏                                      | 47/1568 [00:12<04:27,  5.69it/s]16 03:21:41 Save the image 00100D_flip.png
  3%|█▏                                      | 48/1568 [00:12<04:26,  5.70it/s]16 03:21:41 Save the image 00101D.png
  3%|█▎                                      | 49/1568 [00:12<04:26,  5.71it/s]16 03:21:42 Save the image 00101D_flip.png
  3%|█▎                                      | 50/1568 [00:12<04:09,  6.10it/s]16 03:21:42 Save the image 00102D.png
  3%|█▎                                      | 51/1568 [00:13<04:13,  5.99it/s]16 03:21:42 Save the image 00102D_flip.png
  3%|█▎                                      | 52/1568 [00:13<04:15,  5.93it/s]16 03:21:42 Save the image 00103D.png
  3%|█▎                                      | 53/1568 [00:13<04:17,  5.89it/s]16 03:21:42 Save the image 00103D_flip.png
  3%|█▍                                      | 54/1568 [00:13<04:22,  5.77it/s]16 03:21:42 Save the image 00104D.png
  4%|█▍                                      | 55/1568 [00:13<04:23,  5.75it/s]16 03:21:43 Save the image 00104D_flip.png
  4%|█▍                                      | 56/1568 [00:13<04:23,  5.74it/s]16 03:21:43 Save the image 00105D.png

  4%|█▍                                      | 57/1568 [00:14<04:22,  5.75it/s]16 03:21:43 Save the image 00105D_flip.png
  4%|█▍                                      | 58/1568 [00:14<04:06,  6.12it/s]16 03:21:43 Save the image 00106D.png
  4%|█▌                                      | 59/1568 [00:14<04:11,  6.01it/s]16 03:21:43 Save the image 00106D_flip.png
  4%|█▌                                      | 60/1568 [00:14<04:13,  5.95it/s]16 03:21:43 Save the image 00107D.png
  4%|█▌                                      | 61/1568 [00:14<04:15,  5.90it/s]16 03:21:44 Save the image 00107D_flip.png
  4%|█▌                                      | 62/1568 [00:14<04:17,  5.84it/s]16 03:21:44 Save the image 00108D.png
  4%|█▌                                      | 63/1568 [00:15<04:18,  5.82it/s]16 03:21:44 Save the image 00108D_flip.png
  4%|█▋                                      | 64/1568 [00:15<04:18,  5.81it/s]16 03:21:44 Save the image 00109D.png
  4%|█▋                                      | 65/1568 [00:15<04:15,  5.87it/s]16 03:21:44 Save the image 00109D_flip.png
  4%|█▋                                      | 66/1568 [00:15<04:08,  6.04it/s]16 03:21:44 Save the image 00110D.png
  4%|█▋                                      | 67/1568 [00:15<04:13,  5.92it/s]16 03:21:45 Save the image 00110D_flip.png
  4%|█▋                                      | 68/1568 [00:15<04:14,  5.89it/s]16 03:21:45 Save the image 00111D.png
  4%|█▊                                      | 69/1568 [00:16<04:15,  5.87it/s]16 03:21:45 Save the image 00111D_flip.png
  4%|█▊                                      | 70/1568 [00:16<04:17,  5.82it/s]16 03:21:45 Save the image 00112D.png
  5%|█▊                                      | 71/1568 [00:16<04:20,  5.75it/s]16 03:21:45 Save the image 00112D_flip.png
  5%|█▊                                      | 72/1568 [00:16<04:21,  5.72it/s]16 03:21:45 Save the image 00113D.png
  5%|█▊                                      | 73/1568 [00:16<04:18,  5.78it/s]16 03:21:46 Save the image 00113D_flip.png
  5%|█▉                                      | 74/1568 [00:17<04:16,  5.83it/s]16 03:21:46 Save the image 00114D.png
  5%|█▉                                      | 75/1568 [00:17<04:19,  5.75it/s]16 03:21:46 Save the image 00114D_flip.png
  5%|█▉                                      | 76/1568 [00:17<04:19,  5.75it/s]16 03:21:46 Save the image 00115D.png
  5%|█▉                                      | 77/1568 [00:17<04:21,  5.70it/s]16 03:21:46 Save the image 00115D_flip.png
  5%|█▉                                      | 78/1568 [00:17<04:22,  5.68it/s]16 03:21:47 Save the image 00116D.png
  5%|██                                      | 79/1568 [00:17<04:24,  5.64it/s]16 03:21:47 Save the image 00116D_flip.png
  5%|██                                      | 80/1568 [00:18<04:23,  5.66it/s]16 03:21:47 Save the image 00117D.png
  5%|██                                      | 81/1568 [00:18<04:21,  5.69it/s]16 03:21:47 Save the image 00117D_flip.png
  5%|██                                      | 82/1568 [00:18<04:18,  5.76it/s]16 03:21:47 Save the image 00118D.png
  5%|██                                      | 83/1568 [00:18<04:18,  5.75it/s]16 03:21:47 Save the image 00118D_flip.png
  5%|██▏                                     | 84/1568 [00:18<04:17,  5.77it/s]16 03:21:48 Save the image 00119D.png
  5%|██▏                                     | 85/1568 [00:18<04:16,  5.79it/s]16 03:21:48 Save the image 00119D_flip.png
  5%|██▏                                     | 86/1568 [00:19<04:16,  5.78it/s]16 03:21:48 Save the image 00120D.png
  6%|██▏                                     | 87/1568 [00:19<04:16,  5.78it/s]16 03:21:48 Save the image 00120D_flip.png
  6%|██▏                                     | 88/1568 [00:19<04:15,  5.79it/s]16 03:21:48 Save the image 00121D.png
  6%|██▎                                     | 89/1568 [00:19<04:12,  5.86it/s]16 03:21:48 Save the image 00121D_flip.png
  6%|██▎                                     | 90/1568 [00:19<04:08,  5.94it/s]16 03:21:49 Save the image 00122D.png
  6%|██▎                                     | 91/1568 [00:19<04:11,  5.87it/s]16 03:21:49 Save the image 00122D_flip.png
  6%|██▎                                     | 92/1568 [00:20<04:12,  5.85it/s]16 03:21:49 Save the image 00123D.png
  6%|██▎                                     | 93/1568 [00:20<04:12,  5.84it/s]16 03:21:49 Save the image 00123D_flip.png
  6%|██▍                                     | 94/1568 [00:20<04:13,  5.81it/s]16 03:21:49 Save the image 00124D.png
  6%|██▍                                     | 95/1568 [00:20<04:14,  5.79it/s]16 03:21:49 Save the image 00124D_flip.png
  6%|██▍                                     | 96/1568 [00:20<04:17,  5.71it/s]16 03:21:50 Save the image 00125D.png
  6%|██▍                                     | 97/1568 [00:21<04:19,  5.68it/s]16 03:21:50 Save the image 00125D_flip.png
  6%|██▌                                     | 98/1568 [00:21<04:06,  5.95it/s]16 03:21:50 Save the image 00126D.png
  6%|██▌                                     | 99/1568 [00:21<04:11,  5.85it/s]16 03:21:50 Save the image 00126D_flip.png
  6%|██▍                                    | 100/1568 [00:21<04:11,  5.83it/s]16 03:21:50 Save the image 00127D.png
  6%|██▌                                    | 101/1568 [00:21<04:11,  5.83it/s]16 03:21:50 Save the image 00127D_flip.png
  7%|██▌                                    | 102/1568 [00:21<04:14,  5.75it/s]16 03:21:51 Save the image 00128D.png
  7%|██▌                                    | 103/1568 [00:22<04:17,  5.69it/s]16 03:21:51 Save the image 00128D_flip.png
  7%|██▌                                    | 104/1568 [00:22<04:16,  5.71it/s]16 03:21:51 Save the image 00129D.png
  7%|██▌                                    | 105/1568 [00:22<04:14,  5.74it/s]16 03:21:51 Save the image 00129D_flip.png
  7%|██▋                                    | 106/1568 [00:22<04:05,  5.96it/s]16 03:21:51 Save the image 00130D.png
  7%|██▋                                    | 107/1568 [00:22<04:09,  5.85it/s]16 03:21:52 Save the image 00130D_flip.png
  7%|██▋                                    | 108/1568 [00:22<04:10,  5.84it/s]16 03:21:52 Save the image 00131D.png
  7%|██▋                                    | 109/1568 [00:23<04:10,  5.82it/s]16 03:21:52 Save the image 00131D_flip.png
  7%|██▋                                    | 110/1568 [00:23<04:12,  5.79it/s]16 03:21:52 Save the image 00132D.png
  7%|██▊                                    | 111/1568 [00:23<04:11,  5.79it/s]16 03:21:52 Save the image 00132D_flip.png
  7%|██▊                                    | 112/1568 [00:23<04:12,  5.78it/s]16 03:21:52 Save the image 00133D.png
  7%|██▊                                    | 113/1568 [00:23<04:10,  5.82it/s]16 03:21:53 Save the image 00133D_flip.png
  7%|██▊                                    | 114/1568 [00:23<04:03,  5.97it/s]16 03:21:53 Save the image 00134D.png
  7%|██▊                                    | 115/1568 [00:24<04:07,  5.87it/s]16 03:21:53 Save the image 00134D_flip.png
  7%|██▉                                    | 116/1568 [00:24<04:08,  5.84it/s]16 03:21:53 Save the image 00135D.png
  7%|██▉                                    | 117/1568 [00:24<04:08,  5.84it/s]16 03:21:53 Save the image 00135D_flip.png
  8%|██▉                                    | 118/1568 [00:24<04:09,  5.81it/s]16 03:21:53 Save the image 00136D.png
  8%|██▉                                    | 119/1568 [00:24<04:09,  5.80it/s]16 03:21:54 Save the image 00136D_flip.png
  8%|██▉                                    | 120/1568 [00:24<04:10,  5.78it/s]16 03:21:54 Save the image 00137D.png

  8%|███                                    | 121/1568 [00:25<04:08,  5.83it/s]16 03:21:54 Save the image 00137D_flip.png
  8%|███                                    | 122/1568 [00:25<04:03,  5.95it/s]16 03:21:54 Save the image 00138D.png
  8%|███                                    | 123/1568 [00:25<04:06,  5.87it/s]16 03:21:54 Save the image 00138D_flip.png
  8%|███                                    | 124/1568 [00:25<04:06,  5.86it/s]16 03:21:54 Save the image 00139D.png
  8%|███                                    | 125/1568 [00:25<04:06,  5.85it/s]16 03:21:55 Save the image 00139D_flip.png
  8%|███▏                                   | 126/1568 [00:25<04:08,  5.80it/s]16 03:21:55 Save the image 00140D.png
  8%|███▏                                   | 127/1568 [00:26<04:08,  5.79it/s]16 03:21:55 Save the image 00140D_flip.png
  8%|███▏                                   | 128/1568 [00:26<04:09,  5.77it/s]16 03:21:55 Save the image 00141D.png
  8%|███▏                                   | 129/1568 [00:26<04:07,  5.81it/s]16 03:21:55 Save the image 00141D_flip.png
  8%|███▏                                   | 130/1568 [00:26<04:02,  5.94it/s]16 03:21:55 Save the image 00142D.png
  8%|███▎                                   | 131/1568 [00:26<04:05,  5.85it/s]16 03:21:56 Save the image 00142D_flip.png
  8%|███▎                                   | 132/1568 [00:27<04:05,  5.85it/s]16 03:21:56 Save the image 00143D.png
  8%|███▎                                   | 133/1568 [00:27<04:05,  5.84it/s]16 03:21:56 Save the image 00143D_flip.png
  9%|███▎                                   | 134/1568 [00:27<04:07,  5.79it/s]16 03:21:56 Save the image 00144D.png
  9%|███▎                                   | 135/1568 [00:27<04:07,  5.78it/s]16 03:21:56 Save the image 00144D_flip.png
  9%|███▍                                   | 136/1568 [00:27<04:08,  5.77it/s]16 03:21:56 Save the image 00145D.png
  9%|███▍                                   | 137/1568 [00:27<04:07,  5.79it/s]16 03:21:57 Save the image 00145D_flip.png
  9%|███▍                                   | 138/1568 [00:28<03:59,  5.98it/s]16 03:21:57 Save the image 00146D.png
  9%|███▍                                   | 139/1568 [00:28<04:02,  5.90it/s]16 03:21:57 Save the image 00146D_flip.png
  9%|███▍                                   | 140/1568 [00:28<04:02,  5.88it/s]16 03:21:57 Save the image 00147D.png
  9%|███▌                                   | 141/1568 [00:28<04:03,  5.87it/s]16 03:21:57 Save the image 00147D_flip.png
  9%|███▌                                   | 142/1568 [00:28<04:05,  5.82it/s]16 03:21:58 Save the image 00148D.png
  9%|███▌                                   | 143/1568 [00:28<04:05,  5.81it/s]16 03:21:58 Save the image 00148D_flip.png
  9%|███▌                                   | 144/1568 [00:29<04:05,  5.80it/s]16 03:21:58 Save the image 00149D.png
  9%|███▌                                   | 145/1568 [00:29<04:03,  5.83it/s]16 03:21:58 Save the image 00149D_flip.png
  9%|███▋                                   | 146/1568 [00:29<03:58,  5.97it/s]16 03:21:58 Save the image 00150D.png
  9%|███▋                                   | 147/1568 [00:29<04:01,  5.88it/s]16 03:21:58 Save the image 00150D_flip.png
  9%|███▋                                   | 148/1568 [00:29<04:02,  5.86it/s]16 03:21:59 Save the image 00151D.png
 10%|███▋                                   | 149/1568 [00:29<04:01,  5.87it/s]16 03:21:59 Save the image 00151D_flip.png
 10%|███▋                                   | 150/1568 [00:30<04:02,  5.84it/s]16 03:21:59 Save the image 00152D.png
 10%|███▊                                   | 151/1568 [00:30<04:03,  5.83it/s]16 03:21:59 Save the image 00152D_flip.png
 10%|███▊                                   | 152/1568 [00:30<04:03,  5.82it/s]16 03:21:59 Save the image 00153D.png
 10%|███▊                                   | 153/1568 [00:30<04:00,  5.87it/s]16 03:21:59 Save the image 00153D_flip.png
 10%|███▊                                   | 154/1568 [00:30<03:57,  5.96it/s]16 03:22:00 Save the image 00154D.png
 10%|███▊                                   | 155/1568 [00:30<03:59,  5.90it/s]16 03:22:00 Save the image 00154D_flip.png
 10%|███▉                                   | 156/1568 [00:31<04:01,  5.85it/s]16 03:22:00 Save the image 00155D.png
 10%|███▉                                   | 157/1568 [00:31<04:02,  5.82it/s]16 03:22:00 Save the image 00155D_flip.png
 10%|███▉                                   | 158/1568 [00:31<04:02,  5.82it/s]16 03:22:00 Save the image 00156D.png
 10%|███▉                                   | 159/1568 [00:31<04:02,  5.81it/s]16 03:22:00 Save the image 00156D_flip.png
 10%|███▉                                   | 160/1568 [00:31<04:03,  5.79it/s]16 03:22:01 Save the image 00157D.png
 10%|████                                   | 161/1568 [00:31<04:01,  5.82it/s]16 03:22:01 Save the image 00157D_flip.png
 10%|████                                   | 162/1568 [00:32<03:55,  5.97it/s]16 03:22:01 Save the image 00158D.png
 10%|████                                   | 163/1568 [00:32<03:57,  5.92it/s]16 03:22:01 Save the image 00158D_flip.png
 10%|████                                   | 164/1568 [00:32<03:58,  5.88it/s]16 03:22:01 Save the image 00159D.png
 11%|████                                   | 165/1568 [00:32<03:58,  5.88it/s]16 03:22:01 Save the image 00159D_flip.png
 11%|████▏                                  | 166/1568 [00:32<03:59,  5.85it/s]16 03:22:02 Save the image 00160D.png
 11%|████▏                                  | 167/1568 [00:32<04:00,  5.82it/s]16 03:22:02 Save the image 00160D_flip.png
 11%|████▏                                  | 168/1568 [00:33<04:00,  5.81it/s]16 03:22:02 Save the image 00161D.png
 11%|████▏                                  | 169/1568 [00:33<03:59,  5.84it/s]16 03:22:02 Save the image 00161D_flip.png
 11%|████▏                                  | 170/1568 [00:33<03:56,  5.91it/s]16 03:22:02 Save the image 00162D.png
 11%|████▎                                  | 171/1568 [00:33<03:59,  5.84it/s]16 03:22:02 Save the image 00162D_flip.png
 11%|████▎                                  | 172/1568 [00:33<03:58,  5.84it/s]16 03:22:03 Save the image 00163D.png
 11%|████▎                                  | 173/1568 [00:34<03:59,  5.82it/s]16 03:22:03 Save the image 00163D_flip.png
 11%|████▎                                  | 174/1568 [00:34<04:02,  5.76it/s]16 03:22:03 Save the image 00164D.png
 11%|████▎                                  | 175/1568 [00:34<04:01,  5.77it/s]16 03:22:03 Save the image 00164D_flip.png
 11%|████▍                                  | 176/1568 [00:34<04:01,  5.77it/s]16 03:22:03 Save the image 00165D.png
 11%|████▍                                  | 177/1568 [00:34<03:59,  5.82it/s]16 03:22:03 Save the image 00165D_flip.png
 11%|████▍                                  | 178/1568 [00:34<03:52,  5.98it/s]16 03:22:04 Save the image 00166D.png
 11%|████▍                                  | 179/1568 [00:35<03:55,  5.89it/s]16 03:22:04 Save the image 00166D_flip.png
 11%|████▍                                  | 180/1568 [00:35<03:56,  5.87it/s]16 03:22:04 Save the image 00167D.png
 12%|████▌                                  | 181/1568 [00:35<03:57,  5.85it/s]16 03:22:04 Save the image 00167D_flip.png
 12%|████▌                                  | 182/1568 [00:35<03:58,  5.81it/s]16 03:22:04 Save the image 00168D.png
 12%|████▌                                  | 183/1568 [00:35<03:59,  5.78it/s]16 03:22:05 Save the image 00168D_flip.png
 12%|████▌                                  | 184/1568 [00:35<03:59,  5.78it/s]16 03:22:05 Save the image 00169D.png

 12%|████▌                                  | 185/1568 [00:36<03:56,  5.85it/s]16 03:22:05 Save the image 00169D_flip.png
 12%|████▋                                  | 186/1568 [00:36<03:50,  6.00it/s]16 03:22:05 Save the image 00170D.png
 12%|████▋                                  | 187/1568 [00:36<03:54,  5.88it/s]16 03:22:05 Save the image 00170D_flip.png
 12%|████▋                                  | 188/1568 [00:36<03:56,  5.83it/s]16 03:22:05 Save the image 00171D.png
 12%|████▋                                  | 189/1568 [00:36<03:55,  5.84it/s]16 03:22:06 Save the image 00171D_flip.png
 12%|████▋                                  | 190/1568 [00:36<03:57,  5.80it/s]16 03:22:06 Save the image 00172D.png
 12%|████▊                                  | 191/1568 [00:37<03:57,  5.79it/s]16 03:22:06 Save the image 00172D_flip.png
 12%|████▊                                  | 192/1568 [00:37<03:57,  5.78it/s]16 03:22:06 Save the image 00173D.png
 12%|████▊                                  | 193/1568 [00:37<03:54,  5.85it/s]16 03:22:06 Save the image 00173D_flip.png
 12%|████▊                                  | 194/1568 [00:37<03:48,  6.01it/s]16 03:22:06 Save the image 00174D.png
 12%|████▊                                  | 195/1568 [00:37<03:51,  5.92it/s]16 03:22:07 Save the image 00174D_flip.png
 12%|████▉                                  | 196/1568 [00:37<03:52,  5.89it/s]16 03:22:07 Save the image 00175D.png
 13%|████▉                                  | 197/1568 [00:38<03:54,  5.86it/s]16 03:22:07 Save the image 00175D_flip.png
 13%|████▉                                  | 198/1568 [00:38<03:57,  5.76it/s]16 03:22:07 Save the image 00176D.png
 13%|████▉                                  | 199/1568 [00:38<03:58,  5.73it/s]16 03:22:07 Save the image 00176D_flip.png
 13%|████▉                                  | 200/1568 [00:38<04:00,  5.69it/s]16 03:22:07 Save the image 00177D.png
 13%|████▉                                  | 201/1568 [00:38<03:58,  5.73it/s]16 03:22:08 Save the image 00177D_flip.png
 13%|█████                                  | 202/1568 [00:38<03:54,  5.83it/s]16 03:22:08 Save the image 00178D.png
 13%|█████                                  | 203/1568 [00:39<03:56,  5.78it/s]16 03:22:08 Save the image 00178D_flip.png
 13%|█████                                  | 204/1568 [00:39<03:57,  5.75it/s]16 03:22:08 Save the image 00179D.png
 13%|█████                                  | 205/1568 [00:39<03:57,  5.73it/s]16 03:22:08 Save the image 00179D_flip.png
 13%|█████                                  | 206/1568 [00:39<03:58,  5.70it/s]16 03:22:08 Save the image 00180D.png
 13%|█████▏                                 | 207/1568 [00:39<03:58,  5.70it/s]16 03:22:09 Save the image 00180D_flip.png
 13%|█████▏                                 | 208/1568 [00:40<03:58,  5.69it/s]16 03:22:09 Save the image 00181D.png
 13%|█████▏                                 | 209/1568 [00:40<03:55,  5.78it/s]16 03:22:09 Save the image 00181D_flip.png
 13%|█████▏                                 | 210/1568 [00:40<03:56,  5.75it/s]16 03:22:09 Save the image 00182D.png
 13%|█████▏                                 | 211/1568 [00:40<03:57,  5.72it/s]16 03:22:09 Save the image 00182D_flip.png
 14%|█████▎                                 | 212/1568 [00:40<03:57,  5.71it/s]16 03:22:10 Save the image 00183D.png
 14%|█████▎                                 | 213/1568 [00:40<03:57,  5.70it/s]16 03:22:10 Save the image 00183D_flip.png
 14%|█████▎                                 | 214/1568 [00:41<03:57,  5.69it/s]16 03:22:10 Save the image 00184D.png
 14%|█████▎                                 | 215/1568 [00:41<03:57,  5.70it/s]16 03:22:10 Save the image 00184D_flip.png
 14%|█████▎                                 | 216/1568 [00:41<03:57,  5.70it/s]16 03:22:10 Save the image 00185D.png
 14%|█████▍                                 | 217/1568 [00:41<03:54,  5.77it/s]16 03:22:10 Save the image 00185D_flip.png
 14%|█████▍                                 | 218/1568 [00:41<03:54,  5.75it/s]16 03:22:11 Save the image 00186D.png
 14%|█████▍                                 | 219/1568 [00:41<03:55,  5.72it/s]16 03:22:11 Save the image 00186D_flip.png
 14%|█████▍                                 | 220/1568 [00:42<03:55,  5.72it/s]16 03:22:11 Save the image 00187D.png
 14%|█████▍                                 | 221/1568 [00:42<03:55,  5.73it/s]16 03:22:11 Save the image 00187D_flip.png
 14%|█████▌                                 | 222/1568 [00:42<03:55,  5.72it/s]16 03:22:11 Save the image 00188D.png
 14%|█████▌                                 | 223/1568 [00:42<03:55,  5.70it/s]16 03:22:11 Save the image 00188D_flip.png
 14%|█████▌                                 | 224/1568 [00:42<03:55,  5.70it/s]16 03:22:12 Save the image 00189D.png
 14%|█████▌                                 | 225/1568 [00:43<03:54,  5.72it/s]16 03:22:12 Save the image 00189D_flip.png
 14%|█████▌                                 | 226/1568 [00:43<03:51,  5.80it/s]16 03:22:12 Save the image 00190D.png
 14%|█████▋                                 | 227/1568 [00:43<03:52,  5.76it/s]16 03:22:12 Save the image 00190D_flip.png
 15%|█████▋                                 | 228/1568 [00:43<03:53,  5.74it/s]16 03:22:12 Save the image 00191D.png
 15%|█████▋                                 | 229/1568 [00:43<03:56,  5.65it/s]16 03:22:13 Save the image 00191D_flip.png
 15%|█████▋                                 | 230/1568 [00:43<03:58,  5.62it/s]16 03:22:13 Save the image 00192D.png
 15%|█████▋                                 | 231/1568 [00:44<03:58,  5.62it/s]16 03:22:13 Save the image 00192D_flip.png
 15%|█████▊                                 | 232/1568 [00:44<03:56,  5.64it/s]16 03:22:13 Save the image 00193D.png
 15%|█████▊                                 | 233/1568 [00:44<03:53,  5.72it/s]16 03:22:13 Save the image 00193D_flip.png
 15%|█████▊                                 | 234/1568 [00:44<03:46,  5.88it/s]16 03:22:13 Save the image 00194D.png
 15%|█████▊                                 | 235/1568 [00:44<03:49,  5.80it/s]16 03:22:14 Save the image 00194D_flip.png
 15%|█████▊                                 | 236/1568 [00:44<03:50,  5.77it/s]16 03:22:14 Save the image 00195D.png
 15%|█████▉                                 | 237/1568 [00:45<03:51,  5.74it/s]16 03:22:14 Save the image 00195D_flip.png
 15%|█████▉                                 | 238/1568 [00:45<03:54,  5.66it/s]16 03:22:14 Save the image 00196D.png
 15%|█████▉                                 | 239/1568 [00:45<03:55,  5.65it/s]16 03:22:14 Save the image 00196D_flip.png
 15%|█████▉                                 | 240/1568 [00:45<03:55,  5.63it/s]16 03:22:14 Save the image 00197D.png
 15%|█████▉                                 | 241/1568 [00:45<03:52,  5.70it/s]16 03:22:15 Save the image 00197D_flip.png
 15%|██████                                 | 242/1568 [00:46<03:53,  5.68it/s]16 03:22:15 Save the image 00198D.png
 15%|██████                                 | 243/1568 [00:46<03:53,  5.67it/s]16 03:22:15 Save the image 00198D_flip.png
 16%|██████                                 | 244/1568 [00:46<03:53,  5.68it/s]16 03:22:15 Save the image 00199D.png
 16%|██████                                 | 245/1568 [00:46<03:52,  5.69it/s]16 03:22:15 Save the image 00199D_flip.png
 16%|██████                                 | 246/1568 [00:46<03:53,  5.67it/s]16 03:22:16 Save the image 00200D.png
 16%|██████▏                                | 247/1568 [00:46<03:52,  5.67it/s]16 03:22:16 Save the image 00200D_flip.png
 16%|██████▏                                | 248/1568 [00:47<03:53,  5.66it/s]16 03:22:16 Save the image 00201D.png

 16%|██████▏                                | 249/1568 [00:47<03:49,  5.74it/s]16 03:22:16 Save the image 00201D_flip.png
 16%|██████▏                                | 250/1568 [00:47<03:50,  5.71it/s]16 03:22:16 Save the image 00202D.png
 16%|██████▏                                | 251/1568 [00:47<03:51,  5.68it/s]16 03:22:16 Save the image 00202D_flip.png
 16%|██████▎                                | 252/1568 [00:47<03:52,  5.66it/s]16 03:22:17 Save the image 00203D.png
 16%|██████▎                                | 253/1568 [00:47<03:52,  5.67it/s]16 03:22:17 Save the image 00203D_flip.png
 16%|██████▎                                | 254/1568 [00:48<03:52,  5.65it/s]16 03:22:17 Save the image 00204D.png
 16%|██████▎                                | 255/1568 [00:48<03:52,  5.64it/s]16 03:22:17 Save the image 00204D_flip.png
 16%|██████▎                                | 256/1568 [00:48<03:52,  5.64it/s]16 03:22:17 Save the image 00205D.png
 16%|██████▍                                | 257/1568 [00:48<03:50,  5.69it/s]16 03:22:17 Save the image 00205D_flip.png
 16%|██████▍                                | 258/1568 [00:48<03:50,  5.69it/s]16 03:22:18 Save the image 00206D.png
 17%|██████▍                                | 259/1568 [00:49<03:50,  5.67it/s]16 03:22:18 Save the image 00206D_flip.png
 17%|██████▍                                | 260/1568 [00:49<03:52,  5.63it/s]16 03:22:18 Save the image 00207D.png
 17%|██████▍                                | 261/1568 [00:49<03:52,  5.62it/s]16 03:22:18 Save the image 00207D_flip.png
 17%|██████▌                                | 262/1568 [00:49<03:53,  5.60it/s]16 03:22:18 Save the image 00208D.png
 17%|██████▌                                | 263/1568 [00:49<03:53,  5.59it/s]16 03:22:19 Save the image 00208D_flip.png
 17%|██████▌                                | 264/1568 [00:49<03:53,  5.59it/s]16 03:22:19 Save the image 00209D.png
 17%|██████▌                                | 265/1568 [00:50<03:49,  5.68it/s]16 03:22:19 Save the image 00209D_flip.png
 17%|██████▌                                | 266/1568 [00:50<03:49,  5.68it/s]16 03:22:19 Save the image 00210D.png
 17%|██████▋                                | 267/1568 [00:50<03:48,  5.69it/s]16 03:22:19 Save the image 00210D_flip.png
 17%|██████▋                                | 268/1568 [00:50<03:47,  5.71it/s]16 03:22:19 Save the image 00211D.png
 17%|██████▋                                | 269/1568 [00:50<03:46,  5.72it/s]16 03:22:20 Save the image 00211D_flip.png
 17%|██████▋                                | 270/1568 [00:50<03:46,  5.74it/s]16 03:22:20 Save the image 00212D.png
 17%|██████▋                                | 271/1568 [00:51<03:45,  5.75it/s]16 03:22:20 Save the image 00212D_flip.png
 17%|██████▊                                | 272/1568 [00:51<03:44,  5.77it/s]16 03:22:20 Save the image 00213D.png
 17%|██████▊                                | 273/1568 [00:51<03:42,  5.81it/s]16 03:22:20 Save the image 00213D_flip.png
 17%|██████▊                                | 274/1568 [00:51<03:38,  5.93it/s]16 03:22:20 Save the image 00214D.png
 18%|██████▊                                | 275/1568 [00:51<03:40,  5.86it/s]16 03:22:21 Save the image 00214D_flip.png
 18%|██████▊                                | 276/1568 [00:51<03:41,  5.84it/s]16 03:22:21 Save the image 00215D.png
 18%|██████▉                                | 277/1568 [00:52<03:40,  5.85it/s]16 03:22:21 Save the image 00215D_flip.png
 18%|██████▉                                | 278/1568 [00:52<03:42,  5.80it/s]16 03:22:21 Save the image 00216D.png
 18%|██████▉                                | 279/1568 [00:52<03:42,  5.80it/s]16 03:22:21 Save the image 00216D_flip.png
 18%|██████▉                                | 280/1568 [00:52<03:42,  5.78it/s]16 03:22:21 Save the image 00217D.png
 18%|██████▉                                | 281/1568 [00:52<03:41,  5.80it/s]16 03:22:22 Save the image 00217D_flip.png
 18%|███████                                | 282/1568 [00:52<03:36,  5.94it/s]16 03:22:22 Save the image 00218D.png
 18%|███████                                | 283/1568 [00:53<03:38,  5.89it/s]16 03:22:22 Save the image 00218D_flip.png
 18%|███████                                | 284/1568 [00:53<03:38,  5.88it/s]16 03:22:22 Save the image 00219D.png
 18%|███████                                | 285/1568 [00:53<03:38,  5.87it/s]16 03:22:22 Save the image 00219D_flip.png
 18%|███████                                | 286/1568 [00:53<03:40,  5.82it/s]16 03:22:22 Save the image 00220D.png
 18%|███████▏                               | 287/1568 [00:53<03:40,  5.80it/s]16 03:22:23 Save the image 00220D_flip.png
 18%|███████▏                               | 288/1568 [00:54<03:40,  5.81it/s]16 03:22:23 Save the image 00221D.png
 18%|███████▏                               | 289/1568 [00:54<03:38,  5.85it/s]16 03:22:23 Save the image 00221D_flip.png
 18%|███████▏                               | 290/1568 [00:54<03:34,  5.97it/s]16 03:22:23 Save the image 00222D.png
 19%|███████▏                               | 291/1568 [00:54<03:35,  5.92it/s]16 03:22:23 Save the image 00222D_flip.png
 19%|███████▎                               | 292/1568 [00:54<03:36,  5.89it/s]16 03:22:23 Save the image 00223D.png
 19%|███████▎                               | 293/1568 [00:54<03:37,  5.86it/s]16 03:22:24 Save the image 00223D_flip.png
 19%|███████▎                               | 294/1568 [00:55<03:38,  5.83it/s]16 03:22:24 Save the image 00224D.png
 19%|███████▎                               | 295/1568 [00:55<03:38,  5.82it/s]16 03:22:24 Save the image 00224D_flip.png
 19%|███████▎                               | 296/1568 [00:55<03:39,  5.80it/s]16 03:22:24 Save the image 00225D.png
 19%|███████▍                               | 297/1568 [00:55<03:37,  5.83it/s]16 03:22:24 Save the image 00225D_flip.png
 19%|███████▍                               | 298/1568 [00:55<03:33,  5.95it/s]16 03:22:25 Save the image 00226D.png
 19%|███████▍                               | 299/1568 [00:55<03:35,  5.88it/s]16 03:22:25 Save the image 00226D_flip.png
 19%|███████▍                               | 300/1568 [00:56<03:36,  5.86it/s]16 03:22:25 Save the image 00227D.png
 19%|███████▍                               | 301/1568 [00:56<03:36,  5.85it/s]16 03:22:25 Save the image 00227D_flip.png
 19%|███████▌                               | 302/1568 [00:56<03:38,  5.79it/s]16 03:22:25 Save the image 00228D.png
 19%|███████▌                               | 303/1568 [00:56<03:38,  5.79it/s]16 03:22:25 Save the image 00228D_flip.png
 19%|███████▌                               | 304/1568 [00:56<03:38,  5.78it/s]16 03:22:26 Save the image 00229D.png
 19%|███████▌                               | 305/1568 [00:56<03:36,  5.82it/s]16 03:22:26 Save the image 00229D_flip.png
 20%|███████▌                               | 306/1568 [00:57<03:31,  5.96it/s]16 03:22:26 Save the image 00230D.png
 20%|███████▋                               | 307/1568 [00:57<03:33,  5.90it/s]16 03:22:26 Save the image 00230D_flip.png
 20%|███████▋                               | 308/1568 [00:57<03:34,  5.87it/s]16 03:22:26 Save the image 00231D.png
 20%|███████▋                               | 309/1568 [00:57<03:34,  5.88it/s]16 03:22:26 Save the image 00231D_flip.png
 20%|███████▋                               | 310/1568 [00:57<03:37,  5.78it/s]16 03:22:27 Save the image 00232D.png
 20%|███████▋                               | 311/1568 [00:57<03:38,  5.76it/s]16 03:22:27 Save the image 00232D_flip.png
 20%|███████▊                               | 312/1568 [00:58<03:37,  5.78it/s]16 03:22:27 Save the image 00233D.png

 20%|███████▊                               | 313/1568 [00:58<03:34,  5.86it/s]16 03:22:27 Save the image 00233D_flip.png
 20%|███████▊                               | 314/1568 [00:58<03:28,  6.02it/s]16 03:22:27 Save the image 00234D.png
 20%|███████▊                               | 315/1568 [00:58<03:31,  5.94it/s]16 03:22:27 Save the image 00234D_flip.png
 20%|███████▊                               | 316/1568 [00:58<03:32,  5.91it/s]16 03:22:28 Save the image 00235D.png
 20%|███████▉                               | 317/1568 [00:58<03:32,  5.89it/s]16 03:22:28 Save the image 00235D_flip.png
 20%|███████▉                               | 318/1568 [00:59<03:33,  5.85it/s]16 03:22:28 Save the image 00236D.png
 20%|███████▉                               | 319/1568 [00:59<03:34,  5.82it/s]16 03:22:28 Save the image 00236D_flip.png
 20%|███████▉                               | 320/1568 [00:59<03:34,  5.81it/s]16 03:22:28 Save the image 00237D.png
 20%|███████▉                               | 321/1568 [00:59<03:33,  5.84it/s]16 03:22:28 Save the image 00237D_flip.png
 21%|████████                               | 322/1568 [00:59<03:29,  5.94it/s]16 03:22:29 Save the image 00238D.png
 21%|████████                               | 323/1568 [00:59<03:32,  5.85it/s]16 03:22:29 Save the image 00238D_flip.png
 21%|████████                               | 324/1568 [01:00<03:32,  5.85it/s]16 03:22:29 Save the image 00239D.png
 21%|████████                               | 325/1568 [01:00<03:32,  5.84it/s]16 03:22:29 Save the image 00239D_flip.png
 21%|████████                               | 326/1568 [01:00<03:33,  5.82it/s]16 03:22:29 Save the image 00240D.png
 21%|████████▏                              | 327/1568 [01:00<03:33,  5.81it/s]16 03:22:29 Save the image 00240D_flip.png
 21%|████████▏                              | 328/1568 [01:00<03:34,  5.79it/s]16 03:22:30 Save the image 00241D.png
 21%|████████▏                              | 329/1568 [01:01<03:32,  5.83it/s]16 03:22:30 Save the image 00241D_flip.png
 21%|████████▏                              | 330/1568 [01:01<03:26,  6.00it/s]16 03:22:30 Save the image 00242D.png
 21%|████████▏                              | 331/1568 [01:01<03:29,  5.89it/s]16 03:22:30 Save the image 00242D_flip.png
 21%|████████▎                              | 332/1568 [01:01<03:31,  5.85it/s]16 03:22:30 Save the image 00243D.png
 21%|████████▎                              | 333/1568 [01:01<03:32,  5.81it/s]16 03:22:30 Save the image 00243D_flip.png
 21%|████████▎                              | 334/1568 [01:01<03:32,  5.80it/s]16 03:22:31 Save the image 00244D.png
 21%|████████▎                              | 335/1568 [01:02<03:32,  5.79it/s]16 03:22:31 Save the image 00244D_flip.png
 21%|████████▎                              | 336/1568 [01:02<03:33,  5.78it/s]16 03:22:31 Save the image 00245D.png
 21%|████████▍                              | 337/1568 [01:02<03:31,  5.83it/s]16 03:22:31 Save the image 00245D_flip.png
 22%|████████▍                              | 338/1568 [01:02<03:28,  5.91it/s]16 03:22:31 Save the image 00246D.png
 22%|████████▍                              | 339/1568 [01:02<03:32,  5.79it/s]16 03:22:32 Save the image 00246D_flip.png
 22%|████████▍                              | 340/1568 [01:02<03:35,  5.69it/s]16 03:22:32 Save the image 00247D.png
 22%|████████▍                              | 341/1568 [01:03<03:37,  5.63it/s]16 03:22:32 Save the image 00247D_flip.png
 22%|████████▌                              | 342/1568 [01:03<03:36,  5.66it/s]16 03:22:32 Save the image 00248D.png
 22%|████████▌                              | 343/1568 [01:03<03:35,  5.69it/s]16 03:22:32 Save the image 00248D_flip.png
 22%|████████▌                              | 344/1568 [01:03<03:34,  5.71it/s]16 03:22:32 Save the image 00249D.png
 22%|████████▌                              | 345/1568 [01:03<03:33,  5.73it/s]16 03:22:33 Save the image 00249D_flip.png
 22%|████████▌                              | 346/1568 [01:03<03:21,  6.08it/s]16 03:22:33 Save the image 00250D.png
 22%|████████▋                              | 347/1568 [01:04<03:24,  5.97it/s]16 03:22:33 Save the image 00250D_flip.png
 22%|████████▋                              | 348/1568 [01:04<03:25,  5.93it/s]16 03:22:33 Save the image 00251D.png
 22%|████████▋                              | 349/1568 [01:04<03:26,  5.91it/s]16 03:22:33 Save the image 00251D_flip.png
 22%|████████▋                              | 350/1568 [01:04<03:27,  5.87it/s]16 03:22:33 Save the image 00252D.png
 22%|████████▋                              | 351/1568 [01:04<03:28,  5.84it/s]16 03:22:34 Save the image 00252D_flip.png
 22%|████████▊                              | 352/1568 [01:04<03:29,  5.81it/s]16 03:22:34 Save the image 00253D.png
 23%|████████▊                              | 353/1568 [01:05<03:26,  5.88it/s]16 03:22:34 Save the image 00253D_flip.png
 23%|████████▊                              | 354/1568 [01:05<03:21,  6.03it/s]16 03:22:34 Save the image 00254D.png
 23%|████████▊                              | 355/1568 [01:05<03:25,  5.91it/s]16 03:22:34 Save the image 00254D_flip.png
 23%|████████▊                              | 356/1568 [01:05<03:26,  5.88it/s]16 03:22:34 Save the image 00255D.png
 23%|████████▉                              | 357/1568 [01:05<03:25,  5.88it/s]16 03:22:35 Save the image 00255D_flip.png
 23%|████████▉                              | 358/1568 [01:05<03:26,  5.86it/s]16 03:22:35 Save the image 00256D.png
 23%|████████▉                              | 359/1568 [01:06<03:27,  5.84it/s]16 03:22:35 Save the image 00256D_flip.png
 23%|████████▉                              | 360/1568 [01:06<03:27,  5.83it/s]16 03:22:35 Save the image 00257D.png
 23%|████████▉                              | 361/1568 [01:06<03:25,  5.86it/s]16 03:22:35 Save the image 00257D_flip.png
 23%|█████████                              | 362/1568 [01:06<03:21,  5.97it/s]16 03:22:35 Save the image 00258D.png
 23%|█████████                              | 363/1568 [01:06<03:24,  5.90it/s]16 03:22:36 Save the image 00258D_flip.png
 23%|█████████                              | 364/1568 [01:07<03:25,  5.87it/s]16 03:22:36 Save the image 00259D.png
 23%|█████████                              | 365/1568 [01:07<03:25,  5.86it/s]16 03:22:36 Save the image 00259D_flip.png
 23%|█████████                              | 366/1568 [01:07<03:25,  5.84it/s]16 03:22:36 Save the image 00260D.png
 23%|█████████▏                             | 367/1568 [01:07<03:26,  5.82it/s]16 03:22:36 Save the image 00260D_flip.png
 23%|█████████▏                             | 368/1568 [01:07<03:26,  5.81it/s]16 03:22:36 Save the image 00261D.png
 24%|█████████▏                             | 369/1568 [01:07<03:25,  5.85it/s]16 03:22:37 Save the image 00261D_flip.png
 24%|█████████▏                             | 370/1568 [01:08<03:21,  5.94it/s]16 03:22:37 Save the image 00262D.png
 24%|█████████▏                             | 371/1568 [01:08<03:23,  5.87it/s]16 03:22:37 Save the image 00262D_flip.png
 24%|█████████▎                             | 372/1568 [01:08<03:24,  5.85it/s]16 03:22:37 Save the image 00263D.png
 24%|█████████▎                             | 373/1568 [01:08<03:24,  5.84it/s]16 03:22:37 Save the image 00263D_flip.png
 24%|█████████▎                             | 374/1568 [01:08<03:25,  5.82it/s]16 03:22:38 Save the image 00264D.png
 24%|█████████▎                             | 375/1568 [01:08<03:27,  5.76it/s]16 03:22:38 Save the image 00264D_flip.png
 24%|█████████▎                             | 376/1568 [01:09<03:28,  5.71it/s]16 03:22:38 Save the image 00265D.png

 24%|█████████▍                             | 377/1568 [01:09<03:25,  5.80it/s]16 03:22:38 Save the image 00265D_flip.png
 24%|█████████▍                             | 378/1568 [01:09<03:22,  5.88it/s]16 03:22:38 Save the image 00266D.png
 24%|█████████▍                             | 379/1568 [01:09<03:24,  5.81it/s]16 03:22:38 Save the image 00266D_flip.png
 24%|█████████▍                             | 380/1568 [01:09<03:25,  5.78it/s]16 03:22:39 Save the image 00267D.png
 24%|█████████▍                             | 381/1568 [01:09<03:26,  5.74it/s]16 03:22:39 Save the image 00267D_flip.png
 24%|█████████▌                             | 382/1568 [01:10<03:27,  5.71it/s]16 03:22:39 Save the image 00268D.png
 24%|█████████▌                             | 383/1568 [01:10<03:27,  5.71it/s]16 03:22:39 Save the image 00268D_flip.png
 24%|█████████▌                             | 384/1568 [01:10<03:26,  5.73it/s]16 03:22:39 Save the image 00269D.png
 25%|█████████▌                             | 385/1568 [01:10<03:24,  5.77it/s]16 03:22:39 Save the image 00269D_flip.png
 25%|█████████▌                             | 386/1568 [01:10<03:25,  5.74it/s]16 03:22:40 Save the image 00270D.png
 25%|█████████▋                             | 387/1568 [01:10<03:26,  5.73it/s]16 03:22:40 Save the image 00270D_flip.png
 25%|█████████▋                             | 388/1568 [01:11<03:26,  5.71it/s]16 03:22:40 Save the image 00271D.png
 25%|█████████▋                             | 389/1568 [01:11<03:26,  5.71it/s]16 03:22:40 Save the image 00271D_flip.png
 25%|█████████▋                             | 390/1568 [01:11<03:27,  5.68it/s]16 03:22:40 Save the image 00272D.png
 25%|█████████▋                             | 391/1568 [01:11<03:26,  5.69it/s]16 03:22:40 Save the image 00272D_flip.png
 25%|█████████▊                             | 392/1568 [01:11<03:27,  5.66it/s]16 03:22:41 Save the image 00273D.png
 25%|█████████▊                             | 393/1568 [01:12<03:24,  5.75it/s]16 03:22:41 Save the image 00273D_flip.png
 25%|█████████▊                             | 394/1568 [01:12<03:26,  5.70it/s]16 03:22:41 Save the image 00274D.png
 25%|█████████▊                             | 395/1568 [01:12<03:25,  5.70it/s]16 03:22:41 Save the image 00274D_flip.png
 25%|█████████▊                             | 396/1568 [01:12<03:26,  5.67it/s]16 03:22:41 Save the image 00275D.png
 25%|█████████▊                             | 397/1568 [01:12<03:25,  5.69it/s]16 03:22:42 Save the image 00275D_flip.png
 25%|█████████▉                             | 398/1568 [01:12<03:28,  5.62it/s]16 03:22:42 Save the image 00276D.png
 25%|█████████▉                             | 399/1568 [01:13<03:26,  5.66it/s]16 03:22:42 Save the image 00276D_flip.png
 26%|█████████▉                             | 400/1568 [01:13<03:25,  5.68it/s]16 03:22:42 Save the image 00277D.png
 26%|█████████▉                             | 401/1568 [01:13<03:22,  5.76it/s]16 03:22:42 Save the image 00277D_flip.png
 26%|█████████▉                             | 402/1568 [01:13<03:19,  5.85it/s]16 03:22:42 Save the image 00278D.png
 26%|██████████                             | 403/1568 [01:13<03:20,  5.82it/s]16 03:22:43 Save the image 00278D_flip.png
 26%|██████████                             | 404/1568 [01:13<03:20,  5.82it/s]16 03:22:43 Save the image 00279D.png
 26%|██████████                             | 405/1568 [01:14<03:22,  5.74it/s]16 03:22:43 Save the image 00279D_flip.png
 26%|██████████                             | 406/1568 [01:14<03:24,  5.67it/s]16 03:22:43 Save the image 00280D.png
 26%|██████████                             | 407/1568 [01:14<03:25,  5.65it/s]16 03:22:43 Save the image 00280D_flip.png
 26%|██████████▏                            | 408/1568 [01:14<03:24,  5.67it/s]16 03:22:43 Save the image 00281D.png
 26%|██████████▏                            | 409/1568 [01:14<03:22,  5.73it/s]16 03:22:44 Save the image 00281D_flip.png
 26%|██████████▏                            | 410/1568 [01:15<03:19,  5.81it/s]16 03:22:44 Save the image 00282D.png
 26%|██████████▏                            | 411/1568 [01:15<03:20,  5.76it/s]16 03:22:44 Save the image 00282D_flip.png
 26%|██████████▏                            | 412/1568 [01:15<03:19,  5.78it/s]16 03:22:44 Save the image 00283D.png
 26%|██████████▎                            | 413/1568 [01:15<03:19,  5.79it/s]16 03:22:44 Save the image 00283D_flip.png
 26%|██████████▎                            | 414/1568 [01:15<03:19,  5.78it/s]16 03:22:44 Save the image 00284D.png
 26%|██████████▎                            | 415/1568 [01:15<03:19,  5.77it/s]16 03:22:45 Save the image 00284D_flip.png
 27%|██████████▎                            | 416/1568 [01:16<03:19,  5.77it/s]16 03:22:45 Save the image 00285D.png
 27%|██████████▎                            | 417/1568 [01:16<03:17,  5.84it/s]16 03:22:45 Save the image 00285D_flip.png
 27%|██████████▍                            | 418/1568 [01:16<03:13,  5.94it/s]16 03:22:45 Save the image 00286D.png
 27%|██████████▍                            | 419/1568 [01:16<03:17,  5.82it/s]16 03:22:45 Save the image 00286D_flip.png
 27%|██████████▍                            | 420/1568 [01:16<03:19,  5.74it/s]16 03:22:46 Save the image 00287D.png
 27%|██████████▍                            | 421/1568 [01:16<03:19,  5.76it/s]16 03:22:46 Save the image 00287D_flip.png
 27%|██████████▍                            | 422/1568 [01:17<03:20,  5.70it/s]16 03:22:46 Save the image 00288D.png
 27%|██████████▌                            | 423/1568 [01:17<03:22,  5.65it/s]16 03:22:46 Save the image 00288D_flip.png
 27%|██████████▌                            | 424/1568 [01:17<03:22,  5.65it/s]16 03:22:46 Save the image 00289D.png
 27%|██████████▌                            | 425/1568 [01:17<03:20,  5.70it/s]16 03:22:46 Save the image 00289D_flip.png
 27%|██████████▌                            | 426/1568 [01:17<03:20,  5.70it/s]16 03:22:47 Save the image 00290D.png
 27%|██████████▌                            | 427/1568 [01:17<03:20,  5.69it/s]16 03:22:47 Save the image 00290D_flip.png
 27%|██████████▋                            | 428/1568 [01:18<03:19,  5.72it/s]16 03:22:47 Save the image 00291D.png
 27%|██████████▋                            | 429/1568 [01:18<03:17,  5.75it/s]16 03:22:47 Save the image 00291D_flip.png
 27%|██████████▋                            | 430/1568 [01:18<03:18,  5.73it/s]16 03:22:47 Save the image 00292D.png
 27%|██████████▋                            | 431/1568 [01:18<03:20,  5.68it/s]16 03:22:47 Save the image 00292D_flip.png
 28%|██████████▋                            | 432/1568 [01:18<03:20,  5.66it/s]16 03:22:48 Save the image 00293D.png
 28%|██████████▊                            | 433/1568 [01:19<03:18,  5.72it/s]16 03:22:48 Save the image 00293D_flip.png
 28%|██████████▊                            | 434/1568 [01:19<03:17,  5.75it/s]16 03:22:48 Save the image 00294D.png
 28%|██████████▊                            | 435/1568 [01:19<03:17,  5.75it/s]16 03:22:48 Save the image 00294D_flip.png
 28%|██████████▊                            | 436/1568 [01:19<03:18,  5.70it/s]16 03:22:48 Save the image 00295D.png
 28%|██████████▊                            | 437/1568 [01:19<03:18,  5.70it/s]16 03:22:49 Save the image 00295D_flip.png
 28%|██████████▉                            | 438/1568 [01:19<03:20,  5.63it/s]16 03:22:49 Save the image 00296D.png
 28%|██████████▉                            | 439/1568 [01:20<03:20,  5.63it/s]16 03:22:49 Save the image 00296D_flip.png
 28%|██████████▉                            | 440/1568 [01:20<03:18,  5.67it/s]16 03:22:49 Save the image 00297D.png

 28%|██████████▉                            | 441/1568 [01:20<03:16,  5.74it/s]16 03:22:49 Save the image 00297D_flip.png
 28%|██████████▉                            | 442/1568 [01:20<03:12,  5.84it/s]16 03:22:49 Save the image 00298D.png
 28%|███████████                            | 443/1568 [01:20<03:13,  5.82it/s]16 03:22:50 Save the image 00298D_flip.png
 28%|███████████                            | 444/1568 [01:20<03:13,  5.82it/s]16 03:22:50 Save the image 00299D.png
 28%|███████████                            | 445/1568 [01:21<03:12,  5.83it/s]16 03:22:50 Save the image 00299D_flip.png
 28%|███████████                            | 446/1568 [01:21<03:12,  5.82it/s]16 03:22:50 Save the image 00300D.png
 29%|███████████                            | 447/1568 [01:21<03:13,  5.80it/s]16 03:22:50 Save the image 00300D_flip.png
 29%|███████████▏                           | 448/1568 [01:21<03:13,  5.79it/s]16 03:22:50 Save the image 00301D.png
 29%|███████████▏                           | 449/1568 [01:21<03:13,  5.78it/s]16 03:22:51 Save the image 00301D_flip.png
 29%|███████████▏                           | 450/1568 [01:21<03:11,  5.83it/s]16 03:22:51 Save the image 00302D.png
 29%|███████████▏                           | 451/1568 [01:22<03:13,  5.76it/s]16 03:22:51 Save the image 00302D_flip.png
 29%|███████████▏                           | 452/1568 [01:22<03:13,  5.76it/s]16 03:22:51 Save the image 00303D.png
 29%|███████████▎                           | 453/1568 [01:22<03:12,  5.78it/s]16 03:22:51 Save the image 00303D_flip.png
 29%|███████████▎                           | 454/1568 [01:22<03:13,  5.75it/s]16 03:22:51 Save the image 00304D.png
 29%|███████████▎                           | 455/1568 [01:22<03:14,  5.72it/s]16 03:22:52 Save the image 00304D_flip.png
 29%|███████████▎                           | 456/1568 [01:23<03:13,  5.74it/s]16 03:22:52 Save the image 00305D.png
 29%|███████████▎                           | 457/1568 [01:23<03:12,  5.79it/s]16 03:22:52 Save the image 00305D_flip.png
 29%|███████████▍                           | 458/1568 [01:23<03:10,  5.83it/s]16 03:22:52 Save the image 00306D.png
 29%|███████████▍                           | 459/1568 [01:23<03:10,  5.81it/s]16 03:22:52 Save the image 00306D_flip.png
 29%|███████████▍                           | 460/1568 [01:23<03:12,  5.76it/s]16 03:22:52 Save the image 00307D.png
 29%|███████████▍                           | 461/1568 [01:23<03:12,  5.75it/s]16 03:22:53 Save the image 00307D_flip.png
 29%|███████████▍                           | 462/1568 [01:24<03:12,  5.74it/s]16 03:22:53 Save the image 00308D.png
 30%|███████████▌                           | 463/1568 [01:24<03:12,  5.75it/s]16 03:22:53 Save the image 00308D_flip.png
 30%|███████████▌                           | 464/1568 [01:24<03:11,  5.77it/s]16 03:22:53 Save the image 00309D.png
 30%|███████████▌                           | 465/1568 [01:24<03:09,  5.81it/s]16 03:22:53 Save the image 00309D_flip.png
 30%|███████████▌                           | 466/1568 [01:24<03:07,  5.87it/s]16 03:22:54 Save the image 00310D.png
 30%|███████████▌                           | 467/1568 [01:24<03:09,  5.81it/s]16 03:22:54 Save the image 00310D_flip.png
 30%|███████████▋                           | 468/1568 [01:25<03:09,  5.81it/s]16 03:22:54 Save the image 00311D.png
 30%|███████████▋                           | 469/1568 [01:25<03:09,  5.81it/s]16 03:22:54 Save the image 00311D_flip.png
 30%|███████████▋                           | 470/1568 [01:25<03:09,  5.80it/s]16 03:22:54 Save the image 00312D.png
 30%|███████████▋                           | 471/1568 [01:25<03:11,  5.72it/s]16 03:22:54 Save the image 00312D_flip.png
 30%|███████████▋                           | 472/1568 [01:25<03:11,  5.73it/s]16 03:22:55 Save the image 00313D.png
 30%|███████████▊                           | 473/1568 [01:25<03:09,  5.78it/s]16 03:22:55 Save the image 00313D_flip.png
 30%|███████████▊                           | 474/1568 [01:26<03:03,  5.97it/s]16 03:22:55 Save the image 00314D.png
 30%|███████████▊                           | 475/1568 [01:26<03:04,  5.91it/s]16 03:22:55 Save the image 00314D_flip.png
 30%|███████████▊                           | 476/1568 [01:26<03:05,  5.88it/s]16 03:22:55 Save the image 00315D.png
 30%|███████████▊                           | 477/1568 [01:26<03:06,  5.85it/s]16 03:22:55 Save the image 00315D_flip.png
 30%|███████████▉                           | 478/1568 [01:26<03:07,  5.82it/s]16 03:22:56 Save the image 00316D.png
 31%|███████████▉                           | 479/1568 [01:26<03:07,  5.81it/s]16 03:22:56 Save the image 00316D_flip.png
 31%|███████████▉                           | 480/1568 [01:27<03:07,  5.81it/s]16 03:22:56 Save the image 00317D.png
 31%|███████████▉                           | 481/1568 [01:27<03:06,  5.84it/s]16 03:22:56 Save the image 00317D_flip.png
 31%|███████████▉                           | 482/1568 [01:27<03:02,  5.97it/s]16 03:22:56 Save the image 00318D.png
 31%|████████████                           | 483/1568 [01:27<03:04,  5.88it/s]16 03:22:56 Save the image 00318D_flip.png
 31%|████████████                           | 484/1568 [01:27<03:04,  5.86it/s]16 03:22:57 Save the image 00319D.png
 31%|████████████                           | 485/1568 [01:27<03:05,  5.83it/s]16 03:22:57 Save the image 00319D_flip.png
 31%|████████████                           | 486/1568 [01:28<03:06,  5.80it/s]16 03:22:57 Save the image 00320D.png
 31%|████████████                           | 487/1568 [01:28<03:06,  5.79it/s]16 03:22:57 Save the image 00320D_flip.png
 31%|████████████▏                          | 488/1568 [01:28<03:06,  5.79it/s]16 03:22:57 Save the image 00321D.png
 31%|████████████▏                          | 489/1568 [01:28<03:05,  5.83it/s]16 03:22:57 Save the image 00321D_flip.png
 31%|████████████▏                          | 490/1568 [01:28<03:00,  5.99it/s]16 03:22:58 Save the image 00322D.png
 31%|████████████▏                          | 491/1568 [01:29<03:02,  5.90it/s]16 03:22:58 Save the image 00322D_flip.png
 31%|████████████▏                          | 492/1568 [01:29<03:03,  5.87it/s]16 03:22:58 Save the image 00323D.png
 31%|████████████▎                          | 493/1568 [01:29<03:03,  5.84it/s]16 03:22:58 Save the image 00323D_flip.png
 32%|████████████▎                          | 494/1568 [01:29<03:05,  5.79it/s]16 03:22:58 Save the image 00324D.png
 32%|████████████▎                          | 495/1568 [01:29<03:05,  5.79it/s]16 03:22:58 Save the image 00324D_flip.png
 32%|████████████▎                          | 496/1568 [01:29<03:06,  5.75it/s]16 03:22:59 Save the image 00325D.png
 32%|████████████▎                          | 497/1568 [01:30<03:04,  5.80it/s]16 03:22:59 Save the image 00325D_flip.png
 32%|████████████▍                          | 498/1568 [01:30<02:57,  6.02it/s]16 03:22:59 Save the image 00326D.png
 32%|████████████▍                          | 499/1568 [01:30<03:00,  5.93it/s]16 03:22:59 Save the image 00326D_flip.png
 32%|████████████▍                          | 500/1568 [01:30<03:01,  5.88it/s]16 03:22:59 Save the image 00327D.png
 32%|████████████▍                          | 501/1568 [01:30<03:01,  5.89it/s]16 03:23:00 Save the image 00327D_flip.png
 32%|████████████▍                          | 502/1568 [01:30<03:04,  5.79it/s]16 03:23:00 Save the image 00328D.png
 32%|████████████▌                          | 503/1568 [01:31<03:04,  5.78it/s]16 03:23:00 Save the image 00328D_flip.png
 32%|████████████▌                          | 504/1568 [01:31<03:03,  5.78it/s]16 03:23:00 Save the image 00329D.png

 32%|████████████▌                          | 505/1568 [01:31<03:02,  5.82it/s]16 03:23:00 Save the image 00329D_flip.png
 32%|████████████▌                          | 506/1568 [01:31<02:57,  5.97it/s]16 03:23:00 Save the image 00330D.png
 32%|████████████▌                          | 507/1568 [01:31<03:00,  5.87it/s]16 03:23:01 Save the image 00330D_flip.png
 32%|████████████▋                          | 508/1568 [01:31<03:01,  5.84it/s]16 03:23:01 Save the image 00331D.png
 32%|████████████▋                          | 509/1568 [01:32<03:01,  5.85it/s]16 03:23:01 Save the image 00331D_flip.png
 33%|████████████▋                          | 510/1568 [01:32<03:01,  5.83it/s]16 03:23:01 Save the image 00332D.png
 33%|████████████▋                          | 511/1568 [01:32<03:01,  5.81it/s]16 03:23:01 Save the image 00332D_flip.png
 33%|████████████▋                          | 512/1568 [01:32<03:01,  5.81it/s]16 03:23:01 Save the image 00333D.png
 33%|████████████▊                          | 513/1568 [01:32<02:59,  5.87it/s]16 03:23:02 Save the image 00333D_flip.png
 33%|████████████▊                          | 514/1568 [01:32<02:56,  5.97it/s]16 03:23:02 Save the image 00334D.png
 33%|████████████▊                          | 515/1568 [01:33<02:57,  5.92it/s]16 03:23:02 Save the image 00334D_flip.png
 33%|████████████▊                          | 516/1568 [01:33<02:58,  5.88it/s]16 03:23:02 Save the image 00335D.png
 33%|████████████▊                          | 517/1568 [01:33<02:59,  5.87it/s]16 03:23:02 Save the image 00335D_flip.png
 33%|████████████▉                          | 518/1568 [01:33<03:00,  5.81it/s]16 03:23:02 Save the image 00336D.png
 33%|████████████▉                          | 519/1568 [01:33<03:01,  5.79it/s]16 03:23:03 Save the image 00336D_flip.png
 33%|████████████▉                          | 520/1568 [01:33<03:01,  5.78it/s]16 03:23:03 Save the image 00337D.png
 33%|████████████▉                          | 521/1568 [01:34<03:00,  5.82it/s]16 03:23:03 Save the image 00337D_flip.png
 33%|████████████▉                          | 522/1568 [01:34<02:56,  5.93it/s]16 03:23:03 Save the image 00338D.png
 33%|█████████████                          | 523/1568 [01:34<02:58,  5.86it/s]16 03:23:03 Save the image 00338D_flip.png
 33%|█████████████                          | 524/1568 [01:34<02:58,  5.84it/s]16 03:23:03 Save the image 00339D.png
 33%|█████████████                          | 525/1568 [01:34<02:59,  5.82it/s]16 03:23:04 Save the image 00339D_flip.png
 34%|█████████████                          | 526/1568 [01:35<03:00,  5.76it/s]16 03:23:04 Save the image 00340D.png
 34%|█████████████                          | 527/1568 [01:35<03:00,  5.76it/s]16 03:23:04 Save the image 00340D_flip.png
 34%|█████████████▏                         | 528/1568 [01:35<03:00,  5.77it/s]16 03:23:04 Save the image 00341D.png
 34%|█████████████▏                         | 529/1568 [01:35<02:58,  5.82it/s]16 03:23:04 Save the image 00341D_flip.png
 34%|█████████████▏                         | 530/1568 [01:35<02:53,  5.98it/s]16 03:23:04 Save the image 00342D.png
 34%|█████████████▏                         | 531/1568 [01:35<02:55,  5.92it/s]16 03:23:05 Save the image 00342D_flip.png
 34%|█████████████▏                         | 532/1568 [01:36<02:55,  5.89it/s]16 03:23:05 Save the image 00343D.png
 34%|█████████████▎                         | 533/1568 [01:36<02:56,  5.88it/s]16 03:23:05 Save the image 00343D_flip.png
 34%|█████████████▎                         | 534/1568 [01:36<02:57,  5.82it/s]16 03:23:05 Save the image 00344D.png
 34%|█████████████▎                         | 535/1568 [01:36<02:58,  5.80it/s]16 03:23:05 Save the image 00344D_flip.png
 34%|█████████████▎                         | 536/1568 [01:36<02:58,  5.79it/s]16 03:23:05 Save the image 00345D.png
 34%|█████████████▎                         | 537/1568 [01:36<02:56,  5.83it/s]16 03:23:06 Save the image 00345D_flip.png
 34%|█████████████▍                         | 538/1568 [01:37<02:53,  5.95it/s]16 03:23:06 Save the image 00346D.png
 34%|█████████████▍                         | 539/1568 [01:37<02:54,  5.89it/s]16 03:23:06 Save the image 00346D_flip.png
 34%|█████████████▍                         | 540/1568 [01:37<02:55,  5.86it/s]16 03:23:06 Save the image 00347D.png
 35%|█████████████▍                         | 541/1568 [01:37<02:55,  5.85it/s]16 03:23:06 Save the image 00347D_flip.png
 35%|█████████████▍                         | 542/1568 [01:37<02:56,  5.80it/s]16 03:23:07 Save the image 00348D.png
 35%|█████████████▌                         | 543/1568 [01:37<02:56,  5.80it/s]16 03:23:07 Save the image 00348D_flip.png
 35%|█████████████▌                         | 544/1568 [01:38<02:57,  5.76it/s]16 03:23:07 Save the image 00349D.png
 35%|█████████████▌                         | 545/1568 [01:38<02:55,  5.81it/s]16 03:23:07 Save the image 00349D_flip.png
 35%|█████████████▌                         | 546/1568 [01:38<02:53,  5.89it/s]16 03:23:07 Save the image 00350D.png
 35%|█████████████▌                         | 547/1568 [01:38<02:54,  5.85it/s]16 03:23:07 Save the image 00350D_flip.png
 35%|█████████████▋                         | 548/1568 [01:38<02:54,  5.84it/s]16 03:23:08 Save the image 00351D.png
 35%|█████████████▋                         | 549/1568 [01:38<02:54,  5.83it/s]16 03:23:08 Save the image 00351D_flip.png
 35%|█████████████▋                         | 550/1568 [01:39<02:55,  5.79it/s]16 03:23:08 Save the image 00352D.png
 35%|█████████████▋                         | 551/1568 [01:39<02:55,  5.78it/s]16 03:23:08 Save the image 00352D_flip.png
 35%|█████████████▋                         | 552/1568 [01:39<02:56,  5.77it/s]16 03:23:08 Save the image 00353D.png
 35%|█████████████▊                         | 553/1568 [01:39<02:54,  5.81it/s]16 03:23:08 Save the image 00353D_flip.png
 35%|█████████████▊                         | 554/1568 [01:39<02:50,  5.93it/s]16 03:23:09 Save the image 00354D.png
 35%|█████████████▊                         | 555/1568 [01:39<02:52,  5.86it/s]16 03:23:09 Save the image 00354D_flip.png
 35%|█████████████▊                         | 556/1568 [01:40<02:53,  5.82it/s]16 03:23:09 Save the image 00355D.png
 36%|█████████████▊                         | 557/1568 [01:40<02:53,  5.82it/s]16 03:23:09 Save the image 00355D_flip.png
 36%|█████████████▉                         | 558/1568 [01:40<02:54,  5.78it/s]16 03:23:09 Save the image 00356D.png
 36%|█████████████▉                         | 559/1568 [01:40<02:54,  5.77it/s]16 03:23:09 Save the image 00356D_flip.png
 36%|█████████████▉                         | 560/1568 [01:40<02:54,  5.76it/s]16 03:23:10 Save the image 00357D.png
 36%|█████████████▉                         | 561/1568 [01:41<02:53,  5.81it/s]16 03:23:10 Save the image 00357D_flip.png
 36%|█████████████▉                         | 562/1568 [01:41<02:49,  5.94it/s]16 03:23:10 Save the image 00358D.png
 36%|██████████████                         | 563/1568 [01:41<02:51,  5.86it/s]16 03:23:10 Save the image 00358D_flip.png
 36%|██████████████                         | 564/1568 [01:41<02:51,  5.84it/s]16 03:23:10 Save the image 00359D.png
 36%|██████████████                         | 565/1568 [01:41<02:51,  5.83it/s]16 03:23:10 Save the image 00359D_flip.png
 36%|██████████████                         | 566/1568 [01:41<02:53,  5.79it/s]16 03:23:11 Save the image 00360D.png
 36%|██████████████                         | 567/1568 [01:42<02:52,  5.79it/s]16 03:23:11 Save the image 00360D_flip.png
 36%|██████████████▏                        | 568/1568 [01:42<02:52,  5.80it/s]16 03:23:11 Save the image 00361D.png

 36%|██████████████▏                        | 569/1568 [01:42<02:50,  5.87it/s]16 03:23:11 Save the image 00361D_flip.png
 36%|██████████████▏                        | 570/1568 [01:42<02:46,  5.98it/s]16 03:23:11 Save the image 00362D.png
 36%|██████████████▏                        | 571/1568 [01:42<02:49,  5.89it/s]16 03:23:11 Save the image 00362D_flip.png
 36%|██████████████▏                        | 572/1568 [01:42<02:49,  5.86it/s]16 03:23:12 Save the image 00363D.png
 37%|██████████████▎                        | 573/1568 [01:43<02:51,  5.79it/s]16 03:23:12 Save the image 00363D_flip.png
 37%|██████████████▎                        | 574/1568 [01:43<02:51,  5.79it/s]16 03:23:12 Save the image 00364D.png
 37%|██████████████▎                        | 575/1568 [01:43<02:52,  5.75it/s]16 03:23:12 Save the image 00364D_flip.png
 37%|██████████████▎                        | 576/1568 [01:43<02:52,  5.75it/s]16 03:23:12 Save the image 00365D.png
 37%|██████████████▎                        | 577/1568 [01:43<02:49,  5.83it/s]16 03:23:13 Save the image 00365D_flip.png
 37%|██████████████▍                        | 578/1568 [01:43<02:43,  6.05it/s]16 03:23:13 Save the image 00366D.png
 37%|██████████████▍                        | 579/1568 [01:44<02:46,  5.95it/s]16 03:23:13 Save the image 00366D_flip.png
 37%|██████████████▍                        | 580/1568 [01:44<02:47,  5.91it/s]16 03:23:13 Save the image 00367D.png
 37%|██████████████▍                        | 581/1568 [01:44<02:47,  5.90it/s]16 03:23:13 Save the image 00367D_flip.png
 37%|██████████████▍                        | 582/1568 [01:44<02:48,  5.86it/s]16 03:23:13 Save the image 00368D.png
 37%|██████████████▌                        | 583/1568 [01:44<02:48,  5.83it/s]16 03:23:14 Save the image 00368D_flip.png
 37%|██████████████▌                        | 584/1568 [01:44<02:49,  5.81it/s]16 03:23:14 Save the image 00369D.png
 37%|██████████████▌                        | 585/1568 [01:45<02:48,  5.85it/s]16 03:23:14 Save the image 00369D_flip.png
 37%|██████████████▌                        | 586/1568 [01:45<02:44,  5.96it/s]16 03:23:14 Save the image 00370D.png
 37%|██████████████▌                        | 587/1568 [01:45<02:46,  5.89it/s]16 03:23:14 Save the image 00370D_flip.png
 38%|██████████████▋                        | 588/1568 [01:45<02:47,  5.86it/s]16 03:23:14 Save the image 00371D.png
 38%|██████████████▋                        | 589/1568 [01:45<02:48,  5.82it/s]16 03:23:15 Save the image 00371D_flip.png
 38%|██████████████▋                        | 590/1568 [01:45<02:48,  5.79it/s]16 03:23:15 Save the image 00372D.png
 38%|██████████████▋                        | 591/1568 [01:46<02:48,  5.78it/s]16 03:23:15 Save the image 00372D_flip.png
 38%|██████████████▋                        | 592/1568 [01:46<02:48,  5.78it/s]16 03:23:15 Save the image 00373D.png
 38%|██████████████▋                        | 593/1568 [01:46<02:46,  5.85it/s]16 03:23:15 Save the image 00373D_flip.png
 38%|██████████████▊                        | 594/1568 [01:46<02:42,  5.99it/s]16 03:23:15 Save the image 00374D.png
 38%|██████████████▊                        | 595/1568 [01:46<02:44,  5.90it/s]16 03:23:16 Save the image 00374D_flip.png
 38%|██████████████▊                        | 596/1568 [01:46<02:45,  5.87it/s]16 03:23:16 Save the image 00375D.png
 38%|██████████████▊                        | 597/1568 [01:47<02:45,  5.85it/s]16 03:23:16 Save the image 00375D_flip.png
 38%|██████████████▊                        | 598/1568 [01:47<02:46,  5.83it/s]16 03:23:16 Save the image 00376D.png
 38%|██████████████▉                        | 599/1568 [01:47<02:46,  5.81it/s]16 03:23:16 Save the image 00376D_flip.png
 38%|██████████████▉                        | 600/1568 [01:47<02:46,  5.80it/s]16 03:23:16 Save the image 00377D.png
 38%|██████████████▉                        | 601/1568 [01:47<02:45,  5.83it/s]16 03:23:17 Save the image 00377D_flip.png
 38%|██████████████▉                        | 602/1568 [01:47<02:42,  5.94it/s]16 03:23:17 Save the image 00378D.png
 38%|██████████████▉                        | 603/1568 [01:48<02:44,  5.85it/s]16 03:23:17 Save the image 00378D_flip.png
 39%|███████████████                        | 604/1568 [01:48<02:45,  5.84it/s]16 03:23:17 Save the image 00379D.png
 39%|███████████████                        | 605/1568 [01:48<02:44,  5.84it/s]16 03:23:17 Save the image 00379D_flip.png
 39%|███████████████                        | 606/1568 [01:48<02:45,  5.80it/s]16 03:23:17 Save the image 00380D.png
 39%|███████████████                        | 607/1568 [01:48<02:45,  5.80it/s]16 03:23:18 Save the image 00380D_flip.png
 39%|███████████████                        | 608/1568 [01:49<02:45,  5.79it/s]16 03:23:18 Save the image 00381D.png
 39%|███████████████▏                       | 609/1568 [01:49<02:44,  5.83it/s]16 03:23:18 Save the image 00381D_flip.png
 39%|███████████████▏                       | 610/1568 [01:49<02:40,  5.97it/s]16 03:23:18 Save the image 00382D.png
 39%|███████████████▏                       | 611/1568 [01:49<02:43,  5.86it/s]16 03:23:18 Save the image 00382D_flip.png
 39%|███████████████▏                       | 612/1568 [01:49<02:43,  5.85it/s]16 03:23:18 Save the image 00383D.png
 39%|███████████████▏                       | 613/1568 [01:49<02:43,  5.84it/s]16 03:23:19 Save the image 00383D_flip.png
 39%|███████████████▎                       | 614/1568 [01:50<02:44,  5.80it/s]16 03:23:19 Save the image 00384D.png
 39%|███████████████▎                       | 615/1568 [01:50<02:44,  5.79it/s]16 03:23:19 Save the image 00384D_flip.png
 39%|███████████████▎                       | 616/1568 [01:50<02:44,  5.80it/s]16 03:23:19 Save the image 00385D.png
 39%|███████████████▎                       | 617/1568 [01:50<02:43,  5.83it/s]16 03:23:19 Save the image 00385D_flip.png
 39%|███████████████▎                       | 618/1568 [01:50<02:38,  5.99it/s]16 03:23:20 Save the image 00386D.png
 39%|███████████████▍                       | 619/1568 [01:50<02:40,  5.92it/s]16 03:23:20 Save the image 00386D_flip.png
 40%|███████████████▍                       | 620/1568 [01:51<02:41,  5.89it/s]16 03:23:20 Save the image 00387D.png
 40%|███████████████▍                       | 621/1568 [01:51<02:41,  5.85it/s]16 03:23:20 Save the image 00387D_flip.png
 40%|███████████████▍                       | 622/1568 [01:51<02:42,  5.82it/s]16 03:23:20 Save the image 00388D.png
 40%|███████████████▍                       | 623/1568 [01:51<02:42,  5.81it/s]16 03:23:20 Save the image 00388D_flip.png
 40%|███████████████▌                       | 624/1568 [01:51<02:43,  5.79it/s]16 03:23:21 Save the image 00389D.png
 40%|███████████████▌                       | 625/1568 [01:51<02:40,  5.86it/s]16 03:23:21 Save the image 00389D_flip.png
 40%|███████████████▌                       | 626/1568 [01:52<02:37,  5.99it/s]16 03:23:21 Save the image 00390D.png
 40%|███████████████▌                       | 627/1568 [01:52<02:39,  5.91it/s]16 03:23:21 Save the image 00390D_flip.png
 40%|███████████████▌                       | 628/1568 [01:52<02:40,  5.87it/s]16 03:23:21 Save the image 00391D.png
 40%|███████████████▋                       | 629/1568 [01:52<02:40,  5.84it/s]16 03:23:21 Save the image 00391D_flip.png
 40%|███████████████▋                       | 630/1568 [01:52<02:41,  5.79it/s]16 03:23:22 Save the image 00392D.png
 40%|███████████████▋                       | 631/1568 [01:52<02:41,  5.79it/s]16 03:23:22 Save the image 00392D_flip.png
 40%|███████████████▋                       | 632/1568 [01:53<02:43,  5.71it/s]16 03:23:22 Save the image 00393D.png

 40%|███████████████▋                       | 633/1568 [01:53<02:41,  5.80it/s]16 03:23:22 Save the image 00393D_flip.png
 40%|███████████████▊                       | 634/1568 [01:53<02:35,  6.02it/s]16 03:23:22 Save the image 00394D.png
 40%|███████████████▊                       | 635/1568 [01:53<02:37,  5.93it/s]16 03:23:22 Save the image 00394D_flip.png
 41%|███████████████▊                       | 636/1568 [01:53<02:38,  5.89it/s]16 03:23:23 Save the image 00395D.png
 41%|███████████████▊                       | 637/1568 [01:53<02:38,  5.89it/s]16 03:23:23 Save the image 00395D_flip.png
 41%|███████████████▊                       | 638/1568 [01:54<02:40,  5.80it/s]16 03:23:23 Save the image 00396D.png
 41%|███████████████▉                       | 639/1568 [01:54<02:41,  5.74it/s]16 03:23:23 Save the image 00396D_flip.png
 41%|███████████████▉                       | 640/1568 [01:54<02:42,  5.72it/s]16 03:23:23 Save the image 00397D.png
 41%|███████████████▉                       | 641/1568 [01:54<02:40,  5.78it/s]16 03:23:23 Save the image 00397D_flip.png
 41%|███████████████▉                       | 642/1568 [01:54<02:37,  5.87it/s]16 03:23:24 Save the image 00398D.png
 41%|███████████████▉                       | 643/1568 [01:55<02:39,  5.80it/s]16 03:23:24 Save the image 00398D_flip.png
 41%|████████████████                       | 644/1568 [01:55<02:39,  5.81it/s]16 03:23:24 Save the image 00399D.png
 41%|████████████████                       | 645/1568 [01:55<02:39,  5.80it/s]16 03:23:24 Save the image 00399D_flip.png
 41%|████████████████                       | 646/1568 [01:55<02:39,  5.78it/s]16 03:23:24 Save the image 00400D.png
 41%|████████████████                       | 647/1568 [01:55<02:39,  5.77it/s]16 03:23:25 Save the image 00400D_flip.png
 41%|████████████████                       | 648/1568 [01:55<02:41,  5.71it/s]16 03:23:25 Save the image 00401D.png
 41%|████████████████▏                      | 649/1568 [01:56<02:40,  5.73it/s]16 03:23:25 Save the image 00401D_flip.png
 41%|████████████████▏                      | 650/1568 [01:56<02:35,  5.89it/s]16 03:23:25 Save the image 00402D.png
 42%|████████████████▏                      | 651/1568 [01:56<02:38,  5.78it/s]16 03:23:25 Save the image 00402D_flip.png
 42%|████████████████▏                      | 652/1568 [01:56<02:38,  5.79it/s]16 03:23:25 Save the image 00403D.png
 42%|████████████████▏                      | 653/1568 [01:56<02:39,  5.74it/s]16 03:23:26 Save the image 00403D_flip.png
 42%|████████████████▎                      | 654/1568 [01:56<02:40,  5.71it/s]16 03:23:26 Save the image 00404D.png
 42%|████████████████▎                      | 655/1568 [01:57<02:40,  5.70it/s]16 03:23:26 Save the image 00404D_flip.png
 42%|████████████████▎                      | 656/1568 [01:57<02:40,  5.67it/s]16 03:23:26 Save the image 00405D.png
 42%|████████████████▎                      | 657/1568 [01:57<02:38,  5.73it/s]16 03:23:26 Save the image 00405D_flip.png
 42%|████████████████▎                      | 658/1568 [01:57<02:39,  5.71it/s]16 03:23:26 Save the image 00406D.png
 42%|████████████████▍                      | 659/1568 [01:57<02:39,  5.72it/s]16 03:23:27 Save the image 00406D_flip.png
 42%|████████████████▍                      | 660/1568 [01:57<02:40,  5.67it/s]16 03:23:27 Save the image 00407D.png
 42%|████████████████▍                      | 661/1568 [01:58<02:38,  5.71it/s]16 03:23:27 Save the image 00407D_flip.png
 42%|████████████████▍                      | 662/1568 [01:58<02:40,  5.63it/s]16 03:23:27 Save the image 00408D.png
 42%|████████████████▍                      | 663/1568 [01:58<02:39,  5.67it/s]16 03:23:27 Save the image 00408D_flip.png
 42%|████████████████▌                      | 664/1568 [01:58<02:40,  5.63it/s]16 03:23:27 Save the image 00409D.png
 42%|████████████████▌                      | 665/1568 [01:58<02:38,  5.70it/s]16 03:23:28 Save the image 00409D_flip.png
 42%|████████████████▌                      | 666/1568 [01:59<02:35,  5.78it/s]16 03:23:28 Save the image 00410D.png
 43%|████████████████▌                      | 667/1568 [01:59<02:37,  5.72it/s]16 03:23:28 Save the image 00410D_flip.png
 43%|████████████████▌                      | 668/1568 [01:59<02:36,  5.74it/s]16 03:23:28 Save the image 00411D.png
 43%|████████████████▋                      | 669/1568 [01:59<02:35,  5.79it/s]16 03:23:28 Save the image 00411D_flip.png
 43%|████████████████▋                      | 670/1568 [01:59<02:36,  5.75it/s]16 03:23:29 Save the image 00412D.png
 43%|████████████████▋                      | 671/1568 [01:59<02:35,  5.76it/s]16 03:23:29 Save the image 00412D_flip.png
 43%|████████████████▋                      | 672/1568 [02:00<02:35,  5.76it/s]16 03:23:29 Save the image 00413D.png
 43%|████████████████▋                      | 673/1568 [02:00<02:34,  5.80it/s]16 03:23:29 Save the image 00413D_flip.png
 43%|████████████████▊                      | 674/1568 [02:00<02:29,  5.97it/s]16 03:23:29 Save the image 00414D.png
 43%|████████████████▊                      | 675/1568 [02:00<02:30,  5.92it/s]16 03:23:29 Save the image 00414D_flip.png
 43%|████████████████▊                      | 676/1568 [02:00<02:31,  5.88it/s]16 03:23:30 Save the image 00415D.png
 43%|████████████████▊                      | 677/1568 [02:00<02:32,  5.86it/s]16 03:23:30 Save the image 00415D_flip.png
 43%|████████████████▊                      | 678/1568 [02:01<02:32,  5.82it/s]16 03:23:30 Save the image 00416D.png
 43%|████████████████▉                      | 679/1568 [02:01<02:33,  5.80it/s]16 03:23:30 Save the image 00416D_flip.png
 43%|████████████████▉                      | 680/1568 [02:01<02:33,  5.79it/s]16 03:23:30 Save the image 00417D.png
 43%|████████████████▉                      | 681/1568 [02:01<02:32,  5.83it/s]16 03:23:30 Save the image 00417D_flip.png
 43%|████████████████▉                      | 682/1568 [02:01<02:28,  5.95it/s]16 03:23:31 Save the image 00418D.png
 44%|████████████████▉                      | 683/1568 [02:01<02:31,  5.85it/s]16 03:23:31 Save the image 00418D_flip.png
 44%|█████████████████                      | 684/1568 [02:02<02:31,  5.83it/s]16 03:23:31 Save the image 00419D.png
 44%|█████████████████                      | 685/1568 [02:02<02:31,  5.84it/s]16 03:23:31 Save the image 00419D_flip.png
 44%|█████████████████                      | 686/1568 [02:02<02:32,  5.79it/s]16 03:23:31 Save the image 00420D.png
 44%|█████████████████                      | 687/1568 [02:02<02:32,  5.78it/s]16 03:23:31 Save the image 00420D_flip.png
 44%|█████████████████                      | 688/1568 [02:02<02:32,  5.77it/s]16 03:23:32 Save the image 00421D.png
 44%|█████████████████▏                     | 689/1568 [02:02<02:31,  5.81it/s]16 03:23:32 Save the image 00421D_flip.png
 44%|█████████████████▏                     | 690/1568 [02:03<02:27,  5.94it/s]16 03:23:32 Save the image 00422D.png
 44%|█████████████████▏                     | 691/1568 [02:03<02:29,  5.88it/s]16 03:23:32 Save the image 00422D_flip.png
 44%|█████████████████▏                     | 692/1568 [02:03<02:29,  5.85it/s]16 03:23:32 Save the image 00423D.png
 44%|█████████████████▏                     | 693/1568 [02:03<02:29,  5.85it/s]16 03:23:32 Save the image 00423D_flip.png
 44%|█████████████████▎                     | 694/1568 [02:03<02:30,  5.82it/s]16 03:23:33 Save the image 00424D.png
 44%|█████████████████▎                     | 695/1568 [02:04<02:30,  5.80it/s]16 03:23:33 Save the image 00424D_flip.png
 44%|█████████████████▎                     | 696/1568 [02:04<02:30,  5.79it/s]16 03:23:33 Save the image 00425D.png

 44%|█████████████████▎                     | 697/1568 [02:04<02:31,  5.76it/s]16 03:23:33 Save the image 00425D_flip.png
 45%|█████████████████▎                     | 698/1568 [02:04<02:26,  5.96it/s]16 03:23:33 Save the image 00426D.png
 45%|█████████████████▍                     | 699/1568 [02:04<02:27,  5.89it/s]16 03:23:33 Save the image 00426D_flip.png
 45%|█████████████████▍                     | 700/1568 [02:04<02:28,  5.86it/s]16 03:23:34 Save the image 00427D.png
 45%|█████████████████▍                     | 701/1568 [02:05<02:28,  5.86it/s]16 03:23:34 Save the image 00427D_flip.png
 45%|█████████████████▍                     | 702/1568 [02:05<02:28,  5.83it/s]16 03:23:34 Save the image 00428D.png
 45%|█████████████████▍                     | 703/1568 [02:05<02:28,  5.82it/s]16 03:23:34 Save the image 00428D_flip.png
 45%|█████████████████▌                     | 704/1568 [02:05<02:28,  5.80it/s]16 03:23:34 Save the image 00429D.png
 45%|█████████████████▌                     | 705/1568 [02:05<02:27,  5.87it/s]16 03:23:34 Save the image 00429D_flip.png
 45%|█████████████████▌                     | 706/1568 [02:05<02:24,  5.97it/s]16 03:23:35 Save the image 00430D.png
 45%|█████████████████▌                     | 707/1568 [02:06<02:25,  5.91it/s]16 03:23:35 Save the image 00430D_flip.png
 45%|█████████████████▌                     | 708/1568 [02:06<02:26,  5.88it/s]16 03:23:35 Save the image 00431D.png
 45%|█████████████████▋                     | 709/1568 [02:06<02:26,  5.87it/s]16 03:23:35 Save the image 00431D_flip.png
 45%|█████████████████▋                     | 710/1568 [02:06<02:27,  5.81it/s]16 03:23:35 Save the image 00432D.png
 45%|█████████████████▋                     | 711/1568 [02:06<02:27,  5.79it/s]16 03:23:36 Save the image 00432D_flip.png
 45%|█████████████████▋                     | 712/1568 [02:06<02:27,  5.79it/s]16 03:23:36 Save the image 00433D.png
 45%|█████████████████▋                     | 713/1568 [02:07<02:26,  5.83it/s]16 03:23:36 Save the image 00433D_flip.png
 46%|█████████████████▊                     | 714/1568 [02:07<02:23,  5.95it/s]16 03:23:36 Save the image 00434D.png
 46%|█████████████████▊                     | 715/1568 [02:07<02:24,  5.90it/s]16 03:23:36 Save the image 00434D_flip.png
 46%|█████████████████▊                     | 716/1568 [02:07<02:24,  5.88it/s]16 03:23:36 Save the image 00435D.png
 46%|█████████████████▊                     | 717/1568 [02:07<02:25,  5.85it/s]16 03:23:37 Save the image 00435D_flip.png
 46%|█████████████████▊                     | 718/1568 [02:07<02:25,  5.83it/s]16 03:23:37 Save the image 00436D.png
 46%|█████████████████▉                     | 719/1568 [02:08<02:26,  5.81it/s]16 03:23:37 Save the image 00436D_flip.png
 46%|█████████████████▉                     | 720/1568 [02:08<02:26,  5.80it/s]16 03:23:37 Save the image 00437D.png
 46%|█████████████████▉                     | 721/1568 [02:08<02:25,  5.82it/s]16 03:23:37 Save the image 00437D_flip.png
 46%|█████████████████▉                     | 722/1568 [02:08<02:22,  5.94it/s]16 03:23:37 Save the image 00438D.png
 46%|█████████████████▉                     | 723/1568 [02:08<02:23,  5.89it/s]16 03:23:38 Save the image 00438D_flip.png
 46%|██████████████████                     | 724/1568 [02:08<02:23,  5.86it/s]16 03:23:38 Save the image 00439D.png
 46%|██████████████████                     | 725/1568 [02:09<02:23,  5.86it/s]16 03:23:38 Save the image 00439D_flip.png
 46%|██████████████████                     | 726/1568 [02:09<02:24,  5.83it/s]16 03:23:38 Save the image 00440D.png
 46%|██████████████████                     | 727/1568 [02:09<02:26,  5.74it/s]16 03:23:38 Save the image 00440D_flip.png
 46%|██████████████████                     | 728/1568 [02:09<02:26,  5.72it/s]16 03:23:38 Save the image 00441D.png
 46%|██████████████████▏                    | 729/1568 [02:09<02:25,  5.78it/s]16 03:23:39 Save the image 00441D_flip.png
 47%|██████████████████▏                    | 730/1568 [02:09<02:20,  5.97it/s]16 03:23:39 Save the image 00442D.png
 47%|██████████████████▏                    | 731/1568 [02:10<02:21,  5.90it/s]16 03:23:39 Save the image 00442D_flip.png
 47%|██████████████████▏                    | 732/1568 [02:10<02:22,  5.87it/s]16 03:23:39 Save the image 00443D.png
 47%|██████████████████▏                    | 733/1568 [02:10<02:22,  5.85it/s]16 03:23:39 Save the image 00443D_flip.png
 47%|██████████████████▎                    | 734/1568 [02:10<02:23,  5.82it/s]16 03:23:39 Save the image 00444D.png
 47%|██████████████████▎                    | 735/1568 [02:10<02:24,  5.77it/s]16 03:23:40 Save the image 00444D_flip.png
 47%|██████████████████▎                    | 736/1568 [02:11<02:24,  5.76it/s]16 03:23:40 Save the image 00445D.png
 47%|██████████████████▎                    | 737/1568 [02:11<02:23,  5.79it/s]16 03:23:40 Save the image 00445D_flip.png
 47%|██████████████████▎                    | 738/1568 [02:11<02:22,  5.84it/s]16 03:23:40 Save the image 00446D.png
 47%|██████████████████▍                    | 739/1568 [02:11<02:23,  5.78it/s]16 03:23:40 Save the image 00446D_flip.png
 47%|██████████████████▍                    | 740/1568 [02:11<02:23,  5.79it/s]16 03:23:41 Save the image 00447D.png
 47%|██████████████████▍                    | 741/1568 [02:11<02:22,  5.81it/s]16 03:23:41 Save the image 00447D_flip.png
 47%|██████████████████▍                    | 742/1568 [02:12<02:23,  5.77it/s]16 03:23:41 Save the image 00448D.png
 47%|██████████████████▍                    | 743/1568 [02:12<02:23,  5.75it/s]16 03:23:41 Save the image 00448D_flip.png
 47%|██████████████████▌                    | 744/1568 [02:12<02:22,  5.77it/s]16 03:23:41 Save the image 00449D.png
 48%|██████████████████▌                    | 745/1568 [02:12<02:21,  5.81it/s]16 03:23:41 Save the image 00449D_flip.png
 48%|██████████████████▌                    | 746/1568 [02:12<02:20,  5.85it/s]16 03:23:42 Save the image 00450D.png
 48%|██████████████████▌                    | 747/1568 [02:12<02:21,  5.81it/s]16 03:23:42 Save the image 00450D_flip.png
 48%|██████████████████▌                    | 748/1568 [02:13<02:21,  5.81it/s]16 03:23:42 Save the image 00451D.png
 48%|██████████████████▋                    | 749/1568 [02:13<02:20,  5.82it/s]16 03:23:42 Save the image 00451D_flip.png
 48%|██████████████████▋                    | 750/1568 [02:13<02:21,  5.80it/s]16 03:23:42 Save the image 00452D.png
 48%|██████████████████▋                    | 751/1568 [02:13<02:20,  5.80it/s]16 03:23:42 Save the image 00452D_flip.png
 48%|██████████████████▋                    | 752/1568 [02:13<02:20,  5.80it/s]16 03:23:43 Save the image 00453D.png
 48%|██████████████████▋                    | 753/1568 [02:13<02:19,  5.84it/s]16 03:23:43 Save the image 00453D_flip.png
 48%|██████████████████▊                    | 754/1568 [02:14<02:16,  5.97it/s]16 03:23:43 Save the image 00454D.png
 48%|██████████████████▊                    | 755/1568 [02:14<02:17,  5.90it/s]16 03:23:43 Save the image 00454D_flip.png
 48%|██████████████████▊                    | 756/1568 [02:14<02:18,  5.88it/s]16 03:23:43 Save the image 00455D.png
 48%|██████████████████▊                    | 757/1568 [02:14<02:20,  5.78it/s]16 03:23:43 Save the image 00455D_flip.png
 48%|██████████████████▊                    | 758/1568 [02:14<02:23,  5.65it/s]16 03:23:44 Save the image 00456D.png
 48%|██████████████████▉                    | 759/1568 [02:15<02:22,  5.69it/s]16 03:23:44 Save the image 00456D_flip.png
 48%|██████████████████▉                    | 760/1568 [02:15<02:21,  5.71it/s]16 03:23:44 Save the image 00457D.png

 49%|██████████████████▉                    | 761/1568 [02:15<02:20,  5.72it/s]16 03:23:44 Save the image 00457D_flip.png
 49%|██████████████████▉                    | 762/1568 [02:15<02:11,  6.12it/s]16 03:23:44 Save the image 00458D.png
 49%|██████████████████▉                    | 763/1568 [02:15<02:14,  5.98it/s]16 03:23:44 Save the image 00458D_flip.png
 49%|███████████████████                    | 764/1568 [02:15<02:15,  5.94it/s]16 03:23:45 Save the image 00459D.png
 49%|███████████████████                    | 765/1568 [02:16<02:15,  5.92it/s]16 03:23:45 Save the image 00459D_flip.png
 49%|███████████████████                    | 766/1568 [02:16<02:17,  5.84it/s]16 03:23:45 Save the image 00460D.png
 49%|███████████████████                    | 767/1568 [02:16<02:17,  5.82it/s]16 03:23:45 Save the image 00460D_flip.png
 49%|███████████████████                    | 768/1568 [02:16<02:17,  5.81it/s]16 03:23:45 Save the image 00461D.png
 49%|███████████████████▏                   | 769/1568 [02:16<02:18,  5.79it/s]16 03:23:45 Save the image 00461D_flip.png
 49%|███████████████████▏                   | 770/1568 [02:16<02:10,  6.13it/s]16 03:23:46 Save the image 00462D.png
 49%|███████████████████▏                   | 771/1568 [02:17<02:13,  5.98it/s]16 03:23:46 Save the image 00462D_flip.png
 49%|███████████████████▏                   | 772/1568 [02:17<02:14,  5.93it/s]16 03:23:46 Save the image 00463D.png
 49%|███████████████████▏                   | 773/1568 [02:17<02:14,  5.92it/s]16 03:23:46 Save the image 00463D_flip.png
 49%|███████████████████▎                   | 774/1568 [02:17<02:15,  5.87it/s]16 03:23:46 Save the image 00464D.png
 49%|███████████████████▎                   | 775/1568 [02:17<02:15,  5.84it/s]16 03:23:46 Save the image 00464D_flip.png
 49%|███████████████████▎                   | 776/1568 [02:17<02:15,  5.82it/s]16 03:23:47 Save the image 00465D.png
 50%|███████████████████▎                   | 777/1568 [02:18<02:15,  5.86it/s]16 03:23:47 Save the image 00465D_flip.png
 50%|███████████████████▎                   | 778/1568 [02:18<02:11,  6.02it/s]16 03:23:47 Save the image 00466D.png
 50%|███████████████████▍                   | 779/1568 [02:18<02:13,  5.91it/s]16 03:23:47 Save the image 00466D_flip.png
 50%|███████████████████▍                   | 780/1568 [02:18<02:13,  5.89it/s]16 03:23:47 Save the image 00478D.png
 50%|███████████████████▍                   | 781/1568 [02:18<02:13,  5.88it/s]16 03:23:48 Save the image 00478D_flip.png
 50%|███████████████████▍                   | 782/1568 [02:18<02:15,  5.80it/s]16 03:23:48 Save the image 00479D.png
 50%|███████████████████▍                   | 783/1568 [02:19<02:15,  5.80it/s]16 03:23:48 Save the image 00479D_flip.png
 50%|███████████████████▌                   | 784/1568 [02:19<02:15,  5.80it/s]16 03:23:48 Save the image 00480D.png
 50%|███████████████████▌                   | 785/1568 [02:19<02:13,  5.84it/s]16 03:23:48 Save the image 00480D_flip.png
 50%|███████████████████▌                   | 786/1568 [02:19<02:09,  6.02it/s]16 03:23:48 Save the image 00481D.png
 50%|███████████████████▌                   | 787/1568 [02:19<02:11,  5.94it/s]16 03:23:49 Save the image 00481D_flip.png
 50%|███████████████████▌                   | 788/1568 [02:19<02:12,  5.89it/s]16 03:23:49 Save the image 00482D.png
 50%|███████████████████▌                   | 789/1568 [02:20<02:13,  5.85it/s]16 03:23:49 Save the image 00482D_flip.png
 50%|███████████████████▋                   | 790/1568 [02:20<02:13,  5.81it/s]16 03:23:49 Save the image 00483D.png
 50%|███████████████████▋                   | 791/1568 [02:20<02:13,  5.80it/s]16 03:23:49 Save the image 00483D_flip.png
 51%|███████████████████▋                   | 792/1568 [02:20<02:14,  5.79it/s]16 03:23:49 Save the image 00484D.png
 51%|███████████████████▋                   | 793/1568 [02:20<02:12,  5.87it/s]16 03:23:50 Save the image 00484D_flip.png
 51%|███████████████████▋                   | 794/1568 [02:20<02:08,  6.04it/s]16 03:23:50 Save the image 00485D.png
 51%|███████████████████▊                   | 795/1568 [02:21<02:09,  5.95it/s]16 03:23:50 Save the image 00485D_flip.png
 51%|███████████████████▊                   | 796/1568 [02:21<02:10,  5.92it/s]16 03:23:50 Save the image 00486D.png
 51%|███████████████████▊                   | 797/1568 [02:21<02:10,  5.90it/s]16 03:23:50 Save the image 00486D_flip.png
 51%|███████████████████▊                   | 798/1568 [02:21<02:11,  5.86it/s]16 03:23:50 Save the image 00487D.png
 51%|███████████████████▊                   | 799/1568 [02:21<02:11,  5.83it/s]16 03:23:51 Save the image 00487D_flip.png
 51%|███████████████████▉                   | 800/1568 [02:21<02:12,  5.81it/s]16 03:23:51 Save the image 00488D.png
 51%|███████████████████▉                   | 801/1568 [02:22<02:11,  5.84it/s]16 03:23:51 Save the image 00488D_flip.png
 51%|███████████████████▉                   | 802/1568 [02:22<02:08,  5.97it/s]16 03:23:51 Save the image 00489D.png
 51%|███████████████████▉                   | 803/1568 [02:22<02:10,  5.87it/s]16 03:23:51 Save the image 00489D_flip.png
 51%|███████████████████▉                   | 804/1568 [02:22<02:10,  5.85it/s]16 03:23:51 Save the image 00490D.png
 51%|████████████████████                   | 805/1568 [02:22<02:11,  5.80it/s]16 03:23:52 Save the image 00490D_flip.png
 51%|████████████████████                   | 806/1568 [02:22<02:12,  5.74it/s]16 03:23:52 Save the image 00491D.png
 51%|████████████████████                   | 807/1568 [02:23<02:12,  5.73it/s]16 03:23:52 Save the image 00491D_flip.png
 52%|████████████████████                   | 808/1568 [02:23<02:13,  5.71it/s]16 03:23:52 Save the image 00492D.png
 52%|████████████████████                   | 809/1568 [02:23<02:12,  5.74it/s]16 03:23:52 Save the image 00492D_flip.png
 52%|████████████████████▏                  | 810/1568 [02:23<02:09,  5.84it/s]16 03:23:52 Save the image 00493D.png
 52%|████████████████████▏                  | 811/1568 [02:23<02:10,  5.80it/s]16 03:23:53 Save the image 00493D_flip.png
 52%|████████████████████▏                  | 812/1568 [02:24<02:12,  5.69it/s]16 03:23:53 Save the image 00494D.png
 52%|████████████████████▏                  | 813/1568 [02:24<02:11,  5.73it/s]16 03:23:53 Save the image 00494D_flip.png
 52%|████████████████████▏                  | 814/1568 [02:24<02:12,  5.71it/s]16 03:23:53 Save the image 00495D.png
 52%|████████████████████▎                  | 815/1568 [02:24<02:12,  5.69it/s]16 03:23:53 Save the image 00495D_flip.png
 52%|████████████████████▎                  | 816/1568 [02:24<02:12,  5.66it/s]16 03:23:54 Save the image 00496D.png
 52%|████████████████████▎                  | 817/1568 [02:24<02:11,  5.72it/s]16 03:23:54 Save the image 00496D_flip.png
 52%|████████████████████▎                  | 818/1568 [02:25<02:10,  5.77it/s]16 03:23:54 Save the image 00497D.png
 52%|████████████████████▎                  | 819/1568 [02:25<02:10,  5.72it/s]16 03:23:54 Save the image 00497D_flip.png
 52%|████████████████████▍                  | 820/1568 [02:25<02:11,  5.71it/s]16 03:23:54 Save the image 00003N.png
 52%|████████████████████▍                  | 821/1568 [02:25<02:10,  5.72it/s]16 03:23:54 Save the image 00003N_flip.png
 52%|████████████████████▍                  | 822/1568 [02:25<02:11,  5.68it/s]16 03:23:55 Save the image 00004N.png
 52%|████████████████████▍                  | 823/1568 [02:25<02:11,  5.67it/s]16 03:23:55 Save the image 00004N_flip.png
 53%|████████████████████▍                  | 824/1568 [02:26<02:10,  5.69it/s]16 03:23:55 Save the image 00005N.png

 53%|████████████████████▌                  | 825/1568 [02:26<02:10,  5.71it/s]16 03:23:55 Save the image 00005N_flip.png
 53%|████████████████████▌                  | 826/1568 [02:26<02:08,  5.77it/s]16 03:23:55 Save the image 00006N.png
 53%|████████████████████▌                  | 827/1568 [02:26<02:09,  5.74it/s]16 03:23:55 Save the image 00006N_flip.png
 53%|████████████████████▌                  | 828/1568 [02:26<02:10,  5.68it/s]16 03:23:56 Save the image 00007N.png
 53%|████████████████████▌                  | 829/1568 [02:27<02:09,  5.70it/s]16 03:23:56 Save the image 00007N_flip.png
 53%|████████████████████▋                  | 830/1568 [02:27<02:10,  5.66it/s]16 03:23:56 Save the image 00008N.png
 53%|████████████████████▋                  | 831/1568 [02:27<02:09,  5.70it/s]16 03:23:56 Save the image 00008N_flip.png
 53%|████████████████████▋                  | 832/1568 [02:27<02:10,  5.66it/s]16 03:23:56 Save the image 00009N.png
 53%|████████████████████▋                  | 833/1568 [02:27<02:08,  5.71it/s]16 03:23:57 Save the image 00009N_flip.png
 53%|████████████████████▋                  | 834/1568 [02:27<02:08,  5.73it/s]16 03:23:57 Save the image 00010N.png
 53%|████████████████████▊                  | 835/1568 [02:28<02:08,  5.70it/s]16 03:23:57 Save the image 00010N_flip.png
 53%|████████████████████▊                  | 836/1568 [02:28<02:08,  5.72it/s]16 03:23:57 Save the image 00011N.png
 53%|████████████████████▊                  | 837/1568 [02:28<02:08,  5.68it/s]16 03:23:57 Save the image 00011N_flip.png
 53%|████████████████████▊                  | 838/1568 [02:28<02:08,  5.68it/s]16 03:23:57 Save the image 00012N.png
 54%|████████████████████▊                  | 839/1568 [02:28<02:07,  5.70it/s]16 03:23:58 Save the image 00012N_flip.png
 54%|████████████████████▉                  | 840/1568 [02:28<02:07,  5.72it/s]16 03:23:58 Save the image 00013N.png
 54%|████████████████████▉                  | 841/1568 [02:29<02:05,  5.77it/s]16 03:23:58 Save the image 00013N_flip.png
 54%|████████████████████▉                  | 842/1568 [02:29<02:04,  5.82it/s]16 03:23:58 Save the image 00014N.png
 54%|████████████████████▉                  | 843/1568 [02:29<02:05,  5.77it/s]16 03:23:58 Save the image 00014N_flip.png
 54%|████████████████████▉                  | 844/1568 [02:29<02:06,  5.72it/s]16 03:23:58 Save the image 00015N.png
 54%|█████████████████████                  | 845/1568 [02:29<02:06,  5.73it/s]16 03:23:59 Save the image 00015N_flip.png
 54%|█████████████████████                  | 846/1568 [02:29<02:05,  5.74it/s]16 03:23:59 Save the image 00016N.png
 54%|█████████████████████                  | 847/1568 [02:30<02:06,  5.69it/s]16 03:23:59 Save the image 00016N_flip.png
 54%|█████████████████████                  | 848/1568 [02:30<02:07,  5.64it/s]16 03:23:59 Save the image 00017N.png
 54%|█████████████████████                  | 849/1568 [02:30<02:06,  5.69it/s]16 03:23:59 Save the image 00017N_flip.png
 54%|█████████████████████▏                 | 850/1568 [02:30<02:04,  5.76it/s]16 03:23:59 Save the image 00018N.png
 54%|█████████████████████▏                 | 851/1568 [02:30<02:07,  5.63it/s]16 03:24:00 Save the image 00018N_flip.png
 54%|█████████████████████▏                 | 852/1568 [02:31<02:06,  5.67it/s]16 03:24:00 Save the image 00019N.png
 54%|█████████████████████▏                 | 853/1568 [02:31<02:04,  5.72it/s]16 03:24:00 Save the image 00019N_flip.png
 54%|█████████████████████▏                 | 854/1568 [02:31<02:06,  5.66it/s]16 03:24:00 Save the image 00020N.png
 55%|█████████████████████▎                 | 855/1568 [02:31<02:05,  5.67it/s]16 03:24:00 Save the image 00020N_flip.png
 55%|█████████████████████▎                 | 856/1568 [02:31<02:05,  5.65it/s]16 03:24:01 Save the image 00021N.png
 55%|█████████████████████▎                 | 857/1568 [02:31<02:04,  5.70it/s]16 03:24:01 Save the image 00021N_flip.png
 55%|█████████████████████▎                 | 858/1568 [02:32<02:04,  5.69it/s]16 03:24:01 Save the image 00022N.png
 55%|█████████████████████▎                 | 859/1568 [02:32<02:04,  5.67it/s]16 03:24:01 Save the image 00022N_flip.png
 55%|█████████████████████▍                 | 860/1568 [02:32<02:04,  5.68it/s]16 03:24:01 Save the image 00023N.png
 55%|█████████████████████▍                 | 861/1568 [02:32<02:03,  5.71it/s]16 03:24:01 Save the image 00023N_flip.png
 55%|█████████████████████▍                 | 862/1568 [02:32<02:04,  5.67it/s]16 03:24:02 Save the image 00024N.png
 55%|█████████████████████▍                 | 863/1568 [02:32<02:04,  5.66it/s]16 03:24:02 Save the image 00024N_flip.png
 55%|█████████████████████▍                 | 864/1568 [02:33<02:03,  5.69it/s]16 03:24:02 Save the image 00025N.png
 55%|█████████████████████▌                 | 865/1568 [02:33<02:01,  5.78it/s]16 03:24:02 Save the image 00025N_flip.png
 55%|█████████████████████▌                 | 866/1568 [02:33<02:02,  5.74it/s]16 03:24:02 Save the image 00026N.png
 55%|█████████████████████▌                 | 867/1568 [02:33<02:02,  5.72it/s]16 03:24:02 Save the image 00026N_flip.png
 55%|█████████████████████▌                 | 868/1568 [02:33<02:01,  5.74it/s]16 03:24:03 Save the image 00027N.png
 55%|█████████████████████▌                 | 869/1568 [02:34<02:02,  5.71it/s]16 03:24:03 Save the image 00027N_flip.png
 55%|█████████████████████▋                 | 870/1568 [02:34<02:02,  5.68it/s]16 03:24:03 Save the image 00028N.png
 56%|█████████████████████▋                 | 871/1568 [02:34<02:02,  5.67it/s]16 03:24:03 Save the image 00028N_flip.png
 56%|█████████████████████▋                 | 872/1568 [02:34<02:03,  5.63it/s]16 03:24:03 Save the image 00029N.png
 56%|█████████████████████▋                 | 873/1568 [02:34<02:02,  5.69it/s]16 03:24:04 Save the image 00029N_flip.png
 56%|█████████████████████▋                 | 874/1568 [02:34<02:01,  5.71it/s]16 03:24:04 Save the image 00030N.png
 56%|█████████████████████▊                 | 875/1568 [02:35<02:01,  5.68it/s]16 03:24:04 Save the image 00030N_flip.png
 56%|█████████████████████▊                 | 876/1568 [02:35<02:01,  5.71it/s]16 03:24:04 Save the image 00031N.png
 56%|█████████████████████▊                 | 877/1568 [02:35<02:00,  5.74it/s]16 03:24:04 Save the image 00031N_flip.png
 56%|█████████████████████▊                 | 878/1568 [02:35<02:00,  5.75it/s]16 03:24:04 Save the image 00032N.png
 56%|█████████████████████▊                 | 879/1568 [02:35<01:59,  5.76it/s]16 03:24:05 Save the image 00032N_flip.png
 56%|█████████████████████▉                 | 880/1568 [02:35<02:00,  5.69it/s]16 03:24:05 Save the image 00033N.png
 56%|█████████████████████▉                 | 881/1568 [02:36<01:59,  5.76it/s]16 03:24:05 Save the image 00033N_flip.png
 56%|█████████████████████▉                 | 882/1568 [02:36<01:56,  5.87it/s]16 03:24:05 Save the image 00034N.png
 56%|█████████████████████▉                 | 883/1568 [02:36<01:57,  5.82it/s]16 03:24:05 Save the image 00034N_flip.png
 56%|█████████████████████▉                 | 884/1568 [02:36<01:57,  5.81it/s]16 03:24:05 Save the image 00035N.png
 56%|██████████████████████                 | 885/1568 [02:36<01:57,  5.81it/s]16 03:24:06 Save the image 00035N_flip.png
 57%|██████████████████████                 | 886/1568 [02:36<01:57,  5.79it/s]16 03:24:06 Save the image 00036N.png
 57%|██████████████████████                 | 887/1568 [02:37<01:57,  5.79it/s]16 03:24:06 Save the image 00036N_flip.png
 57%|██████████████████████                 | 888/1568 [02:37<01:57,  5.78it/s]16 03:24:06 Save the image 00037N.png

 57%|██████████████████████                 | 889/1568 [02:37<01:56,  5.82it/s]16 03:24:06 Save the image 00037N_flip.png
 57%|██████████████████████▏                | 890/1568 [02:37<01:54,  5.93it/s]16 03:24:06 Save the image 00038N.png
 57%|██████████████████████▏                | 891/1568 [02:37<01:55,  5.86it/s]16 03:24:07 Save the image 00038N_flip.png
 57%|██████████████████████▏                | 892/1568 [02:38<01:55,  5.84it/s]16 03:24:07 Save the image 00039N.png
 57%|██████████████████████▏                | 893/1568 [02:38<01:54,  5.87it/s]16 03:24:07 Save the image 00039N_flip.png
 57%|██████████████████████▏                | 894/1568 [02:38<01:55,  5.86it/s]16 03:24:07 Save the image 00040N.png
 57%|██████████████████████▎                | 895/1568 [02:38<01:54,  5.86it/s]16 03:24:07 Save the image 00040N_flip.png
 57%|██████████████████████▎                | 896/1568 [02:38<01:55,  5.84it/s]16 03:24:07 Save the image 00041N.png
 57%|██████████████████████▎                | 897/1568 [02:38<01:53,  5.89it/s]16 03:24:08 Save the image 00041N_flip.png
 57%|██████████████████████▎                | 898/1568 [02:39<01:53,  5.88it/s]16 03:24:08 Save the image 00042N.png
 57%|██████████████████████▎                | 899/1568 [02:39<01:54,  5.84it/s]16 03:24:08 Save the image 00042N_flip.png
 57%|██████████████████████▍                | 900/1568 [02:39<01:55,  5.78it/s]16 03:24:08 Save the image 00043N.png
 57%|██████████████████████▍                | 901/1568 [02:39<01:55,  5.77it/s]16 03:24:08 Save the image 00043N_flip.png
 58%|██████████████████████▍                | 902/1568 [02:39<01:55,  5.78it/s]16 03:24:09 Save the image 00044N.png
 58%|██████████████████████▍                | 903/1568 [02:39<01:56,  5.71it/s]16 03:24:09 Save the image 00044N_flip.png
 58%|██████████████████████▍                | 904/1568 [02:40<01:55,  5.76it/s]16 03:24:09 Save the image 00047N.png
 58%|██████████████████████▌                | 905/1568 [02:40<01:55,  5.75it/s]16 03:24:09 Save the image 00047N_flip.png
 58%|██████████████████████▌                | 906/1568 [02:40<01:55,  5.71it/s]16 03:24:09 Save the image 00048N.png
 58%|██████████████████████▌                | 907/1568 [02:40<01:56,  5.68it/s]16 03:24:09 Save the image 00048N_flip.png
 58%|██████████████████████▌                | 908/1568 [02:40<01:56,  5.68it/s]16 03:24:10 Save the image 00049N.png
 58%|██████████████████████▌                | 909/1568 [02:40<01:55,  5.71it/s]16 03:24:10 Save the image 00049N_flip.png
 58%|██████████████████████▋                | 910/1568 [02:41<01:54,  5.72it/s]16 03:24:10 Save the image 00050N.png
 58%|██████████████████████▋                | 911/1568 [02:41<01:54,  5.74it/s]16 03:24:10 Save the image 00050N_flip.png
 58%|██████████████████████▋                | 912/1568 [02:41<01:54,  5.74it/s]16 03:24:10 Save the image 00051N.png
 58%|██████████████████████▋                | 913/1568 [02:41<01:53,  5.79it/s]16 03:24:10 Save the image 00051N_flip.png
 58%|██████████████████████▋                | 914/1568 [02:41<01:53,  5.77it/s]16 03:24:11 Save the image 00052N.png
 58%|██████████████████████▊                | 915/1568 [02:41<01:53,  5.76it/s]16 03:24:11 Save the image 00052N_flip.png
 58%|██████████████████████▊                | 916/1568 [02:42<01:52,  5.79it/s]16 03:24:11 Save the image 00053N.png
 58%|██████████████████████▊                | 917/1568 [02:42<01:52,  5.81it/s]16 03:24:11 Save the image 00053N_flip.png
 59%|██████████████████████▊                | 918/1568 [02:42<01:52,  5.79it/s]16 03:24:11 Save the image 00054N.png
 59%|██████████████████████▊                | 919/1568 [02:42<01:51,  5.81it/s]16 03:24:11 Save the image 00054N_flip.png
 59%|██████████████████████▉                | 920/1568 [02:42<01:51,  5.79it/s]16 03:24:12 Save the image 00678N.png
 59%|██████████████████████▉                | 921/1568 [02:43<01:51,  5.83it/s]16 03:24:12 Save the image 00678N_flip.png
 59%|██████████████████████▉                | 922/1568 [02:43<01:50,  5.85it/s]16 03:24:12 Save the image 00679N.png
 59%|██████████████████████▉                | 923/1568 [02:43<01:50,  5.83it/s]16 03:24:12 Save the image 00679N_flip.png
 59%|██████████████████████▉                | 924/1568 [02:43<01:50,  5.82it/s]16 03:24:12 Save the image 00680N.png
 59%|███████████████████████                | 925/1568 [02:43<01:50,  5.81it/s]16 03:24:13 Save the image 00680N_flip.png
 59%|███████████████████████                | 926/1568 [02:43<01:51,  5.78it/s]16 03:24:13 Save the image 00681N.png
 59%|███████████████████████                | 927/1568 [02:44<01:50,  5.78it/s]16 03:24:13 Save the image 00681N_flip.png
 59%|███████████████████████                | 928/1568 [02:44<01:50,  5.78it/s]16 03:24:13 Save the image 00682N.png
 59%|███████████████████████                | 929/1568 [02:44<01:49,  5.81it/s]16 03:24:13 Save the image 00682N_flip.png
 59%|███████████████████████▏               | 930/1568 [02:44<01:47,  5.94it/s]16 03:24:13 Save the image 00683N.png
 59%|███████████████████████▏               | 931/1568 [02:44<01:48,  5.87it/s]16 03:24:14 Save the image 00683N_flip.png
 59%|███████████████████████▏               | 932/1568 [02:44<01:48,  5.85it/s]16 03:24:14 Save the image 00684N.png
 60%|███████████████████████▏               | 933/1568 [02:45<01:48,  5.84it/s]16 03:24:14 Save the image 00684N_flip.png
 60%|███████████████████████▏               | 934/1568 [02:45<01:48,  5.82it/s]16 03:24:14 Save the image 00685N.png
 60%|███████████████████████▎               | 935/1568 [02:45<01:49,  5.81it/s]16 03:24:14 Save the image 00685N_flip.png
 60%|███████████████████████▎               | 936/1568 [02:45<01:48,  5.80it/s]16 03:24:14 Save the image 00686N.png
 60%|███████████████████████▎               | 937/1568 [02:45<01:47,  5.86it/s]16 03:24:15 Save the image 00686N_flip.png
 60%|███████████████████████▎               | 938/1568 [02:45<01:45,  5.96it/s]16 03:24:15 Save the image 00687N.png
 60%|███████████████████████▎               | 939/1568 [02:46<01:46,  5.89it/s]16 03:24:15 Save the image 00687N_flip.png
 60%|███████████████████████▍               | 940/1568 [02:46<01:47,  5.86it/s]16 03:24:15 Save the image 00688N.png
 60%|███████████████████████▍               | 941/1568 [02:46<01:48,  5.78it/s]16 03:24:15 Save the image 00688N_flip.png
 60%|███████████████████████▍               | 942/1568 [02:46<01:48,  5.76it/s]16 03:24:15 Save the image 00689N.png
 60%|███████████████████████▍               | 943/1568 [02:46<01:48,  5.76it/s]16 03:24:16 Save the image 00689N_flip.png
 60%|███████████████████████▍               | 944/1568 [02:46<01:48,  5.76it/s]16 03:24:16 Save the image 00690N.png
 60%|███████████████████████▌               | 945/1568 [02:47<01:47,  5.81it/s]16 03:24:16 Save the image 00690N_flip.png
 60%|███████████████████████▌               | 946/1568 [02:47<01:43,  6.02it/s]16 03:24:16 Save the image 00691N.png
 60%|███████████████████████▌               | 947/1568 [02:47<01:44,  5.93it/s]16 03:24:16 Save the image 00691N_flip.png
 60%|███████████████████████▌               | 948/1568 [02:47<01:45,  5.89it/s]16 03:24:16 Save the image 00692N.png
 61%|███████████████████████▌               | 949/1568 [02:47<01:45,  5.88it/s]16 03:24:17 Save the image 00692N_flip.png
 61%|███████████████████████▋               | 950/1568 [02:47<01:46,  5.81it/s]16 03:24:17 Save the image 00693N.png
 61%|███████████████████████▋               | 951/1568 [02:48<01:46,  5.80it/s]16 03:24:17 Save the image 00693N_flip.png
 61%|███████████████████████▋               | 952/1568 [02:48<01:46,  5.79it/s]16 03:24:17 Save the image 00694N.png

 61%|███████████████████████▋               | 953/1568 [02:48<01:45,  5.82it/s]16 03:24:17 Save the image 00694N_flip.png
 61%|███████████████████████▋               | 954/1568 [02:48<01:42,  5.97it/s]16 03:24:17 Save the image 00695N.png
 61%|███████████████████████▊               | 955/1568 [02:48<01:43,  5.90it/s]16 03:24:18 Save the image 00695N_flip.png
 61%|███████████████████████▊               | 956/1568 [02:49<01:44,  5.87it/s]16 03:24:18 Save the image 00696N.png
 61%|███████████████████████▊               | 957/1568 [02:49<01:44,  5.87it/s]16 03:24:18 Save the image 00696N_flip.png
 61%|███████████████████████▊               | 958/1568 [02:49<01:44,  5.84it/s]16 03:24:18 Save the image 00697N.png
 61%|███████████████████████▊               | 959/1568 [02:49<01:44,  5.81it/s]16 03:24:18 Save the image 00697N_flip.png
 61%|███████████████████████▉               | 960/1568 [02:49<01:44,  5.80it/s]16 03:24:18 Save the image 00698N.png
 61%|███████████████████████▉               | 961/1568 [02:49<01:43,  5.85it/s]16 03:24:19 Save the image 00698N_flip.png
 61%|███████████████████████▉               | 962/1568 [02:50<01:41,  5.97it/s]16 03:24:19 Save the image 00699N.png
 61%|███████████████████████▉               | 963/1568 [02:50<01:42,  5.89it/s]16 03:24:19 Save the image 00699N_flip.png
 61%|███████████████████████▉               | 964/1568 [02:50<01:42,  5.87it/s]16 03:24:19 Save the image 00700N.png
 62%|████████████████████████               | 965/1568 [02:50<01:43,  5.85it/s]16 03:24:19 Save the image 00700N_flip.png
 62%|████████████████████████               | 966/1568 [02:50<01:43,  5.83it/s]16 03:24:20 Save the image 00701N.png
 62%|████████████████████████               | 967/1568 [02:50<01:43,  5.81it/s]16 03:24:20 Save the image 00701N_flip.png
 62%|████████████████████████               | 968/1568 [02:51<01:43,  5.81it/s]16 03:24:20 Save the image 00702N.png
 62%|████████████████████████               | 969/1568 [02:51<01:42,  5.86it/s]16 03:24:20 Save the image 00702N_flip.png
 62%|████████████████████████▏              | 970/1568 [02:51<01:39,  6.03it/s]16 03:24:20 Save the image 00703N.png
 62%|████████████████████████▏              | 971/1568 [02:51<01:40,  5.93it/s]16 03:24:20 Save the image 00703N_flip.png
 62%|████████████████████████▏              | 972/1568 [02:51<01:41,  5.90it/s]16 03:24:21 Save the image 00704N.png
 62%|████████████████████████▏              | 973/1568 [02:51<01:40,  5.90it/s]16 03:24:21 Save the image 00704N_flip.png
 62%|████████████████████████▏              | 974/1568 [02:52<01:41,  5.86it/s]16 03:24:21 Save the image 00705N.png
 62%|████████████████████████▎              | 975/1568 [02:52<01:41,  5.83it/s]16 03:24:21 Save the image 00705N_flip.png
 62%|████████████████████████▎              | 976/1568 [02:52<01:41,  5.81it/s]16 03:24:21 Save the image 00706N.png
 62%|████████████████████████▎              | 977/1568 [02:52<01:41,  5.85it/s]16 03:24:21 Save the image 00706N_flip.png
 62%|████████████████████████▎              | 978/1568 [02:52<01:39,  5.90it/s]16 03:24:22 Save the image 00707N.png
 62%|████████████████████████▎              | 979/1568 [02:52<01:40,  5.84it/s]16 03:24:22 Save the image 00707N_flip.png
 62%|████████████████████████▍              | 980/1568 [02:53<01:40,  5.82it/s]16 03:24:22 Save the image 00708N.png
 63%|████████████████████████▍              | 981/1568 [02:53<01:40,  5.84it/s]16 03:24:22 Save the image 00708N_flip.png
 63%|████████████████████████▍              | 982/1568 [02:53<01:41,  5.78it/s]16 03:24:22 Save the image 00709N.png
 63%|████████████████████████▍              | 983/1568 [02:53<01:41,  5.78it/s]16 03:24:22 Save the image 00709N_flip.png
 63%|████████████████████████▍              | 984/1568 [02:53<01:41,  5.78it/s]16 03:24:23 Save the image 00710N.png
 63%|████████████████████████▍              | 985/1568 [02:53<01:39,  5.85it/s]16 03:24:23 Save the image 00710N_flip.png
 63%|████████████████████████▌              | 986/1568 [02:54<01:37,  5.97it/s]16 03:24:23 Save the image 00711N.png
 63%|████████████████████████▌              | 987/1568 [02:54<01:38,  5.91it/s]16 03:24:23 Save the image 00711N_flip.png
 63%|████████████████████████▌              | 988/1568 [02:54<01:38,  5.87it/s]16 03:24:23 Save the image 00712N.png
 63%|████████████████████████▌              | 989/1568 [02:54<01:38,  5.86it/s]16 03:24:23 Save the image 00712N_flip.png
 63%|████████████████████████▌              | 990/1568 [02:54<01:39,  5.83it/s]16 03:24:24 Save the image 00713N.png
 63%|████████████████████████▋              | 991/1568 [02:54<01:39,  5.81it/s]16 03:24:24 Save the image 00713N_flip.png
 63%|████████████████████████▋              | 992/1568 [02:55<01:39,  5.80it/s]16 03:24:24 Save the image 00714N.png
 63%|████████████████████████▋              | 993/1568 [02:55<01:38,  5.82it/s]16 03:24:24 Save the image 00714N_flip.png
 63%|████████████████████████▋              | 994/1568 [02:55<01:36,  5.96it/s]16 03:24:24 Save the image 00715N.png
 63%|████████████████████████▋              | 995/1568 [02:55<01:37,  5.88it/s]16 03:24:24 Save the image 00715N_flip.png
 64%|████████████████████████▊              | 996/1568 [02:55<01:37,  5.86it/s]16 03:24:25 Save the image 00716N.png
 64%|████████████████████████▊              | 997/1568 [02:56<01:37,  5.84it/s]16 03:24:25 Save the image 00716N_flip.png
 64%|████████████████████████▊              | 998/1568 [02:56<01:38,  5.82it/s]16 03:24:25 Save the image 00717N.png
 64%|████████████████████████▊              | 999/1568 [02:56<01:38,  5.80it/s]16 03:24:25 Save the image 00717N_flip.png
 64%|████████████████████████▏             | 1000/1568 [02:56<01:38,  5.79it/s]16 03:24:25 Save the image 00718N.png
 64%|████████████████████████▎             | 1001/1568 [02:56<01:37,  5.83it/s]16 03:24:25 Save the image 00718N_flip.png
 64%|████████████████████████▎             | 1002/1568 [02:56<01:34,  5.97it/s]16 03:24:26 Save the image 00719N.png
 64%|████████████████████████▎             | 1003/1568 [02:57<01:35,  5.91it/s]16 03:24:26 Save the image 00719N_flip.png
 64%|████████████████████████▎             | 1004/1568 [02:57<01:35,  5.89it/s]16 03:24:26 Save the image 00720N.png
 64%|████████████████████████▎             | 1005/1568 [02:57<01:35,  5.87it/s]16 03:24:26 Save the image 00720N_flip.png
 64%|████████████████████████▍             | 1006/1568 [02:57<01:36,  5.84it/s]16 03:24:26 Save the image 00721N.png
 64%|████████████████████████▍             | 1007/1568 [02:57<01:36,  5.81it/s]16 03:24:27 Save the image 00721N_flip.png
 64%|████████████████████████▍             | 1008/1568 [02:57<01:36,  5.81it/s]16 03:24:27 Save the image 00722N.png
 64%|████████████████████████▍             | 1009/1568 [02:58<01:35,  5.84it/s]16 03:24:27 Save the image 00722N_flip.png
 64%|████████████████████████▍             | 1010/1568 [02:58<01:33,  5.94it/s]16 03:24:27 Save the image 00723N.png
 64%|████████████████████████▌             | 1011/1568 [02:58<01:34,  5.88it/s]16 03:24:27 Save the image 00723N_flip.png
 65%|████████████████████████▌             | 1012/1568 [02:58<01:34,  5.85it/s]16 03:24:27 Save the image 00724N.png
 65%|████████████████████████▌             | 1013/1568 [02:58<01:34,  5.85it/s]16 03:24:28 Save the image 00724N_flip.png
 65%|████████████████████████▌             | 1014/1568 [02:58<01:35,  5.81it/s]16 03:24:28 Save the image 00725N.png
 65%|████████████████████████▌             | 1015/1568 [02:59<01:35,  5.80it/s]16 03:24:28 Save the image 00725N_flip.png
 65%|████████████████████████▌             | 1016/1568 [02:59<01:35,  5.78it/s]16 03:24:28 Save the image 00726N.png

 65%|████████████████████████▋             | 1017/1568 [02:59<01:34,  5.86it/s]16 03:24:28 Save the image 00726N_flip.png
 65%|████████████████████████▋             | 1018/1568 [02:59<01:31,  6.00it/s]16 03:24:28 Save the image 00727N.png
 65%|████████████████████████▋             | 1019/1568 [02:59<01:32,  5.94it/s]16 03:24:29 Save the image 00727N_flip.png
 65%|████████████████████████▋             | 1020/1568 [02:59<01:32,  5.92it/s]16 03:24:29 Save the image 00728N.png
 65%|████████████████████████▋             | 1021/1568 [03:00<01:32,  5.90it/s]16 03:24:29 Save the image 00728N_flip.png
 65%|████████████████████████▊             | 1022/1568 [03:00<01:33,  5.86it/s]16 03:24:29 Save the image 00729N.png
 65%|████████████████████████▊             | 1023/1568 [03:00<01:33,  5.84it/s]16 03:24:29 Save the image 00729N_flip.png
 65%|████████████████████████▊             | 1024/1568 [03:00<01:33,  5.81it/s]16 03:24:29 Save the image 00730N.png
 65%|████████████████████████▊             | 1025/1568 [03:00<01:32,  5.88it/s]16 03:24:30 Save the image 00730N_flip.png
 65%|████████████████████████▊             | 1026/1568 [03:00<01:31,  5.95it/s]16 03:24:30 Save the image 00731N.png
 65%|████████████████████████▉             | 1027/1568 [03:01<01:31,  5.90it/s]16 03:24:30 Save the image 00731N_flip.png
 66%|████████████████████████▉             | 1028/1568 [03:01<01:31,  5.87it/s]16 03:24:30 Save the image 00732N.png
 66%|████████████████████████▉             | 1029/1568 [03:01<01:32,  5.84it/s]16 03:24:30 Save the image 00732N_flip.png
 66%|████████████████████████▉             | 1030/1568 [03:01<01:32,  5.79it/s]16 03:24:30 Save the image 00733N.png
 66%|████████████████████████▉             | 1031/1568 [03:01<01:33,  5.74it/s]16 03:24:31 Save the image 00733N_flip.png
 66%|█████████████████████████             | 1032/1568 [03:02<01:33,  5.74it/s]16 03:24:31 Save the image 00734N.png
 66%|█████████████████████████             | 1033/1568 [03:02<01:32,  5.79it/s]16 03:24:31 Save the image 00734N_flip.png
 66%|█████████████████████████             | 1034/1568 [03:02<01:29,  5.97it/s]16 03:24:31 Save the image 00735N.png
 66%|█████████████████████████             | 1035/1568 [03:02<01:29,  5.92it/s]16 03:24:31 Save the image 00735N_flip.png
 66%|█████████████████████████             | 1036/1568 [03:02<01:30,  5.89it/s]16 03:24:31 Save the image 00736N.png
 66%|█████████████████████████▏            | 1037/1568 [03:02<01:30,  5.85it/s]16 03:24:32 Save the image 00736N_flip.png
 66%|█████████████████████████▏            | 1038/1568 [03:03<01:31,  5.80it/s]16 03:24:32 Save the image 00737N.png
 66%|█████████████████████████▏            | 1039/1568 [03:03<01:31,  5.80it/s]16 03:24:32 Save the image 00737N_flip.png
 66%|█████████████████████████▏            | 1040/1568 [03:03<01:31,  5.79it/s]16 03:24:32 Save the image 00738N.png
 66%|█████████████████████████▏            | 1041/1568 [03:03<01:30,  5.83it/s]16 03:24:32 Save the image 00738N_flip.png
 66%|█████████████████████████▎            | 1042/1568 [03:03<01:28,  5.96it/s]16 03:24:32 Save the image 00739N.png
 67%|█████████████████████████▎            | 1043/1568 [03:03<01:29,  5.90it/s]16 03:24:33 Save the image 00739N_flip.png
 67%|█████████████████████████▎            | 1044/1568 [03:04<01:29,  5.87it/s]16 03:24:33 Save the image 00740N.png
 67%|█████████████████████████▎            | 1045/1568 [03:04<01:29,  5.85it/s]16 03:24:33 Save the image 00740N_flip.png
 67%|█████████████████████████▎            | 1046/1568 [03:04<01:29,  5.83it/s]16 03:24:33 Save the image 00741N.png
 67%|█████████████████████████▎            | 1047/1568 [03:04<01:29,  5.81it/s]16 03:24:33 Save the image 00741N_flip.png
 67%|█████████████████████████▍            | 1048/1568 [03:04<01:29,  5.80it/s]16 03:24:34 Save the image 00742N.png
 67%|█████████████████████████▍            | 1049/1568 [03:04<01:29,  5.79it/s]16 03:24:34 Save the image 00742N_flip.png
 67%|█████████████████████████▍            | 1050/1568 [03:05<01:29,  5.82it/s]16 03:24:34 Save the image 00743N.png
 67%|█████████████████████████▍            | 1051/1568 [03:05<01:29,  5.78it/s]16 03:24:34 Save the image 00743N_flip.png
 67%|█████████████████████████▍            | 1052/1568 [03:05<01:30,  5.72it/s]16 03:24:34 Save the image 00744N.png
 67%|█████████████████████████▌            | 1053/1568 [03:05<01:29,  5.73it/s]16 03:24:34 Save the image 00744N_flip.png
 67%|█████████████████████████▌            | 1054/1568 [03:05<01:30,  5.68it/s]16 03:24:35 Save the image 00745N.png
 67%|█████████████████████████▌            | 1055/1568 [03:05<01:30,  5.69it/s]16 03:24:35 Save the image 00745N_flip.png
 67%|█████████████████████████▌            | 1056/1568 [03:06<01:30,  5.66it/s]16 03:24:35 Save the image 00746N.png
 67%|█████████████████████████▌            | 1057/1568 [03:06<01:29,  5.69it/s]16 03:24:35 Save the image 00746N_flip.png
 67%|█████████████████████████▋            | 1058/1568 [03:06<01:29,  5.72it/s]16 03:24:35 Save the image 00747N.png
 68%|█████████████████████████▋            | 1059/1568 [03:06<01:29,  5.71it/s]16 03:24:35 Save the image 00747N_flip.png
 68%|█████████████████████████▋            | 1060/1568 [03:06<01:30,  5.63it/s]16 03:24:36 Save the image 00748N.png
 68%|█████████████████████████▋            | 1061/1568 [03:07<01:29,  5.64it/s]16 03:24:36 Save the image 00748N_flip.png
 68%|█████████████████████████▋            | 1062/1568 [03:07<01:29,  5.63it/s]16 03:24:36 Save the image 00749N.png
 68%|█████████████████████████▊            | 1063/1568 [03:07<01:29,  5.61it/s]16 03:24:36 Save the image 00749N_flip.png
 68%|█████████████████████████▊            | 1064/1568 [03:07<01:29,  5.64it/s]16 03:24:36 Save the image 00750N.png
 68%|█████████████████████████▊            | 1065/1568 [03:07<01:28,  5.68it/s]16 03:24:37 Save the image 00750N_flip.png
 68%|█████████████████████████▊            | 1066/1568 [03:07<01:27,  5.74it/s]16 03:24:37 Save the image 00751N.png
 68%|█████████████████████████▊            | 1067/1568 [03:08<01:28,  5.68it/s]16 03:24:37 Save the image 00751N_flip.png
 68%|█████████████████████████▉            | 1068/1568 [03:08<01:27,  5.70it/s]16 03:24:37 Save the image 00752N.png
 68%|█████████████████████████▉            | 1069/1568 [03:08<01:28,  5.62it/s]16 03:24:37 Save the image 00752N_flip.png
 68%|█████████████████████████▉            | 1070/1568 [03:08<01:29,  5.58it/s]16 03:24:37 Save the image 00753N.png
 68%|█████████████████████████▉            | 1071/1568 [03:08<01:28,  5.59it/s]16 03:24:38 Save the image 00753N_flip.png
 68%|█████████████████████████▉            | 1072/1568 [03:08<01:27,  5.65it/s]16 03:24:38 Save the image 00754N.png
 68%|██████████████████████████            | 1073/1568 [03:09<01:27,  5.69it/s]16 03:24:38 Save the image 00754N_flip.png
 68%|██████████████████████████            | 1074/1568 [03:09<01:21,  6.04it/s]16 03:24:38 Save the image 00755N.png
 69%|██████████████████████████            | 1075/1568 [03:09<01:22,  5.95it/s]16 03:24:38 Save the image 00755N_flip.png
 69%|██████████████████████████            | 1076/1568 [03:09<01:23,  5.91it/s]16 03:24:38 Save the image 00756N.png
 69%|██████████████████████████            | 1077/1568 [03:09<01:23,  5.90it/s]16 03:24:39 Save the image 00756N_flip.png
 69%|██████████████████████████▏           | 1078/1568 [03:09<01:23,  5.85it/s]16 03:24:39 Save the image 00757N.png
 69%|██████████████████████████▏           | 1079/1568 [03:10<01:23,  5.82it/s]16 03:24:39 Save the image 00757N_flip.png
 69%|██████████████████████████▏           | 1080/1568 [03:10<01:24,  5.81it/s]16 03:24:39 Save the image 00758N.png

 69%|██████████████████████████▏           | 1081/1568 [03:10<01:23,  5.84it/s]16 03:24:39 Save the image 00758N_flip.png
 69%|██████████████████████████▏           | 1082/1568 [03:10<01:20,  6.02it/s]16 03:24:39 Save the image 00759N.png
 69%|██████████████████████████▏           | 1083/1568 [03:10<01:21,  5.93it/s]16 03:24:40 Save the image 00759N_flip.png
 69%|██████████████████████████▎           | 1084/1568 [03:10<01:22,  5.90it/s]16 03:24:40 Save the image 00760N.png
 69%|██████████████████████████▎           | 1085/1568 [03:11<01:22,  5.85it/s]16 03:24:40 Save the image 00760N_flip.png
 69%|██████████████████████████▎           | 1086/1568 [03:11<01:22,  5.83it/s]16 03:24:40 Save the image 00761N.png
 69%|██████████████████████████▎           | 1087/1568 [03:11<01:22,  5.81it/s]16 03:24:40 Save the image 00761N_flip.png
 69%|██████████████████████████▎           | 1088/1568 [03:11<01:22,  5.80it/s]16 03:24:40 Save the image 00762N.png
 69%|██████████████████████████▍           | 1089/1568 [03:11<01:22,  5.80it/s]16 03:24:41 Save the image 00762N_flip.png
 70%|██████████████████████████▍           | 1090/1568 [03:12<01:19,  6.00it/s]16 03:24:41 Save the image 00763N.png
 70%|██████████████████████████▍           | 1091/1568 [03:12<01:20,  5.94it/s]16 03:24:41 Save the image 00763N_flip.png
 70%|██████████████████████████▍           | 1092/1568 [03:12<01:20,  5.90it/s]16 03:24:41 Save the image 00764N.png
 70%|██████████████████████████▍           | 1093/1568 [03:12<01:20,  5.87it/s]16 03:24:41 Save the image 00764N_flip.png
 70%|██████████████████████████▌           | 1094/1568 [03:12<01:21,  5.83it/s]16 03:24:41 Save the image 00765N.png
 70%|██████████████████████████▌           | 1095/1568 [03:12<01:21,  5.81it/s]16 03:24:42 Save the image 00765N_flip.png
 70%|██████████████████████████▌           | 1096/1568 [03:13<01:21,  5.79it/s]16 03:24:42 Save the image 00766N.png
 70%|██████████████████████████▌           | 1097/1568 [03:13<01:20,  5.83it/s]16 03:24:42 Save the image 00766N_flip.png
 70%|██████████████████████████▌           | 1098/1568 [03:13<01:18,  5.96it/s]16 03:24:42 Save the image 00767N.png
 70%|██████████████████████████▋           | 1099/1568 [03:13<01:19,  5.90it/s]16 03:24:42 Save the image 00767N_flip.png
 70%|██████████████████████████▋           | 1100/1568 [03:13<01:19,  5.87it/s]16 03:24:43 Save the image 00768N.png
 70%|██████████████████████████▋           | 1101/1568 [03:13<01:20,  5.84it/s]16 03:24:43 Save the image 00768N_flip.png
 70%|██████████████████████████▋           | 1102/1568 [03:14<01:20,  5.81it/s]16 03:24:43 Save the image 00769N.png
 70%|██████████████████████████▋           | 1103/1568 [03:14<01:20,  5.80it/s]16 03:24:43 Save the image 00769N_flip.png
 70%|██████████████████████████▊           | 1104/1568 [03:14<01:20,  5.79it/s]16 03:24:43 Save the image 00770N.png
 70%|██████████████████████████▊           | 1105/1568 [03:14<01:19,  5.83it/s]16 03:24:43 Save the image 00770N_flip.png
 71%|██████████████████████████▊           | 1106/1568 [03:14<01:17,  5.94it/s]16 03:24:44 Save the image 00771N.png
 71%|██████████████████████████▊           | 1107/1568 [03:14<01:18,  5.91it/s]16 03:24:44 Save the image 00771N_flip.png
 71%|██████████████████████████▊           | 1108/1568 [03:15<01:18,  5.87it/s]16 03:24:44 Save the image 00772N.png
 71%|██████████████████████████▉           | 1109/1568 [03:15<01:18,  5.87it/s]16 03:24:44 Save the image 00772N_flip.png
 71%|██████████████████████████▉           | 1110/1568 [03:15<01:18,  5.82it/s]16 03:24:44 Save the image 00773N.png
 71%|██████████████████████████▉           | 1111/1568 [03:15<01:18,  5.83it/s]16 03:24:44 Save the image 00773N_flip.png
 71%|██████████████████████████▉           | 1112/1568 [03:15<01:18,  5.80it/s]16 03:24:45 Save the image 00774N.png
 71%|██████████████████████████▉           | 1113/1568 [03:15<01:17,  5.84it/s]16 03:24:45 Save the image 00774N_flip.png
 71%|██████████████████████████▉           | 1114/1568 [03:16<01:16,  5.91it/s]16 03:24:45 Save the image 00775N.png
 71%|███████████████████████████           | 1115/1568 [03:16<01:17,  5.87it/s]16 03:24:45 Save the image 00775N_flip.png
 71%|███████████████████████████           | 1116/1568 [03:16<01:17,  5.86it/s]16 03:24:45 Save the image 00776N.png
 71%|███████████████████████████           | 1117/1568 [03:16<01:17,  5.85it/s]16 03:24:45 Save the image 00776N_flip.png
 71%|███████████████████████████           | 1118/1568 [03:16<01:17,  5.83it/s]16 03:24:46 Save the image 00777N.png
 71%|███████████████████████████           | 1119/1568 [03:16<01:18,  5.74it/s]16 03:24:46 Save the image 00777N_flip.png
 71%|███████████████████████████▏          | 1120/1568 [03:17<01:17,  5.76it/s]16 03:24:46 Save the image 00778N.png
 71%|███████████████████████████▏          | 1121/1568 [03:17<01:16,  5.84it/s]16 03:24:46 Save the image 00778N_flip.png
 72%|███████████████████████████▏          | 1122/1568 [03:17<01:14,  5.97it/s]16 03:24:46 Save the image 00779N.png
 72%|███████████████████████████▏          | 1123/1568 [03:17<01:15,  5.89it/s]16 03:24:46 Save the image 00779N_flip.png
 72%|███████████████████████████▏          | 1124/1568 [03:17<01:15,  5.86it/s]16 03:24:47 Save the image 00780N.png
 72%|███████████████████████████▎          | 1125/1568 [03:18<01:16,  5.79it/s]16 03:24:47 Save the image 00780N_flip.png
 72%|███████████████████████████▎          | 1126/1568 [03:18<01:17,  5.70it/s]16 03:24:47 Save the image 00781N.png
 72%|███████████████████████████▎          | 1127/1568 [03:18<01:17,  5.72it/s]16 03:24:47 Save the image 00781N_flip.png
 72%|███████████████████████████▎          | 1128/1568 [03:18<01:16,  5.73it/s]16 03:24:47 Save the image 00782N.png
 72%|███████████████████████████▎          | 1129/1568 [03:18<01:16,  5.73it/s]16 03:24:47 Save the image 00782N_flip.png
 72%|███████████████████████████▍          | 1130/1568 [03:18<01:12,  6.06it/s]16 03:24:48 Save the image 00783N.png
 72%|███████████████████████████▍          | 1131/1568 [03:19<01:13,  5.91it/s]16 03:24:48 Save the image 00783N_flip.png
 72%|███████████████████████████▍          | 1132/1568 [03:19<01:14,  5.88it/s]16 03:24:48 Save the image 00784N.png
 72%|███████████████████████████▍          | 1133/1568 [03:19<01:14,  5.88it/s]16 03:24:48 Save the image 00784N_flip.png
 72%|███████████████████████████▍          | 1134/1568 [03:19<01:14,  5.82it/s]16 03:24:48 Save the image 00785N.png
 72%|███████████████████████████▌          | 1135/1568 [03:19<01:14,  5.80it/s]16 03:24:49 Save the image 00785N_flip.png
 72%|███████████████████████████▌          | 1136/1568 [03:19<01:14,  5.79it/s]16 03:24:49 Save the image 00786N.png
 73%|███████████████████████████▌          | 1137/1568 [03:20<01:14,  5.81it/s]16 03:24:49 Save the image 00786N_flip.png
 73%|███████████████████████████▌          | 1138/1568 [03:20<01:10,  6.08it/s]16 03:24:49 Save the image 00787N.png
 73%|███████████████████████████▌          | 1139/1568 [03:20<01:11,  5.99it/s]16 03:24:49 Save the image 00787N_flip.png
 73%|███████████████████████████▋          | 1140/1568 [03:20<01:12,  5.94it/s]16 03:24:49 Save the image 00788N.png
 73%|███████████████████████████▋          | 1141/1568 [03:20<01:12,  5.92it/s]16 03:24:50 Save the image 00788N_flip.png
 73%|███████████████████████████▋          | 1142/1568 [03:20<01:12,  5.88it/s]16 03:24:50 Save the image 00789N.png
 73%|███████████████████████████▋          | 1143/1568 [03:21<01:12,  5.87it/s]16 03:24:50 Save the image 00789N_flip.png
 73%|███████████████████████████▋          | 1144/1568 [03:21<01:12,  5.85it/s]16 03:24:50 Save the image 00790N.png

 73%|███████████████████████████▋          | 1145/1568 [03:21<01:12,  5.84it/s]16 03:24:50 Save the image 00790N_flip.png
 73%|███████████████████████████▊          | 1146/1568 [03:21<01:11,  5.92it/s]16 03:24:50 Save the image 00791N.png
 73%|███████████████████████████▊          | 1147/1568 [03:21<01:11,  5.87it/s]16 03:24:51 Save the image 00791N_flip.png
 73%|███████████████████████████▊          | 1148/1568 [03:21<01:11,  5.87it/s]16 03:24:51 Save the image 00792N.png
 73%|███████████████████████████▊          | 1149/1568 [03:22<01:12,  5.81it/s]16 03:24:51 Save the image 00792N_flip.png
 73%|███████████████████████████▊          | 1150/1568 [03:22<01:12,  5.80it/s]16 03:24:51 Save the image 00793N.png
 73%|███████████████████████████▉          | 1151/1568 [03:22<01:11,  5.81it/s]16 03:24:51 Save the image 00793N_flip.png
 73%|███████████████████████████▉          | 1152/1568 [03:22<01:11,  5.80it/s]16 03:24:51 Save the image 00794N.png
 74%|███████████████████████████▉          | 1153/1568 [03:22<01:11,  5.84it/s]16 03:24:52 Save the image 00794N_flip.png
 74%|███████████████████████████▉          | 1154/1568 [03:22<01:09,  5.93it/s]16 03:24:52 Save the image 00795N.png
 74%|███████████████████████████▉          | 1155/1568 [03:23<01:09,  5.91it/s]16 03:24:52 Save the image 00795N_flip.png
 74%|████████████████████████████          | 1156/1568 [03:23<01:09,  5.90it/s]16 03:24:52 Save the image 00796N.png
 74%|████████████████████████████          | 1157/1568 [03:23<01:09,  5.89it/s]16 03:24:52 Save the image 00796N_flip.png
 74%|████████████████████████████          | 1158/1568 [03:23<01:09,  5.87it/s]16 03:24:52 Save the image 00797N.png
 74%|████████████████████████████          | 1159/1568 [03:23<01:09,  5.84it/s]16 03:24:53 Save the image 00797N_flip.png
 74%|████████████████████████████          | 1160/1568 [03:23<01:09,  5.83it/s]16 03:24:53 Save the image 00798N.png
 74%|████████████████████████████▏         | 1161/1568 [03:24<01:09,  5.86it/s]16 03:24:53 Save the image 00798N_flip.png
 74%|████████████████████████████▏         | 1162/1568 [03:24<01:08,  5.89it/s]16 03:24:53 Save the image 00799N.png
 74%|████████████████████████████▏         | 1163/1568 [03:24<01:08,  5.87it/s]16 03:24:53 Save the image 00799N_flip.png
 74%|████████████████████████████▏         | 1164/1568 [03:24<01:08,  5.87it/s]16 03:24:53 Save the image 00800N.png
 74%|████████████████████████████▏         | 1165/1568 [03:24<01:08,  5.84it/s]16 03:24:54 Save the image 00800N_flip.png
 74%|████████████████████████████▎         | 1166/1568 [03:24<01:09,  5.82it/s]16 03:24:54 Save the image 00801N.png
 74%|████████████████████████████▎         | 1167/1568 [03:25<01:09,  5.81it/s]16 03:24:54 Save the image 00801N_flip.png
 74%|████████████████████████████▎         | 1168/1568 [03:25<01:08,  5.81it/s]16 03:24:54 Save the image 00802N.png
 75%|████████████████████████████▎         | 1169/1568 [03:25<01:08,  5.86it/s]16 03:24:54 Save the image 00802N_flip.png
 75%|████████████████████████████▎         | 1170/1568 [03:25<01:07,  5.89it/s]16 03:24:54 Save the image 00803N.png
 75%|████████████████████████████▍         | 1171/1568 [03:25<01:08,  5.82it/s]16 03:24:55 Save the image 00803N_flip.png
 75%|████████████████████████████▍         | 1172/1568 [03:26<01:07,  5.84it/s]16 03:24:55 Save the image 00804N.png
 75%|████████████████████████████▍         | 1173/1568 [03:26<01:07,  5.85it/s]16 03:24:55 Save the image 00804N_flip.png
 75%|████████████████████████████▍         | 1174/1568 [03:26<01:07,  5.83it/s]16 03:24:55 Save the image 00805N.png
 75%|████████████████████████████▍         | 1175/1568 [03:26<01:07,  5.83it/s]16 03:24:55 Save the image 00805N_flip.png
 75%|████████████████████████████▌         | 1176/1568 [03:26<01:07,  5.81it/s]16 03:24:55 Save the image 00806N.png
 75%|████████████████████████████▌         | 1177/1568 [03:26<01:06,  5.85it/s]16 03:24:56 Save the image 00806N_flip.png
 75%|████████████████████████████▌         | 1178/1568 [03:27<01:06,  5.88it/s]16 03:24:56 Save the image 00807N.png
 75%|████████████████████████████▌         | 1179/1568 [03:27<01:06,  5.85it/s]16 03:24:56 Save the image 00807N_flip.png
 75%|████████████████████████████▌         | 1180/1568 [03:27<01:06,  5.86it/s]16 03:24:56 Save the image 00808N.png
 75%|████████████████████████████▌         | 1181/1568 [03:27<01:06,  5.86it/s]16 03:24:56 Save the image 00808N_flip.png
 75%|████████████████████████████▋         | 1182/1568 [03:27<01:06,  5.83it/s]16 03:24:57 Save the image 00809N.png
 75%|████████████████████████████▋         | 1183/1568 [03:27<01:06,  5.83it/s]16 03:24:57 Save the image 00809N_flip.png
 76%|████████████████████████████▋         | 1184/1568 [03:28<01:05,  5.84it/s]16 03:24:57 Save the image 00810N.png
 76%|████████████████████████████▋         | 1185/1568 [03:28<01:05,  5.87it/s]16 03:24:57 Save the image 00810N_flip.png
 76%|████████████████████████████▋         | 1186/1568 [03:28<01:04,  5.90it/s]16 03:24:57 Save the image 00811N.png
 76%|████████████████████████████▊         | 1187/1568 [03:28<01:04,  5.87it/s]16 03:24:57 Save the image 00811N_flip.png
 76%|████████████████████████████▊         | 1188/1568 [03:28<01:05,  5.84it/s]16 03:24:58 Save the image 00812N.png
 76%|████████████████████████████▊         | 1189/1568 [03:28<01:05,  5.81it/s]16 03:24:58 Save the image 00812N_flip.png
 76%|████████████████████████████▊         | 1190/1568 [03:29<01:05,  5.79it/s]16 03:24:58 Save the image 00813N.png
 76%|████████████████████████████▊         | 1191/1568 [03:29<01:04,  5.80it/s]16 03:24:58 Save the image 00813N_flip.png
 76%|████████████████████████████▉         | 1192/1568 [03:29<01:04,  5.80it/s]16 03:24:58 Save the image 00814N.png
 76%|████████████████████████████▉         | 1193/1568 [03:29<01:04,  5.84it/s]16 03:24:58 Save the image 00814N_flip.png
 76%|████████████████████████████▉         | 1194/1568 [03:29<01:03,  5.93it/s]16 03:24:59 Save the image 00815N.png
 76%|████████████████████████████▉         | 1195/1568 [03:29<01:03,  5.88it/s]16 03:24:59 Save the image 00815N_flip.png
 76%|████████████████████████████▉         | 1196/1568 [03:30<01:03,  5.86it/s]16 03:24:59 Save the image 00816N.png
 76%|█████████████████████████████         | 1197/1568 [03:30<01:03,  5.84it/s]16 03:24:59 Save the image 00816N_flip.png
 76%|█████████████████████████████         | 1198/1568 [03:30<01:03,  5.80it/s]16 03:24:59 Save the image 00817N.png
 76%|█████████████████████████████         | 1199/1568 [03:30<01:03,  5.79it/s]16 03:24:59 Save the image 00817N_flip.png
 77%|█████████████████████████████         | 1200/1568 [03:30<01:03,  5.79it/s]16 03:25:00 Save the image 00818N.png
 77%|█████████████████████████████         | 1201/1568 [03:30<01:03,  5.82it/s]16 03:25:00 Save the image 00818N_flip.png
 77%|█████████████████████████████▏        | 1202/1568 [03:31<01:01,  5.94it/s]16 03:25:00 Save the image 00819N.png
 77%|█████████████████████████████▏        | 1203/1568 [03:31<01:02,  5.87it/s]16 03:25:00 Save the image 00819N_flip.png
 77%|█████████████████████████████▏        | 1204/1568 [03:31<01:02,  5.86it/s]16 03:25:00 Save the image 00820N.png
 77%|█████████████████████████████▏        | 1205/1568 [03:31<01:02,  5.85it/s]16 03:25:00 Save the image 00820N_flip.png
 77%|█████████████████████████████▏        | 1206/1568 [03:31<01:02,  5.80it/s]16 03:25:01 Save the image 00821N.png
 77%|█████████████████████████████▎        | 1207/1568 [03:32<01:03,  5.73it/s]16 03:25:01 Save the image 00821N_flip.png
 77%|█████████████████████████████▎        | 1208/1568 [03:32<01:02,  5.72it/s]16 03:25:01 Save the image 00822N.png

 77%|█████████████████████████████▎        | 1209/1568 [03:32<01:02,  5.77it/s]16 03:25:01 Save the image 00822N_flip.png
 77%|█████████████████████████████▎        | 1210/1568 [03:32<00:59,  6.00it/s]16 03:25:01 Save the image 00823N.png
 77%|█████████████████████████████▎        | 1211/1568 [03:32<01:00,  5.93it/s]16 03:25:01 Save the image 00823N_flip.png
 77%|█████████████████████████████▎        | 1212/1568 [03:32<01:00,  5.90it/s]16 03:25:02 Save the image 00824N.png
 77%|█████████████████████████████▍        | 1213/1568 [03:33<01:00,  5.87it/s]16 03:25:02 Save the image 00824N_flip.png
 77%|█████████████████████████████▍        | 1214/1568 [03:33<01:00,  5.83it/s]16 03:25:02 Save the image 00825N.png
 77%|█████████████████████████████▍        | 1215/1568 [03:33<01:00,  5.81it/s]16 03:25:02 Save the image 00825N_flip.png
 78%|█████████████████████████████▍        | 1216/1568 [03:33<01:00,  5.80it/s]16 03:25:02 Save the image 00826N.png
 78%|█████████████████████████████▍        | 1217/1568 [03:33<01:00,  5.83it/s]16 03:25:02 Save the image 00826N_flip.png
 78%|█████████████████████████████▌        | 1218/1568 [03:33<00:58,  5.98it/s]16 03:25:03 Save the image 00827N.png
 78%|█████████████████████████████▌        | 1219/1568 [03:34<00:59,  5.89it/s]16 03:25:03 Save the image 00827N_flip.png
 78%|█████████████████████████████▌        | 1220/1568 [03:34<00:59,  5.87it/s]16 03:25:03 Save the image 00828N.png
 78%|█████████████████████████████▌        | 1221/1568 [03:34<00:59,  5.87it/s]16 03:25:03 Save the image 00828N_flip.png
 78%|█████████████████████████████▌        | 1222/1568 [03:34<00:59,  5.84it/s]16 03:25:03 Save the image 00829N.png
 78%|█████████████████████████████▋        | 1223/1568 [03:34<00:59,  5.81it/s]16 03:25:04 Save the image 00829N_flip.png
 78%|█████████████████████████████▋        | 1224/1568 [03:34<00:59,  5.80it/s]16 03:25:04 Save the image 00830N.png
 78%|█████████████████████████████▋        | 1225/1568 [03:35<00:58,  5.83it/s]16 03:25:04 Save the image 00830N_flip.png
 78%|█████████████████████████████▋        | 1226/1568 [03:35<00:57,  5.92it/s]16 03:25:04 Save the image 00831N.png
 78%|█████████████████████████████▋        | 1227/1568 [03:35<00:58,  5.87it/s]16 03:25:04 Save the image 00831N_flip.png
 78%|█████████████████████████████▊        | 1228/1568 [03:35<00:58,  5.84it/s]16 03:25:04 Save the image 00832N.png
 78%|█████████████████████████████▊        | 1229/1568 [03:35<00:57,  5.85it/s]16 03:25:05 Save the image 00832N_flip.png
 78%|█████████████████████████████▊        | 1230/1568 [03:35<00:57,  5.83it/s]16 03:25:05 Save the image 00833N.png
 79%|█████████████████████████████▊        | 1231/1568 [03:36<00:58,  5.81it/s]16 03:25:05 Save the image 00833N_flip.png
 79%|█████████████████████████████▊        | 1232/1568 [03:36<00:58,  5.79it/s]16 03:25:05 Save the image 00834N.png
 79%|█████████████████████████████▉        | 1233/1568 [03:36<00:57,  5.83it/s]16 03:25:05 Save the image 00834N_flip.png
 79%|█████████████████████████████▉        | 1234/1568 [03:36<00:56,  5.92it/s]16 03:25:05 Save the image 00835N.png
 79%|█████████████████████████████▉        | 1235/1568 [03:36<00:56,  5.88it/s]16 03:25:06 Save the image 00835N_flip.png
 79%|█████████████████████████████▉        | 1236/1568 [03:36<00:56,  5.86it/s]16 03:25:06 Save the image 00836N.png
 79%|█████████████████████████████▉        | 1237/1568 [03:37<00:57,  5.79it/s]16 03:25:06 Save the image 00836N_flip.png
 79%|██████████████████████████████        | 1238/1568 [03:37<00:57,  5.76it/s]16 03:25:06 Save the image 00837N.png
 79%|██████████████████████████████        | 1239/1568 [03:37<00:57,  5.76it/s]16 03:25:06 Save the image 00837N_flip.png
 79%|██████████████████████████████        | 1240/1568 [03:37<00:56,  5.76it/s]16 03:25:06 Save the image 00838N.png
 79%|██████████████████████████████        | 1241/1568 [03:37<00:56,  5.81it/s]16 03:25:07 Save the image 00838N_flip.png
 79%|██████████████████████████████        | 1242/1568 [03:37<00:54,  5.99it/s]16 03:25:07 Save the image 00839N.png
 79%|██████████████████████████████        | 1243/1568 [03:38<00:55,  5.89it/s]16 03:25:07 Save the image 00839N_flip.png
 79%|██████████████████████████████▏       | 1244/1568 [03:38<00:55,  5.86it/s]16 03:25:07 Save the image 00840N.png
 79%|██████████████████████████████▏       | 1245/1568 [03:38<00:55,  5.83it/s]16 03:25:07 Save the image 00840N_flip.png
 79%|██████████████████████████████▏       | 1246/1568 [03:38<00:55,  5.82it/s]16 03:25:07 Save the image 00841N.png
 80%|██████████████████████████████▏       | 1247/1568 [03:38<00:55,  5.81it/s]16 03:25:08 Save the image 00841N_flip.png
 80%|██████████████████████████████▏       | 1248/1568 [03:39<00:55,  5.81it/s]16 03:25:08 Save the image 00842N.png
 80%|██████████████████████████████▎       | 1249/1568 [03:39<00:54,  5.85it/s]16 03:25:08 Save the image 00842N_flip.png
 80%|██████████████████████████████▎       | 1250/1568 [03:39<00:53,  5.90it/s]16 03:25:08 Save the image 00843N.png
 80%|██████████████████████████████▎       | 1251/1568 [03:39<00:54,  5.83it/s]16 03:25:08 Save the image 00843N_flip.png
 80%|██████████████████████████████▎       | 1252/1568 [03:39<00:54,  5.85it/s]16 03:25:08 Save the image 00844N.png
 80%|██████████████████████████████▎       | 1253/1568 [03:39<00:53,  5.86it/s]16 03:25:09 Save the image 00844N_flip.png
 80%|██████████████████████████████▍       | 1254/1568 [03:40<00:53,  5.82it/s]16 03:25:09 Save the image 00845N.png
 80%|██████████████████████████████▍       | 1255/1568 [03:40<00:54,  5.76it/s]16 03:25:09 Save the image 00845N_flip.png
 80%|██████████████████████████████▍       | 1256/1568 [03:40<00:54,  5.76it/s]16 03:25:09 Save the image 00846N.png
 80%|██████████████████████████████▍       | 1257/1568 [03:40<00:53,  5.81it/s]16 03:25:09 Save the image 00846N_flip.png
 80%|██████████████████████████████▍       | 1258/1568 [03:40<00:52,  5.92it/s]16 03:25:10 Save the image 00847N.png
 80%|██████████████████████████████▌       | 1259/1568 [03:40<00:52,  5.88it/s]16 03:25:10 Save the image 00847N_flip.png
 80%|██████████████████████████████▌       | 1260/1568 [03:41<00:52,  5.86it/s]16 03:25:10 Save the image 00848N.png
 80%|██████████████████████████████▌       | 1261/1568 [03:41<00:52,  5.84it/s]16 03:25:10 Save the image 00848N_flip.png
 80%|██████████████████████████████▌       | 1262/1568 [03:41<00:52,  5.82it/s]16 03:25:10 Save the image 00849N.png
 81%|██████████████████████████████▌       | 1263/1568 [03:41<00:52,  5.80it/s]16 03:25:10 Save the image 00849N_flip.png
 81%|██████████████████████████████▋       | 1264/1568 [03:41<00:52,  5.79it/s]16 03:25:11 Save the image 00850N.png
 81%|██████████████████████████████▋       | 1265/1568 [03:41<00:51,  5.83it/s]16 03:25:11 Save the image 00850N_flip.png
 81%|██████████████████████████████▋       | 1266/1568 [03:42<00:50,  5.95it/s]16 03:25:11 Save the image 00851N.png
 81%|██████████████████████████████▋       | 1267/1568 [03:42<00:51,  5.87it/s]16 03:25:11 Save the image 00851N_flip.png
 81%|██████████████████████████████▋       | 1268/1568 [03:42<00:51,  5.85it/s]16 03:25:11 Save the image 00852N.png
 81%|██████████████████████████████▊       | 1269/1568 [03:42<00:51,  5.83it/s]16 03:25:11 Save the image 00852N_flip.png
 81%|██████████████████████████████▊       | 1270/1568 [03:42<00:51,  5.81it/s]16 03:25:12 Save the image 00853N.png
 81%|██████████████████████████████▊       | 1271/1568 [03:42<00:51,  5.79it/s]16 03:25:12 Save the image 00853N_flip.png
 81%|██████████████████████████████▊       | 1272/1568 [03:43<00:51,  5.72it/s]16 03:25:12 Save the image 00854N.png

 81%|██████████████████████████████▊       | 1273/1568 [03:43<00:51,  5.78it/s]16 03:25:12 Save the image 00854N_flip.png
 81%|██████████████████████████████▉       | 1274/1568 [03:43<00:49,  5.98it/s]16 03:25:12 Save the image 00855N.png
 81%|██████████████████████████████▉       | 1275/1568 [03:43<00:49,  5.93it/s]16 03:25:12 Save the image 00855N_flip.png
 81%|██████████████████████████████▉       | 1276/1568 [03:43<00:49,  5.91it/s]16 03:25:13 Save the image 00856N.png
 81%|██████████████████████████████▉       | 1277/1568 [03:43<00:49,  5.87it/s]16 03:25:13 Save the image 00856N_flip.png
 82%|██████████████████████████████▉       | 1278/1568 [03:44<00:49,  5.83it/s]16 03:25:13 Save the image 00857N.png
 82%|██████████████████████████████▉       | 1279/1568 [03:44<00:49,  5.83it/s]16 03:25:13 Save the image 00857N_flip.png
 82%|███████████████████████████████       | 1280/1568 [03:44<00:49,  5.81it/s]16 03:25:13 Save the image 00858N.png
 82%|███████████████████████████████       | 1281/1568 [03:44<00:49,  5.85it/s]16 03:25:13 Save the image 00858N_flip.png
 82%|███████████████████████████████       | 1282/1568 [03:44<00:48,  5.95it/s]16 03:25:14 Save the image 00859N.png
 82%|███████████████████████████████       | 1283/1568 [03:45<00:48,  5.87it/s]16 03:25:14 Save the image 00859N_flip.png
 82%|███████████████████████████████       | 1284/1568 [03:45<00:48,  5.86it/s]16 03:25:14 Save the image 00860N.png
 82%|███████████████████████████████▏      | 1285/1568 [03:45<00:48,  5.86it/s]16 03:25:14 Save the image 00860N_flip.png
 82%|███████████████████████████████▏      | 1286/1568 [03:45<00:48,  5.84it/s]16 03:25:14 Save the image 00861N.png
 82%|███████████████████████████████▏      | 1287/1568 [03:45<00:48,  5.82it/s]16 03:25:14 Save the image 00861N_flip.png
 82%|███████████████████████████████▏      | 1288/1568 [03:45<00:48,  5.81it/s]16 03:25:15 Save the image 00862N.png
 82%|███████████████████████████████▏      | 1289/1568 [03:46<00:47,  5.85it/s]16 03:25:15 Save the image 00862N_flip.png
 82%|███████████████████████████████▎      | 1290/1568 [03:46<00:46,  5.95it/s]16 03:25:15 Save the image 00863N.png
 82%|███████████████████████████████▎      | 1291/1568 [03:46<00:46,  5.90it/s]16 03:25:15 Save the image 00863N_flip.png
 82%|███████████████████████████████▎      | 1292/1568 [03:46<00:46,  5.89it/s]16 03:25:15 Save the image 00864N.png
 82%|███████████████████████████████▎      | 1293/1568 [03:46<00:46,  5.88it/s]16 03:25:16 Save the image 00864N_flip.png
 83%|███████████████████████████████▎      | 1294/1568 [03:46<00:47,  5.82it/s]16 03:25:16 Save the image 00865N.png
 83%|███████████████████████████████▍      | 1295/1568 [03:47<00:47,  5.81it/s]16 03:25:16 Save the image 00865N_flip.png
 83%|███████████████████████████████▍      | 1296/1568 [03:47<00:46,  5.80it/s]16 03:25:16 Save the image 00866N.png
 83%|███████████████████████████████▍      | 1297/1568 [03:47<00:46,  5.87it/s]16 03:25:16 Save the image 00866N_flip.png
 83%|███████████████████████████████▍      | 1298/1568 [03:47<00:45,  5.95it/s]16 03:25:16 Save the image 00867N.png
 83%|███████████████████████████████▍      | 1299/1568 [03:47<00:45,  5.90it/s]16 03:25:17 Save the image 00867N_flip.png
 83%|███████████████████████████████▌      | 1300/1568 [03:47<00:45,  5.87it/s]16 03:25:17 Save the image 00868N.png
 83%|███████████████████████████████▌      | 1301/1568 [03:48<00:45,  5.86it/s]16 03:25:17 Save the image 00868N_flip.png
 83%|███████████████████████████████▌      | 1302/1568 [03:48<00:45,  5.83it/s]16 03:25:17 Save the image 00869N.png
 83%|███████████████████████████████▌      | 1303/1568 [03:48<00:45,  5.81it/s]16 03:25:17 Save the image 00869N_flip.png
 83%|███████████████████████████████▌      | 1304/1568 [03:48<00:45,  5.81it/s]16 03:25:17 Save the image 00870N.png
 83%|███████████████████████████████▋      | 1305/1568 [03:48<00:44,  5.87it/s]16 03:25:18 Save the image 00870N_flip.png
 83%|███████████████████████████████▋      | 1306/1568 [03:48<00:44,  5.93it/s]16 03:25:18 Save the image 00871N.png
 83%|███████████████████████████████▋      | 1307/1568 [03:49<00:44,  5.89it/s]16 03:25:18 Save the image 00871N_flip.png
 83%|███████████████████████████████▋      | 1308/1568 [03:49<00:44,  5.86it/s]16 03:25:18 Save the image 00872N.png
 83%|███████████████████████████████▋      | 1309/1568 [03:49<00:44,  5.85it/s]16 03:25:18 Save the image 00872N_flip.png
 84%|███████████████████████████████▋      | 1310/1568 [03:49<00:44,  5.83it/s]16 03:25:18 Save the image 00873N.png
 84%|███████████████████████████████▊      | 1311/1568 [03:49<00:44,  5.82it/s]16 03:25:19 Save the image 00873N_flip.png
 84%|███████████████████████████████▊      | 1312/1568 [03:49<00:44,  5.80it/s]16 03:25:19 Save the image 00874N.png
 84%|███████████████████████████████▊      | 1313/1568 [03:50<00:43,  5.83it/s]16 03:25:19 Save the image 00874N_flip.png
 84%|███████████████████████████████▊      | 1314/1568 [03:50<00:42,  5.92it/s]16 03:25:19 Save the image 00875N.png
 84%|███████████████████████████████▊      | 1315/1568 [03:50<00:43,  5.88it/s]16 03:25:19 Save the image 00875N_flip.png
 84%|███████████████████████████████▉      | 1316/1568 [03:50<00:43,  5.86it/s]16 03:25:19 Save the image 00876N.png
 84%|███████████████████████████████▉      | 1317/1568 [03:50<00:42,  5.85it/s]16 03:25:20 Save the image 00876N_flip.png
 84%|███████████████████████████████▉      | 1318/1568 [03:50<00:42,  5.82it/s]16 03:25:20 Save the image 00877N.png
 84%|███████████████████████████████▉      | 1319/1568 [03:51<00:42,  5.81it/s]16 03:25:20 Save the image 00877N_flip.png
 84%|███████████████████████████████▉      | 1320/1568 [03:51<00:42,  5.80it/s]16 03:25:20 Save the image 00878N.png
 84%|████████████████████████████████      | 1321/1568 [03:51<00:42,  5.83it/s]16 03:25:20 Save the image 00878N_flip.png
 84%|████████████████████████████████      | 1322/1568 [03:51<00:41,  5.92it/s]16 03:25:20 Save the image 00879N.png
 84%|████████████████████████████████      | 1323/1568 [03:51<00:41,  5.88it/s]16 03:25:21 Save the image 00879N_flip.png
 84%|████████████████████████████████      | 1324/1568 [03:52<00:41,  5.86it/s]16 03:25:21 Save the image 00880N.png
 85%|████████████████████████████████      | 1325/1568 [03:52<00:41,  5.84it/s]16 03:25:21 Save the image 00880N_flip.png
 85%|████████████████████████████████▏     | 1326/1568 [03:52<00:41,  5.81it/s]16 03:25:21 Save the image 00881N.png
 85%|████████████████████████████████▏     | 1327/1568 [03:52<00:41,  5.80it/s]16 03:25:21 Save the image 00881N_flip.png
 85%|████████████████████████████████▏     | 1328/1568 [03:52<00:41,  5.79it/s]16 03:25:21 Save the image 00882N.png
 85%|████████████████████████████████▏     | 1329/1568 [03:52<00:41,  5.82it/s]16 03:25:22 Save the image 00882N_flip.png
 85%|████████████████████████████████▏     | 1330/1568 [03:53<00:40,  5.94it/s]16 03:25:22 Save the image 00883N.png
 85%|████████████████████████████████▎     | 1331/1568 [03:53<00:40,  5.86it/s]16 03:25:22 Save the image 00883N_flip.png
 85%|████████████████████████████████▎     | 1332/1568 [03:53<00:41,  5.75it/s]16 03:25:22 Save the image 00884N.png
 85%|████████████████████████████████▎     | 1333/1568 [03:53<00:40,  5.80it/s]16 03:25:22 Save the image 00884N_flip.png
 85%|████████████████████████████████▎     | 1334/1568 [03:53<00:40,  5.79it/s]16 03:25:23 Save the image 00885N.png
 85%|████████████████████████████████▎     | 1335/1568 [03:53<00:40,  5.77it/s]16 03:25:23 Save the image 00885N_flip.png
 85%|████████████████████████████████▍     | 1336/1568 [03:54<00:40,  5.77it/s]16 03:25:23 Save the image 00886N.png

 85%|████████████████████████████████▍     | 1337/1568 [03:54<00:39,  5.81it/s]16 03:25:23 Save the image 00886N_flip.png
 85%|████████████████████████████████▍     | 1338/1568 [03:54<00:38,  5.99it/s]16 03:25:23 Save the image 00887N.png
 85%|████████████████████████████████▍     | 1339/1568 [03:54<00:38,  5.91it/s]16 03:25:23 Save the image 00887N_flip.png
 85%|████████████████████████████████▍     | 1340/1568 [03:54<00:38,  5.88it/s]16 03:25:24 Save the image 00888N.png
 86%|████████████████████████████████▍     | 1341/1568 [03:54<00:38,  5.87it/s]16 03:25:24 Save the image 00888N_flip.png
 86%|████████████████████████████████▌     | 1342/1568 [03:55<00:38,  5.84it/s]16 03:25:24 Save the image 00889N.png
 86%|████████████████████████████████▌     | 1343/1568 [03:55<00:38,  5.82it/s]16 03:25:24 Save the image 00889N_flip.png
 86%|████████████████████████████████▌     | 1344/1568 [03:55<00:38,  5.80it/s]16 03:25:24 Save the image 00890N.png
 86%|████████████████████████████████▌     | 1345/1568 [03:55<00:38,  5.83it/s]16 03:25:24 Save the image 00890N_flip.png
 86%|████████████████████████████████▌     | 1346/1568 [03:55<00:37,  5.95it/s]16 03:25:25 Save the image 00891N.png
 86%|████████████████████████████████▋     | 1347/1568 [03:55<00:37,  5.85it/s]16 03:25:25 Save the image 00891N_flip.png
 86%|████████████████████████████████▋     | 1348/1568 [03:56<00:37,  5.84it/s]16 03:25:25 Save the image 00892N.png
 86%|████████████████████████████████▋     | 1349/1568 [03:56<00:37,  5.81it/s]16 03:25:25 Save the image 00892N_flip.png
 86%|████████████████████████████████▋     | 1350/1568 [03:56<00:37,  5.80it/s]16 03:25:25 Save the image 00893N.png
 86%|████████████████████████████████▋     | 1351/1568 [03:56<00:37,  5.79it/s]16 03:25:25 Save the image 00893N_flip.png
 86%|████████████████████████████████▊     | 1352/1568 [03:56<00:37,  5.78it/s]16 03:25:26 Save the image 00894N.png
 86%|████████████████████████████████▊     | 1353/1568 [03:56<00:36,  5.82it/s]16 03:25:26 Save the image 00894N_flip.png
 86%|████████████████████████████████▊     | 1354/1568 [03:57<00:35,  5.98it/s]16 03:25:26 Save the image 00895N.png
 86%|████████████████████████████████▊     | 1355/1568 [03:57<00:36,  5.90it/s]16 03:25:26 Save the image 00895N_flip.png
 86%|████████████████████████████████▊     | 1356/1568 [03:57<00:36,  5.88it/s]16 03:25:26 Save the image 00896N.png
 87%|████████████████████████████████▉     | 1357/1568 [03:57<00:35,  5.88it/s]16 03:25:26 Save the image 00896N_flip.png
 87%|████████████████████████████████▉     | 1358/1568 [03:57<00:35,  5.85it/s]16 03:25:27 Save the image 00897N.png
 87%|████████████████████████████████▉     | 1359/1568 [03:58<00:35,  5.83it/s]16 03:25:27 Save the image 00897N_flip.png
 87%|████████████████████████████████▉     | 1360/1568 [03:58<00:35,  5.78it/s]16 03:25:27 Save the image 00898N.png
 87%|████████████████████████████████▉     | 1361/1568 [03:58<00:35,  5.82it/s]16 03:25:27 Save the image 00898N_flip.png
 87%|█████████████████████████████████     | 1362/1568 [03:58<00:34,  5.94it/s]16 03:25:27 Save the image 00899N.png
 87%|█████████████████████████████████     | 1363/1568 [03:58<00:34,  5.86it/s]16 03:25:27 Save the image 00899N_flip.png
 87%|█████████████████████████████████     | 1364/1568 [03:58<00:34,  5.85it/s]16 03:25:28 Save the image 00900N.png
 87%|█████████████████████████████████     | 1365/1568 [03:59<00:34,  5.84it/s]16 03:25:28 Save the image 00900N_flip.png
 87%|█████████████████████████████████     | 1366/1568 [03:59<00:35,  5.70it/s]16 03:25:28 Save the image 00901N.png
 87%|█████████████████████████████████▏    | 1367/1568 [03:59<00:35,  5.69it/s]16 03:25:28 Save the image 00901N_flip.png
 87%|█████████████████████████████████▏    | 1368/1568 [03:59<00:35,  5.66it/s]16 03:25:28 Save the image 00902N.png
 87%|█████████████████████████████████▏    | 1369/1568 [03:59<00:34,  5.71it/s]16 03:25:29 Save the image 00902N_flip.png
 87%|█████████████████████████████████▏    | 1370/1568 [03:59<00:33,  5.83it/s]16 03:25:29 Save the image 00903N.png
 87%|█████████████████████████████████▏    | 1371/1568 [04:00<00:33,  5.80it/s]16 03:25:29 Save the image 00903N_flip.png
 88%|█████████████████████████████████▎    | 1372/1568 [04:00<00:33,  5.81it/s]16 03:25:29 Save the image 00904N.png
 88%|█████████████████████████████████▎    | 1373/1568 [04:00<00:33,  5.79it/s]16 03:25:29 Save the image 00904N_flip.png
 88%|█████████████████████████████████▎    | 1374/1568 [04:00<00:33,  5.76it/s]16 03:25:29 Save the image 00905N.png
 88%|█████████████████████████████████▎    | 1375/1568 [04:00<00:33,  5.77it/s]16 03:25:30 Save the image 00905N_flip.png
 88%|█████████████████████████████████▎    | 1376/1568 [04:00<00:33,  5.75it/s]16 03:25:30 Save the image 00906N.png
 88%|█████████████████████████████████▎    | 1377/1568 [04:01<00:32,  5.80it/s]16 03:25:30 Save the image 00906N_flip.png
 88%|█████████████████████████████████▍    | 1378/1568 [04:01<00:31,  5.94it/s]16 03:25:30 Save the image 00907N.png
 88%|█████████████████████████████████▍    | 1379/1568 [04:01<00:32,  5.82it/s]16 03:25:30 Save the image 00907N_flip.png
 88%|█████████████████████████████████▍    | 1380/1568 [04:01<00:32,  5.82it/s]16 03:25:30 Save the image 00908N.png
 88%|█████████████████████████████████▍    | 1381/1568 [04:01<00:32,  5.78it/s]16 03:25:31 Save the image 00908N_flip.png
 88%|█████████████████████████████████▍    | 1382/1568 [04:01<00:32,  5.77it/s]16 03:25:31 Save the image 00909N.png
 88%|█████████████████████████████████▌    | 1383/1568 [04:02<00:32,  5.77it/s]16 03:25:31 Save the image 00909N_flip.png
 88%|█████████████████████████████████▌    | 1384/1568 [04:02<00:32,  5.70it/s]16 03:25:31 Save the image 00910N.png
 88%|█████████████████████████████████▌    | 1385/1568 [04:02<00:31,  5.74it/s]16 03:25:31 Save the image 00910N_flip.png
 88%|█████████████████████████████████▌    | 1386/1568 [04:02<00:31,  5.85it/s]16 03:25:31 Save the image 00911N.png
 88%|█████████████████████████████████▌    | 1387/1568 [04:02<00:31,  5.74it/s]16 03:25:32 Save the image 00911N_flip.png
 89%|█████████████████████████████████▋    | 1388/1568 [04:03<00:31,  5.72it/s]16 03:25:32 Save the image 00912N.png
 89%|█████████████████████████████████▋    | 1389/1568 [04:03<00:31,  5.77it/s]16 03:25:32 Save the image 00912N_flip.png
 89%|█████████████████████████████████▋    | 1390/1568 [04:03<00:30,  5.76it/s]16 03:25:32 Save the image 00913N.png
 89%|█████████████████████████████████▋    | 1391/1568 [04:03<00:30,  5.77it/s]16 03:25:32 Save the image 00913N_flip.png
 89%|█████████████████████████████████▋    | 1392/1568 [04:03<00:30,  5.77it/s]16 03:25:33 Save the image 00914N.png
 89%|█████████████████████████████████▊    | 1393/1568 [04:03<00:30,  5.78it/s]16 03:25:33 Save the image 00914N_flip.png
 89%|█████████████████████████████████▊    | 1394/1568 [04:04<00:29,  5.89it/s]16 03:25:33 Save the image 00915N.png
 89%|█████████████████████████████████▊    | 1395/1568 [04:04<00:29,  5.83it/s]16 03:25:33 Save the image 00915N_flip.png
 89%|█████████████████████████████████▊    | 1396/1568 [04:04<00:29,  5.80it/s]16 03:25:33 Save the image 00916N.png
 89%|█████████████████████████████████▊    | 1397/1568 [04:04<00:29,  5.77it/s]16 03:25:33 Save the image 00916N_flip.png
 89%|█████████████████████████████████▉    | 1398/1568 [04:04<00:29,  5.75it/s]16 03:25:34 Save the image 00917N.png
 89%|█████████████████████████████████▉    | 1399/1568 [04:04<00:29,  5.75it/s]16 03:25:34 Save the image 00917N_flip.png
 89%|█████████████████████████████████▉    | 1400/1568 [04:05<00:29,  5.74it/s]16 03:25:34 Save the image 00918N.png

 89%|█████████████████████████████████▉    | 1401/1568 [04:05<00:28,  5.81it/s]16 03:25:34 Save the image 00918N_flip.png
 89%|█████████████████████████████████▉    | 1402/1568 [04:05<00:27,  6.05it/s]16 03:25:34 Save the image 00919N.png
 89%|██████████████████████████████████    | 1403/1568 [04:05<00:27,  5.93it/s]16 03:25:34 Save the image 00919N_flip.png
 90%|██████████████████████████████████    | 1404/1568 [04:05<00:27,  5.89it/s]16 03:25:35 Save the image 00920N.png
 90%|██████████████████████████████████    | 1405/1568 [04:05<00:27,  5.87it/s]16 03:25:35 Save the image 00920N_flip.png
 90%|██████████████████████████████████    | 1406/1568 [04:06<00:27,  5.82it/s]16 03:25:35 Save the image 00921N.png
 90%|██████████████████████████████████    | 1407/1568 [04:06<00:27,  5.80it/s]16 03:25:35 Save the image 00921N_flip.png
 90%|██████████████████████████████████    | 1408/1568 [04:06<00:27,  5.78it/s]16 03:25:35 Save the image 00922N.png
 90%|██████████████████████████████████▏   | 1409/1568 [04:06<00:27,  5.82it/s]16 03:25:35 Save the image 00922N_flip.png
 90%|██████████████████████████████████▏   | 1410/1568 [04:06<00:26,  5.91it/s]16 03:25:36 Save the image 00923N.png
 90%|██████████████████████████████████▏   | 1411/1568 [04:06<00:26,  5.84it/s]16 03:25:36 Save the image 00923N_flip.png
 90%|██████████████████████████████████▏   | 1412/1568 [04:07<00:26,  5.81it/s]16 03:25:36 Save the image 00924N.png
 90%|██████████████████████████████████▏   | 1413/1568 [04:07<00:26,  5.81it/s]16 03:25:36 Save the image 00924N_flip.png
 90%|██████████████████████████████████▎   | 1414/1568 [04:07<00:26,  5.75it/s]16 03:25:36 Save the image 00925N.png
 90%|██████████████████████████████████▎   | 1415/1568 [04:07<00:26,  5.73it/s]16 03:25:36 Save the image 00925N_flip.png
 90%|██████████████████████████████████▎   | 1416/1568 [04:07<00:26,  5.74it/s]16 03:25:37 Save the image 00926N.png
 90%|██████████████████████████████████▎   | 1417/1568 [04:08<00:26,  5.73it/s]16 03:25:37 Save the image 00926N_flip.png
 90%|██████████████████████████████████▎   | 1418/1568 [04:08<00:24,  6.09it/s]16 03:25:37 Save the image 00927N.png
 90%|██████████████████████████████████▍   | 1419/1568 [04:08<00:25,  5.96it/s]16 03:25:37 Save the image 00927N_flip.png
 91%|██████████████████████████████████▍   | 1420/1568 [04:08<00:25,  5.89it/s]16 03:25:37 Save the image 00928N.png
 91%|██████████████████████████████████▍   | 1421/1568 [04:08<00:24,  5.89it/s]16 03:25:37 Save the image 00928N_flip.png
 91%|██████████████████████████████████▍   | 1422/1568 [04:08<00:25,  5.83it/s]16 03:25:38 Save the image 00929N.png
 91%|██████████████████████████████████▍   | 1423/1568 [04:09<00:24,  5.80it/s]16 03:25:38 Save the image 00929N_flip.png
 91%|██████████████████████████████████▌   | 1424/1568 [04:09<00:24,  5.80it/s]16 03:25:38 Save the image 00930N.png
 91%|██████████████████████████████████▌   | 1425/1568 [04:09<00:24,  5.78it/s]16 03:25:38 Save the image 00930N_flip.png
 91%|██████████████████████████████████▌   | 1426/1568 [04:09<00:23,  6.11it/s]16 03:25:38 Save the image 00931N.png
 91%|██████████████████████████████████▌   | 1427/1568 [04:09<00:23,  5.95it/s]16 03:25:38 Save the image 00931N_flip.png
 91%|██████████████████████████████████▌   | 1428/1568 [04:09<00:23,  5.88it/s]16 03:25:39 Save the image 00932N.png
 91%|██████████████████████████████████▋   | 1429/1568 [04:10<00:23,  5.88it/s]16 03:25:39 Save the image 00932N_flip.png
 91%|██████████████████████████████████▋   | 1430/1568 [04:10<00:23,  5.82it/s]16 03:25:39 Save the image 00933N.png
 91%|██████████████████████████████████▋   | 1431/1568 [04:10<00:23,  5.80it/s]16 03:25:39 Save the image 00933N_flip.png
 91%|██████████████████████████████████▋   | 1432/1568 [04:10<00:23,  5.80it/s]16 03:25:39 Save the image 00934N.png
 91%|██████████████████████████████████▋   | 1433/1568 [04:10<00:23,  5.78it/s]16 03:25:39 Save the image 00934N_flip.png
 91%|██████████████████████████████████▊   | 1434/1568 [04:10<00:21,  6.12it/s]16 03:25:40 Save the image 00935N.png
 92%|██████████████████████████████████▊   | 1435/1568 [04:11<00:22,  5.98it/s]16 03:25:40 Save the image 00935N_flip.png
 92%|██████████████████████████████████▊   | 1436/1568 [04:11<00:22,  5.93it/s]16 03:25:40 Save the image 00936N.png
 92%|██████████████████████████████████▊   | 1437/1568 [04:11<00:22,  5.87it/s]16 03:25:40 Save the image 00936N_flip.png
 92%|██████████████████████████████████▊   | 1438/1568 [04:11<00:22,  5.83it/s]16 03:25:40 Save the image 00937N.png
 92%|██████████████████████████████████▊   | 1439/1568 [04:11<00:22,  5.81it/s]16 03:25:41 Save the image 00937N_flip.png
 92%|██████████████████████████████████▉   | 1440/1568 [04:11<00:22,  5.72it/s]16 03:25:41 Save the image 00938N.png
 92%|██████████████████████████████████▉   | 1441/1568 [04:12<00:22,  5.71it/s]16 03:25:41 Save the image 00938N_flip.png
 92%|██████████████████████████████████▉   | 1442/1568 [04:12<00:20,  6.07it/s]16 03:25:41 Save the image 00939N.png
 92%|██████████████████████████████████▉   | 1443/1568 [04:12<00:21,  5.94it/s]16 03:25:41 Save the image 00939N_flip.png
 92%|██████████████████████████████████▉   | 1444/1568 [04:12<00:21,  5.90it/s]16 03:25:41 Save the image 00940N.png
 92%|███████████████████████████████████   | 1445/1568 [04:12<00:20,  5.87it/s]16 03:25:42 Save the image 00940N_flip.png
 92%|███████████████████████████████████   | 1446/1568 [04:12<00:20,  5.84it/s]16 03:25:42 Save the image 00941N.png
 92%|███████████████████████████████████   | 1447/1568 [04:13<00:20,  5.82it/s]16 03:25:42 Save the image 00941N_flip.png
 92%|███████████████████████████████████   | 1448/1568 [04:13<00:20,  5.80it/s]16 03:25:42 Save the image 00942N.png
 92%|███████████████████████████████████   | 1449/1568 [04:13<00:20,  5.78it/s]16 03:25:42 Save the image 00942N_flip.png
 92%|███████████████████████████████████▏  | 1450/1568 [04:13<00:19,  6.10it/s]16 03:25:42 Save the image 00943N.png
 93%|███████████████████████████████████▏  | 1451/1568 [04:13<00:19,  5.96it/s]16 03:25:43 Save the image 00943N_flip.png
 93%|███████████████████████████████████▏  | 1452/1568 [04:13<00:19,  5.92it/s]16 03:25:43 Save the image 00944N.png
 93%|███████████████████████████████████▏  | 1453/1568 [04:14<00:19,  5.89it/s]16 03:25:43 Save the image 00944N_flip.png
 93%|███████████████████████████████████▏  | 1454/1568 [04:14<00:19,  5.85it/s]16 03:25:43 Save the image 00945N.png
 93%|███████████████████████████████████▎  | 1455/1568 [04:14<00:19,  5.82it/s]16 03:25:43 Save the image 00945N_flip.png
 93%|███████████████████████████████████▎  | 1456/1568 [04:14<00:19,  5.81it/s]16 03:25:43 Save the image 00946N.png
 93%|███████████████████████████████████▎  | 1457/1568 [04:14<00:19,  5.84it/s]16 03:25:44 Save the image 00946N_flip.png
 93%|███████████████████████████████████▎  | 1458/1568 [04:14<00:18,  6.04it/s]16 03:25:44 Save the image 00947N.png
 93%|███████████████████████████████████▎  | 1459/1568 [04:15<00:18,  5.92it/s]16 03:25:44 Save the image 00947N_flip.png
 93%|███████████████████████████████████▍  | 1460/1568 [04:15<00:18,  5.89it/s]16 03:25:44 Save the image 00948N.png
 93%|███████████████████████████████████▍  | 1461/1568 [04:15<00:18,  5.85it/s]16 03:25:44 Save the image 00948N_flip.png
 93%|███████████████████████████████████▍  | 1462/1568 [04:15<00:18,  5.83it/s]16 03:25:44 Save the image 00949N.png
 93%|███████████████████████████████████▍  | 1463/1568 [04:15<00:18,  5.80it/s]16 03:25:45 Save the image 00949N_flip.png
 93%|███████████████████████████████████▍  | 1464/1568 [04:16<00:17,  5.80it/s]16 03:25:45 Save the image 00950N.png

 93%|███████████████████████████████████▌  | 1465/1568 [04:16<00:17,  5.83it/s]16 03:25:45 Save the image 00950N_flip.png
 93%|███████████████████████████████████▌  | 1466/1568 [04:16<00:17,  5.98it/s]16 03:25:45 Save the image 00951N.png
 94%|███████████████████████████████████▌  | 1467/1568 [04:16<00:17,  5.93it/s]16 03:25:45 Save the image 00951N_flip.png
 94%|███████████████████████████████████▌  | 1468/1568 [04:16<00:16,  5.89it/s]16 03:25:45 Save the image 00952N.png
 94%|███████████████████████████████████▌  | 1469/1568 [04:16<00:16,  5.87it/s]16 03:25:46 Save the image 00952N_flip.png
 94%|███████████████████████████████████▋  | 1470/1568 [04:17<00:17,  5.76it/s]16 03:25:46 Save the image 00953N.png
 94%|███████████████████████████████████▋  | 1471/1568 [04:17<00:16,  5.76it/s]16 03:25:46 Save the image 00953N_flip.png
 94%|███████████████████████████████████▋  | 1472/1568 [04:17<00:16,  5.76it/s]16 03:25:46 Save the image 00954N.png
 94%|███████████████████████████████████▋  | 1473/1568 [04:17<00:16,  5.84it/s]16 03:25:46 Save the image 00954N_flip.png
 94%|███████████████████████████████████▋  | 1474/1568 [04:17<00:15,  6.00it/s]16 03:25:46 Save the image 00955N.png
 94%|███████████████████████████████████▋  | 1475/1568 [04:17<00:15,  5.91it/s]16 03:25:47 Save the image 00955N_flip.png
 94%|███████████████████████████████████▊  | 1476/1568 [04:18<00:15,  5.88it/s]16 03:25:47 Save the image 00956N.png
 94%|███████████████████████████████████▊  | 1477/1568 [04:18<00:15,  5.85it/s]16 03:25:47 Save the image 00956N_flip.png
 94%|███████████████████████████████████▊  | 1478/1568 [04:18<00:15,  5.83it/s]16 03:25:47 Save the image 00957N.png
 94%|███████████████████████████████████▊  | 1479/1568 [04:18<00:15,  5.82it/s]16 03:25:47 Save the image 00957N_flip.png
 94%|███████████████████████████████████▊  | 1480/1568 [04:18<00:15,  5.80it/s]16 03:25:48 Save the image 00958N.png
 94%|███████████████████████████████████▉  | 1481/1568 [04:18<00:14,  5.87it/s]16 03:25:48 Save the image 00958N_flip.png
 95%|███████████████████████████████████▉  | 1482/1568 [04:19<00:14,  5.96it/s]16 03:25:48 Save the image 00959N.png
 95%|███████████████████████████████████▉  | 1483/1568 [04:19<00:14,  5.91it/s]16 03:25:48 Save the image 00959N_flip.png
 95%|███████████████████████████████████▉  | 1484/1568 [04:19<00:14,  5.89it/s]16 03:25:48 Save the image 00960N.png
 95%|███████████████████████████████████▉  | 1485/1568 [04:19<00:14,  5.88it/s]16 03:25:48 Save the image 00960N_flip.png
 95%|████████████████████████████████████  | 1486/1568 [04:19<00:14,  5.84it/s]16 03:25:49 Save the image 00961N.png
 95%|████████████████████████████████████  | 1487/1568 [04:19<00:13,  5.82it/s]16 03:25:49 Save the image 00961N_flip.png
 95%|████████████████████████████████████  | 1488/1568 [04:20<00:13,  5.80it/s]16 03:25:49 Save the image 00962N.png
 95%|████████████████████████████████████  | 1489/1568 [04:20<00:13,  5.86it/s]16 03:25:49 Save the image 00962N_flip.png
 95%|████████████████████████████████████  | 1490/1568 [04:20<00:13,  5.96it/s]16 03:25:49 Save the image 00963N.png
 95%|████████████████████████████████████▏ | 1491/1568 [04:20<00:13,  5.91it/s]16 03:25:49 Save the image 00963N_flip.png
 95%|████████████████████████████████████▏ | 1492/1568 [04:20<00:12,  5.90it/s]16 03:25:50 Save the image 00964N.png
 95%|████████████████████████████████████▏ | 1493/1568 [04:20<00:12,  5.91it/s]16 03:25:50 Save the image 00964N_flip.png
 95%|████████████████████████████████████▏ | 1494/1568 [04:21<00:12,  5.89it/s]16 03:25:50 Save the image 00965N.png
 95%|████████████████████████████████████▏ | 1495/1568 [04:21<00:12,  5.85it/s]16 03:25:50 Save the image 00965N_flip.png
 95%|████████████████████████████████████▎ | 1496/1568 [04:21<00:12,  5.84it/s]16 03:25:50 Save the image 00966N.png
 95%|████████████████████████████████████▎ | 1497/1568 [04:21<00:12,  5.87it/s]16 03:25:50 Save the image 00966N_flip.png
 96%|████████████████████████████████████▎ | 1498/1568 [04:21<00:11,  5.89it/s]16 03:25:51 Save the image 00967N.png
 96%|████████████████████████████████████▎ | 1499/1568 [04:21<00:11,  5.86it/s]16 03:25:51 Save the image 00967N_flip.png
 96%|████████████████████████████████████▎ | 1500/1568 [04:22<00:11,  5.76it/s]16 03:25:51 Save the image 00968N.png
 96%|████████████████████████████████████▍ | 1501/1568 [04:22<00:11,  5.71it/s]16 03:25:51 Save the image 00968N_flip.png
 96%|████████████████████████████████████▍ | 1502/1568 [04:22<00:11,  5.70it/s]16 03:25:51 Save the image 00969N.png
 96%|████████████████████████████████████▍ | 1503/1568 [04:22<00:11,  5.68it/s]16 03:25:51 Save the image 00969N_flip.png
 96%|████████████████████████████████████▍ | 1504/1568 [04:22<00:11,  5.68it/s]16 03:25:52 Save the image 00970N.png
 96%|████████████████████████████████████▍ | 1505/1568 [04:23<00:10,  5.74it/s]16 03:25:52 Save the image 00970N_flip.png
 96%|████████████████████████████████████▍ | 1506/1568 [04:23<00:10,  5.74it/s]16 03:25:52 Save the image 00971N.png
 96%|████████████████████████████████████▌ | 1507/1568 [04:23<00:10,  5.74it/s]16 03:25:52 Save the image 00971N_flip.png
 96%|████████████████████████████████████▌ | 1508/1568 [04:23<00:10,  5.73it/s]16 03:25:52 Save the image 00972N.png
 96%|████████████████████████████████████▌ | 1509/1568 [04:23<00:10,  5.68it/s]16 03:25:53 Save the image 00972N_flip.png
 96%|████████████████████████████████████▌ | 1510/1568 [04:23<00:10,  5.67it/s]16 03:25:53 Save the image 00973N.png
 96%|████████████████████████████████████▌ | 1511/1568 [04:24<00:10,  5.66it/s]16 03:25:53 Save the image 00973N_flip.png
 96%|████████████████████████████████████▋ | 1512/1568 [04:24<00:09,  5.65it/s]16 03:25:53 Save the image 00974N.png
 96%|████████████████████████████████████▋ | 1513/1568 [04:24<00:09,  5.73it/s]16 03:25:53 Save the image 00974N_flip.png
 97%|████████████████████████████████████▋ | 1514/1568 [04:24<00:09,  5.72it/s]16 03:25:53 Save the image 00975N.png
 97%|████████████████████████████████████▋ | 1515/1568 [04:24<00:09,  5.68it/s]16 03:25:54 Save the image 00975N_flip.png
 97%|████████████████████████████████████▋ | 1516/1568 [04:24<00:09,  5.69it/s]16 03:25:54 Save the image 00976N.png
 97%|████████████████████████████████████▊ | 1517/1568 [04:25<00:08,  5.67it/s]16 03:25:54 Save the image 00976N_flip.png
 97%|████████████████████████████████████▊ | 1518/1568 [04:25<00:08,  5.63it/s]16 03:25:54 Save the image 00977N.png
 97%|████████████████████████████████████▊ | 1519/1568 [04:25<00:08,  5.65it/s]16 03:25:54 Save the image 00977N_flip.png
 97%|████████████████████████████████████▊ | 1520/1568 [04:25<00:08,  5.61it/s]16 03:25:54 Save the image 00978N.png
 97%|████████████████████████████████████▊ | 1521/1568 [04:25<00:08,  5.68it/s]16 03:25:55 Save the image 00978N_flip.png
 97%|████████████████████████████████████▉ | 1522/1568 [04:26<00:08,  5.72it/s]16 03:25:55 Save the image 00979N.png
 97%|████████████████████████████████████▉ | 1523/1568 [04:26<00:07,  5.68it/s]16 03:25:55 Save the image 00979N_flip.png
 97%|████████████████████████████████████▉ | 1524/1568 [04:26<00:07,  5.69it/s]16 03:25:55 Save the image 00980N.png
 97%|████████████████████████████████████▉ | 1525/1568 [04:26<00:07,  5.73it/s]16 03:25:55 Save the image 00980N_flip.png
 97%|████████████████████████████████████▉ | 1526/1568 [04:26<00:07,  5.74it/s]16 03:25:56 Save the image 00981N.png
 97%|█████████████████████████████████████ | 1527/1568 [04:26<00:07,  5.74it/s]16 03:25:56 Save the image 00981N_flip.png
 97%|█████████████████████████████████████ | 1528/1568 [04:27<00:06,  5.75it/s]16 03:25:56 Save the image 00982N.png

 98%|█████████████████████████████████████ | 1529/1568 [04:27<00:06,  5.82it/s]16 03:25:56 Save the image 00982N_flip.png
 98%|█████████████████████████████████████ | 1530/1568 [04:27<00:06,  5.86it/s]16 03:25:56 Save the image 00983N.png
 98%|█████████████████████████████████████ | 1531/1568 [04:27<00:06,  5.78it/s]16 03:25:56 Save the image 00983N_flip.png
 98%|█████████████████████████████████████▏| 1532/1568 [04:27<00:06,  5.80it/s]16 03:25:57 Save the image 00984N.png
 98%|█████████████████████████████████████▏| 1533/1568 [04:27<00:06,  5.80it/s]16 03:25:57 Save the image 00984N_flip.png
 98%|█████████████████████████████████████▏| 1534/1568 [04:28<00:05,  5.72it/s]16 03:25:57 Save the image 00985N.png
 98%|█████████████████████████████████████▏| 1535/1568 [04:28<00:05,  5.69it/s]16 03:25:57 Save the image 00985N_flip.png
 98%|█████████████████████████████████████▏| 1536/1568 [04:28<00:05,  5.72it/s]16 03:25:57 Save the image 00986N.png
 98%|█████████████████████████████████████▏| 1537/1568 [04:28<00:05,  5.75it/s]16 03:25:57 Save the image 00986N_flip.png
 98%|█████████████████████████████████████▎| 1538/1568 [04:28<00:05,  5.77it/s]16 03:25:58 Save the image 00987N.png
 98%|█████████████████████████████████████▎| 1539/1568 [04:28<00:05,  5.73it/s]16 03:25:58 Save the image 00987N_flip.png
 98%|█████████████████████████████████████▎| 1540/1568 [04:29<00:04,  5.72it/s]16 03:25:58 Save the image 00988N.png
 98%|█████████████████████████████████████▎| 1541/1568 [04:29<00:04,  5.74it/s]16 03:25:58 Save the image 00988N_flip.png
 98%|█████████████████████████████████████▎| 1542/1568 [04:29<00:04,  5.74it/s]16 03:25:58 Save the image 00989N.png
 98%|█████████████████████████████████████▍| 1543/1568 [04:29<00:04,  5.71it/s]16 03:25:58 Save the image 00989N_flip.png
 98%|█████████████████████████████████████▍| 1544/1568 [04:29<00:04,  5.68it/s]16 03:25:59 Save the image 00990N.png
 99%|█████████████████████████████████████▍| 1545/1568 [04:30<00:04,  5.74it/s]16 03:25:59 Save the image 00990N_flip.png
 99%|█████████████████████████████████████▍| 1546/1568 [04:30<00:03,  5.71it/s]16 03:25:59 Save the image 00991N.png
 99%|█████████████████████████████████████▍| 1547/1568 [04:30<00:03,  5.66it/s]16 03:25:59 Save the image 00991N_flip.png
 99%|█████████████████████████████████████▌| 1548/1568 [04:30<00:03,  5.68it/s]16 03:25:59 Save the image 00992N.png
 99%|█████████████████████████████████████▌| 1549/1568 [04:30<00:03,  5.69it/s]16 03:26:00 Save the image 00992N_flip.png
 99%|█████████████████████████████████████▌| 1550/1568 [04:30<00:03,  5.69it/s]16 03:26:00 Save the image 00993N.png
 99%|█████████████████████████████████████▌| 1551/1568 [04:31<00:02,  5.68it/s]16 03:26:00 Save the image 00993N_flip.png
 99%|█████████████████████████████████████▌| 1552/1568 [04:31<00:02,  5.67it/s]16 03:26:00 Save the image 00994N.png
 99%|█████████████████████████████████████▋| 1553/1568 [04:31<00:02,  5.75it/s]16 03:26:00 Save the image 00994N_flip.png
 99%|█████████████████████████████████████▋| 1554/1568 [04:31<00:02,  5.76it/s]16 03:26:00 Save the image 00995N.png
 99%|█████████████████████████████████████▋| 1555/1568 [04:31<00:02,  5.72it/s]16 03:26:01 Save the image 00995N_flip.png
 99%|█████████████████████████████████████▋| 1556/1568 [04:31<00:02,  5.68it/s]16 03:26:01 Save the image 00996N.png
 99%|█████████████████████████████████████▋| 1557/1568 [04:32<00:01,  5.66it/s]16 03:26:01 Save the image 00996N_flip.png
 99%|█████████████████████████████████████▊| 1558/1568 [04:32<00:01,  5.65it/s]16 03:26:01 Save the image 00997N.png
 99%|█████████████████████████████████████▊| 1559/1568 [04:32<00:01,  5.68it/s]16 03:26:01 Save the image 00997N_flip.png
 99%|█████████████████████████████████████▊| 1560/1568 [04:32<00:01,  5.65it/s]16 03:26:01 Save the image 00998N.png
100%|█████████████████████████████████████▊| 1561/1568 [04:32<00:01,  5.69it/s]16 03:26:02 Save the image 00998N_flip.png
100%|█████████████████████████████████████▊| 1562/1568 [04:33<00:01,  5.79it/s]16 03:26:02 Save the image 00999N.png
100%|█████████████████████████████████████▉| 1563/1568 [04:33<00:00,  5.73it/s]16 03:26:02 Save the image 00999N_flip.png
100%|█████████████████████████████████████▉| 1564/1568 [04:33<00:00,  5.73it/s]16 03:26:02 Save the image 01000N.png
100%|█████████████████████████████████████▉| 1565/1568 [04:33<00:00,  5.75it/s]16 03:26:02 Save the image 01000N_flip.png
100%|█████████████████████████████████████▉| 1566/1568 [04:33<00:00,  5.75it/s]16 03:26:02 Save the image 01001N.png
100%|█████████████████████████████████████▉| 1567/1568 [04:33<00:00,  5.75it/s]16 03:26:03 Save the image 01001N_flip.png
100%|██████████████████████████████████████| 1568/1568 [04:34<00:00,  5.72it/s]
1 unlabeled	99.729%
2 car   	98.371%
3 person	93.343%
4 bike  	94.276%
5 curve 	95.114%
6 car_stop	96.096%
7 guardrail	97.956%
8 color_cone	91.805%
9 bump  	97.413%
----------     mean_IoU	96.011%	freq_IoU	99.483%	mean_pixel_acc	98.149%	pixel_acc	99.738%
16 03:26:03 Evaluation Elapsed Time: 274.06s

# e5

In [23]:
import os

checkpoint = "/home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2_e5/checkpoint/epoch-100.pth"

print("Checkpoint exists:", os.path.exists(checkpoint))

if os.path.exists(checkpoint):
    print(f"Checkpoint size: {os.path.getsize(checkpoint) / (1024**3):.2f} GB")

Checkpoint exists: True
Checkpoint size: 0.75 GB

In [24]:
import os

base = "/home/cse-sdpl/Downloads/CMX_E5"

print("E5 directory exists:", os.path.isdir(base))
print("\nFiles in E5 directory:")

for item in os.listdir(base):
    print(item)

print("\nEvaluation scripts:")
for root, dirs, files in os.walk(base):
    dirs[:] = [d for d in dirs if d not in ["datasets", ".git", "__pycache__"]]
    for file in files:
        if file in ["eval.py", "test.py", "evaluate.py"]:
            print(os.path.join(root, file))

E5 directory exists: True

Files in E5 directory:
config.py
pretraining_backups
.gitignore
eval.py
CMX_Original_Test.ipynb
train.py.pre_e3_init_backup
e1_predictions
CMX_E0_E1_E2_Complete_Comparison.ipynb
train.py
eval.py.repair.bak
utils
config.py.e2_backup
config.py.pre_e5.bak
E2_Learnable_Weighted_Fusion.ipynb
official_checkpoints
eval.ipynb
Untitled.ipynb
pretrained
config.py.pre_e3_backup
results
train.py.e2_backup
train.py.backup
LICENSE
__pycache__
e1_predictions_color
config.py.pre_final_e5.bak
config.py.repair.bak
e5trainig.ipynb
README.md
train.py.pre_e5_init.bak
train.py.before_e4_transfer.bak
config.py.pre_counterfactual.bak
dataloader
engine
.ipynb_checkpoints
E3_Corruption_Aware_Reliability_Fusion.ipynb
segmentation.jpg
train.py.before_e4_audit.bak
CMX_Official_Baseline_Comparison.ipynb
log_TDD_mit_b2_e5
requirements.txt
train.py.pre_optimizer_audit_backup
models
comparison_results

Evaluation scripts:
/home/cse-sdpl/Downloads/CMX_E5/eval.py

In [25]:
cd /home/cse-sdpl/Downloads/CMX_E5

python eval.py --help

grep -nE 'backbone|dataset|checkpoint|num_classes|test|val|split|argparse' eval.py config.py

SyntaxError: invalid syntax (1345769112.py, line 3)

In [26]:

%cd /home/cse-sdpl/Downloads/CMX_E5

!python eval.py --help

/home/cse-sdpl/Downloads/CMX_E5

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
usage: eval.py [-h] [-e EPOCHS] [-d DEVICES] [-v] [--show_image]
               [--save_path SAVE_PATH] [--split {train,val,test}]

options:
  -h, --help            show this help message and exit
  -e EPOCHS, --epochs EPOCHS
  -d DEVICES, --devices DEVICES
  -v, --verbose
  --show_image, -s
  --save_path SAVE_PATH, -p SAVE_PATH
  --split {train,val,test}

In [27]:

!grep -nE 'backbone|dataset|checkpoint|num_classes|test|val|split|argparse' eval.py config.py

eval.py:4:import argparse
eval.py:13:from engine.evaluator import Evaluator
eval.py:22:class SegEvaluator(Evaluator):
eval.py:28:        pred = self.sliding_eval_rgbX(img, modal_x, config.eval_crop_size, config.eval_stride_rate, device)
eval.py:29:        hist_tmp, labeled_tmp, correct_tmp = hist_info(config.num_classes, pred, label)
eval.py:45:            colors = self.dataset.get_class_colors
eval.py:57:        hist = np.zeros((config.num_classes, config.num_classes))
eval.py:69:                                dataset.class_names, show_no_back=False)
eval.py:73:    parser = argparse.ArgumentParser()
eval.py:81:    parser.add_argument('--split', choices=['train', 'val', 'test'], default='val')
eval.py:96:                    'eval_source': config.eval_source,
eval.py:97:                    'test_source': config.test_source,
eval.py:99:    val_pre = ValPre()
eval.py:100:    dataset = RGBXDataset(data_setting, args.split, val_pre)
eval.py:103:        segmentor = SegEvaluator(dataset, config.num_classes, config.norm_mean,
eval.py:105:                                 config.eval_scale_array, config.eval_flip,
eval.py:108:        segmentor.run(config.checkpoint_dir, args.epochs, config.val_log_file,
eval.py:109:                      config.link_val_log_file)
config.py:8:import argparse
config.py:25:C.dataset_name = 'TDD'
config.py:26:C.dataset_path = '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD'
config.py:29:C.rgb_root_folder = osp.join(C.dataset_path, 'RGB')
config.py:33:C.gt_root_folder = osp.join(C.dataset_path, 'Label')
config.py:38:C.x_root_folder = osp.join(C.dataset_path, 'Thermal')
config.py:42:# Dataset split files
config.py:43:C.train_source = osp.join(C.dataset_path, 'train.txt')
config.py:44:C.eval_source = osp.join(C.dataset_path, 'val.txt')
config.py:45:C.test_source = osp.join(C.dataset_path, 'test.txt')
config.py:46:C.is_test = False
config.py:50:C.num_eval_imgs = 392
config.py:53:C.num_classes = 9
config.py:81:C.backbone = 'mit_b2_e5'
config.py:113:C.eval_iter = 25
config.py:114:C.eval_stride_rate = 2 / 3
config.py:115:C.eval_scale_array = [1]
config.py:116:C.eval_flip = False
config.py:117:C.eval_crop_size = [480, 640]
config.py:122:C.checkpoint_start_epoch = 1
config.py:123:C.checkpoint_step = 5
config.py:138:    'log_' + C.dataset_name + '_' + C.backbone
config.py:143:C.checkpoint_dir = osp.join(C.log_dir, 'checkpoint')
config.py:152:C.val_log_file = osp.join(
config.py:153:    C.log_dir, 'val_' + exp_time + '.log'
config.py:155:C.link_val_log_file = osp.join(C.log_dir, 'val_last.log')
config.py:161:    print('Dataset:', C.dataset_name)
config.py:162:    print('Dataset path:', C.dataset_path)
config.py:163:    print('Backbone:', C.backbone)
config.py:165:    print('Number of classes:', C.num_classes)
config.py:167:    print('Validation images:', C.num_eval_imgs)
config.py:171:    parser = argparse.ArgumentParser()
config.py:182:# Experimental starting values; validate before full training.

In [28]:

%cd /home/cse-sdpl/Downloads/CMX_E5

!python eval.py -e 100 -d 0 --split test -p predictions_E5_test

/home/cse-sdpl/Downloads/CMX_E5
/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 19:07:47 using devices 0
16 19:07:47 Using E5: SegFormer-B2 with counterfactual reliability
16 19:07:48 Using MLP Decoder
16 19:07:50 Load Model: /home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2_e5/checkpoint/epoch-100.pth
16 19:07:51 Load model, Time usage:
	IO: 0.751262903213501, initialize parameters: 0.042250633239746094
16 19:07:51 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@7.081] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 19:07:52 Save the image 01402D.png
  0%|                                          | 1/393 [00:01<08:43,  1.34s/it]16 19:07:52 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:01<03:59,  1.63it/s]16 19:07:52 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:01<02:28,  2.62it/s]16 19:07:53 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:01<01:45,  3.68it/s]16 19:07:53 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:01<01:21,  4.75it/s]16 19:07:53 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:01<01:07,  5.76it/s]16 19:07:53 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:01<00:57,  6.67it/s]16 19:07:53 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:02<00:51,  7.43it/s]16 19:07:53 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:02<00:47,  8.04it/s]16 19:07:53 Save the image 01411D.png
  3%|█                                        | 10/393 [00:02<00:45,  8.46it/s]16 19:07:53 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:02<00:43,  8.73it/s]16 19:07:53 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:02<00:42,  8.92it/s]16 19:07:54 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:02<00:42,  9.02it/s]16 19:07:54 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:02<00:41,  9.15it/s]16 19:07:54 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:02<00:40,  9.30it/s]16 19:07:54 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:02<00:40,  9.42it/s]16 19:07:54 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:03<00:39,  9.49it/s]16 19:07:54 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:03<00:39,  9.53it/s]16 19:07:54 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:03<00:39,  9.59it/s]16 19:07:54 Save the image 01421D.png
  5%|██                                       | 20/393 [00:03<00:38,  9.61it/s]16 19:07:54 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:03<00:38,  9.63it/s]16 19:07:54 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:03<00:38,  9.67it/s]16 19:07:55 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:03<00:38,  9.68it/s]16 19:07:55 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:03<00:38,  9.67it/s]16 19:07:55 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:03<00:38,  9.67it/s]16 19:07:55 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:03<00:37,  9.69it/s]16 19:07:55 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:04<00:37,  9.69it/s]16 19:07:55 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:04<00:37,  9.72it/s]16 19:07:55 Save the image 01430D.png
  7%|███                                      | 29/393 [00:04<00:38,  9.52it/s]16 19:07:55 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:04<00:37,  9.57it/s]16 19:07:55 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:04<00:37,  9.61it/s]16 19:07:55 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:04<00:37,  9.63it/s]16 19:07:56 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:04<00:37,  9.64it/s]16 19:07:56 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:04<00:37,  9.66it/s]16 19:07:56 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:04<00:36,  9.68it/s]16 19:07:56 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:04<00:36,  9.69it/s]16 19:07:56 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:05<00:36,  9.69it/s]16 19:07:56 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:05<00:36,  9.61it/s]16 19:07:56 Save the image 01440D.png
 10%|████                                     | 39/393 [00:05<00:37,  9.55it/s]16 19:07:56 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:05<00:37,  9.48it/s]16 19:07:56 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:05<00:36,  9.52it/s]16 19:07:57 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:05<00:36,  9.59it/s]16 19:07:57 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:05<00:36,  9.54it/s]16 19:07:57 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:05<00:36,  9.50it/s]16 19:07:57 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:05<00:36,  9.53it/s]16 19:07:57 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:06<00:36,  9.60it/s]16 19:07:57 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:06<00:36,  9.53it/s]16 19:07:57 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:06<00:36,  9.51it/s]16 19:07:57 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:06<00:35,  9.57it/s]16 19:07:57 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:06<00:35,  9.58it/s]16 19:07:57 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:06<00:35,  9.62it/s]16 19:07:58 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:06<00:35,  9.62it/s]16 19:07:58 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:06<00:35,  9.61it/s]16 19:07:58 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:06<00:35,  9.50it/s]16 19:07:58 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:06<00:35,  9.44it/s]16 19:07:58 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:07<00:35,  9.40it/s]16 19:07:58 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:07<00:35,  9.36it/s]16 19:07:58 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:07<00:35,  9.43it/s]16 19:07:58 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:07<00:35,  9.49it/s]16 19:07:58 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:07<00:35,  9.48it/s]16 19:07:59 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:07<00:35,  9.46it/s]16 19:07:59 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:07<00:35,  9.41it/s]16 19:07:59 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:07<00:34,  9.47it/s]16 19:07:59 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:07<00:34,  9.45it/s]16 19:07:59 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:08<00:34,  9.40it/s]16 19:07:59 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:08<00:34,  9.48it/s]16 19:07:59 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:08<00:34,  9.44it/s]16 19:07:59 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:08<00:34,  9.39it/s]16 19:07:59 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:08<00:34,  9.42it/s]16 19:07:59 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:08<00:34,  9.40it/s]16 19:08:00 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:08<00:34,  9.37it/s]16 19:08:00 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:08<00:33,  9.45it/s]16 19:08:00 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:08<00:33,  9.45it/s]16 19:08:00 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:08<00:33,  9.42it/s]16 19:08:00 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:09<00:33,  9.39it/s]16 19:08:00 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:09<00:33,  9.47it/s]16 19:08:00 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:09<00:33,  9.44it/s]16 19:08:00 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:09<00:33,  9.39it/s]16 19:08:00 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:09<00:33,  9.46it/s]16 19:08:01 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:09<00:33,  9.44it/s]16 19:08:01 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:09<00:33,  9.38it/s]16 19:08:01 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:09<00:33,  9.42it/s]16 19:08:01 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:09<00:32,  9.48it/s]16 19:08:01 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:10<00:32,  9.43it/s]16 19:08:01 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:10<00:32,  9.41it/s]16 19:08:01 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:10<00:32,  9.33it/s]16 19:08:01 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:10<00:32,  9.31it/s]16 19:08:01 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:10<00:32,  9.31it/s]16 19:08:02 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:10<00:32,  9.31it/s]16 19:08:02 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:10<00:32,  9.39it/s]16 19:08:02 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:10<00:31,  9.49it/s]16 19:08:02 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:10<00:31,  9.54it/s]16 19:08:02 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:10<00:31,  9.60it/s]16 19:08:02 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:11<00:31,  9.64it/s]16 19:08:02 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:11<00:30,  9.64it/s]16 19:08:02 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:11<00:30,  9.64it/s]16 19:08:02 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:11<00:30,  9.64it/s]16 19:08:02 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:11<00:30,  9.65it/s]16 19:08:03 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:11<00:30,  9.65it/s]16 19:08:03 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:11<00:30,  9.62it/s]16 19:08:03 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:11<00:30,  9.64it/s]16 19:08:03 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:11<00:30,  9.65it/s]16 19:08:03 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:12<00:29,  9.68it/s]16 19:08:03 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:12<00:29,  9.68it/s]16 19:08:03 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:12<00:29,  9.65it/s]16 19:08:03 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:12<00:29,  9.66it/s]16 19:08:03 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:12<00:29,  9.66it/s]16 19:08:03 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:12<00:29,  9.69it/s]16 19:08:04 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:12<00:29,  9.74it/s]16 19:08:04 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:12<00:29,  9.69it/s]16 19:08:04 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:12<00:29,  9.69it/s]16 19:08:04 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:12<00:28,  9.70it/s]16 19:08:04 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:13<00:28,  9.69it/s]16 19:08:04 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:13<00:28,  9.69it/s]16 19:08:04 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:13<00:28,  9.68it/s]16 19:08:04 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:13<00:28,  9.65it/s]16 19:08:04 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:13<00:28,  9.66it/s]16 19:08:05 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:13<00:28,  9.66it/s]16 19:08:05 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:13<00:28,  9.65it/s]16 19:08:05 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:13<00:28,  9.64it/s]16 19:08:05 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:13<00:28,  9.64it/s]16 19:08:05 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:13<00:28,  9.67it/s]16 19:08:05 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:14<00:27,  9.67it/s]16 19:08:05 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:14<00:27,  9.67it/s]16 19:08:05 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:14<00:27,  9.66it/s]16 19:08:05 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:14<00:27,  9.67it/s]16 19:08:05 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:14<00:27,  9.69it/s]16 19:08:06 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:14<00:27,  9.69it/s]16 19:08:06 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:14<00:27,  9.69it/s]16 19:08:06 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:14<00:27,  9.68it/s]16 19:08:06 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:14<00:27,  9.65it/s]16 19:08:06 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:15<00:26,  9.67it/s]16 19:08:06 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:15<00:26,  9.67it/s]16 19:08:06 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:15<00:26,  9.66it/s]16 19:08:06 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:15<00:27,  9.46it/s]16 19:08:06 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:15<00:27,  9.48it/s]16 19:08:06 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:15<00:26,  9.53it/s]16 19:08:07 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:15<00:26,  9.59it/s]16 19:08:07 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:15<00:26,  9.61it/s]16 19:08:07 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:15<00:26,  9.64it/s]16 19:08:07 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:15<00:26,  9.61it/s]16 19:08:07 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:16<00:26,  9.64it/s]16 19:08:07 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:16<00:25,  9.64it/s]16 19:08:07 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:16<00:25,  9.65it/s]16 19:08:07 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:16<00:25,  9.67it/s]16 19:08:07 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:16<00:25,  9.63it/s]16 19:08:08 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:16<00:25,  9.64it/s]16 19:08:08 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:16<00:25,  9.65it/s]16 19:08:08 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:16<00:25,  9.67it/s]16 19:08:08 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:16<00:25,  9.67it/s]16 19:08:08 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:16<00:25,  9.64it/s]16 19:08:08 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:17<00:24,  9.66it/s]16 19:08:08 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:17<00:24,  9.65it/s]16 19:08:08 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:17<00:24,  9.65it/s]16 19:08:08 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:17<00:24,  9.65it/s]16 19:08:08 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:17<00:24,  9.61it/s]16 19:08:09 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:17<00:24,  9.61it/s]16 19:08:09 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:17<00:24,  9.65it/s]16 19:08:09 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:17<00:24,  9.66it/s]16 19:08:09 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:17<00:24,  9.66it/s]16 19:08:09 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:18<00:23,  9.67it/s]16 19:08:09 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:18<00:23,  9.66it/s]16 19:08:09 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:18<00:23,  9.68it/s]16 19:08:09 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:18<00:23,  9.68it/s]16 19:08:09 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:18<00:23,  9.67it/s]16 19:08:09 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:18<00:23,  9.66it/s]16 19:08:10 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:18<00:23,  9.64it/s]16 19:08:10 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:18<00:23,  9.65it/s]16 19:08:10 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:18<00:23,  9.66it/s]16 19:08:10 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:18<00:23,  9.56it/s]16 19:08:10 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:19<00:23,  9.60it/s]16 19:08:10 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:19<00:22,  9.64it/s]16 19:08:10 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:19<00:22,  9.69it/s]16 19:08:10 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:19<00:22,  9.70it/s]16 19:08:10 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:19<00:22,  9.70it/s]16 19:08:11 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:19<00:22,  9.71it/s]16 19:08:11 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:19<00:22,  9.68it/s]16 19:08:11 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:19<00:22,  9.69it/s]16 19:08:11 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:19<00:22,  9.69it/s]16 19:08:11 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:20<00:21,  9.69it/s]16 19:08:11 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:20<00:21,  9.67it/s]16 19:08:11 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:20<00:21,  9.68it/s]16 19:08:11 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:20<00:21,  9.67it/s]16 19:08:11 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:20<00:21,  9.69it/s]16 19:08:11 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:20<00:21,  9.65it/s]16 19:08:12 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:20<00:21,  9.65it/s]16 19:08:12 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:20<00:21,  9.65it/s]16 19:08:12 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:20<00:21,  9.66it/s]16 19:08:12 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:20<00:21,  9.66it/s]16 19:08:12 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:21<00:21,  9.65it/s]16 19:08:12 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:21<00:20,  9.66it/s]16 19:08:12 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:21<00:20,  9.62it/s]16 19:08:12 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:21<00:20,  9.65it/s]16 19:08:12 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:21<00:20,  9.66it/s]16 19:08:12 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:21<00:20,  9.65it/s]16 19:08:13 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:21<00:20,  9.67it/s]16 19:08:13 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:21<00:20,  9.66it/s]16 19:08:13 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:21<00:20,  9.68it/s]16 19:08:13 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:21<00:19,  9.70it/s]16 19:08:13 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:22<00:19,  9.69it/s]16 19:08:13 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:22<00:19,  9.69it/s]16 19:08:13 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:22<00:19,  9.68it/s]16 19:08:13 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:22<00:19,  9.67it/s]16 19:08:13 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:22<00:19,  9.66it/s]16 19:08:14 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:22<00:19,  9.67it/s]16 19:08:14 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:22<00:19,  9.72it/s]16 19:08:14 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:22<00:19,  9.73it/s]16 19:08:14 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:22<00:19,  9.72it/s]16 19:08:14 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:22<00:18,  9.77it/s]16 19:08:14 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:23<00:18,  9.77it/s]16 19:08:14 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:23<00:18,  9.78it/s]16 19:08:14 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:23<00:18,  9.76it/s]16 19:08:14 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:23<00:18,  9.75it/s]16 19:08:14 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:23<00:18,  9.75it/s]16 19:08:15 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:23<00:18,  9.77it/s]16 19:08:15 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:23<00:18,  9.81it/s]16 19:08:15 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:23<00:17,  9.83it/s]16 19:08:15 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:23<00:17,  9.84it/s]16 19:08:15 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:24<00:17,  9.81it/s]16 19:08:15 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:24<00:17,  9.77it/s]16 19:08:15 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:24<00:17,  9.74it/s]16 19:08:15 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:24<00:17,  9.64it/s]16 19:08:15 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:24<00:17,  9.65it/s]16 19:08:15 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:24<00:17,  9.70it/s]16 19:08:16 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:24<00:17,  9.72it/s]16 19:08:16 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:24<00:17,  9.77it/s]16 19:08:16 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:24<00:16,  9.82it/s]16 19:08:16 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:24<00:16,  9.82it/s]16 19:08:16 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:25<00:16,  9.82it/s]16 19:08:16 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:25<00:16,  9.83it/s]16 19:08:16 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:25<00:16,  9.86it/s]16 19:08:16 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:25<00:16,  9.85it/s]16 19:08:16 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:25<00:16,  9.82it/s]16 19:08:16 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:25<00:16,  9.82it/s]16 19:08:17 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:25<00:16,  9.82it/s]16 19:08:17 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:25<00:15,  9.83it/s]16 19:08:17 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:25<00:15,  9.82it/s]16 19:08:17 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:25<00:15,  9.82it/s]16 19:08:17 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:26<00:15,  9.82it/s]16 19:08:17 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:26<00:15,  9.82it/s]16 19:08:17 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:26<00:15,  9.83it/s]16 19:08:17 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:26<00:15,  9.81it/s]16 19:08:17 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:26<00:15,  9.80it/s]16 19:08:18 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:26<00:15,  9.76it/s]16 19:08:18 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:26<00:15,  9.74it/s]16 19:08:18 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:26<00:15,  9.74it/s]16 19:08:18 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:26<00:14,  9.75it/s]16 19:08:18 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:26<00:14,  9.75it/s]16 19:08:18 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:27<00:14,  9.74it/s]16 19:08:18 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:27<00:14,  9.76it/s]16 19:08:18 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:27<00:14,  9.77it/s]16 19:08:18 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:27<00:14,  9.74it/s]16 19:08:18 Save the image 01236N.png

 64%|█████████████████████████▊              | 253/393 [00:27<00:14,  9.73it/s]16 19:08:19 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:27<00:14,  9.71it/s]16 19:08:19 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:27<00:14,  9.75it/s]16 19:08:19 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:27<00:13,  9.80it/s]16 19:08:19 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:27<00:13,  9.83it/s]16 19:08:19 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:28<00:13,  9.87it/s]16 19:08:19 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:28<00:13,  9.85it/s]16 19:08:19 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:28<00:13,  9.85it/s]16 19:08:19 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:28<00:13,  9.88it/s]16 19:08:19 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:28<00:13,  9.87it/s]16 19:08:19 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:28<00:13,  9.87it/s]16 19:08:20 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:28<00:13,  9.65it/s]16 19:08:20 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:28<00:13,  9.68it/s]16 19:08:20 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:28<00:13,  9.72it/s]16 19:08:20 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:28<00:12,  9.74it/s]16 19:08:20 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:29<00:12,  9.77it/s]16 19:08:20 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:29<00:12,  9.77it/s]16 19:08:20 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:29<00:12,  9.79it/s]16 19:08:20 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:29<00:12,  9.79it/s]16 19:08:20 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:29<00:12,  9.77it/s]16 19:08:20 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:29<00:12,  9.78it/s]16 19:08:21 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:29<00:12,  9.82it/s]16 19:08:21 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:29<00:12,  9.80it/s]16 19:08:21 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:29<00:11,  9.83it/s]16 19:08:21 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:29<00:11,  9.80it/s]16 19:08:21 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:30<00:11,  9.80it/s]16 19:08:21 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:30<00:11,  9.78it/s]16 19:08:21 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:30<00:11,  9.72it/s]16 19:08:21 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:30<00:11,  9.74it/s]16 19:08:21 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:30<00:11,  9.75it/s]16 19:08:21 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:30<00:11,  9.77it/s]16 19:08:22 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:30<00:11,  9.77it/s]16 19:08:22 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:30<00:11,  9.79it/s]16 19:08:22 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:30<00:10,  9.77it/s]16 19:08:22 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:30<00:10,  9.77it/s]16 19:08:22 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:31<00:10,  9.77it/s]16 19:08:22 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:31<00:10,  9.77it/s]16 19:08:22 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:31<00:10,  9.77it/s]16 19:08:22 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:31<00:10,  9.79it/s]16 19:08:22 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:31<00:10,  9.80it/s]16 19:08:23 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:31<00:10,  9.79it/s]16 19:08:23 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:31<00:10,  9.76it/s]16 19:08:23 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:31<00:10,  9.76it/s]16 19:08:23 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:31<00:09,  9.74it/s]16 19:08:23 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:31<00:09,  9.75it/s]16 19:08:23 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:32<00:09,  9.74it/s]16 19:08:23 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:32<00:09,  9.69it/s]16 19:08:23 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:32<00:09,  9.69it/s]16 19:08:23 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:32<00:09,  9.69it/s]16 19:08:23 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:32<00:09,  9.72it/s]16 19:08:24 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:32<00:09,  9.72it/s]16 19:08:24 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:32<00:09,  9.71it/s]16 19:08:24 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:32<00:09,  9.73it/s]16 19:08:24 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:32<00:08,  9.70it/s]16 19:08:24 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:33<00:08,  9.72it/s]16 19:08:24 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:33<00:08,  9.74it/s]16 19:08:24 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:33<00:08,  9.76it/s]16 19:08:24 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:33<00:08,  9.74it/s]16 19:08:24 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:33<00:08,  9.72it/s]16 19:08:24 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:33<00:08,  9.73it/s]16 19:08:25 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:33<00:08,  9.58it/s]16 19:08:25 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:33<00:08,  9.59it/s]16 19:08:25 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:33<00:08,  9.64it/s]16 19:08:25 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:33<00:07,  9.66it/s]16 19:08:25 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:34<00:07,  9.71it/s]16 19:08:25 Save the image 01301N.png

 81%|████████████████████████████████▎       | 318/393 [00:34<00:07,  9.73it/s]16 19:08:25 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:34<00:07,  9.76it/s]16 19:08:25 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:34<00:07,  9.77it/s]16 19:08:25 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:34<00:07,  9.73it/s]16 19:08:26 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:34<00:07,  9.74it/s]16 19:08:26 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [00:34<00:07,  9.74it/s]16 19:08:26 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:34<00:07,  9.77it/s]16 19:08:26 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:34<00:06,  9.80it/s]16 19:08:26 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:34<00:06,  9.79it/s]16 19:08:26 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:35<00:06,  9.77it/s]16 19:08:26 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:35<00:06,  9.76it/s]16 19:08:26 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:35<00:06,  9.76it/s]16 19:08:26 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:35<00:06,  9.75it/s]16 19:08:26 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:35<00:06,  9.73it/s]16 19:08:27 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [00:35<00:06,  9.73it/s]16 19:08:27 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:35<00:06,  9.76it/s]16 19:08:27 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [00:35<00:06,  9.75it/s]16 19:08:27 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [00:35<00:05,  9.78it/s]16 19:08:27 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [00:36<00:05,  9.79it/s]16 19:08:27 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [00:36<00:05,  9.73it/s]16 19:08:27 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [00:36<00:05,  9.73it/s]16 19:08:27 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [00:36<00:05,  9.74it/s]16 19:08:27 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [00:36<00:05,  9.74it/s]16 19:08:27 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [00:36<00:05,  9.73it/s]16 19:08:28 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [00:36<00:05,  9.71it/s]16 19:08:28 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [00:36<00:05,  9.72it/s]16 19:08:28 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [00:36<00:05,  9.74it/s]16 19:08:28 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [00:36<00:04,  9.73it/s]16 19:08:28 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [00:37<00:04,  9.72it/s]16 19:08:28 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [00:37<00:04,  9.68it/s]16 19:08:28 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [00:37<00:04,  9.71it/s]16 19:08:28 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [00:37<00:04,  9.75it/s]16 19:08:28 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [00:37<00:04,  9.74it/s]16 19:08:28 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [00:37<00:04,  9.71it/s]16 19:08:29 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [00:37<00:04,  9.69it/s]16 19:08:29 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [00:37<00:04,  9.70it/s]16 19:08:29 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [00:37<00:04,  9.70it/s]16 19:08:29 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [00:37<00:03,  9.71it/s]16 19:08:29 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [00:38<00:03,  9.73it/s]16 19:08:29 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [00:38<00:03,  9.73it/s]16 19:08:29 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [00:38<00:03,  9.72it/s]16 19:08:29 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [00:38<00:03,  9.71it/s]16 19:08:29 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [00:38<00:03,  9.72it/s]16 19:08:30 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [00:38<00:03,  9.72it/s]16 19:08:30 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [00:38<00:03,  9.54it/s]16 19:08:30 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [00:38<00:03,  9.56it/s]16 19:08:30 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [00:38<00:03,  9.60it/s]16 19:08:30 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [00:38<00:02,  9.62it/s]16 19:08:30 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [00:39<00:02,  9.65it/s]16 19:08:30 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [00:39<00:02,  9.67it/s]16 19:08:30 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [00:39<00:02,  9.69it/s]16 19:08:30 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [00:39<00:02,  9.71it/s]16 19:08:30 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [00:39<00:02,  9.78it/s]16 19:08:31 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [00:39<00:02,  9.82it/s]16 19:08:31 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [00:39<00:02,  9.83it/s]16 19:08:31 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [00:39<00:02,  9.81it/s]16 19:08:31 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [00:39<00:01,  9.81it/s]16 19:08:31 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [00:40<00:01,  9.80it/s]16 19:08:31 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [00:40<00:01,  9.79it/s]16 19:08:31 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [00:40<00:01,  9.79it/s]16 19:08:31 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [00:40<00:01,  9.77it/s]16 19:08:31 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [00:40<00:01,  9.78it/s]16 19:08:31 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [00:40<00:01,  9.78it/s]16 19:08:32 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [00:40<00:01,  9.78it/s]16 19:08:32 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [00:40<00:01,  9.80it/s]16 19:08:32 Save the image 01366N.png

 97%|██████████████████████████████████████▉ | 383/393 [00:40<00:01,  9.78it/s]16 19:08:32 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [00:40<00:00,  9.79it/s]16 19:08:32 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [00:41<00:00,  9.80it/s]16 19:08:32 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [00:41<00:00,  9.83it/s]16 19:08:32 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [00:41<00:00,  9.84it/s]16 19:08:32 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [00:41<00:00,  9.85it/s]16 19:08:32 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [00:41<00:00,  9.85it/s]16 19:08:32 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [00:41<00:00,  9.87it/s]16 19:08:33 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [00:41<00:00,  9.87it/s]16 19:08:33 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [00:41<00:00,  9.88it/s]16 19:08:33 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [00:41<00:00,  9.39it/s]
1 unlabeled	98.318%
2 car   	89.264%
3 person	75.482%
4 bike  	65.006%
5 curve 	47.410%
6 car_stop	32.014%
7 guardrail	7.243%
8 color_cone	52.236%
9 bump  	58.436%
----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
16 19:08:33 Evaluation Elapsed Time: 41.85s

In [29]:

%cd /home/cse-sdpl/Downloads/CMX_E5

!python eval.py -e 100 -d 0 --split test -p predictions_E5_test

/home/cse-sdpl/Downloads/CMX_E5
/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 19:09:43 using devices 0
16 19:09:43 Using E5: SegFormer-B2 with counterfactual reliability
16 19:09:44 Using MLP Decoder
16 19:09:44 Load Model: /home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2_e5/checkpoint/epoch-100.pth
16 19:09:45 Load model, Time usage:
	IO: 0.7491490840911865, initialize parameters: 0.042465925216674805
16 19:09:45 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@3.650] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 19:09:45 Save the image 01402D.png
  0%|                                          | 1/393 [00:00<02:05,  3.11it/s]16 19:09:45 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:00<01:16,  5.13it/s]16 19:09:45 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:00<00:59,  6.55it/s]16 19:09:45 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:00<00:51,  7.55it/s]16 19:09:45 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:00<00:47,  8.24it/s]16 19:09:45 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:00<00:44,  8.72it/s]16 19:09:45 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:00<00:42,  9.06it/s]16 19:09:46 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:01<00:41,  9.30it/s]16 19:09:46 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:01<00:40,  9.48it/s]16 19:09:46 Save the image 01411D.png
  3%|█                                        | 10/393 [00:01<00:39,  9.58it/s]16 19:09:46 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:01<00:39,  9.65it/s]16 19:09:46 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:01<00:39,  9.67it/s]16 19:09:46 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:01<00:39,  9.68it/s]16 19:09:46 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:01<00:39,  9.70it/s]16 19:09:46 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:01<00:38,  9.70it/s]16 19:09:46 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:01<00:38,  9.71it/s]16 19:09:46 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:01<00:38,  9.72it/s]16 19:09:47 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:02<00:38,  9.75it/s]16 19:09:47 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:02<00:38,  9.76it/s]16 19:09:47 Save the image 01421D.png
  5%|██                                       | 20/393 [00:02<00:38,  9.77it/s]16 19:09:47 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:02<00:37,  9.80it/s]16 19:09:47 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:02<00:37,  9.80it/s]16 19:09:47 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:02<00:37,  9.82it/s]16 19:09:47 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:02<00:37,  9.81it/s]16 19:09:47 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:02<00:37,  9.77it/s]16 19:09:47 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:02<00:37,  9.75it/s]16 19:09:47 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:02<00:37,  9.74it/s]16 19:09:48 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:03<00:37,  9.75it/s]16 19:09:48 Save the image 01430D.png
  7%|███                                      | 29/393 [00:03<00:37,  9.76it/s]16 19:09:48 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:03<00:37,  9.77it/s]16 19:09:48 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:03<00:37,  9.76it/s]16 19:09:48 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:03<00:36,  9.76it/s]16 19:09:48 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:03<00:36,  9.75it/s]16 19:09:48 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:03<00:36,  9.76it/s]16 19:09:48 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:03<00:36,  9.77it/s]16 19:09:48 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:03<00:36,  9.77it/s]16 19:09:49 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:04<00:36,  9.76it/s]16 19:09:49 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:04<00:36,  9.78it/s]16 19:09:49 Save the image 01440D.png
 10%|████                                     | 39/393 [00:04<00:36,  9.77it/s]16 19:09:49 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:04<00:36,  9.75it/s]16 19:09:49 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:04<00:36,  9.74it/s]16 19:09:49 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:04<00:36,  9.74it/s]16 19:09:49 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:04<00:35,  9.76it/s]16 19:09:49 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:04<00:35,  9.78it/s]16 19:09:49 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:04<00:35,  9.78it/s]16 19:09:49 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:04<00:35,  9.78it/s]16 19:09:50 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:05<00:35,  9.77it/s]16 19:09:50 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:05<00:35,  9.72it/s]16 19:09:50 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:05<00:35,  9.63it/s]16 19:09:50 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:05<00:36,  9.39it/s]16 19:09:50 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:05<00:36,  9.26it/s]16 19:09:50 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:05<00:37,  9.11it/s]16 19:09:50 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:05<00:37,  9.02it/s]16 19:09:50 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:05<00:37,  8.96it/s]16 19:09:50 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:05<00:37,  8.91it/s]16 19:09:51 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:06<00:37,  8.87it/s]16 19:09:51 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:06<00:37,  8.86it/s]16 19:09:51 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:06<00:37,  8.87it/s]16 19:09:51 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:06<00:37,  8.86it/s]16 19:09:51 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:06<00:37,  8.85it/s]16 19:09:51 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:06<00:37,  8.84it/s]16 19:09:51 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:06<00:37,  8.84it/s]16 19:09:51 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:06<00:37,  8.85it/s]16 19:09:51 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:06<00:37,  8.84it/s]16 19:09:52 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:07<00:37,  8.86it/s]16 19:09:52 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:07<00:36,  8.85it/s]16 19:09:52 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:07<00:36,  8.87it/s]16 19:09:52 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:07<00:36,  8.95it/s]16 19:09:52 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:07<00:35,  9.17it/s]16 19:09:52 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:07<00:34,  9.36it/s]16 19:09:52 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:07<00:33,  9.48it/s]16 19:09:52 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:07<00:33,  9.54it/s]16 19:09:52 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:07<00:33,  9.61it/s]16 19:09:53 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:08<00:33,  9.62it/s]16 19:09:53 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:08<00:32,  9.68it/s]16 19:09:53 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:08<00:32,  9.72it/s]16 19:09:53 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:08<00:32,  9.74it/s]16 19:09:53 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:08<00:32,  9.75it/s]16 19:09:53 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:08<00:32,  9.75it/s]16 19:09:53 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:08<00:32,  9.74it/s]16 19:09:53 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:08<00:32,  9.73it/s]16 19:09:53 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:08<00:31,  9.73it/s]16 19:09:53 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:08<00:31,  9.75it/s]16 19:09:54 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:09<00:31,  9.78it/s]16 19:09:54 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:09<00:31,  9.78it/s]16 19:09:54 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:09<00:31,  9.80it/s]16 19:09:54 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:09<00:31,  9.80it/s]16 19:09:54 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:09<00:31,  9.76it/s]16 19:09:54 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:09<00:31,  9.75it/s]16 19:09:54 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:09<00:31,  9.75it/s]16 19:09:54 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:09<00:30,  9.76it/s]16 19:09:54 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:09<00:30,  9.76it/s]16 19:09:54 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:09<00:30,  9.75it/s]16 19:09:55 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:10<00:30,  9.74it/s]16 19:09:55 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:10<00:30,  9.76it/s]16 19:09:55 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:10<00:30,  9.76it/s]16 19:09:55 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:10<00:30,  9.75it/s]16 19:09:55 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:10<00:30,  9.76it/s]16 19:09:55 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:10<00:30,  9.76it/s]16 19:09:55 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:10<00:30,  9.76it/s]16 19:09:55 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:10<00:29,  9.73it/s]16 19:09:55 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:10<00:29,  9.73it/s]16 19:09:55 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:10<00:29,  9.72it/s]16 19:09:56 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:11<00:29,  9.73it/s]16 19:09:56 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:11<00:29,  9.75it/s]16 19:09:56 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:11<00:29,  9.75it/s]16 19:09:56 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:11<00:29,  9.77it/s]16 19:09:56 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:11<00:29,  9.77it/s]16 19:09:56 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:11<00:29,  9.77it/s]16 19:09:56 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:11<00:29,  9.74it/s]16 19:09:56 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:11<00:28,  9.74it/s]16 19:09:56 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:11<00:28,  9.74it/s]16 19:09:57 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:11<00:28,  9.73it/s]16 19:09:57 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:12<00:28,  9.73it/s]16 19:09:57 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:12<00:28,  9.74it/s]16 19:09:57 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:12<00:28,  9.74it/s]16 19:09:57 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:12<00:28,  9.74it/s]16 19:09:57 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:12<00:28,  9.72it/s]16 19:09:57 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:12<00:28,  9.73it/s]16 19:09:57 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:12<00:28,  9.71it/s]16 19:09:57 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:12<00:27,  9.73it/s]16 19:09:57 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:12<00:27,  9.73it/s]16 19:09:58 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:13<00:27,  9.73it/s]16 19:09:58 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:13<00:27,  9.72it/s]16 19:09:58 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:13<00:27,  9.73it/s]16 19:09:58 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:13<00:27,  9.74it/s]16 19:09:58 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:13<00:27,  9.75it/s]16 19:09:58 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:13<00:27,  9.76it/s]16 19:09:58 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:13<00:27,  9.75it/s]16 19:09:58 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:13<00:27,  9.72it/s]16 19:09:58 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:13<00:26,  9.72it/s]16 19:09:58 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:13<00:26,  9.72it/s]16 19:09:59 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:14<00:26,  9.73it/s]16 19:09:59 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:14<00:26,  9.72it/s]16 19:09:59 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:14<00:26,  9.74it/s]16 19:09:59 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:14<00:26,  9.76it/s]16 19:09:59 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:14<00:26,  9.74it/s]16 19:09:59 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:14<00:26,  9.72it/s]16 19:09:59 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:14<00:26,  9.74it/s]16 19:09:59 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:14<00:25,  9.74it/s]16 19:09:59 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:14<00:25,  9.76it/s]16 19:09:59 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:14<00:25,  9.76it/s]16 19:10:00 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:15<00:25,  9.77it/s]16 19:10:00 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:15<00:25,  9.75it/s]16 19:10:00 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:15<00:25,  9.73it/s]16 19:10:00 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:15<00:25,  9.76it/s]16 19:10:00 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:15<00:25,  9.75it/s]16 19:10:00 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:15<00:25,  9.60it/s]16 19:10:00 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:15<00:25,  9.65it/s]16 19:10:00 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:15<00:25,  9.67it/s]16 19:10:00 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:15<00:24,  9.71it/s]16 19:10:01 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:16<00:24,  9.71it/s]16 19:10:01 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:16<00:24,  9.69it/s]16 19:10:01 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:16<00:24,  9.70it/s]16 19:10:01 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:16<00:24,  9.69it/s]16 19:10:01 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:16<00:24,  9.72it/s]16 19:10:01 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:16<00:24,  9.72it/s]16 19:10:01 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:16<00:24,  9.72it/s]16 19:10:01 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:16<00:24,  9.73it/s]16 19:10:01 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:16<00:23,  9.72it/s]16 19:10:01 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:16<00:23,  9.74it/s]16 19:10:02 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:17<00:23,  9.76it/s]16 19:10:02 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:17<00:23,  9.80it/s]16 19:10:02 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:17<00:23,  9.80it/s]16 19:10:02 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:17<00:23,  9.77it/s]16 19:10:02 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:17<00:23,  9.77it/s]16 19:10:02 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:17<00:23,  9.74it/s]16 19:10:02 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:17<00:23,  9.72it/s]16 19:10:02 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:17<00:23,  9.72it/s]16 19:10:02 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:17<00:22,  9.71it/s]16 19:10:02 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:17<00:22,  9.74it/s]16 19:10:03 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:18<00:22,  9.77it/s]16 19:10:03 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:18<00:22,  9.81it/s]16 19:10:03 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:18<00:22,  9.84it/s]16 19:10:03 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:18<00:22,  9.83it/s]16 19:10:03 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:18<00:22,  9.82it/s]16 19:10:03 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:18<00:22,  9.82it/s]16 19:10:03 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:18<00:21,  9.83it/s]16 19:10:03 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:18<00:21,  9.81it/s]16 19:10:03 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:18<00:21,  9.78it/s]16 19:10:03 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:18<00:21,  9.78it/s]16 19:10:04 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:19<00:21,  9.77it/s]16 19:10:04 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:19<00:21,  9.78it/s]16 19:10:04 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:19<00:21,  9.77it/s]16 19:10:04 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:19<00:21,  9.78it/s]16 19:10:04 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:19<00:21,  9.76it/s]16 19:10:04 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:19<00:21,  9.75it/s]16 19:10:04 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:19<00:21,  9.75it/s]16 19:10:04 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:19<00:20,  9.75it/s]16 19:10:04 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:19<00:20,  9.76it/s]16 19:10:05 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:20<00:20,  9.75it/s]16 19:10:05 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:20<00:20,  9.75it/s]16 19:10:05 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:20<00:20,  9.75it/s]16 19:10:05 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:20<00:20,  9.74it/s]16 19:10:05 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:20<00:20,  9.74it/s]16 19:10:05 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:20<00:20,  9.74it/s]16 19:10:05 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:20<00:20,  9.73it/s]16 19:10:05 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:20<00:19,  9.77it/s]16 19:10:05 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:20<00:19,  9.77it/s]16 19:10:05 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:20<00:19,  9.77it/s]16 19:10:06 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:21<00:19,  9.75it/s]16 19:10:06 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:21<00:19,  9.75it/s]16 19:10:06 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:21<00:19,  9.75it/s]16 19:10:06 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:21<00:19,  9.75it/s]16 19:10:06 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:21<00:19,  9.76it/s]16 19:10:06 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:21<00:19,  9.80it/s]16 19:10:06 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:21<00:18,  9.83it/s]16 19:10:06 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:21<00:18,  9.83it/s]16 19:10:06 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:21<00:18,  9.83it/s]16 19:10:06 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:21<00:18,  9.85it/s]16 19:10:07 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:22<00:18,  9.85it/s]16 19:10:07 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:22<00:18,  9.84it/s]16 19:10:07 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:22<00:18,  9.82it/s]16 19:10:07 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:22<00:18,  9.82it/s]16 19:10:07 Save the image 01198N.png
 55%|█████████████████████▉                  | 215/393 [00:22<00:18,  9.87it/s]16 19:10:07 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:22<00:17,  9.88it/s]16 19:10:07 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:22<00:17,  9.88it/s]16 19:10:07 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:22<00:17,  9.89it/s]16 19:10:07 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:22<00:17,  9.91it/s]16 19:10:07 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:22<00:17,  9.90it/s]16 19:10:08 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:23<00:17,  9.92it/s]16 19:10:08 Save the image 01205N.png
16 19:10:08 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:23<00:17,  9.95it/s]16 19:10:08 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:23<00:17,  9.93it/s]16 19:10:08 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:23<00:16,  9.93it/s]16 19:10:08 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:23<00:16,  9.93it/s]16 19:10:08 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:23<00:16,  9.92it/s]16 19:10:08 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:23<00:16,  9.89it/s]16 19:10:08 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:23<00:16,  9.91it/s]16 19:10:08 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:23<00:16,  9.92it/s]16 19:10:09 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:24<00:16,  9.92it/s]16 19:10:09 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:24<00:16,  9.90it/s]16 19:10:09 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:24<00:16,  9.89it/s]16 19:10:09 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:24<00:16,  9.87it/s]16 19:10:09 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:24<00:15,  9.89it/s]16 19:10:09 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:24<00:15,  9.90it/s]16 19:10:09 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:24<00:15,  9.88it/s]16 19:10:09 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:24<00:15,  9.87it/s]16 19:10:09 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:24<00:15,  9.91it/s]16 19:10:09 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:24<00:15,  9.91it/s]16 19:10:10 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:25<00:15,  9.83it/s]16 19:10:10 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:25<00:15,  9.82it/s]16 19:10:10 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:25<00:15,  9.83it/s]16 19:10:10 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:25<00:15,  9.83it/s]16 19:10:10 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:25<00:15,  9.84it/s]16 19:10:10 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:25<00:14,  9.85it/s]16 19:10:10 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:25<00:14,  9.86it/s]16 19:10:10 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:25<00:14,  9.83it/s]16 19:10:10 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:25<00:14,  9.85it/s]16 19:10:10 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:25<00:14,  9.87it/s]16 19:10:11 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:26<00:14,  9.89it/s]16 19:10:11 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:26<00:14,  9.89it/s]16 19:10:11 Save the image 01236N.png
 64%|█████████████████████████▊              | 253/393 [00:26<00:14,  9.87it/s]16 19:10:11 Save the image 01237N.png

 65%|█████████████████████████▊              | 254/393 [00:26<00:14,  9.88it/s]16 19:10:11 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:26<00:13,  9.91it/s]16 19:10:11 Save the image 01239N.png
16 19:10:11 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:26<00:13,  9.95it/s]16 19:10:11 Save the image 01241N.png
16 19:10:11 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:26<00:13,  9.97it/s]16 19:10:12 Save the image 01243N.png
16 19:10:12 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:27<00:13,  9.99it/s]16 19:10:12 Save the image 01245N.png
16 19:10:12 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:27<00:13,  9.99it/s]16 19:10:12 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:27<00:12,  9.97it/s]16 19:10:12 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:27<00:12,  9.97it/s]16 19:10:12 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:27<00:12,  9.97it/s]16 19:10:12 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:27<00:12,  9.97it/s]16 19:10:12 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:27<00:12,  9.95it/s]16 19:10:12 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:27<00:12,  9.91it/s]16 19:10:13 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:28<00:12,  9.93it/s]16 19:10:13 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:28<00:12,  9.93it/s]16 19:10:13 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:28<00:12,  9.95it/s]16 19:10:13 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:28<00:12,  9.95it/s]16 19:10:13 Save the image 01257N.png
16 19:10:13 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:28<00:11,  9.96it/s]16 19:10:13 Save the image 01259N.png
16 19:10:13 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:28<00:11,  9.96it/s]16 19:10:13 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:28<00:11,  9.93it/s]16 19:10:13 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:28<00:11,  9.91it/s]16 19:10:14 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:29<00:11,  9.89it/s]16 19:10:14 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:29<00:11,  9.87it/s]16 19:10:14 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:29<00:11,  9.89it/s]16 19:10:14 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:29<00:11,  9.90it/s]16 19:10:14 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:29<00:11,  9.89it/s]16 19:10:14 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:29<00:10,  9.89it/s]16 19:10:14 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:29<00:10,  9.90it/s]16 19:10:14 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:29<00:10,  9.89it/s]16 19:10:14 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:29<00:10,  9.89it/s]16 19:10:14 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:29<00:10,  9.87it/s]16 19:10:15 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:30<00:10,  9.87it/s]16 19:10:15 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:30<00:10,  9.91it/s]16 19:10:15 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:30<00:10,  9.93it/s]16 19:10:15 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:30<00:10,  9.93it/s]16 19:10:15 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:30<00:09,  9.92it/s]16 19:10:15 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:30<00:09,  9.88it/s]16 19:10:15 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:30<00:09,  9.87it/s]16 19:10:15 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:30<00:09,  9.85it/s]16 19:10:15 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:30<00:09,  9.84it/s]16 19:10:15 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:30<00:09,  9.85it/s]16 19:10:16 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:31<00:09,  9.86it/s]16 19:10:16 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:31<00:09,  9.87it/s]16 19:10:16 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:31<00:09,  9.89it/s]16 19:10:16 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:31<00:09,  9.88it/s]16 19:10:16 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:31<00:09,  9.86it/s]16 19:10:16 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:31<00:08,  9.84it/s]16 19:10:16 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:31<00:08,  9.84it/s]16 19:10:16 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:31<00:08,  9.82it/s]16 19:10:16 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:31<00:08,  9.80it/s]16 19:10:16 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:31<00:08,  9.81it/s]16 19:10:17 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:32<00:08,  9.81it/s]16 19:10:17 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:32<00:08,  9.82it/s]16 19:10:17 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:32<00:08,  9.84it/s]16 19:10:17 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:32<00:08,  9.86it/s]16 19:10:17 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:32<00:07,  9.88it/s]16 19:10:17 Save the image 01298N.png
16 19:10:17 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:32<00:07,  9.92it/s]16 19:10:17 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:32<00:07,  9.93it/s]16 19:10:17 Save the image 01301N.png
 81%|████████████████████████████████▎       | 318/393 [00:32<00:07,  9.93it/s]16 19:10:17 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:32<00:07,  9.92it/s]16 19:10:18 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:33<00:07,  9.88it/s]16 19:10:18 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:33<00:07,  9.83it/s]16 19:10:18 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:33<00:07,  9.84it/s]16 19:10:18 Save the image 01306N.png

 82%|████████████████████████████████▉       | 323/393 [00:33<00:07,  9.83it/s]16 19:10:18 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:33<00:07,  9.85it/s]16 19:10:18 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:33<00:06,  9.85it/s]16 19:10:18 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:33<00:06,  9.86it/s]16 19:10:18 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:33<00:06,  9.86it/s]16 19:10:18 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:33<00:06,  9.87it/s]16 19:10:18 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:33<00:06,  9.88it/s]16 19:10:19 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:34<00:06,  9.89it/s]16 19:10:19 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:34<00:06,  9.88it/s]16 19:10:19 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [00:34<00:06,  9.86it/s]16 19:10:19 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:34<00:06,  9.87it/s]16 19:10:19 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [00:34<00:05,  9.87it/s]16 19:10:19 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [00:34<00:05,  9.87it/s]16 19:10:19 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [00:34<00:05,  9.87it/s]16 19:10:19 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [00:34<00:05,  9.84it/s]16 19:10:19 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [00:34<00:05,  9.84it/s]16 19:10:19 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [00:34<00:05,  9.86it/s]16 19:10:20 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [00:35<00:05,  9.88it/s]16 19:10:20 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [00:35<00:05,  9.88it/s]16 19:10:20 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [00:35<00:05,  9.88it/s]16 19:10:20 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [00:35<00:05,  9.90it/s]16 19:10:20 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [00:35<00:04,  9.89it/s]16 19:10:20 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [00:35<00:04,  9.90it/s]16 19:10:20 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [00:35<00:04,  9.90it/s]16 19:10:20 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [00:35<00:04,  9.84it/s]16 19:10:20 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [00:35<00:04,  9.83it/s]16 19:10:21 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [00:36<00:04,  9.83it/s]16 19:10:21 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [00:36<00:04,  9.85it/s]16 19:10:21 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [00:36<00:04,  9.84it/s]16 19:10:21 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [00:36<00:04,  9.83it/s]16 19:10:21 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [00:36<00:04,  9.84it/s]16 19:10:21 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [00:36<00:03,  9.85it/s]16 19:10:21 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [00:36<00:03,  9.83it/s]16 19:10:21 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [00:36<00:03,  9.81it/s]16 19:10:21 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [00:36<00:03,  9.81it/s]16 19:10:21 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [00:36<00:03,  9.79it/s]16 19:10:22 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [00:37<00:03,  9.84it/s]16 19:10:22 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [00:37<00:03,  9.85it/s]16 19:10:22 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [00:37<00:03,  9.88it/s]16 19:10:22 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [00:37<00:03,  9.89it/s]16 19:10:22 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [00:37<00:03,  9.88it/s]16 19:10:22 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [00:37<00:02,  9.86it/s]16 19:10:22 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [00:37<00:02,  9.84it/s]16 19:10:22 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [00:37<00:02,  9.84it/s]16 19:10:22 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [00:37<00:02,  9.82it/s]16 19:10:22 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [00:37<00:02,  9.84it/s]16 19:10:23 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [00:38<00:02,  9.84it/s]16 19:10:23 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [00:38<00:02,  9.89it/s]16 19:10:23 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [00:38<00:02,  9.91it/s]16 19:10:23 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [00:38<00:02,  9.93it/s]16 19:10:23 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [00:38<00:02,  9.94it/s]16 19:10:23 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [00:38<00:01,  9.92it/s]16 19:10:23 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [00:38<00:01,  9.90it/s]16 19:10:23 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [00:38<00:01,  9.90it/s]16 19:10:23 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [00:38<00:01,  9.92it/s]16 19:10:23 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [00:38<00:01,  9.91it/s]16 19:10:24 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [00:39<00:01,  9.90it/s]16 19:10:24 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [00:39<00:01,  9.90it/s]16 19:10:24 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [00:39<00:01,  9.90it/s]16 19:10:24 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [00:39<00:01,  9.85it/s]16 19:10:24 Save the image 01366N.png
 97%|██████████████████████████████████████▉ | 383/393 [00:39<00:01,  9.87it/s]16 19:10:24 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [00:39<00:00,  9.88it/s]16 19:10:24 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [00:39<00:00,  9.87it/s]16 19:10:24 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [00:39<00:00,  9.90it/s]16 19:10:24 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [00:39<00:00,  9.92it/s]16 19:10:24 Save the image 01371N.png
16 19:10:25 Save the image 01372N.png

 99%|███████████████████████████████████████▌| 389/393 [00:40<00:00,  9.98it/s]16 19:10:25 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [00:40<00:00,  9.97it/s]16 19:10:25 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [00:40<00:00,  9.97it/s]16 19:10:25 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [00:40<00:00,  9.94it/s]16 19:10:25 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [00:40<00:00,  9.72it/s]
1 unlabeled	98.318%
2 car   	89.264%
3 person	75.482%
4 bike  	65.006%
5 curve 	47.410%
6 car_stop	32.014%
7 guardrail	7.243%
8 color_cone	52.236%
9 bump  	58.436%
----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
16 19:10:25 Evaluation Elapsed Time: 40.45s

In [30]:
!python eval.py -e 100 -d 0 --split test -p predictions_E5_test

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 19:11:51 using devices 0
16 19:11:51 Using E5: SegFormer-B2 with counterfactual reliability
16 19:11:52 Using MLP Decoder
16 19:11:52 Load Model: /home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2_e5/checkpoint/epoch-100.pth
16 19:11:52 Load model, Time usage:
	IO: 0.7427487373352051, initialize parameters: 0.041689395904541016
16 19:11:52 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@3.599] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 19:11:53 Save the image 01402D.png
  0%|                                          | 1/393 [00:00<02:02,  3.20it/s]16 19:11:53 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:00<01:14,  5.24it/s]16 19:11:53 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:00<00:59,  6.59it/s]16 19:11:53 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:00<00:51,  7.59it/s]16 19:11:53 Save the image 01406D.png
  1%|▌                                         | 5/393 [00:00<00:46,  8.28it/s]16 19:11:53 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:00<00:44,  8.77it/s]16 19:11:53 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:00<00:42,  9.13it/s]16 19:11:53 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:01<00:41,  9.37it/s]16 19:11:53 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:01<00:40,  9.53it/s]16 19:11:54 Save the image 01411D.png
  3%|█                                        | 10/393 [00:01<00:39,  9.63it/s]16 19:11:54 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:01<00:39,  9.69it/s]16 19:11:54 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:01<00:39,  9.73it/s]16 19:11:54 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:01<00:39,  9.74it/s]16 19:11:54 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:01<00:38,  9.78it/s]16 19:11:54 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:01<00:38,  9.80it/s]16 19:11:54 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:01<00:38,  9.82it/s]16 19:11:54 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:01<00:38,  9.83it/s]16 19:11:54 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:02<00:38,  9.84it/s]16 19:11:54 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:02<00:37,  9.85it/s]16 19:11:55 Save the image 01421D.png
  5%|██                                       | 20/393 [00:02<00:37,  9.86it/s]16 19:11:55 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:02<00:37,  9.88it/s]16 19:11:55 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:02<00:37,  9.88it/s]16 19:11:55 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:02<00:37,  9.88it/s]16 19:11:55 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:02<00:37,  9.88it/s]16 19:11:55 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:02<00:37,  9.87it/s]16 19:11:55 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:02<00:37,  9.84it/s]16 19:11:55 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:02<00:37,  9.84it/s]16 19:11:55 Save the image 01429D.png
  7%|██▉                                      | 28/393 [00:03<00:37,  9.75it/s]16 19:11:55 Save the image 01430D.png
  7%|███                                      | 29/393 [00:03<00:37,  9.78it/s]16 19:11:56 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:03<00:37,  9.81it/s]16 19:11:56 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:03<00:36,  9.82it/s]16 19:11:56 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:03<00:36,  9.83it/s]16 19:11:56 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:03<00:36,  9.82it/s]16 19:11:56 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:03<00:36,  9.81it/s]16 19:11:56 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:03<00:36,  9.81it/s]16 19:11:56 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:03<00:36,  9.82it/s]16 19:11:56 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:03<00:36,  9.81it/s]16 19:11:56 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:04<00:36,  9.79it/s]16 19:11:56 Save the image 01440D.png
 10%|████                                     | 39/393 [00:04<00:36,  9.80it/s]16 19:11:57 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:04<00:36,  9.80it/s]16 19:11:57 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:04<00:35,  9.79it/s]16 19:11:57 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:04<00:35,  9.81it/s]16 19:11:57 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:04<00:35,  9.79it/s]16 19:11:57 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:04<00:35,  9.81it/s]16 19:11:57 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:04<00:35,  9.81it/s]16 19:11:57 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:04<00:35,  9.80it/s]16 19:11:57 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:04<00:35,  9.80it/s]16 19:11:57 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:05<00:35,  9.80it/s]16 19:11:58 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:05<00:35,  9.81it/s]16 19:11:58 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:05<00:34,  9.82it/s]16 19:11:58 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:05<00:34,  9.81it/s]16 19:11:58 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:05<00:34,  9.80it/s]16 19:11:58 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:05<00:34,  9.76it/s]16 19:11:58 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:05<00:34,  9.75it/s]16 19:11:58 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:05<00:34,  9.73it/s]16 19:11:58 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:05<00:34,  9.71it/s]16 19:11:58 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:06<00:34,  9.72it/s]16 19:11:58 Save the image 01459D.png

 15%|██████                                   | 58/393 [00:06<00:34,  9.74it/s]16 19:11:59 Save the image 01460D.png
 15%|██████▏                                  | 59/393 [00:06<00:34,  9.75it/s]16 19:11:59 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:06<00:34,  9.74it/s]16 19:11:59 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:06<00:34,  9.75it/s]16 19:11:59 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:06<00:34,  9.73it/s]16 19:11:59 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:06<00:33,  9.76it/s]16 19:11:59 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:06<00:33,  9.78it/s]16 19:11:59 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:06<00:33,  9.79it/s]16 19:11:59 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:06<00:33,  9.78it/s]16 19:11:59 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:07<00:33,  9.75it/s]16 19:11:59 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:07<00:33,  9.74it/s]16 19:12:00 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:07<00:33,  9.54it/s]16 19:12:00 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:07<00:34,  9.44it/s]16 19:12:00 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:07<00:33,  9.55it/s]16 19:12:00 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:07<00:33,  9.63it/s]16 19:12:00 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:07<00:33,  9.67it/s]16 19:12:00 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:07<00:32,  9.70it/s]16 19:12:00 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:07<00:32,  9.72it/s]16 19:12:00 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:07<00:32,  9.73it/s]16 19:12:00 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:08<00:32,  9.74it/s]16 19:12:00 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:08<00:32,  9.74it/s]16 19:12:01 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:08<00:32,  9.74it/s]16 19:12:01 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:08<00:32,  9.74it/s]16 19:12:01 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:08<00:32,  9.75it/s]16 19:12:01 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:08<00:31,  9.76it/s]16 19:12:01 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:08<00:31,  9.78it/s]16 19:12:01 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:08<00:31,  9.77it/s]16 19:12:01 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:08<00:31,  9.76it/s]16 19:12:01 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:09<00:31,  9.77it/s]16 19:12:01 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:09<00:31,  9.77it/s]16 19:12:02 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:09<00:31,  9.76it/s]16 19:12:02 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:09<00:31,  9.75it/s]16 19:12:02 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:09<00:31,  9.75it/s]16 19:12:02 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:09<00:30,  9.76it/s]16 19:12:02 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:09<00:30,  9.78it/s]16 19:12:02 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:09<00:30,  9.78it/s]16 19:12:02 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:09<00:30,  9.78it/s]16 19:12:02 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:09<00:30,  9.76it/s]16 19:12:02 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:10<00:30,  9.73it/s]16 19:12:02 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:10<00:30,  9.74it/s]16 19:12:03 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:10<00:30,  9.75it/s]16 19:12:03 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:10<00:30,  9.75it/s]16 19:12:03 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:10<00:30,  9.76it/s]16 19:12:03 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:10<00:29,  9.77it/s]16 19:12:03 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:10<00:29,  9.79it/s]16 19:12:03 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:10<00:29,  9.76it/s]16 19:12:03 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:10<00:29,  9.64it/s]16 19:12:03 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:10<00:30,  9.60it/s]16 19:12:03 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:11<00:29,  9.58it/s]16 19:12:03 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:11<00:29,  9.54it/s]16 19:12:04 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:11<00:29,  9.54it/s]16 19:12:04 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:11<00:29,  9.55it/s]16 19:12:04 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:11<00:29,  9.63it/s]16 19:12:04 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:11<00:29,  9.69it/s]16 19:12:04 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:11<00:28,  9.71it/s]16 19:12:04 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:11<00:28,  9.74it/s]16 19:12:04 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:11<00:28,  9.73it/s]16 19:12:04 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:11<00:28,  9.72it/s]16 19:12:04 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:12<00:28,  9.74it/s]16 19:12:05 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:12<00:28,  9.73it/s]16 19:12:05 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:12<00:28,  9.73it/s]16 19:12:05 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:12<00:28,  9.74it/s]16 19:12:05 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:12<00:27,  9.75it/s]16 19:12:05 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:12<00:27,  9.75it/s]16 19:12:05 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:12<00:27,  9.76it/s]16 19:12:05 Save the image 01524D.png

 31%|████████████▌                           | 123/393 [00:12<00:27,  9.74it/s]16 19:12:05 Save the image 01525D.png
 32%|████████████▌                           | 124/393 [00:12<00:27,  9.74it/s]16 19:12:05 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:13<00:27,  9.76it/s]16 19:12:05 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:13<00:27,  9.78it/s]16 19:12:06 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:13<00:27,  9.80it/s]16 19:12:06 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:13<00:27,  9.79it/s]16 19:12:06 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:13<00:27,  9.77it/s]16 19:12:06 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:13<00:26,  9.77it/s]16 19:12:06 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:13<00:26,  9.78it/s]16 19:12:06 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:13<00:26,  9.75it/s]16 19:12:06 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:13<00:26,  9.73it/s]16 19:12:06 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:13<00:26,  9.72it/s]16 19:12:06 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:14<00:26,  9.71it/s]16 19:12:06 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:14<00:26,  9.71it/s]16 19:12:07 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:14<00:26,  9.70it/s]16 19:12:07 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:14<00:26,  9.71it/s]16 19:12:07 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:14<00:26,  9.73it/s]16 19:12:07 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:14<00:25,  9.74it/s]16 19:12:07 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:14<00:25,  9.74it/s]16 19:12:07 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:14<00:25,  9.74it/s]16 19:12:07 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:14<00:25,  9.73it/s]16 19:12:07 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:14<00:25,  9.73it/s]16 19:12:07 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:15<00:25,  9.73it/s]16 19:12:07 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:15<00:25,  9.72it/s]16 19:12:08 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:15<00:25,  9.73it/s]16 19:12:08 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:15<00:25,  9.73it/s]16 19:12:08 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:15<00:25,  9.74it/s]16 19:12:08 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:15<00:24,  9.76it/s]16 19:12:08 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:15<00:24,  9.76it/s]16 19:12:08 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:15<00:24,  9.75it/s]16 19:12:08 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:15<00:24,  9.75it/s]16 19:12:08 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:15<00:24,  9.75it/s]16 19:12:08 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:16<00:24,  9.76it/s]16 19:12:09 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:16<00:24,  9.76it/s]16 19:12:09 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:16<00:24,  9.76it/s]16 19:12:09 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:16<00:24,  9.76it/s]16 19:12:09 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:16<00:23,  9.77it/s]16 19:12:09 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:16<00:23,  9.77it/s]16 19:12:09 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:16<00:23,  9.79it/s]16 19:12:09 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:16<00:23,  9.79it/s]16 19:12:09 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:16<00:23,  9.79it/s]16 19:12:09 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:17<00:23,  9.77it/s]16 19:12:09 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:17<00:23,  9.76it/s]16 19:12:10 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:17<00:23,  9.76it/s]16 19:12:10 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:17<00:23,  9.75it/s]16 19:12:10 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:17<00:23,  9.74it/s]16 19:12:10 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:17<00:22,  9.74it/s]16 19:12:10 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:17<00:22,  9.75it/s]16 19:12:10 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:17<00:22,  9.76it/s]16 19:12:10 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:17<00:22,  9.78it/s]16 19:12:10 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:17<00:22,  9.79it/s]16 19:12:10 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:18<00:22,  9.80it/s]16 19:12:10 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:18<00:22,  9.80it/s]16 19:12:11 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:18<00:22,  9.82it/s]16 19:12:11 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:18<00:22,  9.79it/s]16 19:12:11 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:18<00:21,  9.78it/s]16 19:12:11 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:18<00:21,  9.77it/s]16 19:12:11 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:18<00:21,  9.77it/s]16 19:12:11 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:18<00:21,  9.78it/s]16 19:12:11 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:18<00:21,  9.78it/s]16 19:12:11 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:18<00:21,  9.75it/s]16 19:12:11 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:19<00:21,  9.74it/s]16 19:12:11 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:19<00:21,  9.73it/s]16 19:12:12 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:19<00:21,  9.73it/s]16 19:12:12 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:19<00:21,  9.73it/s]16 19:12:12 Save the image 01589D.png

 48%|███████████████████▏                    | 188/393 [00:19<00:21,  9.75it/s]16 19:12:12 Save the image 01590D.png
 48%|███████████████████▏                    | 189/393 [00:19<00:20,  9.75it/s]16 19:12:12 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:19<00:20,  9.75it/s]16 19:12:12 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:19<00:20,  9.73it/s]16 19:12:12 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:19<00:20,  9.75it/s]16 19:12:12 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:19<00:20,  9.73it/s]16 19:12:12 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:20<00:20,  9.74it/s]16 19:12:12 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:20<00:20,  9.75it/s]16 19:12:13 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:20<00:20,  9.73it/s]16 19:12:13 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:20<00:20,  9.74it/s]16 19:12:13 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:20<00:19,  9.75it/s]16 19:12:13 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:20<00:19,  9.78it/s]16 19:12:13 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:20<00:19,  9.78it/s]16 19:12:13 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:20<00:19,  9.76it/s]16 19:12:13 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:20<00:19,  9.72it/s]16 19:12:13 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:21<00:19,  9.70it/s]16 19:12:13 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:21<00:19,  9.71it/s]16 19:12:14 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:21<00:19,  9.74it/s]16 19:12:14 Save the image 01189N.png
 52%|████████████████████▉                   | 206/393 [00:21<00:19,  9.79it/s]16 19:12:14 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:21<00:18,  9.83it/s]16 19:12:14 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:21<00:18,  9.85it/s]16 19:12:14 Save the image 01192N.png
 53%|█████████████████████▎                  | 209/393 [00:21<00:18,  9.88it/s]16 19:12:14 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:21<00:18,  9.90it/s]16 19:12:14 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:21<00:18,  9.89it/s]16 19:12:14 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:21<00:18,  9.84it/s]16 19:12:14 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:22<00:18,  9.84it/s]16 19:12:14 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:22<00:18,  9.83it/s]16 19:12:15 Save the image 01198N.png
16 19:12:15 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:22<00:17,  9.92it/s]16 19:12:15 Save the image 01200N.png
 55%|██████████████████████                  | 217/393 [00:22<00:17,  9.92it/s]16 19:12:15 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:22<00:17,  9.93it/s]16 19:12:15 Save the image 01202N.png
 56%|██████████████████████▎                 | 219/393 [00:22<00:17,  9.94it/s]16 19:12:15 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:22<00:17,  9.90it/s]16 19:12:15 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:22<00:17,  9.89it/s]16 19:12:15 Save the image 01205N.png
 56%|██████████████████████▌                 | 222/393 [00:22<00:17,  9.89it/s]16 19:12:15 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:23<00:17,  9.89it/s]16 19:12:15 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:23<00:17,  9.91it/s]16 19:12:16 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:23<00:16,  9.90it/s]16 19:12:16 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:23<00:16,  9.91it/s]16 19:12:16 Save the image 01210N.png
 58%|███████████████████████                 | 227/393 [00:23<00:16,  9.90it/s]16 19:12:16 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:23<00:16,  9.91it/s]16 19:12:16 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:23<00:16,  9.92it/s]16 19:12:16 Save the image 01213N.png
 59%|███████████████████████▍                | 230/393 [00:23<00:16,  9.93it/s]16 19:12:16 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:23<00:16,  9.93it/s]16 19:12:16 Save the image 01215N.png
 59%|███████████████████████▌                | 232/393 [00:23<00:16,  9.92it/s]16 19:12:16 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:24<00:16,  9.89it/s]16 19:12:16 Save the image 01217N.png
 60%|███████████████████████▊                | 234/393 [00:24<00:16,  9.91it/s]16 19:12:17 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:24<00:15,  9.90it/s]16 19:12:17 Save the image 01219N.png
 60%|████████████████████████                | 236/393 [00:24<00:15,  9.87it/s]16 19:12:17 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:24<00:15,  9.87it/s]16 19:12:17 Save the image 01221N.png
 61%|████████████████████████▏               | 238/393 [00:24<00:15,  9.87it/s]16 19:12:17 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:24<00:15,  9.91it/s]16 19:12:17 Save the image 01223N.png
 61%|████████████████████████▍               | 240/393 [00:24<00:15,  9.92it/s]16 19:12:17 Save the image 01224N.png
16 19:12:17 Save the image 01225N.png
 62%|████████████████████████▋               | 242/393 [00:24<00:15,  9.95it/s]16 19:12:17 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:25<00:15,  9.93it/s]16 19:12:17 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:25<00:15,  9.92it/s]16 19:12:18 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:25<00:14,  9.91it/s]16 19:12:18 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:25<00:14,  9.87it/s]16 19:12:18 Save the image 01230N.png
 63%|█████████████████████████▏              | 247/393 [00:25<00:14,  9.84it/s]16 19:12:18 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:25<00:14,  9.84it/s]16 19:12:18 Save the image 01232N.png
 63%|█████████████████████████▎              | 249/393 [00:25<00:14,  9.86it/s]16 19:12:18 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:25<00:14,  9.85it/s]16 19:12:18 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:25<00:14,  9.83it/s]16 19:12:18 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:25<00:14,  9.86it/s]16 19:12:18 Save the image 01236N.png
 64%|█████████████████████████▊              | 253/393 [00:26<00:14,  9.87it/s]16 19:12:18 Save the image 01237N.png

 65%|█████████████████████████▊              | 254/393 [00:26<00:14,  9.87it/s]16 19:12:19 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:26<00:13,  9.89it/s]16 19:12:19 Save the image 01239N.png
 65%|██████████████████████████              | 256/393 [00:26<00:13,  9.90it/s]16 19:12:19 Save the image 01240N.png
16 19:12:19 Save the image 01241N.png
 66%|██████████████████████████▎             | 258/393 [00:26<00:13,  9.97it/s]16 19:12:19 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:26<00:13,  9.97it/s]16 19:12:19 Save the image 01243N.png
 66%|██████████████████████████▍             | 260/393 [00:26<00:13,  9.97it/s]16 19:12:19 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:26<00:13,  9.98it/s]16 19:12:19 Save the image 01245N.png
 67%|██████████████████████████▋             | 262/393 [00:26<00:13,  9.97it/s]16 19:12:19 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:27<00:13,  9.97it/s]16 19:12:19 Save the image 01247N.png
 67%|██████████████████████████▊             | 264/393 [00:27<00:12,  9.95it/s]16 19:12:20 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:27<00:12,  9.97it/s]16 19:12:20 Save the image 01249N.png
 68%|███████████████████████████             | 266/393 [00:27<00:12,  9.93it/s]16 19:12:20 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:27<00:12,  9.91it/s]16 19:12:20 Save the image 01251N.png
 68%|███████████████████████████▎            | 268/393 [00:27<00:12,  9.92it/s]16 19:12:20 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:27<00:12,  9.92it/s]16 19:12:20 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:27<00:12,  9.93it/s]16 19:12:20 Save the image 01254N.png
 69%|███████████████████████████▌            | 271/393 [00:27<00:12,  9.93it/s]16 19:12:20 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:27<00:12,  9.90it/s]16 19:12:20 Save the image 01256N.png
 69%|███████████████████████████▊            | 273/393 [00:28<00:12,  9.92it/s]16 19:12:20 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:28<00:12,  9.91it/s]16 19:12:21 Save the image 01258N.png
 70%|███████████████████████████▉            | 275/393 [00:28<00:11,  9.91it/s]16 19:12:21 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:28<00:11,  9.90it/s]16 19:12:21 Save the image 01260N.png
 70%|████████████████████████████▏           | 277/393 [00:28<00:11,  9.90it/s]16 19:12:21 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:28<00:11,  9.88it/s]16 19:12:21 Save the image 01262N.png
 71%|████████████████████████████▍           | 279/393 [00:28<00:11,  9.90it/s]16 19:12:21 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:28<00:11,  9.90it/s]16 19:12:21 Save the image 01264N.png
 72%|████████████████████████████▌           | 281/393 [00:28<00:11,  9.87it/s]16 19:12:21 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:28<00:11,  9.87it/s]16 19:12:21 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:29<00:11,  9.87it/s]16 19:12:22 Save the image 01267N.png
 72%|████████████████████████████▉           | 284/393 [00:29<00:11,  9.87it/s]16 19:12:22 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:29<00:10,  9.88it/s]16 19:12:22 Save the image 01269N.png
 73%|█████████████████████████████           | 286/393 [00:29<00:10,  9.89it/s]16 19:12:22 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:29<00:10,  9.88it/s]16 19:12:22 Save the image 01271N.png
 73%|█████████████████████████████▎          | 288/393 [00:29<00:10,  9.87it/s]16 19:12:22 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:29<00:10,  9.86it/s]16 19:12:22 Save the image 01273N.png
 74%|█████████████████████████████▌          | 290/393 [00:29<00:10,  9.89it/s]16 19:12:22 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:29<00:10,  9.91it/s]16 19:12:22 Save the image 01275N.png
 74%|█████████████████████████████▋          | 292/393 [00:30<00:10,  9.80it/s]16 19:12:22 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:30<00:10,  9.81it/s]16 19:12:23 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:30<00:10,  9.82it/s]16 19:12:23 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:30<00:09,  9.82it/s]16 19:12:23 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:30<00:09,  9.76it/s]16 19:12:23 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:30<00:09,  9.67it/s]16 19:12:23 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:30<00:09,  9.62it/s]16 19:12:23 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:30<00:09,  9.63it/s]16 19:12:23 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:30<00:09,  9.66it/s]16 19:12:23 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:30<00:09,  9.68it/s]16 19:12:23 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:31<00:09,  9.65it/s]16 19:12:23 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:31<00:09,  9.55it/s]16 19:12:24 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:31<00:09,  9.51it/s]16 19:12:24 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:31<00:09,  9.52it/s]16 19:12:24 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:31<00:09,  9.50it/s]16 19:12:24 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:31<00:09,  9.46it/s]16 19:12:24 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:31<00:08,  9.48it/s]16 19:12:24 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:31<00:08,  9.55it/s]16 19:12:24 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:31<00:08,  9.52it/s]16 19:12:24 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:31<00:08,  9.52it/s]16 19:12:24 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:32<00:08,  9.60it/s]16 19:12:25 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:32<00:08,  9.65it/s]16 19:12:25 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:32<00:08,  9.70it/s]16 19:12:25 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:32<00:08,  9.69it/s]16 19:12:25 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:32<00:07,  9.63it/s]16 19:12:25 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:32<00:07,  9.61it/s]16 19:12:25 Save the image 01301N.png
 81%|████████████████████████████████▎       | 318/393 [00:32<00:07,  9.62it/s]16 19:12:25 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:32<00:07,  9.67it/s]16 19:12:25 Save the image 01303N.png

 81%|████████████████████████████████▌       | 320/393 [00:32<00:07,  9.51it/s]16 19:12:25 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:33<00:07,  9.26it/s]16 19:12:25 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:33<00:07,  9.17it/s]16 19:12:26 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [00:33<00:07,  9.07it/s]16 19:12:26 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:33<00:07,  9.03it/s]16 19:12:26 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:33<00:07,  8.97it/s]16 19:12:26 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:33<00:07,  8.87it/s]16 19:12:26 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:33<00:07,  8.81it/s]16 19:12:26 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:33<00:07,  8.75it/s]16 19:12:26 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:33<00:07,  8.71it/s]16 19:12:26 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:34<00:07,  8.69it/s]16 19:12:26 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:34<00:07,  8.67it/s]16 19:12:27 Save the image 01315N.png
 84%|█████████████████████████████████▊      | 332/393 [00:34<00:06,  8.76it/s]16 19:12:27 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:34<00:06,  8.80it/s]16 19:12:27 Save the image 01317N.png
 85%|█████████████████████████████████▉      | 334/393 [00:34<00:06,  8.83it/s]16 19:12:27 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [00:34<00:06,  8.87it/s]16 19:12:27 Save the image 01319N.png
 85%|██████████████████████████████████▏     | 336/393 [00:34<00:06,  8.90it/s]16 19:12:27 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [00:34<00:06,  8.90it/s]16 19:12:27 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [00:34<00:06,  8.81it/s]16 19:12:27 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [00:35<00:06,  8.82it/s]16 19:12:27 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [00:35<00:05,  9.02it/s]16 19:12:28 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [00:35<00:05,  9.15it/s]16 19:12:28 Save the image 01325N.png
 87%|██████████████████████████████████▊     | 342/393 [00:35<00:05,  9.26it/s]16 19:12:28 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [00:35<00:05,  9.41it/s]16 19:12:28 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [00:35<00:05,  9.47it/s]16 19:12:28 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [00:35<00:05,  9.58it/s]16 19:12:28 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [00:35<00:04,  9.66it/s]16 19:12:28 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [00:35<00:04,  9.69it/s]16 19:12:28 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [00:36<00:04,  9.71it/s]16 19:12:28 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [00:36<00:04,  9.72it/s]16 19:12:29 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [00:36<00:04,  9.73it/s]16 19:12:29 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [00:36<00:04,  9.71it/s]16 19:12:29 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [00:36<00:04,  9.74it/s]16 19:12:29 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [00:36<00:04,  9.72it/s]16 19:12:29 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [00:36<00:04,  9.73it/s]16 19:12:29 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [00:36<00:03,  9.74it/s]16 19:12:29 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [00:36<00:03,  9.76it/s]16 19:12:29 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [00:36<00:03,  9.76it/s]16 19:12:29 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [00:37<00:03,  9.73it/s]16 19:12:29 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [00:37<00:03,  9.74it/s]16 19:12:30 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [00:37<00:03,  9.75it/s]16 19:12:30 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [00:37<00:03,  9.75it/s]16 19:12:30 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [00:37<00:03,  9.76it/s]16 19:12:30 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [00:37<00:03,  9.77it/s]16 19:12:30 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [00:37<00:02,  9.76it/s]16 19:12:30 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [00:37<00:02,  9.76it/s]16 19:12:30 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [00:37<00:02,  9.77it/s]16 19:12:30 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [00:37<00:02,  9.77it/s]16 19:12:30 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [00:38<00:02,  9.77it/s]16 19:12:30 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [00:38<00:02,  9.76it/s]16 19:12:31 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [00:38<00:02,  9.81it/s]16 19:12:31 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [00:38<00:02,  9.82it/s]16 19:12:31 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [00:38<00:02,  9.85it/s]16 19:12:31 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [00:38<00:02,  9.85it/s]16 19:12:31 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [00:38<00:01,  9.85it/s]16 19:12:31 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [00:38<00:01,  9.86it/s]16 19:12:31 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [00:38<00:01,  9.85it/s]16 19:12:31 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [00:38<00:01,  9.86it/s]16 19:12:31 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [00:39<00:01,  9.85it/s]16 19:12:31 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [00:39<00:01,  9.82it/s]16 19:12:32 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [00:39<00:01,  9.85it/s]16 19:12:32 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [00:39<00:01,  9.84it/s]16 19:12:32 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [00:39<00:01,  9.88it/s]16 19:12:32 Save the image 01366N.png
 97%|██████████████████████████████████████▉ | 383/393 [00:39<00:01,  9.89it/s]16 19:12:32 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [00:39<00:00,  9.91it/s]16 19:12:32 Save the image 01368N.png

 98%|███████████████████████████████████████▏| 385/393 [00:39<00:00,  9.88it/s]16 19:12:32 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [00:39<00:00,  9.86it/s]16 19:12:32 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [00:39<00:00,  9.86it/s]16 19:12:32 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [00:40<00:00,  9.86it/s]16 19:12:32 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [00:40<00:00,  9.88it/s]16 19:12:33 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [00:40<00:00,  9.87it/s]16 19:12:33 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [00:40<00:00,  9.86it/s]16 19:12:33 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [00:40<00:00,  9.86it/s]16 19:12:33 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [00:40<00:00,  9.68it/s]
1 unlabeled	98.318%
2 car   	89.264%
3 person	75.482%
4 bike  	65.006%
5 curve 	47.410%
6 car_stop	32.014%
7 guardrail	7.243%
8 color_cone	52.236%
9 bump  	58.436%
----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
16 19:12:33 Evaluation Elapsed Time: 40.60s

In [31]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -n -E 'split|test.txt|val.txt|test' eval.py

/home/cse-sdpl/Downloads/CMX_E5
81:    parser.add_argument('--split', choices=['train', 'val', 'test'], default='val')
97:                    'test_source': config.test_source,
100:    dataset = RGBXDataset(data_setting, args.split, val_pre)

In [32]:
!ls -ld predictions_E5_val predictions_E5_test
!find predictions_E5_val -type f | wc -l
!find predictions_E5_test -type f | wc -l

ls: cannot access 'predictions_E5_val': No such file or directory
drwxrwxr-x 2 cse-sdpl cse-sdpl 12288 Oct 16 19:08 predictions_E5_test
find: ‘predictions_E5_val’: No such file or directory
0
393

In [33]:
%cd /home/cse-sdpl/Downloads/CMX_E5

# Check dataset split paths configured in the project
!grep -n -E 'val_source|test_source|train_source' config.py

# Inspect the saved test predictions
!ls -lh predictions_E5_test | head -15

# Check whether validation predictions exist under another name
!find . -maxdepth 2 -type d -iname '*val*' | head -30

/home/cse-sdpl/Downloads/CMX_E5
43:C.train_source = osp.join(C.dataset_path, 'train.txt')
44:C.eval_source = osp.join(C.dataset_path, 'val.txt')
45:C.test_source = osp.join(C.dataset_path, 'test.txt')
total 1.7M
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.7K Oct 16 19:12 01189N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.0K Oct 16 19:12 01190N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 1.2K Oct 16 19:12 01191N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 1.2K Oct 16 19:12 01192N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 1.2K Oct 16 19:12 01193N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.0K Oct 16 19:12 01194N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.6K Oct 16 19:12 01195N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 1.7K Oct 16 19:12 01196N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.9K Oct 16 19:12 01197N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.2K Oct 16 19:12 01198N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.3K Oct 16 19:12 01199N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.1K Oct 16 19:12 01200N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.0K Oct 16 19:12 01201N.png
-rw-rw-r-- 1 cse-sdpl cse-sdpl 2.2K Oct 16 19:12 01202N.png
ls: write error: Broken pipe

In [34]:

%cd /home/cse-sdpl/Downloads/CMX_E5

# 1. Check how eval.py chooses the split and loads the dataset
!sed -n '70,125p' eval.py

# 2. Check whether val_pre changes the split behavior
!grep -n -E 'val_pre|eval_source|test_source|RGBXDataset' eval.py

# 3. Check the list files and their first entries
!head -5 /home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/test.txt
!head -5 /home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/val.txt

/home/cse-sdpl/Downloads/CMX_E5
        return result_line

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-e', '--epochs', default='last', type=str)
    parser.add_argument('-d', '--devices', default='0', type=str)
    parser.add_argument('-v', '--verbose', default=False, action='store_true')
    parser.add_argument('--show_image', '-s', default=False,
                        action='store_true')
    parser.add_argument('--save_path', '-p', default=None)

    parser.add_argument('--split', choices=['train', 'val', 'test'], default='val')
    args = parser.parse_args()
    all_dev = parse_devices(args.devices)

    network = segmodel(cfg=config, criterion=None, norm_layer=nn.BatchNorm2d)
    data_setting = {'rgb_root': config.rgb_root_folder,
                    'rgb_format': config.rgb_format,
                    'gt_root': config.gt_root_folder,
                    'gt_format': config.gt_format,
                    'transform_gt': config.gt_transform,
                    'x_root':config.x_root_folder,
                    'x_format': config.x_format,
                    'x_single_channel': config.x_is_single_channel,
                    'class_names': config.class_names,
                    'train_source': config.train_source,
                    'eval_source': config.eval_source,
                    'test_source': config.test_source,
                    'class_names': config.class_names}
    val_pre = ValPre()
    dataset = RGBXDataset(data_setting, args.split, val_pre)

    with torch.no_grad():
        segmentor = SegEvaluator(dataset, config.num_classes, config.norm_mean,
                                 config.norm_std, network,
                                 config.eval_scale_array, config.eval_flip,
                                 all_dev, args.verbose, args.save_path,
                                 args.show_image)
        segmentor.run(config.checkpoint_dir, args.epochs, config.val_log_file,
                      config.link_val_log_file)
16:from dataloader.RGBXDataset import RGBXDataset
96:                    'eval_source': config.eval_source,
97:                    'test_source': config.test_source,
99:    val_pre = ValPre()
100:    dataset = RGBXDataset(data_setting, args.split, val_pre)
01402D
01403D
01404D
01405D
01406D
00498D
00499D
00500D
00501D
00502D

In [35]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -n -A45 -B10 'def __init__' dataloader/RGBXDataset.py

/home/cse-sdpl/Downloads/CMX_E5
1-import os
2-from pickletools import uint8
3-import cv2
4-import torch
5-import numpy as np
6-
7-import torch.utils.data as data
8-
9-
10-class RGBXDataset(data.Dataset):
11:    def __init__(self, setting, split_name, preprocess=None, file_length=None):
12-        super(RGBXDataset, self).__init__()
13-        self._split_name = split_name
14-        self._rgb_path = setting['rgb_root']
15-        self._rgb_format = setting['rgb_format']
16-        self._gt_path = setting['gt_root']
17-        self._gt_format = setting['gt_format']
18-        self._transform_gt = setting['transform_gt']
19-        self._x_path = setting['x_root']
20-        self._x_format = setting['x_format']
21-        self._x_single_channel = setting['x_single_channel']
22-        self._train_source = setting['train_source']
23-        self._eval_source = setting['eval_source']
24-        self._test_source = setting['test_source']
25-        self.class_names = setting['class_names']
26-        self._file_names = self._get_file_names(split_name)
27-        self._file_length = file_length
28-        self.preprocess = preprocess
29-
30-    def __len__(self):
31-        if self._file_length is not None:
32-            return self._file_length
33-        return len(self._file_names)
34-
35-    def __getitem__(self, index):
36-        if self._file_length is not None:
37-            item_name = self._construct_new_file_names(self._file_length)[index]
38-        else:
39-            item_name = self._file_names[index]
40-        rgb_path = os.path.join(self._rgb_path, item_name + self._rgb_format)
41-        x_path = os.path.join(self._x_path, item_name + self._x_format)
42-        gt_path = os.path.join(self._gt_path, item_name + self._gt_format)
43-
44-        # Check the following settings if necessary
45-        rgb = self._open_image(rgb_path, cv2.COLOR_BGR2RGB)
46-
47-        gt = self._open_image(gt_path, cv2.IMREAD_GRAYSCALE, dtype=np.uint8)
48-        if self._transform_gt:
49-            gt = self._gt_transform(gt)
50-
51-        if self._x_single_channel:
52-            x = self._open_image(x_path, cv2.IMREAD_GRAYSCALE)
53-            x = cv2.merge([x, x, x])
54-        else:
55-            x =  self._open_image(x_path, cv2.COLOR_BGR2RGB)
56-

In [36]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -n -A30 -B5 'def _get_file_names' dataloader/RGBXDataset.py

/home/cse-sdpl/Downloads/CMX_E5
60-
61-        output_dict = dict(data=rgb, label=gt, modal_x=x, fn=str(item_name), n=len(self._file_names))
62-
63-        return output_dict
64-
65:    def _get_file_names(self, split_name):
66-        assert split_name in ['train', 'val', 'test']
67-        source = self._train_source
68-        if split_name == "val":
69-            source = self._eval_source
70-        elif split_name == "test":
71-            source = self._test_source
72-
73-        file_names = []
74-        with open(source) as f:
75-            files = f.readlines()
76-
77-        for item in files:
78-            file_name = item.strip()
79-            file_names.append(file_name)
80-
81-        return file_names
82-
83-    def _construct_new_file_names(self, length):
84-        assert isinstance(length, int)
85-        files_len = len(self._file_names)
86-        new_file_names = self._file_names * (length // files_len)
87-
88-        rand_indices = torch.randperm(files_len).tolist()
89-        new_indices = rand_indices[:length % files_len]
90-
91-        new_file_names += [self._file_names[i] for i in new_indices]
92-
93-        return new_file_names
94-
95-    def get_length(self):

In [37]:
import config
from dataloader.RGBXDataset import RGBXDataset
from dataloader.RGBXDataset import ValPre

setting = {
    'rgb_root': config.rgb_root_folder,
    'rgb_format': config.rgb_format,
    'gt_root': config.gt_root_folder,
    'gt_format': config.gt_format,
    'transform_gt': config.gt_transform,
    'x_root': config.x_root_folder,
    'x_format': config.x_format,
    'x_single_channel': config.x_is_single_channel,
    'class_names': config.class_names,
    'train_source': config.train_source,
    'eval_source': config.eval_source,
    'test_source': config.test_source,
}

for split in ['val', 'test']:
    ds = RGBXDataset(setting, split, ValPre())
    print(f"{split}: {len(ds)} images")
    print(f"First 5 IDs: {ds._file_names[:5]}")

ImportError: cannot import name 'ValPre' from 'dataloader.RGBXDataset' (/home/cse-sdpl/Downloads/CMX_E5/dataloader/RGBXDataset.py)

In [38]:
%cd /home/cse-sdpl/Downloads/CMX_E5

import config
from dataloader.RGBXDataset import RGBXDataset

setting = {
    'rgb_root': config.rgb_root_folder,
    'rgb_format': config.rgb_format,
    'gt_root': config.gt_root_folder,
    'gt_format': config.gt_format,
    'transform_gt': config.gt_transform,
    'x_root': config.x_root_folder,
    'x_format': config.x_format,
    'x_single_channel': config.x_is_single_channel,
    'class_names': config.class_names,
    'train_source': config.train_source,
    'eval_source': config.eval_source,
    'test_source': config.test_source,
}

for split in ['val', 'test']:
    ds = RGBXDataset(setting, split, preprocess=None)
    print(f"\n{split.upper()} images: {len(ds)}")
    print("First 5 IDs:", ds._file_names[:5])
    print("Last 5 IDs:", ds._file_names[-5:])

/home/cse-sdpl/Downloads/CMX_E5

/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/IPython/core/magics/osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

AttributeError: module 'config' has no attribute 'rgb_root_folder'

In [39]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!head -70 eval.py
!grep -n -E 'rgb_root_folder|gt_root_folder|x_root_folder|class_names|config =' config.py
!grep -n -A25 'def _get_file_names' dataloader/RGBXDataset.py

/home/cse-sdpl/Downloads/CMX_E5
from PIL import Image
import os
import cv2
import argparse
import numpy as np

import torch
import torch.nn as nn

from config import config
from utils.pyt_utils import ensure_dir, link_file, load_model, parse_devices
from utils.visualize import print_iou, show_img
from engine.evaluator import Evaluator
from engine.logger import get_logger
from utils.metric import hist_info, compute_score
from dataloader.RGBXDataset import RGBXDataset
from models.builder import EncoderDecoder as segmodel
from dataloader.dataloader import ValPre

logger = get_logger()

class SegEvaluator(Evaluator):
    def func_per_iteration(self, data, device):
        img = data['data']
        label = data['label']
        modal_x = data['modal_x']
        name = data['fn']
        pred = self.sliding_eval_rgbX(img, modal_x, config.eval_crop_size, config.eval_stride_rate, device)
        hist_tmp, labeled_tmp, correct_tmp = hist_info(config.num_classes, pred, label)
        results_dict = {'hist': hist_tmp, 'labeled': labeled_tmp, 'correct': correct_tmp}

        if self.save_path is not None:
            ensure_dir(self.save_path)
            ensure_dir(self.save_path+'_color')

            fn = name + '.png'

            # save colored result

            # save raw result
            cv2.imwrite(os.path.join(self.save_path, fn), pred)
            logger.info('Save the image ' + fn)

        if self.show_image:
            colors = self.dataset.get_class_colors
            image = img
            clean = np.zeros(label.shape)
            comp_img = show_img(colors, config.background, image, clean,
                                label,
                                pred)
            cv2.imshow('comp_image', comp_img)
            cv2.waitKey(0)

        return results_dict

    def compute_metric(self, results):
        hist = np.zeros((config.num_classes, config.num_classes))
        correct = 0
        labeled = 0
        count = 0
        for d in results:
            hist += d['hist']
            correct += d['correct']
            labeled += d['labeled']
            count += 1

        iou, mean_IoU, _, freq_IoU, mean_pixel_acc, pixel_acc = compute_score(hist, correct, labeled)
        result_line = print_iou(iou, freq_IoU, mean_pixel_acc, pixel_acc,
                                dataset.class_names, show_no_back=False)
        return result_line
11:config = C
29:C.rgb_root_folder = osp.join(C.dataset_path, 'RGB')
33:C.gt_root_folder = osp.join(C.dataset_path, 'Label')
38:C.x_root_folder = osp.join(C.dataset_path, 'Thermal')
54:C.class_names = [
65:    def _get_file_names(self, split_name):
66-        assert split_name in ['train', 'val', 'test']
67-        source = self._train_source
68-        if split_name == "val":
69-            source = self._eval_source
70-        elif split_name == "test":
71-            source = self._test_source
72-
73-        file_names = []
74-        with open(source) as f:
75-            files = f.readlines()
76-
77-        for item in files:
78-            file_name = item.strip()
79-            file_names.append(file_name)
80-
81-        return file_names
82-
83-    def _construct_new_file_names(self, length):
84-        assert isinstance(length, int)
85-        files_len = len(self._file_names)
86-        new_file_names = self._file_names * (length // files_len)
87-
88-        rand_indices = torch.randperm(files_len).tolist()
89-        new_indices = rand_indices[:length % files_len]
90-

In [40]:
%cd /home/cse-sdpl/Downloads/CMX_E5

from config import config
from dataloader.RGBXDataset import RGBXDataset

setting = {
    'rgb_root': config.rgb_root_folder,
    'rgb_format': config.rgb_format,
    'gt_root': config.gt_root_folder,
    'gt_format': config.gt_format,
    'transform_gt': config.gt_transform,
    'x_root': config.x_root_folder,
    'x_format': config.x_format,
    'x_single_channel': config.x_is_single_channel,
    'class_names': config.class_names,
    'train_source': config.train_source,
    'eval_source': config.eval_source,
    'test_source': config.test_source,
}

for split in ['val', 'test']:
    ds = RGBXDataset(setting, split, preprocess=None)
    print(f"\n{split.upper()} count: {len(ds)}")
    print("First 5 IDs:", ds._file_names[:5])
    print("Last 5 IDs:", ds._file_names[-5:])

/home/cse-sdpl/Downloads/CMX_E5

VAL count: 392
First 5 IDs: ['00498D', '00499D', '00500D', '00501D', '00502D']
Last 5 IDs: ['01184N', '01185N', '01186N', '01187N', '01188N']

TEST count: 393
First 5 IDs: ['01402D', '01403D', '01404D', '01405D', '01406D']
Last 5 IDs: ['01372N', '01373N', '01374N', '01375N', '01376N']

In [41]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -R -n -E 'mean_IoU|freq_IoU|58.379|98.318' log_TDD_mit_b2_e5 2>/dev/null | tail -30

/home/cse-sdpl/Downloads/CMX_E5
log_TDD_mit_b2_e5/val_2026_10_16_19_11_50.log:2:1 unlabeled	98.318%
log_TDD_mit_b2_e5/val_2026_10_16_19_11_50.log:11:----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
log_TDD_mit_b2_e5/val_2026_10_16_19_09_42.log:2:1 unlabeled	98.318%
log_TDD_mit_b2_e5/val_2026_10_16_19_09_42.log:11:----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
log_TDD_mit_b2_e5/val_last.log:2:1 unlabeled	98.318%
log_TDD_mit_b2_e5/val_last.log:11:----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
log_TDD_mit_b2_e5/val_2026_10_16_19_07_46.log:2:1 unlabeled	98.318%
log_TDD_mit_b2_e5/val_2026_10_16_19_07_46.log:11:----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%

In [42]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -n -A100 -B15 'def run' engine/evaluator.py

/home/cse-sdpl/Downloads/CMX_E5
27-        self.multi_scales = multi_scales
28-        self.is_flip = is_flip
29-        self.network = network
30-        self.devices = devices
31-
32-        self.context = mp.get_context('spawn')
33-        self.val_func = None
34-        self.results_queue = self.context.Queue(self.ndata)
35-
36-        self.verbose = verbose
37-        self.save_path = save_path
38-        if save_path is not None:
39-            ensure_dir(save_path)
40-        self.show_image = show_image
41-
42:    def run(self, model_path, model_indice, log_file, log_file_link):
43-        """There are four evaluation modes:
44-            1.only eval a .pth model: -e *.pth
45-            2.only eval a certain epoch: -e epoch
46-            3.eval all epochs in a given section: -e start_epoch-end_epoch
47-            4.eval all epochs from a certain started epoch: -e start_epoch-
48-            """
49-        if '.pth' in model_indice:
50-            models = [model_indice, ]
51-        elif "-" in model_indice:
52-            start_epoch = int(model_indice.split("-")[0])
53-            end_epoch = model_indice.split("-")[1]
54-
55-            models = os.listdir(model_path)
56-            models.remove("epoch-last.pth")
57-            sorted_models = [None] * len(models)
58-            model_idx = [0] * len(models)
59-
60-            for idx, m in enumerate(models):
61-                num = m.split(".")[0].split("-")[1]
62-                model_idx[idx] = num
63-                sorted_models[idx] = m
64-            model_idx = np.array([int(i) for i in model_idx])
65-
66-            down_bound = model_idx >= start_epoch
67-            up_bound = [True] * len(sorted_models)
68-            if end_epoch:
69-                end_epoch = int(end_epoch)
70-                assert start_epoch < end_epoch
71-                up_bound = model_idx <= end_epoch
72-            bound = up_bound * down_bound
73-            model_slice = np.array(sorted_models)[bound]
74-            models = [os.path.join(model_path, model) for model in
75-                      model_slice]
76-        else:
77-            if os.path.exists(model_path):
78-                models = [os.path.join(model_path, 'epoch-%s.pth' % model_indice), ]
79-            else:
80-                models = [None]
81-
82-        results = open(log_file, 'a')
83-        link_file(log_file, log_file_link)
84-
85-        for model in models:
86-            logger.info("Load Model: %s" % model)
87-            self.val_func = load_model(self.network, model)
88-            if len(self.devices ) == 1:
89-                result_line = self.single_process_evalutation()
90-            else:
91-                result_line = self.multi_process_evaluation()
92-
93-            results.write('Model: ' + model + '\n')
94-            results.write(result_line)
95-            results.write('\n')
96-            results.flush()
97-
98-        results.close()
99-
100-
101-    def single_process_evalutation(self):
102-        start_eval_time = time.perf_counter()
103-
104-        logger.info('GPU %s handle %d data.' % (self.devices[0], self.ndata))
105-        all_results = []
106-        for idx in tqdm(range(self.ndata)):
107-            dd = self.dataset[idx]
108-            results_dict = self.func_per_iteration(dd,self.devices[0])
109-            all_results.append(results_dict)
110-        result_line = self.compute_metric(all_results)
111-        logger.info(
112-            'Evaluation Elapsed Time: %.2fs' % (
113-                    time.perf_counter() - start_eval_time))
114-        return result_line
115-
116-
117-    def multi_process_evaluation(self):
118-        start_eval_time = time.perf_counter()
119-        nr_devices = len(self.devices)
120-        stride = int(np.ceil(self.ndata / nr_devices))
121-
122-        # start multi-process on multi-gpu
123-        procs = []
124-        for d in range(nr_devices):
125-
126-            e_record = min((d + 1) * stride, self.ndata)
127-            shred_list = list(range(d * stride, e_record))
128-            device = self.devices[d]
129-            logger.info('GPU %s handle %d data.' % (device, len(shred_list)))
130-
131-            p = self.context.Process(target=self.worker,
132-                                     args=(shred_list, device))
133-            procs.append(p)
134-
135-        for p in procs:
136-
137-            p.start()
138-
139-        all_results = []
140-        for _ in tqdm(range(self.ndata)):
141-            t = self.results_queue.get()
142-            all_results.append(t)

In [43]:
from pathlib import Path

test_file = Path(
    "/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/test.txt"
)
pred_dir = Path("predictions_E5_test")

test_ids = {line.strip() for line in test_file.read_text().splitlines() if line.strip()}
pred_ids = {p.stem for p in pred_dir.glob("*.png")}

print("Test IDs:", len(test_ids))
print("Prediction IDs:", len(pred_ids))
print("Predictions matching test IDs:", len(test_ids & pred_ids))
print("Predictions not in test list:", sorted(pred_ids - test_ids)[:10])
print("Missing test predictions:", sorted(test_ids - pred_ids)[:10])

Test IDs: 393
Prediction IDs: 393
Predictions matching test IDs: 393
Predictions not in test list: []
Missing test predictions: []

In [44]:
%cd /home/cse-sdpl/Downloads/CMX_E5

from config import config
from dataloader.RGBXDataset import RGBXDataset
from dataloader.dataloader import ValPre

setting = {
    'rgb_root': config.rgb_root_folder,
    'rgb_format': config.rgb_format,
    'gt_root': config.gt_root_folder,
    'gt_format': config.gt_format,
    'transform_gt': config.gt_transform,
    'x_root': config.x_root_folder,
    'x_format': config.x_format,
    'x_single_channel': config.x_is_single_channel,
    'class_names': config.class_names,
    'train_source': config.train_source,
    'eval_source': config.eval_source,
    'test_source': config.test_source,
}

test_ds = RGBXDataset(setting, 'test', ValPre())

print("Dataset length:", len(test_ds))
for i in [0, 1, 2, len(test_ds)-1]:
    item = test_ds[i]
    print(i, item['fn'])

/home/cse-sdpl/Downloads/CMX_E5
Dataset length: 393
0 01402D
1 01403D
2 01404D
392 01376N

In [45]:
%cd /home/cse-sdpl/Downloads/CMX_E5

from pathlib import Path
import hashlib

folder = Path("predictions_E5_test")
files = sorted(folder.glob("*.png"))

print("Number of prediction files:", len(files))

for f in files[:5]:
    digest = hashlib.md5(f.read_bytes()).hexdigest()
    print(f.name, digest)

/home/cse-sdpl/Downloads/CMX_E5
Number of prediction files: 393
01189N.png e4ee2c345e00d55250236dfcbc2f52ef
01190N.png 47270e7d8b1398f251253d1f2dd71eb4
01191N.png a50689866c60ea907ad9ce265c0f10ab
01192N.png a50689866c60ea907ad9ce265c0f10ab
01193N.png a50689866c60ea907ad9ce265c0f10ab

In [46]:
from pathlib import Path

base = Path("/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD")
pred_dir = Path("/home/cse-sdpl/Downloads/CMX_E5/predictions_E5_test")

def read_ids(path):
    return {x.strip() for x in path.read_text().splitlines() if x.strip()}

val_ids = read_ids(base / "val.txt")
test_ids = read_ids(base / "test.txt")
pred_ids = {p.stem for p in pred_dir.glob("*.png")}

print("Predictions matching validation IDs:", len(pred_ids & val_ids))
print("Predictions matching test IDs:", len(pred_ids & test_ids))
print("First 10 prediction IDs:", sorted(pred_ids)[:10])
print("First 10 test IDs:", sorted(test_ids)[:10])

Predictions matching validation IDs: 0
Predictions matching test IDs: 393
First 10 prediction IDs: ['01189N', '01190N', '01191N', '01192N', '01193N', '01194N', '01195N', '01196N', '01197N', '01198N']
First 10 test IDs: ['01189N', '01190N', '01191N', '01192N', '01193N', '01194N', '01195N', '01196N', '01197N', '01198N']

In [47]:
from pathlib import Path
import numpy as np
from PIL import Image

base = Path("/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD")
project = Path("/home/cse-sdpl/Downloads/CMX_E5")

val_ids = {x.strip() for x in (base / "val.txt").read_text().splitlines() if x.strip()}
test_ids = {x.strip() for x in (base / "test.txt").read_text().splitlines() if x.strip()}

print("Validation/test ID intersection:", len(val_ids & test_ids))
print("Test prediction count:", len(list((project / "predictions_E5_test").glob("*.png"))))

Validation/test ID intersection: 0
Test prediction count: 393

In [48]:
from pathlib import Path
import hashlib

base = Path("/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD")

print("Label root:", base / "labels")

for split in ["val", "test"]:
    ids = [
        x.strip()
        for x in (base / f"{split}.txt").read_text().splitlines()
        if x.strip()
    ]

    print(f"\n{split.upper()} — {len(ids)} images")
    for image_id in ids[:3]:
        matches = list(base.rglob(image_id + ".png"))
        print(image_id, [str(p) for p in matches[:3]])

Label root: /home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/labels

VAL — 392 images
00498D ['/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/RGB/00498D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Thermal/00498D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Label/00498D.png']
00499D ['/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/RGB/00499D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Thermal/00499D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Label/00499D.png']
00500D ['/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/RGB/00500D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Thermal/00500D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Label/00500D.png']

TEST — 393 images
01402D ['/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/RGB/01402D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Thermal/01402D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Label/01402D.png']
01403D ['/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/RGB/01403D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Thermal/01403D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Label/01403D.png']
01404D ['/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/RGB/01404D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Thermal/01404D.png', '/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD/Label/01404D.png']

In [49]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!python eval.py -e 100 -d 0 --split test -p predictions_E5_test_verify

/home/cse-sdpl/Downloads/CMX_E5
/home/cse-sdpl/miniconda3/envs/cmx/lib/python3.10/site-packages/timm/models/layers/__init__.py:49: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
16 19:23:30 using devices 0
16 19:23:30 Using E5: SegFormer-B2 with counterfactual reliability
16 19:23:31 Using MLP Decoder
16 19:23:34 Load Model: /home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2_e5/checkpoint/epoch-100.pth
16 19:23:34 Load model, Time usage:
	IO: 0.7498226165771484, initialize parameters: 0.04236721992492676
16 19:23:34 GPU 0 handle 393 data.
  0%|                                                  | 0/393 [00:00<?, ?it/s][ WARN:0@7.604] global loadsave.cpp:1089 imwrite_ Unsupported depth image for selected encoder is fallbacked to CV_8U.
16 19:23:36 Save the image 01402D.png
  0%|                                          | 1/393 [00:01<08:35,  1.32s/it]16 19:23:36 Save the image 01403D.png
  1%|▏                                         | 2/393 [00:01<03:56,  1.65it/s]16 19:23:36 Save the image 01404D.png
  1%|▎                                         | 3/393 [00:01<02:26,  2.66it/s]16 19:23:36 Save the image 01405D.png
  1%|▍                                         | 4/393 [00:01<01:43,  3.74it/s]16 19:23:36 Save the image 01406D.png
16 19:23:36 Save the image 01407D.png
  2%|▋                                         | 6/393 [00:01<01:08,  5.61it/s]16 19:23:36 Save the image 01408D.png
  2%|▋                                         | 7/393 [00:01<01:00,  6.38it/s]16 19:23:37 Save the image 01409D.png
  2%|▊                                         | 8/393 [00:02<00:54,  7.10it/s]16 19:23:37 Save the image 01410D.png
  2%|▉                                         | 9/393 [00:02<00:49,  7.74it/s]16 19:23:37 Save the image 01411D.png
  3%|█                                        | 10/393 [00:02<00:46,  8.27it/s]16 19:23:37 Save the image 01412D.png
  3%|█▏                                       | 11/393 [00:02<00:43,  8.71it/s]16 19:23:37 Save the image 01413D.png
  3%|█▎                                       | 12/393 [00:02<00:42,  9.03it/s]16 19:23:37 Save the image 01414D.png
  3%|█▎                                       | 13/393 [00:02<00:40,  9.29it/s]16 19:23:37 Save the image 01415D.png
  4%|█▍                                       | 14/393 [00:02<00:39,  9.48it/s]16 19:23:37 Save the image 01416D.png
  4%|█▌                                       | 15/393 [00:02<00:39,  9.62it/s]16 19:23:37 Save the image 01417D.png
  4%|█▋                                       | 16/393 [00:02<00:38,  9.69it/s]16 19:23:37 Save the image 01418D.png
  4%|█▊                                       | 17/393 [00:02<00:38,  9.75it/s]16 19:23:38 Save the image 01419D.png
  5%|█▉                                       | 18/393 [00:03<00:38,  9.79it/s]16 19:23:38 Save the image 01420D.png
  5%|█▉                                       | 19/393 [00:03<00:38,  9.83it/s]16 19:23:38 Save the image 01421D.png
  5%|██                                       | 20/393 [00:03<00:37,  9.86it/s]16 19:23:38 Save the image 01422D.png
  5%|██▏                                      | 21/393 [00:03<00:37,  9.87it/s]16 19:23:38 Save the image 01423D.png
  6%|██▎                                      | 22/393 [00:03<00:37,  9.90it/s]16 19:23:38 Save the image 01424D.png
  6%|██▍                                      | 23/393 [00:03<00:37,  9.92it/s]16 19:23:38 Save the image 01425D.png
  6%|██▌                                      | 24/393 [00:03<00:37,  9.92it/s]16 19:23:38 Save the image 01426D.png
  6%|██▌                                      | 25/393 [00:03<00:37,  9.91it/s]16 19:23:38 Save the image 01427D.png
  7%|██▋                                      | 26/393 [00:03<00:36,  9.92it/s]16 19:23:38 Save the image 01428D.png
  7%|██▊                                      | 27/393 [00:03<00:36,  9.92it/s]16 19:23:39 Save the image 01429D.png
16 19:23:39 Save the image 01430D.png
  7%|███                                      | 29/393 [00:04<00:36,  9.94it/s]16 19:23:39 Save the image 01431D.png
  8%|███▏                                     | 30/393 [00:04<00:36,  9.94it/s]16 19:23:39 Save the image 01432D.png
  8%|███▏                                     | 31/393 [00:04<00:36,  9.94it/s]16 19:23:39 Save the image 01433D.png
  8%|███▎                                     | 32/393 [00:04<00:36,  9.93it/s]16 19:23:39 Save the image 01434D.png
  8%|███▍                                     | 33/393 [00:04<00:36,  9.94it/s]16 19:23:39 Save the image 01435D.png
  9%|███▌                                     | 34/393 [00:04<00:36,  9.94it/s]16 19:23:39 Save the image 01436D.png
  9%|███▋                                     | 35/393 [00:04<00:35,  9.96it/s]16 19:23:39 Save the image 01437D.png
  9%|███▊                                     | 36/393 [00:04<00:35,  9.92it/s]16 19:23:39 Save the image 01438D.png
  9%|███▊                                     | 37/393 [00:04<00:35,  9.90it/s]16 19:23:40 Save the image 01439D.png
 10%|███▉                                     | 38/393 [00:05<00:35,  9.89it/s]16 19:23:40 Save the image 01440D.png
 10%|████                                     | 39/393 [00:05<00:35,  9.87it/s]16 19:23:40 Save the image 01441D.png
 10%|████▏                                    | 40/393 [00:05<00:35,  9.86it/s]16 19:23:40 Save the image 01442D.png
 10%|████▎                                    | 41/393 [00:05<00:35,  9.84it/s]16 19:23:40 Save the image 01443D.png
 11%|████▍                                    | 42/393 [00:05<00:36,  9.74it/s]16 19:23:40 Save the image 01444D.png
 11%|████▍                                    | 43/393 [00:05<00:36,  9.51it/s]16 19:23:40 Save the image 01445D.png
 11%|████▌                                    | 44/393 [00:05<00:37,  9.38it/s]16 19:23:40 Save the image 01446D.png
 11%|████▋                                    | 45/393 [00:05<00:37,  9.34it/s]16 19:23:40 Save the image 01447D.png
 12%|████▊                                    | 46/393 [00:05<00:36,  9.50it/s]16 19:23:40 Save the image 01448D.png
 12%|████▉                                    | 47/393 [00:05<00:36,  9.61it/s]16 19:23:41 Save the image 01449D.png
 12%|█████                                    | 48/393 [00:06<00:35,  9.69it/s]16 19:23:41 Save the image 01450D.png
 12%|█████                                    | 49/393 [00:06<00:35,  9.76it/s]16 19:23:41 Save the image 01451D.png
 13%|█████▏                                   | 50/393 [00:06<00:34,  9.80it/s]16 19:23:41 Save the image 01452D.png
 13%|█████▎                                   | 51/393 [00:06<00:35,  9.76it/s]16 19:23:41 Save the image 01453D.png
 13%|█████▍                                   | 52/393 [00:06<00:34,  9.80it/s]16 19:23:41 Save the image 01454D.png
 13%|█████▌                                   | 53/393 [00:06<00:35,  9.68it/s]16 19:23:41 Save the image 01455D.png
 14%|█████▋                                   | 54/393 [00:06<00:35,  9.51it/s]16 19:23:41 Save the image 01456D.png
 14%|█████▋                                   | 55/393 [00:06<00:35,  9.55it/s]16 19:23:41 Save the image 01457D.png
 14%|█████▊                                   | 56/393 [00:06<00:35,  9.62it/s]16 19:23:42 Save the image 01458D.png
 15%|█████▉                                   | 57/393 [00:07<00:34,  9.68it/s]16 19:23:42 Save the image 01459D.png
 15%|██████                                   | 58/393 [00:07<00:34,  9.74it/s]16 19:23:42 Save the image 01460D.png

 15%|██████▏                                  | 59/393 [00:07<00:34,  9.77it/s]16 19:23:42 Save the image 01461D.png
 15%|██████▎                                  | 60/393 [00:07<00:34,  9.79it/s]16 19:23:42 Save the image 01462D.png
 16%|██████▎                                  | 61/393 [00:07<00:33,  9.83it/s]16 19:23:42 Save the image 01463D.png
 16%|██████▍                                  | 62/393 [00:07<00:33,  9.85it/s]16 19:23:42 Save the image 01464D.png
 16%|██████▌                                  | 63/393 [00:07<00:33,  9.85it/s]16 19:23:42 Save the image 01465D.png
 16%|██████▋                                  | 64/393 [00:07<00:33,  9.85it/s]16 19:23:42 Save the image 01466D.png
 17%|██████▊                                  | 65/393 [00:07<00:33,  9.86it/s]16 19:23:42 Save the image 01467D.png
 17%|██████▉                                  | 66/393 [00:07<00:33,  9.85it/s]16 19:23:43 Save the image 01468D.png
 17%|██████▉                                  | 67/393 [00:08<00:33,  9.87it/s]16 19:23:43 Save the image 01469D.png
 17%|███████                                  | 68/393 [00:08<00:32,  9.90it/s]16 19:23:43 Save the image 01470D.png
 18%|███████▏                                 | 69/393 [00:08<00:32,  9.88it/s]16 19:23:43 Save the image 01471D.png
 18%|███████▎                                 | 70/393 [00:08<00:32,  9.88it/s]16 19:23:43 Save the image 01472D.png
 18%|███████▍                                 | 71/393 [00:08<00:32,  9.86it/s]16 19:23:43 Save the image 01473D.png
 18%|███████▌                                 | 72/393 [00:08<00:32,  9.86it/s]16 19:23:43 Save the image 01474D.png
 19%|███████▌                                 | 73/393 [00:08<00:32,  9.83it/s]16 19:23:43 Save the image 01475D.png
 19%|███████▋                                 | 74/393 [00:08<00:32,  9.71it/s]16 19:23:43 Save the image 01476D.png
 19%|███████▊                                 | 75/393 [00:08<00:32,  9.66it/s]16 19:23:43 Save the image 01477D.png
 19%|███████▉                                 | 76/393 [00:08<00:32,  9.62it/s]16 19:23:44 Save the image 01478D.png
 20%|████████                                 | 77/393 [00:09<00:32,  9.67it/s]16 19:23:44 Save the image 01479D.png
 20%|████████▏                                | 78/393 [00:09<00:32,  9.71it/s]16 19:23:44 Save the image 01480D.png
 20%|████████▏                                | 79/393 [00:09<00:32,  9.67it/s]16 19:23:44 Save the image 01481D.png
 20%|████████▎                                | 80/393 [00:09<00:32,  9.62it/s]16 19:23:44 Save the image 01482D.png
 21%|████████▍                                | 81/393 [00:09<00:32,  9.53it/s]16 19:23:44 Save the image 01483D.png
 21%|████████▌                                | 82/393 [00:09<00:32,  9.55it/s]16 19:23:44 Save the image 01484D.png
 21%|████████▋                                | 83/393 [00:09<00:32,  9.46it/s]16 19:23:44 Save the image 01485D.png
 21%|████████▊                                | 84/393 [00:09<00:32,  9.57it/s]16 19:23:44 Save the image 01486D.png
 22%|████████▊                                | 85/393 [00:09<00:31,  9.64it/s]16 19:23:44 Save the image 01487D.png
 22%|████████▉                                | 86/393 [00:09<00:31,  9.70it/s]16 19:23:45 Save the image 01488D.png
 22%|█████████                                | 87/393 [00:10<00:31,  9.67it/s]16 19:23:45 Save the image 01489D.png
 22%|█████████▏                               | 88/393 [00:10<00:31,  9.70it/s]16 19:23:45 Save the image 01490D.png
 23%|█████████▎                               | 89/393 [00:10<00:31,  9.71it/s]16 19:23:45 Save the image 01491D.png
 23%|█████████▍                               | 90/393 [00:10<00:31,  9.74it/s]16 19:23:45 Save the image 01492D.png
 23%|█████████▍                               | 91/393 [00:10<00:30,  9.78it/s]16 19:23:45 Save the image 01493D.png
 23%|█████████▌                               | 92/393 [00:10<00:30,  9.76it/s]16 19:23:45 Save the image 01494D.png
 24%|█████████▋                               | 93/393 [00:10<00:30,  9.69it/s]16 19:23:45 Save the image 01495D.png
 24%|█████████▊                               | 94/393 [00:10<00:31,  9.64it/s]16 19:23:45 Save the image 01496D.png
 24%|█████████▉                               | 95/393 [00:10<00:31,  9.58it/s]16 19:23:46 Save the image 01497D.png
 24%|██████████                               | 96/393 [00:11<00:31,  9.53it/s]16 19:23:46 Save the image 01498D.png
 25%|██████████                               | 97/393 [00:11<00:31,  9.53it/s]16 19:23:46 Save the image 01499D.png
 25%|██████████▏                              | 98/393 [00:11<00:30,  9.54it/s]16 19:23:46 Save the image 01500D.png
 25%|██████████▎                              | 99/393 [00:11<00:30,  9.51it/s]16 19:23:46 Save the image 01501D.png
 25%|██████████▏                             | 100/393 [00:11<00:30,  9.52it/s]16 19:23:46 Save the image 01502D.png
 26%|██████████▎                             | 101/393 [00:11<00:30,  9.52it/s]16 19:23:46 Save the image 01503D.png
 26%|██████████▍                             | 102/393 [00:11<00:30,  9.56it/s]16 19:23:46 Save the image 01504D.png
 26%|██████████▍                             | 103/393 [00:11<00:30,  9.62it/s]16 19:23:46 Save the image 01505D.png
 26%|██████████▌                             | 104/393 [00:11<00:30,  9.59it/s]16 19:23:46 Save the image 01506D.png
 27%|██████████▋                             | 105/393 [00:11<00:29,  9.61it/s]16 19:23:47 Save the image 01507D.png
 27%|██████████▊                             | 106/393 [00:12<00:29,  9.67it/s]16 19:23:47 Save the image 01508D.png
 27%|██████████▉                             | 107/393 [00:12<00:29,  9.73it/s]16 19:23:47 Save the image 01509D.png
 27%|██████████▉                             | 108/393 [00:12<00:29,  9.76it/s]16 19:23:47 Save the image 01510D.png
 28%|███████████                             | 109/393 [00:12<00:29,  9.77it/s]16 19:23:47 Save the image 01511D.png
 28%|███████████▏                            | 110/393 [00:12<00:29,  9.69it/s]16 19:23:47 Save the image 01512D.png
 28%|███████████▎                            | 111/393 [00:12<00:29,  9.64it/s]16 19:23:47 Save the image 01513D.png
 28%|███████████▍                            | 112/393 [00:12<00:29,  9.59it/s]16 19:23:47 Save the image 01514D.png
 29%|███████████▌                            | 113/393 [00:12<00:28,  9.66it/s]16 19:23:47 Save the image 01515D.png
 29%|███████████▌                            | 114/393 [00:12<00:29,  9.60it/s]16 19:23:48 Save the image 01516D.png
 29%|███████████▋                            | 115/393 [00:13<00:29,  9.55it/s]16 19:23:48 Save the image 01517D.png
 30%|███████████▊                            | 116/393 [00:13<00:29,  9.48it/s]16 19:23:48 Save the image 01518D.png
 30%|███████████▉                            | 117/393 [00:13<00:29,  9.50it/s]16 19:23:48 Save the image 01519D.png
 30%|████████████                            | 118/393 [00:13<00:28,  9.50it/s]16 19:23:48 Save the image 01520D.png
 30%|████████████                            | 119/393 [00:13<00:28,  9.49it/s]16 19:23:48 Save the image 01521D.png
 31%|████████████▏                           | 120/393 [00:13<00:28,  9.49it/s]16 19:23:48 Save the image 01522D.png
 31%|████████████▎                           | 121/393 [00:13<00:28,  9.47it/s]16 19:23:48 Save the image 01523D.png
 31%|████████████▍                           | 122/393 [00:13<00:28,  9.51it/s]16 19:23:48 Save the image 01524D.png
 31%|████████████▌                           | 123/393 [00:13<00:28,  9.57it/s]16 19:23:48 Save the image 01525D.png

 32%|████████████▌                           | 124/393 [00:13<00:28,  9.57it/s]16 19:23:49 Save the image 01526D.png
 32%|████████████▋                           | 125/393 [00:14<00:28,  9.53it/s]16 19:23:49 Save the image 01527D.png
 32%|████████████▊                           | 126/393 [00:14<00:27,  9.58it/s]16 19:23:49 Save the image 01528D.png
 32%|████████████▉                           | 127/393 [00:14<00:27,  9.57it/s]16 19:23:49 Save the image 01529D.png
 33%|█████████████                           | 128/393 [00:14<00:27,  9.50it/s]16 19:23:49 Save the image 01530D.png
 33%|█████████████▏                          | 129/393 [00:14<00:27,  9.58it/s]16 19:23:49 Save the image 01531D.png
 33%|█████████████▏                          | 130/393 [00:14<00:27,  9.52it/s]16 19:23:49 Save the image 01532D.png
 33%|█████████████▎                          | 131/393 [00:14<00:27,  9.52it/s]16 19:23:49 Save the image 01533D.png
 34%|█████████████▍                          | 132/393 [00:14<00:27,  9.44it/s]16 19:23:49 Save the image 01534D.png
 34%|█████████████▌                          | 133/393 [00:14<00:27,  9.44it/s]16 19:23:50 Save the image 01535D.png
 34%|█████████████▋                          | 134/393 [00:15<00:27,  9.46it/s]16 19:23:50 Save the image 01536D.png
 34%|█████████████▋                          | 135/393 [00:15<00:27,  9.47it/s]16 19:23:50 Save the image 01537D.png
 35%|█████████████▊                          | 136/393 [00:15<00:27,  9.47it/s]16 19:23:50 Save the image 01538D.png
 35%|█████████████▉                          | 137/393 [00:15<00:27,  9.48it/s]16 19:23:50 Save the image 01539D.png
 35%|██████████████                          | 138/393 [00:15<00:26,  9.54it/s]16 19:23:50 Save the image 01540D.png
 35%|██████████████▏                         | 139/393 [00:15<00:26,  9.50it/s]16 19:23:50 Save the image 01541D.png
 36%|██████████████▏                         | 140/393 [00:15<00:26,  9.49it/s]16 19:23:50 Save the image 01542D.png
 36%|██████████████▎                         | 141/393 [00:15<00:26,  9.47it/s]16 19:23:50 Save the image 01543D.png
 36%|██████████████▍                         | 142/393 [00:15<00:26,  9.56it/s]16 19:23:50 Save the image 01544D.png
 36%|██████████████▌                         | 143/393 [00:15<00:26,  9.61it/s]16 19:23:51 Save the image 01545D.png
 37%|██████████████▋                         | 144/393 [00:16<00:25,  9.62it/s]16 19:23:51 Save the image 01546D.png
 37%|██████████████▊                         | 145/393 [00:16<00:25,  9.68it/s]16 19:23:51 Save the image 01547D.png
 37%|██████████████▊                         | 146/393 [00:16<00:25,  9.71it/s]16 19:23:51 Save the image 01548D.png
 37%|██████████████▉                         | 147/393 [00:16<00:25,  9.75it/s]16 19:23:51 Save the image 01549D.png
 38%|███████████████                         | 148/393 [00:16<00:25,  9.74it/s]16 19:23:51 Save the image 01550D.png
 38%|███████████████▏                        | 149/393 [00:16<00:24,  9.77it/s]16 19:23:51 Save the image 01551D.png
 38%|███████████████▎                        | 150/393 [00:16<00:24,  9.81it/s]16 19:23:51 Save the image 01552D.png
 38%|███████████████▎                        | 151/393 [00:16<00:24,  9.83it/s]16 19:23:51 Save the image 01553D.png
 39%|███████████████▍                        | 152/393 [00:16<00:24,  9.82it/s]16 19:23:51 Save the image 01554D.png
 39%|███████████████▌                        | 153/393 [00:16<00:24,  9.82it/s]16 19:23:52 Save the image 01555D.png
 39%|███████████████▋                        | 154/393 [00:17<00:24,  9.82it/s]16 19:23:52 Save the image 01556D.png
 39%|███████████████▊                        | 155/393 [00:17<00:24,  9.82it/s]16 19:23:52 Save the image 01557D.png
 40%|███████████████▉                        | 156/393 [00:17<00:24,  9.82it/s]16 19:23:52 Save the image 01558D.png
 40%|███████████████▉                        | 157/393 [00:17<00:24,  9.81it/s]16 19:23:52 Save the image 01559D.png
 40%|████████████████                        | 158/393 [00:17<00:23,  9.82it/s]16 19:23:52 Save the image 01560D.png
 40%|████████████████▏                       | 159/393 [00:17<00:23,  9.82it/s]16 19:23:52 Save the image 01561D.png
 41%|████████████████▎                       | 160/393 [00:17<00:23,  9.82it/s]16 19:23:52 Save the image 01562D.png
 41%|████████████████▍                       | 161/393 [00:17<00:23,  9.86it/s]16 19:23:52 Save the image 01563D.png
 41%|████████████████▍                       | 162/393 [00:17<00:23,  9.85it/s]16 19:23:52 Save the image 01564D.png
 41%|████████████████▌                       | 163/393 [00:17<00:23,  9.86it/s]16 19:23:53 Save the image 01565D.png
 42%|████████████████▋                       | 164/393 [00:18<00:23,  9.87it/s]16 19:23:53 Save the image 01566D.png
 42%|████████████████▊                       | 165/393 [00:18<00:23,  9.88it/s]16 19:23:53 Save the image 01567D.png
 42%|████████████████▉                       | 166/393 [00:18<00:23,  9.86it/s]16 19:23:53 Save the image 01568D.png
 42%|████████████████▉                       | 167/393 [00:18<00:22,  9.86it/s]16 19:23:53 Save the image 01569D.png
 43%|█████████████████                       | 168/393 [00:18<00:22,  9.83it/s]16 19:23:53 Save the image 01570D.png
 43%|█████████████████▏                      | 169/393 [00:18<00:22,  9.82it/s]16 19:23:53 Save the image 01571D.png
 43%|█████████████████▎                      | 170/393 [00:18<00:22,  9.81it/s]16 19:23:53 Save the image 01572D.png
 44%|█████████████████▍                      | 171/393 [00:18<00:22,  9.81it/s]16 19:23:53 Save the image 01573D.png
 44%|█████████████████▌                      | 172/393 [00:18<00:22,  9.84it/s]16 19:23:54 Save the image 01574D.png
 44%|█████████████████▌                      | 173/393 [00:19<00:22,  9.86it/s]16 19:23:54 Save the image 01575D.png
 44%|█████████████████▋                      | 174/393 [00:19<00:22,  9.86it/s]16 19:23:54 Save the image 01576D.png
 45%|█████████████████▊                      | 175/393 [00:19<00:22,  9.86it/s]16 19:23:54 Save the image 01577D.png
 45%|█████████████████▉                      | 176/393 [00:19<00:21,  9.87it/s]16 19:23:54 Save the image 01578D.png
 45%|██████████████████                      | 177/393 [00:19<00:21,  9.83it/s]16 19:23:54 Save the image 01579D.png
 45%|██████████████████                      | 178/393 [00:19<00:21,  9.84it/s]16 19:23:54 Save the image 01580D.png
 46%|██████████████████▏                     | 179/393 [00:19<00:21,  9.82it/s]16 19:23:54 Save the image 01581D.png
 46%|██████████████████▎                     | 180/393 [00:19<00:22,  9.63it/s]16 19:23:54 Save the image 01582D.png
 46%|██████████████████▍                     | 181/393 [00:19<00:21,  9.64it/s]16 19:23:54 Save the image 01583D.png
 46%|██████████████████▌                     | 182/393 [00:19<00:21,  9.68it/s]16 19:23:55 Save the image 01584D.png
 47%|██████████████████▋                     | 183/393 [00:20<00:21,  9.73it/s]16 19:23:55 Save the image 01585D.png
 47%|██████████████████▋                     | 184/393 [00:20<00:21,  9.77it/s]16 19:23:55 Save the image 01586D.png
 47%|██████████████████▊                     | 185/393 [00:20<00:21,  9.79it/s]16 19:23:55 Save the image 01587D.png
 47%|██████████████████▉                     | 186/393 [00:20<00:21,  9.81it/s]16 19:23:55 Save the image 01588D.png
 48%|███████████████████                     | 187/393 [00:20<00:20,  9.81it/s]16 19:23:55 Save the image 01589D.png
 48%|███████████████████▏                    | 188/393 [00:20<00:20,  9.84it/s]16 19:23:55 Save the image 01590D.png

 48%|███████████████████▏                    | 189/393 [00:20<00:20,  9.83it/s]16 19:23:55 Save the image 01591D.png
 48%|███████████████████▎                    | 190/393 [00:20<00:20,  9.81it/s]16 19:23:55 Save the image 01592D.png
 49%|███████████████████▍                    | 191/393 [00:20<00:20,  9.80it/s]16 19:23:55 Save the image 01593D.png
 49%|███████████████████▌                    | 192/393 [00:20<00:20,  9.81it/s]16 19:23:56 Save the image 01594D.png
 49%|███████████████████▋                    | 193/393 [00:21<00:20,  9.82it/s]16 19:23:56 Save the image 01595D.png
 49%|███████████████████▋                    | 194/393 [00:21<00:20,  9.83it/s]16 19:23:56 Save the image 01596D.png
 50%|███████████████████▊                    | 195/393 [00:21<00:20,  9.84it/s]16 19:23:56 Save the image 01597D.png
 50%|███████████████████▉                    | 196/393 [00:21<00:20,  9.84it/s]16 19:23:56 Save the image 01598D.png
 50%|████████████████████                    | 197/393 [00:21<00:19,  9.83it/s]16 19:23:56 Save the image 01599D.png
 50%|████████████████████▏                   | 198/393 [00:21<00:19,  9.84it/s]16 19:23:56 Save the image 01600D.png
 51%|████████████████████▎                   | 199/393 [00:21<00:19,  9.85it/s]16 19:23:56 Save the image 01601D.png
 51%|████████████████████▎                   | 200/393 [00:21<00:19,  9.88it/s]16 19:23:56 Save the image 01602D.png
 51%|████████████████████▍                   | 201/393 [00:21<00:19,  9.87it/s]16 19:23:56 Save the image 01603D.png
 51%|████████████████████▌                   | 202/393 [00:21<00:19,  9.87it/s]16 19:23:57 Save the image 01604D.png
 52%|████████████████████▋                   | 203/393 [00:22<00:19,  9.86it/s]16 19:23:57 Save the image 01605D.png
 52%|████████████████████▊                   | 204/393 [00:22<00:19,  9.86it/s]16 19:23:57 Save the image 01606D.png
 52%|████████████████████▊                   | 205/393 [00:22<00:19,  9.86it/s]16 19:23:57 Save the image 01189N.png
16 19:23:57 Save the image 01190N.png
 53%|█████████████████████                   | 207/393 [00:22<00:18,  9.94it/s]16 19:23:57 Save the image 01191N.png
 53%|█████████████████████▏                  | 208/393 [00:22<00:18,  9.95it/s]16 19:23:57 Save the image 01192N.png
16 19:23:57 Save the image 01193N.png
 53%|█████████████████████▎                  | 210/393 [00:22<00:18,  9.97it/s]16 19:23:57 Save the image 01194N.png
 54%|█████████████████████▍                  | 211/393 [00:22<00:18,  9.97it/s]16 19:23:57 Save the image 01195N.png
 54%|█████████████████████▌                  | 212/393 [00:22<00:18,  9.96it/s]16 19:23:58 Save the image 01196N.png
 54%|█████████████████████▋                  | 213/393 [00:23<00:18,  9.93it/s]16 19:23:58 Save the image 01197N.png
 54%|█████████████████████▊                  | 214/393 [00:23<00:18,  9.92it/s]16 19:23:58 Save the image 01198N.png
16 19:23:58 Save the image 01199N.png
 55%|█████████████████████▉                  | 216/393 [00:23<00:17,  9.97it/s]16 19:23:58 Save the image 01200N.png
16 19:23:58 Save the image 01201N.png
 55%|██████████████████████▏                 | 218/393 [00:23<00:17,  9.99it/s]16 19:23:58 Save the image 01202N.png
16 19:23:58 Save the image 01203N.png
 56%|██████████████████████▍                 | 220/393 [00:23<00:17,  9.98it/s]16 19:23:58 Save the image 01204N.png
 56%|██████████████████████▍                 | 221/393 [00:23<00:17,  9.98it/s]16 19:23:58 Save the image 01205N.png
16 19:23:59 Save the image 01206N.png
 57%|██████████████████████▋                 | 223/393 [00:24<00:17,  9.99it/s]16 19:23:59 Save the image 01207N.png
 57%|██████████████████████▊                 | 224/393 [00:24<00:16,  9.99it/s]16 19:23:59 Save the image 01208N.png
 57%|██████████████████████▉                 | 225/393 [00:24<00:16,  9.97it/s]16 19:23:59 Save the image 01209N.png
 58%|███████████████████████                 | 226/393 [00:24<00:16,  9.97it/s]16 19:23:59 Save the image 01210N.png
16 19:23:59 Save the image 01211N.png
 58%|███████████████████████▏                | 228/393 [00:24<00:16,  9.99it/s]16 19:23:59 Save the image 01212N.png
 58%|███████████████████████▎                | 229/393 [00:24<00:16,  9.99it/s]16 19:23:59 Save the image 01213N.png
16 19:23:59 Save the image 01214N.png
 59%|███████████████████████▌                | 231/393 [00:24<00:16, 10.03it/s]16 19:23:59 Save the image 01215N.png
16 19:24:00 Save the image 01216N.png
 59%|███████████████████████▋                | 233/393 [00:25<00:15, 10.03it/s]16 19:24:00 Save the image 01217N.png
16 19:24:00 Save the image 01218N.png
 60%|███████████████████████▉                | 235/393 [00:25<00:15, 10.04it/s]16 19:24:00 Save the image 01219N.png
16 19:24:00 Save the image 01220N.png
 60%|████████████████████████                | 237/393 [00:25<00:15, 10.05it/s]16 19:24:00 Save the image 01221N.png
16 19:24:00 Save the image 01222N.png
 61%|████████████████████████▎               | 239/393 [00:25<00:15, 10.04it/s]16 19:24:00 Save the image 01223N.png
16 19:24:00 Save the image 01224N.png
 61%|████████████████████████▌               | 241/393 [00:25<00:15, 10.04it/s]16 19:24:00 Save the image 01225N.png
16 19:24:01 Save the image 01226N.png
 62%|████████████████████████▋               | 243/393 [00:26<00:15,  9.89it/s]16 19:24:01 Save the image 01227N.png
 62%|████████████████████████▊               | 244/393 [00:26<00:15,  9.90it/s]16 19:24:01 Save the image 01228N.png
 62%|████████████████████████▉               | 245/393 [00:26<00:14,  9.92it/s]16 19:24:01 Save the image 01229N.png
 63%|█████████████████████████               | 246/393 [00:26<00:14,  9.91it/s]16 19:24:01 Save the image 01230N.png
16 19:24:01 Save the image 01231N.png
 63%|█████████████████████████▏              | 248/393 [00:26<00:14,  9.95it/s]16 19:24:01 Save the image 01232N.png
16 19:24:01 Save the image 01233N.png
 64%|█████████████████████████▍              | 250/393 [00:26<00:14,  9.97it/s]16 19:24:01 Save the image 01234N.png
 64%|█████████████████████████▌              | 251/393 [00:26<00:14,  9.96it/s]16 19:24:01 Save the image 01235N.png
 64%|█████████████████████████▋              | 252/393 [00:26<00:14,  9.95it/s]16 19:24:02 Save the image 01236N.png
 64%|█████████████████████████▊              | 253/393 [00:27<00:14,  9.94it/s]16 19:24:02 Save the image 01237N.png
 65%|█████████████████████████▊              | 254/393 [00:27<00:13,  9.95it/s]16 19:24:02 Save the image 01238N.png
 65%|█████████████████████████▉              | 255/393 [00:27<00:13,  9.95it/s]16 19:24:02 Save the image 01239N.png
16 19:24:02 Save the image 01240N.png
 65%|██████████████████████████▏             | 257/393 [00:27<00:13,  9.99it/s]16 19:24:02 Save the image 01241N.png
16 19:24:02 Save the image 01242N.png
 66%|██████████████████████████▎             | 259/393 [00:27<00:13, 10.02it/s]16 19:24:02 Save the image 01243N.png
16 19:24:02 Save the image 01244N.png
 66%|██████████████████████████▌             | 261/393 [00:27<00:13, 10.05it/s]16 19:24:02 Save the image 01245N.png
16 19:24:03 Save the image 01246N.png
 67%|██████████████████████████▊             | 263/393 [00:28<00:12, 10.05it/s]16 19:24:03 Save the image 01247N.png
16 19:24:03 Save the image 01248N.png
 67%|██████████████████████████▉             | 265/393 [00:28<00:12, 10.01it/s]16 19:24:03 Save the image 01249N.png
16 19:24:03 Save the image 01250N.png
 68%|███████████████████████████▏            | 267/393 [00:28<00:12, 10.01it/s]16 19:24:03 Save the image 01251N.png

16 19:24:03 Save the image 01252N.png
 68%|███████████████████████████▍            | 269/393 [00:28<00:12,  9.99it/s]16 19:24:03 Save the image 01253N.png
 69%|███████████████████████████▍            | 270/393 [00:28<00:12,  9.99it/s]16 19:24:03 Save the image 01254N.png
16 19:24:03 Save the image 01255N.png
 69%|███████████████████████████▋            | 272/393 [00:28<00:12, 10.00it/s]16 19:24:04 Save the image 01256N.png
16 19:24:04 Save the image 01257N.png
 70%|███████████████████████████▉            | 274/393 [00:29<00:11, 10.01it/s]16 19:24:04 Save the image 01258N.png
16 19:24:04 Save the image 01259N.png
 70%|████████████████████████████            | 276/393 [00:29<00:11, 10.02it/s]16 19:24:04 Save the image 01260N.png
16 19:24:04 Save the image 01261N.png
 71%|████████████████████████████▎           | 278/393 [00:29<00:11, 10.01it/s]16 19:24:04 Save the image 01262N.png
16 19:24:04 Save the image 01263N.png
 71%|████████████████████████████▍           | 280/393 [00:29<00:11, 10.00it/s]16 19:24:04 Save the image 01264N.png
16 19:24:04 Save the image 01265N.png
 72%|████████████████████████████▋           | 282/393 [00:29<00:11, 10.00it/s]16 19:24:05 Save the image 01266N.png
 72%|████████████████████████████▊           | 283/393 [00:30<00:11, 10.00it/s]16 19:24:05 Save the image 01267N.png
16 19:24:05 Save the image 01268N.png
 73%|█████████████████████████████           | 285/393 [00:30<00:10, 10.02it/s]16 19:24:05 Save the image 01269N.png
16 19:24:05 Save the image 01270N.png
 73%|█████████████████████████████▏          | 287/393 [00:30<00:10, 10.03it/s]16 19:24:05 Save the image 01271N.png
16 19:24:05 Save the image 01272N.png
 74%|█████████████████████████████▍          | 289/393 [00:30<00:10, 10.02it/s]16 19:24:05 Save the image 01273N.png
16 19:24:05 Save the image 01274N.png
 74%|█████████████████████████████▌          | 291/393 [00:30<00:10, 10.02it/s]16 19:24:05 Save the image 01275N.png
16 19:24:06 Save the image 01276N.png
 75%|█████████████████████████████▊          | 293/393 [00:31<00:10,  9.90it/s]16 19:24:06 Save the image 01277N.png
 75%|█████████████████████████████▉          | 294/393 [00:31<00:10,  9.88it/s]16 19:24:06 Save the image 01278N.png
 75%|██████████████████████████████          | 295/393 [00:31<00:09,  9.89it/s]16 19:24:06 Save the image 01279N.png
 75%|██████████████████████████████▏         | 296/393 [00:31<00:09,  9.91it/s]16 19:24:06 Save the image 01280N.png
 76%|██████████████████████████████▏         | 297/393 [00:31<00:09,  9.90it/s]16 19:24:06 Save the image 01281N.png
 76%|██████████████████████████████▎         | 298/393 [00:31<00:09,  9.89it/s]16 19:24:06 Save the image 01282N.png
 76%|██████████████████████████████▍         | 299/393 [00:31<00:09,  9.89it/s]16 19:24:06 Save the image 01283N.png
 76%|██████████████████████████████▌         | 300/393 [00:31<00:09,  9.87it/s]16 19:24:06 Save the image 01284N.png
 77%|██████████████████████████████▋         | 301/393 [00:31<00:09,  9.77it/s]16 19:24:07 Save the image 01285N.png
 77%|██████████████████████████████▋         | 302/393 [00:32<00:09,  9.47it/s]16 19:24:07 Save the image 01286N.png
 77%|██████████████████████████████▊         | 303/393 [00:32<00:09,  9.29it/s]16 19:24:07 Save the image 01287N.png
 77%|██████████████████████████████▉         | 304/393 [00:32<00:09,  9.18it/s]16 19:24:07 Save the image 01288N.png
 78%|███████████████████████████████         | 305/393 [00:32<00:09,  9.13it/s]16 19:24:07 Save the image 01289N.png
 78%|███████████████████████████████▏        | 306/393 [00:32<00:09,  9.11it/s]16 19:24:07 Save the image 01290N.png
 78%|███████████████████████████████▏        | 307/393 [00:32<00:09,  9.05it/s]16 19:24:07 Save the image 01291N.png
 78%|███████████████████████████████▎        | 308/393 [00:32<00:09,  9.02it/s]16 19:24:07 Save the image 01292N.png
 79%|███████████████████████████████▍        | 309/393 [00:32<00:09,  9.00it/s]16 19:24:07 Save the image 01293N.png
 79%|███████████████████████████████▌        | 310/393 [00:32<00:09,  8.98it/s]16 19:24:08 Save the image 01294N.png
 79%|███████████████████████████████▋        | 311/393 [00:33<00:09,  9.00it/s]16 19:24:08 Save the image 01295N.png
 79%|███████████████████████████████▊        | 312/393 [00:33<00:09,  8.99it/s]16 19:24:08 Save the image 01296N.png
 80%|███████████████████████████████▊        | 313/393 [00:33<00:08,  9.01it/s]16 19:24:08 Save the image 01297N.png
 80%|███████████████████████████████▉        | 314/393 [00:33<00:08,  9.01it/s]16 19:24:08 Save the image 01298N.png
 80%|████████████████████████████████        | 315/393 [00:33<00:08,  9.01it/s]16 19:24:08 Save the image 01299N.png
 80%|████████████████████████████████▏       | 316/393 [00:33<00:08,  9.03it/s]16 19:24:08 Save the image 01300N.png
 81%|████████████████████████████████▎       | 317/393 [00:33<00:08,  9.06it/s]16 19:24:08 Save the image 01301N.png
 81%|████████████████████████████████▎       | 318/393 [00:33<00:08,  9.04it/s]16 19:24:08 Save the image 01302N.png
 81%|████████████████████████████████▍       | 319/393 [00:33<00:08,  9.05it/s]16 19:24:08 Save the image 01303N.png
 81%|████████████████████████████████▌       | 320/393 [00:33<00:07,  9.29it/s]16 19:24:09 Save the image 01304N.png
 82%|████████████████████████████████▋       | 321/393 [00:34<00:07,  9.48it/s]16 19:24:09 Save the image 01305N.png
 82%|████████████████████████████████▊       | 322/393 [00:34<00:07,  9.63it/s]16 19:24:09 Save the image 01306N.png
 82%|████████████████████████████████▉       | 323/393 [00:34<00:07,  9.71it/s]16 19:24:09 Save the image 01307N.png
 82%|████████████████████████████████▉       | 324/393 [00:34<00:07,  9.78it/s]16 19:24:09 Save the image 01308N.png
 83%|█████████████████████████████████       | 325/393 [00:34<00:06,  9.81it/s]16 19:24:09 Save the image 01309N.png
 83%|█████████████████████████████████▏      | 326/393 [00:34<00:06,  9.86it/s]16 19:24:09 Save the image 01310N.png
 83%|█████████████████████████████████▎      | 327/393 [00:34<00:06,  9.89it/s]16 19:24:09 Save the image 01311N.png
 83%|█████████████████████████████████▍      | 328/393 [00:34<00:06,  9.92it/s]16 19:24:09 Save the image 01312N.png
 84%|█████████████████████████████████▍      | 329/393 [00:34<00:06,  9.92it/s]16 19:24:09 Save the image 01313N.png
 84%|█████████████████████████████████▌      | 330/393 [00:35<00:06,  9.93it/s]16 19:24:10 Save the image 01314N.png
 84%|█████████████████████████████████▋      | 331/393 [00:35<00:06,  9.92it/s]16 19:24:10 Save the image 01315N.png
16 19:24:10 Save the image 01316N.png
 85%|█████████████████████████████████▉      | 333/393 [00:35<00:06,  9.99it/s]16 19:24:10 Save the image 01317N.png
16 19:24:10 Save the image 01318N.png
 85%|██████████████████████████████████      | 335/393 [00:35<00:05, 10.01it/s]16 19:24:10 Save the image 01319N.png
16 19:24:10 Save the image 01320N.png
 86%|██████████████████████████████████▎     | 337/393 [00:35<00:05,  9.99it/s]16 19:24:10 Save the image 01321N.png
 86%|██████████████████████████████████▍     | 338/393 [00:35<00:05,  9.97it/s]16 19:24:10 Save the image 01322N.png
 86%|██████████████████████████████████▌     | 339/393 [00:35<00:05,  9.95it/s]16 19:24:11 Save the image 01323N.png
 87%|██████████████████████████████████▌     | 340/393 [00:36<00:05,  9.78it/s]16 19:24:11 Save the image 01324N.png
 87%|██████████████████████████████████▋     | 341/393 [00:36<00:05,  9.81it/s]16 19:24:11 Save the image 01325N.png

 87%|██████████████████████████████████▊     | 342/393 [00:36<00:05,  9.84it/s]16 19:24:11 Save the image 01326N.png
 87%|██████████████████████████████████▉     | 343/393 [00:36<00:05,  9.88it/s]16 19:24:11 Save the image 01327N.png
 88%|███████████████████████████████████     | 344/393 [00:36<00:04,  9.89it/s]16 19:24:11 Save the image 01328N.png
 88%|███████████████████████████████████     | 345/393 [00:36<00:04,  9.87it/s]16 19:24:11 Save the image 01329N.png
 88%|███████████████████████████████████▏    | 346/393 [00:36<00:04,  9.85it/s]16 19:24:11 Save the image 01330N.png
 88%|███████████████████████████████████▎    | 347/393 [00:36<00:04,  9.84it/s]16 19:24:11 Save the image 01331N.png
 89%|███████████████████████████████████▍    | 348/393 [00:36<00:04,  9.81it/s]16 19:24:11 Save the image 01332N.png
 89%|███████████████████████████████████▌    | 349/393 [00:36<00:04,  9.83it/s]16 19:24:12 Save the image 01333N.png
 89%|███████████████████████████████████▌    | 350/393 [00:37<00:04,  9.82it/s]16 19:24:12 Save the image 01334N.png
 89%|███████████████████████████████████▋    | 351/393 [00:37<00:04,  9.82it/s]16 19:24:12 Save the image 01335N.png
 90%|███████████████████████████████████▊    | 352/393 [00:37<00:04,  9.80it/s]16 19:24:12 Save the image 01336N.png
 90%|███████████████████████████████████▉    | 353/393 [00:37<00:04,  9.80it/s]16 19:24:12 Save the image 01337N.png
 90%|████████████████████████████████████    | 354/393 [00:37<00:03,  9.80it/s]16 19:24:12 Save the image 01338N.png
 90%|████████████████████████████████████▏   | 355/393 [00:37<00:03,  9.81it/s]16 19:24:12 Save the image 01339N.png
 91%|████████████████████████████████████▏   | 356/393 [00:37<00:03,  9.82it/s]16 19:24:12 Save the image 01340N.png
 91%|████████████████████████████████████▎   | 357/393 [00:37<00:03,  9.77it/s]16 19:24:12 Save the image 01341N.png
 91%|████████████████████████████████████▍   | 358/393 [00:37<00:03,  9.69it/s]16 19:24:12 Save the image 01342N.png
 91%|████████████████████████████████████▌   | 359/393 [00:37<00:03,  9.62it/s]16 19:24:13 Save the image 01343N.png
 92%|████████████████████████████████████▋   | 360/393 [00:38<00:03,  9.60it/s]16 19:24:13 Save the image 01344N.png
 92%|████████████████████████████████████▋   | 361/393 [00:38<00:03,  9.57it/s]16 19:24:13 Save the image 01345N.png
 92%|████████████████████████████████████▊   | 362/393 [00:38<00:03,  9.55it/s]16 19:24:13 Save the image 01346N.png
 92%|████████████████████████████████████▉   | 363/393 [00:38<00:03,  9.55it/s]16 19:24:13 Save the image 01347N.png
 93%|█████████████████████████████████████   | 364/393 [00:38<00:03,  9.56it/s]16 19:24:13 Save the image 01348N.png
 93%|█████████████████████████████████████▏  | 365/393 [00:38<00:02,  9.51it/s]16 19:24:13 Save the image 01349N.png
 93%|█████████████████████████████████████▎  | 366/393 [00:38<00:02,  9.50it/s]16 19:24:13 Save the image 01350N.png
 93%|█████████████████████████████████████▎  | 367/393 [00:38<00:02,  9.59it/s]16 19:24:13 Save the image 01351N.png
 94%|█████████████████████████████████████▍  | 368/393 [00:38<00:02,  9.66it/s]16 19:24:13 Save the image 01352N.png
 94%|█████████████████████████████████████▌  | 369/393 [00:38<00:02,  9.71it/s]16 19:24:14 Save the image 01353N.png
 94%|█████████████████████████████████████▋  | 370/393 [00:39<00:02,  9.76it/s]16 19:24:14 Save the image 01354N.png
 94%|█████████████████████████████████████▊  | 371/393 [00:39<00:02,  9.81it/s]16 19:24:14 Save the image 01355N.png
 95%|█████████████████████████████████████▊  | 372/393 [00:39<00:02,  9.86it/s]16 19:24:14 Save the image 01356N.png
 95%|█████████████████████████████████████▉  | 373/393 [00:39<00:02,  9.89it/s]16 19:24:14 Save the image 01357N.png
 95%|██████████████████████████████████████  | 374/393 [00:39<00:01,  9.77it/s]16 19:24:14 Save the image 01358N.png
 95%|██████████████████████████████████████▏ | 375/393 [00:39<00:01,  9.70it/s]16 19:24:14 Save the image 01359N.png
 96%|██████████████████████████████████████▎ | 376/393 [00:39<00:01,  9.66it/s]16 19:24:14 Save the image 01360N.png
 96%|██████████████████████████████████████▎ | 377/393 [00:39<00:01,  9.62it/s]16 19:24:14 Save the image 01361N.png
 96%|██████████████████████████████████████▍ | 378/393 [00:39<00:01,  9.63it/s]16 19:24:15 Save the image 01362N.png
 96%|██████████████████████████████████████▌ | 379/393 [00:40<00:01,  9.72it/s]16 19:24:15 Save the image 01363N.png
 97%|██████████████████████████████████████▋ | 380/393 [00:40<00:01,  9.74it/s]16 19:24:15 Save the image 01364N.png
 97%|██████████████████████████████████████▊ | 381/393 [00:40<00:01,  9.81it/s]16 19:24:15 Save the image 01365N.png
 97%|██████████████████████████████████████▉ | 382/393 [00:40<00:01,  9.86it/s]16 19:24:15 Save the image 01366N.png
 97%|██████████████████████████████████████▉ | 383/393 [00:40<00:01,  9.89it/s]16 19:24:15 Save the image 01367N.png
 98%|███████████████████████████████████████ | 384/393 [00:40<00:00,  9.90it/s]16 19:24:15 Save the image 01368N.png
 98%|███████████████████████████████████████▏| 385/393 [00:40<00:00,  9.90it/s]16 19:24:15 Save the image 01369N.png
 98%|███████████████████████████████████████▎| 386/393 [00:40<00:00,  9.93it/s]16 19:24:15 Save the image 01370N.png
 98%|███████████████████████████████████████▍| 387/393 [00:40<00:00,  9.93it/s]16 19:24:15 Save the image 01371N.png
 99%|███████████████████████████████████████▍| 388/393 [00:40<00:00,  9.93it/s]16 19:24:16 Save the image 01372N.png
 99%|███████████████████████████████████████▌| 389/393 [00:41<00:00,  9.76it/s]16 19:24:16 Save the image 01373N.png
 99%|███████████████████████████████████████▋| 390/393 [00:41<00:00,  9.79it/s]16 19:24:16 Save the image 01374N.png
 99%|███████████████████████████████████████▊| 391/393 [00:41<00:00,  9.83it/s]16 19:24:16 Save the image 01375N.png
100%|███████████████████████████████████████▉| 392/393 [00:41<00:00,  9.87it/s]16 19:24:16 Save the image 01376N.png
100%|████████████████████████████████████████| 393/393 [00:41<00:00,  9.48it/s]
1 unlabeled	98.318%
2 car   	89.264%
3 person	75.482%
4 bike  	65.006%
5 curve 	47.410%
6 car_stop	32.014%
7 guardrail	7.243%
8 color_cone	52.236%
9 bump  	58.436%
----------     mean_IoU	58.379%	freq_IoU	96.795%	mean_pixel_acc	67.820%	pixel_acc	98.250%
16 19:24:16 Evaluation Elapsed Time: 41.44s

In [50]:
from pathlib import Path
from PIL import Image
import numpy as np

folder = Path("predictions_E5_test_verify")
files = sorted(folder.glob("*.png"))

print("Test prediction count:", len(files))
print("First 10 prediction files:", [p.name for p in files[:10]])

for p in files[:5]:
    arr = np.array(Image.open(p))
    print(
        p.name,
        "shape:", arr.shape,
        "unique predicted values:", np.unique(arr)[:20],
        "unique-value count:", len(np.unique(arr))
    )

Test prediction count: 393
First 10 prediction files: ['01189N.png', '01190N.png', '01191N.png', '01192N.png', '01193N.png', '01194N.png', '01195N.png', '01196N.png', '01197N.png', '01198N.png']
01189N.png shape: (480, 640) unique predicted values: [0 2 3] unique-value count: 3
01190N.png shape: (480, 640) unique predicted values: [0 2 3] unique-value count: 3
01191N.png shape: (480, 640) unique predicted values: [0] unique-value count: 1
01192N.png shape: (480, 640) unique predicted values: [0] unique-value count: 1
01193N.png shape: (480, 640) unique predicted values: [0] unique-value count: 1

In [51]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -n -A35 -B8 "def __getitem__" dataloader/RGBXDataset.py
!grep -n -A35 -B8 "def func_per_iteration" eval.py
!grep -n -A35 -B8 "def run" eval.py

/home/cse-sdpl/Downloads/CMX_E5
27-        self._file_length = file_length
28-        self.preprocess = preprocess
29-
30-    def __len__(self):
31-        if self._file_length is not None:
32-            return self._file_length
33-        return len(self._file_names)
34-
35:    def __getitem__(self, index):
36-        if self._file_length is not None:
37-            item_name = self._construct_new_file_names(self._file_length)[index]
38-        else:
39-            item_name = self._file_names[index]
40-        rgb_path = os.path.join(self._rgb_path, item_name + self._rgb_format)
41-        x_path = os.path.join(self._x_path, item_name + self._x_format)
42-        gt_path = os.path.join(self._gt_path, item_name + self._gt_format)
43-
44-        # Check the following settings if necessary
45-        rgb = self._open_image(rgb_path, cv2.COLOR_BGR2RGB)
46-
47-        gt = self._open_image(gt_path, cv2.IMREAD_GRAYSCALE, dtype=np.uint8)
48-        if self._transform_gt:
49-            gt = self._gt_transform(gt)
50-
51-        if self._x_single_channel:
52-            x = self._open_image(x_path, cv2.IMREAD_GRAYSCALE)
53-            x = cv2.merge([x, x, x])
54-        else:
55-            x =  self._open_image(x_path, cv2.COLOR_BGR2RGB)
56-
57-        if self.preprocess is not None:
58-            rgb, gt, x = self.preprocess(rgb, gt, x)
59-
60-
61-        output_dict = dict(data=rgb, label=gt, modal_x=x, fn=str(item_name), n=len(self._file_names))
62-
63-        return output_dict
64-
65-    def _get_file_names(self, split_name):
66-        assert split_name in ['train', 'val', 'test']
67-        source = self._train_source
68-        if split_name == "val":
69-            source = self._eval_source
70-        elif split_name == "test":
15-from utils.metric import hist_info, compute_score
16-from dataloader.RGBXDataset import RGBXDataset
17-from models.builder import EncoderDecoder as segmodel
18-from dataloader.dataloader import ValPre
19-
20-logger = get_logger()
21-
22-class SegEvaluator(Evaluator):
23:    def func_per_iteration(self, data, device):
24-        img = data['data']
25-        label = data['label']
26-        modal_x = data['modal_x']
27-        name = data['fn']
28-        pred = self.sliding_eval_rgbX(img, modal_x, config.eval_crop_size, config.eval_stride_rate, device)
29-        hist_tmp, labeled_tmp, correct_tmp = hist_info(config.num_classes, pred, label)
30-        results_dict = {'hist': hist_tmp, 'labeled': labeled_tmp, 'correct': correct_tmp}
31-
32-        if self.save_path is not None:
33-            ensure_dir(self.save_path)
34-            ensure_dir(self.save_path+'_color')
35-
36-            fn = name + '.png'
37-
38-            # save colored result
39-
40-            # save raw result
41-            cv2.imwrite(os.path.join(self.save_path, fn), pred)
42-            logger.info('Save the image ' + fn)
43-
44-        if self.show_image:
45-            colors = self.dataset.get_class_colors
46-            image = img
47-            clean = np.zeros(label.shape)
48-            comp_img = show_img(colors, config.background, image, clean,
49-                                label,
50-                                pred)
51-            cv2.imshow('comp_image', comp_img)
52-            cv2.waitKey(0)
53-
54-        return results_dict
55-
56-    def compute_metric(self, results):
57-        hist = np.zeros((config.num_classes, config.num_classes))
58-        correct = 0

In [52]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!grep -n -A70 -B10 "def main" eval.py
!grep -n -A35 -B5 "def __init__" dataloader/RGBXDataset.py
!grep -n -A45 -B5 "def compute_metric" eval.py
!grep -n -A35 -B5 "def run" eval.py

/home/cse-sdpl/Downloads/CMX_E5
6-
7-import torch.utils.data as data
8-
9-
10-class RGBXDataset(data.Dataset):
11:    def __init__(self, setting, split_name, preprocess=None, file_length=None):
12-        super(RGBXDataset, self).__init__()
13-        self._split_name = split_name
14-        self._rgb_path = setting['rgb_root']
15-        self._rgb_format = setting['rgb_format']
16-        self._gt_path = setting['gt_root']
17-        self._gt_format = setting['gt_format']
18-        self._transform_gt = setting['transform_gt']
19-        self._x_path = setting['x_root']
20-        self._x_format = setting['x_format']
21-        self._x_single_channel = setting['x_single_channel']
22-        self._train_source = setting['train_source']
23-        self._eval_source = setting['eval_source']
24-        self._test_source = setting['test_source']
25-        self.class_names = setting['class_names']
26-        self._file_names = self._get_file_names(split_name)
27-        self._file_length = file_length
28-        self.preprocess = preprocess
29-
30-    def __len__(self):
31-        if self._file_length is not None:
32-            return self._file_length
33-        return len(self._file_names)
34-
35-    def __getitem__(self, index):
36-        if self._file_length is not None:
37-            item_name = self._construct_new_file_names(self._file_length)[index]
38-        else:
39-            item_name = self._file_names[index]
40-        rgb_path = os.path.join(self._rgb_path, item_name + self._rgb_format)
41-        x_path = os.path.join(self._x_path, item_name + self._x_format)
42-        gt_path = os.path.join(self._gt_path, item_name + self._gt_format)
43-
44-        # Check the following settings if necessary
45-        rgb = self._open_image(rgb_path, cv2.COLOR_BGR2RGB)
46-
51-            cv2.imshow('comp_image', comp_img)
52-            cv2.waitKey(0)
53-
54-        return results_dict
55-
56:    def compute_metric(self, results):
57-        hist = np.zeros((config.num_classes, config.num_classes))
58-        correct = 0
59-        labeled = 0
60-        count = 0
61-        for d in results:
62-            hist += d['hist']
63-            correct += d['correct']
64-            labeled += d['labeled']
65-            count += 1
66-
67-        iou, mean_IoU, _, freq_IoU, mean_pixel_acc, pixel_acc = compute_score(hist, correct, labeled)
68-        result_line = print_iou(iou, freq_IoU, mean_pixel_acc, pixel_acc,
69-                                dataset.class_names, show_no_back=False)
70-        return result_line
71-
72-if __name__ == "__main__":
73-    parser = argparse.ArgumentParser()
74-    parser.add_argument('-e', '--epochs', default='last', type=str)
75-    parser.add_argument('-d', '--devices', default='0', type=str)
76-    parser.add_argument('-v', '--verbose', default=False, action='store_true')
77-    parser.add_argument('--show_image', '-s', default=False,
78-                        action='store_true')
79-    parser.add_argument('--save_path', '-p', default=None)
80-
81-    parser.add_argument('--split', choices=['train', 'val', 'test'], default='val')
82-    args = parser.parse_args()
83-    all_dev = parse_devices(args.devices)
84-
85-    network = segmodel(cfg=config, criterion=None, norm_layer=nn.BatchNorm2d)
86-    data_setting = {'rgb_root': config.rgb_root_folder,
87-                    'rgb_format': config.rgb_format,
88-                    'gt_root': config.gt_root_folder,
89-                    'gt_format': config.gt_format,
90-                    'transform_gt': config.gt_transform,
91-                    'x_root':config.x_root_folder,
92-                    'x_format': config.x_format,
93-                    'x_single_channel': config.x_is_single_channel,
94-                    'class_names': config.class_names,
95-                    'train_source': config.train_source,
96-                    'eval_source': config.eval_source,
97-                    'test_source': config.test_source,
98-                    'class_names': config.class_names}
99-    val_pre = ValPre()
100-    dataset = RGBXDataset(data_setting, args.split, val_pre)
101-

In [53]:
%cd /home/cse-sdpl/Downloads/CMX_E5

!sed -n '99,165p' eval.py
!sed -n '65,105p' dataloader/RGBXDataset.py

/home/cse-sdpl/Downloads/CMX_E5
    val_pre = ValPre()
    dataset = RGBXDataset(data_setting, args.split, val_pre)

    with torch.no_grad():
        segmentor = SegEvaluator(dataset, config.num_classes, config.norm_mean,
                                 config.norm_std, network,
                                 config.eval_scale_array, config.eval_flip,
                                 all_dev, args.verbose, args.save_path,
                                 args.show_image)
        segmentor.run(config.checkpoint_dir, args.epochs, config.val_log_file,
                      config.link_val_log_file)
    def _get_file_names(self, split_name):
        assert split_name in ['train', 'val', 'test']
        source = self._train_source
        if split_name == "val":
            source = self._eval_source
        elif split_name == "test":
            source = self._test_source

        file_names = []
        with open(source) as f:
            files = f.readlines()

        for item in files:
            file_name = item.strip()
            file_names.append(file_name)

        return file_names

    def _construct_new_file_names(self, length):
        assert isinstance(length, int)
        files_len = len(self._file_names)
        new_file_names = self._file_names * (length // files_len)

        rand_indices = torch.randperm(files_len).tolist()
        new_indices = rand_indices[:length % files_len]

        new_file_names += [self._file_names[i] for i in new_indices]

        return new_file_names

    def get_length(self):
        return self.__len__()

    @staticmethod
    def _open_image(filepath, mode=cv2.IMREAD_COLOR, dtype=None):
        img = np.array(cv2.imread(filepath, mode), dtype=dtype)
        return img

    @staticmethod
    def _gt_transform(gt):
        return gt

In [54]:
from collections import Counter
from pathlib import Path
import cv2
import numpy as np

root = Path("/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD")
label_dir = root / "Label"

for split in ["val", "test"]:
    ids = [
        x.strip()
        for x in (root / f"{split}.txt").read_text().splitlines()
        if x.strip()
    ]

    counts = Counter()
    for image_id in ids:
        label = cv2.imread(str(label_dir / f"{image_id}.png"),
                           cv2.IMREAD_GRAYSCALE)
        if label is not None:
            values, frequencies = np.unique(label, return_counts=True)
            counts.update(dict(zip(values.tolist(), frequencies.tolist())))

    print(f"\n{split.upper()} — {len(ids)} images")
    print("Raw label pixel counts:", dict(sorted(counts.items())))

VAL — 392 images
Raw label pixel counts: {0: 110824522, 1: 4219671, 2: 1106006, 3: 2122305, 4: 684884, 5: 499275, 6: 75317, 7: 361079, 8: 529341}

TEST — 393 images
Raw label pixel counts: {0: 112023545, 1: 4854504, 2: 1345972, 3: 1261567, 4: 602620, 5: 355314, 6: 17794, 7: 85246, 8: 183038}

In [55]:

from pathlib import Path
from collections import Counter
import cv2
import numpy as np

root = Path("/home/cse-sdpl/Downloads/CMX_Original/datasets/TDD")
pred_dir = Path("/home/cse-sdpl/Downloads/CMX_E5/predictions_E5_test_verify")

ids = [
    x.strip()
    for x in (root / "test.txt").read_text().splitlines()
    if x.strip()
]

hist = np.zeros((9, 9), dtype=np.int64)
missing = []
shape_errors = []

for image_id in ids:
    gt_path = root / "Label" / f"{image_id}.png"
    pred_path = pred_dir / f"{image_id}.png"

    gt = cv2.imread(str(gt_path), cv2.IMREAD_GRAYSCALE)
    pred = cv2.imread(str(pred_path), cv2.IMREAD_GRAYSCALE)

    if gt is None or pred is None:
        missing.append(image_id)
        continue

    if gt.shape != pred.shape:
        shape_errors.append((image_id, gt.shape, pred.shape))
        continue

    valid = (gt >= 0) & (gt < 9) & (pred >= 0) & (pred < 9)
    encoded = 9 * gt[valid].astype(np.int64) + pred[valid].astype(np.int64)
    hist += np.bincount(encoded, minlength=81).reshape(9, 9)

tp = np.diag(hist)
gt_count = hist.sum(axis=1)
pred_count = hist.sum(axis=0)
union = gt_count + pred_count - tp

iou = np.divide(tp, union, out=np.zeros(9, dtype=float), where=union > 0)
class_acc = np.divide(tp, gt_count, out=np.zeros(9, dtype=float), where=gt_count > 0)

print("Test IDs:", len(ids))
print("Missing files:", len(missing))
print("Shape errors:", len(shape_errors))
print("Confusion matrix:\n", hist)
print("Class IoU (%):", np.round(iou * 100, 3))
print("Mean IoU (%):", round(iou[union > 0].mean() * 100, 3))
print("Mean class accuracy (%):", round(class_acc[gt_count > 0].mean() * 100, 3))
print("Pixel accuracy (%):", round(tp.sum() / max(hist.sum(), 1) * 100, 3))

Test IDs: 393
Missing files: 0
Shape errors: 0
Confusion matrix:
 [[111288758    215373    114731    148646    185341     23516      5034
       4496     37650]
 [   260457   4569084     24277       589         3        55         2
         37         0]
 [   161101     26671   1136966     19791        80      1327        36
          0         0]
 [   283073     16994     17905    939566        21      3278         0
        730         0]
 [   226138        21        45      1759    374024       263         0
        370         0]
 [   148427      3958      2902     12366       208    126227     61226
          0         0]
 [    11383         0       280         0         0        40      6091
          0         0]
 [    25284      1055       159       630       150     10496         0
      47472         0]
 [    53561        23         0         0       492         0         0
          0    128962]]
Class IoU (%): [98.318 89.264 75.482 65.006 47.41  32.014  7.243 52.236 58.436]
Mean IoU (%): 58.379
Mean class accuracy (%): 67.82
Pixel accuracy (%): 98.25

# plot and graphs

In [57]:

# ============================================================
# CMX E0-E5: COMPLETE MODEL COMPARISON PIPELINE
# Run this cell in Jupyter on your Ubuntu machine
# ============================================================

from pathlib import Path
import subprocess
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import os
import sys
import json
import time

# -------------------- CONFIGURATION -------------------------

BASE = Path("/home/cse-sdpl/Downloads")

PROJECTS = {
    "E0": BASE / "CMX_Original",
    "E1": BASE / "CMX_E1",
    "E2": BASE / "CMX_E2",
    "E3": BASE / "CMX_E3",
    "E4": BASE / "CMX_E4",
    "E5": BASE / "CMX_E5",
}

# Change this if your Conda environment has a different Python.
PYTHON = sys.executable

# Use the same epoch/checkpoint selection rule for every model.
EPOCH = 100
DEVICE = "0"

# Your CMX evaluation script's split names.
SPLITS = ["train", "val", "test"]

OUT = BASE / "CMX_ALL_MODEL_COMPARISON"
OUT.mkdir(parents=True, exist_ok=True)

for split in SPLITS:
    (OUT / split).mkdir(exist_ok=True)

# -------------------- FIND CHECKPOINTS ----------------------

def find_checkpoint(project):
    checkpoint_dir = project / "log_TDD_mit_b2" / "checkpoint"

    # Prefer the epoch-100 checkpoint.
    candidates = [
        checkpoint_dir / f"epoch-{EPOCH}.pth",
        checkpoint_dir / f"epoch-{EPOCH}.pth.tar",
        project / "checkpoint" / f"epoch-{EPOCH}.pth",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    # Search recursively if the log directory differs.
    found = list(project.rglob(f"epoch-{EPOCH}.pth"))
    if found:
        return found[0]

    # Fallback to latest/last checkpoint if epoch 100 is absent.
    for pattern in ["epoch-last.pth", "*best*.pth", "*.pth"]:
        found = sorted(project.rglob(pattern))
        if found:
            return found[-1]

    return None


# -------------------- METRIC PARSER -------------------------

def extract_metrics(text):
    """
    Parse the metric names commonly printed by CMX eval.py.
    Missing metrics remain NaN; they are never set to zero.
    """
    patterns = {
        "mIoU": [
            r"mean_IoU\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
            r"Mean IoU\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
        ],
        "FWIoU": [
            r"freq_IoU\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
            r"Frequency.weighted IoU\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
        ],
        "mPA": [
            r"mean_pixel_acc\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
            r"Mean Pixel Accuracy\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
        ],
        "PA": [
            r"pixel_acc\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
            r"Pixel Accuracy\s*[:=]?\s*([0-9]+\.?[0-9]*)\s*%?",
        ],
    }

    result = {}
    for metric, regexes in patterns.items():
        result[metric] = np.nan
        for pattern in regexes:
            matches = re.findall(pattern, text, flags=re.IGNORECASE)
            if matches:
                result[metric] = float(matches[-1])
                break

    # Detect class-wise lines such as:
    # 1 unlabeled 97.821%
    # 2 car 87.388%
    class_rows = []
    for line in text.splitlines():
        match = re.match(
            r"^\s*\d+\s+([A-Za-z_][A-Za-z_0-9 -]*?)\s+"
            r"([0-9]+\.?[0-9]*)\s*%\s*$",
            line
        )
        if match:
            class_rows.append({
                "Class": match.group(1).strip(),
                "IoU": float(match.group(2))
            })

    result["ClassIoU"] = class_rows
    return result


# -------------------- RUN EVALUATION ------------------------

all_results = []
all_class_results = []
run_status = []

for model_name, project in PROJECTS.items():

    print("\n" + "=" * 72)
    print(f"MODEL: {model_name} | PROJECT: {project}")
    print("=" * 72)

    if not project.exists():
        print("SKIPPED: project folder does not exist.")
        run_status.append({
            "Model": model_name,
            "Split": "all",
            "Status": "Project folder missing",
            "Project": str(project),
        })
        continue

    eval_script = project / "eval.py"
    if not eval_script.exists():
        print("SKIPPED: eval.py not found.")
        run_status.append({
            "Model": model_name,
            "Split": "all",
            "Status": "eval.py missing",
            "Project": str(project),
        })
        continue

    checkpoint = find_checkpoint(project)
    if checkpoint is None:
        print("SKIPPED: no checkpoint found.")
        run_status.append({
            "Model": model_name,
            "Split": "all",
            "Status": "Checkpoint missing",
            "Project": str(project),
        })
        continue

    print("Checkpoint:", checkpoint)

    for split in SPLITS:
        print(f"\nEvaluating {model_name} on {split}...")

        prediction_dir = OUT / split / f"predictions_{model_name}"
        prediction_dir.mkdir(parents=True, exist_ok=True)

        log_path = OUT / split / f"{model_name}_{split}.log"

        # Each subprocess runs inside its own project directory,
        # so its local config.py and models/builder.py are used.
        command = [
            PYTHON,
            str(eval_script),
            "-e", str(EPOCH),
            "-d", DEVICE,
            "--split", split,
            "-p", str(prediction_dir),
        ]

        try:
            completed = subprocess.run(
                command,
                cwd=str(project),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                timeout=None,
            )

            log_text = completed.stdout or ""
            log_path.write_text(log_text, encoding="utf-8")

            if completed.returncode != 0:
                print(f"FAILED. Check log: {log_path}")
                print(log_text[-2500:])
                run_status.append({
                    "Model": model_name,
                    "Split": split,
                    "Status": f"Evaluation failed (exit {completed.returncode})",
                    "Project": str(project),
                })
                continue

            metrics = extract_metrics(log_text)

            row = {
                "Model": model_name,
                "Split": split,
                "Checkpoint": str(checkpoint),
                "mIoU": metrics["mIoU"],
                "PA": metrics["PA"],
                "mPA": metrics["mPA"],
                "FWIoU": metrics["FWIoU"],
                "Log": str(log_path),
            }
            all_results.append(row)

            for item in metrics["ClassIoU"]:
                all_class_results.append({
                    "Model": model_name,
                    "Split": split,
                    "Class": item["Class"],
                    "IoU": item["IoU"],
                })

            run_status.append({
                "Model": model_name,
                "Split": split,
                "Status": "Completed; metrics parsed",
                "Project": str(project),
            })

            print("mIoU:", metrics["mIoU"])
            print("PA:", metrics["PA"])
            print("mPA:", metrics["mPA"])
            print("FWIoU:", metrics["FWIoU"])
            print("Saved log:", log_path)

        except Exception as exc:
            print("ERROR:", repr(exc))
            run_status.append({
                "Model": model_name,
                "Split": split,
                "Status": f"Error: {exc}",
                "Project": str(project),
            })


# -------------------- SAVE TABLES ---------------------------

results_df = pd.DataFrame(all_results)
class_df = pd.DataFrame(all_class_results)
status_df = pd.DataFrame(run_status)

results_df.to_csv(OUT / "all_metrics_long.csv", index=False)
class_df.to_csv(OUT / "classwise_iou.csv", index=False)
status_df.to_csv(OUT / "run_status.csv", index=False)

print("\n\nEVALUATION SUMMARY")
display(status_df)

if not results_df.empty:
    display(results_df)

    # One row per model, separate columns for every split and metric.
    wide_df = results_df.pivot(
        index="Model",
        columns="Split",
        values=["mIoU", "PA", "mPA", "FWIoU"]
    )
    wide_df.columns = [
        f"{metric}_{split}" for metric, split in wide_df.columns
    ]
    wide_df = wide_df.reset_index()
    wide_df.to_csv(OUT / "all_models_comparison_table.csv", index=False)

    print("\nALL-MODEL COMPARISON TABLE")
    display(wide_df)

print("\nOutputs saved in:", OUT)

========================================================================
MODEL: E0 | PROJECT: /home/cse-sdpl/Downloads/CMX_Original
========================================================================
Checkpoint: /home/cse-sdpl/Downloads/CMX_Original/log_TDD_mit_b2/checkpoint/epoch-100.pth

Evaluating E0 on train...
mIoU: 92.72
PA: 99.535
mPA: 96.772
FWIoU: 99.092
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/train/E0_train.log

Evaluating E0 on val...
mIoU: 62.726
PA: 97.732
mPA: 72.982
FWIoU: 95.784
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/val/E0_val.log

Evaluating E0 on test...
mIoU: 58.923
PA: 98.227
mPA: 70.841
FWIoU: 96.777
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/test/E0_test.log

========================================================================
MODEL: E1 | PROJECT: /home/cse-sdpl/Downloads/CMX_E1
========================================================================
Checkpoint: /home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth

Evaluating E1 on train...
mIoU: 93.043
PA: 99.557
mPA: 96.913
FWIoU: 99.134
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/train/E1_train.log

Evaluating E1 on val...
mIoU: 60.944
PA: 97.684
mPA: 70.88
FWIoU: 95.678
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/val/E1_val.log

Evaluating E1 on test...
mIoU: 56.786
PA: 98.176
mPA: 65.979
FWIoU: 96.664
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/test/E1_test.log

========================================================================
MODEL: E2 | PROJECT: /home/cse-sdpl/Downloads/CMX_E2
========================================================================
Checkpoint: /home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth

Evaluating E2 on train...
mIoU: 92.646
PA: 99.528
mPA: 96.752
FWIoU: 99.08
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/train/E2_train.log

Evaluating E2 on val...
mIoU: 62.325
PA: 97.731
mPA: 72.627
FWIoU: 95.773
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/val/E2_val.log

Evaluating E2 on test...
mIoU: 57.83
PA: 98.224
mPA: 67.892
FWIoU: 96.768
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/test/E2_test.log

========================================================================
MODEL: E3 | PROJECT: /home/cse-sdpl/Downloads/CMX_E3
========================================================================
Checkpoint: /home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2_e1/checkpoint/epoch-100.pth

Evaluating E3 on train...
mIoU: 94.915
PA: 99.67
mPA: 97.607
FWIoU: 99.351
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/train/E3_train.log

Evaluating E3 on val...
mIoU: 61.961
PA: 97.723
mPA: 71.182
FWIoU: 95.739
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/val/E3_val.log

Evaluating E3 on test...
mIoU: 57.894
PA: 98.247
mPA: 67.03
FWIoU: 96.792
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/test/E3_test.log

========================================================================
MODEL: E4 | PROJECT: /home/cse-sdpl/Downloads/CMX_E4
========================================================================
Checkpoint: /home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2_e4/checkpoint/epoch-100.pth

Evaluating E4 on train...
mIoU: 96.011
PA: 99.738
mPA: 98.149
FWIoU: 99.483
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/train/E4_train.log

Evaluating E4 on val...
mIoU: 62.211
PA: 97.758
mPA: 71.387
FWIoU: 95.808
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/val/E4_val.log

Evaluating E4 on test...
mIoU: 58.086
PA: 98.258
mPA: 66.617
FWIoU: 96.816
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/test/E4_test.log

========================================================================
MODEL: E5 | PROJECT: /home/cse-sdpl/Downloads/CMX_E5
========================================================================
Checkpoint: /home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2_e5/checkpoint/epoch-100.pth

Evaluating E5 on train...
mIoU: 96.611
PA: 99.776
mPA: 98.424
FWIoU: 99.557
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/train/E5_train.log

Evaluating E5 on val...
mIoU: 61.947
PA: 97.716
mPA: 70.97
FWIoU: 95.732
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/val/E5_val.log

Evaluating E5 on test...
mIoU: 58.379
PA: 98.25
mPA: 67.82
FWIoU: 96.795
Saved log: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON/test/E5_test.log


EVALUATION SUMMARY

,Model,Split,Status,Project
0,E0,train,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_Original
1,E0,val,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_Original
2,E0,test,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_Original
3,E1,train,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E1
4,E1,val,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E1
5,E1,test,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E1
6,E2,train,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E2
7,E2,val,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E2
8,E2,test,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E2
9,E3,train,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E3
10,E3,val,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E3
11,E3,test,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E3
12,E4,train,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E4
13,E4,val,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E4
14,E4,test,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E4
15,E5,train,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E5
16,E5,val,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E5
17,E5,test,Completed; metrics parsed,/home/cse-sdpl/Downloads/CMX_E5

,Model,Split,Checkpoint,mIoU,PA,mPA,FWIoU,Log
0,E0,train,/home/cse-sdpl/Downloads/CMX_Original/log_TDD_...,92.720,99.535,96.772,99.092,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
1,E0,val,/home/cse-sdpl/Downloads/CMX_Original/log_TDD_...,62.726,97.732,72.982,95.784,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
2,E0,test,/home/cse-sdpl/Downloads/CMX_Original/log_TDD_...,58.923,98.227,70.841,96.777,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
3,E1,train,/home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2...,93.043,99.557,96.913,99.134,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
4,E1,val,/home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2...,60.944,97.684,70.880,95.678,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
5,E1,test,/home/cse-sdpl/Downloads/CMX_E1/log_TDD_mit_b2...,56.786,98.176,65.979,96.664,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
6,E2,train,/home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2...,92.646,99.528,96.752,99.080,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
7,E2,val,/home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2...,62.325,97.731,72.627,95.773,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
8,E2,test,/home/cse-sdpl/Downloads/CMX_E2/log_TDD_mit_b2...,57.830,98.224,67.892,96.768,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
9,E3,train,/home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2...,94.915,99.670,97.607,99.351,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
10,E3,val,/home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2...,61.961,97.723,71.182,95.739,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
11,E3,test,/home/cse-sdpl/Downloads/CMX_E3/log_TDD_mit_b2...,57.894,98.247,67.030,96.792,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
12,E4,train,/home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2...,96.011,99.738,98.149,99.483,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
13,E4,val,/home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2...,62.211,97.758,71.387,95.808,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
14,E4,test,/home/cse-sdpl/Downloads/CMX_E4/log_TDD_mit_b2...,58.086,98.258,66.617,96.816,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
15,E5,train,/home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2...,96.611,99.776,98.424,99.557,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
16,E5,val,/home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2...,61.947,97.716,70.970,95.732,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...
17,E5,test,/home/cse-sdpl/Downloads/CMX_E5/log_TDD_mit_b2...,58.379,98.250,67.820,96.795,/home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARI...

ALL-MODEL COMPARISON TABLE

,Model,mIoU_test,mIoU_train,mIoU_val,PA_test,PA_train,PA_val,mPA_test,mPA_train,mPA_val,FWIoU_test,FWIoU_train,FWIoU_val
0,E0,58.923,92.720,62.726,98.227,99.535,97.732,70.841,96.772,72.982,96.777,99.092,95.784
1,E1,56.786,93.043,60.944,98.176,99.557,97.684,65.979,96.913,70.880,96.664,99.134,95.678
2,E2,57.830,92.646,62.325,98.224,99.528,97.731,67.892,96.752,72.627,96.768,99.080,95.773
3,E3,57.894,94.915,61.961,98.247,99.670,97.723,67.030,97.607,71.182,96.792,99.351,95.739
4,E4,58.086,96.011,62.211,98.258,99.738,97.758,66.617,98.149,71.387,96.816,99.483,95.808
5,E5,58.379,96.611,61.947,98.250,99.776,97.716,67.820,98.424,70.970,96.795,99.557,95.732

Outputs saved in: /home/cse-sdpl/Downloads/CMX_ALL_MODEL_COMPARISON

In [58]:
import pandas as pd
from pathlib import Path

# Output folder
out = Path.home() / "Downloads" / "CMX_ALL_MODEL_COMPARISON"
out.mkdir(parents=True, exist_ok=True)

# Copy the already-created files into Downloads
source_xlsx = Path("/mnt/data/CMX_ALL_MODEL_COMPARISON.xlsx")
source_csv = Path("/mnt/data/CMX_ALL_MODEL_COMPARISON.csv")

if source_xlsx.exists():
    df = pd.read_excel(source_xlsx)
    df.to_excel(out / "CMX_ALL_MODEL_COMPARISON.xlsx", index=False)
    df.to_csv(out / "CMX_ALL_MODEL_COMPARISON.csv", index=False, float_format="%.3f")
    print("Excel:", out / "CMX_ALL_MODEL_COMPARISON.xlsx")
    print("CSV:  ", out / "CMX_ALL_MODEL_COMPARISON.csv")
else:
    print("Source Excel file isn't accessible from your local Jupyter environment.")
    print("Download the Excel file from this chat first.")

Source Excel file isn't accessible from your local Jupyter environment.
Download the Excel file from this chat first.

In [59]:
from pathlib import Path
import shutil

downloads = Path.home() / "Downloads"
source = downloads / "CMX_ALL_MODEL_COMPARISON.xlsx"
destination = downloads / "CMX_ALL_MODEL_COMPARISON" / source.name

destination.parent.mkdir(parents=True, exist_ok=True)

if source.exists():
    shutil.copy2(source, destination)
    print("Saved to:", destination)
else:
    print("First download CMX_ALL_MODEL_COMPARISON.xlsx into your Downloads folder.")

First download CMX_ALL_MODEL_COMPARISON.xlsx into your Downloads folder.

In [62]:
from pathlib import Path
import subprocess
import os

ROOT = Path("/home/cse-sdpl/Downloads/CMX_SCR")
PREDICTIONS = ROOT / "predictions_SCR_test"

assert (ROOT / "eval.py").is_file(), "eval.py not found"
assert (
    ROOT / "log_TDD_mit_b2_scr/checkpoint/epoch-100.pth"
).is_file(), "Final SCR checkpoint not found"

if PREDICTIONS.exists() and any(PREDICTIONS.iterdir()):
    raise RuntimeError(
        f"Prediction directory is not empty: {PREDICTIONS}\n"
        "Choose a fresh output directory to avoid mixing predictions."
    )

os.chdir(ROOT)

command = [
    "conda", "run", "--no-capture-output", "-n", "cmx",
    "python", "eval.py",
    "-e", "100",
    "-d", "0",
    "--split", "test",
    "-p", "predictions_SCR_test",
]

print("Evaluating SCR epoch 100 on the TDD test split...")
print("Command:", " ".join(command))

result = subprocess.run(command, cwd=str(ROOT), check=False)

print("\nEvaluation exit code:", result.returncode)
if result.returncode == 0:
    print("Evaluation process completed. Capture the reported metrics.")
else:
    print("Evaluation failed. Share the error output before retrying.")

RuntimeError: Prediction directory is not empty: /home/cse-sdpl/Downloads/CMX_SCR/predictions_SCR_test
Choose a fresh output directory to avoid mixing predictions.